### ISSUE TITLE
Leak in `bins/asan/h2_http_proxy_test` and `bins/h2_http_proxy_nosec_test`

### ISSUE THREAD

**Issue by y-zeng** [grpc/grpc#10169]
Seen in master: https://grpc-testing.appspot.com/job/gRPC_master_asanitizer_c/1107/

Also in PR:
- [c_linux_asan_native.bins/asan/h2_http_proxy_nosec_test cancel_after_invoke GRPC_POLL_STRATEGY=poll](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2795/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_nosec_test_cancel_after_invoke_GRPC_POLL_STRATEGY_poll/)
- [c_linux_asan_native.bins/asan/h2_http_proxy_nosec_test max_message_length GRPC_POLL_STRATEGY=poll-cv](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2795/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_nosec_test_max_message_length_GRPC_POLL_STRATEGY_poll_cv/)
- [c_linux_asan_native.bins/asan/h2_http_proxy_nosec_test resource_quota_server GRPC_POLL_STRATEGY=poll-cv](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2807/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_nosec_test_resource_quota_server_GRPC_POLL_STRATEGY_poll_cv/)
- [c_linux_asan_native.bins/asan/h2_http_proxy_nosec_test cancel_with_status GRPC_POLL_STRATEGY=poll](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2807/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_nosec_test_cancel_with_status_GRPC_POLL_STRATEGY_poll/)
- [c_linux_asan_native.bins/asan/h2_http_proxy_test cancel_after_invoke GRPC_POLL_STRATEGY=poll](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2802/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_test_cancel_after_invoke_GRPC_POLL_STRATEGY_poll/)
- [c_linux_asan_native.bins/asan/h2_http_proxy_test cancel_with_status GRPC_POLL_STRATEGY=poll](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2802/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_test_cancel_with_status_GRPC_POLL_STRATEGY_poll/)
- [c_linux_asan_native.bins/asan/h2_http_proxy_test max_message_length GRPC_POLL_STRATEGY=poll-cv](https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/2799/testReport/junit/(root)/c_linux_asan_native/bins_asan_h2_http_proxy_test_max_message_length_GRPC_POLL_STRATEGY_poll_cv/)

**Comment by y-zeng** [comment]
bins/asan/h2_http_proxy_nosec_test cancel_after_invoke GRPC_POLL_STRATEGY=epoll
```
D0315 08:39:48.814039324   29533 iomgr.c:127]                Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0315 08:39:48.814096078   29533 iomgr.c:82]                 LEAKED OBJECT: tcp-server-connection:ipv6:[::1]:46688 fd=9 0x60d00000cbd8

=================================================================
[1m[31m==29533==ERROR: LeakSanitizer: detected memory leaks
[1m[0m
[1m[34mIndirect leak of 5904 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x5a92b9 in on_accept /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:379:28
    #3 0x61ca70 in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:458:5
    #4 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #5 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #6 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #7 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #8 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #9 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x62300000a900 (5904 bytes)

[1m[34mIndirect leak of 560 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x60f557 in grpc_tcp_create /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:541:31
    #3 0x61ca4e in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:460:9
    #4 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #5 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #6 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #7 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #8 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #9 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x616000027380 (560 bytes)

[1m[34mIndirect leak of 400 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x5fe071 in grpc_resource_user_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:686:39
    #3 0x60f9fd in grpc_tcp_create /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:562:24
    #4 0x61ca4e in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:460:9
    #5 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #6 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #7 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #8 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #9 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #10 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x61400001e840 (400 bytes)

[1m[34mIndirect leak of 248 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x750174 in polling_island_create /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:577:8
    #3 0x753c11 in add_poll_object /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1877:18
    #4 0x74aa17 in pollset_add_fd /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1977:3
    #5 0x5f4fef in grpc_pollset_add_fd /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:211:3
    #6 0x61a796 in grpc_tcp_server_start /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:910:9
    #7 0x5a9043 in grpc_end2end_http_proxy_create /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:459:3
    #8 0x4f3aea in chttp2_create_fixture_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:69:16
    #9 0x508a43 in begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:57:7
    #10 0x5075f3 in test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:108:7
    #11 0x5071e4 in cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:200:7
    #12 0x4f4aea in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:283:7
    #13 0x4f3903 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:125:5
    #14 0x7f98355c4b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x6110000025c0 (248 bytes)

[1m[34mIndirect leak of 224 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x5e51d3 in grpc_combiner_create /var/local/git/grpc/src/core/lib/iomgr/combiner.c:129:25
    #3 0x5fc88e in grpc_resource_quota_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:575:30
    #4 0x6163b7 in grpc_tcp_server_create /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:168:23
    #5 0x5a8c23 in grpc_end2end_http_proxy_create /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:443:23
    #6 0x4f3aea in chttp2_create_fixture_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:69:16
    #7 0x508a43 in begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:57:7
    #8 0x5075f3 in test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:108:7
    #9 0x5071e4 in cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:200:7
    #10 0x4f4aea in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:283:7
    #11 0x4f3903 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:125:5
    #12 0x7f98355c4b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x611000002700 (224 bytes)

[1m[34mIndirect leak of 184 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x5fc873 in grpc_resource_quota_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:573:41
    #3 0x6163b7 in grpc_tcp_server_create /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:168:23
    #4 0x5a8c23 in grpc_end2end_http_proxy_create /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:443:23
    #5 0x4f3aea in chttp2_create_fixture_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:69:16
    #6 0x508a43 in begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:57:7
    #7 0x5075f3 in test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:108:7
    #8 0x5071e4 in cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:200:7
    #9 0x4f4aea in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:283:7
    #10 0x4f3903 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:125:5
    #11 0x7f98355c4b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x610000003540 (184 bytes)

[1m[34mIndirect leak of 144 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x746f28 in fd_create /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1003:14
    #3 0x5f457b in grpc_fd_create /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:149:10
    #4 0x60c99d in tcp_client_connect_impl /var/local/git/grpc/src/core/lib/iomgr/tcp_client_posix.c:319:11
    #5 0x60d617 in grpc_tcp_client_connect /var/local/git/grpc/src/core/lib/iomgr/tcp_client_posix.c:380:3
    #6 0x6a3e7d in chttp2_connector_connect /var/local/git/grpc/src/core/ext/transport/chttp2/client/chttp2_connector.c:240:3
    #7 0x6b6b52 in grpc_connector_connect /var/local/git/grpc/src/core/ext/client_channel/connector.c:49:3
    #8 0x6c2007 in continue_connect_locked /var/local/git/grpc/src/core/ext/client_channel/subchannel.c:413:3
    #9 0x6bff07 in maybe_start_connecting_locked /var/local/git/grpc/src/core/ext/client_channel/subchannel.c:494:5
    #10 0x6bf31c in grpc_subchannel_notify_on_state_change /var/local/git/grpc/src/core/ext/client_channel/subchannel.c:545:5
    #11 0x81e728 in start_picking /var/local/git/grpc/src/core/ext/lb_policy/pick_first/pick_first.c:177:3
    #12 0x81d416 in pf_pick_locked /var/local/git/grpc/src/core/ext/lb_policy/pick_first/pick_first.c:205:5
    #13 0x6b7538 in grpc_lb_policy_pick_locked /var/local/git/grpc/src/core/ext/client_channel/lb_policy.c:123:10
    #14 0x6adf02 in pick_subchannel_locked /var/local/git/grpc/src/core/ext/client_channel/client_channel.c:919:26
    #15 0x6b0346 in continue_picking_locked /var/local/git/grpc/src/core/ext/client_channel/client_channel.c:850:9
    #16 0x5e67c8 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:320:5
    #17 0x5f619e in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:80:17
    #18 0x5f63f4 in grpc_exec_ctx_finish /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:91:3
    #19 0x64e102 in grpc_call_start_batch /var/local/git/grpc/src/core/lib/surface/call.c:1734:3
    #20 0x50821f in test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:169:11
    #21 0x5071e4 in cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:200:7
    #22 0x4f4aea in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:283:7
    #23 0x4f3903 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:125:5
    #24 0x7f98355c4b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60d00000cb60 (144 bytes)

[1m[34mIndirect leak of 64 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c2428 in realloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:71
    #1 0x6ce9cf in gpr_realloc /var/local/git/grpc/src/core/lib/support/alloc.c:100:7
    #2 0x7523dc in polling_island_add_fds_locked /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:474:17
    #3 0x75077f in polling_island_create /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:609:5
    #4 0x753c11 in add_poll_object /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1877:18
    #5 0x74aa17 in pollset_add_fd /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1977:3
    #6 0x5f4fef in grpc_pollset_add_fd /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:211:3
    #7 0x61a796 in grpc_tcp_server_start /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:910:9
    #8 0x5a9043 in grpc_end2end_http_proxy_create /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:459:3
    #9 0x4f3aea in chttp2_create_fixture_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:69:16
    #10 0x508a43 in begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:57:7
    #11 0x5075f3 in test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:108:7
    #12 0x5071e4 in cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:200:7
    #13 0x4f4aea in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:283:7
    #14 0x4f3903 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:125:5
    #15 0x7f98355c4b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x606000005300 (64 bytes)

[1m[34mIndirect leak of 48 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x74aa56 in pollset_set_create /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1986:27
    #3 0x5f505e in grpc_pollset_set_create /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:215:10
    #4 0x5a932a in on_accept /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:383:23
    #5 0x61ca70 in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:458:5
    #6 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #7 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #8 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #9 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #10 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #11 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x60400000a590 (48 bytes)

[1m[34mIndirect leak of 44 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x6da0d8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:56:9
    #3 0x5f91eb in grpc_iomgr_register_object /var/local/git/grpc/src/core/lib/iomgr/iomgr.c:155:15
    #4 0x7472ef in fd_create /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1031:3
    #5 0x5f457b in grpc_fd_create /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:149:10
    #6 0x61c67c in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:448:22
    #7 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #8 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #9 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #10 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #11 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #12 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x60400000a5d0 (44 bytes)

[1m[34mIndirect leak of 28 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x6de1ff in gpr_asprintf /var/local/git/grpc/src/core/lib/support/string_posix.c:61:16
    #3 0x5fcad6 in grpc_resource_quota_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:584:5
    #4 0x6163b7 in grpc_tcp_server_create /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:168:23
    #5 0x5a8c23 in grpc_end2end_http_proxy_create /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:443:23
    #6 0x4f3aea in chttp2_create_fixture_fullstack /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:69:16
    #7 0x508a43 in begin_test /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:57:7
    #8 0x5075f3 in test_cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:108:7
    #9 0x5071e4 in cancel_after_invoke /var/local/git/grpc/test/core/end2end/tests/cancel_after_invoke.c:200:7
    #10 0x4f4aea in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:283:7
    #11 0x4f3903 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:125:5
    #12 0x7f98355c4b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x603000005c80 (28 bytes)

[1m[34mIndirect leak of 17 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x6da0d8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:56:9
    #3 0x60f597 in grpc_tcp_create /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:543:22
    #4 0x61ca4e in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:460:9
    #5 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #6 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #7 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #8 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #9 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #10 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x603000008050 (17 bytes)

[1m[34mIndirect leak of 17 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c20a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6ce4f7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x6da0d8 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:56:9
    #3 0x5fe75f in grpc_resource_user_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:718:27
    #4 0x60f9fd in grpc_tcp_create /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:562:24
    #5 0x61ca4e in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:460:9
    #6 0x5f6138 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:76:9
    #7 0x749473 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1787:5
    #8 0x5f4e63 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:201:10
    #9 0x5a9def in thread_main /var/local/git/grpc/test/core/end2end/fixtures/http_proxy_fixture.c:424:47
    #10 0x6e1904 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #11 0x7f9835b6c0a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x80a3)

Objects leaked above:
0x603000008020 (17 bytes)

SUMMARY: AddressSanitizer: 7882 byte(s) leaked in 13 allocation(s).
```

**Comment by y-zeng** [comment]
This leak can be reproduced locally with
```
tools/run_tests/run_tests.py -lc -c asan -r "h2_http_proxy_test cancel_after_invoke" -n 300
```
