### ISSUE TITLE
interop_server_java fails to start as part of gRPC_interop_master

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10374]
From https://grpc-testing.appspot.com/job/gRPC_interop_master/11989/console :

```
2017-03-29 23:11:45,672 START: interop_server_java
2017-03-29 23:12:00,684 docker: Error response from daemon: driver failed programming external connectivity on endpoint interop_server_java_12fc5396-deb4-4c23-8e63-51bc91a4439e (38efc23e2fcbedafd53bf21503ec758d5d13dea9d795246c941f602a7d36952c): Bind for 0.0.0.0:8080 failed: port is already allocated.

2017-03-29 23:12:00,685 FAILED: interop_server_java [ret=125, pid=25038]
exception occurred:
Traceback (most recent call last):
  File "tools/run_tests/run_interop_tests.py", line 978, in <module>
    server_addresses[lang] = ('localhost', job.mapped_port(_DEFAULT_SERVER_PORT))
  File "/home/jenkins/workspace/gRPC_interop_master/grpc/tools/run_tests/python_utils/dockerjob.py", line 131, in mapped_port
    return docker_mapped_port(self._container_name, port)
  File "/home/jenkins/workspace/gRPC_interop_master/grpc/tools/run_tests/python_utils/dockerjob.py", line 70, in docker_mapped_port
    (port, cid))
Exception: Failed to get exposed port 8080 for container interop_server_java_12fc5396-deb4-4c23-8e63-51bc91a4439e.
stty: standard input: Inappropriate ioctl for device
Server "java" has exited prematurely.
```

**Comment by ericgribkoff** [comment]
I had a look and this is actually an error in the test's Docker setup, not Java. `run_interop_tests.py` was recently updated to pass the server port arg as `-p PORT:PORT`, which tells Docker to map the container port to a specific host port - this constrains exactly one container to listen on the port, so when any server container runs after another server container has already started, it fails to bind.

I will send out a fix.

**Comment by dgquintas** [comment]
Nice! Thanks @ericgribkoff
