### ISSUE TITLE
Interop fail on tests.cloud_to_cloud:java:http2_server:max_streams

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#10390]
Seen at https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12744/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/

**Comment by matt-kwong** [comment]
Seen again here: https://grpc-testing.appspot.com/job/gRPC_interop_master/12849/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/

```
Error Message

Failure
Stacktrace

ask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:534)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:138)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:347)
	... 7 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:587)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:135)
	... 9 more

May 12, 2017 7:01:35 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by io.grpc.netty.NettyClientStream$Sink$2.operationComplete()
java.lang.IllegalStateException: onStreamAllocated was not called, but it seems the stream is active
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.AbstractStream2$TransportState.onSentBytes(AbstractStream2.java:289)
	at io.grpc.netty.NettyClientStream$Sink$2.operationComplete(NettyClientStream.java:173)
	at io.grpc.netty.NettyClientStream$Sink$2.operationComplete(NettyClientStream.java:167)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:76)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:71)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$Frame.release(StreamBufferingEncoder.java:309)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$DataFrame.release(StreamBufferingEncoder.java:357)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$PendingStream.close(StreamBufferingEncoder.java:292)
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeRstStream(StreamBufferingEncoder.java:184)
	at io.grpc.netty.NettyClientHandler.cancelStream(NettyClientHandler.java:470)
	at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:127)
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:47)
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

May 12, 2017 7:01:35 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Got more than one input Future failure. Logging failures after the first
java.lang.RuntimeException: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:349)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:534)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:138)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:347)
	... 7 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:587)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:135)
	... 9 more

May 12, 2017 7:01:35 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Got more than one input Future failure. Logging failures after the first
java.lang.RuntimeException: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:349)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:534)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:138)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:347)
	... 7 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:587)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:135)
	... 9 more
```

**Comment by apolcyn** [comment]
seen again:

```
2017-07-12 01:01:31,020 WAITING: ETA 3.0 sec; 0 queued, 6 jobs running, 1344 complete, 1 failed
2017-07-12 01:01:36,234 Jul 12, 2017 1:00:17 AM io.grpc.testing.integration.Http2Client run
INFO: Running test max_streams
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:171)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:75)
Caused by: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:411)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:84)
	at io.grpc.testing.integration.Http2Client$Tester.maxStreams(Http2Client.java:280)
	at io.grpc.testing.integration.Http2Client$Tester.access$800(Http2Client.java:201)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:194)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:167)
	... 1 more
```

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15301/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/

**Comment by dgquintas** [comment]
Again: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15858/

**Comment by dgquintas** [comment]
This has been happening relatively often for a while now. Any plans/ideas? @ericgribkoff @ejona86

**Comment by ericgribkoff** [comment]
@dgquintas No ideas yet. I will prioritize looking into this and updating this thread.

**Comment by ericgribkoff** [comment]
I'm unable to reproduce these failures after running continuously for several hours locally.

I looked into the warning messages for "onStreamAllocated was not called, but it seems the stream is active" (https://github.com/grpc/grpc-java/issues/3007) and believe I have a fix for those, but I'm fairly certain the warnings are irrelevant to the actual test failures: this and the other java:http2 flakes all indicate that the Java client is timing out waiting for a response from the server. When this first appeared, I had thought this might be a test infrastructure problem, but the infrastructure seems far more reliable now and the same tests work reliably for the other languages.

Interestingly, it's not that Java can't connect to the server but that it doesn't seem to receive the same responses the other language clients are successfully getting. It's consistently just these three tests that fail (max streams, rst after data, and rst during data): the very similar rst after header seems to reliably pass. Tomorrow I'll have a more detailed look at the Python server and see if I can make any educated guesses about what might be going wrong by looking at the differences between the three rst stream tests.

**Comment by ericgribkoff** [comment]
> It's consistently just these three tests that fail (max streams, rst after data, and rst during data): the very similar rst after header seems to reliably pass. 

These are also the only tests with a timeout in the Java client, and it's only set to 5 seconds. It looks like these test cases sometimes take up to 2 minutes to pass for the other languages. Just submitted https://github.com/grpc/grpc-java/pull/3333 which bumps the timeout up to 180 seconds, and will monitor this to see if the change reduces the flakiness.

**Comment by ericgribkoff** [comment]
The tests have consistently passed since grpc/grpc-java#3333. Marking this resolved.

**Comment by dgquintas** [comment]
Thanks @ericgribkoff !
