### ISSUE TITLE
build_docker_ruby fails for interop pull requests

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10434]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12845/console

```
Bundler cannot continue installing faraday (0.12.0).
The checksum for the downloaded `faraday-0.12.0.gem` does not match the checksum
given by the server. This means the contents of the downloaded gem is different
from what was uploaded to the server, and could be a potential security issue.

To resolve this issue:
1. delete the downloaded gem located at:
`/usr/local/rvm/gems/ruby-2.1.10/gems/faraday-0.12.0/faraday-0.12.0.gem`
2. run `bundle install`

If you wish to continue installing the downloaded gem, and are certain it does
not pose a security issue despite the mismatching checksum, do the following:
1. run `bundle config disable_checksum_validation true` to turn off checksum
verification
2. run `bundle install`

(More info: The expected SHA256 checksum was
"467b18cc2683845e90996e2c7f3af0cf34493d78b687445b2b4999711f6f6dca", but the
checksum for the downloaded gem was
"974ec50064433c84a0015b9f985d676e82b5532fd82ca0e2e546fbd63034a1b8".)
+ EXITCODE=19
+ docker rm -f build_grpc_interop_ruby_f4ace20d-bc45-422d-8b7e-a54b2fceed4f
build_grpc_interop_ruby_f4ace20d-bc45-422d-8b7e-a54b2fceed4f
+ exit 19

2017-04-02 05:41:45,542 FAILED: build_docker_ruby [ret=19, pid=15943]
```

**Comment by apolcyn** [comment]
I think this is due to a recent `faraday` update, which can be pinned.

But after this issue, at least on the head of master, I'm actually seeing all ruby builds with `rake compile` fail with:

```
mkdir -p tmp/x86_64-linux/grpc_c/2.1.10
cd tmp/x86_64-linux/grpc_c/2.1.10
/usr/local/rvm/rubies/ruby-2.1.10/bin/ruby -I. ../../../../src/ruby/ext/grpc/extconf.rb
Building internal gRPC into /var/local/git/grpc/tmp/x86_64-linux/grpc_c/2.1.10/libs/opt
make: Entering directory '/var/local/git/grpc'
make: Circular /var/local/git/grpc/tmp/x86_64-linux/grpc_c/2.1.10/libs/opt/libares.a <- /var/local/git/grpc/tmp/x86_64-linux/grpc_c/2.1.10/libs/opt/libz.a dependency dropped.
make: *** No rule to make target '/var/local/git/grpc/tmp/x86_64-linux/grpc_c/2.1.10/objs/opt/third_party/cares/cares/ares__close_sockets.o', needed by '/var/local/git/grpc/tmp/x86_64-linux/grpc_c/2.1.10/libs/opt/libares.a'.  Stop.
make: Leaving directory '/var/local/git/grpc'
*** ../../../../src/ruby/ext/grpc/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=../../../../src/ruby/ext/grpc
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.1.10/bin/ruby
rake aborted!
Command failed with status (1): [/usr/local/rvm/rubies/ruby-2.1.10/bin/ruby...]
/usr/local/rvm/gems/ruby-2.1.10/gems/rake-compiler-1.0.3/lib/rake/extensiontask.rb:205:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.1.10/gems/rake-compiler-1.0.3/lib/rake/extensiontask.rb:202:in `block in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => compile => compile:x86_64-linux => compile:grpc_c:x86_64-linux => copy:grpc_c:x86_64-linux:2.1.10 => tmp/x86_64-linux/grpc_c/2.1.10/grpc_c.so => tmp/x86_64-linux/grpc_c/2.1.10/Makefile
(See full trace by running task with --trace)
+ EXITCODE=1
+ docker rm -f build_grpc_interop_ruby_3c92c2a0-4ffd-4fc6-869c-828256828905
build_grpc_interop_ruby_3c92c2a0-4ffd-4fc6-869c-828256828905
+ exit 1
FAILED: build_docker_ruby [ret=1, pid=96824]
FAILED: Failed to build interop docker images.

```

**Comment by apolcyn** [comment]
I'm actually not sure how any ruby tests are passing on master right now.

cc @zyc `tools/run_tests/run_tests.py -l ruby --use_docker` on everything starting from https://github.com/grpc/grpc/commit/f466ae116e7b9804458129e95d790e7f20042ffc shows this error.

**Comment by apolcyn** [comment]
ftr the above ruby error seems likely related to https://github.com/grpc/grpc/issues/10403, 

from current head of master, there are multiple build failures (in languages including c# and ruby) during `run_tests.py`, that seem related to cares

**Comment by apolcyn** [comment]
the original issue here I think is the same as in https://github.com/grpc/grpc/issues/10435 (issues installing `faraday 0.12.0.0`, which appears fixed with `0.12.0.1` release. latest interop PR jobs look  passing

**Comment by y-zeng** [comment]
@apolcyn I could not reproduce the c-ares error locally with `tools/run_tests/run_tests.py -l ruby --use_docker`. Looks like #10361 may have fixed it. Could you please try again on master?

**Comment by apolcyn** [comment]
@y-zeng I think this is just an issue for me locally, I can get the error in some environments but not others, thanks for checking
