### ISSUE TITLE
Jenkins disk check fails sometimes

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10512]
Not sure if this is a one-off (first time I see this), but happended on 2 jobs at a time.

https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_c/3530/console
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/4361/console

```
Disk space threshold is set to :50Gb
Checking disk space Now 
FATAL: null
java.lang.NullPointerException
	at org.jenkinsci.plugin.Diskcheck.preCheckout(Diskcheck.java:118)
	at jenkins.scm.SCMCheckoutStrategy.preCheckout(SCMCheckoutStrategy.java:76)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

**Comment by adelez** [comment]
Happened again https://grpc-testing.appspot.com/job/gRPC_master_tsan_cpp/1334/console

Do we still need this disk checker?

**Comment by murgatroid99** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_master_msan_c/1559/console
