### ISSUE TITLE
ASAN bm_cq_multiple_threads flake (leaks found)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10535]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_cpp/3660/

```
Run on (16 X 2600 MHz CPU s)
2017-04-07 12:28:45
***WARNING*** Library was built as DEBUG. Timings may be affected.
Benchmark                                      Time           CPU Iterations
----------------------------------------------------------------------------
D0407 12:28:45.488470350   18651 ev_posix.c:107]             Using polling engine: poll
D0407 12:28:45.488546525   18651 dns_resolver.c:316]         Using native dns resolver
BM_Cq_Throughput/real_time/threads:1       26941 ns      25528 ns          1   36.2478k items/s
BM_Cq_Throughput/real_time/threads:2       28193 ns      44065 ns          2   34.6385k items/s
BM_Cq_Throughput/real_time/threads:4       11995 ns      40012 ns          4   81.4112k items/s
BM_Cq_Throughput/real_time/threads:8        1993 ns      13591 ns          8   489.989k items/s
BM_Cq_Throughput/real_time/threads:16       6408 ns      51549 ns         16   152.387k items/s

=================================================================
[1m[31m==18651==ERROR: LeakSanitizer: detected memory leaks
[1m[0m
[1m[34mDirect leak of 304 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4caae0 in calloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x609ae6 in zalloc_with_calloc /var/local/git/grpc/src/core/lib/support/alloc.c:42:53
    #2 0x609537 in gpr_zalloc /var/local/git/grpc/src/core/lib/support/alloc.c:83:7
    #3 0x599749 in grpc_completion_queue_create /var/local/git/grpc/src/core/lib/surface/completion_queue.c:121:8
    #4 0x4fef93 in grpc::testing::setup() /var/local/git/grpc/test/cpp/microbenchmarks/bm_cq_multiple_threads.cc:109:10
    #5 0x4fe93f in grpc::testing::BM_Cq_Throughput(benchmark::State&) /var/local/git/grpc/test/cpp/microbenchmarks/bm_cq_multiple_threads.cc:117:5
    #6 0x5380b8 in benchmark::internal::FunctionBenchmark::Run(benchmark::State&) /var/local/git/grpc/third_party/benchmark/src/benchmark_register.cc:408:42
    #7 0x50b311 in benchmark::internal::(anonymous namespace)::RunInThread(benchmark::internal::Benchmark::Instance const*, unsigned long, int, benchmark::internal::ThreadManager*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:263:3
    #8 0x50890b in benchmark::internal::(anonymous namespace)::RunBenchmark(benchmark::internal::Benchmark::Instance const&, std::vector<benchmark::BenchmarkReporter::Run, std::allocator<benchmark::BenchmarkReporter::Run> >*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:304:7
    #9 0x505baa in benchmark::internal::(anonymous namespace)::RunMatchingBenchmarks(std::vector<benchmark::internal::Benchmark::Instance, std::allocator<benchmark::internal::Benchmark::Instance> > const&, benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:494:11
    #10 0x504691 in benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:587:5
    #11 0x503625 in benchmark::RunSpecifiedBenchmarks() /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:526:10
    #12 0x4feef1 in main /var/local/git/grpc/test/cpp/microbenchmarks/bm_cq_multiple_threads.cc:142:73
    #13 0x7fc88efd3b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x61200000a9c0 (304 bytes)

[1m[34mIndirect leak of 32 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4cacd8 in realloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:71
    #1 0x60985f in gpr_realloc /var/local/git/grpc/src/core/lib/support/alloc.c:100:7
    #2 0x59a274 in grpc_cq_begin_op /var/local/git/grpc/src/core/lib/surface/completion_queue.c:193:9
    #3 0x4fea64 in grpc::testing::BM_Cq_Throughput(benchmark::State&) /var/local/git/grpc/test/cpp/microbenchmarks/bm_cq_multiple_threads.cc:123:5
    #4 0x5380b8 in benchmark::internal::FunctionBenchmark::Run(benchmark::State&) /var/local/git/grpc/third_party/benchmark/src/benchmark_register.cc:408:42
    #5 0x50b311 in benchmark::internal::(anonymous namespace)::RunInThread(benchmark::internal::Benchmark::Instance const*, unsigned long, int, benchmark::internal::ThreadManager*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:263:3
    #6 0x50890b in benchmark::internal::(anonymous namespace)::RunBenchmark(benchmark::internal::Benchmark::Instance const&, std::vector<benchmark::BenchmarkReporter::Run, std::allocator<benchmark::BenchmarkReporter::Run> >*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:304:7
    #7 0x505baa in benchmark::internal::(anonymous namespace)::RunMatchingBenchmarks(std::vector<benchmark::internal::Benchmark::Instance, std::allocator<benchmark::internal::Benchmark::Instance> > const&, benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:494:11
    #8 0x504691 in benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:587:5
    #9 0x503625 in benchmark::RunSpecifiedBenchmarks() /var/local/git/grpc/third_party/benchmark/src/benchmark.cc:526:10
    #10 0x4feef1 in main /var/local/git/grpc/test/cpp/microbenchmarks/bm_cq_multiple_threads.cc:142:73
    #11 0x7fc88efd3b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60300000dd80 (32 bytes)

SUMMARY: AddressSanitizer: 336 byte(s) leaked in 2 allocation(s).
```

**Comment by sreecha** [comment]
This is a dup of issue #10530  and the fix is in PR #10531
