### ISSUE TITLE
Ruby MacOS fails to compile tests

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10555]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/4396/testReport/junit/(root)/aggregate_tests/run_tests_ruby_macos_dbg_native/

```
+ rake compile
/usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:77:in `block in rubygems_spec': undefined method `executables' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:77:in `each'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:77:in `detect'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:77:in `rubygems_spec'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:48:in `candidate?'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:92:in `setup'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:124:in `check'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /usr/local/rvm/gems/ruby-2.4.0@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:10:in `<main>'

2017-04-10 10:13:28,855 FAILED: tools/run_tests/helper_scripts/build_ruby.sh [ret=1, pid=69884]
2017-04-10 10:13:28,855 FAILED: Some tests failed
```

**Comment by apolcyn** [comment]
FTR this is error is being thrown from the `rake compiler` dependency during the ruby build. 

This original failure was seen on `macos-node4`, but it doesn't easily reproduce and recent runs have passed on that same worker, so I'm not sure if this is still an issue.
