### ISSUE TITLE
Interop Java failing many tests

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10552]
https://grpc-testing.appspot.com/job/gRPC_interop_master/12264/console

Example error:

```
Exception in thread "main" java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at io.grpc.testing.integration.AbstractInteropTest.tearDown(AbstractInteropTest.java:257)
	at io.grpc.testing.integration.TestServiceClient.tearDown(TestServiceClient.java:186)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:83)
Exception in thread "Thread-1" java.lang.AssertionError: expected:<0> but was:<1>
Shutting down
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at io.grpc.testing.integration.AbstractInteropTest.tearDown(AbstractInteropTest.java:257)
	at io.grpc.testing.integration.TestServiceClient.tearDown(TestServiceClient.java:186)
	at io.grpc.testing.integration.TestServiceClient.access$000(TestServiceClient.java:56)
	at io.grpc.testing.integration.TestServiceClient$1.run(TestServiceClient.java:73)
```

**Comment by ejona86** [comment]
Looks like the failure link is wrong. This one should be better:
https://grpc-testing.appspot.com/job/gRPC_interop_master/12264/console

@zhangkun83, this seems likely caused by https://github.com/grpc/grpc-java/commit/903197b2aac6d4fc3b01d7c545608bfb9ab97266

**Comment by dgquintas** [comment]
Thank you @ejona86 . Multitasking, how does it work? (it doesn't). Fixed.
