### ISSUE TITLE
Node fails to connect to Go GRPC: http1.x

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#10673]
My node process is unable to connect to a GRPC Golang server on OS X. I believe the source code is fine because it worked last week, but this is a new node installation so I was wondering what component may be broken / related? This does work fine in a Docker container, too.

This may be a wider issue though... maybe a dep of Node? Maybe OpenSSL (since HTTP/2 requires TLS?)? I see a similar issue here- https://github.com/grpc/grpc/issues/7726. I've tried the stupid stuff like `npm rebuild` and `rm -r node_modules && npm i`

```
{
  "message": "{\"created\":\"@1492321122.263552000\",\"description\":\"Failed parsing HTTP/2\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1869,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1492321122.263541000\",\"description\":\"Expected SETTINGS frame as the first frame, got frame type 80\",\"file\":\"../src/core/ext/transport/chttp2/transport/parsing.c\",\"file_line\":280},{\"created\":\"@1492321122.263547000\",\"description\":\"Trying to connect an http1.x server\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1830,\"http_status\":400}]}",
  "name": "Error",
  "stack": "Error: {\"created\":\"@1492321122.263552000\",\"description\":\"Failed parsing HTTP/2\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1869,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1492321122.263541000\",\"description\":\"Expected SETTINGS frame as the first frame, got frame type 80\",\"file\":\"../src/core/ext/transport/chttp2/transport/parsing.c\",\"file_line\":280},{\"created\":\"@1492321122.263547000\",\"description\":\"Trying to connect an http1.x server\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1830,\"http_status\":400}]}\n    at /Users/tejas/dev/src/github.com/segment-sources/stripe/node_modules/grpc/src/node/src/client.js:434:17",
  "code": 14
}
```

Node client code
```
const proto = grpc.load(`${__dirname}/../domain/library.proto`)
const credentials = grpc.credentials.createInsecure()
const libraryServiceURL = process.env['LIBRARY_SERVICE_URL'] || 'localhost:4000'
const libraryService = new proto.domain.LibraryService(libraryServiceURL, credentials)

Promise.promisifyAll(libraryService, { suffix: 'AsPromised' })

async function index(ctx) {
  const resp = await libraryService.getCatalogAsPromised({})
  ctx.render('index', { libraries: resp.libraries })
}
```

Go server code
```
	server := grpc.NewServer()
	service := Service{Catalog: fakeCatalog}
	domain.RegisterLibraryServiceServer(server, &service)

	sock, err := net.Listen("tcp", ":4000")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	server.Serve(sock)
```

**Comment by tejasmanohar** [comment]
I have a hunch this has to do with mismatched GRPC versions on client and server. I know I'm using node's grpc module at 1.1.2, but any idea how to find out what protocol version that is and how it compared to grpc-go? grpc-go's releases don't line up with grpc node :(

**Comment by tejasmanohar** [comment]
It's weird though. Apps that used to work stopped working with the same node_modules (no changes there)... maybe, something to do with node installation itself?  I got some more details on the error from the stack in another node GRPC program.

```
{
  "message": "{\"created\":\"@1492321122.263552000\",\"description\":\"Failed parsing HTTP/2\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1869,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1492321122.263541000\",\"description\":\"Expected SETTINGS frame as the first frame, got frame type 80\",\"file\":\"../src/core/ext/transport/chttp2/transport/parsing.c\",\"file_line\":280},{\"created\":\"@1492321122.263547000\",\"description\":\"Trying to connect an http1.x server\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1830,\"http_status\":400}]}",
  "name": "Error",
  "stack": "Error: {\"created\":\"@1492321122.263552000\",\"description\":\"Failed parsing HTTP/2\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1869,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1492321122.263541000\",\"description\":\"Expected SETTINGS frame as the first frame, got frame type 80\",\"file\":\"../src/core/ext/transport/chttp2/transport/parsing.c\",\"file_line\":280},{\"created\":\"@1492321122.263547000\",\"description\":\"Trying to connect an http1.x server\",\"file\":\"../src/core/ext/transport/chttp2/transport/chttp2_transport.c\",\"file_line\":1830,\"http_status\":400}]}\n    at /Users/tejas/dev/src/github.com/segment-sources/stripe/node_modules/grpc/src/node/src/client.js:434:17",
  "code": 14
}
```

**Comment by tejasmanohar** [comment]
Oh man, this actually seems to have nothing to do with the version of `node_modules`. I spun up a Docker container (linux) and re-npm-install'd inside of it (already tried that on my host-- OS X) and am unable to reproduce... so it must be related to my Node.js setup locally.

This may be a wider issue though... maybe a dep of Node? Maybe OpenSSL (since HTTP/2 requires TLS?)? I see a similar issue here- https://github.com/grpc/grpc/issues/7726

**Comment by murgatroid99** [comment]
The Node code looks right, though I'm not entirely familiar with the ES6 idioms. The error says (if you scroll far enough) "Trying to connect an http1.x server". Is it possible that the environment variable `LIBRARY_SERVICE_URL` is set, and you're not actually connecting to the local server? Are you sure that the Go server is successfully listening on that port, and that some other HTTP 1 server isn't already listening there?

**Comment by tejasmanohar** [comment]
@murgatroid99 Nah, env var isn't set. Happens for all GRPC Node apps in my host environment. It's quite a peculiar issue... source code works fine in Docker container. Happy to dive deeper... just a bit stuck, let me know if you have any debugging tips

**Comment by murgatroid99** [comment]
If it's happening to every gRPC Node app in your host environment, the simplest explanation is that they are actually connecting through a proxy, as was mentioned in the issue you linked. In general, to get a lot of debugging information, you can run the Node client with the environment variables `GRPC_TRACE=all GRPC_VERBOSITY=DEBUG`. A dump of that log from a run of the client could help find the source of the problem. If you decide to share it, check that it doesn't have anything private.

**Comment by ntindall** [comment]
I am experiencing a similar issue. Running a `node` client against a `go` grpc server on `Mac OS X`

```D0613 21:16:33.310429000 140736045106112 combiner.c:217]               C:0x1023076d0 grpc_combiner_execute c=0x103800120 cov=0 last=1
D0613 21:16:33.310435000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.310439000 140736045106112 combiner.c:308]               C:0x1023076d0 maybe_finish_one n=0x103800120
D0613 21:16:33.310448000 140736045106112 parsing.c:420]                FLOW    parse: client DEBIT                                   STREAM[1]:incoming_window_delta  -150515 by                                              incoming_frame_size       99 giving -150614
D0613 21:16:33.310455000 140736045106112 parsing.c:436]                FLOW    parse: client DEBIT                                         TRANSPORT:incoming_window 2146730919 by                                              incoming_frame_size       99 giving 2146730820
D0613 21:16:33.310466000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=3
D0613 21:16:33.310484000 140736045106112 tcp_uv.c:223]                 write complete on 0x102306d90: error="No Error"
D0613 21:16:33.310488000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 32; free_pool -> 32
D0613 21:16:33.310492000 140736045106112 combiner.c:217]               C:0x1023076d0 grpc_combiner_execute c=0x1038000f8 cov=0 last=1
D0613 21:16:33.310856000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.310863000 140736045106112 combiner.c:308]               C:0x1023076d0 maybe_finish_one n=0x1038000f8
D0613 21:16:33.310868000 140736045106112 chttp2_transport.c:797]       W:0x103800000 CLIENT state WRITING+MORE -> WRITING [continue writing [!covered]]
D0613 21:16:33.310873000 140736045106112 combiner.c:406]               C:0x1023076d0 grpc_combiner_execute_finally c=0x1038000a8; ac=0x1023076d0; cov=0
D0613 21:16:33.310877000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=5
D0613 21:16:33.310881000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=1
D0613 21:16:33.310885000 140736045106112 combiner.c:340]               C:0x1023076d0 execute_final[0] c=0x1038000a8
D0613 21:16:33.310921000 140736045106112 writing.c:216]                W:0x103800000 CLIENT[1] im-(sent,send)=(1,0) announce=0
D0613 21:16:33.310932000 140736045106112 chttp2_transport.c:797]       W:0x103800000 CLIENT state WRITING -> WRITING [begin writing]
D0613 21:16:33.310937000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=3
D0613 21:16:33.310943000 140736045106112 tcp_uv.c:248]                 WRITE 0x102306d90 (peer=ipv6:[::1]:8024): 00 00 06 04 00 00 00 00 00 00 04 00 02 44 1c '.............D.'
D0613 21:16:33.310948000 140736045106112 resource_quota.c:790]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: alloc 16; free_pool -> 16
D0613 21:16:33.310966000 140736045106112 tcp_uv.c:223]                 write complete on 0x102306d90: error="No Error"
D0613 21:16:33.310974000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 16; free_pool -> 32
D0613 21:16:33.311059000 140736045106112 combiner.c:217]               C:0x1023076d0 grpc_combiner_execute c=0x1038000f8 cov=0 last=1
D0613 21:16:33.311067000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.311071000 140736045106112 combiner.c:308]               C:0x1023076d0 maybe_finish_one n=0x1038000f8
D0613 21:16:33.311075000 140736045106112 chttp2_transport.c:797]       W:0x103800000 CLIENT state WRITING -> IDLE [finish writing]
D0613 21:16:33.311079000 140736045106112 chttp2_transport.c:2397]      set connectivity_state=4
D0613 21:16:33.311126000 140736045106112 connectivity_state.c:185]     SET: 0x103800248 client_transport: READY --> SHUTDOWN [close_transport] error=0x1020a2120 {"created":"@1497413793.310465000","description":"Delayed close due to in-progress write","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":591,"referenced_errors":[{"created":"@1497413793.310464000","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":2166,"grpc_status":14,"referenced_errors":[{"created":"@1497413793.310461000","description":"frame of size 102 overflows incoming window of 1","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":413}]}]}
D0613 21:16:33.311132000 140736045106112 connectivity_state.c:212]     NOTIFY: 0x103800248 client_transport: 0x10201c360
D0613 21:16:33.311152000 140736045106112 combiner.c:217]               C:0x10170b060 grpc_combiner_execute c=0x10201c360 cov=0 last=1
D0613 21:16:33.311164000 140736045106112 connectivity_state.c:212]     NOTIFY: 0x103800248 client_transport: 0x102307930
D0613 21:16:33.311226000 140736045106112 combiner.c:217]               C:0x102305880 grpc_combiner_execute c=0x10206e8e0 cov=0 last=1
D0613 21:16:33.311232000 140736045106112 chttp2_transport.c:797]       W:0x103800000 CLIENT state IDLE -> WRITING [rst_stream]
D0613 21:16:33.311237000 140736045106112 combiner.c:406]               C:0x1023076d0 grpc_combiner_execute_finally c=0x1038000a8; ac=0x1023076d0; cov=0
D0613 21:16:33.311271000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 8224
D0613 21:16:33.311289000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 16416
D0613 21:16:33.311305000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 24608
D0613 21:16:33.311321000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 32800
D0613 21:16:33.311336000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 40992
D0613 21:16:33.311351000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 49184
D0613 21:16:33.311367000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 57376
D0613 21:16:33.311385000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 65568
D0613 21:16:33.311402000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 73760
D0613 21:16:33.311418000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 81952
D0613 21:16:33.311434000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 90144
D0613 21:16:33.311449000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 98336
D0613 21:16:33.311465000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 106528
D0613 21:16:33.311480000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 114720
D0613 21:16:33.311496000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 122912
D0613 21:16:33.311512000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 131104
D0613 21:16:33.311527000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 139296
D0613 21:16:33.311543000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 147488
D0613 21:16:33.311559000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 155680
D0613 21:16:33.311575000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 163872
D0613 21:16:33.311579000 140736045106112 resource_quota.c:814]         RQ anonymous_pool_1023057c0 ipv6:[::1]:8024: free 8192; free_pool -> 172064
D0613 21:16:33.311585000 140736045106112 chttp2_transport.c:1086]      complete_closure_step: 0x104006b48 refs=0 flags=0x0001 desc=recv_trailing_metadata_finished err="No Error"
D0613 21:16:33.311593000 140736045106112 call.c:690]                   get_final_status CLI
D0613 21:16:33.311604000 140736045106112 call.c:693]                     1: {"created":"@1497413793.311592000","description":"Error received from peer","file":"../src/core/lib/surface/call.c","file_line":939,"grpc_message":"Failed parsing HTTP/2","grpc_status":14}
I0613 21:16:33.311633000 140736045106112 completion_queue.c:224]       grpc_cq_end_op(exec_ctx=0x7fff5fbfedc0, cc=0x102300810, tag=0x102400380, error="No Error", done=0x10286b045, done_arg=0x1018723c8, storage=0x1018723d0)
D0613 21:16:33.311645000 140736045106112 combiner.c:217]               C:0x1023076d0 grpc_combiner_execute c=0x103803348 cov=0 last=5
D0613 21:16:33.311649000 140736045106112 combiner.c:217]               C:0x1023076d0 grpc_combiner_execute c=0x103803370 cov=0 last=7
D0613 21:16:33.311653000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=9
D0613 21:16:33.311659000 140736045106112 connectivity_state.c:185]     SET: 0x10201d4b8 subchannel: READY --> SHUTDOWN [reflect_child] error=0x1020a2120 {"created":"@1497413793.310465000","description":"Delayed close due to in-progress write","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":591,"referenced_errors":[{"created":"@1497413793.310464000","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":2166,"grpc_status":14,"referenced_errors":[{"created":"@1497413793.310461000","description":"frame of size 102 overflows incoming window of 1","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":413}]}]}
D0613 21:16:33.311674000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.311677000 140736045106112 combiner.c:308]               C:0x1023076d0 maybe_finish_one n=0x103803348
D0613 21:16:33.311681000 140736045106112 chttp2_transport.c:2253]      ipv6:[::1]:8024: Start BDP ping
D0613 21:16:33.311685000 140736045106112 bdp_estimator.c:81]           bdp[ipv6:[::1]:8024]:start acc=833093 est=65536
D0613 21:16:33.311688000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=7
D0613 21:16:33.311693000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.311696000 140736045106112 combiner.c:308]               C:0x1023076d0 maybe_finish_one n=0x103803370
D0613 21:16:33.311699000 140736045106112 chttp2_transport.c:2266]      ipv6:[::1]:8024: Complete BDP ping
D0613 21:16:33.311806000 140736045106112 bdp_estimator.c:91]           bdp[ipv6:[::1]:8024]:complete acc=0 est=65536
D0613 21:16:33.311815000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=5
D0613 21:16:33.311820000 140736045106112 combiner.c:282]               C:0x1023076d0 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=1
D0613 21:16:33.311825000 140736045106112 combiner.c:340]               C:0x1023076d0 execute_final[0] c=0x1038000a8
D0613 21:16:33.311829000 140736045106112 chttp2_transport.c:797]       W:0x103800000 CLIENT state WRITING -> IDLE [begin writing nothing]
D0613 21:16:33.311833000 140736045106112 combiner.c:359]               C:0x1023076d0 finish old_state=3
D0613 21:16:33.311838000 140736045106112 combiner.c:282]               C:0x10170b060 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.311841000 140736045106112 combiner.c:308]               C:0x10170b060 maybe_finish_one n=0x10201c360
D0613 21:16:33.311846000 140736045106112 connectivity_state.c:185]     SET: 0x10201c3b0 (null): READY --> SHUTDOWN [selected_changed] error=0x1020a2120 {"created":"@1497413793.310465000","description":"Delayed close due to in-progress write","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":591,"referenced_errors":[{"created":"@1497413793.310464000","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":2166,"grpc_status":14,"referenced_errors":[{"created":"@1497413793.310461000","description":"frame of size 102 overflows incoming window of 1","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":413}]}]}
D0613 21:16:33.311952000 140736045106112 connectivity_state.c:212]     NOTIFY: 0x10201c3b0 (null): 0x102400248
D0613 21:16:33.311960000 140736045106112 combiner.c:217]               C:0x10170b060 grpc_combiner_execute c=0x102400248 cov=0 last=3
D0613 21:16:33.311964000 140736045106112 combiner.c:359]               C:0x10170b060 finish old_state=5
D0613 21:16:33.311969000 140736045106112 combiner.c:282]               C:0x10170b060 grpc_combiner_continue_exec_ctx workqueue=0x0 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0613 21:16:33.311972000 140736045106112 combiner.c:308]               C:0x10170b060 maybe_finish_one n=0x102400248
D0613 21:16:33.311983000 140736045106112 combiner.c:217]               C:0x10170b060 grpc_combiner_execute c=0x1020a2370 cov=0 last=3
D0613 21:16:33.311988000 140736045106112 connectivity_state.c:185]     SET: 0x10170af80 client_channel: READY --> TRANSIENT_FAILURE [lb_changed] error=0x1020a2120 {"created":"@1497413793.310465000","description":"Delayed close due to in-progress write","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":591,"referenced_errors":[{"created":"@1497413793.310464000","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":2166,"grpc_status":14,"referenced_errors":[{"created":"@1497413793.310461000","description":"frame of size 102 overflows incoming window of 1","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":413}]}]}
```

**Comment by ntindall** [comment]
It seems like this error may be related to https://github.com/grpc/grpc-go/issues/1192

@mehrdada does this look familar to you? The error reproduces on `Ubuntu 14` as well (node client / golang server). 

```D0613 21:16:33.311846000 140736045106112 connectivity_state.c:185]     SET: 0x10201c3b0 (null): READY --> SHUTDOWN [selected_changed] error=0x1020a2120 {"created":"@1497413793.310465000","description":"Delayed close due to in-progress write","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":591,"referenced_errors":[{"created":"@1497413793.310464000","description":"Failed parsing HTTP/2","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":2166,"grpc_status":14,"referenced_errors":[{"created":"@1497413793.310461000","description":"frame of size 102 overflows incoming window of 1","file":"../src/core/ext/transport/chttp2/transport/parsing.c","file_line":413}]}]}```

**Comment by mehrdada** [comment]
There was an integer overflow bug in flow control logic that should be already fixed in HEAD in the Go implementation. Can you please try this with the Go HEAD and see if the issue exists? Otherwise it is very likely that you are encountering the same issue.

**Comment by ntindall** [comment]
Thank you @mehrdada for your rapid response. It would appear that the issue does not persist after upgrading to `Go` HEAD. I suppose this is a little obvious in hind sight.

Thank you for your help!

**Comment by mehrdada** [comment]
I'm going to close this issue as it is a duplicate of grpc/grpc-go#1192. If you are facing this, please make sure you upgrade your Go side to HEAD and please do let us know if similar issues persist despite Go endpoints being updated. Thanks!
