### ISSUE TITLE
python_linux_opt_native.py34.test.protoc_plugin._python_plugin_test.PythonPluginTest flakes with StatusCode.DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#10807]
https://grpc-testing.appspot.com/job/gRPC_master_linux/2175/testReport/junit/(root)/python_linux_opt_native/py34_test_protoc_plugin__python_plugin_test_PythonPluginTest/

**Comment by adelez** [comment]
c_plugin._python_plugin_test.PythonPluginTest.testUnaryCallFutureExpired
[0mRunning       protoc_plugin._python_plugin_test.PythonPluginTest.testUnaryCallFutureFailed
[92mSUCCESS       protoc_plugin._python_plugin_test.PythonPluginTest.testUnaryCallFutureFailed
[0mRunning       protoc_plugin._python_plugin_test.PythonPluginTest.testUpDown
[92mSUCCESS       protoc_plugin._python_plugin_test.PythonPluginTest.testUpDown
[0m23 tests finished:
	22 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91mprotoc_plugin._python_plugin_test.PythonPluginTest.testFullDuplexCallExpired[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/protoc_plugin/_python_plugin_test.py", line 418, in testFullDuplexCallExpired
    grpc.StatusCode.DEADLINE_EXCEEDED)
  File "/usr/lib/python3.4/unittest/case.py", line 1070, in assertIs
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.4/unittest/case.py", line 642, in fail
    raise self.failureException(msg)
AssertionError: <StatusCode.UNIMPLEMENTED: (12, 'unimplemented')> is not <StatusCode.DEADLINE_EXCEEDED: (4, 'deadline exceeded')>

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure

**Comment by apolcyn** [comment]
a different failure for this same test happened on 4/23 at 1pm from master (about 10 runs have since passed)

the failure was `StatusCode.UNIMPLEMENTED`

```
Regression

python_linux_opt_native.py34.test.protoc_plugin._python_plugin_test.PythonPluginTest (from grpc.python_linux_opt_native)

Failing for the past 1 build (Since Failed#2192 )
Took 22 sec.
Error Message

Failure
Standard Output

[92mSUCCESS       protoc_plugin._python_plugin_test.PythonPluginTest.testUnaryCallFutureExpired
[0mRunning       protoc_plugin._python_plugin_test.PythonPluginTest.testUnaryCallFutureFailed
[92mSUCCESS       protoc_plugin._python_plugin_test.PythonPluginTest.testUnaryCallFutureFailed
[0mRunning       protoc_plugin._python_plugin_test.PythonPluginTest.testUpDown
[92mSUCCESS       protoc_plugin._python_plugin_test.PythonPluginTest.testUpDown
[0m23 tests finished:
	22 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91mprotoc_plugin._python_plugin_test.PythonPluginTest.testHalfDuplexCall[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/protoc_plugin/_python_plugin_test.py", line 457, in testHalfDuplexCall
    responses):
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 363, in __next__
    return self._next()
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 357, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found!)>

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure
```

**Comment by dgquintas** [comment]
Again: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/4954/console

**Comment by ericgribkoff** [comment]
Seen again: https://grpc-testing.appspot.com/job/gRPC_master_linux/2289/

**Comment by dgquintas** [comment]
Again, on windows: https://grpc-testing.appspot.com/job/gRPC_pr_win/6719/testReport/junit/(root)/python_windows_dbg_native/py35_test_protoc_plugin_beta_python_plugin_test_PythonPluginTest/

**Comment by markdroth** [comment]
Similar problem seen on Mac:

https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/6991/testReport/junit/(root)/python_macos_opt_native/py34_test_protoc_plugin_beta_python_plugin_test_PythonPluginTest/

```
[92mSUCCESS       protoc_plugin.beta_python_plugin_test.PythonPluginTest.testUnaryCallFutureFailed
[0mRunning       protoc_plugin.beta_python_plugin_test.PythonPluginTest.testUpDown
[92mSUCCESS       protoc_plugin.beta_python_plugin_test.PythonPluginTest.testUpDown
[0m23 tests finished:
	22 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91mprotoc_plugin.beta_python_plugin_test.PythonPluginTest.testStreamingInputCallFuture[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt_native/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 95, in result
    return self._future.result(timeout=timeout)
  File "/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt_native/py34/lib/python3.4/site-packages/grpc/_channel.py", line 279, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt_native/src/python/grpcio_tests/tests/protoc_plugin/beta_python_plugin_test.py", line 349, in testStreamingInputCallFuture
    response = response_future.result()
  File "/jenkins/workspace/gRPC_pull_requests_macos/workspace_python_macos_opt_native/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 97, in result
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure
```
