### ISSUE TITLE
python_linux_opt_native.py27.test.unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest flakes to raise expected RemoteError

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#10808]
https://grpc-testing.appspot.com/job/gRPC_master_linux/2170/testReport/junit/(root)/python_linux_opt_native/py27_test_unit_beta__face_interface_test_MultiCallableInvokerBlockingInvocationInlineServiceTest/

**Comment by adelez** [comment]
++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py27/bin/python
+ PYTHON=/var/local/git/grpc/py27/bin/python2.7
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py27/bin/python2.7 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledStreamRequestStreamResponse
[95mTesting gRPC Python...
[0m[94mSKIP          unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledStreamRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledStreamRequestUnaryResponse
[94mSKIP          unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledStreamRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledUnaryRequestStreamResponse
[94mSKIP          unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledUnaryRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledUnaryRequestUnaryResponse
[94mSKIP          unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testCancelledUnaryRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredStreamRequestStreamResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredStreamRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredStreamRequestUnaryResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredStreamRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredUnaryRequestStreamResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredUnaryRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredUnaryRequestUnaryResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testExpiredUnaryRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedStreamRequestStreamResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedStreamRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedStreamRequestUnaryResponse
[91mFAILURE       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedStreamRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedUnaryRequestStreamResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedUnaryRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedUnaryRequestUnaryResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedUnaryRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testParallelInvocations
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testParallelInvocations
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSequentialInvocations
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSequentialInvocations
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulStreamRequestStreamResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulStreamRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulStreamRequestUnaryResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulStreamRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulUnaryRequestStreamResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulUnaryRequestStreamResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulUnaryRequestUnaryResponse
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulUnaryRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testWaitingForSomeButNotAllParallelInvocations
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testWaitingForSomeButNotAllParallelInvocations
[0m15 tests finished:
	14 successful
	1 unsuccessful
	4 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91munit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedStreamRequestUnaryResponse[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/framework/interfaces/face/_blocking_invocation_inline_service.py", line 291, in testFailedStreamRequestUnaryResponse
    iter(requests), test_constants.LONG_TIMEOUT)
  File "/usr/lib/python2.7/unittest/case.py", line 116, in __exit__
    "{0} not raised".format(exc_name))
AssertionError: RemoteError not raised

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure
 Help us localize this page Page generated: Apr 21, 2017 4:32:41 PM PDTREST APIJenkins ver. 2.53
