### ISSUE TITLE
Issue with grpc for loading of pbjs 6 object when proto file references imports to other proto files.

### ISSUE THREAD

**Issue by Arun-KumarH** [grpc/grpc#10816]
Hello,

I have used the master branch's source code (which contains support for pbjs v6) and have resolved the path for imports for protobufjs object (v 6.7.3).

The grpc.loadObject(root) works when proto file does not contain any import but I get below exception when the proto file references to other proto files via imports.

```
Error: no such type
      at Service.lookupType (node_modules/protobufjs/src/namespace.js:357:15)
      at Method.resolve (node_modules/protobufjs/src/method.js:138:45)
      at Service.resolveAll (node_modules/protobufjs/src/service.js:109:20)
      at getProtobufServiceAttrs (node_modules/grpc/src/node/src/protobuf_js_6_common.js:115:11)
      at loadObject (node_modules/grpc/src/node/src/protobuf_js_6_common.js:143:25)
      at node_modules/grpc/src/node/src/protobuf_js_6_common.js:150:22
      at node_modules/lodash/lodash.js:4944:15
      at baseForOwn (node_modules/lodash/lodash.js:3001:24)
      at node_modules/lodash/lodash.js:4913:18
      at Function.forEach (node_modules/lodash/lodash.js:9359:14)
      at loadObject (node_modules/grpc/src/node/src/protobuf_js_6_common.js:149:7)
      at node_modules/grpc/src/node/src/protobuf_js_6_common.js:150:22
      at node_modules/lodash/lodash.js:4944:15
      at baseForOwn (node_modules/lodash/lodash.js:3001:24)
      at node_modules/lodash/lodash.js:4913:18
      at Function.forEach (node_modules/lodash/lodash.js:9359:14)
      at loadObject (node_modules/grpc/src/node/src/protobuf_js_6_common.js:149:7)
      at node_modules/grpc/src/node/src/protobuf_js_6_common.js:150:22
      at node_modules/lodash/lodash.js:4944:15
      at baseForOwn (node_modules/lodash/lodash.js:3001:24)
      at node_modules/lodash/lodash.js:4913:18
      at Function.forEach (node_modules/lodash/lodash.js:9359:14)
      at loadObject (node_modules/grpc/src/node/src/protobuf_js_6_common.js:149:7)
      at node_modules/grpc/src/node/src/protobuf_js_6_common.js:150:22
      at node_modules/lodash/lodash.js:4944:15
      at baseForOwn (node_modules/lodash/lodash.js:3001:24)
      at node_modules/lodash/lodash.js:4913:18
      at Function.forEach (node_modules/lodash/lodash.js:9359:14)
      at Object.loadObject (node_modules/grpc/src/node/src/protobuf_js_6_common.js:149:7)
      at Object.loadObject (node_modules/grpc/src/node/index.js:100:41)
```

Thank you.

**Comment by murgatroid99** [comment]
Are you calling `grpc.loadObject` directly, or through `grpc.load`? If you're calling it directly, that implies that you are loading the proto file with Protobuf.js yourself; have you tried doing anything with the loaded object yourself to verify that it loaded correctly? If you're using `grpc.load`, you should use the alternate argument format and pass an object with `root` and `file` properties, where `root` is the path that the proto imports are relative to, and `file` is the relative path from `root` to the file that you want to load.

**Comment by Arun-KumarH** [comment]
`grpc.load` using `root` and `file` properties works and hence closing. Thank you.
