### ISSUE TITLE
Flake in c++_linux_asan_native.bins/asan/end2end_test --gtest_filter=End2endServerTryCancel/End2endServerTryCancelTest.RequestEchoServerCancel/1 GRPC_POLL_STRATEGY=epoll

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#10830]
This test failed once on master today (4/24 at 1pm), but then 4 runs on master since then passed.

```
Regression

c++_linux_asan_native.bins/asan/end2end_test --gtest_filter=End2endServerTryCancel/End2endServerTryCancelTest.RequestEchoServerCancel/1 GRPC_POLL_STRATEGY=epoll (from grpc.c++_linux_asan_native)

Failing for the past 1 build (Since Failed#1397 )
Took 0.94 sec.
Error Message

Failure
Standard Output

l::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #27 0x14259b1 in testing::UnitTest::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4257:10
    #28 0x5ec8e3 in RUN_ALL_TESTS() /var/local/git/grpc/third_party/googletest/googletest/include/gtest/gtest.h:2233:10
    #29 0x51d9c8 in main /var/local/git/grpc/test/cpp/end2end/end2end_test.cc:1703:10

Objects leaked above:
0x602000003970 (15 bytes)

[1m[34mIndirect leak of 15 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4d2c38 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x889f27 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x88f568 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:56:9
    #3 0x70c4d8 in resolve_address_impl /var/local/git/grpc/src/core/lib/iomgr/resolve_address_posix.c:195:13
    #4 0xc4ae6f in dns_start_resolving_locked /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:216:3
    #5 0xc4a777 in dns_channel_saw_error_locked /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:129:5
    #6 0x99d592 in grpc_resolver_channel_saw_error_locked /var/local/git/grpc/src/core/ext/filters/client_channel/resolver.c:81:3
    #7 0x999bac in on_lb_policy_state_changed_locked /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.c:264:7
    #8 0x75380a in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:325:5
    #9 0x706d7a in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:83:17
    #10 0x77cb99 in closure_exec_thread_func /var/local/git/grpc/src/core/lib/iomgr/executor.c:93:7
    #11 0x896d94 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #12 0x7f9809a8b063 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8063)

Objects leaked above:
0x602000002710 (15 bytes)

[1m[34mIndirect leak of 6 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4d2c38 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x889f27 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x88f568 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:56:9
    #3 0xc49d23 in dns_create /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:262:21
    #4 0xc498b0 in dns_factory_create_resolver /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:288:10
    #5 0xc2381c in grpc_resolver_factory_create_resolver /var/local/git/grpc/src/core/ext/filters/client_channel/resolver_factory.c:49:10
    #6 0x99e4f2 in grpc_resolver_create /var/local/git/grpc/src/core/ext/filters/client_channel/resolver_registry.c:150:7
    #7 0x98af63 in cc_init_channel_elem /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.c:701:21
    #8 0x8b35ba in grpc_channel_stack_init /var/local/git/grpc/src/core/lib/channel/channel_stack.c:137:9
    #9 0x8b6de1 in grpc_channel_stack_builder_finish /var/local/git/grpc/src/core/lib/channel/channel_stack_builder.c:269:23
    #10 0x84dd9b in grpc_channel_create_with_builder /var/local/git/grpc/src/core/lib/surface/channel.c:95:23
    #11 0x84fddf in grpc_channel_create /var/local/git/grpc/src/core/lib/surface/channel.c:194:10
    #12 0x9b77cb in client_channel_factory_create_channel /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.c:81:27
    #13 0x9b7353 in grpc_insecure_channel_create /var/local/git/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.c:112:27
    #14 0x78357e in grpc::(anonymous namespace)::InsecureChannelCredentialsImpl::CreateChannel(std::string const&, grpc::ChannelArguments const&) /var/local/git/grpc/src/cpp/client/insecure_credentials.cc:54:9
    #15 0x7b013b in grpc::CreateCustomChannel(std::string const&, std::shared_ptr<grpc::ChannelCredentials> const&, grpc::ChannelArguments const&) /var/local/git/grpc/src/cpp/client/create_channel.cc:59:16
    #16 0x526bf2 in grpc::testing::(anonymous namespace)::End2endTest::ResetChannel() /var/local/git/grpc/test/cpp/end2end/end2end_test.cc:290:16
    #17 0x5254b7 in grpc::testing::(anonymous namespace)::End2endTest::ResetStub() /var/local/git/grpc/test/cpp/end2end/end2end_test.cc:294:5
    #18 0x521ce9 in grpc::testing::(anonymous namespace)::End2endServerTryCancelTest_RequestEchoServerCancel_Test::TestBody() /var/local/git/grpc/test/cpp/end2end/end2end_test.cc:588:3
    #19 0x1479cab in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #20 0x14484f0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #21 0x1413b39 in testing::Test::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2474:5
    #22 0x141599c in testing::TestInfo::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2656:5
    #23 0x1416b31 in testing::TestCase::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2774:5
    #24 0x14263bc in testing::internal::UnitTestImpl::RunAllTests() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4649:11
    #25 0x14834e6 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #26 0x144daa0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #27 0x14259b1 in testing::UnitTest::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4257:10
    #28 0x5ec8e3 in RUN_ALL_TESTS() /var/local/git/grpc/third_party/googletest/googletest/include/gtest/gtest.h:2233:10
    #29 0x51d9c8 in main /var/local/git/grpc/test/cpp/end2end/end2end_test.cc:1703:10

Objects leaked above:
0x602000003950 (6 bytes)

[1m[34mIndirect leak of 6 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4d2c38 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x889f27 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:71:7
    #2 0x88f568 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:56:9
    #3 0x70c524 in resolve_address_impl /var/local/git/grpc/src/core/lib/iomgr/resolve_address_posix.c:196:21
    #4 0xc4ae6f in dns_start_resolving_locked /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:216:3
    #5 0xc4a777 in dns_channel_saw_error_locked /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:129:5
    #6 0x99d592 in grpc_resolver_channel_saw_error_locked /var/local/git/grpc/src/core/ext/filters/client_channel/resolver.c:81:3
    #7 0x999bac in on_lb_policy_state_changed_locked /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.c:264:7
    #8 0x75380a in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:325:5
    #9 0x706d7a in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:83:17
    #10 0x77cb99 in closure_exec_thread_func /var/local/git/grpc/src/core/lib/iomgr/executor.c:93:7
    #11 0x896d94 in thread_body /var/local/git/grpc/src/core/lib/support/thd_posix.c:57:3
    #12 0x7f9809a8b063 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8063)

Objects leaked above:
0x6020000026f0 (6 bytes)

SUMMARY: AddressSanitizer: 2000 byte(s) leaked in 36 allocation(s).
```

log in https://grpc-testing.appspot.com/job/gRPC_master_asanitizer_cpp/1397/

**Comment by yang-g** [comment]
Could not seem to reproduce locally with 100k runs.

**Comment by muxi** [comment]
Still failing in master:
https://grpc-testing.appspot.com/job/gRPC_master_asanitizer_cpp/1565/
