### ISSUE TITLE
bm_diff is failing to comment on PR's

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#10852]
```
Traceback (most recent call last):
  File "tools/profiling/microbenchmarks/bm_diff.py", line 255, in <module>
    eintr_be_gone(finalize)
  File "tools/profiling/microbenchmarks/bm_diff.py", line 200, in eintr_be_gone
    return fn()
  File "tools/profiling/microbenchmarks/bm_diff.py", line 251, in finalize
    comment_on_pr.comment_on_pr('```\n%s\n```' % text)
  File "tools/profiling/microbenchmarks/../../run_tests/python_utils/comment_on_pr.py", line 49, in comment_on_pr
    print urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by matt-kwong** [comment]
I think this is related to exceeding GH's API quota, so I'm switching the commenting to a different GH account and will see how if this resolves this issue.

**Comment by matt-kwong** [comment]
According to https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits, specific actions, e.g. commenting on PRs, are subject to stricter rate limits. Maybe having an account dedicated to commenting might resolve this issue.

**Comment by matt-kwong** [comment]
This issue hasn't been seen in a while.

**Comment by apolcyn** [comment]
just seen again in both the `bm_diff` and `trickle_diff` jobs:

```
19:11:57 
19:11:57 [microbenchmarks] Performance differences noted:
19:11:57 Benchmark                                                                            cpu_time    nows_per_iteration    real_time
19:11:57 -----------------------------------------------------------------------------------  ----------  --------------------  -----------
19:11:57 BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/1/1/1  +4%                               +4%
19:11:57 BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/16M                                -4%
19:11:57 Traceback (most recent call last):
19:11:57   File "tools/profiling/microbenchmarks/bm_diff/bm_main.py", line 145, in <module>
19:11:57     main(args)
19:11:57   File "tools/profiling/microbenchmarks/bm_diff/bm_main.py", line 140, in main
19:11:57     comment_on_pr.comment_on_pr('```\n%s\n```' % text)
19:11:57   File "tools/profiling/microbenchmarks/bm_diff/../../../run_tests/python_utils/comment_on_pr.py", line 34, in comment_on_pr
19:11:57     print urllib2.urlopen(req).read()
19:11:57   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
19:11:57     return opener.open(url, data, timeout)
19:11:57   File "/usr/lib/python2.7/urllib2.py", line 435, in open
19:11:57     response = meth(req, response)
19:11:57   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
19:11:57     'http', request, response, code, msg, hdrs)
19:11:57   File "/usr/lib/python2.7/urllib2.py", line 473, in error
19:11:57     return self._call_chain(*args)
19:11:57   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
19:11:57     result = func(*args)
19:11:57   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
19:11:57     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
19:11:57 urllib2.HTTPError: HTTP Error 403: Forbidden
```

in `bm_diff` and

```
19:48:28 2017-09-15 02:47:19
19:48:28 Benchmark                                         Time           CPU Iterations
19:48:28 -------------------------------------------------------------------------------
19:48:28 BM_PumpUnbalancedUnary_Trickle/64/1/256k    2233467 ns      98562 ns       7092   644.026kB/s writes/iter:3.26325 cli_transport_stalls/iter:0 cli_stream_stalls/iter:0 svr_transport_stalls/iter:0 svr_stream_stalls/iter:0
19:48:28 
19:48:28 2017-09-15 02:48:28,236 PASSED: bm_fullstack_trickle BM_PumpUnbalancedUnary_Trickle/64/1/256k opt old 3/4 [time=68.3sec; retries=0:0]
19:48:28 [trickle] No significant performance differences
19:48:28 Traceback (most recent call last):
19:48:28   File "tools/profiling/microbenchmarks/bm_diff/bm_main.py", line 145, in <module>
19:48:28     main(args)
19:48:28   File "tools/profiling/microbenchmarks/bm_diff/bm_main.py", line 140, in main
19:48:28     comment_on_pr.comment_on_pr('```\n%s\n```' % text)
19:48:28   File "tools/profiling/microbenchmarks/bm_diff/../../../run_tests/python_utils/comment_on_pr.py", line 34, in comment_on_pr
19:48:28     print urllib2.urlopen(req).read()
19:48:28   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
19:48:28     return opener.open(url, data, timeout)
19:48:28   File "/usr/lib/python2.7/urllib2.py", line 435, in open
19:48:28     response = meth(req, response)
19:48:28   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
19:48:28     'http', request, response, code, msg, hdrs)
19:48:28   File "/usr/lib/python2.7/urllib2.py", line 473, in error
19:48:28     return self._call_chain(*args)
19:48:28   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
19:48:28     result = func(*args)
19:48:28   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
19:48:28     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
19:48:28 urllib2.HTTPError: HTTP Error 403: Forbidden
19:48:28 Build step 'Execute shell' marked build as failure
```

in `trickle_diff`


in https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/14717/console and https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests_trickle/2100/console

**Comment by matt-kwong** [comment]
I see this job was failing for a few hours last night, but it seems to be passing now. It probably was a GitHub API quota issue, which I haven't seen happen in a while.

**Comment by matt-kwong** [comment]
Haven't seen this in a while. It was probably a transient error
