### ISSUE TITLE
grpc C# reports failure to bind port by BoundPort == 0

### ISSUE THREAD

**Issue by chwarr** [grpc/grpc#10918]
In the C# grpc library I'm seeing that a failure to bind/listen to a `ServerPort` is reported by the `ServerPort.BoundPort` property being 0 after calling `Server.Start()`. Is this the expected behavior? My expectation would have been for `Server.Start()` to throw an exception, based on my experience with `System.Net.Sockets.TcpListener` and `System.Net.Sockets.Socket`.

Here's a sample program that demonstrates what I'm seeing:

```
namespace grpc_port_bind_failure
{
    using System;
    using System.Net;
    using System.Net.Sockets;

    using Grpc.Core;

    class PortBindFailure
    {
        const int ConflictPort = 50051;

        static void Main(string[] args)
        {
            // Start a TcpListener on a port to prevent gRPC from being able to bind to it later.
            var tcpListener = new TcpListener(IPAddress.Loopback, ConflictPort);
            tcpListener.Start();
            Console.WriteLine($"tcpListener listening on {tcpListener.LocalEndpoint}");

            try
            {
                // Attempt to bind to the port--again. Expect failure, and get failure.
                var tcpListener2 = new TcpListener(IPAddress.Loopback, ConflictPort);
                tcpListener2.Start();
                Console.WriteLine($"tcpListener2 listening on {tcpListener.LocalEndpoint}!?!");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"tcpListener2 failed to start: {ex}");
            }

            var s = new Server
            {
                Ports =
                {
                    new ServerPort("127.0.0.1", ConflictPort, ServerCredentials.Insecure),
                }
            };

            // Attempt to bind to the port--again. Expect failure, but get success.
            s.Start();

            Console.WriteLine("Binding details for gRPC ports:");

            foreach (var p in s.Ports)
            {
                Console.WriteLine($"{p.Host}:{p.Port} actually listening on {p.BoundPort}");
            }
        }
    }
}
```

Here's the console output when I run this:

```
tcpListener listening on 127.0.0.1:50051
tcpListener2 failed to start: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at grpc_port_bind_failure.PortBindFailure.Main(String[] args) in D:\TEMP\grpc-port-bind-failure\grpc-port-bind-failure\Program.cs:line 24
Binding details for gRPC ports:
127.0.0.1:50051 actually listening on 0
```

Environment details:
* Console application
* NuGet packages Grpc and Grpc.Core 1.3.0
* Targeting .NET Framework 4.6.1
* Visual C# 2015 (Visual C# Compiler version 1.3.1.60616)
* Windows 10 Version 1703 (OS Build 15063.250) amd64

**Comment by apolcyn** [comment]
By default the gRPC C# servers will start with `SO_REUSEPORT`. There's an option to disable this  with a "channel arg" though, an example of doing so is in https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Examples.Tests/MathClientServerTests.cs#L59

**Comment by apolcyn** [comment]
actually might have misunderstood, leaving this open to take another look at `127.0.0.1:50051 actually listening on 0`

**Comment by jtattermusch** [comment]
Will be in v1.4.x release.
