### ISSUE TITLE
bdist_wheel fails: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by drigz** [grpc/grpc#10986]
Steps to reproduce:

```
git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init --recursive
python setup.py bdist_wheel
```

Complete error:

```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/usr/include/python2.7 -c src/core/lib/support/env_linux.c -o python_build/temp.linux-x86_64-2.7/src/core/lib/support/env_linux.o -std=c++11 -fvisibility=hidden -fno-wrapv -pthread
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
In file included from src/core/lib/support/env_linux.c:50:0:
include/grpc/support/log.h:86:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 GPRAPI void gpr_log_verbosity_init();
 ^
src/core/lib/support/env_linux.c: In function ‘gpr_getenv’:
src/core/lib/support/env_linux.c:63:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; getenv_func == NULL && i < GPR_ARRAY_SIZE(names); i++) {
   ^
src/core/lib/support/env_linux.c:63:3: note: use option -std=c99 or -std=gnu99 to compile your code
creating tmp
creating tmp/tmpQdTE7w
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /tmp/tmpQdTE7w/a.c -o tmp/tmpQdTE7w/a.o
Traceback (most recent call last):
  File "setup.py", line 304, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 66, in run
    _build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/usr/local/google/home/rodrigoq/git/grpc/src/python/grpcio/commands.py", line 310, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/usr/local/google/home/rodrigoq/git/grpc/src/python/grpcio/commands.py", line 305, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 178, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by nathanielmanistaatgoogle** [comment]
With what operating system (and version) are you running, and on what platform?
