### ISSUE TITLE
Jenkins failed on "NameError: global name 'upload_results_to_bq' is not defined"

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#11211]
Happened in MacOS master:
https://grpc-testing.appspot.com/job/gRPC_master_macos/2408/#showFailuresLink
```
Traceback (most recent call last):
  File "workspace_c_macos_dbg_native/tools/run_tests/run_tests.py", line 1565, in <module>
    build_only=args.build_only)
  File "workspace_c_macos_dbg_native/tools/run_tests/run_tests.py", line 1526, in _build_and_run
    upload_results_to_bq(resultset, args.bq_result_table, args, platform_string())
NameError: global name 'upload_results_to_bq' is not defined
```

**Comment by adelez** [comment]
Not happening any more.
