### ISSUE TITLE
FAILED: objc_macos_opt_native.objc-examples-build

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#11213]
Failed in master:
https://grpc-testing.appspot.com/job/gRPC_master_macos/2396/testReport/junit/(root)/objc_macos_opt_native/objc_examples_build/
```
Error Message

Failure
Stacktrace

 Compiling RouteGuide-dummy.m
 Compiling RouteGuide.pbobjc.m
 Compiling RouteGuide.pbrpc.m
 Building library libRouteGuide.a
 Copying RouteGuide.pbrpc.h
 Copying RouteGuide.pbobjc.h
 Building Pods/Pods-RouteGuideClient [Debug]
 Check Dependencies
 Compiling Pods-RouteGuideClient-dummy.m
 Building library libPods-RouteGuideClient.a
 Building RouteGuideClient/RouteGuideClient [Debug]
 Check Dependencies
 Running script '[CP] Check Pods Manifest.lock'
 Compiling main.m
 Compiling AppDelegate.m
 Linking RouteGuideClient
 Copying route_guide_db.json
 Compiling Main.storyboard
 Processing Info.plist
 Generating 'RouteGuideClient.app.dSYM'
 Running script '[CP] Copy Pods Resources'
 Running script '[CP] Embed Pods Frameworks'
 Touching RouteGuideClient.app
 Build Succeeded

echo "TIME:  $(date)"
date
TIME:  Tue May 16 21:32:02 PDT 2017
SCHEME=AuthSample                               \
  EXAMPLE_PATH=examples/objective-c/auth_sample \
  ./build_one_example.sh

# Params:
# EXAMPLE_PATH - directory of the example
# SCHEME - scheme of the example, used by xcodebuild

# CocoaPods requires the terminal to be using UTF-8 encoding.
export LANG=en_US.UTF-8

cd `dirname $0`/../../..
dirname $0

cd $EXAMPLE_PATH

# clean the directory
rm -rf Pods
rm -rf $SCHEME.xcworkspace
rm -f Podfile.lock

pod install
Analyzing dependencies
Fetching podspec for `AuthTestService` from `.`
Downloading dependencies
Installing !ProtoCompiler (3.2.0)
Installing !ProtoCompiler-gRPCPlugin (1.3.0)
Installing AuthTestService (0.0.1)
Installing BoringSSL (8.2)

 MARKDOWN TEMPLATE 

### Command

```
/usr/local/rvm/gems/ruby-2.4.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]
    RubyGems : 2.6.10
        Host : Mac OS X 10.10.5 (14F2315)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f0acffea804ddc155099c1239659faa81738cb37
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'AuthSample' do
  # Depend on the generated AuthTestService library.
  pod 'AuthTestService', :path => '.'

  # Depend on Google's OAuth2 library
  pod 'Google/SignIn'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_file_s_lstat - /Users/jenkins/Library/Caches/CocoaPods/Pods/Release/BoringSSL/8.2-4135a/crypto/bytestring/internal.h
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1220:in `lstat'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1220:in `lstat'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1247:in `copy'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:409:in `block in copy_entry'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1381:in `wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1384:in `block in wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1383:in `each'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1383:in `wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1384:in `block in wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1383:in `each'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1383:in `wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1384:in `block in wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1383:in `each'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1383:in `wrap_traverse'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:406:in `copy_entry'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:384:in `block in cp_r'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1454:in `block in fu_each_src_dest'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1470:in `fu_each_src_dest0'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:1452:in `fu_each_src_dest'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:383:in `cp_r'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:54:in `block in download'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:52:in `download'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:313:in `each'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:157:in `download_dependencies'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:111:in `install!'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/rvm/gems/ruby-2.4.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/rvm/gems/ruby-2.4.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/bin/pod:22:in `load'
/usr/local/rvm/gems/ruby-2.4.0/bin/pod:22:in `<main>'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

 TEMPLATE END 

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_file_s_lstat+-+%2FUsers%2Fjenkins%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FRelease%2FBoringSSL%2F8.2-4135a%2Fcrypto%2Fbytestring%2Finternal.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
echo "EXIT TIME:  $(date)"
date
EXIT TIME:  Tue May 16 21:32:29 PDT 2017
real       237.81
user       134.62
sys         39.89
```

**Comment by murgatroid99** [comment]
I'm seeing a similar failure with a different reason: https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/5730/testReport/junit/(root)/objc_macos_dbg_native/objc_examples_build/

The error at the end is `sed: crypto/cipher/e_tls.c: No such file or directory`

**Comment by adelez** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/7330/ for both opt and dbg builds.

**Comment by jtattermusch** [comment]
Seems fixed (https://github.com/grpc/grpc/pull/13094)
