### ISSUE TITLE
double free error

### ISSUE THREAD

**Issue by bwins3939** [grpc/grpc#11234]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 
1.3.1 C++
 
### What operating system (Linux, Windows, …) and version?
 
 linuc ubuntu 14.04
### What runtime / compiler are you using (e.g. python version or version of gcc)

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
I have a web interface using go grpc which is talking to my c++ application using grpc 1.3.1

### What did you see instead?
 
double free or corruption errors.. sig abort

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

 I0518 16:56:28.758254546    2282 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
main() calling IBOApp::run()
NET-SNMP version 5.7.2 AgentX subagent connected
*** Error in `./bhio': double free or corruption (fasttop): 0x00007fb20c002f00 ***
# 

gdb dump:

```
[New Thread 0x7fff8ffff700 (LWP 3457)]
[Thread 0x7fff8ffff700 (LWP 3457) exited]
*** Error in `/bhio': munmap_chunk(): invalid pointer: 0x00007fff6c0026f0 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff8e7fc700 (LWP 3444)]
0x00007ffff6343cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007ffff6343cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff63470d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6380394 in __libc_message (do_abort=do_abort@entry=1,
    fmt=fmt@entry=0x7ffff648eb28 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff638b0f7 in malloc_printerr (action=<optimized out>,
    str=0x7ffff648eea8 "munmap_chunk(): invalid pointer", ptr=<optimized out>)
    at malloc.c:4996
#4  0x000000000077b7bd in grpc_byte_buffer_destroy ()
#5  0x0000000000773ac3 in grpc::Server::SyncRequest::CallData::~CallData() ()
#6  0x000000000077405a in grpc::Server::SyncRequestThreadManager::DoWork(void*, bool) ()
#7  0x0000000000776111 in grpc::ThreadManager::MainWorkLoop() ()
#8  0x000000000077616c in grpc::ThreadManager::WorkerThread::Run() ()
#9  0x00007ffff6c9fa40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff6efa182 in start_thread (arg=0x7fff8e7fc700)
    at pthread_create.c:312
#11 0x00007ffff640747d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)
```

### Anything else we should know about your project / environment?

anybody else seeing this?   is there a previous release that I should try which might not have this error?
sorry, new to this grpc, taking over for a previous software engineer who left... argh!

**Comment by bwins3939** [comment]
I finally figured it out... 

  not a grpc issue per say.....    had a really small memory leak in the registered service function.. which over time caused the core above...

kicker was finding which one of the hundreds of registered service functions that was causing the issue with the memory leak (someone forgot to close a socket FD.)

Bob
