### ISSUE TITLE
Tests on windows worker 4 failing for no apparent reason.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11243]
https://grpc-testing.appspot.com/job/gRPC_pr_win/5472/

```
+ python workspace_csharp_windows_dbg_native/tools/run_tests/run_tests.py -t -j 8 -x ../report_csharp_windows_dbg_native_sponge_log.xml --report_suite_name csharp_windows_dbg_native -l csharp -c dbg --iomgr_platform native --max_time 3600
2017-05-19 15:44:06,067 START: tools\run_tests\helper_scripts\pre_build_csharp.bat
2017-05-19 15:44:06,095 WARNING: Failed to start tools\run_tests\helper_scripts\pre_build_csharp.bat, retrying in 0.300000 seconds
2017-05-19 15:44:06,422 WARNING: Failed to start tools\run_tests\helper_scripts\pre_build_csharp.bat, retrying in 0.600000 seconds
2017-05-19 15:44:07,046 WARNING: Failed to start tools\run_tests\helper_scripts\pre_build_csharp.bat, retrying in 1.200000 seconds
2017-05-19 15:44:08,270 WARNING: Failed to start tools\run_tests\helper_scripts\pre_build_csharp.bat, retrying in 2.400000 seconds
Traceback (most recent call last):
  File "workspace_csharp_windows_dbg_native/tools/run_tests/run_tests.py", line 1568, in <module>
    build_only=args.build_only)
  File "workspace_csharp_windows_dbg_native/tools/run_tests/run_tests.py", line 1455, in _build_and_run
    newline_on_success=newline_on_success, travis=args.travis)
  File "/c/jenkins/workspace/gRPC_pr_win/workspace_csharp_windows_dbg_native/tools/run_tests/python_utils/jobset.py", line 522, in run
    if not js.start(cmdline):
  File "/c/jenkins/workspace/gRPC_pr_win/workspace_csharp_windows_dbg_native/tools/run_tests/python_utils/jobset.py", line 422, in start
    self._quiet_success)
  File "/c/jenkins/workspace/gRPC_pr_win/workspace_csharp_windows_dbg_native/tools/run_tests/python_utils/jobset.py", line 260, in __init__
    self.start()
  File "/c/jenkins/workspace/gRPC_pr_win/workspace_csharp_windows_dbg_native/tools/run_tests/python_utils/jobset.py", line 291, in start
    self._process = try_start()
  File "/c/jenkins/workspace/gRPC_pr_win/workspace_csharp_windows_dbg_native/tools/run_tests/python_utils/jobset.py", line 280, in <lambda>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by matt-kwong** [comment]
I restarted all the failing Windows PR jobs that failed on worker 4. There was an issue with the PATH that made that worker use a different version of Python that was causing issues when using `subprocess.Popen()`. 

The issue should be fixed, but I'll leave this open until a few builds are successful on worker 4.

**Comment by matt-kwong** [comment]
Builds looking good on worker 4.
