### ISSUE TITLE
FLAKE: tests.cloud_to_prod:default:csharpcoreclr:cancel_after_begin

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11274]
seen in https://github.com/grpc/grpc/pull/11267

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/14299/testReport/junit/(root)/tests/cloud_to_prod_default_csharpcoreclr_cancel_after_begin/

```
Regression

tests.cloud_to_prod:default:csharpcoreclr:cancel_after_begin (from grpc.tests)

Failing for the past 1 build (Since Unstable#14299 )
Took 4.1 sec.
Error Message

Failure
Stacktrace

D0522 18:39:26.358033 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0522 18:39:26.408191 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running cancel_after_begin

Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Assert.ReportFailure(String message)
   at Grpc.IntegrationTesting.InteropClient.<RunCancelAfterBeginAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)
```

**Comment by jtattermusch** [comment]
not seen for a month
