### ISSUE TITLE
FLAKE: bins/ubsan/h2_proxy_test payload GRPC_POLL_STRATEGY=poll-cv

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11321]
the log shows:

https://grpc-testing.appspot.com/job/gRPC_pull_requests_ubsan_c/484/consoleFull

```
2017-05-26 05:43:51,933 PASSED: bins/ubsan/client_fuzzer_one_entry test/core/end2end/fuzzers/client_fuzzer_corpus/17b1758fc7cd69a00d140f113b1ac894023ff20b [time=0.0sec; retries=0:0]
2017-05-26 05:43:52,013 D0526 05:43:51.564966874    3213 test_config.c:403]          test slowdown factor: sanitizer=5, fixture=1, poller=5, total=25
D0526 05:43:51.565259573    3213 ev_posix.c:121]             Using polling engine: poll-cv
D0526 05:43:51.565829598    3213 dns_resolver.c:316]         Using native dns resolver
I0526 05:43:51.565916606    3213 payload.c:53]               Running test: test_invoke_request_response_with_payload/chttp2/fullstack+proxy
D0526 05:43:51.571065125    3213 proxy.c:104]                PROXY ADDR:localhost:28366 BACKEND:localhost:32261
I0526 05:43:51.682169706    3213 payload.c:53]               Running test: test_invoke_10_request_response_with_payload/chttp2/fullstack+proxy
D0526 05:43:51.685834661    3213 proxy.c:104]                PROXY ADDR:localhost:24670 BACKEND:localhost:24162
src/core/ext/transport/chttp2/transport/chttp2_transport.c:2162:22: runtime error: value 2.74071e+09 is outside the range of representable values of type 'int'
    #0 0xc7e78b in update_frame /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:2162:22
    #1 0xc541f2 in read_action_locked /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:2320:9
    #2 0x89881b in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:325:5
    #3 0x6a3b61 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:88:17
    #4 0x9707a6 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_poll_posix.c:1032:22
    #5 0x69f952 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:223:10
    #6 0x7f6e38 in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:844:23
    #7 0x7ee279 in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:873:10
    #8 0x60d0d6 in cq_verify /var/local/git/grpc/test/core/end2end/cq_verifier.c:269:21
    #9 0x573c4c in request_response_with_payload /var/local/git/grpc/test/core/end2end/tests/payload.c:219:3
    #10 0x56e421 in test_invoke_10_request_response_with_payload /var/local/git/grpc/test/core/end2end/tests/payload.c:292:5
    #11 0x56e144 in payload /var/local/git/grpc/test/core/end2end/tests/payload.c:300:3
    #12 0x42f083 in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_tests.c:423:7
    #13 0x429851 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_proxy.c:133:5
    #14 0x7f12cd66ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #15 0x405f0c in _start (/var/local/git/grpc/bins/ubsan/h2_proxy_test+0x405f0c)


2017-05-26 05:43:52,013 FAILED: bins/ubsan/h2_proxy_test payload GRPC_POLL_STRATEGY=poll-cv [ret=1, pid=3213]

```

What looks noteable is: `src/core/ext/transport/chttp2/transport/chttp2_transport.c:2162:22: runtime error: value 2.74071e+09 is outside the range of representable values of type 'int'`

**Comment by jtattermusch** [comment]
not seen in >1month.
