### ISSUE TITLE
run_tests_c++_linux_dbg_native_x64_gcc5.3 portability test failed

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11320]
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/5722/testReport/junit/(root)/aggregate_tests/run_tests_c___linux_dbg_native_x64_gcc5_3/

```
...
2017-05-26 05:13:55,571 START: make
2017-05-26 05:24:45,606 PASSED: make [time=650.0sec; retries=0:0]
2017-05-26 05:24:45,608 SUCCESS: All tests passed
/var/local/jenkins/grpc/tools/run_tests/dockerize/docker_run_tests.sh: line 57:   652 Alarm clock             $RUN_TESTS_COMMAND
  adding: reports/ (stored 0%)
  adding: reports/index.html (deflated 22%)
  adding: report_c++_linux_dbg_native_x64_gcc5.3_sponge_log.xml (deflated 25%)
+ DOCKER_EXIT_CODE=142
++ mktemp
+ TEMP_REPORTS_ZIP=/tmp/tmp.tFcJZe7mMy
+ docker cp run_tests_a9337925-661a-4660-bbdb-802190062cdb:/var/local/git/grpc/reports.zip /tmp/tmp.tFcJZe7mMy
+ unzip -o /tmp/tmp.tFcJZe7mMy -d /home/jenkins/workspace/gRPC_portability_pull_requests_linux
Archive:  /tmp/tmp.tFcJZe7mMy
  inflating: /home/jenkins/workspace/gRPC_portability_pull_requests_linux/reports/index.html  
  inflating: /home/jenkins/workspace/gRPC_portability_pull_requests_linux/report_c++_linux_dbg_native_x64_gcc5.3_sponge_log.xml  
+ rm -f /tmp/tmp.tFcJZe7mMy
+ docker rm -f run_tests_a9337925-661a-4660-bbdb-802190062cdb
run_tests_a9337925-661a-4660-bbdb-802190062cdb
+ exit 142
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1316, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 142

2017-05-26 05:24:48,648 FAILED: run_tests_c++_linux_dbg_native_x64_gcc5.3 [ret=1, pid=16109]
```

**Comment by jtattermusch** [comment]
Obsolete.
