### ISSUE TITLE
Node artifact build is broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11372]
```
Command failed: /root/.nvm/versions/node/v4.4.3/bin/node --eval require('/var/local/git/grpc/src/node/extension_binary/grpc_node.node')
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)

+ FAILED=true
```

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/140/platform=linux/testReport/junit/(root)/tasks/build_artifact_node_ext_linux_x64/

**Comment by murgatroid99** [comment]
This is fixed by #11354, which will get to master in the next upmerge.
