### ISSUE TITLE
Connection Failed on node after some successful calls.

### ISSUE THREAD

**Issue by krundrufanatics** [grpc/grpc#11523]
`Connection failed` error event from server stream call. this is happening only after some successful calls. 

```javascript
$ commit call status : Connect Failed

$ { Error: Connect Failed
    at ClientReadableStream._emitStatusIfDone (/rapid/node_modules/grpc/src/node/src/client.js:209:19)
    at ClientReadableStream._readsDone (/rapid/node_modules/grpc/src/node/src/client.js:177:8)
    at readCallback (/rapid/node_modules/grpc/src/node/src/client.js:237:12) code: 14, metadata: Metadata { _internal_repr: {} } }
```
grpc version: 1.3.8
OS: centos  (AWS cloud)
Platform: NODE JS.

**Code from rpc-client.js file**
``` javascript
import grpc from 'grpc'

const ckService = grpc.load(PROTO_PATH).external.protocol
const client = new ckService.CkPublic(url, grpc.credentials.createInsecure())

function executeCommand(request) {
  return client.executeCommand(request)
}

export default { executeCommand }
```
**Code from action.js**
``` javascript
import ckClient from './rpc-client.js'
const stream = ckClient.executeCommand(request)
stream.on('error', function(err) {
    console.error(err)
})

stream.on('data', function(chunk) { 
})
stream.on('status', function(rpcStatus) {
    console.log(`${request.rpcRequest.action} call status : ${rpcStatus.details}`)
})
```

**Comment by murgatroid99** [comment]
I think it is most likely that you would see that error if your client is connected to a server and then that connection drops, as reported in #11411. You may be able to fix this simply by retrying the request once the connection is reestablished.

**Comment by krundrufanatics** [comment]
It happened again today for two hours. Until I restart the docker image, calls were continuously failed with "Connect Failed". 

Is it something related to docker ? I am using node:6.11.0-slim as base image.

```
FROM node:6.11.0-slim

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Bundle app source
COPY build/ ./
COPY package.json ./
COPY yarn.lock ./

# Install node dependencies.
RUN yarn  --prod
CMD [ "./node_modules/pm2/bin/pm2-docker", "--raw", "server.js" ]
```

**Comment by murgatroid99** [comment]
Can you show the server code? When you say that you use consul for service registry, how is that being used with gRPC?

**Comment by krundrufanatics** [comment]
Regarding above comment: The url I use for creating client, is pointed to consul service. More about [consul DNS](https://www.consul.io/docs/agent/dns.html)

I have reproduced this issue locally. by changing `/etc/hosts`. 
Steps are 
1. Start grpc client server, by pointing to a actual service ( say url is `grpc.service.dynamic.dev.example.com`)
2. Call grpc method => successfully executed.
3. Change the host and point above url to fake IP where no service is running.
` 10.0.0.1 grpc.service.dynamic.dev.example.com `
4. Called grpc method again and expected `connect fail` but it went through. 

I am suspecting that the DNS resolution is not happening every call may be it is b/c i created one client instance and using for every call.  

Note: also tried by pointing to fake which resulted 'Connect Failed' then updated hosts to actual address, it still pointed to fake IP.

**Comment by nicolasnoble** [comment]
CC @dgquintas

**Comment by dgquintas** [comment]
The way things works in C Core and, by extension, in Node:
1. You create a channel using a target name. Let's assume we are using DNS as the resolving mechanism. That target name resolves to a set of addresses.
1. By default, the channel will go over the list of resolved addresses. If it can connect to one of them, it'll stick to that one for the duration of the channel _or_ the connection.
   - If an already established connection fails, _a new (DNS) resolution will happen_ and go back to the beginning of this point, going over the resolved addresses _for the name used when creating the channel_.

Note that _nothing will happen for as long as a previously established connection is still healthy_. If you update the /etc/hosts file, it'll only be taken into account the moment you terminate the connection to the service you created in your step 1. (presumably by killing that server).

**Comment by krundrufanatics** [comment]
So, My understanding is:
At the time of client creation, DNS will resolve set of addresses then client will only go over each address and established a connection. if existing connection fails, it will go over pre-resolved address and find others. 
That means, Dynamically updated addresses will not be used.  How to deal with dynamic addresses. 

How do i know that my client is not healthy, so I can create new only ? 
I am using server stream call, which is hard to retry.

**Comment by dgquintas** [comment]
No: if an existing connection fails, **the client will re-resolve the name given at channel creation** and then start trying to connect to the list of addresses (which may be the same or different. In your case it'd be different if you changed the /etc/hosts in the meantime).

**Comment by krundrufanatics** [comment]
Then, I also tried first connecting to fake ip (in host file) and it got failed with 'Connect Failed' then I have updated host file with actual address and tried again. but it still says 'Connect Failed'. 

Is the initial connection to fake IP address healthy ? so, it doesn't retry to connect new IP ?

What is target name ? as I mentioned in the initial comment, this is how I am creating client with consul url `grpc.service.dynamic.dev.example.com`
``` javascript
new ckService.CkPublic(url, grpc.credentials.createInsecure())
```

**Comment by dgquintas** [comment]
The problem is that, by using the fake address from the start, you never actually establish a connection. The sequence to re-trigger a resolution is as previously described: 1. working connection 2. working connection fails 3. re-resolution triggered.

It could be argued that a re-resolution should also be triggered none of the initial addresses can connect. We'll explore this possibility, but in any case, the current behavior requires a connection to go from good to bad. 

I'd suggest:
1. Have the client connect successfully.
2. Update /etc/hosts
3. Make the client fail by killing the service from point 1. currently successfully connected.
4. The next client call should trigger a re-resolution a pick up the changes to /etc/hosts from step 2.

What I mean by "target name" would be "grpc.service.dynamic.dev.example.com:50051", yes. And "grpc.service.dynamic.dev.example.com" is what you should be using as the key in /etc/hosts.

**Comment by krundrufanatics** [comment]
Thanks @dgquintas  for quick responses and letting me know the details of gRPC. 

I will try the suggested approach and also simulate whole integration on consul & dynamic instance meanwhile. 

So, what is your opinion/guess on actual issue. I was continuously getting 'Connect Failed' error untill I restart the server.

**Comment by krundrufanatics** [comment]
As I was suspecting, it is trying to connect 3 IPs (Staled) on which service is not running. At the time of this error, service is running on 3 different IPs. 

I was able to capture all the logs of "Connect Failed" call by enabling the env variables. 
[connect-fail-log.txt](https://github.com/grpc/grpc/files/1092059/connect-fail-log.txt)

I don't see DNS resolution call :(

**Comment by dgquintas** [comment]
Thanks for the log. I don't see any successful call. Please re-read [my previous comment](https://github.com/grpc/grpc/issues/11523#issuecomment-309938518). In particular, the need for the channel to _successfully connect first_. I'll discuss with the team if the current behavior of not re-resolving unless there's a successful connection is what we want, but in any case, that's the current one.

**Comment by krundrufanatics** [comment]
I just posted the logs of the last rpc call and rest I have removed. But there were some successful calls but the time gap was almost a  12 hrs. 

Since I haven't setup up proper log mechanism yet, I lost all the logs after I restart my docker.  Also, as I mentioned through out this issue, this is happening after some successful calls.

**Comment by krundrufanatics** [comment]
What is the best way to add retry mechanism in case of server stream call for `Connect Failed` error. Do you have any high level code ? 
Is there way I can listen to connect-errors and re-create client ?
How to close old channels ?

**Comment by lakshmantgld** [comment]
Any solutions for the above problem? I am getting the same error:
`{ [Error: Connect Failed] code: 14, metadata: Metadata { _internal_repr: {} } }`

**node.js:** v4.8.4
**O.S:** mac OS
I am trying the greeter example from `gRPC/examples/node`. I have tried multiple times, I am encountering the same error. The example works properly in other machines (linux with same node version). Here is the server and client side code.

`greeter_server.js`

```js
var PROTO_PATH = __dirname + '/../../protos/helloworld.proto';

var grpc = require('grpc');
var hello_proto = grpc.load(PROTO_PATH).helloworld;

/**
 * Implements the SayHello RPC method.
 */
function sayHello(call, callback) {
  callback(null, {message: 'Hello ' + call.request.name});
}

/**
 * Starts an RPC server that receives requests for the Greeter service at the
 * sample server port
 */
function main() {
  var server = new grpc.Server();
  server.addProtoService(hello_proto.Greeter.service, {sayHello: sayHello});
  server.bind('localhost:50051', grpc.ServerCredentials.createInsecure());
  server.start();
}

main();
```

`greeter_client.js`

```js
var PROTO_PATH = __dirname + '/../../protos/helloworld.proto';

var grpc = require('grpc');
var hello_proto = grpc.load(PROTO_PATH).helloworld;

function main() {
  var client = new hello_proto.Greeter('localhost:50051',
                                       grpc.credentials.createInsecure());
  var user;
  if (process.argv.length >= 3) {
    user = process.argv[2];
  } else {
    user = 'world';
  }
  client.sayHello({name: user}, function(err, response) {
    if (err) {
      console.log(err);
    }

    console.log('Greeting:', response);
  });
}

main();
```

Any idea what am I missing?

**Comment by murgatroid99** [comment]
@lakshmantgld Are you just running the server and client, or are you doing server restarts or something as described in the original question? What version of gRPC are you using (you should be able to see this in `npm ls`)?

The only way I was able to reproduce this was by running the client while the server was not running.

**Comment by lakshmantgld** [comment]
Thank you @murgatroid99 for your response. Yes I got this error when the server was running. In my case the solution was to use `sudo`. I think I messed up my user/root accounts in mac OS X. 

When I tried `sudo node greeter_client.js`, It was able to connect with the running server. The example worked like a charm. Sorry for the inconvenience caused. Thank you.
