### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by zsxgb** [grpc/grpc#11673]
I want to use grpc overnight between node and py, so I learned examples of node and py. I found that node / static_codegen / route_guide and / node / static_codegen / route_guide are problematic.

The problem seems to be because I used the version of node v8. In line 231 at fs.readFile (path.resolve (argv.db_path), function (err, data) {
Here is an error, but I do not know how to deal with.

Does anyone have to tell me how to do it

Server#addProtoService is deprecated. Use addService instead
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at Object.<anonymous> (/home/zsx/桌面/GPR-max/grpc/examples/node/dynamic_codegen/route_guide/route_guide_server.js:231:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

**Comment by zsxgb** [comment]
I found that I did not see the tutorial, it was a low level error

**Comment by haio** [comment]
@zsxgb You should specify a db_path,
`node route_guide_client.js --db_path .`

**Comment by hcaseyal** [comment]
Closing because user has not responded in over a month.
