### ISSUE TITLE
nodejs/windows: prebuilt npm package missing .pdb file (debug symbols)

### ISSUE THREAD

**Issue by a-teammate** [grpc/grpc#11688]
### What version of gRPC and what language are you using?
 
grpc-node v 1.4.1
 
### What operating system (Linux, Windows, …) and version?
 
Windows 8.1 Pro (Windows_NT 6.3.9600) 
Visual Studio 2015 Community Edition
Python v2.7.12
nodejs version 6.9.4

### What did you do?

My gRPC node.js native module crashed. _(This issue is not about **why** it crashed, just that it did)_

I catched the error with https://github.com/ddopson/node-segfault-handler by registering a handler for crashes in native modules.
That helper printed the stacktrace.

### What did you expect to see?

 ```
Native Module Crashed!
PID 4932 received SIGSEGV for address: 0xc9e885b7
SymInit: Symbol-SearchPath: '.;E:\weitere-Dokumente\Git\code2\flex;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\w
ebsymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'madoe'
OS-Version: 6.3.9600 () 0x100-0x1
e:\weitere-dokumente\git\code2\flex\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
e:\weitere-dokumente\git\code2\flex\node_modules\segfault-handler\src\segfault-handler.cpp (116): segfault_handler
00007FFFE569BAF9 (ntdll): (filename not available): RtlLookupFunctionEntry
00007FFFE5699033 (ntdll): (filename not available): RtlRaiseException
00007FFFE56EC9EE (ntdll): (filename not available): KiUserExceptionDispatcher
e:\weitere-dokumente\git\code2\flex\node_modules\grpc\src\core\ext\filters\client_channel\channel_connectivity.c (49): grpc_channel_check_connectivity_state
e:\weitere-dokumente\git\code2\flex\node_modules\grpc\src\node\ext\channel.cc (251): grpc::node::Channel::GetConnectivityState
e:\weitere-dokumente\git\code2\flex\node_modules\nan\nan_callbacks_12_inl.h (175): Nan::imp::FunctionCallbackWrapper
00007FF762E2A77A (node): (filename not available): v8::experimental::FastAccessorBuilder::Call
00007FF762C5A512 (node): (filename not available): v8::Testing::DeoptimizeAll
00007FF762C538D3 (node): (filename not available): v8::Testing::DeoptimizeAll
00007FF762C53844 (node): (filename not available): v8::Testing::DeoptimizeAll
```
 (notice the correct stacktrace giving insights where in grpc this thing crashed)

### What did you see instead?
```
Native Module Crashed!
PID 4932 received SIGSEGV for address: 0xc9e885b7
SymInit: Symbol-SearchPath: '.;E:\weitere-Dokumente\Git\code2\flex;C:\Program Files\nodejs;C:\Windows;C:\Windows\system32;SRV*C:\w
ebsymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'madoe'
OS-Version: 6.3.9600 () 0x100-0x1
e:\weitere-dokumente\git\code2\flex\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
e:\weitere-dokumente\git\code2\flex\node_modules\segfault-handler\src\segfault-handler.cpp (116): segfault_handler
00007FFFE569BAF9 (ntdll): (filename not available): RtlLookupFunctionEntry
00007FFFE5699033 (ntdll): (filename not available): RtlRaiseException
00007FFFE56EC9EE (ntdll): (filename not available): KiUserExceptionDispatcher
00007FFFCF808A37 (grpc_node): (filename not available): (function name not available)
00007FFFCF7F9458 (grpc_node): (filename not available): (function name not available)
00007FFFCF7F17CC (grpc_node): (filename not available): (function name not available) 
00007FF762E2A77A (node): (filename not available): v8::experimental::FastAccessorBuilder::Call
00007FF762C5A512 (node): (filename not available): v8::Testing::DeoptimizeAll
00007FF762C538D3 (node): (filename not available): v8::Testing::DeoptimizeAll
00007FF762C53844 (node): (filename not available): v8::Testing::DeoptimizeAll
```
Due to missing debug symbols it was not able to find out where in grpc_node we crashed.

### Did you resolve that error?

Yes, the missing .pdb file appeared after building with `node-pre-gyp rebuild --build-from-sources` inside grpcs place in the node_modules folder.

### Anything else we should know about your project / environment?

```
Jul 5 15:06:57 flex.instances.Connector.localhost.31418.6j8i[4932] DEBUG: Connecting to the gRPC server on localhost:31418
Jul 5 15:06:57 flex.instances.Connector.localhost.31418.6j8i[4932] DEBUG: Created a new GRPC client
Jul 5 15:06:59 flex.instances.Connector.localhost.31418.6j8i[4932] ERROR: Synchronize ERROR
Jul 5 15:06:59 flex.instances.Connector.localhost.31418.6j8i[4932] ERROR: Connect Failed
  err: Error: Connect Failed
      at ClientDuplexStream._emitStatusIfDone (.\node_modules\grpc\src\node\src\client.js:270:19)
      at ClientDuplexStream._readsDone (.\node_modules\grpc\src\node\src\client.js:236:8)
      at readCallback (.\node_modules\grpc\src\node\src\client.js:298:12)
Jul 5 15:06:59 flex.instances.Connector.localhost.31418.6j8i[4932] ERROR: Endpoint read failed
Jul 5 15:06:59 flex.instances.Connector.localhost.31418.6j8i[4932] ERROR:
  code: 14
  details: "Connect Failed"
  metadata: {"_internal_repr":{}}
Jul 5 15:06:59 flex.instances.Connector.localhost.31418.6j8i[4932] INFO:  Closing GRPC connection
```
was the output previous to this error, ill probably post that in #11177 as that seems the corresponding issue for the error which caused the crash.

**Comment by kpayson64** [comment]
Is this still an issue on 1.7?

**Comment by murgatroid99** [comment]
Yes, we haven't changed this yet.

**Comment by murgatroid99** [comment]
We don't plan to do this.
