### ISSUE TITLE
tests.cloud_to_prod:default:csharpcoreclr:ping_pong interop failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#11721]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15202/consoleFull

```
2017-07-07 01:31:16,505 D0707 01:31:13.404161 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0707 01:31:13.462920 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running ping_pong

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unknown, Detail="")) ---> Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunPingPongAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)

2017-07-07 01:31:16,505 FAILED: cloud_to_prod:default:csharpcoreclr:ping_pong [ret=139, pid=20715]
```

**Comment by kpayson64** [comment]
Hasn't been referenced since Jul, to close.
