### ISSUE TITLE
Ruby Concurrent Requests

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#11776]
Hello, we are unable to make more than 4 concurrent requests using the Ruby client. When more than 4 concurrent requests are made the client seems to lock up until the requests time out. We are currently in an effort to add more concurrency in the Google Cloud Pub/Sub Ruby library, and while this seems to be working well while making concurrent streaming API calls, we are seeing the grpc client lock up while concurrently calling non-streaming APIs under moderate load.

To illustrate, I have included a ruby script that attempts to benchmark the performance differences between making sequential and concurrent requests. The default number of requests is 4, but you can pass in an argument to change the number of requests. This script will lock up and eventually time out when passing in a number larger than 4. Here is the output when running 4 and 6 concurrent requests:

```
$ ruby benchmark_gapic.rb 4
       user     system      total        real
sequential#<Google::Pubsub::V1::PublishResponse:0x007faed3afb160>
#<Google::Pubsub::V1::PublishResponse:0x007faed3ad8660>
#<Google::Pubsub::V1::PublishResponse:0x007faed3aa9bd0>
#<Google::Pubsub::V1::PublishResponse:0x007faed3a7b118>
  0.390000   0.500000   0.890000 ( 16.913990)
concurrent#<Google::Pubsub::V1::PublishResponse:0x007faed1845b20>
#<Google::Pubsub::V1::PublishResponse:0x007faed18a7898>
#<Google::Pubsub::V1::PublishResponse:0x007faed19372b8>
#<Google::Pubsub::V1::PublishResponse:0x007faed1955178>
  0.390000   0.540000   0.930000 ( 11.678385)

$ ruby benchmark_gapic.rb 6
       user     system      total        real
sequential#<Google::Pubsub::V1::PublishResponse:0x007ffd71951f48>
#<Google::Pubsub::V1::PublishResponse:0x007ffd71923418>
#<Google::Pubsub::V1::PublishResponse:0x007ffd719009b8>
#<Google::Pubsub::V1::PublishResponse:0x007ffd718d1f28>
#<Google::Pubsub::V1::PublishResponse:0x007ffd6f847488>
#<Google::Pubsub::V1::PublishResponse:0x007ffd6f8979d8>
  0.570000   0.700000   1.270000 ( 18.899312)
concurrent/Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:357:in `rescue in block (2 levels) in retryable': GaxError Retry total timeout exceeded with exception, caused by 4:Deadline Exceeded (Google::Gax::RetryError)
	from /Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:343:in `block (2 levels) in retryable'
	from /Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:342:in `loop'
	from /Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:342:in `block in retryable'
	from /Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:262:in `block in catch_errors'
	from /Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:224:in `block in create_api_call'
	from /Users/blowmage/.gem/repos/gcloud-ruby/gems/google-gax-0.8.4/lib/google/gax/api_callable.rb:250:in `block in create_api_call'
	from /Users/blowmage/google/codez/gcloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb:326:in `publish'
	from benchmark_gapic.rb:56:in `block (4 levels) in <main>'
```

Here is the script:

```ruby
$stdout.sync = true
Thread.abort_on_exception = true

require "google/cloud/pubsub/v1"
require "grpc"
require "googleauth"
require "securerandom"
require "benchmark"

# This will benchmark publishing 1 million 4KB messages
# using the previous batch method, and the new async publisher

project = ENV["GOOGLE_CLOUD_PROJECT"] || "<ENTER-PROJECT-ID-HERE>"
keyfile = ENV["GOOGLE_CLOUD_KEYFILE"] || "<ENTER-KEYFILE-PATH-HERE>"

host = Google::Cloud::Pubsub::V1::PublisherClient::SERVICE_ADDRESS
chan_args = { "grpc.max_send_message_length"    => -1,
              "grpc.max_receive_message_length" => -1 }
auth = Google::Auth::ServiceAccountCredentials.make_creds \
  json_key_io: File.open(keyfile, mode: "r"),
  scope: Google::Cloud::Pubsub::V1::PublisherClient::ALL_SCOPES
chan_creds = GRPC::Core::ChannelCredentials.new.compose \
  GRPC::Core::CallCredentials.new(auth.updater_proc)
channel = GRPC::Core::Channel.new host, chan_args, chan_creds
pub_client = Google::Cloud::Pubsub::V1::PublisherClient.new channel: channel

topic_name = "loadtest"
topic_path = Google::Cloud::Pubsub::V1::PublisherClient.topic_path project, topic_name
topic_grpc = begin
               pub_client.get_topic topic_path
             rescue Google::Gax::GaxError => e
               raise e unless e.cause.code == 5
               pub_client.create_topic topic_path
             end

msg_data = SecureRandom.random_bytes 4*1024
messages = 1000.times.map { Google::Pubsub::V1::PubsubMessage.new data: msg_data }

n = (ARGV.first || 4).to_i

Benchmark.bm do |bm|
  bm.report "sequential" do
    # runs the publish requests synchronously
    responses = n.times.map do
      pub_response = pub_client.publish topic_path, messages
      puts pub_response # uncomment to see when recieved
      pub_response
    end
    # puts responses.inspect
  end

  bm.report "concurrent" do
    # runs the publish requests asynchronously
    threads = n.times.map do
      Thread.new do
        pub_response = pub_client.publish topic_path, messages
        puts pub_response # uncomment to see when recieved
        pub_response
      end
    end
    responses = threads.map &:value
    # puts responses.inspect
  end
end
```

This script is using the GAPIC layer to make the GRPC calls. I can rewrite it to make the calls on the GRPC stub directly, but the GAPIC layer doesn't look to be doing anything to prevent concurrent calls.

**Comment by blowmage** [comment]
For whatever reason, the streaming APIs don't seem to have this issue. We can open 16 streaming connections and push/pull from them concurrently with no problem.

**Comment by blowmage** [comment]
It looks like this is an issue with the GAPIC layer after all. I rewrote the script to make the calls directly on the GRPC stub and was able to make more than 4 requests concurrently:

```
$ ruby benchmark_grpc.rb 4
       user     system      total        real
sequential#<Google::Pubsub::V1::PublishResponse:0x007ff0818f8530>
#<Google::Pubsub::V1::PublishResponse:0x007ff0818c9dc0>
#<Google::Pubsub::V1::PublishResponse:0x007ff08189b6f0>
#<Google::Pubsub::V1::PublishResponse:0x007ff081879050>
  0.340000   0.290000   0.630000 ( 12.599871)
concurrent#<Google::Pubsub::V1::PublishResponse:0x007ff07f844aa0>
#<Google::Pubsub::V1::PublishResponse:0x007ff07f8a48b0>
#<Google::Pubsub::V1::PublishResponse:0x007ff080052328>
#<Google::Pubsub::V1::PublishResponse:0x007ff080070210>
  0.390000   0.520000   0.910000 ( 11.779743)
$ ruby benchmark_grpc.rb 6
       user     system      total        real
sequential#<Google::Pubsub::V1::PublishResponse:0x007fb64a8c8888>
#<Google::Pubsub::V1::PublishResponse:0x007fb64a89a0f0>
#<Google::Pubsub::V1::PublishResponse:0x007fb64a86ba20>
#<Google::Pubsub::V1::PublishResponse:0x007fb64a849380>
#<Google::Pubsub::V1::PublishResponse:0x007fb648046c98>
#<Google::Pubsub::V1::PublishResponse:0x007fb648096720>
  0.580000   0.700000   1.280000 ( 18.323580)
concurrent#<Google::Pubsub::V1::PublishResponse:0x007fb64803f290>
#<Google::Pubsub::V1::PublishResponse:0x007fb6480cfa48>
#<Google::Pubsub::V1::PublishResponse:0x007fb6490422f0>
#<Google::Pubsub::V1::PublishResponse:0x007fb6490601d8>
#<Google::Pubsub::V1::PublishResponse:0x007fb649092070>
#<Google::Pubsub::V1::PublishResponse:0x007fb6490c3f08>
  0.650000   0.900000   1.550000 ( 17.147526)
$ ruby benchmark_grpc.rb 8
       user     system      total        real
sequential#<Google::Pubsub::V1::PublishResponse:0x007f80ec9e0178>
#<Google::Pubsub::V1::PublishResponse:0x007f80ec9b1a08>
#<Google::Pubsub::V1::PublishResponse:0x007f80ec983310>
#<Google::Pubsub::V1::PublishResponse:0x007f80ec960c98>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb0465c8>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb094ef8>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb1372e8>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb154c58>
  0.770000   0.940000   1.710000 ( 24.771185)
concurrent#<Google::Pubsub::V1::PublishResponse:0x007f80eb03dab8>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb0bc408>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb15c430>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb19e2b8>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb1bc1a0>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb1ee038>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb21fed0>
#<Google::Pubsub::V1::PublishResponse:0x007f80eb23ddb8>
  0.850000   1.230000   2.080000 ( 22.813085)
$ ruby benchmark_grpc.rb 16
       user     system      total        real
sequential#<Google::Pubsub::V1::PublishResponse:0x007ffc809e1158>
#<Google::Pubsub::V1::PublishResponse:0x007ffc809b29c0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc80990348>
#<Google::Pubsub::V1::PublishResponse:0x007ffc80961c50>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f047580>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f084fc0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f1242f0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f155c10>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f187530>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f1a4ea0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f1d67c0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f02f868>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f08cc98>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f16d2c0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f1cf538>
#<Google::Pubsub::V1::PublishResponse:0x007ffc7f205778>
  1.500000   1.820000   3.320000 ( 50.884646)
concurrent#<Google::Pubsub::V1::PublishResponse:0x007ffc82dd3340>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82dc00d8>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82da9018>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d92b38>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d801b8>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d697d8>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d4b1e8>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d389f8>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d23198>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82d01c50>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82ceb568>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82cd8508>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82cc0d90>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82cab2d8>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82c917c0>
#<Google::Pubsub::V1::PublishResponse:0x007ffc82c7b128>
  1.900000   3.490000   5.390000 ( 45.391527)
```

Here is the updated script. It still creates the GAPIC client, but uses the GRPC stub from the client instead.

```ruby
$stdout.sync = true
Thread.abort_on_exception = true

require "google/cloud/pubsub/v1"
require "grpc"
require "googleauth"
require "securerandom"
require "benchmark"

# This will benchmark publishing 1 million 4KB messages
# using the previous batch method, and the new async publisher

project = ENV["GOOGLE_CLOUD_PROJECT"] || "<ENTER-PROJECT-ID-HERE>"
keyfile = ENV["GOOGLE_CLOUD_KEYFILE"] || "<ENTER-KEYFILE-PATH-HERE>"

host = Google::Cloud::Pubsub::V1::PublisherClient::SERVICE_ADDRESS
chan_args = { "grpc.max_send_message_length"    => -1,
              "grpc.max_receive_message_length" => -1 }
auth = Google::Auth::ServiceAccountCredentials.make_creds \
  json_key_io: File.open(keyfile, mode: "r"),
  scope: Google::Cloud::Pubsub::V1::PublisherClient::ALL_SCOPES
chan_creds = GRPC::Core::ChannelCredentials.new.compose \
  GRPC::Core::CallCredentials.new(auth.updater_proc)
channel = GRPC::Core::Channel.new host, chan_args, chan_creds
pub_client = Google::Cloud::Pubsub::V1::PublisherClient.new channel: channel
pub_stub = pub_client.publisher_stub

topic_name = "loadtest"
topic_path = Google::Cloud::Pubsub::V1::PublisherClient.topic_path project, topic_name
topic_grpc = begin
               pub_client.get_topic topic_path
             rescue Google::Gax::GaxError => e
               raise e unless e.cause.code == 5
               pub_client.create_topic topic_path
             end

msg_data = SecureRandom.random_bytes 4*1024
messages = 1000.times.map { Google::Pubsub::V1::PubsubMessage.new data: msg_data }
pub_request = Google::Pubsub::V1::PublishRequest.new topic: topic_path, messages: messages

n = (ARGV.first || 4).to_i

Benchmark.bm do |bm|
  bm.report "sequential" do
    # runs the publish requests synchronously
    responses = n.times.map do
      pub_response = pub_stub.publish pub_request
      puts pub_response # uncomment to see when recieved
      pub_response
    end
    # puts responses.inspect
  end

  bm.report "concurrent" do
    # runs the publish requests asynchronously
    threads = n.times.map do
      Thread.new do
        pub_response = pub_stub.publish pub_request
        puts pub_response # uncomment to see when recieved
        pub_response
      end
    end
    responses = threads.map &:value
    # puts responses.inspect
  end
end
```

Apologies for not verifying this before opening this issue.
