### ISSUE TITLE
Flake in ruby_linux_dbg_native.tools/run_tests/helper_scripts/run_ruby.sh

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11911]
Noticed in tests of https://github.com/grpc/grpc/pull/11849#pullrequestreview-51603342

The exception looks like:

```
Failures:

  1) ClientStub #server_streamer via a call operation behaves like server streaming the call terminates when there is an unmarshalling error
     Failure/Error: replys.each { |r| c.remote_send(r) }

     GRPC::Core::CallError:
       call#run_batch failed somehow
     Shared Example Group: "server streaming" called from ./src/ruby/spec/generic/client_stub_spec.rb:520
     # ./src/ruby/lib/grpc/generic/active_call.rb:185:in `run_batch'
     # ./src/ruby/lib/grpc/generic/active_call.rb:185:in `remote_send'
     # ./src/ruby/spec/generic/client_stub_spec.rb:683:in `block (2 levels) in run_server_streamer'
     # ./src/ruby/spec/generic/client_stub_spec.rb:683:in `each'
     # ./src/ruby/spec/generic/client_stub_spec.rb:683:in `block in run_server_streamer'
     # ./src/ruby/spec/generic/client_stub_spec.rb:22:in `call'
     # ./src/ruby/spec/generic/client_stub_spec.rb:22:in `block in wakey_thread'
     # /usr/local/rvm/gems/ruby-2.1.10/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `call'
     # /usr/local/rvm/gems/ruby-2.1.10/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

```

It looks like this is due to a race in a recently added test (it starts reproducing frequently at e8e05f90a40c59, but it seems that commit e8e05f90a40c59 is only exposing the pre-existing race in that test).

**Comment by apolcyn** [comment]
should be fixed by https://github.com/grpc/grpc/pull/11913
