### ISSUE TITLE
cloud_to_prod_auth:default:javaokhttp:compute_engine_creds flaked on CI

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#11974]
https://sponge.corp.google.com/target?id=0e66886a-43fe-4afe-9fcb-914d183d30da&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

Jul 27, 2017 4:15:50 PM io.grpc.internal.ChannelExecutor drain
WARNING: Runnable threw exception in ChannelExecutor
java.lang.IllegalStateException: ConnectivityStateManager is already disabled
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.ConnectivityStateManager.gotoState(ConnectivityStateManager.java:66)
	at io.grpc.internal.ManagedChannelImpl$5.run(ManagedChannelImpl.java:465)
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:72)
	at io.grpc.internal.DelayedClientTransport.shutdown(DelayedClientTransport.java:211)
	at io.grpc.internal.ManagedChannelImpl.shutdown(ManagedChannelImpl.java:469)
	at io.grpc.internal.ManagedChannelImpl.shutdown(ManagedChannelImpl.java:68)
	at io.grpc.testing.integration.AbstractInteropTest.tearDown(AbstractInteropTest.java:242)
	at io.grpc.testing.integration.TestServiceClient.tearDown(TestServiceClient.java:170)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:67)

Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.AbstractInteropTest.computeEngineCreds(AbstractInteropTest.java:1281)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:222)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:181)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:65)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at io.grpc.okhttp.OkHttpProtocolNegotiator.negotiate(OkHttpProtocolNegotiator.java:88)
	at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
	at io.grpc.okhttp.OkHttpClientTransport$1.run(OkHttpClientTransport.java:416)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Shutting down

2017-07-27 09:15:51,157 FAILED: cloud_to_prod_auth:default:javaokhttp:compute_engine_creds [ret=1, pid=21387]

**Comment by adelez** [comment]
Duplicate of #10763
