### ISSUE TITLE
Flake: Kokoro - cloud_to_prod:gateway_v4:csharpcoreclr:server_streaming

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11994]
Possibly similar to https://github.com/grpc/grpc/issues/11967, but filing specific for C#

```
2017-07-28 17:47:09,788 D0729 00:47:08.969546 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0729 00:47:09.020447 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running server_streaming

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unavailable, Detail="Connect Failed")) ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Core.Utils.AsyncStreamExtensions.<ToListAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunServerStreamingAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)

2017-07-28 17:47:09,789 FAILED: cloud_to_prod:gateway_v4:csharpcoreclr:server_streaming [ret=139, pid=10193]
```

**Comment by adelez** [comment]
Please post the link to the test result if you still have it.

**Comment by apolcyn** [comment]
sponge log is in https://sponge.corp.google.com/target?id=4134491f-6fad-4e3b-8273-a00062fdbd18&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS
- from (https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/194/)

**Comment by jtattermusch** [comment]
That looks like just a random flake to me (that status code is generated by C core, so it's unlikely it's C# specific and other languages seem to be doing fine).

**Comment by jtattermusch** [comment]
Closing in favor of https://github.com/grpc/grpc/issues/12261
