### ISSUE TITLE
Kokoro: All cloud to prod tests sometimes fail with "502:Bad Gateway (GRPC::Unavailable)"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12027]
https://sponge.corp.google.com/target?id=23753e32-f6e2-4b1c-9e22-49f95f760fa1&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

```
2017-08-01 04:33:21,776 /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:502:Bad Gateway (GRPC::Unavailable)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:171:in `attach_status_results_and_complete_call'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:363:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/client_stub.rb:152:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from src/ruby/pb/test/client.rb:262:in `empty_unary'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-08-01T11:33:01.755697 #68]  INFO -- : ... connecting securely to 216.239.32.254:443

2017-08-01 04:33:21,776 FAILED: cloud_to_prod:default:ruby:empty_unary [ret=1, pid=31714]
```

```
2017-08-01 04:33:41,639 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 98, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 184, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 200, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 126, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 456, in test_interoperability
    _ping_pong(stub)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 234, in _ping_pong
    response = next(response_iterator)
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 351, in next
    return self._next()
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 342, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, 502:Bad Gateway)>

2017-08-01 04:33:41,639 FAILED: cloud_to_prod:default:python:ping_pong [ret=1, pid=706]
```

```

Failure Gradle is no longer run automatically. Make sure to run './gradlew installDist -PskipCodegen=true' or './gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any changes. -PskipCodegen=true is optional, but requires less setup. [jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar Running test oauth2_auth_token [jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker [jetty-alpn-agent] Replacing: sun/security/ssl/ServerHandshaker [jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions [jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType [jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2 Aug 01, 2017 11:35:46 AM io.grpc.internal.ChannelExecutor drain WARNING: Runnable threw exception in ChannelExecutor java.lang.IllegalStateException: ConnectivityStateManager is already disabled 	at com.google.common.base.Preconditions.checkState(Preconditions.java:174) 	at io.grpc.internal.ConnectivityStateManager.gotoState(ConnectivityStateManager.java:66) 	at io.grpc.internal.ManagedChannelImpl$5.run(ManagedChannelImpl.java:465) 	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:72) 	at io.grpc.internal.DelayedClientTransport.shutdown(DelayedClientTransport.java:211) 	at io.grpc.internal.ManagedChannelImpl.shutdown(ManagedChannelImpl.java:469) 	at io.grpc.internal.ManagedChannelImpl.shutdown(ManagedChannelImpl.java:68) 	at io.grpc.testing.integration.AbstractInteropTest.tearDown(AbstractInteropTest.java:244) 	at io.grpc.testing.integration.TestServiceClient.tearDown(TestServiceClient.java:170) 	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:67)  Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210) 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191) 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124) 	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473) 	at io.grpc.testing.integration.AbstractInteropTest.oauth2AuthToken(AbstractInteropTest.java:1526) 	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:257) 	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:181) 	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:65) Shutting down
--

```

**Comment by jtattermusch** [comment]
Might be related to https://github.com/grpc/grpc/issues/9504

**Comment by jtattermusch** [comment]
Same on jenkins: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15804/#showFailuresLink

**Comment by jtattermusch** [comment]
It looks like the tests are not failing anymore as of now, but it would still be interesting to understand what when wrong.

**Comment by ncteisen** [comment]
There is an issue with the borgcron job that schedules the internal test service. I noticed it last night (because of my noogler project!) and manually restarted it.
