### ISSUE TITLE
Node performance data not available for v1.4.x release

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#12079]
In https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_released/344/console:

```
+ node src/node/performance/worker.js --benchmark_impl=grpc --driver_port=10200
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/jenkins/performance_workspace/grpc/src/node/extension_binary/grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jenkins/performance_workspace/grpc/src/node/src/grpc_extension.js:45:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

2017-08-03 04:25:28,550 FAILED: qps_worker_node_0 [ret=1, pid=4573]
```

It's working in master, so it seems like a backport would fix this. Perhaps #11627 fixes this?

**Comment by murgatroid99** [comment]
Is this still happening?

**Comment by matt-kwong** [comment]
We're now on v1.6.x and I don't see this happening in the latest performance test on that branch. This is fine to close.
