### ISSUE TITLE
FAILURE: tests.cloud_to_prod_auth:default:java:per_rpc_creds

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12106]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15877/

seen in PR: https://github.com/grpc/grpc/pull/12066

```
2017-08-03 22:32:59,213 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar
Running test per_rpc_creds
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/ServerHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
[jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.AbstractInteropTest.oauth2AuthToken(AbstractInteropTest.java:1527)
	at io.grpc.testing.integration.AbstractInteropTest.perRpcCreds(AbstractInteropTest.java:1542)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:264)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:181)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:65)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Shutting down

2017-08-03 22:32:59,213 FAILED: cloud_to_prod_auth:default:java:per_rpc_creds [ret=1, pid=5379]
```

**Comment by jtattermusch** [comment]
Seen here: https://github.com/grpc/grpc/pull/12264 (per_rpc_creds and jwt_token_creds)

**Comment by ericgribkoff** [comment]
In the test failures reported by @jtattermusch, the Python client also failed with an UNAVAILABLE status code when attempting to reach the prod server, for both per_rpc_creds and jwt_token_creds (@jtattermusch did you open a separate issue for the Python failures? I didn't see one on the PR). 

Along with the connectivity issues reported in cloud_to_prod tests to gateway_v4 in https://github.com/grpc/grpc/issues/12261, it seems like the problem is on the network or server-side, rather than a language-specific issue.
