### ISSUE TITLE
Windows benchmark data not getting uploaded to perf dashboard.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12148]
Dashboard says "no data"
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

Seems like port_server.py might be the issue
```
02:50:42 2017-08-10 09:50:42,650 2017-08-10 09:35:41,854 failed to detect port server
02:50:42 Traceback (most recent call last):
02:50:42   File "/home/jenkins/performance_workspace/grpc/tools/run_tests/python_utils/start_port_server.py", line 38, in start_port_server
02:50:42     _PORT_SERVER_PORT).read())
02:50:42   File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
02:50:42     return opener.open(url)
02:50:42   File "/usr/lib/python2.7/urllib.py", line 213, in open
02:50:42     return getattr(self, name)(url)
02:50:42   File "/usr/lib/python2.7/urllib.py", line 350, in open_http
02:50:42     h.endheaders(data)
02:50:42   File "/usr/lib/python2.7/httplib.py", line 1049, in endheaders
02:50:42     self._send_output(message_body)
02:50:42   File "/usr/lib/python2.7/httplib.py", line 893, in _send_output
02:50:42     self.send(msg)
02:50:42   File "/usr/lib/python2.7/httplib.py", line 855, in send
02:50:42     self.connect()
02:50:42   File "/usr/lib/python2.7/httplib.py", line 832, in connect
02:50:42     self.timeout, self.source_address)
02:50:42   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
02:50:42     raise err
02:50:42 IOError: [Errno socket error] [Errno 111] Connection refused
02:50:42 2017-08-10 09:35:41,979 starting port_server, with log file /tmp/tmpNZUVMS
02:50:42 Traceback (most recent call last):
02:50:42   File "tools/run_tests/start_port_server.py", line 29, in <module>
02:50:42     start_port_server.start_port_server()
02:50:42   File "/home/jenkins/performance_workspace/grpc/tools/run_tests/python_utils/start_port_server.py", line 78, in start_port_server
02:50:42     close_fds=True)
02:50:42   File "/usr/lib/python2.7/subprocess.py", line 675, in __init__
02:50:42     raise ValueError("creationflags is only supported on Windows "
02:50:42 ValueError: creationflags is only supported on Windows platforms
02:50:42 
02:50:42 2017-08-10 09:50:42,650 FAILED: qps_worker_csharp_0 [ret=1, pid=3071]
```

```
02:50:42 2017-08-10 09:50:42,650 2017-08-10 09:35:38,831 failed to detect port server
02:50:42 Traceback (most recent call last):
02:50:42   File "/home/jenkins/performance_workspace/grpc/tools/run_tests/python_utils/start_port_server.py", line 38, in start_port_server
02:50:42     _PORT_SERVER_PORT).read())
02:50:42   File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
02:50:42     return opener.open(url)
02:50:42   File "/usr/lib/python2.7/urllib.py", line 213, in open
02:50:42     return getattr(self, name)(url)
02:50:42   File "/usr/lib/python2.7/urllib.py", line 350, in open_http
02:50:42     h.endheaders(data)
02:50:42   File "/usr/lib/python2.7/httplib.py", line 1049, in endheaders
02:50:42     self._send_output(message_body)
02:50:42   File "/usr/lib/python2.7/httplib.py", line 893, in _send_output
02:50:42     self.send(msg)
02:50:42   File "/usr/lib/python2.7/httplib.py", line 855, in send
02:50:42     self.connect()
02:50:42   File "/usr/lib/python2.7/httplib.py", line 832, in connect
02:50:42     self.timeout, self.source_address)
02:50:42   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
02:50:42     raise err
02:50:42 IOError: [Errno socket error] [Errno 111] Connection refused
02:50:42 2017-08-10 09:35:38,831 starting port_server, with log file /tmp/tmpk1H3jq
02:50:42 Traceback (most recent call last):
02:50:42   File "tools/run_tests/start_port_server.py", line 29, in <module>
02:50:42     start_port_server.start_port_server()
02:50:42   File "/home/jenkins/performance_workspace/grpc/tools/run_tests/python_utils/start_port_server.py", line 78, in start_port_server
02:50:42     close_fds=True)
02:50:42   File "/usr/lib/python2.7/subprocess.py", line 675, in __init__
02:50:42     raise ValueError("creationflags is only supported on Windows "
02:50:42 ValueError: creationflags is only supported on Windows platforms
02:50:42 
02:50:42 2017-08-10 09:50:42,650 FAILED: qps_worker_csharp_1 [ret=1, pid=3072]
```

```
03:17:42 RUNNING SCENARIO: csharp_generic_async_streaming_qps_unconstrained_insecure
03:17:42 I0810 10:05:42.707294643    3595 driver.cc:266]              Starting server on grpc-performance-windows1:10100 (worker #0)
03:17:42 I0810 10:05:42.707525037    3595 ev_epollsig_linux.c:71]     epoll engine will be using signal: 40
03:17:42 D0810 10:05:42.707537152    3595 ev_posix.c:111]             Using polling engine: epollsig
03:17:42 D0810 10:05:42.707584500    3595 dns_resolver.c:301]         Using native dns resolver
03:17:42 I0810 10:06:02.709807799    3597 subchannel.c:683]           Connect failed: {"created":"@1502359562.709733478","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359562.709707158","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:06:02.709867904    3597 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:06:02.709873264    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:06:22.710722329    3601 subchannel.c:683]           Connect failed: {"created":"@1502359582.710640908","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359582.710613859","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:06:22.710794644    3601 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:06:22.710800713    3601 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:06:42.711762004    3597 subchannel.c:683]           Connect failed: {"created":"@1502359602.711683309","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359602.711653613","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:06:42.711814188    3597 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:06:42.711819899    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:07:02.712748051    3601 subchannel.c:683]           Connect failed: {"created":"@1502359622.712672556","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359622.712643406","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:07:02.712802301    3601 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:07:02.712808430    3601 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:07:22.713756763    3597 subchannel.c:683]           Connect failed: {"created":"@1502359642.713684313","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359642.713654655","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:07:22.713809389    3597 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:07:22.713815240    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:07:42.714734395    3601 subchannel.c:683]           Connect failed: {"created":"@1502359662.714662482","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359662.714633097","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:07:42.714799185    3601 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:07:42.714806015    3601 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:08:02.715813144    3597 subchannel.c:683]           Connect failed: {"created":"@1502359682.715710346","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359682.715678502","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:08:02.715884649    3597 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:08:02.715895887    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:08:30.549750204    3601 subchannel.c:683]           Connect failed: {"created":"@1502359710.549678055","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359710.549647777","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:08:30.549810146    3601 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:08:30.549816521    3601 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:09:23.483828037    3597 subchannel.c:683]           Connect failed: {"created":"@1502359763.483742313","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359763.483682560","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:09:23.483897966    3597 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:09:23.483908759    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:10:53.946704393    3601 subchannel.c:683]           Connect failed: {"created":"@1502359853.946645665","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359853.946621064","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:10:53.946740172    3601 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:10:53.946746566    3601 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:12:42.187785694    3597 subchannel.c:683]           Connect failed: {"created":"@1502359962.187702852","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502359962.187669015","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:12:42.187864271    3597 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:12:42.187870951    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:14:26.379789820    3601 subchannel.c:683]           Connect failed: {"created":"@1502360066.379704069","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1502360066.379665280","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":110}],"target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:14:26.379859380    3601 subchannel.c:477]           Retry immediately
03:17:42 I0810 10:14:26.379866357    3601 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 I0810 10:16:36.041474133    3595 subchannel.c:683]           Connect failed: {"created":"@1502360196.041387586","description":"Failed to connect to remote host: OS Error","errno":110,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":205,"os_error":"Connection timed out","syscall":"getsockopt(SO_ERROR)","target_address":"ipv4:10.240.0.145:10100"}
03:17:42 I0810 10:16:36.041534486    3595 subchannel.c:479]           Retry in 20.427336751 seconds
03:17:42 I0810 10:16:56.469661082    3597 subchannel.c:429]           Failed to connect to channel, retrying
03:17:42 
03:17:42 2017-08-10 10:17:42,718 TIMEOUT: qps_json_driver.csharp_generic_async_streaming_qps_unconstrained_insecure [pid=3592]
```

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/4273/consoleFull

**Comment by jtattermusch** [comment]
FYI @chwarr @ lalo  (we discussed this before)
