### ISSUE TITLE
Ruby gRPC server does not stop gracefully after receiving SIGINT / SIGTERM

### ISSUE THREAD

**Issue by dylandrop** [grpc/grpc#12189]
### What version of gRPC and what language are you using?
 
Ruby, gRPC gem version: `1.4.5`

### What operating system (Linux, Windows, …) and version?
 
Mac OS X El Capitan 10.11.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

 ```
$ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
```
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```rb
require 'google/protobuf'
require 'grpc'

# The following definitions for EchoRequest, EchoReply, and EchoServer
# are taken straight from https://github.com/grpc/grpc/tree/master/src/ruby/end2end
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "echo.EchoRequest" do
    optional :request, :string, 1
  end
  add_message "echo.EchoReply" do
    optional :response, :string, 1
  end
end

module Echo
  EchoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.EchoRequest").msgclass
  EchoReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.EchoReply").msgclass
end

module Echo
  module EchoServer
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'echo.EchoServer'

      rpc :Echo, EchoRequest, EchoReply
    end

    Stub = Service.rpc_stub_class
  end
end

class EchoServerImpl < Echo::EchoServer::Service
  # say_hello implements the SayHello rpc method.
  def echo(echo_req, _)
    Echo::EchoReply.new(response: echo_req.request)
  end
end

s = GRPC::RpcServer.new

grpc_host = '0.0.0.0:50051'

begin
  s.add_http2_port(
    grpc_host,
    :this_port_is_insecure
  )
  s.handle(EchoServerImpl)
  s.run_till_terminated
rescue SignalException => e
  puts e.inspect
  s.stop
end
```

Invoked using `ruby grpc_test.rb` (the name of the file).
 
### What did you expect to see?

Upon sending a SIGTERM or SIGINT to the process, I would expect the process to exit gracefully.
 
### What did you see instead?
 
Upon sending SIGTERM:

```
$ruby grpc_test.rb 
#<SignalException: SIGTERM>
E0815 14:01:15.239863000 140735163437056 completion_queue.c:486]       assertion failed: cqd->completed_head.next == (uintptr_t)&cqd->completed_head
Abort trap: 6
```

Upon sending SIGINT:

```
$ruby grpc_test.rb 
^CInterrupt
E0815 14:00:59.510724000 140735163437056 completion_queue.c:486]       assertion failed: cqd->completed_head.next == (uintptr_t)&cqd->completed_head
Abort trap: 6
```
 
### Anything else we should know about your project / environment?

Not that I know of.

**Comment by vbalazs** [comment]
`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]`
gRPC gem version: `1.7.1`
Mac OS 10.13.1

Seems fixed, I can't see the error above.

**Comment by mehrdada** [comment]
Seen again on https://github.com/grpc/grpc/pull/13898

https://sponge.corp.google.com/invocation?tab=Kokoro&id=70c24214-1cc7-460f-ba1a-954265337f1d&searchFor=

**Comment by rurounijones** [comment]
Getting the same issue:

OS: Kubuntu 16.04 LTS Linux devbox 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Ruby: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
GRPC: 1.8.0

Doesn't close gracefully on the example greeter_server.rb

```
^C/home/jjones/.rvm/gems/ruby-2.3.6/gems/grpc-1.8.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:391:in `request_call': Interrupt
        from /home/jjones/.rvm/gems/ruby-2.3.6/gems/grpc-1.8.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:391:in `loop_handle_server_calls'
        from /home/jjones/.rvm/gems/ruby-2.3.6/gems/grpc-1.8.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:352:in `run'
        from greeter_server.rb:42:in `main'
        from greeter_server.rb:45:in `<main>'
E0106 12:15:11.923710507   11844 completion_queue.cc:510]    assertion failed: cqd->completed_head.next == (uintptr_t)&cqd->completed_head
[1]    11844 abort (core dumped)  ruby greeter_server.rb

```

**Comment by rurounijones** [comment]
Still new to grpc so not sure if this methodology is valid but built grpc locally from master and installed gem. Issue is still occuring.

OS: Kubuntu 16.04 LTS Linux devbox 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Ruby: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
GRPC: 1.9.0.dev (built from master locally)

```
^C
/home/jjones/.rvm/gems/ruby-2.3.6@ganges-product-service/gems/grpc-1.9.0.dev/src/ruby/lib/grpc/generic/rpc_server.rb:391:in `request_call': Interrupt
        from /home/jjones/.rvm/gems/ruby-2.3.6@ganges-product-service/gems/grpc-1.9.0.dev/src/ruby/lib/grpc/generic/rpc_server.rb:391:in `loop_handle_server_calls'
        from /home/jjones/.rvm/gems/ruby-2.3.6@ganges-product-service/gems/grpc-1.9.0.dev/src/ruby/lib/grpc/generic/rpc_server.rb:352:in `run'
        from ./exe/product-service:22:in `<main>'
E0108 07:18:01.472909701     325 completion_queue.cc:490]    assertion failed: cqd->completed_head.next == (uintptr_t)&cqd->completed_head
[1]    325 abort (core dumped)  ./exe/product-service
```
