### ISSUE TITLE
INTERNAL status on cloud_to_prod_auth:gateway_v4:java:jwt_token_creds

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12208]
```
2017-08-16 14:03:50,204 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar
Running test jwt_token_creds
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.AbstractInteropTest.jwtTokenCreds(AbstractInteropTest.java:1505)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:253)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:184)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:66)
Shutting down

2017-08-16 14:03:50,205 FAILED: cloud_to_prod_auth:gateway_v4:java:jwt_token_creds [ret=1, pid=28122]
```

sponge log is in https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/1139/

**Comment by apolcyn** [comment]
also seen on `FAILED: cloud_to_prod_auth:default:javaokhttp:jwt_token_creds`.

https://sponge.corp.google.com/target?id=f86bde11-d189-4f63-ada7-5a8cba7508ef&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS
