### ISSUE TITLE
interop flake: mutiple cloud_to_prod_auth tests to gateway_v4 are failing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12261]
https://sponge.corp.google.com/target?id=a2fbd891-e1ac-4c5c-b871-126d7fdbff17&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

```
2017-08-22 23:22:32,373 /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Connect Failed (GRPC::Unavailable)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:171:in `attach_status_results_and_complete_call'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:363:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/client_stub.rb:152:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from src/ruby/pb/test/client.rb:668:in `perform_large_unary'
	from src/ruby/pb/test/client.rb:344:in `oauth2_auth_token'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-08-23T06:22:32.119941 #68]  INFO -- : ... connecting securely to 216.239.32.254:443

2017-08-22 23:22:32,373 FAILED: cloud_to_prod_auth:gateway_v4:ruby:oauth2_auth_token [ret=1, pid=27626]
2017-08-22 23:22:32,373 START: cloud_to_prod_auth:gateway_v4:java:oauth2_auth_token
2017-08-22 23:22:32,376 WAITING: ETA 5.0 sec; 21 queued, 12 jobs running, 253 complete, 2 failed
2017-08-22 23:22:32,592 /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Endpoint read failed (GRPC::Unavailable)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:171:in `attach_status_results_and_complete_call'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:363:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/client_stub.rb:152:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from src/ruby/pb/test/client.rb:668:in `perform_large_unary'
	from src/ruby/pb/test/client.rb:362:in `per_rpc_creds'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-08-23T06:22:32.025022 #68]  INFO -- : ... connecting securely to 216.239.32.254:443

2017-08-22 23:22:32,592 FAILED: cloud_to_prod_auth:gateway_v4:ruby:per_rpc_creds [ret=1, pid=27678]
2017-08-22 23:22:32,592 START: cloud_to_prod_auth:gateway_v4:java:per_rpc_creds
2017-08-22 23:22:32,596 PASSED: cloud_to_prod_auth:gateway_v4:csharpcoreclr:jwt_token_creds [time=2.0sec; retries=0:0]
2017-08-22 23:22:32,596 START: cloud_to_prod_auth:gateway_v4:python:compute_engine_creds
2017-08-22 23:22:32,600 PASSED: cloud_to_prod_auth:gateway_v4:csharpcoreclr:per_rpc_creds [time=1.7sec; retries=0:0]
2017-08-22 23:22:32,600 START: cloud_to_prod_auth:gateway_v4:python:jwt_token_creds
2017-08-22 23:22:32,604 WAITING: ETA 4.5 sec; 18 queued, 12 jobs running, 256 complete, 3 failed
2017-08-22 23:22:32,717 D0823 06:22:31.593509 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0823 06:22:31.649081 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running compute_engine_creds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unknown, Detail="")) ---> Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, CallOptions options)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.InteropClient.RunComputeEngineCreds(TestServiceClient client, String defaultServiceAccount, String oauthScope)
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)

2017-08-22 23:22:32,717 FAILED: cloud_to_prod_auth:gateway_v4:csharpcoreclr:compute_engine_creds [ret=139, pid=27072]
```

similar failures have been seen on master too 
https://sponge.corp.google.com/invocation?id=aec32e22-dca1-4412-bf7b-2de0c667db29&searchFor=

**Comment by jtattermusch** [comment]
@adelez  about 35% of the grpc_interop_toprod runs fails because of one of auth tests failing:
- compute_engine_creds
- jwt_token_creds
- per_rpc_creds

It looks like it's not language-dependent (I've seen several languages fail with the same error randomly - including javaokhttp, csharp, ruby, php, python, ...).

It would be worth investigating what's causing this.

**Comment by adelez** [comment]
@yang-g , I found the auth tests are a lot more flaky than other tests. If it's not a bug, is it possible to deflake it?

**Comment by adelez** [comment]
By the way, gateway4 uses gRPC from GFE to backend.

**Comment by jtattermusch** [comment]
@adelez  @yang-g  is any of you actively working on this? cloud_to_prod tests are pretty flaky so if you don't have cycles we need to find someone to reassign to.

CC @matt-kwong @dgquintas

**Comment by adelez** [comment]
Sorry I planned to add flake detection but it's been on my back burner...
@yang-g could you please investigate the root cause of the bug?

**Comment by yang-g** [comment]
I tried running it locally with C++ client and could not reproduce it. Also cannot view the backend logs. Will give it another try later.

**Comment by jtattermusch** [comment]
Basically a dupe of https://github.com/grpc/grpc/issues/10763.
