### ISSUE TITLE
Asan Failure: bins/asan/h2_full+trace_nosec_test resource_quota_server GRPC_POLL_STRATEGY=epollsig 

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12275]
build link on https://kokoro.corp.google.com/job/grpc/job/release/job/ubuntu/job/grpc_c_asan/227/

PR against the 1.6.x branch

sponge link on https://sponge.corp.google.com/invocation?id=95adff32-9c39-4e2c-a6fd-d0611e83e8ef&searchFor=

```
Failure
d_nosec_tests.c:440:7
    #14 0x4f700f in main /var/local/git/grpc/test/core/end2end/fixtures/h2_full+trace.c:120:5
    #15 0x7f88a6563b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60300010e880 (24 bytes)

[1m[34mIndirect leak of 17 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x8063c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x813988 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x614886 in tcp_get_peer /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:545:10
    #4 0x5ea1d2 in grpc_endpoint_get_peer /var/local/git/grpc/src/core/lib/iomgr/endpoint.c:52:10
    #5 0x76dee8 in init_transport /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:264:20
    #6 0x76d7bc in grpc_create_chttp2_transport /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:2954:3
    #7 0x800ae6 in on_handshake_done /var/local/git/grpc/src/core/ext/transport/chttp2/server/chttp2_server.c:89:11
    #8 0x5f7dcb in exec_ctx_run /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:70:3
    #9 0x5f77b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:90:9
    #10 0x71bc14 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epollsig_linux.c:1371:5
    #11 0x5f6573 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:214:10
    #12 0x665edc in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:913:23
    #13 0x66234b in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:992:10
    #14 0x59564f in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:231:9
    #15 0x4fa044 in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:440:7
    #16 0x4f700f in main /var/local/git/grpc/test/core/end2end/fixtures/h2_full+trace.c:120:5
    #17 0x7f88a6563b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x603000014410 (17 bytes)

[1m[34mIndirect leak of 17 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x8063c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x813988 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x611cf1 in grpc_tcp_create /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:609:22
    #4 0x8862a2 in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:261:9
    #5 0x5f7dcb in exec_ctx_run /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:70:3
    #6 0x5f77b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:90:9
    #7 0x71bc14 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epollsig_linux.c:1371:5
    #8 0x5f6573 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:214:10
    #9 0x665edc in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:913:23
    #10 0x66234b in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:992:10
    #11 0x59564f in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:231:9
    #12 0x4fa044 in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:440:7
    #13 0x4f700f in main /var/local/git/grpc/test/core/end2end/fixtures/h2_full+trace.c:120:5
    #14 0x7f88a6563b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x603000014680 (17 bytes)

[1m[34mIndirect leak of 17 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x8063c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x813988 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x5ff85d in grpc_resource_user_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:719:27
    #4 0x6122e6 in grpc_tcp_create /var/local/git/grpc/src/core/lib/iomgr/tcp_posix.c:631:24
    #5 0x8862a2 in on_read /var/local/git/grpc/src/core/lib/iomgr/tcp_server_posix.c:261:9
    #6 0x5f7dcb in exec_ctx_run /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:70:3
    #7 0x5f77b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:90:9
    #8 0x71bc14 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epollsig_linux.c:1371:5
    #9 0x5f6573 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:214:10
    #10 0x665edc in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:913:23
    #11 0x66234b in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:992:10
    #12 0x59564f in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:231:9
    #13 0x4fa044 in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:440:7
    #14 0x4f700f in main /var/local/git/grpc/test/core/end2end/fixtures/h2_full+trace.c:120:5
    #15 0x7f88a6563b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x603000014650 (17 bytes)

[1m[34mIndirect leak of 17 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x8063c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x813988 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x74ed6b in grpc_connectivity_state_init /var/local/git/grpc/src/core/lib/transport/connectivity_state.c:54:19
    #4 0x76e2ac in init_transport /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:273:3
    #5 0x76d7bc in grpc_create_chttp2_transport /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:2954:3
    #6 0x800ae6 in on_handshake_done /var/local/git/grpc/src/core/ext/transport/chttp2/server/chttp2_server.c:89:11
    #7 0x5f7dcb in exec_ctx_run /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:70:3
    #8 0x5f77b0 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:90:9
    #9 0x71bc14 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epollsig_linux.c:1371:5
    #10 0x5f6573 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:214:10
    #11 0x665edc in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:913:23
    #12 0x66234b in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:992:10
    #13 0x59564f in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:231:9
    #14 0x4fa044 in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:440:7
    #15 0x4f700f in main /var/local/git/grpc/test/core/end2end/fixtures/h2_full+trace.c:120:5
    #16 0x7f88a6563b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x6030000143e0 (17 bytes)

[1m[34mIndirect leak of 12 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4c29a8 in malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x8063c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x813988 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x5fd938 in grpc_resource_quota_create /var/local/git/grpc/src/core/lib/iomgr/resource_quota.c:578:28
    #4 0x59408f in resource_quota_server /var/local/git/grpc/test/core/end2end/tests/resource_quota_server.c:110:7
    #5 0x4fa044 in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_nosec_tests.c:440:7
    #6 0x4f700f in main /var/local/git/grpc/test/core/end2end/fixtures/h2_full+trace.c:120:5
    #7 0x7f88a6563b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60200000e950 (12 bytes)

SUMMARY: AddressSanitizer: 32301 byte(s) leaked in 28 allocation(s).
```

**Comment by markdroth** [comment]
I believe this is a duplicate of #11055.
