### ISSUE TITLE
bins/ubsan/h2_proxy_test payload GRPC_POLL_STRATEGY=epoll1 failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#12312]
https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_c_ubsan/2782/

```
D0828 13:48:20.590424511   13716 test_config.c:388]          test slowdown factor: sanitizer=5, fixture=1, poller=1, total=5
E0828 13:48:20.591319825   13716 ev_epoll1_linux.c:1105]     grpc epoll fd: 3
D0828 13:48:20.591335480   13716 ev_posix.c:111]             Using polling engine: epoll1
D0828 13:48:20.591483535   13716 dns_resolver.c:301]         Using native dns resolver
I0828 13:48:20.591598568   13716 payload.c:38]               Running test: test_invoke_request_response_with_payload/chttp2/fullstack+proxy
D0828 13:48:20.594113375   13716 proxy.c:89]                 PROXY ADDR:localhost:26655 BACKEND:localhost:3071
I0828 13:48:20.704649306   13716 payload.c:38]               Running test: test_invoke_10_request_response_with_payload/chttp2/fullstack+proxy
D0828 13:48:20.706449808   13716 proxy.c:89]                 PROXY ADDR:localhost:3242 BACKEND:localhost:29382
src/core/ext/transport/chttp2/transport/flow_control.c:485:41: runtime error: value 2.45784e+09 is outside the range of representable values of type 'int'
    #0 0xb70caf in grpc_chttp2_flowctl_get_bdp_action /var/local/git/grpc/src/core/ext/transport/chttp2/transport/flow_control.c:485:41
    #1 0xb3d35a in read_action_locked /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:2405:19
    #2 0x990a02 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:254:5
    #3 0x6eb3fd in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:93:17
    #4 0x9b57d4 in end_worker /var/local/git/grpc/src/core/lib/iomgr/ev_epoll1_linux.c:805:7
    #5 0x99f60e in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll1_linux.c:855:3
    #6 0x6e7912 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:214:10
    #7 0x847f14 in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:913:23
    #8 0x83f0e4 in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:991:10
    #9 0x647fb6 in cq_verify /var/local/git/grpc/test/core/end2end/cq_verifier.c:254:21
    #10 0x581e3b in request_response_with_payload /var/local/git/grpc/test/core/end2end/tests/payload.c:231:3
    #11 0x57a461 in test_invoke_10_request_response_with_payload /var/local/git/grpc/test/core/end2end/tests/payload.c:277:5
    #12 0x57a184 in payload /var/local/git/grpc/test/core/end2end/tests/payload.c:285:3
    #13 0x42f2fc in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_tests.c:432:7
    #14 0x429821 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_proxy.c:118:5
    #15 0x7f64b03a7b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #16 0x405edc in _start (/var/local/git/grpc/bins/ubsan/h2_proxy_test+0x405edc)
```

**Comment by dgquintas** [comment]
Seen again for `bins/ubsan/h2_proxy_test stream_compression_payload GRPC_POLL_STRATEGY=poll`:

```
src/core/ext/transport/chttp2/transport/flow_control.c:485:41: runtime error: value 2.77018e+09 is outside the range of representable values of type 'int'
    #0 0xb695cf in grpc_chttp2_flowctl_get_bdp_action /var/local/git/grpc/src/core/ext/transport/chttp2/transport/flow_control.c:485:41
    #1 0xb3698a in read_action_locked /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:2391:19
    #2 0x987cb2 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:254:5
    #3 0x6e722d in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:93:17
    #4 0xa5ed20 in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_poll_posix.c:1041:22
    #5 0x6e3742 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:214:10
    #6 0x841ddf in cq_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:913:23
    #7 0x838fa4 in grpc_completion_queue_next /var/local/git/grpc/src/core/lib/surface/completion_queue.c:991:10
    #8 0x648d56 in cq_verify /var/local/git/grpc/test/core/end2end/cq_verifier.c:254:21
    #9 0x60788c in request_response_with_payload /var/local/git/grpc/test/core/end2end/tests/stream_compression_payload.c:208:3
    #10 0x602061 in test_invoke_10_request_response_with_payload /var/local/git/grpc/test/core/end2end/tests/stream_compression_payload.c:294:5
    #11 0x601cf4 in stream_compression_payload /var/local/git/grpc/test/core/end2end/tests/stream_compression_payload.c:302:3
    #12 0x43120c in grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_tests.c:496:7
    #13 0x429841 in main /var/local/git/grpc/test/core/end2end/fixtures/h2_proxy.c:118:5
    #14 0x7f0516b77b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #15 0x405efc in _start (/var/local/git/grpc/bins/ubsan/h2_proxy_test+0x405efc)

Command exited with non-zero status 1
real 6.15
user 6.08
sys 0.04

2017-09-06 15:57:20,671 FAILED: bins/ubsan/h2_proxy_test stream_compression_payload GRPC_POLL_STRATEGY=poll [ret=1, pid=30644]
```

**Comment by apolcyn** [comment]
seen also on 1.6.x branch https://grpc-testing.appspot.com/job/gRPC_pull_requests_ubsan_c/2843/testReport/junit/(root)/c_linux_ubsan_native/bins_ubsan_h2_proxy_test_payload_GRPC_POLL_STRATEGY_poll/
