### ISSUE TITLE
Artifacts build failed with timeout

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12336]
```
ERROR: Aborting VM command due to timeout of 14400 seconds

I0830 09:57:57.888712  546381 vm_accessor.py:232] Rsyncing from VM /tmpfs/src/ to local /tmp/workspace/workspace/grpc/ubuntu/pull_request/grpc_basictests_multilang/artifacts/
I0830 09:57:57.889361  546381 util.py:125] [ID: 2885707] Running command:
['rsync', '-rltD', '--no-checksum', '--partial', '--no-p', '--no-g', '--no-o', '--safe-links', '--ignore-existing', '--compare-dest=/tmp/workspace/workspace/grpc/ubuntu/pull_request/grpc_basictests_multilang/src/', '--rsh="/tmp/kokoro-rsync-proxy"', 'kbuilder@localhost:/tmpfs/src/', '/tmp/workspace/workspace/grpc/ubuntu/pull_request/grpc_basictests_multilang/artifacts/']
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
I0830 09:58:11.052761  546381 util.py:133] [ID: 2885707] Process finished after 13 secs, exit value: 0
E0830 09:58:11.132246  546381 kokoro_builder.py:282] Build script failed with exit code: 1
Traceback (most recent call last):
  File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-gcp_ubuntu-dynamic-grpc-prod-1054164648.jenkins_slave.kokoro-dedicated.51897918423.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/devtools/kokoro/jenkins/slave/kokoro_builder.py", line 280, in main
    builder.Run()
  File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-gcp_ubuntu-dynamic-grpc-prod-1054164648.jenkins_slave.kokoro-dedicated.51897918423.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/devtools/kokoro/jenkins/slave/kokoro_builder.py", line 258, in Run
    self._ExecuteBuild(command)
  File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-gcp_ubuntu-dynamic-grpc-prod-1054164648.jenkins_slave.kokoro-dedicated.51897918423.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/devtools/kokoro/jenkins/slave/kokoro_builder.py", line 164, in _ExecuteBuild
    raise UserError('Build script failed with exit code: %d' % build_result)
UserError: Build script failed with exit code: 1
[09:58:11][ERROR] Command execution completed with failure
[09:58:12][ERROR] Build failed
```

**Comment by adelez** [comment]
Can you please provide a sponge link?

**Comment by adelez** [comment]
This is the artifact test failure. Assigning to @jtattermusch

**Comment by AspirinSJL** [comment]
@adelez Oh, sorry! The previous test results seem to have been overwritten by a new one because I pushed a new commit. And now I can't find the link.. I should copy a link in the issue next time.

**Comment by yashykt** [comment]
Found this bug with PR #12440 
Here's the sponge log : http://sponge/082b2660-219a-4d28-86cb-ed1483557251

**Comment by AspirinSJL** [comment]
Seen again: https://sponge.corp.google.com/target?id=508e1ee7-6380-4833-bb92-f6ad7d8169f4&target=grpc/ubuntu/pull_request/grpc_basictests_c_cpp_dbg&searchFor=&show=FAILED&sortBy=STATUS

**Comment by apolcyn** [comment]
https://sponge.corp.google.com/target?id=43f3a5e5-7ded-4e69-b864-25b1a454a32b&target=grpc/windows/pull_request/grpc_build_artifacts&searchFor=&show=ALL&sortBy=STATUS

This failure doesn't have the same "timeout" told in the log, but I believe this is also a timeout:

```
2017-09-26 13:47:26,816 START: build_artifact.node_ext_windows_x86
2017-09-26 14:01:59,926 PASSED: build_artifact.node_ext_windows_x86 [time=873.1sec; retries=0:0]
2017-09-26 14:01:59,926 START: build_artifact.node_ext_windows_x64
[14:09:15][ERROR] Interrupted while executing command
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
	at com.google.devtools.kokoro.jenkins.shared.ExecuteAgentCommand.doInvoke(ExecuteAgentCommand.java:136)
	at com.google.devtools.kokoro.jenkins.shared.ExecuteAgentCommand.doInvoke(ExecuteAgentCommand.java:23)
	at com.google.devtools.kokoro.jenkins.shared.BaseMasterToAgentFileCallable.invoke(BaseMasterToAgentFileCallable.java:83)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.jenkinsci.remoting.kokoro.RpcSlaveEngine$1$1.run(RpcSlaveEngine.java:116)
	at java.lang.Thread.run(Thread.java:745)
```
