### ISSUE TITLE
yapf_code.sh Failure

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#12458]
This occurred on the internal CI build.
It looks like this is a known issue: https://github.com/pypa/pip/issues/4165

There have been a series of of cache-corruption issues with Python on the internal CI build:
https://github.com/grpc/grpc/issues/11968

This looks very similar, so I'll try adding the failing library to the cache-warmup.
```
Failure .py", line 488, in get     return self.request('GET', url, **kwargs)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 386, in request     return super(PipSession, self).request(method, url, *args, **kwargs)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 475, in request     resp = self.send(prep, **send_kwargs)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 596, in send     r = adapter.send(request, **kwargs)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/adapter.py", line 37, in send     cached_response = self.controller.cached_request(request)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request     resp = self.serializer.loads(request, cache_data)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/serialize.py", line 114, in loads     return getattr(self, "_loads_v{0}".format(ver))(request, data)   File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/cachecontrol/serialize.py", line 176, in _loads_v2     cached = json.loads(zlib.decompress(data).decode("utf8")) error: Error -5 while decompressing data: incomplete or truncated stream ---------------------------------------- ...Installing setuptools, pip, wheel...done. Traceback (most recent call last):   File "/usr/local/bin/virtualenv", line 11, in <module>     sys.exit(main())   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main     symlink=options.symlink)   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 945, in create_environment     download=download,   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 901, in install_wheel     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)   File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 797, in call_subprocess     % (cmd_desc, proc.returncode)) OSError: Command /var/local/git/grpc/...vironment/bin/python - setuptools pip wheel failed with error code 2 Command exited with non-zero status 1 real 0.94 user 0.58 sys 0.12  2017-09-08 15:24:42,177 FAILED: tools/distrib/yapf_code.sh [ret=1, pid=1542]
--

```

**Comment by nathanielmanistaatgoogle** [comment]
Do we believe that this was fixed by [pull request 12460](https://github.com/grpc/grpc/pull/12460)?

**Comment by kpayson64** [comment]
That was the intent. We can re-open if it is still happening.

**Comment by muxi** [comment]
Looks like it is still happening in master

**Comment by muxi** [comment]
https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_basictests_multilang/780/

**Comment by kpayson64** [comment]
@muxi 
It looks like the issue you linked is slightly different.  In this issue   ```yapf_code.sh``` was failing because pip failed to download the needed packages.

I've created a new bug with a more specific failure, it should be an easy fix:
#13757

**Comment by muxi** [comment]
I see. Thank you Ken.
