### ISSUE TITLE
cloud_to_prod:default:javaokhttp:server_streaming Failure

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#12518]
WARNING: Unable to find Conscrypt
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
[jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
[jetty-alpn-agent] Replacing: sun/security/ssl/Alerts
Sep 08, 2017 10:20:40 PM io.grpc.okhttp.AsyncFrameWriter$14 run
WARNING: Failed closing connection
java.net.SocketException: Socket is closed
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1532)
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1553)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at okio.Okio$1.write(Okio.java:80)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.close(RealBufferedSink.java:234)
	at io.grpc.okhttp.internal.framed.Http2$Writer.close(Http2.java:569)
	at io.grpc.okhttp.AsyncFrameWriter$14.run(AsyncFrameWriter.java:203)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" java.lang.AssertionError: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
	at io.grpc.testing.integration.AbstractInteropTest.assertSuccess(AbstractInteropTest.java:1557)
	at io.grpc.testing.integration.AbstractInteropTest.serverStreaming(AbstractInteropTest.java:472)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:225)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:184)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:66)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:289)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Shutting down

2017-09-08 15:20:40,443 FAILED: cloud_to_prod:default:javaokhttp:server_streaming [ret=1, pid=7184]

**Comment by jtattermusch** [comment]
Dupe of #10763
