### ISSUE TITLE
Failure: cloud_to_prod_auth:default:ruby:per_rpc_creds, unavailable status

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12530]
```
Error Message

Failure
Stacktrace

/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Endpoint read failed (GRPC::Unavailable)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:171:in `attach_status_results_and_complete_call'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:363:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/client_stub.rb:152:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from src/ruby/pb/test/client.rb:668:in `perform_large_unary'
	from src/ruby/pb/test/client.rb:362:in `per_rpc_creds'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-09-12T19:21:42.668838 #68]  INFO -- : ... connecting securely to 216.239.32.254:443
```

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16556/testReport/junit/(root)/tests/cloud_to_prod_auth_default_ruby_per_rpc_creds/

**Comment by jtattermusch** [comment]
Dupe of https://github.com/grpc/grpc/issues/10763
