### ISSUE TITLE
run_ruby_end2end_tests failing consistently on Mac: exception thrown while child thread initing class (RuntimeError)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12538]
https://sponge.corp.google.com/target?id=97c82115-5a8e-403c-9189-9a644bcebe08&target=github/grpc/ruby_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:57:in `run_concurrency_stress_test': exception thrown while child thread initing class (RuntimeError)
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:119:in `main'
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:128:in `<main>'
start client
"run default"
start client
"run gc stress"
start client
"run concurrency stress"
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:57:in `run_concurrency_stress_test': exception thrown while child thread initing class (RuntimeError)
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:119:in `main'
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:128:in `<main>'
start client
"run default"
start client
"run gc stress"
start client
"run concurrency stress"
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:57:in `run_concurrency_stress_test': exception thrown while child thread initing class (RuntimeError)
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:119:in `main'
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:128:in `<main>'
start client
"run default"
start client
"run gc stress"
start client
"run concurrency stress"
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:57:in `run_concurrency_stress_test': exception thrown while child thread initing class (RuntimeError)
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:119:in `main'
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:128:in `<main>'
start client
"run default"
start client
"run gc stress"
start client
"run concurrency stress"
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:57:in `run_concurrency_stress_test': exception thrown while child thread initing class (RuntimeError)
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:119:in `main'
	from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_opt_native/src/ruby/end2end/grpc_class_init_client.rb:128:in `<main>'
start client
"run default"
start client
"run gc stress"
start client
"run concurrency stress"
```

**Comment by apolcyn** [comment]
Noting that I don't expect to see this on jenkins, and I think it is specific to kokoro (it looks like this test has passed on all recent jenkins mac runs in https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/).

**Comment by apolcyn** [comment]
with logs on the kokoro macs now, my current finding: on kokoro/mac/ruby, `SIGINT` either doesn't reach or is ignored by the child process in the failing test (which relies on it in order to terminate). `SIGTERM` doesn't have that problem though.

**Comment by apolcyn** [comment]
Looking into this... the test that's failing here relies on `SIGINT` getting sent to a child process, setting of the ruby default signal handler, and terminating the process.

I am theorizing that a kokoro parent driver script does a `sigmask` on SIGINT somewhere. When placing a `trap("INT", "DEFAULT")` at the beginning of the child process script to cause the ruby process running `killed_thread_during_channel_watch_client.rb` to do a `sigaction`  call
 and set the process SIGINT handler to the ruby-default SIGINT handler, everything works as expected. Also, using SIGTERM instead (treated basically the same as SIGINT by ruby), causes things to work out normally.
