### ISSUE TITLE
Failure: c++_linux_asan_native.bins/asan/grpclb_test GRPC_POLL_STRATEGY=epollsig (from grpc.c++_linux_asan_native)

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12546]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_cpp/7050/testReport/(root)/c++_linux_asan_native/bins_asan_grpclb_test_GRPC_POLL_STRATEGY_epollsig/

```
grpc/third_party/googletest/googletest/src/gtest.cc:4257:10
    #24 0x58ca63 in RUN_ALL_TESTS() /var/local/git/grpc/third_party/googletest/googletest/include/gtest/gtest.h:2233:10
    #25 0x57fc40 in main /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:794:23
    #26 0x7fa452a6ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x60200001c110 (7 bytes)

[1m[34mIndirect leak of 7 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4ccd28 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6e2807 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x6e8448 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x5999a4 in copy_arg /var/local/git/grpc/src/core/lib/channel/channel_args.c:40:26
    #4 0x59915c in grpc_channel_args_copy_and_add_and_remove /var/local/git/grpc/src/core/lib/channel/channel_args.c:108:28
    #5 0x9fbbd2 in glb_create /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.c:1020:22
    #6 0x671492 in grpc_lb_policy_factory_create_lb_policy /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy_factory.c:167:10
    #7 0x9e06ca in grpc_lb_policy_create /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy_registry.c:68:7
    #8 0xd79e04 in on_resolver_result_changed_locked /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.c:438:11
    #9 0x5b26a6 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:258:5
    #10 0x5c2a0d in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:93:17
    #11 0x5c2714 in grpc_exec_ctx_finish /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:56:3
    #12 0x61633d in grpc_call_start_batch /var/local/git/grpc/src/core/lib/surface/call.c:2077:3
    #13 0x581d17 in grpc::(anonymous namespace)::perform_request(grpc::(anonymous namespace)::client_fixture*) /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:500:11
    #14 0x580c37 in grpc::(anonymous namespace)::test_update(int) /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:728:3
    #15 0x58013d in grpc::(anonymous namespace)::GrpclbTest_Updates_Test::TestBody() /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:753:15
    #16 0x135b8eb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #17 0x1326af0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #18 0x12f06b9 in testing::Test::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2474:5
    #19 0x12f251c in testing::TestInfo::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2656:5
    #20 0x12f36b1 in testing::TestCase::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2774:5
    #21 0x1302f3c in testing::internal::UnitTestImpl::RunAllTests() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4649:11
    #22 0x1365126 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #23 0x132c1d0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #24 0x1302531 in testing::UnitTest::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4257:10
    #25 0x58ca63 in RUN_ALL_TESTS() /var/local/git/grpc/third_party/googletest/googletest/include/gtest/gtest.h:2233:10
    #26 0x57fc40 in main /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:794:23
    #27 0x7fa452a6ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x602000003bf0 (7 bytes)

[1m[34mIndirect leak of 7 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4ccd28 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x6e2807 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:56:7
    #2 0x6e8448 in gpr_strdup /var/local/git/grpc/src/core/lib/support/string.c:41:17
    #3 0x6dfd3b in grpc_connectivity_state_init /var/local/git/grpc/src/core/lib/transport/connectivity_state.c:54:19
    #4 0x9fc148 in glb_create /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.c:1053:3
    #5 0x671492 in grpc_lb_policy_factory_create_lb_policy /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy_factory.c:167:10
    #6 0x9e06ca in grpc_lb_policy_create /var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy_registry.c:68:7
    #7 0xd79e04 in on_resolver_result_changed_locked /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.c:438:11
    #8 0x5b26a6 in grpc_combiner_continue_exec_ctx /var/local/git/grpc/src/core/lib/iomgr/combiner.c:258:5
    #9 0x5c2a0d in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:93:17
    #10 0x5c2714 in grpc_exec_ctx_finish /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:56:3
    #11 0x61633d in grpc_call_start_batch /var/local/git/grpc/src/core/lib/surface/call.c:2077:3
    #12 0x581d17 in grpc::(anonymous namespace)::perform_request(grpc::(anonymous namespace)::client_fixture*) /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:500:11
    #13 0x580c37 in grpc::(anonymous namespace)::test_update(int) /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:728:3
    #14 0x58013d in grpc::(anonymous namespace)::GrpclbTest_Updates_Test::TestBody() /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:753:15
    #15 0x135b8eb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #16 0x1326af0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #17 0x12f06b9 in testing::Test::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2474:5
    #18 0x12f251c in testing::TestInfo::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2656:5
    #19 0x12f36b1 in testing::TestCase::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2774:5
    #20 0x1302f3c in testing::internal::UnitTestImpl::RunAllTests() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4649:11
    #21 0x1365126 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #22 0x132c1d0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #23 0x1302531 in testing::UnitTest::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4257:10
    #24 0x58ca63 in RUN_ALL_TESTS() /var/local/git/grpc/third_party/googletest/googletest/include/gtest/gtest.h:2233:10
    #25 0x57fc40 in main /var/local/git/grpc/test/cpp/grpclb/grpclb_test.cc:794:23
    #26 0x7fa452a6ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

Objects leaked above:
0x602000003610 (7 bytes)

SUMMARY: AddressSanitizer: 5584 byte(s) leaked in 66 allocation(s).
```

**Comment by dgquintas** [comment]
Fixed in #12601
