### ISSUE TITLE
ipv4:/// URI does not work with pick-first LB policy on secured channels

### ISSUE THREAD

**Issue by hubo1016** [grpc/grpc#12569]
### What version of gRPC and what language are you using?
GRPC 1.6.0, Python 
 
### What operating system (Linux, Windows, …) and version?
 CentOS 7.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.6
 
### What did you do?
1. Create a server credential with 2 IPs (`ip1`, `ip2`) as the SubjectAltNames
2. Start GRPC server on two IPs with credentials
3. Use `ipv4:///ip1:port1,ip2:port2` to create a secured client to connect to the two servers, by default it use "pick-first" policy
 
### What did you expect to see?
Successfully connected to the servers 
 
### What did you see instead?
GRPC core reporting UNAVAILABLE, with the following debug information:

```
I0914 07:56:42.322974724     372 socket_utils_common_posix.c:223] Disabling AF_INET6 sockets because ::1 is not available.
D0914 07:56:42.346802780     381 security_handshaker.c:111]  Security handshake failed: {"created":"@1505375802.346768004","description":"Peer name 10.0.252.4:2379,10.0.252.6:2379 is not in peer certificate","file":"src/core/lib/security/transport/security_connector.c","file_line":611}
I0914 07:56:42.346972222     381 subchannel.c:683]           Connect failed: {"created":"@1505375802.346768004","description":"Peer name 10.0.252.4:2379,10.0.252.6:2379 is not in peer certificate","file":"src/core/lib/security/transport/security_connector.c","file_line":611}
D0914 07:56:42.369349452     379 security_handshaker.c:111]  Security handshake failed: {"created":"@1505375802.369332185","description":"Peer name 10.0.252.4:2379,10.0.252.6:2379 is not in peer certificate","file":"src/core/lib/security/transport/security_connector.c","file_line":611}
I0914 07:56:42.369498822     379 subchannel.c:683]           Connect failed: {"created":"@1505375802.369332185","description":"Peer name 10.0.252.4:2379,10.0.252.6:2379 is not in peer certificate","file":"src/core/lib/security/transport/security_connector.c","file_line":611}
I0914 07:56:42.369598260     379 subchannel.c:479]           Retry in 19.953330303 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "<stdin>", line 4, in x
  File "/usr/local/lib/python3.6/site-packages/aioetcd3/kv.py", line 49, in grpc_func
    return response(await self.grpc_call(method(self), request, timeout=timeout))
  File "/usr/local/lib/python3.6/site-packages/aioetcd3/base.py", line 18, in grpc_call
    response = await stub_func(request, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/aiogrpc/channel.py", line 40, in __call__
    return await fut
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
```

It seems that the GRPC core is using the full server uri (ip1:port1,ip2:port2) as the peer name to match against the SubjectAltNames, instead of the picked address.

When using ipv4:///ip1:port1, the client connects to the server successfully.

**Comment by hubo1016** [comment]
https://github.com/grpc/grpc/blob/696560cf35a49a0e92249ea92fda67fafcf144c5/src/core/ext/transport/chttp2/client/secure/secure_channel_create.c#L46

This should be the target name related function, in which the server URI is used as the target name. 

https://github.com/grpc/grpc/blob/696560cf35a49a0e92249ea92fda67fafcf144c5/src/core/ext/transport/chttp2/client/secure/secure_channel_create.c#L79

It seems that pick-first should set a target_info argument, but it did not.

**Comment by markdroth** [comment]
This isn't actually related to pick_first; the same problem would exist with round_robin.  I think the right place to fix this is in the sockaddr resolver, which can use `grpc_lb_targets_info_create_channel_arg()` to add a target map to the channel args it returns.  (We should probably also rename `grpc_lb_targets_info_create_channel_arg()` and `grpc_lb_targets_info_find_in_args()`, since they will no longer be specific to grpclb.)

I think that using an IP address instead of a hostname in the SSL certificate is a bit of an odd setup, so I doubt this is affecting too many people.  As such, I'm not sure how quickly we'll get to this, but I'd be happy to review a pull request if you want to take a stab at fixing it.

**Comment by hubo1016** [comment]
@markdroth I'm using an etcdv3 cluster. Usually we use an IP list to configure the client.
Although it is possible to create a DNS name for the cluster, it is usually not as reliable as the fixed IP list, and our DNS system depends on the etcd cluster.
Currently we are overriding the SSL target name for a workaround. I will try to fix it if I have time, but not now.
