### ISSUE TITLE
Timeout: Basic Tests Linux (dbg)

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12593]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/7886/console

The tail of the log is like:
```
15:03:49 + /var/local/git/grpc/py34/bin/python3.4 -m pip install cython
15:03:49 Collecting cython
15:03:49   Downloading Cython-0.26.1-cp34-cp34m-manylinux1_x86_64.whl (2.9MB)
15:03:49 Exception:
15:03:49 Traceback (most recent call last):
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 232, in _error_catcher
15:03:49     yield
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
15:03:49     data = self._fp.read(amt)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
15:03:49     data = self.__fp.read(amt)
15:03:49   File "/usr/lib/python3.4/http/client.py", line 500, in read
15:03:49     return super(HTTPResponse, self).read(amt)
15:03:49   File "/usr/lib/python3.4/http/client.py", line 539, in readinto
15:03:49     n = self.fp.readinto(b)
15:03:49   File "/usr/lib/python3.4/socket.py", line 371, in readinto
15:03:49     return self._sock.recv_into(b)
15:03:49   File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
15:03:49     return self.read(nbytes, buffer)
15:03:49   File "/usr/lib/python3.4/ssl.py", line 617, in read
15:03:49     v = self._sslobj.read(len, buffer)
15:03:49 ConnectionResetError: [Errno 104] Connection reset by peer
15:03:49 
15:03:49 During handling of the above exception, another exception occurred:
15:03:49 
15:03:49 Traceback (most recent call last):
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
15:03:49     status = self.run(options, args)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/commands/install.py", line 335, in run
15:03:49     wb.build(autobuilding=True)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/wheel.py", line 749, in build
15:03:49     self.requirement_set.prepare_files(self.finder)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/req/req_set.py", line 380, in prepare_files
15:03:49     ignore_dependencies=self.ignore_dependencies))
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/req/req_set.py", line 620, in _prepare_file
15:03:49     session=self.session, hashes=hashes)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/download.py", line 821, in unpack_url
15:03:49     hashes=hashes
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/download.py", line 659, in unpack_http_url
15:03:49     hashes)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/download.py", line 882, in _download_http_url
15:03:49     _download_url(resp, link, content_file, hashes)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/download.py", line 603, in _download_url
15:03:49     hashes.check_against_chunks(downloaded_chunks)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
15:03:49     for chunk in chunks:
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/download.py", line 571, in written_chunks
15:03:49     for chunk in chunks:
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/utils/ui.py", line 139, in iter
15:03:49     for x in it:
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/download.py", line 560, in resp_read
15:03:49     decode_content=False):
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
15:03:49     data = self.read(amt=amt, decode_content=decode_content)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
15:03:49     flush_decoder = True
15:03:49   File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
15:03:49     self.gen.throw(type, value, traceback)
15:03:49   File "/var/local/git/grpc/py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 250, in _error_catcher
15:03:49     raise ProtocolError('Connection broken: %r' % e, e)
15:03:49 pip._vendor.requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
15:03:49 
15:03:49 2017-09-13 22:03:47,602 FAILED: /var/local/git/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=2, pid=6277]
15:03:49 2017-09-13 22:03:47,602 FAILED: Some tests failed
15:03:49   adding: reports/ (stored 0%)
15:03:49   adding: reports/index.html (deflated 22%)
15:03:49 + DOCKER_EXIT_CODE=1
15:03:49 ++ mktemp
15:03:49 + TEMP_REPORTS_ZIP=/tmp/tmp.cfkmZJfhan
15:03:49 + docker cp run_tests_ba3b3e3c-0637-4b5d-9dc5-3381a04184f4:/var/local/git/grpc/reports.zip /tmp/tmp.cfkmZJfhan
15:03:49 + unzip -o /tmp/tmp.cfkmZJfhan -d /home/jenkins/workspace/gRPC_pull_requests_linux
15:03:49 Archive:  /tmp/tmp.cfkmZJfhan
15:03:49   inflating: /home/jenkins/workspace/gRPC_pull_requests_linux/reports/index.html  
15:03:49 + rm -f /tmp/tmp.cfkmZJfhan
15:03:49 + docker rm -f run_tests_ba3b3e3c-0637-4b5d-9dc5-3381a04184f4
15:03:49 run_tests_ba3b3e3c-0637-4b5d-9dc5-3381a04184f4
15:03:49 + exit 1
15:03:49 Traceback (most recent call last):
15:03:49   File "tools/run_tests/run_tests.py", line 1375, in <module>
15:03:49     env=env)
15:03:49   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
15:03:49     raise CalledProcessError(retcode, cmd)
15:03:49 subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 1
15:03:49 
15:03:49 2017-09-13 22:03:49,412 FAILED: run_tests_python_linux_dbg_native [ret=1, pid=31904]
15:03:49 2017-09-13 22:03:49,412 START: run_tests_c++_linux_dbg_native
18:55:35 Build timed out (after 300 minutes). Marking the build as aborted.
18:55:35 Build was aborted
18:55:35 Recording test results
18:55:36 [Set GitHub commit status (universal)] PENDING on repos [GHRepository@7934bd2d[description=The C based gRPC (C++, Node.js, Python, Ruby, Objective-C, PHP, C#),homepage=,name=grpc,license=<null>,fork=false,size=136797,milestones={},language=C,commits={},source=<null>,parent=<null>,url=https://api.github.com/repos/grpc/grpc,id=27729880], GHRepository@48977047[description=The C based gRPC (C++, Node.js, Python, Ruby, Objective-C, PHP, C#),homepage=,name=grpc,license=<null>,fork=false,size=136797,milestones={},language=C,commits={},source=<null>,parent=<null>,url=https://api.github.com/repos/grpc/grpc,id=27729880]] (sha:db9171f) with context:gRPC_pull_requests_linux_dbg
18:55:36 Setting commit status on GitHub for https://github.com/grpc/grpc/commit/db9171f9ecd487302355c4286840248039cff416
18:55:36 Setting commit status on GitHub for https://github.com/grpc/grpc/commit/db9171f9ecd487302355c4286840248039cff416
18:55:36 Setting status of 6502ecc812cba929453115a0475804304db243a6 to FAILURE with url https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/7886/ and message: 'Build finished. '
18:55:36 Using context: Basic Tests Linux (dbg)
18:55:36 Finished: ABORTED
```

**Comment by dgquintas** [comment]
Looks like things couldn't be downloaded. Closing.
