### ISSUE TITLE
Node servers fail with TypeError when calling the callback with an Error object.

### ISSUE THREAD

**Issue by vgatto** [grpc/grpc#1262]
My gRPC server always crashes when attempting to respond with an error to the client, so I added the following to `src/node/test/math_client_test.js` to exercise the server side error handling (divide by zero):

```
  it('should handle a failing request', function(done) {
    var arg = {dividend: 7, divisor: 0};
    math_client.div(arg, function handleDivResult(err, value) {
      assert(err);
      done();
    });
  });
```
And the test fails, causing the following exception:

```
  1) Math client should handle a failing request:
     Uncaught TypeError: Incorrectly typed arguments to startBatch
      at TypeError (native)
      at handleError (/Users/vgatto/dev/springful/grpc/src/node/src/server.js:78:8)
      at sendUnaryData (/Users/vgatto/dev/springful/grpc/src/node/src/server.js:364:9)
      at Object.mathDiv [as func] (/Users/vgatto/dev/springful/grpc/src/node/examples/math_server.js:56:5)
      at /Users/vgatto/dev/springful/grpc/src/node/src/server.js:361:13
```

**Comment by murgatroid99** [comment]
Thank you for bringing this to my attention. The error you were seeing was caused by a bug in the trailing metadata handling code I recently added. The pull request linked above fixes it (and adds that test to the test suite).
