### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TestServiceStub' in python kokoro cloud to prod interop

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12659]
```
2017-09-20 15:34:57,377 WAITING: ETA 81.4 sec; 256 queued, 12 jobs running, 18 complete, 0 failed
2017-09-20 15:34:57,548 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:57,548 FAILED: cloud_to_prod:default:python:ping_pong [ret=1, pid=1044]
2017-09-20 15:34:57,549 START: cloud_to_prod:default:java:empty_stream
2017-09-20 15:34:57,553 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:57,553 FAILED: cloud_to_prod:default:python:large_unary [ret=1, pid=1038]
2017-09-20 15:34:57,553 START: cloud_to_prod:default:java:client_streaming
2017-09-20 15:34:57,555 WAITING: ETA 75.1 sec; 254 queued, 12 jobs running, 20 complete, 2 failed
2017-09-20 15:34:57,645 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:57,646 FAILED: cloud_to_prod:default:python:client_streaming [ret=1, pid=1054]
2017-09-20 15:34:57,646 START: cloud_to_prod:default:java:server_streaming
2017-09-20 15:34:57,649 WAITING: ETA 72.4 sec; 253 queued, 12 jobs running, 21 complete, 3 failed
2017-09-20 15:34:57,650 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:57,650 FAILED: cloud_to_prod:default:python:empty_unary [ret=1, pid=1043]
2017-09-20 15:34:57,650 START: cloud_to_prod:default:java:cancel_after_begin
2017-09-20 15:34:57,653 WAITING: ETA 68.9 sec; 252 queued, 12 jobs running, 22 complete, 4 failed
2017-09-20 15:34:57,656 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:57,656 FAILED: cloud_to_prod:default:python:server_streaming [ret=1, pid=1519]
2017-09-20 15:34:57,657 START: cloud_to_prod:default:java:cancel_after_first_response
2017-09-20 15:34:57,659 WAITING: ETA 65.7 sec; 251 queued, 12 jobs running, 23 complete, 5 failed
2017-09-20 15:34:57,762 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:57,762 FAILED: cloud_to_prod:default:python:empty_stream [ret=1, pid=1049]
2017-09-20 15:34:57,762 START: cloud_to_prod:default:java:timeout_on_sleeping_server
2017-09-20 15:34:57,765 WAITING: ETA 63.9 sec; 250 queued, 12 jobs running, 24 complete, 6 failed
2017-09-20 15:34:58,346 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:58,346 FAILED: cloud_to_prod:default:python:cancel_after_begin [ret=1, pid=1939]
2017-09-20 15:34:58,346 START: cloud_to_prod:default:javaokhttp:large_unary
2017-09-20 15:34:58,350 WAITING: ETA 67.2 sec; 249 queued, 12 jobs running, 25 complete, 7 failed
2017-09-20 15:34:58,529 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:58,529 FAILED: cloud_to_prod:default:python:cancel_after_first_response [ret=1, pid=2111]
2017-09-20 15:34:58,529 START: cloud_to_prod:default:javaokhttp:empty_unary
2017-09-20 15:34:58,533 WAITING: ETA 66.2 sec; 248 queued, 12 jobs running, 26 complete, 8 failed
2017-09-20 15:34:58,656 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 135, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 151, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 124, in test_interoperability
    stub = _stub(args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 111, in _stub
    return test_pb2.TestServiceStub(channel)
AttributeError: 'module' object has no attribute 'TestServiceStub'

2017-09-20 15:34:58,656 FAILED: cloud_to_prod:default:python:timeout_on_sleeping_server [ret=1, pid=2121]
2017-09-20 15:34:58,656 START: cloud_to_prod:default:javaokhttp:ping_pong
```

https://sponge.corp.google.com/target?id=e943ecd9-c173-4671-a738-1883d88c5401&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by nathanielmanistaatgoogle** [comment]
[Pull request 12666](https://github.com/grpc/grpc/pull/12666) should fix this.
