### ISSUE TITLE
node portability test: FAILED: tools/run_tests/helper_scripts/build_node_electron.sh

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12705]
Failing in 100% cases.

```
Error: Failed to find Electron v1.8.0 for linux-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-linux-x64.zip
    at Request.<anonymous> (/var/local/git/grpc/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (/var/local/git/grpc/node_modules/request/request.js:1068:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
```

https://sponge.corp.google.com/target?id=877617da-2ea3-48af-b31b-5b99427a051f&target=github/grpc/aggregate_tests&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment]
Not seeing this anymore.
