### ISSUE TITLE
Add bm_diff test(s) for stream compression

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12768]
@ncteisen

**Comment by muxi** [comment]
@ncteisen - Got the following error after 4-5 hours of running bm_main.py:
```
Traceback (most recent call last):
  File "tools/profiling/microbenchmarks/bm_diff/bm_main.py", line 145, in <module>
    main(args)
  File "tools/profiling/microbenchmarks/bm_diff/bm_main.py", line 129, in main
    bm_run.run(old, args.benchmarks, args.jobs, args.loops, args.regex, args.counters)
  File "/usr/local/google/home/mxyan/grpc/grpc2/tools/profiling/microbenchmarks/bm_diff/bm_run.py", line 106, in run
    jobs_list += _collect_bm_data(bm, 'opt', name, regex, loop, loops)
  File "/usr/local/google/home/mxyan/grpc/grpc2/tools/profiling/microbenchmarks/bm_diff/bm_run.py", line 84, in _collect_bm_data
    '--benchmark_list_tests', '--benchmark_filter=%s' % regex]).splitlines():
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Known issue?

**Comment by muxi** [comment]
Not completed yet
