### ISSUE TITLE
Basic Tests Mac - Build Fails

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#12785]
Error: coreutils 8.28 is already installed
To upgrade to 8.28_1, run brew upgrade coreutils
I1002 10:33:42.148541  756895 util.py:310] 

[ID: 1603328] Build finished after 111 secs, exit value: 1

I1002 10:33:42.148964  756895 vm_accessor.py:232] Rsyncing from VM /tmpfs/src/ to local /tmp/workspace/workspace/grpc/macos/pull_request/grpc_basictests_dbg/artifacts/
I1002 10:33:42.149107  756895 util.py:133] [ID: 5994192] Running command:
['rsync', '-rltD', '--no-checksum', '--partial', '--no-p', '--no-g', '--no-o', '--safe-links', '--ignore-existing', '--compare-dest=/tmp/workspace/workspace/grpc/macos/pull_request/grpc_basictests_dbg/src/', '--rsh="/tmp/kokoro-rsync-proxy"', 'kbuilder@localhost:/tmpfs/src/', '/tmp/workspace/workspace/grpc/macos/pull_request/grpc_basictests_dbg/artifacts/']
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
I1002 10:33:43.238449  756895 util.py:141] [ID: 5994192] Process finished after 1 secs, exit value: 0
E1002 10:33:43.291600  756895 kokoro_builder.py:313] Build script failed with exit code: 1
Traceback (most recent call last):
  File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-macos_external-dynamic-prod-1656608747.jenkins_slave.kokoro-dedicated.9287892079.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/devtools/kokoro/jenkins/slave/kokoro_builder.py", line 311, in main
    builder.Run()
  File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-macos_external-dynamic-prod-1656608747.jenkins_slave.kokoro-dedicated.9287892079.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/devtools/kokoro/jenkins/slave/kokoro_builder.py", line 289, in Run
    self._ExecuteBuild(command)
  File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-macos_external-dynamic-prod-1656608747.jenkins_slave.kokoro-dedicated.9287892079.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/devtools/kokoro/jenkins/slave/kokoro_builder.py", line 166, in _ExecuteBuild
    raise UserError('Build script failed with exit code: %d' % build_result)
UserError: Build script failed with exit code: 1
[10:33:43][ERROR] Command execution completed with failure
[10:33:44][ERROR] Build failed

**Comment by jtattermusch** [comment]
This was fixed here: https://github.com/grpc/grpc/pull/12779/files#diff-035a14c04ab4a7d5b15c576e6398058bL54
