### ISSUE TITLE
E1006...Failed to initialize UV tcp handle in nodejs

### ISSUE THREAD

**Issue by echoma** [grpc/grpc#12861]
My Env:
```
grpc@1.6.6
node v8.4.0
CentOS 6.7 x86_64 GNU/Linux
gcc 4.4.7
```

This can be re-produced with the following simple code:

```node
const grpc = require('grpc');
let server = new grpc.Server();
server.bind('0.0.0.0:9527', grpc.ServerCredentials.createInsecure());
server.start();
```

This code runs well in Ubuntu17.04, the server started and listened on port 9527.

But in CentOS 6.7, I got this error
```
E1006 16:28:26.036382546   15707 server_chttp2.c:38]         {"created":"@1507278506.036355919","description":"No address added out of total 1 resolved","file":"../src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":245,"referenced_errors":[{"created":"@1507278506.036350397","description":"Failed to add port to server","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":418,"referenced_errors":[{"created":"@1507278506.036345700","description":"Failed to initialize UV tcp handle","file":"../src/core/lib/iomgr/tcp_server_uv.c","file_line":396,"os_error":"address family not supported"}]}]}
```

**Comment by hrdwdmrbl** [comment]
I'm getting this too

**Comment by murgatroid99** [comment]
I think this is a bug related to how the code is handling wildcard addresses (`0.0.0.0`) internally.

**Comment by murgatroid99** [comment]
We have published the prerelease package grpc@1.8.0-pre2. I believe it fixes this problem. If you could try it out, that would be helpful.

**Comment by echoma** [comment]
@murgatroid99 How can i install 1.8.0-pre2?  Is there any guide?  I installed 1.6.6 with npm.

**Comment by murgatroid99** [comment]
Simply doing `npm install grpc@1.8.0-pre2` should work. Alternatively, it is tagged "next", so you can also do `npm install grpc@next`.

**Comment by echoma** [comment]
@murgatroid99 Sorry, I am encounting some problem with npm here, I can't install any version of grpc right now. 

Part of the error log produced by npm:
```
2966 silly install grpc@1.8.0-pre2
2967 info lifecycle grpc@1.8.0-pre2~install: grpc@1.8.0-pre2
2968 verbose lifecycle grpc@1.8.0-pre2~install: unsafe-perm in lifecycle true
2969 verbose lifecycle grpc@1.8.0-pre2~install: PATH: /data/release/node/node-v8.4.0-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/data/release/balance/src/grpc/example_adapter/node/node_modules/grpc/node_modules/.bin:/data/release/balance/src/grpc/example_adapter/node/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${HOME}/bin:/home/ops/victor/tools/:/home/ops/bin
2970 verbose lifecycle grpc@1.8.0-pre2~install: CWD: /data/release/balance/src/grpc/example_adapter/node/node_modules/grpc
2971 silly lifecycle grpc@1.8.0-pre2~install: Args: [ '-c',
2971 silly lifecycle   'node-pre-gyp install --fallback-to-build --library=static_library' ]
2972 silly lifecycle grpc@1.8.0-pre2~install: Returned: code: 1  signal: null
2973 info lifecycle grpc@1.8.0-pre2~install: Failed to exec install script
2974 verbose unlock done using /home/ops/.npm/_locks/staging-1f649d8bd2f153a5.lock for /data/release/balance/src/grpc/example_adapter/node/node_modules/.staging
2975 warn balance-example-adapter-nodejs@1.0.0 No description
2976 warn balance-example-adapter-nodejs@1.0.0 No repository field.
2977 warn balance-example-adapter-nodejs@1.0.0 No license field.
2978 verbose stack Error: grpc@1.8.0-pre2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2978 verbose stack Exit status 1
2978 verbose stack     at EventEmitter.<anonymous> (/data/release/node/node-v8.4.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
2978 verbose stack     at emitTwo (events.js:125:13)
2978 verbose stack     at EventEmitter.emit (events.js:213:7)
2978 verbose stack     at ChildProcess.<anonymous> (/data/release/node/node-v8.4.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
2978 verbose stack     at emitTwo (events.js:125:13)
2978 verbose stack     at ChildProcess.emit (events.js:213:7)
2978 verbose stack     at maybeClose (internal/child_process.js:927:16)
2978 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2979 verbose pkgid grpc@1.8.0-pre2
2980 verbose cwd /data/release/balance/src/grpc/example_adapter/node
2981 verbose Linux 2.6.32-573.18.1.el6.x86_64
2982 verbose argv "/data/release/node/node-v8.4.0-linux-x64/bin/node" "/bin/npm" "install" "grpc@next"
2983 verbose node v8.4.0
2984 verbose npm  v5.3.0
2985 error code ELIFECYCLE
2986 error errno 1
2987 error grpc@1.8.0-pre2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
2987 error Exit status 1
2988 error Failed at the grpc@1.8.0-pre2 install script.
2988 error This is probably not a problem with npm. There is likely additional logging output above.
2989 verbose exit [ 1, true ]
```

**Comment by 253056965** [comment]
你好我也遇见和你一样的问题，请问nodejs 版本的怎么解决这个bug

**Comment by 253056965** [comment]
@echoma 这个问题你解决了吗？

**Comment by murgatroid99** [comment]
The fix is now in regular versions of the library.
