### ISSUE TITLE
tools/run_tests/helper_scripts/run_grpc-node.sh: cannot find module semver

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#12978]
Broken 100% of cases

https://sponge.corp.google.com/target?id=48f2ff7e-1756-4865-a885-060aa4f1fa75&target=github/grpc/grpc-node_linux_opt_native&searchFor=&show=FAILED&sortBy=STATUS

```
[05:54:48] Starting 'internal.test.install'...
module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.nvm/versions/node/v4.8.4/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.nvm/versions/node/v4.8.4/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
[05:54:48] 'js.core.install' errored after 98 ms
[05:54:48] Error: Command failed: npm install --unsafe-perm
    at /var/local/git/grpc-node/node_modules/execa/index.js:236:11
    at process._tickCallback (node.js:438:9)
[05:54:48] 'health-check.install' errored after 89 ms
[05:54:48] Error: Command failed: npm install --unsafe-perm
    at /var/local/git/grpc-node/node_modules/execa/index.js:236:11
    at process._tickCallback (node.js:438:9)
module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.nvm/versions/node/v4.8.4/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.nvm/versions/node/v4.8.4/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
[05:54:48] 'native.core.install' errored after 97 ms
[05:54:48] Error: Command failed: npm install --build-from-source --unsafe-perm
    at /var/local/git/grpc-node/node_modules/execa/index.js:236:11
    at process._tickCallback (node.js:438:9)
[05:54:48] 'internal.test.install' errored after 93 ms
[05:54:48] Error: Command failed: npm install
    at /var/local/git/grpc-node/node_modules/execa/index.js:236:11
    at process._tickCallback (node.js:438:9)
```

**Comment by murgatroid99** [comment]
I don't know what might be causing this. The same test script is passing in the grpc-node test jobs. @matt-kwong is there maybe something different about the environment where the tests are running?

**Comment by matt-kwong** [comment]
The image used by VMs to run grpc-node tests on grpc/grpc and grpc/grpc-node should be the same.

**Comment by murgatroid99** [comment]
Is the test that's failing here running under docker? I don't think that's the case for the tests running directly from the grpc-node repo.

**Comment by matt-kwong** [comment]
Yes, it's running under Docker.

**Comment by murgatroid99** [comment]
It looks like the issue here is related to a bug with updating npm under Docker: npm/npm#16807. I'll try to use one of the workarounds from that thread.
