### ISSUE TITLE
cloud_to_cloud:java:go_server custom_metadata and large_unary tests failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#12994]
For both java and javaokhttp.

https://sponge.corp.google.com/target?id=eb88d050-932c-4d3a-a222-ca67c99b33f4&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

```
Timeout
Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar
Running test custom_metadata
Exception in thread "main" java.lang.AssertionError: expected:<314167> but was:<314169>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.grpc.testing.integration.AbstractInteropTest.checkTracerMetrics(AbstractInteropTest.java:1881)
	at io.grpc.testing.integration.AbstractInteropTest.assertClientMetrics(AbstractInteropTest.java:1740)
	at io.grpc.testing.integration.AbstractInteropTest.assertMetrics(AbstractInteropTest.java:1712)
	at io.grpc.testing.integration.AbstractInteropTest.customMetadata(AbstractInteropTest.java:1310)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:278)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:190)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:67)
```

**Comment by adelez** [comment]
This is a dup of https://github.com/grpc/grpc-go/issues/1572.

**Comment by adelez** [comment]
This should be fixed. But please reopen the Go bug if it's still an issue.
