### ISSUE TITLE
Python Alpine build broken

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#13044]
Broken by #13021
https://sponge.corp.google.com/target?id=f383a075-a883-4171-908c-993e40b5808b&target=github/grpc/aggregate_tests&searchFor=&show=FAILED&sortBy=STATUS
```
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    ccache gcc -DNDEBUG -Os -fomit-frame-pointer -I/var/local/git/grpc/include -std=gnu99 -fno-wrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/usr/include/python2.7 -c src/core/lib/support/cmdline.cc -o python_build/temp.linux-x86_64-2.7/src/core/lib/support/cmdline.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    ccache gcc -DNDEBUG -Os -fomit-frame-pointer -I/var/local/git/grpc/include -std=gnu99 -fno-wrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/usr/include/python2.7 -c src/core/lib/support/cpu_iphone.cc -o python_build/temp.linux-x86_64-2.7/src/core/lib/support/cpu_iphone.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    ccache gcc -DNDEBUG -Os -fomit-frame-pointer -I/var/local/git/grpc/include -std=gnu99 -fno-wrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/usr/include/python2.7 -c src/core/lib/support/cpu_linux.cc -o python_build/temp.linux-x86_64-2.7/src/core/lib/support/cpu_linux.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
    src/core/lib/support/cpu_linux.cc: In function 'void init_num_cpus()':
    src/core/lib/support/cpu_linux.cc:41:26: error: 'sched_getcpu' was not declared in this scope
       int cpu = sched_getcpu();
                              ^
    creating tmp/tmpOqLmEc
    ccache gcc -DNDEBUG -Os -fomit-frame-pointer -I/var/local/git/grpc/include -std=gnu99 -fno-wrapv -fPIC -I/usr/include/python2.7 -c /tmp/tmpOqLmEc/a.c -o tmp/tmpOqLmEc/a.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-MrJjLm-build/setup.py", line 309, in <module>
        cmdclass=COMMAND_CLASS,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/local/git/grpc/py27/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/local/git/grpc/py27/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/var/local/git/grpc/py27/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-MrJjLm-build/src/python/grpcio/commands.py", line 295, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "/tmp/pip-MrJjLm-build/src/python/grpcio/commands.py", line 290, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/var/local/git/grpc/py27/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/var/local/git/grpc/py27/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 498, in build_extension
        depends=ext.depends)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
        raise CompileError, msg
    CompileError: command 'ccache' failed with exit status 1
    
    
    ----------------------------------------
Command "/var/local/git/grpc/py27/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-MrJjLm-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IZ7FM8-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/local/git/grpc/py27/include/site/python2.7/grpcio" failed with error code 1 in /tmp/pip-MrJjLm-build/

2017-10-17 16:37:42,115 FAILED: /var/local/git/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=1098, time=158.6sec]
```
CC @nathanielmanistaatgoogle @kpayson64

**Comment by vjpai** [comment]
I can pick this up

**Comment by vjpai** [comment]
We reverted this and I don't think it was ever added back; the original PR author ( @iancoolidge ) had mentioned a plan to do that. Closing.

**Comment by iancoolidge** [comment]
https://github.com/grpc/grpc/pull/13138
I'm not sure how reviewers are added or whatever.

**Comment by nathanielmanistaatgoogle** [comment]
@vjpai: so should this issue remain open until the "it [is] added back"? Does this issue describe a currently-active problem that we intend to resolve?
