### ISSUE TITLE
Docker image for node interop tests failed to build

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#13054]
What looks like the relevant parts of the log:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/root/.nvm/versions/node/v8.6.0/bin/gulp -> /root/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/bin/gulp.js
/root/.nvm/versions/node/v8.6.0/bin/node-gyp -> /root/.nvm/versions/node/v8.6.0/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@3.6.2
+ gulp@3.9.1
added 288 packages in 6.577s
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 416 packages in 16.46s
[02:02:50] Using gulpfile /var/local/git/grpc-node/gulpfile.js
[02:02:50] Starting 'setup'...
[02:02:50] Starting 'js.core.install'...
[02:02:50] Starting 'native.core.install'...
[02:02:50] Starting 'health-check.install'...
[02:02:50] Starting 'internal.test.install'...
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! code EINTEGRITY
npm ERR! sha1-IFF4T2vWE0aB+ixLXnXcgsbCP/o= integrity checksum failed when using sha1: wanted sha1-IFF4T2vWE0aB+ixLXnXcgsbCP/o= but got sha1-F2fvi78cvzecgJ+bS2ek7fW6C6g=. (6241789 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2017-10-18T02_02_52_837Z-debug.log
[02:02:52] 'health-check.install' errored after 2.55 s
[02:02:52] Error: Command failed: npm install --unsafe-perm
    at Promise.all.then.arr (/var/local/git/grpc-node/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[02:02:52] 'setup' errored after 2.56 s
[02:02:52] Error in plugin 'run-sequence(health-check.install)'
Message:
    Command failed: npm install --unsafe-perm
Details:
    code: 1
    killed: false
    stdout: null
    stderr: null
    failed: true
    signal: null
    cmd: npm install --unsafe-perm
    timedOut: false
Stack:
Error: Command failed: npm install --unsafe-perm
    at Promise.all.then.arr (/var/local/git/grpc-node/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

> grpc@1.8.0-dev install /var/local/git/grpc-node/packages/grpc-native-core
> node-pre-gyp install --fallback-to-build --library=static_library

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/var/local/git/grpc-node/packages/grpc-native-core/build'
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
```

....

```
  CXX(target) Release/obj.target/grpc_node/ext/call.o
  CXX(target) Release/obj.target/grpc_node/ext/call_credentials.o
  CXX(target) Release/obj.target/grpc_node/ext/channel.o
  CXX(target) Release/obj.target/grpc_node/ext/channel_credentials.o
  CXX(target) Release/obj.target/grpc_node/ext/completion_queue.o
  CXX(target) Release/obj.target/grpc_node/ext/node_grpc.o
  CXX(target) Release/obj.target/grpc_node/ext/server.o
  CXX(target) Release/obj.target/grpc_node/ext/server_credentials.o
  CXX(target) Release/obj.target/grpc_node/ext/slice.o
  CXX(target) Release/obj.target/grpc_node/ext/timeval.o
  SOLINK_MODULE(target) Release/obj.target/grpc_node.node
  COPY Release/grpc_node.node
  COPY /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/var/local/git/grpc-node/packages/grpc-native-core/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
added 205 packages in 55.824s
[02:03:46] Finished 'native.core.install' after 56 s
npm notice created a lockfile as package-lock.json. You should commit this file.
added 148 packages in 72.67s
[02:04:03] Finished 'internal.test.install' after 1.22 min
+ EXITCODE=1
+ docker rm -f build_grpc_interop_node_89138609-5391-402d-8411-e9d20324273d
build_grpc_interop_node_89138609-5391-402d-8411-e9d20324273d
+ exit 1
```

https://sponge.corp.google.com/target?id=8e953673-5e18-4ebf-ba9c-56e1a9beb07b&target=grpc%2Fubuntu%2Fpull_request%2Fgrpc_interop_tocloud&searchFor=

**Comment by apolcyn** [comment]
haven't seen this recently
