### ISSUE TITLE
run-grpc-node.sh failure with "undefined symbol: grpc_fork_support_init"

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#13073]
from the log:

```
> grpc@1.8.0-dev build /var/local/git/grpc-node/packages/grpc-native-core
> node-pre-gyp build

/root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init
[01:02:13] 'health-check.test' errored after 264 ms
[01:02:13] Error in plugin 'gulp-mocha'
Message:
    Command failed: mocha /var/local/git/grpc-node/packages/grpc-health-check/test/health_test.js --colors --reporter=mocha-jenkins-reporter
/root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init

Details:
    code: 127
    killed: false
    stdout: 
    stderr: /root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init

    failed: true
    signal: null
    cmd: mocha /var/local/git/grpc-node/packages/grpc-health-check/test/health_test.js --colors --reporter=mocha-jenkins-reporter
    timedOut: false
[01:02:13] 'native.test' errored after 2.52 s
[01:02:13] Error in plugin 'run-sequence(health-check.test)'
Message:
    Command failed: mocha /var/local/git/grpc-node/packages/grpc-health-check/test/health_test.js --colors --reporter=mocha-jenkins-reporter
/root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init

Details:
    code: 127
    killed: false
    stdout: 
    stderr: /root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init

    failed: true
    signal: null
    cmd: mocha /var/local/git/grpc-node/packages/grpc-health-check/test/health_test.js --colors --reporter=mocha-jenkins-reporter
    timedOut: false
Stack:
Error: Command failed: mocha /var/local/git/grpc-node/packages/grpc-health-check/test/health_test.js --colors --reporter=mocha-jenkins-reporter
/root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init

    at Promise.all.then.arr (/var/local/git/grpc-node/node_modules/gulp-mocha/node_modules/execa/index.js:210:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
/root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init
[01:02:13] 'internal.test.test' errored after 280 ms
[01:02:13] Error in plugin 'gulp-mocha'
Message:
    Command failed: mocha /var/local/git/grpc-node/test/api/async_test.js /var/local/git/grpc-node/test/api/credentials_test.js /var/local/git/grpc-node/test/api/interop_sanity_test.js /var/local/git/grpc-node/test/api/math_client_test.js /var/local/git/grpc-node/test/api/metadata_test.js /var/local/git/grpc-node/test/api/surface_test.js --colors --reporter=mocha-jenkins-reporter
/root/.nvm/versions/node/v8.7.0/bin/node: symbol lookup error: /var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_fork_support_init

Details:
    code: 127
    killed: false
```

https://sponge.corp.google.com/target?id=aafc3df2-1de0-4b96-80b6-b1d51120d66e&target=github/grpc/grpc-node_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by kpayson64** [comment]
```grpc@1.8.0-dev``` it looks like this is against master, has there been an upmerge from 1.7?

**Comment by kpayson64** [comment]
@apolcyn 
Any idea if this is still an issue after the upmerge?

**Comment by apolcyn** [comment]
based on https://github.com/grpc/grpc/issues/13669, this script failing but for a possibly different reason. I'm not sure if this particular failure has been fixed or if it's still present but within the larger #13669 issue.
