### ISSUE TITLE
MacOS grpc-node fails to generate .xml logs

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#13085]
https://sponge.corp.google.com/target?id=16e080b6-dc77-4703-9378-833fda02f9ea&target=github/grpc/grpc-node_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```
[16:50:52] Finished 'internal.test.test' after 5.59 s
+ FAILED=true
+ set +ex
Now using node v8.7.0 (npm v5.4.2)
+ node merge_kokoro_logs.js
TypeError: Cannot read property 'testsuites' of null
    at merged.testsuites.testsuite.Array.concat.apply.objects.map (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/merge_kokoro_logs.js:44:126)
    at Array.map (<anonymous>)
    at readDir.then.then (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/merge_kokoro_logs.js:44:109)
    at <anonymous>
+ '[' true '!=' '' ']'
+ exit 1
```
It looks like `merge_kokoro_logs.js` is failing, but the it's still showing up as a target on Sponge, so I'm not sure what the issue is here.

**Comment by murgatroid99** [comment]
I notice that that test log also shows that at least one test run crashed due to #12932. I suspect that resulted in an invalid XML file.

**Comment by jtattermusch** [comment]
Seems fixed.
