### ISSUE TITLE
Node: merge_kokoro_logs.js: Cannot read property 'testsuites' of null

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13151]
I saw this in recent builds, not sure how significant it is.
```
+ node merge_kokoro_logs.js
TypeError: Cannot read property 'testsuites' of null
    at merged.testsuites.testsuite.Array.concat.apply.objects.map (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/merge_kokoro_logs.js:44:126)
    at Array.map (<anonymous>)
    at readDir.then.then (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/merge_kokoro_logs.js:44:109)
    at <anonymous>
+ '[' true '!=' '' ']'
```

**Comment by murgatroid99** [comment]
I think this is the same as #13085
