### ISSUE TITLE
Python v1.0.x interop matrix failure

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#13230]
```
stdin: is not a tty
running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 115, in <module>
    test_runner=TEST_RUNNER,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 201, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 217, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 123, in test_interoperability
    test_case = _test_case_from_arg(args.test_case)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 117, in _test_case_from_arg
    raise ValueError('No test case "%s"!' % test_case_arg)
ValueError: No test case "None"!
FAILED: python__python_v1.0.x:python:grpc-test4:cancel_after_first_response" [ret=1, pid=48163, time=2.8sec]
```

**Comment by adelez** [comment]
Docker image:
https://pantheon.corp.google.com/gcr/images/grpc-testing/GLOBAL/grpc_interop_python@sha256:8fcc7e1b075392274374034a0d0f4b75be8559e05b0a67a581492b2105a63b72/details/info?project=grpc-testing

Docker command to run the image:
docker run -i --rm=true -e PYTHONPATH=/var/local/git/grpc/src/python/gens -e LD_LIBRARY_PATH=/var/local/git/grpc/libs/opt -w /var/local/git/grpc --net=host --name interop_client_python_95c06f76-cc4a-4b80-9fa5-e2f03dc27722 $docker_image bash -l -c "py27/bin/python src/python/grpcio_tests/setup.py run_interop --client --args="--server_host=grpc-test.sandbox.googleapis.com --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=large_unary""
