### ISSUE TITLE
Node fails to generate from template

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13338]
2017-11-09 01:31:39,884 START: /var/local/git/grpc-node/packages/grpc-native-core/package.json
2017-11-09 01:31:39,886 START: /var/local/git/grpc-node/packages/grpc-native-core/binding.gyp
2017-11-09 01:31:39,888 WAITING: 0 queued, 2 jobs running, 0 complete, 0 failed (load 2.00)
2017-11-09 01:31:40,308 Traceback (most recent call last):
  File "tools/buildgen/mako_renderer.py", line 187, in <module>
    main(sys.argv[1:])
  File "tools/buildgen/mako_renderer.py", line 144, in main
    template.render_context(Context(output_file, **dictionary))
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 485, in render_context
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "_var_local_git_grpc_node_packages_grpc_native_core_templates_package_json_template", line 22, in render_body
AttributeError: 'Bunch' object has no attribute 'node_version'

2017-11-09 01:31:40,308 FAILED: /var/local/git/grpc-node/packages/grpc-native-core/package.json [ret=1, pid=4298, time=0.4sec]
2017-11-09 01:31:40,308 WAITING: ETA 0.4 sec; 0 queued, 1 jobs running, 1 complete, 1 failed (load 1.00)
2017-11-09 01:31:40,357 Traceback (most recent call last):
  File "tools/buildgen/mako_renderer.py", line 187, in <module>
    main(sys.argv[1:])
  File "tools/buildgen/mako_renderer.py", line 144, in main
    template.render_context(Context(output_file, **dictionary))
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 485, in render_context
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "_var_local_git_grpc_node_packages_grpc_native_core_templates_binding_gyp_template", line 79, in render_body
TypeError: 'Undefined' object is not iterable

2017-11-09 01:31:40,357 FAILED: /var/local/git/grpc-node/packages/grpc-native-core/binding.gyp [ret=1, pid=4299, time=0.5sec]

**Comment by murgatroid99** [comment]
This should have been fixed by grpc/grpc-node#86
