### ISSUE TITLE
grpc/ubuntu/pull_request/grpc_interop_tocloud  Error: Invalid value for global._client_implementation: undefined.

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#13393]
https://sponge.corp.google.com/target?id=322fc9bc-983a-4ed5-a3d3-6ffdf7bb20f7&target=grpc/ubuntu/pull_request/grpc_interop_tocloud&searchFor=&show=ALL&sortBy=STATUS

There are many errors about `Error: Invalid value for global._client_implementation: undefined.`

A sample:

```
2017-11-14 14:22:42,027 /var/local/git/grpc-node/test/any_grpc.js:9
    throw new Error([
    ^

Error: Invalid value for global._client_implementation: undefined. If running from the command line, please --require a fixture first.
    at getImplementation (/var/local/git/grpc-node/test/any_grpc.js:9:11)
    at Object.<anonymous> (/var/local/git/grpc-node/test/any_grpc.js:23:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:23:12)
```

**Comment by jtattermusch** [comment]
Already fixed as https://github.com/grpc/grpc-node/issues/89
