### ISSUE TITLE
tools/distrib/python/check_grpcio_tools.py 

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#13404]
https://sponge.corp.google.com/target?id=da3d57a5-8611-4d52-bf57-2f9d84460c50&target=github/grpc/sanity_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```
Failure
Extracting Bazel installation...
...........................................
____Loading package: 
____Loading package: @bazel_tools//tools/genrule
____Loading package: tools/defaults
____Loading package: @local_config_cc//
ERROR: /var/local/git/grpc/third_party/protobuf/BUILD:283:1: in cc_library rule //:protoc_lib: cycle in dependency graph:
.-> //:protoc_lib
|   //:protobuf
|   //:src/google/protobuf/unittest_custom_options.pb.h
|   //:cc_test_protos_genproto
|   //:protoc
`-- //:protoc_lib.
ERROR: Loading of target '//:protoc_lib' failed; build aborted.
ERROR: Evaluation of query "deps(//:protoc_lib)" failed due to BUILD file errors.
Traceback (most recent call last):
  File "tools/distrib/python/check_grpcio_tools.py", line 25, in <module>
    check_protoc_lib_deps_content = make.get_deps()
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 89, in get_deps
    cc_files_output = bazel_query(BAZEL_DEPS_PROTOC_LIB_QUERY)
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 83, in bazel_query
    output = subprocess.check_output([BAZEL_DEPS, query])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/var/local/git/grpc/tools/distrib/python/bazel_deps.sh', '//:protoc_lib']' returned non-zero exit status 7
```

**Comment by jtattermusch** [comment]
@mehrdada, can you take a look?

**Comment by mehrdada** [comment]
@jtattermusch will do. there's another failure caused by an upgrade to Python protobuf package that we are waiting for them to fix, FYI.

**Comment by mehrdada** [comment]
Seems like this is the same issue as this old one: https://github.com/grpc/grpc/issues/9677

**Comment by mehrdada** [comment]
Should be fixed now. Please ping the issue if you see it again.
