### ISSUE TITLE
cloud_to_cloud:ruby:node_server test failures

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#13421]
https://sponge.corp.google.com/target?id=fa4d7a6b-d97a-45b7-804f-f648640ae262&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

There are several tests failing, but they all look related.  Here's the output from the cloud_to_cloud:ruby:node_server:unimplemented_method test:

```
Failure
src/ruby/pb/test/client.rb:508:in `rescue in unimplemented_method': Expected BadStatus. Received: #<GRPC::Unavailable: 14:Connect Failed> (AssertionError)
	from src/ruby/pb/test/client.rb:503:in `unimplemented_method'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-11-16T19:23:44.585504 #73]  INFO -- : ... connecting securely to localhost:32768
```

**Comment by murgatroid99** [comment]
This should be fixed by grpc/grpc-node#95.
