### ISSUE TITLE
several cloud_to_cloud:ruby:node_server scenarios failing consistently

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13471]
https://sponge.corp.google.com/target?id=62a92114-e7c7-4e13-bc75-4335389d55d2&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

scenarios:
cloud_to_cloud:ruby:node_server:unimplemented_method 
cloud_to_cloud:ruby:node_server:custom_metadata
cloud_to_cloud:ruby:node_server:status_code_and_message 
cloud_to_cloud:ruby:node_server:unimplemented_service
cloud_to_cloud:ruby:node_server:timeout_on_sleeping_server 

```
Failure
src/ruby/pb/test/client.rb:508:in `rescue in unimplemented_method': Expected BadStatus. Received: #<GRPC::Unavailable: 14:Connect Failed> (AssertionError)
	from src/ruby/pb/test/client.rb:503:in `unimplemented_method'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-11-17T19:55:27.650709 #71]  INFO -- : ... connecting securely to localhost:32768
```

**Comment by jtattermusch** [comment]
I actually don't see these failures anymore (on last X builds on master).
