### ISSUE TITLE
Ruby: Problems establishing secure connection

### ISSUE THREAD

**Issue by davissp14** [grpc/grpc#13501]
grpc version: 1.7.2
OS: MacOS High Sierra

I am getting `Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.` every time I try and connect securely to a locally run Etcd v3 instance.  

I am able to use `curl` and the `etcdctl` just fine, but I am unable to connect using  `GRPC::Core::ChannelCredentials`. 

**Steps:** 

1. I generated certificates using the following documentation: 
https://coreos.com/os/docs/latest/generate-self-signed-certificates.html
_Note: No peer certificates are being used_

2. Spun up an Etcd node specifying the cert, key and ca. 
```
etcd  --name=node --initial-advertise-peer-urls=http://127.0.0.1:2380 --listen-peer-urls=http://127.0.0.1:2380 --listen-client-urls=https://127.0.0.1:2379 --advertise-client-urls=https://127.0.0.1:2379 --initial-cluster=node=http://127.0.0.1:2380  --cert-file=spec/fixtures/cert.pem --key-file=spec/fixtures/key.pem --trusted-ca-file=spec/fixtures/cacert.pem
```

3. Tested the connection using the etcdctl and curl:
```
ETCDCTL_API=3 etcdctl put name test  --endpoints='https://127.0.0.1:2379' --cacert spec/fixtures/cacert.pem --cert spec/fixtures/cert.pem --key spec/fixtures/key.pem
OK

curl --cacert spec/fixtures/cacert.pem --cert spec/fixtures/cert.pem --key spec/fixtures/key.pem https://127.0.0.1:2379/metrics
[metrics data]
```

4. Use grpc to securely connect.
```
files = ['spec/fixtures/cacert.pem', 'spec/fixtures/key.pem', 'spec/fixtures/cert.pem']
certs = files.map { |f| File.open(f).read }
creds = GRPC::Core::ChannelCredentials.new(*certs)
stub = Etcdserverpb::Maintenance::Stub.new('127.0.0.1:2379', creds)
stub.status(Etcdserverpb::StatusRequest.new)

E1125 07:53:34.467619000 123145402527744 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
GRPC::Unavailable: 14:Connect Failed
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:180:in `attach_status_results_and_complete_call'
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:372:in `request_response'
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
	from /Users/shaun/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.7.2-universal-darwin/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from (irb):8
	from /Users/shaun/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'

```

I'm hoping it's just a small detail i'm missing...

Any ideas what's going on?

**Comment by apolcyn** [comment]
@davissp14 trying to reproduce but stumbling a little bit when trying to follow those directions to generate certs in the way you did.

Are you able to provide already-generated example certs to repro this? Or maybe a script or docker file that builds dependencies and reproduces?

**Comment by davissp14** [comment]
Yeah, definitely.  I'll try and get something together today or tomorrow.

**Comment by vishnuvntcr** [comment]
Kindly provide some suggestions or solution for the above SSL connection issue with grpc using ruby

**Comment by apolcyn** [comment]
To investigate this, please provide a repro that can be easily ran, e.g. in the form of a script
