### ISSUE TITLE
Unable to install due to missing ObjectHandling.c

### ISSUE THREAD

**Issue by levelxplane** [grpc/grpc#13738]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 No
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
grpcio-1.7.3. Python 2.7
 
 
### What operating system (Linux, Windows, …) and version?
LLinux b6ad6eb9d62c 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 Linux

google/cloud-sdk:alpine docker image.
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Alpine 6.2.1) 6.2.1 20160822
Python 2.7.13

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
From Dockerfile
```
RUN apk upgrade --update
RUN apk add curl vim py-pip python-dev gcc linux-headers make musl-dev cython

RUN pip install pprint pymongo pyyaml pycrypto
RUN pip install grpcio
# RUN pip install --upgrade google-cloud-datastore
```

Trying to install grpcio via pip manually.
 
### What did you expect to see?
Google.Cloud Datastore to install without any issues.
 
 
### What did you see instead?
Google.Cloud Datastore SDK failing to install because of grpc.io
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
Collecting grpcio
  Using cached grpcio-1.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Found cython-generated files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_1Tkpk/grpcio/setup.py", line 226, in <module>
        CYTHON_EXTENSION_MODULES, need_cython = cython_extensions_and_necessity()
      File "/tmp/pip-build-_1Tkpk/grpcio/setup.py", line 224, in cython_extensions_and_necessity
        return commands.try_cythonize(extensions, linetracing=ENABLE_CYTHON_TRACING, mandatory=BUILD_WITH_CYTHON), need_cython
      File "/tmp/pip-build-_1Tkpk/grpcio/src/python/grpcio/commands.py", line 241, in try_cythonize
        compiler_directives=cython_compiler_directives)
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 800, in cythonize
        ctx = c_options.create_context()
      File "/usr/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 582, in create_context
        self.cplus, self.language_level, options=self)
      File "/usr/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 75, in __init__
        from . import Builtin, CythonScope
      File "/usr/lib/python2.7/site-packages/Cython/Compiler/Builtin.py", line 16, in <module>
        iter_next_utility_code = UtilityCode.load("IterNext", "ObjectHandling.c")
      File "Cython/Compiler/Code.py", line 256, in Cython.Compiler.Code.UtilityCodeBase.load (/home/buildozer/aports/main/cython/src/cython-0.25.1/Cython/Compiler/Code.c:9556)
      File "Cython/Compiler/Code.py", line 180, in Cython.Compiler.Code.UtilityCodeBase.load_utilities_from_file (/home/buildozer/aports/main/cython/src/cython-0.25.1/Cython/Compiler/Code.c:7108)
      File "/usr/lib/python2.7/site-packages/Cython/Utils.py", line 306, in open_source_file
        encoding=encoding, errors=error_handling)
    IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/Cython/Utility/ObjectHandling.c'
```

 
### Anything else we should know about your project / environment?

I mentioned before, but this is an alpine image, so no access to yum or apt.

**Comment by levelxplane** [comment]
Nevermind. Turns out using cython-dev and alpine-sdk fixes the issue.
