### ISSUE TITLE
Error building with grpc_node_plugin

### ISSUE THREAD

**Issue by jamesjwarren** [grpc/grpc#13750]
### What version of gRPC and what language are you using?
Node.js
 
### What operating system (Linux, Windows, …) and version?
Linux alpine 3.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Running in a docker container with node 9.1 and alpine.
```
FROM node:9.1-alpine

RUN apk update && apk add \
    build-base \
    linux-headers \
    make \
    git \
    protobuf \
    protobuf-dev

RUN npm --global install ts-protoc-gen
RUN npm --global install --unsafe-perm grpc-tools
```
 
### What did you do?

```
> protoc -I .:/usr/local/include  --js_out=import_style=commonjs,binary:./codegen/ts --ts_out=service=true:./codegen/ts --grpc_out=./codegen/ts --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` helloworld/helloworld.proto
```
 
### What did you expect to see?
Successful protobuff codegen
 
### What did you see instead?
```
/usr/local/lib/node_modules/grpc-tools/bin/protoc_plugin.js:37
    throw error;
    ^

Error: spawn /usr/local/lib/node_modules/grpc-tools/bin/grpc_node_plugin ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
make: *** [Makefile:47: helloworld/helloworld.proto] Error 1
```

**Comment by jamesjwarren** [comment]
Resolved this error by moving to a debian base image.

**Comment by mehrdada** [comment]
Closing the issue as resolved.
