### ISSUE TITLE
runt_tests.py cannot find big_query_utils

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc#13804]
```
Unexpected error getting flaky tests: Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1230, in <module>
    for test in get_bqtest_data():
  File "tools/run_tests/run_tests.py", line 75, in get_bqtest_data
    import big_query_utils
  File "/home/notcarl/git/grpc/tools/gcp/utils/big_query_utils.py", line 21, in <module>
    from apiclient import discovery
ImportError: No module named apiclient
```

cc @jtattermusch

**Comment by jtattermusch** [comment]
The error message gets printed to indicate it there was an error getting the list of flaky tests, but run_tests.py actually continues running without a problem.
