### ISSUE TITLE
Checksum issue downloading node-js

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#13945]
```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 502 status code downloading checksum
gyp ERR! stack     at Request.<anonymous> (/root/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:289:18)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:191:7)
gyp ERR! stack     at Request.onRequestResponse (/root/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/request/request.js:986:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at TLSSocket.emit (events.js:191:7)
gyp ERR! System Linux 4.4.0-83-generic
gyp ERR! command "/root/.nvm/versions/node/v7.10.1/bin/node" "/root/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v51-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v51-linux-x64-glibc"
gyp ERR! cwd /var/local/git/grpc-node/packages/grpc-native-core
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v7.10.1/bin/node /root/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v51-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v51-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/local/git/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-83-generic
node-pre-gyp ERR! command "/root/.nvm/versions/node/v7.10.1/bin/node" "/var/local/git/grpc-node/packages/grpc-native-core/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /var/local/git/grpc-node/packages/grpc-native-core
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/root/.nvm/versions/node/v7.10.1/bin/node /root/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v51-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v51-linux-x64-glibc' (1)

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/root/.nvm/versions/node/v7.10.1/bin/node" "/root/.nvm/versions/node/v7.10.1/bin/npm" "install" "--build-from-source" "--unsafe-perm"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.9.0-dev install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.9.0-dev install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-cache/_logs/2018-01-06T03_04_42_921Z-debug.log
[03:04:42] 'native.core.install' errored after 2.96 s
[03:04:42] Error: Command failed: npm install --build-from-source --unsafe-perm
    at Promise.all.then.arr (/var/local/git/grpc-node/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[03:04:42] 'setup' errored after 2.97 s
[03:04:42] Error in plugin "run-sequence(native.core.install)"
Message:
    Command failed: npm install --build-from-source --unsafe-perm
Details:
    code: 1
    killed: false
    stdout: null
    stderr: null
    failed: true
    signal: null
    cmd: npm install --build-from-source --unsafe-perm
    timedOut: false
```
https://sponge.corp.google.com/invocation?id=5cfe9ba8-2cf8-4298-bb9b-66d711c1d8f2&searchFor=

**Comment by jtattermusch** [comment]
Related to https://github.com/grpc/grpc/issues/13945.

**Comment by murgatroid99** [comment]
This doesn't seem to have happened again since then.
