### ISSUE TITLE
tools/run_tests/helper_scripts/run_grpc-node.sh is flaky on both macos and linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14234]
Currently failing 6% of our macos dbg builds and flaking on linux too.

Recent mac failures (all dbg):
https://sponge.corp.google.com/invocation?id=24ec39a3-3f1c-46fa-bfc3-8b44e80dee81
https://sponge.corp.google.com/invocation?id=12cb3013-c824-43bc-aa18-c2d83e348568
https://sponge.corp.google.com/invocation?id=2e8305e9-47a0-4fc1-9238-82371b99b901

Recent linux failures (all dbg):
https://sponge.corp.google.com/invocation?id=9935ab4f-0a02-4923-a4c3-e7190afd0a19
https://sponge.corp.google.com/invocation?id=6568a50f-7893-44d8-a5c9-48cc5478a6da

**Comment by jtattermusch** [comment]
It seems to boil down to occasional failures when downloading packages
On Mac:
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/Users/kbuilder/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (/Users/kbuilder/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/request/request.js:878:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/kbuilder/.nvm/versions/node/v8.9.4/bin/node" "/Users/kbuilder/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-darwin-x64-unknown"
gyp ERR! cwd /Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-native-core
```

On Linux:
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 response downloading https://nodejs.org/dist/v8.9.4/node-v8.9.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/request/request.js:1068:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Linux 4.4.0-83-generic
gyp ERR! command "/root/.nvm/versions/node/v8.9.4/bin/node" "/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/var/local/git/grpc-node/packages/grpc-native-core/src/node/extension_binary/node-v57-linux-x64-glibc"
gyp ERR! cwd /var/local/git/grpc-node/packages/grpc-native-core
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by jtattermusch** [comment]
@murgatroid99 , what can we do to increase build robustness?

**Comment by jtattermusch** [comment]
@murgatroid99  is this on your radar?

**Comment by murgatroid99** [comment]
This looks like a network failure when downloading external resources that are required for the tests. There is only so much we can do about failures like that. And it's difficult to programmatically distinguish between that and a compilation failure, so I don't know if we want to just blindly retry.

**Comment by jtattermusch** [comment]
I understand this issue is pain to deal with, but currently the flakiness is a bit too high and we should figure out something. 
Is there a way we can isolate the "prepare" commands (that download and install the prerequisites) from the actual build of our code and only retry the first group?

**Comment by jtattermusch** [comment]
Still seeing this (and still on the list of our top few flakes).
https://sponge.corp.google.com/invocation?tab=Build+Log&id=f91bec72-924f-4657-a3c2-088f398ccb11

We really ought to fix this somehow, we can't have this failing forever.

@matt-kwong , do you have any ideas how we could reduce the flakiness rate?

**Comment by murgatroid99** [comment]
The linked PR will hopefully decrease the frequency of this failure. Until we know what the impact of that PR is I am going to downgrade this to a P2.
