### ISSUE TITLE
Build instructions don't work on ARM, HelloWorld example segfaults

### ISSUE THREAD

**Issue by whiplash86** [grpc/grpc#14391]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
 1.9.1
C++
 
### What operating system (Linux, Windows, …) and version?
 Linux tegra-ubuntu 4.4.38 aarch64 ARM
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.4.0
 
### What did you do?

```
cloned tag v1.9.1
$ git submodule update --init
$ make
```

failed with:

```
/usr/bin/ld: /usr/local/lib/libprotobuf.a(descriptor.cc.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `__stack_chk_guard@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libprotobuf.a(descriptor.cc.o)(.text+0x15c): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `__stack_chk_guard@@GLIBC_2.17'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:5301: recipe for target '/home/username/grpc/libs/opt/libgrpc++_error_details.so.1.9.1' failed
make: *** [/home/username/grpc/libs/opt/libgrpc++_error_details.so.1.9.1] Error 1
```

```
$ cd test/distrib/cpp
$ sudo ./run_distrib_test_cmake.sh
```

failed with:

```
W: The repository 'http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ftp.debian.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553  NO_PUBKEY 7638D0442B90D010
W: The repository 'http://ftp.debian.org/debian jessie-backports InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu/dists/xenial/main/binary-arm64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

after commenting out line 20-22 in run_distrib_test_cmake.sh everything builds and installs successfully.
 
```
$ cd examples/cpp/helloworld
$ make
```

failed with:

```
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_channel_next_get_info'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_mdelem_from_slices'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_metadata_batch_link_head'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_call_stack_ignore_set_pollset_or_pollset_set'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_channel_init_register_stage'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_channel_stack_builder_get_channel_arguments'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_exec_ctx_finish'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_log_if_error'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_channel_next_op'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_channel_stack_builder_prepend_filter'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_socket_mutator_to_arg'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_call_next_op'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_inproc_channel_create'
/usr/local/lib/libgrpc++.so: undefined reference to `grpc_call_log_batch'
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'greeter_client' failed
make: *** [greeter_client] Error 1
```

```
$ cd cmake/build
$ sudo cmake .
$ cmake --build .
```

HelloWorld example build successfully. If I now run the server and the client a few times, the client often segfaults, i.e.:

```
$ greeter_client
Segmentation fault (core dumped)
$ greeter_client
Greeter received: Hello world
*** Error in `greeter_client': munmap_chunk(): invalid pointer: 0x00000000006d9c30 ***
Aborted (core dumped)
```

gdb backtrace:

```
#0  __GI___libc_free (mem=0x6d9e10) at malloc.c:2967
#1  0x00000000005a41e8 in grpc_slice_intern_shutdown() ()
#2  0x0000000000594a8c in grpc_shutdown ()
#3  0x0000000000593834 in grpc::Channel::~Channel() ()
#4  0x00000000005938c4 in grpc::Channel::~Channel() ()
#5  0x00000000004a5208 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#6  0x00000000004a5064 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() ()
#7  0x00000000004a4cbc in std::__shared_ptr<grpc::ChannelInterface, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() ()
#8  0x00000000004a4cdc in std::shared_ptr<grpc::ChannelInterface>::~shared_ptr() ()
#9  0x00000000004a536c in helloworld::Greeter::Stub::~Stub() ()
#10 0x00000000004a53a4 in helloworld::Greeter::Stub::~Stub() ()
#11 0x00000000004a53d8 in std::default_delete<helloworld::Greeter::Stub>::operator()(helloworld::Greeter::Stub*) const ()
#12 0x00000000004a5190 in std::unique_ptr<helloworld::Greeter::Stub, std::default_delete<helloworld::Greeter::Stub> >::~unique_ptr() ()
#13 0x00000000004a5030 in GreeterClient::~GreeterClient() ()
#14 0x00000000004a4840 in main ()
```

### What did you expect to see?
All of the above working 
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ncteisen** [comment]
@jtattermusch can we set up ARM compilation on our VMs to repro this?

**Comment by whiplash86** [comment]
Hey,

I also wonder if there's some sort of performance issue with the ARM platform. I've tried transmitting 16 MByte of random data split into 2 kByte chunks from one node to another and measuring the total time the client takes to complete the RPC call. Between two Windows PCs (i7, 3.6 GHz) it takes around 150 ms corresponding to 109 MB/s whereas between a Jetson TX2 as a server and one of the Windows machines as client it dropps down to 200 ms at 80 MB/s which is quite far away from net Gigabit Ethernet performance. Yes, the Jetson's CPU is slower but is this reasonable?

**Comment by jtattermusch** [comment]
@ncteisen  I think the best we can do is to add ARM cross-compilation to our portability suite (can you provide the cmdline for that?). We currently don't have access to an actual ARM machine in our test platform.

**Comment by whiplash86** [comment]
@ncteisen any updates on this?
