### ISSUE TITLE
Deadlock when calling GoogleDefaultCredentials during dlopen'd shared object initialization

### ISSUE THREAD

**Issue by mestar99** [grpc/grpc#14418]
### What version of gRPC and what language are you using?
 v1.9.1 in C++
 
### What operating system (Linux, Windows, …) and version?
 Linux - Centos 7.4.1708
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
```
% g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-3/root/usr --mandir=/opt/rh/devtoolset-3/root/usr/share/man --infodir=/opt/rh/devtoolset-3/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)

% /lib64/libc.so.6 
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-16).
Compiled on a Linux 3.10.0 system on 2017-11-30.
Available extensions:
        The C stubs add-on version 2.1.2.
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
        RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```
 
### What did you do?
Shared object is being dlopen'd by main thread. The shared object has a constructor function which will call grpc::GoogleDefaultCredentials. 

```
% cat main.cpp

#include <cstdio>
#include <cstdlib>
#include <dlfcn.h>

int main()
{
  void *handle;

  handle = dlopen("libA.so", RTLD_NOW | RTLD_LOCAL | RTLD_DEEPBIND);
  if( !handle ) {
    fprintf(stderr, "%s\n", dlerror());
    exit(EXIT_FAILURE);
  }

  dlclose(handle);
  
  return 0;
}
```
```
% cat libA.cpp

#include <grpc++/grpc++.h>
#include <memory>
#include <cstdio>

extern "C" {
  
  static void initLibrary() __attribute__((constructor));

  void initLibrary()
  {
    printf("Library Init\n");

    std::shared_ptr< grpc::ChannelCredentials > creds = grpc::GoogleDefaultCredentials();

    printf("Library Init Finished\n");
  }
}
```
```
% cat Makefile

all: libA.so
	g++ -o a.out -g -std=c++11 main.cpp -ldl -Wl,-rpath -Wl,'$$ORIGIN'

libA.so: libA.cpp
	g++ -shared -o libA.so -g -std=c++11 libA.cpp -fPIC -pthread -lgrpc++

```
 
### What did you expect to see?
 grpc::GoogleDefaultCredentials would complete quickly and program would continue
 
### What did you see instead?

If the environment variable or well-known credentials file is not set, it will attempt to check if it's running on google compute engine. This will involve a DNS lookup which, with glibc, will dlopen libnss_files, libnss_dns, etc. However, since we are already inside of a dlopen call, the DNS lookup will hang indefinitely waiting on glibc's dlopen lock to be released. 

The lock in dlopen is recursive so if the DNS lookup was inside the same thread as the GoogleDefaultCredentials call then it wouldn't have an issue with the lock

Here are the stack traces from gdb on each of the threads at the point of deadlock...

```
(gdb) info threads
  Id   Target Id         Frame 
  3    Thread 0x7ffff3762700 (LWP 6270) "grpc_global_tim" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  2    Thread 0x7ffff3f63700 (LWP 6269) "grpc_executor" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
* 1    Thread 0x7ffff7fdb740 (LWP 6265) "a.out" 0x00007ffff70ec923 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81

(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7fdb740 (LWP 6265))]
#0  0x00007ffff70ec923 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
81      T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)
(gdb) bt
#0  0x00007ffff70ec923 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff5cbc8b1 in do_epoll_wait (ps=0x613370, deadline=9223372036854775807) at src/core/lib/iomgr/ev_epoll1_linux.cc:651
#2  0x00007ffff5cbd84b in pollset_work (ps=0x613370, worker_hdl=0x7fffffffd188, deadline=9223372036854775807) at src/core/lib/iomgr/ev_epoll1_linux.cc:977
#3  0x00007ffff5cca387 in grpc_pollset_work (pollset=0x613370, worker=0x7fffffffd188, deadline=9223372036854775807) at src/core/lib/iomgr/ev_posix.cc:225
#4  0x00007ffff5d2198b in is_stack_running_on_compute_engine () at src/core/lib/security/credentials/google_default/google_default_credentials.cc:131
#5  0x00007ffff5d22077 in grpc_google_default_credentials_create () at src/core/lib/security/credentials/google_default/google_default_credentials.cc:252
#6  0x00007ffff6b811c7 in grpc::GoogleDefaultCredentials () at src/cpp/client/secure_credentials.cc:74
#7  0x00007ffff6df1e07 in initLibrary () at libA.cpp:14
#8  0x00007ffff7dea4c3 in call_init (env=0x7fffffffd948, argv=0x7fffffffd938, argc=1, l=<optimized out>) at dl-init.c:82
#9  _dl_init (main_map=main_map@entry=0x602050, argc=1, argv=0x7fffffffd938, env=0x7fffffffd948) at dl-init.c:131
#10 0x00007ffff7deebd6 in dl_open_worker (a=a@entry=0x7fffffffd608) at dl-open.c:560
#11 0x00007ffff7dea2d4 in _dl_catch_error (objname=objname@entry=0x7fffffffd5f8, errstring=errstring@entry=0x7fffffffd600, mallocedp=mallocedp@entry=0x7fffffffd5f0, 
    operate=operate@entry=0x7ffff7dee820 <dl_open_worker>, args=args@entry=0x7fffffffd608) at dl-error.c:177
#12 0x00007ffff7dee2cb in _dl_open (file=0x400890 "libA.so", mode=-2147483638, caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffffffd938, env=0x7fffffffd948)
    at dl-open.c:650
#13 0x00007ffff7bd7fbb in dlopen_doit (a=a@entry=0x7fffffffd810) at dlopen.c:66
#14 0x00007ffff7dea2d4 in _dl_catch_error (objname=0x7ffff7dda110 <last_result+16>, errstring=0x7ffff7dda118 <last_result+24>, mallocedp=0x7ffff7dda108 <last_result+8>, 
    operate=0x7ffff7bd7f60 <dlopen_doit>, args=0x7fffffffd810) at dl-error.c:177
#15 0x00007ffff7bd85bd in _dlerror_run (operate=operate@entry=0x7ffff7bd7f60 <dlopen_doit>, args=args@entry=0x7fffffffd810) at dlerror.c:163
#16 0x00007ffff7bd8051 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#17 0x00000000004007ad in main () at main.cpp:10

(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff3f63700 (LWP 6269))]
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135     2:      movl    %edx, %eax
(gdb) bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff6899de6 in _L_lock_870 () from /lib64/libpthread.so.0
#2  0x00007ffff6899cdf in __GI___pthread_mutex_lock (mutex=0x7ffff7ffd908 <_rtld_local+2312>) at ../nptl/pthread_mutex_lock.c:114
#3  0x00007ffff7dee25e in _dl_open (file=0x7ffff3f62230 "libnss_files.so.2", mode=-2147483647, caller_dlopen=0x7ffff70fe609 <__GI___nss_lookup_function+649>, nsid=-2, argc=1, 
    argv=0x7fffffffd938, env=0x7fffffffd948) at dl-open.c:596
#4  0x00007ffff7127a72 in do_dlopen (ptr=ptr@entry=0x7ffff3f62200) at dl-libc.c:87
#5  0x00007ffff7dea2d4 in _dl_catch_error (objname=0x7ffff3f621e0, errstring=0x7ffff3f621f0, mallocedp=0x7ffff3f621d0, operate=0x7ffff7127a30 <do_dlopen>, args=0x7ffff3f62200)
    at dl-error.c:177
#6  0x00007ffff7127b32 in dlerror_run (args=0x7ffff3f62200, operate=0x7ffff7127a30 <do_dlopen>) at dl-libc.c:46
#7  __GI___libc_dlopen_mode (name=name@entry=0x7ffff3f62230 "libnss_files.so.2", mode=mode@entry=-2147483647) at dl-libc.c:163
#8  0x00007ffff70fe609 in nss_load_library (ni=0x7fffec0012c0) at nsswitch.c:358
#9  __GI___nss_lookup_function (ni=0x7fffec0012c0, fct_name=fct_name@entry=0x7ffff7174414 "getservbyname_r") at nsswitch.c:455
#10 0x00007ffff70fe74e in __GI___nss_lookup (ni=ni@entry=0x7ffff3f62310, fct_name=fct_name@entry=0x7ffff7174414 "getservbyname_r", fct2_name=fct2_name@entry=0x0, 
    fctp=fctp@entry=0x7ffff3f62320) at nsswitch.c:189
#11 0x00007ffff70ff7f0 in __GI___nss_services_lookup2 (ni=ni@entry=0x7ffff3f62310, fct_name=fct_name@entry=0x7ffff7174414 "getservbyname_r", fct2_name=fct2_name@entry=0x0, 
    fctp=fctp@entry=0x7ffff3f62320) at XXX-lookup.c:75
#12 0x00007ffff7107b20 in __getservbyname_r (name=name@entry=0x7fffec000a00 "http", proto=proto@entry=0x7ffff716fb9e <gaih_inet_typeproto+30> "tcp", 
    resbuf=resbuf@entry=0x7ffff3f627b0, buffer=buffer@entry=0x7ffff3f62370 "", buflen=buflen@entry=1024, result=result@entry=0x7ffff3f627a0) at ../nss/getXXbyYY_r.c:254
#13 0x00007ffff70d11b4 in gaih_inet_serv (servicename=0x7fffec000a00 "http", tp=0x7ffff716fb94 <gaih_inet_typeproto+20>, st=st@entry=0x7ffff3f62830, req=0x7ffff3f62bf0)
    at ../sysdeps/posix/getaddrinfo.c:164
#14 0x00007ffff70d1b5e in gaih_inet (name=name@entry=0x7fffec0009d0 "metadata.google.internal", service=0x7ffff3f62a90, req=req@entry=0x7ffff3f62bf0, 
    pai=pai@entry=0x7ffff3f62a60, naddrs=naddrs@entry=0x7ffff3f62a50) at ../sysdeps/posix/getaddrinfo.c:332
#15 0x00007ffff70d55cd in __GI_getaddrinfo (name=0x7fffec0009d0 "metadata.google.internal", service=0x7fffec000a00 "http", hints=0x7ffff3f62bf0, pai=0x7ffff3f62c78)
    at ../sysdeps/posix/getaddrinfo.c:2431
#16 0x00007ffff5cccf81 in blocking_resolve_address_impl (name=0x6133e0 "metadata.google.internal", default_port=0x60c010 "http", addresses=0x60ddb0)
    at src/core/lib/iomgr/resolve_address_posix.cc:84
#17 0x00007ffff5ccd352 in do_request_thread (rp=0x614610, error=0x0) at src/core/lib/iomgr/resolve_address_posix.cc:158
#18 0x00007ffff5ccac66 in run_closures (list=...) at src/core/lib/iomgr/executor.cc:76
#19 0x00007ffff5ccb212 in executor_thread (arg=0x613870) at src/core/lib/iomgr/executor.cc:177
#20 0x00007ffff5d63b09 in thread_body (v=0x60b190) at src/core/lib/gpr/thd_posix.cc:67
#21 0x00007ffff6897e25 in start_thread (arg=0x7ffff3f63700) at pthread_create.c:308
#22 0x00007ffff70ec34d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

(gdb) thread 3
[Switching to thread 3 (Thread 0x7ffff3762700 (LWP 6270))]
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
238     62:     movq    %rax, %r14
(gdb) bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00007ffff5d6387f in gpr_cv_wait (cv=0x7ffff5fd5700 <g_cv_wait>, mu=0x7ffff5fd56c0 <_ZL4g_mu>, abs_deadline=...) at src/core/lib/gpr/sync_posix.cc:93
#2  0x00007ffff5cd9d2d in wait_until (next=3014) at src/core/lib/iomgr/timer_manager.cc:195
#3  0x00007ffff5cd9e67 in timer_main_loop () at src/core/lib/iomgr/timer_manager.cc:248
#4  0x00007ffff5cd9f41 in timer_thread (completed_thread_ptr=0x6130e0) at src/core/lib/iomgr/timer_manager.cc:277
#5  0x00007ffff5d63b09 in thread_body (v=0x617130) at src/core/lib/gpr/thd_posix.cc:67
#6  0x00007ffff6897e25 in start_thread (arg=0x7ffff3762700) at pthread_create.c:308
#7  0x00007ffff70ec34d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by ncteisen** [comment]
What is your use case for dlopen-ing a lib that calls GoogleDefaultCredentials?

**Comment by mestar99** [comment]
The library contains a logging stream static global variable which gets initialized when the shared object is loaded. The stream establishes the connection to Stackdriver Logging API during its constructor using the GoogleDefaultCredentials so it's ready to use after.

We were able to get around it by changing the static global variable into a static local variable inside of a getter function and replacing calls to the global variable with calls to the function. It still wouldn't be callable during library's constructor function though (although we aren't using that)

**Comment by jiangtaoli2016** [comment]
https://github.com/grpc/grpc/pull/15408 would resolve the deadlock.

**Comment by mestar99** [comment]
Thanks! This has been fixed with the latest GRPC version
