### ISSUE TITLE
Python Linux artifact build fails on Kokoro and Jenkins

### ISSUE THREAD

**Issue by mehrdada** [grpc/grpc#14496]
Artifact builds have started failing on master and 1.10.x (and on Jenkins). 

https://sponge.corp.google.com/invocation?id=ca340df2-5a17-496f-938b-e9169aabfcbd&searchFor=

Starting from my PR (which is a C# only PR and passed Artifact Linux before merge): https://github.com/grpc/grpc/pull/12613

Also the same SHA1 on master has passed the test, which is strange.

```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DGPR_MANYLINUX1=1 -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/opt/python/cp27-cp27m/include/python2.7 -c src/core/lib/security/credentials/iam/iam_credentials.cc -o python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/iam/iam_credentials.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DGPR_MANYLINUX1=1 -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -I/opt/python/cp27-cp27m/include/python2.7 -c src/core/lib/security/credentials/jwt/json_token.cc -o python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/jwt/json_token.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++ [enabled by default]
src/core/lib/security/credentials/jwt/json_token.cc: In function ‘char* compute_and_encode_signature(const grpc_auth_json_key*, const char*, const char*)’:
src/core/lib/security/credentials/jwt/json_token.cc:263:59: error: ‘EVP_DigestSignInit’ was not declared in this scope
   if (EVP_DigestSignInit(md_ctx, nullptr, md, nullptr, key) != 1) {
                                                           ^
src/core/lib/security/credentials/jwt/json_token.cc:267:60: error: ‘EVP_DigestSignUpdate’ was not declared in this scope
   if (EVP_DigestSignUpdate(md_ctx, to_sign, strlen(to_sign)) != 1) {
                                                            ^
src/core/lib/security/credentials/jwt/json_token.cc:271:52: error: ‘EVP_DigestSignFinal’ was not declared in this scope
   if (EVP_DigestSignFinal(md_ctx, nullptr, &sig_len) != 1) {
                                                    ^
src/core/lib/security/credentials/jwt/json_token.cc:276:48: error: ‘EVP_DigestSignFinal’ was not declared in this scope
   if (EVP_DigestSignFinal(md_ctx, sig, &sig_len) != 1) {
                                                ^
creating tmp
creating tmp/tmpmYxD1l
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DGPR_MANYLINUX1=1 -fPIC -I/opt/python/cp27-cp27m/include/python2.7 -c /tmp/tmpmYxD1l/a.c -o tmp/tmpmYxD1l/a.o
Traceback (most recent call last):
  File "setup.py", line 311, in <module>
    cmdclass=COMMAND_CLASS,
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 297, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 292, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/opt/python/cp27-cp27m/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/opt/python/cp27-cp27m/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
CompileError: command 'gcc' failed with exit status 1


```

**Comment by mehrdada** [comment]
@apolcyn do you think the header shuffling that went on in Core may have caused this?

**Comment by apolcyn** [comment]
Further up the log, I'm seeing these errors, which appear to be transient infrastructure flakes:

```
Entering 'third_party/abseil-cpp'
Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp) registered for path 'third_party/abseil-cpp'
Cloning into '/var/local/git/grpc/third_party/abseil-cpp'...
Submodule path 'third_party/abseil-cpp': checked out 'cc4bed2d74f7c8717e31f9579214ab52a9c9c610'
Entering 'third_party/benchmark'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Cloning into '/var/local/git/grpc/third_party/benchmark'...
fatal: unable to access 'https://github.com/google/benchmark/': SSL connect error
fatal: clone of 'https://github.com/google/benchmark' into submodule path '/var/local/git/grpc/third_party/benchmark' failed
Failed to clone 'third_party/benchmark'. Retry scheduled
Cloning into '/var/local/git/grpc/third_party/benchmark'...
fatal: unable to access 'https://github.com/google/benchmark/': SSL connect error
fatal: clone of 'https://github.com/google/benchmark' into submodule path '/var/local/git/grpc/third_party/benchmark' failed
Failed to clone 'third_party/benchmark' a second time, aborting
Stopping at 'third_party/benchmark'; script returned non-zero status.
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ docker cp build_and_run_docker_37e9a1bc-5026-4c76-8f3e-97811468e9e2:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
Error response from daemon: Could not find the file /var/local/git/grpc/artifacts in container build_and_run_docker_37e9a1bc-5026-4c76-8f3e-97811468e9e2
+ FAILED=true
+ docker rm -f build_and_run_docker_37e9a1bc-5026-4c76-8f3e-97811468e9e2
build_and_run_docker_37e9a1bc-5026-4c76-8f3e-97811468e9e2
+ '[' true '!=' '' ']'
+ exit 1

2018-02-22 11:19:27,143 FAILED: build_artifact.protoc_linux_x86 [ret=1, pid=9353, time=118.5sec]
```

for protoc build,

and this for what I think is during the python build:

```
+ docker run -e PIP=/opt/python/cp36-cp36m/bin/pip -e SETARCH_CMD=linux32 -e ARTIFACTS_OUT=artifacts/python_linux_x86_cp36-cp36m -e CFLAGS=-DGPR_MANYLINUX1=1 -e GRPC_BUILD_MANYLINUX_WHEEL=TRUE -e PYTHON=/opt/python/cp36-cp36m/bin/python -e GRPC_BUILD_GRPCIO_TOOLS_DEPENDENTS=TRUE -e RUN_COMMAND=tools/run_tests/artifacts/build_artifact_python.sh -e EXTERNAL_GIT_ROOT=/var/local/jenkins/grpc -e 'THIS_IS_REALLY_NEEDED=see https://github.com/docker/docker/issues/14203 for why docker is awful' -v /tmpfs/src/github/grpc:/var/local/jenkins/grpc:ro -w /var/local/git/grpc --name=build_and_run_docker_07255a60-d2af-4e64-bb87-b7f4fc96e0be grpctesting/grpc_artifact_python_manylinux_x86_3b9bca4a7b51e892d78f56d3f3bac8d4375808fa /bin/bash -l /var/local/jenkins/grpc/tools/run_tests/dockerize/docker_run.sh
+ '[' '' == '' ']'
+ mkdir -p /var/local/git
+ git clone /var/local/jenkins/grpc /var/local/git/grpc
Cloning into '/var/local/git/grpc'...
done.
+ cd /var/local/jenkins/grpc
+ git submodule foreach 'cd /var/local/git/grpc \
  && git submodule update --init --reference ${EXTERNAL_GIT_ROOT}/${name} \
  ${name}'
Entering 'third_party/abseil-cpp'
Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp) registered for path 'third_party/abseil-cpp'
Cloning into 'third_party/abseil-cpp'...
fatal: unable to access 'https://github.com/abseil/abseil-cpp/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Clone of 'https://github.com/abseil/abseil-cpp' into submodule path 'third_party/abseil-cpp' failed
Stopping at 'third_party/abseil-cpp'; script returned non-zero status.
```

**Comment by mehrdada** [comment]
@matt-kwong Looks like https://github.com/grpc/grpc/pull/14504 has fixed the issue on Kokoro, but Jenkins still faces an infra issue (similar to the older ones we faced that related to caching)

**Comment by mehrdada** [comment]
@matt-kwong nevermind, the error seems to have gone away on Jenkins too.
