### ISSUE TITLE
grpc-tools arm64 support 

### ISSUE THREAD

**Issue by iiSeymour** [grpc/grpc#14741]
### What version of gRPC and what language are you using?

Node 8, grpc 1.9.1, grpc-toos 1.6.6 
 
### What operating system (Linux, Windows, …) and version?

Ubuntu Linux 4.4.38 aarch64 (arm64 v8).
  
 
### What did you do?

Using the following `Dockerfile` and running `docker build .`

```
FROM arm64v8/node:8
RUN npm install grpc-tools
```

### What did you expect to see?
 
The package `grpc-tools` installed. 

### What did you see instead?
 
```
RUN npm install grpc-tools
 ---> Running in 29b80e5e1509

> grpc@1.9.1 install /node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm64-glibc/grpc_node.node" is installed via remote

> grpc-tools@1.6.6 install /node_modules/grpc-tools
> node-pre-gyp install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc-tools/v1.6.6/linux-arm64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/node_modules/grpc-tools/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:121:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/node_modules/grpc-tools/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! System Linux 4.4.38-tegra
node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /node_modules/grpc-tools
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc-tools/v1.6.6/linux-arm64.tar.gz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.6.6 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc-tools@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-18T14_33_53_596Z-debug.log
The command '/bin/sh -c npm install grpc-tools' returned a non-zero code: 1
```

**Comment by iiSeymour** [comment]
Adding debug log: [2018-03-18T14_33_53_596Z-debug.log](https://github.com/grpc/grpc/files/1822780/2018-03-18T14_33_53_596Z-debug.log)

**Comment by nicolasnoble** [comment]
I'm afraid this isn't something we will be able to provide easily, if at all.

Could you describe your usage case that would entice you to develop on an arm64 machine ?

**Comment by murgatroid99** [comment]
With no response in over a month, this is stale.
