### ISSUE TITLE
Segmentation fault when calculate memory usage

### ISSUE THREAD

**Issue by Everysick** [grpc/grpc#14808]
### Should this be an issue in the gRPC issue tracker?
yes

### What version of gRPC and what language are you using?
lang: ruby
gRPC gem: 1.10.0 and 1.11.0-dev (local build)
 
### What operating system (Linux, Windows, …) and version?
macOS 10.13.3
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
- ruby: 2.5.0p0
- gRPC: 1.11.0-dev
	- built by clang from master locally 
	- Apple LLVM version 9.0.0 (clang-900.0.39.2)
	- Target: x86_64-apple-darwin17.4.0
 
### What did you do?
I used `ObjectSpace.memsize_of_all` to get  the client's side memory usage at run time.

**server.rb**
```server.rb
# GreeterServer is simple server that implements the Helloworld Greeter server.

class GreeterService < Helloworld::Greeter::Service
  def say_hello(hello_req, _unused_call)
    Helloworld::HelloReply.new(message: "Hello #{hello_req.name}")
  end
end

def main
  s = GRPC::RpcServer.new
  s.add_http2_port('0.0.0.0:50051', :this_port_is_insecure)
  s.handle(GreeterService)
  s.run_till_terminated
end

main

```

**client.rb**
```client.rb
# GreeterServer is simple server that implements the Helloworld Greeter server.

def main
  loop do
    puts "#{ObjectSpace.memsize_of_all(GRPC::Core::MetadataArray)} byte"

    stub = Helloworld::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure)
    message = stub.say_hello(Helloworld::HelloRequest.new(name: 'world')).message

    sleep(0.2)
  end
end

main
```
 
### What did you expect to see?
got emory usage per `sleep(0.2)`.
 
### What did you see instead?
Segmentation fault.

```
client.rb:13: [BUG] Segmentation fault at 0x0000000000000005
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0009 p:---- s:0040 e:000039 CFUNC  :memsize_of
c:0008 p:0035 s:0035 e:000033 BLOCK  client.rb:13 [FINISH]
c:0007 p:---- s:0030 e:000029 CFUNC  :each_object
c:0006 p:0011 s:0026 e:000025 METHOD client.rb:11
c:0005 p:0052 s:0022 e:000021 BLOCK  client.rb:25 [FINISH]
c:0004 p:---- s:0017 e:000016 CFUNC  :loop
c:0003 p:0008 s:0013 e:000012 METHOD client.rb:21
c:0002 p:0102 s:0008 E:002260 EVAL   client.rb:36 [FINISH]
c:0001 p:0000 s:0003 E:000fb0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
client.rb:36:in `<main>'
client.rb:21:in `call_hello_world'
client.rb:21:in `loop'
client.rb:25:in `block in call_hello_world'
client.rb:11:in `print_call_metadata'
client.rb:11:in `each_object'
client.rb:13:in `block in print_call_metadata'
client.rb:13:in `memsize_of'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000005 rbx: 0x00007f826d330ec0 rcx: 0x0000000000000000
 rdx: 0x000000010bd6bcf8 rdi: 0x00007f826b63de58 rsi: 0x0000000000000001
 rbp: 0x00007ffee3f45b00 rsp: 0x00007ffee3f45b00  r8: 0x000000010bf43f90
  r9: 0x00007f826d871d50 r10: 0x0000000000000000 r11: 0x000000010c19e128
 r12: 0x0000000000000000 r13: 0x0000000000000000 r14: 0x0000000000000003
 r15: 0x0000000000000000 rip: 0x000000010c3ef219 rfl: 0x0000000000010206

-- C level backtrace information -------------------------------------------
0   ruby                                0x000000010bf58e49 rb_print_backtrace + 25
1   ruby                                0x000000010bf58f58 rb_vm_bugreport + 136
2   ruby                                0x000000010bd4b262 rb_bug_context + 450
3   ruby                                0x000000010be9d51e sigsegv + 94
4   libsystem_platform.dylib            0x00007fff695bbf5a _sigtramp + 26
5   grpc_c.bundle                       0x000000010c3ef219 md_ary_datasize + 73
6   ruby                                0x000000010bd6a21b rb_objspace_data_type_memsize + 91
7   ruby                                0x000000010bd6bd0b obj_memsize_of + 843
8   ruby                                0x000000010bd6b9ba rb_obj_memsize_of + 26
9   objspace.bundle                     0x000000010c3da329 memsize_of_m + 25
10  ruby                                0x000000010bf43fba call_cfunc_1 + 42
11  ruby                                0x000000010bf42d4d vm_call_cfunc_with_frame + 605
12  ruby                                0x000000010bf3e44d vm_call_cfunc + 173
13  ruby                                0x000000010bf2987e vm_exec_core + 8974
14  ruby                                0x000000010bf39016 vm_exec + 182
15  ruby                                0x000000010bf50638 invoke_block + 216
16  ruby                                0x000000010bf504a2 invoke_iseq_block_from_c + 434
17  ruby                                0x000000010bf5019e invoke_block_from_c_bh + 158
18  ruby                                0x000000010bf500eb vm_yield + 107
19  ruby                                0x000000010bf33a73 rb_yield_0 + 35
20  ruby                                0x000000010bf33a3c rb_yield_1 + 28
21  ruby                                0x000000010bf33ab4 rb_yield + 52
22  ruby                                0x000000010bd7e62b os_obj_of_i + 139
23  ruby                                0x000000010bd6a97c objspace_each_objects + 412
24  ruby                                0x000000010bd56fc5 rb_ensure + 245
25  ruby                                0x000000010bd6a6d6 rb_objspace_each_objects + 182
26  ruby                                0x000000010bd7e582 os_obj_of + 50
27  ruby                                0x000000010bd749cf os_each_obj + 159
28  ruby                                0x000000010bf43f5a call_cfunc_m1 + 42
29  ruby                                0x000000010bf42d4d vm_call_cfunc_with_frame + 605
30  ruby                                0x000000010bf3e44d vm_call_cfunc + 173
31  ruby                                0x000000010bf29459 vm_exec_core + 7913
32  ruby                                0x000000010bf39016 vm_exec + 182
33  ruby                                0x000000010bf50638 invoke_block + 216
34  ruby                                0x000000010bf504a2 invoke_iseq_block_from_c + 434
35  ruby                                0x000000010bf5019e invoke_block_from_c_bh + 158
36  ruby                                0x000000010bf500eb vm_yield + 107
37  ruby                                0x000000010bf33a73 rb_yield_0 + 35
38  ruby                                0x000000010bf51723 loop_i + 19
39  ruby                                0x000000010bd569d5 rb_rescue2 + 517
40  ruby                                0x000000010bf36024 rb_f_loop + 148
41  ruby                                0x000000010bf43f83 call_cfunc_0 + 35
42  ruby                                0x000000010bf42d4d vm_call_cfunc_with_frame + 605
43  ruby                                0x000000010bf3e44d vm_call_cfunc + 173
44  ruby                                0x000000010bf3d92e vm_call_method_each_type + 190
45  ruby                                0x000000010bf3d753 vm_call_method + 307
46  ruby                                0x000000010bf3d615 vm_call_general + 53
47  ruby                                0x000000010bf29459 vm_exec_core + 7913
48  ruby                                0x000000010bf39016 vm_exec + 182
49  ruby                                0x000000010bf39d8b rb_iseq_eval_main + 43
50  ruby                                0x000000010bd55d78 ruby_exec_internal + 232
51  ruby                                0x000000010bd55c81 ruby_exec_node + 33
52  ruby                                0x000000010bd55c40 ruby_run_node + 64
53  ruby                                0x000000010bcb5b0f main + 95

-- Other runtime information -----------------------------------------------

* Loaded script: client.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/enc/encdb.bundle
    5 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/enc/trans/transdb.bundle
    6 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb
    7 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/compatibility.rb
    8 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/defaults.rb
    9 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/deprecate.rb
   10 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/errors.rb
   11 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/version.rb
   12 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/requirement.rb
   13 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/platform.rb
   14 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/basic_specification.rb
   15 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/stub_specification.rb
   16 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/util/list.rb
   17 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/stringio.bundle
   18 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/specification.rb
   19 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/exceptions.rb
   20 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/dependency.rb
   21 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_gem.rb
   22 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb
   23 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb
   24 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems.rb
   25 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/path_support.rb
   26 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/version.rb
   27 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/core_ext/name_error.rb
   28 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/levenshtein.rb
   29 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/jaro_winkler.rb
   30 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checker.rb
   31 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/delegate.rb
   32 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   33 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   34 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   35 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   36 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
   37 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/formatters/plain_formatter.rb
   39 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean.rb
   40 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/version.rb
   41 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/compatibility_guard.rb
   42 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/pathname.bundle
   43 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/pathname.rb
   44 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/constants.rb
   45 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/util.rb
   46 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/user_interaction.rb
   47 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/etc.bundle
   48 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/config_file.rb
   49 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb
   50 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/current_ruby.rb
   51 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb
   52 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/fileutils/lib/fileutils.rb
   53 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendored_fileutils.rb
   54 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/errors.rb
   55 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/environment_preserver.rb
   56 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/plugin/api.rb
   57 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/plugin.rb
   58 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source/git.rb
   59 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source/installed.rb
   60 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source/specific_file.rb
   61 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source/local.rb
   62 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source/lock.rb
   63 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source/vendor.rb
   64 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/source.rb
   65 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/gem_helpers.rb
   66 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/match_platform.rb
   67 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/rubygems_ext.rb
   68 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/build_metadata.rb
   69 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb
   70 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/rfc2396_parser.rb
   71 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/rfc3986_parser.rb
   72 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/common.rb
   73 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/generic.rb
   74 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/ftp.rb
   75 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/http.rb
   76 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/https.rb
   77 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/ldap.rb
   78 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/ldaps.rb
   79 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/mailto.rb
   80 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri.rb
   81 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/settings.rb
   82 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/yaml_serializer.rb
   83 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/ext/builder.rb
   84 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/feature_flag.rb
   85 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source.rb
   86 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source/path.rb
   87 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source/git.rb
   88 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb
   89 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/lockfile_parser.rb
   90 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/set.rb
   91 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb
   92 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/dependency.rb
   93 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ruby_dsl.rb
   94 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/dsl.rb
   95 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source_list.rb
   96 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source/metadata.rb
   97 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/lazy_specification.rb
   98 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/index.rb
   99 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb
  100 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable/impl.rb
  101 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb
  102 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb
  103 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/source/gemspec.rb
  104 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/version.rb
  105 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui.rb
  106 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/silent.rb
  107 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/rg_proxy.rb
  108 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/text.rb
  109 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/util/licenses.rb
  110 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/remote_specification.rb
  111 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/compatibility.rb
  112 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb
  113 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb
  114 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/errors.rb
  115 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/action.rb
  116 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb
  117 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_vertex.rb
  118 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/delete_edge.rb
  119 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb
  120 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/set_payload.rb
  121 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/tag.rb
  122 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/log.rb
  123 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb
  124 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb
  125 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/state.rb
  126 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/modules/specification_provider.rb
  127 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/delegates/resolution_state.rb
  128 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
  129 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb
  130 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo/modules/ui.rb
  131 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/molinillo/lib/molinillo.rb
  132 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendored_molinillo.rb
  133 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver/spec_group.rb
  134 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver.rb
  135 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/gem_version_promoter.rb
  136 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb
  137 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/dep_proxy.rb
  138 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/stub_specification.rb
  139 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/endpoint_specification.rb
  140 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ruby_version.rb
  141 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb
  142 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb
  143 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/objspace.bundle
  144 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/grpc_c.bundle
  145 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/grpc.rb
  146 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/errors.rb
  147 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/logconfig.rb
  148 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/notifier.rb
  149 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/core/time_consts.rb
  150 /Users/everysick/.rbenv/versions/2.5.0/lib/ruby/2.5.0/weakref.rb
  151 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/bidi_call.rb
  152 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/active_call.rb
  153 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/client_stub.rb
  154 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/rpc_desc.rb
  155 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/service.rb
  156 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/rpc_server.rb
  157 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/interceptor_registry.rb
  158 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc/generic/interceptors.rb
  159 /Users/everysick/src/github.com/Everysick/grpc/src/ruby/lib/grpc.rb
  160 /Users/everysick/dev/grpc-test/vendor/bundle/ruby/2.5.0/gems/google-protobuf-3.5.1.2-universal-darwin/lib/google/protobuf/message_exts.rb
  161 /Users/everysick/dev/grpc-test/vendor/bundle/ruby/2.5.0/gems/google-protobuf-3.5.1.2-universal-darwin/lib/google/2.5/protobuf_c.bundle
  162 /Users/everysick/dev/grpc-test/vendor/bundle/ruby/2.5.0/gems/google-protobuf-3.5.1.2-universal-darwin/lib/google/protobuf/repeated_field.rb
  163 /Users/everysick/dev/grpc-test/vendor/bundle/ruby/2.5.0/gems/google-protobuf-3.5.1.2-universal-darwin/lib/google/protobuf.rb
  164 /Users/everysick/dev/grpc-test/lib/helloworld_pb.rb
  165 /Users/everysick/dev/grpc-test/lib/helloworld_services_pb.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

zsh: abort (core dumped)  bundle exec ruby client.rb
```
 
### Anything else we should know about your project / environment?

This SEGV is caused by the early release of `grpc_metadata_array` that wraped by [grpc_rb_md_ary_data_type](https://github.com/grpc/grpc/blob/baa14a975ef92ee6fb301f0e684f56f18f2c55a7/src/ruby/ext/grpc/rb_call.c#L118).

The entities of `grpc_metadata_array` owned by `run_batch_stack` is released after execution of `run_batch`. It does not consider ruby level's reference. When I use `ObjectSpace.memsize_of` for instance of  `GRPC::Core::MetadataArray`, we refer to `grpc_metadata_array` in [this function](https://github.com/grpc/grpc/blob/baa14a975ef92ee6fb301f0e684f56f18f2c55a7/src/ruby/ext/grpc/rb_call.c#L106). But the `grpc_metadata_array` had released, and SEGV occurs.

`grpc_rb_md_ary_data_type` was introduced by https://github.com/grpc/grpc/pull/1295.

I think dsize function poineter of `grpc_rb_md_ary_data_type` should be `GRPC_RB_MEMSIZE_UNAVAILABLE`. I wrote a patch. and I want to send it.

**Comment by apolcyn** [comment]
Marking this as fixed by https://github.com/grpc/grpc/pull/14809 - that patch will be in the 1.11 release (the first pre-release for 1.11 will probably be pushed within ~2 weeks).

**Comment by apolcyn** [comment]
thanks for filing and fixing!
