### ISSUE TITLE
Ruby: Unhandled GRPC::Core::CallError on streams

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#14853]
We are seeing streams under heavy load fail silently. This is because a GRPC::Core::CallError is being raised in a Ruby Thread used by the Ruby GRPC client. It closes the stream connection and we are unable to recover. The unhandled error in the Thread kills the thread. We do see one of the following errors printed to stderr:

```
$ /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:127:in `run_batch': call#run_batch failed somehow (GRPC::Core::CallError)
        from /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:127:in `read_using_run_batch'
        from /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:187:in `block in read_loop'
        from /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:184:in `loop'
        from /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:184:in `read_loop'
        from sub.rb:1:in `each'
```

```
$ /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:158:in `run_batch': call#run_batch failed somehow (GRPC::Core::CallError)
        from /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:158:in `write_loop'
        from /var/lib/gems/2.3.0/gems/grpc-1.10.0-x86_64-linux/src/ruby/lib/grpc/generic/bidi_call.rb:75:in `block in run_on_client'
```

If `Thread.abort_on_exception` is set to `true`, then the unhandled error is aborts the main thread, but we also cannot handle it.

It would be best if we could determine why the `GRPC::Core::CallError` is being raised and change the Ruby GRPC client to handle the behavior without raising. But, if that is not possible, it would be very helpful when using streams if the `GRPC::Core::CallError` was raised when `Enumerator#next` is called, so the streaming client code can properly handle the error.

This was brought to our attention in GoogleCloudPlatform/google-cloud-ruby#2011. The Pub/Sub Subscriber was originally written against the ruby grpc gem version 1.6. At the time, we tested long running processes handling a moderate amount of load on both a consumer internet connection and a GCE instance. Here is a chart that shows grpc 1.6.7 processing 2 million messages on a GCE instance in ~45 minutes.

<img width="541" alt="pubsub-grpc-1 6 7" src="https://user-images.githubusercontent.com/730/38057740-9a486ab2-329d-11e8-89fe-38501d158ad6.png">

When switching to grpc 1.7.0 (and later) we see the same behavior as reported in the google-cloud-ruby issue. The process will run for ~10 minutes and hang when `Thread.abort_on_exception` is set to `false`, and run for ~10 minutes and abort when `Thread.abort_on_exception` is set to `true`.

<img width="543" alt="pubsub-grpc-1 7 0" src="https://user-images.githubusercontent.com/730/38057744-9f129662-329d-11e8-818b-cbe100b07300.png">

I've annotated the image to show when the process was started and when it either aborts or hangs.

<img width="543" alt="pubsub-grpc-1 7 0-annotated" src="https://user-images.githubusercontent.com/730/38057755-a8de2440-329d-11e8-904f-eef538b13e32.png">

Here are the threads created when the process first starts:

```
top - 14:28:29 up 15:06,  2 users,  load average: 2.45, 0.98, 1.27
Threads:  22 total,   2 running,  20 sleeping,   0 stopped,   0 zombie
%Cpu(s): 98.3 us,  1.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3781968 total,   507604 free,   440616 used,  2833748 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3049584 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                         
16796 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.01 ruby_thread_po*                                 
16795 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.00 ruby_thread_po*                                 
16794 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.00 ruby_thread_po*                                 
16793 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.00 ruby_thread_po*                                 
16792 mike      20   0  849884 302080   9880 S  0.7  8.0   0:00.33 async_pusher.r*                                 
16791 mike      20   0  849884 302080   9880 S  5.6  8.0   0:04.62 ruby_thread_po*                                 
16790 mike      20   0  849884 302080   9880 S  5.6  8.0   0:04.86 ruby_thread_po*                                 
16789 mike      20   0  849884 302080   9880 S  6.0  8.0   0:04.82 ruby_thread_po*                                 
16788 mike      20   0  849884 302080   9880 R  6.3  8.0   0:04.75 ruby_thread_po*                                 
16787 mike      20   0  849884 302080   9880 S  6.0  8.0   0:04.85 ruby_thread_po*                                 
16786 mike      20   0  849884 302080   9880 S  6.0  8.0   0:05.02 ruby_thread_po*                                 
16785 mike      20   0  849884 302080   9880 S  6.0  8.0   0:04.73 ruby_thread_po*                                 
16784 mike      20   0  849884 302080   9880 R  6.6  8.0   0:04.69 ruby_thread_po*                                 
16783 mike      20   0  849884 302080   9880 S 47.5  8.0   0:09.52 stream.rb:317                                   
16782 mike      20   0  849884 302080   9880 S  2.7  8.0   0:02.25 stream.rb:234                                   
16781 mike      20   0  849884 302080   9880 S  0.3  8.0   0:00.20 bidi_call.rb:74                                 
16778 mike      20   0  849884 302080   9880 S  0.0  8.0   0:01.01 ruby                                            
16777 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.00 ruby                                            
16776 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.00 ruby                                            
16775 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.08 ruby                                            
16770 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.00 ruby-timer-thr                                  
16767 mike      20   0  849884 302080   9880 S  0.0  8.0   0:00.54 ruby                                            
```

Here are the threads just before the 10 minute mark.

```
top - 14:36:39 up 15:14,  2 users,  load average: 3.17, 2.80, 2.11
Threads:  23 total,   8 running,  15 sleeping,   0 stopped,   0 zombie
%Cpu(s): 98.3 us,  1.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3781968 total,   459956 free,   466144 used,  2855868 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3023780 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                         
16825 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.00 ruby                                            
16796 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.09 ruby_thread_po*                                 
16795 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.00 ruby_thread_po*                                 
16794 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.00 ruby_thread_po*                                 
16793 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.00 ruby_thread_po*                                 
16792 mike      20   0  864368 328464   9880 S  0.7  8.7   0:03.39 async_pusher.r*                                 
16791 mike      20   0  864368 328464   9880 R 12.7  8.7   0:50.10 ruby_thread_po*                                 
16790 mike      20   0  864368 328464   9880 S 11.7  8.7   0:50.36 ruby_thread_po*                                 
16789 mike      20   0  864368 328464   9880 R 11.3  8.7   0:50.12 ruby_thread_po*                                 
16788 mike      20   0  864368 328464   9880 R 13.0  8.7   0:50.66 ruby_thread_po*                                 
16787 mike      20   0  864368 328464   9880 R 10.7  8.7   0:50.17 ruby_thread_po*                                 
16786 mike      20   0  864368 328464   9880 S  7.6  8.7   0:49.86 ruby_thread_po*                                 
16785 mike      20   0  864368 328464   9880 S 12.0  8.7   0:49.68 ruby_thread_po*                                 
16784 mike      20   0  864368 328464   9880 S  9.0  8.7   0:49.88 ruby_thread_po*                                 
16783 mike      20   0  864368 328464   9880 S 20.3  8.7   1:45.90 stream.rb:317                                   
16782 mike      20   0  864368 328464   9880 R  5.0  8.7   0:24.10 stream.rb:234                                   
16781 mike      20   0  864368 328464   9880 S  0.3  8.7   0:02.26 bidi_call.rb:74                                 
16778 mike      20   0  864368 328464   9880 S  0.0  8.7   0:02.62 ruby                                            
16777 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.00 ruby                                            
16776 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.02 ruby                                            
16775 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.12 ruby                                            
16770 mike      20   0  864368 328464   9880 S  0.3  8.7   0:00.06 ruby-timer-thr                                  
16767 mike      20   0  864368 328464   9880 S  0.0  8.7   0:00.54 ruby                                            
```

Here are the threads just after the 10 minute mark when the process starts to hang. Messages are still being processed by the Ruby code, but the thread created by GRPC in `bidi_call.rb:74` has already crashed:

```
top - 14:37:39 up 15:15,  2 users,  load average: 3.26, 2.89, 2.19
Threads:  20 total,   0 running,  20 sleeping,   0 stopped,   0 zombie
%Cpu(s): 41.7 us,  0.3 sy,  0.0 ni, 58.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3781968 total,   504696 free,   418672 used,  2858600 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3071216 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                         
16825 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby                                            
16796 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.10 ruby_thread_po*                                 
16795 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby_thread_po*                                 
16794 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby_thread_po*                                 
16793 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby_thread_po*                                 
16792 mike      20   0  798832 285456   9880 S  0.3  7.5   0:03.76 async_pusher.r*                                 
16791 mike      20   0  798832 285456   9880 S  4.3  7.5   0:55.46 ruby_thread_po*                                 
16790 mike      20   0  798832 285456   9880 S  4.3  7.5   0:55.80 ruby_thread_po*                                 
16789 mike      20   0  798832 285456   9880 S  6.3  7.5   0:55.54 ruby_thread_po*                                 
16788 mike      20   0  798832 285456   9880 S  4.3  7.5   0:56.06 ruby_thread_po*                                 
16787 mike      20   0  798832 285456   9880 S  4.3  7.5   0:55.73 ruby_thread_po*                                 
16786 mike      20   0  798832 285456   9880 S  4.3  7.5   0:55.60 ruby_thread_po*                                 
16785 mike      20   0  798832 285456   9880 S  5.3  7.5   0:55.49 ruby_thread_po*                                 
16784 mike      20   0  798832 285456   9880 S  6.7  7.5   0:55.64 ruby_thread_po*                                 
16778 mike      20   0  798832 285456   9880 S  0.0  7.5   0:02.82 ruby                                            
16777 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby                                            
16776 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.03 ruby                                            
16775 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.12 ruby                                            
16770 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.06 ruby-timer-thr                                  
16767 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.54 ruby                                            
```

A couple minutes later all available messages have been processed and there is no more work to do. The process still runs, but there is no connection as the stream has silently failed.

```
top - 14:39:04 up 15:17,  2 users,  load average: 0.79, 2.17, 1.99
Threads:  20 total,   0 running,  20 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3781968 total,   503256 free,   420068 used,  2858644 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3069820 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                         
16825 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby                                            
16796 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.10 ruby_thread_po*                                 
16795 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby_thread_po*                                 
16794 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby_thread_po*                                 
16793 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby_thread_po*                                 
16792 mike      20   0  798832 285456   9880 S  0.0  7.5   0:03.76 async_pusher.r*                                 
16791 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.46 ruby_thread_po*                                 
16790 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.80 ruby_thread_po*                                 
16789 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.54 ruby_thread_po*                                 
16788 mike      20   0  798832 285456   9880 S  0.0  7.5   0:56.06 ruby_thread_po*                                 
16787 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.73 ruby_thread_po*                                 
16786 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.60 ruby_thread_po*                                 
16785 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.49 ruby_thread_po*                                 
16784 mike      20   0  798832 285456   9880 S  0.0  7.5   0:55.64 ruby_thread_po*                                 
16778 mike      20   0  798832 285456   9880 S  0.0  7.5   0:02.82 ruby                                            
16777 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.00 ruby                                            
16776 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.04 ruby                                            
16775 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.12 ruby                                            
16770 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.06 ruby-timer-thr                                  
16767 mike      20   0  798832 285456   9880 S  0.0  7.5   0:00.54 ruby                                            
```

We see this when the process is under heavy load. If the process has no messages to process, or only a few messages a minute, then it will run with no problems past the 10 minute mark.

The google-cloud-pubsub gem is setting the `grpc.keepalive_time_ms` arg to `300000` (5 minutes). We have seen this reliably across multiple ruby versions, on both Linux and OS X.

I've captured the [GRPC log output for both 1.7.2 and 1.10.0 here](https://gist.github.com/blowmage/2543e9b3d9bc0187170f977553de2999).

**Comment by blowmage** [comment]
We also [have a report](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2001#discussion_r177400490) that `GRPC::Core::CallError` is raised from _non-streaming_ calls that are also under heavy load. Those errors can be handled normally, as they are not raised in a different thread.

**Comment by apolcyn** [comment]
https://github.com/grpc/grpc/pull/14922 should stop raising `CallErrors` and start converting those failed read/write attempts into grpc-status-code-mapped errors (which involves more robust bidi call termination in the error case).

**Comment by apolcyn** [comment]
accidentally closed this. Leaving this open for now, so that we can verify it when 1.11.pre1 is released

**Comment by apolcyn** [comment]
FYI #14922 is in the 1.11.x branch and was just pushed in a pre-release, at version `1.11.0.pre2`.

**Comment by blowmage** [comment]
I've verified that version `1.11.0.pre2` does indeed stop raising `CallError`. An un-patched perf setup that would fail after ~10 minutes on previous `grpc` gems ran continually for 45+ minutes. Thanks!

**Comment by bchurchill** [comment]
Can confirm -- I'm developing a small system and was having similar problems with `CallError` being thrown  with 1.10.0.  I couldn't reproduce it consistently, but today I upgraded to 1.11.0.pre2 and haven't seen it since.

**Comment by apolcyn** [comment]
thanks for confirming! 1.11.0 was just pushed with the fix, so I'll mark this as fixed.
