### ISSUE TITLE
Building grpc for csharp c# fails with "ResponseNotReady"

### ISSUE THREAD

**Issue by AtosNicoS** [grpc/grpc#15100]
### What version of gRPC and what language are you using?
 1.11.0 c#
 
### What operating system (Linux, Windows, …) and version?
Arch Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.14
 
### What did you do?
I try to compile the c# nuget package as requested here: https://github.com/grpc/grpc/issues/8636#issuecomment-382278725 with this tutorial:
https://github.com/grpc/grpc/blob/master/src/csharp/README.md

I already fixed some of the compile errors, which I uploaded here as fix:
https://github.com/grpc/grpc/pull/15099
 
### What did you expect to see?
 The code compile.
 
### What did you see instead?
```bash
[nico@archlinuxpc grpc]$ python2 tools/run_tests/run_tests.py -c dbg -l csharp --build_only
Unexpected error getting flaky tests: Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1434, in <module>
    for test in get_bqtest_data():
  File "tools/run_tests/run_tests.py", line 74, in get_bqtest_data
    bq = big_query_utils.create_big_query()
  File "/home/user/git/grpc/tools/gcp/utils/big_query_utils.py", line 33, in create_big_query
    creds = GoogleCredentials.get_application_default()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 1271, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 1256, in _get_implicit_credentials
    credentials = checker()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 1187, in _implicit_credentials_from_gce
    if not _in_gce_environment():
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 1042, in _in_gce_environment
    if NO_GCE_CHECK != 'True' and _detect_gce_environment():
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 999, in _detect_gce_environment
    http, _GCE_METADATA_URI, headers=_GCE_HEADERS)
  File "/usr/lib/python2.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1693, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1433, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1389, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1108, in getresponse
    raise ResponseNotReady()
ResponseNotReady

WAITING: 2 queued, 1 jobs running, 0 complete, 0 failed (load 1.00) next: make @
++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
tools/run_tests/helper_scripts/pre_build_csharp.sh: line 21: dotnet: command not found
FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=127, pid=1129]
WAITING: 2 queued, 1 jobs running, 0 complete, 0 failed (load 1.00) next: make @
++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
tools/run_tests/helper_scripts/pre_build_csharp.sh: line 21: dotnet: command not found
FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=127, pid=1132]
WAITING: 2 queued, 1 jobs running, 0 complete, 0 failed (load 1.00) next: make @
++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
tools/run_tests/helper_scripts/pre_build_csharp.sh: line 21: dotnet: command not found
FAILED: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=127, pid=1135, time=0.0sec]
FAILED: Some tests failed
```
 
### Anything else we should know about your project / environment?
Its a fresh install, dependencies might be missing. I could not find any list of dependencies, please give me suggestions on how to fix it.

**Comment by jtattermusch** [comment]
Can you try running `run_tests.py` with an extra `--disable_auto_set_flakes` flag? According to the log, things are failing with `Unexpected error getting flaky tests`

**Comment by AtosNicoS** [comment]
This error is not gone. However I ran into several other issues. I also hat to install the dotnetsdk, initialize the submodules (otherwise I get a dependency cycle error for zlib) and disable the "First time experience", as my fallback nuget folder is write protected (in /opt).

I have [updated my PR](https://github.com/grpc/grpc/pull/15099) with the instructions so far, now I am stuck at the following error which I am unable to resolve:
```bash
[nico@archlinuxpc grpc]$ DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 python2 tools/run_tests/run_tests.py -c dbg -l csharp --build_only --disable_auto_set_flakes

++ dirname tools/run_tests/helper_scripts/build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ '[' dbg == gcov ']'
+ dotnet build --configuration Debug Grpc.sln
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34.43 ms for /home/user/git/grpc/src/csharp/Grpc.Auth/Grpc.Auth.csproj.
  Restore completed in 34.43 ms for /home/user/git/grpc/src/csharp/Grpc.Core.Testing/Grpc.Core.Testing.csproj.
  Restore completed in 1.31 ms for /home/user/git/grpc/src/csharp/Grpc.Examples.MathServer/Grpc.Examples.MathServer.csproj.
  Restore completed in 0.99 ms for /home/user/git/grpc/src/csharp/Grpc.Core.Tests/Grpc.Core.Tests.csproj.
  Restore completed in 0.51 ms for /home/user/git/grpc/src/csharp/Grpc.Core/Grpc.Core.csproj.
  Restore completed in 0.69 ms for /home/user/git/grpc/src/csharp/Grpc.Examples/Grpc.Examples.csproj.
  Restore completed in 0.68 ms for /home/user/git/grpc/src/csharp/Grpc.HealthCheck/Grpc.HealthCheck.csproj.
  Restore completed in 0.83 ms for /home/user/git/grpc/src/csharp/Grpc.HealthCheck.Tests/Grpc.HealthCheck.Tests.csproj.
  Restore completed in 1.33 ms for /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/Grpc.IntegrationTesting.Client.csproj.
  Restore completed in 1.05 ms for /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.QpsWorker/Grpc.IntegrationTesting.QpsWorker.csproj.
  Restore completed in 1.04 ms for /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Server/Grpc.IntegrationTesting.Server.csproj.
  Restore completed in 1.18 ms for /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.StressClient/Grpc.IntegrationTesting.StressClient.csproj.
  Restore completed in 5.55 ms for /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting/Grpc.IntegrationTesting.csproj.
  Restore completed in 0.79 ms for /home/user/git/grpc/src/csharp/Grpc.Microbenchmarks/Grpc.Microbenchmarks.csproj.
  Restore completed in 0.68 ms for /home/user/git/grpc/src/csharp/Grpc.Reflection/Grpc.Reflection.csproj.
  Restore completed in 0.82 ms for /home/user/git/grpc/src/csharp/Grpc.Reflection.Tests/Grpc.Reflection.Tests.csproj.
  Restore completed in 0.94 ms for /home/user/git/grpc/src/csharp/Grpc.Examples.MathClient/Grpc.Examples.MathClient.csproj.
  Restore completed in 0.87 ms for /home/user/git/grpc/src/csharp/Grpc.Examples.Tests/Grpc.Examples.Tests.csproj.
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Auth/Grpc.Auth.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Core/Grpc.Core.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Core.Testing/Grpc.Core.Testing.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Core.Tests/Grpc.Core.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples/Grpc.Examples.csproj]
  Grpc.Core -> /home/user/git/grpc/src/csharp/Grpc.Core/bin/Debug/netstandard1.5/Grpc.Core.dll
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples.Tests/Grpc.Examples.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples.MathClient/Grpc.Examples.MathClient.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples.MathServer/Grpc.Examples.MathServer.csproj]
  Grpc.Examples -> /home/user/git/grpc/src/csharp/Grpc.Examples/bin/Debug/netcoreapp1.0/Grpc.Examples.dll
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.HealthCheck/Grpc.HealthCheck.csproj]
  Grpc.Core.Testing -> /home/user/git/grpc/src/csharp/Grpc.Core.Testing/bin/Debug/netstandard1.5/Grpc.Core.Testing.dll
  Grpc.HealthCheck -> /home/user/git/grpc/src/csharp/Grpc.HealthCheck/bin/Debug/netstandard1.5/Grpc.HealthCheck.dll
  Grpc.Auth -> /home/user/git/grpc/src/csharp/Grpc.Auth/bin/Debug/netstandard1.5/Grpc.Auth.dll
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.HealthCheck.Tests/Grpc.HealthCheck.Tests.csproj]
  Grpc.Core.Tests -> /home/user/git/grpc/src/csharp/Grpc.Core.Tests/bin/Debug/netcoreapp1.0/Grpc.Core.Tests.dll
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/Grpc.IntegrationTesting.Client.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting/Grpc.IntegrationTesting.csproj]
  Grpc.Examples.MathServer -> /home/user/git/grpc/src/csharp/Grpc.Examples.MathServer/bin/Debug/netcoreapp1.0/Grpc.Examples.MathServer.dll
  Grpc.Examples.Tests -> /home/user/git/grpc/src/csharp/Grpc.Examples.Tests/bin/Debug/netcoreapp1.0/Grpc.Examples.Tests.dll
  Grpc.Examples.MathClient -> /home/user/git/grpc/src/csharp/Grpc.Examples.MathClient/bin/Debug/netcoreapp1.0/Grpc.Examples.MathClient.dll
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.QpsWorker/Grpc.IntegrationTesting.QpsWorker.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Server/Grpc.IntegrationTesting.Server.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.StressClient/Grpc.IntegrationTesting.StressClient.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Reflection/Grpc.Reflection.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Reflection.Tests/Grpc.Reflection.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Microbenchmarks/Grpc.Microbenchmarks.csproj]
  Grpc.IntegrationTesting -> /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting/bin/Debug/netcoreapp1.0/Grpc.IntegrationTesting.dll
  Grpc.Reflection -> /home/user/git/grpc/src/csharp/Grpc.Reflection/bin/Debug/netstandard1.5/Grpc.Reflection.dll
  Grpc.IntegrationTesting.Client -> /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/Grpc.IntegrationTesting.Client.dll
  Grpc.IntegrationTesting.StressClient -> /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.StressClient/bin/Debug/netcoreapp1.0/Grpc.IntegrationTesting.StressClient.dll
  Grpc.IntegrationTesting.QpsWorker -> /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.QpsWorker/bin/Debug/netcoreapp1.0/Grpc.IntegrationTesting.QpsWorker.dll
  Grpc.IntegrationTesting.Server -> /home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Server/bin/Debug/netcoreapp1.0/Grpc.IntegrationTesting.Server.dll
  Grpc.Microbenchmarks -> /home/user/git/grpc/src/csharp/Grpc.Microbenchmarks/bin/Debug/netcoreapp1.0/Grpc.Microbenchmarks.dll
  Grpc.HealthCheck.Tests -> /home/user/git/grpc/src/csharp/Grpc.HealthCheck.Tests/bin/Debug/netcoreapp1.0/Grpc.HealthCheck.Tests.dll
  Grpc.Reflection.Tests -> /home/user/git/grpc/src/csharp/Grpc.Reflection.Tests/bin/Debug/netcoreapp1.0/Grpc.Reflection.Tests.dll

Build FAILED.

/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Auth/Grpc.Auth.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Core/Grpc.Core.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Core.Testing/Grpc.Core.Testing.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Core.Tests/Grpc.Core.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples/Grpc.Examples.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples.Tests/Grpc.Examples.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples.MathClient/Grpc.Examples.MathClient.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Examples.MathServer/Grpc.Examples.MathServer.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.HealthCheck/Grpc.HealthCheck.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.HealthCheck.Tests/Grpc.HealthCheck.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/Grpc.IntegrationTesting.Client.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting/Grpc.IntegrationTesting.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.QpsWorker/Grpc.IntegrationTesting.QpsWorker.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.Server/Grpc.IntegrationTesting.Server.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.IntegrationTesting.StressClient/Grpc.IntegrationTesting.StressClient.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Reflection/Grpc.Reflection.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Reflection.Tests/Grpc.Reflection.Tests.csproj]
/opt/dotnet/sdk/2.1.103/Microsoft.Common.CurrentVersion.targets(1126,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/user/git/grpc/src/csharp/Grpc.Microbenchmarks/Grpc.Microbenchmarks.csproj]
    0 Warning(s)
    18 Error(s)

Time Elapsed 00:00:13.41
FAILED: tools/run_tests/helper_scripts/build_csharp.sh [ret=1, pid=14088, time=13.7sec]
FAILED: Some tests failed
```

**Comment by jtattermusch** [comment]
I'm sorry you're having trouble with building. I'm updating the build instructions in https://github.com/grpc/grpc/pull/15178.

About the other failures
- we should probably disable the `auto_set_flakes`  feature in run_tests.py by default.  I might do that in a separate PR.
- the "Reference assemblies not found" problem is actually  https://github.com/dotnet/sdk/issues/335 and it's a problem with dotnet SDK itself, not really a gRPC specific issue. We did our best to work around the problem here https://github.com/grpc/grpc/blob/246071a4e22d3d2ea19dad8714b19ef2dae5464a/src/csharp/Grpc.Core/Common.csproj.include#L23, but that workaround might not work for Arch Linux (I suspect you can fix it by providing the right `FrameworkPathOverride` value for your system)
- the problem with "First time experience" of dotnet SDK breaking your build seems to be a problem with dotnet SDK installation for Arch Linux being broken. I don't think it's reasonable to make our build instructions more convoluted to workaround a non-grpc specific problem on a single linux distribution.

I hope with modifying the workaround for https://github.com/dotnet/sdk/issues/335 you should be able to build successfully.

**Comment by AtosNicoS** [comment]
The problem was that I did not install mono. I am not sure why the .net framework/mono is required here, but now grpc builds. I expected it would just build with .net core.

Could you please give me a quick guidiance on how to use the final build in my (windows) c# solution for testing the uwp bug? Which files do I have to use?

**Comment by jtattermusch** [comment]
@AtosNicoS  you basically need to take Grpc.Core.dll (the C# assembly)  you just built after changing the C# core as instructed in https://github.com/grpc/grpc/issues/8636#issuecomment-382278725 and replacing the Grpc.Core.dll in the .nupkg file (the nupkg file is just a zipfile, so this should be doable) and then use the nupkg file for testing.  There might be other ways but I'll leave that up to you.
