### ISSUE TITLE
FLAKE testing._time_test.StrictRealTimeTest.test_call_at

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#15119]
Running       testing._time_test.StrictRealTimeTest.test_call_at
[95mTesting gRPC Python...
[0m[92mSUCCESS       testing._time_test.StrictRealTimeTest.test_call_at
[0mRunning       testing._time_test.StrictRealTimeTest.test_call_in
[92mSUCCESS       testing._time_test.StrictRealTimeTest.test_call_in
[0mRunning       testing._time_test.StrictRealTimeTest.test_cancel
[91mFAILURE       testing._time_test.StrictRealTimeTest.test_cancel
[0mRunning       testing._time_test.StrictRealTimeTest.test_many
[92mSUCCESS       testing._time_test.StrictRealTimeTest.test_many
[0mRunning       testing._time_test.StrictRealTimeTest.test_same_behavior_used_several_times
[92mSUCCESS       testing._time_test.StrictRealTimeTest.test_same_behavior_used_several_times
[0mRunning       testing._time_test.StrictRealTimeTest.test_sleep_for
[92mSUCCESS       testing._time_test.StrictRealTimeTest.test_sleep_for
[0mRunning       testing._time_test.StrictRealTimeTest.test_sleep_until
[92mSUCCESS       testing._time_test.StrictRealTimeTest.test_sleep_until
[0m7 tests finished:
	6 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]
Errors/Failures:
[91mtesting._time_test.StrictRealTimeTest.test_cancel[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "C:\Python35\Lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python35\Lib\unittest\case.py", line 601, in run
    testMethod()
  File "T:\src\github\grpc\workspace_python_windows_opt_native\src\python\grpcio_tests\tests\testing\_time_test.py", line 94, in test_cancel
    self.assertFalse(call_times, msg=_PATHOLOGICAL_SCHEDULING)
  File "C:\Python35\Lib\unittest\case.py", line 672, in assertFalse
    raise self.failureException(msg)
AssertionError: (1524117154.2802734,) is not false : pathological thread scheduling!
[1mstdout:[0m
[1mstderr:[0m
Unexpected successes: []
Test failure

https://source.cloud.google.com/results/invocations/2f5fbc7c-8466-4f42-b114-6f6e2cf4f32f/targets/github%2Fgrpc%2Fpython_windows_opt_native/tests

**Comment by jtattermusch** [comment]
I haven't seen any instances of this problem at all in historical data from upstream/master.  Closing for now.
