### ISSUE TITLE
gRPC Client.js error on starting the server.

### ISSUE THREAD

**Issue by benciuf** [grpc/grpc#15126]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 GRPC latest and NodeJS
 
### What operating system (Linux, Windows, …) and version?
Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 I run the node app.js command
app.js is the server configuration.
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
By running the command node app.js the following error ocurse:

 
### What did you expect to see?
 The server has to start.
 
### What did you see instead?
 The error:
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: Connect Failed
    at createStatusError (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:64:15)
    at ClientReadableStream._emitStatusIfDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:270:19)
    at ClientReadableStream._readsDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:236:8)
    at readCallback (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:296:12)
Emitted 'error' event at:
    at ClientReadableStream._emitStatusIfDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:271:12)
    at ClientReadableStream._readsDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:236:8)
    at readCallback (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:296:12)

 
### Anything else we should know about your project / environment?
It is a making of https://github.com/elaineo/Jellybean

**Comment by murgatroid99** [comment]
That error means that your client failed to connect to the server. Perhaps you don't have the correct address, or maybe they're not physically connected.

**Comment by benciuf** [comment]
Hi and thank you for your answer.
I am running the server and the client from the same raspberry. 
How do i check if my address are correct or they are phisically connected? Do i have to check if the port is open?

**Comment by murgatroid99** [comment]
If they're on the same physical machine, then the physical connection is not the problem. You should choose a port number, then bind your server to either `localhost:[port]` or `[::]:port`, then connect your client to `localhost:[port]`. If you are still having problems, you should make sure that you call both `server.bind` and `server.start`, and check the return value of `server.bind`. If it is successful, the return value will be the port number, otherwise, it will be 0.

**Comment by benciuf** [comment]
How can i call server.start and server.bind when the server is no starting, when the connection failed?
Or when?

Mon Apr 23 2018 18:47:04 GMT+0000 (UTC) Server is listening on port 8080
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: Connect Failed
    at createStatusError (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:64:15)
    at ClientReadableStream._emitStatusIfDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:270:19)
    at ClientReadableStream._readsDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:236:8)
    at readCallback (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:296:12)
Emitted 'error' event at:
    at ClientReadableStream._emitStatusIfDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:271:12)
    at ClientReadableStream._readsDone (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:236:8)
    at readCallback (/home/pi/Jellybean/jellybean-server/node_modules/grpc/src/client.js:296:12)

**Comment by murgatroid99** [comment]
OK, that output seems to indicate that your server is successfully binding to port 8080. Are you sure your client is trying to connect to `localhost:8080`?
