### ISSUE TITLE
System.InvalidOperationException in SendStatusFromServerAsync for csharp grpc server

### ISSUE THREAD

**Issue by Itfly** [grpc/grpc#15271]
### What version of gRPC and what language are you using?
 gRPC version: 1.11.0
 
### What operating system (Linux, Windows, …) and version?
 Linux docker
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 dotnet core 2.0
 
### What did you do?
Got exception when starting the gRPC server:
```
words_1  | 2018-05-04 07:00:07.828 +00:00 [Debug] [Microsoft.Extensions.Hosting.Internal.Host] [{ Id: 1 }] [ ] Hosting starting
words_1  | 2018-05-04 07:00:08.093 +00:00 [Debug] [Grpc.Core.Internal.UnmanagedLibrary] [{ Id: 1000 }] [ ] Attempting to load native library ""/app/runtimes/linux/native/libgrpc_csharp_ext.x64.so""
words_1  | 2018-05-04 07:00:08.271 +00:00 [Debug] [Grpc.Core.Internal.NativeExtension] [{ Id: 1000 }] [ ] gRPC native library loaded successfully.
words_1  | Application started. Press Ctrl+C to shut down.
words_1  | Hosting environment: Production
words_1  | Content root path: /app/
words_1  | 2018-05-04 07:00:08.782 +00:00 [Debug] [Microsoft.Extensions.Hosting.Internal.Host] [{ Id: 2 }] [ ] Hosting started
words_1  | 2018-05-04 07:00:17.296 +00:00 [Warning] [Grpc.Core.Server] [{ Id: 1000 }] [ ] Exception while handling RPC.
words_1  | System.InvalidOperationException: Operation is not valid due to the current state of the object.
words_1  |    at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
words_1  |    at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__4.MoveNext()
words_1  | --- End of stack trace from previous location where exception was thrown ---
words_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
words_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
words_1  |    at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()
```
This exception only throws when server processes the first two requests, and then the server works well

**Comment by jtattermusch** [comment]
I think this might have been the same problem as https://github.com/grpc/grpc/issues/13943?
