### ISSUE TITLE
`tools/buildgen/generate_projects.sh` fails in v1.11.0 on macOS

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc#15276]
### What version of gRPC and what language are you using?
 
v1.11.0, language not relevant
 
### What operating system (Linux, Windows, …) and version?
 
macOS 10.12.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Python 2.7 I think.
 
### What did you do?

Run `git submodule update --init`, then `tools/buildgen/generate_projects.sh` from the main `grpc` directory.
 
### What did you expect to see?
 
All project files are rebuilt.
 
### What did you see instead?
 
The following command line output:

    Traceback (most recent call last):
      File "src/boringssl/gen_build_yaml.py", line 153, in <module>
        generate_build_files.main([g])
      File "/Users/daniel/Documents/Xcode/Cloud/grpc/third_party/boringssl/util/generate_build_files.py", line 601, in main
        stdout=err_data)
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 181, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 168, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1025, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

With some caveman debugging I traced the error to `. tools/buildgen/generate_build_additions.sh`. Removing the line

      src/boringssl        \
 
makes the command run to completion.

**Comment by jtattermusch** [comment]
What is your `go` version? I had a similar problem (even for upstream/master and v1.12.x branch) and the tools/buildget/generate_build_additions.sh was getting stuck forever.

In my case, `go run third_party/boringssl/crypto/err/err_data_generate.go` was the root cause (go runtime was sometimes getting stuck and sometimes segfaulting which seems to be a bug in go runtime) - you can try it for yourself.

The solution is to updated your go runtime (mine was at go1.5 AFAIR) and the problem goes away - I'm reasonably sure you're seeing the same issue.
