### ISSUE TITLE
build_artifact.csharp_ext_windows_x64  is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15305]
https://source.cloud.google.com/results/invocations/80fb0b1e-163f-4281-996a-3f0fe783afd7/targets/github%2Fgrpc/tests

```
T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\csharp>dotnet restore Grpc.sln   || goto :error
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
System.IO.IOException: The process cannot access the file 'C:\Users\builder\.dotnet\2.1.3.dotnetFirstUseSentinel' because it is being used by another process.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.PrintFirstTimeUseNotice()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\csharp>echo Failed!
```

This is most likely due to dotnet's "first time experience" that hasn't been performed on kokoro windows image after installing dotnet.

**Comment by jtattermusch** [comment]
Workaround: we could set 
NUGET_XMLDOC_MODE=skip
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

**Comment by jtattermusch** [comment]
Seems fixed by https://github.com/grpc/grpc/pull/15306.
