### ISSUE TITLE
performance benchmarks: python build is broken

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15376]
Thanks to the build problem, all the 8core scenarios are being skipped currently. I think it's a similar problem we saw a while ago with basic and interop tests, but it hasn't been fixed for performance tests.

https://source.cloud.google.com/results/invocations/6954f3e4-0de4-4317-88b9-ed2613ba6add/log

```
+ ROOT=/home/kbuilder/performance_workspace/grpc
+ export 'CFLAGS=-I/home/kbuilder/performance_workspace/grpc/include -std=gnu99 -fno-wrapv '
+ CFLAGS='-I/home/kbuilder/performance_workspace/grpc/include -std=gnu99 -fno-wrapv '
+ export GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
++ is_linux
++ '[' '' '!=' Linux ']'
++ echo true
+ '[' true ']'
++ command -v ccache
+ '[' -x /usr/bin/ccache ']'
++ command -v gcc
+ '[' -x /usr/bin/gcc ']'
+ export 'CC=ccache gcc'
+ CC='ccache gcc'
+ python3.4 -m pip install virtualenv
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/ed/ea/e20b5cbebf45d3096e8138ab74eda139595d827677f38e9dd543e6015bdf/virtualenv-15.2.0-py2.py3-none-any.whl
Installing collected packages: virtualenv
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.4/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.4/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/lib/python3.4/shutil.py", line 109, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/site-packages/virtualenv.py'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

2018-05-15 04:24:45,807 FAILED: /home/kbuilder/performance_workspace/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=2, pid=32611, time=0.7sec]
2018-05-15 04:24:45,807 FAILED: Some tests failed

2018-05-15 04:24:45,820 FAILED: remote_host_build.grpc-kokoro-performance-client2-8core [ret=1, pid=6786, time=310.2sec]
```

**Comment by jtattermusch** [comment]
CC @mehrdada

**Comment by matt-kwong** [comment]
Should be fixed by #15396

cc @nathanielmanistaatgoogle

**Comment by jtattermusch** [comment]
This still seems to be a problem. Currently python benchmarks are not running, because the qps_workers fail to start:

```
Port server started successfully
++ dirname tools/run_tests/performance/run_worker_python.sh
+ cd tools/run_tests/performance/../../..
+ PYTHONPATH=src/python/grpcio_tests:src/python/gens
+ py27/bin/python src/python/grpcio_tests/tests/qps/qps_worker.py --driver_port=10500
tools/run_tests/performance/run_worker_python.sh: line 20: py27/bin/python: No such file or directory

2018-05-20 23:11:01,470 FAILED: qps_worker_python_0 [ret=127, pid=26302, time=900.4sec]
```

**Comment by jtattermusch** [comment]
This should help: https://github.com/grpc/grpc/pull/15477
