### ISSUE TITLE
Interop ALTS Tests Failing

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#15434]
https://source.cloud.google.com/results/invocations/85388509-906f-41fd-8505-0c1b4c77aed2/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

Log excerpt

```
2018-05-17 08:03:06,148 TIMEOUT: cloud_to_cloud:java:go_server:large_unary [pid=2176, time=189.2sec]
2018-05-17 08:03:06,451 START: cloud_to_cloud:go:go_server:large_unary
2018-05-17 08:03:06,454 I0517 15:00:00.529596764       1 client.cc:92]               Testing these cases: server_streaming
2018-05-17 08:03:06,455 TIMEOUT: cloud_to_cloud:c++:go_server:server_streaming [pid=4293, time=186.3sec]
2018-05-17 08:03:06,776 START: cloud_to_cloud:go:go_server:empty_unary
2018-05-17 08:03:06,780 I0517 15:00:06.321036952       1 client.cc:92]               Testing these cases: unimplemented_method
2018-05-17 08:03:06,780 TIMEOUT: cloud_to_cloud:c++:go_server:unimplemented_method [pid=4981, time=180.8sec]
2018-05-17 08:03:07,154 START: cloud_to_cloud:go:go_server:ping_pong
2018-05-17 08:03:07,158 I0517 15:00:00.735447911       1 client.cc:92]               Testing these cases: cancel_after_begin
2018-05-17 08:03:07,159 TIMEOUT: cloud_to_cloud:c++:go_server:cancel_after_begin [pid=4402, time=186.8sec]
2018-05-17 08:03:07,459 START: cloud_to_cloud:go:go_server:empty_stream
2018-05-17 08:03:07,463 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test status_code_and_message
2018-05-17 08:03:07,463 TIMEOUT: cloud_to_cloud:java:go_server:status_code_and_message [pid=2277, time=190.4sec]
2018-05-17 08:03:07,840 START: cloud_to_cloud:go:go_server:client_streaming
2018-05-17 08:03:07,844 I0517 15:00:00.284605679       1 client.cc:92]               Testing these cases: ping_pong
2018-05-17 08:03:07,845 TIMEOUT: cloud_to_cloud:c++:go_server:ping_pong [pid=4116, time=188.0sec]
2018-05-17 08:03:08,195 START: cloud_to_cloud:go:go_server:server_streaming
2018-05-17 08:03:08,200 PASSED: cloud_to_cloud:go:go_server:large_unary [time=1.7sec, retries=0:0]
2018-05-17 08:03:08,200 START: cloud_to_cloud:go:go_server:cancel_after_begin
2018-05-17 08:03:08,205 I0517 15:00:01.758384073       1 client.cc:92]               Testing these cases: status_code_and_message
2018-05-17 08:03:08,205 TIMEOUT: cloud_to_cloud:c++:go_server:status_code_and_message [pid=4811, time=186.8sec]
2018-05-17 08:03:08,561 START: cloud_to_cloud:go:go_server:cancel_after_first_response
2018-05-17 08:03:08,566 I0517 15:00:06.486966545       1 client.cc:92]               Testing these cases: unimplemented_service
2018-05-17 08:03:08,566 TIMEOUT: cloud_to_cloud:c++:go_server:unimplemented_service [pid=5004, time=182.4sec]
2018-05-17 08:03:08,943 START: cloud_to_cloud:go:go_server:timeout_on_sleeping_server
2018-05-17 08:03:08,948 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test cancel_after_first_response
2018-05-17 08:03:08,948 TIMEOUT: cloud_to_cloud:java:go_server:cancel_after_first_response [pid=2230, time=191.9sec]
2018-05-17 08:03:09,322 START: cloud_to_cloud:go:go_server:custom_metadata
2018-05-17 08:03:09,327 PASSED: cloud_to_cloud:go:go_server:empty_stream [time=1.9sec, retries=0:0]
2018-05-17 08:03:09,327 START: cloud_to_cloud:go:go_server:status_code_and_message
2018-05-17 08:03:09,331 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test unimplemented_service
2018-05-17 08:03:09,332 TIMEOUT: cloud_to_cloud:java:go_server:unimplemented_service [pid=3788, time=190.1sec]
2018-05-17 08:03:09,673 START: cloud_to_cloud:go:go_server:unimplemented_method
2018-05-17 08:03:09,677 I0517 15:00:01.568222470       1 client.cc:92]               Testing these cases: custom_metadata
```

**Comment by jiangtaoli2016** [comment]
It looks like all tests are failing. We did not change ALTS code recently.

**Comment by jiangtaoli2016** [comment]
It looks like there were some hiccups in test. Now the tests are passing
https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_alts

**Comment by apolcyn** [comment]
Seen again, but this time tests failed rather than timed out:

```
2018-06-18 09:59:28,904 WAITING: ETA 0.8 sec; 0 queued, 5 jobs running, 120 complete, 0 failed (load 5.00)
2018-06-18 09:59:29,060 I0618 16:59:28.356846280       1 client.cc:92]               Testing these cases: client_compressed_unary
E0618 16:59:28.683508775       1 interop_client.cc:146]      Error status code: 14 (expected: 0), message: Socket closed, debug string: {"created":"@1529341168.683339778","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"Socket closed","grpc_status":14}
2018-06-18 09:59:29,061 FAILED: cloud_to_cloud:c++:c++_server:client_compressed_unary [ret=139, pid=19230, time=1.1sec]
2018-06-18 09:59:29,062 WAITING: ETA 0.7 sec; 0 queued, 4 jobs running, 121 complete, 1 failed (load 4.00)
2018-06-18 09:59:29,063 I0618 16:59:28.476374859       1 client.cc:92]               Testing these cases: server_compressed_unary
E0618 16:59:28.688966382       1 interop_client.cc:146]      Error status code: 14 (expected: 0), message: Connect Failed, debug string: {"created":"@1529341168.688808662","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2673,"referenced_errors":[{"created":"@1529341168.688805320","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":210,"referenced_errors":[{"created":"@1529341168.688797861","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":641,"grpc_status":14,"referenced_errors":[{"created":"@1529341168.688716130","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":321,"referenced_errors":[{"created":"@1529341168.688714438","description":"Socket closed","fd":9,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":424,"grpc_status":14,"target_address":"ipv4:127.0.0.1:32770"}]}]}]}]}
2018-06-18 09:59:29,063 FAILED: cloud_to_cloud:c++:c++_server:server_compressed_unary [ret=139, pid=19314, time=1.0sec]
2018-06-18 09:59:29,063 WAITING: ETA 0.5 sec; 0 queued, 3 jobs running, 122 complete, 2 failed (load 3.00)
2018-06-18 09:59:29,077 I0618 16:59:28.578622910       1 client.cc:92]               Testing these cases: server_compressed_streaming
E0618 16:59:28.688884298       1 interop_client.cc:579]      DoServerCompressedStreaming(): Responses read (k=0) is less than the expected number of  messages (2).
2018-06-18 09:59:29,078 FAILED: cloud_to_cloud:c++:c++_server:server_compressed_streaming [ret=139, pid=19350, time=0.9sec]
2018-06-18 09:59:29,078 WAITING: ETA 0.3 sec; 0 queued, 2 jobs running, 123 complete, 3 failed (load 2.00)
2018-06-18 09:59:29,083 I0618 16:59:28.527778251       1 client.cc:92]               Testing these cases: client_compressed_streaming
E0618 16:59:28.688935618       1 interop_client.cc:484]      DoClientCompressedStreaming(): stream->Write() failed
2018-06-18 09:59:29,084 FAILED: cloud_to_cloud:c++:c++_server:client_compressed_streaming [ret=139, pid=19340, time=1.0sec]
2018-06-18 09:59:29,084 WAITING: ETA 0.2 sec; 0 queued, 1 jobs running, 124 complete, 4 failed (load 1.00)
2018-06-18 09:59:29,123 I0618 16:59:28.753311297       1 client.cc:92]               Testing these cases: unimplemented_service
E0618 16:59:28.760891734       1 interop_client.cc:146]      Error status code: 14 (expected: 12), message: Connect Failed, debug string: {"created":"@1529341168.760735348","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2673,"referenced_errors":[{"created":"@1529341168.760732295","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":210,"referenced_errors":[{"created":"@1529341168.760725455","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":641,"grpc_status":14,"referenced_errors":[{"created":"@1529341168.760651809","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":321,"referenced_errors":[{"created":"@1529341168.760649675","description":"Socket closed","fd":9,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":424,"grpc_status":14,"target_address":"ipv4:127.0.0.1:32770"}]}]}]}]}
2018-06-18 09:59:29,123 FAILED: cloud_to_cloud:c++:c++_server:unimplemented_service [ret=139, pid=19619, time=0.7sec]
2018-06-18 09:59:29,123 FAILED: Some tests failed
```

https://source.cloud.google.com/results/invocations/bc75bb99-9484-48fb-b494-f8dab5c38b88/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

PR which was unrelated: https://github.com/grpc/grpc/pull/15377

**Comment by jiangtaoli2016** [comment]
running on master is all green
https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_alts
test flakiness?

**Comment by hcaseyal** [comment]
I got an interop failure on my PR #15879 in  cloud_to_cloud:java:go_server:ping_pong

![vpqaegjzck4](https://user-images.githubusercontent.com/8952658/41992541-9b9c963e-79fd-11e8-8899-a38502f4a9ea.png)

https://source.cloud.google.com/results/invocations/6b6dbbf3-192d-4b92-9c15-db4587a0a6fa/targets/github%2Fgrpc/tests

https://source.cloud.google.com/results/invocations/6b6dbbf3-192d-4b92-9c15-db4587a0a6fa/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

**Comment by jiangtaoli2016** [comment]
@hcaseyal Can you re-run the test? It looks tests are a little bit flaky. The master are green. 
https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_alts

**Comment by hcaseyal** [comment]
@jiangtaoli2016 I re-ran the test and it passes now on my PR. Looks like the test is flaky

**Comment by apolcyn** [comment]
saw:

```
2018-07-26 14:53:35,834 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test ping_pong
Exception in thread "main" java.lang.AssertionError: Timed out waiting for response
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at io.grpc.testing.integration.AbstractInteropTest.pingPong(AbstractInteropTest.java:726)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:256)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:199)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:68)
Shutting down
2018-07-26 14:53:35,834 FAILED: cloud_to_cloud:java:go_server:ping_pong [ret=1, pid=4388, time=7.0sec]
```

https://source.cloud.google.com/results/invocations/257a3252-9945-4b4e-9d5d-eb74c506952c/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

in PR: https://github.com/grpc/grpc/pull/16158

**Comment by jiangtaoli2016** [comment]
The kokoro ALTS interop test is occasionally flaky.

https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_alts

On master, it fails once every a few days. Root cause unknow.

**Comment by jtattermusch** [comment]
@jiangtaoli2016 FYI the link you posted is not accessible externally. It would be better to post a few recent builds with failures (which are public).
E.g.
https://source.cloud.google.com/results/invocations/2ccbd3ff-2362-4769-9d51-0b92fc97a5c1/targets (but that specific one turns out to be an infrastructure failure: `FAILED: build_docker_java [ret=1, pid=8794, time=80.5sec]`).

**Comment by jiangtaoli2016** [comment]
@jtattermusch Is there an external version of kokoro test result link on master?

ALTS interop tests are not 100% stable, after all, they are e2e tests. If failure once a while is annoying, we can disable such test on PR. We just need to run on master. If there are a few continuous failures on master, that will trigger us (security team) to take a look a root cause.

**Comment by jtattermusch** [comment]
@jiangtaoli2016   there's no public link for the job's history (the one you posted), but the individual test runs have public links (the ones starting with https://source.cloud.google.com).

As a side note, disabling a test on PRs is a bad idea because we want an early warning that something is being broken. Finding breakages after the fact costs way more time and effort (and sometimes takes long time to resolve).

**Comment by jtattermusch** [comment]
tests seem to be passing recently.
