### ISSUE TITLE
grpc-node_macos_opt_native and grpc-node_macos_dbg_native failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#15433]
Example:

https://source.cloud.google.com/results/invocations/93381198-f39f-46dd-bc71-9a9ed9778e1c/targets/github%2Fgrpc%2Fgrpc-node_macos_opt_native/tests

I think this is the relevant part of the log:

```
Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-health-check/node_modules/grpc/node_modules/node-pre-gyp/lib/node-pre-gyp.js:15:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/kbuilder/.nvm/versions/node/v4.9.1/bin/node" "/Users/kbuilder/.nvm/versions/node/v4.9.1/bin/npm" "install" "--unsafe-perm"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
```

**Comment by jtattermusch** [comment]
not happening anymore.
