### ISSUE TITLE
PHP failed to use closure in function to create credential

### ISSUE THREAD

**Issue by wenerme** [grpc/grpc#15441]
### What version of gRPC and what language are you using?

```
PHP 7.2.5 (cli) (built: Apr 26 2018 12:07:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies
``` 

GRPC 1.12.0
PB 3.5.2
 
### What operating system (Linux, Windows, …) and version?
 
macOS 10.13.4
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
PHP
 
### What did you do?

```php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Wener\Api;


$updateMetadata = function ($context) {
//    echo "CALL $context->service_url : $context->method_name" . PHP_EOL;
    return [];
};

function createCred(){
    $updateMetadata = function ($context) {
        return [];
    };
    $cred = Grpc\ChannelCredentials::createComposite(
        Grpc\ChannelCredentials::createSsl(file_get_contents('roots.pem')),
        Grpc\CallCredentials::createFromPlugin($updateMetadata));
    return $cred;
}

$cred = Grpc\ChannelCredentials::createComposite(
    Grpc\ChannelCredentials::createSsl(file_get_contents('roots.pem')),
    Grpc\CallCredentials::createFromPlugin($updateMetadata));

// This works
$client = new \Wener\Service\V1\InfoServiceClient("myservice.com:443", [
    'credentials' => $cred,
]);

list($reply, $status) = $client->GetInfo(new \Wener\Service\V1\GetInfoRequest())->wait();

// This not work
$client = new \Wener\Service\V1\InfoServiceClient("myservice.com:443", [
    'credentials' => createCred(),
]);

list($reply, $status) = $client->GetInfo(new \Wener\Service\V1\GetInfoRequest())->wait();
```
 
### What did you expect to see?
 
Works the same
 
### What did you see instead?
 
```
PHP Fatal error:  Uncaught Error: Cannot call overloaded function for non-object in /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php:44
Stack trace:
#0 /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php(44): Grpc\Call->startBatch(Array)
#1 /Workspace/vendor/grpc/grpc/src/lib/BaseStub.php(242): Grpc\UnaryCall->start(Object(Wener\Service\V1\GetInfoRequest), Array, Array)
#2 /Workspace/vendor/wen/wenapis/Wener/Service/V1/InfoServiceClient.php(31): Grpc\BaseStub->_simpleRequest('/Wener.servic...', Object(Wener\Service\V1\GetInfoRequest), Array, Array, Array)
#3 /Workspace/ignored/t3.php(39): Wener\Service\V1\InfoServiceClient->GetInfo(Object(Wener\Service\V1\GetInfoRequest))
#4 {main}
  thrown in /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php on line 44

Fatal error: Uncaught Error: Cannot call overloaded function for non-object in /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php:44
Stack trace:
#0 /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php(44): Grpc\Call->startBatch(Array)
#1 /Workspace/vendor/grpc/grpc/src/lib/BaseStub.php(242): Grpc\UnaryCall->start(Object(Wener\Service\V1\GetInfoRequest), Array, Array)
#2 /Workspace/vendor/wen/wenapis/Wener/Service/V1/InfoServiceClient.php(31): Grpc\BaseStub->_simpleRequest('/Wener.servic...', Object(Wener\Service\V1\GetInfoRequest), Array, Array, Array)
#3 /Workspace/ignored/t3.php(39): Wener\Service\V1\InfoServiceClient->GetInfo(Object(Wener\Service\V1\GetInfoRequest))
#4 {main}
  thrown in /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php on line 44
```
 
### Anything else we should know about your project / environment?

NO

**Comment by ZhouyihaiDing** [comment]
It's mostly likely cause by the life cycle of the function variable `$updateMetadata` you defined inside the function `createCred`. This variable is destroy after the function ends. 
We [save the pointer](https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/call_credentials.c#L122:3) for this variable  function variable instead of copying the whole function. As this pointer becomes invalid, I expect a `segment fault` when the call wants to fetch it.

Can you please try it by define `$updateMetadata` out of the function and passing it into the closure?
```
function createCred($updateMetadata){
    $cred = Grpc\ChannelCredentials::createComposite(
        Grpc\ChannelCredentials::createSsl(file_get_contents('roots.pem')),
        Grpc\CallCredentials::createFromPlugin($updateMetadata));
    return $cred;
}
```

**Comment by wenerme** [comment]
```php
// This works
$updateMetadata2 = function ($context) {
    return [];
};
function createCred()
{
    global $updateMetadata2;

    $cred = Grpc\ChannelCredentials::createComposite(
        Grpc\ChannelCredentials::createSsl(file_get_contents('roots.pem')),
        Grpc\CallCredentials::createFromPlugin($updateMetadata2));
    return $cred;
}

// This also works
$holder = [];
function createCred()
{
    global $holder;
    $updateMetadata2 = function ($context) {
        return [];
    };
    $holder[] = $updateMetadata2;
    $cred = Grpc\ChannelCredentials::createComposite(
        Grpc\ChannelCredentials::createSsl(file_get_contents('roots.pem')),
        Grpc\CallCredentials::createFromPlugin($updateMetadata2));
    return $cred;
}
```

I know how to write my helper function now, but the problem still exists.

```php
class MoreGrpc
{
    static private $_rootPem;
    static private $_holder = [];

    static function getRootPem()
    {
        if (self::$_rootPem == null) {
            $reflector = new ReflectionClass("Grpc\AbstractCall");
            $grpcDir = dirname(dirname(dirname($reflector->getFileName())));
            self::$_rootPem = file_get_contents("$grpcDir/etc/roots.pem");
        }

        return self::$_rootPem;
    }

    static function createCredentialWithAccessIdAndSecret($accessId, $accessSecret)
    {

        $updateMetadata = function ($context) use ($accessId, $accessSecret) {
            return ['x-access-id' => [$accessId], 'x-access-secret' => [$accessSecret]];
        };
        self::$_holder[] = $updateMetadata;

        $cred = Grpc\ChannelCredentials::createComposite(
            Grpc\ChannelCredentials::createSsl(self::getRootPem()),
            Grpc\CallCredentials::createFromPlugin($updateMetadata));

        return $cred;
    }
}
```

**Comment by ZhouyihaiDing** [comment]
By `the problem still exists`, do you mean the error `PHP Fatal error:  Uncaught Error: Cannot call overloaded function for non-object in /Workspace/vendor/grpc/grpc/src/lib/UnaryCall.php:44
Stack trace` still exists?
Have you tried assign the result of creating new credentials into a variable and then pass it to the stub?
```
$creds = createCred(); 
$client = new \Wener\Service\V1\InfoServiceClient("myservice.com:443", [
    'credentials' => $creds,
]);
```
If this still fail, please let me know. Thanks!

I wrote [a simple test case](https://gist.github.com/ZhouyihaiDing/42c6e793cd7ced7515298d9dc95c6691) which runs well under the grpc root directory:

**Comment by wenerme** [comment]
```php
// Still not work
// PHP Fatal error:  Uncaught Error: Cannot call overloaded function for non-object in /.../vendor/grpc/grpc/src/lib/UnaryCall.php:44

function createCred2()
{
    $updateMetadata = function ($context) {
        return [];
    };
    $cred = Grpc\ChannelCredentials::createComposite(
        Grpc\ChannelCredentials::createSsl(file_get_contents('roots.pem')),
        Grpc\CallCredentials::createFromPlugin($updateMetadata));
    return $cred;
}
$cred = createCred2();
$client = new \Yikaiye\Service\V1\InfoServiceClient("sms.ykyapis.com:443", [
    'credentials' => $cred,
]);
```

For `the problem still exists` I mean even I can use the workaround(use an array to hold the closure), but the original version should not failed, that's the problem.If this is by design, then just add a note about this will be fine.

**Comment by ZhouyihaiDing** [comment]
I checked php-src, and zend doesn't provide an API for me to make a copy of `zend_fcall_info_cache` and `zend_fcall_info` easily, as well as expend the life cycle of the object to cross the script.

I am working on adding documents for c extension recently. I will add notes for `createFromPlugin` method until we find a way to manage the `function` object.
