### ISSUE TITLE
python: Building the python module fails with: src/boringssl/err_data.c:17:10: fatal error: openssl/base.h: No such file or directory

### ISSUE THREAD

**Issue by toabctl** [grpc/grpc#15453]
### What version of gRPC and what language are you using?
 Latest git master version (bdbf04cde1f429787c41013071dea12c6ab2088e) and python 2.7.14
 
### What operating system (Linux, Windows, …) and version?
Linux, openSUSE Tumbleweed (version 20180516)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
- python 2.7.14
- gcc 7.3.1+r258812-3.4
- libopenssl-devel 1.1.0h-1.1
 
### What did you do?
I try to build the python module for python2. The ultimate goal is to build the module with the system shared libs (instead of the third party provided code).
But as a start, I did:
```
~/devel/grpc/grpc$ python setup.py build
Found cython-generated files...
running build
running build_py
running build_project_metadata
copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.linux-x86_64-2.7/grpc
copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.linux-x86_64-2.7/grpc/_cython/_credentials
running build_ext
Found cython-generated files...
building 'grpc._cython.cygrpc' extension
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c src/python/grpcio/grpc/_cython/cygrpc.cpp -o python_build/temp.linux-x86_64-2.7/src/python/grpcio/grpc/_cython/cygrpc.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread
cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c third_party/address_sorting/address_sorting.c -o python_build/temp.linux-x86_64-2.7/third_party/address_sorting/address_sorting.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C

[...snipped a lot of compiler output...]

gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c src/boringssl/err_data.c -o python_build/temp.linux-x86_64-2.7/src/boringssl/err_data.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
src/boringssl/err_data.c:17:10: fatal error: openssl/base.h: No such file or directory
 #include <openssl/base.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
creating tmp/tmps97ErI
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c /tmp/tmps97ErI/a.c -o tmp/tmps97ErI/a.o
Traceback (most recent call last):
  File "setup.py", line 310, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/tom/devel/grpc/grpc/src/python/grpcio/commands.py", line 297, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/home/tom/devel/grpc/grpc/src/python/grpcio/commands.py", line 292, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
CompileError: command 'gcc' failed with exit status 1
```

### What did you expect to see?
I expected that the python module sucessfully build
 
### What did you see instead?
A compiler error
 
 
### Anything else we should know about your project / environment?
How can I build the python module with the system libraries (zlib, openssl, ...) instead of using the third_party code? I did not found a way to do that.

**Comment by mehrdada** [comment]
@toabctl Should this be closed now that #15548 is merged?
