### ISSUE TITLE
ERROR: Connection reset by peer while running build_python.sh

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#15455]
https://source.cloud.google.com/results/invocations/e7ae4ca3-2e3a-4825-9285-d8ea45af7389/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_basictests_multilang/log

```
Successfully installed pip-10.0.1
+ case "$VENV" in
+ /var/local/git/grpc/py34_gevent/bin/python3.4 -m pip install gevent==1.3.b1
Collecting gevent==1.3.b1
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/e8/dd/d40d5156831422b4fc434a06c3a725c541c4dc8084e0840b44e878b6b2ed/gevent-1.3b1-cp34-cp34m-manylinux1_x86_64.whl (4.3MB)
Exception:
Traceback (most recent call last):
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_vendor/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_vendor/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/operations/prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/download.py", line 674, in unpack_http_url
    progress_bar)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/utils/hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/download.py", line 586, in written_chunks
    for chunk in chunks:
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/utils/ui.py", line 159, in iter
    for x in it:
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_internal/download.py", line 575, in resp_read
    decode_content=False):
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_vendor/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_vendor/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/local/git/grpc/py34_gevent/lib/python3.4/site-packages/pip/_vendor/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2018-05-18 17:05:48,186 FAILED: /var/local/git/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=2, pid=5744, time=7.8sec]
2018-05-18 17:05:48,186 FAILED: Some tests failed
```

**Comment by mehrdada** [comment]
Looks like a random network error when downloading packages in CI infra. Not seen in a while. Closing.
