### ISSUE TITLE
Segmentation Fault when running gevent-patched GRPC

### ISSUE THREAD

**Issue by fardog** [grpc/grpc#15615]
### What version of gRPC and what language are you using?
GRPC 1.12.0
 
### What operating system (Linux, Windows, …) and version?

Linux (Arch Linux x86_64)
output of `uname -a`
```
Linux belka 4.16.12-1-ARCH #1 SMP PREEMPT Fri May 25 23:30:31 UTC 2018 x86_64 GNU/Linux
```
However this issue was reproduced on a debian-based container running on a Google Compute instance also, so is not specific to this OS (but may be to 64-bit linux).

### What runtime / compiler are you using (e.g. python version or version of gcc)
* Python 3.6.5

This issue was also reproducible on Python 2.7.15 however all stacktraces you'll see in this report are from 3.6.5.
 
### What did you do?

Attempted to publish a message to Google Cloud Pubsub using the `google-cloud-pubsub` library; a segmentation fault occurs within GRPC.

Output of the below test case is:

```
(test-case.py3) ➜  python run.py
[1]    7682 segmentation fault (core dumped)  python run.py
```

#### requirements.txt
```
gevent==1.3.2post0
google-cloud-pubsub==0.35.2
six==1.11.0
```

#### run.py

```
#!/usr/bin/env python
from gevent import monkey
monkey.patch_all()

# patch grpc for gevent
import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()

from google.cloud import pubsub
import six


_topic = 'project/doesntmatter/topic/whocares'
_client = None


def emit(msg):
    # type: (six.binary_type) -> None
    future = _client.publish(_topic, msg)
    # block until published
    future.result()


if __name__ == '__main__':
    _client = pubsub.PublisherClient()
    emit(b'cool-message')
```
 
### Anything else we should know about your project / environment?

Stacktraces and the like are below. At first, I had worried this was a problem with the precompiled wheel that was on pypi, so I installed using `pip install --force-reinstall --no-binary :all: grpcio` and ended up with the same error. Please let me know if I can provide any further information.

#### `gdb` stacktrace

Output from a `gdb` session, including stacktrace

```
(test-case.py3) ➜  gdb ex -r --args python run.py 
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...expanding to full symbols...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/nwittstock/workon/test-case.py3/bin/python run.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
/home/nwittstock/workon/test-case.py3/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
[New Thread 0x7fffede62700 (LWP 7171)]
[Thread 0x7fffede62700 (LWP 7171) exited]
[New Thread 0x7fffede62700 (LWP 7172)]
[New Thread 0x7fffed621700 (LWP 7173)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff092f50a in grpc_call_combiner_set_notify_on_cancel(grpc_call_combiner*, grpc_closure*) ()
   from /home/nwittstock/workon/test-case.py3/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so
(gdb) bt
#0  0x00007ffff092f50a in grpc_call_combiner_set_notify_on_cancel(grpc_call_combiner*, grpc_closure*) ()
   from /home/nwittstock/workon/test-case.py3/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so
#1  0x00007ffff099d7e8 in send_security_metadata (batch=0x555555ef04d0, elem=0x55555602b148)
    at src/core/lib/security/transport/client_auth_filter.cc:229
#2  on_host_checked (arg=arg@entry=0x555555ef04d0, error=<optimized out>) at src/core/lib/security/transport/client_auth_filter.cc:240
#3  0x00007ffff099da93 in auth_start_transport_stream_op_batch (elem=0x55555602b148, batch=0x555555ef04d0)
    at src/core/lib/security/transport/client_auth_filter.cc:314
#4  0x00007ffff09b9fe9 in pick_done(void*, grpc_error*) ()
   from /home/nwittstock/workon/test-case.py3/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so
#5  0x00007ffff093bc2c in exec_ctx_run (error=0x0, closure=<optimized out>) at src/core/lib/iomgr/exec_ctx.cc:40
#6  grpc_core::ExecCtx::Flush (this=this@entry=0x7fffffff3a60) at src/core/lib/iomgr/exec_ctx.cc:128
#7  0x00007ffff094525b in grpc_core::ExecCtx::~ExecCtx (this=0x7fffffff3a60, __in_chrg=<optimized out>)
    at ./src/core/lib/iomgr/exec_ctx.h:96
#8  custom_read_callback (socket=<optimized out>, nread=284, error=0x0) at src/core/lib/iomgr/tcp_custom.cc:168
#9  0x00007ffff090a8ae in __pyx_f_4grpc_7_cython_6cygrpc_socket_read_async_cython (__pyx_v_socket_wrapper=0x7fffed629048)
    at src/python/grpcio/grpc/_cython/cygrpc.cpp:40582
#10 __pyx_pf_4grpc_7_cython_6cygrpc_22socket_read_async (__pyx_self=<optimized out>, __pyx_v_socket_wrapper=0x7fffed629048)
    at src/python/grpcio/grpc/_cython/cygrpc.cpp:40769
#11 __pyx_pw_4grpc_7_cython_6cygrpc_23socket_read_async (__pyx_self=<optimized out>, __pyx_v_socket_wrapper=0x7fffed629048)
    at src/python/grpcio/grpc/_cython/cygrpc.cpp:40748
#12 0x00007ffff7420698 in PyCFunction_Call () from /usr/lib/libpython3.6m.so.1.0
#13 0x00007ffff573290f in __Pyx_PyObject_Call (kw=<optimized out>, arg=0x7fffed6260b8, func=0x7ffff0092360)
    at src/gevent/greenlet.c:20634
#14 __pyx_pf_6gevent_9_greenlet_8Greenlet_34run (__pyx_v_self=0x7fffee1c6748) at src/gevent/greenlet.c:11280
#15 __pyx_pw_6gevent_9_greenlet_8Greenlet_35run (__pyx_v_self=0x7fffee1c6748, unused=<optimized out>) at src/gevent/greenlet.c:11185
#16 0x00007ffff61fb8ff in __Pyx_CyFunction_CallMethod (kw=0x0, arg=0x7ffff7dfd048, self=0x7fffee1c6748, func=0x7ffff5978328)
    at src/gevent/_hub_local.c:4212
#17 __Pyx_CyFunction_CallAsMethod (func=0x7ffff5978328, args=<optimized out>, kw=0x0) at src/gevent/_hub_local.c:4270
#18 0x00007ffff741afec in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#19 0x00007ffff741bc12 in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#20 0x00007ffff741bcf3 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#21 0x00007ffff5ff15cf in g_initialstub (mark=mark@entry=0x7fffffff3fa0) at greenlet.c:810
#22 0x00007ffff5ff0f76 in g_switch (target=0x7fffee1c6748, args=0x7ffff7dfd048, kwargs=<optimized out>) at greenlet.c:582
#23 0x00007ffff0055df0 in ?? ()
---Type <return> to continue, or q <return> to quit---
#24 0x00007ffff7dfd048 in ?? ()
#25 0x00007ffff77c9a60 in _Py_NotImplementedStruct () from /usr/lib/libpython3.6m.so.1.0
#26 0x00007fffee1c6848 in ?? ()
#27 0xcd6455dd7c92b500 in ?? ()
#28 0x00007ffff77f0590 in ?? () from /usr/lib/libpython3.6m.so.1.0
#29 0x00007fffedf08b88 in ?? ()
#30 0x00007ffff740e6e0 in ?? () from /usr/lib/libpython3.6m.so.1.0
#31 0x00007ffff77b5b24 in ?? () from /usr/lib/libpython3.6m.so.1.0
#32 0x00007ffff77c9a60 in _Py_NotImplementedStruct () from /usr/lib/libpython3.6m.so.1.0
#33 0x00007ffff741bcf3 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#34 0x00007ffff6484d07 in gevent_call (loop=0x7ffff0055df0, cb=0x7fffed62b208) at src/gevent/libev/callbacks.c:152
#35 0x00007ffff647bd46 in __pyx_f_6gevent_5libev_8corecext_4loop__run_callbacks (__pyx_v_self=0x7ffff0055df0)
    at src/gevent/libev/corecext.c:5393
#36 0x00007ffff647e85a in gevent_loop_run_callbacks (__pyx_v_loop=__pyx_v_loop@entry=0x7ffff0055df0)
    at src/gevent/libev/corecext.c:15543
#37 0x00007ffff6486ac0 in gevent_run_callbacks (_loop=<optimized out>, watcher=0x7ffff0055e08, revents=<optimized out>)
    at src/gevent/libev/callbacks.c:194
#38 0x00007ffff644fccd in ev_invoke_pending (loop=0x7ffff66979c0 <default_loop_struct>) at /tmp/build/gevent/deps/libev/ev.c:3314
#39 0x00007ffff647d060 in ev_run (loop=0x7ffff66979c0 <default_loop_struct>, flags=flags@entry=0)
    at /tmp/build/gevent/deps/libev/ev.c:3606
#40 0x00007ffff647d71a in __pyx_pf_6gevent_5libev_8corecext_4loop_14run (__pyx_v_once=0x7ffff77c89e0 <_Py_FalseStruct>, 
    __pyx_v_nowait=<optimized out>, __pyx_v_self=0x7ffff0055df0) at src/gevent/libev/corecext.c:6690
#41 __pyx_pw_6gevent_5libev_8corecext_4loop_15run (__pyx_v_self=0x7ffff0055df0, __pyx_args=<optimized out>, 
    __pyx_kwds=<optimized out>) at src/gevent/libev/corecext.c:6650
#42 0x00007ffff74204d4 in _PyCFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#43 0x00007ffff73e984e in ?? () from /usr/lib/libpython3.6m.so.1.0
#44 0x00007ffff73ad0fa in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#45 0x00007ffff73e8b2b in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#46 0x00007ffff741b28f in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#47 0x00007ffff741bc12 in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#48 0x00007ffff741bcf3 in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#49 0x00007ffff5ff15cf in g_initialstub (mark=mark@entry=0x7fffffff4630) at greenlet.c:810
#50 0x00007ffff5ff0f76 in g_switch (target=0x7ffff00ae240, args=0x7ffff7dfd048, kwargs=<optimized out>) at greenlet.c:582
#51 0x00007ffff1c2a1b8 in ?? ()
---Type <return> to continue, or q <return> to quit---
#52 0x00007fffee163a08 in ?? ()
#53 0x0000000000000000 in ?? ()
(gdb) q
A debugging session is active.

	Inferior 1 [process 7145] will be killed.

Quit anyway? (y or n) y
```

**Comment by fardog** [comment]
@kpayson64 that's excellent; thank you. i'll give that release a try once it's out, and update/close here.

**Comment by kpayson64** [comment]
I've pushed 1.12.1.

**Comment by fardog** [comment]
@kpayson64 this does appear to fix the issue, thank you! i'll re-open or create a new ticket if any other problems arise.

**Comment by kpayson64** [comment]
Sounds good, thanks for the bug report!

**Comment by ckmvishnu** [comment]
Ubuntu 16.04.3 LTS 4.13.0-38-generic

pip-freeze: python 2.7.12
------------
grpcio==1.13.0rc1
google-api-core==1.2.1
google-api-python-client==1.7.3
google-auth==1.5.0
google-auth-httplib2==0.0.3
google-cloud-pubsub==0.35.4
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4

Subscribed to 3 topics in eventlet==0.23.0. 

Getting Segmentation Fault from 40s to 1m.

Currently polling to get VM lifecycle. tried downgrading grpcio all the way to 1.7.0 with same result. I follow sample code as in google pubsub document but with eventlet.

**Comment by kpayson64** [comment]
@ckmvishnu 
Eventlet is not currently supported.
