### ISSUE TITLE
high-throughput ruby benchmarking scenarios are failing "assertion failed: i != pss->pollset_count"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15628]
Some qps benchmarking scenarios for ruby are failing in almost every run of benchmarks (which makes the entire benchmark suite red).

These are usually the "unconstrained" scenarios - e.g. ones with high troughput. Looks like qps driver might have issues talking to ruby workers when they are overloaded - or the workers might be crashing.
Other scenarios seem to be working well.

```
I0603 22:12:22.891677467   21888 driver.cc:272]              Starting server on grpc-kokoro-performance-server-8core:10300 (worker #0)
D0603 22:12:22.891859697   21888 ev_posix.cc:145]            Using polling engine: epollex
D0603 22:12:22.891896063   21888 dns_resolver.cc:339]        Using native dns resolver
D0603 22:12:22.891995418   21888 dns_resolver.cc:280]        Start resolving.
I0603 22:12:22.894072279   21888 subchannel.cc:646]          Connect failed: {"created":"@1528063942.894016912","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":202,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:10.240.0.251:10300"}
I0603 22:12:22.894110584   21888 subchannel.cc:470]          Subchannel 0x7f6b68003600: Retry in 999 milliseconds
I0603 22:12:23.894000818   21890 subchannel.cc:425]          Failed to connect to channel, retrying
I0603 22:12:23.894731259   21888 subchannel.cc:608]          New connected subchannel at 0x55ee9998e1a0 for subchannel 0x7f6b68003600
I0603 22:12:23.898988872   21888 driver.cc:328]              Starting client on grpc-kokoro-performance-client-8core:10300 (worker #1)
D0603 22:12:23.899072854   21888 driver.cc:350]              Client 0 gets 32 channels
D0603 22:12:23.899101046   21888 dns_resolver.cc:280]        Start resolving.
I0603 22:12:23.900947839   21888 subchannel.cc:608]          New connected subchannel at 0x55ee9999faf0 for subchannel 0x7f6b680054e0
I0603 22:12:23.901084122   21888 driver.cc:328]              Starting client on grpc-kokoro-performance-client2-8core:10300 (worker #2)
D0603 22:12:23.901132159   21888 driver.cc:350]              Client 1 gets 32 channels
D0603 22:12:23.901152426   21888 dns_resolver.cc:280]        Start resolving.
I0603 22:12:23.902497589   21888 subchannel.cc:608]          New connected subchannel at 0x55ee999a8f80 for subchannel 0x7f6b68006820
D0603 22:12:24.260049773   21888 dns_resolver.cc:256]        In cooldown from last resolution (from 359 ms ago). Will resolve again in 641 ms
D0603 22:12:24.260098935   21888 dns_resolver.cc:280]        Start resolving.
E0603 22:12:24.260161008   21888 driver.cc:365]              Client 1 did not yield initial status
I0603 22:12:24.260167264   21888 driver.cc:371]              Initiating
E0603 22:12:24.260298852   21888 driver.cc:381]              Couldn't write mark to client 1
E0603 22:12:24.268348884   21888 driver.cc:387]              Couldn't get status from client 1
I0603 22:12:24.268385275   21888 driver.cc:392]              Warming up
D0603 22:12:27.892067729   21891 dns_resolver.cc:280]        Start resolving.
I0603 22:12:29.268511877   21888 driver.cc:398]              Starting
E0603 22:12:29.268669391   21888 driver.cc:408]              Couldn't write mark to client 0
E0603 22:12:29.268683111   21888 driver.cc:408]              Couldn't write mark to client 1
E0603 22:12:29.394972218   21888 driver.cc:420]              Couldn't get status from client 0
E0603 22:12:29.395016932   21888 driver.cc:420]              Couldn't get status from client 1
I0603 22:12:29.395020519   21888 driver.cc:425]              Running
I0603 22:12:59.268580537   21888 driver.cc:439]              Finishing clients
E0603 22:12:59.268667437   21888 driver.cc:443]              Couldn't write mark to client 0
E0603 22:12:59.268675518   21888 driver.cc:446]              Failed WritesDone for client 0
E0603 22:12:59.268682385   21888 driver.cc:443]              Couldn't write mark to client 1
E0603 22:12:59.268686670   21888 driver.cc:446]              Failed WritesDone for client 1
E0603 22:12:59.268695798   21888 driver.cc:464]              Couldn't get final status from client 0
E0603 22:12:59.268700768   21888 driver.cc:464]              Couldn't get final status from client 1
E0603 22:12:59.268754106   21888 driver.cc:472]              Client 0 had an error Socket closed
E0603 22:12:59.268791488   21888 driver.cc:472]              Client 1 had an error OS Error
I0603 22:12:59.268819479   21888 driver.cc:485]              Finishing servers
I0603 22:12:59.271583068   21888 driver.cc:499]              Received final status from server 0
I0603 22:12:59.430907960   21888 report.cc:82]               QPS: -nan
I0603 22:12:59.431559041   21888 report.cc:122]              QPS: -nan (-nan/server core)
I0603 22:12:59.431570519   21888 report.cc:127]              Latencies (50/90/95/99/99.9%-ile): 0.0/0.0/0.0/0.0/0.0 us
I0603 22:12:59.431574295   21888 report.cc:137]              Server system time: 0.00%
I0603 22:12:59.431577220   21888 report.cc:139]              Server user time:   0.00%
I0603 22:12:59.431579987   21888 report.cc:141]              Client system time: -nan%
I0603 22:12:59.431582824   21888 report.cc:143]              Client user time:   -nan%
I0603 22:12:59.431585829   21888 report.cc:148]              Server CPU usage: 0.00%
I0603 22:12:59.431588542   21888 report.cc:153]              Client Polls per Request: -nan
I0603 22:12:59.431591106   21888 report.cc:155]              Server Polls per Request: -nan
I0603 22:12:59.431593782   21888 report.cc:160]              Server Queries/CPU-sec: -nan
I0603 22:12:59.431596325   21888 report.cc:162]              Client Queries/CPU-sec: -nan
```

From the log it looks like the clients aren't really very responsive - "Couldn't get status" ,  "Couldn't write mark",   "Couldn't get final status from client 0",  "Client 0 had an error Socket closed", "Client 1 had an error OS Error"

Examples:
https://source.cloud.google.com/results/invocations/2abc6ab4-38ad-4d3a-b195-582e9b2e26f5/targets/github%2Fgrpc%2Freports%2F8core/tests
https://source.cloud.google.com/results/invocations/cc556cbf-1034-43f6-8400-5cc302caaa3d/targets/github%2Fgrpc%2Freports%2F8core/tests
https://source.cloud.google.com/results/invocations/8d669a37-23bf-4c41-b15c-c2358edae8e3/targets/github%2Fgrpc%2Freports%2F8core/tests
https://source.cloud.google.com/results/invocations/ff536ea4-a655-42d4-a24f-880b2a657a74/targets/github%2Fgrpc%2Freports%2F8core/tests

**Comment by jtattermusch** [comment]
Also found this in the logs:

```
+ ruby src/ruby/qps/worker.rb --driver_port=10300
E0604 05:59:06.714226484   26305 ev_epollex_linux.cc:1387]   pollset_set_add_pollset: {"created":"@1528091946.714195777","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_eventfd.cc","file_line":37,"os_error":"Too many open files","syscall":"eventfd"}
E0604 05:59:06.714402224   26306 ev_epollex_linux.cc:1387]   pollset_set_add_pollset: {"created":"@1528091946.714386997","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_eventfd.cc","file_line":37,"os_error":"Too many open files","syscall":"eventfd"}
E0604 05:59:06.714888714   25778 ev_epollex_linux.cc:1337]   assertion failed: i != pss->pollset_count
tools/run_tests/performance/run_worker_ruby.sh: line 21: 25776 Aborted                 (core dumped) ruby src/ruby/qps/worker.rb "$@"

2018-06-04 06:02:42,306 FAILED: qps_worker_ruby_1 [ret=134, pid=25677, time=216.9sec]
```

**Comment by jtattermusch** [comment]
@apolcyn  any ideas?

**Comment by apolcyn** [comment]
Haven't had time to take a good look into this yet, planning to look further in tomorrow. FWIW here was a socket leak (possibly related to the "Too many open files" in this bug) that was a fixed a while ago in this PR: https://github.com/grpc/grpc/pull/11764, but this bug seems different from that issue because it seems that the failing scenarios are streaming....

**Comment by apolcyn** [comment]
FTR this is reproduces locally every time.

```
tools/run_tests/performance/run_worker_ruby.sh --driver_port=10310 &
tools/run_tests/performance/run_worker_ruby.sh --driver_port=10310 &
```

```
bins/opt/qps_json_driver '--scenarios_json={"scenarios": [{"name": "ruby_protobuf_sync_streaming_qps_unconstrained", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"async_server_threads": 0, "channel_args": [{"str_value": "throughput", "name": "grpc.optimization_target"}], "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "threads_per_cq": 0, "server_type": "SYNC_SERVER"}, "client_config": {"security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "channel_args": [{"str_value": "throughput", "name": "grpc.optimization_target"}], "async_client_threads": 0, "outstanding_rpcs_per_channel": 16, "rpc_type": "STREAMING", "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "client_channels": 64, "threads_per_cq": 0, "load_params": {"closed_loop": {}}, "client_type": "SYNC_CLIENT", "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 0}]}'
```

it seems that this happens every time, during the time that the <i>client</i> is opening up all of its <i>streams</i> that the beginning of the test (there are 1024 in total to open). The number of total calls alone doesn't seem to be whats triggering all of the 

```
E0621 07:11:11.207012779     472 ev_epollex_linux.cc:1461]   pollset_set_add_pollset: {"created":"@1529565071.206996829","description":"OS Error","errno":24,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":520,"os_error":"Too many open files","syscall":"epoll_create1"}
```

errors though....

**Comment by apolcyn** [comment]
an easier way to reproduce this is with client in `src/ruby/end2end` of:

```
require_relative './end2end_common'
t = []
p ARGV[0]
stub = Echo::EchoServer::Stub.new("localhost:#{ARGV[0]}",
                                  :this_channel_is_insecure)
<variable number of concurrent calls>.times do |i|
  t << Thread.new do
    r = stub.echo_stream([Echo::EchoRequest.new(request: 'client/child started')])
    r.each { |r| r }
  end
end
t.each(&:join)
```

running against server of 

```
require_relative './end2end_common'

p ServerRunner.new(EchoServerImpl, 'rpc_server_args': {'pool_size': 8192}).run
sleep
```

where <variable number of concurrent calls> is something just greater than `ulimit -n`

e.g., with a `ulimit -n` of 1024, I'm seeing ~1K calls can be made, and then that "too many open files" error starts happening once we go over that.

The ruby wrapper associates 1 new completion queue for <i>every</i> call, translating to 1 epollfd for every call [under epollex](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/ev_epollex_linux.cc#L518) poller. That benchmark creates 1024 concurrent streaming calls, and it does so on 64 different channels, which means that there is certainly more than 1024 open fd's at once, and on my debian 9 GCP VM ,`ulimit -n` defaulted to 1024. It's not yet clear to me that there is a grpc bug here. @jtattermusch do you know if anything has changed recently on benchmark workers?

**Comment by jtattermusch** [comment]
@apolcyn   we migrated the multi-machines benchmarks to kokoro which also involved recreating the bechmark workers (currently the "driver" machine is a kokoro-created VM, but the slaves running qps_workers are manually-provided VMs) - it might well be that the ruby benchmarks have been flaky for long time.

I ssh'd to the new workers and they have the default `ulimit -n`  of  1024.
We do set the ulimit here:  https://github.com/grpc/grpc/blob/74a53c2440823e7b53741edba883ff1f4fb8f23a/tools/internal_ci/helper_scripts/prepare_build_linux_perf_multilang_rc#L19,  but as far as I can tell, that's only applied for the driver VM - not for the worker VMs that actually run the qps_worker binaries.

Btw, I though that for languages with only sync API we use deliberately use fewer concurrent calls in scenario_config.py to not run into the "too many open files" problem.

CC @matt-kwong

**Comment by sreecha** [comment]
This is due to bug: https://github.com/grpc/grpc/issues/15759  - The fix is not straightforward :(

**Comment by jtattermusch** [comment]
@apolcyn   we need to fix this. The ruby benchmarks have been failing with very high failure rate for >1 year. Here's an overview that should help:

SingleVM benchmarks (they make things much easier to debug and test)
https://testgrid.corp.google.com/End2end%20OSS%20Benchmarks#Linux%20single-VM%20end2end%20benchmarks&width=20

MultiVM benchmarks:
https://testgrid.corp.google.com/End2end%20OSS%20Benchmarks#Linux%20multi-VM%20end2end%20benchmarks%20for%20master&width=20

Another source of failures (besides what's above) is this
```
#<Thread:0x00007f952800fb80@/tmpfs/src/github/grpc/src/ruby/qps/client.rb:84 run> terminated with exception (report_on_exception is true):
/tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Socket closed (GRPC::Unavailable)
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:377:in `request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from /tmpfs/src/github/grpc/src/ruby/qps/client.rb:113:in `unary_ping_ponger'
	from /tmpfs/src/github/grpc/src/ruby/qps/client.rb:95:in `block (3 levels) in initialize'
#<Thread:0x00007f952800e0f0@/tmpfs/src/github/grpc/src/ruby/qps/client.rb:84 run> terminated with exception (report_on_exception is true):
/tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:26:in `check_status': 1:unknown cause (GRPC::Cancelled)
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:377:in `request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from /tmpfs/src/github/grpc/src/ruby/qps/client.rb:113:in `unary_ping_ponger'
	from /tmpfs/src/github/grpc/src/ruby/qps/client.rb:95:in `block (3 levels) in initialize'
/tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:26:in `check_status': 1:unknown cause (GRPC::Cancelled)
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/active_call.rb:377:in `request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
	from /tmpfs/src/github/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from /tmpfs/src/github/grpc/src/ruby/qps/client.rb:113:in `unary_ping_ponger'
	from /tmpfs/src/github/grpc/src/ruby/qps/client.rb:95:in `block (3 levels) in initialize'

2019-10-29 21:54:50,628 FAILED: qps_worker_ruby_1 [ret=1, pid=12041, time=158.0sec]
```
https://sponge.corp.google.com/invocation?tab=Build+Log&id=25c7c8b8-1de0-4577-9d5d-56b10b6588c9&searchFor=

**Comment by yashykt** [comment]
@apolcyn Any update on this? (Please downgrade to P2 if it is not urgent.)

**Comment by ruuda** [comment]
We hit this assertion in production yesterday. GRPC is used as a dependency in Google's official [Python `google-ads` client library](https://github.com/googleads/google-ads-python). The assertion aborted the process, so there was no opportunity for error handling, and our normal Python-based error reporting failed to collect more details because of this. Therefore, unfortunately the only data I have are these two log lines:

```
E1208 09:22:13.287932530 1319028 ev_epollex_linux.cc:1457]   pollset_set_add_pollset: {"created":"@1607415733.287914268","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_eventfd.cc","file_line":38,"os_error":"Too many open files","syscall":"eventfd"}
E1208 09:22:34.287580800 1319044 ev_epollex_linux.cc:1408]   assertion failed: i != pss->pollset_count
```

This was using version 1.29.0 of the Python `grpc` package.

**Comment by yashykt** [comment]
@veblush @drfloob Y'all might be interested in this.

**Comment by jtattermusch** [comment]
The problem I originally reported was happening for the legacy benchmarking framework. 
I checked the results for the new GKE-based OSS benchmarking framework and all the ruby benchmarking scenarios we're running seem stable (I checked runs for the past month).
