### ISSUE TITLE
Node tests broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15814]
Broken in 100% of cases

```
  CXX(target) Release/obj.target/grpc_node/ext/channel.o
  CXX(target) Release/obj.target/grpc_node/ext/channel_credentials.o
  CXX(target) Release/obj.target/grpc_node/ext/completion_queue.o
  CXX(target) Release/obj.target/grpc_node/ext/node_grpc.o
  CXX(target) Release/obj.target/grpc_node/ext/server.o
../ext/channel_credentials.cc:151:37: error: no matching function for call to 'grpc_ssl_credentials_create'
  grpc_channel_credentials *creds = grpc_ssl_credentials_create(
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/grpc/include/grpc/grpc_security.h:204:35: note: candidate function not viable: requires 4 arguments, but 3 were provided
GRPCAPI grpc_channel_credentials* grpc_ssl_credentials_create(
                                  ^
1 error generated.
make: *** [Release/obj.target/grpc_node/ext/channel_credentials.o] Error 1
make: *** Waiting for unfinished jobs....
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kbuilder/.nvm/versions/node/v4.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
```

MacOS
https://source.cloud.google.com/results/invocations/cb0fe7b3-c713-41c7-9b70-2fdc29055674/

Linux
https://source.cloud.google.com/results/invocations/73a033fb-7760-4987-9b96-4346a5d67f8a/targets/github%2Fgrpc%2Fgrpc-node_linux_dbg_native/tests

**Comment by jtattermusch** [comment]
CC @nicolasnoble

**Comment by jtattermusch** [comment]
This is probably the culprit: https://github.com/grpc/grpc/pull/15274. Interestingly enough, the grpc-node build is green on that PR's tests - do we have a problem with how the cross-repo node tests are setup? 

CC @markdroth

**Comment by murgatroid99** [comment]
The tests in that PR should have failed. It's hard to tell why it passed, because we don't record any substantial logs from tests that pass.
