### ISSUE TITLE
grpc_interop_tocloud test fails with "Socket closed"

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#15831]
https://source.cloud.google.com/results/invocations/cf409f73-cde7-4d69-8c07-1c504213ae16/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

```
2018-06-18 17:05:43,466 FAILED: cloud_to_cloud:php:csharpcoreclr_server:unimplemented_method [ret=1, pid=30224, time=1.1sec]
2018-06-18 17:05:43,466 START: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:custom_metadata
2018-06-18 17:05:43,470 WAITING: ETA 176.5 sec; 1151 queued, 12 jobs running, 392 complete, 1 failed (load 12.00) next: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:status_code_and_message @ 1.00 cpu
2018-06-18 17:05:43,509 Running test case custom_metadata
Call did not complete successfully. Status object:
object(stdClass)#389 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(14)
  ["details"]=>
  string(13) "Socket closed"
}

2018-06-18 17:05:43,509 FAILED: cloud_to_cloud:php:csharpcoreclr_server:custom_metadata [ret=1, pid=29935, time=1.3sec]
2018-06-18 17:05:43,509 START: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:status_code_and_message
2018-06-18 17:05:43,514 WAITING: ETA 176.0 sec; 1150 queued, 12 jobs running, 393 complete, 2 failed (load 12.00) next: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:unimplemented_method @ 1.00 cpu
2018-06-18 17:05:43,517 Running test case unimplemented_service
Received unexpected status code

2018-06-18 17:05:43,517 FAILED: cloud_to_cloud:php:csharpcoreclr_server:unimplemented_service [ret=1, pid=30264, time=1.1sec]
2018-06-18 17:05:43,517 START: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:unimplemented_method
2018-06-18 17:05:43,526 WAITING: ETA 175.5 sec; 1149 queued, 12 jobs running, 394 complete, 3 failed (load 12.00) next: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:unimplemented_service @ 1.00 cpu
2018-06-18 17:05:43,747 WAITING: ETA 176.1 sec; 1149 queued, 12 jobs running, 394 complete, 3 failed (load 12.00) next: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:unimplemented_service @ 1.00 cpu
2018-06-18 17:05:44,726 D0619 00:05:43.982262 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0619 00:05:44.044250 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running ping_pong

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unavailable, Detail="Connect Failed")) ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunPingPongAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)

2018-06-18 17:05:44,726 FAILED: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:ping_pong [ret=139, pid=30538, time=2.1sec]
2018-06-18 17:05:44,727 START: cloud_to_cloud:csharpcoreclr:csharpcoreclr_server:unimplemented_service
2018-06-18 17:05:44,731 WAITING: ETA 178.4 sec; 1148 queued, 12 jobs running, 395 complete, 4 failed (load 12.00) next: cloud_to_cloud:dart:csharpcoreclr_server:large_unary @ 1.00 cpu
2018-06-18 17:05:44,748 D0619 00:05:44.003344 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0619 00:05:44.086758 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running large_unary

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unavailable, Detail="Connect Failed")) ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, CallOptions options)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.InteropClient.RunLargeUnary(TestServiceClient client)
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)


```

**Comment by ZhouyihaiDing** [comment]
Seems all languages failed with `csharpcoreclr_server` test.
```
2018-06-18 17:08:53,412 FAILED: cloud_to_cloud:java:csharpcoreclr_server:ping_pong [ret=1, pid=6624, time=2.6sec]
```

**Comment by AspirinSJL** [comment]
Stale.
