### ISSUE TITLE
Unable to install grpcio

### ISSUE THREAD

**Issue by jasontyler** [grpc/grpc#15868]
### What version of gRPC and what language are you using?
 grpc = 1.12.0 and language = Python
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python version 2.7.6
 
### What did you do?
Tried to install grpcio==1.12.0
 
### What did you expect to see?
 Successful installation
 
### What did you see instead?
 
```
    
    warning: no files found matching '*.c' under directory 'src/python/grpcio/grpc'
    warning: no files found matching '*.h' under directory 'src/python/grpcio/grpc'
    warning: no files found matching '*.python' under directory 'src/python/grpcio/grpc'
    warning: no previously-included files matching '*.so' found under directory 'src/python/grpcio/grpc/_cython'
    warning: no previously-included files matching '*.pyd' found under directory 'src/python/grpcio/grpc/_cython'
    warning: no files found matching 'src/python/grpcio/precompiled.py'
Downloading/unpacking six>=1.5.2 (from grpcio==1.12.0)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking futures>=2.2.0 (from grpcio==1.12.0)
  Downloading futures-3.2.0-py2-none-any.whl
Downloading/unpacking enum34>=1.0.4 (from grpcio==1.12.0)
  Downloading enum34-1.1.6-py2-none-any.whl
Installing collected packages: grpcio, six, futures, enum34
  Running setup.py install for grpcio
    Found cython-generated files...
    Found cython-generated files...
    building 'grpc._cython.cygrpc' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c src/python/grpcio/grpc/_cython/cygrpc.c -o python_build/temp.linux-x86_64-2.7/src/python/grpcio/grpc/_cython/cygrpc.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread
    x86_64-linux-gnu-gcc: error: src/python/grpcio/grpc/_cython/cygrpc.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /tmp/tmp_9oOik/a.c -o tmp/tmp_9oOik/a.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/me/bucket/build/grpcio/setup.py", line 310, in <module>
        cmdclass=COMMAND_CLASS,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/me/bucket/local/lib/python2.7/site-packages/setuptools/command/install.py", line 54, in run
        return _install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/me/bucket/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 52, in run
        _build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/home/me/bucket/build/grpcio/src/python/grpcio/commands.py", line 297, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "/home/me/bucket/build/grpcio/src/python/grpcio/commands.py", line 292, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/home/me/bucket/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 186, in build_extension
        _build_ext.build_extension(self,ext)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
        depends=ext.depends)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
        raise CompileError, msg
    CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    
    Complete output from command /home/me/bucket/bin/python -c "import setuptools, tokenize;__file__='/home/me/bucket/build/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-z9TWUI-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/me/bucket/include/site/python2.7:
    Found cython-generated files...

running install

running build

running build_py

running build_project_metadata

creating python_build

creating python_build/lib.linux-x86_64-2.7

creating python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_auth.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_common.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_channel.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_server.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_plugin_wrapping.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_interceptor.py -> python_build/lib.linux-x86_64-2.7/grpc

copying src/python/grpcio/grpc/_utilities.py -> python_build/lib.linux-x86_64-2.7/grpc

creating python_build/lib.linux-x86_64-2.7/grpc/_cython

copying src/python/grpcio/grpc/_cython/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/_cython

creating python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/_server_adaptations.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/interfaces.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/utilities.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/implementations.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/_metadata.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

copying src/python/grpcio/grpc/beta/_client_adaptations.py -> python_build/lib.linux-x86_64-2.7/grpc/beta

creating python_build/lib.linux-x86_64-2.7/grpc/framework

copying src/python/grpcio/grpc/framework/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/framework

creating python_build/lib.linux-x86_64-2.7/grpc/experimental

copying src/python/grpcio/grpc/experimental/gevent.py -> python_build/lib.linux-x86_64-2.7/grpc/experimental

copying src/python/grpcio/grpc/experimental/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/experimental

creating python_build/lib.linux-x86_64-2.7/grpc/_cython/_cygrpc

copying src/python/grpcio/grpc/_cython/_cygrpc/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/_cython/_cygrpc

creating python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/logging_pool.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/stream_util.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/abandonment.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/callable_util.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/future.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

copying src/python/grpcio/grpc/framework/foundation/stream.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/foundation

creating python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces

copying src/python/grpcio/grpc/framework/interfaces/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces

creating python_build/lib.linux-x86_64-2.7/grpc/framework/common

copying src/python/grpcio/grpc/framework/common/cardinality.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/common

copying src/python/grpcio/grpc/framework/common/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/common

copying src/python/grpcio/grpc/framework/common/style.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/common

creating python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/face

copying src/python/grpcio/grpc/framework/interfaces/face/face.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/face

copying src/python/grpcio/grpc/framework/interfaces/face/utilities.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/face

copying src/python/grpcio/grpc/framework/interfaces/face/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/face

creating python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/base

copying src/python/grpcio/grpc/framework/interfaces/base/utilities.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/base

copying src/python/grpcio/grpc/framework/interfaces/base/__init__.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/base

copying src/python/grpcio/grpc/framework/interfaces/base/base.py -> python_build/lib.linux-x86_64-2.7/grpc/framework/interfaces/base

creating python_build/lib.linux-x86_64-2.7/grpc/_cython/_credentials

copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.linux-x86_64-2.7/grpc/_cython/_credentials

running build_ext

Found cython-generated files...

building 'grpc._cython.cygrpc' extension

creating python_build/temp.linux-x86_64-2.7

creating python_build/temp.linux-x86_64-2.7/src

creating python_build/temp.linux-x86_64-2.7/src/python

creating python_build/temp.linux-x86_64-2.7/src/python/grpcio

creating python_build/temp.linux-x86_64-2.7/src/python/grpcio/grpc

creating python_build/temp.linux-x86_64-2.7/src/python/grpcio/grpc/_cython

creating python_build/temp.linux-x86_64-2.7/third_party

creating python_build/temp.linux-x86_64-2.7/third_party/address_sorting

creating python_build/temp.linux-x86_64-2.7/src/core

creating python_build/temp.linux-x86_64-2.7/src/core/lib

creating python_build/temp.linux-x86_64-2.7/src/core/lib/gpr

creating python_build/temp.linux-x86_64-2.7/src/core/lib/gprpp

creating python_build/temp.linux-x86_64-2.7/src/core/lib/profiling

creating python_build/temp.linux-x86_64-2.7/src/core/lib/surface

creating python_build/temp.linux-x86_64-2.7/src/core/lib/avl

creating python_build/temp.linux-x86_64-2.7/src/core/lib/backoff

creating python_build/temp.linux-x86_64-2.7/src/core/lib/channel

creating python_build/temp.linux-x86_64-2.7/src/core/lib/compression

creating python_build/temp.linux-x86_64-2.7/src/core/lib/debug

creating python_build/temp.linux-x86_64-2.7/src/core/lib/http

creating python_build/temp.linux-x86_64-2.7/src/core/lib/iomgr

creating python_build/temp.linux-x86_64-2.7/src/core/lib/json

creating python_build/temp.linux-x86_64-2.7/src/core/lib/slice

creating python_build/temp.linux-x86_64-2.7/src/core/lib/transport

creating python_build/temp.linux-x86_64-2.7/src/core/ext

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/server

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/server/secure

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/transport

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/alpn

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/http

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/http/client

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/http/message_compress

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/http/server

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/context

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/alts

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/composite

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/fake

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/google_default

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/iam

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/jwt

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/oauth2

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/plugin

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/credentials/ssl

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/security_connector

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/transport

creating python_build/temp.linux-x86_64-2.7/src/core/lib/security/util

creating python_build/temp.linux-x86_64-2.7/src/core/tsi

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/alts

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/alts/crypt

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/alts/frame_protector

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/alts/handshaker

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/alts/zero_copy_frame_protector

creating python_build/temp.linux-x86_64-2.7/third_party/nanopb

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/client

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/client/insecure

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/deadline

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/ssl

creating python_build/temp.linux-x86_64-2.7/src/core/tsi/ssl/session_cache

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/client/secure

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/chttp2/server/insecure

creating python_build/temp.linux-x86_64-2.7/src/core/ext/transport/inproc

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/grpclb

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/grpclb/proto

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/grpclb/proto/grpc/lb/v1

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/resolver

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/resolver/fake

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/pick_first

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/lb_policy/round_robin

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/resolver/dns

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/resolver/dns/c_ares

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/resolver/dns/native

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/client_channel/resolver/sockaddr

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/load_reporting

creating python_build/temp.linux-x86_64-2.7/src/core/ext/census

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/max_age

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/message_size

creating python_build/temp.linux-x86_64-2.7/src/core/ext/filters/workarounds

creating python_build/temp.linux-x86_64-2.7/src/core/plugin_registry

creating python_build/temp.linux-x86_64-2.7/src/boringssl

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/asn1

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/base64

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/bio

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/bn_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/buf

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/bytestring

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/chacha

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/cipher_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/cmac

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/conf

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/curve25519

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/dh

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/digest_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/dsa

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/ec_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/ecdh

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/ecdsa_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/engine

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/err

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/evp

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/fipsmodule

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/hkdf

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/lhash

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/obj

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/pem

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/pkcs7

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/pkcs8

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/poly1305

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/pool

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/rand_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/rc4

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/rsa_extra

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/stack

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/x509

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/crypto/x509v3

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/ssl

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/third_party

creating python_build/temp.linux-x86_64-2.7/third_party/boringssl/third_party/fiat

creating python_build/temp.linux-x86_64-2.7/third_party/zlib

creating python_build/temp.linux-x86_64-2.7/third_party/cares

creating python_build/temp.linux-x86_64-2.7/third_party/cares/cares

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c src/python/grpcio/grpc/_cython/cygrpc.c -o python_build/temp.linux-x86_64-2.7/src/python/grpcio/grpc/_cython/cygrpc.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread

x86_64-linux-gnu-gcc: error: src/python/grpcio/grpc/_cython/cygrpc.c: No such file or directory

x86_64-linux-gnu-gcc: fatal error: no input files

compilation terminated.

creating tmp

creating tmp/tmp_9oOik

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /tmp/tmp_9oOik/a.c -o tmp/tmp_9oOik/a.o

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/me/bucket/build/grpcio/setup.py", line 310, in <module>

    cmdclass=COMMAND_CLASS,

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/home/me/bucket/local/lib/python2.7/site-packages/setuptools/command/install.py", line 54, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/home/me/bucket/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 52, in run

    _build_ext.run(self)

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run

    self.build_extensions()

  File "/home/me/bucket/build/grpcio/src/python/grpcio/commands.py", line 297, in build_extensions

    "Failed `build_ext` step:\n{}".format(formatted_exception))

commands.CommandError: Failed `build_ext` step:

Traceback (most recent call last):

  File "/home/me/bucket/build/grpcio/src/python/grpcio/commands.py", line 292, in build_extensions

    build_ext.build_ext.build_extensions(self)

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions

    self.build_extension(ext)

  File "/home/me/bucket/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 186, in build_extension

    _build_ext.build_extension(self,ext)

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension

    depends=ext.depends)

  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile

    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)

  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile

    raise CompileError, msg

CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by kasanadu** [comment]
hi.. i also have same issue ..
///
x86_64-linux-gnu-gcc: error: src/python/grpcio/grpc/_cython/cygrpc.c: No such file or directory
///

  above is coming up when i used the following to install tensorflow in ubuntu machone
sudo pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0-cp34-cp34m-linux_x86_64.whl

**Comment by jasontyler** [comment]
Upgrade the pip version and that should fix it.

**Comment by mehrdada** [comment]
I'm glad that upgrading `pip` has resolved the issue. We do have continuous tests running that installs our released packages on various Linux distros with only the minimal dependencies installed, so in general, it's rare that we face installation failures on popular distros.
