### ISSUE TITLE
Python 3.7 gRPC binaries on Windows

### ISSUE THREAD

**Issue by johanbn** [grpc/grpc#15925]
Did not get to install grpcio

Runned, pip install grpcio, and got following back

    Traceback (most recent call last):
      File "C:\Users\johan\AppData\Local\Temp\pip-install-za6mhjg6\grpcio\src\python\grpcio\commands.py", line 292, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "c:\python37\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\python37\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\python37\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\python37\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "c:\python37\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\python37\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 844, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 486, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python37\lib\site-packages\setuptools\msvc.py", line 493, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\johan\AppData\Local\Temp\pip-install-za6mhjg6\grpcio\setup.py", line 347, in <module>
        cmdclass=COMMAND_CLASS,
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\python37\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\johan\AppData\Local\Temp\pip-install-za6mhjg6\grpcio\src\python\grpcio\commands.py", line 295, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "C:\Users\johan\AppData\Local\Temp\pip-install-za6mhjg6\grpcio\src\python\grpcio\support.py", line 109, in diagnose_build_ext_error
        "backtrace).\n\n{}".format(formatted))
    commands.CommandError:

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by srini100** [comment]
Have you tried upgrading pip version?

**Comment by mehrdada** [comment]
We do not yet have Python 3.7 binary packages for Windows and Mac built and uploaded. It likely takes a week or two for us to get them integrated in our build pipeline. In the meantime, if you want to install `grpcio` on Windows using Python 3.7, you need a C compiler and Python development headers installed for `pip install` to work and compile the source package.

**Comment by mehrdada** [comment]
64-bit Windows binaries for Python3.7 are uploaded to PyPI.

**Comment by sraman24** [comment]
Failure on Windows 10, with Python v 3.7 , PIP 18.0 while installing grpcio with the "pip install grpcio" command. Requirement already satisfied: six>=1.5.2 in c:\users\sraman24\appdata\local\programs\python\python37-32\lib\site-packages (from grpcio) (1.11.0)
Installing collected packages: grpcio
  Running setup.py install for grpcio ... error
    Complete output from command c:\users\sraman24\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SRAMAN24\\AppData\\Local\\Temp\\pip-install-xmnokwqt\\grpcio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SRAMAN24\AppData\Local\Temp\pip-record-g0tcscm0\install-record.txt --single-version-externally-managed --compile:

**Comment by mehrdada** [comment]
@sraman24 This PR only adds 64 bit Windows binaries for Python3.7. There's an open issue for 32-bit here:  https://github.com/grpc/grpc/issues/15968. Please use 64-bit Python or downgrade to 3.6 in the meantime.

**Comment by sraman24** [comment]
@mehrdada - thanks and downgrade to 64-bit python version 3.6 and pip v 18.0 worked  - thanks for quick reply mehrDADA

**Comment by mehrdada** [comment]
32-bit Python 3.7 binary wheels for Windows are now uploaded on PyPI.
