### ISSUE TITLE
Basic Python route_guide gRPC example is not working with latest library versions

### ISSUE THREAD

**Issue by Pet3ris** [grpc/grpc#15920]
### What version of gRPC and what language are you using?
 
```
Python
```

```
Name: grpcio
Version: 1.13.0
Summary: HTTP/2-based RPC framework
Home-page: https://grpc.io
Author: The gRPC Authors
Author-email: grpc-io@googlegroups.com
License: Apache License 2.0
Location: /Users/p/anaconda/envs/py36/lib/python3.6/site-packages
Requires: six
Required-by: grpcio-tools
```
 
### What operating system (Linux, Windows, …) and version?
 
```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
```
Python 3.6.1 :: Anaconda custom (x86_64)
```
 
### What did you do?

```bash
pip install grpcio grpcio-tools
git clone https://github.com/grpc/grpc.git
cd grpc/examples/python/route_guide
python run_codegen.py # Everything breaks whether I include this step or not
python route_guide_server.py
```

Then in a separate window:

```bash
python route_guide_client.py
```
 
### What did you expect to see?
 
Successful execution.
 
### What did you see instead?
 
```
-------------- GetFeature --------------
Traceback (most recent call last):
  File "route_guide_client.py", line 119, in <module>
    run()
  File "route_guide_client.py", line 109, in run
    guide_get_feature(stub)
  File "route_guide_client.py", line 48, in guide_get_feature
    latitude=409146138, longitude=-746188906))
  File "route_guide_client.py", line 34, in guide_get_one_feature
    feature = stub.GetFeature(point)
  File "/Users/p/anaconda/envs/py36/lib/python3.6/site-packages/grpc/_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/p/anaconda/envs/py36/lib/python3.6/site-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Method not found!"
	debug_error_string = "{"created":"@1530451116.454542000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"Method not found!","grpc_status":12}"
>
```

**Comment by Pet3ris** [comment]
Sorry - realised that port `50051` was occupied!
