### ISSUE TITLE
python AttributeError: 'Channel' object has no attribute '_connectivity_state'

### ISSUE THREAD

**Issue by wangqiqianggithub** [grpc/grpc#15936]
When I started the client, an error occurred。the error message is:
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    channel = grpc.insecure_channel('127.0.0.1',8080)
  File "C:\Users\qiqia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\grpc\__init__.py", line 1584, in insecure_channel
    return _channel.Channel(target, () if options is None else options, None)
  File "C:\Users\qiqia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\grpc\_channel.py", line 876, in __init__
    _common.encode(target), _options(options), credentials)
  File "C:\Users\qiqia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\grpc\_channel.py", line 856, in _options
    return list(options) + [
TypeError: 'int' object is not iterable
Exception ignored in: <bound method Channel.__del__ of <grpc._channel.Channel object at 0x02D03470>>
Traceback (most recent call last):
  File "C:\Users\qiqia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\grpc\_channel.py", line 942, in __del__
    _moot(self._connectivity_state)
AttributeError: 'Channel' object has no attribute '_connectivity_state'

somebody who know this error,help me please,thank you very much.

**Comment by srini100** [comment]
@wangqiqianggithub , can you please provide reproduction steps and out of pip freeze. Thanks.

**Comment by mehrdada** [comment]
Closing as we never heard back and we don't have a repro case. Please let us know if you have a clear reproduction example.  Thanks!
