### ISSUE TITLE
 build_artifact.python_windows_x64_Python34 broken on windows.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15951]
Broken in 100% runs.

First occurrence is here:
https://source.cloud.google.com/results/invocations/cbe8fc02-7a9b-4f9e-81a1-51f87a2d4c37/targets/github%2Fgrpc/tests

The culprit might be `T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\poison.c:1:2: error: `

```
T:\src\github\grpc\workspace_python_windows_x64_Python34>python setup.py build_ext -c mingw32   || goto :error
running build_ext
building 'grpc._cython.cygrpc' extension
C:\tools\msys64\mingw64\bin\gcc.exe -mdll -O -Wall -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DWIN32_LEAN_AND_MEAN=1 -DCARES_STATICLIB=1 -DGRPC_ARES=0 -DNTDDI_VERSION=100663296 -DNOMINMAX=1 -DMS_WIN64=1 -Isrc\python\grpcio -Iinclude -I. -Ithird_party\boringssl\include -Ithird_party\zlib -Ithird_party\nanopb -Ithird_party\cares -Ithird_party\cares\cares -Ithird_party\address_sorting\include -IC:\Python34\include -IC:\Python34\include -c T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\poison.c -o t:\src\github\grpc\workspace_python_windows_x64_python34\src\python\grpcio\poison.o -std=c++11 -D_hypot=hypot -D_ftime=_ftime64 -D_timeb=__timeb64 -DPB_FIELD_16BIT
cc1.exe: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C
T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\poison.c:1:2: error: #error Extensions have been poisoned due to missing Cython-generated code.
 #error Extensions have been poisoned due to missing Cython-generated code.
  ^~~~~
C:\tools\msys64\mingw64\bin\gcc.exe -mdll -O -Wall -IC:\Python34\include -IC:\Python34\include -c T:\tmp\tmp579t2vue\a.c -o t:\tmp\tmp579t2vue\a.o
This package needs to generate C files with Cython but it cannot. Poisoning extension sources to disallow extension commands...You requested a Cython build via GRPC_PYTHON_BUILD_WITH_CYTHON, but do not have Cython installed. We won't stop you from using other commands, but the extension files will fail to build.
Found cython-generated files...
Traceback (most recent call last):
  File "C:\Python34\lib\distutils\cygwinccompiler.py", line 170, in _compile
    extra_postargs)
  File "T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "C:\Python34\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Python34\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Python34\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\tools\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\commands.py", line 292, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "C:\Python34\lib\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:\Python34\lib\distutils\cygwinccompiler.py", line 172, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\tools\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 348, in <module>
    cmdclass=COMMAND_CLASS,
  File "C:\Python34\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\commands.py", line 297, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "C:\Python34\lib\distutils\cygwinccompiler.py", line 170, in _compile
    extra_postargs)
  File "T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "C:\Python34\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Python34\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Python34\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\tools\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "T:\src\github\grpc\workspace_python_windows_x64_Python34\src\python\grpcio\commands.py", line 292, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "C:\Python34\lib\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:\Python34\lib\distutils\cygwinccompiler.py", line 172, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\tools\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
```

**Comment by mehrdada** [comment]
Looks like a new version of Cython has been released yesterday. I strongly suspect that's the cause of the failure. Is it happening on any other platforms? https://pypi.org/project/Cython/#history
