### ISSUE TITLE
Error while running rake from source code !

### ISSUE THREAD

**Issue by rohitsakala** [grpc/grpc#15996]
### What version of gRPC and what language are you using?
Version : Latest source code from master
Language : Ruby
 
### What operating system (Linux, Windows, …) and version?
Linux - SUSE, s390x architecture
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Using rake to install grpc from source code. Link : https://github.com/grpc/grpc/tree/master/src/ruby 
 
### What did you do?

1. git clone https://github.com/grpc/grpc.git
2. cd grpc/src/ruby
3. git submodule update --init
4. gem install bundle
5. bundle install
6. rake

Link to Google Protobuf Issue : https://github.com/google/protobuf/issues/4893
 
### What did you expect to see?
Successful completion of command rake.
 
### What did you see instead?
```Inspecting 63 files
...............................................................

63 files inspected, no offenses detected
/usr/local/rvm/rubies/ruby-2.3.1/bin/ruby -I/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib:/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-support-3.7.1/lib /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb
/grpc/src/ruby/spec/channel_credentials_spec.rb:19: warning: already initialized constant CallCredentials
/grpc/src/ruby/spec/call_credentials_spec.rb:18: warning: previous definition of CallCredentials was here

An error occurred while loading ./src/ruby/spec/google_rpc_status_utils_spec.rb.
Failure/Error: Any = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.protobuf.Any").msgclass

NoMethodError:
  undefined method `msgclass' for nil:NilClass
# /usr/local/rvm/gems/ruby-2.3.1/gems/google-protobuf-3.6.0/lib/google/protobuf/any_pb.rb:15:in `<module:Protobuf>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/google-protobuf-3.6.0/lib/google/protobuf/any_pb.rb:14:in `<module:Google>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/google-protobuf-3.6.0/lib/google/protobuf/any_pb.rb:13:in `<top (required)>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/googleapis-common-protos-types-1.0.1/lib/google/rpc/status_pb.rb:6:in `require'
# /usr/local/rvm/gems/ruby-2.3.1/gems/googleapis-common-protos-types-1.0.1/lib/google/rpc/status_pb.rb:6:in `<top (required)>'
# ./src/ruby/lib/grpc/google_rpc_status_utils.rb:16:in `require'
# ./src/ruby/lib/grpc/google_rpc_status_utils.rb:16:in `<top (required)>'
# ./src/ruby/spec/google_rpc_status_utils_spec.rb:16:in `require_relative'
# ./src/ruby/spec/google_rpc_status_utils_spec.rb:16:in `<top (required)>'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1954:in `load'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1954:in `load_spec_file_handling_errors'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1496:in `block in load_spec_files'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1494:in `each'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1494:in `load_spec_files'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:100:in `setup'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
# /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec:4:in `<main>'

Finished in 0.00014 seconds (files took 0.23957 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Coverage report generated for wrapper to /grpc/coverage. 334 / 1011 LOC (33.04%) covered.
/usr/local/rvm/rubies/ruby-2.3.1/bin/ruby -I/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib:/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-support-3.7.1/lib /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb failed```

**Comment by rohitsakala** [comment]
Hi @apolcyn,

Any update on the error?

Thanks :)

**Comment by prankkelkar** [comment]
Any updates? @rohitsakala

**Comment by apolcyn** [comment]
sorry there, this feels like a potential memory bug somewhere between the grpc and protobuf libraries. On the mentioned platform, how reliably does this reproduce? E.g.., is it flakey, or does the exception ever change to a different one?

**Comment by rohitsakala** [comment]
Hi @apolcyn , it is always reproducible in the mentioned platform.

**Comment by prankkelkar** [comment]
Even i am facing the same issue on rhel 7.6 s390x. It is working on ubuntu Distro.

**Comment by rohitsakala** [comment]
Hi @prankkelkar , was it working on Ubuntu s390x ?

**Comment by apolcyn** [comment]
Anyone able to do a short script that involves just a `require` of that  `googleapis-common-protos-types-1.0.1/lib/google/rpc/status_pb.rb` file, and that alone?

If we can do that, and hit the same bug, then this could be narrowed down to a platform-specific bug with protobuf

**Comment by prankkelkar** [comment]
@rohitsakala Yes few months back i had built the same on ubuntu 18.04 s390x

**Comment by prankkelkar** [comment]
One workaround is to try building grpc gem by mske command from source .

**Comment by prankkelkar** [comment]
another solution : comment out google protobuf as dependancy in Gemfile of grpc and run bundle install to install remaining required gems. now build google-protobuf gem separately and keep it in local repository along with other gems installed. then edit the gemfile to install gems from this local source.

**Comment by alto-ruby** [comment]
Looks like fixed in https://github.com/protocolbuffers/upb/pull/119. Closing, feel free to reopen if not the case.
