### ISSUE TITLE
compute_engine_creds interop test is failing when run from Windows.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#1604]
The call fails with StatusCode=Unauthenticated, Detail="Request had invalid credentials.".

$ grpc_cloud_prod_auth_test compute_engine_creds jtattermusch-interop-windows2 csharp_dotnet
will run:
  cd /cygdrive/c/github/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug && SSL_CERT_FILE=/cacerts/roots.pem ./Grpc.IntegrationTesting.Client.exe --use_tls=true --server_port=443 --server_host=grpc-test.sandbox.google.com --server_host_override=grpc-test.sandbox.google.com --test_case=compute_engine_creds
on jtattermusch-interop-windows2 (through grpc-windows-proxy)
[1] 28932
pid is 28932
  PID TTY          TIME CMD
28932 pts/37   00:00:00 gcloud
  PID TTY          TIME CMD
28932 pts/37   00:00:00 gcloud
  PID TTY          TIME CMD
28932 pts/37   00:00:00 gcloud
Warning: Permanently added '104.155.196.56' (ECDSA) to the list of known hosts.
gRPC C# interop testing client
GRPC initialized.
  PID TTY          TIME CMD
28932 pts/37   00:00:00 gcloud
running compute_engine_creds
D5/14/2015 11:00:20 PM 5225336 c:\github\grpc\src\core\transport\chttp2\frame_settings.c:226: adding 983041 for initial_window change

Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unauthenticated, Detail="Request had invalid credentials.")
   at Grpc.Core.Utils.ExceptionHelper.UnwrapRpcException(AggregateException ae) in c:\github\grpc\src\csharp\Grpc.Core\Utils\ExceptionHelper.cs:line 51
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(Channel channel, String methodName, TRequest msg, Metadata headers) in c:\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 109
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](Call`2 call, TRequest req, CancellationToken token) in c:\github\grpc\src\csharp\Grpc.Core\Calls.cs:line 53
   at grpc.testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, CancellationToken token) in c:\github\grpc\src\csharp\Grpc.IntegrationTesting\TestGrpc.cs:line 105
   at Grpc.IntegrationTesting.InteropClient.RunComputeEngineCreds(ITestServiceClient client) in c:\github\grpc\src\csharp\Grpc.IntegrationTesting\InteropClient.cs:line 352
   at Grpc.IntegrationTesting.InteropClient.RunTestCase(String testCase, ITestServiceClient client) in c:\github\grpc\src\csharp\Grpc.IntegrationTesting\InteropClient.cs:line 168
   at Grpc.IntegrationTesting.InteropClient.Run() in c:\github\grpc\src\csharp\Grpc.IntegrationTesting\InteropClient.cs:line 136
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args) in c:\github\grpc\src\csharp\Grpc.IntegrationTesting\InteropClient.cs:line 100
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args) in c:\github\grpc\src\csharp\Grpc.IntegrationTesting.Client\Program.cs:line 43
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [127].
[1]+  Exit 1                  gcloud compute $project_opt ssh $zone_opt stoked-keyword-656@grpc-windows-proxy --command "ssh $host '$cmd'"
  PID TTY          TIME CMD
 test runner return 1 before timeout

**Comment by jtattermusch** [comment]
Upon creation of a GCE instance, you have to specify "--scopes https://www.googleapis.com/auth/xapi.zoo" parameter in order for compute_engine_creds work. 
I recreated the GCE windows instance I was using with the right params and the test is now passing.
