### ISSUE TITLE
"cloud_to_cloud:node:python_server:status_code_and_message" interop test broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16078]
Failing consistently on master. I haven't been able to track this down to a PR that caused it since we had the dart breakage.

the error looks like an encoding problem:
```
assert.js:77
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- 'Exception iterating responses: \'ascii\' codec can\'t encode characters in position 22-26: ordinal not in range(128)'
+ 'test status message - '
    at ClientDuplexStream.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:364:12)
    at ClientDuplexStream.emit (events.js:182:13)
    at ClientDuplexStream._emitStatusIfDone (/var/local/git/grpc-node/packages/grpc-native-core/src/client.js:238:10)
    at ClientDuplexStream._receiveStatus (/var/local/git/grpc-node/packages/grpc-native-core/src/client.js:213:8)
    at Object.onReceiveStatus (/var/local/git/grpc-node/packages/grpc-native-core/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/var/local/git/grpc-node/packages/grpc-native-core/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/var/local/git/grpc-node/packages/grpc-native-core/src/client_interceptors.js:614:8)
    at /var/local/git/grpc-node/packages/grpc-native-core/src/client_interceptors.js:1110:18
```

https://source.cloud.google.com/results/invocations/b4bc6314-3894-4596-b7ba-74eadbceb90e/targets/github%2Fgrpc/tests
https://source.cloud.google.com/results/invocations/f73767e4-5cb9-46a9-a669-56a50d62424a/targets/github%2Fgrpc/tests

**Comment by jtattermusch** [comment]
I looked at the bigquery data and this has been consistently failing starting from this build https://source.cloud.google.com/results/invocations/f12ffbd5-ed6b-4c56-b600-4ed66aba2302/targets/github%2Fgrpc/tests;query=python_server.

The previous build https://source.cloud.google.com/results/invocations/6d451e3f-369d-491f-9e07-9e4e244bb050  has succeeded, but both build are at git commit https://github.com/grpc/grpc/commit/4ba4d18960ccc762d5228a314c574050afadddac  which would indicate the the issue was introduced by merging a PR in grpc/grpc-node repository.

Assigning to @murgatroid99

**Comment by murgatroid99** [comment]
The culprit is almost definitely the test modified in grpc/grpc-node#428. But I think this actually exposes a bug in the Python implementation that it does not correctly handle UTF-8 characters, which is the bug on the Node side that was fixed in that PR.

So, we'll fix our side, but I think there should also be a change on the Python side too.

**Comment by nicolasnoble** [comment]
Closed this one by reverting the added interop behavior, and opened #16102 and #16113 to make sure the behavior is properly implemented everywhere.
