### ISSUE TITLE
C++ grpc_auth_json_key_create_from_json Null Point issue

### ISSUE THREAD

**Issue by Daemoneyes** [grpc/grpc#16154]
Trying to use gRPC to talk with Google cloud, the json got from google has been pass down to the function grpc_auth_json_key_create_from_json under 
https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/jwt/json_token.cc#L67
In my GDB stack info it show as:

`  #7  0x0188e4b4 in grpc_auth_json_key_create_from_string (
    json_string=0x9cd81c4 "{\n  \"type\": \"service_account\",\n  \"project_id\": \"psychic-etching-207502\",\n  \"private_key_id\": \"9b4a5f06ad9711b8e359cad5464c705a56ac6dcb\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkq"...)
    at src/core/lib/security/credentials/jwt/json_token.cc:123`

from the print out json string it do have the private_key part, but later on what I got is 
`#6  0x0188e42f in grpc_auth_json_key_create_from_json (json=0x9cd4d28)
    at src/core/lib/security/credentials/jwt/json_token.cc:106`

Address 0x9cd4d28 is already empty string
Later on it cause the libcrypto crash due to segment fault.

Any ideas?

 
### What version of gRPC and what language are you using?
 commit 15e95b30e962178cf8ea7c16662bd104fce0b29d with C++ GCC v7.4
 
### What operating system (Linux, Windows, …) and version?
 REHL 6.8 with devltoolset-7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 gcc 7.4
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
try use grpc to talk with google cloud.

 `		grpc::SslCredentialsOptions ssl_opts = {pem_roots, "", ""};
		std::shared_ptr<grpc::ChannelCredentials> creds = grpc::CompositeChannelCredentials(grpc::SslCredentials(ssl_opts), grpc::ServiceAccountJWTAccessCredentials(jsonKey, 3600));
`

### What did you expect to see?
 talk with google correctly
 
### What did you see instead?
 Segmentation Fault
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by Daemoneyes** [comment]
Sry I've Locate the issue is in LibCrypto. You can close it.
