### ISSUE TITLE
Problem with command [Python install]

### ISSUE THREAD

**Issue by hgorski6** [grpc/grpc#16174]
### What operating system (Linux, Windows, …) and version?
Windows 10 KB4338819
 
### What runtime / compiler are you using
 Python version
 
### What did you do?
pip install --upgrade google-assistant-sdk[samples] in Command Propmt 
 
### What did you expect to see?
 Not error
 
### What did you see instead?
 Error

```Collecting google-assistant-sdk[samples]
  Using cached https://files.pythonhosted.org/packages/63/1d/c161b38a4e7ce72edcf78aab725dcb07047c13e17dacede142931159adb4/google_assistant_sdk-0.5.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: google-auth-oauthlib[tool]>=0.1.0 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (0.2.0)
Requirement already satisfied, skipping upgrade: click<7,>=6.7; extra == "samples" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (6.7)
Requirement already satisfied, skipping upgrade: pathlib2<3,>=2.3.0; extra == "samples" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (2.3.2)
Requirement already satisfied, skipping upgrade: futures<4,>=3.1.1; extra == "samples" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (3.1.1)
Collecting google-assistant-grpc==0.2.0; extra == "samples" (from google-assistant-sdk[samples])
  Using cached https://files.pythonhosted.org/packages/d3/3c/4a44b54b196fb7f23335f17fdfd3ce477cbff2404324df2ef9ef1f3e4bd3/google_assistant_grpc-0.2.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: sounddevice<0.4,>=0.3.7; extra == "samples" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (0.3.11)
Requirement already satisfied, skipping upgrade: tenacity<5,>=4.1.0; extra == "samples" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (4.12.0)
Requirement already satisfied, skipping upgrade: urllib3[secure]<2,>=1.21; extra == "samples" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-sdk[samples]) (1.23)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (1.0.0)
Requirement already satisfied, skipping upgrade: google-auth in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (1.5.0)
Requirement already satisfied, skipping upgrade: six in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from pathlib2<3,>=2.3.0; extra == "samples"->google-assistant-sdk[samples]) (1.11.0)
Requirement already satisfied, skipping upgrade: googleapis-common-protos>=1.5.2 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-assistant-grpc==0.2.0; extra == "samples"->google-assistant-sdk[samples]) (1.5.3)
Collecting grpcio>=1.3.5 (from google-assistant-grpc==0.2.0; extra == "samples"->google-assistant-sdk[samples])
  Using cached https://files.pythonhosted.org/packages/e6/27/1f138a6f8691b8d1c1a4f2005f9293da6641c806d5626eb6c43e765962b1/grpcio-1.13.0.tar.gz
Requirement already satisfied, skipping upgrade: CFFI>=1.0 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from sounddevice<0.4,>=0.3.7; extra == "samples"->google-assistant-sdk[samples]) (1.11.5)
Requirement already satisfied, skipping upgrade: certifi; extra == "secure" in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from urllib3[secure]<2,>=1.21; extra == "samples"->google-assistant-sdk[samples]) (2018.4.16)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (2.19.1)
Requirement already satisfied, skipping upgrade: oauthlib>=0.6.2 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (2.1.0)
Requirement already satisfied, skipping upgrade: cachetools>=2.0.0 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-auth->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (2.1.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-auth->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (0.2.2)
Requirement already satisfied, skipping upgrade: rsa>=3.1.4 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from google-auth->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (3.4.2)
Requirement already satisfied, skipping upgrade: protobuf>=3.0.0 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from googleapis-common-protos>=1.5.2->google-assistant-grpc==0.2.0; extra == "samples"->google-assistant-sdk[samples]) (3.6.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from CFFI>=1.0->sounddevice<0.4,>=0.3.7; extra == "samples"->google-assistant-sdk[samples]) (2.18)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (2.7)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (3.0.4)
Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.1 in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth->google-auth-oauthlib[tool]>=0.1.0->google-assistant-sdk[samples]) (0.4.4)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages (from protobuf>=3.0.0->googleapis-common-protos>=1.5.2->google-assistant-grpc==0.2.0; extra == "samples"->google-assistant-sdk[samples]) (39.0.1)
Installing collected packages: grpcio, google-assistant-grpc, google-assistant-sdk
  Running setup.py install for grpcio ... error
    Complete output from command c:\users\huber\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\huber\\AppData\\Local\\Temp\\pip-install-s8tj37s0\\grpcio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\huber\AppData\Local\Temp\pip-record-yxmlny94\install-record.txt --single-version-externally-managed --compile:
    Found cython-generated files...
    running install
    running build
    running build_py
    running build_project_metadata
    creating python_build
    creating python_build\lib.win32-3.7
    creating python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_common.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_server.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win32-3.7\grpc
    creating python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win32-3.7\grpc\beta
    creating python_build\lib.win32-3.7\grpc\experimental
    copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win32-3.7\grpc\experimental
    copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win32-3.7\grpc\experimental
    copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win32-3.7\grpc\experimental
    creating python_build\lib.win32-3.7\grpc\framework
    copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win32-3.7\grpc\framework
    creating python_build\lib.win32-3.7\grpc\_cython
    copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win32-3.7\grpc\_cython
    creating python_build\lib.win32-3.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win32-3.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win32-3.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win32-3.7\grpc\framework\common
    creating python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win32-3.7\grpc\framework\foundation
    creating python_build\lib.win32-3.7\grpc\framework\interfaces
    copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win32-3.7\grpc\framework\interfaces
    creating python_build\lib.win32-3.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win32-3.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win32-3.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win32-3.7\grpc\framework\interfaces\base
    creating python_build\lib.win32-3.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win32-3.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win32-3.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win32-3.7\grpc\framework\interfaces\face
    creating python_build\lib.win32-3.7\grpc\_cython\_cygrpc
    copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win32-3.7\grpc\_cython\_cygrpc
    creating python_build\lib.win32-3.7\grpc\_cython\_credentials
    copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win32-3.7\grpc\_cython\_credentials
    running build_ext
    Found cython-generated files...
    building 'grpc._cython.cygrpc' extension
    Traceback (most recent call last):
      File "C:\Users\huber\AppData\Local\Temp\pip-install-s8tj37s0\grpcio\src\python\grpcio\commands.py", line 292, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
        [self.VCIncludes,
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 877, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 556, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\huber\AppData\Local\Temp\pip-install-s8tj37s0\grpcio\setup.py", line 347, in <module>
        cmdclass=COMMAND_CLASS,
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\huber\AppData\Local\Temp\pip-install-s8tj37s0\grpcio\src\python\grpcio\commands.py", line 295, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "C:\Users\huber\AppData\Local\Temp\pip-install-s8tj37s0\grpcio\src\python\grpcio\support.py", line 109, in diagnose_build_ext_error
        "backtrace).\n\n{}".format(formatted))
    commands.CommandError:

    We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).

    Traceback (most recent call last):
      File "C:\Users\huber\AppData\Local\Temp\pip-install-s8tj37s0\grpcio\src\python\grpcio\commands.py", line 292, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
        [self.VCIncludes,
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 877, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\users\huber\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\msvc.py", line 556, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools


    ----------------------------------------
Command "c:\users\huber\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\huber\\AppData\\Local\\Temp\\pip-install-s8tj37s0\\grpcio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\huber\AppData\Local\Temp\pip-record-yxmlny94\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\huber\AppData\Local\Temp\pip-install-s8tj37s0\grpcio\```

**Comment by mehrdada** [comment]
You are using 32-bit Python 3.7 on Windows. We don't yet have binary wheels produced for that platform (we are working on it and will happen as soon as our continuous integration infra provides that distribution on the installed images; tracking bug: https://github.com/grpc/grpc/issues/15968) and you'll need build-from-source toolchain installed for the source build to work. In the meantime, my suggested workaround is to switch to a 64-bit Python3.7 on Windows or downgrade to Python3.6 where we do have binary wheels.

I'm closing this bug as we can consolidate discussions around this issue in the bug I referenced above.

**Comment by mehrdada** [comment]
32-bit Python 3.7 binary wheels for Windows are now uploaded on PyPI.
