### ISSUE TITLE
ConcurrentObjectUseError with grpc + gevent

### ISSUE THREAD

**Issue by bastova** [grpc/grpc#16216]
### What version of gRPC and what language are you using?
 grpcio 1.12.1 python
 
### What operating system (Linux, Windows, …) and version?
Centos 7.5, kernel 4.7.11
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 2.7.10
 
### What did you do?
I have a gunicorn+gevent+grpc setup. I have gcloud libraries imported but not actually using them yet. I have also checked that gevent is using 'libev' and not 'libuv' event loop. 

I am patching grpc in a custom gunicorn worker:

gevent_grpc_worker.py:
```
import gunicorn.workers.ggevent


class GeventGrpcWorker(gunicorn.workers.ggevent.GeventWorker):

  def patch(self):
    super(GeventGrpcWorker, self).patch()

    # Patch grpc library to support gevent.
    import grpc._cython.cygrpc
    grpc._cython.cygrpc.init_grpc_gevent()
    self.log.info('GeventGrpcWorker: patched grpc.')
```

gunicorn.conf:
```
bind = "unix:/tmp/gunicorn.sock"
workers = 129
worker_class = "gevent_grpc_worker.GeventGrpcWorker"
logerror = "/mnt/log/gunicorn-error.log"
max_requests = 100000
backlog = 2048
user = "dropcam"
group = "dropcam"
pidfile = "/var/run/gunicorn.pid"
timeout = 90
worker_connections = 25
```

I am using:
gunicorn==19.8.1
grpcio==1.12.1
gevent==1.3.5
greenlet==0.4.14
google-cloud-core==0.28.1
google-cloud-pubsub==0.35.4
google-cloud-storage==1.10.0
google-cloud-bigquery==1.4.0
google-api-core==1.3.0
google-api-python-client==1.7.4
google-apitools==0.5.23
grpc-google-iam-v1==0.11.4

I am getting the following stack trace in my logs. There is no request_id meaning that it's not tied to a specific operation/web-request, so it's not causing any issues yet, and I am not aware of what's triggering it. Regardless, it doesn't seem like the right thing is happening, seems like some kind of incompatibility with the google auth library and gevent.
```
2018-08-01 08:24:08,146 ERROR [root] request_id=None AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x152a040fe610>" raised exception!
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "/usr/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/usr/lib/python2.7/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/usr/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/usr/lib/python2.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/lib/python2.7/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/usr/lib/python2.7/site-packages/google_auth_httplib2.py", line 116, in __call__
    url, method=method, body=body, headers=headers, **kwargs)
  File "/usr/lib64/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/external_trace.py", line 103, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()
  File "/usr/lib64/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/external_httplib.py", line 65, in httplib_getresponse_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib64/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/site-packages/gevent/_sslgte279.py", line 457, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/site-packages/gevent/_sslgte279.py", line 318, in read
    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 245, in gevent.__hub_primitives._primitive_wait
ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.__waiter.Waiter object at 0x152a03bfe9f0>>
```
 
### What did you expect to see?
 No errors around grpc + gevent
 
### What did you see instead?
ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.__waiter.Waiter object at 0x152a03bfe9f0>>

**Comment by mehrdada** [comment]
Can you try the latest gRPC and see if it still happens? There have been a number of gevent fixes since I think.

**Comment by bastova** [comment]
Don't see issues after update, closing.

**Comment by mehrdada** [comment]
Cool, thanks for the update.
