### ISSUE TITLE
mac opt tests failing due to python install problem

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#16270]
https://source.cloud.google.com/results/invocations/cb811bf7-b7ab-4788-afb5-e24b81fc8b4e/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_opt/log

Looks like this is the error:

```
Download error on https://pypi.python.org/simple/futures/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600) -- Some packages may not be found!
Couldn't find index page for 'futures' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600) -- Some packages may not be found!
No local packages or working download links found for futures>=2.2.0
Traceback (most recent call last):
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_health_checking/setup.py", line 95, in <module>
    cmdclass=COMMAND_CLASS)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/setuptools/dist.py", line 315, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
    replace_conflicting=True,
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py34_gevent/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('futures>=2.2.0')

2018-08-06 15:29:02,761 FAILED: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=59431, time=325.2sec]
```

**Comment by jtattermusch** [comment]
This is failing 100% of mac opt builds on master, so we need to fix asap.

A few recent failures:
https://source.cloud.google.com/results/invocations/f6742277-341b-4f6f-ab5b-6458a5d6ee1f/targets/github%2Fgrpc%2Faggregate_tests/tests
https://source.cloud.google.com/results/invocations/b4464015-9d59-42c6-91f3-170647614124/targets/github%2Fgrpc%2Faggregate_tests/tests
https://source.cloud.google.com/results/invocations/c1857d07-d8b0-4b98-985d-1c553a2cf918/targets/github%2Fgrpc%2Faggregate_tests/tests

**Comment by mehrdada** [comment]
@jtattermusch this is not a network failure?

**Comment by mehrdada** [comment]
Looks like some sort of pip failure, but probably not a network issue... investigating.
