### ISSUE TITLE
protobuf_at_head test suite is broken: python build failing at  _protoc_compiler.so

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16333]
First failing build, failing consistently since then
https://source.cloud.google.com/results/invocations/ef98d949-6132-4dd1-a6a7-553e0e90ce34/targets

(probably some PR got merged in google/protobuf that broke this).

`ImportError: Error relocating /var/local/git/grpc/py27_native/lib/python2.7/sitepackages/grpc_tools/_protoc_compiler.so:_ZN6google8protobuf8compiler11SCCAnalyzer3DFSEPKNS0_10DescriptorE: symbol not found`

```
Processing /var/local/git/grpc/tools/distrib/python/grpcio_tools
Building wheels for collected packages: grpcio-tools
  Running setup.py bdist_wheel for grpcio-tools: started
  Running setup.py bdist_wheel for grpcio-tools: finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-4UScRn/wheels/bb/24/1f/d3aec3b098b62df25737cdaffa904d0bc5015aebac7d200fd1
Successfully built grpcio-tools
Installing collected packages: grpcio-tools
Successfully installed grpcio-tools-1.15.0.dev0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ cd /var/local/git/grpc/tools/distrib/python/grpcio_tools
+ /var/local/git/grpc/py27_native/bin/python2.7 /var/local/git/grpc/src/python/grpcio_health_checking/setup.py preprocess
running preprocess
+ /var/local/git/grpc/py27_native/bin/python2.7 /var/local/git/grpc/src/python/grpcio_health_checking/setup.py build_package_protos
running build_package_protos
Traceback (most recent call last):
  File "/var/local/git/grpc/src/python/grpcio_health_checking/setup.py", line 95, in <module>
    cmdclass=COMMAND_CLASS)
  File "/var/local/git/grpc/py27_native/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_health_checking/health_commands.py", line 61, in run
    from grpc_tools import command
  File "/var/local/git/grpc/py27_native/lib/python2.7/site-packages/grpc_tools/command.py", line 21, in <module>
    from grpc_tools import protoc
  File "/var/local/git/grpc/py27_native/lib/python2.7/site-packages/grpc_tools/protoc.py", line 20, in <module>
    from grpc_tools import _protoc_compiler
ImportError: Error relocating /var/local/git/grpc/py27_native/lib/python2.7/site-packages/grpc_tools/_protoc_compiler.so: _ZN6google8protobuf8compiler11SCCAnalyzer3DFSEPKNS0_10DescriptorE: symbol not found
2018-08-11 10:17:48,659 FAILED: /var/local/git/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=373, time=797.9sec]
```

**Comment by jtattermusch** [comment]
This is the google/protobuf diff between green build and red build. It seems that the down-integrate from google3 could have broken our build:
https://github.com/google/protobuf/compare/fe80059c8d5d78f73b9b3bd0f6276c7b05a3f574...acd5b05e9f1ec2153574807463af0612267b6067

@xfxyjwf any ideas?

**Comment by xfxyjwf** [comment]
@jtattermusch The missing symbol is from this new source file:
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/scc.cc

It seems you have a list of protoc source files in your own build. If the list is auto-generated from protobuf bazel BUILD file, you probably need to sync past https://github.com/google/protobuf/commit/bde4eaf137c5c5ee3f6ffa4288307750d95c6281

**Comment by mehrdada** [comment]
Evidently it has started passing again. Closing. Thanks @xfxyjwf.
