### ISSUE TITLE
tools/run_tests/helper_scripts/run_grpc-node.sh bash error

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#16380]
https://source.cloud.google.com/results/invocations/8e0dd169-e778-4d6c-b6b9-ae51c17ab404/targets/github%2Fgrpc%2Fgrpc-node_macos_opt_native/tests

```
2018-08-16 19:03:26,854 WAITING: ETA 1.1 sec; 0 queued, 1 jobs running, 1 complete, 0 failed (load 1.00)
2018-08-16 19:03:26,893 PASSED: /Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-native-core/binding.gyp [time=1.1sec, retries=0:0]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
100   448  100   448    0     0     22      0  0:00:20  0:00:19  0:00:01    90
100   448  100   448    0     0     22      0  0:00:20  0:00:19  0:00:01   114
bash: line 2: syntax error near unexpected token `newline'
bash: line 2: `<?xml version="1.0" encoding="utf-8"?>'
./run-tests.sh: line 23: /Users/kbuilder/.nvm/nvm.sh: No such file or directory
```

**Comment by yashykt** [comment]
```
found 14 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN gts@0.5.4 requires a peer of typescript@^2.6.1 but none is installed. You must install peer dependencies yourself.
> grpc@1.25.0-dev install /Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-native-core
> node-pre-gyp install --fallback-to-build --library=static_library
[18:32:08] Finished 'install' after 3.58 s
npm ERR! code ENOENT
npm ERR! syscall lchown
npm ERR! path /Users/kbuilder/.npm/_locks/staging-85077874ff9f9636.lock
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lchown '/Users/kbuilder/.npm/_locks/staging-85077874ff9f9636.lock'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kbuilder/.npm/_logs/2019-09-20T01_32_08_492Z-debug.log
[18:32:08] 'install' errored after 3.63 s
[18:32:08] Error: exited with error code: 254
    at ChildProcess.onexit (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:214:15)
    at ChildProcess.EventEmitter.emit (domain.js:499:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[18:32:08] 'setup' errored after 3.63 s
[18:32:08] The following tasks did not complete: <anonymous>, install, <series>, runInstall
[18:32:08] Did you forget to signal async completion?
``` 

probably a similar transient error
