### ISSUE TITLE
ASAN failure for newly introduced //test/cpp/qps:qps_json_driver_test bazel tests

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16491]
Some of the newly added tests from https://github.com/grpc/grpc/pull/16402  are failing with 100% failure rate on ASAN.

E.g. here: https://source.cloud.google.com/results/invocations/d967d661-c511-455e-bd24-3c48379b3d78/targets

The failing tests are 
`//test/cpp/qps:qps_json_driver_test_cpp_generic_async_streaming_qps_unconstrained_64KBmsg_insecure`
and 
`//test/cpp/qps:qps_json_driver_test_cpp_protobuf_async_streaming_from_client_1channel_1MB`, for all pollers.

All the listed test cases seem to be failing with a memory leak (there are more kinds but all seem to be related to slice.cc).
```
=================================================================
==18==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 131120 byte(s) in 2 object(s) allocated from:
    #0 0x4c9713 in malloc /tmp/clang-build/src/compiler-rt/lib/asan/asan_malloc_linux.cc:88:3
    #1 0x7fa45aff925c in gpr_malloc /proc/self/cwd/src/core/lib/gpr/alloc.cc:57:7
    #2 0x7fa45b16ba16 in grpc_slice_malloc_large /proc/self/cwd/src/core/lib/slice/slice.cc:242:7
    #3 0x7fa45b16a5c3 in grpc_slice_malloc /proc/self/cwd/src/core/lib/slice/slice.cc:265:12
    #4 0x7fa45b16b861 in grpc_slice_from_copied_buffer /proc/self/cwd/src/core/lib/slice/slice.cc:199:22
    #5 0x7fa45bdc25e7 in grpc::CoreCodegen::grpc_slice_from_copied_buffer(void const*, unsigned long) /proc/self/cwd/src/cpp/common/core_codegen.cc:181:10
    #6 0x7fa45c359a76 in grpc::Slice::Slice(void const*, unsigned long) /proc/self/cwd/include/grpcpp/impl/codegen/slice.h:57:42
    #7 0x7fa45c3aafd0 in grpc::testing::ProcessGenericRPC(grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*) /proc/self/cwd/test/cpp/qps/server_async.cc:565:9
    #8 0x7fa45c3f27a1 in std::_Function_handler<grpc::Status (grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*), grpc::Status (*)(grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*)>::_M_invoke(std::_Any_data const&, grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2024:9
    #9 0x7fa45c3fc913 in std::function<grpc::Status (grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*)>::operator()(grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2440:14
    #10 0x7fa45c3fc5a2 in grpc::Status std::_Bind<std::function<grpc::Status (grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*)> (grpc::testing::PayloadConfig, std::_Placeholder<1>, std::_Placeholder<2>)>::__call<grpc::Status, grpc::ByteBuffer*&&, grpc::ByteBuffer*&&, 0ul, 1ul, 2ul>(std::tuple<grpc::ByteBuffer*&&, grpc::ByteBuffer*&&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11
    #11 0x7fa45c3fc2f2 in grpc::Status std::_Bind<std::function<grpc::Status (grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*)> (grpc::testing::PayloadConfig, std::_Placeholder<1>, std::_Placeholder<2>)>::operator()<grpc::ByteBuffer*, grpc::ByteBuffer*, grpc::Status>(grpc::ByteBuffer*&&, grpc::ByteBuffer*&&) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:17
    #12 0x7fa45c3fbb12 in std::_Function_handler<grpc::Status (grpc::ByteBuffer*, grpc::ByteBuffer*), std::_Bind<std::function<grpc::Status (grpc::testing::PayloadConfig const&, grpc::ByteBuffer*, grpc::ByteBuffer*)> (grpc::testing::PayloadConfig, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, grpc::ByteBuffer*, grpc::ByteBuffer*) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2024:9
    #13 0x7fa45c3fe909 in std::function<grpc::Status (grpc::ByteBuffer*, grpc::ByteBuffer*)>::operator()(grpc::ByteBuffer*, grpc::ByteBuffer*) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2440:14
    #14 0x7fa45c403257 in grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::ServerRpcContextStreamingImpl::read_done(bool) /proc/self/cwd/test/cpp/qps/server_async.cc:347:31
    #15 0x7fa45c402c42 in grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::ServerRpcContextStreamingImpl::RunNextState(bool) /proc/self/cwd/test/cpp/qps/server_async.cc:321:50
    #16 0x7fa45c415517 in grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::ThreadFunc(int)::'lambda'()::operator()() const /proc/self/cwd/test/cpp/qps/server_async.cc:224:21
    #17 0x7fa45c415269 in grpc::CompletionQueue::NextStatus grpc::CompletionQueue::DoThenAsyncNext<gpr_timespec, grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::ThreadFunc(int)::'lambda'()>(grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::ThreadFunc(int)::'lambda'()&&, void**, bool*, gpr_timespec const&) /proc/self/cwd/include/grpcpp/impl/codegen/completion_queue.h:209:5
    #18 0x7fa45c3f5599 in grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::ThreadFunc(int) /proc/self/cwd/test/cpp/qps/server_async.cc:221:41
    #19 0x7fa45c4145ec in void std::_Mem_fn<void (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::*)(int)>::operator()<int, void>(grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>*, int&&) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11
    #20 0x7fa45c414482 in void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::*)(int)> (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>*, int)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18
    #21 0x7fa45c4143f4 in std::_Bind_simple<std::_Mem_fn<void (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::*)(int)> (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>*, int)>::operator()() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16
    #22 0x7fa45c414118 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>::*)(int)> (grpc::testing::AsyncQpsServerTest<grpc::ByteBuffer, grpc::ByteBuffer, grpc::AsyncGenericService, grpc::GenericServerContext>*, int)> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13
    #23 0x7fa459b15c7f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c7f)
SUMMARY: AddressSanitizer: 131120 byte(s) leaked in 2 allocation(s).
```

**Comment by jtattermusch** [comment]
CC @adelez  @dgquintas

**Comment by adelez** [comment]
Dup of #16471

**Comment by vjpai** [comment]
I'm not sure that this is a dup of the other issue, as the other issue seems to see far fewer failures than we're seeing now pretty consistently since the new tests were added. Additionally, the new failures seem to be much more widespread than even just ASAN.
