### ISSUE TITLE
ObjectDisposedException when accessing ServerCallContext.Peer

### ISSUE THREAD

**Issue by jlao** [grpc/grpc#16570]
### What version of gRPC and what language are you using?
 Language is C#. Using Grpc 1.14.2.
 
### What operating system (Linux, Windows, …) and version?
 Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET Framework 4.6.2
 
### What did you do?
We have an interceptor that logs some information about all requests. Notably, we log Method, Host, Peer, and Status from the ServerCallContext.
 
### What did you expect to see?
We should see a log with the information from ServerCallContext.
 
### What did you see instead?
This usually works, but every once in a while we see an ObjectDisposedException when we access ServerCallContext.Peer.  Here's the stack trace:

```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.CallSafeHandle.GetPeer()
```

We did some investigation and found we could reproduce this consistently when we kill the caller with Ctrl+C so the channel is disconnected unexpectedly.

I looked in the gRPC code and found this:
```
        public string Peer
        {
            get
            {
                if (testingOnlyPeerGetter != null)
                {
                    return testingOnlyPeerGetter();
                }
                // Getting the peer lazily is fine as the native call is guaranteed
                // not to be disposed before user-supplied server side handler returns.
                // Most users won't need to read this field anyway.
                return this.callHandle.GetPeer();
            }
        }
```

Maybe the comment is wrong? Maybe it is only true for the handler but not the interceptors? Not sure.

### Anything else we should know about your project / environment?

Everything is pretty vanilla. We use Visual Studio 2017.

**Comment by JimHume** [comment]
I'm experiencing the same type of exception when attempting to use the auth context:
```System.ObjectDisposedException: Safe handle has been closed
   at void System.Runtime.InteropServices.SafeHandle.DangerousAddRef(ref bool success)
   at IntPtr System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, ref bool success)
   at AuthContextSafeHandle Grpc.Core.Internal.CallSafeHandle.GetAuthContext() in T:/src/github/grpc/src/csharp/Grpc.Core/Internal/CallSafeHandle.cs:line 199
   at AuthContext Grpc.Core.ServerCallContext.GetAuthContextEager() in T:/src/github/grpc/src/csharp/Grpc.Core/ServerCallContext.cs:line 217
   at Boxed System.Lazy<T>.CreateValue()
   at T System.Lazy<T>.LazyInitValue()
   at T System.Lazy<T>.get_Value()
   at AuthContext Grpc.Core.ServerCallContext.get_AuthContext() in T:/src/github/grpc/src/csharp/Grpc.Core/ServerCallContext.cs:line 211```

and:

```System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.CallSafeHandle.GetAuthContext()
   at Grpc.Core.ServerCallContext.GetAuthContextEager()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Grpc.Core.ServerCallContext.get_AuthContext()
   at My.Grpc.Utils.Interceptors.Transient.ServerCallContextValidator.CustomAuthContextMethod(ServerCallContext context)
   at My.Grpc.Utils.Interceptors.Transient.GrpcServerAuthInterceptor.<CustomAuthContextMethod>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at My.Grpc.Utils.Interceptors.Transient.GrpcServerAuthInterceptor.<UnaryServerHandler>d__3`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__4.MoveNext()```

The server is C# with the client coming from dart.

**Comment by JimHume** [comment]
I'm still seeing this issue in version 1.19.0 and I will be testing it against 1.23.0 within the next couple of weeks.

**Comment by aaronhudon-ts** [comment]
I am seeing this behavior in the stream override methods of my service.  It is easily reproducible by having a client connect and disconnect in quick succession.
