### ISSUE TITLE
Ruby test failure about status code

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#16587]
To be honest, I'm not sure how to read this failure log.. But this test failure happens on my PR(https://github.com/grpc/grpc/pull/16575) that should only affect the behavior of this line in test (https://github.com/grpc/grpc/blob/bbc9a203c97e2b6a73991345fdc18e87d6466237/test/cpp/end2end/client_lb_end2end_test.cc#L574). So I think there is something wrong with the Ruby test itself.

https://source.cloud.google.com/results/invocations/071d734a-5e0c-4bcf-a735-865d1c39d87e/targets/github%2Fgrpc%2Fruby_linux_dbg_native/tests

```
Failures:
  1) ClientStub #bidi_streamer without a call operation behaves like bidi streaming client-side error handling on bidi streams receives a grpc status code when reading from a failed bidi call
     Failure/Error:
       fail GRPC::BadStatus.new_status_exception(
         status.code, status.details, md)
     GRPC::Internal:
       13:Received RST_STREAM with error code 2
     Shared Example Group: "bidi streaming" called from ./src/ruby/spec/generic/client_stub_spec.rb:859
     # ./src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
     # ./src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
     # ./src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
     # ./src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
     # /usr/local/rvm/gems/ruby-2.1.10/gems/rspec-core-3.8.0/exe/rspec:1:in `each'
Finished in 0.15751 seconds (files took 0.27019 seconds to load)
25 examples, 1 failure
Failed examples:
rspec './src/ruby/spec/generic/client_stub_spec.rb[1:5:1:1:9:2]' # ClientStub #bidi_streamer without a call operation behaves like bidi streaming client-side error handling on bidi streams receives a grpc status code when reading from a failed bidi call

```

**Comment by AspirinSJL** [comment]
Stale.
