### ISSUE TITLE
All foundry tests red: upload_rb_results.py failing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16589]
Seems to be happening for all foundry tests on master

https://source.cloud.google.com/results/invocations/85785cf1-8281-4e6e-abe1-389f8d122cfb/log
https://source.cloud.google.com/results/invocations/0966f827-f71f-424e-bba3-25694b5a7bef/log

```
+ python ./tools/run_tests/python_utils/upload_rbe_results.py
Traceback (most recent call last):
  File "./tools/run_tests/python_utils/upload_rbe_results.py", line 136, in <module>
    resultstore_actions = _get_resultstore_data(api_key, invocation_id)
  File "./tools/run_tests/python_utils/upload_rbe_results.py", line 120, in _get_resultstore_data
    all_actions.extend(results['actions'])
KeyError: 'actions'
[ID: 2494210] Build finished after 4016 secs, exit value: 1
```

**Comment by jtattermusch** [comment]
CC @adelez

**Comment by jtattermusch** [comment]
The corresponding bazel links logs have no useful information: 
https://source.cloud.google.com/results/invocations/d256d2c7-57b1-4527-ac41-944fe3fa2066/targets

the only interesting things I can see in the kokoro logs is
```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Option 'bes_best_effort' is deprecated: BES best effort upload has been removed. The flag has no more functionality attached to it and will be removed in a future release.
INFO: Streaming Build Event Protocol to buildeventservice.googleapis.com build_request_id: 487d26d0-c22c-4221-9dd0-f9fc4cad6453 invocation_id: d256d2c7-57b1-4527-ac41-944fe3fa2066
WARNING: BAZEL_INTERNAL_INVOCATION_ID is set. This will soon be deprecated in favor of --invocation_id. Please switch to using the flag.
```
It also looks like the tests have run and the kokoro jobs only fails after that, so I'm not sure if this is a problem with uploading test results on the bazel side (which would explain why bazel link shows 0 targets and our upload script fails) or if it's just our upload script failing everything.

**Comment by jtattermusch** [comment]
Filed internal b/114625469

**Comment by jtattermusch** [comment]
Resolved internally.
