### ISSUE TITLE
Bazel tests consistently fail on v1.15.x

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#16687]
Consistent failure on all bazel tests on `v1.15.x` branch for multiple reasons

A sample reason:
```
ERROR: /tmpfs/src/github/grpc/test/core/gpr/BUILD:41:1: Couldn't build file test/core/gpr/_objs/cpu_test/cpu_test.pic.o: C++ compilation of rule '//test/core/gpr:cpu_test' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed with not retriable error: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Actions can no longer target legacy instances. This can likely be fixed by changing projects/grpc-testing to projects/grpc-testing/instances/default_instance
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:286)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:121)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:215)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:66)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1043)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:971)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:900)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:118)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:744)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:699)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:459)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Actions can no longer target legacy instances. This can likely be fixed by changing projects/grpc-testing to projects/grpc-testing/instances/default_instance
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:557)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$0(GrpcRemoteExecutor.java:149)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:268)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:121)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:138)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$0(RemoteSpawnRunner.java:219)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:268)
	... 21 more
```

**Comment by jtattermusch** [comment]
I think we'd need to backport https://github.com/grpc/grpc/pull/16466/files

**Comment by jtattermusch** [comment]
And this one? https://github.com/grpc/grpc/pull/16498/files
