### ISSUE TITLE
Grpc csharp client Can't connect to Grpc server running on docker for windows

### ISSUE THREAD

**Issue by kumarmo2** [grpc/grpc#16682]
### What version of gRPC and what language are you using?
 Grpc version is 1.14.1 and language is csharp
 
### What operating system (Linux, Windows, …) and version?
 Windows 10 Pro
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 dotnet 2.1.402
 
### What did you do?
 I made a simple Grpc Server and client and ran them directly on localhost. The client is able to make the request to the server and getting a response. But when I am running the server inside a docker container and running the grpc client on localhost, the client is not able to connect to the service. 

**Grpc Server Code**
```
using System;
using Grpc.Core;
using Greeter.Proto;
using System.Threading;

namespace GreeterServer
{
    class Program
    {
        private readonly static ManualResetEvent shutdown = new ManualResetEvent(false);
        static void Main(string[] args)
        {
            int port = 5000;
            Console.WriteLine("Hello World!");
            Server server = new Server{
                Services = {GreeterService.BindService(new GreeterController())},
                Ports = {new ServerPort("localhost", port, ServerCredentials.Insecure)}
            };
            server.Start();
            Console.WriteLine("Grpc Server started");
            Console.Read();
            shutdown.WaitOne();
        }
    }
}
```
**Dockerfile**
```
FROM microsoft/dotnet:2.1-sdk as base
WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet build -c Release -o out

FROM microsoft/dotnet:2.1-runtime
WORKDIR /app
COPY --from=base /app/out .
ENTRYPOINT ["dotnet", "GreeterServer.dll"]
EXPOSE 5000

```

Command to make docker image:  **docker build -t greeter-service:1.0 .**
Command to run docker container: **docker run --rm -p 5000:5000 greeter-service:1.0**

**Grpc client**
```
using System;
using Grpc.Core;
using Greeter.Proto;

namespace GreeterClient
{
    class Program
    {
        static void Main(string[] args)
        {
            GreeterService.GreeterServiceClient client = null;
            HelloResponse response = null;
            HelloRequest request = null;
            try
            {
                Console.WriteLine("Hello World!");
                Channel channel = new Channel("127.0.0.1:5000", ChannelCredentials.Insecure);
                // Channel channel = new Channel("192.168.0.103:5000", ChannelCredentials.Insecure);
                // Channel channel = new Channel("172.17.0.2:5000", ChannelCredentials.Insecure);
                client = new GreeterService.GreeterServiceClient(channel);
                request = new HelloRequest
                {
                    Message = "Hi From Client"
                };
                response = client.SayHello(request);
                Console.WriteLine(response.Message);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.ToString());
                // client.SayHello(request);
                // Console.WriteLine(response.Message);
            }

        }
    }
}

```

 
### What did you expect to see?
After I run the server inside the docker container and then run my client on localhost, I expected it to run and see the output : **Hello from Server** 
 
### What did you see instead?
Exception Log:

Hello World!
```
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 75
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 51
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 48
   at Greeter.Proto.GreeterService.GreeterServiceClient.SayHello(HelloRequest request, CallOptions options) in F:\c#\GrpcPracticeWithDocker\GreeterClient\GrpcClasses\GreeterGrpc.cs:line 70
   at Greeter.Proto.GreeterService.GreeterServiceClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in F:\c#\GrpcPracticeWithDocker\GreeterClient\GrpcClasses\GreeterGrpc.cs:line 66
   at GreeterClient.Program.Main(String[] args) in F:\c#\GrpcPracticeWithDocker\GreeterClient\Program.cs:line 25
```

 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jtattermusch** [comment]
I'm going to close this and will reopen if we establish that gRPC is actually the culprit (and not just docker configuration).

**Comment by spirasean** [comment]
I found that this code only works if I use an interactive session and keep the stdin open, so for docker run you need to add the -it, eg. docker run --rm -p 5000:5000 -it -d greeter-service:1.0, in docker-compose you would add tty: true and std_open: true. To test if this is the case add a Console.WriteLine("Grpc Server stopped"); after shutdown.WaitOne(); If it stops then that means the server is stopped. By adding the stdin and interactive session variables this does not occur.
