### ISSUE TITLE
node compile issue due to ClientHttp2StreamMock 

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#16692]
https://source.cloud.google.com/results/invocations/38d0fdf3-0f01-437f-9094-2acd8d425873/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

Please decrease priority if appropriate. 

```
> grpc@1.15.0-dev install /var/local/git/grpc-node/packages/grpc-native-core
> node-pre-gyp install --fallback-to-build --library=static_library
npm notice created a lockfile as package-lock.json. You should commit this file.
added 103 packages in 6.407s
[20:32:36] Finished 'health-check.install' after 7 s
node-pre-gyp WARN Using request for node-pre-gyp https download
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/var/local/git/grpc-node/packages/grpc-native-core/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
npm notice created a lockfile as package-lock.json. You should commit this file.
added 192 packages in 9.358s
[20:32:39] Finished 'protobuf.install' after 9.97 s
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
test/test-call-stream.ts:30:7 - error TS2420: Class 'ClientHttp2StreamMock' incorrectly implements interface 'ClientHttp2Stream'.
  Property 'endAfterHeaders' is missing in type 'ClientHttp2StreamMock'.
30 class ClientHttp2StreamMock extends stream.Duplex implements
         ~~~~~~~~~~~~~~~~~~~~~
test/test-call-stream.ts:107:37 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
  Property 'endAfterHeaders' is missing in type 'ClientHttp2StreamMock'.
107        callStream.attachHttp2Stream(http2Stream);
                                        ~~~~~~~~~~~
test/test-call-stream.ts:141:40 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
141           callStream.attachHttp2Stream(http2Stream);
                                           ~~~~~~~~~~~
test/test-call-stream.ts:183:36 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
183       callStream.attachHttp2Stream(http2Stream);
                                       ~~~~~~~~~~~
test/test-call-stream.ts:213:41 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
213            callStream.attachHttp2Stream(http2Stream);
                                            ~~~~~~~~~~~
test/test-call-stream.ts:247:38 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
247         callStream.attachHttp2Stream(http2Stream);
                                         ~~~~~~~~~~~
test/test-call-stream.ts:270:36 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
270       callStream.attachHttp2Stream(http2Stream);
                                       ~~~~~~~~~~~
test/test-call-stream.ts:286:39 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
286          callStream.attachHttp2Stream(http2Stream);
                                          ~~~~~~~~~~~
test/test-call-stream.ts:301:36 - error TS2345: Argument of type 'ClientHttp2StreamMock' is not assignable to parameter of type 'ClientHttp2Stream'.
301       callStream.attachHttp2Stream(http2Stream);
                                       ~~~~~~~~~~~
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grpc/grpc-js@0.3.0 compile: `tsc -p .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @grpc/grpc-js@0.3.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2018-09-24T20_32_39_461Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grpc/grpc-js@0.3.0 prepare: `npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @grpc/grpc-js@0.3.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2018-09-24T20_32_39_702Z-debug.log
[20:32:40] 'js.core.install' errored after 11 s
[20:32:40] Error: Command failed: npm install --unsafe-perm
    at Promise.all.then.arr (/var/local/git/grpc-node/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[20:32:40] 'setup' errored after 11 s
[20:32:40] Error in plugin "run-sequence(js.core.install)"
Message:
    Command failed: npm install --unsafe-perm
Details:
    code: 1
    killed: false
    stdout: null
    stderr: null
    failed: true
    signal: null
    cmd: npm install --unsafe-perm
    timedOut: false
```

**Comment by murgatroid99** [comment]
`ClientHttp2Stream` is part of the Node HTTP/2 module. It looks like they added a method, and that broke our mock class. That is impacting us here because we are building our test code as part of our normal build process.

**Comment by murgatroid99** [comment]
OK, I don't know what's happening here. I can't figure out how to reproduce this failure on my local machine.

**Comment by AspirinSJL** [comment]
Stale.
