### ISSUE TITLE
Bazel build crashes because python workspace is broken

### ISSUE THREAD

**Issue by ikishchenko** [grpc/grpc#16771]
### What version of gRPC and what language are you using?
Language: `C++`
 Bug found in `master` and in `1.15.x` branches.
 Last working version (without bug): `1.14.x` branch.
 
### What operating system (Linux, Windows, …) and version?
 Windows 7 Professional SP1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Bazel: 0.16.1
 Python: 2.7.13
 
### What did you do?
* Clone 1.15.x branch from grpc repo
* Execute command `bazel build grpc++` from grpc root directory.
 
### What did you expect to see?
 Successfully compiled `grpc++.lib`
 
### What did you see instead?
```
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@grpc_python_dependencies//': pip_import failed: Collecting coverage>=4.0 (from -r S:/temp/grpc_winexp/grpc/requi
  Using cached https://files.pythonhosted.org/packages/a6/2c/39d7da4ea22cf32fd43a72732a4009891d17f237a0ac24bb99ed88e3a86b/coverage-4.5.1-cp27-cp27m-win_amd64.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\coverage-4.5.1-cp27-cp27m-win_amd64.whl
Collecting cython==0.28.3 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/db/02/473a6bf31e6560d8313818d61007baa721b0827970b87385ef271b403a57/Cython-0.28.3-cp27-cp27m-win_amd64.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\cython-0.28.3-cp27-cp27m-win_amd64.whl
Collecting enum34>=1.0.4 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\enum34-1.1.6-py2-none-any.whl
Collecting protobuf>=3.5.0.post1 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/77/78/a7f1ce761e2c738e209857175cd4f90a8562d1bde32868a8cd5290d58926/protobuf-3.6.1-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\protobuf-3.6.1-py2.py3-none-any.whl
Collecting six>=1.10 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\six-1.11.0-py2.py3-none-any.whl
Collecting wheel>=0.29 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/b3/bb/42354ce8c08f66ae0cd0f4a841f40ed41d709ac9c28f292bfeb383236a4a/wheel-0.32.0-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\wheel-0.32.0-py2.py3-none-any.whl
Collecting futures>=2.2.0 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\futures-3.2.0-py2-none-any.whl
Collecting google-auth>=1.0.0 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/58/cb/96dbb4e50e7a9d856e89cc9c8e36ab1055f9774f7d85f37e2156c1d79d9f/google_auth-1.5.1-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\google_auth-1.5.1-py2.py3-none-any.whl
Collecting oauth2client==4.1.0 (from -r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2a/8f/8ad3507de44331c16af8328bd4c38992121226e2ad5947c41eb682ebbdb6/oauth2client-4.1.0-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\oauth2client-4.1.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.5.0.post1->-r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\setuptools-40.4.3-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.0.0->-r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.0.0->-r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\rsa-4.0-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.0.0->-r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
  Saved c:\users\kishchenko\_bazel_kishchenko\3em7ib5l\external\grpc_python_dependencies\cachetools-2.1.0-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client==4.1.0->-r S:/temp/grpc_winexp/grpc/requirements.bazel.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/fd/ce/aa4a385e3e9fd351737fd2b07edaa56e7a730448465aceda6b35086a0d9b/httplib2-0.11.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\kishch~1\appdata\local\temp\pip-build-2wycfe\httplib2\setup.py", line 77, in <module>
        'Topic :: Software Development :: Libraries',
      File "C:\Program Files\Python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Program Files\Python27\lib\site-packages\setuptools\dist.py", line 316, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "C:\Program Files\Python27\lib\site-packages\pkg_resources\__init__.py", line 730, in iter_entry_points
        entries = dist.get_entry_map(group)
      File "C:\Program Files\Python27\lib\site-packages\pkg_resources\__init__.py", line 2639, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "C:\Program Files\Python27\lib\site-packages\pkg_resources\__init__.py", line 2373, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
``` 

### Additional information
I fix compilation when remove this lines from WORKSPACE file:
```
load("@grpc_python_dependencies//:requirements.bzl", "pip_install")
pip_install()
```

**Comment by mehrdada** [comment]
@ghostwriternr can you take a look?

**Comment by ikishchenko** [comment]
@mehrdada, @ghostwriternr any progress?

**Comment by ghostwriternr** [comment]
Hey @ikishchenko,

This issue doesn't seem to be Bazel or gRPC related. I couldn't reproduce this issue myself, but searching around for this error hints that this might be showing up due to a misformatted/corrupt Python egg that might be existing on your machine. Did you have any luck trying to uninstall and reinstall 'httplib2' (which seems to be the source of the error here)? [There is a SO thread](https://stackoverflow.com/questions/17985110/errors-while-installing-python-packages) with some steps to debug a very similar issue. Can you please report back with results?

Although on a different note, it is indeed bad for our build to fail because of such discrepancies in a user's Python install. The Python rules for Bazel are still a huge WIP and are seemingly not yet fully sandboxed (since Bazel sees and uses Python packages installed in the current environment). There are [some ongoing discussions](https://docs.google.com/document/d/1A6J3j3y1SQ0HliS86_mZBnB5UeBe7vExWL2Ryd_EONI/edit#heading=h.onyijsxsw1p2) to achieve this, but a perfect solution might still be very far away.

**Comment by ikishchenko** [comment]
Hey @ghostwriternr,

I try to compile grpc on another computer and it works.
Sorry, this issue relevant only for my machine.
