### ISSUE TITLE
flaky test: iOS Binary Size Diff

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16796]
https://source.cloud.google.com/results/invocations/215ee82f-9f69-4ee2-a135-9f04413e2481/log

Error: `fatal: unable to access 'https://github.com/google/boringssl.git/': Could not resolve host: github.com`

```
[!] Error installing BoringSSL-GRPC
[!] /usr/local/bin/git clone https://github.com/google/boringssl.git /tmpfs/tmp/d20181005-9451-1wu5iqw --template=
Cloning into '/tmpfs/tmp/d20181005-9451-1wu5iqw'...
fatal: unable to access 'https://github.com/google/boringssl.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "tools/profiling/ios_bin/binary_size.py", line 93, in <module>
    build('new', frameworks)
  File "tools/profiling/ios_bin/binary_size.py", line 86, in build
    cwd='src/objective-c/tests')
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'CONFIG=opt EXAMPLE_PATH=src/objective-c/examples/Sample SCHEME=Sample FRAMEWORKS=NO ./build_one_example.sh' returned non-zero exit status 1
[ID: 6291591] Build finished after 1577 secs, exit value: 1
```

**Comment by muxi** [comment]
Seems like name resolution is not working properly in Kokoro
