### ISSUE TITLE
many cloud to prod interop tests failing on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16818]
Failing in 100% of cases, first failing build is:
https://source.cloud.google.com/results/invocations/2e1317a7-74b2-4362-a8f2-5b6a2ecb16e2/targets/github%2Fgrpc/tests

Log snippets from failures:
```
Running test case compute_engine_creds
Payload had the wrong type
```

```
running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 107, in <module>
    test_runner=TEST_RUNNER,
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 188, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 204, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 127, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 514, in test_interoperability
    _per_rpc_creds(stub, args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 454, in _per_rpc_creds
    response = _large_unary_common_behavior(stub, True, False, call_credentials)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 140, in _large_unary_common_behavior
    _validate_payload_type_and_length(response, messages_pb2.COMPRESSABLE, size)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 122, in _validate_payload_type_and_length
    (expected_type, type(response.payload.type)))
ValueError: expected payload type 0, got <type 'int'>
```

```
- undefined
+ 'COMPRESSABLE'
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:12)
    at ClientReadableStreamImpl.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:217:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js-core/build/src/call.js:36:21)
    at Http2CallStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at Http2CallStream.Readable.push (_stream_readable.js:217:10)
(node:195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:195) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- undefined
+ 'COMPRESSABLE'
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:12)
    at ClientReadableStreamImpl.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:217:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js-core/build/src/call.js:36:21)
    at Http2CallStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at Http2CallStream.Readable.push (_stream_readable.js:217:10)
(node:195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:195) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- undefined
+ 'COMPRESSABLE'
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:12)
    at ClientReadableStreamImpl.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:217:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js-core/build/src/call.js:36:21)
    at Http2CallStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at Http2CallStream.Readable.push (_stream_readable.js:217:10)
(node:195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
assert.js:77
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- 0
+ 4
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:167:12)
    at ClientReadableStreamImpl.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by jtattermusch** [comment]
CC @nicolasnoble  @billfeng327 

looks like grpc_interop_matrix is failing too, likely due to the same problem
https://source.cloud.google.com/results/invocations/14084483-8e23-49d9-8e80-86a7c13a0012/targets/github%2Fgrpc/tests

**Comment by jtattermusch** [comment]
@yang-g , can you take a look? Perhaps something wrong with the prod backend?

**Comment by jtattermusch** [comment]
CC @srini100

**Comment by yang-g** [comment]
The backends seem fine. Note a lot of tests actually pass talking to the same backends.

Some of the failing tests complain about a payload type, maybe it is something out of sync.

**Comment by yang-g** [comment]
Nothing is obvious when checking the code on both sides.

**Comment by muxi** [comment]
I investigated a bit into the ObjC interop failure (#16817) and the reason for that was the [response payload](https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/messages.proto#L39) is corrupted. It is getting bytes `0a0e0801 120a0000 00000000 00000000`, which caused proto parsing to fail. I wonder if there is a recent change in the proto being used by the interop test server that caused this problem?

**Comment by yang-g** [comment]
So muxi and I found out someone accidentally pushed a custom built backend server with uncompatible proto, which likely caused the problem here.

He is trying to do a clean up and I think latest around 9pm today the change should be propagated and the test should start passing again.

**Comment by yang-g** [comment]
The backend seems to be killed as usual but not restarted somehow.

**Comment by yang-g** [comment]
Re-assigning to @billfeng327 as I am no longer in the group of controling the backend.

**Comment by jtattermusch** [comment]
grpc_interop_tocloud and grpc_interop_toprod test seem fixed.
