### ISSUE TITLE
Fix Python3.6/3.7 Docker Environment Testing Initialization Failure

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#16900]
Related Issues: #13978 #16870
Related PR: #16893

If the testing environment have both Python2 and Python 3.6/3.7, then the `run_tests.py` can go through without problems. Since @mehrdada mentioned in this [comment](https://github.com/grpc/grpc/pull/16893#issuecomment-430081837), I start to look into the Docker Environment Testing. After hours of investigating, I found things is not that straightforward.

Firstly, I encountered a noob problem that not downloading all the submodules and breaks the Cython build in Docker. Then, I found the `pyenv` initialization has problem and not working properly for Python3.6/3.7, and I fix it. But it still not working in Docker.

Here is the error log, basically it complains about an undefined symbol `OPENSSL_sk_pop_free`. The error log for 3.6 is exactly the same, except replace "37", "3.7" with "36", "3.6".

```
FAILED: py37_native.test.unit._cython.cygrpc_test.InsecureServerInsecureClient [ret=1, pid=1980, time=0.4sec]

++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py37_native/bin/python
+ PYTHON=/var/local/git/grpc/py37_native/bin/python3.7
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py37_native/bin/python3.7 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Traceback (most recent call last):
  File "/var/local/git/grpc/src/python/grpcio_tests/setup.py", line 107, in <module>
    test_runner=TEST_RUNNER,
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 99, in run
    loader.loadTestsFromNames(['tests'])
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/_loader.py", line 60, in loadTestsFromNames
    self.walk_packages(package_paths)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/_loader.py", line 74, in walk_packages
    module = importer.find_module(module_name).load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/fork/client.py", line 20, in <module>
    from tests.fork import methods
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/fork/methods.py", line 24, in <module>
    import grpc
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so: undefined symbol: OPENSSL_sk_pop_free
```

In order to fix it, it may require digging into the `.so` artifact and building dependency of `cygrpc`. And it can be potentially a problem for distributing `gRPC-Python` for higher version Python.

FYI, success testing log for Python3.7 without Docker.

```
root@ddev:/usr/local/google/home/lidiz/src/grpc# tools/run_tests/run_tests.py --language=python --compiler=python3.7
PASSED: /usr/local/google/home/lidiz/src/grpc/tools/run_tests/helper_scripts/build_python.sh [time=672.8sec, retries=0:0]

Omitting EPOLLEXCLUSIVE tests


2018-10-16 13:26:37,091 detected port server running version 20
2018-10-16 13:26:37,122 my port server is version 20
WAITING: 54 queued, 12 jobs running, 0 complete, 0 failed (load 12.00) next: py37_native.test.protoc_plugin._split_definitions_test.SameProtoGrpcBeforeProtoProtocStyleTest @ 1.00 cpWAITING: ETA 10.8 sec; 43 queued, 12 jobs running, 11 complete, 0 failed (load 12.00) next: py37_native.test.protoc_plugin._split_definitions_test.SplitProtoProtoBeforeGrpcProtocStyWAITING: ETA 7.7 sec; 33 queued, 12 jobs running, 21 complete, 0 failed (load 12.00) next: py37_native.test.protoc_plugin._split_definitions_test.SplitProtoMid2016ProtocStyleTest @ WAITING: ETA 6.2 sec; 23 queued, 12 jobs running, 31 complete, 0 failed (load 12.00) next: py37_native.test.unit._server_ssl_cert_config_test.ServerSSLCertReloadTestWithClientAuth @WAITING: ETA 5.9 sec; 22 queued, 12 jobs running, 32 complete, 0 failed (load 12.00) next: py37_native.test.unit._cython._no_messages_single_server_completion_queue_test.Test @ 1.00WAITING: ETA 5.5 sec; 20 queued, 12 jobs running, 34 complete, 0 failed (load 12.00) next: py37_native.test.unit._server_ssl_cert_config_test.ServerSSLCertReloadTestCertConfigReuse WAITING: ETA 4.6 sec; 13 queued, 12 jobs running, 41 complete, 0 failed (load 12.00) next: py37_native.test.protoc_plugin._split_definitions_test.SameProtoMid2016ProtocStyleTest @ 1WAITING: ETA 4.4 sec; 11 queued, 12 jobs running, 43 complete, 0 failed (load 12.00) next: py37_native.test.protoc_plugin._split_definitions_test.SplitProtoSingleProtocExecutionProtWAITING: ETA 3.8 sec; 7 queued, 12 jobs running, 47 complete, 0 failed (load 12.00) next: py37_native.test.unit._server_ssl_cert_config_test.ServerSSLCertConfigFetcherParamsChecks @WAITING: ETA 3.3 sec; 4 queued, 12 jobs running, 50 complete, 0 failed (load 12.00) next: py37_native.test.unit._server_ssl_cert_config_test.ServerSSLCertReloadTestWithoutClientAuth
SUCCESS: All tests passed
```

**Comment by lidizheng** [comment]
Currently, I found that if the `cygrpc` is built inside of the Docker volumn (specified by -v) then it runs fine, but if the artifact is built upon the Docker filesystem  it will through the "undefined symbol" error.

So, I tried to dig into the two binaries to see what is different between them
```shell
# The running fine one
/var/local/jenkins/grpc/py37_native/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
# The error-throwing one
/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
```

I checked their linkage to system lib are identical (using `ldd`).
But their symbol usage is different at the beginning.
```shell
$ export FILE1=/var/local/jenkins/grpc/py37_native/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
$ export FILE2=/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
$ diff <(nm -gC $FILE1) <(nm -gC FILE2)
0a1,6
>                  U CRYPTO_free
>                  U OPENSSL_sk_new_null
>                  U OPENSSL_sk_num
>                  U OPENSSL_sk_pop_free
>                  U OPENSSL_sk_push
>                  U OPENSSL_sk_value
```

Well, after I dig into one level lower using `objdump` to compare the disassembles, I can't really decipher the difference (almost every line are different due to shift of addresses)...

But I did find a workaround, please refer to in the following PR.

**Comment by lidizheng** [comment]
Left clues
* Due to `pyenv` install logic, Python was built every time, so possibly the old version OpenSSL getting in at this time.
* Continue to inspect the difference between two Docker file systems
* Try to overriding the OpenSSL reference
