### ISSUE TITLE
Error pulling docker image  while testing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16922]
Probably an occasional flake.

```
Error response from daemon: Get https://registry-1.docker.io/v2/: EOF
```

https://source.cloud.google.com/results/invocations/bd8d9363-63fc-44d3-bef0-d25c07debdee/targets/github%2Fgrpc%2Faggregate_tests/tests

**Comment by jtattermusch** [comment]
similar problem seen here: https://source.cloud.google.com/results/invocations/3844fa65-b243-4926-b181-07c1c9a8324c/log
```
Error response from daemon: Get https://registry-1.docker.io/v2/grpctesting/php_jessie_x64_22e4c68f9941b88938618e4bb61680045a3ff35c/manifests/latest: received unexpected HTTP status: 503 Service Unavailable
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1540, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 1
```

**Comment by jtattermusch** [comment]
Transient issue
