### ISSUE TITLE
Python Failure on Travis:  socket error: connection refused

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1708]
```
D0521 20:08:28.988947053    9025 iomgr.c:114] Waiting for 5 iomgr objects to be destroyed and executing final callbacks
D0521 20:08:29.089330080    9025 iomgr.c:114] Waiting for 4 iomgr objects to be destroyed and executing final callbacks
D0521 20:08:38.992397085    9025 iomgr.c:137] Failed to free 2 iomgr objects before shutdown deadline: memory leaks are likely
[0;31mFAILED[0m: grpc._adapter._blocking_invocation_inline_service_test [ret=1, pid=8984]
[0G[2K
++dirname tools/run_tests/run_python.sh
+cd tools/run_tests/../..
++pwd
+root=/home/travis/build/grpc/grpc
+export LD_LIBRARY_PATH=/home/travis/build/grpc/grpc/libs/opt
+LD_LIBRARY_PATH=/home/travis/build/grpc/grpc/libs/opt
+source python2.7_virtual_environment/bin/activate
++deactivate nondestructive
++'[' -n '' ']'
++'[' -n '' ']'
++'[' -n /bin/bash -o -n '' ']'
++hash -r
++'[' -n '' ']'
++unset VIRTUAL_ENV
++'[' '!' nondestructive = nondestructive ']'
++VIRTUAL_ENV=/home/travis/build/grpc/grpc/python2.7_virtual_environment
++export VIRTUAL_ENV
++_OLD_VIRTUAL_PATH=/home/travis/.rvm/gems/ruby-2.1.5/bin:/home/travis/.rvm/gems/ruby-2.1.5@global/bin:/home/travis/.rvm/rubies/ruby-2.1.5/bin:/home/travis/.rvm/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++PATH=/home/travis/build/grpc/grpc/python2.7_virtual_environment/bin:/home/travis/.rvm/gems/ruby-2.1.5/bin:/home/travis/.rvm/gems/ruby-2.1.5@global/bin:/home/travis/.rvm/rubies/ruby-2.1.5/bin:/home/travis/.rvm/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++export PATH
++'[' -n '' ']'
++'[' -z '' ']'
++_OLD_VIRTUAL_PS1=
++'[' x '!=' x ']'
+++basename /home/travis/build/grpc/grpc/python2.7_virtual_environment
++'[' python2.7_virtual_environment = __ ']'
+++basename /home/travis/build/grpc/grpc/python2.7_virtual_environment
++PS1='(python2.7_virtual_environment)'
++export PS1
++'[' -n /bin/bash -o -n '' ']'
++hash -r
+python2.7 -B -m grpc._adapter._event_invocation_synchronous_event_service_test
....E0521 20:08:09.482323706    9195 tcp_client_posix.c:149] socket error: 104
E0521 20:08:09.581508312    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:10.679201692    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:10.781519270    9195 tcp_client_posix.c:146] socket error: connection refused
.ERROR:root:Exception during ingestion!
Traceback (most recent call last):
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/foundation/callable_util.py", line 69, in _call_logging_exceptions
    return _EasyOutcome(Outcome.Kind.RETURNED, behavior(*args, **kwargs), None)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/base/_ingestion.py", line 194, in moar
    self._consumer.terminate()
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/face/testing/stock_service.py", line 110, in terminate
    raise ValueError()
ValueError
.E0521 20:08:17.231136300    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:17.278691226    9195 tcp_client_posix.c:146] socket error: connection refused
..ssssFE0521 20:08:26.255655504    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:26.255897492    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:26.255967477    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:26.256186379    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:26.256267345    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:26.256295150    9195 tcp_client_posix.c:146] socket error: connection refused
.E0521 20:08:27.279123952    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:27.279290592    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:27.378698011    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:27.378777479    9195 tcp_client_posix.c:146] socket error: connection refused
...E0521 20:08:29.478972235    9195 tcp_client_posix.c:146] socket error: connection refused
E0521 20:08:29.479135848    9195 tcp_client_posix.c:146] socket error: connection refused
.s
======================================================================
FAIL: testParallelInvocations (__main__.EventInvocationSynchronousEventServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/face/testing/event_invocation_synchronous_event_service_test_case.py", line 297, in testParallelInvocations
    first_response = first_callback.response()
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/face/testing/callback.py", line 83, in response
    raise AssertionError('Aborted with abortion "%s"!' % self._abortion)
AssertionError: Aborted with abortion "Abortion.EXPIRED"!

----------------------------------------------------------------------
Ran 19 tests in 20.565s

FAILED (failures=1, skipped=5)
```

**Comment by nathanielmanistaatgoogle** [comment]
What could be the reason for those "socket error: connection refused" messages? Other than obvious Python-level possibilities like bringing up a stub before its corresponding server or issues like that?

**Comment by ctiller** [comment]
That's probably the issue. I think the socket errors here are red herrings.
If the stub is around before the server, then we'll keep trying to connect
until it's possible.

The only other thing that might cause this (that I can think of now - I
reserve the right to add reasons later) is if we failed to bind the server
port - but I'd assume there's some wrapping to throw an exception in that
case?

**Comment by nathanielmanistaatgoogle** [comment]
@dgquintas: to answer @ctiller's question: I'm not sure that we have appropriate safety surrounding failure to bind the server port. That might be where to start looking?

If the server port is failing to bind, reporting that more clearly wouldn't fix a failing test but would at least move us closer to the defect's ultimate cause.

**Comment by dgquintas** [comment]
@nathanielmanistaatgoogle: sounds like a good idea. I'm looking around the python code to get my bearings. Of course, I haven't been able to repro on my machine, even with -t -n 25. Bringing it up too -n 100.

**Comment by dgquintas** [comment]
Can't reproduce. Has anyone seen this one again lately?
