### ISSUE TITLE
Ruby test failure: ClientStub #server_streamer via a call operation behaves like server streaming should send a request to/receive replies from a server

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#17174]
https://source.cloud.google.com/results/invocations/5d19f0eb-680d-4ce4-8d7e-551013486c8b/targets/github%2Fgrpc%2Fruby_macos_opt_native/log

```
Failures:
  1) ClientStub #server_streamer via a call operation behaves like server streaming should send a request to/receive replies from a server
     Got 0 failures and 2 other errors:
     Shared Example Group: "server streaming" called from ./src/ruby/spec/generic/client_stub_spec.rb:563
     1.1) Failure/Error: expect(get_responses(stub).collect { |r| r }).to eq(@replys)
          GRPC::Unavailable:
            14:Received RST_STREAM with error code 7
          # ./src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
          # ./src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
          # ./src/ruby/lib/grpc/generic/active_call.rb:170:in `receive_and_check_status'
          # ./src/ruby/lib/grpc/generic/active_call.rb:338:in `each_remote_read_then_finish'
          # ./src/ruby/spec/generic/client_stub_spec.rb:465:in `each'
          # ./src/ruby/spec/generic/client_stub_spec.rb:465:in `collect'
          # ./src/ruby/spec/generic/client_stub_spec.rb:465:in `block (4 levels) in <top (required)>'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'
     1.2) Failure/Error: recvd_rpc = @server.request_call
          GRPC::Core::CallError:
            request_call completion failed
          # ./src/ruby/spec/generic/client_stub_spec.rb:1076:in `request_call'
          # ./src/ruby/spec/generic/client_stub_spec.rb:1076:in `expect_server_to_be_invoked'
          # ./src/ruby/spec/generic/client_stub_spec.rb:971:in `block in run_server_streamer'
          # ./src/ruby/spec/generic/client_stub_spec.rb:22:in `block in wakey_thread'
          # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

```

**Comment by AspirinSJL** [comment]
Stale.
