### ISSUE TITLE
python bazel test //src/python/grpcio_tests/tests/interop:_secure_intraop_test  broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17170]
Started with this build, failing in 100% run since then
https://source.cloud.google.com/results/invocations/6ca8e8f5-9dd6-4ced-830e-a9b2a6f7adbb/log

```
//src/python/grpcio_tests/tests/interop:_insecure_intraop_test           FAILED in 0.5s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests/interop/_insecure_intraop_test/test.log
//src/python/grpcio_tests/tests/interop:_secure_intraop_test             FAILED in 0.5s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests/interop/_secure_intraop_test/test.log
```

**Comment by jtattermusch** [comment]
The full error listing obtained thanks to #17171 
```
FAIL: //src/python/grpcio_tests/tests/interop:_insecure_intraop_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests/interop/_insecure_intraop_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests/interop:_insecure_intraop_test:
==================== Test output for //src/python/grpcio_tests/tests/interop:_insecure_intraop_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.py", line 21, in <module>
    from tests.interop import _intraop_test_case
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/_intraop_test_case.py", line 16, in <module>
    from tests.interop import methods
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/methods.py", line 24, in <module>
    from google.auth.transport import requests as google_auth_transport_requests
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.runfiles/pypi__google_auth_1_5_1/google/auth/transport/requests.py", line 31, in <module>
    caught_exc,
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.runfiles/pypi__six_1_11_0/six.py", line 737, in raise_from
    raise value
ImportError: The requests library is not installed, please install the requests package to use the requests transport.
================================================================================
FAIL: //src/python/grpcio_tests/tests/interop:_secure_intraop_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests/interop/_secure_intraop_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests/interop:_secure_intraop_test:
==================== Test output for //src/python/grpcio_tests/tests/interop:_secure_intraop_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_secure_intraop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/_secure_intraop_test.py", line 21, in <module>
    from tests.interop import _intraop_test_case
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_secure_intraop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/_intraop_test_case.py", line 16, in <module>
    from tests.interop import methods
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_secure_intraop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/methods.py", line 24, in <module>
    from google.auth.transport import requests as google_auth_transport_requests
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_secure_intraop_test.runfiles/pypi__google_auth_1_5_1/google/auth/transport/requests.py", line 31, in <module>
    caught_exc,
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/interop/_secure_intraop_test.runfiles/pypi__six_1_11_0/six.py", line 737, in raise_from
    raise value
ImportError: The requests library is not installed, please install the requests package to use the requests transport.
================================================================================
[1,045 / 1,048] 34 / 37 tests, 2 failed; Testing //src/python/grpcio_tests/tests/unit:_rpc_test; 12s local ... (3 actions running)
[1,046 / 1,048] 35 / 37 tests, 2 failed; Testing //src/python/grpcio_tests/tests/unit:_rpc_test; 24s local ... (2 actions running)
[1,047 / 1,048] 36 / 37 tests, 2 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test; 38s local
INFO: Elapsed time: 101.705s, Critical Path: 49.70s
INFO: 924 processes: 924 local.
INFO: Build completed, 2 tests FAILED, 1048 total actions
```
