### ISSUE TITLE
Node flake in interop test

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1720]
-- deleted bad log

**Comment by murgatroid99** [comment]
That's obviously not the whole trace, but from what you have there, it's not even clear that there was a failure.

**Comment by ctiller** [comment]
Copy-paste problems on my behalf, sorry. Will update momentarily.

**Comment by ctiller** [comment]
Final output:
```
  1 failing
  1) Interop tests should pass server_streaming:
     Uncaught AssertionError: 3 === 4
      at ClientReadableStream.<anonymous> (/home/travis/build/grpc/grpc/src/node/interop/interop_client.js:159:12)
      at ClientReadableStream.emit (events.js:95:17)
      at /home/travis/build/grpc/grpc/src/node/src/client.js:386:16
```

Full log here:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/63581683/log.txt

My suspicion is that call.c is discarding the final message errantly.

Is there a way to run just the server_streaming interop test?

**Comment by murgatroid99** [comment]
The simplest way would be to edit `test/interop_sanity_test.js` and, in the line with that description (`"should pass server_streaming"`), replace `it` with `it.only`

**Comment by murgatroid99** [comment]
Alternately, if you don't want to edit anything, (from `src/node`) `./node_modules/mocha/bin/mocha --grep server_streaming`

**Comment by ctiller** [comment]
Complete log of a failure:
```
+ CONFIG=opt
++ dirname tools/run_tests/run_node.sh
+ cd tools/run_tests/../..
++ pwd
+ root=/usr/local/google/home/ctiller/grpc
+ export LD_LIBRARY_PATH=/usr/local/google/home/ctiller/grpc/libs/opt
+ LD_LIBRARY_PATH=/usr/local/google/home/ctiller/grpc/libs/opt
+ /usr/local/google/home/ctiller/grpc/src/node/node_modules/mocha/bin/mocha --timeout 8000 /usr/local/google/home/ctiller/grpc/src/node/test --grep server_streaming


  Interop tests
Server starting
Serving /grpc.testing.TestService/EmptyCall
Serving /grpc.testing.TestService/UnaryCall
Serving /grpc.testing.TestService/StreamingOutputCall
Serving /grpc.testing.TestService/StreamingInputCall
Serving /grpc.testing.TestService/FullDuplexCall
Serving /grpc.testing.TestService/HalfDuplexCall
I0522 09:09:44.986836458   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x2053c50, nops=4, tag=0x2053f30)
I0522 09:09:44.986926648   16441 call.c:1199] ops[0]: SEND_INITIAL_METADATA
I0522 09:09:44.986937975   16441 call.c:1199] ops[1]: SEND_MESSAGE ptr=0x2053d60
I0522 09:09:44.986944634   16441 call.c:1199] ops[2]: SEND_CLOSE_FROM_CLIENT
I0522 09:09:44.986951153   16441 call.c:1199] ops[3]: RECV_INITIAL_METADATA ptr=0x2053f08
I0522 09:09:44.987040553   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x2053c50, nops=1, tag=0x2054180)
I0522 09:09:44.987053396   16441 call.c:1199] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x2053ca8 status=0x2053cc0 details=0x2053cc8
I0522 09:09:44.987711858   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x2053c50, nops=1, tag=0x20540b0)
I0522 09:09:44.987729726   16441 call.c:1199] ops[0]: RECV_MESSAGE ptr=0x2053fb8
I0522 09:09:45.784953053   17075 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x204fcb0 OK
I0522 09:09:45.785643755   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x20573f0, nops=1, tag=0x2059300)
I0522 09:09:45.785660732   16441 call.c:1199] ops[0]: RECV_CLOSE_ON_SERVER cancelled=0x20592a8
I0522 09:09:45.785681268   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x20594e0, nops=2, tag=0x20573f0)
I0522 09:09:45.785688496   16441 call.c:1199] ops[0]: SEND_INITIAL_METADATA
I0522 09:09:45.785693462   16441 call.c:1199] ops[1]: RECV_MESSAGE ptr=0x20595c8
I0522 09:09:45.785731777   17075 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x20573f0 OK
I0522 09:09:45.785774251   17074 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2053f30 OK
I0522 09:09:45.787698190   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x204fcb0, nops=1, tag=0x2059980)
I0522 09:09:45.787720972   16441 call.c:1199] ops[0]: SEND_MESSAGE ptr=0x2059810
I0522 09:09:45.787756738   17074 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2059980 OK
I0522 09:09:45.788648408   17074 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x20540b0 OK
I0522 09:09:45.788777430   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x204fcb0, nops=1, tag=0x20593e0)
I0522 09:09:45.788790514   16441 call.c:1199] ops[0]: SEND_MESSAGE ptr=0x2053e50
I0522 09:09:45.788842434   17075 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x20593e0 OK
I0522 09:09:45.789545604   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x204fcb0, nops=1, tag=0x2059770)
I0522 09:09:45.789558787   16441 call.c:1199] ops[0]: RECV_MESSAGE ptr=0x20595a8
I0522 09:09:45.789592130   17073 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2059770 OK
I0522 09:09:45.789782950   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x204fcb0, nops=1, tag=0x20597a0)
I0522 09:09:45.789795153   16441 call.c:1199] ops[0]: SEND_MESSAGE ptr=0x2054b70
I0522 09:09:45.789843926   17075 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x20597a0 OK
I0522 09:09:45.790066266   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x20573f0, nops=1, tag=0x2059480)
I0522 09:09:45.790078186   16441 call.c:1199] ops[0]: RECV_MESSAGE ptr=0x2053f48
I0522 09:09:45.790107984   17075 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2059480 OK
I0522 09:09:45.790283761   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x2059770, nops=1, tag=0x2059370)
I0522 09:09:45.790300585   16441 call.c:1199] ops[0]: SEND_MESSAGE ptr=0x2059bc0
I0522 09:09:45.790326006   17074 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2059370 OK
I0522 09:09:45.791176705   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x20594b0, nops=1, tag=0x20540b0)
I0522 09:09:45.791190700   16441 call.c:1199] ops[0]: RECV_MESSAGE ptr=0x2054128
I0522 09:09:45.791302415   16441 call.c:1199] grpc_call_start_batch(call=0x7ff53c000930, ops=0x204fcb0, nops=1, tag=0x2059980)
I0522 09:09:45.791313447   16441 call.c:1199] ops[0]: SEND_STATUS_FROM_SERVER status=0 details=OK
I0522 09:09:45.791348059   17074 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2059980 OK
I0522 09:09:45.791374491   17072 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2059300 OK
I0522 09:09:45.791953174   17074 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x2054180 OK
I0522 09:09:45.791954262   17075 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x20540b0 OK
    1) should pass server_streaming
I0522 09:09:45.793317403   16441 call.c:1199] grpc_call_start_batch(call=0x20582c0, ops=0x2059370, nops=1, tag=0x204fcb0)
I0522 09:09:45.793334955   16441 call.c:1199] ops[0]: RECV_MESSAGE ptr=0x204f7b8
I0522 09:09:45.793385046   17073 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x204fcb0 OK
I0522 09:09:45.793895668   17072 completion_queue.c:223] RETURN_EVENT[0x1eb4470]: OP_COMPLETE: tag:0x1f11910 ERROR


  0 passing (919ms)
  1 failing

  1) Interop tests should pass server_streaming:
     Uncaught AssertionError: 3 === 4
      at ClientReadableStream.<anonymous> (/usr/local/google/home/ctiller/grpc/src/node/interop/interop_client.js:159:12)
      at ClientReadableStream.EventEmitter.emit (events.js:95:17)
      at /usr/local/google/home/ctiller/grpc/src/node/src/client.js:393:16
```

**Comment by ctiller** [comment]
I see the expected 4 SEND_MESSAGE ops from the server.
All 4 RECV_MESSAGE ops on the client are also posted.
Assuming that the last RECV_MESSAGE gets a null?

**Comment by murgatroid99** [comment]
That should be how it works.
