### ISSUE TITLE
Bazel RBE UBSAN failure : //test/cpp/end2end:client_lb_end2end_test@poller=poll-cv

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#17347]
There are other failures from client_lb_end2end_test but I didn't find something like this.

Seen on #17331 
```
[ RUN      ] ClientLbEnd2endTest.RoundRobinWithHealthCheckingInhibitPerChannel
D1129 19:29:10.741561568      19 ev_posix.cc:170]            Using polling engine: poll-cv
D1129 19:29:10.741677720      19 dns_resolver.cc:338]        Using native dns resolver
I1129 19:29:10.741826490      19 client_lb_end2end_test.cc:274] starting server on port 2857
I1129 19:29:10.742072267     384 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I1129 19:29:10.742956106      19 client_lb_end2end_test.cc:282] server startup complete
I1129 19:29:10.745616565      19 subchannel.cc:841]          New connected subchannel at 0x1323f40 for subchannel 0x1324190
D1129 19:29:10.746584458     385 default_health_check_service.cc:378] [HCS 0x7f39b0013b90] Health watch started for service "health_check_service_name" (handler: 0x7f39b00055f0)
I1129 19:29:35.745476423      19 subchannel.cc:841]          New connected subchannel at 0x13346f0 for subchannel 0x1332af0
D1129 19:29:35.749382338     385 default_health_check_service.cc:378] [HCS 0x7f39b0013b90] Health watch started for service "health_check_service_name" (handler: 0x7f39b0005e70)
src/core/ext/filters/client_channel/subchannel.cc:328:33: runtime error: member call on null pointer of type 'grpc_core::HealthCheckClient'
D1129 19:29:35.751244532     385 default_health_check_service.cc:472] [HCS 0x7f39b0013b90] Health watch call is notified done (handler: 0x7f39b00055f0, is_cancelled: 1).
    #0 0x7f39dee989ed in grpc_core::ConnectedSubchannelStateWatcher::OnHealthChanged(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:328:33
D1129 19:29:35.752292616     385 default_health_check_service.cc:472] [HCS 0x7f39b0013b90] Health watch call is notified done (handler: 0x7f39b0005e70, is_cancelled: 1).
    #1 0x7f39ddd81b16 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #2 0x7f39ddd818c2 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:134:9
    #3 0x7f39ddd67bc6 in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_poll_posix.cc:1133:49
    #4 0x7f39ddd80128 in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:321:21
    #5 0x7f39ddd8b15c in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10
    #6 0x7f39dee0f4b1 in run_poller(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/backup_poller.cc:122:7
    #7 0x7f39ddd81b16 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #8 0x7f39ddd818c2 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:134:9
    #9 0x7f39ddde016c in run_some_timers() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:131:30
    #10 0x7f39ddddfd94 in timer_main_loop() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:232:9
    #11 0x7f39ddddfcae in timer_thread(void*) /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:279:3
    #12 0x7f39ddb8ec60 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100:27
    #13 0x7f39ddb8e724 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74:25
    #14 0x7f39dc4ba6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #15 0x7f39db54141c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)
```

**Comment by jtattermusch** [comment]
poll-cv was removed in #18298 (the problem itself seems to be what was diagnosed as poll-cv specific by @yashykt in #18272)

**Comment by adelez** [comment]
Why do we keep this open?

**Comment by yashykt** [comment]
This might have been solved along with the other bugs. Since no one has referenced this again, it might be fine to close this
