### ISSUE TITLE
[FLAKE] ClientCallbackEnd2endTest msan failure

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#17431]
```
[ RUN      ] ClientCallbackEnd2endTest/ClientCallbackEnd2endTest.SequentialGenericRpcsAsBidi/1
I1206 17:43:57.542269033      19 ev_epoll1_linux.cc:116]     grpc epoll fd: 3
D1206 17:43:57.542325999      19 ev_posix.cc:170]            Using polling engine: epoll1
D1206 17:43:57.542615063      19 dns_resolver.cc:338]        Using native dns resolver
D1206 17:43:57.543273829      19 client_callback_end2end_test.cc:61] TestScenario{callback_server=true}
I1206 17:43:57.543796448      19 server_builder.cc:289]      Callback server.
I1206 17:43:57.544114639      19 server.cc:998]              Completion queue which is not of type GRPC_CQ_NEXT is being registered as a server-completion-queue
D1206 17:43:57.550675918      19 test_service_impl.cc:308]   Request message was Hello world.
==19==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f5b0f79fdd4 in grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall() /proc/self/cwd/include/grpcpp/impl/codegen/client_callback.h:318:9
    #1 0x971d96 in grpc::experimental::ClientBidiReactor<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall() /proc/self/cwd/external/com_github_grpc_grpc/include/grpcpp/impl/codegen/client_callback.h:166:31
    #2 0x5a3be2 in grpc::testing::(anonymous namespace)::ClientCallbackEnd2endTest::SendGenericEchoAsBidi(int)::Client::Client(grpc::testing::(anonymous namespace)::ClientCallbackEnd2endTest*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /proc/self/cwd/test/cpp/end2end/client_callback_end2end_test.cc:201:11
    #3 0x59ed2b in grpc::testing::(anonymous namespace)::ClientCallbackEnd2endTest::SendGenericEchoAsBidi(int) /proc/self/cwd/test/cpp/end2end/client_callback_end2end_test.cc:229:9
    #4 0x59d8ee in grpc::testing::(anonymous namespace)::ClientCallbackEnd2endTest_SequentialGenericRpcsAsBidi_Test::TestBody() /proc/self/cwd/test/cpp/end2end/client_callback_end2end_test.cc:296:3
    #5 0x1118348 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2402:10
    #6 0xf42c47 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2438:14
    #7 0xcab0d6 in testing::Test::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2474:5
    #8 0xcb8e7b in testing::TestInfo::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2656:11
    #9 0xccf034 in testing::TestCase::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2774:28
    #10 0xd81251 in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:4649:43
    #11 0x1162723 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2402:10
    #12 0xf6398f in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2438:14
    #13 0xd7db28 in testing::UnitTest::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:4257:10
    #14 0x65b565 in RUN_ALL_TESTS() /proc/self/cwd/external/com_github_google_googletest/googletest/include/gtest/gtest.h:2233:46
    #15 0x50e48f in main /proc/self/cwd/test/cpp/end2end/client_callback_end2end_test.cc:517:10
    #16 0x7f5b0661682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #17 0x487168 in _start (/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/end2end/client_callback_end2end_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/end2end/client_callback_end2end_test+0x487168)
  Memory was marked as uninitialized
    #0 0x4b260f in __sanitizer_dtor_callback /tmp/clang-build/src/compiler-rt/lib/msan/msan_interceptors.cc:931:3
    #1 0x7f5b0f79e3c0 in grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::~ClientCallbackReaderWriterImpl() /proc/self/cwd/include/grpcpp/impl/codegen/client_callback.h:240:7
    #2 0x7f5b0f7cfb88 in grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::MaybeFinish() /proc/self/cwd/include/grpcpp/impl/codegen/client_callback.h:260:14
    #3 0x7f5b0f7fdc29 in grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall()::'lambda2'(bool)::operator()(bool) const /proc/self/cwd/include/grpcpp/impl/codegen/client_callback.h:308:53
    #4 0x7f5b0f7fd9b5 in __invoke<(lambda at include/grpcpp/impl/codegen/client_callback.h:308:35) &, bool> /usr/local/bin/../include/c++/v1/type_traits:4356:1
    #5 0x7f5b0f7fd9b5 in void std::__1::__invoke_void_return_wrapper<void>::__call<grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall()::'lambda2'(bool)&, bool>(grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall()::'lambda2'(bool)&, bool&&) /usr/local/bin/../include/c++/v1/__functional_base:349
    #6 0x7f5b0f7fc770 in std::__1::__function::__func<grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall()::'lambda2'(bool), std::__1::allocator<grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall()::'lambda2'(bool)>, void (bool)>::operator()(bool&&) /usr/local/bin/../include/c++/v1/functional:1563:12
    #7 0x74c38f in std::__1::function<void (bool)>::operator()(bool) const /usr/local/bin/../include/c++/v1/functional:1914:12
    #8 0x74bcf1 in void grpc::internal::CatchingCallback<std::__1::function<void (bool)>&, bool&>(std::__1::function<void (bool)>&, bool&) /proc/self/cwd/external/com_github_grpc_grpc/include/grpcpp/impl/codegen/callback_common.h:41:5
    #9 0x74b83b in grpc::internal::CallbackWithSuccessTag::Run(bool) /proc/self/cwd/external/com_github_grpc_grpc/include/grpcpp/impl/codegen/callback_common.h:209:7
    #10 0x74a682 in grpc::internal::CallbackWithSuccessTag::StaticRun(grpc_experimental_completion_queue_functor*, int) /proc/self/cwd/external/com_github_grpc_grpc/include/grpcpp/impl/codegen/callback_common.h:198:47
    #11 0x7f5b0d17495c in cq_end_op_for_callback(grpc_completion_queue*, void*, grpc_error*, void (*)(void*, grpc_cq_completion*), void*, grpc_cq_completion*) /proc/self/cwd/src/core/lib/surface/completion_queue.cc:871:3
    #12 0x7f5b0d1605c6 in grpc_cq_end_op(grpc_completion_queue*, void*, grpc_error*, void (*)(void*, grpc_cq_completion*), void*, grpc_cq_completion*) /proc/self/cwd/src/core/lib/surface/completion_queue.cc:877:3
    #13 0x7f5b0d12afbe in post_batch_completion(batch_control*) /proc/self/cwd/src/core/lib/surface/call.cc:1209:5
    #14 0x7f5b0d11e539 in finish_batch_step(batch_control*) /proc/self/cwd/src/core/lib/surface/call.cc:1217:5
    #15 0x7f5b0d11809f in receiving_trailing_metadata_ready(void*, grpc_error*) /proc/self/cwd/src/core/lib/surface/call.cc:1472:3
    #16 0x7f5b0cf86088 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #17 0x7f5b0f423288 in grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /proc/self/cwd/./src/core/lib/iomgr/closure.h:259:5
    #18 0x7f5b0f40e0a2 in recv_trailing_metadata_ready(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/message_size/message_size_filter.cc:221:3
    #19 0x7f5b0cf86088 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #20 0x7f5b0f423288 in grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /proc/self/cwd/./src/core/lib/iomgr/closure.h:259:5
SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/include/grpcpp/impl/codegen/client_callback.h:318:9 in grpc::internal::ClientCallbackReaderWriterImpl<grpc::ByteBuffer, grpc::ByteBuffer>::StartCall()
Exiting
```

**Comment by yashykt** [comment]
Please close this if it was fixed.
