### ISSUE TITLE
grpc python  support protobuf2.6?

### ISSUE THREAD

**Issue by jianpingjwang** [grpc/grpc#17588]
With this command:
`python -m grpc_tools.protoc --proto_path=.  --python_out=. --grpc_python_out=. helloworld.proto
`
I can get helloworld_pb2.py and helloworld_pb2_grpc.py, which can be imported with python protobuf 3.6.

If the version of python protobuf is 2.6, there seems to be import errors:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "helloworld_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x02(\t2I\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00')
TypeError: __init__() got an unexpected keyword argument 'syntax'`

So, can I use grpc_tools.protoc to generate python files  compatible with protobuf2.6?

**Comment by jianpingjwang** [comment]
Fix this problem..
