### ISSUE TITLE
grpc 1.17.2 won't build with bazel-0.21.0

### ISSUE THREAD

**Issue by unrstuart** [grpc/grpc#17645]
grpc 1.17.2
Linux amd64

you can't just run bazel build -c opt :all, you have to specify an additional flag (which one shouldn't have to do, and which will break in future bazel releases)

```
cpunerd@cpunerd:~/src/grpc-1.17.2$ bazel build -c opt :all
INFO: Invocation ID: 209add0f-117a-46c4-935c-842f4c5ad681
INFO: SHA256 (https://github.com/census-instrumentation/opencensus-cpp/archive/fdf0f308b1631bb4a942e32ba5d22536a6170274.tar.gz) = c3a0a760759420645699140f0f7124605177a12ce0b8a2379946973771473c5d
INFO: SHA256 (https://github.com/nanopb/nanopb/archive/f8ac463766281625ad710900479130c7fcb4d63b.tar.gz) = 8bbbb1e78d4ddb0a1919276924ab10d11b631df48b657d960e0c795a25515735
INFO: SHA256 (https://github.com/madler/zlib/archive/cacf7f1d4e3d44d871b605da3b647f07d718623f.tar.gz) = 6d4d6640ca3121620995ee255945161821218752b551a1a180f4215f7d124d45
INFO: SHA256 (https://github.com/abseil/abseil-cpp/archive/cd95e71df6eaf8f2a282b1da556c2cf1c9b09207.tar.gz) = 8d6d1d6609ba9d77b3663278091643798f670d5128e0e72bf579187269281516
INFO: SHA256 (https://github.com/c-ares/c-ares/archive/3be1924221e1326df520f8498d704a5c4c8d0cce.tar.gz) = e69e33fd40a254fcf00d76efa76776d45f960e34307bd9cea9df93ef79a933f1
INFO: SHA256 (https://github.com/google/protobuf/archive/48cb18e5c419ddd23d9badcfe4e9df7bde1979b2.tar.gz) = f5a35e17fb07f3b13517264cd17a089636fcbb2912f9df7bef7414058969a8d2
ERROR: /usr/local/google/home/cpunerd/.cache/bazel/_bazel_cpunerd/1b8824ce75b8cfadab85fe4356067bd8/external/com_google_protobuf/BUILD:573:1: Traceback (most recent call last):
	File "/usr/local/google/home/cpunerd/.cache/bazel/_bazel_cpunerd/1b8824ce75b8cfadab85fe4356067bd8/external/com_google_protobuf/BUILD", line 573
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/usr/local/google/home/cpunerd/.cache/bazel/_bazel_cpunerd/1b8824ce75b8cfadab85fe4356067bd8/external/com_google_protobuf/protobuf.bzl", line 269, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/usr/local/google/home/cpunerd/.cache/bazel/_bazel_cpunerd/1b8824ce75b8cfadab85fe4356067bd8/external/com_google_protobuf/protobuf.bzl", line 269, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: /usr/local/google/home/cpunerd/.cache/bazel/_bazel_cpunerd/1b8824ce75b8cfadab85fe4356067bd8/external/com_google_protobuf/BUILD:355:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /usr/local/google/home/cpunerd/.cache/bazel/_bazel_cpunerd/1b8824ce75b8cfadab85fe4356067bd8/external/com_google_protobuf/BUILD:355:1: Target '@com_google_protobuf//:msvc' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /usr/local/google/home/cpunerd/src/grpc-1.17.2/src/proto/grpc/reflection/v1alpha/BUILD:21:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
ERROR: Analysis of target '//:grpc++_reflection' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.357s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (31 packages loaded, 1747 targets configured)
    Fetching @boringssl; fetching
```

Passing an additional flag seems to solve the problem.

```
cpunerd@cpunerd:~/src/grpc-1.17.2$ bazel build -c opt :all --incompatible_package_name_is_a_function=false
```

**Comment by unrstuart** [comment]
seems like it

**Comment by jtattermusch** [comment]
#17590 was merged, I thinks we can close now.

**Comment by devjgm** [comment]
The latest release, v1.18.0, still shows this problem with protobuf's use of REPOSITORY_NAME. When will there be a grpc release that has the fix?

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/master/doc/grpc_release_schedule.md
