### ISSUE TITLE
All macos tests failing on master: rvm problem

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17674]
https://source.cloud.google.com/results/invocations/1db967ff-0b48-496a-97a4-e963886f4fb6/log

```
++ set +ex
Warning, new version of rvm available '1.29.7-next', you are using older version '1.29.4'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.13/x86_64/ruby-2.5.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and homebrew/core).
==> New Formulae
anycable-go
atomist-cli
...
...
...
rock
/usr/local/Homebrew/Library/Homebrew/config.rb:39:in `initialize': no implicit conversion of nil into String (TypeError)
	from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `new'
	from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:25:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `<main>'
Requirements installation failed with status: 1.
[ID: 2408787] Build finished after 96 secs, exit value: 1
```

this seems to be related to the rvm setup here:
https://github.com/grpc/grpc/blob/3a59faf632427f26bc8dceed46c1fe748fd7df3c/tools/internal_ci/helper_scripts/prepare_build_macos_rc#L41

**Comment by apolcyn** [comment]
strangely, this is only happening on master, but `pull_request` jobs look green. Looking so far like a homebrew issue similar to https://github.com/Homebrew/brew/issues/4261

**Comment by jtattermusch** [comment]
Looks like #17682 have helped, test are now green on master. Thanks!
