### ISSUE TITLE
Unable to pip install grpcio

### ISSUE THREAD

**Issue by JohnVillalovos** [grpc/grpc#17711]
### What version of gRPC and what language are you using?
grpc = 1.17.1
python = 2.7.5

 
### What operating system (Linux, Windows, …) and version?
Oracle Linux Server 7.6 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.5
 
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
```
[grpcio-1.17.1]# python setup.py build
Found cython-generated files...
running build
running build_py
running build_project_metadata
copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.linux-aarch64-2.7/grpc
copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.linux-aarch64-2.7/grpc/_cython/_credentials
running build_ext
Found cython-generated files...
building 'grpc._cython.cygrpc' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) void -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/boringssl/include -Ithird_party/zlib -Ithird_party/nanopb -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/address_sorting/include -I/usr/include/python2.7 -c src/python/grpcio/grpc/_cython/cygrpc.c -o python_build/temp.linux-aarch64-2.7/src/python/grpcio/grpc/_cython/cygrpc.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -DPB_FIELD_16BIT -pthread
gcc: error: src/python/grpcio/grpc/_cython/cygrpc.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
creating tmp/tmpyBJWv5
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c /tmp/tmpyBJWv5/a.c -o tmp/tmpyBJWv5/a.o
Traceback (most recent call last):
  File "setup.py", line 353, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 52, in run
    _build_ext.run(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/grpcio-1.17.1/src/python/grpcio/commands.py", line 277, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/root/grpcio-1.17.1/src/python/grpcio/commands.py", line 272, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 186, in build_extension
    _build_ext.build_extension(self,ext)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 132, in _compile
    raise CompileError, msg
CompileError: command 'gcc' failed with exit status 4
```

 
### What did you expect to see?
 Build success
 
### What did you see instead?
Failure
 
### Anything else we should know about your project / environment?
I noticed that on CentOS 7.6 it tries to uses the C++ file: rc/python/grpcio/grpc/_cython/cygrpc.c

I am running pip 18.1

This seems like issue #15868 but I did update pip and have the same issue.

**Comment by gnossen** [comment]
I was able to reproduce with a centos 7.5 docker image. Try installing cython with `pip install cython` It appears as though we have a poor error message here. I'm looking into that.

**Comment by JohnVillalovos** [comment]
Sweet, it didn't fail after I re-ran the build with 'cython' installed.

Is there a way to mark 'cython' as a build dependency in the Python package? So pip knows to install it first.

**Comment by gnossen** [comment]
We actually do that depending on your build configuration.

After some investigation, I think the real issue here is an outdated version of setuptools. It looks like the yum `python-pip` package for centos 7.5 is installing setuptools `0.9.8`. I'm seeing some weird behavior out of this version when instantiating [`distutil.core.Extension`](https://docs.python.org/3/distutils/apiref.html#distutils.core.Extension) objects. After upgrading distutils  with  `pip install --upgrade distutils` from a fresh centos 7.5 instance, the build seems to be working just fine, regardless of whether cython is installed.
