### ISSUE TITLE
Node tests failing in interop_sanity_test.sh

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#17769]
```
[19:09:43] 'internal.test.test' errored after 15 s
[19:09:43] Error in plugin 'gulp-mocha'
Message:
    Command failed: mocha /var/local/git/grpc-node/test/api/error_test.js /var/local/git/grpc-node/test/api/interop_sanity_test.js --colors --reporter=mocha-jenkins-reporter --require=/var/local/git/grpc-node/test/fixtures/native_native.js
(node:15519) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Method handler CacheableUnaryCall for /grpc.testing.TestService/CacheableUnaryCall expected but not provided
Method handler UnimplementedCall for /grpc.testing.TestService/UnimplementedCall expected but not provided
(node:15560) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:15534) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:15575) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:15605) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:15650) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:15665) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:15676) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  Client malformed response handling
    [32m  [0m[90m should get an INTERNAL status with a unary call: [0m[90m15ms[0m
    [32m  [0m[90m should get an INTERNAL status with a client stream call: [0m[90m5ms[0m
    [32m  [0m[90m should get an INTERNAL status with a server stream call: [0m[90m4ms[0m
    [32m  [0m[90m should get an INTERNAL status with a bidi stream call: [0m[90m2ms[0m
  Suite duration: 0.034 s, Tests: 4
  Server serialization failure handling
    [32m  [0m[90m should get an INTERNAL status with a unary call: [0m[90m1ms[0m
    [32m  [0m[90m should get an INTERNAL status with a client stream call: [0m[90m1ms[0m
    [32m  [0m[90m should get an INTERNAL status with a server stream call: [0m[90m1ms[0m
    [32m  [0m[90m should get an INTERNAL status with a bidi stream call: [0m[90m1ms[0m
  Suite duration: 0.006 s, Tests: 4
  Other conditions Server recieving bad input
    [32m  [0m[90m should respond correctly to a unary call: [0m[90m1ms[0m
    [32m  [0m[90m should respond correctly to a client stream: [0m[90m1ms[0m
    [32m  [0m[90m should respond correctly to a server stream: [0m[90m1ms[0m
    [32m  [0m[90m should respond correctly to a bidi stream: [0m[90m1ms[0m
  Suite duration: 0.005 s, Tests: 4
  Other conditions Trailing metadata
    [32m  [0m[90m should be present when a unary call succeeds: [0m[90m3ms[0m
    [32m  [0m[90m should be present when a unary call fails: [0m[90m1ms[0m
    [32m  [0m[90m should be present when a client stream call succeeds: [0m[90m1ms[0m
    [32m  [0m[90m should be present when a client stream call fails: [0m[90m1ms[0m
    [32m  [0m[90m should be present when a server stream call succeeds: [0m[90m1ms[0m
    [32m  [0m[90m should be present when a server stream call fails: [0m[90m0ms[0m
    [32m  [0m[90m should be present when a bidi stream succeeds: [0m[90m1ms[0m
    [32m  [0m[90m should be present when a bidi stream fails: [0m[90m2ms[0m
  Suite duration: 0.013 s, Tests: 8
  Other conditions Error object should contain the status
    [32m  [0m[90m for a unary call: [0m[90m1ms[0m
    [32m  [0m[90m for a client stream call: [0m[90m1ms[0m
    [32m  [0m[90m for a server stream call: [0m[90m1ms[0m
    [32m  [0m[90m for a bidi stream call: [0m[90m1ms[0m
    [32m  [0m[90m for a UTF-8 error message: [0m[90m2ms[0m
  Suite duration: 0.006 s, Tests: 5
  Interop tests
OK: empty_unary
    [31m  1) should pass empty_unary[0m
OK: large_unary
    [31m  2) should pass large_unary[0m
OK: client_streaming
    [31m  3) should pass client_streaming[0m
OK: server_streaming
    [31m  4) should pass server_streaming[0m
OK: ping_pong
    [31m  5) should pass ping_pong[0m
OK: empty_stream
    [31m  6) should pass empty_stream[0m
OK: cancel_after_begin
    [31m  7) should pass cancel_after_begin[0m
OK: cancel_after_first_response
    [31m  8) should pass cancel_after_first_response[0m
OK: timeout_on_sleeping_server
    [31m  9) should pass timeout_on_sleeping_server[0m
OK: custom_metadata
    [31m  10) should pass custom_metadata[0m
OK: status_code_and_message
    [31m  11) should pass status_code_and_message[0m
OK: special_status_message
    [31m  12) should pass special_status_message[0m
OK: unimplemented_service
    [31m  13) should pass unimplemented_service[0m
OK: unimplemented_method
    [31m  14) should pass unimplemented_method[0m
  Suite duration: 14.252 s, Tests: 14
[92m [0m[32m 25 passing[0m[90m (14s)[0m
[31m  14 failing[0m
[0m  1) Interop tests should pass empty_unary:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  2) Interop tests should pass large_unary:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  3) Interop tests should pass client_streaming:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  4) Interop tests should pass server_streaming:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  5) Interop tests should pass ping_pong:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  6) Interop tests should pass empty_stream:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  7) Interop tests should pass cancel_after_begin:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  8) Interop tests should pass cancel_after_first_response:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  9) Interop tests should pass timeout_on_sleeping_server:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  10) Interop tests should pass custom_metadata:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  11) Interop tests should pass status_code_and_message:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  12) Interop tests should pass special_status_message:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  13) Interop tests should pass unimplemented_service:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
[0m  14) Interop tests should pass unimplemented_method:
[0m[31m     Error: Client exited with signal SIGSEGV[0m[90m
      at ChildProcess.clientProcess.on (test/api/interop_sanity_test.js:98:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
[0m
```

https://source.cloud.google.com/results/invocations/c96c938c-e454-48d8-a210-4a551042ce9c/targets/github%2Fgrpc%2Fgrpc-node_linux_dbg_native/tests

From the fusion dashboard, this seems to be happening on all multilang-linux PR test jobs since around 3pm today

**Comment by vjpai** [comment]
I'm going to mark this unstale since it has caused flakes within the last 3 months.

**Comment by vjpai** [comment]
@murgatroid99 tells me that this is apparently fixed, so I'll leave it closed and we can reopen only if it pops up again.
