### ISSUE TITLE
Call to grpc::InsecureChannelCredentials() is getting stuck

### ISSUE THREAD

**Issue by navneetkryadav** [grpc/grpc#17813]
Language: C++
Platform:Linux

I am trying create channel between client and server here using client code as below;
NewConnection::NewConnection() {
                // Some code here
std::shared_ptr<Channel> serverChannel = grpc::CreateChannel(serverAddress, grpc::InsecureChannelCredentials());
}

Problem Statement:
Client process is stuck with following stack trace;
Thread 1 (Thread 0x7f86264158a0 (LWP 11045)):
#0  0x000000372d8f833e in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x000000372d849616 in _L_lock_14204 () from /lib64/libc.so.6
#2  0x000000372d8494ba in buffered_vfprintf () from /lib64/libc.so.6
#3  0x000000372d84408e in vfprintf () from /lib64/libc.so.6
#4  0x000000372d84ef58 in fprintf () from /lib64/libc.so.6
#5  0x00007f86283b79a3 in gpr_default_log () from /grpc/libs/opt/libgrpc.so.1
#6  0x00007f86283b77ed in gpr_log_message () from /grpc/libs/opt/libgrpc.so.1
#7  0x00007f86283b7adb in gpr_log () from /grpc/libs/opt/libgrpc.so.1
#8  0x00007f86283b74f7 in gpr_getenv () from /grpc/libs/opt/libgrpc.so.1
#9  0x00007f86283b7742 in gpr_log_verbosity_init () from /grpc/libs/opt/libgrpc.so.1
#10 0x00007f862836202b in do_basic_init () from /grpc/libs/opt/libgrpc.so.1
#11 0x000000372dc0ce03 in pthread_once () from /lib64/libpthread.so.0
#12 0x00007f86283ba1f9 in gpr_once_init () from /grpc/libs/opt/libgrpc.so.1
#13 0x00007f8628362137 in grpc_init () from /grpc/libs/opt/libgrpc.so.1
#14 0x00007f86280b2b94 in grpc::ChannelCredentials::ChannelCredentials() () from /grpc/libs/opt/libgrpc++.so.1
#15 0x00007f86280b572d in grpc::InsecureChannelCredentials() () from /grpc/libs/opt/libgrpc++.so.1
#16 0x00000000005916ec in NewConnection::NewConnection() ()

Scenario:
It works fine for single call, but when i make say more than 100 individual calls for channel creation between client and server, the thread gets locked and stays in waiting state.

Query:
Can someone help me on this, why it is stuck, any help would be appreciated.

**Comment by navneetkryadav** [comment]
Closing this as it is resolved, problem found with max file descriptor.
