### ISSUE TITLE
new ASAN issues in client_channel code 

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#17819]
I am seeing this failure

```

    #1 0x4bf5aa in __asan_memcpy (/usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/bins/asan/h2_full+trace_test+0x4bf5aa)
    #2 0x72aceb in put_metadata_list(gpr_strvec*, grpc_metadata_batch) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/transport/transport_op_string.cc:51:21
    #3 0x72a172 in grpc_transport_stream_op_batch_string(grpc_transport_stream_op_batch*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/transport/transport_op_string.cc:71:5
    #4 0x73f0fb in on_complete(void*, grpc_error*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/ext/filters/client_channel/client_channel.cc:1731:23
    #5 0x67a96a in exec_ctx_run(grpc_closure*, grpc_error*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3
    #6 0x67a4d4 in grpc_core::ExecCtx::Flush() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/exec_ctx.cc:147:9
    #7 0x6b40f0 in run_some_timers() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/timer_manager.cc:132:30
    #8 0x6b3bf4 in timer_main_loop() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/timer_manager.cc:238:9
    #9 0x6b39a7 in timer_thread(void*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/timer_manager.cc:285:3
    #10 0x8cb411 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/gprpp/thd_posix.cc:100:27
    #11 0x8cae45 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/gprpp/thd_posix.cc:74:25
    #12 0x4e2302 in __asan::AsanThread::ThreadStart(unsigned long, __sanitizer::atomic_uintptr_t*) (/usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/bins/asan/h2_full+trace_test+0x4e2302)
    #13 0x7fab5c0ef493 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7493)
    #14 0x7fab5b894a8e in clone (/lib/x86_64-linux-gnu/libc.so.6+0xe8a8e)
 
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x83f5d) 
Thread T3 (grpc_global_tim) created by T0 here:
    #0 0x437d40 in pthread_create (/usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/bins/asan/h2_full+trace_test+0x437d40)
    #1 0x8ca9cf in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/gprpp/thd_posix.cc:73:10
    #2 0x8ca4c9 in grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/./src/core/lib/gprpp/memory.h:47:18
    #3 0x8ca030 in grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/gprpp/thd_posix.cc:142:7
    #4 0x6b3825 in start_timer_thread_and_unlock() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/timer_manager.cc:98:13
    #5 0x6b3081 in start_threads() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/timer_manager.cc:294:5
    #6 0x6b3013 in grpc_timer_manager_init() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/timer_manager.cc:317:3
    #7 0x67b501 in grpc_iomgr_start() /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/iomgr/iomgr.cc:63:27
    #8 0x8a575f in grpc_init /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/src/core/lib/surface/init.cc:150:5
    #9 0x513146 in main /usr/local/google/home/yashkt/grpc-projects/grpc-c-fork/grpc/test/core/end2end/fixtures/h2_full+trace.cc:127:3
    #10 0x7fab5b7cc2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
```

on running gRPC Core tests with ASAN on. I can consistently reproduce it with -
tools/run_tests/run_tests.py -lc --regex "h2_full" -ninf -casan

There isn't much information here, but I'm guessing it's not safe to access some elements of the batch at this point.

**Comment by yashykt** [comment]
This happens when client_channel tracer is enabled

**Comment by yashykt** [comment]
We also get segfaults on Basic Tests C Linux [dbg].. #17817 seemed to make these fail more deterministically..

Relevant log files -
https://source.cloud.google.com/results/invocations/356a5d1e-a9de-4c61-803f-d33036d86b36/targets/github%2Fgrpc%2Fc_linux_dbg_native/log
https://source.cloud.google.com/results/invocations/c98c362c-64e5-4254-9d3f-8a054f7b1941/targets/github%2Fgrpc%2Fc_linux_asan_native_x64_clang7.0/log

**Comment by markdroth** [comment]
I can reliably reproduce this by running the following:

```
GRPC_VERBOSITY=DEBUG GRPC_TRACE=client_channel,channel ./bins/dbg/client_lb_end2end_test --gtest_filter=ClientLbInterceptTrailingMetadataTest.InterceptsRetriesEnabled
```

I tried modifying `grpc_transport_stream_op_batch_string()` to log the address of the send_initial_metadata batch instead of logging its contents, so that it looks something like this:

```
gpr_asprintf(&tmp, "MD=%p,", op->payload->send_initial_metadata.send_initial_metadata);
gpr_strvec_add(&b, tmp);
//    put_metadata_list(
//        &b, *op->payload->send_initial_metadata.send_initial_metadata);
```

What I'm seeing is that the `op->payload->send_initial_metadata.send_initial_metadata` is being set to a different location between the time that the batch hits the transport and the time that the on_complete callback is invoked.  So I think this must be a chttp2 bug somewhere.

I suspect that this has nothing to do with the retry code; it's probably just that the retry code is the only place where we're trying to log the contents of the batch on the way back up the stack.

**Comment by yashykt** [comment]
Found it. 

What was happening was grpc_chttp2_stream->byte_counter was using the same memory address as the send_initial_metadata pointer in a subchannel batch. So, when the byte_counter was being incremented, so was the pointer. This meant that when we tried to print out the send_initial_metadata after it was modified, we were getting a corrupt address.

The root reason for this was that we align addresses using GPR_ROUND_UP_TO_ALIGNMENT_SIZE and this also needs to be factored in when performing size calculations. One place in the subchannel code was not doing this, and hence the strange bug :)
