### ISSUE TITLE
GRPC C#  Hellow world sample  fails to run on Rpi 

### ISSUE THREAD

**Issue by AjitParanjpeDev** [grpc/grpc#18090]
### What version of gRPC and what language are you using?
 gRPC- tried with  1.18.0,1.17.0 1.16.0 
Language : C# dotnet core
 
### What operating system (Linux, Windows, …) and version?
 Linux on rapspberri pi 
OS: debian version 8
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/opt/dotnet/shared/Microsoft.NETCore.App]

 
 
### What did you do?
1. I downloaded GRPC master [1.18.0]
   examples>csharp>Helloworld eg.  
2. I published it for deployment publish command used
   Win7: dotnet publish -r win7-x64
   ubuntu: dotnet publish -r linux-64 (ubuntu.14.04-x64)
   Rpi: dotnet publish -r linux-arm 

i am able to successfully deploy  the sample in win7 and Ubuntu .

### What did you expect to see?
 I was expecting successful deployment of server in rpi as well.
 
### What did you see instead?
 I am observing exception while trying to run server
 
Exception:
{  
{ Unhandled Exception: System.IO.IOException: Error loading native library "/mnt/automation/Ajit/Greeter_18referringDLL/Server/publish/libgrpc_csharp_ext.x86.so".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\UnmanagedLibrary.cs:line 58
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary() in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\NativeExtension.cs:line 100
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods() in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\NativeExtension.cs:line 117
   at Grpc.Core.Internal.NativeExtension..ctor() in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\NativeExtension.cs:line 38
   at Grpc.Core.Internal.NativeExtension.Get() in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\NativeExtension.cs:line 62
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit() in T:\src\github\grpc\src\csharp\Grpc.Core\GrpcEnvironment.cs:line 373
   at Grpc.Core.GrpcEnvironment..ctor() in T:\src\github\grpc\src\csharp\Grpc.Core\GrpcEnvironment.cs:line 302
   at Grpc.Core.GrpcEnvironment.AddRef() in T:\src\github\grpc\src\csharp\Grpc.Core\GrpcEnvironment.cs:line 78
   at Grpc.Core.Server..ctor(IEnumerable`1 options) in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 72
   at Grpc.Core.Server..ctor() in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 60
   at GreeterServer.Program.Main(String[] args) in D:\GRPC\GreeterSolutionCreated\18_02_2019\Greeter\GreeterServer\Program.cs:line 37
}

 
### Anything else we should know about your project / environment?
Rpi Details:
Linux rpigta 4.9.35-v7+ #1014 SMParmv7l GNU/Linux.

**Comment by Pablotagu** [comment]
@AjitParanjpeDev  I faced the same problem when I was deploying (with 1.17) and I solved it by adding the grpc.native.csharp nuget package. Anyway it might not be the proper solution

**Comment by AjitParanjpeDev** [comment]
@Pablotagu 
I added grpc.native.csharp package to Greeter solution. (GRPC 1.17.0)
I added it to all 3 projects (Greeter, GreeterServer, GreeterClient ).
after adding it created nativeLibs folder into Server and Client Project.

I published it for all 3 (win7,linux, Rpi)
Win7 [dotnet publish -r win7-x64]
linux  [dotnet publish -r linux-x64]
Rpi    [dotnet publish -r linux-arm ]

Win7 it is running fine.

Rpi it is giving same error 
 Error loading native library "/mnt/a                                                                                                             utomation/Ajit/Greeter_19_02/linux-arm/publish/libgrpc_csharp_ext.x86.so".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives  


Can you please tell me if i am doing something wrong . 
Did you deploy it in Rpi?

**Comment by jtattermusch** [comment]
Normally, just building (and publishing in your case) the helloworld project would work just fine - no other steps should be needed. The problem here is that it seems you're trying to run on a linux with arm processor and gRPC C# doesn't support that (you'd need the internal native library built for arm, and we don't ship one with the Grpc.Core nuget.

Related issues: https://github.com/grpc/grpc/issues/17451 https://github.com/grpc/grpc/issues/16929

I'm going to close this issue as a duplicate.
