### ISSUE TITLE
[Flake] Interop ALTS java->go server time out

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#18111]
https://source.cloud.google.com/results/invocations/45c5d7af-84de-4ac3-8f27-ed0acb9b4c6d/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log
This looks very similar to #15434

```
2019-02-20 12:16:43,025 Running test ping_pong
Exception in thread "main" java.lang.AssertionError: Timed out waiting for response
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at io.grpc.testing.integration.AbstractInteropTest.pingPong(AbstractInteropTest.java:725)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:269)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:212)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:70)
Shutting down
2019-02-20 12:16:43,025 FAILED: cloud_to_cloud:java:go_server:ping_pong:alts [ret=1, pid=2259, time=7.2sec]
```

**Comment by gnossen** [comment]
Spotted again in the wild: https://source.cloud.google.com/results/invocations/c2359a46-d3d2-49a1-a5e8-9bdd5a24767b/log

**Comment by jtattermusch** [comment]
based on go/grpc-flaky dashboard, I don't think we are seeing this anymore

**Comment by dapengzhang0** [comment]
How flaky is the test? The timeout for this test is 5 seconds, so there is a very small chance that timeout could happen.

**Comment by gnossen** [comment]
Two instances since May 14th that we've noticed. I don't have a number to put on it at the moment.

**Comment by gnossen** [comment]
Another instance: https://source.cloud.google.com/results/invocations/6dc06a00-8d77-469c-979b-da6ace70fdd8/log

**Comment by apolcyn** [comment]
another instance: https://source.cloud.google.com/results/invocations/29f20b8e-1031-490a-bc0d-edb3a12be523/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

**Comment by dapengzhang0** [comment]
@temawi would be the candidate to triage the issue.

**Comment by drfloob** [comment]
@temawi   I'm guessing this is stale, as we've just gone through a fixit sprint, but I'll let you evaluate and decide.

**Comment by temawi** [comment]
I went through a bunch of the most recent failures for this target and this error did not appear. I believe this one is stale and I'll close it.

**Comment by rockspore** [comment]
This test has been failing for about a week again with the same error log. For example: https://source.cloud.google.com/results/invocations/6a70fbad-1029-4fad-b80a-f930ab46f5f2/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

**Comment by yashykt** [comment]
As we decided some time back, we don't want to track interop flakes here. (It should go to internal buganizer.)
