### ISSUE TITLE
Test flake: py27_native.test.health_check._health_servicer_test.HealthServicerTest

### ISSUE THREAD

**Issue by rmstar** [grpc/grpc#18127]
https://source.cloud.google.com/results/invocations/b9013af2-c6e4-4197-b96a-6865e3656cbc/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_basictests_multilang/log
```
Errors/Failures:
health_check._health_servicer_test.HealthServicerTest.test_cancelled_watch_removed_from_watch_list
traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/health_check/_health_servicer_test.py", line 203, in test_cancelled_watch_removed_from_watch_list
    'watch set should be empty')
  File "/usr/lib/python2.7/unittest/case.py", line 416, in assertFalse
    raise self.failureException(msg)
AssertionError: watch set should be empty
stdout:
stderr:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/health_check/_health_servicer_test.py", line 38, in _consume_responses
    for response in response_iterator:
  File "/var/local/git/grpc/py27_native/lib/python2.7/site-packages/grpc/_channel.py", line 366, in next
    return self._next()
  File "/var/local/git/grpc/py27_native/lib/python2.7/site-packages/grpc/_channel.py", line 357, in _next
    raise self
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Locally cancelled by application!"
	debug_error_string = "None"
>
Unexpected successes: []
Test failure
2019-02-21 09:37:43,182 FAILED: py27_native.test.health_check._health_servicer_test.HealthServicerTest [ret=1, pid=22908, time=15.8sec]
```

**Comment by ericgribkoff** [comment]
Also seen at https://source.cloud.google.com/results/invocations/a5f88a91-bfa7-43b1-8c50-934c352031b8/targets. Sending a PR to temporarily disable the test, as it looks like the assumption that cancellation will always propagate to the server callback is false.

**Comment by ericgribkoff** [comment]
@gnossen I was unable to determine anything in the health service itself that should be the cause of this flake. I did check and we do not actually have a separate test that guarantees that a client cancellation always triggers the server's `{on_done_}callback`, which is the portion of this test that appears to be failing. It may also be that there is no such guarantee in our API, although AFAICT it is at least implied...
