### ISSUE TITLE
Python Bazel build failed after #18082

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#18267]
I found the `bazel test src/python/...` will fail with:

```
FAIL: //src/python/grpcio_tests/tests/unit:_rpc_test (see /private/var/tmp/_bazel_lidiz/ee2c6ba1011b403418e3cd5ac063655b/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/testlogs/src/python/grpcio_tests/tests/unit/_rpc_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests/unit:_rpc_test:
==================== Test output for //src/python/grpcio_tests/tests/unit:_rpc_test:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_lidiz/ee2c6ba1011b403418e3cd5ac063655b/sandbox/darwin-sandbox/36/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/src/python/grpcio_tests/tests/unit/_rpc_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/unit/_rpc_test.py", line 22, in <module>
    import grpc
  File "/private/var/tmp/_bazel_lidiz/ee2c6ba1011b403418e3cd5ac063655b/sandbox/darwin-sandbox/36/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/src/python/grpcio_tests/tests/unit/_rpc_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: dlopen(/private/var/tmp/_bazel_lidiz/ee2c6ba1011b403418e3cd5ac063655b/sandbox/darwin-sandbox/36/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/src/python/grpcio_tests/tests/unit/_rpc_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so, 2): Symbol not found: __Z31grpc_set_default_iomgr_platformv
  Referenced from: /private/var/tmp/_bazel_lidiz/ee2c6ba1011b403418e3cd5ac063655b/sandbox/darwin-sandbox/36/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/src/python/grpcio_tests/tests/unit/_rpc_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_lidiz/ee2c6ba1011b403418e3cd5ac063655b/sandbox/darwin-sandbox/36/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/bin/src/python/grpcio_tests/tests/unit/_rpc_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so
```

After bisecting the problem, I found the https://github.com/grpc/grpc/commit/6177befe94cd98906daea492f04ed9248be6b4bb is the first bad commit.

**Comment by srini100** [comment]
Marked this as blocker for 1.19.1 patch. 
@lidizheng, does the fix in https://github.com/grpc/grpc/pull/18201 apply here?

**Comment by lidizheng** [comment]
@srini100 The latest fix didn't fix the Python Bazel build. But I'm trying to apply similar change, and see  if I can put the symbol back.

**Comment by lidizheng** [comment]
Thanks to @gnossen for pointing out the way of validating included code trunks, which makes the debugging much more easier.
