### ISSUE TITLE
C# with TLS exceptions broken `Status(StatusCode=Unknown, Detail="")` 

### ISSUE THREAD

**Issue by clehene** [grpc/grpc#18288]
### What version of gRPC and what language are you using?
1.19 and 1.18  C#
 
### What operating system (Linux, Windows,...) and version?
 
OSX / Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
.net core 2.2
 
### What did you do?

When making the request from a java client to the TLS endpoint I get the full exception detail
When making the request from C# to the local gRPC server directly I get the full exception detail
When making the request from C# to the TLS endpoint the details are lost.

```
...
var channelCredentials = new SslCredentials(File.ReadAllText(certRoot));
var ch = new Channel(host, port, channelCredentials);
return ch.Intercept(new AuthInterceptor(apiKey, ""));

// vs

var ch = new Channel("localhost", 8000, ChannelCredentials.Insecure);

...

            using (var call = txnService.StreamTransactions(new Metadata()))
            {
                //create async task to process response stream
                var responseTask = Task.Run(async () =>
                {
                    while (await call.ResponseStream.MoveNext())
                    {
                        var ack = call.ResponseStream.Current;
                        testResults.Add(ack.AckId);
                        Console.WriteLine("Received id: " + ack.AckId);
                    }
                });

                foreach (var tr in TestData)
                {
                    Console.WriteLine($"Sending  id: {tr} ...");
                    await call.RequestStream.WriteAsync(tr);
                }

                await call.RequestStream.CompleteAsync();
                try
                {
                    await responseTask;
                }
                catch (RpcException e)
                {
                    Console.WriteLine(e);
                }
            }
        }
```

### What did you expect to see?

E.g. When doing the same request to directly to my local gRPC server

```
Grpc.Core.RpcException: Status(StatusCode=PermissionDenied, Detail="<ACTUAL ERROR DETAIL (REDCATED)>")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ClientResponseStream.cs:line 61
   at TWSdk.Program.<>c__DisplayClass7_1.<<StreamTransactions>b__0>d.MoveNext() in /Users/clehene/TW/csharp-sdk/TWSdk/Program.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at TWSdk.Program.StreamTransactions(CallInvoker ch_) in /Users/clehene/TW/csharp-sdk/TWSdk/Program.cs:line 132
```
 
### What did you see instead?

When making the request over TLS:

```
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ClientResponseStream.cs:line 61
   at TWSdk.Program.<>c__DisplayClass7_1.<<StreamTransactions>b__0>d.MoveNext() in /Users/clehene/TW/csharp-sdk/TWSdk/Program.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at TWSdk.Program.StreamTransactions(CallInvoker ch) in /Users/clehene/TW/csharp-sdk/TWSdk/Program.cs:line 132

```

**Comment by jtattermusch** [comment]
please enable extra tracing using https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md and report back any findings.

I can't know for sure but it seems like it could be the TLS connection failing (bad certificates?) so the connection never gets established (which leads to a different error).

**Comment by jtattermusch** [comment]
Also, you should consider using https://github.com/grpc/grpc/blob/7095e051f2183b632aac241c27cf6b53b69d50e9/src/csharp/Grpc.Core/CallCredentials.cs#L49 instead of the auth interceptor because then the gRPC stack will stop the auth metadata from being sent over an insecure connection (which is dangerous).
