### ISSUE TITLE
grpc_ios_binary_size flake

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#18282]
https://source.cloud.google.com/results/invocations/0075e296-23ab-4b8c-a490-d0e5a647a2da/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size/log

```
Previous HEAD position was 2bd7ad0112... Merge pull request #18263 from markdroth/grpclb_child_policy_configurable
Switched to branch 'pull_branch'
Traceback (most recent call last):
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 64, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'
Traceback (most recent call last):
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 64, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'
Traceback (most recent call last):
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 64, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'
Traceback (most recent call last):
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 64, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'
Traceback (most recent call last):
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 64, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,093,825      Total (<)      2,093,897
 No significant differences in binary sizes
***************FRAMEWORKS****************
  New size                      Old size
11,722,920      Total (>)     11,722,918
 No significant differences in binary sizes
HTTP Status 401 Unauthorized
Fetch access token from Github API failed:
{"message":"'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued","documentation_url":"https://developer.github.com/v3"}
Retrying after 1.00 second.
HTTP Status 401 Unauthorized
Fetch access token from Github API failed:
{"message":"'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued","documentation_url":"https://developer.github.com/v3"}
Retrying after 1.00 second.
HTTP Status 401 Unauthorized
Fetch access token from Github API failed:
{"message":"'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued","documentation_url":"https://developer.github.com/v3"}
Retrying after 1.00 second.
HTTP Status 401 Unauthorized
Fetch access token from Github API failed:
{"message":"'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued","documentation_url":"https://developer.github.com/v3"}
Retrying after 1.00 second.
HTTP Status 401 Unauthorized
Fetch access token from Github API failed:
{"message":"'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued","documentation_url":"https://developer.github.com/v3"}
error: Unable to fetch access token, exiting...
[ID: 4094683] Build finished after 3387 secs, exit value: 1
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[12:20:52] Collecting build artifacts from build VM
Build script failed with exit code: 1
```

**Comment by rmstar** [comment]
Looks like the retries added in #18031 don't help in this case as the error is not transient. CC @lidizheng
