### ISSUE TITLE
Server send INVALID_ARGUMENT, client receive CANCELLED

### ISSUE THREAD

**Issue by xolott** [grpc/grpc#18316]
### What version of gRPC and what language are you using?
 1.17.0
 
### What operating system (Linux, Windows,...) and version?
 Ubuntu 18.04.1
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .net core 2.2
 
### What did you do?
I'm trying to add custom data to the RpcException generated by my server. Like this:
```chsarp
throw new RpcException(
    status: new Status(StatusCode.InvalidArgument, "Custom details"),
    trailers: new Metadata(),
    message: "CustomInvalidArgumentException"
);
```
 
### What did you expect to see?
 RcpException on the client with status code `INVALID_ARGUMENT`
 
### What did you see instead?
 ```console
Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")
         at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ClientResponseStream.cs:line 61
```
I changed the `StatusCode` to `Unknown` and the client shows the correct exception information. Is there any reason that justifies the `Cancelled` status?

### Anything else we should know about your project / environment?
Both server and client runs locally.

**Comment by jtattermusch** [comment]
I tried to reproduce based on your instructions (throw an RpcException from the server-side handler and check that I get StatusCode.InvalidArgument on the client side) and everything worked as expected. 

I'm going to close this issue as "not reproducible". If you can provide more data on how to reproduce, I can reopen.

**Comment by xolott** [comment]
I managed to find where the issue is originated. I'm trying to return the internal Stack Trace of my custom exception via Metadata.

I implemented the Greeter Example using Grpc.Core, and modified the `SayHello` method

```csharp
public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
{
    try
    {
        RecursiveMethod(4);
    }
    catch(Exception)
    {
        var metadata = new Metadata();
        metadata.Add("stack_trace", exc.StackTrace);
        throw new RpcException(
            status: new Status(StatusCode.InvalidArgument, "Custom details"),
            trailers: metadata,
            message: "Custom Message"
        );
    }
}
private void RecursiveMethod(int iteration)
{
    if(iteration < 1)
    {
        throw new Exception("Custom Exception!");
    }
    RecursiveMethod(iteration -1);
}
```
This exception generate the following stack trace (722 chars length):

```
at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.SayHello(HelloRequest request, ServerCallContext context) in ~/Desktop/app/Services/GreeterImpl.cs:line 51
```

And receive a `Cancelled` status on the client side. If I set to 0 the parameter passed to `RecursiveMethod` (reducing the length of the stack trace), o remove the metadata from the generated `RpcEception`, the client receives the custom RpcException.

Is there any limitation on the metadata?

**Comment by jtattermusch** [comment]
Can you run with GRPC_VERBBOSITY=debug as described in https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md? Perhaps that will tell us more.

**Comment by xolott** [comment]
This is the server running as requested

```console
$ GRPC_VERBOSITY=DEBUG dotnet run -p GreeterServer/
D0312 11:38:22.745150 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/home/jose/.nuget/packages/grpc.core/1.17.0/lib/netstandard1.5/../../runtimes/linux/native/libgrpc_csharp_ext.x64.so"
D0312 11:38:22.778401 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0312 11:38:22.779392 139695844788032 /var/local/git/grpc/src/core/lib/iomgr/ev_posix.cc:169: Using polling engine: epollex
D0312 11:38:22.779486 139695844788032 /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:338: Using native dns resolver
Greeter server listening on port 50051
Press any key to stop the server...
E0312 11:38:40.449061 139692821419776 /var/local/git/grpc/src/core/lib/surface/call.cc:897: validate_metadata: {"created":"@1552401520.448874453","description":"Illegal header value","file":"/var/local/git/grpc/src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":151,"raw_bytes":"20 20 20 61 74 20 47 72 65 65 74 65 72 53 65 72 76 65 72 2e 47 72 65 65 74 65 72 49 6d 70 6c 2e 52 65 63 75 72 73 69 76 65 4d 65 74 68 6f 64 28 49 6e 74 33 32 20 69 74 65 72 61 74 69 6f 6e 29 20 69 6e 20 2f 68 6f 6d 65 2f 6a 6f 73 65 2f 44 65 73 6b 74 6f 70 2f 67 72 70 63 2f 65 78 61 6d 70 6c 65 73 2f 63 73 68 61 72 70 2f 48 65 6c 6c 6f 77 6f 72 6c 64 2f 47 72 65 65 74 65 72 53 65 72 76 65 72 2f 50 72 6f 67 72 61 6d 2e 63 73 3a 6c 69 6e 65 20 34 39 0a 20 20 20 61 74 20 47 72 65 65 74 65 72 53 65 72 76 65 72 2e 47 72 65 65 74 65 72 49 6d 70 6c 2e 52 65 63 75 72 73 69 76 65 4d 65 74 68 6f 64 28 49 6e 74 33 32 20 69 74 65 72 61 74 69 6f 6e 29 20 69 6e 20 2f 68 6f 6d 65 2f 6a 6f 73 65 2f 44 65 73 6b 74 6f 70 2f 67 72 70 63 2f 65 78 61 6d 70 6c 65 73 2f 63 73 68 61 72 70 2f 48 65 6c 6c 6f 77 6f 72 6c 64 2f 47 72 65 65 74 65 72 53 65 72 76 65 72 2f 50 72 6f 67 72 61 6d 2e 63 73 3a 6c 69 6e 65 20 34 39 0a 20 20 20 61 74 20 47 72 65 65 74 65 72 53 65 72 76 65 72 2e 47 72 65 65 74 65 72 49 6d 70 6c 2e 52 65 63 75 72 73 69 76 65 4d 65 74 68 6f 64 28 49 6e 74 33 32 20 69 74 65 72 61 74 69 6f 6e 29 20 69 6e 20 2f 68 6f 6d 65 2f 6a 6f 73 65 2f 44 65 73 6b 74 6f 70 2f 67 72 70 63 2f 65 78 61 6d 70 6c 65 73 2f 63 73 68 61 72 70 2f 48 65 6c 6c 6f 77 6f 72 6c 64 2f 47 72 65 65 74 65 72 53 65 72 76 65 72 2f 50 72 6f 67 72 61 6d 2e 63 73 3a 6c 69 6e 65 20 34 39 0a 20 20 20 61 74 20 47 72 65 65 74 65 72 53 65 72 76 65 72 2e 47 72 65 65 74 65 72 49 6d 70 6c 2e 52 65 63 75 72 73 69 76 65 4d 65 74 68 6f 64 28 49 6e 74 33 32 20 69 74 65 72 61 74 69 6f 6e 29 20 69 6e 20 2f 68 6f 6d 65 2f 6a 6f 73 65 2f 44 65 73 6b 74 6f 70 2f 67 72 70 63 2f 65 78 61 6d 70 6c 65 73 2f 63 73 68 61 72 70 2f 48 65 6c 6c 6f 77 6f 72 6c 64 2f 47 72 65 65 74 65 72 53 65 72 76 65 72 2f 50 72 6f 67 72 61 6d 2e 63 73 3a 6c 69 6e 65 20 34 39 0a 20 20 20 61 74 20 47 72 65 65 74 65 72 53 65 72 76 65 72 2e 47 72 65 65 74 65 72 49 6d 70 6c 2e 52 65 63 75 72 73 69 76 65 4d 65 74 68 6f 64 28 49 6e 74 33 32 20 69 74 65 72 61 74 69 6f 6e 29 20 69 6e 20 2f 68 6f 6d 65 2f 6a 6f 73 65 2f 44 65 73 6b 74 6f 70 2f 67 72 70 63 2f 65 78 61 6d 70 6c 65 73 2f 63 73 68 61 72 70 2f 48 65 6c 6c 6f 77 6f 72 6c 64 2f 47 72 65 65 74 65 72 53 65 72 76 65 72 2f 50 72 6f 67 72 61 6d 2e 63 73 3a 6c 69 6e 65 20 34 39 0a 20 20 20 61 74 20 47 72 65 65 74 65 72 53 65 72 76 65 72 2e 47 72 65 65 74 65 72 49 6d 70 6c 2e 53 61 79 48 65 6c 6c 6f 28 48 65 6c 6c 6f 52 65 71 75 65 73 74 20 72 65 71 75 65 73 74 2c 20 53 65 72 76 65 72 43 61 6c 6c 43 6f 6e 74 65 78 74 20 63 6f 6e 74 65 78 74 29 20 69 6e 20 2f 68 6f 6d 65 2f 6a 6f 73 65 2f 44 65 73 6b 74 6f 70 2f 67 72 70 63 2f 65 78 61 6d 70 6c 65 73 2f 63 73 68 61 72 70 2f 48 65 6c 6c 6f 77 6f 72 6c 64 2f 47 72 65 65 74 65 72 53 65 72 76 65 72 2f 50 72 6f 67 72 61 6d 2e 63 73 3a 6c 69 6e 65 20 32 39 '   at GreeterServer.GreeterImpl.RecursiveMethod(Int32 iteration) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterServer/Program.cs:line 49.   at GreeterServer.GreeterImpl.RecursiveMethod(Int32 iteration) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterServer/Program.cs:line 49.   at GreeterServer.GreeterImpl.RecursiveMethod(Int32 iteration) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterServer/Program.cs:line 49.   at GreeterServer.GreeterImpl.RecursiveMethod(Int32 iteration) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterServer/Program.cs:line 49.   at GreeterServer.GreeterImpl.RecursiveMethod(Int32 iteration) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterServer/Program.cs:line 49.   at GreeterServer.GreeterImpl.SayHello(HelloRequest request, ServerCallContext context) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterServer/Program.cs:line 29'"}
W0312 11:38:40.454152 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Call error: 10
   at Grpc.Core.Internal.CallErrorExtensions.CheckOk(CallError callError) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\CallError.cs:line 62
   at Grpc.Core.Internal.CallSafeHandle.StartSendStatusFromServer(ISendStatusFromServerCompletionCallback callback, Status status, MetadataArraySafeHandle metadataArray, Boolean sendEmptyInitialMetadata, Byte[] optionalPayload, WriteFlags writeFlags) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\CallSafeHandle.cs:line 138
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCallServer.cs:line 143
   at Grpc.Core.Internal.UnaryServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ServerCallHandler.cs:line 85
   at Grpc.Core.Server.HandleCallAsync(ServerRpcNew newRpc, CompletionQueueSafeHandle cq, Action continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 346
```

An the client:
```console
$ GRPC_VERBOSITY=DEBUG dotnet run -p GreeterClient/
D0312 11:38:40.333613 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/home/jose/.nuget/packages/grpc.core/1.17.0/lib/netstandard1.5/../../runtimes/linux/native/libgrpc_csharp_ext.x64.so"
D0312 11:38:40.366065 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0312 11:38:40.366999 140198980872000 /var/local/git/grpc/src/core/lib/iomgr/ev_posix.cc:169: Using polling engine: epollex
D0312 11:38:40.367104 140198980872000 /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:338: Using native dns resolver
D0312 11:38:40.397160 140198980872000 /var/local/git/grpc/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:279: Start resolving.
I0312 11:38:40.397800 140198980872000 /var/local/git/grpc/src/core/ext/filters/client_channel/subchannel.cc:841: New connected subchannel at 0x1bfaf70 for subchannel 0x7f81ec0026c0

Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 78
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 51
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 48
   at Helloworld.Greeter.GreeterClient.SayHello(HelloRequest request, CallOptions options) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/Greeter/obj/Debug/netstandard1.5/HelloworldGrpc.cs:line 108
   at Helloworld.Greeter.GreeterClient.SayHello(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/Greeter/obj/Debug/netstandard1.5/HelloworldGrpc.cs:line 98
   at GreeterClient.Program.Main(String[] args) in /home/jose/Desktop/grpc/examples/csharp/Helloworld/GreeterClient/Program.cs:line 30

```

**Comment by jtattermusch** [comment]
The message is pretty clear. You're trying to use illegal characters as metadata values.
The spec https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md   only allows `ASCII-Value → 1*( %x20-%x7E ) ; space and printable ASCII` (you probably have newline characters in your msg.

To overcome this limitation, you can use binary-valued metadata. 
A common best practice is to send exception details (e.g. stack trace) in form of a protocol buffer message serialized in a binary-valued metadata entry.
Example: 
https://github.com/grpc/grpc/blob/a76465c65cca37dbb85adc7d97c5d4af367bef0f/src/csharp/Grpc.IntegrationTesting/CustomErrorDetailsTest.cs#L119
