### ISSUE TITLE
objc build failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#18430]
https://source.cloud.google.com/results/invocations/4e5fac14-bad9-46da-9d49-bc46dce6a07a/targets/github%2Fgrpc%2Fobjc_macos_opt_native/tests

```
GenerateDSYMFile /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/APIv2Tests.xctest.dSYM /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/APIv2Tests.xctest/APIv2Tests
    /Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/APIv2Tests.xctest/APIv2Tests -o /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/APIv2Tests.xctest.dSYM
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/APIv2Tests.build/Script-C17B826BBD02FDD4A5F355AF.sh
    /bin/sh -c /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/APIv2Tests.build/Script-C17B826BBD02FDD4A5F355AF.sh
/Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/APIv2Tests.build/Script-C17B826BBD02FDD4A5F355AF.sh: line 2: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/Pods/Target Support Files/Pods-APIv2Tests/Pods-APIv2Tests-resources.sh: No such file or directory
kill -9 `jobs -p` ; echo "EXIT TIME:  $(date)"
jobs -p
date
EXIT TIME:  Mon Mar 18 15:29:46 PDT 2019
```

**Comment by apolcyn** [comment]
just saw an objc build failure with:

```
xcodebuild \
    -workspace Tests.xcworkspace \
    -scheme $SCHEME \
    -destination "$DESTINATION" \
    HOST_PORT_LOCALSSL=localhost:$TLS_PORT \
    HOST_PORT_LOCAL=localhost:$PLAIN_PORT \
    HOST_PORT_REMOTE=grpc-test.sandbox.googleapis.com \
    test \
    | ./verbose_time.sh \
    | egrep -v "$XCODEBUILD_FILTER" \
    | egrep -v '^$' \
    | egrep -v "(GPBDictionary|GPBArray)" -
D0219 10:34:26.473819000 140735887516544 test_config.cc:385]           test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0219 10:34:26.475175000 140735887516544 test_config.cc:385]           test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
xcodebuild: error: 'Tests.xcworkspace' does not exist.
Wed Feb 19 10:34:27 PST 2020 - Build settings from command line:
Wed Feb 19 10:34:27 PST 2020 -     HOST_PORT_LOCAL = localhost:17996
Wed Feb 19 10:34:27 PST 2020 -     HOST_PORT_LOCALSSL = localhost:25172
Wed Feb 19 10:34:27 PST 2020 -     HOST_PORT_REMOTE = grpc-test.sandbox.googleapis.com
Wed Feb 19 10:34:27 PST 2020 -
finish
jobs -p
date
EXIT TIME:  Wed Feb 19 10:34:27 PST 2020

2020-02-19 10:34:27,871 FAILED: mac-test-basictests [ret=66, pid=27977, time=473.9sec]
2020-02-19 10:34:27,872 FAILED: mac-test-basictests
2020-02-19 10:34:27,893 FAILED: Some tests failed
```

further up the log was:

```
Wed Feb 19 10:27:17 PST 2020 - INFO: Call stack for the definition of repository 'go_sdk' which is a _go_download_sdk (rule definition at /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl:53:20):
Wed Feb 19 10:27:17 PST 2020 -  - /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl:65:5
Wed Feb 19 10:27:17 PST 2020 -  - /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:13
Wed Feb 19 10:27:17 PST 2020 -  - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/bazel/grpc_extra_deps.bzl:36:5
Wed Feb 19 10:27:17 PST 2020 -  - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/WORKSPACE:11:1
Wed Feb 19 10:27:17 PST 2020 - WARNING: Download from https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 1f2ae0afcb7541a61e96926ed3749a2c7e32a8b53905121cc4c8b670fc367e93 but wanted 566d0b407f7d4aa5a1315988b562bbe4e9422a93ce2fbf27a664cddcb9a3e617
Wed Feb 19 10:27:17 PST 2020 - ERROR: An error occurred during the fetch of repository 'go_sdk':
Wed Feb 19 10:27:17 PST 2020 -    Traceback (most recent call last):
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 51
Wed Feb 19 10:27:17 PST 2020 - 		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 121, in _remote_sdk
Wed Feb 19 10:27:17 PST 2020 - 		ctx.download(url = urls, sha256 = sha256, output ...")
Wed Feb 19 10:27:17 PST 2020 - java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/go_sdk/go_sdk.tar.gz: Checksum was 1f2ae0afcb7541a61e96926ed3749a2c7e32a8b53905121cc4c8b670fc367e93 but wanted 566d0b407f7d4aa5a1315988b562bbe4e9422a93ce2fbf27a664cddcb9a3e617
Wed Feb 19 10:27:17 PST 2020 - ERROR: While resolving toolchains for target @bazel_tools//tools/cpp:compiler: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 51
Wed Feb 19 10:27:17 PST 2020 - 		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 121, in _remote_sdk
Wed Feb 19 10:27:17 PST 2020 - 		ctx.download(url = urls, sha256 = sha256, output ...")
Wed Feb 19 10:27:17 PST 2020 - java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/go_sdk/go_sdk.tar.gz: Checksum was 1f2ae0afcb7541a61e96926ed3749a2c7e32a8b53905121cc4c8b670fc367e93 but wanted 566d0b407f7d4aa5a1315988b562bbe4e9422a93ce2fbf27a664cddcb9a3e617
Wed Feb 19 10:27:17 PST 2020 - ERROR: While resolving configuation keys for @com_google_protobuf//:protoc: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 51
Wed Feb 19 10:27:17 PST 2020 - 		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 121, in _remote_sdk
Wed Feb 19 10:27:17 PST 2020 - 		ctx.download(url = urls, sha256 = sha256, output ...")
Wed Feb 19 10:27:17 PST 2020 - java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/go_sdk/go_sdk.tar.gz: Checksum was 1f2ae0afcb7541a61e96926ed3749a2c7e32a8b53905121cc4c8b670fc367e93 but wanted 566d0b407f7d4aa5a1315988b562bbe4e9422a93ce2fbf27a664cddcb9a3e617
Wed Feb 19 10:27:17 PST 2020 - ERROR: Analysis of target '@com_google_protobuf//:protoc' failed; build aborted: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 51
Wed Feb 19 10:27:17 PST 2020 - 		_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
Wed Feb 19 10:27:17 PST 2020 - 	File "/Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/io_bazel_rules_go/go/private/sdk.bzl", line 121, in _remote_sdk
Wed Feb 19 10:27:17 PST 2020 - 		ctx.download(url = urls, sha256 = sha256, output ...")
Wed Feb 19 10:27:17 PST 2020 - java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/fb29e378133afd959be023fae47df9ad/external/go_sdk/go_sdk.tar.gz: Checksum was 1f2ae0afcb7541a61e96926ed3749a2c7e32a8b53905121cc4c8b670fc367e93 but wanted 566d0b407f7d4aa5a1315988b562bbe4e9422a93ce2fbf27a664cddcb9a3e617
Wed Feb 19 10:27:17 PST 2020 - INFO: Elapsed time: 33.868s
Wed Feb 19 10:27:17 PST 2020 - INFO: 0 processes.
Wed Feb 19 10:27:17 PST 2020 - FAILED: Build did NOT complete successfully (11 packages loaded, 18 targets configured)
Wed Feb 19 10:27:17 PST 2020 - FAILED: Build did NOT complete successfully (11 packages loaded, 18 targets configured)
```

https://source.cloud.google.com/results/invocations/a8ad7401-71cb-4af9-8f59-f214ea8cf3f5/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_objc_macos_opt_native/tests

seen in PR: https://github.com/grpc/grpc/pull/21698

**Comment by gnossen** [comment]
I'm seeing this on the `1.28` branch. @muxi Is this something I should be worried about?

**Comment by muxi** [comment]
Could you paste the link?

**Comment by gnossen** [comment]
https://source.cloud.google.com/results/invocations/7da1c587-87c8-40e4-86f1-c0b586e8a7b8/log

Sorry about that.

Relevant line is

```
xcodebuild: error: 'Tests.xcworkspace' does not exist.
```

Similar to what @apolcyn posted above.

**Comment by muxi** [comment]
I don't think it is something to block the release. Very likely to be another infra craziness I need to deal with.

**Comment by gnossen** [comment]
Closing since this hasn't been seen since March.
