### ISSUE TITLE
cloud_to_cloud:ruby:aspnetcore_server:timeout_on_sleeping_server:tls flake

### ISSUE THREAD

**Issue by rmstar** [grpc/grpc#18523]
```
2019-03-26 12:05:24,993 /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 13:Received RST_STREAM with error code 2 (GRPC::Internal)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
	from src/ruby/pb/test/client.rb:461:in `each'
	from src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
	from src/ruby/pb/test/client.rb:763:in `call'
	from src/ruby/pb/test/client.rb:763:in `main'
	from src/ruby/pb/test/client.rb:768:in `<main>'
I, [2019-03-26T19:05:23.709421 #77]  INFO -- : ... connecting securely to localhost:32771
W, [2019-03-26T19:05:24.711003 #77]  WARN -- : bidi: read-loop failed
W, [2019-03-26T19:05:24.711090 #77]  WARN -- : 13:Received RST_STREAM with error code 2 (GRPC::Internal)
/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
src/ruby/pb/test/client.rb:461:in `each'
src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
src/ruby/pb/test/client.rb:763:in `call'
src/ruby/pb/test/client.rb:763:in `main'
src/ruby/pb/test/client.rb:768:in `<main>'
2019-03-26 12:05:24,993 FAILED: cloud_to_cloud:ruby:aspnetcore_server:timeout_on_sleeping_server:tls [ret=1, pid=20518, time=2.5sec]
```
https://source.cloud.google.com/results/invocations/6647903f-c025-43dd-a9db-66259a622e21/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

Seen on PR: #18381

**Comment by JamesNK** [comment]
I think this should be fixed with the latest version of grpc-dotnet

**Comment by JamesNK** [comment]
Comment on https://github.com/grpc/grpc-dotnet/issues/160 if it continues to be flaky.
