### ISSUE TITLE
Flake: csharp.Grpc.IntegrationTesting.ExternalDnsClientServerTest (StatusCode=Unavailable, Detail="DNS resolution failed")

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#18637]
This issue is specific to flakes in that test that have an RPC failure with `Status(StatusCode=Unavailable, Detail="DNS resolution failed")`

(differently from https://github.com/grpc/grpc/issues/18126)

Example failure log:

```
NUnitLite 3.10.1 (.NET Framework 4.5)
Copyright (c) 2018 Charlie Poole, Rob Prouse
Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601.65536
  CLR Version: 4.0.30319.42000
Test Files
    T:/src/github/grpc/workspace_csharp_windows_opt_native/src/csharp/Grpc.IntegrationTesting/bin/Release/net45/Grpc.IntegrationTesting.exe
Test Filters
    Test: Grpc.IntegrationTesting.ExternalDnsClientServerTest
=> Grpc.IntegrationTesting.ExternalDnsClientServerTest
D0329 15:51:36.710937 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "T:\src\github\grpc\workspace_csharp_windows_opt_native\src\csharp\Grpc.IntegrationTesting\bin\Release\net45\grpc_csharp_ext.x64.dll"
D0329 15:51:36.804687 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
=> Grpc.IntegrationTesting.ExternalDnsClientServerTest.EmptyUnary
running empty_unary
Errors, Failures and Warnings
1) Error : Grpc.IntegrationTesting.ExternalDnsClientServerTest.EmptyUnary
Grpc.Core.RpcException : Status(StatusCode=Unavailable, Detail="DNS resolution failed")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Testing.TestService.TestServiceClient.EmptyCall(Empty request, CallOptions options)
   at Grpc.Testing.TestService.TestServiceClient.EmptyCall(Empty request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.InteropClient.RunEmptyUnary(TestServiceClient client)
Run Settings
    Number of Test Workers: 1
    Work Directory: T:\src\github\grpc\workspace_csharp_windows_opt_native
    Internal Trace: Off
Test Run Summary
  Overall result: Failed
  Test Count: 1, Passed: 0, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2019-03-29 22:51:36Z
    End time: 2019-03-29 22:51:47Z
    Duration: 10.455 seconds
```

from https://source.cloud.google.com/results/invocations/5aa1ddd7-4ddf-448f-a195-9ececb0aec05/targets/github%2Fgrpc%2Fcsharp_windows_opt_native/tests

Described in more detail in https://github.com/grpc/grpc/issues/18126#issuecomment-479679713

**Comment by jtattermusch** [comment]
@apolcyn  I keep seeing this flake a lot on windows.

**Comment by apolcyn** [comment]
This should be fixed by https://github.com/grpc/grpc/pull/17688 - reviewer is out of office this week, and am waiting on that.

**Comment by jtattermusch** [comment]
@apolcyn  Any progress with the fix? I keep seeing this on my PRs regularly.
