### ISSUE TITLE
Remaining problems with building Bazel RBE issues under bazel 0.24

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#18642]
A few more problems to resolve to be able to build with bazel 0.24.

Problem 1:
https://source.cloud.google.com/results/invocations/dfb2fc60-ce40-4e4c-bd57-e1f69b05dd1e
```
$ ~/bazel_versions/bazel-0.24.0-linux-x86_64 --bazelrc=tools/remote_build/manual.bazelrc build --config=opt //test/...
INFO: Invocation ID: dfb2fc60-ce40-4e4c-bd57-e1f69b05dd1e
INFO: Streaming Build Event Protocol to https://source.cloud.google.com/results/invocations/dfb2fc60-ce40-4e4c-bd57-e1f69b05dd1e
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl:771:21: Traceback (most recent call last):
	File "/usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 761
		rule(implementation = _proto_compile_..., <3 more arguments>)
	File "/usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 770, in rule
		attr.label_list(allow_files = FileType([".proto"...))
	File "/usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 771, in attr.label_list
		FileType([".proto"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
```

Problem 2:
https://source.cloud.google.com/results/invocations/77bfffc6-3b44-4de6-82a1-7bc84f1d15b9
```
$ ~/bazel_versions/bazel-0.24.0-linux-x86_64 --bazelrc=tools/remote_build/manual.bazelrc build --config=opt //test/... --incompatible_disallow_filetype=false
INFO: Invocation ID: 77bfffc6-3b44-4de6-82a1-7bc84f1d15b9
INFO: Streaming Build Event Protocol to https://source.cloud.google.com/results/invocations/77bfffc6-3b44-4de6-82a1-7bc84f1d15b9
DEBUG: /usr/local/google/home/jtattermusch/github/grpc/bazel/grpc_python_deps.bzl:14:9: Building Python gRPC with bazel 23.0+ is disabled pending resolution of https://github.com/grpc/grpc/issues/18256.
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_github_bazelbuild_bazeltoolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:57:1: @com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8: no such attribute 'dynamic_runtime_libs' in 'cc_toolchain' rule
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_github_bazelbuild_bazeltoolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:57:1: @com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8: no such attribute 'static_runtime_libs' in 'cc_toolchain' rule
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_github_bazelbuild_bazeltoolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:87:1: @com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-armeabi-v7a: no such attribute 'dynamic_runtime_libs' in 'cc_toolchain' rule
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_github_bazelbuild_bazeltoolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:87:1: @com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-armeabi-v7a: no such attribute 'static_runtime_libs' in 'cc_toolchain' rule
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_github_bazelbuild_bazeltoolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:57:1: Target '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:compiler_deps' contains an error and its package is in error and referenced by '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8'
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_github_bazelbuild_bazeltoolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default/BUILD:57:1: Target '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:empty' contains an error and its package is in error and referenced by '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8'
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:8:1: every rule of type java_binary implicitly depends upon the target '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain', but this target could not be found because of: Target '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain' contains an error and its package is in error
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:8:1: Target '@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main' depends on toolchain '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8', which cannot be found: Target '@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8' contains an error and its package is in error'
ERROR: Analysis of target '//test/core/end2end:h2_uds_nosec_test@no_logging@poller=epoll1' failed; build aborted: Analysis failed
```

**Comment by jtattermusch** [comment]
CC @gnossen @nicolasnoble

**Comment by jtattermusch** [comment]
Problem 2 might be helped by https://github.com/grpc/grpc/pull/18280

**Comment by jtattermusch** [comment]
Btw, looks like we are currently able to build with bazel 0.23.2 (which might be good enough for windows RBE build).

**Comment by jtattermusch** [comment]
I think this was fixed by re-applying rules_proto changes in https://github.com/grpc/grpc/pull/18922

**Comment by jtattermusch** [comment]
Thanks @gnossen !
