### ISSUE TITLE
test handshake_server failure

### ISSUE THREAD

**Issue by yuangongji** [grpc/grpc#18758]
### What version of gRPC and what language are you using?
 version: 1.12.0
 language: c
### What operating system (Linux, Windows,...) and version?
 lsb_release -a:
 LSB Version:    n/a
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 12 (x86_64)
Release:        12
Codename:       n/a

### What runtime / compiler are you using (e.g. python version or version of gcc)
 python : 2.7.15
 gcc : 6.1.0

### What did you do?
git clone -b v1.12.0 https://github.com/grpc/grpc.git
git submodule update --init
make
tools/run_tests/run_tests.py -l c -x report.xml   #run all test case, get some fails
bins/opt/handshake_server GRPC_POLL_STRATEGY=epoll1  #run single test case, but not run
### What did you expect to see?
type the single test case "bins/opt/handshake_server GRPC_POLL_STRATEGY=epoll1" should run success.
 
### What did you see instead?
 type the single  test case "bins/opt/handshake_server GRPC_POLL_STRATEGY=epoll1" can not run.
Then I move the line 146、147 （SSL_load_error_strings(); OpenSSL_add_ssl_algorithms();） in file "test\core\handshake\server_ssl_common.cc" to the line 135、136，then type  
make handshake_server
bins/opt/handshake_server GRPC_POLL_STRATEGY=epoll1
I get this :
Unable to connect: Connection refused
Unable to connect: Connection refused
Unable to connect: Connection refused
Unable to connect: Connection refused
E0415 22:10:06.839884524   92046 server_ssl_common.cc:225]   Unexpected ALPN protocol preference
 
### Anything else we should know about your project / environment?
OpenSSL : 1.0.2j-fips

**Comment by yuangongji** [comment]
## Analysis of the failure of grpc's testcase "handshake_server"

### Software Info
version: 1.12.0  
language: c
### Environment
```bash
# lsb_release -a
LSB Version: n/a
Distributor ID: SUSE LINUX
Description: SUSE Linux Enterprise Server 12 (x86_64)
Release: 12
Codename: n/a
```
### Tools
python : 2.7.15  
gcc : 6.1.0  
openssl : OpenSSL 1.0.2j-fips  26 Sep 2016
### Steps
```bash
# git clone -b v1.12.0 https://github.com/grpc/grpc.git
# git submodule update --init
# make
# tools/run_tests/run_tests.py -l c -x report.xml 
# bins/opt/handshake_server GRPC_POLL_STRATEGY=epoll1
```
### Observation
1、Here is the backtrace of openssl's initialization when creating ssl server：
```bash
grpc-1.12.0 # gdb bins/opt/handshake_server GRPC_POLL_STRATEGY=epoll1
...
...
(gdb) b ssl_transport_security.cc:init_openssl
Breakpoint 1 at 0x4461f0: file src/core/tsi/ssl_transport_security.cc, line 142.
(gdb) r
Starting program: /data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-49.16.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: the debug information found in "/usr/lib/debug//lib64/libssl.so.1.0.0.debug" does not match "/lib64/libssl.so.1.0.0" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libcrypto.so.1.0.0.debug" does not match "/lib64/libcrypto.so.1.0.0" (CRC mismatch).

[New Thread 0x7ffff6846700 (LWP 126533)]
[New Thread 0x7ffff6045700 (LWP 126534)]
[New Thread 0x7ffff5844700 (LWP 126536)]
[Switching to Thread 0x7ffff5844700 (LWP 126536)]

Thread 4 "grpc_ssl_test" hit Breakpoint 1, init_openssl ()
    at src/core/tsi/ssl_transport_security.cc:142
142     static void init_openssl(void) {
Missing separate debuginfos, use: zypper install libopenssl1_0_0-debuginfo-1.0.2j-55.1.x86_64
(gdb) bt
#0  init_openssl () at src/core/tsi/ssl_transport_security.cc:142
#1  0x00007ffff72b6c03 in __pthread_once_slow () from /lib64/libpthread.so.0
#2  0x000000000044a349 in gpr_once_init (
    once=once@entry=0x6f0938 <g_init_openssl_once>,
    init_function=init_function@entry=0x4461f0 <init_openssl()>)
    at src/core/lib/gpr/sync_posix.cc:104
#3  0x0000000000446d17 in tsi_create_ssl_server_handshaker_factory_with_options (options=0x7ffff5843b70, factory=0x7fffe8001838)
    at src/core/tsi/ssl_transport_security.cc:1643
#4  0x000000000044725b in tsi_create_ssl_server_handshaker_factory_ex (
    pem_key_cert_pairs=0x7fffe8000990, num_key_cert_pairs=<optimized out>,
    pem_client_root_certs=<optimized out>,
    client_certificate_request=<optimized out>,
    cipher_suites=<optimized out>,
    alpn_protocols=alpn_protocols@entry=0x7fffe80008e0, num_alpn_protocols=2,
    factory=0x7fffe8001838) at src/core/tsi/ssl_transport_security.cc:1633
#5  0x0000000000440f16 in grpc_ssl_server_security_connector_create (
    gsc=0x7fffe8000920, sc=0x7ffff5843c58)
    at src/core/lib/security/security_connector/security_connector.cc:1121
#6  0x000000000043de58 in grpc_server_add_secure_http2_port (
    server=server@entry=0x7fffe8001650,
    addr=0x7fffe8000900 "127.0.0.1:28049", creds=creds@entry=0x7fffe8000920)
    at src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.cc:57
#7  0x000000000040629a in server_thread (arg=<optimized out>)
    at test/core/handshake/server_ssl_common.cc:95
#8  0x000000000044aeac in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>)
    at src/core/lib/gprpp/thd_posix.cc:105
#9  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at src/core/lib/gprpp/thd_posix.cc:108
```

2、When the testcase "test/core/handshake/server_ssl_common.cc" execute to the line 146, 3 possible errors may occur (randomly).  
 (1) double free or corruption
 ```bash
*** Error in `grpc-1.12.0/bins/opt/handshake_server': double free or corruption (!prev): 0x0000000000715cf0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x721af)[0x7ffff68b91af]
/lib64/libc.so.6(+0x779d6)[0x7ffff68be9d6]
/lib64/libc.so.6(+0x78723)[0x7ffff68bf723]
/lib64/libc.so.6(+0x7a980)[0x7ffff68c1980]
/lib64/libc.so.6(realloc+0x12f)[0x7ffff68c2daf]
/lib64/libcrypto.so.1.0.0(CRYPTO_realloc+0x49)[0x7ffff6c57d39]
/lib64/libcrypto.so.1.0.0(lh_insert+0x101)[0x7ffff6d0a561]
/lib64/libcrypto.so.1.0.0(+0x122b4a)[0x7ffff6d0cb4a]
/lib64/libcrypto.so.1.0.0(+0x12255b)[0x7ffff6d0c55b]
/lib64/libcrypto.so.1.0.0(ERR_load_FIPS_strings+0x2e)[0x7ffff6c5a1ce]
/lib64/libcrypto.so.1.0.0(ERR_load_crypto_strings+0x9a)[0x7ffff6d0deba]
/lib64/libssl.so.1.0.0(SSL_load_error_strings+0x9)[0x7ffff7086059]
/data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server[0x4065bb]
/data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server[0x40599f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ffff68676e5]
/data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server[0x406089]
======= Memory map: ========
00400000-004e6000 r-xp 00000000 ca:41 2836416                            /data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server
006e5000-006ea000 r--p 000e5000 ca:41 2836416                            /data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server
006ea000-006ee000 rw-p 000ea000 ca:41 2836416                            /data1/opensource_workspace/yuan/grpc-1.12.0/bins/opt/handshake_server
006ee000-00746000 rw-p 00000000 00:00 0                                  [heap]
7fffe8000000-7fffe8021000 rw-p 00000000 00:00 0
7fffe8021000-7fffec000000 ---p 00000000 00:00 0
7fffec000000-7fffec021000 rw-p 00000000 00:00 0
7fffec021000-7ffff0000000 ---p 00000000 00:00 0
7ffff0000000-7ffff0021000 rw-p 00000000 00:00 0
7ffff0021000-7ffff4000000 ---p 00000000 00:00 0
7ffff4e2d000-7ffff4e43000 r-xp 00000000 ca:02 1727473                    /usr/local/lib64/libgcc_s.so.1
7ffff4e43000-7ffff5042000 ---p 00016000 ca:02 1727473                    /usr/local/lib64/libgcc_s.so.1
7ffff5042000-7ffff5043000 r--p 00015000 ca:02 1727473                    /usr/local/lib64/libgcc_s.so.1
7ffff5043000-7ffff5044000 rw-p 00016000 ca:02 1727473                    /usr/local/lib64/libgcc_s.so.1
7ffff5044000-7ffff5045000 ---p 00000000 00:00 0
7ffff5045000-7ffff5845000 rw-p 00000000 00:00 0
7ffff5845000-7ffff5846000 ---p 00000000 00:00 0
7ffff5846000-7ffff6046000 rw-p 00000000 00:00 0
7ffff6046000-7ffff6047000 ---p 00000000 00:00 0
7ffff6047000-7ffff6847000 rw-p 00000000 00:00 0
7ffff6847000-7ffff69e1000 r-xp 00000000 ca:02 1264042                    /lib64/libc-2.22.so
7ffff69e1000-7ffff6be0000 ---p 0019a000 ca:02 1264042                    /lib64/libc-2.22.so
7ffff6be0000-7ffff6be4000 r--p 00199000 ca:02 1264042                    /lib64/libc-2.22.so
7ffff6be4000-7ffff6be6000 rw-p 0019d000 ca:02 1264042                    /lib64/libc-2.22.so
7ffff6be6000-7ffff6bea000 rw-p 00000000 00:00 0
7ffff6bea000-7ffff6e17000 r-xp 00000000 ca:02 1264125                    /lib64/libcrypto.so.1.0.0
7ffff6e17000-7ffff7017000 ---p 0022d000 ca:0··2 1264125                    /lib64/libcrypto.so.1.0.0
7ffff7017000-7ffff7032000 r--p 0022d000 ca:02 1264125                    /lib64/libcrypto.so.1.0.0
7ffff7032000-7ffff7040000 rw-p 00248000 ca:02 1264125                    /lib64/libcrypto.so.1.0.0
7ffff7040000-7ffff7044000 rw-p 00000000 00:00 0
7ffff7044000-7ffff70a5000 r-xp 00000000 ca:02 1264126                    /lib64/libssl.so.1.0.0
7ffff70a5000-7ffff72a5000 ---p 00061000 ca:02 1264126                    /lib64/libssl.so.1.0.0
7ffff72a5000-7ffff72a9000 r--p 00061000 ca:02 1264126                    /lib64/libssl.so.1.0.0
7ffff72a9000-7ffff72b0000 rw-p 00065000 ca:02 1264126                    /lib64/libssl.so.1.0.0
7ffff72b0000-7ffff72c8000 r-xp 00000000 ca:02 1264072                    /lib64/libpthread-2.22.so
7ffff72c8000-7ffff74c7000 ---p 00018000 ca:02 1264072                    /lib64/libpthread-2.22.so
7ffff74c7000-7ffff74c8000 r--p 00017000 ca:02 1264072                    /lib64/libpthread-2.22.so
7ffff74c8000-7ffff74c9000 rw-p 00018000 ca:02 1264072                    /lib64/libpthread-2.22.so
7ffff74c9000-7ffff74cd000 rw-p 00000000 00:00 0
7ffff74cd000-7ffff75c9000 r-xp 00000000 ca:02 1264050                    /lib64/libm-2.22.so
7ffff75c9000-7ffff77c8000 ---p 000fc000 ca:02 1264050                    /lib64/libm-2.22.so
7ffff77c8000-7ffff77c9000 r--p 000fb000 ca:02 1264050                    /lib64/libm-2.22.so
7ffff77c9000-7ffff77ca000 rw-p 000fc000 ca:02 1264050                    /lib64/libm-2.22.so
7ffff77ca000-7ffff77d1000 r-xp 00000000 ca:02 1264076                    /lib64/librt-2.22.so
7ffff77d1000-7ffff79d0000 ---p 00007000 ca:02 1264076                    /lib64/librt-2.22.so
7ffff79d0000-7ffff79d1000 r--p 00006000 ca:02 1264076                    /lib64/librt-2.22.so
7ffff79d1000-7ffff79d2000 rw-p 00007000 ca:02 1264076                    /lib64/librt-2.22.so
7ffff79d2000-7ffff79d4000 r-xp 00000000 ca:02 1264048                    /lib64/libdl-2.22.so
7ffff79d4000-7ffff7bd4000 ---p 00002000 ca:02 1264048                    /lib64/libdl-2.22.so
7ffff7bd4000-7ffff7bd5000 r--p 00002000 ca:02 1264048                    /lib64/libdl-2.22.so
7ffff7bd5000-7ffff7bd6000 rw-p 00003000 ca:02 1264048                    /lib64/libdl-2.22.so
7ffff7bd6000-7ffff7bdb000 r-xp 00000000 ca:02 1266846                    /lib64/libachk.so
7ffff7bdb000-7ffff7dda000 ---p 00005000 ca:02 1266846                    /lib64/libachk.so
7ffff7dda000-7ffff7ddb000 r--p 00004000 ca:02 1266846                    /lib64/libachk.so
7ffff7ddb000-7ffff7ddc000 rw-p 00005000 ca:02 1266846                    /lib64/libachk.so
7ffff7ddc000-7ffff7dfd000 r-xp 00000000 ca:02 1264034                    /lib64/ld-2.22.so
7ffff7f14000-7ffff7f49000 r--s 00000000 00:13 19831                      /run/nscd/passwd
7ffff7f69000-7ffff7f9e000 r--s 00000000 00:13 19833                      /run/nscd/dbGT2ET5 (deleted)
7ffff7f9e000-7ffff7fa1000 rw-p 00000000 00:00 0
7ffff7fa1000-7ffff7fa4000 r--p 00000000 ca:02 1717401                    /usr/local/lib/libz.so.1.2.11
7ffff7fa4000-7ffff7fb6000 r-xp 00003000 ca:02 1717401                    /usr/local/lib/libz.so.1.2.11
7ffff7fb6000-7ffff7fbc000 r--p 00015000 ca:02 1717401                    /usr/local/lib/libz.so.1.2.11
7ffff7fbc000-7ffff7fbd000 ---p 0001b000 ca:02 1717401                    /usr/local/lib/libz.so.1.2.11
7ffff7fbd000-7ffff7fbe000 r--p 0001b000 ca:02 1717401                    /usr/local/lib/libz.so.1.2.11
7ffff7fbe000-7ffff7fbf000 rw-p 0001c000 ca:02 1717401                    /usr/local/lib/libz.so.1.2.11
7ffff7fbf000-7ffff7fc0000 rw-p 00000000 00:00 0
7ffff7fc0000-7ffff7fc3000 r--p 00000000 ca:02 1720129                    /usr/local/lib/libcares.so.2.2.0
7ffff7fc3000-7ffff7fcf000 r-xp 00003000 ca:02 1720129                    /usr/local/lib/libcares.so.2.2.0
7ffff7fcf000-7ffff7fd2000 r--p 0000f000 ca:02 1720129                    /usr/local/lib/libcares.so.2.2.0
7ffff7fd2000-7ffff7fd3000 r--p 00011000 ca:02 1720129                    /usr/local/lib/libcares.so.2.2.0
7ffff7fd3000-7ffff7fd4000 rw-p 00012000 ca:02 1720129                    /usr/local/lib/libcares.so.2.2.0
7ffff7fd4000-7ffff7fd5000 rw-p 00000000 00:00 0
7ffff7ff4000-7ffff7ff7000 rw-p 00000000 00:00 0
7ffff7ff7000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00020000 ca:02 1264034                    /lib64/ld-2.22.so
7ffff7ffd000-7ffff7ffe000 rw-p 00021000 ca:02 1264034                    /lib64/ld-2.22.so
7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Thread 1 "handshake_serve" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7f9e800 (LWP 126528)]
0x00007ffff687b8d7 in raise () from /lib64/libc.so.6
```

（2）Segmentation fault error：
```bash
grpc-1.12.0 # ./bins/opt/handshake_server
Segmentation fault (core dumped)
```

（3）Hang up with no message：
 ```bash
grpc-1.12.0 # ./bins/opt/handshake_server
        --> cursor will stop here
```

### Analysis
The source code of grpc uses *pthread_once* to make sure that openssl is initialized only once. Here are the related function calls at line 1515 and 1643 of "src/core/tsi/ssl_transport_security.cc":
```c
gpr_once_init(&g_init_openssl_once, init_openssl);
```
the function *gpr_once_init* is defined in "src/core/lib/gpr/sync_posix.cc"：
```c
void gpr_once_init(gpr_once* once, void (*init_function)(void)) {
  GPR_ASSERT(pthread_once(once, init_function) == 0);
}
```
initialize ssl server at line 142 in the testcase "test/core/handshake/server_ssl_common.cc":
```c
grpc_core::Thread thd("grpc_ssl_test", server_thread, &port, &ok);
```
initialize openssl at line 146 and 167 within the same file：
```c
SSL_load_error_strings();
OpenSSL_add_ssl_algorithms();
```
According to the analysis above, initializing openssl too many times is what leads to this error and it happens only when the interval of initializations happens to be very short. Here is the discussion about repeatedly initializing openssl: http://openssl.6102.n7.nabble.com/calling-SSL-library-init-multiple-times-td4111.html

### Verification
The following verifying code can reproduce this problem, with the same outcome(3 randomly appeared errors and associated error messages):
```c
#include <pthread.h>
#include <openssl/ssl.h>
#include <openssl/err.h>

void *server_thread(void *arg)
{
    SSL_load_error_strings();
    SSL_library_init();
    pthread_exit((void *)0);
}
int main()
{
    pthread_t tid;
    printf("OPENSSL_VERSION_TEXT: %s\n", OPENSSL_VERSION_TEXT);
    pthread_create(&tid, NULL, server_thread, NULL);
    SSL_load_error_strings();
    SSL_library_init();
    pthread_join(tid, NULL);
    return 0;
}
```

the version of output openssl is 1.0.2j-fips。

### Solution
Since openssl only needs to be initialized once in a single process before it is called, we can delete the second initialization code at line 146, 147 of the file "test/core/handshake/server_ssl_common.cc".
```bash
146		// SSL_load_error_strings();
147		// OpenSSL_add_ssl_algorithms();
```
the patch files are
```patch
--- server_ssl_common_new.cc    2019-04-28 12:05:27.279720516 +0800
+++ server_ssl_common.cc        2019-04-28 12:05:29.000000000 +0800
@@ -143,8 +143,8 @@
   GPR_ASSERT(ok);
   thd.Start();

-  SSL_load_error_strings();
-  OpenSSL_add_ssl_algorithms();
+
+

   const SSL_METHOD* method = TLSv1_2_client_method();
   SSL_CTX* ctx = SSL_CTX_new(method);
```
Or, we can put a time interval, let's say 2 seconds, between two initializations:
```bash
145		sleep(2);
```
the patch files are:
```patch
--- server_ssl_common_new.cc    2019-04-28 12:05:27.279720516 +0800
+++ server_ssl_common.cc        2019-04-28 14:22:33.000000000 +0800
@@ -142,7 +142,7 @@
   grpc_core::Thread thd("grpc_ssl_test", server_thread, &port, &ok);
   GPR_ASSERT(ok);
   thd.Start();
-
+  sleep(2);
   SSL_load_error_strings();
   OpenSSL_add_ssl_algorithms();
```

**Comment by sheenaqotj** [comment]
Is this related to https://github.com/grpc/grpc/issues/18900?

**Comment by vjpai** [comment]
I'm taking a crack at #18900 and will post a followup here also

**Comment by vjpai** [comment]
Does #20176 solve this problem? Can anyone check?

**Comment by vjpai** [comment]
I'm going to close this issue but we can reopen if it arises again.
