### ISSUE TITLE
csharp_linux_dbg_native_default_coreclr csharp.Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#18812]
https://source.cloud.google.com/results/invocations/8b1a406c-8edf-438b-8dec-f11fbddbdf7c/targets/github%2Fgrpc%2Fcsharp_linux_dbg_native_default_coreclr/tests

```
NUnitLite 3.10.1 (.NET Standard 2.0)
Copyright (c) 2018 Charlie Poole, Rob Prouse
Runtime Environment
   OS Version: Linux 4.15.16-041516-generic #201804080932 SMP Sun Apr 8 13:36:35 UTC 2018
  CLR Version: 4.0.30319.42000
Test Files
    /var/local/git/grpc/src/csharp/Grpc.Tools.Tests/bin/Debug/netcoreapp2.1/Grpc.Tools.Tests.dll
Test Filters
    Test: Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileTwoFiles
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Cpp")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("CSharp")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Java")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Javanano")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Js")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Objc")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Php")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Python")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithOptions("Ruby")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.CompileWithProtoPaths
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectoryArgumentsSlashTrimmed
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases(".",".")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("/","/")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("//","/")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("/foo/","/foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("/foo","/foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("foo/","foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("foo//","foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("foo/\\","foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("foo\\/","foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("C:\\foo","C:\\foo")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("C:","C:")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("C:\\","C:\\")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.DirectorySlashTrimmingCases("C:\\\\","C:\\")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.ErrorsParsed("../Protos/greet.proto(14) : error in column=10: \"name\" is already defined in \"Greet.HelloRequest\".","../Protos/greet.proto",14,10,"\"name\" is already defined in \"Greet.HelloRequest\".")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.ErrorsParsed("../Protos/greet.proto: Import \"google / protobuf / empty.proto\" was listed twice.","../Protos/greet.proto",0,0,"Import \"google / protobuf / empty.proto\" was listed twice.")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.ErrorsParsed("../Protos/greet.proto(19) : warning in column=5 : warning : When enum name is stripped and label is PascalCased (Zero) this value label conflicts with Zero.",null,0,0,null)
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.ErrorsParsed("../Protos/greet.proto: warning: Import google/protobuf/empty.proto but not used.",null,0,0,null)
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.GenerateGrpc
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.GenerateGrpcWithOptions
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.GenerateGrpcWithOutDir
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.MinimalCompile
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.OutputDependencyFile
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.OutputDependencyWithProtoDepDir
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.RequiredAttributePresentOnProperty("Protobuf")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.RequiredAttributePresentOnProperty("Generator")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.RequiredAttributePresentOnProperty("OutputDir")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.WarningsParsed("../Protos/greet.proto(19) : warning in column=5 : warning : When enum name is stripped and label is PascalCased (Zero) this value label conflicts with Zero.","../Protos/greet.proto",19,5,"warning : When enum name is stripped and label is PascalCased (Zero) this value label conflicts with Zero.")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.WarningsParsed("../Protos/greet.proto: warning: Import google/protobuf/empty.proto but not used.","../Protos/greet.proto",0,0,"Import google/protobuf/empty.proto but not used.")
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.WarningsParsed("../Protos/greet.proto(14) : error in column=10: \"name\" is already defined in \"Greet.HelloRequest\".",null,0,0,null)
=> Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.WarningsParsed("../Protos/greet.proto: Import \"google / protobuf / empty.proto\" was listed twice.",null,0,0,null)
Errors, Failures and Warnings
1) Error : Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.ErrorsParsed("../Protos/greet.proto(14) : error in column=10: \"name\" is already defined in \"Greet.HelloRequest\".","../Protos/greet.proto",14,10,"\"name\" is already defined in \"Greet.HelloRequest\".")
System.Text.RegularExpressions.RegexMatchTimeoutException : The RegEx engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.
   at System.Text.RegularExpressions.RegexRunner.DoCheckTimeout()
   at Go2(RegexRunner )
   at System.Text.RegularExpressions.CompiledRegexRunner.Go()
   at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.Regex.Match(String input, Int32 startat)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Grpc.Tools.ProtoCompile.LogEventsFromTextOutput(String singleLine, MessageImportance messageImportance) in /var/local/git/grpc/src/csharp/Grpc.Tools/ProtoCompile.cs:line 520
   at Grpc.Tools.Tests.ProtoCompileBasicTest.ProtoCompileTestable.ExecuteTool(String pathToTool, String response, String commandLine) in /var/local/git/grpc/src/csharp/Grpc.Tools.Tests/ProtoCompileBasicTest.cs:line 53
   at Microsoft.Build.Utilities.ToolTask.Execute() in E:\A\_work\82\s\src\Utilities\ToolTask.cs:line 1655
   at Grpc.Tools.ProtoCompile.Execute() in /var/local/git/grpc/src/csharp/Grpc.Tools/ProtoCompile.cs:line 537
   at Grpc.Tools.Tests.ProtoCompileCommandLineGeneratorTest.ErrorsParsed(String stderr, String file, Int32 line, Int32 col, String message) in /var/local/git/grpc/src/csharp/Grpc.Tools.Tests/ProtoCompileCommandLineGeneratorTest.cs:line 256
Run Settings
    Number of Test Workers: 1
    Work Directory: /var/local/git/grpc
    Internal Trace: Off
Test Run Summary
  Overall result: Failed
  Test Count: 42, Passed: 41, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2019-04-18 00:19:28Z
    End time: 2019-04-18 00:19:31Z
    Duration: 2.873 seconds
```

**Comment by jtattermusch** [comment]
This is easily reproduces locally with 
`tools/run_tests/run_tests.py -l csharp -c dbg -r Grpc.Tools.Tests.ProtoCompileCommandLineGenerator --compiler coreclr  -n 250 -j 30`

**Comment by jtattermusch** [comment]
Should be fixed by https://github.com/grpc/grpc/pull/19259
