### ISSUE TITLE
TEST FAILURE: cloud_to_cloud:dart:aspnetcore_server:status_code_and_message:tls

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#18843]
```
2019-04-23 18:13:32,575 START: cloud_to_cloud:php7:aspnetcore_server:cancel_after_begin:tls
2019-04-23 18:13:32,580 WAITING: ETA 216.1 sec; 1140 queued, 12 jobs running, 614 complete, 0 failed (load 12.00) next: cloud_to_cloud:php7:aspnetcore_server:cancel_after_first_response:tls @ 1.00 cpu
2019-04-23 18:13:32,595 Unhandled exception:
Received incorrect status: gRPC Error (2, test%20status%20message).
#0      Tester.statusCodeAndMessage (package:interop/src/client.dart:1016:9)
<asynchronous suspension>
#1      Tester.runTestCase (package:interop/src/client.dart:150:16)
<asynchronous suspension>
#2      Tester.runTest (package:interop/src/client.dart:109:11)
<asynchronous suspension>
#3      main (file:///var/local/git/grpc-dart/interop/bin/client.dart:107:20)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
2019-04-23 18:13:32,595 FAILED: cloud_to_cloud:dart:aspnetcore_server:status_code_and_message:tls [ret=255, pid=14723, time=9.0sec]
2019-04-23 18:13:32,596 START: cloud_to_cloud:php7:aspnetcore_server:cancel_after_first_response:tls
2019-04-23 18:13:32,601 WAITING: ETA 215.6 sec; 1139 queued, 12 jobs running, 615 complete, 1 failed (load 12.00) next: cloud_to_cloud:php7:aspnetcore_server:timeout_on_sleeping_server:tls @ 1.00 cpu
2019-04-23 18:13:32,618 PASSED: cloud_to_cloud:dart:aspnetcore_server:ping_pong:tls [time=9.6sec, retries=0:0]
2019-04-23 18:13:32,619 START: cloud_to_cloud:php7:aspnetcore_server:timeout_on_sleeping_server:tls
2019-04-23 18:13:32,630 WAITING: ETA 215.2 sec; 1138 queued, 12 jobs running, 616 complete, 1 failed (load 12.00) next: 
```

https://source.cloud.google.com/results/invocations/58c894d9-4c77-41bf-8ee2-99810cff266c/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

**Comment by AspirinSJL** [comment]
This seems failing 100% now.

**Comment by jtattermusch** [comment]
I suspect this could have been broken by https://github.com/grpc/grpc-dotnet/pull/216
First failure is https://source.cloud.google.com/results/invocations/68b8bc8d-2b93-41bf-96ec-97086bbf0752/targets, which coincides with merging the PR.
