### ISSUE TITLE
Bazel RBE build broken on master with bazel 0.25

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#18947]
The build complains with the newly released bazel 0.25 (it works with 0.24.x)

```
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/io_opencensus_cpp/opencensus/copts.bzl:24:1: file '@com_google_absl//absl:copts/configure_copts.bzl' does not contain symbol 'GCC_FLAGS'
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/io_opencensus_cpp/opencensus/copts.bzl:37:35: Traceback (most recent call last):
	File "/usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/io_opencensus_cpp/opencensus/copts.bzl", line 36
		select({"//opencensus:llvm_compiler": (...)})
	File "/usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/io_opencensus_cpp/opencensus/copts.bzl", line 37, in select
		LLVM_FLAGS
global variable 'LLVM_FLAGS' is referenced before assignment.
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/io_opencensus_cpp/opencensus/copts.bzl:42:14: global variable 'DEFAULT_COPTS' is referenced before assignment.
INFO: An error occurred during the fetch of repository 'remote_java_tools_linux'
INFO: Call stack for the definition of repository 'remote_java_tools_linux':
 - /DEFAULT.WORKSPACE.SUFFIX:208:1
INFO: An error occurred during the fetch of repository 'remotejdk11_linux'
INFO: Call stack for the definition of repository 'remotejdk11_linux':
 - /DEFAULT.WORKSPACE.SUFFIX:178:1
INFO: An error occurred during the fetch of repository 'boringssl'
INFO: Call stack for the definition of repository 'boringssl':
 - /usr/local/google/home/jtattermusch/github/grpc/bazel/grpc_deps.bzl:110:9
 - /usr/local/google/home/jtattermusch/github/grpc/WORKSPACE:7:1
INFO: An error occurred during the fetch of repository 'com_github_twisted_twisted'
INFO: Call stack for the definition of repository 'com_github_twisted_twisted':
 - /usr/local/google/home/jtattermusch/github/grpc/bazel/grpc_deps.bzl:236:9
 - /usr/local/google/home/jtattermusch/github/grpc/WORKSPACE:9:1
INFO: Repository 'com_github_twisted_twisted' used the following cache hits instead of downloading the corresponding file.
 * Hash 'ca17699d0d62eafc5c28daf2c7d0a18e62ae77b4137300b6c7d7868b39b06139' for https://github.com/twisted/twisted/archive/twisted-17.5.0.zip
If the definition of 'com_github_twisted_twisted' was updated, verify that the hashes were also updated.
ERROR: /usr/local/google/home/jtattermusch/github/grpc/bazel/grpc_deps.bzl:104:5: error loading package '@io_opencensus_cpp//opencensus/stats': Extension file 'opencensus/copts.bzl' has errors and referenced by '//external:opencensus-stats-test'
ERROR: Analysis of target '//test/cpp/server/load_reporter:lb_load_reporter_test@poller=poll' failed; build aborted: Analysis failed
INFO: Elapsed time: 62.749s
INFO: 0 processes.
INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/06994460-def5-496a-ad84-6a178528c440
FAILED: Build did NOT complete successfully (100 packages loaded, 7333 targets configured)
    currently loading: @io_opencensus_cpp//opencensus/stats ... (2 packages)
```

https://source.cloud.google.com/results/invocations/06994460-def5-496a-ad84-6a178528c440

**Comment by jtattermusch** [comment]
CC @gnossen  @nicolasnoble

**Comment by gnossen** [comment]
Potentially related? https://github.com/census-instrumentation/opencensus-cpp/issues/304

**Comment by AustinSchuh** [comment]
At least for me, updating to the latest opencensus-cpp fixed the opencensus related problem.

**Comment by jtattermusch** [comment]
We only support bazel 1.0+
