### ISSUE TITLE
Macos build flakes - fatal: Not a valid object name origin/null

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#18968]
This error was seen on two different test suites that run on macos:

```
++ ln -s /tmpfs/DerivedData /Users/kbuilder/Library/Developer/Xcode/DerivedData
++ ln -sf /usr/local/bin/phpunit-5.7 /usr/local/bin/phpunit
+ tools/run_tests/run_tests_matrix.py -f basictests macos opt --exclude objc --internal_ci -j 1 --inner_jobs 4 --max_time=3600 --filter_pr_tests --base_branch origin/null
fatal: Not a valid object name origin/null
IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment or into subworkspaces.
Looking for irrelevant tests to skip...
Finding file differences between gRPC origin/null branch and pull request...
Traceback (most recent call last):
  File "tools/run_tests/run_tests_matrix.py", line 564, in <module>
    relevant_jobs = filter_tests(jobs, args.base_branch)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/tools/run_tests/python_utils/filter_pull_request_tests.py", line 184, in filter_tests
    changed_files = _get_changed_files(base_branch)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/tools/run_tests/python_utils/filter_pull_request_tests.py", line 128, in _get_changed_files
    "HEAD"]).rstrip()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'merge-base', 'origin/null', 'HEAD']' returned non-zero exit status 128
+ FAILED=true
+ ps aux
```

https://source.cloud.google.com/results/invocations/3b82fe6a-f4be-44bc-b410-e69221beb29d/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_opt/log

https://source.cloud.google.com/results/invocations/3d5be068-23ea-472f-8c29-955a32119961/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_objc_dbg/log

**Comment by jtattermusch** [comment]
the nonsensical "origin/null"  base branch is coming from https://github.com/grpc/grpc/blob/f95fe7e5484367ce806b60ce94135da3d2f71e22/tools/internal_ci/helper_scripts/prepare_build_macos_rc#L31

**Comment by gnossen** [comment]
I just saw eight instances of this on a single PR. Any idea what the root cause is? Is this a flake on Github's end? Or is our json parsing not smart enough?

**Comment by gnossen** [comment]
I [instrumented the setup scripts](https://github.com/grpc/grpc/pull/19112) and can confirm that github API rate limiting is the problem:
```
++ echo 'PR info did not contain the base ref.'
PR info did not contain the base ref.
++ echo '{
  "message": "API rate limit exceeded for 108.177.31.30. (But here'\''s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}'
{
  "message": "API rate limit exceeded for 108.177.31.30. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
