### ISSUE TITLE
FAILED: cloud_to_cloud:nodepurejs:java_server:server_streaming:tls

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#18967]
This seen in cloud to cloud:

```
2019-05-06 14:20:23,925 WAITING: ETA 254.8 sec; 1519 queued, 12 jobs running, 235 complete, 0 failed (load 12.00) next: cloud_to_cloud:php:java_server:empty_stream:tls @ 1.00 cpu
2019-05-06 14:20:24,106 (node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:194) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:161:38)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
assert.js:85
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- 1
+ 4
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:167:12)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-05-06 14:20:24,106 FAILED: cloud_to_cloud:nodepurejs:java_server:server_streaming:tls [ret=1, pid=12364, time=1.7sec]
```

https://source.cloud.google.com/results/invocations/d1cec282-0a5b-4165-8994-6455ff4080c4/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

**Comment by apolcyn** [comment]
seen in https://github.com/grpc/grpc/pull/18964

**Comment by apolcyn** [comment]
This seen in cloud to prod against both servers:

```
2019-05-06 14:21:39,289 WAITING: ETA 48.4 sec; 242 queued, 12 jobs running, 224 complete, 1 failed (load 12.00) next: cloud_to_prod:dart:gateway_v4:ping_pong:tls @ 1.00 cpu
2019-05-06 14:21:39,393 (node:194) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- 2653
+ 9
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:162:12)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:194) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- 58979
+ 9
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:162:12)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStreamImpl.Readable.push (_stream_readable.js:220:10)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/call.js:52:21)
    at Http2CallStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Http2CallStream.Readable.push (_stream_readable.js:220:10)
(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
assert.js:85
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- 1
+ 4
    at ClientReadableStreamImpl.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:167:12)
    at ClientReadableStreamImpl.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-05-06 14:21:39,393 FAILED: cloud_to_prod:nodepurejs:gateway_v4:server_streaming:tls [ret=1, pid=10098, time=1.8sec]
```

https://source.cloud.google.com/results/invocations/9a98bd9a-4d34-4125-a1c0-1a0e1b5fbd58/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

**Comment by gnossen** [comment]
Bump.

**Comment by gnossen** [comment]
@murgatroid99 @nicolasnoble Any ideas?

**Comment by jtattermusch** [comment]
This has been failing consistently on master for a while now. It's also failing on all pull requests.
@nicolasnoble  @murgatroid99  can we please fix ASAP?

Most recent failures for interop_to_prod
https://source.cloud.google.com/results/invocations/3465880d-84ee-4ea2-ba70-369e81651aeb/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/a56b72b2-7598-46ac-920a-68ee546f4189/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/5985d9bb-ac06-4fa8-9b1c-e965d2b0b1bd/targets/github%2Fgrpc%2Finterop_test/tests

Most recent failures for interop_to_cloud
https://source.cloud.google.com/results/invocations/2eaa3e5b-b011-43cc-bf78-a59c3af638d4/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/c1c2361a-cf52-45ac-8a92-ef805e9b93d4/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/968f566a-cbcd-4f8d-82d5-8051caf8917a/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by jtattermusch** [comment]
Seems fixed now.
