### ISSUE TITLE
System.AccessViolationException in BatchContextSafeHandle.Recycle

### ISSUE THREAD

**Issue by adamreeve** [grpc/grpc#19020]
### What version of gRPC and what language are you using?

1.16.0 with C# 
 
### What operating system (Linux, Windows,...) and version?

Windows Server 2016
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

.NET framework 4.6.1
 
### What did you do?

I have a gRPC client that makes two streaming calls concurrently. Before this exception was thrown, an error response was received from one of the calls so the other had been cancelled using a cancellation token. Both of the `AsyncServerStreamingCall<T>` instances as well as the client instance had been disposed before the exception was thrown.
 
### What did you expect to see? 

The gRPC client and streaming calls should have been cleanly disposed without any errors.
 
### What did you see instead?

An AccessViolationException was thrown with the following stack trace:

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Grpc.Core.Internal.BatchContextSafeHandle.Recycle() in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\BatchContextSafeHandle.cs:line 121
   at Grpc.Core.Internal.BatchContextSafeHandle.Grpc.Core.Internal.IOpCompletionCallback.OnComplete(Boolean success) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\BatchContextSafeHandle.cs:line 153
   at Grpc.Core.Internal.GrpcThreadPool.RunCompletionQueueEventCallback(IOpCompletionCallback callback, Boolean success) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\GrpcThreadPool.cs:line 232
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
``` 

The 121 line number might be misleading, it looks like the access violation probably occurred inside grpcsharp_batch_context_reset.
 
### Anything else we should know about your project / environment?

This code has been running without any problem in production for weeks, including receiving errors when processing streaming calls and reconnecting successfully. I haven't been able to reproduce the bug since so it looks like there's a race condition somewhere.

**Comment by a11r** [comment]
There is no way to tell if the memory corruption is happening in the application code or down in the gRPC code. The only way to proceed would be to have a usable reproduction of the issue.
