### ISSUE TITLE
C# build failing for unclear reason

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#19051]
https://source.cloud.google.com/results/invocations/afc994a2-46fb-4a02-87e9-377c0c657f3d/targets

End of relevant log output:

```

Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:15.38
2019-05-15 17:03:47,245 FAILED: tools/run_tests/helper_scripts/build_csharp.sh [ret=134, pid=7043, time=16.1sec]
2019-05-15 17:03:47,245 FAILED: Some tests failed
  adding: reports/ (stored 0%)
+ DOCKER_EXIT_CODE=1
++ mktemp
+ TEMP_REPORTS_ZIP=/tmpfs/tmp/tmp.4SzwJ3J9Mx
+ docker cp run_tests_ce16a783-f198-49a1-be8c-4291e7191955:/var/local/git/grpc/reports.zip /tmpfs/tmp/tmp.4SzwJ3J9Mx
+ unzip -o /tmpfs/tmp/tmp.4SzwJ3J9Mx -d /tmpfs/src/github/grpc
Archive:  /tmpfs/tmp/tmp.4SzwJ3J9Mx
   creating: /tmpfs/src/github/grpc/reports/
+ rm -f /tmpfs/tmp/tmp.4SzwJ3J9Mx
+ docker rm -f run_tests_ce16a783-f198-49a1-be8c-4291e7191955
run_tests_ce16a783-f198-49a1-be8c-4291e7191955
+ exit 1
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1540, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 1
2019-05-15 10:03:50,457 FAILED: run_tests_csharp_linux_opt_native [ret=1, pid=8980, time=147.7sec]
```

**Comment by AspirinSJL** [comment]
Seems transient. Closing.
