### ISSUE TITLE
gem install ruby fails if the entire grpc source tree is not present

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc#1908]
```
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

    /Users/tbetbetbe/.rbenv/versions/2.2.0/bin/ruby -r ./siteconf20150604-38023-r9giku.rb extconf.rb --with-grpc-dir=/usr/local
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/tbetbetbe/.rbenv/versions/2.2.0/bin/$(RUBY_BASE_NAME)
extconf.rb:55:in `join': no implicit conversion of nil into String (TypeError)
	from extconf.rb:55:in `<main>'
```

**Comment by nicolasnoble** [comment]
Bah! And here's why we need better end-to-end packages testing :-)
