### ISSUE TITLE
grpc::Status coredump when call destructor

### ISSUE THREAD

**Issue by huqianghuq** [grpc/grpc#19165]
### What version of gRPC and what language are you using?
 
* gRPC version: v1.17.1
* Language: C++
 
### What operating system (Linux, Windows,...) and version?

* Linux: Fedora 29
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
* gcc 8.2.0
 
### What did you do?

* i'm use grpc to sync data
 
### What did you expect to see?
 
* Don't abort.
 
### What did you see instead?

* coredump after a while

```log
#0  0x00007fa9a0fb80b9 in free () from /lib64/libc.so.6
#1  0x000000000061bdfc in __gnu_cxx::new_allocator<char>::deallocate (this=0x7fa987b61d20, 
    __p=0x31520d134ee9d8d <Address 0x31520d134ee9d8d out of bounds>)
    at /usr/local/include/c++/8.2.0/ext/new_allocator.h:125
#2  0x0000000000609c05 in std::allocator_traits<std::allocator<char> >::deallocate (__a=..., 
    __p=0x31520d134ee9d8d <Address 0x31520d134ee9d8d out of bounds>, __n=6717686389133503647)
    at /usr/local/include/c++/8.2.0/bits/alloc_traits.h:462
#3  0x00000000005f6053 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (this=0x7fa987b61d20, __size=6717686389133503646)
    at /usr/local/include/c++/8.2.0/bits/basic_string.h:226
#4  0x00000000005f4742 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7fa987b61d20) at /usr/local/include/c++/8.2.0/bits/basic_string.h:221
#5  0x00000000005cfb5c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x7fa987b61d20, __in_chrg=<optimized out>)
    at /usr/local/include/c++/8.2.0/bits/basic_string.h:657
#6  0x00000000005c3c2a in grpc::Status::~Status (this=0x7fa987b61cf8, __in_chrg=<optimized out>)
    at /usr/local/include/grpcpp/impl/codegen/status.h:31
#7  0x00000000005c53c2 in grpc::internal::InterceptorBatchMethodsImpl::~InterceptorBatchMethodsImpl (
    this=0x7fa987b61c78, __in_chrg=<optimized out>)
    at /usr/local/include/grpcpp/impl/codegen/interceptor_common.h:48
#8  0x0000000000610942 in grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::inte---Type <return> to continue, or q <return> to quit---
rnal::CallOpClientRecvStatus, grpc::internal::CallNoOp<3>, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::~CallOpSet (this=0x7fa987b61bc8, __in_chrg=<optimized out>)
    at /usr/local/include/grpcpp/impl/codegen/call_op_set.h:764
#9  0x00000000006128dc in grpc::ClientAsyncReaderWriter<google::protobuf::Message, google::protobuf::Message>::~ClientAsyncReaderWriter (this=0x7fa987b61710, __in_chrg=<optimized out>)
    at /usr/local/include/grpcpp/impl/codegen/async_stream.h:514
#10 0x00000000006129b6 in grpc::ClientAsyncReaderWriter<google::protobuf::Message, google::protobuf::Message>::~ClientAsyncReaderWriter (this=0x7fa987b61710, __in_chrg=<optimized out>)
    at /usr/local/include/grpcpp/impl/codegen/async_stream.h:514
#11 0x0000000000612a41 in std::default_delete<grpc::ClientAsyncReaderWriter<google::protobuf::Message, google::protobuf::Message> >::operator() (this=0x7fa92fc00c30, __ptr=0x7fa987b61710)
    at /usr/local/include/c++/8.2.0/bits/unique_ptr.h:81
#12 0x00000000005eae17 in std::unique_ptr<grpc::ClientAsyncReaderWriter<google::protobuf::Message, google::protobuf::Message>, std::default_delete<grpc::ClientAsyncReaderWriter<google::protobuf::Message, google::protobuf::Message> > >::~unique_ptr (this=0x7fa92fc00c30, __in_chrg=<optimized out>)
    at /usr/local/include/c++/8.2.0/bits/unique_ptr.h:274
#13 0x0000000000872fce in hasync::ClientRpc::~ClientRpc (this=0x7fa92fc00ac0, __in_chrg=<optimized out>)
```
 
### Anything else we should know about your project / environment?

* I use a unique_ptr to manager stream io
```c++
  std::unique_ptr <> m_stream; 
  m_stream.reset(grpc::internal::ClientAsyncReaderWriterFactory<
                 google::protobuf::Message,
                 google::protobuf::Message>::Create(m_channel.get(), m_cq.get(),
                                                    method, m_context.get(),
                                                    true, &m_event_write));
```

**Comment by yang-g** [comment]
Looks like application error to me.
