### ISSUE TITLE
Python: end the connection with grpclb load balancer gracefully

### ISSUE THREAD

**Issue by blazej24** [grpc/grpc#19368]
### What version of gRPC and what language are you using?
grpcio == 1.16.0 (for 1.21.1 see another issue: #19401)
 
### What operating system (Linux, Windows,...) and version?
Linux Ubuntu 18.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.7
 
### What did you do?
Simple grpclb usage: 
1) enable grpclb / ares resolver: environment variable GRPC_DNS_RESOLVER=ares
2) run a simple client and use dns:///hello.mimgrpc.me for channel creation
3) do some requests
4) close the channel by channel.close()
 
### What did you expect to see?
The connection to grpclb load balancer should be closed down gracefully, without any errors on the balancer side.
 
### What did you see instead?
onError on the `balanceLoad` RPC is being called in my loadbalancer (in Java), just in the moment of the channel.close() call
```
2019-06-17 12:35:14,552 [grpc-default-executor-12] ERROR c.r.g.l.s.LoadBalanceService - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:517) ~[loadbalancer-standalone-1.0-SNAPSHOT-shaded.jar:na]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) ~[loadbalancer-standalone-1.0-SNAPSHOT-shaded.jar:na]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293) ~[loadbalancer-standalone-1.0-SNAPSHOT-shaded.jar:na]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:741) ~[loadbalancer-standalone-1.0-SNAPSHOT-shaded.jar:na]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[loadbalancer-standalone-1.0-SNAPSHOT-shaded.jar:na]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[loadbalancer-standalone-1.0-SNAPSHOT-shaded.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

### Anything else we should know about your project / environment?
Everything works fine when I use Java/Go clients. Maybe I don't close the channel properly?

**Comment by gnossen** [comment]
CC @zhangkun83

**Comment by zhangkun83** [comment]
Do you mean with Java/Go clients this error doesn't appear, and it only does with Python clients? Anyway, you load balancer could safely skip logging the `CANCELLED` status passed to `StreamObserver.onError()`.

**Comment by blazej24** [comment]
I meant that this error didn't appear with Java/Go clients, but I found out that I was wrong, it **does** appear. So, as you said, I will simply skip logging this error.
