### ISSUE TITLE
RBE infra build flake: "execution failed catastrophically io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway"

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#19500]
```
[36,852 / 36,861] 8259 / 8263 tests; Compiling test/core/tsi/alts/fake_handshaker/handshaker.grpc.pb.cc; 1303s remote ... (6 actions running)
[36,854 / 36,861] 8260 / 8263 tests; Compiling test/core/tsi/alts/fake_handshaker/handshaker.grpc.pb.cc; 1510s remote ... (4 actions running)
ERROR: /tmpfs/src/github/grpc/test/core/tsi/alts/fake_handshaker/BUILD:30:1: Couldn't build file test/core/tsi/alts/fake_handshaker/_objs/handshaker_proto/handshaker.grpc.pb.pic.o: C++ compilation of rule '//test/core/tsi/alts/fake_handshaker:handshaker_proto' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed catastrophically io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway: java.io.IOException: io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.lambda$downloadBlob$4(GrpcRemoteCache.java:318)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:175)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:162)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:107)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:752)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:116)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache$2.onError(GrpcRemoteCache.java:358)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: 502:Bad Gateway
	at io.grpc.Status.asRuntimeException(Status.java:532)
	... 19 more
INFO: Elapsed time: 1730.703s, Critical Path: 1699.66s
INFO: 18976 processes: 2338 remote cache hit, 16638 remote.
FAILED: Build did NOT complete successfully
//test/cpp/codegen:run_golden_file_test                         (cached) PASSED in 3.0s
//test/core/end2end:h2_proxy_nosec_test@cancel_after_round_trip@poller=epollex NO STATUS
//test/core/end2end:h2_proxy_nosec_test@graceful_server_shutdown@poller=epoll1 NO STATUS
//test/core/end2end:h2_sockpair_nosec_test@workaround_cronet_compression@poller=epoll1 NO STATUS
//test/core/avl:avl_test@poller=epoll1                                   PASSED in 8.5s
//test/core/avl:avl_test@poller=epollex                                  PASSED in 9.8s
//test/core/avl:avl_test@poller=poll                                     PASSED in 11.0s
```

Looks like an RBE build infra flake

https://source.cloud.google.com/results/invocations/9c5fbc9a-039d-4f46-b6d2-aed7941ac0bc/log

**Comment by a11r** [comment]
Should this be filed in the java repo ?

**Comment by vjpai** [comment]
@a11r @srini100 I think it looks more like a catastrophic infrastructure failure triggered by Bazel (which happens to use grpc-java) rather than a failure in grpc-java, so I'm going to move it to infra rather than lang/java

**Comment by jtattermusch** [comment]
Looks like an infra failure inceed, but I don't think I've seen more instances since. Closing.
