### ISSUE TITLE
Unexpected StatusCode.UNAVAILABLE: Connection reset by peer

### ISSUE THREAD

**Issue by yutkin** [grpc/grpc#19514]
### What version of gRPC and what language are you using?
Python 3.6
`grpcio==1.21.1`
 
### What operating system (Linux, Windows,...) and version?
Ubuntu 18 in Docker
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Running in Kubernetes with Envoy as a proxy
 
### What did you do?
Invoke a function via gRPC
 
### What did you expect to see?
Normal invocation and computed result 
 
### What did you see instead?
Sometimes (~ in 1-5 %) I get:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/backoffice/worker.py", line 138, in handle text

File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner return func(*args, **kwds) 

File "/usr/local/lib/python3.6/site-packages/backoffice/worker.py", line 261, in task_handler data.update(self.get_faq_search_article(input_text)) 

File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner return func(*args, **kwds) 

File "/usr/local/lib/python3.6/site-packages/backoffice/worker.py", line 225, in get_faq_search_article response = 
self.faq_search_stub.GetFAQArticleID(query) 

File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__ return _end_unary_response_blocking(state, call, False, None) 

File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "Connection reset by peer" debug_error_string = "{"created":"@1561963566.707249650","description":"Error received from peer ipv4:172.23.218.229:8100","file":"src/core/lib/surface/call.cc","file_line":1046,"grpc_message":"Connection reset by peer","grpc_status":14}" >

status_code => 'StatusCode.UNAVAILABLE'
error_details => 'Connection reset by peer'
```

**Comment by yutkin** [comment]
Self-made retry mechanism with exp. backoff helped mitigate this issue.

**Comment by gnossen** [comment]
How can we reproduce this problem? Do you have a minimal reproduction case?
Failing that, can you please turn up logging by setting the following environment variables and supply us with the output?
```
GRPC_TRACE=all
GRPC_VERBOSITY=DEBUG
```
Does this problem occur in earlier versions of gRPC?

**Comment by geoffjukes** [comment]
@yutkin Would you be willing to share your solution?

**Comment by yutkin** [comment]
@geoffjukes You have to define an interceptor for RPC Errors. It will doing retries on failures with exponential backoff sleeping policy:
```python
class SleepingPolicy(abc.ABC):
    @abc.abstractmethod
    def sleep(self, try_i: int):
        """
        How long to sleep in milliseconds.
        :param try_i: the number of retry (starting from zero)
        """
        assert try_i >= 0

class ExponentialBackoff(SleepingPolicy):
    def __init__(self, *, init_backoff_ms: int, max_backoff_ms: int, multiplier: int):
        self.init_backoff = randint(0, init_backoff_ms)
        self.max_backoff = max_backoff_ms
        self.multiplier = multiplier

    def sleep(self, try_i: int):
        sleep_range = min(
            self.init_backoff * self.multiplier ** try_i, self.max_backoff
        )
        sleep_ms = randint(0, sleep_range)
        logger.debug(f"Sleeping for {sleep_ms}")
        time.sleep(sleep_ms / 1000)

class RetryOnRpcErrorClientInterceptor(
    grpc.UnaryUnaryClientInterceptor, grpc.StreamUnaryClientInterceptor
):
    def __init__(
        self,
        *,
        max_attempts: int,
        sleeping_policy: SleepingPolicy,
        status_for_retry: Optional[Tuple[grpc.StatusCode]] = None,
    ):
        self.max_attempts = max_attempts
        self.sleeping_policy = sleeping_policy
        self.status_for_retry = status_for_retry

    def _intercept_call(self, continuation, client_call_details, request_or_iterator):

        for try_i in range(self.max_attempts):
            response = continuation(client_call_details, request_or_iterator)

            if isinstance(response, grpc.RpcError):

                # Return if it was last attempt
                if try_i == (self.max_attempts - 1):
                    return response

                # If status code is not in retryable status codes
                if (
                    self.status_for_retry
                    and response.code() not in self.status_for_retry
                ):
                    return response

                self.sleeping_policy.sleep(try_i)
            else:
                return response

    def intercept_unary_unary(self, continuation, client_call_details, request):
        return self._intercept_call(continuation, client_call_details, request)

    def intercept_stream_unary(
        self, continuation, client_call_details, request_iterator
    ):
        return self._intercept_call(continuation, client_call_details, request_iterator)
```

Usage example:

```python
interceptors = (
  RetryOnRpcErrorClientInterceptor(
    max_attempts=4,
    sleeping_policy=ExponentialBackoff(init_backoff_ms=100, max_backoff_ms=1600, multiplier=2),
    status_for_retry=(grpc.StatusCode.UNAVAILABLE,),
  ),
)
stub = YourStub(
    grpc.intercept_channel(grpc.insecure_channel("service-hostname:8100"), *interceptors)
)
```

**Comment by geoffjukes** [comment]
Thank you so much for sharing @yutkin, this is incredibly helpful.

**Comment by gnossen** [comment]
@yutkin Thanks for the detailed interceptor! Retries are something that are not currently handled automatically within the gRPC library, either in Python or in C++, so doing retries like this within your application is definitely the way to go. If you'd like to contribute this interceptor, we have a Github project called [`grpc-ecosystem`](https://github.com/grpc-ecosystem) for great community-authored add-ons like this. ([guide for contributing](https://github.com/grpc/grpc-community/blob/master/grpc_ecosystem.md))

**Comment by iamliamc** [comment]
What I don't understand is why would this happen in the first place? Is this a normal potentiality in the python GRPC library or does it say something about the service that is responding: 

```
status_code => 'StatusCode.UNAVAILABLE'
error_details => 'Connection reset by peer'
```

It's also not clear here https://grpc.github.io/grpc/python/grpc.html

If there is support for `secure_channels` --- finally does anyone know what `This is an EXPERIMENTAL API.` means in so far as using this channel intercept stuff?

**Comment by gnossen** [comment]
@iamliamc It says something about the connection between the client and the server.

Yes, interceptors do indeed work with secure_channels.

Interceptors *are* currently considered an experimental API. Which means that we technically reserve the right to change the API without making it a major version bump. In practice however, so many things have come to depend upon the current form of the interceptor API, that it's highly unlikely we'll do this. In fact, we probably need to to make it a priority to graduate the API from experimental in the not-too-distant future.

**Comment by caryan** [comment]
For anyone trying this approach with the `aio` flavour there is an [if-else chain](https://github.com/grpc/grpc/blob/265dc3bd3363d9acbf1e32e5d6740a7f2dfff7b8/src/python/grpcio/grpc/aio/_channel.py#L259) that prevents you from using the multiple inheritance style above and you have to make separate interceptor classes for each type of RPC call. E.g.

```python
class RetryOnRpcErrorClientInterceptor:
    def __init__(
        self,
        *,
        max_attempts: int,
        sleeping_policy: SleepingPolicy,
        status_for_retry: Optional[Tuple[grpc.StatusCode]] = None,
    ):
        self.max_attempts = max_attempts
        self.sleeping_policy = sleeping_policy
        self.status_for_retry = status_for_retry

    def _intercept_call(self, continuation, client_call_details, request_or_iterator):

        for try_i in range(self.max_attempts):
            response = continuation(client_call_details, request_or_iterator)

            if isinstance(response, grpc.RpcError):

                # Return if it was last attempt
                if try_i == (self.max_attempts - 1):
                    return response

                # If status code is not in retryable status codes
                if (
                    self.status_for_retry
                    and response.code() not in self.status_for_retry
                ):
                    return response

                self.sleeping_policy.sleep(try_i)
            else:
                return response

class UnaryUnaryRetryOnRpcErrorClientInterceptor(
    RetryOnRpcErrorClientInterceptor,
    grpc.aio.UnaryUnaryClientInterceptor
):
    def intercept_unary_unary(self, continuation, client_call_details, request):
        return self._intercept_call(continuation, client_call_details, request)

class UnaryUnaryRetryOnRpcErrorClientInterceptor(
    RetryOnRpcErrorClientInterceptor,
    grpc.aio.StreamUnaryClientInterceptor
):
    def intercept_unary_unary(self, continuation, client_call_details, request_iterator):
        return self._intercept_call(continuation, client_call_details, request_iterator)
```

**Comment by vanakema** [comment]
We weirdly only experience this on versions > 1.25. We are also building from source now since we need to use OpenSSL instead of BoringSSL (our certs are somehow incompatible with BoringSSL but work fine with OpenSSL. We're working on replacing them with BoringSSL compatible certs), but I can't see how this issue would be related to OpenSSL. 

Has anyone else experienced this in the latest versions of gRPC (1.46.3)?

**Comment by ndvbd** [comment]
Is the randomness in the sleep needed in this grpc case?
