### ISSUE TITLE
Basic Tests Python MacOS DNSResolverTest

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#19523]
Seen on #19516 

```
Errors/Failures:
[91munit._dns_resolver_test.DNSResolverTest.test_connect_loopback[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/src/python/grpcio_tests/tests/unit/_dns_resolver_test.py", line 57, in test_connect_loopback
    timeout=test_constants.SHORT_TIMEOUT,
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py27_native/lib/python2.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py27_native/lib/python2.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1562017691.790340000","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
>
[1mstdout:[0m
```

https://source.cloud.google.com/results/invocations/8ac2cce1-bf8d-4c2b-8337-2295d552989b/targets/github%2Fgrpc%2Fpython_macos_opt_native/tests

**Comment by gnossen** [comment]
Interesting. This test is solid green on master. And the only instance of this failure I see on the PR fusion job is on builds for #19516.

**Comment by gnossen** [comment]
And master is still green in the first build after #19516 was merged. Odd.

**Comment by yashykt** [comment]
there's probably some element that's making it flaky

**Comment by gnossen** [comment]
Downgrading to P2 since it apparently hasn't been since in the past 10 days.

**Comment by XuanWang-Amos** [comment]
Can't find `_dns_resolver_test` in Basic Tests Python MacOS job anymore, it does exist in Bazel Basic Tests and it's passing, @gnossen can we close this?
