### ISSUE TITLE
bad pointer in ./include/grpcpp/impl/codegen/call_op_set.h

### ISSUE THREAD

**Issue by abalib** [grpc/grpc#19601]
### What version of gRPC and what language are you using?
 1.19.1 C++
 
### What operating system (Linux, Windows,...) and version?
Linux for IBM Z (s390x)
Linux 8e08LP30 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:26:33 UTC 2019 s390x s390x s390x GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

protoc --version
libprotoc 3.6.1
 
### What did you do?
Running the ./examples/cpp/helloworld greeter_server and greeter_client. 

Running them as-is with no modifications.

### What did you expect to see?
./greeter_client should print

Greeter received: Hello world 
 
### What did you see instead?
./greeter_client prints the following

 terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

I think a bad pointer is causing an exception as I demonstrate in the following diff. Changing the arguments of the string function makes the exception go away.

Either the grpc::string() or GRPC_SLICE_START_PTR() is producing a bad pointer which throws an exception.  I give you a debug output and also a gdb backtrace as well.
Notice `__beg=0` in the backtrace, which doesn't look right to me. 
`__beg=0x0, __end=0x3fffd4dd2e2`.   

```
diff --git a/include/grpcpp/impl/codegen/call_op_set.h b/include/grpcpp/impl/codegen/call_op_set.h
index 4ca87a99fc..14bb4cd571 100644
--- a/include/grpcpp/impl/codegen/call_op_set.h
+++ b/include/grpcpp/impl/codegen/call_op_set.h
@@ -779,9 +779,9 @@ class CallOpClientRecvStatus {
     *recv_status_ =
         Status(static_cast<StatusCode>(status_code_),
                GRPC_SLICE_IS_EMPTY(error_message_)
-                   ? grpc::string()
-                   : grpc::string(GRPC_SLICE_START_PTR(error_message_),
-                                  GRPC_SLICE_END_PTR(error_message_)),
+                   ? grpc::string("ababa")
+              : grpc::string("ababa"),// GRPC_SLICE_START_PTR(error_message_),
+              //GRPC_SLICE_END_PTR(error_message_)),
                binary_error_details);
     client_context_->set_debug_error_string(
         debug_error_string_ != nullptr ? debug_error_string_ : "");
```

```
  $ GRPC_VERBOSITY=debug GRPC_TRACE=api   ./greeter_client
D0710 08:12:08.522755376   42611 ev_posix.cc:170]            Using polling engine: epollex
D0710 08:12:08.522818895   42611 dns_resolver.cc:334]        Using native dns resolver
I0710 08:12:08.522851899   42611 init.cc:155]                grpc_init(void)
I0710 08:12:08.522868574   42611 init.cc:155]                grpc_init(void)
I0710 08:12:08.522874157   42611 channel_create.cc:91]       grpc_insecure_channel_create(target=0.0.0.0:50051, args=0x3fff777e398, reserved=(nil))
I0710 08:12:08.522923116   42611 channel.cc:285]             grpc_channel_get_target(channel=0x2aa4f386890)
I0710 08:12:08.522935901   42611 init.cc:155]                grpc_init(void)
I0710 08:12:08.522940081   42611 init.cc:160]                grpc_shutdown(void)
I0710 08:12:08.522948775   42611 channel.cc:378]             grpc_channel_register_call(channel=0x2aa4f386890, method=/helloworld.Greeter/SayHello, host=(null), reserved=(nil))
I0710 08:12:08.522955734   42611 init.cc:160]                grpc_shutdown(void)
I0710 08:12:08.522974504   42611 init.cc:155]                grpc_init(void)
I0710 08:12:08.522979660   42611 completion_queue.cc:481]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0710 08:12:08.522985823   42611 channel.cc:413]             grpc_channel_create_registered_call(channel=0x2aa4f386890, parent_call=(nil), propagation_mask=ffff, completion_queue=0x2aa4f3846b0, registered_call_handle=0x2aa4f388ac0, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0710 08:12:08.522999252   42611 grpc_context.cc:28]         grpc_census_call_set_context(call=0x2aa4f397e70, census_context=(nil))
I0710 08:12:08.523017816   42611 call.cc:1905]               grpc_call_start_batch(call=0x2aa4f397e70, ops=0x3fff777d8f0, nops=6, tag=0x3fff777ddf0, reserved=(nil))
I0710 08:12:08.523024757   42611 call.cc:1511]               ops[0]: SEND_INITIAL_METADATA(nil)
I0710 08:12:08.523028629   42611 call.cc:1511]               ops[1]: SEND_MESSAGE ptr=0x2aa4f38a570
I0710 08:12:08.523033082   42611 call.cc:1511]               ops[2]: RECV_INITIAL_METADATA ptr=0x3fff777e4a8
I0710 08:12:08.523036631   42611 call.cc:1511]               ops[3]: RECV_MESSAGE ptr=0x3fff777de80
I0710 08:12:08.523039936   42611 call.cc:1511]               ops[4]: SEND_CLOSE_FROM_CLIENT
I0710 08:12:08.523044795   42611 call.cc:1511]               ops[5]: RECV_STATUS_ON_CLIENT metadata=0x3fff777e4f8 status=0x3fff777deb8 details=0x3fff777dec0
D0710 08:12:08.523056659   42611 dns_resolver.cc:275]        Start resolving.
I0710 08:12:08.523323651   42611 subchannel.cc:1016]         New connected subchannel at 0x2aa4f384af0 for subchannel 0x3ff94002360
I0710 08:12:08.523593065   42611 completion_queue.cc:782]    cq_end_op_for_pluck(cq=0x2aa4f3846b0, tag=0x3fff777ddf0, error="No Error", done=0x3ffa389bc68, done_arg=0x2aa4f398d70, storage=0x2aa4f398dc0)
I0710 08:12:08.523600290   42611 completion_queue.cc:1295]   RETURN_EVENT[0x2aa4f3846b0]: OP_COMPLETE: tag:0x3fff777ddf0 OK
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

```
 $ gdb greeter_client
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "s390x-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from greeter_client...done.
(gdb) run
Starting program: ./grpc/examples/cpp/helloworld/greeter_client
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/s390x-linux-gnu/libthread_db.so.1".
[New Thread 0x3fffcd7f910 (LWP 43000)]
[New Thread 0x3fffc57e910 (LWP 43001)]
[New Thread 0x3fffbd7d910 (LWP 43002)]
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

Thread 1 "greeter_client" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x000003fffd63f37a in __GI_abort () at abort.c:79
#2  0x000003fffd92b300 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/s390x-linux-gnu/libstdc++.so.6
#3  0x000003fffd928bf6 in ?? () from /usr/lib/s390x-linux-gnu/libstdc++.so.6
#4  0x000003fffd928c58 in std::terminate() () from /usr/lib/s390x-linux-gnu/libstdc++.so.6
#5  0x000003fffd928f32 in __cxa_throw () from /usr/lib/s390x-linux-gnu/libstdc++.so.6
#6  0x000003fffd957454 in std::__throw_logic_error(char const*) () from /usr/lib/s390x-linux-gnu/libstdc++.so.6
#7  0x000002aa000202ce in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<unsigned char*> (
    this=0x3ffffffe590, __beg=0x0, __end=0x3fffd4dd2e2 "") at /usr/include/c++/7/bits/basic_string.tcc:212
#8  0x000002aa0001ec34 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<unsigned char*> (
    this=0x3ffffffe590, __beg=0x0, __end=0x3fffd4dd2e2 "") at /usr/include/c++/7/bits/basic_string.h:236
#9  0x000002aa0001c17e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<unsigned char*> (
    this=0x3ffffffe590, __beg=0x0, __end=0x3fffd4dd2e2 "") at /usr/include/c++/7/bits/basic_string.h:255
#10 0x000002aa0001ad4a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<unsigned char*, void> (
    this=0x3ffffffe590, __beg=0x0, __end=0x3fffd4dd2e2 "", __a=...) at /usr/include/c++/7/bits/basic_string.h:607
#11 0x000002aa00017c4e in grpc::internal::CallOpClientRecvStatus::FinishOp (this=0x3ffffffea10, status=0x3ffffffe787)
    at /usr/local/include/grpcpp/impl/codegen/call_op_set.h:782
#12 0x000002aa0002332a in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpRecvInitialMetadata, grpc::internal::CallOpRecvMessage<helloworld::HelloReply>, grpc::internal::CallOpClientSendClose, grpc::internal::CallOpClientRecvStatus>::FinalizeResult (this=0x3ffffffe970, tag=0x3ffffffe788, status=0x3ffffffe787)
    at /usr/local/include/grpcpp/impl/codegen/call_op_set.h:897
#13 0x000002aa00013ae0 in grpc::CompletionQueue::Pluck (this=0x3ffffffe890, tag=0x3ffffffe970)
    at /usr/local/include/grpcpp/impl/codegen/completion_queue.h:314
#14 0x000002aa0001d014 in grpc::internal::BlockingUnaryCallImpl<helloworld::HelloRequest, helloworld::HelloReply>::BlockingUnaryCallImpl (
    this=0x3ffffffecb8, channel=0x2aa00051780, method=..., context=0x3ffffffef48, request=..., result=0x3ffffffeec0)
    at /usr/local/include/grpcpp/impl/codegen/client_unary_call.h:72
#15 0x000002aa0001b382 in grpc::internal::BlockingUnaryCall<helloworld::HelloRequest, helloworld::HelloReply> (channel=0x2aa00051780,
    method=..., context=0x3ffffffef48, request=..., result=0x3ffffffeec0) at /usr/local/include/grpcpp/impl/codegen/client_unary_call.h:43
#16 0x000002aa0001101a in helloworld::Greeter::Stub::SayHello (this=0x2aa00056710, context=0x3ffffffef48, request=..., response=0x3ffffffeec0)
    at helloworld.grpc.pb.cc:36
#17 0x000002aa0002912a in GreeterClient::SayHello (this=0x3fffffff200, user="world") at greeter_client.cc:59
#18 0x000002aa00028c1c in main (argc=1, argv=0x3fffffff498) at greeter_client.cc:88
```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by weiyongji** [comment]
maybe cause by locale, try [http://manpages.ubuntu.com/manpages/bionic/man8/locale-gen.8.html](url)

**Comment by abalib** [comment]
> maybe cause by locale, try [http://manpages.ubuntu.com/manpages/bionic/man8/locale-gen.8.html](url)

Thanks for the advice.  Tried few locale settings but no difference.

```
~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=


~$ cat /etc/default/locale
#  File generated by update-locale
LANG="en_US.UTF-8"

~$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

~$ export LANGUAGE=en_US.UTF-8
~$ export LC_ALL=en_US.UTF-8
~$ env | grep LAN
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8

~/project/mygrpc/2/grpc/examples/cpp/helloworld$ ./greeter_client
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted

```

**Comment by yashykt** [comment]
This issue is being closed because it has been marked with the label kind/question. This form is for bug reports and feature requests ONLY!
Please post questions on https://groups.google.com/g/grpc-io so that the wider community can help answer.
