### ISSUE TITLE
Error loading native library when running application under IIS

### ISSUE THREAD

**Issue by YNauholnykh** [grpc/grpc#19666]
### What version of gRPC and what language are you using?
1.18.0, C#
 
### What operating system (Linux, Windows,...) and version?
 Windows Sever Core 2016
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Net 4.7
 
### What did you do?
I have my application which is running under IIS where I use Grpc Client. When I using it, it fails saying it cannot find the native library

### What did you expect to see?
Grpc.Core should be able to load grpc_csharp dll
 
### What did you see instead?
Error like the following:

Description
Error loading native library. Not found in any of the possible locations: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\4e462769\bed5319d\assembly\dl3\d06f6afb\00ce939b_16acd401\grpc_csharp_ext.x64.dll,C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\4e462769\bed5319d\assembly\dl3\d06f6afb\00ce939b_16acd401\runtimes/win/native\grpc_csharp_ext.x64.dll,C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\4e462769\bed5319d\assembly\dl3\d06f6afb\00ce939b_16acd401\../..\runtimes/win/native\grpc_csharp_ext.x64.dll
Source
Grpc.Core

Both Grpc.Core and grpc_csharp_ext are present in my application bin folder. However it looks like IIS puts Grpc.Core dll in cache and it searches for grpc_csharp dll there. 

I looked through Grpc.Core dll source code and it looks like it searches for this dll only in 3 locations: same as Grpc.Core and two relative locations. As Grpc.Core is used by IIS and it puts it to cache, it fails to load native dll.
 
### Anything else we should know about your project / environment?
IIS version: 10.0.16299

**Comment by DenSmoke** [comment]
Same problem when testing my multi-target (net472, netstandard2.0, netcoreapp3.0) library when test is compiled to net472
```
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: d:\a\1\s\TechWiz.Lib.Tests\bin\release\net472\grpc_csharp_ext.x86.dll,d:\a\1\s\TechWiz.Lib.Tests\bin\release\net472\runtimes/win/native\grpc_csharp_ext.x86.dll,d:\a\1\s\TechWiz.Lib.Tests\bin\release\net472\../..\runtimes/win/native\grpc_csharp_ext.x86.dll
at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
at Grpc.Core.Internal.NativeExtension..ctor()
at Grpc.Core.Internal.NativeExtension.Get()
at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
at Grpc.Core.GrpcEnvironment..ctor()
at Grpc.Core.GrpcEnvironment.AddRef()
at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
at DpLib.Firebase.FirebaseService.<InitAsync>d__12.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at TechWiz.Lib.Tests.TechWizServerFirebaseServiceTest.get_Firebase() in d:\a\1\s\TechWiz.Lib.Tests\TechWizServerFirebaseServiceTest.cs:line 27
at TechWiz.Lib.Tests.TechWizServerFirebaseServiceTest.<>c.<AddMessageAsync>b__4_0() in d:\a\1\s\TechWiz.Lib.Tests\TechWizServerFirebaseServiceTest.cs:line 37
at Xunit.Record.<ExceptionAsync>d__3.MoveNext() in C:\Dev\xunit\xunit\src\xunit.core\Record.cs:line 76
---> (Inner Exception #0) System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: d:\a\1\s\TechWiz.Lib.Tests\bin\release\net472\grpc_csharp_ext.x86.dll,d:\a\1\s\TechWiz.Lib.Tests\bin\release\net472\runtimes/win/native\grpc_csharp_ext.x86.dll,d:\a\1\s\TechWiz.Lib.Tests\bin\release\net472\../..\runtimes/win/native\grpc_csharp_ext.x86.dll
at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
at Grpc.Core.Internal.NativeExtension..ctor()
at Grpc.Core.Internal.NativeExtension.Get()
at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
at Grpc.Core.GrpcEnvironment..ctor()
at Grpc.Core.GrpcEnvironment.AddRef()
at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
at DpLib.Firebase.FirebaseService.<InitAsync>d__12.MoveNext()<---
```

**Comment by bneumann** [comment]
Thanks @DenSmoke that did the trick for me. I think this is still a issue by the way

**Comment by jtattermusch** [comment]
Unfortunately I don't think there is a "proper" way to fix this. The way the copying of the native library grpc_csharp_ext works is basically a trick to make the native dependencies work on legacy .NET based frameworks (which don't support native dependencies as a feature) and while it works in most cases, there might be cases (such as yours) where it doesn't work. Looks like you've figured out a very reasonable workaround, so I'd suggest using it.

Note that the problems with native library copying don't affect any of the .NET core targets (netcoreapp etc.), where native libraries are a feature supported by the framework - so I'd suggest using the netcoreapp target if you can.

**Comment by bneumann** [comment]
Thanks @jtattermusch for that explanation. I didn't know that the native delivery is not part of the legacy .NET frameworks. But it makes sense of course.
