### ISSUE TITLE
segfault, fast simultaneous calls from the same client terminates the program with a segfaultg

### ISSUE THREAD

**Issue by theopencompany** [grpc/grpc#19842]
### What version of gRPC and what language are you using?
V1.22.X 
proto 3.8.0
 
### What operating system (Linux, Windows,...) and version?
 LINUX UBUNTU 19.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc
 
### What did you do?
I have a grpc server in c ++ that has a service (NOT asynchronous synchronization service) to authenticate my users, the process is:

1. I receive a request for user credentials with username and password
2. go to the database (MYSQL c ++ connector) and run a query to search for the user and return it to the grpc client
3. If I click on the login button and wait for the request (0.300-0.500ms), everything works fine.

**but ... if I SIMULATE (using BloomRPC client or nodegrpc client ) quickly clicks on the login button as a crazy user, my backend crashes and I get a**

**SEGFAULT**

so in summary, sending fasting and simultaneous requests to the server causes the server to crash with segfault

```
GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Nuevo Thread 0x7ffff64b8700 (LWP 9985)]
[Nuevo Thread 0x7ffff5cb7700 (LWP 9986)]
[Nuevo Thread 0x7ffff54b6700 (LWP 9987)]
[Nuevo Thread 0x7ffff4cb5700 (LWP 9988)]
[Nuevo Thread 0x7fffe7fff700 (LWP 10003)]
[Nuevo Thread 0x7fffe77fe700 (LWP 10004)]
[Nuevo Thread 0x7fffe6ffd700 (LWP 10016)]

Thread 6 "grpcpp_sync_ser" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7fffe7fff700 (LWP 10003)]
0x00007fffe00008d0 in ?? ()
```

**Backtrace**

```
(gdb) backtrace
#0  futex_reltimed_wait_cancelable (private=<optimized out>, reltime=0x7ffff4cb4ab0, expected=0, futex_word=0x7ffff4cb4bf0) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
#1  __pthread_cond_wait_common (abstime=0x7ffff4cb4b50, mutex=0x7fffe0001020, cond=0x7ffff4cb4bc8) at pthread_cond_wait.c:533
#2  __pthread_cond_timedwait (cond=0x7ffff4cb4bc8, mutex=0x7fffe0001020, abstime=0x7ffff4cb4b50) at pthread_cond_wait.c:667
#3  0x00007ffff6984127 in gpr_cv_wait () from /usr/local/lib/libgrpc.so.7
#4  0x00007ffff68c74b5 in ?? () from /usr/local/lib/libgrpc.so.7
#5  0x00007ffff68edab4 in ?? () from /usr/local/lib/libgrpc.so.7
#6  0x00007ffff7ccfb98 in grpc_impl::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) () from /usr/local/lib/libgrpc++.so.1
#7  0x00007ffff7ce5b30 in grpc_impl::Server::SyncRequestThreadManager::PollForWork(void**, bool*) () from /usr/local/lib/libgrpc++.so.1
#8  0x00007ffff7cf049c in grpc::ThreadManager::MainWorkLoop() () from /usr/local/lib/libgrpc++.so.1
#9  0x00007ffff7cf05fc in grpc::ThreadManager::WorkerThread::Run() () from /usr/local/lib/libgrpc++.so.1
#10 0x00007ffff6985703 in ?? () from /usr/local/lib/libgrpc.so.7
#11 0x00007ffff6c0f182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007ffff6b38b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**other backtrace**

```
(gdb) backtrace
#0  0x00007fffe00008d0 in ?? ()
#1  0x00007ffff6d52ce0 in BIO_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00007ffff6d53614 in BIO_free_all () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#3  0x00007ffff70c6457 in SSL_free () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#4  0x00007ffff75fad88 in vio_ssl_delete (vio=0x555555791cb0) at ../../mysql-8.0.16/vio/viossl.cc:393
#5  0x00007ffff764cfa3 in end_server (mysql=0x55555578f830) at ../../mysql-8.0.16/sql-common/client.cc:1744
#6  0x00007ffff764d244 in cli_safe_read_with_ok_complete (mysql=mysql@entry=0x55555578f830, parse_ok=<optimized out>, is_data_packet=is_data_packet@entry=0x0, len=<optimized out>) at ../../mysql-8.0.16/sql-common/client.cc:1101
#7  0x00007ffff764d604 in cli_safe_read_with_ok (mysql=mysql@entry=0x55555578f830, parse_ok=parse_ok@entry=false, is_data_packet=is_data_packet@entry=0x0) at ../../mysql-8.0.16/sql-common/client.cc:1084
#8  0x00007ffff764d62a in cli_safe_read (mysql=mysql@entry=0x55555578f830, is_data_packet=is_data_packet@entry=0x0) at ../../mysql-8.0.16/sql-common/client.cc:1206
#9  0x00007ffff765b156 in cli_read_prepare_result (mysql=0x55555578f830, stmt=0x7fffdc00db40) at ../../mysql-8.0.16/libmysql/libmysql.cc:1288
#10 0x00007ffff765b5f7 in mysql_stmt_prepare (stmt=0x7fffdc00db40, query=0x7fffdc000b20 "SELECT * FROM User WHERE email = ? and password = ?", length=51) at ../../mysql-8.0.16/libmysql/libmysql.cc:1500
#11 0x00007ffff757e177 in sql::mysql::MySQL_Connection::prepareStatement(sql::SQLString const&) () at ../../mysql-8.0.16/sql-common/client.cc:8267
#12 0x00005555555d9a08 in Database::query (query="SELECT * FROM User WHERE email = ? and password = ?") at /home/samuel/Proyectos/toc/fitx/user/common/db/database.cpp:48
#13 0x0000555555617519 in AuthService::login (userCredentials=...) at /home/samuel/Proyectos/toc/fitx/user/common/service/auth_service.cpp:23
#14 0x00005555556248ae in AuthController::<lambda()>::operator()(void) const (__closure=0x7fffe7ffe4b0) at /home/samuel/Proyectos/toc/fitx/user/src/controller/auth_controller.cpp:17
#15 0x0000555555624ac6 in std::_Function_handler<void(), AuthController::login(grpc::ServerContext*, const protoModel::UserCredentialRequest*, protoModel::UserResponse*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/8/bits/std_function.h:297
#16 0x0000555555592eca in std::function<void ()>::operator()() const (this=0x7fffe7ffe4b0) at /usr/include/c++/8/bits/std_function.h:687
#17 0x00005555556163fe in CommonService::ResponseEntity(std::function<void ()> const&) (execute=...) at /home/samuel/Proyectos/toc/fitx/user/common/service/common_service.cpp:59
#18 0x000055555562495f in AuthController::login (this=0x7fffffffe2f0, context=0x7fffdc00cf60, request=0x7fffdc00c8b0, response=0x7fffe7ffe800) at /home/samuel/Proyectos/toc/fitx/user/src/controller/auth_controller.cpp:20
#19 0x0000555555599a1b in std::__invoke_impl<grpc::Status, grpc::Status (protoService::Auth::Service::* const&)(grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*), protoService::Auth::Service*, grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*> (__f=@0x5555557c2be8: &virtual protoService::Auth::Service::login(grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*), __t=@0x7fffe7ffe6d8: 0x7fffffffe2f0, __args#0=@0x7fffe7ffe6d0: 0x7fffdc00cf60, __args#1=@0x7fffe7ffe6c8: 0x7fffdc00c8b0, __args#2=@0x7fffe7ffe6c0: 0x7fffe7ffe800) at /usr/include/c++/8/bits/invoke.h:73
#20 0x00005555555992c9 in std::__invoke<grpc::Status (protoService::Auth::Service::* const&)(grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*), protoService::Auth::Service*, grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*> (__fn=@0x5555557c2be8: &virtual protoService::Auth::Service::login(grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*), __args#0=@0x7fffe7ffe6d8: 0x7fffffffe2f0, __args#1=@0x7fffe7ffe6d0: 0x7fffdc00cf60, __args#2=@0x7fffe7ffe6c8: 0x7fffdc00c8b0, __args#3=@0x7fffe7ffe6c0: 0x7fffe7ffe800) at /usr/include/c++/8/bits/invoke.h:96
#21 0x00005555555984e1 in std::_Mem_fn_base<grpc::Status (protoService::Auth::Service::*)(grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*), true>::operator()<protoService::Auth::Service*, grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*> (this=0x5555557c2be8, __args#0=@0x7fffe7ffe6d8: 0x7fffffffe2f0, __args#1=@0x7fffe7ffe6d0: 0x7fffdc00cf60, __args#2=@0x7fffe7ffe6c8: 0x7fffdc00c8b0, __args#3=@0x7fffe7ffe6c0: 0x7fffe7ffe800) at /usr/include/c++/8/functional:114
#22 0x0000555555596bcb in std::_Function_handler<grpc::Status (protoService::Auth::Service*, grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*), std::_Mem_fn<grpc::Status (protoService::Auth::Service::*)(grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*)> >::_M_invoke(std::_Any_data const&, protoService::Auth::Service*&&, grpc_impl::ServerContext*&&, protoModel::UserCredentialRequest const*&&, protoModel::UserResponse*&&) (__functor=..., __args#0=@0x7fffe7ffe6d8: 0x7fffffffe2f0, __args#1=@0x7fffe7ffe6d0: 0x7fffdc00cf60, __args#2=@0x7fffe7ffe6c8: 0x7fffdc00c8b0, __args#3=@0x7fffe7ffe6c0: 0x7fffe7ffe800) at /usr/include/c++/8/bits/std_function.h:283
#23 0x000055555559d8e7 in std::function<grpc::Status (protoService::Auth::Service*, grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*)>::operator()(protoService::Auth::Service*, grpc_impl::ServerContext*, protoModel::UserCredentialRequest const*, protoModel::UserResponse*) const (this=0x5555557c2be8, __args#0=0x7fffffffe2f0, __args#1=0x7fffdc00cf60, __args#2=0x7fffdc00c8b0, __args#3=0x7fffe7ffe800) at /usr/include/c++/8/bits/std_function.h:687
#24 0x000055555559b417 in grpc::internal::RpcMethodHandler<protoService::Auth::Service, protoModel::UserCredentialRequest, protoModel::UserResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}::operator()() const (this=0x5555557c2be0) at /usr/local/include/grpcpp/impl/codegen/method_handler_impl.h:67
#25 0x000055555559d93f in grpc::internal::CatchingFunctionHandler<grpc::internal::RpcMethodHandler<protoService::Auth::Service, protoModel::UserCredentialRequest, protoModel::UserResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc::internal::RpcMethodHandler<protoService::Auth::Service, protoModel::UserCredentialRequest, protoModel::UserResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&) (handler=...) at /usr/local/include/grpcpp/impl/codegen/method_handler_impl.h:42
#26 0x000055555559b599 in grpc::internal::RpcMethodHandler<protoService::Auth::Service, protoModel::UserCredentialRequest, protoModel::UserResponse>::RunHandler (this=0x5555557c2be0, param=...) at /usr/local/include/grpcpp/impl/codegen/method_handler_impl.h:65
#27 0x00007ffff7ce99e8 in grpc_impl::Server::SyncRequest::CallData::ContinueRunAfterInterception() () from /usr/local/lib/libgrpc++.so.1
#28 0x00007ffff7cea0d1 in grpc_impl::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) () from /usr/local/lib/libgrpc++.so.1
#29 0x00007ffff7cf0513 in grpc::ThreadManager::MainWorkLoop() () from /usr/local/lib/libgrpc++.so.1
#30 0x00007ffff7cf05fc in grpc::ThreadManager::WorkerThread::Run() () from /usr/local/lib/libgrpc++.so.1
#31 0x00007ffff6985703 in ?? () from /usr/local/lib/libgrpc.so.7
#32 0x00007ffff6c0f182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#33 0x00007ffff6b38b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
/home/samuel/Proyectos/toc/fitx/user/cmake-build-debug/user-dev
D0803 03:06:47.741262373    9949 ev_posix.cc:174]            Using polling engine: epollex
D0803 03:06:47.741531372    9949 dns_resolver_ares.cc:483]   Using ares dns resolver
I0803 03:06:47.741662708    9949 init.cc:163]                grpc_init(void)
I0803 03:06:47.741691487    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I0803 03:06:47.741718462    9949 server_builder.cc:310]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 900000
I0803 03:06:47.741734599    9949 init.cc:163]                grpc_init(void)
I0803 03:06:47.741796740    9949 server.cc:1017]             grpc_server_create(0x7ffca61a6a10, (nil))
I0803 03:06:47.741847777    9949 server.cc:1000]             grpc_server_register_completion_queue(server=0x55ee8c6914a0, cq=0x55ee8c690f40, reserved=(nil))
I0803 03:06:47.741871868    9949 server.cc:1075]             grpc_server_register_method(server=0x55ee8c6914a0, method=/protoService.Permission/getPermission, host=(null), flags=0x00000000)
I0803 03:06:47.741888943    9949 metadata_array.cc:29]       grpc_metadata_array_init(array=0x55ee8c690850)
I0803 03:06:47.741905985    9949 server.cc:1075]             grpc_server_register_method(server=0x55ee8c6914a0, method=/protoService.Permission/createPermission, host=(null), flags=0x00000000)
I0803 03:06:47.741918882    9949 metadata_array.cc:29]       grpc_metadata_array_init(array=0x55ee8c691a10)
I0803 03:06:47.741970987    9949 server.cc:1075]             grpc_server_register_method(server=0x55ee8c6914a0, method=/protoService.User/getUser, host=(null), flags=0x00000000)
I0803 03:06:47.741985466    9949 metadata_array.cc:29]       grpc_metadata_array_init(array=0x55ee8c691b30)
I0803 03:06:47.741997741    9949 server.cc:1075]             grpc_server_register_method(server=0x55ee8c6914a0, method=/protoService.User/createUser, host=(null), flags=0x00000000)
I0803 03:06:47.742009919    9949 metadata_array.cc:29]       grpc_metadata_array_init(array=0x55ee8c691cb0)
I0803 03:06:47.742028454    9949 server.cc:1075]             grpc_server_register_method(server=0x55ee8c6914a0, method=/protoService.Auth/login, host=(null), flags=0x00000000)
I0803 03:06:47.742041441    9949 metadata_array.cc:29]       grpc_metadata_array_init(array=0x55ee8c691dd0)
I0803 03:06:47.742062388    9949 server_chttp2.cc:34]        grpc_server_add_insecure_http2_port(server=0x55ee8c6914a0, addr=0.0.0.0:8080)
I0803 03:06:47.742361633    9949 server.cc:1107]             grpc_server_start(server=0x55ee8c6914a0)
I0803 03:06:47.742411887    9949 metadata_array.cc:29]       grpc_metadata_array_init(array=0x55ee8c691ef0)
I0803 03:06:47.742429036    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:06:47.742509423    9949 server.cc:1529]             grpc_server_request_registered_call(server=0x55ee8c6914a0, rmp=0x55ee8c691950, call=0x55ee8c690830, deadline=0x55ee8c690840, initial_metadata=0x55ee8c690850, optional_payload=0x55ee8c690868, cq_bound_to_call=0x55ee8c692a50, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c690810)
I0803 03:06:47.742541106    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:06:47.742558030    9949 server.cc:1529]             grpc_server_request_registered_call(server=0x55ee8c6914a0, rmp=0x55ee8c691aa0, call=0x55ee8c6919f0, deadline=0x55ee8c691a00, initial_metadata=0x55ee8c691a10, optional_payload=0x55ee8c691a28, cq_bound_to_call=0x55ee8c692bc0, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c6919d0)
I0803 03:06:47.742572768    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:06:47.742587805    9949 server.cc:1529]             grpc_server_request_registered_call(server=0x55ee8c6914a0, rmp=0x55ee8c691c20, call=0x55ee8c691b10, deadline=0x55ee8c691b20, initial_metadata=0x55ee8c691b30, optional_payload=0x55ee8c691b48, cq_bound_to_call=0x55ee8c692f00, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c691af0)
I0803 03:06:47.742601930    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:06:47.742617680    9949 server.cc:1529]             grpc_server_request_registered_call(server=0x55ee8c6914a0, rmp=0x55ee8c691d10, call=0x55ee8c691c90, deadline=0x55ee8c691ca0, initial_metadata=0x55ee8c691cb0, optional_payload=0x55ee8c691cc8, cq_bound_to_call=0x55ee8c6a2990, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c691c70)
I0803 03:06:47.742631908    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:06:47.742646662    9949 server.cc:1529]             grpc_server_request_registered_call(server=0x55ee8c6914a0, rmp=0x55ee8c691e60, call=0x55ee8c691db0, deadline=0x55ee8c691dc0, initial_metadata=0x55ee8c691dd0, optional_payload=0x55ee8c691de8, cq_bound_to_call=0x55ee8c6a2cd0, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c691d90)
I0803 03:06:47.742660794    9949 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:06:47.742676574    9949 call_details.cc:31]         grpc_call_details_init(cd=0x55ee8c692930)
I0803 03:06:47.742694054    9949 server.cc:1480]             grpc_server_request_call(server=0x55ee8c6914a0, call=0x55ee8c691ed0, details=0x55ee8c692930, initial_metadata=0x55ee8c691ef0, cq_bound_to_call=0x55ee8c6a3010, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c691eb0)
I0803 03:06:47.742901199    9992 completion_queue.cc:963]    grpc_completion_queue_next(cq=0x55ee8c690f40, deadline=gpr_timespec { tv_sec: 37200, tv_nsec: 109180261, clock_type: 0 }, reserved=(nil))
Server listening on 0.0.0.0:8080
I0803 03:07:24.230780637    9992 call.cc:1526]               ops[0]: RECV_INITIAL_METADATA ptr=0x7f73f80076f8
I0803 03:07:24.230871304    9992 call.cc:1526]               ops[0]: RECV_MESSAGE ptr=0x7f73f8007718
I0803 03:07:24.230939938    9992 completion_queue.cc:688]    cq_end_op_for_next(cq=0x55ee8c690f40, tag=0x55ee8c691d90, error="No Error", done=0x7f740e0690e0, done_arg=0x55ee8c6a2e40, storage=0x55ee8c6a2e78)
I0803 03:07:24.230961778    9992 completion_queue.cc:1063]   RETURN_EVENT[0x55ee8c690f40]: OP_COMPLETE: tag:0x55ee8c691d90 OK
I0803 03:07:24.231047465    9992 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0803 03:07:24.231066771    9992 server.cc:1529]             grpc_server_request_registered_call(server=0x55ee8c6914a0, rmp=0x55ee8c691e60, call=0x55ee8c691db0, deadline=0x55ee8c691dc0, initial_metadata=0x55ee8c691dd0, optional_payload=0x55ee8c691de8, cq_bound_to_call=0x7f73f800a940, cq_for_notification=0x55ee8c690f40, tag=0x55ee8c691d90)
I0803 03:07:24.231085136   10032 completion_queue.cc:963]    grpc_completion_queue_next(cq=0x55ee8c690f40, deadline=gpr_timespec { tv_sec: 37236, tv_nsec: 597374095, clock_type: 0 }, reserved=(nil))
I0803 03:07:24.231129282    9992 call.cc:1922]               grpc_call_start_batch(call=0x7f73f8006c60, ops=0x7f73ffffeac0, nops=1, tag=0x7f73f8009120, reserved=(nil))
I0803 03:07:24.231143636    9992 call.cc:1526]               ops[0]: RECV_CLOSE_ON_SERVER cancelled=0x7f73f80091ac
I0803 03:07:24.735161592    9992 call.cc:1922]               grpc_call_start_batch(call=0x7f73f8006c60, ops=0x7f73ffffe560, nops=2, tag=0x7f73ffffe970, reserved=(nil))
I0803 03:07:24.735199808    9992 call.cc:1526]               ops[0]: SEND_INITIAL_METADATA(nil)
I0803 03:07:24.735219917    9992 call.cc:1526]               ops[1]: SEND_STATUS_FROM_SERVER status=16 details=user or password incorrect(nil)
I0803 03:07:24.735320064    9992 completion_queue.cc:770]    cq_end_op_for_pluck(cq=0x55ee8c6a2cd0, tag=0x7f73f8009120, error="No Error", done=0x7f740e062490, done_arg=0x7f73f80092c0, storage=0x7f73f8009310)
I0803 03:07:24.735374450    9992 completion_queue.cc:770]    cq_end_op_for_pluck(cq=0x55ee8c6a2cd0, tag=0x7f73ffffe970, error="No Error", done=0x7f740e062490, done_arg=0x7f73f80093a0, storage=0x7f73f80093f0)
I0803 03:07:24.735395448    9992 completion_queue.cc:1299]   RETURN_EVENT[0x55ee8c6a2cd0]: OP_COMPLETE: tag:0x7f73ffffe970 OK
I0803 03:07:24.735414135    9992 completion_queue.cc:1394]   grpc_completion_queue_shutdown(cq=0x55ee8c6a2cd0)
I0803 03:07:24.735426432    9992 completion_queue.cc:1299]   RETURN_EVENT[0x55ee8c6a2cd0]: OP_COMPLETE: tag:0x7f73f8009120 OK
I0803 03:07:24.735437331    9992 completion_queue.cc:1299]   RETURN_EVENT[0x55ee8c6a2cd0]: QUEUE_SHUTDOWN
I0803 03:07:24.735453650    9992 metadata_array.cc:34]       grpc_metadata_array_destroy(array=0x7f73f800a4c0)
I0803 03:07:24.735462627    9992 call.cc:573]                grpc_call_unref(c=0x7f73f8006c60)
I0803 03:07:24.735486442    9992 metadata_array.cc:34]       grpc_metadata_array_destroy(array=0x7f73f80076f8)
I0803 03:07:24.735511095    9992 metadata_array.cc:34]       grpc_metadata_array_destroy(array=0x7f73f800a4c0)
I0803 03:07:24.735522619    9992 completion_queue.cc:1400]   grpc_completion_queue_destroy(cq=0x55ee8c6a2cd0)
I0803 03:07:24.735532354    9992 completion_queue.cc:1394]   grpc_completion_queue_shutdown(cq=0x55ee8c6a2cd0)
I0803 03:07:24.735547392    9992 completion_queue.cc:963]    grpc_completion_queue_next(cq=0x55ee8c690f40, deadline=gpr_timespec { tv_sec: 37237, tv_nsec: 101838526, clock_type: 0 }, reserved=(nil))

```
On my client side I can prevent the user from doing this by freezing the screen and the button while the request is complete, but there is something I can do to prevent my backend from breaking and ending the execution due to this segfault.

thanks.

**Comment by theopencompany** [comment]
I was doing some research about this, and i found the issue:

my database connection pool is singleton thread safe, but mysql connector is not. so... if i start to making a crazy clicks on my login button with only 1 connection in the pool when the new request and thread from grpc try to access to the connection that is used by the old thread make the segfault in the new request grpc thread... that is not happen if i first create a pool for example with 10 connections because new thread use different connection pointer from the pool, but because i want to use this with google cloud run or aws fargate i cant wait for the initilization of the pool to start the service, for that reason i start the pool in other thread that works good... so for fix this issue im involving the mysql connector in a wrapper that is thread safe with mutex lock and unlock.

**Comment by theopencompany** [comment]
i close this because with my thread safe mysql client implementations all segfault are gone.
