### ISSUE TITLE
Grpc ssl self signed certclient verification is failing

### ISSUE THREAD

**Issue by ArturoGarciaRegueiro** [grpc/grpc#19875]
Hi,

I've done a self signed ssl cert for my grpc client/server connection but the same error keeps popping. 

Here it is the  log from client side: 

```
D0807 09:46:44.636038 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Users\ArturoGarcíaRegueiro\.nuget\packages\grpc.core\1.22.0\lib\netstandard2.0\../..\runtimes/win/native\grpc_csharp_ext.x64.dll"
D0807 09:46:44.668478 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0807 09:46:44.672889 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\native\dns_resolver.cc:280: Using native dns resolver
D0807 09:46:44.703004 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\native\dns_resolver.cc:242: Start resolving.
E0807 09:46:44.722050 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1238: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0807 09:46:44.722324 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1565164004.722000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0807 09:46:44.724602 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:1031: Connect failed: {"created":"@1565164004.722000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
E0807 09:46:44.734743 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1238: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0807 09:46:44.735286 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1565164004.735000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0807 09:46:44.736552 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:1031: Connect failed: {"created":"@1565164004.735000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
D0807 09:46:44.738200 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\native\dns_resolver.cc:224: In cooldown from last resolution (from 35 ms ago). Will resolve again in 965 ms
I0807 09:46:44.739222 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:970: Subchannel 0000025BEE1E0050: Retry in 99972 milliseconds
Exception encountered: Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 78
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Interceptors\InterceptingCallInvoker.cs:line 51
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Interceptors\InterceptingCallInvoker.cs:line 48
   at JwtTokenizerService.JwtTokenizerServiceClient.GetJwtToken(UserValues request, CallOptions options) in C:\Users\ArturoGarcíaRegueiro\source\repos\JwtTokenizerClient\JwtTokenizerClient\Protos\JwtTokenizerGrpc.cs:line 70
   at JwtTokenizerService.JwtTokenizerServiceClient.GetJwtToken(UserValues request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Users\ArturoGarcíaRegueiro\source\repos\JwtTokenizerClient\JwtTokenizerClient\Protos\JwtTokenizerGrpc.cs:line 66
   at JwtTokenizerClient.Program.Main(String[] args) in C:\Users\ArturoGarcíaRegueiro\source\repos\JwtTokenizerClient\JwtTokenizerClient\Program.cs:line 51
```

And the log in server side: 

```
D0807 09:46:44.724354 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1565164004.724000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1565164004.724000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}
D0807 09:46:44.726952 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\transport\chttp2\server\chttp2_server.cc:123: Handshaking failed: {"created":"@1565164004.724000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1565164004.724000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}
D0807 09:46:44.736511 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1565164004.736000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1565164004.736000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}
D0807 09:46:44.739036 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\transport\chttp2\server\chttp2_server.cc:123: Handshaking failed: {"created":"@1565164004.736000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1565164004.736000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}
```

**Comment by mhaidrygoog** [comment]
Could you please provide more info about your setup? What languages are being used for server and client side. Do you have a small PR to repro the issue? Thanks

**Comment by jtattermusch** [comment]
Also, please exactly describe how your keys were generated and which party is using what keys and certs. the term "self-signed" certs is often used to describe several different scenarios and the differences between them might matter.

**Comment by chinadragon0515** [comment]
I met the exactly same issue, I have added the certificate into trust store.
If I use dotnet client, the certificate can be trusted and validate passed.
But if I use th .Net framework client (Grpc.Core.Channel), the certificate always has the issue.

**Comment by markdroth** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
