### ISSUE TITLE
Basic C++ ios test fails

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#19949]
### What version of gRPC and what language are you using?
v1.23.x
 
### What operating system (Linux, Windows,...) and version?
build for ios
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
kokoro run
 
### What did you do?
run kokoro test
 
### What did you expect to see?
 build pass
 
### What did you see instead?
sponge link - https://sponge.corp.google.com/target?id=3f89af73-212b-4d66-89bf-72185abedd61&target=grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_cpp_ios&searchFor=

[10:36:33][ERROR] Failed to get build config
com.google.devtools.kokoro.config.ConfigException: Couldn't find build configuration grpc_basictests_cpp_ios under /tmp/workspace/workspace/grpc/core/pull_request/macos/grpc_basictests_cpp_ios/src/github/grpc/tools/internal_ci/macos/pull_request.
	at com.google.devtools.kokoro.config.BuildConfigReader.lambda$read$2(BuildConfigReader.java:54)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.google.devtools.kokoro.config.BuildConfigReader.read(BuildConfigReader.java:51)
	at com.google.devtools.kokoro.jenkins.plugin.kokorojob.store.NodeBuildConfigReader.invoke(NodeBuildConfigReader.java:39)
	at com.google.devtools.kokoro.jenkins.plugin.kokorojob.store.NodeBuildConfigReader.invoke(NodeBuildConfigReader.java:13)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.jenkinsci.remoting.kokoro.RpcSlaveEngine$1$1.run(RpcSlaveEngine.java:107)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to macos_external-prod-dynamic-qu-88558201(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:822)
	at hudson.FilePath.act(FilePath.java:985)
	at hudson.FilePath.act(FilePath.java:974)
	at com.google.devtools.kokoro.jenkins.plugin.kokorojob.store.ConfigStore.getKokoroBuildConfig(ConfigStore.java:102)
	at com.google.devtools.kokoro.jenkins.plugin.pipeline.KokoroFlowExecution.getBuildConfig(KokoroFlowExecution.java:649)
	at com.google.devtools.kokoro.jenkins.plugin.pipeline.KokoroFlowExecution.addPostScmSteps(KokoroFlowExecution.java:596)
	at com.google.devtools.kokoro.jenkins.plugin.pipeline.KokoroScmStepContext.onSuccess(KokoroScmStepContext.java:25)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rmstar** [comment]
`grpc_basictests_cpp_ios` is a new test that was was added recently in #19850. That commit didn't make it into 1.23, but the corresponding kokoro config exists in [google3](http://cl/261947910). There's only [one version](http://go/oneversion) of kokoro config in google3, so I don't think we can fix this issue.
