### ISSUE TITLE
LinkError: command 'aarch64-linux-gnu-g++' failed with exit status 1 and failed building wheel for grpcio

### ISSUE THREAD

**Issue by samhithaaaa** [grpc/grpc#20038]
unable to execute 'aarch64-linux-gnu-g++': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-WT9TE4/grpcio/setup.py", line 368, in <module>
        cmdclass=COMMAND_CLASS,
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-WT9TE4/grpcio/src/python/grpcio/commands.py", line 265, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "/tmp/pip-install-WT9TE4/grpcio/src/python/grpcio/support.py", line 109, in diagnose_build_ext_error
        "backtrace).\n\n{}".format(formatted))
    commands.CommandError:
    
    We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).
    
    Traceback (most recent call last):
      File "/tmp/pip-install-WT9TE4/grpcio/src/python/grpcio/commands.py", line 262, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 531, in build_extension
        target_lang=language)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 207, in link
        raise LinkError, msg
    LinkError: command 'aarch64-linux-gnu-g++' failed with exit status 1
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tf/venv/venc-tf-1.14/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-WT9TE4/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-WT9TE4/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-otPtXv/install-record.txt --single-version-externally-managed --compile --install-headers /home/tf/venv/venc-tf-1.14/include/site/python2.7/grpcio Check the logs for full command output.

This is issue I am facing.Anyone please help.

**Comment by lidizheng** [comment]
I'm confused by your description. In the first line, you said `arch64-linux-gnu-g++` not found. Did you installed it? Which command failed?

In general, you don't need to compile gRPC Python. If you do, that means something is wrong. Can you provide information about your platform and what you are trying to do?

**Comment by samhithaaaa** [comment]
> I'm confused by your description. In the first line, you said `arch64-linux-gnu-g++` not found. Did you installed it? Which command failed?
> 
> In general, you don't need to compile gRPC Python. If you do, that means something is wrong. Can you provide information about your platform and what you are trying to do?
my platform is armv8 ,64bit I am trying to build tensorflow 1.14 with bazel 0.24.1.I have the wheel package but while installing the wheel package i face this issue.

**Comment by samhithaaaa** [comment]
> > I'm confused by your description. In the first line, you said `arch64-linux-gnu-g++` not found. Did you installed it? Which command failed?
> > In general, you don't need to compile gRPC Python. If you do, that means something is wrong. Can you provide information about your platform and what you are trying to do?
> > my platform is armv8 ,64bit I am trying to build tensorflow 1.14 with bazel 0.24.1.I have the wheel package but while installing the wheel package i face this issue.

error:failed building wheel for grpcio

**Comment by samhithaaaa** [comment]
> > > I'm confused by your description. In the first line, you said `arch64-linux-gnu-g++` not found. Did you installed it? Which command failed?
> > > In general, you don't need to compile gRPC Python. If you do, that means something is wrong. Can you provide information about your platform and what you are trying to do?
> > > my platform is armv8 ,64bit I am trying to build tensorflow 1.14 with bazel 0.24.1.I have the wheel package but while installing the wheel package i face this issue.
> 
> error:failed building wheel for grpcio

**Comment by samhithaaaa** [comment]
![Screen Shot 2019-08-22 at 3 28 59 PM](https://user-images.githubusercontent.com/36496141/63554217-b8e9c000-c4f1-11e9-942e-d2303ac260a4.png)

**Comment by samhithaaaa** [comment]
This the scrrenshot

**Comment by samhithaaaa** [comment]
> This the scrrenshot

![image](https://user-images.githubusercontent.com/36496141/63554567-c2bff300-c4f2-11e9-96a1-65823d825aa8.png)

**Comment by lidizheng** [comment]
Can you include the full log? Better post it in https://gist.github.com/

**Comment by samhithaaaa** [comment]
> Can you include the full log? Better post it in https://gist.github.com/
  unable to execute 'aarch64-linux-gnu-g++': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jc4IvK/grpcio/setup.py", line 368, in <module>
        cmdclass=COMMAND_CLASS,
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-jc4IvK/grpcio/src/python/grpcio/commands.py", line 265, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "/tmp/pip-install-jc4IvK/grpcio/src/python/grpcio/support.py", line 109, in diagnose_build_ext_error
        "backtrace).\n\n{}".format(formatted))
    commands.CommandError:
    
    We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).
    
    Traceback (most recent call last):
      File "/tmp/pip-install-jc4IvK/grpcio/src/python/grpcio/commands.py", line 262, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "/home/tf/venv/venc-tf-1.14/local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 531, in build_extension
        target_lang=language)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 207, in link
        raise LinkError, msg
    LinkError: command 'aarch64-linux-gnu-g++' failed with exit status 1
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tf/venv/venc-tf-1.14/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jc4IvK/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jc4IvK/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-MggUu3/install-record.txt --single-version-externally-managed --compile --install-headers /home/tf/venv/venc-tf-1.14/include/site/python2.7/grpcio Check the logs for full command output.

**Comment by samhithaaaa** [comment]
Here you go

**Comment by lidizheng** [comment]
Can you please lint your comments... It is really hard to read. There is a preview tab in the UI.

Seems pip didn't print all necessary information. Can you download the source code wheel for [grpcio v1.23.0](https://files.pythonhosted.org/packages/b0/12/31d6d1faa6685465632458eecfc57b49b32ed65023abb75bc27113d6e449/grpcio-1.23.0.tar.gz), and pip install it?

```
pip install grpcio-1.23.0.tar.gz
```

**Comment by samhithaaaa** [comment]
> ```
> pip install grpcio-1.23.0.tar.gz
>this does not work either.same error

**Comment by samhithaaaa** [comment]
![image](https://user-images.githubusercontent.com/36496141/63618143-2f44fb80-c5a0-11e9-8480-4be84690a292.png)

**Comment by samhithaaaa** [comment]
i face new issue like .
ImportError: No module named cv2

**Comment by dyseo** [comment]
i have sams issue here, this issue already closed? i didn't see any hint
