### ISSUE TITLE
build: terminate called after throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by jengelh** [grpc/grpc#20033]
```
abuild@a4:~/rpmbuild/BUILD/grpc-1.23.0> make V=1 VERBOSE=1
echo " HAS_PKG_CONFIG = true, HAS_SYSTEM_OPENSSL_ALPN = true, HAS_SYSTEM_ZLIB = true, HAS_SYSTEM_PROTOBUF = true, HAS_SYSTEM_CARES = true, HAS_PROTOC = true, HAS_VALID_PROTOC = true," | tr , '\n' >cache.mk
mkdir -p `dirname /home/abuild/rpmbuild/BUILD/grpc-1.23.0/gens/src/proto/grpc/channelz/channelz.grpc.pb.cc`
protoc -Ithird_party/protobuf/src -I. --grpc_out=/home/abuild/rpmbuild/BUILD/grpc-1.23.0/gens --plugin=protoc-gen-grpc=/home/abuild/rpmbuild/BUILD/grpc-1.23.0/bins/opt/grpc_cpp_plugin src/proto/grpc/channelz/channelz.proto
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
```
Using protobuf-3.9.1 on openSUSE Tumbleweed. Sorry I can't provide more info at this time, the error message `Unknown error -1` is just useless, it does not even say what syscall it attempted to do that led to error -1 (`open`, `mkdir`, `stat`, anything). Compare that to e.g. `ls` (assuming unknown errno):

```
ls: cannot access 'xxx': Unknown error -2147xxxxx / No such file or directory
```

**Comment by jengelh** [comment]
```
abuild@a4:~/rpmbuild/BUILD/grpc-1.23.0> strace -e openat protoc -Ithird_party/protobuf/src -I. --grpc_out=/home/abuild/rpmbuild/BUILD/grpc-1.23.0/gens --plugin=protoc-gen-grpc=/home/abuild/rpmbuild/BUILD/grpc-1.23.0/bins/opt/grpc_cpp_plugin src/proto/grpc/channelz/channelz.proto
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libprotoc.so.20", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libprotobuf.so.20", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "src/proto/grpc/channelz/channelz.proto", O_RDONLY) = 3
openat(AT_FDCWD, "third_party/protobuf/src/src/proto/grpc/channelz/channelz.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "src/proto/grpc/channelz/channelz.proto", O_RDONLY) = 3
openat(AT_FDCWD, "third_party/protobuf/src/google/protobuf/any.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "google/protobuf/any.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/include/google/protobuf/any.proto", O_RDONLY) = 3
openat(AT_FDCWD, "third_party/protobuf/src/google/protobuf/duration.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "google/protobuf/duration.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/include/google/protobuf/duration.proto", O_RDONLY) = 3
openat(AT_FDCWD, "third_party/protobuf/src/google/protobuf/timestamp.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "google/protobuf/timestamp.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/include/google/protobuf/timestamp.proto", O_RDONLY) = 3
openat(AT_FDCWD, "third_party/protobuf/src/google/protobuf/wrappers.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "google/protobuf/wrappers.proto", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/include/google/protobuf/wrappers.proto", O_RDONLY) = 3
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
```

I am using the `https://github.com/grpc/grpc/archive/v1.23.0.tar.gz` tarball.

**Comment by luzpaz** [comment]
This issue is blocking downstream packaging efforts. Please raise priority, thank you.

**Comment by AspirinSJL** [comment]
Does this happen with v1.22?

**Comment by jengelh** [comment]
Apparently, it is caused by g++ `-flto`. gcc version 9.1.1 20190805 [gcc-9-branch revision 274114] is used.

```
abuild@a4:~/rpmbuild/BUILD/grpc-1.23.0> gdb bins/opt/grpc_cpp_plugin /var/core/'!home!abuild!rpmbuild!BUILD!grpc-1.23.0!bins!opt!grpc_cpp_plugin.28916'
GNU gdb (GDB; openSUSE Tumbleweed) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bins/opt/grpc_cpp_plugin...
[New LWP 28916]
Core was generated by `/home/abuild/rpmbuild/BUILD/grpc-1.23.0/bins/opt/grpc_cpp_plugin'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) up
#1  0x00007f3d384aa549 in __GI_abort () at abort.c:79
79      abort.c: No such file or directory.
(gdb) 
#2  0x00007f3d3786564b in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
95          abort();
(gdb) 
#3  0x00007f3d37871088 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
47            handler ();
(gdb) 
#4  0x00007f3d378710d3 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
57        __terminate (get_terminate ());
(gdb) 
#5  0x00007f3d37871305 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x21a7660, 
    tinfo=tinfo@entry=0x7f3d37999630 <typeinfo for std::system_error>, 
    dest=dest@entry=0x7f3d3789acc0 <std::system_error::~system_error()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
95        std::terminate ();
(gdb) 
#6  0x00007f3d3786816e in std::__throw_system_error (__i=-1)
    at /usr/src/debug/gcc9-9.1.1+r274111-1.1.x86_64/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/ext/new_allocator.h:89
89            ~new_allocator() _GLIBCXX_USE_NOEXCEPT { }
(gdb) 
#7  0x00007f3d37d7d9d5 in std::call_once<void (&)(std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*), std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*> (__once=..., __f=
    @0x7f3d37d45758: {void (std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*> *)} 0x7f3d37d45758 <google::protobuf::FileDescriptorTables::BuildLocationsByPath(std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*)>, __args#0=@0x7fffc95da558: 0x7fffc95da540)
    at /usr/include/c++/9/mutex:697
697             __throw_system_error(__e);
(gdb) 
#8  0x00007f3d37d7386b in google::protobuf::internal::call_once<std::once_flag&, void (&)(std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*), std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*> (args#0=..., 
    args#1=@0x7f3d37d45758: {void (std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*> *)} 0x7f3d37d45758 <google::protobuf::FileDescriptorTables::BuildLocationsByPath(std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*)>, args#2=@0x7fffc95da558: 0x7fffc95da540)
    at ./google/protobuf/stubs/once.h:46
46        std::call_once(std::forward<Args>(args)...);
(gdb) dow
#7  0x00007f3d37d7d9d5 in std::call_once<void (&)(std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*), std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*> (__once=..., 
    __f=@0x7f3d37d45758: {void (std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*> *)} 0x7f3d37d45758 <google::protobuf::FileDescriptorTables::BuildLocationsByPath(std::pair<google::protobuf::FileDescriptorTables const*, google::protobuf::SourceCodeInfo const*>*)>, __args#0=@0x7fffc95da558: 0x7fffc95da540)
    at /usr/include/c++/9/mutex:697
697             __throw_system_error(__e);
(gdb) p __e
$1 = -1
(gdb) l 680
675           __once_callable = std::__addressof(__callable);
676           __once_call = []{ (*(decltype(__callable)*)__once_callable)(); };
677     #else
678           unique_lock<mutex> __functor_lock(__get_once_mutex());
679           __once_functor = __callable;
680           __set_once_functor_lock_ptr(&__functor_lock);
681     #endif
682
683           int __e = __gthread_once(&__once._M_once, &__once_proxy);
```

So nothing to see here.
