### ISSUE TITLE
dart server occasionally crashes in interop_to_cloud tests: NoSuchMethodError: The method 'remove' was called on null.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20075]
https://source.cloud.google.com/results/invocations/11887490-ef6b-4c70-a316-8f3156cd476b/targets/github%2Fgrpc%2Finterop_test/tests

```
2019-08-26 00:32:34,074 Server listening on port 8080...
Socket error: HandshakeException: Connection terminated during handshake
Socket error: HandshakeException: Connection terminated during handshake
Unhandled exception:
NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove(":status")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:283:23)
#2      ServerHandler_._sendError (package:grpc/src/server/handler.dart:347:5)
#3      ServerHandler_._onResponse (package:grpc/src/server/handler.dart:236:7)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:114:18)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#18     TestService.streamingInputCall (file:///var/local/git/grpc-dart/interop/bin/server.dart)
<asynchronous suspension>
#19     ServiceMethod.handle (package:grpc/src/server/service.dart:61:20)
#20     ServerHandler_._startStreamingRequest (package:grpc/src/server/handler.dart:151:30)
#21     ServerHandler_._onDataIdle (package:grpc/src/server/handler.dart:128:5)
<asynchronous suspension>
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     grpcDecompressor.<anonymous closure> (package:grpc/src/shared/message.dart:77:12)
#28     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _GrpcMessageConversionSink._addHeaders (package:grpc/src/shared/streams.dart:121:10)
#36     _GrpcMessageConversionSink.add (package:grpc/src/shared/streams.dart:129:7)
#37     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#42     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#43     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#47     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
2019-08-26 00:32:34,074 FAILED: interop_server_dart [ret=255, pid=5969, time=418.5sec]
```

**Comment by jtattermusch** [comment]
@mit-mit @sigurdm

**Comment by jtattermusch** [comment]
@mit-mit @sigurdm, any ideas?

**Comment by jtattermusch** [comment]
I opened a new issue and I'll try to provide more info there: https://github.com/grpc/grpc/issues/21755
