### ISSUE TITLE
GRPC native method missing

### ISSUE THREAD

**Issue by phw198** [grpc/grpc#20230]
### What version of gRPC and what language are you using?
v1.22.0 for C#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Compiling in Visual Studio Express 2015.

### What did you do?
I have a GoogleStackDriver log4net appender defined as:
```
  <appender name="GoogleStackdriver" type="Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender,Google.Cloud.Logging.Log4Net">
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%property{CloudLogUuid} %-4timestamp [%thread] %-5level %logger - %message" />
    </layout>
    <projectId value="*****" />
    <logId type="log4net.Util.PatternString" value="%property{CloudLogId}" />
  </appender>
```
Since updating various `Google.Apis` libraries, the appender no longer initialises - see error stack below.

### What did you expect to see?
The GoogleStackdriver appender initialising successfully.

### What did you see instead?
```
Exception thrown: 'System.MissingMethodException' in Grpc.Core.dll
log4net:ERROR Could not create Appender [GoogleStackdriver] of type [Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender,Google.Cloud.Logging.Log4Net]. Reported error follows.
System.MissingMethodException: The native method "grpcsharp_batch_context_recv_message_next_slice_peek" does not exist
   at Grpc.Core.Internal.UnmanagedLibrary.GetNativeMethodDelegate[T](String methodName)
   at Grpc.Core.Internal.NativeMethods.GetMethodDelegate[T](UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeMethods..ctor(UnmanagedLibrary library)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, IEnumerable`1 channelOptions, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, IEnumerable`1 channelOptions)
   at Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.BuildLoggingServiceClient()
   at Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.ActivateOptions()
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
```

**Comment by phw198** [comment]
I have now also tested with v1.22.1 and v2.23.0 of `Grpc.Core` and the result is exactly the same.

**Comment by jskeet** [comment]
Could you clarify the situation the exact type of project you're building? Are you able to use a more modern Visual Studio build? Which version of .NET are you targeting? If we can reproduce the problem, it'll make it much easier to fix.

**Comment by phw198** [comment]
Thanks for such a quick response! It's a Windows Forms project that targets .Net 4.5 - it's hosted on GH. `XmlConfigurator.Configure()` is [called here](https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/src/OutlookGoogleCalendarSync/Program.cs#L221-L223) against [logger.xml](https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/src/OutlookGoogleCalendarSync/logger.xml).

I could certainly give VS Community 2019 a whirl if it's likely to help.

**Comment by jskeet** [comment]
Ah - I think I see the problem. It looks like you updated the copies of Grpc.Core.dll and Grpc.Core.Api.dll last month, but you didn't update the native files [under runtimes/win/native](https://github.com/phw198/OutlookGoogleCalendarSync/tree/master/src/OutlookGoogleCalendarSync/lib/runtimes/win/native)

In general I'd strongly recommend *not* keeping a local copy of the dependencies - at least not in the expanded form - but instead letting NuGet manage the files. If you need to be able to build without an internet connection, I'd suggest creating a directory to host the `.nupkg` files and configure that as a local NuGet source, which means you can update packages on a per-package basis rather than updating the individual files.
