### ISSUE TITLE
Crash (SIGSEGV) in ServerInterface::Shutdown() of Synchronous gRPC server, Linux, C++

### ISSUE THREAD

**Issue by pkbehera** [grpc/grpc#20289]
### What version of gRPC and what language are you using?
C++, gRPC version: commit 5d57a8d09a7f7202ba8eaa56b3b88a5da05ad057 (tag: v1.13.0)

### What operating system (Linux, Windows,...) and version?
Linux, Ubuntu 16.04.6 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version: 7.3.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

We have written a ***synchronous*** gRPC service implementing the [gNMI service](https://github.com/openconfig/gnmi).

We are trying to test this service interface in a c++ gTest.

- Create and start an instance of the gRPC/gNMI service
- Do the tests
- Stop the gRPC/gNMI service, by calling `ServerInterface::Shutdown()`

### What did you expect to see?
gRPC/gNMI service should shutdown fine and the test should pass. 

### What did you see instead?
The test fails intermittently about 5 times in 100 times, a SIGSEGV is thrown from `Shutdown()`, here is the back trace:
```
Core was generated by `bazel-bin/devmgr/devmgr_gnmi_test --gtest_repeat=100'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f251ddbe3d7 in gpr_unref ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs$
Uh10_Sx86_U64_Susr_Slib/libgpr.so.6
[Current thread is 1 (LWP 29583)]
warning: File "/var/cache/tarana/releases/TCN.A3.H10.XXX.0.410.000.00/host/x86_64/x86_64-tarana-linux-gnu/x86_64-tarana-linux-gnu/sysroot/lib/libstdc++.so.6.0.24-gdb.py" auto-loading has 
been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
(gdb) bt   
#0  0x00007f251ddbe3d7 in gpr_unref ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs$
Uh10_Sx86_U64_Susr_Slib/libgpr.so.6
#1  0x00007f251dcc99c0 in grpc_error_unref(grpc_error*) ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs$
Uh10_Sx86_U64_Susr_Slib/libgrpc++_cronet.so.1
#2  0x00007f251dcc9a1e in grpc_error_unref(grpc_error*) ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs$
Uh10_Sx86_U64_Susr_Slib/libgrpc++_cronet.so.1
#3  0x00007f251dcc9a1e in grpc_error_unref(grpc_error*) ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs$
Uh10_Sx86_U64_Susr_Slib/libgrpc++_cronet.so.1
#4  0x00007f251dcd4d09 in grpc_core::ExecCtx::Flush() ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs_
Uh10_Sx86_U64_Susr_Slib/libgrpc++_cronet.so.1
#5  0x00007f251dcf5f6c in grpc_server_shutdown_and_notify ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs_
Uh10_Sx86_U64_Susr_Slib/libgrpc++_cronet.so.1
#6  0x00007f251dd9e8e8 in grpc::Server::ShutdownInternal(gpr_timespec) ()
   from /var/tmp/prasanta.behera/dff6c68026f1f353/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-bn_h10/bin/devmgr/../_solib_k8/_U@cfs_Uh10_S_S_Cgrpc++___Uexternal_Scfs_
Uh10_Sx86_U64_Susr_Slib/libgrpc++.so.1
#7  0x00007f251f19155f in grpc::ServerInterface::Shutdown<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > > (
    deadline=..., this=0x19c69b0) at external/cfs_h10/x86_64/usr/include/grpcpp/impl/codegen/server_interface.h:63
#8  cmf::SyncService::Stop (this=0x19bc440) at cmf/sync_service.cpp:114
#9  0x00000000004d3c25 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#10 0x00000000004ce422 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#11 0x00000000004b4409 in testing::Test::Run() ()
#12 0x00000000004b4c28 in testing::TestInfo::Run() ()
#13 0x00000000004b524d in testing::TestCase::Run() ()
#14 0x00000000004bbb13 in testing::internal::UnitTestImpl::RunAllTests() ()
#15 0x00000000004d4c35 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::
UnitTestImpl::*)(), char const*) ()
#16 0x00000000004cf16e in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::Uni
tTestImpl::*)(), char const*) ()
#17 0x00000000004ba844 in testing::UnitTest::Run() ()
#18 0x0000000000490620 in RUN_ALL_TESTS () at external/cfs_h10/x86_64/usr/include/gtest/gtest.h:2233
#19 main (argc=<optimized out>, argv=0x7fff99aaec48) at devmgr/device_manager_gnmi_test.cpp:194
```
### Anything else we should know about your project / environment?
- We **have also tried** `Shutdown` **with deadline**, `ServerInterface::Shutdown(const T &deadline)` but still not able get around the crash.
- We use bazel to build our c++ code inside a docker instance running Linux (Ubuntu 16.04.6 LTS)

**Comment by karthikravis** [comment]
pkbehera@ - can you try the latest gRPC version and see if this issue is reproducible? will help us narrow down the issue.

**Comment by markdroth** [comment]
No response from user, assuming stale.
