### ISSUE TITLE
Unity build linker error for Windows Standalone/HoloLens 1 & 2 ( x86 & x86_64 )

### ISSUE THREAD

**Issue by aleneum** [grpc/grpc#20344]
### What version of gRPC and what language are you using?

* C#
* 1.25-dev
* Unity 2019.2.6f1

### What operating system (Linux, Windows,...) and version?

* Windows 10
* SDK 10.0.17763.0 (x86)
* SDK 10.0.18362.0 (x64)

### What runtime / compiler are you using (e.g. python version or version of gcc)

* VS Toolset v142

### What did you do?

* Created empty Unity project
* Copied Plugins folder from this [artifact](https://packages.grpc.io/archive/2019/09/5f11fae4d20aba502b317919a051b18056c8ae17-f25d2c07-b548-44a1-870c-f2c2d464a034/csharp/grpc_unity_package.2.25.0-dev.zip) of this [build](https://packages.grpc.io/archive/2019/09/5f11fae4d20aba502b317919a051b18056c8ae17-f25d2c07-b548-44a1-870c-f2c2d464a034/index.xml#) into Unity Assets folder.
* Added `Plugins\Grpc.Core\runtimes\win\x86\grpc_csharp_ext` to 'Any Platform -> x86'
* Added `Plugins\Grpc.Core\runtimes\win\x64\grpc_csharp_ext` to 'Any Platform -> x64'
* Added `Plugins\Grpc.Core\runtimes\grpc_csharp_ext_dummy` to `Standalon` and `WSA` with `Any SDK`
* Added `RPCServer.cs` to `Assets\Scripts` and added it to the Scene:

```
using UnityEngine;
using Grpc.Core;

public class RPCServer: MonoBehaviour
{
    public Server _server;

    protected void Awake()
    {
        Debug.Log("Init RPC Server");
        _server = new Server
        {
            Ports = { new ServerPort("localhost", 12345, ServerCredentials.Insecure) }
        };
        Debug.Log("RPC Server initialized");

    }
}
```

### What did you expect to see?

* Compilation success

### What did you see instead?

x86:
```
1>Creating library D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\Win32\Debug\linkresult_D88CFD5142EDC344E98E9548C1260915\GameAssembly.lib and object D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\Win32\Debug\linkresult_D88CFD5142EDC344E98E9548C1260915\GameAssembly.exp
1>6860474D8DC7A65FE4EE10F1482E5E5F.obj : error LNK2019: unresolved external symbol _grpcsharp_init@0 referenced in function _DllImportsFromStaticLib_grpcsharp_init_mD33485A76947BECB3FB8D588729F5A75DBF058E7
1>  Hint on symbols that are defined and could potentially match:
1>    _grpcsharp_init
1>6860474D8DC7A65FE4EE10F1482E5E5F.obj : error LNK2019: unresolved external symbol _grpcsharp_shutdown@0 referenced in function _DllImportsFromStaticLib_grpcsharp_shutdown_m2238A66AFFCC96D5BD4A30FBD2A5DE8FD10D50F5
1>  Hint on symbols that are defined and could potentially match:
1>    _grpcsharp_shutdown
1>6860474D8DC7A65FE4EE10F1482E5E5F.obj : error LNK2019: unresolved external symbol _grpcsharp_version_string@0 referenced in function _DllImportsFromStaticLib_grpcsharp_version_string_mBA017FAEEF230F896AFE112589C7758B2A1E020A
1>  Hint on symbols that are defined and could potentially match:
1>    _grpcsharp_version_string
...
1>6860474D8DC7A65FE4EE10F1482E5E5F.obj : error LNK2019: unresolved external symbol _grpcsharp_test_call_start_unary_echo@24 referenced in function _DllImportsFromStaticLib_grpcsharp_test_call_start_unary_echo_mACA7A3152CFE80D962D680C17AB5E0FBD6CAAC3B
1>  Hint on symbols that are defined and could potentially match:
1>    _grpcsharp_test_call_start_unary_echo
1>7A26A50001DCF70793854F547D470510.obj : error LNK2019: unresolved external symbol _dlopen@8 referenced in function _Mono_dlopen_mD32390860E62629D34C5680BB1A4D8737986E725
1>7A26A50001DCF70793854F547D470510.obj : error LNK2019: unresolved external symbol _dlerror@0 referenced in function _Mono_dlerror_m7A2342CF799D2F296D8FEE7B9AA56FCA687913F5
1>7A26A50001DCF70793854F547D470510.obj : error LNK2019: unresolved external symbol _dlsym@8 referenced in function _Mono_dlsym_m3BFEF9952963669C7B0FC7AA527945E796CF9BCC
1>D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\Win32\Debug\linkresult_D88CFD5142EDC344E98E9548C1260915\GameAssembly.dll : fatal error LNK1120: 106 unresolved externals
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
1>   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
1>   at il2cpp.Program.DoRun(String[] args)
1>   at il2cpp.Program.Run(String[] args)
1>   at il2cpp.Program.Main(String[] args)
1>
1>Unhandled Exception:
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(49,5): error MSB3073: The command ""D:\workspace\GrpcUnity\Builds\Il2CppOutputProject\\IL2CPP\build\il2cpp.exe" --libil2cpp-static --compile-cpp -architecture=x86 -configuration=Debug -platform=winrt -outputpath="D:\workspace\GrpcUnity\Builds\\build\bin\Win32\Debug\GameAssembly.dll" --data-folder="D:\workspace\GrpcUnity\Builds\\build\bin\Win32\Debug\\" -cachedirectory="D:\workspace\GrpcUnity\Builds\\build\obj\il2cppOutputProject\Win32\Debug\\" -generatedcppdir="D:\workspace\GrpcUnity\Builds\Il2CppOutputProject\\Source"  --profiler-report --additional-defines=WINDOWS_UWP --additional-defines=UNITY_UWP --additional-defines=UNITY_WSA_10_0 --additional-defines=UNITY_WSA --additional-defines=UNITY_WINRT --additional-defines=PLATFORM_WINRT -dotnetprofile=unityaot -verbose --map-file-parser="D:\workspace\GrpcUnity\Builds\Il2CppOutputProject\\IL2CPP\MapFileParser\MapFileParser.exe" -forcerebuild" exited with code -532462766.
1>Done building project "Il2CppOutputProject.vcxproj" -- FAILED.
```

x64
```
1>Creating library D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.lib and object D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.exp
1>3B616D723DD5AFFC3EEB7E766F8D9807.obj : error LNK2019: unresolved external symbol dlopen referenced in function Mono_dlopen_mD32390860E62629D34C5680BB1A4D8737986E725
1>3B616D723DD5AFFC3EEB7E766F8D9807.obj : error LNK2019: unresolved external symbol dlerror referenced in function Mono_dlerror_m7A2342CF799D2F296D8FEE7B9AA56FCA687913F5
1>3B616D723DD5AFFC3EEB7E766F8D9807.obj : error LNK2019: unresolved external symbol dlsym referenced in function Mono_dlsym_m3BFEF9952963669C7B0FC7AA527945E796CF9BCC
1>D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.dll : fatal error LNK1120: 3 unresolved externals
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
1>   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
1>   at il2cpp.Program.DoRun(String[] args)
1>   at il2cpp.Program.Run(String[] args)
1>   at il2cpp.Program.Main(String[] args)
1>
1>Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX64\x64\link.exe /out:"D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.dll" /DEBUG:FASTLINK /INCREMENTAL:NO /LARGEADDRESSAWARE /NXCOMPAT /DYNAMICBASE /NOLOGO /TLBID:1 /HIGHENTROPYVA /DLL /NODEFAULTLIB:uuid.lib "Shcore.lib" "WindowsApp.lib" "Crypt32.lib" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\lib\x64\store" /APPCONTAINER /SUBSYSTEM:WINDOWS /NODEFAULTLIB:ole32.lib /NODEFAULTLIB:kernel32.lib /NODEFAULTLIB:msvcrt.lib @"C:\Users\avikom_admin\AppData\Local\Temp\tmpEA7A.tmp"
1>
1>Creating library D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.lib and object D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.exp
1>3B616D723DD5AFFC3EEB7E766F8D9807.obj : error LNK2019: unresolved external symbol dlopen referenced in function Mono_dlopen_mD32390860E62629D34C5680BB1A4D8737986E725
1>3B616D723DD5AFFC3EEB7E766F8D9807.obj : error LNK2019: unresolved external symbol dlerror referenced in function Mono_dlerror_m7A2342CF799D2F296D8FEE7B9AA56FCA687913F5
1>3B616D723DD5AFFC3EEB7E766F8D9807.obj : error LNK2019: unresolved external symbol dlsym referenced in function Mono_dlsym_m3BFEF9952963669C7B0FC7AA527945E796CF9BCC
1>D:\workspace\GrpcUnity\Builds\build\obj\il2cppOutputProject\x64\Debug\linkresult_E66935DFECF713A67C1DEF87496019C7\GameAssembly.dll : fatal error LNK1120: 3 unresolved externals
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
1>   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
1>   at il2cpp.Program.DoRun(String[] args)
1>   at il2cpp.Program.Run(String[] args)
1>   at il2cpp.Program.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(49,5): error MSB3073: The command ""D:\workspace\GrpcUnity\Builds\Il2CppOutputProject\\IL2CPP\build\il2cpp.exe" --libil2cpp-static --compile-cpp -architecture=x64 -configuration=Debug -platform=winrt -outputpath="D:\workspace\GrpcUnity\Builds\\build\bin\x64\Debug\GameAssembly.dll" --data-folder="D:\workspace\GrpcUnity\Builds\\build\bin\x64\Debug\\" -cachedirectory="D:\workspace\GrpcUnity\Builds\\build\obj\il2cppOutputProject\x64\Debug\\" -generatedcppdir="D:\workspace\GrpcUnity\Builds\Il2CppOutputProject\\Source"  --profiler-report --additional-defines=WINDOWS_UWP --additional-defines=UNITY_UWP --additional-defines=UNITY_WSA_10_0 --additional-defines=UNITY_WSA --additional-defines=UNITY_WINRT --additional-defines=PLATFORM_WINRT -dotnetprofile=unityaot -verbose --map-file-parser="D:\workspace\GrpcUnity\Builds\Il2CppOutputProject\\IL2CPP\MapFileParser\MapFileParser.exe" -forcerebuild" exited with code -532462766.
1>Done building project "Il2CppOutputProject.vcxproj" -- FAILED.
```

### Anything else we should know about your project / environment?

I tried to add `grpc_csharp_ext_dummy` as this used to solve issues for Android and Il2CPP. As seen in the output for x86, it is recognized as a candidate but not used. The `x64` does not have the linker issues related to grpc functions but still returns linking issues with `_Mono_dlsym`, `_dlerror`, `_dlopen`

In case I should try something: I managed to build `grpc_csharp_ext` for `x64 (net45)` with `\tools\run_tests\run_tests.py` but  could not build with arch x86/win32 since the scripts reports that this arch is not supported.

**Comment by darshitg** [comment]
Having the same LNK errors ...

**Comment by aleneum** [comment]
Hi @darshitg,

 my workaround for this problem involves compiling a Grpc.Core.dll without the Mono and DllImportsFromStaticLib which is used for WSA builds:

* Download a daily build unity package (e.g. [this](https://packages.grpc.io/archive/2019/10/8853754e8caa0b2ffb3ab0e25514f3f7612ebf7a-d6090f79-7b70-429d-a477-9df736e4941a/index.xml) one) and unzip it
* clone grpc and checkout the daily build commit: `git checkout 8853754e8caa0b2ffb3ab0e25514f3f7612ebf7a`
* init submodules: `git submodule update --init`
* build `grpc_charp_ext`: `python tools/run_tests/run_tests.py -l csharp -c opt --build_only`
* Apply [grpc-no-static.patch.txt](https://github.com/grpc/grpc/files/3921123/grpc-no-static.patch.txt)
* Open Grpc.sln and compile a Release build
* Copy the resulting Grpc.Core.dll into Plugins/Grcp.Core/lib/net45_wsa of the downloaded package
* Copy the Plugins folder into your Unity project
* Make sure that Grpc.Core.dll in the folder net45_wsa is only used for WSA builds and the original build EXCLUDES Grpc.Core.dll in net45_wsa: ![Grpc Core_wsa](https://user-images.githubusercontent.com/205986/70131567-cda62a00-1682-11ea-81c0-f9c1b18a921f.png)
* Make sure that grpc_charp_ext in Grpc.Core/runtimes/win/x86 and x64 is exported correctly (correct arch) for WSA: ![grpc_cscharp_ext](https://user-images.githubusercontent.com/205986/70131566-cda62a00-1682-11ea-8a1d-ab7e34f979e5.png)

**Comment by Noemata** [comment]
Because reflection is used to resolve assemblies in parts of the grpc DLL loader code, IL2CPP will not generate correct code for assembly name resolution.  Fixes for this have been described elsewhere.  Filter with UWP to see the workaround code.

**Comment by markdroth** [comment]
PLEASE DO NOT POST A QUESTION HERE.
This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by amlinux** [comment]
Could you explain why you closed this issue? It's a linker bug that also affects my project.

**Comment by Noemata** [comment]
It's not a linker bug.  Code changes to the grpc managed layer are required to correct this problem.  Look for my other postings for full details.  I outlined the fix.  Don't have the link handy.
