### ISSUE TITLE
cloud_to_prod js test failure 

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#20395]
https://source.cloud.google.com/results/invocations/50f5e521-6f73-40da-b06b-d231ded590f3/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_prod_auth:nodepurejs:default:compute_engine_creds:tls;row=1

```
assert.js:749
    throw newErr;
    ^
AssertionError [ERR_ASSERTION]: ifError got unwanted exception: No connection established
    at /var/local/git/grpc-node/test/interop/interop_client.js:425:12
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/client.js:97:17)
    at Http2CallStream.call.on (/var/local/git/grpc-node/packages/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:194:15)
    at process.nextTick (/var/local/git/grpc-node/packages/grpc-js/build/src/call-stream.js:75:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by yashykt** [comment]
Similar error - https://source.cloud.google.com/results/invocations/ce5e98e0-e44f-4aa9-a753-12a23c7892fb/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log
 
2019-09-27 12:04:50,318 assert.js:85
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual
- ''
