### ISSUE TITLE
ruby_linux_x64_centos6 distribtest is failing on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20508]
https://source.cloud.google.com/results/invocations/1f7d7a7f-ede9-4e8d-9766-786aac2dafeb/targets/github%2Fgrpc/tests

```
Bundle complete! 3 Gemfile dependencies, 7 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
+ bundle exec ./distribtest.rb
bundler: failed to load command: ./distribtest.rb (./distribtest.rb)
LoadError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/local/rvm/gems/ruby-2.3.8/gems/grpc-1.25.0.dev-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so) - /usr/local/rvm/gems/ruby-2.3.8/gems/grpc-1.25.0.dev-x86_64-linux/src/ruby/lib/grpc/2.3/grpc_c.so
  /usr/local/rvm/gems/ruby-2.3.8/gems/grpc-1.25.0.dev-x86_64-linux/src/ruby/lib/grpc/grpc.rb:20:in `require'
  /usr/local/rvm/gems/ruby-2.3.8/gems/grpc-1.25.0.dev-x86_64-linux/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.8/gems/grpc-1.25.0.dev-x86_64-linux/src/ruby/lib/grpc.rb:19:in `require_relative'
  /usr/local/rvm/gems/ruby-2.3.8/gems/grpc-1.25.0.dev-x86_64-linux/src/ruby/lib/grpc.rb:19:in `<top (required)>'
  /var/local/git/grpc/test/distrib/ruby/distribtest.rb:17:in `require'
  /var/local/git/grpc/test/distrib/ruby/distribtest.rb:17:in `<top (required)>'
```

**Comment by jtattermusch** [comment]
I'm not 100%, but this was likely introduced by https://github.com/grpc/grpc/pull/20441 

or some other PR in this diff https://github.com/grpc/grpc/compare/6c2eb034f7159d3c74509a35e47bd0e1605de29e...c8c755ac9de28f810af44b1939265a3414a3404c

**Comment by veblush** [comment]
thanks for report. PR (https://github.com/grpc/grpc/pull/20496) to fix the problem is in progress.

**Comment by veblush** [comment]
Fixed
