### ISSUE TITLE
npm ERR! Failed at the grpc@1.24.0 install script.

### ISSUE THREAD

**Issue by huturen** [grpc/grpc#20534]
Error as below:
```
npm ERR! Failed at the grpc@1.24.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-09T11_59_21_558Z-debug.log
Task quited with error: Task end with error: Error: Command failed: npm --registry=http://r.npm.oa.com install --production In file included from ../deps/grpc/third_party/upb/upb/msg.h:14:0, from ../deps/grpc/third_party/upb/upb/generated_util.h:10, from ../deps/grpc/src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12, from ../deps/grpc/src/core/tsi/alts/handshaker/transport_security_common_api.h:29, from ../deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26, from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.h:26, from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.cc:21: ../deps/grpc/third_party/upb/upb/upb.h:27:28: fatal error: upb/port_def.inc: No such file or directory compilation terminated. make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1 gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23) gyp ERR! stack at ChildProcess.emit (events.js:198:13) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) gyp ERR! System Linux 3.10.107-1-tlinux2-0048 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64" gyp ERR! cwd ~/dataServer/dataServer/src/node_modules/grpc gyp ERR! node -v v10.16.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1) node-pre-gyp ERR! stack at ChildProcess. (~/dataServer/dataServer/src/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29) node-pre-gyp ERR! stack at ChildProcess.emit (events.js:198:13) node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:982:16) node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) node-pre-gyp ERR! System Linux 3.10.107-1-tlinux2-0048 node-pre-gyp ERR! command "/usr/local/bin/node" "~/dataServer/dataServer/src/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library" node-pre-gyp ERR! cwd ~/dataServer/dataServer/src/node_modules/grpc node-pre-gyp ERR! node -v v10.16.0 node-pre-gyp ERR! node-pre-gyp -v v0.13.0 node-pre-gyp ERR! not ok npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! grpc@1.24.0 install: `node-pre-gyp install --fallback-to-build --library=static_library` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the grpc@1.24.0 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2019-10-09T11_59_21_558Z-debug.log (2)
```
dependency tree like below:
```
➜  DataServer git:(master) ✗ npm ls grpc 
dataserver@1.0.0 ~/DataServer
└─┬ @lag/ad-api@1.2.3
  └─┬ google-ads-api@3.4.2
    └─┬ google-ads-node@1.13.8
      └── grpc@1.24.0 
```

**Comment by huturen** [comment]
Fixed it after degrading to `"grpc": "1.23.3"`
```
 "dependencies": {
  ...
  "grpc": "1.23.3",
  ...
}

➜  DataServer git:(master) ✗ npm ls grpc 
dataserver@1.0.0 ~/DataServer
├─┬ @lag/ad-api@1.2.3
│ └─┬ google-ads-api@3.4.2
│   └─┬ google-ads-node@1.13.8
│     └── grpc@1.23.3  deduped
└── grpc@1.23.3 
```

**Comment by nuri-engin** [comment]
I got similar error for installing `grpc@1.24.0` during `npm install --save firebase`.
I just upgrade NodeJS version from v8* to latest v10 and problem solved.

**Comment by huturen** [comment]
> I got similar error for installing `grpc@1.24.0` during `npm install --save firebase`.
> I just upgrade NodeJS version from v8* to latest v10 and problem solved.

@nuri-engin I got this error on NodeJS version **v10.16.0**.

Maybe it's a bug with `grpc@1.24.0`.

**Comment by SmirnovM91** [comment]
any updates?

**Comment by mdenissov** [comment]
I got similar error for npm install --save firebase
Linux 4.4.0-101-generic
node v11.12.0
npm  v6.7.0

**Comment by Katsukiniwa** [comment]
I got same error when tried `npm install`
My local enviroment is
 - macOS Mojave version 10.14.6
 - node v10.16.0
 - npm v6.12.0
Who know how to solve this error ???

**Comment by scriptPilot** [comment]
Same issue on my side while installing latest Firebase ...

**Comment by Aimeelynnramirez** [comment]
I had the same problem but I just downgraded and it worked. 🤷

> Just downgrade your Node.js version . And try to use node-v6.9.0 version.

[#8495](https://github.com/grpc/grpc/issues/8495)

**Comment by crudexec** [comment]
same issue on my end and its failing on my heroku build.

**Comment by micah-akpan** [comment]
I fixed this error by downgrading my node version from the latest (13.1.0) to 12.13.0
