### ISSUE TITLE
Build error for py_grpc_library bazel target on windows

### ISSUE THREAD

**Issue by gallmerci** [grpc/grpc#20773]
### What version of gRPC and what language are you using?
Recent commit 018580fb89fa66bfb724d3d0e51aea1aa6474ca1
Python

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.7.3
Visual Studio Build Tools 2019
Bazel 1.1.0

### What did you do?

1. Create a rpc service in a service.proto file and create a bazel BUILD file
```
proto_library(
    name = "service_proto",
    srcs = ["service.proto"],
)
py_proto_library(
    name = "service_py_pb2",
    deps = [":service_proto"]
)
py_grpc_library(
    name = "service_py_pb2_grpc",
    srcs = [":service_proto"],
    deps = [":service_py_pb2"],
)
```
2. Create a WORKSPACE file (this include the fix from https://github.com/grpc/grpc/pull/20586):
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "bazel_federation",
    url = "https://github.com/bazelbuild/bazel-federation/releases/download/0.0.1/bazel_federation-0.0.1.tar.gz",
    sha256 = "506dfbfd74ade486ac077113f48d16835fdf6e343e1d4741552b450cfc2efb53",
)
http_archive(
    name = "rules_proto",
    sha256 = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208",
    strip_prefix = "rules_proto-97d8af4dc474595af3900dd85cb3a29ad28cc313",
    urls = [
      "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
       "https://github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
    ],
)
load("@bazel_federation//:repositories.bzl", "rules_python")
rules_python()
load("@bazel_federation//setup:rules_python.bzl",  "rules_python_setup")
rules_python_setup()
http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-master",
    urls = ["https://github.com/grpc/grpc/archive/master.zip"],
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
load("@upb//bazel:workspace_deps.bzl", "upb_deps")
load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")
http_archive(
    name = "build_bazel_apple_support",
    urls = [
        "https://github.com/bazelbuild/apple_support/releases/download/0.7.1/apple_support.0.7.1.tar.gz",
    ],
    sha256 = "122ebf7fe7d1c8e938af6aeaee0efe788a3a2449ece5a8d6a428cb18d6f88033",
)
load("@build_bazel_apple_support//lib:repositories.bzl", "apple_support_dependencies")
protobuf_deps()
upb_deps()
api_dependencies()
go_rules_dependencies()
go_register_toolchains()
apple_rules_dependencies()
apple_support_dependencies()
```
3. Build the target with `bazel build //:service_py_pb2_grpc`

### What did you expect to see?
Successful build.

### What did you see instead?
```
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "../external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 281   
                _create_single_version_package(<5 more arguments>)
        File "../external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 263, in _create_single_version_package
                bin_path_key(repository_ctx, <1 more arguments>)
'string' object is not callable
ERROR: ../external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/BUILD.bazel:5:1: @com_github_grpc_grpc//src/python/grpcio/grpc/_cython:cygrpc.so depends on @local_config_python//:python_headers in repository @local_config_python which failed to fetch. no such package '@local_config_python//': Traceback (most recent call last):
        File "../external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 281   
                _create_single_version_package(<5 more arguments>)
        File "../external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 263, in _create_single_version_package
                bin_path_key(repository_ctx, <1 more arguments>)
'string' object is not callable
ERROR: Analysis of target '//proto:service_py_pb2_grpc' failed; build aborted: no such package '@local_config_python//': Traceback (most recent call last):
        File "../external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 281   
                _create_single_version_package(<5 more arguments>)
        File "../external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 263, in _create_single_version_package
                bin_path_key(repository_ctx, <1 more arguments>)
'string' object is not callable
```
This seems to be cause by some error in this [line](https://github.com/grpc/grpc/blob/018580fb89fa66bfb724d3d0e51aea1aa6474ca1/third_party/py/python_configure.bzl#L263). After changing it to

`python_import_lib_name = _get_python_import_lib_name(repository_ctx, python_bin, bin_path_key)`

I get the next error:

```
INFO: From Compiling external/com_github_grpc_grpc/third_party/address_sorting/address_sorting_posix.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
INFO: From Compiling external/com_github_grpc_grpc/third_party/address_sorting/address_sorting.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
INFO: From Compiling external/com_github_grpc_grpc/third_party/address_sorting/address_sorting_windows.c:
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
ERROR: ../external/com_github_grpc_grpc/third_party/address_sorting/BUILD:45:1: Linking of rule 
'@com_github_grpc_grpc//third_party/address_sorting:address_sorting' failed (Exit 1120)
address_sorting.obj : error LNK2019: unresolved external symbol __imp_htonl referenced in function in6_is_addr_loopback
address_sorting_windows.obj : error LNK2019: unresolved external symbol __imp_closesocket referenced in function address_sorting_create_source_addr_factory_for_current_platform
address_sorting_windows.obj : error LNK2019: unresolved external symbol __imp_connect referenced in function address_sorting_create_source_addr_factory_for_current_platform
address_sorting_windows.obj : error LNK2019: unresolved external symbol __imp_getsockname referenced in function address_sorting_create_source_addr_factory_for_current_platform
address_sorting_windows.obj : error LNK2019: unresolved external symbol __imp_socket referenced in function address_sorting_create_source_addr_factory_for_current_platform
bazel-out\x64_windows-fastbuild\bin\external\com_github_grpc_grpc\third_party\address_sorting\address_sorting.dll : fatal error LNK1120: 5 unresolved externals
Target //proto:service_py_pb2_grpc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 108.487s, Critical Path: 7.64s
INFO: 670 processes: 670 local.
FAILED: Build did NOT complete successfully
```

There seems to be a similar [closed issue](https://github.com/grpc/grpc/issues/15333)  but which did not build via bazel. So I assume some environment config is maybe off when building with bazel.

### Anything else we should know about your project / environment?
I also tested it successfully with bazel on linux using [Bazel on Google cloud](https://console.cloud.google.com/marketplace/details/google/bazel?filter=category:developer-tools).

**Comment by gnossen** [comment]
Thank you for such a detailed write-up!

Regarding the first failure you mentioned, that is certainly a typo. Good catch! If you'd like to submit a PR with that change, we'd be more than happy to accept it. Otherwise, I'll get to it in the not-too-distant future.

CC @apolcyn for what looks like an `address_sorting` Windows Bazel issue.

**Comment by apolcyn** [comment]
I agree that https://github.com/grpc/grpc/issues/15333 seems related. Just a guess, but can `--dynamic_mode=off` fix your build?

cc @nicolasnoble

**Comment by gallmerci** [comment]
> I agree that #15333 seems related. Just a guess, but can `--dynamic_mode=off` fix your build?
> 
> cc @nicolasnoble

Unfortunately not.

**Comment by gallmerci** [comment]
Any idea how to debug this further? Seems to be bazel related because building everything with cmake is successful.

**Comment by gallmerci** [comment]
I tried now to add `linkopts = ["-DEFAULTLIB:ws2_32.lib"]` to [address_sorting.bzl](https://github.com/grpc/grpc/blob/ab7e5e8dec5ab3cda56fca9f9c25eb7cbeb2a017/third_party/address_sorting/address_sorting.bzl#L31) to fix the unresolved symbols errors. 

Now, I get different errors:
``` 
ERROR: .../grpc/BUILD:568:1: Linking of rule '//:grpc_trace' failed (Exit 1120)
   Creating library bazel-out/x64_windows-fastbuild/bin/grpc_trace.if.lib and object bazel-out/x64_windows-fastbuild/bin/grpc_trace.if.exp
trace.obj : error LNK2019: unresolved external symbol gpr_malloc referenced in function "void __cdecl add(char const *,char const 
*,char * * *,unsigned __int64 *)" (?add@@YAXPEBD0PEAPEAPEADPEA_K@Z)
trace.obj : error LNK2019: unresolved external symbol gpr_free referenced in function "void __cdecl parse(char const *)" (?parse@@YAXPEBD@Z)
trace.obj : error LNK2019: unresolved external symbol gpr_realloc referenced in function "void __cdecl add(char const *,char const *,char * * *,unsigned __int64 *)" (?add@@YAXPEBD0PEAPEAPEADPEA_K@Z)
trace.obj : error LNK2019: unresolved external symbol gpr_log referenced in function "public: static bool __cdecl grpc_core::TraceFlagList::Set(char const *,bool)" (?Set@TraceFlagList@grpc_core@@SA_NPEBD_N@Z)
trace.obj : error LNK2019: unresolved external symbol "public: class std::unique_ptr<char,class grpc_core::DefaultDelete> __cdecl 
grpc_core::GlobalConfigEnvString::Get(void)" (?Get@GlobalConfigEnvString@grpc_core@@QEAA?AV?$unique_ptr@DVDefaultDelete@grpc_core@@@std@@XZ) referenced in function "class std::unique_ptr<char,class grpc_core::DefaultDelete> __cdecl gpr_global_config_get_grpc_trace(void)" (?gpr_global_config_get_grpc_trace@@YA?AV?$unique_ptr@DVDefaultDelete@grpc_core@@@std@@XZ)
trace.obj : error LNK2019: unresolved external symbol "public: void __cdecl grpc_core::GlobalConfigEnvString::Set(char const *)" (?Set@GlobalConfigEnvString@grpc_core@@QEAAXPEBD@Z) referenced in function "void __cdecl gpr_global_config_set_grpc_trace(char const *)" (?gpr_global_config_set_grpc_trace@@YAXPEBD@Z)
bazel-out\x64_windows-fastbuild\bin\grpc_trace.dll : fatal error LNK1120: 6 unresolved external
```

There are different unresolved symbols error with each new build. Somehow difficult to get the root cause for the errors. If anybody has some advice how to debug it, I am listening :D

**Comment by gallmerci** [comment]
I make progress :) I can now compile my py_binary but I get now the following error when running the program:
```ImportError: cannot import name 'cygrpc' from 'grpc._cython' (...\com_github_grpc_grpc\src\python\grpcio\grpc\_cython\__init__.py)```

To fix the unresolved symbol errors I added a `linkstatic = True,` to the `grpc_cc_library` rule in `grpc_build_system.bzl`. I also needed to modify the `_get_python_lib` in `python_configure.bzl` to make it work under windows. 

It seems that Cython is not really generating the __init__.py properly. But the genrules for the .cpp files seem to work and I also see the output. Any ideas why this is not working?

PS: I also tried to do the same changes as described above, and try to build and run `import_test` in `bazel/test/python_test_repo/BUILD` and I get the same error.

**Comment by kentakozuka** [comment]
Any updates?
I got the same error running the program.

```
  File "/app/main_image.binary.runfiles/my_deps_pypi__grpcio_1_27_2/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc'
```

**Comment by skeptic-monkey** [comment]
This is also impacting one of my project, I simply can't use py_grpc_library on windows.

Building //src/python/grpcio/grpc:grpcio (v1.44.0) fails on windows using Bazel, and //src/python/grpcio/grpc:grpcio is a dependency of py_grpc_library.

Did it ever work on windows ? Is it supposed to ? Is there a workaround ?
