### ISSUE TITLE
Unary Sync Callback API crach

### ISSUE THREAD

**Issue by clearday4** [grpc/grpc#20781]
### What version of gRPC and what language are you using?
gRPC version v.1.21.1
Language: C++

### What operating system (Linux, Windows,...) and version?
Ubuntu Linux 4.15.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Run RPC Call

class FmGrpcClient {
public:
    static FmGrpcClient* getInstance();
    static FmGrpcClient* m_myInstance;
    ~FmGrpcClient();
.....
    static void sendFaultMsg(PB_FaultNotificationType);
    static void sendFaultExtMsg(PB_FaultNotificationExtType);
.....
private:
    static std::unique_ptr<AlarmGreeter::Stub> alarmStub_;
    static std::unique_ptr<FaultGreeter::Stub>  faultStub_;
.....
}

FmGrpcClient::FmGrpcClient() {}

FmGrpcClient::FmGrpcClient(std::shared_ptr<Channel> channel) {
    alarmStub_ = AlarmGreeter::NewStub(channel);
    faultStub_ = FaultGreeter::NewStub(channel);
...
...
}

void FmGrpcClient::sendFaultExtMsg(PB_FaultNotificationExtType DataMessage)
{
    ClientContext context;
    FaultEmpty rpy;

    Status status = faultStub_->FMFaultExtNoti(&context, DataMessage, &rpy);
    if (!status.ok()) {
        std::cout << "GetFeature rpc failed." << status.error_code() <<std::endl;
        std::cout << "GetFeature rpc failed." << status.error_message()  <<std::endl;
        faultStub_ = getFaultServerAddr();
        status = faultStub_->FMFaultExtNoti(&context, DataMessage, &rpy);
        if (!status.ok()) {
            std::cout << "GetFeature rpc failed." << status.error_code() <<std::endl;
            std::cout << "GetFeature rpc failed." << status.error_message()  <<std::endl;
        }
    }
}

### What did you expect to see?
RPC Call Success

### What did you see instead?
set_call makes Abort

 #0 0x00007f173500ca47 in abort () from /lib64/libc.so.6
#1 0x00007f17365623f4 in grpc::ClientContext::set_call(grpc_call*, std::shared_ptr const&) ()
from /lib64/libgrpc++.so
#2 0x00007f173655f532 in grpc_impl::Channel::CreateCallInternal(grpc::internal::RpcMethod const&, grpc::ClientContext*, grp
c_impl::CompletionQueue*, unsigned long) () from /lib64/libgrpc++.so
#3 0x00007f173655f603 in grpc_impl::Channel::CreateCall(grpc::internal::RpcMethod const&, grpc::ClientContext*, grpc_impl::
CompletionQueue*) () from /lib64/libgrpc++.so
#4 0x0000000000cbecaa in grpc::internal::BlockingUnaryCallImpl
::BlockingUnaryCallImpl (this=0x7f16f1fbb450, channel=0x7f14680039d0, method=..., context=0x7f16f1fbb4f0, request=..., 
result=0x7f16f1fbb6e0) 
#5 0x0000000000cbcc33 in grpc::internal::BlockingUnaryCall (
channel=0x7f14680039d0, method=..., context=0x7f16f1fbb4f0, request=..., result=0x7f16f1fbb6e0)
#6 0x0000000000cbb742 in PB_FAULT::FaultGreeter::Stub::FMFaultExtNoti (this=0x7f1468005c90, context=0x7f16f1fbb4f0, 
request=..., response=0x7f16f1fbb6e0) 
#7 0x0000000000c11ab6 in FmGrpcClient::sendFaultExtMsg (DataMessage=...) 
#8 0x0000000000c0bc37 in FMClient::sendExtFaultMsg (this=0xa2949b0, fault=...) 
#9 0x0000000000c08dc4 in fmiSendExtFault (msg=...) 
#10 0x000000000083724e in CommIpcMgr::sendGenFltMsg (this=0x3684ee0, msg=...) 
#11 0x000000000083bfe2 in CommIpcMgr::sendMessage (this=0x3684ee0, msgId=msgId@entry=3022, mh=..., pb=...)

--

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

gRPC logs

I1021 05:26:56.634274077      88 init.cc:163]                grpc_init(void)
I1021 05:26:56.634279343      56 tcp_posix.cc:611]           TCP:0x2512410 got_read: "No Error"
I1021 05:26:56.634298295      56 tcp_posix.cc:596]           TCP:0x2512410 alloc_slices
I1021 05:26:56.634289191      88 completion_queue.cc:506]    grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I1021 05:26:56.634310515      56 tcp_posix.cc:577]           TCP:0x2512410 read_allocation_done: "No Error"
I1021 05:26:56.634334524      56 tcp_posix.cc:413]           TCP:0x2512410 call_cb 0x2513ea0 0x7fdba2be7773:0x2513ce0
I1021 05:26:56.634342567      56 tcp_posix.cc:416]           READ 0x2512410 (peer=ipv4:10.108.212.187:50601) error="No Error"
D1021 05:26:56.634353567      56 tcp_posix.cc:422]           DATA: 11 63 88 c2 c1 '.c...'
I1021 05:26:56.634340656      88 channel.cc:413]             grpc_channel_create_registered_call(channel=0x7fdb6400dc60, parent_call=(nil), propagation_mask=ffff, completion_queue=0x7fdb640165b0, registered_call_handle=0x7fdb64002c80, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
D1021 05:26:56.634363958      56 tcp_posix.cc:571]           TCP unref 0x2512410 : read 2 -> 1
I1021 05:26:56.634386590      56 parsing.cc:649]             parsing Trailers-Only
I1021 05:26:56.634391975      88 grpc_context.cc:28]         grpc_census_call_set_context(call=0x7fdb640167a0, census_context=(nil))
I1021 05:26:56.634397364      56 hpack_parser.cc:636]        Decode: ':status: 200', elem_interned=1 [3], k_interned=1, v_interned=1
I1021 05:26:56.634415829      56 parsing.cc:503]             HTTP:4451:TRL:CLI: :status: 32 30 30 '200'
I1021 05:26:56.634425884      56 hpack_parser.cc:636]        Decode: 'content-type: application/grpc', elem_interned=1 [3], k_interned=1, v_interned=1
E1021 05:26:56.634427268      88 client_context.cc:94]       assertion failed: call_ == nullptr
I1021 05:26:56.634437778      56 parsing.cc:503]             HTTP:4451:TRL:CLI: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
I1021 05:26:56.634458627      56 hpack_parser.cc:636]        Decode: 'grpc-status: 1', elem_interned=1 [3], k_interned=1, v_interned=1
Aborted

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by clearday4** [comment]
Solved the problem.
If RPC call error occurred, the context was reused.
Remove the context reuse code and it works.
