### ISSUE TITLE
cloud_to_cloud:dart:aspnetcore_server:cancel_after_begin:tls Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#20890]
```
Unhandled exception:
NoSuchMethodError: The method 'read' was called on null.
Receiver: null
Tried calling: read()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Socket._onData (dart:io-patch/socket_patch.dart:1785:27)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#6      _StreamController._add (dart:async/stream_controller.dart:640:7)
#7      _StreamController.add (dart:async/stream_controller.dart:586:5)
#8      _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

2019-10-29 00:04:49,256 FAILED: cloud_to_cloud:dart:aspnetcore_server:cancel_after_begin:tls [ret=255, pid=2607, time=9.1sec]
```

https://source.cloud.google.com/results/invocations/fa6d701d-3e6a-4b44-bbe8-2de107ff08aa/log

**Comment by sheenaqotj** [comment]
@sigurdm is the best person to look at this, but I'm not sure how to tag him.

**Comment by sigurdm** [comment]
This seems very mysterious.
Does this happen consistently or it is a flaky situation?

**Comment by jtattermusch** [comment]
According to the test results, this is just a flake.

https://source.cloud.google.com/results/invocations/da8fb91e-5216-475f-bb79-9c22d1b00d18/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/f96aedd7-c8ff-4e87-be17-6ed15c5fd3e9/targets/github%2Fgrpc%2Finterop_test/tests

job history is here: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_tocloud

**Comment by yashykt** [comment]
Closing stale issue
