### ISSUE TITLE
FLAKE: tests.cloud_to_cloud:dart:aspnetcore_server:timeout_on_sleeping_server:tls

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21387]
```
Passed.
Unhandled exception:
NoSuchMethodError: The method 'read' was called on null.
Receiver: null
Tried calling: read()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Socket._onData (dart:io-patch/socket_patch.dart:1785:27)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#6      _StreamController._add (dart:async/stream_controller.dart:640:7)
#7      _StreamController.add (dart:async/stream_controller.dart:586:5)
#8      _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

https://source.cloud.google.com/results/invocations/9a3a28aa-9239-4ab8-ab84-c59f27ed76f4/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by karthikravis** [comment]
Assigning to current build cop

**Comment by veblush** [comment]
Closed because it's obsolete.
