### ISSUE TITLE
BAD_ECC_CERT when connecting from grpc-python to golang-based server

### ISSUE THREAD

**Issue by ioncebotari** [grpc/grpc#21407]
### What version of gRPC and what language are you using?
Python 3.6
grpcio 1.25.0   
grpcio-tools 1.25.0 

On the other side:
BTCWallet btcwallet version 0.11.0-alpha built against golang 1.12

### What operating system (Linux, Windows,...) and version?
The error is the same on both CentOS7 and CentOS8. I've tested how it behaves on both, thinking that maybe going from OpenSSL 1.02 to 1.10 would fix the problem

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6
On CentOS 7 I'm using the version from [SCL](https://wiki.centos.org/AdditionalResources/Repositories/SCL), on CentOS 8 it's the default version

### What did you do?
I'm testing using BTCWallet as with gRPC. It is listening on port 18332, with the certificates available at /data/btc/.btcwallet/.

This is the code I'm using for interfacing with gRPC:

```python
import grpc
from api_pb2_grpc import VersionServiceStub
import api_pb2 as req


class BitcoinProcessor:
    """
    Class used for defining Bitcoin operations
    """

    def __init__(self, ip, port, secure=True, certificate_path='/data/btc/.btcwallet/rpc.cert'):
        if secure:
            with open(certificate_path, 'rb') as f:
                cert = f.read()
            creds = implementations.ssl_channel_credentials(cert, None, None)
            self.ic = grpc.secure_channel(ip+':'+str(port), creds)
        else:
            self.ic = grpc.insecure_channel(ip+":"+str(port))

    def version(self):
        stub = VersionServiceStub(self.ic)
        try:
            response = stub.Version(req.VersionRequest())
        except grpc.RpcError as e:
            logger.info('Version failed with {0}: {1}'.format(e.code(), e.details()))
            return None
        return response
```

And this is how I'm calling it:

```python
import unittest
from bitcoin import BitcoinProcessor

host = 'localhost'
port = 18332


class MyTestCase(unittest.TestCase):

    def test_btc_version(self):
        processor = BitcoinProcessor(host, port)
        self.assertEqual(processor.version(), '0')
```
### What did you expect to see?
I was expecting to get the correct version of BTCWallet with an error that it's different from 0

### What did you see instead?
```
# GRPC_VERBOSITY=debug GRPC_TRACE=tcp python test_bitcoin.py          
I1206 09:32:18.455278329   11960 ev_epoll1_linux.cc:116]     grpc epoll fd: 3
D1206 09:32:18.455320853   11960 ev_posix.cc:174]            Using polling engine: epoll1
D1206 09:32:18.455386150   11960 dns_resolver_ares.cc:503]   Using ares dns resolver
I1206 09:32:18.457164945   11960 socket_utils_common_posix.cc:318] TCP_USER_TIMEOUT not supported for this platform
I1206 09:32:18.457358696   11960 tcp_client_posix.cc:325]    CLIENT_CONNECT: ipv6:[::1]:18332: asynchronously connecting fd 0x5630b43ac8c0
I1206 09:32:18.457419288   11960 tcp_client_posix.cc:143]    CLIENT_CONNECT: ipv6:[::1]:18332: on_writable: error="No Error"
I1206 09:32:18.457455390   11960 tcp_client_posix.cc:106]    CLIENT_CONNECT: ipv6:[::1]:18332: on_alarm: error="Cancelled"
I1206 09:32:18.457494963   11960 subchannel.cc:1000]         Connect failed: {"created":"@1575624738.457436952","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv6:[::1]:18332"}
I1206 09:32:18.457566047   11960 socket_utils_common_posix.cc:318] TCP_USER_TIMEOUT not supported for this platform
I1206 09:32:18.457686404   11960 tcp_client_posix.cc:325]    CLIENT_CONNECT: ipv4:127.0.0.1:18332: asynchronously connecting fd 0x5630b43ac8c0
I1206 09:32:18.457707435   11960 tcp_client_posix.cc:143]    CLIENT_CONNECT: ipv4:127.0.0.1:18332: on_writable: error="No Error"
I1206 09:32:18.457724243   11960 tcp_client_posix.cc:106]    CLIENT_CONNECT: ipv4:127.0.0.1:18332: on_alarm: error="Cancelled"
I1206 09:32:18.457803478   11960 tcp_posix.cc:1062]          WRITE 0x5630b43acda0 (peer=ipv4:127.0.0.1:18332)
D1206 09:32:18.457820308   11960 tcp_posix.cc:1066]          DATA: 16 03 01 00 90 01 00 00 8c 03 03 cf 0b 2c 48 94 21 d1 14 be 9c 52 5f 1b c1 a5 30 09 5a e0 62 ed dd 66 2d 0c 7b 2b 2b 95 02 e1 6a 00 00 08 c0 2b c0 2c c0 2f c0 30 01 00 00 5b 00 00 00 0e 00 0c 00 00 09 6c 6f 63 61 6c 68 6f 73 74 00 17 00 00 ff 01 00 01 00 00 0a 00 04 00 02 00 17 00 0b 00 02 01 00 00 23 00 00 00 10 00 0e 00 0c 08 67 72 70 63 2d 65 78 70 02 68 32 00 0d 00 14 00 12 04 03 08 04 04 01 05 03 08 05 05 01 08 06 06 01 02 01 33 74 00 00 '.............,H.!....R_...0.Z.b..f-.{++...j....+.,./.0...[.........localhost........................#.........grpc-exp.h2........................3t..'
I1206 09:32:18.457856956   11960 tcp_posix.cc:1100]          write: "No Error"
I1206 09:32:18.457869675   11960 tcp_posix.cc:265]           TCP:0x5630b43acda0 notify_on_read
I1206 09:32:18.470072897   11960 tcp_posix.cc:608]           TCP:0x5630b43acda0 got_read: "No Error"
I1206 09:32:18.470103653   11960 tcp_posix.cc:590]           TCP:0x5630b43acda0 alloc_slices
I1206 09:32:18.470111904   11960 tcp_posix.cc:571]           TCP:0x5630b43acda0 read_allocation_done: "No Error"
I1206 09:32:18.470137551   11960 tcp_posix.cc:401]           TCP:0x5630b43acda0 call_cb 0x5630b43b7cd0 0x7f6e9debac60:0x5630b43b7b00
I1206 09:32:18.470152470   11960 tcp_posix.cc:404]           READ 0x5630b43acda0 (peer=ipv4:127.0.0.1:18332) error="No Error"
D1206 09:32:18.470178522   11960 tcp_posix.cc:410]           DATA: 16 03 03 00 3e 02 00 00 3a 03 03 e8 3a 79 32 37 8f 79 ff 1a 2b b2 1e 73 09 1b 7c c2 72 3f db 6a 11 a9 a4 de 3b 94 38 6a f5 22 3d 00 c0 2b 00 00 12 00 23 00 00 ff 01 00 01 00 00 10 00 05 00 03 02 68 32 16 03 03 02 81 0b 00 02 7d 00 02 7a 00 02 77 30 82 02 73 30 82 01 d4 a0 03 02 01 02 02 10 3e c1 45 78 82 66 4a 98 7c 9f 13 75 dd 24 7b d4 30 0a 06 08 2a 86 48 ce 3d 04 03 04 30 3c 31 25 30 23 06 03 55 04 0a 13 1c 62 74 63 77 61 6c 6c 65 74 20 61 75 74 6f 67 65 6e 65 72 61 74 65 64 20 63 65 72 74 31 13 30 11 06 03 55 04 03 13 0a 69 6e 73 74 61 6e 63 65 2d 34 30 1e 17 0d 31 39 31 32 30 35 30 39 30 36 33 39 5a 17 0d 32 39 31 32 30 33 30 39 30 36 33 39 5a 30 3c 31 25 30 23 06 03 55 04 0a 13 1c 62 74 63 77 61 6c 6c 65 74 20 61 75 74 6f 67 65 6e 65 72 61 74 65 64 20 63 65 72 74 31 13 30 11 06 03 55 04 03 13 0a 69 6e 73 74 61 6e 63 65 2d 34 30 81 9b 30 10 06 07 2a 86 48 ce 3d 02 01 06 05 2b 81 04 00 23 03 81 86 00 04 01 a8 b1 e0 b4 7f 37 99 99 f6 d5 b1 7b c0 00 eb 4f 23 be 27 3c ce 64 65 91 23 c3 c7 6c e3 cb 42 be ae 7f 8a ec aa c9 5c 61 b6 9e 87 4f c4 8f 55 fc 0f 60 e3 88 03 b8 92 4e f1 f7 f0 d6 c2 af 87 6b ee 00 f6 00 fd 36 eb b9 ad 01 cc 14 6e 4f 7a 1f d7 f7 00 6b 09 9d 5f db d4 cd 88 d7 89 2c 93 93 01 06 1c 5e 28 5f dc 99 c0 0e b6 71 40 b4 0a 98 62 ef 0a 7b 2f 48 dc 6e b7 b0 f3 7b 18 a2 e6 aa 3a 4b b0 a3 75 30 73 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 02 02 a4 30 0f 06 03 55 1d 13 01 01 ff 04 05 30 03 01 01 ff 30 50 06 03 55 1d 11 04 49 30 47 82 0a 69 6e 73 74 61 6e 63 65 2d 34 82 09 6c 6f 63 61 6c 68 6f 73 74 87 04 7f 00 00 01 87 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 87 04 0a 9c 00 07 87 10 fe 80 00 00 00 00 00 00 70 39 ca 38 31 72 46 46 30 0a 06 08 2a 86 48 ce 3d 04 03 04 03 81 8c 00 30 81 88 02 42 01 2f b0 5e d5 2e a6 87 fc 81 d6 75 3a 70 2d c1 71 57 91 a3 06 a6 29 0c 11 7c d3 4a 87 7e 3a d6 f9 ed 87 2b 33 71 a3 83 10 88 08 e9 4a 03 4c c8 57 3b 2b e5 01 6f 87 2a 0b ad d8 1e 10 e1 fa ed 0d 0b 02 42 01 56 11 ce b9 a7 93 b6 af 56 40 ab 9d 00 e7 bb 44 71 3e 45 a0 60 51 09 49 a0 74 e2 2d 9e 4e c1 b5 7a 86 51 08 24 05 87 2c 64 ca 5f f1 f7 de 3c 52 07 5b bc 3f d6 5c 86 fa 42 1b 9f 90 fd 8d 1c c5 f5 16 03 03 00 d8 0c 00 00 d4 03 00 17 41 04 53 5e c5 9b b1 97 c1 b1 cd 59 74 a3 ac 73 24 fb 7f 07 c2 76 21 da eb ef 9f 2d 63 15 17 c3 d1 74 cf 1b 55 eb 3d f8 8d a5 ed ad 2e 47 70 4c b0 97 ea e3 8c ac e5 bc b9 e1 ea ca 17 d0 79 01 cb 25 04 03 00 8b 30 81 88 02 42 01 39 3f 1a d6 d4 1c 74 da 50 c4 e8 ae fc 56 06 26 3a 30 00 8f e1 e2 02 c3 be f8 f0 d8 7a cc ea 76 8d d9 80 31 3b 24 45 c3 fe 48 4e 1c 07 2d e0 b8 61 20 72 c3 e7 44 09 87 c5 86 cc 03 c8 16 1e 61 de 02 42 01 e6 5a 56 0a 1f 64 70 04 ad 24 0b 06 dd e2 38 3f ae 1c 7b 5a 20 6c 15 16 7b c4 a1 4b 67 27 b4 f4 10 07 6b 54 b5 17 0e 8c 60 47 55 91 4e 3a 24 39 4e a7 bf 9b 33 ae 4b 3b 56 98 fa d5 5f ee a2 ca aa 16 03 03 00 04 0e 00 00 00 '....>...:...:y27.y..+..s..|.r?.j....;.8j."=..+....#..............h2........}..z..w0..s0..........>.Ex.fJ.|..u.${.0...*.H.=...0<1%0#..U....btcwallet autogenerated cert1.0...U....instance-40...191205090639Z..291203090639Z0<1%0#..U....btcwallet autogenerated cert1.0...U....instance-40..0...*.H.=....+...#...........7.....{...O#.'<.de.#..l..B.......\a...O..U..`.....N.......k.....6......nOz....k.._......,.....^(_.....q@...b..{/H.n...{....:K..u0s0...U...........0...U.......0....0P..U...I0G..instance-4..localhost........................................p9.81rFF0...*.H.=.......0...B./.^.......u:p-.qW....)..|.J.~:....+3q......J.L.W;+..o.*...........B.V.......V@.....Dq>E.`Q.I.t.-.N..z.Q.$..,d._...<R.[.?.\..B....................A.S^.......Yt..s$....v!....-c....t..U.=......GpL..............y..%....0...B.9?....t.P....V.&:0..........z..v...1;$E..HN..-..a r..D.........a..B..ZV..dp..$....8?..{Z l..{..Kg'....kT....`GU.N:$9N...3.K;V..._.............'
E1206 09:32:18.470330775   11960 ssl_transport_security.cc:1246] Handshake failed with fatal error SSL_ERROR_SSL: error:1000006b:SSL routines:OPENSSL_internal:BAD_ECC_CERT.
D1206 09:32:18.470354814   11960 security_handshaker.cc:186] Security handshake failed: {"created":"@1575624738.470344372","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I1206 09:32:18.470452210   11960 subchannel.cc:1000]         Connect failed: {"created":"@1575624738.470344372","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":303,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I1206 09:32:18.470479746   11960 subchannel.cc:939]          Subchannel 0x5630b424d220: Retry in 985 milliseconds
E
======================================================================
ERROR: test_btc_version (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_bitcoin.py", line 13, in test_btc_version
    self.assertEqual(processor.version(), '0')
  File "/opt/test/crypto/bitcoin.py", line 24, in version
    response = stub.Version(req.VersionRequest())
  File "/opt/test/venv/lib/python3.6/site-packages/grpc/_channel.py", line 690, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/test/venv/lib/python3.6/site-packages/grpc/_channel.py", line 592, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1575624738.470475491","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1575624738.470471411","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

----------------------------------------------------------------------
Ran 1 test in 0.019s

FAILED (errors=1)

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
There is a similar bug that I found - https://github.com/grpc/grpc/issues/6722 , but it doesn't seem that it applies to my environment.

**Comment by lidizheng** [comment]
Well, this seem like a setting issue. But first, I see in your snippet, you are using `implementations` which looks like beta API, if you are using beta API, please upgrade to our stable public API.

```
E1206 09:32:18.470330775   11960 ssl_transport_security.cc:1246] Handshake failed with fatal error SSL_ERROR_SSL: error:1000006b:SSL routines:OPENSSL_internal:BAD_ECC_CERT.
```

In your snippet, you are passing the certificate as first argument, which is an unlikely setting. In our [API reference](https://grpc.github.io/grpc/python/grpc.html#grpc.ssl_channel_credentials). The arguments are root certs, private key, and cert chains. Usually, the you can leave the root cert blank to be fetched from default location. As for private key, its usage depends on your cert generation, and we can leave it `None` as well. Then, you should put the certificate as third argument.

```
import grpc

certs = grpc.ssl_channel_credentials(None, None, cert)
```

**Comment by ioncebotari** [comment]
@lidizheng Thank you for your help. This was indeed a configuration error on my part. I was influenced by the outdated example code from btcwallet's [documentation](https://github.com/btcsuite/btcwallet/blob/master/rpc/documentation/clientusage.md#python).

I've created my own CA, based on EC prime256v1 and SHA256 hash and changed my code to
```python
def __init__(self, ip, port, secure=True, 
    ca_path='/data/btc/.btcwallet/ec-ca.cert',
    cert_path='/data/btc/.btcwallet/rpc.cert',
    key_path='/data/btc/.btcwallet/rpc.key',
):
        if secure:
            with open(os.path.abspath(certificate_path), 'rb') as f:
                root = f.read()
            with open(os.path.abspath(cert_paht), 'rb') as f:
                cert = f.read()
            with open(os.path.abspath(key_path), 'rb') as f:
                key = f.read()
            creds = implementations.ssl_channel_credentials(root, key, cert)
            self.ic = grpc.secure_channel(ip+':'+str(port), creds)
        else:
            self.ic = grpc.insecure_channel(ip+":"+str(port))
```

and I've been able to connect. I get now a 401 authentication error when trying to connect, though. 
Please see the attached file [401_error_debug.txt](https://github.com/grpc/grpc/files/3962546/401_error_debug.txt).

I have username and password credentials but don't know how to plug them in. I think that [access_token_call_credentials](https://grpc.github.io/grpc/python/grpc.html#grpc.access_token_call_credentials) might be the method to use, but I don't understand how to use it. I've found this [golang example in a blog post](https://jbrandhorst.com/post/grpc-auth/), about using HTTP Basic Auth, but couldn't understand how to translate it into Python. Is this still tied to the gRPC protocol or I should open a bug request with btcwallet?

**Comment by lidizheng** [comment]
The HTTP basic auth mechanism: https://en.wikipedia.org/wiki/Basic_access_authentication

In short, by adding an `Authorization` HTTP header with base64 encoded `username:password`, you should be able to pass the basic-auth check.

**Comment by ioncebotari** [comment]
I've been able to properly connect by using example code from [the gRPC Google group](https://groups.google.com/forum/#!searchin/grpc-io/basic%7Csort:date/grpc-io/EgLjNzF4Yuc/xWCWPO8bBAAJ).
@lidizheng thank you for your amazing work! Closing the issue as solved
