### ISSUE TITLE
Pip install failing using docker

### ISSUE THREAD

**Issue by drinkmorewaters** [grpc/grpc#21483]
### What version of gRPC and what language are you using?
Python, v 1.25.0, Docker version 19.03.5

### What operating system (Linux, Windows,...) and version?
OSX 10.15.2

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8

### What did you do?
GRPC install fails on pip install whilst using docker. It also fails using google cloud build. It just fails on any build i try.

### What did you expect to see?
a successful install

### What did you see instead?

```
 Downloading https://files.pythonhosted.org/packages/e4/60/40c4d2b61d9e4349bc89445deb8d04cc000b10a63446c42d311e0d21d127/grpcio-1.25.0.tar.gz (15.4MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-83zchz0q/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-83zchz0q/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-83zchz0q/grpcio/pip-egg-info
         cwd: /tmp/pip-install-83zchz0q/grpcio/
    Complete output (13 lines):
    /tmp/pip-install-83zchz0q/grpcio/src/python/grpcio/commands.py:102: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if exit_code is not 0:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-83zchz0q/grpcio/setup.py", line 190, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-83zchz0q/grpcio/setup.py", line 148, in check_linker_need_libatomic
        cc_test = subprocess.Popen(['cc', '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```
### Anything else we should know about your project / environment?

I have tried with both venv and without both fail.

**Comment by drinkmorewaters** [comment]
Alpine Linux broke things i DO NOT recommend it. Use python:[python.version]-slim-buster instead

**Comment by dcmoore-gd** [comment]
@drinkmorewaters Did you determine why this started with `grpcio==1.26.0`?  `1.25.0` works fine in the same environment (Alpine 3.10 in Docker).
