### ISSUE TITLE
grpcio-1.26.0.tar python3 setup.py build error

### ISSUE THREAD

**Issue by shmily3929** [grpc/grpc#21565]
grpcio-1.26.0.tar.gz
python3.6.5
centos 6.5
gcc 4.4.7
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/crypto/rc4
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/crypto/rsa_extra
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/crypto/siphash
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/crypto/stack
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/crypto/x509
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/crypto/x509v3
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/ssl
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/third_party
creating python_build/temp.linux-x86_64-3.6/third_party/boringssl/third_party/fiat
creating python_build/temp.linux-x86_64-3.6/third_party/cares
creating python_build/temp.linux-x86_64-3.6/third_party/cares/cares
creating python_build/temp.linux-x86_64-3.6/third_party/upb
creating python_build/temp.linux-x86_64-3.6/third_party/upb/upb
creating python_build/temp.linux-x86_64-3.6/third_party/zlib
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/boringssl/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Ithird_party/zlib -I/usr/local/python3/include/python3.6m -c src/python/grpcio/grpc/_cython/cygrpc.cpp -o python_build/temp.linux-x86_64-3.6/src/python/grpcio/grpc/_cython/cygrpc.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: warning: command line option "-std=gnu99" is valid for C/ObjC but not for C++
creating tmp
creating tmp/tmp12woyffn
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/python3/include/python3.6m -c /tmp/tmp12woyffn/a.c -o tmp/tmp12woyffn/a.o
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/wqq/grpcio-1.26.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "/usr/local/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wqq/grpcio-1.26.0/src/python/grpcio/commands.py", line 263, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/local/python3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/python3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/local/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 400, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/local/python3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/python3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/python3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/python3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/python3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/python3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/local/python3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/wqq/grpcio-1.26.0/src/python/grpcio/commands.py", line 268, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/wqq/grpcio-1.26.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "/usr/local/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wqq/grpcio-1.26.0/src/python/grpcio/commands.py", line 263, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/local/python3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/python3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/python3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/local/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

**Comment by shmily3929** [comment]
update gcc 4.8.5 success
