### ISSUE TITLE
UBSAN error: member call on null pointer in XdsTest/FailoverTest.UpdateInitialUnavailable/FakeResolverWithLoadReporting

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#21694]
log snippet:

```
[ RUN      ] XdsTest/FailoverTest.UpdateInitialUnavailable/FakeResolverWithLoadReporting
I0116 23:14:15.061206513      19 xds_end2end_test.cc:992]    starting Backend server on port 20310
I0116 23:14:15.061585305     123 server_builder.cc:332]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0116 23:14:15.062416887      19 xds_end2end_test.cc:1004]   Backend server startup complete
I0116 23:14:15.062715060      19 xds_end2end_test.cc:992]    starting Backend server on port 20311
src/core/ext/filters/client_channel/xds/xds_client.cc:1276:50: runtime error: member call on null pointer of type 'grpc_core::XdsClient::ChannelState::RetryableCall<grpc_core::XdsClient::ChannelState::AdsCallState>'
I0116 23:14:15.063165616     125 server_builder.cc:332]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0116 23:14:15.063852613      19 xds_end2end_test.cc:1004]   Backend server startup complete
I0116 23:14:15.064076251      19 xds_end2end_test.cc:992]    starting Backend server on port 20312
I0116 23:14:15.064385425     127 server_builder.cc:332]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0116 23:14:15.064947604      19 xds_end2end_test.cc:1004]   Backend server startup complete
I0116 23:14:15.065003530      19 xds_end2end_test.cc:992]    starting Backend server on port 20313
I0116 23:14:15.065246650     129 server_builder.cc:332]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0116 23:14:15.065755206      19 xds_end2end_test.cc:1004]   Backend server startup complete
I0116 23:14:15.065859788      19 xds_end2end_test.cc:992]    starting Balancer server on port 20314
I0116 23:14:15.066141262     131 server_builder.cc:332]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0116 23:14:15.066805534      19 xds_end2end_test.cc:1004]   Balancer server startup complete
I0116 23:14:15.067474772      19 xds_end2end_test.cc:1025]   Backend about to shutdown
I0116 23:14:15.067876254      19 xds_end2end_test.cc:1029]   Backend shutdown completed
I0116 23:14:15.067894713      19 xds_end2end_test.cc:1025]   Backend about to shutdown
I0116 23:14:15.068295437      19 xds_end2end_test.cc:1029]   Backend shutdown completed
I0116 23:14:15.070331449     132 subchannel.cc:1055]         New connected subchannel at 0x7f28740018f0 for subchannel 0x2cea030
I0116 23:14:15.071223486     132 xds_end2end_test.cc:593]    LRS[0x2cd1670]: StreamLoadStats starts
I0116 23:14:15.071497249     134 xds_end2end_test.cc:450]    ADS[0x2cd1528]: StreamAggregatedResources starts
I0116 23:14:15.072221842     134 xds_end2end_test.cc:425]    ADS[0x2cd1528]: received EDS request 'node {
  id: "xds_end2end_test"
  cluster: "test"
  metadata {
    fields {
      key: "foo"
      value {
        string_value: "bar"
      }
    }
  }
  locality {
    region: "corp"
    zone: "svl"
    sub_zone: "mp3"
  }
  build_version: "gRPC C-core 9.0.0 linux"
}
resource_names: "application_target_name"
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
'
I0116 23:14:15.072257189     134 xds_end2end_test.cc:437]    ADS[0x2cd1528]: sleeping for 0 ms...
I0116 23:14:15.072921309     134 xds_end2end_test.cc:441]    ADS[0x2cd1528]: Woke up! Sending response 'resources {
  [type.googleapis.com/envoy.api.v2.ClusterLoadAssignment] {
    cluster_name: "application_target_name"
    endpoints {
      locality {
        region: "xds_default_locality_region"
        zone: "xds_default_locality_zone"
        sub_zone: "locality0"
      }
      lb_endpoints {
        endpoint {
          address {
            socket_address {
              address: "127.0.0.1"
              port_value: 20310
            }
          }
        }
      }
      load_balancing_weight {
        value: 3
      }
    }
    endpoints {
      locality {
        region: "xds_default_locality_region"
        zone: "xds_default_locality_zone"
        sub_zone: "locality1"
      }
      lb_endpoints {
        endpoint {
          address {
            socket_address {
              address: "127.0.0.1"
              port_value: 20311
            }
          }
        }
      }
      load_balancing_weight {
        value: 3
      }
      priority: 1
    }
  }
}
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
'
I0116 23:14:15.073940920     130 subchannel.cc:1003]         Connect failed: {"created":"@1579216455.073877157","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:20310"}
I0116 23:14:15.074023129     130 subchannel.cc:942]          Subchannel 0x7f28600039a0: Retry in 1000 milliseconds
I0116 23:14:15.074630961     135 subchannel.cc:1003]         Connect failed: {"created":"@1579216455.074562695","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:20311"}
I0116 23:14:15.074665673     135 subchannel.cc:942]          Subchannel 0x7f286000cf00: Retry in 998 milliseconds
I0116 23:14:15.075014784     134 xds_end2end_test.cc:437]    ADS[0x2cd1528]: sleeping for 1000 ms...
I0116 23:14:15.568615191      19 xds_end2end_test.cc:853]    ========= WAITING FOR BACKEND 2 ==========
    #0 0x7f289ca98e8e in grpc_core::XdsClient::ChannelState::LrsCallState::MaybeStartReportingLocked() /proc/self/cwd/src/core/ext/filters/client_channel/xds/xds_client.cc:1276:50
    #1 0x7f289ca9bd5d in grpc_core::XdsClient::ChannelState::LrsCallState::Reporter::OnReportDoneLocked(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/xds/xds_client.cc:1136:22
    #2 0x7f289aebb2f1 in grpc_combiner_continue_exec_ctx() /proc/self/cwd/src/core/lib/iomgr/combiner.cc:236:5
    #3 0x7f289af09d96 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:156:17
    #4 0x7f289aed56aa in end_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:991:32
    #5 0x7f289aeccf71 in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:1055:3
    #6 0x7f289af08351 in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:324:21
    #7 0x7f289af1b5c4 in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10
    #8 0x7f289c2a13b2 in run_poller(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/backup_poller.cc:130:7
    #9 0x7f289af09fe9 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #10 0x7f289af09d7f in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:153:9
    #11 0x7f289af82d4d in run_some_timers() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:134:30
    #12 0x7f289af82911 in timer_main_loop() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:237:9
    #13 0x7f289af8282e in timer_thread(void*) /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:284:3
    #14 0x7f289ac48b93 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:140:27
    #15 0x7f289ac48554 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:110:25
I0116 23:14:16.072536621     137 subchannel.cc:967]          Failed to connect to channel, retrying
I0116 23:14:16.073383474     137 subchannel.cc:967]          Failed to connect to channel, retrying
I0116 23:14:16.074296140     130 subchannel.cc:1003]         Connect failed: {"created":"@1579216456.074235634","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:20311"}
I0116 23:14:16.074699407     130 subchannel.cc:942]          Subchannel 0x7f286000cf00: Retry in 1404 milliseconds
I0116 23:14:16.073957012     132 subchannel.cc:1003]         Connect failed: {"created":"@1579216456.073833702","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:20310"}
I0116 23:14:16.075444712     130 subchannel.cc:942]          Subchannel 0x7f28600039a0: Retry in 1880 milliseconds
    #16 0x7f2898e6d6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #17 0x7f289858041c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)
```

https://source.cloud.google.com/results/invocations/d8da2df6-1db0-4a8a-a91b-97126a4640e3/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Depoll1/log

seen in PR: https://github.com/grpc/grpc/pull/21684

**Comment by donnadionne** [comment]
We no longer have the version of test FakeResolverWithLoadReporting, the other versions of FailoverTest.UpdateInitialUnavailable are fine with 1000 runs.

Closing this bug
