### ISSUE TITLE
c_linux_dbg_native_x64_gcc8_3.bins/dbg/httpscli_test failing at 100% on master

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#21697]
From the portability master suite: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_portability

Log snippet:

```
D0117 01:20:16.009991164    2053 ev_posix.cc:174]            Using polling engine: poll
D0117 01:20:16.010214358    2053 dns_resolver_ares.cc:516]   Using ares dns resolver
D0117 01:20:16.011004707    2053 tcp_posix.cc:1811]          cannot set inq fd=3 errno=92
/var/local/git/grpc/src/core/tsi/test_creds/server1.pem
server running on port 11967
Traceback (most recent call last):
  File "bins/dbg/../../test/core/http/test_server.py", line 64, in <module>
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:2815)
D0117 01:20:21.012465286    2053 test_config.cc:385]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0117 01:20:21.012739203    2053 ev_posix.cc:174]            Using polling engine: poll
D0117 01:20:21.012834684    2053 dns_resolver_ares.cc:516]   Using ares dns resolver
I0117 01:20:21.012898913    2053 httpscli_test.cc:72]        test_get
I0117 01:20:21.012905891    2053 httpscli_test.cc:75]        requesting from localhost:11967
I0117 01:20:22.015425653    2053 httpscli_test.cc:53]        response status=0 error={"created":"@1579224022.015352031","description":"Failed HTTP requests to all targets","file":"src/core/lib/http/httpcli.cc","file_line":202,"referenced_errors":[{"created":"@1579224022.015307820","description":"Failed HTTP/1 client request","file":"src/core/lib/http/httpcli.cc","file_line":113,"referenced_errors":[{"created":"@1579224022.015299152","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv6:[::1]:11967"},{"created":"@1579224022.015344404","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:11967"}]}]}
E0117 01:20:22.015445341    2053 httpscli_test.cc:55]        assertion failed: response->status == 200



*******************************
Caught signal SIGABRT
bins/dbg/httpscli_test(+0x36880)[0x556a3292a880]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fb63b47a730]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7fb63afbb7bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7fb63afa6535]
bins/dbg/httpscli_test(+0x341fc)[0x556a329281fc]
bins/dbg/httpscli_test(+0x35041)[0x556a32929041]
bins/dbg/httpscli_test(+0x3c351)[0x556a32930351]
bins/dbg/httpscli_test(+0x3c881)[0x556a32930881]
bins/dbg/httpscli_test(+0x6988f)[0x556a3295d88f]
bins/dbg/httpscli_test(+0x5bc70)[0x556a3294fc70]
bins/dbg/httpscli_test(+0x3d89c)[0x556a3293189c]
bins/dbg/httpscli_test(+0x345ae)[0x556a329285ae]
bins/dbg/httpscli_test(+0x34db9)[0x556a32928db9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fb63afa809b]
bins/dbg/httpscli_test(+0x3402a)[0x556a3292802a]
Command terminated by signal 6
real 6.14
user 0.00
sys 0.00
```

**Comment by nicolasnoble** [comment]
Is it still happening?

**Comment by markdroth** [comment]
Doesn't seem like this has been seen for a long time, so I'm closing it.
