### ISSUE TITLE
14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by SeanDez** [grpc/grpc#21727]
### What version of gRPC and what language are you using?

Typescript. How can I find gRPC verion in a node.js project?

### What operating system (Linux, Windows,...) and version?

Lubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

`    "typescript": "^3.7.2"`

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

1. setup a node.js project with `firebase`, `firebase-admin`, `firebase-testing`
2. write the code below.
3. Run `jest --watch` The error should occur

```
// FirestoreConnection.ts
import {DocumentTarget, RecordTypes} from "../../../shared";

import firebaseAdmin, {firestore} from "firebase-admin";
import keys from "../keys";



export default class FirestoreConnection {
  protected shopDomain: string;
  protected database: firestore.Firestore;
  
  constructor(shopDomain: string, database: firestore.Firestore) {
    this.shopDomain = shopDomain;
    this.database = database;
  }
  
  /** Matches the stated type against recordData shape
   */
  
  protected async addDocument(collectionName: string, documentData: object): Promise<firestore.DocumentSnapshot|null> {
    try {
      const newlyAddedDocument = await this.database
        .collection(collectionName)
        .add(documentData);
    
      return await newlyAddedDocument.get();
    }
    catch (e) {
      console.log(e, `=====error=====`);
      return null;
    }
  }
  
  // --------------- Public Methods
  
  public async createNew(type: RecordTypes, documentData: object): Promise<firestore.DocumentSnapshot|null> {
    
    // can be void/empty
    return await this.addDocument("testArea", documentData);
  }

}


// FirestoreConnection.test.ts
import * as firebaseTesting from "@firebase/testing";
import {RecordTypes} from "../../../../shared";

import FirestoreConnection from "../FirestoreConnection";
import {getDatabase, setDatabase} from "../../../../shared/database";

/* * * * * * * * * * * * * * * * * * * * *
                  Setup
* * * * * * * * * * * * * * * * * * * * */
const createTestDatabase = (credentials): any => {
  return firebaseTesting
    .initializeTestApp({
      projectId: 'testProject',
      auth: credentials
    })
    .firestore();
};

const nullAllApps = firebaseTesting
  .apps().map(app => app.delete());

const db = new FirestoreConnection('testShopDomain', createTestDatabase(null));

/* * * * * * * * * * * * * * * * * * * * *
                  Tests
* * * * * * * * * * * * * * * * * * * * */
test("creates new record", async () => {
  const addedDocument = await db
    .createNew(RecordTypes.globalRule, {
      storeId : "dummyStoreId"
      , globalPercent : 40
    });

  expect(addedDocument).toEqual({
    storeId : "dummyStoreId"
    , globalPercent : 40
    , badProp : 0
  });
}, 100000);
```

### What did you expect to see?

Test passes for basic google cloud firestore crud operation (create record).

### What did you see instead?

```
// terminal
● creates new record

    : Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error:

      51 | 
      52 | 
    > 53 | test("creates new record", async () => {
         | ^
      54 |   const addedDocument = await db
      55 |     .createNew(RecordTypes.globalRule, {
      56 |       storeId : "dummyStoreId"

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (functions/src/classes/__tests__/FirestoreConnection.test.ts:53:1)

  ● creates new record

    14 UNAVAILABLE: failed to connect to all addresses

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 skipped, 2 total
Snapshots:   0 total
Time:        106.03s, estimated 116s
Ran all test suites related to changed files.

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

I raised the async timeout threshold in jest's `test()` function from 5000ms to 100000ms. it had no effect, errors were the same.

**Comment by HofmannZ** [comment]
@SeanDez Do you only experience the issue in Jest tests?

**Comment by SeanDez** [comment]
@HofmannZ, yes, and only this specific test interacting with firebase. I was able to solve it by doing the following:

1. Enabled logging using `firestore.setLogFunction();`
2. It was found from the underlying error that the projectId `testProject` was invalid. Changing the projectId to testproject with all lowercase letters worked.
