### ISSUE TITLE
interop tests: dart_server crashes with "The method 'remove' was called on null"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21755]
In our cloud_to_cloud test suite, the dart server occasionally crashes (at which point it stops processing requests and all the interop tests against it fail).
Currently this is our most frequent interop_tests flake (failing ~ 10% of interop test runs).

For flakiness overview, see go/grpc-flaky
https://screenshot.googleplex.com/thTiGyktXen

Examples failures:
https://source.cloud.google.com/results/invocations/1b706719-f354-4485-a0bd-d35f426a41b8/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/f8663aa4-40e2-4a85-821f-e89fb22434e7/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/3f7eacf3-2d2b-4de0-b1cc-34332e4d51e7/targets/github%2Fgrpc%2Finterop_test/tests

As can be seen in the log, the dart server crashes with this failure (and all the subsequent request fail)
```
2020-01-21 10:59:35,874 Server listening on port 8080...
Socket error: HandshakeException: Connection terminated during handshake
Unhandled exception:
NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove(":status")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:283:23)
#2      ServerHandler_._sendError (package:grpc/src/server/handler.dart:348:5)
#3      ServerHandler_._onResponse (package:grpc/src/server/handler.dart:236:7)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:114:18)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#18     TestService.streamingInputCall (file:///var/local/git/grpc-dart/interop/bin/server.dart)
<asynchronous suspension>
#19     ServiceMethod.handle (package:grpc/src/server/service.dart:61:20)
#20     ServerHandler_._startStreamingRequest (package:grpc/src/server/handler.dart:151:30)
#21     ServerHandler_._onDataIdle (package:grpc/src/server/handler.dart:128:5)
<asynchronous suspension>
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     grpcDecompressor.<anonymous closure> (package:grpc/src/shared/message.dart:77:12)
#28     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _GrpcMessageConversionSink._addHeaders (package:grpc/src/shared/streams.dart:121:10)
#36     _GrpcMessageConversionSink.add (package:grpc/src/shared/streams.dart:129:7)
#37     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#42     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#43     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#47     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

2020-01-21 10:59:35,874 FAILED: interop_server_dart [ret=255, pid=6033, time=549.2sec]
```

**Comment by jtattermusch** [comment]
CC @sigurdm @mit-mit

**Comment by jtattermusch** [comment]
After some effort, I'm able to reproduce locally on my workstation:

Preparation:
1. clone grpc/grpc into ./grpc
2. clone grpc/grpc-dart into ./grpc-dart (the last **committed** version in this directory will be used for testing)
3. clone grpc/grpc-java into ./grpc-java (the last **committed** version in this directory will be used for testing)

Run command:
```
for a in `seq 1 20`; do echo "iteration $a"; DOCKERHUB_ORGANIZATION=grpctesting tools/run_tests/run_interop_tests.py -l dart go java -s dart --use_docker -t -j 8 || break; done;
```
it might take several iterations (and each iteration takes several minutes to run), but eventually interop tests are going to fail due dart server crashing with "The method 'remove' was called on null".
The setup is not ideal but allows some local debugging (make modifications to local clone of grpc-dart and commit, then test again).

**Comment by jtattermusch** [comment]
From my experiments It seems that  interaction  between go client and dart server might be the problem.
I'm able to reproduce with only the client go against dart:
`DOCKERHUB_ORGANIZATION=grpctesting tools/run_tests/run_interop_tests.py -l go -s dart --use_docker -t -j 8`
(this fails after several iterations, e.g. dart client vs dart server seems way more stable).

**Comment by sigurdm** [comment]
Thanks for the investigation and reproduction!

I will try to find some time to look into this.

**Comment by jtattermusch** [comment]
@sigurdm  thanks!

Here's a log that I got with my local repro (I added a few debug prints)

```
START: Building interop docker images.
PASSED: build_docker_dart [time=32.6sec, retries=0:0]
PASSED: build_docker_go [time=61.6sec, retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_dart
PASSED: cloud_to_cloud:go:dart_server:large_unary:tls [time=6.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:empty_unary:tls [time=6.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:empty_stream:tls [time=6.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:ping_pong:tls [time=6.8sec, retries=0:0]

FATAL: 2020/01/23 09:16:06 Failed to finish the server streaming rpc: rpc error: code = Unavailable desc = transport is closing
exit status 1
FAILED: cloud_to_cloud:go:dart_server:server_streaming:tls [ret=1, pid=218214, time=3.4sec]
PASSED: cloud_to_cloud:go:dart_server:cancel_after_begin:tls [time=3.4sec, retries=0:0]

TIMEOUT: cloud_to_cloud:go:dart_server:custom_metadata:tls [pid=218988, time=180.2sec]

TIMEOUT: cloud_to_cloud:go:dart_server:timeout_on_sleeping_server:tls [pid=218987, time=180.6sec]

TIMEOUT: cloud_to_cloud:go:dart_server:cancel_after_first_response:tls [pid=218349, time=184.0sec]

TIMEOUT: cloud_to_cloud:go:dart_server:client_streaming:tls [pid=218213, time=184.8sec]

TIMEOUT: cloud_to_cloud:go:dart_server:status_code_and_message:tls [pid=219688, time=181.3sec]

TIMEOUT: cloud_to_cloud:go:dart_server:unimplemented_method:tls [pid=219769, time=181.3sec]

TIMEOUT: cloud_to_cloud:go:dart_server:unimplemented_service:tls [pid=219881, time=181.2sec]
FAILED: Some tests failed

Server listening on port 8080...
empty call
  headers sent
  sendTrailers
unaryCall
  headers sent
  sendTrailers
fullDuplexCall
  sendTrailers
  sendTrailers:!_headersSent
fullDuplexCall
  headers sent
  sendTrailers
streamingOutputCall
  headers sent
  sendTrailers
streamingInputCall
  sendTrailers
  sendTrailers:!_headersSent
  sendTrailers
  sendTrailers:!_headersSent
Unhandled exception:
NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove(":status")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:286:23)
#2      ServerHandler_._sendError (package:grpc/src/server/handler.dart:351:5)
#3      ServerHandler_._onResponse (package:grpc/src/server/handler.dart:236:7)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#8      _StreamController._add (dart:async/stream_controller.dart:640:7)
#9      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:114:18)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#18     TestService.streamingInputCall (file:///var/local/git/grpc-dart/interop/bin/server.dart)
<asynchronous suspension>
#19     ServiceMethod.handle (package:grpc/src/server/service.dart:61:20)
#20     ServerHandler_._startStreamingRequest (package:grpc/src/server/handler.dart:151:30)
#21     ServerHandler_._onDataIdle (package:grpc/src/server/handler.dart:128:5)
<asynchronous suspension>
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     grpcDecompressor.<anonymous closure> (package:grpc/src/shared/message.dart:77:12)
#28     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _GrpcMessageConversionSink._addHeaders (package:grpc/src/shared/streams.dart:121:10)
#36     _GrpcMessageConversionSink.add (package:grpc/src/shared/streams.dart:129:7)
#37     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#42     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#43     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#47     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
FAILED: interop_server_dart [ret=255, pid=217314, time=373.5sec]
Server "dart" has exited prematurely.
```

**Comment by jtattermusch** [comment]
The interesting part is when the streamingInputCall seems to call sendTrailers twice and also evaluates   _headersSent as false twice  (it that a race condition?)
```
streamingInputCall
  sendTrailers
  sendTrailers:!_headersSent
  sendTrailers
  sendTrailers:!_headersSent
```
https://github.com/grpc/grpc-dart/blob/ae17e712e4f5431eb6664f0589899c77462e5475/lib/src/server/handler.dart#L283

**Comment by jtattermusch** [comment]
Same situation with a few more debug logs:
```
START: interop_server_dart
PASSED: cloud_to_cloud:go:dart_server:empty_unary:tls [time=8.0sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:large_unary:tls [time=8.0sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:ping_pong:tls [time=2.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:empty_stream:tls [time=2.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:client_streaming:tls [time=2.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:server_streaming:tls [time=2.4sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:cancel_after_first_response:tls [time=2.3sec, retries=0:0]
PASSED: cloud_to_cloud:go:dart_server:cancel_after_begin:tls [time=2.3sec, retries=0:0]

TIMEOUT: cloud_to_cloud:go:dart_server:timeout_on_sleeping_server:tls [pid=150258, time=180.3sec]

TIMEOUT: cloud_to_cloud:go:dart_server:custom_metadata:tls [pid=150260, time=180.7sec]

TIMEOUT: cloud_to_cloud:go:dart_server:status_code_and_message:tls [pid=151052, time=180.4sec]

TIMEOUT: cloud_to_cloud:go:dart_server:unimplemented_method:tls [pid=151135, time=180.4sec]

TIMEOUT: cloud_to_cloud:go:dart_server:unimplemented_service:tls [pid=151764, time=180.4sec]
FAILED: Some tests failed

Server listening on port 8080...
empty call [callHashcode:436953701]
  headers sent [handlerHashcode:436953701]
  sendTrailers [handlerHashcode:436953701]
unaryCall [callHashcode:540299868]
  headers sent [handlerHashcode:540299868]
  sendTrailers [handlerHashcode:540299868]
fullDuplexCall [callHashcode:652890549]
  headers sent [handlerHashcode:652890549]
  sendTrailers [handlerHashcode:652890549]
fullDuplexCall [callHashcode:880900767]
  sendTrailers [handlerHashcode:880900767]
  sendTrailers:!_headersSent [handlerHashcode:880900767]
streamingInputCall [callHashcode:590507184]
streamingOutputCall [callHashcode:914915549]
  headers sent [handlerHashcode:914915549]
  sendTrailers [handlerHashcode:914915549]
  headers sent [handlerHashcode:590507184]
  sendTrailers [handlerHashcode:590507184]
fullDuplexCall [callHashcode:444430933]
  headers sent [handlerHashcode:444430933]
streamingInputCall [callHashcode:104740291]
  sendTrailers [handlerHashcode:104740291]
  sendTrailers:!_headersSent [handlerHashcode:104740291]
  sendTrailers [handlerHashcode:104740291]
  sendTrailers:!_headersSent [handlerHashcode:104740291]
Unhandled exception:
NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove(":status")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:286:23)
```

From this log, one can see that the handler with hashcode 104740291 really does invoke sendTrailers twice

**Comment by jtattermusch** [comment]
in not 100% sure, but from my investigation is looks like that the problematic scenario is 
"cancel_after_begin" (see https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#cancel_after_begin)
- client starts a StreamingInputCall and immediately cancels it.

In the current situation it seems that this has the ability to kill the dart server (not clear if other concurrent request must be running at the same time for this to happen).

**Comment by jtattermusch** [comment]
Hopefully this is fixed by https://github.com/grpc/grpc-dart/pull/274.
We can take a look at go/grpc-flaky next week to confirm that the dart_server failures are gone.
