### ISSUE TITLE
Installation of grpcio Python package on Alpine Linux fails

### ISSUE THREAD

**Issue by comedian780** [grpc/grpc#21918]
### What version of gRPC and what language are you using?
Python grpcio version 1.27.0

### What operating system (Linux, Windows,...) and version?
python:alpine Docker image which contains Alpine Linux 3.11

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.1, installation of grpcio via pip

### What did you do?
Start container:
```sh
docker run -it python:alpine ash
```
installation inside container:
```sh
apk add build-base
pip install grpcio
```

### What did you expect to see?
```
Successfully built grpcio
Installing collected packages: six, grpcio
Successfully installed grpcio-1.27.0 six-1.14.0
```

### What did you see instead?
Installation exits with failure because it seems abseil-cpp can't find `linux/futex.h`.

Logs:
```
 In file included from third_party/abseil-cpp/absl/base/internal/spinlock_wait.cc:27:
  third_party/abseil-cpp/absl/base/internal/spinlock_linux.inc:17:10: fatal error: linux/futex.h: No such file or directory
     17 | #include <linux/futex.h>
        |          ^~~~~~~~~~~~~~~
  compilation terminated.
  creating tmp
  creating tmp/tmpfdam0s70
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.8 -c /tmp/tmpfdam0s70/a.c -o tmp/tmpfdam0s70/a.o
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] +
    File "/tmp/pip-install-7kd3fdwz/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/usr/local/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/local/lib/python3.8/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/local/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-7kd3fdwz/grpcio/src/python/grpcio/commands.py", line 260, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "/usr/local/lib/python3.8/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/local/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7kd3fdwz/grpcio/setup.py", line 384, in <module>
      setuptools.setup(
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-7kd3fdwz/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
      raise CommandError(
  commands.CommandError: Failed `build_ext` step:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] +
    File "/tmp/pip-install-7kd3fdwz/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/usr/local/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/local/lib/python3.8/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/local/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-7kd3fdwz/grpcio/src/python/grpcio/commands.py", line 260, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "/usr/local/lib/python3.8/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/local/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'gcc' failed with exit status 1

  ----------------------------------------
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
```

### Anything else we should know about your project / environment?
`pip install grpcio==1.26.0` works as expected

**Comment by malcolm-white** [comment]
I am seeing a "Could not find <Python.h>" failure in Docker on ubuntu 18.04 (`nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`) if I do not first install python3-dev, which was not necessary with 1.26.0

**Comment by lidizheng** [comment]
@comedian780 Alpine is not `manylinux` compatible, we are still pending on PyPA 
 releasing a new standard of wheels (https://github.com/pypa/manylinux/issues/37).

Back to the failure itself, the latest release starts depending on `Abseil` which introduces new transitive dependency. The `<linux/futex.h>` seems due to missing the `linux-headers` package. I manually tested that it should be able to build after installing it:

```
apk add linux-headers
```

---

@malcolm-white The new release `v1.27.0` only releases binary wheels for `manylinux2010`, which will only be accepted by `pip > 19.0.0`. So, can you upgrade your `pip` and try again?

**Comment by malcolm-white** [comment]
@lidizheng Thanks for the update. I'm using pip via bazel/rules_python's pip3_import, and I can't find any documentation on how to specify a pip version. I have a workaround with installing python3-dev.

**Comment by gnossen** [comment]
@malcolm-white `rules_python` is not hermetic. It will depend on your system installation of `pip`. So, it should be equivalent to doing `python -m pip` or `python3 -m pip` depending on whether your target specifies a version of Python 2 or Python 3.

**Comment by comedian780** [comment]
@lidizheng Thanks for the clarification. I can confirm that adding the `linux-headers` resolves the build issues. Tested it with 1.27.1.
