### ISSUE TITLE
FLAKE: //test/cpp/microbenchmarks:bm_metadata report a memory leak under ASAN

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#22140]
The test was enabled here: #21739

https://source.cloud.google.com/results/invocations/f8e55220-b108-4b2d-82e0-34a2beafd4ab/targets/%2F%2Ftest%2Fcpp%2Fmicrobenchmarks:bm_metadata/log
https://source.cloud.google.com/results/invocations/d290cb99-2405-46b2-b9e8-3c98ead1886b/targets/%2F%2Ftest%2Fcpp%2Fmicrobenchmarks:bm_metadata/log
https://source.cloud.google.com/results/invocations/acf5808b-4cf0-436b-b599-235494f316b6/targets/%2F%2Ftest%2Fcpp%2Fmicrobenchmarks:bm_metadata/log

```
BM_MetadataRefUnrefStatic                              64.4 ns         64.2 ns     11124181
D0225 03:01:19.292227846      21 slice_intern.cc:360]        WARNING: 1 metadata strings were leaked
D0225 03:01:19.292306883      21 slice_intern.cc:366]        LEAKED: 61 62 63 'abc'

=================================================================
==17==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 123 byte(s) in 1 object(s) allocated from:
    #0 0x49a81d in malloc /tmp/clang-build/src/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x7fef80943d78 in gpr_malloc /proc/self/cwd/src/core/lib/gpr/alloc.cc:32:7
    #2 0x7fef80bec755 in grpc_core::InternedSliceRefcount* InternNewStringLocked<grpc_slice>(slice_shard*, unsigned long, unsigned int, grpc_slice const&) /proc/self/cwd/src/core/lib/slice/slice_intern.cc:213:43
    #3 0x7fef80beaa64 in grpc_core::InternedSliceRefcount* FindOrCreateInternedSlice<grpc_slice>(unsigned int, grpc_slice const&) /proc/self/cwd/src/core/lib/slice/slice_intern.cc:267:9
    #4 0x7fef80bea4d0 in grpc_core::ManagedMemorySlice::ManagedMemorySlice(grpc_slice const*) /proc/self/cwd/src/core/lib/slice/slice_intern.cc:303:38
    #5 0x4cc1ad in BM_SliceReIntern(benchmark::State&) /proc/self/cwd/test/cpp/microbenchmarks/bm_metadata.cc:62:33
    #6 0x7fef80658527 in benchmark::internal::FunctionBenchmark::Run(benchmark::State&) /proc/self/cwd/external/com_github_google_benchmark/src/benchmark_register.cc:496:42
    #7 0x7fef8064e05f in benchmark::internal::BenchmarkInstance::Run(unsigned long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*) const /proc/self/cwd/external/com_github_google_benchmark/src/benchmark_api_internal.cc:10:14
```

**Comment by jtattermusch** [comment]
This is actually one of our top flakes currently.
