### ISSUE TITLE
`gpr_ref ()` involved an operation on null pointer.

### ISSUE THREAD

**Issue by vertextao** [grpc/grpc#22141]
### What version of gRPC and what language are you using?

* gRPC v1.8.3
* C++

### What operating system (Linux, Windows,...) and version?

* CentOS Linux release 7.7.1908 (Core)

### What runtime / compiler are you using (e.g. python version or version of gcc)

* gcc 4.8.5

```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
```

### What did you do?

Just normally linked the grpc static libraries into my project.

### What did you expect to see?

Runs stably.

### What did you see instead?

Occasionally, `Program terminated with signal 11, Segmentation fault.`

### Anything else we should know about your project / environment?

* `gpr_ref ()` involved an operation on null pointer.

```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000079e3d0 in gpr_ref ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64
(gdb) bt
#0  0x000000000079e3d0 in gpr_ref ()
#1  0x0000000000799c09 in grpc_connected_subchannel_ref ()
#2  0x00000000007dd2cc in ?? ()
#3  0x00000000007afa56 in ?? ()
#4  0x00000000007b08e2 in ?? ()
#5  0x0000000000780bf4 in grpc_combiner_continue_exec_ctx ()
#6  0x0000000000782d02 in grpc_exec_ctx_flush ()
#7  0x00000000007b6755 in ?? ()
#8  0x0000000000793f9d in ?? ()
#9  0x000000000079459b in grpc_completion_queue_next ()
#10 0x00000000007658e8 in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) ()
#11 0x00000000006df30a in Next (ok=0x7fe262ffcd73, tag=0x7fe262ffcd78, this=0x1f807a0) at /usr/local/include/grpc++/impl/codegen/completion_queue.h:170
#12 ...
#13 ...
#14 0x00007fe2694a0e65 in start_thread () from /lib64/libpthread.so.0
#15 0x00007fe2691c988d in clone () from /lib64/libc.so.6
(gdb) i r
rax            0x7fe240000fe0   140609713082336
rbx            0x0      0
rcx            0x7fe25570a920   140610072783136
rdx            0x7fe262ffc5b0   140610300265904
rsi            0x7fe240000a70   140609713080944
rdi            0x0      0
rbp            0x7fe25570a920   0x7fe25570a920
rsp            0x7fe262ffc558   0x7fe262ffc558
r8             0x7fe25570a928   140610072783144
r9             0x0      0
r10            0x4      4
r11            0xc7e12187356a5  3516315905250981
r12            0x7fe25570a7a0   140610072782752
r13            0x7fe254002278   140610048631416
r14            0x7fe262ffcc60   140610300267616
r15            0x7fe25570a7c0   140610072782784
rip            0x79e3d0 0x79e3d0 <gpr_ref>
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
(gdb) disassemble 
Dump of assembler code for function gpr_ref:
=> 0x000000000079e3d0 <+0>:     lock addq $0x1,(%rdi)
   0x000000000079e3d5 <+5>:     retq   
End of assembler dump.
```

**Comment by yashykt** [comment]
Hi, sorry for the late response. Please provide steps to reproduce this issue.

**Comment by vertextao** [comment]
@yashykt I'm not sure abort steps to reproduce this issue. This issue occurred occasionally in a 24hr service, I could just get the coredump. Do you have any advice to gather more information?

**Comment by yashykt** [comment]
Hi @vertextao I just noticed that the grpc version you are using is pretty old. Please try using the latest version. 

Also, with a reproduction, it's easier to debug but I understand that that's not always possible. In that case, we can collect logs and hope for the best.

**Comment by vertextao** [comment]
@yashykt ok, this may be the best idea.
