### ISSUE TITLE
Why are these two C# gRPC examples run in different ways?

### ISSUE THREAD

**Issue by grassit** [grpc/grpc#22157]
In example HelloWorld in https://grpc.io/docs/quickstart/csharp/

> from the examples/csharp/Helloworld directory:
> 
> Run the server
> 
>     cd GreeterServer
>     dotnet run -f netcoreapp2.1
> 
> In another terminal, run the client
> 
>     cd GreeterClient
>     dotnet run -f netcoreapp2.1

In example [RouteGuide](https://github.com/grpc/grpc/tree/v1.27.0/examples/csharp/RouteGuide) in https://grpc.io/docs/tutorials/basic/csharp/

> Run the server, which will listen on port 50052:
> 
>     cd RouteGuideServer/bin/Debug/netcoreapp2.1
>     dotnet exec RouteGuideServer.dll
> 
> Run the client (in a different terminal):
> 
>     cd RouteGuideClient/bin/Debug/netcoreapp2.1
>     dotnet exec RouteGuideClient.dll

In the second example, why  use `dotnet exec`  not `dotnet run`? (https://github.com/dotnet/sdk/issues/5573 says `dotnet exec` is for internal use only)

Can I run the service and client in the second example, using the same way of running first example? Why do I have following errors?

    $ cd RouteGuideServer
    $ dotnet run     
    Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/t/RouteGuide/RouteGuideServer/route_guide_db.json'.
    File name: '/home/t/RouteGuide/RouteGuideServer/route_guide_db.json'
       at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
       at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
       at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
       at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
       at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
       at System.IO.File.InternalReadAllText(String path, Encoding encoding)
       at System.IO.File.ReadAllText(String path)
       at Routeguide.RouteGuideUtil.ParseFeatures(String filename) in /home/t/RouteGuide/RouteGuide/RouteGuideUtil.cs:line 98
       at Routeguide.Program.Main(String[] args) in /home/t/RouteGuide/RouteGuideServer/Program.cs:line 30

and in another shell:

    $ cd RouteGuideClient
    $ dotnet run 
    Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/t/RouteGuide/RouteGuideClient/route_guide_db.json'.
    File name: '/home/t/RouteGuide/RouteGuideClient/route_guide_db.json'
       at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
       at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
       at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
       at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
       at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
       at System.IO.File.InternalReadAllText(String path, Encoding encoding)
       at System.IO.File.ReadAllText(String path)
       at Routeguide.RouteGuideUtil.ParseFeatures(String filename) in /home/t/RouteGuide/RouteGuide/RouteGuideUtil.cs:line 98
       at Routeguide.Program.Main(String[] args) in /home/t/RouteGuide/RouteGuideClient/Program.cs:line 231

Thanks.

**Comment by jtattermusch** [comment]
I agree that this is inconsistent and just `dotnet run` would have been simpler, but currently the `dotnet exec RouteGuideServer.dll` is required because when running the client/server, you actually need to be in the output directory (hence the `cd RouteGuideServer/bin/Debug/netcoreapp2.1`), otherwise it won't find route_guide_db.json - exactly as you reported.

**Comment by jtattermusch** [comment]
This should be fixed at some point, but it's not urgent because the example works the way it is.

**Comment by yashykt** [comment]
Since @jtattermusch used the word 'fixed', i'm going to change this to a kind/bug

**Comment by yashykt** [comment]
If it's actually a question, please move the question to one of the larger community forums

**Comment by jtattermusch** [comment]
I reclassified as "enhancement" because currently the instructions are working just fine.
