### ISSUE TITLE
MSAN Error in grpc_build_protobuf_at_head

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#22191]
This job is continuously broken on master.

https://fusion.corp.google.com/runanalysis/buildartifacts/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_protobuf_at_head/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_protobuf_at_head/KOKORO/94fde3f3-f624-4650-97b0-6b4c26bfbb6c/1582914038016/build%20%233066/Targets

```
/var/local/git/grpc/bins/msan/protobuf/protoc -Ithird_party/protobuf/src -I. --grpc_out=/var/local/git/grpc/gens --plugin=protoc-gen-grpc=/var/local/git/grpc/bins/msan/grpc_cpp_plugin test/core/tsi/alts/fake_handshaker/transport_security_common.proto
==15614==WARNING: MemorySanitizer: use-of-uninitialized-value
==15615==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7e00002254a4 in std::__1::basic_istream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) /usr/include/c++/v1/istream:268:9
    #1 0x7e00002205de in std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) /usr/include/c++/v1/istream:1591:57
    #2 0x7e00001de323 in std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /usr/include/c++/v1/istream:1636:12
    #3 0x7e00001de323 in grpc_generator::Split(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:173
    #4 0x7e00001ca00c in void grpc_generator::GetComment<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, grpc_generator::CommentType, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:229:7
    #5 0x7e00001c4e24 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > grpc_generator::GetPrefixedComments<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /var/local/git/grpc/./src/compiler/generator_helpers.h:262:5
    #6 0x7e00001c37d5 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > GetCommentsHelper<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /var/local/git/grpc/./src/compiler/protobuf_plugin.h:34:10
    #7 0x7e00001bc720 in ProtoBufFile::GetLeadingComments(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const /var/local/git/grpc/./src/compiler/protobuf_plugin.h:182:12
    #8 0x7e00002f007c in grpc_cpp_generator::GetHeaderPrologue(grpc_generator::File*, grpc_cpp_generator::Parameters const&) /var/local/git/grpc/src/compiler/cpp_generator.cc:105:43
    #9 0x7e0000183fa2 in CppGrpcGenerator::Generate(google::protobuf::FileDescriptor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const /var/local/git/grpc/./src/compiler/cpp_plugin.h:107:9
    #10 0x7e000055b82e in google::protobuf::compiler::CodeGenerator::GenerateAll(std::__1::vector<google::protobuf::FileDescriptor const*, std::__1::allocator<google::protobuf::FileDescriptor const*> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/code_generator.cc:58:17
    #11 0x7e0000560e0f in google::protobuf::compiler::GenerateCode(google::protobuf::compiler::CodeGeneratorRequest const&, google::protobuf::compiler::CodeGenerator const&, google::protobuf::compiler::CodeGeneratorResponse*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/plugin.cc:132:30
    #12 0x7e000056280a in google::protobuf::compiler::PluginMain(int, char**, google::protobuf::compiler::CodeGenerator const*) /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/plugin.cc:169:7
    #13 0x7e000012ad23 in grpc::protobuf::compiler::PluginMain(int, char**, google::protobuf::compiler::CodeGenerator const*) /var/local/git/grpc/./src/compiler/config.h:40:10
    #14 0x7e000012a88c in main /var/local/git/grpc/src/compiler/cpp_plugin.cc:25:10
    #15 0x7f8b2fffab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #16 0x7e00000b44a7 in _start (/var/local/git/grpc/bins/msan/grpc_cpp_plugin+0x7e00000b44a7)

  Uninitialized value was created by an allocation of 'iss' in the stack frame of function '_ZN14grpc_generator5SplitERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEcPNS0_6vectorIS6_NS4_IS6_EEEE'
    #0 0x7e00001da710 in grpc_generator::Split(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:170

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/include/c++/v1/istream:268:9 in std::__1::basic_istream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool)
Exiting
--grpc_out: protoc-gen-grpc: Plugin failed with status code 77.
Uninitialized bytes in __interceptor_fwrite at offset 0 inside [0x7fffacaec37f, 1)
==15589==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7e00002254a4 in std::__1::basic_istream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) /usr/include/c++/v1/istream:268:9
    #1 0x7e00002205de in std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) /usr/include/c++/v1/istream:1591:57
    #2 0x7e00001de323 in std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /usr/include/c++/v1/istream:1636:12
    #3 0x7e00001de323 in grpc_generator::Split(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:173
    #4 0x7e00001ca00c in void grpc_generator::GetComment<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, grpc_generator::CommentType, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:229:7
    #5 0x7e00001c4e24 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > grpc_generator::GetPrefixedComments<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /var/local/git/grpc/./src/compiler/generator_helpers.h:262:5
    #6 0x7e00001c37d5 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > GetCommentsHelper<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /var/local/git/grpc/./src/compiler/protobuf_plugin.h:34:10
    #7 0x7e00001bc720 in ProtoBufFile::GetLeadingComments(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const /var/local/git/grpc/./src/compiler/protobuf_plugin.h:182:12
    #0 0x7e00002254a4 in std::__1::basic_istream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) /usr/include/c++/v1/istream:268:9
    #1 0x7e00002205de in std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) /usr/include/c++/v1/istream:1591:57
    #2 0x7e00001de323 in std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /usr/include/c++/v1/istream:1636:12
    #3 0x7e00001de323 in grpc_generator::Split(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:173
    #4 0x7e00001ca00c in void grpc_generator::GetComment<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, grpc_generator::CommentType, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:229:7
    #5 0x7e00001c4e24 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > grpc_generator::GetPrefixedComments<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /var/local/git/grpc/./src/compiler/generator_helpers.h:262:5
    #6 0x7e00001c37d5 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > GetCommentsHelper<google::protobuf::FileDescriptor>(google::protobuf::FileDescriptor const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /var/local/git/grpc/./src/compiler/protobuf_plugin.h:34:10
    #7 0x7e00001bc720 in ProtoBufFile::GetLeadingComments(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const /var/local/git/grpc/./src/compiler/protobuf_plugin.h:182:12
    #8 0x7e00002f007c in grpc_cpp_generator::GetHeaderPrologue(grpc_generator::File*, grpc_cpp_generator::Parameters const&) /var/local/git/grpc/src/compiler/cpp_generator.cc:105:43
    #9 0x7e0000183fa2 in CppGrpcGenerator::Generate(google::protobuf::FileDescriptor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const /var/local/git/grpc/./src/compiler/cpp_plugin.h:107:9
    #10 0x7e000055b82e in google::protobuf::compiler::CodeGenerator::GenerateAll(std::__1::vector<google::protobuf::FileDescriptor const*, std::__1::allocator<google::protobuf::FileDescriptor const*> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/code_generator.cc:58:17
    #8 0x7e00002f007c in grpc_cpp_generator::GetHeaderPrologue(grpc_generator::File*, grpc_cpp_generator::Parameters const&) /var/local/git/grpc/src/compiler/cpp_generator.cc:105:43
    #9 0x7e0000183fa2 in CppGrpcGenerator::Generate(google::protobuf::FileDescriptor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const /var/local/git/grpc/./src/compiler/cpp_plugin.h:107:9
    #11 0x7e0000560e0f in google::protobuf::compiler::GenerateCode(google::protobuf::compiler::CodeGeneratorRequest const&, google::protobuf::compiler::CodeGenerator const&, google::protobuf::compiler::CodeGeneratorResponse*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/plugin.cc:132:30
    #12 0x7e000056280a in google::protobuf::compiler::PluginMain(int, char**, google::protobuf::compiler::CodeGenerator const*) /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/plugin.cc:169:7
    #13 0x7e000012ad23 in grpc::protobuf::compiler::PluginMain(int, char**, google::protobuf::compiler::CodeGenerator const*) /var/local/git/grpc/./src/compiler/config.h:40:10
    #14 0x7e000012a88c in main /var/local/git/grpc/src/compiler/cpp_plugin.cc:25:10
    #10 0x7e000055b82e in google::protobuf::compiler::CodeGenerator::GenerateAll(std::__1::vector<google::protobuf::FileDescriptor const*, std::__1::allocator<google::protobuf::FileDescriptor const*> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const /var/local/git/grpc/third_party/protobuf/src/google/protobuf/compiler/code_generator.cc:58:17
    #15 0x7f24610f0b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #16 0x7e00000b44a7 in _start (/var/local/git/grpc/bins/msan/grpc_cpp_plugin+0x7e00000b44a7)

  Uninitialized value was created by an allocation of 'iss' in the stack frame of function '_ZN14grpc_generator5SplitERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEcPNS0_6vectorIS6_NS4_IS6_EEEE'
    #0 0x7e00001da710 in grpc_generator::Split(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) /var/local/git/grpc/./src/compiler/generator_helpers.h:170
```

**Comment by yashykt** [comment]
It seems to be passing now. I didn't make any change.
I don't see any gRPC/protobuf change either
