### ISSUE TITLE
"gpr_mu_lock" received signal SIGSEGV, program crash.

### ISSUE THREAD

**Issue by jinguo998** [grpc/grpc#22198]
### What version of gRPC and what language are you using?
grpc-1.22.0, but the same problem with grpc-1.27.0
c++
### What operating system (Linux, Windows,...) and version?
Linux ubuntu1 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:14:11 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
### What runtime / compiler are you using (e.g. python version or version of gcc)
root@ubuntu1:~# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-unknown-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-unknown-linux-gnu
Configured with: /home/wzh/tools/gcc-7.3.0-update/gcc_source/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-languages=c,c++,fortran,go --disable-multilib
Thread model: posix
gcc version 7.3.0 (GCC)

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
1. download grpc source code and run `make static -j HAS_SYSTEM_PROTOBUF=false`
2. a service with 2 client streaming RPCs  ,1 server streaming RPC and 2 unary RPCs defined in `.proto` file.
3. generate grpc.pb.cc ,grpc.pb.h, pb.h, pb.cc with protoc in `grpc/bins/opt/protobuf/protoc`
4. in my code, 5 stubs shares a grpc channel in 5 thread
5. compile generated code and my own source code with `CXXFLAGS = -g -O0`
6. run program
### What did you expect to see?
No segmentfault.

### What did you see instead?
program crash with SIGSEGV
```
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x249935480000) at pthread_mutex_lock.c:65
#1  0x000000000058e72c in gpr_mu_lock (mu=<optimized out>) at src/core/lib/gpr/sync_posix.cc:103
#2  0x00000000005af150 in ExecCtxPluck::CheckReadyToFinish (this=<optimized out>)
    at src/core/lib/surface/completion_queue.cc:1158
#3  0x00000000005d89e8 in grpc_core::ExecCtx::IsReadyToFinish (this=<optimized out>) at ./src/core/lib/iomgr/exec_ctx.h:168
#4  grpc_combiner_continue_exec_ctx () at src/core/lib/iomgr/combiner.cc:238
#5  0x0000000000596f94 in grpc_core::ExecCtx::Flush (this=0xffffe7fb5000) at src/core/lib/iomgr/exec_ctx.cc:151
#6  0x0000000000625fd0 in pollset_work (pollset=0x24993548, worker_hdl=<optimized out>, deadline=<optimized out>)
    at src/core/lib/iomgr/ev_epollex_linux.cc:1151
#7  0x00000000005ae098 in cq_pluck (cq=0x24993450, tag=0xffffe7fb50d8, deadline=..., reserved=<optimized out>)
    at src/core/lib/surface/completion_queue.cc:1282
#8  0x0000000000432c40 in grpc_impl::CompletionQueue::Pluck(grpc::internal::CompletionQueueTag*) ()
#9  0x000000000044feb8 in grpc::ClientReader<saverpc::Task>::Read(saverpc::Task*) ()
#10 0x00000000004b2ee8 in GrpcCmdHandler::GetTask() ()
#11 0x00000000004b27bc in GrpcCmdHandler::Start() ()
#12 0x00000000004c49ec in Application::Start() ()
#13 0x00000000004c58b0 in main ()
(gdb) p *(ExecCtxPluck*)0xffffe7fb5000
$1 = {<grpc_core::ExecCtx> = {_vptr.ExecCtx = 0x821eb0 <vtable for ExecCtxPluck+16>, closure_list_ = {head = 0x0, tail = 0x0}, combiner_data_ = {active_combiner = 0x2498b970, last_combiner = 0x2498b970}, flags_ = 0, starting_cpu_ = 0, now_is_valid_ = false, now_ = 21794, static exec_ctx_ = {value = 281474573750272}, last_exec_ctx_ = 0x0}, check_ready_to_finish_arg_ = 0xffffe7fb4fd0}
(gdb) p *((cq_is_finished_arg*)0xffffe7fb4fd0)
$2 = {last_seen_things_queued_ever = 1583119012, cq = 0x2499344e, deadline = 9223372036854775807, stolen_completion = 0x0, tag = 0xffffe7fb50d8, first_loop = false}
(gdb) p *((cq_is_finished_arg*)0xffffe7fb4fd0)->cq
$3 = {owning_refs = {count = 262144}, mu = 0x249935480000, vtable = 0x81b0e00000, poller_vtable = 0x821ec80000, pollset_shutdown_done = {next_data = {next = 0x0, atm_next = {next = 0}, scratch = 0}, cb = 0x5aded00000, cb_arg = 0x249934500000, scheduler = 0x82e9080000, error_data = {error = 0x0, scratch = 0}}, num_polls = 917504}
(gdb) p *((cq_is_finished_arg*)0xffffe7fb4fd0)->cq->mu
Cannot access memory at address 0x249935480000

(gdb)  p ((cq_is_finished_arg*)0xffffe7fb4fd0)->cq
$4 = (grpc_completion_queue *) 0x2499344e
(gdb) p *(grpc_completion_queue *) 0x2499344e
$5 = {owning_refs = {count = 262144}, mu = 0x249935480000, vtable = 0x81b0e00000, poller_vtable = 0x821ec80000,
  pollset_shutdown_done = {next_data = {next = 0x0, atm_next = {next = 0}, scratch = 0}, cb = 0x5aded00000,
    cb_arg = 0x249934500000, scheduler = 0x82e9080000, error_data = {error = 0x0, scratch = 0}}, num_polls = 917504}
(gdb) p *(grpc_completion_queue *) 0x24993450
$6 = {owning_refs = {count = 4}, mu = 0x24993548, vtable = 0x81b0e0 <g_cq_vtable+72>,
  poller_vtable = 0x821ec8 <(anonymous namespace)::g_poller_vtable_by_poller_type>, pollset_shutdown_done = {next_data = {
      next = 0x0, atm_next = {next = 0}, scratch = 0}, cb = 0x5aded0 <on_pollset_shutdown_done(void*, grpc_error*)>,
    cb_arg = 0x24993450, scheduler = 0x82e908 <exec_ctx_scheduler>, error_data = {error = 0x0, scratch = 0}}, num_polls = 14}
(gdb) p *((grpc_completion_queue *) 0x24993450)->mu
$7 = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0,
      __next = 0x0}}, __size = '\000' <repeats 47 times>, __align = 0}
```
It seems that the value of `check_ready_to_finish_arg_->cq` should be `0x24993450` but it changes to `0x2499344e`
<details>
<summary>full backtrace </summary>

```
Thread 10 (Thread 0xffff81e08100 (LWP 43372)):
#0  0x0000ffff8378e600 in __GI_epoll_pwait (epfd=<optimized out>, events=0xffff81e065d8, maxevents=<optimized out>, timeout=614000952, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x000000000048e8c0 in ExeProxy::StartReceiveMessage(ReporterIntf&) ()
#2  0x000000000048e7c4 in ExeProxy::StartCollect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ReporterIntf&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#3  0x00000000004ba8e4 in ExeCollector::Start(ReporterIntf&) ()
#4  0x00000000004c5be0 in MetricTask::Run(Reporter&) ()
#5  0x00000000004c13e8 in MetricTaskManager::ExecuteTask(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Reporter&) ()
#6  0x0000000000461e94 in MetricThread::Start()::{lambda()#1}::operator()() const ()
#7  0x0000000000462220 in void std::__invoke_impl<void, MetricThread::Start()::{lambda()#1}>(std::__invoke_other, MetricThread::Start()::{lambda()#1}&&) ()
#8  0x0000000000462034 in std::__invoke_result<MetricThread::Start()::{lambda()#1}>::type std::__invoke<MetricThread::Start()::{lambda()#1}>(std::__invoke_result&&, (MetricThread::Start()::{lambda()#1}&&)...) ()
#9  0x00000000004624d0 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#10 0x00000000004624a4 in std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> >::operator()() ()
#11 0x0000000000462484 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> > >::_M_run() ()
#12 0x000000000065fc34 in std::execute_native_thread_routine (__p=0x24992730) at /home/wzh/tools/gcc-7.3.0-update/gcc_source/libstdc++-v3/src/c++11/thread.cc:83
#13 0x0000ffff8391c088 in start_thread (arg=0xffffe7fb551f) at pthread_create.c:463
#14 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 9 (Thread 0xffff7affd100 (LWP 43376)):
#0  0x0000ffff83760728 in __GI___nanosleep (requested_time=0xffff7affc7f8, requested_time@entry=0xffff7affc808, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000ffff83787fec in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x00000000004b2760 in GrpcCmdHandler::Start()::{lambda()#1}::operator()() const ()
#3  0x00000000004b37a0 in void std::__invoke_impl<void, GrpcCmdHandler::Start()::{lambda()#1}>(std::__invoke_other, GrpcCmdHandler::Start()::{lambda()#1}&&) ()
#4  0x00000000004b35b8 in std::__invoke_result<GrpcCmdHandler::Start()::{lambda()#1}>::type std::__invoke<GrpcCmdHandler::Start()::{lambda()#1}>(std::__invoke_result&&, (GrpcCmdHandler::Start()::{lambda()#1}&&)...) ()
#5  0x00000000004b3a50 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<GrpcCmdHandler::Start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#6  0x00000000004b3a24 in std::thread::_Invoker<std::tuple<GrpcCmdHandler::Start()::{lambda()#1}> >::operator()() ()
#7  0x00000000004b3a04 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<GrpcCmdHandler::Start()::{lambda()#1}> > >::_M_run() ()
#8  0x000000000065fc34 in std::execute_native_thread_routine (__p=0x24992cb0) at /home/wzh/tools/gcc-7.3.0-update/gcc_source/libstdc++-v3/src/c++11/thread.cc:83
#9  0x0000ffff8391c088 in start_thread (arg=0xffffe7fb553f) at pthread_create.c:463
#10 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 8 (Thread 0xffff82609100 (LWP 43371)):
#0  0x0000ffff83922544 in futex_reltimed_wait_cancelable (private=<optimized out>, reltime=0xffff00000000, expected=0, futex_word=0x831c18 <g_cv_wait+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
#1  __pthread_cond_wait_common (abstime=0xffff826087b0, mutex=0x831bb8 <g_mu>, cond=0x831bf0 <g_cv_wait>) at pthread_cond_wait.c:533
#2  __pthread_cond_timedwait (cond=cond@entry=0x831bf0 <g_cv_wait>, mutex=mutex@entry=0x831bb8 <g_mu>, abstime=0xffff826087b0, abstime@entry=0xffff826087d0) at pthread_cond_wait.c:667
#3  0x000000000058e998 in gpr_cv_wait (cv=cv@entry=0x831bf0 <g_cv_wait>, mu=mu@entry=0x831bb8 <g_mu>, abs_deadline=...) at src/core/lib/gpr/sync_posix.cc:233
#4  0x00000000005a2434 in wait_until (next=<optimized out>) at src/core/lib/iomgr/timer_manager.cc:211
#5  timer_main_loop () at src/core/lib/iomgr/timer_manager.cc:265
#6  timer_thread (completed_thread_ptr=0x2495dc90) at src/core/lib/iomgr/timer_manager.cc:294
#7  0x00000000005d1a54 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>) at src/core/lib/gprpp/thd_posix.cc:114
#8  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at src/core/lib/gprpp/thd_posix.cc:119
#9  0x0000ffff8391c088 in start_thread (arg=0xffff82e0968f) at pthread_create.c:463
--Type <RET> for more, q to quit, c to continue without paging--
#10 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 7 (Thread 0xffff80e06100 (LWP 43374)):
#0  0x0000ffff83760728 in __GI___nanosleep (requested_time=0xffff80e057b8, requested_time@entry=0xffff80e057c8, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000ffff83787fec in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x0000000000461e00 in MetricThread::Start()::{lambda()#1}::operator()() const ()
#3  0x0000000000462220 in void std::__invoke_impl<void, MetricThread::Start()::{lambda()#1}>(std::__invoke_other, MetricThread::Start()::{lambda()#1}&&) ()
#4  0x0000000000462034 in std::__invoke_result<MetricThread::Start()::{lambda()#1}>::type std::__invoke<MetricThread::Start()::{lambda()#1}>(std::__invoke_result&&, (MetricThread::Start()::{lambda()#1}&&)...) ()
#5  0x00000000004624d0 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#6  0x00000000004624a4 in std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> >::operator()() ()
#7  0x0000000000462484 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> > >::_M_run() ()
#8  0x000000000065fc34 in std::execute_native_thread_routine (__p=0x249929f0) at /home/wzh/tools/gcc-7.3.0-update/gcc_source/libstdc++-v3/src/c++11/thread.cc:83
#9  0x0000ffff8391c088 in start_thread (arg=0xffffe7fb551f) at pthread_create.c:463
#10 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 6 (Thread 0xffff82e0a100 (LWP 43370)):
#0  0x0000ffff8392222c in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x831c18 <g_cv_wait+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x831bb8 <g_mu>, cond=0x831bf0 <g_cv_wait>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x831bf0 <g_cv_wait>, mutex=mutex@entry=0x831bb8 <g_mu>) at pthread_cond_wait.c:655
#3  0x000000000058e944 in gpr_cv_wait (cv=cv@entry=0x831bf0 <g_cv_wait>, mu=mu@entry=0x831bb8 <g_mu>, abs_deadline=...) at src/core/lib/gpr/sync_posix.cc:217
#4  0x00000000005a2434 in wait_until (next=<optimized out>) at src/core/lib/iomgr/timer_manager.cc:211
#5  timer_main_loop () at src/core/lib/iomgr/timer_manager.cc:265
#6  timer_thread (completed_thread_ptr=0x24965130) at src/core/lib/iomgr/timer_manager.cc:294
#7  0x00000000005d1a54 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>) at src/core/lib/gprpp/thd_posix.cc:114
#8  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at src/core/lib/gprpp/thd_posix.cc:119
#9  0x0000ffff8391c088 in start_thread (arg=0xffffe7fb51bf) at pthread_create.c:463
#10 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 5 (Thread 0xffff7bfff100 (LWP 43369)):
#0  0x0000ffff8392222c in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x2497fab8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x2497fa50, cond=0x2497fa90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x2497fa90, mutex=mutex@entry=0x2497fa50) at pthread_cond_wait.c:655
#3  0x000000000058e944 in gpr_cv_wait (cv=cv@entry=0x2497fa90, mu=mu@entry=0x2497fa50, abs_deadline=...) at src/core/lib/gpr/sync_posix.cc:217
#4  0x00000000005972e8 in grpc_core::Executor::ThreadMain (arg=0x2497fa50) at src/core/lib/iomgr/executor.cc:245
#5  0x00000000005d1a54 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>) at src/core/lib/gprpp/thd_posix.cc:114
#6  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at src/core/lib/gprpp/thd_posix.cc:119
#7  0x0000ffff8391c088 in start_thread (arg=0xffffe7fb50af) at pthread_create.c:463
#8  0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 4 (Thread 0xffff81607100 (LWP 43373)):
#0  0x0000ffff8392222c in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0xffff81504c88) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x2498f1e8, cond=0xffff81504c60) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0xffff81504c60, mutex=mutex@entry=0x2498f1e8) at pthread_cond_wait.c:655
#3  0x000000000058e944 in gpr_cv_wait (cv=cv@entry=0xffff81504c60, mu=mu@entry=0x2498f1e8, abs_deadline=...) at src/core/lib/gpr/sync_posix.cc:217
#4  0x0000000000625f30 in begin_worker (deadline=9223372036854775807, worker_hdl=<optimized out>, worker=0xffff81504c58, pollset=0xffff68002c48) at src/core/lib/iomgr/ev_epollex_linux.cc:1041
--Type <RET> for more, q to quit, c to continue without paging--
#5  pollset_work (pollset=0xffff68002c48, worker_hdl=<optimized out>, deadline=9223372036854775807) at src/core/lib/iomgr/ev_epollex_linux.cc:1139
#6  0x00000000005ae098 in cq_pluck (cq=0xffff68002b50, tag=0xffff68002248, deadline=..., reserved=<optimized out>) at src/core/lib/surface/completion_queue.cc:1282
#7  0x0000000000432c40 in grpc_impl::CompletionQueue::Pluck(grpc::internal::CompletionQueueTag*) ()
#8  0x000000000044e8d4 in grpc::ClientWriter<saverpc::FileChunk>::Finish() ()
#9  0x00000000004b5a84 in Reporter::SendFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x000000000048f2f0 in ExeProxy::OnFileChunkMessageReceived(MagentTlv&, ReporterIntf&) ()
#11 0x000000000048eccc in ExeProxy::OnMessageRecived(ReporterIntf&) ()
#12 0x000000000048eaa0 in ExeProxy::HandleEpollEvents(epoll_event*, int, ReporterIntf&) ()
#13 0x000000000048e978 in ExeProxy::StartReceiveMessage(ReporterIntf&) ()
#14 0x000000000048e7c4 in ExeProxy::StartCollect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ReporterIntf&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#15 0x00000000004ba8e4 in ExeCollector::Start(ReporterIntf&) ()
#16 0x00000000004c5be0 in MetricTask::Run(Reporter&) ()
#17 0x00000000004c13e8 in MetricTaskManager::ExecuteTask(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Reporter&) ()
#18 0x0000000000461e94 in MetricThread::Start()::{lambda()#1}::operator()() const ()
#19 0x0000000000462220 in void std::__invoke_impl<void, MetricThread::Start()::{lambda()#1}>(std::__invoke_other, MetricThread::Start()::{lambda()#1}&&) ()
#20 0x0000000000462034 in std::__invoke_result<MetricThread::Start()::{lambda()#1}>::type std::__invoke<MetricThread::Start()::{lambda()#1}>(std::__invoke_result&&, (MetricThread::Start()::{lambda()#1}&&)...) ()
#21 0x00000000004624d0 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#22 0x00000000004624a4 in std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> >::operator()() ()
#23 0x0000000000462484 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<MetricThread::Start()::{lambda()#1}> > >::_M_run() ()
#24 0x000000000065fc34 in std::execute_native_thread_routine (__p=0x24992890) at /home/wzh/tools/gcc-7.3.0-update/gcc_source/libstdc++-v3/src/c++11/thread.cc:83
#25 0x0000ffff8391c088 in start_thread (arg=0xffffe7fb551f) at pthread_create.c:463
#26 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 3 (Thread 0xffff7b7fe100 (LWP 43375)):
#0  0x0000ffff83760728 in __GI___nanosleep (requested_time=0xffff7b7fd7e8, requested_time@entry=0xffff7b7fd808, remaining=0xffff7b7fd7e8, remaining@entry=0xffff7b7fd808) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000ffff8376057c in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x00000000004bdb24 in ExeProxyPoolManager::Start()::{lambda()#1}::operator()() const ()
#3  0x00000000004bdf4c in void std::__invoke_impl<void, ExeProxyPoolManager::Start()::{lambda()#1}>(std::__invoke_other, ExeProxyPoolManager::Start()::{lambda()#1}&&) ()
#4  0x00000000004bdd60 in std::__invoke_result<ExeProxyPoolManager::Start()::{lambda()#1}>::type std::__invoke<ExeProxyPoolManager::Start()::{lambda()#1}>(std::__invoke_result&&, (ExeProxyPoolManager::Start()::{lambda()#1}&&)...) ()
#5  0x00000000004be19c in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<ExeProxyPoolManager::Start()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#6  0x00000000004be170 in std::thread::_Invoker<std::tuple<ExeProxyPoolManager::Start()::{lambda()#1}> >::operator()() ()
#7  0x00000000004be150 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<ExeProxyPoolManager::Start()::{lambda()#1}> > >::_M_run() ()
#8  0x000000000065fc34 in std::execute_native_thread_routine (__p=0x24992b50) at /home/wzh/tools/gcc-7.3.0-update/gcc_source/libstdc++-v3/src/c++11/thread.cc:83
#9  0x0000ffff8391c088 in start_thread (arg=0xffffe7fb554f) at pthread_create.c:463
#10 0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 2 (Thread 0xffff8360b100 (LWP 43368)):
#0  0x0000ffff8392222c in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x24977cac) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x24977c40, cond=0x24977c80) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x24977c80, mutex=mutex@entry=0x24977c40) at pthread_cond_wait.c:655
#3  0x000000000058e944 in gpr_cv_wait (cv=cv@entry=0x24977c80, mu=mu@entry=0x24977c40, abs_deadline=...) at src/core/lib/gpr/sync_posix.cc:217
#4  0x00000000005972e8 in grpc_core::Executor::ThreadMain (arg=0x24977c40) at src/core/lib/iomgr/executor.cc:245
#5  0x00000000005d1a54 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<--Type <RET> for more, q to quit, c to continue without paging--
optimized out>) at src/core/lib/gprpp/thd_posix.cc:114
#6  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at src/core/lib/gprpp/thd_posix.cc:119
#7  0x0000ffff8391c088 in start_thread (arg=0xffffe7fb50af) at pthread_create.c:463
#8  0x0000ffff8378e4ec in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 1 (Thread 0xffff836bc5e0 (LWP 43367)):
#0  __GI___pthread_mutex_lock (mutex=0x249935480000) at pthread_mutex_lock.c:65
#1  0x000000000058e72c in gpr_mu_lock (mu=<optimized out>) at src/core/lib/gpr/sync_posix.cc:103
#2  0x00000000005af150 in ExecCtxPluck::CheckReadyToFinish (this=<optimized out>) at src/core/lib/surface/completion_queue.cc:1158
#3  0x00000000005d89e8 in grpc_core::ExecCtx::IsReadyToFinish (this=<optimized out>) at ./src/core/lib/iomgr/exec_ctx.h:168
#4  grpc_combiner_continue_exec_ctx () at src/core/lib/iomgr/combiner.cc:238
#5  0x0000000000596f94 in grpc_core::ExecCtx::Flush (this=0xffffe7fb5000) at src/core/lib/iomgr/exec_ctx.cc:151
#6  0x0000000000625fd0 in pollset_work (pollset=0x24993548, worker_hdl=<optimized out>, deadline=<optimized out>) at src/core/lib/iomgr/ev_epollex_linux.cc:1151
#7  0x00000000005ae098 in cq_pluck (cq=0x24993450, tag=0xffffe7fb50d8, deadline=..., reserved=<optimized out>) at src/core/lib/surface/completion_queue.cc:1282
#8  0x0000000000432c40 in grpc_impl::CompletionQueue::Pluck(grpc::internal::CompletionQueueTag*) ()
#9  0x000000000044feb8 in grpc::ClientReader<saverpc::Task>::Read(saverpc::Task*) ()
#10 0x00000000004b2ee8 in GrpcCmdHandler::GetTask() ()
#11 0x00000000004b27bc in GrpcCmdHandler::Start() ()
#12 0x00000000004c49ec in Application::Start() ()
#13 0x00000000004c58b0 in main ()
```
</details>
By the way, when I compile the codes generated by protoc with `CXXFLAGS = -O2` the problem disappeared.

**Comment by yashykt** [comment]
This is likely an issue with lifetimes of the underlying objects. We would need to have a look at your code to help debug further.

**Comment by jtattermusch** [comment]
No response from the reporter for >year. closing.
