### ISSUE TITLE
Node MacOS Flake: "Name Resolver DNS Names Should resolve a DNS name to an IPv6 address"

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#22282]
```
  1) Name Resolver DNS Names Should resolve a DNS name to an IPv6 address:
     Error: Failed with status Name resolution failed for target loopback6.unittest.grpc.io
      at Object.onError (packages/grpc-js/test/test-resolver.ts:236:16)
      at packages/grpc-js/src/resolver-dns.ts:69:4

  2) Name Resolver DNS Names Should resolve a DNS name to IPv4 and IPv6 addresses:
     Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

https://source.cloud.google.com/results/invocations/126fa9e9-9a2b-4381-94a4-5e2ae2f53487/log

**Comment by murgatroid99** [comment]
This is also grpc/grpc-node#1289, and it should be fixed by grpc/grpc-node#1297.
