### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Name resolution failure)

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc#22422]
I start to use Grpc framework to achieve some communication between Client/Server but i got this Exception :

Grpc.Core.RpcException: 'Status(StatusCode=Unavailable, Detail="Name resolution failure)'

**As i understand the client is not able to connect to the server for some reason.**

**Can anybody give me any Idea what is going wrong? why i am not able to connect to Server?**

### What version of gRPC and what language are you using?
(1.19.0) 

### What operating system (Linux, Windows,...) and version?
windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
C# .Net Framework 4.7 VS 2017

### What did you do?
Description : I am using .Net Framework 4.7 in my Environment, which it contains client (as Library), Server (as exe) and a caller(as Library) which is used to call the client.

Client Packages : Grpc (1.19.0) / Grpc.Core (1.19.0) / Grpc.Tools (1.19.0) / Goolge.Protobuf (3.7.0) Server Packages : Grpc (1.19.0) / Grpc.Core (1.19.0) / Grpc.Tools (1.19.0) / Goolge.Protobuf (3.7.0) / Goolge.Protobuf.Tools (3.7.0)

The Stack :

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Grpc.Core.Internal.AsyncCall2.UnaryCall(TRequest msg) at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails2 call, TRequest req)
at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method2 method, String host, CallOptions options, TRequest request) at Grpc.Core.Interceptors.InterceptingCallInvoker.b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext2 ctx)
at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext2 context, BlockingUnaryCallContinuation2 continuation)
at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method2 method, String host, CallOptions options, TRequest request) at GrpcStreaming.GrpcStreamingClient.Init(GrpcStreamingContext request, CallOptions options) at GrpcStreaming.GrpcStreamingClient.Init(GrpcStreamingContext request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) at NameSpaceExample.Init(String str1, String str2)

### What did you expect to see?
i did expect to get the connection client/Server

### What did you see instead?
Exception mentioned above.

### Anything else we should know about your project / environment?
I have build a small solution which contains only the client , Server and the a project which calls the client, for this solution i am not be able to reproduce the issue, everything works fine. so  when i tried to build the Client/Server Grpc in a big solution i am able to reproduce the issue.    

I want to understand what are meaning of both Status messages : 

Status(StatusCode=Unavailable --> Is it mean that the Server is unavailable. 

Detail="Name resolution failure" --> What means this message ??? 
 
Thanks for any help.

**Comment by MhdAna** [comment]
The issue is resolved, host name was wrong.
