### ISSUE TITLE
1.28.0 _simple_stubs raising a syntax error

### ISSUE THREAD

**Issue by asingh16** [grpc/grpc#22546]
### What version of gRPC and what language are you using?

1.28.0

### What operating system (Linux, Windows,...) and version?

linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.5.8

### What did you do?

I originally imported exceptions from google.cloud. This eventually triggers the following import statement:

```
from grpc._simple_stubs import unary_unary, unary_stream, stream_unary, stream_stream
```
### What did you expect to see?

I expected the import to pass. 

### What did you see instead?

```

from grpc._simple_stubs import unary_unary, unary_stream, stream_unary, stream_stream
--
File "/workdir/examples/.tox/py35/lib/python3.5/site-packages/grpc/_simple_stubs.py", line 
        _LOGGER.debug(f"Creating insecure channel with options '{options}' " +
SyntaxError: invalid syntax
```

### Anything else we should know about your project / environment?

I tried to replicate the same on OSX and got the following:

```
>>> from grpc._simple_stubs import unary_unary, unary_stream, stream_unary, stream_stream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abhinavasingh/.pyenv/versions/grpcio-3.5.8/lib/python2.7/site-packages/grpc/_simple_stubs.py", line 53
    def _create_channel(target: str, options: Sequence[Tuple[str, str]],
                              ^
SyntaxError: invalid syntax
```

**Comment by osma** [comment]
Encountered the same issue. The problem seems to be the f-string syntax, which requires Python 3.5.

**Comment by gnossen** [comment]
@asingh16 @osma Thank you for the reports! There will be a patch out for this very soon.

**Comment by jvanenckevort** [comment]
This is kinda big. Google cloud build only has python 2.7 and 3.5 in it's pre-cached cloud builders. A lot of google-cloud packages rely on grpcio in the background.

**Comment by gnossen** [comment]
The 1.28.0 release has been deleted. We will follow up with a patched `1.28.1` release shortly.

**Comment by jvanenckevort** [comment]
Thanks for the fast response, everything is working now with `1.28.0` being deleted.

**Comment by cocoa-maemae** [comment]
The python's grammar of f string supports after python3.6, so it seems like it didn't work in python3.5 environment.
I just downgraded grpcio to 1.27 and it worked fine.

**Comment by NicolasPA** [comment]
I was impacted using Google PubSub Python library relying on `grpcio` with Python 3.5 at least between 2:30 and 7:30 UTC.

Since then everything is working as before, thank you!

Here's the error to help people who will search on it:
```bash
2020-04-02 06:58:43 2020-04-02 06:58:43,332 main                  ERROR    invalid syntax (_simple_stubs.py, line 61)
...
2020-04-02 06:58:43     self.subscriber = pubsub_v1.SubscriberClient()
2020-04-02 06:58:43   File "/root/.virtualenvs/date-project-env1339/lib/python3.5/site-packages/google/cloud/pubsub_v1/subscriber/client.py", line 95, in __init__
2020-04-02 06:58:43     "grpc.keepalive_time_ms": 30000,
2020-04-02 06:58:43   File "/root/.virtualenvs/date-project-env1339/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 206, in create_channel
2020-04-02 06:58:43     return grpc.secure_channel(target, composite_credentials, **kwargs)
2020-04-02 06:58:43   File "/root/.virtualenvs/date-project-env1339/lib/python3.5/site-packages/grpc/__init__.py", line 1881, in secure_channel
2020-04-02 06:58:43     from grpc import _channel  # pylint: disable=cyclic-import
2020-04-02 06:58:43   File "/root/.virtualenvs/date-project-env1339/lib/python3.5/site-packages/grpc/_channel.py", line 25, in <module>
2020-04-02 06:58:43     import grpc.experimental
2020-04-02 06:58:43   File "/root/.virtualenvs/date-project-env1339/lib/python3.5/site-packages/grpc/experimental/__init__.py", line 89, in <module>
2020-04-02 06:58:43     from grpc._simple_stubs import unary_unary, unary_stream, stream_unary, stream_stream
2020-04-02 06:58:43   File "/root/.virtualenvs/date-project-env1339/lib/python3.5/site-packages/grpc/_simple_stubs.py", line 61
2020-04-02 06:58:43     _LOGGER.debug(f"Creating insecure channel with options '{options}' " +
2020-04-02 06:58:43                                                                        ^
2020-04-02 06:58:43 SyntaxError: invalid syntax
```

**Comment by asingh16** [comment]
Thanks for the quick turnaround, everything is working now!

**Comment by gnossen** [comment]
[Announcement of the deletion.](https://groups.google.com/g/grpc-io/c/XxVY9yF26F0)
