### ISSUE TITLE
Having both protobuf 2.x and 3.x installed confuses the linker.

### ISSUE THREAD

**Issue by siddharthab** [grpc/grpc#2262]
This is with an Ubuntu distro (14.04 LTS).

When trying to run make, I get the following error:

```
[INSTALL] Installing libgrpc++.so.0.10.0.0
[INSTALL] Installing libgrpc++_unsecure.so.0.10.0.0
[HOSTLD]  Linking bins/opt/grpc_csharp_plugin
./libs/opt/libgrpc_plugin_support.a(csharp_generator.o): In function `GenerateServerInterface':
/usr/local/google/home/sidb/workspaces/genomics/grpc/src/compiler/csharp_generator.cc:305: undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::string const&, char const*, std::string const&, char const*, std::string const&, char const*, std::string const&)'
collect2: error: ld returned 1 exit status
make: *** [bins/opt/grpc_csharp_plugin] Error 1
```

If I remove the C# and Obj-C plugins from PROTOC_PLUGINS in the Makefile, the installation completes, but then when trying to compile a proto file, I get the following:

```
protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/longrunning/*.proto
--grpc_out: protoc-gen-grpc: Plugin killed by signal 11.
make: *** [google/longrunning/operations.pb.cc] Error 1
```

**Comment by siddharthab** [comment]
Removing the system default protobuf packages solved this issue. The installation for protobuf 3.0 was with the standard configure options. Perhaps the precedence for /usr/local/lib was not right.

Happy to provide more information if someone wants to pursue this. Otherwise OK to close this issue.

**Comment by nicolasnoble** [comment]
Which version of protobuf was installed on the system exactly ?

**Comment by siddharthab** [comment]
Package: libprotoc8
Versions:  2.5.0-9ubuntu1 ...

**Comment by nicolasnoble** [comment]
So, another way to solve that would've been to upgrade protobuf 3.0 in your /usr/local. I'm guessing you had installed a version prior to 3.0.0-alpha3, which is the one required by the current version of gRPC.

**Comment by siddharthab** [comment]
I installed from HEAD of the github repo - https://github.com/google/protobuf - as it was yesterday. And later also performed the same install steps from the third_party subdir of the grpc repo in case it was linked to a different version.

**Comment by nicolasnoble** [comment]
Hmmm, that's as if it was linking against the 2.x version for some reason. We'll investigate.

**Comment by xfxyjwf** [comment]
If an user has two versions of protobuf library installed, it's likely that the "-lprotobuf" linker flags will be pointing to the wrong lib. Seems to me the right solution is to give the user an option to specify the exact location and name of the protobuf library to link with.

**Comment by OLGKAD** [comment]
Hey @siddharthab, thanks for sharing this. I'm experiencing a very similar problem right now. How do you make sure that the system default protobuf packages have been removed?  For me "protoc --version" produces "libprotoc [new version]", but I'm not sure if it's a good enough indicator that the old version has been deleted.

**Comment by siddharthab** [comment]
I believe something like ldconfig can help you figure out which directories have protobuf library installed and in which order they are considered.

**Comment by grapemix** [comment]
In ubuntu 16.04, I have problem from multiple libprotobuf version too, but uninstalling old libprotobuf may not be a good idea.
Here is what I tried because I heard about removing old libprotobuf is "the solution":
`sudo apt-get remove libprotobuf9v5 libprotobuf-lite9v5`

I got:
```
The following packages have unmet dependencies:
 ibus : Depends: gir1.2-gtk-3.0 (>= 3.8.5) but it is not going to be installed
        Depends: adwaita-icon-theme but it is not going to be installed
        Recommends: ibus-gtk3 but it is not going to be installed or
                    ibus-qt4 but it is not going to be installed or
                    libqt5gui5 but it is not going to be installed
 libcheese-gtk25 : Depends: libcogl20 (>= 1.17.4) but it is not going to be installed
                   Depends: gstreamer1.0-clutter-3.0 but it is not going to be installed
 libcheese8 : Depends: libclutter-gst-3.0-0 (>= 3.0.4) but it is not going to be installed
 libclutter-1.0-0 : Depends: libcogl-pango20 (>= 1.17.4) but it is not going to be installed
                    Depends: libcogl-path20 (>= 1.17.4) but it is not going to be installed
                    Depends: libcogl20 (>= 1.21.2) but it is not going to be installed
 libclutter-gtk-1.0-0 : Depends: libcogl20 (>= 1.17.4) but it is not going to be installed
 libgtk-3-0 : Depends: libgtk-3-common (>= 3.18.9-1ubuntu3.3) but it is not going to be installed
              Depends: libwayland-egl1-mesa (>= 10.0.2) but it is not going to be installed or
                       libwayland-egl1
 libgtk-3-bin : Depends: libgtk-3-common (>= 3.18.9-1ubuntu3.3) but it is not going to be installed
 libmirclient9 : Depends: libmirprotobuf3 (>= 0.26.3+16.04.20170605) but it is not going to be installed
                 Depends: libprotobuf-lite9v5 but it is not going to be installed
 libonline-accounts-daemon1 : Depends: libonline-accounts-client1 but it is not going to be installed
 liboxideqt-qmlplugin : Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                 libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 liboxideqtcore0 : Depends: libqt5gui5 (>= 5.4.0) but it is not going to be installed or
                            libqt5gui5-gles (>= 5.4.0) but it is not going to be installed
 liboxideqtquick0 : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                             libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                    Depends: libqt5quick5 (>= 5.2.0) but it is not going to be installed or
                             libqt5quick5-gles (>= 5.2.0) but it is not going to be installed
 libqmenumodel0 : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                           libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
 libqt5multimedia5 : Depends: libqt5gui5 (>= 5.2.0) but it is not going to be installed or
                              libqt5gui5-gles (>= 5.2.0) but it is not going to be installed
 libqt5multimedia5-plugins : Depends: libqgsttools-p1 (>= 5.5.1) but it is not going to be installed
                             Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                                      libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
 libqt5multimediaquick-p5 : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                                     libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                            Depends: libqt5quick5 (>= 5.4.0) but it is not going to be installed or
                                     libqt5quick5-gles (>= 5.4.0) but it is not going to be installed
 libqt5widgets5 : Depends: libqt5gui5 (>= 5.5.0) but it is not going to be installed or
                           libqt5gui5-gles (>= 5.5.0) but it is not going to be installed
 libubuntugestures5 : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                               libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                      Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                               libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 libubuntuoneauth-2.0-0 : Depends: account-plugin-tools but it is not going to be installed
 libubuntutoolkit5 : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                              libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
 libwebkit2gtk-4.0-37 : Depends: libegl1-mesa (>= 7.8.1) but it is not going to be installed or
                                 libegl1-x11
                        Depends: libwayland-egl1-mesa (>= 10.0.2) but it is not going to be installed or
                                 libwayland-egl1
                        Recommends: libwebkit2gtk-4.0-37-gtk2 but it is not going to be installed
 qml-module-io-thp-pyotherside : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                                          libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                                 Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                          libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 qml-module-qtmultimedia : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                                    libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                           Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                    libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 qml-module-qtquick-layouts : Depends: libqt5gui5 (>= 5.5.0) but it is not going to be installed or
                                       libqt5gui5-gles (>= 5.5.0) but it is not going to be installed
                              Depends: libqt5quick5 (>= 5.2.0) but it is not going to be installed or
                                       libqt5quick5-gles (>= 5.2.0) but it is not going to be installed
 qml-module-qtquick-window2 : Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                       libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 qml-module-qtquick2 : Depends: libqt5quick5 (>= 5.4.1) but it is not going to be installed or
                                libqt5quick5-gles (>= 5.4.1) but it is not going to be installed
 qml-module-ubuntu-layouts : Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                      libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 qml-module-ubuntu-performancemetrics : Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                                                 libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                                        Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                                 libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 qtdeclarative5-ubuntu-content1 : Depends: libcontent-hub0 but it is not going to be installed
                                  Depends: libqt5gui5 (>= 5.0.2) but it is not going to be installed or
                                           libqt5gui5-gles (>= 5.0.2) but it is not going to be installed
                                  Depends: libqt5quick5 (>= 5.0.2) but it is not going to be installed or
                                           libqt5quick5-gles (>= 5.0.2) but it is not going to be installed
 system-config-printer-gnome : Depends: adwaita-icon-theme but it is not going to be installed
                               Depends: gir1.2-gtk-3.0 but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
I got hesitate because removing old libprotobuf might solve my problem but it will create more problems. Still, I continued with:

`sudo dpkg --remove --force-depends libprotobuf9v5 libprotobuf-lite9v5`

Now, I tried to run my gtk3 + grpc app, but I got an error. And I can reproduce the error by importing gtk3 in python shell like this:

```
>>> import gi
>>> gi.require_version('Gtk', '3.0')
>>> from gi.repository import Gtk as gtk
```

I got:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/crystal/venv/panel/local/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/crystal/venv/panel/local/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/crystal/venv/panel/local/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/crystal/venv/panel/local/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 80, in <module>
    Color = override(Color)
  File "/opt/crystal/venv/panel/local/lib/python2.7/site-packages/gi/overrides/__init__.py", line 206, in override
    assert g_type != TYPE_NONE
AssertionError
```
I ended up reinstalling libprotobuf9v5 libprotobuf-lite9v5 and check around in github. Anyone have any ideas?

**Comment by nicolasnoble** [comment]
Due to semantic versioning with protobuf, it's impossible to really have more than one version of protobuf installed.
