### ISSUE TITLE
`init_grpc_aio()` causes sync calls to hang

### ISSUE THREAD

**Issue by DerekTBrown** [grpc/grpc#22733]
## Context
- I am in the process of developing a Python server handler using the experimental [gRPC aio library](https://grpc.github.io/grpc/python/grpc_asyncio.html). 
- My service relies on etcd, and so I make use of the [`etcd3`](https://pypi.org/project/etcd3/) Python library, which internally uses a synchronous `gRPC` client to communicate with etcd.
- I observed that after `init_grpc_aio` is invoked, synchronous `gRPC` client calls hang indefinitely.

### Repro
- I [modified the provided `helloworld` example](https://repl.it/repls/CyberAwesomeOutliner) to call `stub.SayHello` twice, once before and once after `init_grpc_aio` is invoked:

```python
print("Calling before init_grpc_aio()")
stub = helloworld_pb2_grpc.GreeterStub(channel)
response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
print("Calling before init_grpc_aio() succeeds!")

init_grpc_aio()

print("Calling after init_grpc_aio()")
stub = helloworld_pb2_grpc.GreeterStub(channel)
response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
print("We never reach here.")
```

Sending SIGINT shows exactly where the process is stuck:

```bash
$ python3 greeter_client.py 
Calling before init_grpc_aio()
Calling before init_grpc_aio() succeeds!
Calling after init_grpc_aio()
^CTraceback (most recent call last):
  File "greeter_client.py", line 50, in <module>
    run()
  File "greeter_client.py", line 41, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/derekbro/.local/lib/python3.8/site-packages/grpc/_channel.py", line 824, in __call__
    state, call, = self._blocking(request, timeout, metadata, credentials,
  File "/home/derekbro/.local/lib/python3.8/site-packages/grpc/_channel.py", line 813, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 336, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 169, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 163, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 63, in grpc._cython.cygrpc._latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next
KeyboardInterrupt
```

**Comment by lidizheng** [comment]
Can you try your application again with our daily build?
```
pip install --pre --upgrade --force-reinstall --extra-index-url \
    https://packages.grpc.io/archive/2020/04/c07ddb45047f38c871fbb2519b4832144d09afe7-aee9b5ca-1fda-44da-b5c3-c86dfe95ca88/python \
    grpcio
```

This is a known issue that enable AsyncIO support makes synchronous gRPC call hang. It should be solved recently.

**Comment by DerekTBrown** [comment]
That did the trick.  Thanks @lidizheng .
