### ISSUE TITLE
FLAKE: Failure to download Cython-0.29.17-cp35-cp35m-manylinux1_x86_64.whl during python test

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#22899]
https://source.cloud.google.com/results/invocations/e721cfd0-31a5-457c-aa8c-a7834fd3bf82/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_python_linux_opt_gevent/tests

From the log:

```
+ /usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/llvm-symbolizer /var/local/git/grpc/py35_gevent/bin/python3.5 -m pip install --upgrade setuptools
Requirement already up-to-date: setuptools in ./py35_gevent/lib/python3.5/site-packages (46.1.3)
WARNING: You are using pip version 19.3.1; however, version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ pip_install --upgrade cython
+ /usr/bin/env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/llvm-symbolizer /var/local/git/grpc/py35_gevent/bin/python3.5 -m pip install --upgrade cython
Collecting cython
  Downloading https://files.pythonhosted.org/packages/81/7d/ed2dd579dffd2826d03225b55576d1bf304108c764152e41f7116f2459d8/Cython-0.29.17-cp35-cp35m-manylinux1_x86_64.whl (2.1MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/local/git/grpc/py35_gevent/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
WARNING: You are using pip version 19.3.1; however, version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

2020-05-05 09:29:01,473 FAILED: /var/local/git/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=2, pid=20309, time=19.0sec]
2020-05-05 09:29:01,474 FAILED: Some tests failed
  adding: reports/ (stored 0%)
+ DOCKER_EXIT_CODE=1
++ mktemp
+ TEMP_REPORTS_ZIP=/tmpfs/tmp/tmp.EGIWekxOya
+ docker cp run_tests_14bb754b-94ee-40f0-9fd2-7375b6c978ad:/var/local/git/grpc/reports.zip /tmpfs/tmp/tmp.EGIWekxOya
+ unzip -o /tmpfs/tmp/tmp.EGIWekxOya -d /tmpfs/src/github/grpc
Archive:  /tmpfs/tmp/tmp.EGIWekxOya
   creating: /tmpfs/src/github/grpc/reports/
+ rm -f /tmpfs/tmp/tmp.EGIWekxOya
+ docker rm -f run_tests_14bb754b-94ee-40f0-9fd2-7375b6c978ad
run_tests_14bb754b-94ee-40f0-9fd2-7375b6c978ad
+ exit 1
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1672, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 1
```

**Comment by lidizheng** [comment]
An earlier issue reporting same error: https://github.com/grpc/grpc/issues/22683
Duplicated, closing this one.
