### ISSUE TITLE
gRPC C++ client blocked when I set a deadline time

### ISSUE THREAD

**Issue by forsunwell** [grpc/grpc#22999]
### What version of gRPC and what language are you using?
v1.11.0

### What operating system (Linux, Windows, …) and version?
CentOS Linux release 7.2

### What runtime/compiler are you using (e.g. python version or version of gcc)
gcc (GCC) 4.8.5

### What did you do?
Set a deadline and process sync call. My code like this:
```
    CtlHealthCheckRequest request;
    unsigned int client_connection_timeout = HEALTH_CHECK_TIMER_OUT;
    CtlHealthCheckResponse response;
    ClientContext context;
    std::chrono::system_clock::time_point deadline = std::chrono::system_clock::now() + std::chrono::seconds(client_connection_timeout);
    context.set_deadline(deadline);

    request.set_service(service_name);

    Status s = stub_->check(&context, request, &response);
```

### What did you expect to see?
When I config iptables in Linux to drop all the grpc packets or the server is broken, the call should return after the deadline exceeded.

### What did you see instead?
Call blocked a long time, in epoll_wait function, argument timeout set to -1. 
```
#0  0x00007ffff5e8f873 in epoll_wait () from /lib64/libc.so.6
#1  0x00007ffff69164c8 in pollable_epoll (deadline=<optimized out>, p=0x7fffe4001890)
    at src/core/lib/iomgr/ev_epollex_linux.cc:823
#2  pollset_work (pollset=0x808570, worker_hdl=<optimized out>, deadline=<optimized out>)
    at src/core/lib/iomgr/ev_epollex_linux.cc:1010
#3  0x00007ffff693a651 in cq_pluck (cq=0x808470, tag=0x7fffffffd990, deadline=..., reserved=<optimized out>)
    at src/core/lib/surface/completion_queue.cc:1172
#4  0x00007ffff693a9db in grpc_completion_queue_pluck (cq=<optimized out>, tag=<optimized out>, deadline=..., 
    reserved=<optimized out>) at src/core/lib/surface/completion_queue.cc:1199
#5  0x00007ffff750a9d8 in grpc::CoreCodegen::grpc_completion_queue_pluck (this=<optimized out>, 
    cq=<optimized out>, tag=<optimized out>, deadline=..., reserved=<optimized out>)
    at src/cpp/common/core_codegen.cc:70
#6  0x0000000000477662 in grpc::CompletionQueue::Pluck (this=0x7fffffffd950, tag=0x7fffffffd990)
    at /usr/local/include/grpcpp/impl/codegen/completion_queue.h:297
#7  0x00000000004f83c2 in grpc::internal::BlockingUnaryCallImpl<fcrctlservice::CtlHealthCheckRequest, fcrctlservice::CtlHealthCheckResponse>::BlockingUnaryCallImpl (this=0x7fffffffdb00, channel=0x7fffe00103c0, method=..., 
    context=0x7fffffffdbd0, request=..., result=0x7fffffffdd70)
    at /usr/local/include/grpcpp/impl/codegen/client_unary_call.h:72
#8  0x00000000004f5bd9 in grpc::internal::BlockingUnaryCall<fcrctlservice::CtlHealthCheckRequest, fcrctlservice::CtlHealthCheckResponse> (channel=0x7fffe00103c0, method=..., context=0x7fffffffdbd0, request=..., 
    result=0x7fffffffdd70) at /usr/local/include/grpcpp/impl/codegen/client_unary_call.h:43
#9  0x00000000004f3eca in fcrctlservice::FcrCtlService::Stub::check (this=0x7fffe0006450, context=0x7fffffffdbd0, 
    request=..., response=0x7fffffffdd70) at fcr_config_client.grpc.pb.cc:73
```

### Anything else we should know about your project/environment?
- It may be similar to https://github.com/grpc/grpc/issues/15702
- Channel set argu like this:
```
    grpc::ChannelArguments argu;
    argu.SetInt(GRPC_ARG_INITIAL_RECONNECT_BACKOFF_MS, 1000);
    argu.SetInt(GRPC_ARG_MIN_RECONNECT_BACKOFF_MS, 1000);
    argu.SetInt(GRPC_ARG_MAX_RECONNECT_BACKOFF_MS, 10000);
    argu.SetInt(GRPC_ARG_SERVER_HANDSHAKE_TIMEOUT_MS, 60000);
    argu.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 1000);
    argu.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 1000);
```
- I test GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS, it doesn't work.

**Comment by markdroth** [comment]
1.11 is a very old version of gRPC.  Can you try a more recent version and see if the problem is still present?

**Comment by markdroth** [comment]
I'm fairly sure this is obsolete.

**Comment by sandan** [comment]
@markdroth Do you have a recommendation on which gRPC version to upgrade to?

**Comment by markdroth** [comment]
I would suggest trying the most recent version.  That way, if there's still a problem, we'll be better able to reproduce and debug it.
