### ISSUE TITLE
Python2.7 Python tests failing on 1.30.x 

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#23263]
One example failure:

```
++ dirname /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/tools/run_tests/helper_scripts/run_python.sh
+ cd /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/tools/run_tests/helper_scripts/../../..
++ realpath py27_gevent/bin/python
+ PYTHON=/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/bin/python
++ pwd
+ ROOT=/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent
+ /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/bin/python /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/setup.py test_gevent
running test_gevent
Traceback (most recent call last):
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/setup.py", line 109, in <module>
    test_runner=TEST_RUNNER,
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/commands.py", line 251, in run
    loader.loadTestsFromNames(['tests'])
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/_loader.py", line 60, in loadTestsFromNames
    self.walk_packages(package_paths)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/_loader.py", line 74, in walk_packages
    module = importer.find_module(module_name).load_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/interop/client.py", line 20, in <module>
    from google.auth import jwt as google_auth_jwt
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/google/auth/jwt.py", line 53, in <module>
    from google.auth import _service_account_info
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/google/auth/crypt.py", line 49, in <module>
    import rsa
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/rsa/__init__.py", line 24, in <module>
    from rsa.key import newkeys, PrivateKey, PublicKey
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/rsa/key.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/lib/python2.7/site-packages/rsa/key.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

See other full logs in https://source.cloud.google.com/results/invocations/75498851-9205-4c7e-b512-f781b0498910/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_gevent%2Fpy27_gevent.test._sanity._sanity_test.SanityTest/tests and https://source.cloud.google.com/results/invocations/6d0236a3-e0c8-4ed9-91d5-e10ebcef2c90/targets/github%2Fgrpc%2Frun_tests%2Fpython_macos_opt_gevent%2Fpy27_gevent.test.unit._auth_test.GoogleCallCredentialsTest/tests

**Comment by lidizheng** [comment]
The `rsa` module should be fixed in upstream (PyPI). This error shouldn't occur unless there is another bad release. In either case, it might be better to backport the fix to stabilize the test: https://github.com/grpc/grpc/pull/23264
