### ISSUE TITLE
gRPC converting 400 BadRequest error to 503 Unavailable error

### ISSUE THREAD

**Issue by larkee** [grpc/grpc#23323]
### What version of gRPC and what language are you using?
Python v1.27.2 

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python3.8 

### What did you do?
Try to use the Cloud Spanner client library using a credentials file with an invalid email or id.

### What did you expect to see?
An error to be raised alerting me to the invalid email or id.

### What did you see instead?
The client appears to hang. Using logging, it can be determined it is entering a retry loop.
```
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 400 None
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f8fa88b08b0>" raised exception!
Traceback (most recent call last):
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    self._metadata_plugin(
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 84, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 70, in _get_authorization_headers
    self._credentials.before_request(
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/service_account.py", line 334, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid grant: account not found', '{"error":"invalid_grant","error_description":"Invalid grant: account not found"}')
DEBUG:google.api_core.retry:Retrying due to 503 Getting metadata from plugin failed with error: ('invalid_grant: Invalid grant: account not found', '{"error":"invalid_grant","error_description":"Invalid grant: account not found"}'), sleeping 1.7s ...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 400 None
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f8fa88b08b0>" raised exception!
Traceback (most recent call last):
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    self._metadata_plugin(
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 84, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 70, in _get_authorization_headers
    self._credentials.before_request(
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/service_account.py", line 334, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid grant: account not found', '{"error":"invalid_grant","error_description":"Invalid grant: account not found"}')
DEBUG:google.api_core.retry:Retrying due to 503 Getting metadata from plugin failed with error: ('invalid_grant: Invalid grant: account not found', '{"error":"invalid_grant","error_description":"Invalid grant: account not found"}'), sleeping 1.8s ...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 400 None
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f8fa88b08b0>" raised exception!
Traceback (most recent call last):
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    self._metadata_plugin(
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 84, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 70, in _get_authorization_headers
    self._credentials.before_request(
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/service_account.py", line 334, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/larkee/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid grant: account not found', '{"error":"invalid_grant","error_description":"Invalid grant: account not found"}')
DEBUG:google.api_core.retry:Retrying due to 503 Getting metadata from plugin failed with error: ('invalid_grant: Invalid grant: account not found', '{"error":"invalid_grant","error_description":"Invalid grant: account not found"}'), sleeping 1.5s ...
```
From these logs, the original error code was `400 Bad Request` but the error being returned to the client is `503 Unavailable` which Cloud Spanner retries on.

See googleapis/python-spanner#4 for further details

**Comment by yashykt** [comment]
I am not sure I understand the issue here. 

gRPC converts the http status code to a grpc status according to https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md and you would probably find the underlying details in the error string or the error details. 

So when you say gRPC "converts" 400 to 503, I'm not sure what you are referring to. Also, if gRPC receives 400 as the http status code, it would be converted to INTERNAL and not UNAVAILABLE. Enabling gRPC logs would probably be useful here.

https://github.com/grpc/grpc/blob/master/doc/environment_variables.md
Trace flags like http,http1,channel,api would be useful here in addition to providing more information on the error string and details.

**Comment by gcbirzan** [comment]
As the original reported said, the error surfaces as 503, not 500. I've enabled gRPC tracing (as well as the python logs, to see the 400 going to 503). You can find them here: https://gist.github.com/gcbirzan/df0570bae865e7979e6584225c8dcf11. Based on some poking around, I added to the GRPC_TRACE also `plugin_credentials,call_error,executor`. 

In particular, this seems to be the source of the unavailable: 

```D1203 12:35:17.567223131 2150740 call.cc:740]                {"created":"@1606991717.567166613","description":"Getting metadata from plugin failed with error: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":90,"grpc_status":14}```

gRPC status 14 is unavailable, it should be 13 for internal. I tried to step through the gRPC code, the 400 comes from https://github.com/grpc/grpc/blob/5ab59b2bf7df73bd59c46c5d5d10dbc31d4d7ca9/src/python/grpcio/grpc/_plugin_wrapping.py#L87-L88

But, since this is in a thread, I cannot trivially figure out where it surfaces on the other side. 

I have 3 easy steps to reproduce (this probably happens with all python clients, but I hit it with firestore):

  1. Use  `gcloud auth application-default login` to login.
  2. Go to `https://myaccount.google.com/permissions` and revoke permissions for `Google Auth Library`. 
  3. Attempt to use the client. Anything that requires authentication will hit this.

Because the auth error is not transient, it shouldn't be retried, but because it gets as 503 to the api core, it is, leading to 2 minutes of furious retries.
