### ISSUE TITLE
Master not compiling for python

### ISSUE THREAD

**Issue by staticdev** [grpc/grpc#23338]
### What version of gRPC and what language are you using?

master / python

### What operating system (Linux, Windows,...) and version?

Ubuntu 20.04 64 bit

### What runtime / compiler are you using (e.g. python version or version of gcc)

pyenv 3.8.2 3.7.6 3.6.10 3.5.9 2.7.17

### What did you do?

1. Install all above versions of python
2. pyenv local 3.8.2 3.7.6 3.6.10 3.5.9 2.7.17
3. python tools/run_tests/run_tests.py -l python

### What did you expect to see?

Compile and tests as in [contributing guide](https://github.com/grpc/grpc/blob/master/CONTRIBUTING.md).

### What did you see instead?

Big log of errors:

[log.txt](https://github.com/grpc/grpc/files/4843306/log.txt)

### Anything else we should know about your project / environment?
N/A

**Comment by nicolasnoble** [comment]
How did you get your source ? If through github, you need to clone recursively and get submodules.

**Comment by staticdev** [comment]
@nicolasnoble I created a fork and cloned it. What is it missing? I did not understand how I get this submodules...

**Comment by gnossen** [comment]
@staticdev [`git submodule update --init --recursive` should do the trick.](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by staticdev** [comment]
I think it is working, but it is taking veeeeeeery long. Is that normal?

**Comment by staticdev** [comment]
@gnossen also I just realized --recursive is missing in [this doc](https://github.com/grpc/grpc/blob/master/BUILDING.md#clone-the-repository-including-submodules).

I got other errors, checking if it is missing requirements.

**Comment by gnossen** [comment]
There's a lot of code being pulled down. if you're on a slow network connection, it might be reasonable. Or do you mean the compile is taking a long time? If so, you can set `GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS` to use more cores. Though I recently turned the number of jobs up to the number of cores available on the system by default, so you might just fetch origin instead.

I don't think the `--recursive` option is strictly necessary, since none of our dependencies currently has a submodule dependency of its own, but it doesn't hurt. As the doc I linked above noted, `--init --recursive` is "fool-proof". It wouldn't hurt to add it to our documentation.

**Comment by staticdev** [comment]
@gnossen I was talking about the compiling of python generators. Still even with all documented requirements I am getting the errors:
```

b'++ dirname /home/static/workspace/grpc/tools/run_tests/helper_scripts/build_python.sh\n+ cd /home/static/workspace/grpc/tools/run_tests/helper_scripts/../../..\n++ uname -s\n+ PLATFORM=Linux\n+ PYTHON=python3.7\n+ VENV=py37_native\n+ VENV_RELATIVE_PYTHON=bin/python\n+ TOOLCHAIN=unix\n++ is_msys\n++ \'[\' Linux \'!=\' Linux \']\'\n++ exit 1\n+ \'[\' \'\' \']\'\n++ pwd\n+ ROOT=/home/static/workspace/grpc\n+ export \'CFLAGS=-I/home/static/workspace/grpc/include -std=gnu99 -fno-wrapv \'\n+ CFLAGS=\'-I/home/static/workspace/grpc/include -std=gnu99 -fno-wrapv \'\n+ export GRPC_PYTHON_BUILD_WITH_CYTHON=1\n+ GRPC_PYTHON_BUILD_WITH_CYTHON=1\n+ export LANG=en_US.UTF-8\n+ LANG=en_US.UTF-8\n++ nproc\n+ DEFAULT_PARALLEL_JOBS=4\n+ export GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=4\n+ GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=4\n++ is_linux\n++ \'[\' \'\' \'!=\' Linux \']\'\n++ echo true\n+ \'[\' true \']\'\n++ command -v ccache\n+ \'[\' -x \'\' \']\'\n++ inside_venv\n++ [[ -n \'\' ]]\n+ [[ -n \'\' ]]\n+ python3.7 -m pip install --user virtualenv==16.7.9\nTraceback (most recent call last):\n  File "/home/static/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/home/static/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/home/static/.local/lib/python3.7/site-packages/pip/__main__.py", line 19, in <module>\n    sys.exit(_main())\n  File "/home/static/.local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main\n    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))\n  File "/home/static/.local/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command\n    module = importlib.import_module(module_path)\n  File "/home/static/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 983, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "/home/static/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>\n    from pip._internal.cli.req_command import RequirementCommand\n  File "/home/static/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>\n    from pip._internal.operations.prepare import RequirementPreparer\n  File "/home/static/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 16, in <module>\n    from pip._internal.distributions import (\n  File "/home/static/.local/lib/python3.7/site-packages/pip/_internal/distributions/__init__.py", line 1, in <module>\n    from pip._internal.distributions.source import SourceDistribution\nImportError: cannot import name \'SourceDistribution\' from \'pip._internal.distributions.source\' (/home/static/.local/lib/python3.7/site-packages/pip/_internal/distributions/source/__init__.py)\n'FAILED: /home/static/workspace/grpc/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=63380, time=0.7sec]
FAILED: Some tests failed
```

**Comment by gnossen** [comment]
That's an odd stacktrace. All of it looks like Pip / Setuptools. Nothing specific to gRPC at all. What are you invoking? It looks like you're running an internal script. How about just `python setup.py install` from the repo root directory?

Pyenv may also be a factor. I've never tested with it before. We generally just use virtual environments.

**Comment by staticdev** [comment]
Yes, I installed all versions 2.7, 3.5, ... 3.8.

Just running: `python tools/run_tests/run_tests.py -l python`

**Comment by gnossen** [comment]
You may want to try `--use_docker` as well then. It's worth noting that `run_tests.py` will always rebuild from scratch, so it's going to be quite slow.

**Comment by staticdev** [comment]
Yes, I was just following https://github.com/grpc/grpc/blob/master/CONTRIBUTING.md

**Comment by staticdev** [comment]
@gnossen `--use_docker` worked.. now how am I supported to generate python sources from .proto files?

And as I make changes to `src/compiler/python_generator.cc` do I have to rerun `python tools/run_tests/run_tests.py -l python --use_docker`?

I am sorry if this seems stupid questions, but I did not understand this process from the documentation.

**Comment by gnossen** [comment]
Yeah, that documentation is not the best for someone looking to develop gRPC Python. It might be high time we write a document specifically for Python. The closest thing we have at the moment is [this script](https://github.com/grpc/grpc/blob/master/tools/distrib/install_all_python_modules.sh), which I recently added to try to codify what's mostly tribal knowledge at this point. Still working some kinks out of it though.

Basically, create a virtual environment, run that script, then `cd src/python/grpcio_tests` and `python setup.py test_lite`. After that, the workflow should be relatively normal. Each `grpcio_XXX` directory has a couple of non-standard commands to deal with protos.  There's `python setup.py preprocess`, which copies `.proto` files from the `src/proto` directory to the directory for the individual package. Then there's `python setup.py build_package_protos` which generates code from those packages. It looks like `build_package_protos` is currently missing from that script.

**Comment by staticdev** [comment]
Ok, then the next problem is.. after I create a venv, build source and run tests (without changing anything), there are many tests already failing, just some examples:

```
ERROR         health_check._health_servicer_test.HealthServicerBackwardsCompatibleWatchTest.test_graceful_shutdown
ERROR         health_check._health_servicer_test.HealthServicerBackwardsCompatibleWatchTest.test_two_watchers
ERROR         health_check._health_servicer_test.HealthServicerBackwardsCompatibleWatchTest.test_watch_empty_service
ERROR         health_check._health_servicer_test.HealthServicerBackwardsCompatibleWatchTest.test_watch_new_service
ERROR         health_check._health_servicer_test.HealthServicerBackwardsCompatibleWatchTest.test_watch_service_isolation
ERROR         protoc_plugin._python_plugin_test.SimpleStubsPluginTest.testFullDuplexCall
ERROR         protoc_plugin._python_plugin_test.SimpleStubsPluginTest.testHalfDuplexCall
ERROR         protoc_plugin._python_plugin_test.SimpleStubsPluginTest.testStreamingInputCall
ERROR         protoc_plugin._python_plugin_test.SimpleStubsPluginTest.testStreamingOutputCall
ERROR         protoc_plugin._python_plugin_test.SimpleStubsPluginTest.testUnaryCall
ERROR         protoc_plugin._python_plugin_test.SimpleStubsPluginTest.testUnaryCallInsecureSugar
ERROR         unit._compression_test.CompressionTest.testUnaryStreamChannelUncompressedMulticallableGzipCompressionServerUncompressedServerCallGzipCompression
ERROR         unit._compression_test.CompressionTest.testUnaryStreamChannelUncompressedMulticallableGzipCompressionServerUncompressedServerCallUncompressed
ERROR         unit._compression_test.CompressionTest.testUnaryStreamChannelUncompressedMulticallableUncompressedServerGzipCompressionServerCallGzipCompression
ERROR         unit._compression_test.CompressionTest.testUnaryStreamChannelUncompressedMulticallableUncompressedServerGzipCompressionServerCallUncompressed
ERROR         unit._compression_test.CompressionTest.testUnaryStreamChannelUncompressedMulticallableUncompressedServerUncompressedServerCallGzipCompression
ERROR         unit._compression_test.CompressionTest.testUnaryStreamChannelUncompressedMulticallableUncompressedServerUncompressedServerCallUncompressed
ERROR         unit._compression_test.CompressionTest.testUnaryUnaryChannelGzipCompressionMulticallableGzipCompressionServerGzipCompressionServerCallGzipCompression
ERROR         unit._compression_test.CompressionTest.testUnaryUnaryChannelGzipCompressionMulticallableGzipCompressionServerGzipCompressionServerCallUncompressed
ERROR         unit._compression_test.CompressionTest.testUnaryUnaryChannelGzipCompressionMulticallableGzipCompressionServerUncompressedServerCallGzipCompression
```

And it ends with Test failure =(

**Comment by gnossen** [comment]
Any more detailed error messages?

**Comment by staticdev** [comment]
@gnossen the output is big but just to illustrate:
```

unit._compression_test.CompressionTest.testUnaryUnaryChannelUncompressedMulticallableUncompressedServerGzipCompressionServerCallGzipCompression
traceback:
Traceback (most recent call last):
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 373, in _test_compression
    self.assertConfigurationCompressed(**kwargs)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 309, in assertConfigurationCompressed
    multicallable_kwargs, server_kwargs, server_handler, _REQUEST)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 213, in _get_compression_ratios
    first_server_kwargs, first_server_handler, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 196, in _get_byte_counts
    client_function(client_channel, multicallable_kwargs, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 227, in _unary_unary_client
    response = multi_callable(message, **multicallable_kwargs)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1594412855.627584523","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4056,"referenced_errors":[{"created":"@1594412855.627580858","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

stdout:

stderr:



unit._compression_test.CompressionTest.testUnaryUnaryChannelUncompressedMulticallableUncompressedServerGzipCompressionServerCallUncompressed
traceback:
Traceback (most recent call last):
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 373, in _test_compression
    self.assertConfigurationCompressed(**kwargs)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 309, in assertConfigurationCompressed
    multicallable_kwargs, server_kwargs, server_handler, _REQUEST)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 213, in _get_compression_ratios
    first_server_kwargs, first_server_handler, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 196, in _get_byte_counts
    client_function(client_channel, multicallable_kwargs, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 227, in _unary_unary_client
    response = multi_callable(message, **multicallable_kwargs)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1594412855.730407503","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4056,"referenced_errors":[{"created":"@1594412855.730403350","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

stdout:

stderr:



unit._compression_test.CompressionTest.testUnaryUnaryChannelUncompressedMulticallableUncompressedServerUncompressedServerCallGzipCompression
traceback:
Traceback (most recent call last):
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 373, in _test_compression
    self.assertConfigurationCompressed(**kwargs)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 309, in assertConfigurationCompressed
    multicallable_kwargs, server_kwargs, server_handler, _REQUEST)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 213, in _get_compression_ratios
    first_server_kwargs, first_server_handler, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 196, in _get_byte_counts
    client_function(client_channel, multicallable_kwargs, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 227, in _unary_unary_client
    response = multi_callable(message, **multicallable_kwargs)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1594412855.829502366","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4056,"referenced_errors":[{"created":"@1594412855.829498607","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

stdout:

stderr:



unit._compression_test.CompressionTest.testUnaryUnaryChannelUncompressedMulticallableUncompressedServerUncompressedServerCallUncompressed
traceback:
Traceback (most recent call last):
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/static/.pyenv/versions/3.6.10/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 373, in _test_compression
    self.assertConfigurationCompressed(**kwargs)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 309, in assertConfigurationCompressed
    multicallable_kwargs, server_kwargs, server_handler, _REQUEST)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 213, in _get_compression_ratios
    first_server_kwargs, first_server_handler, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 196, in _get_byte_counts
    client_function(client_channel, multicallable_kwargs, message)
  File "/home/static/workspace/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 227, in _unary_unary_client
    response = multi_callable(message, **multicallable_kwargs)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/static/workspace/grpc/py36_native/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1594412856.014242303","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4056,"referenced_errors":[{"created":"@1594412856.014238269","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

stdout:

stderr:


Unexpected successes: []

```

**Comment by gnossen** [comment]
Quite odd. This would imply that none of your clients are able to connect to locally spun up servers. I don't have an explanation for that. Maybe you have firewall rules set up for loopback? You may need to single out one failing test case and figuring out what's going on at an OS level. Are the servers listening on ports properly, for example?

**Comment by staticdev** [comment]
@gnossen.. I checked and didn't find processes. Most of tests are passing though. There are like 20 or so with errors.

**Comment by gnossen** [comment]
Can you supply the full list of failing tests?

**Comment by staticdev** [comment]
@gnossen sure.. I am attaching full output with errors and stacktraces in a minute (running).

**Comment by staticdev** [comment]
Here you are:

`(py36_native) static:~/workspace/grpc$ python src/python/grpcio_tests/setup.py test_lite > out.txt`

[out.txt](https://github.com/grpc/grpc/files/4905524/out.txt)

**Comment by sreenithi** [comment]
Closing this issue as it's been a while since the last update and may not be relevant anymore. Please feel free to re-open if the  issue still exists.
