### ISSUE TITLE
Ruby install failure on windows

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#23332]
When installing gRPC Ruby `1.30.0.pre1` on Windows Server 2019 64bis and running it, it failed with the following error.

```
C:\Users\veblush\Downloads\ruby>gem install grpc --version 1.30.0.pre1
Fetching grpc-1.30.0.pre1-x64-mingw32.gem
Successfully installed grpc-1.30.0.pre1-x64-mingw32
Parsing documentation for grpc-1.30.0.pre1-x64-mingw32
Installing ri documentation for grpc-1.30.0.pre1-x64-mingw32
Done installing documentation for grpc after 3 seconds
1 gem installed

C:\Users\veblush\Downloads\ruby>ruby
require 'grpc'
ch = GRPC::Core::Channel.new('localhost:1000', nil, :this_channel_is_insecure)
^Z
Traceback (most recent call last):
        2: from -:1:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- grpc (LoadError)
        8: from -:1:in `<main>'
        7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/grpc-1.30.0.pre1-x64-mingw32/src/ruby/lib/grpc.rb:19:in `<top (required)>'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/grpc-1.30.0.pre1-x64-mingw32/src/ruby/lib/grpc.rb:19:in `require_relative'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/grpc-1.30.0.pre1-x64-mingw32/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': Couldn't find or load gRPC's dynamic C core (LoadError)
```

But the previous stable version 1.28 was successfully installed on the same machine.

```
C:\Users\veblush\Downloads\ruby>gem install grpc
Fetching grpc-1.28.0-x64-mingw32.gem
Successfully installed grpc-1.28.0-x64-mingw32
Parsing documentation for grpc-1.28.0-x64-mingw32
Installing ri documentation for grpc-1.28.0-x64-mingw32
Done installing documentation for grpc after 3 seconds
1 gem installed

C:\Users\veblush\Downloads\ruby>ruby
require 'grpc'
ch = GRPC::Core::Channel.new('localhost:1000', nil, :this_channel_is_insecure)
^Z

C:\Users\veblush\Downloads\ruby> 
```

**Comment by veblush** [comment]
It appears that so file of 1.30 has a dll dependency towards `GPR-10.dll`, which is wrong. (In the screenshot below, the first one is 1.28 and the last one is 1.30).

![Screenshot from 2020-06-26 18-28-44](https://user-images.githubusercontent.com/2793282/85911600-f89cca80-b7da-11ea-9279-f266aec7e541.png)

**Comment by veblush** [comment]
`GRPC_C.64.RUBY` is built from the rule in the `Makefile`.

```
$(LIBDIR)/$(CONFIG)/grpc$(SHARED_VERSION_CORE).$(SHARED_EXT_CORE):
    $(LDXX)
    $(LDFLAGS) 
    -L$(LIBDIR)/$(CONFIG) 
    -shared 
    -Wl,--output-def=$(LIBDIR)/$(CONFIG)/grpc$(SHARED_VERSION_CORE).def 
    -Wl,--out-implib=$(LIBDIR)/$(CONFIG)/libgrpc$(SHARED_VERSION_CORE)-dll.a 
    -o $(LIBDIR)/$(CONFIG)/grpc$(SHARED_VERSION_CORE).$(SHARED_EXT_CORE)
    $(LIBGRPC_OBJS)
    $(OPENSSL_MERGE_LIBS)
    $(LDLIBS_SECURE)
    $(ZLIB_MERGE_LIBS)
    $(CARES_MERGE_LIBS)
    $(ADDRESS_SORTING_MERGE_LIBS)
    $(UPB_MERGE_LIBS)
    $(GRPC_ABSEIL_MERGE_LIBS)
    $(LDLIBS) 
    -lgpr$(SHARED_VERSION_CORE)-dll 
    -laddress_sorting$(SHARED_VERSION_CORE)-dll 
    -lupb$(SHARED_VERSION_CORE)-dll
```

Interestingly, it actually has a dependency to `GPR-10.dll`. For address_sorting and upb, it has redundant objs and dll dependency here and dll wil be ignored.

**Comment by veblush** [comment]
Oh this problem was originated from #21929. The rule for `GRPC_C.64.RUBY` looked like before the PR;

```
$(LIBDIR)/$(CONFIG)/grpc$(SHARED_VERSION_CORE).$(SHARED_EXT_CORE):
    $(LDXX)
    $(LDFLAGS)
    -L$(LIBDIR)/$(CONFIG)
    -shared
    -Wl,--output-def=$(LIBDIR)/$(CONFIG)/grpc$(SHARED_VERSION_CORE).def
    -Wl,--out-implib=$(LIBDIR)/$(CONFIG)/libgrpc$(SHARED_VERSION_CORE)-dll.a
    -o
    $(LIBDIR)/$(CONFIG)/grpc$(SHARED_VERSION_CORE).$(SHARED_EXT_CORE)
    $(LIBGRPC_OBJS)
    $(LIBDIR)/$(CONFIG)/libgpr.a
    $(LIBDIR)/$(CONFIG)/libupb.a
    $(OPENSSL_MERGE_LIBS)
    $(LDLIBS_SECURE)
    $(ZLIB_MERGE_LIBS)
    $(CARES_MERGE_LIBS)
    $(ADDRESS_SORTING_MERGE_LIBS)
    $(UPB_MERGE_LIBS)
    $(GRPC_ABSEIL_MERGE_LIBS)
    $(LDLIBS)
```

`gpr` was linked via static library rather than dll. I guess this is why.
