### ISSUE TITLE
gRPC Ruby won't run on Windows

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#23423]
gRPC Ruby won't run on Windows.

```
C:\Users\veblush\Downloads\ruby>gem install grpc
Fetching grpc-1.30.1-x64-mingw32.gem
Successfully installed grpc-1.30.1-x64-mingw32
Parsing documentation for grpc-1.30.1-x64-mingw32
Installing ri documentation for grpc-1.30.1-x64-mingw32
Done installing documentation for grpc after 2 seconds
1 gem installed

C:\Users\veblush\Downloads\ruby>ruby a.rb
Traceback (most recent call last):
        2: from a.rb:1:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- grpc (LoadError)
        8: from a.rb:1:in `<main>'
        7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/grpc-1.30.1-x64-mingw32/src/ruby/lib/grpc.rb:19:in `<top (required)>'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/grpc-1.30.1-x64-mingw32/src/ruby/lib/grpc.rb:19:in `require_relative'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/grpc-1.30.1-x64-mingw32/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': Couldn't find or load gRPC's dynamic C core (LoadError)
```

**Comment by sophieyfang** [comment]
We see similar issue with ruby 2.6.5 and gRPC 1.30.1

**Comment by apolcyn** [comment]
@sophieyfang can you try grpc 1.30.2? This includes https://github.com/grpc/grpc/pull/23343
