### ISSUE TITLE
Ruby end-to-end tests are failing on Ruby 2.7

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#23479]
### What version of gRPC and what language are you using?

gRPC Ruby 1.30.1

### What operating system (Linux, Windows,...) and version?

Linux with Ruby 2.7 (docker: ruby:2.7)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Ruby 2.7

### What did you do?

```
$ docker run -it --rm ruby:2.7 /bin/bash
# mkdir work && cd work
# gem install grpc
# git clone https://github.com/grpc/grpc.git
# cd grpc
# mv src/ruby/lib src/ruby/libx
# tools/run_tests/helper_scripts/run_ruby_end2end_tests.sh 
```

### What did you expect to see?

It ends successfully.

### What did you see instead?

A few tests are failing. One of them

```
+ ruby src/ruby/end2end/sig_int_during_channel_watch_driver.rb
start server
start client
client_control_port not used
timeout wait for client pid 8295
killed client child
src/ruby/end2end/sig_int_during_channel_watch_driver.rb:43:in `rescue in main': Timed out waiting for client process. It likely hangs when a SIGINT is sent while there is an active connectivity_state call (RuntimeError)
	from src/ruby/end2end/sig_int_during_channel_watch_driver.rb:34:in `main'
	from src/ruby/end2end/sig_int_during_channel_watch_driver.rb:55:in `<main>'
src/ruby/end2end/sig_int_during_channel_watch_driver.rb:36:in `wait': execution expired (Timeout::Error)
	from src/ruby/end2end/sig_int_during_channel_watch_driver.rb:36:in `block in main'
	from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	from src/ruby/end2end/sig_int_during_channel_watch_driver.rb:35:in `main'
	from src/ruby/end2end/sig_int_during_channel_watch_driver.rb:55:in `<main>'
E0714 21:18:25.941918529    8258 completion_queue.cc:278]    assertion failed: completed_head.next == reinterpret_cast<uintptr_t>(&completed_head)
tools/run_tests/helper_scripts/run_ruby_end2end_tests.sh: line 25:  8258 Aborted                 (core dumped) ruby src/ruby/end2end/sig_int_during_channel_watch_driver.rb

real	0m11.307s
user	0m0.405s
sys	0m0.143s
+ EXIT_CODE=1
```

**Comment by alto-ruby** [comment]
same as #25662, closing this one
