### ISSUE TITLE
Getting grpc health probe to work in C#

### ISSUE THREAD

**Issue by amarsgithub** [grpc/grpc#23481]
### The Problem
I currently have a health service running in a KinD cluster behind an nginx-ingress with localhost as the host. My ingress uses a self-signed TLS cert that is generated by the kubernetes cert manager. It currently works with the grpc_health_probe client which is written in Go.
The way I'm able to run the grpc_health_probe is: 
./grpc_health_probe -tls -tls-no-verify --connect-timeout 5s --rpc-timeout 5s --addr localhost:4443

 I would like to be able to use the C# client to work. This is what my code currently looks like: 
```
using Grpc.Core;
using Grpc.Health.V1;
using System;
using System.Collections.Generic;

namespace Channeltest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var sslTarget = new ChannelOption("grpc.ssl_target_name_override", "localhost");
            var authority = new ChannelOption("grpc.default_authority", "localhost");

            var channel = new Channel("localhost", 4443, new SslCredentials(null, null, (ctx) => true), new List<ChannelOption> { sslTarget, authority });

            var client = new Health.HealthClient(channel);
            client.Check(new HealthCheckRequest()
            {

            });
        }
    }
}
```

The error that I'm getting: 
```
Hello World!
E0714 20:32:59.876006 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1395: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0714 20:32:59.914034 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1395: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1594773179.917000000","description":"Failed to pick subchannel","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1594773179.917000000","description":"failed to connect to all addresses","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":394,"grpc_status":14}]}")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Health.V1.Health.HealthClient.Check(HealthCheckRequest request, CallOptions options) in C:\Users\t-amsuch\source\repos\Channeltest\Channeltest\obj\Debug\netcoreapp3.1\HealthGrpc.cs:line 145
   at Grpc.Health.V1.Health.HealthClient.Check(HealthCheckRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\Users\t-amsuch\source\repos\Channeltest\Channeltest\obj\Debug\netcoreapp3.1\HealthGrpc.cs:line 134
   at Channeltest.Program.Main(String[] args) in C:\Users\t-amsuch\source\repos\Channeltest\Channeltest\Program.cs:line 19

C:\Users\t-amsuch\source\repos\Channeltest\Channeltest\bin\Debug\netcoreapp3.1\Channeltest.exe (process 22264) exited with code -532462766.
```

### Describe the solution you'd like
I would like to get the grpc health probe to work with my C# client.

**Comment by windNight** [comment]
in net45 ,I handler similar error ，scene is send grpc in a thriftsever.
Grpc.Core.RpcException:Status(StatusCode="Unavailable", Detail="GOAWAY received", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1597976405.826000000","description":"Error received from peer ipv4:121.40.202.78:80","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\surface\call.cc","file_line":1055,"grpc_message":"GOAWAY received","grpc_status":14}").    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at xx.xx.GRpcSvc.ApplicationServices.FiltersGRpcService.FiltersGRpcServiceClient.DoFilter(FilterRequest request, CallOptions options)
   at xx.xx.GRpcSvc.ApplicationServices.FiltersGRpcService.FiltersGRpcServiceClient.DoFilter(FilterRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at xx.xx.GRpcClient.FilterGRpcService.Request(ResolveConditions conditions)
   at xx.xx.GRpcClient.xxGRpcService.FilterForAdWithResult(ResolveConditions conditions, Func`2 func)
   at xx.xx.Application.xxFilter.xxFilterService.<>c__DisplayClass5_0.b__1() in D:\tt\xx\x.x\xx.xx.Application\xxx\xxxFilterService.cs:line 71

**Comment by EliCDavis** [comment]
I'm having similar issues and currently still trying to resolve, but @amarsgithub have you tried specifying your CAs as specified here: https://github.com/grpc/grpc/issues/22474#issuecomment-630329000

That thread says C# client doesn't try loading any CAs off windows by default

**Comment by jtattermusch** [comment]
You should probably enable extra debug traces to see why exactly the connection was rejected.
https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

I suspect the issue is that you're trying to use SslCredentials with default trust roots and provide a verifyPeerCallback that always returns true to  force establishing the connections even if the TLS connection's server certs won't match the client.
But that's not how verifyPeerCallback works - it won't allow you to establish an illegal TLS connection where server identity doesn't match.

If you're using self signed certs, then you need to always create a client with the right trust roots (not "null" meaning default trust roots) so that connection to a server can be established.

https://github.com/grpc/grpc/blob/86f93801e5d452cff40d6958d21a8eb211da0654/src/csharp/Grpc.Core/Internal/ChannelCredentialsSafeHandle.cs#L49
