### ISSUE TITLE
Artifact Build Windows (internal CI) failed due to build_artifact.python_windows_x86_Python38_32bit

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23513]
https://source.cloud.google.com/results/invocations/7aca2539-d104-49d0-bdb9-51b41de997c2/log
```
C:\Python27\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: T:\src\github\grpc\workspace_python_windows_x86_Python38_32bit\src\python\grpcio\grpc\_cython\cygrpc.pxd

  tree = Parsing.p_module(s, pxd, full_module_name)

Found cython-generated files...

Traceback (most recent call last):

  File "setup.py", line 427, in <module>

    cmdclass=COMMAND_CLASS,

  File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 129, in setup

    return distutils.core.setup(**attrs)

  File "C:\Python27\lib\distutils\core.py", line 151, in setup

    dist.run_commands()

  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 75, in run

    _build_ext.run(self)

  File "C:\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run

    _build_ext.build_ext.run(self)

  File "C:\Python27\lib\distutils\command\build_ext.py", line 340, in run

    self.build_extensions()

  File "T:\src\github\grpc\workspace_python_windows_x86_Python38_32bit\src\python\grpcio\commands.py", line 269, in build_extensions

    "Failed `build_ext` step:\n{}".format(formatted_exception))

commands.CommandError: Failed `build_ext` step:

Traceback (most recent call last):

  File "T:\src\github\grpc\workspace_python_windows_x86_Python38_32bit\src\python\grpcio\commands.py", line 264, in build_extensions

    build_ext.build_ext.build_extensions(self)

  File "C:\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions

    _build_ext.build_ext.build_extensions(self)

  File "C:\Python27\lib\distutils\command\build_ext.py", line 449, in build_extensions

    self.build_extension(ext)

  File "C:\Python27\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension

    _build_ext.build_extension(self, ext)

  File "C:\Python27\lib\distutils\command\build_ext.py", line 499, in build_extension

    depends=ext.depends)

  File "C:\Python27\lib\distutils\msvc9compiler.py", line 548, in compile

    raise CompileError(msg)

CompileError: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

T:\src\github\grpc\workspace_python_windows_x86_Python38_32bit>popd



T:\src\github\grpc\workspace_python_windows_x86_Python38_32bit>exit /b 1


2020-07-16 12:42:10,500 FAILED: build_artifact.python_windows_x86_Python38_32bit [ret=1, pid=2412, time=76.7sec]
```

**Comment by lidizheng** [comment]
The root cause seems due to `.\src/core/lib/iomgr/error.h(24) : fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory`

`inttypes.h` was in error.h 3 years ago.
