### ISSUE TITLE
MSAN failure in //test/cpp/codegen:codegen_test_full

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#23675]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/cpp/codegen:codegen_test_full
-----------------------------------------------------------------------------
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CodegenTestFull
[ RUN      ] CodegenTestFull.Init
D0729 22:38:19.571036674      16 ev_posix.cc:173]            Using polling engine: epollex
D0729 22:38:19.573947791      16 lb_policy_registry.cc:40]   registering LB policy factory for "grpclb"
D0729 22:38:19.574513211      16 lb_policy_registry.cc:40]   registering LB policy factory for "cds_experimental"
D0729 22:38:19.575088334      16 lb_policy_registry.cc:40]   registering LB policy factory for "eds_experimental"
D0729 22:38:19.575640604      16 lb_policy_registry.cc:40]   registering LB policy factory for "lrs_experimental"
D0729 22:38:19.576181397      16 lb_policy_registry.cc:40]   registering LB policy factory for "priority_experimental"
D0729 22:38:19.576691762      16 lb_policy_registry.cc:40]   registering LB policy factory for "weighted_target_experimental"
D0729 22:38:19.577178576      16 lb_policy_registry.cc:40]   registering LB policy factory for "xds_routing_experimental"
D0729 22:38:19.577674211      16 lb_policy_registry.cc:40]   registering LB policy factory for "pick_first"
D0729 22:38:19.578184305      16 lb_policy_registry.cc:40]   registering LB policy factory for "round_robin"
D0729 22:38:19.578685073      16 dns_resolver_ares.cc:507]   Using ares dns resolver
[       OK ] CodegenTestFull.Init (16 ms)
[----------] 1 test from CodegenTestFull (16 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (17 ms total)
[  PASSED  ] 1 test.
==16==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f1e173fc6c4 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockInternal(unsigned int, unsigned int) /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:216:7
    #1 0x7f1e173fc0f9 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockImpl() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:172:13
    #2 0x7f1e173fbdeb in absl::lts_2020_02_25::base_internal::SpinLock::Lock() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:85:10
    #3 0x7f1e173fb9c7 in absl::lts_2020_02_25::base_internal::SpinLockHolder::SpinLockHolder(absl::lts_2020_02_25::base_internal::SpinLock*) /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:187:8
    #4 0x7f1e174477a5 in absl::lts_2020_02_25::DeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1320:39
    #5 0x7f1e17419738 in absl::lts_2020_02_25::DebugOnlyDeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1401:12
    #6 0x7f1e17419058 in absl::lts_2020_02_25::Mutex::Lock() /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1460:16
    #7 0x7f1e17698590 in gpr_mu_lock /proc/self/cwd/src/core/lib/gpr/sync_abseil.cc:55:39
    #8 0x7f1e17d4b556 in grpc_core::Executor::SetThreading(bool) /proc/self/cwd/src/core/lib/iomgr/executor.cc:174:7
    #9 0x7f1e17d4ff64 in grpc_core::Executor::Shutdown() /proc/self/cwd/src/core/lib/iomgr/executor.cc:213:29
    #10 0x7f1e17d55031 in grpc_core::Executor::ShutdownAll() /proc/self/cwd/src/core/lib/iomgr/executor.cc:423:59
    #11 0x7f1e1e908840 in grpc_shutdown_internal_locked() /proc/self/cwd/src/core/lib/surface/init.cc:175:7
    #12 0x7f1e1e9090e5 in grpc_shutdown_internal(void*) /proc/self/cwd/src/core/lib/surface/init.cc:208:3
    #13 0x7f1e176d74f9 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:140:27
    #14 0x7f1e176d6913 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:110:25
    #15 0x7f1e164726b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #16 0x7f1e15b8541c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

  Uninitialized value was stored to memory at
    #0 0x7f1e173fc5d7 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockInternal(unsigned int, unsigned int) /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:215
    #1 0x7f1e173fc0f9 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockImpl() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:172:13
    #2 0x7f1e173fbdeb in absl::lts_2020_02_25::base_internal::SpinLock::Lock() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:85:10
    #3 0x7f1e173fb9c7 in absl::lts_2020_02_25::base_internal::SpinLockHolder::SpinLockHolder(absl::lts_2020_02_25::base_internal::SpinLock*) /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:187:8
    #4 0x7f1e174477a5 in absl::lts_2020_02_25::DeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1320:39
    #5 0x7f1e17419738 in absl::lts_2020_02_25::DebugOnlyDeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1401:12
    #6 0x7f1e17419058 in absl::lts_2020_02_25::Mutex::Lock() /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1460:16
    #7 0x7f1e17698590 in gpr_mu_lock /proc/self/cwd/src/core/lib/gpr/sync_abseil.cc:55:39
    #8 0x7f1e17d4b556 in grpc_core::Executor::SetThreading(bool) /proc/self/cwd/src/core/lib/iomgr/executor.cc:174:7
    #9 0x7f1e17d4ff64 in grpc_core::Executor::Shutdown() /proc/self/cwd/src/core/lib/iomgr/executor.cc:213:29
    #10 0x7f1e17d55031 in grpc_core::Executor::ShutdownAll() /proc/self/cwd/src/core/lib/iomgr/executor.cc:423:59
    #11 0x7f1e1e908840 in grpc_shutdown_internal_locked() /proc/self/cwd/src/core/lib/surface/init.cc:175:7
    #12 0x7f1e1e9090e5 in grpc_shutdown_internal(void*) /proc/self/cwd/src/core/lib/surface/init.cc:208:3
    #13 0x7f1e176d74f9 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:140:27
    #14 0x7f1e176d6913 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:110:25
    #15 0x7f1e164726b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

  Uninitialized value was stored to memory at
    #0 0x7f1e173fc061 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockImpl() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:171:14
    #1 0x7f1e173fbdeb in absl::lts_2020_02_25::base_internal::SpinLock::Lock() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:85:10
    #2 0x7f1e173fb9c7 in absl::lts_2020_02_25::base_internal::SpinLockHolder::SpinLockHolder(absl::lts_2020_02_25::base_internal::SpinLock*) /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:187:8
    #3 0x7f1e174477a5 in absl::lts_2020_02_25::DeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1320:39
    #4 0x7f1e17419738 in absl::lts_2020_02_25::DebugOnlyDeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1401:12
    #5 0x7f1e17419058 in absl::lts_2020_02_25::Mutex::Lock() /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1460:16
    #6 0x7f1e17698590 in gpr_mu_lock /proc/self/cwd/src/core/lib/gpr/sync_abseil.cc:55:39
    #7 0x7f1e17d4b556 in grpc_core::Executor::SetThreading(bool) /proc/self/cwd/src/core/lib/iomgr/executor.cc:174:7
    #8 0x7f1e17d4ff64 in grpc_core::Executor::Shutdown() /proc/self/cwd/src/core/lib/iomgr/executor.cc:213:29
    #9 0x7f1e17d55031 in grpc_core::Executor::ShutdownAll() /proc/self/cwd/src/core/lib/iomgr/executor.cc:423:59
    #10 0x7f1e1e908840 in grpc_shutdown_internal_locked() /proc/self/cwd/src/core/lib/surface/init.cc:175:7
    #11 0x7f1e1e9090e5 in grpc_shutdown_internal(void*) /proc/self/cwd/src/core/lib/surface/init.cc:208:3
    #12 0x7f1e176d74f9 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:140:27
    #13 0x7f1e176d6913 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:110:25
    #14 0x7f1e164726b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

  Uninitialized value was stored to memory at
    #0 0x7f1e173fce7c in unsigned int std::__1::__cxx_atomic_load<unsigned int>(std::__1::__cxx_atomic_base_impl<unsigned int> const*, std::__1::memory_order) /usr/local/bin/../include/c++/v1/atomic:970:12
    #1 0x7f1e173fc32d in std::__1::__atomic_base<unsigned int, false>::load(std::__1::memory_order) const /usr/local/bin/../include/c++/v1/atomic:1487:17
    #2 0x7f1e173fc005 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockImpl() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:171:37
    #3 0x7f1e173fbdeb in absl::lts_2020_02_25::base_internal::SpinLock::Lock() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:85:10
    #4 0x7f1e173fb9c7 in absl::lts_2020_02_25::base_internal::SpinLockHolder::SpinLockHolder(absl::lts_2020_02_25::base_internal::SpinLock*) /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:187:8
    #5 0x7f1e174477a5 in absl::lts_2020_02_25::DeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1320:39
    #6 0x7f1e17419738 in absl::lts_2020_02_25::DebugOnlyDeadlockCheck(absl::lts_2020_02_25::Mutex*) /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1401:12
    #7 0x7f1e17419058 in absl::lts_2020_02_25::Mutex::Lock() /proc/self/cwd/external/com_google_absl/absl/synchronization/mutex.cc:1460:16
    #8 0x7f1e17698590 in gpr_mu_lock /proc/self/cwd/src/core/lib/gpr/sync_abseil.cc:55:39
    #9 0x7f1e17d4b556 in grpc_core::Executor::SetThreading(bool) /proc/self/cwd/src/core/lib/iomgr/executor.cc:174:7
    #10 0x7f1e17d4ff64 in grpc_core::Executor::Shutdown() /proc/self/cwd/src/core/lib/iomgr/executor.cc:213:29
    #11 0x7f1e17d55031 in grpc_core::Executor::ShutdownAll() /proc/self/cwd/src/core/lib/iomgr/executor.cc:423:59
    #12 0x7f1e1e908840 in grpc_shutdown_internal_locked() /proc/self/cwd/src/core/lib/surface/init.cc:175:7
    #13 0x7f1e1e9090e5 in grpc_shutdown_internal(void*) /proc/self/cwd/src/core/lib/surface/init.cc:208:3
    #14 0x7f1e176d74f9 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:140:27
    #15 0x7f1e176d6913 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:110:25
    #16 0x7f1e164726b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

  Memory was marked as uninitialized
    #0 0x45026e in __sanitizer_dtor_callback /tmp/clang-build/src/compiler-rt/lib/msan/msan_interceptors.cpp:937:3
    #1 0x7f1e173fb6cd in absl::lts_2020_02_25::base_internal::SpinLock::~SpinLock() /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:80:73
    #2 0x4507db in MSanCxaAtExitWrapper(void*) /tmp/clang-build/src/compiler-rt/lib/msan/msan_interceptors.cpp:1130:3

SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h:216:7 in absl::lts_2020_02_25::base_internal::SpinLock::TryLockInternal(unsigned int, unsigned int)
Exiting
MemorySanitizer: 1 warnings reported.
```

https://source.cloud.google.com/results/invocations/0e01a31e-0c2d-487c-bd38-ccd12254cbe0/targets/%2F%2Ftest%2Fcpp%2Fcodegen:codegen_test_full/log

Seen in PR: https://github.com/grpc/grpc/pull/23670

**Comment by veblush** [comment]
Fixed by https://github.com/grpc/grpc/pull/23673
