### ISSUE TITLE
[bazel][python] py_grpc_library() doesn't transitively provide its dependencies

### ISSUE THREAD

**Issue by xa4a** [grpc/grpc#23769]
### What version of gRPC and what language are you using?

Bazel rules_proto_grpc-1.0.2 , rules_python-0.0.2

### What operating system (Linux, Windows,...) and version?

Bazel on a Mac

### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel Build: 3.4.1-

### What did you do?
I have a bazel workspace with a **proto message** definition under `//proto`, a **grpc service** definition under `//service/proto` and a python library using the grpc service definition under `//service/client`.

See the repro repo: https://github.com/xa4a/grpc-python-rules-repro.

My python library/binary needs to instantiate the gRPC client, so it does: 

`from service.proto import service_pb2_grpc`

This only works if I also specify the proto service's transitive dependency on proto message as a dependency of my python library/binary. Otherwise it fails to import the service python module. Even though my code doesn't reference/need the transitive dependency itself. So I have to:

```
py_binary(
    name = "client",
    srcs = ["client.py"],
    deps = [
        "//proto:foo_py_pb2",
        "//service/proto:service_py_pb2_grpc",
    ],
)
```

### What did you expect to see?

I expected that specifiying in `deps=[..]` just the package that's imported in python code is enough like:
```
py_binary(
    name = "client",
    srcs = ["client.py"],
    deps = [
        "//service/proto:service_py_pb2_grpc",
    ],
)
```

### What did you see instead?

If I don't also specify the transitive dependency it's no included in the runfiles, I'm getting:

```Traceback (most recent call last):
  File "/private/var/tmp/_bazel_.../client.runfiles/repro/service/client/client.py", line 5, in <module>
    from service.proto import service_pb2_grpc
  File "/private/var/tmp/_bazel_.../client.runfiles/repro/service/proto/service_pb2_grpc.py", line 4, in <module>
    from proto import foo_pb2 as proto_dot_foo__pb2
ModuleNotFoundError: No module named 'proto'
```

As the generated _pb2_grpc.py python module references the foo_pb2 that's no included.

### Anything else we should know about your project / environment?

I would expect that just specifying the `py_grpc_library()` as my `py_binary()` dependency should be enough to import the python module with no errors.

**Comment by chokychou** [comment]
Any follow ups?

**Comment by XuanWang-Amos** [comment]
@gnossen PTAL
