### ISSUE TITLE
Running .NET Core with Grpc on Docker (alpine linux) fails with "Error loading shared library ld-linux-x86-64.so.2"

### ISSUE THREAD

**Issue by vuggg** [grpc/grpc#23772]
I'm build a web API app using .NET core and gRPC for Csharp.

In Local, It work verry well, but when I build container and run it on Docker Desktop, receive:

```
docker logs --tail=100 f30a5c0d755e
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {508718d1-f261-4b39-bb67-e3ca9825fc76} may be persisted to storage in unencrypted form.
Unhandled exception. System.IO.IOException: Error loading native library "/app/runtimes/linux/native/libgrpc_csharp_ext.x64.so". Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/runtimes/linux/native/libgrpc_csharp_ext.x64.so)
   at Net.Core.Grpc.GrpcServerManagerment.InvokeException(Exception exception, Action`1 whenException)
   at Net.Core.Grpc.GrpcServerManagerment.InitServer(IEnumerable`1 services, IServerTracer tracer, List`1 interceptors, List`1 channelOptions, Action`1 whenException, Action`1 grpcConfigAction)
   at Net.Core.Grpc.GrpcServerManagerment.InitServer(ServerServiceDefinition service, IServerTracer tracer, List`1 interceptors, List`1 channelOptions, Action`1 whenException, Action`1 grpcConfigAction)
   at iNRES.Service.Category.gRPC.Server.GrpcServer.<StartAsync>b__2_0() in /app/src/iNRES.Service.Category/gRPC/Server/gRPCServers.cs:line 32
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at iNRES.Service.Category.Program.Main(String[] args) in /app/src/iNRES.Service.Category/Program.cs:line 20
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Unhandled exception. System.IO.IOException: Error loading native library "/app/runtimes/linux/native/libgrpc_csharp_ext.x64.so". Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/runtimes/linux/native/libgrpc_csharp_ext.x64.so)
   at Net.Core.Grpc.GrpcServerManagerment.InvokeException(Exception exception, Action`1 whenException)
   at Net.Core.Grpc.GrpcServerManagerment.InitServer(IEnumerable`1 services, IServerTracer tracer, List`1 interceptors, List`1 channelOptions, Action`1 whenException, Action`1 grpcConfigAction)
   at Net.Core.Grpc.GrpcServerManagerment.InitServer(ServerServiceDefinition service, IServerTracer tracer, List`1 interceptors, List`1 channelOptions, Action`1 whenException, Action`1 grpcConfigAction)
   at iNRES.Service.Category.gRPC.Server.GrpcServer.<StartAsync>b__2_0() in /app/src/iNRES.Service.Category/gRPC/Server/gRPCServers.cs:line 32
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at iNRES.Service.Category.Program.Main(String[] args) in /app/src/iNRES.Service.Category/Program.cs:line 20
```
```
<PackageReference Include="Google.Protobuf" Version="3.8.0" />
		<PackageReference Include="Google.Protobuf.Tools" Version="3.8.0" />
		<PackageReference Include="Grpc.Tools" Version="1.22.0" />
<PackageReference Include="Grpc" Version="2.31.0" />

```

```
docker file:

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /app

ARG sln=myproject.sln
ARG service=src/myproject
ARG tests=test/myproject.Test
ARG configuration=Release

COPY ${sln} ./
COPY ./${service} ./${service}/
COPY ./${tests} ./${tests}/

RUN apk update && apk add libc6-compat

RUN dotnet restore /property:Configuration=${configuration}

COPY . ./
RUN dotnet publish ${service} -c ${configuration} -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine as runtime
WORKDIR /app

COPY --from=build /app/${service}/${configuration}/out .

ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT docker

EXPOSE 5000

ENTRYPOINT dotnet myproject.dll

```

**Comment by vuggg** [comment]
solved

**Comment by vuggg** [comment]
Same error when call method:
```
System.IO.IOException: Error loading native library "/app/runtimes/linux/native/libgrpc_csharp_ext.x64.so". Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/runtimes/linux/native/libgrpc_csharp_ext.x64.so)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Net.Core.Grpc.IPEndpointStrategy.SetCallInvokers(String serviceName, Boolean filterBlack)
   at Net.Core.Grpc.IPEndpointStrategy.Get(String serviceName)
   at Net.Core.Grpc.ClientCallInvoker.Call[TResponse](Func`2 call, Int32 retryLeft)
   at Net.Core.Grpc.ClientCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at INRES.Service.Category.GetAllDvhcService.GetAllDvhcServiceClient.GetAllDvhcAsync(GetAllDvhcRequest request, CallOptions options)
   at INRES.Service.Category.GetAllDvhcService.GetAllDvhcServiceClient.GetAllDvhcAsync(GetAllDvhcRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at iNRES.Service.Meteorology.Domain.QueryHandlers.TramkttvQueryHandler.Handle(GetTramkttvQuery request, CancellationToken cancellationToken) in /app/src/iNRES.Service.Meteorology/Domain/QueryHandlers/TramkttvQueryHandler.cs:line 66
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at iNRES.Service.Meteorology.Controllers.BaseController.QueryAsync[TResult](IRequest`1 query) in /app/src/iNRES.Service.Meteorology/Controllers/BaseController.cs:line 45
   at iNRES.Service.Meteorology.Controllers.MtTramkttvController.GetById(Int32 id) in /app/src/iNRES.Service.Meteorology/Controllers/MtTramkttvController.cs:line 39
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-08-09T14:09:40.5396440+00:00 0HM1SDK4V8UDG:00000005 [INF] Request finished in 36.6437ms 500  (791a596a)
```

**Comment by jtattermusch** [comment]
Looks like this might be some issue when trying to run on alpine linux.
You might want to try with a docker image that's based on a different distro (ubuntu debian).

**Comment by jtattermusch** [comment]
.NET core also offers docker images based on Ubuntu and Debian
https://hub.docker.com/_/microsoft-dotnet-core-sdk  - likely that will solve your issue.

**Comment by zenovicharis** [comment]
Anything on this topic I have similar dockerfile, I'm getting the same issue I tried many different docker images 

`mcr.microsoft.com/dotnet/core/sdk:3.1`
`mcr.microsoft.com/dotnet/core/sdk:3.1-alpine`
`mcr.microsoft.com/dotnet/core/sdk:3.1-bionic`

Even tho I tried installing the library and manually installing in Dockerfile, like

`RUN apk update && apk add --no-cache libc6-compat`
`RUN apk update && apk add libc6-compat && ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2`

Image is created successfully, but when I run the container and try calling the API route where I need to get referenced JSON I got the same error. In my case, I try to run .NET Core 3.1 API on Docker (app on host machine is working fine)

```
System.IO.IOException: Error loading native library "/api/runtimes/linux/native/libgrpc_csharp_ext.x64.so".
Error loading shared library ld-linux-x86-64.so.2: 
No such file or directory (needed by /api/runtimes/linux/native/libgrpc_csharp_ext.x64.so)
```

Also, I attached to a docker container with shell and check for files that are missing are there apparently, I was able to find them

Could this be a problem with image or it could be something else

**Comment by zenovicharis** [comment]
Found the solution, it worked for me to run different runtime image
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS runtime
```

**Comment by nroose** [comment]
I don't get how this is a solution. The problem is that it doesn't work on alpine. Using debian is not a solution to getting it working on alpine. Is it that GRPC has decided to not support alpine?

**Comment by nroose** [comment]
Though this seem to work: https://dustri.org/b/error-loading-shared-library-ld-linux-x86-64so2-on-alpine-linux.html. Not sure if there's something that can be done by grpc or alpine.

**Comment by edwardmeng** [comment]
Downgrading lib6-compat to 1.19 fixed this issue for me. Not sure what is impact though.
`
RUN apk add bash libc6-compat=1.1.19-r11 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.8/main
`

**Comment by dragos-durlut** [comment]
> Though this seem to work: https://dustri.org/b/error-loading-shared-library-ld-linux-x86-64so2-on-alpine-linux.html. Not sure if there's something that can be done by GRPC or alpine.

The code from that link fixed my issue with loading the `GoogleOR.Tools` on `dotnet:sdk8.0-alpine`

I've added this to my final image 
```yml
USER root
RUN apk add libc6-compat
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
```
