### ISSUE TITLE
FLAKE: csharp_windows_opt_native_csharp_Grpc_IntegrationTesting_MetadataCredentialsTest.csharp.Grpc.IntegrationTesting.MetadataCredentialsTest

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#23919]
https://source.cloud.google.com/results/invocations/8a0a6b1c-9730-4915-8fa4-c612f0fdd6e4/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_opt_native%2Fcsharp.Grpc.IntegrationTesting.MetadataCredentialsTest/tests

```
NUnitLite 3.10.1 (.NET Framework 4.5)
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601.65536
  CLR Version: 4.0.30319.42000

Test Files
    T:/src/github/grpc/workspace_csharp_windows_opt_native/src/csharp/Grpc.IntegrationTesting/bin/Release/net45/Grpc.IntegrationTesting.exe

Test Filters
    Test: Grpc.IntegrationTesting.MetadataCredentialsTest

=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_BothChannelAndPerCall
D0820 14:06:30.593750 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "T:\src\github\grpc\workspace_csharp_windows_opt_native\src\csharp\Grpc.IntegrationTesting\bin\Release\net45\grpc_csharp_ext.x64.dll"
D0820 14:06:30.687500 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_Channel
=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_Composed
=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_ComposedPerCall
=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_InterceptorLeavesMetadataEmpty
=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_InterceptorThrows
E0820 14:06:31.843750 Grpc.Core.Internal.NativeMetadataCredentialsPlugin Exception occurred in metadata credentials plugin. This is likely not a problem with gRPC itself. Please verify that the code supplying the metadata (usually an authentication token) works correctly. System.Exception: Auth interceptor throws
   at Grpc.IntegrationTesting.MetadataCredentialsTest.<>c__DisplayClass14_0.<MetadataCredentials_InterceptorThrows>b__0(AuthInterceptorContext context, Metadata metadata)
   at Grpc.Core.Internal.NativeMetadataCredentialsPlugin.<GetMetadataAsync>d__12.MoveNext()
=> Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_PerCall

Errors, Failures and Warnings

1) Error : Grpc.IntegrationTesting.MetadataCredentialsTest.MetadataCredentials_PerCall
TearDown : System.AggregateException : One or more errors occurred.
  ----> System.Exception : Shutdown check: Detected 1 pending batch completions.
--TearDown
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.MetadataCredentialsTest.Cleanup()
--Exception
   at Grpc.Core.Internal.DebugStats.DebugWarning(String message)
   at Grpc.Core.Internal.DebugStats.CheckOK()
   at Grpc.Core.GrpcEnvironment.<ShutdownAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.GrpcEnvironment.<ReleaseAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<ShutdownInternalAsync>d__32.MoveNext()

Run Settings
    Number of Test Workers: 1
    Work Directory: T:\src\github\grpc\workspace_csharp_windows_opt_native
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 7, Passed: 6, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2020-08-20 21:06:30Z
    End time: 2020-08-20 21:06:32Z
    Duration: 1.673 seconds
```

**Comment by jtattermusch** [comment]
This only happended once in the last 3 months (https://source.cloud.google.com/results/invocations/5ea8c1f7-e08c-4969-be6c-510bbb21db7a/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_opt_native%2Fcsharp.mono.Grpc.IntegrationTesting.MetadataCredentialsTest/tests), so I'm going to close.

If we ever have to reopen, let's file a buganizer bug instead (we're going to track test flakiness in buganizer going forward).
