### ISSUE TITLE
Flake: test_in_flight_stream_stream_call

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#23982]
Test case "test_in_flight_stream_stream_call" in "_exit_test" fails on Python 2 with following error: 

```Python
test_in_flight_stream_stream_call (__main__.ExitTest) ... Traceback (most recent call last):
  File "/usr/local/google/home/lidiz/src/grpc/src/python/grpcio_tests/tests/unit/_exit_scenarios.py", line 235, in <module>
    for response in response_iterator:
  File "/usr/local/google/home/lidiz/src/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_channel.py", line 413, in next
    return self._next()
  File "/usr/local/google/home/lidiz/src/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_channel.py", line 706, in _next
    raise self
  File "/usr/lib/python2.7/threading.py", line 289, in __exit__
    return self.__lock.__exit__(*args)
  File "/usr/lib/python2.7/threading.py", line 216, in __exit__
    self.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
ERROR
```

There isn't any obviously wrong logic: https://github.com/grpc/grpc/blob/4365bdfdcc3c9cde3a77d5a024d5aaea28bcf911/src/python/grpcio/grpc/_channel.py#L676-L706.

The lock might be deallocated by Python interpretor. There could be a bug in CPython.

**Comment by lidizheng** [comment]
@gnossen The two burdensome workarounds are 1. register a signal handler; 2. catch interrupt key exception within gRPC library. Both ways allow us to enforce the deallocation order, so the spawned thread (request consumption thread, spin thread, etc.) can be collected before main thread. WDYT?
