### ISSUE TITLE
gRPC asynchronous client stuck at cq_.Next() forever

### ISSUE THREAD

**Issue by Jiboxiake** [grpc/grpc#24014]
### What version of gRPC and what language are you using?
1.30.0

### What operating system (Linux, Windows,...) and version?
Linux Ubuntu 18.0.4

### What runtime / compiler are you using (e.g. python version or version of gcc)
7.5.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
I was working on a project with 2 nodes. Each node will use a thread to host an asynchronous server and each node will have 64 threads to process transactions (over 10,000) and will send out asynchronous RPC to the other node at the end of each transaction. I found out, while occasionally I can have all my worker threads joined, mostly 1 or 2 threads on each client will be stuck at cq->Next(&got_tag, &ok). This is the info when I did info thread, then go to the thread and print out the backtrace. 
The following is how I implemented the asynchronous client, which is almost exactly like how [https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_async_client2.cc](url) did it. The following is how I implemented the functions.
```
Status Sundial_Async_Client:: contactRemote(CompletionQueue* cq, TxnManager * txn,uint64_t node_id,SundialRequest& request, SundialResponse** response){

        // Call object to store rpc data
        AsyncClientCall* call = new AsyncClientCall;

        // stub_->PrepareAsyncSayHello() creates an RPC object, returning
        // an instance to store in "call" but does not actually start the RPC
        // Because we are using the asynchronous API, we need to hold on to
        // the "call" instance in order to get updates on the ongoing RPC.
        call->response_reader =
            stub_->PrepareAsynccontactRemote(&call->context, request, cq);

        // StartCall initiates the RPC call
        call->response_reader->StartCall();
        call->reply=*response;
        // Request that, upon completion of the RPC, "reply" be updated with the
        // server's response; "status" with the indication of whether the operation
        // was successful. Tag the request with the memory address of the call object.
        call->response_reader->Finish(call->reply, &call->status, (void*)call);
  
    return Status::OK;
}
```
```
Status Sundial_Async_Client::contactRemoteDone(CompletionQueue* cq, TxnManager * txn,uint64_t node_id, SundialResponse* response, int count){
    void* got_tag;
        bool ok = false;
        int local_count=0;
        // Block until the next result is available in the completion queue "cq".
        while (cq->Next(&got_tag, &ok)) {
            local_count++;
            // The tag in this example is the memory location of the call object
            AsyncClientCall* call = static_cast<AsyncClientCall*>(got_tag);

            // Verify that the request was completed successfully. Note that "ok"
            // corresponds solely to the request for updates introduced by Finish().
            GPR_ASSERT(ok);


            // Once we're complete, deallocate the call object.
             //doing the cleaning
    glob_stats->_stats[GET_THD_ID]->_resp_msg_count[ call->reply->response_type() ] ++;
    glob_stats->_stats[GET_THD_ID]->_resp_msg_size[ call->reply->response_type() ] += call->reply->SpaceUsedLong();
            delete call;
            if(local_count==count){
            break;
        }
        }
        
     
    //txn->rpc_semaphore->decr();
      return Status::OK;
   
}
```

### What did you expect to see?
Things go smoothly and pthread_join() processed.

### What did you see instead?
 I found out, while occasionally I can have all my worker threads joined, mostly 1 or 2 threads on each client will be stuck at cq->Next(&got_tag, &ok). This is the info when I did info thread, then go to the thread and print out the backtrace. 
```
#0  0x00007ffff621cbb7 in epoll_wait (epfd=3, events=0x7ffff404c2b0, 
    maxevents=100, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00000000006a0c7e in pollable_epoll(pollable*, long) ()
#2  0x00000000006a17c5 in pollset_work ()
#3  0x000000000067dd5a in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) ()
#4  0x00000000005219ea in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) ()
#5  0x000000000054fa23 in cq_next(grpc_completion_queue*, gpr_timespec, void*)
    ()
#6  0x000000000054ff18 in grpc_completion_queue_next ()
#7  0x0000000000470676 in grpc_impl::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) ()
#8  0x00000000004434f3 in grpc_impl::CompletionQueue::Next (
    this=0x7ffebbe000c0, tag=0x7ffec39d32d8, ok=0x7ffec39d32d3)
    at /local/include/grpcpp/impl/codegen/completion_queue_impl.h:179
#9  0x0000000000443152 in Sundial_Async_Client::contactRemoteDone (
    this=0x7ffff5a08240, cq=0x7ffebbe000c0, txn=0x7ffebbe037e0, node_id=1, 
    response=0x0, count=1) at grpc/grpc_async_client.cpp:70
#10 0x000000000043b2dc in TxnManager::process_2pc_phase2 (this=0x7ffebbe037e0, 
    rc=ABORT, cq=0x7ffebbe000c0) at system/txn.cpp:462
#11 0x000000000043a38c in TxnManager::start (this=0x7ffebbe037e0)
    at system/txn.cpp:166
---Type <return> to continue, or q <return> to quit---ret
#12 0x000000000043f8c2 in WorkerThread::run (this=0x7fffdb133ec0)
    at system/worker_thread.cpp:92
#13 0x0000000000441ff9 in start_thread (thread=0x7fffdb133ec0)
    at system/main.cpp:204
#14 0x00007ffff64f36db in start_thread (arg=0x7ffec39d5700)
    at pthread_create.c:463
#15 0x00007ffff621c88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
and 
```
#0  0x00007ffff64f99f3 in futex_wait_cancelable (private=<optimized out>, 
    expected=0, futex_word=0x7ffec49d4fb0)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7ffff404c278, 
    cond=0x7ffec49d4f88) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7ffec49d4f88, mutex=0x7ffff404c278)
    at pthread_cond_wait.c:655
#3  0x000000000072f05a in gpr_cv_wait ()
#4  0x00000000006a12b0 in begin_worker ()
#5  0x00000000006a1757 in pollset_work ()
#6  0x000000000067dd5a in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) ()
#7  0x00000000005219ea in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) ()
#8  0x000000000054fa23 in cq_next(grpc_completion_queue*, gpr_timespec, void*)
    ()
#9  0x000000000054ff18 in grpc_completion_queue_next ()
#10 0x0000000000470676 in grpc_impl::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) ()
#11 0x00000000004434f3 in grpc_impl::CompletionQueue::Next (
    this=0x7ffebb632000, tag=0x7ffec49d52d8, ok=0x7ffec49d52d3)
    at /local/include/grpcpp/impl/codegen/completion_queue_impl.h:179
#12 0x0000000000443152 in Sundial_Async_Client::contactRemoteDone (
---Type <return> to continue, or q <return> to quit---ret
    this=0x7ffff5a08240, cq=0x7ffebb632000, txn=0x7ffebb608000, node_id=1, 
    response=0x0, count=1) at grpc/grpc_async_client.cpp:70
#13 0x000000000043b2dc in TxnManager::process_2pc_phase2 (this=0x7ffebb608000, 
    rc=ABORT, cq=0x7ffebb632000) at system/txn.cpp:462
#14 0x000000000043a38c in TxnManager::start (this=0x7ffebb608000)
    at system/txn.cpp:166
#15 0x000000000043f8c2 in WorkerThread::run (this=0x7fffdb133e40)
    at system/worker_thread.cpp:92
#16 0x0000000000441ff9 in start_thread (thread=0x7fffdb133e40)
    at system/main.cpp:204
#17 0x00007ffff64f36db in start_thread (arg=0x7ffec49d7700)
    at pthread_create.c:463
#18 0x00007ffff621c88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
Since it only happenes at a very low rate, I suspect there is something wrong in the communication protocol and the server never gets it or something. I suspect there is a bug in the communication.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
It has 2 machines and 64 threads which will clone itself to run thousands or transactions and I also had synchronous service and it seems to run smoothly.

**Comment by veblush** [comment]
It's a bit old and would you try this with the latest version of gRPC?
