### ISSUE TITLE
Status(StatusCode="Cancelled", Detail="No grpc-status found on response.")

### ISSUE THREAD

**Issue by ikaccc** [grpc/grpc#24065]
`   
StackTrace:
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Web.WidgetManagement.HttpAggregator.Services.WidgetService.<<GetAppliedWidgetsAsync>b__4_0>d.MoveNext() in C:\Users\ivan.cekov\source\repos\Admin-v6-Services\ApiGateways\Web.WidgetManagement.HttpAggregator\Services\WidgetService.cs:line 36
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Web.WidgetManagement.HttpAggregator.Services.GrpcCallerService.<CallService>d__0`1.MoveNext() in C:\Users\ivan.cekov\source\repos\Admin-v6-Services\ApiGateways\Web.WidgetManagement.HttpAggregator\Services\GrpcCallerService.cs:line 38`

client
WidgetService.cs
`       
//_urls.GrpcWidget = "https://localhost:5051
 public async Task<IEnumerable<WidgetData>> GetAppliedWidgetsAsync()
        {
            try
            {
                var res = await GrpcCallerService.CallService(_urls.GrpcWidget, async channel =>
                {
                    var client = new WidgetManager.API.Protos.WidgetManagement.WidgetManagementClient(channel);
                    _logger.LogDebug("grpc client created, GetAppliedWidgets");
                    var response = await client.GetAppliedWidgetsAsync(new Empty { });
                    _logger.LogDebug("grpc response {@response}", response);

                    return MapToWidgetData(response);
                });
                return res;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return null;
        }`

GrpcCallerService.cs
`public static class GrpcCallerService
    {
        public static async Task<TResponse> CallService<TResponse>(string urlGrpc, Func<GrpcChannel, Task<TResponse>> func)
        {
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);
            var channel = GrpcChannel.ForAddress(urlGrpc);

            Log.Information("Creating grpc client base address urlGrpc ={@urlGrpc}, BaseAddress={@BaseAddress} ", urlGrpc, channel.Target);

            try
            {
                return await func(channel);
            }
            catch (RpcException e)
            {
                Log.Error("Error calling via grpc: {Status} - {Message}", e.Status, e.Message);
                return default;
            }
            finally
            {
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", false);
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", false);
            }
        }`

The issue appears when grpc server returns data to the client.

Environment details
OS: Windows 10
Package name and version: .NET Core v3.1.7 & Grpc.Core 2.31.0 & protobuf-net 3.13.0

**Comment by sshbio** [comment]
Any update/suggestion on this issue?

**Comment by jtattermusch** [comment]
Based on your snippets, it looks like you're actually not using Grpc.Core but rather grpc-dotnet. I'll transfer the issue to the correct repository.
