### ISSUE TITLE
"Basic Tests Python MacOS"  failing: AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#24276]
https://source.cloud.google.com/results/invocations/902d4082-1598-44c6-9a65-bfc91ded39c3/targets

It's failing the same way for asyncio, gevent, and native.

```
+ cd /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/src/python/grpcio_testing
+ pip_install coverage==4.4 oauth2client==4.1.0 google-auth requests==2.14.2 googleapis-common-protos rsa==4.0
+ /usr/bin/env -i 'PATH=/Users/kbuilder/.rvm/gems/ruby-2.5.1/bin:/Users/kbuilder/.rvm/gems/ruby-2.5.1@global/bin:/Users/kbuilder/.rvm/rubies/ruby-2.5.1/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/CMake.app/Contents/bin:/Applications/Unity/Unity.app/MacOS:/Users/kbuilder/Library/Android/sdk/platform-tools:/Users/kbuilder/Library/Android/sdk/tools/bin:/Applications/apache-maven-3.5.4/bin:/usr/local/sbin:/Users/kbuilder/.rvm/bin' /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/bin/python3.8 -m pip install coverage==4.4 oauth2client==4.1.0 google-auth requests==2.14.2 googleapis-common-protos rsa==4.0
  ERROR: Command errored out with exit status 1:
   command: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/bin/python3.8 /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /Volumes/BuildData/tmpfs/tmp/pip-build-env-0a7q00pe/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/lib/python3.8/site-packages/pip/_internal/main.py", line 8, in <module>
      import locale
    File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/lib/python3.8/locale.py", line 16, in <module>
      import re
    File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/lib/python3.8/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/bin/python3.8 /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/py38_asyncio/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /Volumes/BuildData/tmpfs/tmp/pip-build-env-0a7q00pe/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

2020-09-29 14:04:40,268 FAILED: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_asyncio/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=53132, time=407.6sec]
2020-09-29 14:04:40,268 FAILED: Some tests failed
```

**Comment by lidizheng** [comment]
Duplicated with https://github.com/grpc/grpc/issues/24269. WIP fix at https://github.com/grpc/grpc/pull/24267.
