### ISSUE TITLE
Porting tooling python code to Python3

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#24359]
As Python2 hit EOL, we need to port our tooling script to run on Python3. This can be done by either making code portable on both or supporting it on Python3 only. This needs to be done because all infrastructures are moving forward to support Python3 only. Recent one is Kokoro MacOS/Catalina which installed Python3.8 as a default Python for users. ([log](https://sponge.corp.google.com/target?id=87f68114-a195-4727-abf6-da3180330f2b&target=grpc%2Fcore%2Fexperimental%2Fmacos%2Fadhoc%2Fgrpc_experiment_catalina&searchFor=))  We can work around this problem by staying with the old version of MacOS as much as we can but I expect more platforms are following this path so we need to address them before it's too late. There are ~110 python sources in tools directory.

Reference:
- [Porting Python 2 Code to Python 3](https://docs.python.org/3/howto/pyporting.html)

**Comment by gnossen** [comment]
I actually tried this while working on something else my first month on the team. I gave up after spending about five hours on it. I think this is probably a couple of solid days of effort and it's likely that there will be subsequent clean-up work since there are no compile errors for mistakes and not all workflows are run all the time.

**Comment by veblush** [comment]
It'd be good if we can make this done this year since PIP keeps saying this ;)

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**Comment by jtattermusch** [comment]
Just FTR, one random place where i ran into python3 incompatibility:

```
python3 tools/run_tests/task_runner.py -f artifact python manylinux2014 aarch64 cp38-cp38
START: Building targets.
PASSED: build_artifact.python_manylinux2014_aarch64_cp38-cp38 [time=547.6sec, retries=0:0]
Traceback (most recent call last):
  File "/usr/local/google/home/jtattermusch/github/grpc/tools/run_tests/task_runner.py", line 116, in <module>
    report_utils.render_junit_xml_report(resultset,
  File "/usr/local/google/home/jtattermusch/github/grpc/tools/run_tests/python_utils/report_utils.py", line 57, in render_junit_xml_report
    append_junit_xml_results(tree, resultset, suite_package, suite_name,
  File "/usr/local/google/home/jtattermusch/github/grpc/tools/run_tests/python_utils/report_utils.py", line 110, in append_junit_xml_results
    filtered_msg = _filter_msg(result.message, 'XML')
  File "/usr/local/google/home/jtattermusch/github/grpc/tools/run_tests/python_utils/report_utils.py", line 36, in _filter_msg
    msg.decode('UTF-8', 'ignore')))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by sergiitk** [comment]
All set here. We don't use python 2 anymore. Also removed code dependency on six.
