### ISSUE TITLE
Interop Cloud-to-Prod Tests (internal CI) fails

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#24375]
https://source.cloud.google.com/results/invocations/68684dd4-c8d4-4615-8506-2ea6c7ad74ac/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log

2020-10-08 14:06:56,925 WAITING: ETA 23.9 sec; 106 queued, 12 jobs running, 376 complete, 0 failed (load 12.00) next: cloud_to_prod_auth:dart:default:compute_engine_creds:tls @ 1.00 cpu
2020-10-08 14:06:57,179 /var/local/git/grpc-node/test/interop/interop_client.js:468
  client.unaryCall(arg, {credentials: creds}, function(err, resp) {
                   ^

ReferenceError: arg is not defined
    at Object.perRpcAuthTest [as run] (/var/local/git/grpc-node/test/interop/interop_client.js:468:20)
    at execute (/var/local/git/grpc-node/test/interop/interop_client.js:582:10)
    at runTest (/var/local/git/grpc-node/test/interop/interop_client.js:592:5)
    at Object.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:607:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

**Comment by karthikravis** [comment]
Hey Michael, would you happen to know about interop_client.js?
