### ISSUE TITLE
tools/interop_matrix/run_interop_matrix_tests.py needs to work with python3

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#24522]
The test script needs to work with python3; current it fails like this:

python3 tools/interop_matrix/run_interop_matrix_tests.py -l all --release v1.33.1
Traceback (most recent call last):
  File "tools/interop_matrix/run_interop_matrix_tests.py", line 38, in <module>
    import upload_test_results
  File "/usr/local/google/home/donnadionne/release/grpc/tools/run_tests/python_utils/upload_test_results.py", line 28, in <module>
    import big_query_utils
  File "/usr/local/google/home/donnadionne/release/grpc/tools/gcp/utils/big_query_utils.py", line 23, in <module>
    from apiclient import discovery
ImportError: cannot import name 'discovery' from 'apiclient' (/usr/local/google/home/donnadionne/.local/lib/python3.8/site-packages/apiclient/__init__.py)

**Comment by jtattermusch** [comment]
I suggest @gnossen take this one since it was his plan to make all our testing scripts python3 compatible.

@gnossen, can you confirm?

**Comment by gnossen** [comment]
Yes, I can take care of this.
