### ISSUE TITLE
[FLAKE] py37_gevent.test timeout

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#24596]
```
2020-10-28 19:28:03,239 ++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py37_gevent/bin/python
+ PYTHON=/var/local/git/grpc/py37_gevent/bin/python3.7
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py37_gevent/bin/python3.7 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_gevent
running test_gevent
Running       unit._dynamic_stubs_test.DynamicStubTest.test_grpc_tools_unimportable
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 50, in _wrapped
    fn()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 63, in _wrapped
    fn()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 119, in _test_grpc_tools_unimportable
    with _grpc_tools_unimportable():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 38, in _grpc_tools_unimportable
    raise unittest.SkipTest("Failed to make grpc_tools unimportable.")
unittest.case.SkipTest: Failed to make grpc_tools unimportable.

2020-10-28 19:28:03,239 TIMEOUT: py37_gevent.test.unit._dynamic_stubs_test.DynamicStubTest [pid=31420, time=304.3sec]
2020-10-28 19:28:03,240 FAILED: py37_gevent.test.unit._dynamic_stubs_test.DynamicStubTest
2020-10-28 19:28:03,308 FAILED: Some tests failed
```

**Comment by lidizheng** [comment]
It's a bit strange why the test runner refused to exit even the test case is skipped.
CC @gnossen

**Comment by markdroth** [comment]
Similar problem:

https://source.cloud.google.com/results/invocations/41fdd7cd-5a6a-4a6b-b9b9-0be4f22277ad/targets/github%2Fgrpc%2Frun_tests%2Fpython_macos_opt_gevent%2Fpy27_gevent.test.unit._dynamic_stubs_test.DynamicStubTest/tests

```
++ dirname /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/tools/run_tests/helper_scripts/run_python.sh
+ cd /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/tools/run_tests/helper_scripts/../../..
++ realpath py27_gevent/bin/python
+ PYTHON=/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/bin/python
++ pwd
+ ROOT=/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent
+ /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py27_gevent/bin/python /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/setup.py test_gevent
running test_gevent
Running       unit._dynamic_stubs_test.DynamicStubTest.test_grpc_tools_unimportable
```
