### ISSUE TITLE
Bazel build fails on Windows

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#24628]
Bazel build on Windows (KOKORO Win7) failed with the following error.

```
$ bazel build :gpr
INFO: Call stack for the definition of repository 'grpc_python_dependencies' which is a pip_import (rule definition at C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/io_bazel_rules_python/python/pip.bzl:42:14):
 - <builtin>
 - C:/cygwin64/home/builder/grpc/WORKSPACE:86:1
ERROR: An error occurred during the fetch of repository 'grpc_python_dependencies':
   pip_import failed:  (java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("python" C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/io_bazel_rules_python/tools/piptool.par --name grpc_python_dependencies --input C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/com_github_grpc_grpc/requirements.bazel.txt --output C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/grpc_python_dependencies/requirements.bzl --directory C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/grpc_python_dependencies): The system cannot find the file specified.
 (error: 2))
ERROR: no such package '@grpc_python_dependencies//': pip_import failed:  (java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("python" C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/io_bazel_rules_python/tools/piptool.par --name grpc_python_dependencies --input C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/com_github_grpc_grpc/requirements.bazel.txt --output C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/grpc_python_dependencies/requirements.bzl --directory C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/grpc_python_dependencies): The system cannot find the file specified.
 (error: 2))
ERROR: no such package '@grpc_python_dependencies//': pip_import failed:  (java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("python" C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/io_bazel_rules_python/tools/piptool.par --name grpc_python_dependencies --input C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/com_github_grpc_grpc/requirements.bazel.txt --output C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/grpc_python_dependencies/requirements.bzl --directory C:/cygwin64/home/builder/_bazel_kbuilder/iarwcrmk/external/grpc_python_dependencies): The system cannot find the file specified.
 (error: 2))
INFO: Elapsed time: 6.258s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

$ bazel --version
bazel 2.2.0
```

This error was gone by removing the very last section for Python of WORKSPACE.

```
load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")

pip_import(
    name = "grpc_python_dependencies",
    requirements = "@com_github_grpc_grpc//:requirements.bazel.txt",
)

load("@grpc_python_dependencies//:requirements.bzl", "pip_install")

pip_repositories()

pip_install()
```

**Comment by veblush** [comment]
Note that this issue happened on the VM with `kokoro-win7build-v11-prod-debug` image but it didn't with `kokoro-winserver2016-v2m-prod-debug` so it could be a kokoro image issue.

**Comment by jtattermusch** [comment]
As expressed before,  I think the problem is related to something with the python installation (could be one of : python2 missing, python3 missing, pip missing, pip being too old, some pip depednencies missing or sth like that). 

Looking at the internal history, the build has worked on kokoro Win7 workers until Sep 18 (at which point we switched to Win2016 workers).

Even if that's not the case, Windows 7 is now after end of support, so if the build doesn't work there, so be it https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

**Comment by devjgm** [comment]
FYI, I see this same problem when trying to build grpc with bazel 3.5.0 on my Windows Server 2019 Datacenter machine. If I delete the python rules from the WORKSPACE file as you suggested in the first comment, the build proceeds. 

If those python rules aren't needed, can they just be removed?

**Comment by danieldjewell** [comment]
I just ran into a related issue I think -- 

```
DEBUG: ~/.cache/bazel/_bazel_root/de9aa8b706e7ed29aab6297d1046aa79/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:                         Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.                                                  DEBUG: ~/.cache/bazel/_bazel_root/de9aa8b706e7ed29aab6297d1046aa79/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 3.7.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"]}                                                           DEBUG: ~/.cache/bazel/_bazel_root/de9aa8b706e7ed29aab6297d1046aa79/e
xternal/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:                         Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.                                                  DEBUG: ~/.cache/bazel/_bazel_root/de9aa8b706e7ed29aab6297d1046aa79/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_msan not using checked in configs; Bazel version 3.7.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"]}```

And then multiple errors from Python ... This is on Python 3.9 on Linux 

```no such package '@grpc_python_dependencies//': pip_import failed:  (Exception:    Traceback (most recent call last):
...
normalize_path(os.path.join(options.cache_dir, "http"))                                
File "/usr/lib/python3.9/posixpath.py", line 76, in join                                   
a = os.fspath(a)                                                                     
TypeError: expected str, bytes or os.PathLike object, not int
```

Strangely, it appears that Bazel is importing Pip v9?! (Or is that just the version of "Piptool"? I'll have to investigate. 

```/.cache/bazel/_bazel_root/de9aa8b706e7ed29aab6297d1046aa79/external/io_bazel_rules_python/tools/piptool.par/pypi__pip_9_0_3/pip/basecommand.py```

**Comment by pearcemc** [comment]
This does not appear to be Windows specific. I recently encountered similar on `Debian GNU/Linux rodete rodete (x86-64)`. Using fresh install of bazel, fresh clone of grpc.

```
cd grpc && bazel build :all
[...]
DEBUG: /usr/local/google/home/mcpearce/.cache/bazel/_bazel_mcpearce/61449c78262e0c91d92c9f2b9ee5529c/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_msan not using checked in configs; Bazel version 3.7.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"]}
ERROR: An error occurred during the fetch of repository 'grpc_python_dependencies':
   Traceback (most recent call last):
        File "/usr/local/google/home/mcpearce/.cache/bazel/_bazel_mcpearce/61449c78262e0c91d92c9f2b9ee5529c/external/io_bazel_rules_python/python/pip.bzl", line 40, column 13, in _pip_import_impl
                fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(python, ...)": No such file or directory
)
ERROR: no such package '@grpc_python_dependencies//': pip_import failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(python, ...)": No such file or directory
)
INFO: Elapsed time: 0.158s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

It is possible that this is an issue related to pip versioning; in particular may be worth checking py2 v py3 issues and whether grpc repo is implicitly assuming availability of py2.

**Comment by veblush** [comment]
@pearcemc Your case could be caused due to missing `/usr/bin/python` on your system. Since Python2 was deprecated, Linux distribution started removing python alias in favor of python3. You might be able to solve your issue by creating a symlink `/usr/bin/python` to your python3.

**Comment by pearcemc** [comment]
Indeed, this was the case and `ln -s /usr/bin/python3 /usr/bin/python` sorted it out.

**Comment by jbemmel** [comment]
Perhaps Bazel should be updated to refer to /usr/bin/python3 (since python2 isn't supported anyway)?
