### ISSUE TITLE
grpcio can't be installed on alpine

### ISSUE THREAD

**Issue by comtihon** [grpc/grpc#24722]
Hi,
I have:
```
grpcio==1.32.*
grpcio-tools==1.32.*
```
in my requirements and 
```
FROM python:3.7-alpine
...
RUN python setup.py install
```
in my [Dockerfile](https://github.com/comtihon/catcher/commit/210bcae8a50f0b1eb4bd2164aefca080d106e64c#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).

Around 6-7 days ago `pip install grpcio` stopped working and build started to fail. I had to move to Debian-python docker, but it increased my image size a lot.
First I noticed that it starts building from source, so I had to add gcc and g++ dep to it
```
RUN apk update \
  && apk add gcc g++
```
but even with it it fails after some (a bit long) time:
```
distutils.errors.CompileError: command 'gcc' failed with exit status 1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    extras={'compose': ["docker-compose==1.24.*"]}
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 721, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 766, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 693, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 719, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 904, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1172, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 140, in resume
    type, exc = map(pickle.loads, self._saved)
ModuleNotFoundError: No module named 'commands'
```

Is there a way to prevent C-compilation during the installation?

**Comment by veblush** [comment]
This seems like that docker image doesn't run python2 when running setup.py which relies on commands module which has been deprecated from python3. I guess that replacing commands modules with subprocess in setup.py could be a solution.

**Comment by gnossen** [comment]
@comtihon You also need to `apk add linux-headers`. Without that, both 1.31 and 1.32 fail. With it, both succeed.

**Comment by gnossen** [comment]
I can't reproduce this from `python:3.7-alpine` after running `apk add gcc g++ linux-headers` and `pip install grpcio==1.33.*`. Have you tried installing `linux-headers`. Based on this, I can't explain why your continuous build would have broken. That dependency is not new.

@comtihon Can you confirm that this fixes your build?

**Comment by comtihon** [comment]
confirm, it works with `linux-headers` added. Thanks!

**Comment by av1m** [comment]
Hello, this does not work on the latest version of python/grpcio.
When i run these commands : 

```bash
docker run -it --rm --entrypoint /bin/sh python:3.12-alpine
# apk add gcc g++ linux-headers
# pip install --upgrade pip setuptools wheel
# pip install grpcio==1.60.1
```

I got this : 

```bash
Collecting grpcio
  Downloading grpcio-1.60.1.tar.gz (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 21.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... |
```
And it runs (infinitely?) on the grpcio build wheel

**Comment by Timelessprod** [comment]
For me version 1.63 on python 3.11 Alpine is installing but it needs to do the whole compilation which is super slow. We'd need to get the pre built wheel of possible.

**Comment by mubashir2k17** [comment]
My trying to install `grpcio==1.64.1` on `python:3.11-alpine` docker base image. Updated and installed the following packages:
```
RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    g++ \
    libffi-dev \
    openssl-dev \
    libstdc++ \
    build-base \
    linux-headers \
    make \
    postgresql-dev \
    python3-dev
```
But grpcio takes forever....

**Comment by danyi1212** [comment]
Same here attempting to install on `python:3.10-alpine` or `python:3.12-alpine`

```docker
FROM python:3.10-alpine

WORKDIR /app

RUN apk update && apk upgrade && \
    apk add --no-cache g++ libc-dev build-base

RUN pip install --upgrade pip setuptools packaging && \
    pip install grpcio

CMD ["python", "-c", "print('Hello, World!')"]
```

It holds forever on 
```bash
#7 6.624 Building wheels for collected packages: grpcio
#7 6.624   Building wheel for grpcio (setup.py): started
```

I've added more details here - https://github.com/grpc/grpc/issues/22815#issuecomment-2661517877
