### ISSUE TITLE
FAILURE: macos/grpc_bazel_c_cpp_dbg & grpc_bazel_c_cpp_opt

### ISSUE THREAD

**Issue by veblush** [grpc/grpc#24738]
[grpc_bazel_c_cpp_dbg](https://source.cloud.google.com/results/invocations/f982f655-5065-4f0d-ab5d-01be24350dd0/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_bazel_c_cpp_dbg/log) & [grpc_bazel_c_cpp_opt](https://source.cloud.google.com/results/invocations/6d91d744-de54-4704-984a-89a828b35c2c/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_bazel_c_cpp_opt/log) are failing although all tests passed with the following error;

```
Executed 2584 out of 2584 tests: 2584 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build completed successfully, 13835 total actions
INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/e5461cab-5b05-4f20-be0d-d6e7ba8022ae
INFO: Build completed successfully, 13835 total actions
+ '[' true '!=' '' ']'
+ sleep 60
+ python ./tools/run_tests/python_utils/upload_rbe_results.py
Traceback (most recent call last):
  File "./tools/run_tests/python_utils/upload_rbe_results.py", line 167, in <module>
    resultstore_actions = _get_resultstore_data(api_key, invocation_id)
  File "./tools/run_tests/python_utils/upload_rbe_results.py", line 128, in _get_resultstore_data
    results = json.loads(urllib2.urlopen(req).read())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
```

**Comment by veblush** [comment]
This could be related with Mojave upgrade. When testing with adhoc machines, uploading the result was suppressed so this wasn't caught.

**Comment by veblush** [comment]
Fixed by the PR above.
