### ISSUE TITLE
The `grpcio-tools` Python distribution is missing an `install_requires` dependency of `grpc_tools.protoc`.

### ISSUE THREAD

**Issue by jsirois** [grpc/grpc#24746]
I've filled out the standard form below, but to get to the point more directly, the `grpcio-tools` Python distribution is missing a dependency declaration by inspection. Here the setuptools distribution is used (it provides both setuptools and pkg_resources top-level packages):
https://github.com/grpc/grpc/blob/cc956c8e85613df8b8bcb7c018fb54f91da66e6c/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L17
https://github.com/grpc/grpc/blob/cc956c8e85613df8b8bcb7c018fb54f91da66e6c/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L62
https://github.com/grpc/grpc/blob/cc956c8e85613df8b8bcb7c018fb54f91da66e6c/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L172

And here a dependency on setuptools is omitted:
https://github.com/grpc/grpc/blob/cc956c8e85613df8b8bcb7c018fb54f91da66e6c/tools/distrib/python/grpcio_tools/setup.py#L232-L235

Prior to this commit over in protobuf you were getting lucky and picking up your direct dependency indirectly: https://github.com/protocolbuffers/protobuf/commit/7daf0aa7b00261bc8e0a433c58e74083cd58ea43

### What version of gRPC and what language are you using?
N/A: Applies from at least grpcio-tools master tip back through version 1.17.1 - which is where I found the issue.

### What operating system (Linux, Windows,...) and version?
N/A

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python

### What did you do?
```
jsirois@gill ~ $ curl -sL https://github.com/pantsbuild/pex/releases/download/v2.1.21/pex > pex && chmod +x pex
jsirois@gill ~ $ ./pex --pre grpcio-tools -e grpc_tools.protoc -o grpcio_tools_protoc.pex
jsirois@gill ~ $ PEX_VERBOSE=1 ./grpcio_tools_protoc.pex 
pex: Found site-library: /usr/lib/python3.8/site-packages
pex: Tainted path element: /usr/lib/python3.8/site-packages
pex: Scrubbing from user site: /home/jsirois/.local/lib/python3.8/site-packages
pex: Scrubbing from site-packages: /usr/lib/python3.8/site-packages
pex: New sys.path: ['/home/jsirois/grpcio_tools_protoc.pex/.bootstrap', '/home/jsirois/grpcio_tools_protoc.pex', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload']
pex: Using cached /home/jsirois/.pex/installed_wheels/b45bf988a282a20ea2dac7c33624e89b34aac016/grpcio-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/5d71a2a9028bb8471445dcd6bb379fc8fd6c0765/grpcio_tools-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/6c5c3e98e66369747b78e6260718833d9bb70427/protobuf-3.14.0rc3-cp38-cp38-manylinux1_x86_64.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/0cb007434fc9c1d2ee600dbd964088b69f5d670a/six-1.15.0-py2.py3-none-any.whl
pex: Activating PEX virtual environment from ./grpcio_tools_protoc.pex: 15.4ms
/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/environment.py:402: PEXWarning: The `pkg_resources` package was loaded from a pex vendored version when declaring namespace packages defined by:

1. protobuf==3.14.0rc3 namespace packages:
  google

These distributions should fix their `install_requires` to include `setuptools`
pex: Bootstrap complete, performing final sys.path modifications...
pex: PYTHONPATH contains:
pex:     /home/jsirois/grpcio_tools_protoc.pex
pex:   * /usr/lib/python38.zip
pex:     /usr/lib/python3.8
pex:     /usr/lib/python3.8/lib-dynload
pex:     /home/jsirois/.pex/installed_wheels/01ea24f5c9496d111a828c96aeab889d47b9fcd9/grpcio_tools-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex:     /home/jsirois/.pex/installed_wheels/1a226b10b2a0608b56452a4006217d15e16c1193/grpcio-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex:     /home/jsirois/.pex/installed_wheels/44339c1e44a57967b53d9da247d22145d3d1e20d/protobuf-3.14.0rc3-cp38-cp38-manylinux1_x86_64.whl
pex:     /home/jsirois/.pex/installed_wheels/8730d16507db66e828c696ecc7cb785e557900bb/six-1.15.0-py2.py3-none-any.whl
pex:   * /home/jsirois/grpcio_tools_protoc.pex/.bootstrap
pex:   * - paths that do not exist or will be imported via zipimport
Traceback (most recent call last):
  File "/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/pex.py", line 446, in execute
  File "/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/pex.py", line 378, in _wrap_coverage
  File "/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/pex.py", line 409, in _wrap_profiling
  File "/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/pex.py", line 508, in _execute
  File "/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/pex.py", line 610, in execute_entry
  File "/home/jsirois/grpcio_tools_protoc.pex/.bootstrap/pex/pex.py", line 618, in execute_module
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jsirois/.pex/installed_wheels/01ea24f5c9496d111a828c96aeab889d47b9fcd9/grpcio_tools-1.33.2-cp38-cp38-manylinux2014_x86_64.whl/grpc_tools/protoc.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### What did you expect to see?
Note - I manually add grpcio-tools' missing but requiredsetuptools dependency here when building the PEX:
```
jsirois@gill ~ $ ./pex --pre grpcio-tools setuptools -e grpc_tools.protoc -o grpcio_tools_protoc.pex
jsirois@gill ~ $ PEX_VERBOSE=1 ./grpcio_tools_protoc.pex 
pex: Found site-library: /usr/lib/python3.8/site-packages
pex: Tainted path element: /usr/lib/python3.8/site-packages
pex: Scrubbing from user site: /home/jsirois/.local/lib/python3.8/site-packages
pex: Scrubbing from site-packages: /usr/lib/python3.8/site-packages
pex: New sys.path: ['/home/jsirois/grpcio_tools_protoc.pex/.bootstrap', '/home/jsirois/grpcio_tools_protoc.pex', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload']
pex: Using cached /home/jsirois/.pex/installed_wheels/b45bf988a282a20ea2dac7c33624e89b34aac016/grpcio-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/5d71a2a9028bb8471445dcd6bb379fc8fd6c0765/grpcio_tools-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/6c5c3e98e66369747b78e6260718833d9bb70427/protobuf-3.14.0rc3-cp38-cp38-manylinux1_x86_64.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/4eb9ecd3b42548b290828be29c99804e7f6bffe2/setuptools-50.3.2-py3-none-any.whl
pex: Using cached /home/jsirois/.pex/installed_wheels/0cb007434fc9c1d2ee600dbd964088b69f5d670a/six-1.15.0-py2.py3-none-any.whl
pex: Activating PEX virtual environment from ./grpcio_tools_protoc.pex: 32.8ms
pex: Bootstrap complete, performing final sys.path modifications...
pex: PYTHONPATH contains:
pex:     /home/jsirois/grpcio_tools_protoc.pex
pex:   * /usr/lib/python38.zip
pex:     /usr/lib/python3.8
pex:     /usr/lib/python3.8/lib-dynload
pex:     /home/jsirois/.pex/installed_wheels/01ea24f5c9496d111a828c96aeab889d47b9fcd9/grpcio_tools-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex:     /home/jsirois/.pex/installed_wheels/1a226b10b2a0608b56452a4006217d15e16c1193/grpcio-1.33.2-cp38-cp38-manylinux2014_x86_64.whl
pex:     /home/jsirois/.pex/installed_wheels/44339c1e44a57967b53d9da247d22145d3d1e20d/protobuf-3.14.0rc3-cp38-cp38-manylinux1_x86_64.whl
pex:     /home/jsirois/.pex/installed_wheels/8730d16507db66e828c696ecc7cb785e557900bb/six-1.15.0-py2.py3-none-any.whl
pex:     /home/jsirois/.pex/installed_wheels/fb7c7015f3c3c273de71dc21a13377cbc577f2f0/setuptools-50.3.2-py3-none-any.whl
pex:   * /home/jsirois/grpcio_tools_protoc.pex/.bootstrap
pex:   * - paths that do not exist or will be imported via zipimport
Missing input file.
```

### What did you see instead?
See "What did you do?".

### Anything else we should know about your project / environment?
No.

**Comment by lidizheng** [comment]
Good finding! Filed a PR https://github.com/grpc/grpc/pull/24752.
