### ISSUE TITLE
grpc __strdup() not found in pyton3.6-alpine arm

### ISSUE THREAD

**Issue by michaelaelise** [grpc/grpc#24808]
Hi,
When using google libraries that require grpc we are running into this error.

The environment is docker arm python3.6-alpine with ...
grpcio>=1.33.2
google-cloud-pubsub>=2.1.0
google-api-python-client>=1.12.5
google-auth>=1.23.0

In our dockerfile we are installing
```
FROM --platform=linux/arm/v7 python:3.6-alpine as basefirmwarebuilder
WORKDIR /tmp
RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
        cmake \
        curl \
        g++ \
        gcc \
        jpeg-dev \
        libffi-dev \
        libjpeg \
        make \
        musl-dev \
        postgresql-dev \
        python3-dev \
        tzdata \
        zlib \
        zlib-dev 

... later on
RUN pip3 install -r requirements.txt

```
and I even added `libc6-compat` and tried that.
also I added alpines `build-base` and `alpine-sdk` to try to cover all the bases. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/...", line 48, in <module>
    from ... import...
  File "/usr/local/lib/python3.6/site-packages/...", line 13, in <module>
    from google.cloud import pubsub_v1
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/types.py", line 36, in <module>
    from google.pubsub_v1.types import pubsub as pubsub_gapic_types
  File "/usr/local/lib/python3.6/site-packages/google/pubsub_v1/__init__.py", line 18, in <module>
    from .services.publisher import PublisherClient
  File "/usr/local/lib/python3.6/site-packages/google/pubsub_v1/services/publisher/__init__.py", line 18, in <module>
    from .client import PublisherClient
  File "/usr/local/lib/python3.6/site-packages/google/pubsub_v1/services/publisher/client.py", line 27, in <module>
    from google.api_core import gapic_v1  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/google/api_core/gapic_v1/__init__.py", line 18, in <module>
    from google.api_core.gapic_v1 import config
  File "/usr/local/lib/python3.6/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/usr/local/lib/python3.6/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: Error relocating /usr/local/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-arm-linux-gnueabihf.so: __strdup: symbol not found
```

This works fine in x64 alpine. So far we are only having issue in the arm version.

Any idea how to resolve this?

**Comment by michaelaelise** [comment]
When I run with the command I get a compile time error instead of a runtime error.
`RUN pip3 install --global-option=build_ext --global-option="--inplace" -r requirements.txt`

```
#25 4696.     creating None
#25 4696.     creating None/tmp
#25 4696.     creating None/tmp/tmpgqkltwkq
#25 4696.     gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.6m -c /tmp/tmpgqkltwkq/a.c -o None/tmp/tmpgqkltwkq/a.o
#25 4696.     Traceback (most recent call last):
#25 4696.       File "/usr/local/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
#25 4696.         extra_postargs)
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
#25 4696.         _classic_spawn(self, command)
#25 4696.       File "/usr/local/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
#25 4696.         spawn(cmd, dry_run=self.dry_run)
#25 4696.       File "/usr/local/lib/python3.6/distutils/spawn.py", line 36, in spawn
#25 4696.         _spawn_posix(cmd, search_path, dry_run=dry_run)
#25 4696.       File "/usr/local/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
#25 4696.         % (cmd, exit_status))
#25 4696.     distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
#25 4696.     
#25 4696.     During handling of the above exception, another exception occurred:
#25 4696.     
#25 4696.     Traceback (most recent call last):
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
#25 4696.         build_ext.build_ext.build_extensions(self)
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
#25 4696.         self._build_extensions_serial()
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
#25 4696.         self.build_extension(ext)
#25 4696.       File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
#25 4696.         _build_ext.build_extension(self, ext)
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
#25 4696.         depends=ext.depends)
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
#25 4696.         _compile_single_file, objects)
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
#25 4696.         return self._map_async(func, iterable, mapstar, chunksize).get()
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
#25 4696.         raise self._value
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
#25 4696.         result = (True, func(*args, **kwds))
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
#25 4696.         return list(map(*args))
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
#25 4696.         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/commands.py", line 248, in new_compile
#25 4696.         pp_opts)
#25 4696.       File "/usr/local/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
#25 4696.         raise CompileError(msg)
#25 4696.     distutils.errors.CompileError: command 'gcc' failed with exit status 1
#25 4696.     
#25 4696.     During handling of the above exception, another exception occurred:
#25 4696.     
#25 4696.     Traceback (most recent call last):
#25 4696.       File "<string>", line 1, in <module>
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/setup.py", line 477, in <module>
#25 4696.         cmdclass=COMMAND_CLASS,
#25 4696.       File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
#25 4696.         return distutils.core.setup(**attrs)
#25 4696.       File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
#25 4696.         dist.run_commands()
#25 4696.       File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
#25 4696.         self.run_command(cmd)
#25 4696.       File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
#25 4696.         cmd_obj.run()
#25 4696.       File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
#25 4696.         _build_ext.run(self)
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
#25 4696.         self.build_extensions()
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/commands.py", line 269, in build_extensions
#25 4696.         "Failed `build_ext` step:\n{}".format(formatted_exception))
#25 4696.     commands.CommandError: Failed `build_ext` step:
#25 4696.     Traceback (most recent call last):
#25 4696.       File "/usr/local/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
#25 4696.         extra_postargs)
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
#25 4696.         _classic_spawn(self, command)
#25 4696.       File "/usr/local/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
#25 4696.         spawn(cmd, dry_run=self.dry_run)
#25 4696.       File "/usr/local/lib/python3.6/distutils/spawn.py", line 36, in spawn
#25 4696.         _spawn_posix(cmd, search_path, dry_run=dry_run)
#25 4696.       File "/usr/local/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
#25 4696.         % (cmd, exit_status))
#25 4696.     distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
#25 4696.     
#25 4696.     During handling of the above exception, another exception occurred:
#25 4696.     
#25 4696.     Traceback (most recent call last):
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
#25 4696.         build_ext.build_ext.build_extensions(self)
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
#25 4696.         self._build_extensions_serial()
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
#25 4696.         self.build_extension(ext)
#25 4696.       File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
#25 4696.         _build_ext.build_extension(self, ext)
#25 4696.       File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
#25 4696.         depends=ext.depends)
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
#25 4696.         _compile_single_file, objects)
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
#25 4696.         return self._map_async(func, iterable, mapstar, chunksize).get()
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
#25 4696.         raise self._value
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
#25 4696.         result = (True, func(*args, **kwds))
#25 4696.       File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
#25 4696.         return list(map(*args))
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
#25 4696.         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
#25 4696.       File "/tmp/pip-install-26a1afcl/grpcio/src/python/grpcio/commands.py", line 248, in new_compile
#25 4696.         pp_opts)
#25 4696.       File "/usr/local/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
#25 4696.         raise CompileError(msg)
#25 4696.     distutils.errors.CompileError: command 'gcc' failed with exit status 1
#25 4696.     
#25 4696.     ----------------------------------------
#25 4696. ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-26a1afcl/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-26a1afcl/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext --inplace install --record /tmp/pip-record-w3vsk0v2/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/grpcio 
```

**Comment by michaelaelise** [comment]
I found `https://pkgs.alpinelinux.org/package/edge/community/armhf/py3-grpcio` and also `https://pkgs.alpinelinux.org/package/edge/community/armhf/py3-google-api-core`
But the issue I see is that in versions of python-pubsub starting at 1.4.3 there is like...
```
dependencies = [
    # google-api-core[grpc] 1.17.0 causes problems, thus restricting its
    # version until the issue gets fixed.
    # https://github.com/googleapis/python-pubsub/issues/74
    "google-api-core[grpc] >= 1.14.0, < 1.17.0",
    "grpc-google-iam-v1 >= 0.12.3, < 0.13dev",
    'enum34; python_version < "3.4"',
]
````

So it says right there not to use v1.17.0

**Comment by michaelaelise** [comment]
I switched to `FROM --platform=linux/arm/v7 python:3.8-alpine` and added some deps
```
RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
        cmake \
        curl \
        g++ \
        gcc \
        jpeg-dev \
        libffi-dev \
        libjpeg \
        make \
        musl-dev \
        musl \
        postgresql-dev \
        python3-dev \
        tzdata \
        zlib \
        zlib-dev \
        libc6-compat \
        libc-dev \
        alpine-sdk \
        build-base \
        linux-headers \
        cython \
        c-ares-dev \
        gdbm \
        libffi
```

Now it works.  So nevermind on the question.
