### ISSUE TITLE
build fails while installing in coral dev board (linux-aarch64)

### ISSUE THREAD

**Issue by Bhanuchander210** [grpc/grpc#24958]
Got build error message while trying to install `google-cloud-pubsub` in **Coral developer board**.

### Environment details

```
$ cat /etc/os-release
PRETTY_NAME="Mendel GNU/Linux 5 (Eagle)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.ai/"
SUPPORT_URL="https://coral.ai/"
BUG_REPORT_URL="https://coral.ai/"
VERSION_CODENAME="eagle"
```
- Python version: 3.7.3
- pip version: 20.3.1
- grpcio-1.34.0

### Build Error

```
Collecting google-cloud-pubsub
  Downloading google_cloud_pubsub-2.2.0-py2.py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 1.3 MB/s 
Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.22.2 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-cloud-pubsub) (1.23.0)
Requirement already satisfied: libcst>=0.3.10 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-cloud-pubsub) (0.3.15)
Requirement already satisfied: proto-plus>=1.7.1 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-cloud-pubsub) (1.13.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (2.25.0)
Requirement already satisfied: setuptools>=34.0.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (49.6.0)
Requirement already satisfied: pytz in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (2020.4)
Requirement already satisfied: six>=1.13.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.15.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.52.0)
Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.23.0)
Requirement already satisfied: protobuf>=3.12.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (3.14.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (2.25.0)
Requirement already satisfied: setuptools>=34.0.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (49.6.0)
Requirement already satisfied: pytz in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (2020.4)
Requirement already satisfied: six>=1.13.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.15.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.52.0)
Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.23.0)
Requirement already satisfied: protobuf>=3.12.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (3.14.0)
Requirement already satisfied: setuptools>=34.0.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (49.6.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (4.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (0.2.8)
Requirement already satisfied: six>=1.13.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.15.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (4.6)
Requirement already satisfied: protobuf>=3.12.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (3.14.0)
Collecting grpc-google-iam-v1<0.13dev,>=0.12.3
  Downloading grpc-google-iam-v1-0.12.3.tar.gz (13 kB)
Requirement already satisfied: googleapis-common-protos[grpc]<2.0.0dev,>=1.5.2 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from grpc-google-iam-v1<0.13dev,>=0.12.3->google-cloud-pubsub) (1.52.0)
Requirement already satisfied: protobuf>=3.12.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (3.14.0)
Collecting grpcio<2.0dev,>=1.29.0
  Downloading grpcio-1.34.0.tar.gz (21.0 MB)
     |████████████████████████████████| 21.0 MB 3.0 MB/s 
Requirement already satisfied: six>=1.13.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.15.0)
Requirement already satisfied: typing-inspect>=0.4.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from libcst>=0.3.10->google-cloud-pubsub) (0.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.2 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from libcst>=0.3.10->google-cloud-pubsub) (3.7.4.3)
Requirement already satisfied: pyyaml>=5.2 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from libcst>=0.3.10->google-cloud-pubsub) (5.3.1)
Requirement already satisfied: protobuf>=3.12.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (3.14.0)
Requirement already satisfied: six>=1.13.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.15.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (2020.12.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (3.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.2->google-cloud-pubsub) (0.4.8)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from typing-inspect>=0.4.0->libcst>=0.3.10->google-cloud-pubsub) (0.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.2 in /home/mendel/.virtualenvs/cv/lib/python3.7/site-packages (from libcst>=0.3.10->google-cloud-pubsub) (3.7.4.3)
Building wheels for collected packages: grpc-google-iam-v1, grpcio
  Building wheel for grpc-google-iam-v1 (setup.py) ... done
  Created wheel for grpc-google-iam-v1: filename=grpc_google_iam_v1-0.12.3-py3-none-any.whl size=18501 sha256=3d680cc10426102f5642d2e0b5ae9d641b5e43931a28092f2e36ca4b885183ce
  Stored in directory: /tmp/pip-ephem-wheel-cache-qyo_e82n/wheels/b9/ee/67/2e444183030cb8d31ce8b34cee34a7afdbd3ba5959ea846380
  Building wheel for grpcio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/mendel/.virtualenvs/cv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_s_lg1kx/grpcio_b6a2e5aada6c4dd48e9313537b1d3658/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_s_lg1kx/grpcio_b6a2e5aada6c4dd48e9313537b1d3658/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tbs2kbmj
       cwd: /tmp/pip-install-_s_lg1kx/grpcio_b6a2e5aada6c4dd48e9313537b1d3658/
  Complete output (1256 lines):
  ASM Builds for BoringSSL currently not supported on: linux-aarch64
  Found cython-generated files...
  running bdist_wheel
  running build
  running build_py
  running build_project_metadata
  creating python_build
  creating python_build/lib.linux-aarch64-3.7
  creating python_build/lib.linux-aarch64-3.7/grpc
  copying src/python/grpcio/grpc/_utilities.py -> python_build/lib.linux-aarch64-3.7/grpc
  copying src/python/grpcio/grpc/_channel.py -> python_build/lib.linux-aarch64-3.7/grpc
  copying src/python/grpcio/grpc/_runtime_protos.py -> python_build/lib.linux-aarch64-3.7/grpc
  copying src/python/grpcio/grpc/_compression.py -> python_build/lib.linux-aarch64-3.7/grpc
  copying src/python/grpcio/grpc/_plugin_wrapping.py -> python_build/lib.linux-aarch64-3.7/grpc
  copying src/python/grpcio/grpc/_simple_stubs.py -> python_build/lib.linux-aarch64-3.7/grpc

----------------------------
Lot of lines.. there..! :(
...................................
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-_s_lg1kx/grpcio_b6a2e5aada6c4dd48e9313537b1d3658/src/python/grpcio/commands.py", line 267, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/mendel/.virtualenvs/cv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "/tmp/pip-install-_s_lg1kx/grpcio_b6a2e5aada6c4dd48e9313537b1d3658/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
      _compile_single_file, objects)
    File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
      return self._map_async(func, iterable, mapstar, chunksize).get()
    File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
      raise self._value
    File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
      result = (True, func(*args, **kwds))
    File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
      return list(map(*args))
    File "/tmp/pip-install-_s_lg1kx/grpcio_b6a2e5aada6c4dd48e9313537b1d3658/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Successfully built grpc-google-iam-v1
Failed to build grpcio
```

### similar issues
- [https://github.com/googleapis/python-pubsub/issues/251](https://github.com/googleapis/python-pubsub/issues/251)
- [https://github.com/grpc/grpc/issues/23373](https://github.com/grpc/grpc/issues/23373)
- [https://github.com/grpc/grpc/issues/21283](https://github.com/grpc/grpc/issues/21283)

### Query

-  Opened this issue to verify that, Is there any lower versions can be build in [Coral dev board](https://coral.ai/docs/dev-board/get-started/) for `google-cloud-pubsub` installation ?

**Comment by Bhanuchander210** [comment]
Actually it works with lower version.. 1.29.0

**Comment by cobbben** [comment]
So did the following env / library details work to install google-cloud-pubsub on the coral dev board? @Bhanuchander210 

Python version: 3.7.3
pip version: 20.3.1
grpcio: 1.29.0

What version of setuptools did you use?

**Comment by Bhanuchander210** [comment]
@cobbben 

setuptools: **51.0.0**

(It may be useful ) I have added the wheel file and all libraries list...

google drive link for wheel file : [grpcio-1.29.0-cp37-cp37m-linux_aarch64.whl](https://drive.google.com/file/d/1wE7kK25OxfbzoVDRD3yPf6N9yRKKc29t/view?usp=sharing)

Libraries list:
```
(mypython) mendel@jumping-zebra:~$ pip freeze --all
cachetools==4.1.1
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
coverage==5.3
cryptography==3.3
Cython==0.29.21
Flask==1.0.2
google-api-core==1.23.0
google-api-python-client==1.12.8
google-auth==1.23.0
google-auth-httplib2==0.0.4
google-cloud-core==1.4.4
google-cloud-pubsub==2.2.0
google-cloud-storage==1.33.0
google-crc32c==1.0.0
google-resumable-media==1.1.0
googleapis-common-protos==1.52.0
grpc-google-iam-v1==0.12.3
grpcio @ file:///external/nms_face_authentication/grpcio-1.29.0-cp37-cp37m-linux_aarch64.whl
httplib2==0.18.1
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
joblib==0.17.0
libcst==0.3.15
MarkupSafe==1.1.1
mypy-extensions==0.4.3
numpy==1.19.4
paho-mqtt==1.5.1
pandas==1.1.4
Pillow==8.0.1
pip==20.3.1
proto-plus==1.13.0
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycoral @ https://github.com/google-coral/pycoral/releases/download/release-frogfish/pycoral-1.0.0-cp37-cp37m-linux_aarch64.whl
pycparser==2.20
PyJWT==1.7.1
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
requests==2.25.0
rsa==4.6
scikit-learn==0.23.2
scipy==1.5.4
setuptools==51.0.0
six==1.15.0
tflite-runtime @ https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp37-cp37m-linux_aarch64.whl
threadpoolctl==2.1.0
typing-extensions==3.7.4.3
typing-inspect==0.6.0
uritemplate==3.0.1
urllib3==1.26.2
Werkzeug==1.0.1
wheel==0.35.1
```
