### ISSUE TITLE
FLAKE: github/grpc/run_tests/csharp_windows_dbg_native_default_coreclr/csharp.Grpc.IntegrationTesting.InteropClientServerTest[default]

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#25004]
https://source.cloud.google.com/results/invocations/df1f5885-d3ee-4c13-a9cd-8a92690660e1/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_dbg_native_default_coreclr%2Fcsharp.Grpc.IntegrationTesting.InteropClientServerTest/tests

```
1) Error : Grpc.IntegrationTesting.InteropClientServerTest.CustomMetadata
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Grpc.IntegrationTesting.InteropClient.RunCustomMetadataAsync(TestServiceClient client) in T:\src\github\grpc\workspace_csharp_windows_dbg_native_default_coreclr\src\csharp\Grpc.IntegrationTesting\InteropClient.cs:line 523
   at Grpc.IntegrationTesting.InteropClientServerTest.CustomMetadata() in T:\src\github\grpc\workspace_csharp_windows_dbg_native_default_coreclr\src\csharp\Grpc.IntegrationTesting\InteropClientServerTest.cs:line 125
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncInvocationRegion.cs:line 113
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 96
```

**Comment by apolcyn** [comment]
Seen again in https://source.cloud.google.com/results/invocations/47e9957b-343f-487b-8ce4-7b9898246036/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_linux_dbg_native%2Fcsharp.Grpc.IntegrationTesting.InteropClientServerTest/tests

```
Errors, Failures and Warnings

1) Failed : Grpc.IntegrationTesting.InteropClientServerTest.CustomMetadata
  String lengths are both 27. Strings differ at index 0.
  Expected: "test_initial_metadata_value"
  But was:  "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
  -----------^
  at Grpc.IntegrationTesting.InteropClient.RunCustomMetadataAsync (Grpc.Testing.TestService+TestServiceClient client) [0x00000] in <3415ff1710ad4cd7a8e8591d164d9fc6>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in <533173d24dae460899d2b10975534bb0>:0

Run Settings
    Number of Test Workers: 1
    Work Directory: /var/local/git/grpc
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 13, Passed: 12, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 1, Errors: 0, Invalid: 0
  Start time: 2021-07-09 05:00:32Z
    End time: 2021-07-09 05:00:49Z
    Duration: 17.173 seconds
```

**Comment by jtattermusch** [comment]
No failures in the last 100 days.
