### ISSUE TITLE
iOS binary size diff failing: TypeError: load_pem_private_key() missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25053]
Example failure: https://source.cloud.google.com/results/invocations/78961fd2-a99c-410e-87ae-2c7d2943ac95/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size/log

```
*****************STATIC******************
  New size                      Old size
 3,260,431      Total (=)      3,260,431

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
20,192,207      Total (<)     20,192,376

 No significant differences in binary sizes


Traceback (most recent call last):
  File "tools/profiling/ios_bin/binary_size.py", line 148, in <module>
    check_on_pr.check_on_pr('Binary Size', '```\n%s\n```' % text)
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 136, in check_on_pr
    'summary': summary,
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 88, in _call
    'Authorization': 'Bearer %s' % _access_token(),
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 58, in _access_token
    'Authorization': 'Bearer %s' % _jwt_token().decode('ASCII'),
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 47, in _jwt_token
    algorithm='RS256')
  File "/Users/kbuilder/Library/Python/3.7/lib/python/site-packages/jwt/api_jwt.py", line 63, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "/Users/kbuilder/Library/Python/3.7/lib/python/site-packages/jwt/api_jws.py", line 110, in encode
    key = alg_obj.prepare_key(key)
  File "/Users/kbuilder/Library/Python/3.7/lib/python/site-packages/jwt/algorithms.py", line 242, in prepare_key
    key = load_pem_private_key(key, password=None)
TypeError: load_pem_private_key() missing 1 required positional argument: 'backend'


[ID: 9110196] Build finished after 2205 secs, exit value: 1

```

**Comment by stanley-cheung** [comment]
Looks like this has been failing since Dec 22nd: https://fusion.corp.google.com/projectanalysis/history/KOKORO/prod:grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size
