### ISSUE TITLE
CONSISTENTLY FAILING: grpc/core/pull_request/macos/grpc_ios_binary_size[default]

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#25097]
https://source.cloud.google.com/results/invocations/055f42f8-06fa-4f2c-8de9-164677902c32/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size/log

```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 3,261,678      Total (<)      3,261,918

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
20,211,930      Total (<)     20,212,355

 No significant differences in binary sizes


Traceback (most recent call last):
  File "tools/profiling/ios_bin/binary_size.py", line 148, in <module>
    check_on_pr.check_on_pr('Binary Size', '```\n%s\n```' % text)
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 136, in check_on_pr
    'summary': summary,
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 88, in _call
    'Authorization': 'Bearer %s' % _access_token(),
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 58, in _access_token
    'Authorization': 'Bearer %s' % _jwt_token().decode('ASCII'),
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 47, in _jwt_token
    algorithm='RS256')
  File "/Users/kbuilder/Library/Python/3.7/lib/python/site-packages/jwt/api_jwt.py", line 63, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "/Users/kbuilder/Library/Python/3.7/lib/python/site-packages/jwt/api_jws.py", line 110, in encode
    key = alg_obj.prepare_key(key)
  File "/Users/kbuilder/Library/Python/3.7/lib/python/site-packages/jwt/algorithms.py", line 242, in prepare_key
    key = load_pem_private_key(key, password=None)
TypeError: load_pem_private_key() missing 1 required positional argument: 'backend'


[ID: 3101439] Build finished after 2215 secs, exit value: 1


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[10:30:27] Collecting build artifacts from build VM
Build script failed with exit code: 1
```

**Comment by yulin-liang** [comment]
#25094 fixed this issue.
