### ISSUE TITLE
cloud_to_cloud:java:java_server:large_unary:alts Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#25149]
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:624)
	at io.grpc.testing.integration.AbstractInteropTest.largeUnary(AbstractInteropTest.java:447)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:228)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:207)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:65)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/0:0:0:0:0:0:0:1:32770
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:251)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

https://source.cloud.google.com/results/invocations/5489b668-8415-4e15-8d68-608623408c05/log

**Comment by voidzcy** [comment]
Why is this linked with the python xDS test client change?

**Comment by voidzcy** [comment]
Seems to be caused by https://github.com/grpc/grpc-java/pull/7799.

**Comment by gnossen** [comment]
@voidzcy That is where the failure was observed. But, since it was a java-only failure, I determined that it was unrelated.

**Comment by YifeiZhuang** [comment]
Regression caused by #7799, reverted in #7805 and tests look green.
