### ISSUE TITLE
pip install tensorflow on aarch64

### ISSUE THREAD

**Issue by zazeje** [grpc/grpc#25205]
i want to install tensorflow 2.4.0 on aarch64 platform
Processing /tensorflow-2.4.0-cp37-cp37m-linux_aarch64.whl
[11:09:13.248]Requirement already satisfied: protobuf>=3.9.2 in /archiconda3/lib/python3.7/site-packages (from tensorflow==2.4.0) (3.14.0)
[11:09:42.014]Requirement already satisfied: wheel>=0.26 in /archiconda3/lib/python3.7/site-packages (from tensorflow==2.4.0) (0.32.1)
[11:09:42.441]Collecting astunparse==1.6.3
[11:09:42.523]  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[11:09:42.709]Collecting gast==0.3.3
[11:09:42.796]  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d6/84/759f5dd23fec8ba71952d97bcc7e2c9d7d63bdc582421f3cd4be845f0c98/gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
[11:09:42.872]Collecting absl-py>=0.7.0
[11:09:42.975]  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/58/0aa6fb779dc69cfc811df3398fcbeaeefbf18561b6e36b185df0782781cc/absl_py-0.11.0-py3-none-any.whl (127 kB)
[11:09:43.066]Collecting google-pasta>=0.1.8
[11:09:43.160]  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl (57 kB)
[11:09:43.224]Collecting grpcio>=1.8.6
[11:09:44.272]  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/81/5e/168a7fa23a025beed6b7daa0981ace55e394a136db3082faed7d6cba4556/grpcio-1.34.1.tar.gz (21.1 MB)
[11:10:30.046]     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–                   | 8.0 MB 276 kB/s eta 0:00:    
.....
ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 21.1 MB 56 kB/s 
[11:11:29.107]    ERROR: Command errored out with exit status 1:
[11:11:29.118]     command: /archiconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f0c67re3/grpcio_a6bf68a58434427d8f48e4f7dce7345c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f0c67re3/grpcio_a6bf68a58434427d8f48e4f7dce7345c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jta1regk
[11:11:29.152]         cwd: /tmp/pip-install-f0c67re3/grpcio_a6bf68a58434427d8f48e4f7dce7345c/
[11:11:29.164]    Complete output (11 lines):
[11:11:29.164]    Traceback (most recent call last):
[11:11:29.165]      File "<string>", line 1, in <module>
[11:11:29.173]      File "/tmp/pip-install-f0c67re3/grpcio_a6bf68a58434427d8f48e4f7dce7345c/setup.py", line 229, in <module>
[11:11:29.178]        if check_linker_need_libatomic():
[11:11:29.184]      File "/tmp/pip-install-f0c67re3/grpcio_a6bf68a58434427d8f48e4f7dce7345c/setup.py", line 179, in check_linker_need_libatomic
[11:11:29.195]        stderr=PIPE)
[11:11:29.196]      File "/archiconda3/lib/python3.7/subprocess.py", line 769, in __init__
[11:11:29.208]        restore_signals, start_new_session)
[11:11:29.208]      File "/archiconda3/lib/python3.7/subprocess.py", line 1516, in _execute_child
[11:11:29.218]        raise child_exception_type(errno_num, err_msg, err_filename)
[11:11:29.218]    FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'
[11:11:29.229]    ----------------------------------------
[11:11:29.238]ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I think C++ is not installed on the development board aarch64++.
isn't it?
how to fix this problem?
thanks!!!
![12](https://user-images.githubusercontent.com/26483646/105122897-08cb1d00-5b12-11eb-80d9-2c6e8d257aa9.jpg)

**Comment by drfloob** [comment]
Hi @zazeje. This doesn't look like a gRPC bug. My guess is that you haven't installed a sufficient build environment, and a quick web search for `No such file or directory: 'c++': 'c++'` brings up a few solutions.

In the future, please follow the instructions on the new issue form and use the channels mentioned below to ask questions. For reference, new issues begin with:

> PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!
> 
> For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc
> 
> For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
>

**Comment by zazeje** [comment]
thanks,i know.but how to install C + + and other tools into Aarch64 development board?



At 2021-01-21 01:22:51, "Adam J Heller" <notifications@github.com> wrote:

Hi @zazeje. This doesn't look like a gRPC bug. My guess is that you haven't installed a sufficient build environment, and a quick web search for No such file or directory: 'c++': 'c++' brings up a few solutions.

In the future, please follow the instructions on the new issue form and use the channels mentioned below to ask questions. For reference, new issues begin with:

PLEASE DO NOT POST A QUESTION HERE. This form is for bug reports and feature requests ONLY!

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io
