### ISSUE TITLE
LoadError with Ruby 3.0 and grpc gem

### ISSUE THREAD

**Issue by rfeldman1-chwy** [grpc/grpc#25222]
### What version of gRPC and what language are you using?
```
gem info --local grpc

*** LOCAL GEMS ***

grpc (1.35.0)
    Platform: universal-darwin
    Author: gRPC Authors
    Homepage: https://github.com/google/grpc/tree/master/src/ruby
    License: Apache-2.0
    Installed at: /Users/<me>/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0

    GRPC system in Ruby
```

### What operating system (Linux, Windows,...) and version?
MacOS 10.15.7

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
```

### What did you do?
Clean install of ruby 3.0, then install pry, grpc, and grpc-tools gems
```
ᐅ rbenv uninstall 3.0.0
ᐅ rbenv install 3.0.0
ᐅ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
ᐅ gem install pry
... pry installed ...

ᐅ gem install grpc
Fetching grpc-1.35.0-universal-darwin.gem
Fetching google-protobuf-3.14.0.gem
Fetching googleapis-common-protos-types-1.0.5.gem
Building native extensions. This could take a while...
Successfully installed google-protobuf-3.14.0
Successfully installed googleapis-common-protos-types-1.0.5
Successfully installed grpc-1.35.0-universal-darwin
Parsing documentation for google-protobuf-3.14.0
Installing ri documentation for google-protobuf-3.14.0
Parsing documentation for googleapis-common-protos-types-1.0.5
Installing ri documentation for googleapis-common-protos-types-1.0.5
Parsing documentation for grpc-1.35.0-universal-darwin
Installing ri documentation for grpc-1.35.0-universal-darwin
Done installing documentation for google-protobuf, googleapis-common-protos-types, grpc after 0 seconds
3 gems installed
ᐅ gem install grpc-tools
Fetching grpc-tools-1.35.0.gem
Successfully installed grpc-tools-1.35.0
Parsing documentation for grpc-tools-1.35.0
Installing ri documentation for grpc-tools-1.35.0
Done installing documentation for grpc-tools after 0 seconds
1 gem installed
ᐅ pry
[1] pry(main)> require 'grpc'
LoadError: cannot load such file -- grpc/grpc_c
from <internal:/Users/<me>/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
Caused by LoadError: cannot load such file -- grpc
from <internal:/Users/<me>/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
[2] pry(main)>
```

### What did you expect to see?
grpc gem loaded

### What did you see instead?
The following error
```
LoadError: cannot load such file -- grpc/grpc_c
```
### Anything else we should know about your project / environment?
No

**Comment by bruno-** [comment]
If it helps anything: running the above steps works on Linux (same grpc version, same ruby version as above).
Btw. I can also reproduce the problem on a mac.

**Comment by thiensubs** [comment]
Same error with me here:

```console
<internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- grpc/grpc_c (LoadError)
	from <internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
	from /Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grpc-1.36.0-universal-darwin/src/ruby/lib/grpc/grpc.rb:22:in `<top (required)>'
	from /Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grpc-1.36.0-universal-darwin/src/ruby/lib/grpc.rb:19:in `require_relative'
	from /Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grpc-1.36.0-universal-darwin/src/ruby/lib/grpc.rb:19:in `<top (required)>'
	from <internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
<internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- grpc (LoadError)
	from <internal:/Users/thiensubs/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

**Comment by Raou1d** [comment]
Same error here on MacOS 11.1 with Ruby 3.0.0 and grpc 1.36.0

**Comment by nitsujri** [comment]
Also errors on MacOS 11.2.1 with Ruby 3.0.0 and grpc 1.36.0.
