### ISSUE TITLE
Flake: cloud_to_cloud:java:go_server:ping_pong:alts

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#25236]
```
2021-01-21 10:38:27,816 Running test ping_pong
Exception in thread "main" java.lang.AssertionError: Timed out waiting for response
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at io.grpc.testing.integration.AbstractInteropTest.pingPong(AbstractInteropTest.java:792)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:264)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:207)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:65)

2021-01-21 10:38:27,816 FAILED: cloud_to_cloud:java:go_server:ping_pong:alts [ret=1, pid=5494, time=7.7sec]
```

https://source.cloud.google.com/results/invocations/c44ed048-298f-4889-937b-90ed180346b5/log

**Comment by yashykt** [comment]
Closing since we decided to move CI test flakes to buganizer
