### ISSUE TITLE
Segmentation fault in Ruby tests

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2535]
[This log](https://grpc-testing.appspot.com/job/gRPC_pull_requests/1053/config=opt,language=ruby,platform=linux/console) is an example of it happening in `GRPC::RpcServer#stopped? is true after a running server is stopped`. Relevant info:

```
-- Control frame information -----------------------------------------------
c:0019 p:---- s:0078 e:000077 CFUNC  :instance_exec
c:0018 p:0013 s:0075 e:000074 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:182
c:0017 p:0028 s:0070 e:000069 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:506
c:0016 p:0122 s:0066 e:000064 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:532
c:0015 p:0010 s:0057 e:000056 BLOCK  /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522 [FINISH]
c:0014 p:---- s:0054 e:000053 CFUNC  :map
c:0013 p:0093 s:0051 e:000050 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522
c:0012 p:0011 s:0043 e:000042 BLOCK  /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115 [FINISH]
c:0011 p:---- s:0040 e:000039 CFUNC  :map
c:0010 p:0009 s:0037 e:000036 BLOCK  /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115
c:0009 p:0048 s:0035 e:000034 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627
c:0008 p:0009 s:0031 e:000030 BLOCK  /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114
c:0007 p:0017 s:0028 e:000027 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77
c:0006 p:0018 s:0024 e:000023 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113
c:0005 p:0022 s:0020 e:000019 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89
c:0004 p:0088 s:0015 e:000014 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73
c:0003 p:0024 s:0008 e:000007 METHOD /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41
c:0002 p:0023 s:0004 E:002158 EVAL   /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/exe/rspec:4 [FINISH]
c:0001 p:0000 s:0002 E:000118 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:532:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:506:in `run_after_context_hooks'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
```

**Comment by tbetbetbe** [comment]
Closing, has not been updated in several months.
