### ISSUE TITLE
[FLAKE] RBE pulling image timeout

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#25369]
```
ERROR: An error occurred during the fetch of repository 'rbe_default':
   Traceback (most recent call last):
	File "/tmpfs/tmp/bazel/external/bazel_toolchains/rules/rbe_repo.bzl", line 452, column 19, in _rbe_autoconfig_impl
		pull_image(ctx, docker_tool_path, image_name)
	File "/tmpfs/tmp/bazel/external/bazel_toolchains/rules/rbe_repo/container.bzl", line 137, column 23, in pull_image
		print_exec_results("pull image", result, fail_on_error = True)
	File "/tmpfs/tmp/bazel/external/bazel_toolchains/rules/rbe_repo/util.bzl", line 191, column 13, in print_exec_results
		fail("Failed to run:" + prefix + ":" + exec_result.stderr)
Error in fail: Failed to run:pull image:Timed out
```

https://source.cloud.google.com/results/invocations/8e2118a6-f136-43a6-b40f-dea5a0cc5891/log

This error is on the very top of the log, needs to download the full log to see it.

**Comment by yashykt** [comment]
Closing since we decided not to track test flakes on github
