### ISSUE TITLE
Multi-thread support for python asyncio gRPC clients

### ISSUE THREAD

**Issue by RonanMcCarthy** [grpc/grpc#25364]
This issue was created at the request of @lidizheng on [a stackoverflow post](https://stackoverflow.com/questions/65945944/multi-thread-support-for-python-asyncio-grpc-clients).

### What version of gRPC and what language are you using?

* Python version: `3.8.6`
* grpcio version: `1.35.0`

### What operating system (Linux, Windows,...) and version?

Issue observed on multiple macOS versions as well as within Ubuntu based docker containers. We have been testing with the `python:3.8.6-slim-buster` image.

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python version: `3.8.6`

### What did you do?

1. Create a gRPC server and launch it
2. Create multiple (two is enough) workers on separate threads
3. Have each thread make calls to the server simultaneously

### What did you expect to see?

No issies.

### What did you see instead?

A stream of the following errors:

```
2021-01-27 09:33:56,937 ERROR [asyncio] [thread_0] Exception in callback PollerCompletionQueue._handle_events()()
handle: )()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
2021-01-27 09:33:56,937 ERROR [asyncio] [thread_1] Exception in callback PollerCompletionQueue._handle_events()()
handle: )()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
``` 

### Anything else we should know about your project / environment?

* The API we are using is stream-stream
* We use interceptors to insert headers into the requests

**Comment by lidizheng** [comment]
I'm able to reproduce this error. I found the `BlockingIOError ` log appears in Python 3.9 for unary-unary but not 3.7, but both passes. But multi-threading with multiple loops doesn't work stream-stream.

CC @dpcollins-google

**Comment by stupidchen** [comment]
I'm able to reproduce this error too. Any update?

**Comment by wti806** [comment]
Seeing this error on the gRPC client when invoking RPCs in multiple threads.

**Comment by wuxibin89** [comment]
@lidizheng Multithread asyncio client works fine, but the message is very annoying. Is there any work on this?

**Comment by lidizheng** [comment]
@wuxibin89 We do want to improve the UX of the API. Can you help to create a new issue to describe the problem you are seeing?

**Comment by jdix531** [comment]
I hit this as well, and the code is in a library I'm consuming so the workaround isn't as helpful as one might hope. I might try to implement it for them in the meantime.

**Comment by wuxibin89** [comment]
> @wuxibin89 We do want to improve the UX of the API. Can you help to create a new issue to describe the problem you are seeing?

@lidizheng My problem is very much like @RonanMcCarthy  describe above. I'm using grpc-python to build a small distributed system. Each node is an actor with two RPC threads:
- server thread: an grpc asyncio server receiving message from other nodes simultaneously.
- client thread: multiple grpc asyncio clients sending message to other nodes simultaneously.

When running, grpc works fine and message passes as expected. But grpc clients keep printing message below and mess up my log.
```
2022-04-08 19:38:59,086,86 ERROR [base_events.py:default_exception_handler:1707] Exception in callback PollerCompletionQueue._handle_events(<_UnixSelecto...e debug=False>)()
handle: <Handle PollerCompletionQueue._handle_events(<_UnixSelecto...e debug=False>)()>
Traceback (most recent call last):
  File "/home/xibin.wxb/miniconda3/envs/secretflow/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by RaiAmanRai** [comment]
Hi, getting the same error. Any updates on this one ?

**Comment by kkroening** [comment]
FWIW, this is still an issue as of grpcio 1.51.1.

I wonder if the [Caveats](https://grpc.github.io/grpc/python/grpc_asyncio.html#caveats) section of the document should be updated to reflect this. Current explanation:

> gRPC Async API objects may only be used on the thread on which they were created. AsyncIO doesn’t provide thread safety for most of its APIs.

But because of this issue, would it be accurate to say that only one gRPC async API objects can be used _per process_, because this issue seems to happen even if you use independent client/transport/channel objects for each thread. It's as though there's some sort of singleton in the background that the seemingly independent gRPC async API objects are fighting over behind the scenes.

**Comment by skykit-karlkroening** [comment]
FWIW, here's a fairly minimal example demonstrating the issue (using Google's auto-generated Datastore client library - `pip install google-cloud-datastore`):
```python
import asyncio
import threading
from google.cloud import datastore_v1

PROJECT_ID = 'fixme'
QUERY_KIND = '__Stat_Kind__'
QUERY_LIMIT = 10

THREAD_COUNT = 2  # Two threads is all it takes to reproduce the issue.


async def _work(thread_id: int) -> None:
    """Performs async work using the Datastore async gRPC client library.

    If desired, swap out the implementation of this method with some other gRPC work to
    make the example more generic.

    Note:
        The actual output value doesn't matter; just print something to prove that
        we did the RPC.
    """
    client = datastore_v1.DatastoreAsyncClient()
    query = datastore_v1.Query(
        kind=[datastore_v1.KindExpression(name=QUERY_KIND)],
        limit=QUERY_LIMIT,
    )
    response = await client.run_query(
        request={
            'project_id': PROJECT_ID,
            'query': query,
        }
    )
    print(f'thread {thread_id}: {len(response.batch.entity_results)}')


def _run(thread_id: int) -> None:
    asyncio.run(_work(thread_id))


def _main() -> None:
    threads = [threading.Thread(target=_run, args=(i,)) for i in range(THREAD_COUNT)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()


if __name__ == '__main__':
    _main()
```
(If desired, change the `_work` method to make the example more generic)

**Comment by ashleystendel** [comment]
Hey! Any idea if this will be fixed in an upcoming releaseÉ

**Comment by davidelkoby7** [comment]
Getting these errors too when using multithreding :/
Any luck with trying to solve this?

**Comment by jluatroblox** [comment]
Ignoring this error is one thing, but will these cause any other side effect? Please please help fix this. It seems to be very dumb to have this sort of problem from gRPC.

**Comment by vhaldemar** [comment]
Hey! I also had this problem. I was able to solve it by making only one event loop for all grpc.aio calls, and by remaking my server as a non-async grpc entity.

**Comment by abellee** [comment]
so this problem won't be fixed?

**Comment by Eric-WK** [comment]
facing this issue as well on grpc using multiple threads. Any updates?

**Comment by kidar2** [comment]
the same issue, any updates?

**Comment by eigen2017** [comment]
hit this too.

when this grpc client:
https://github.com/apache/rocketmq-clients/tree/master/python
integrate with:
fastapi + uvicorn,

the uvloop will be explode

**Comment by niehongxu116** [comment]
the same issue, It seems that the task is being processed normally, but these exception logs are mixed into my logs.  Any updates?

python version 3.9
grpcio version 1.70.0

**Comment by aiguofer** [comment]
We recently switched to asyncio but have some background jobs that run in a ThreadPoolExecutor and we started running into this.

We thought creating a channel and stub for each method call might solve it but alas, we're still hitting this :( It does seem that requests complete successfully though.

**Comment by meacial** [comment]
You can change the way Python creates subprocesses. On Unix systems, the default method is fork, but it doesn't work well with multithreading. You can use 
```python
multiprocessing.set_start_method("spawn", force=True) 
```
to switch to the "spawn" method.

**Comment by chandra-siri** [comment]
Hi @sreenithi , @asheshvidyut 

we're also seeing this issue , filed b/474606210
