### ISSUE TITLE
[FLAKE] macOS tests failed with go_sdk download failure

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#25392]
```
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/io_bazel_rules_go/go/private/sdk.bzl", line 51, column 16, in _go_download_sdk_impl
		_remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/io_bazel_rules_go/go/private/sdk.bzl", line 121, column 21, in _remote_sdk
		ctx.download(
Error in download: java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/external/go_sdk/go_sdk.tar.gz: Read timed out
```

https://source.cloud.google.com/results/invocations/8dd7309c-e556-45b7-b89e-3d59dd6a0122/targets

**Comment by yashykt** [comment]
Closing since we decided to move infra test failures to buganizer
