### ISSUE TITLE
grpc.aio.ServicerContext.peer() raises UnicodeDecodeError (seems like it's trying to decode garbage)

### ISSUE THREAD

**Issue by jimmbelll** [grpc/grpc#25400]
### What version of gRPC and what language are you using?
1.34.1   grpc.__version__ 

### What operating system (Linux, Windows,...) and version?
system='Windows', 
node='...', release='10', 
version='10.0.19041', 
machine='AMD64', 
processor='AMD64 Family 21 Model 1 Stepping 2, AuthenticAMD'

via python platform.uname()

### What runtime / compiler are you using (e.g. python version or version of gcc)
CPython 3.7.3
('v3.7.3:ef4ec6ed12', 'Mar 25 2019 21:26:53')

### What did you do?
Simple server calls from client over IPv6. Client is at [::1].

Fails for some period of time **after booting my machine.** Eventually it starts working.

### What did you expect to see?
c.peer() to return '[::1]:54321'  or something similar with random client port number.

### What did you see instead?
Traceback (most recent call last):
  File "[my-call-site]", line 177, in MyFunction
    peer = c.peer()
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 221, in grpc._cython.cygrpc._ServicerContext.peer
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte

Random errors, different each time suggest garbage input to decode.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 0: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 2: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 0: invalid start byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

### Anything else we should know about your project / environment?
insecure_channel()

Unfortunately, neither python's pdb nor trace lets me look at peer()'s internals.

**Comment by jimmbelll** [comment]
Should have said, "... neither python's pdb nor trace lets me peer into peer."

**Comment by swgr424** [comment]
I believe the root cause is here:
https://github.com/grpc/grpc/blob/4c40ee3f78bafcada42b8ac30570a6a327759ace/src/core/lib/iomgr/tcp_windows.cc#L525

You shouldn't use memset() to zero-initialize the grpc_tcp instance created using the new operator, because one of its member (peer_string) is a std::string. The memset() will mess up with the inner structure of std::string, causing the `tcp->peer_string = peer_string;` below to have unexpected behavior.
