### ISSUE TITLE
Bazel Macos Dbg flake - ERROR: java.io.IOException: Error getting access token for service account: 400 Bad Request

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25432]
log snippet:

```
Port server started successfully
++ uuidgen
++ tr '[:upper:]' '[:lower:]'
+ BAZEL_INVOCATION_ID=56b7ea34-3893-4630-939a-3df3ca8bf25a
+ echo 56b7ea34-3893-4630-939a-3df3ca8bf25a
+ tools/bazel --bazelrc=tools/remote_build/mac.bazelrc test --invocation_id=56b7ea34-3893-4630-939a-3df3ca8bf25a --workspace_status_command=tools/remote_build/workspace_status_kokoro.sh --google_credentials=/tmpfs/src/gfile/GrpcTesting-d0eeee2db331.json --config=dbg -- //test/...
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 3.7.1 will be used instead of system-wide bazel installation.
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 56b7ea34-3893-4630-939a-3df3ca8bf25a
ERROR: java.io.IOException: Error getting access token for service account: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:432)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:145)
	at com.google.auth.Credentials.blockingGetToCallback(Credentials.java:112)
	at com.google.auth.Credentials$1.run(Credentials.java:98)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:690)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:133)
	at build.bazel.remote.execution.v2.CapabilitiesGrpc$CapabilitiesBlockingStub.getCapabilities(CapabilitiesGrpc.java:227)
	at com.google.devtools.build.lib.remote.RemoteServerCapabilities.lambda$get$0(RemoteServerCapabilities.java:77)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:237)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:115)
	at com.google.devtools.build.lib.remote.RemoteServerCapabilities.get(RemoteServerCapabilities.java:77)
	at com.google.devtools.build.lib.remote.RemoteModule.verifyServerCapabilities(RemoteModule.java:174)
	at com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:437)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:388)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:235)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:546)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:611)
	at io.grpc.Context$1.run(Context.java:605)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:429)
	... 21 more

ERROR: Failed to query remote execution capabilities: Error getting access token for service account: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."}
INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/56b7ea34-3893-4630-939a-3df3ca8bf25a
+ FAILED=true
+ '[' '' '!=' '' ']'
+ '[' true '!=' '' ']'
+ exit 1
```

from https://source.cloud.google.com/results/invocations/3a072063-25e8-4fb6-9fa1-e895f2b9f08e/log (bazel macos dbg)

seen in PR: https://github.com/grpc/grpc/pull/25398

**Comment by jtattermusch** [comment]
Interesting, this looks like a one-off auth issue. Have we seen it just once or there's multiple occurences?

**Comment by jtattermusch** [comment]
The only recent occurrence I found on master is https://source.cloud.google.com/results/invocations/1f2d6666-a48e-4788-b8bc-034a44a95480/log (so this issue seems quite rare).

**Comment by jtattermusch** [comment]
Since this flake seems rare, I'm going to close. If we are ever to reopen this, let's file an internal bug instead (we're going to track test flakiness in buganizer going forward).
