### ISSUE TITLE
Failure: iOS Binary Size Diff - TypeError: '>=' not supported between instances of 'KeyError' and 'int'

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25431]
```


Traceback (most recent call last):
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 64, in _access_token
    'token': resp.json()['token'],
KeyError: 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/profiling/ios_bin/binary_size.py", line 148, in <module>
    check_on_pr.check_on_pr('Binary Size', '```\n%s\n```' % text)
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 136, in check_on_pr
    'summary': summary,
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 88, in _call
    'Authorization': 'Bearer %s' % _access_token(),
  File "tools/profiling/ios_bin/../../run_tests/python_utils/check_on_pr.py", line 69, in _access_token
    traceback.print_exc(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 337, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'KeyError' and 'int'
```

Seen in https://github.com/grpc/grpc/pull/25406

**Comment by dennycd** [comment]
turns ont this is already fixed via https://github.com/grpc/grpc/pull/25743
