### ISSUE TITLE
C++ service.server is nullptr causing crashes on the server

### ISSUE THREAD

**Issue by kiwidoggie** [grpc/grpc#25583]
### What version of gRPC and what language are you using?
1.36.x compiled from source

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04.5 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
clang version 6.0.1 (compiled from source)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Here are the files I am using attempting to get working. The server starts, but then when the callback is called, service->server is nullptr, causing a crash on this line: https://github.com/kiwidoggie/mira-project/blob/develop/daemon/src/Rpc/Protos/FileManager.grpc.pb.cpp#L208

Initialization: https://github.com/kiwidoggie/mira-project/blob/develop/daemon/src/Rpc/Manager.cpp#L19

https://github.com/kiwidoggie/mira-project/blob/develop/daemon/src/Rpc/FileManagerImpl.hpp
https://github.com/kiwidoggie/mira-project/blob/develop/daemon/src/Rpc/Protos/FileManager.grpc.pb.h
https://github.com/kiwidoggie/mira-project/blob/develop/daemon/src/Rpc/Protos/FileManager.grpc.pb.cpp

### What did you expect to see?
It not to crash, to actually call my callback.

### What did you see instead?

Crashes that are below:

```
D0227 08:20:47.972236988   30491 ev_posix.cc:173]            Using polling engine: epollex
D0227 08:20:47.972431415   30491 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0227 08:20:47.972459767   30491 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0227 08:20:47.972474765   30491 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0227 08:20:47.972489502   30491 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0227 08:20:47.972504399   30491 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0227 08:20:47.972521991   30491 dns_resolver_ares.cc:491]   Using ares dns resolver
D0227 08:20:47.972576411   30491 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0227 08:20:47.972597390   30491 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0227 08:20:47.972613029   30491 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0227 08:20:47.972626083   30491 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0227 08:20:47.972638636   30491 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
I0227 08:20:47.973052547   30491 server_builder.cc:325]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0227 08:20:47.973291065   30491 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I0227 08:20:47.973891199   30491 server_builder.cc:325]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
```

![image](https://user-images.githubusercontent.com/9152262/109382629-7b0fe980-7896-11eb-9bf0-2a9c0f14cd5e.png)

If I continue, I get from asan:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==16018==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x5555556d9bea bp 0x7ffff1bfa710 sp 0x7ffff1bfa6a0 T6)
==16018==The signal is caused by a READ memory access.
==16018==Hint: address points to the zero page.
    #0 0x5555556d9be9 in Mira::Rpc::FileManager::FileManagerService::Service::Service()::$_0::operator()(Mira::Rpc::FileManager::FileManagerService::Service*, grpc::ServerContext*, Mira::Rpc::FileManager::EchoRequest const*, Mira::Rpc::FileManager::EmptyReply*) const /home/kuser/mira-project/daemon/src/Rpc/Protos/FileManager.grpc.pb.cpp:209:38
    #1 0x5555556d9a9b in std::_Function_handler<grpc::Status (Mira::Rpc::FileManager::FileManagerService::Service*, grpc::ServerContext*, Mira::Rpc::FileManager::EchoRequest const*, Mira::Rpc::FileManager::EmptyReply*), Mira::Rpc::FileManager::FileManagerService::Service::EmptyReply()::$_0>::_M_invoke(std::_Any_data const&, Mira::Rpc::FileManager::FileManagerService::Service*&&, grpc::ServerContext*&&, Mira::Rpc::FileManager::EchoRequest const*&&, Mira::Rpc::FileManager::EmptyReply*&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/std_function.h:301:9
    #2 0x5555556fe678 in std::function<grpc::Status (Mira::Rpc::FileManager::FileManagerService::Service*, grpc::ServerContext*, Mira::Rpc::FileManager::EchoRequest const*, Mira::Rpc::FileManager::EmptyReply*)>::operator()(Mira::Rpc::FileManager::FileManagerService::Service*, grpc::ServerContext*, Mira::Rpc::FileManager::EchoRequest const*, Mira::Rpc::FileManager::EmptyReply*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/std_function.h:706:14
    #3 0x5555556fe5c1 in grpc::internal::RpcMethodHandler<Mira::Rpc::FileManager::FileManagerService::Service, Mira::Rpc::FileManager::EchoRequest, Mira::Rpc::FileManager::EmptyReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}::operator()() const /home/kuser/.local/include/grpcpp/impl/codegen/method_handler.h:112:16
    #4 0x5555556fe21f in grpc::Status grpc::internal::CatchingFunctionHandler<grpc::internal::RpcMethodHandler<Mira::Rpc::FileManager::FileManagerService::Service, Mira::Rpc::FileManager::EchoRequest, Mira::Rpc::FileManager::EmptyReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc::internal::RpcMethodHandler<Mira::Rpc::FileManager::FileManagerService::Service, Mira::Rpc::FileManager::EchoRequest, Mira::Rpc::FileManager::EmptyReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&) /home/kuser/.local/include/grpcpp/impl/codegen/method_handler.h:42:12
    #5 0x5555556fdfea in grpc::internal::RpcMethodHandler<Mira::Rpc::FileManager::FileManagerService::Service, Mira::Rpc::FileManager::EchoRequest, Mira::Rpc::FileManager::EmptyReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) /home/kuser/.local/include/grpcpp/impl/codegen/method_handler.h:111:16
    #6 0x5555558db9cd in grpc::Server::SyncRequest::CallData::ContinueRunAfterInterception() /home/kuser/grpc/src/cpp/server/server_cc.cc:489
    #7 0x5555558db7e8 in grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks> const&, bool) /home/kuser/grpc/src/cpp/server/server_cc.cc:476
    #8 0x5555558dbe93 in grpc::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) /home/kuser/grpc/src/cpp/server/server_cc.cc:823
    #9 0x5555558f0976 in grpc::ThreadManager::MainWorkLoop() /home/kuser/grpc/src/cpp/thread_manager/thread_manager.cc:213
    #10 0x5555558efeec in grpc::ThreadManager::WorkerThread::Run() /home/kuser/grpc/src/cpp/thread_manager/thread_manager.cc:43
    #11 0x5555558efd87 in operator() /home/kuser/grpc/src/cpp/thread_manager/thread_manager.cc:35
    #12 0x5555558efd87 in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::{lambda(void*)#1}::operator()(void*) const (/home/kuser/mira-project/daemon/x64/Debug/MiraDaemon.elf+0x39bd87)
    #13 0x5555558efda7 in _FUN /home/kuser/grpc/src/cpp/thread_manager/thread_manager.cc:35
    #14 0x5555558efda7 in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::{lambda(void*)#1}::_FUN(void*) (/home/kuser/mira-project/daemon/x64/Debug/MiraDaemon.elf+0x39bda7)
    #15 0x555555ccf6c7 in operator() /home/kuser/grpc/src/core/lib/gprpp/thd_posix.cc:140
    #16 0x555555ccf6c7 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::operator()(void*) const (/home/kuser/mira-project/daemon/x64/Debug/MiraDaemon.elf+0x77b6c7)
    #17 0x555555ccf70c in _FUN /home/kuser/grpc/src/core/lib/gprpp/thd_posix.cc:145
    #18 0x555555ccf70c in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::_FUN(void*) (/home/kuser/mira-project/daemon/x64/Debug/MiraDaemon.elf+0x77b70c)
    #19 0x5555556a37ce in __asan::AsanThread::ThreadStart(unsigned long, __sanitizer::atomic_uintptr_t*) (/home/kuser/mira-project/daemon/x64/Debug/MiraDaemon.elf+0x14f7ce)
    #20 0x7ffff7bbd6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #21 0x7ffff697da3e in clone (/lib/x86_64-linux-gnu/libc.so.6+0x121a3e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/kuser/mira-project/daemon/src/Rpc/Protos/FileManager.grpc.pb.cpp:209:38 in Mira::Rpc::FileManager::FileManagerService::Service::Service()::$_0::operator()(Mira::Rpc::FileManager::FileManagerService::Service*, grpc::ServerContext*, Mira::Rpc::FileManager::EchoRequest const*, Mira::Rpc::FileManager::EmptyReply*) const
Thread T6 (grpcpp_sync_ser) created by T0 here:
    #0 0x5555555eed70 in pthread_create (/home/kuser/mira-project/daemon/x64/Debug/MiraDaemon.elf+0x9ad70)
    #1 0x555555ccfa20 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) /home/kuser/grpc/src/core/lib/gprpp/thd_posix.cc:108
    #2 0x555555ccfc46 in grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) /home/kuser/grpc/src/core/lib/gprpp/thd_posix.cc:186
    #3 0x5555558efe40 in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*) /home/kuser/grpc/src/cpp/thread_manager/thread_manager.cc:33
    #4 0x5555558f068c in grpc::ThreadManager::Initialize() /home/kuser/grpc/src/cpp/thread_manager/thread_manager.cc:143
    #5 0x5555558dc260 in grpc::Server::SyncRequestThreadManager::Start() /home/kuser/grpc/src/cpp/server/server_cc.cc:876
    #6 0x5555558d6876 in grpc::Server::Start(grpc::ServerCompletionQueue**, unsigned long) /home/kuser/grpc/src/cpp/server/server_cc.cc:1219
    #7 0x5555558c73d3 in grpc::ServerBuilder::BuildAndStart() /home/kuser/grpc/src/cpp/server/server_builder.cc:424
    #8 0x5555556d5b0e in Mira::Rpc::Manager::Manager() /home/kuser/mira-project/daemon/src/Rpc/Manager.cpp:30:31
    #9 0x5555556d48eb in void __gnu_cxx::new_allocator<Mira::Rpc::Manager>::construct<Mira::Rpc::Manager>(Mira::Rpc::Manager*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/ext/new_allocator.h:136:23
    #10 0x5555556d46b7 in void std::allocator_traits<std::allocator<Mira::Rpc::Manager> >::construct<Mira::Rpc::Manager>(std::allocator<Mira::Rpc::Manager>&, Mira::Rpc::Manager*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/alloc_traits.h:475:8
    #11 0x5555556d4458 in std::_Sp_counted_ptr_inplace<Mira::Rpc::Manager, std::allocator<Mira::Rpc::Manager>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<>(std::allocator<Mira::Rpc::Manager>) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr_base.h:526:4
    #12 0x5555556d4256 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Mira::Rpc::Manager, std::allocator<Mira::Rpc::Manager>>(std::_Sp_make_shared_tag, Mira::Rpc::Manager*, std::allocator<Mira::Rpc::Manager> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr_base.h:637:18
    #13 0x5555556d4185 in std::__shared_ptr<Mira::Rpc::Manager, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Mira::Rpc::Manager>>(std::_Sp_make_shared_tag, std::allocator<Mira::Rpc::Manager> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr_base.h:1294:14
    #14 0x5555556d4147 in std::shared_ptr<Mira::Rpc::Manager>::shared_ptr<std::allocator<Mira::Rpc::Manager>>(std::_Sp_make_shared_tag, std::allocator<Mira::Rpc::Manager> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr.h:344:4
    #15 0x5555556d40cb in std::shared_ptr<Mira::Rpc::Manager> std::allocate_shared<Mira::Rpc::Manager, std::allocator<Mira::Rpc::Manager>>(std::allocator<Mira::Rpc::Manager> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr.h:690:14
    #16 0x5555556d2d4f in std::shared_ptr<Mira::Rpc::Manager> std::make_shared<Mira::Rpc::Manager>() /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr.h:706:14
    #17 0x5555556d2833 in Mira::Daemon::OnLoad() /home/kuser/mira-project/daemon/src/Daemon.cpp:44:24
    #18 0x5555556d57fc in main /home/kuser/mira-project/daemon/src/Entry.cpp:22:20
    #19 0x7ffff687db96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

==16018==ABORTING
```

### Anything else we should know about your project / environment?

This build configuration is using the default setup, grpc and all required modules were compiled with cmake with: make ../.. -DCMAKE_BUILD_TYPE=Debug -DgRPC_ABSL_PROVIDER=module -DgRPC_CARES_PROVIDER=module -DgRPC_PROTOBUF_PROVIDER=module -DgRPC_RE2_PROVIDER=module -DgRPC_SSL_PROVIDER=module -DgRPC_ZLIB_PROVIDER=module

**Comment by kiwidoggie** [comment]
Update: This is a regression, I built 1.35.0 instead of 1.36.0 and it works 100% fine.

**Comment by donnadionne** [comment]
Can this be tested against the latest grpc version and see if it's still an issue?

**Comment by kiwidoggie** [comment]
I will have to give it a try at another time. You can close this issue for now.
