### ISSUE TITLE
Documentation for plain SSL using C#?

### ISSUE THREAD

**Issue by tdhintz** [grpc/grpc#25658]
I want to create a TLS connection to a service with no authentication and I can't find an example.

           ` Channel = new Channel("localhost:443", new SslCredentials());`

Results in:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at LicClient.LicenseGRpcClientChannel..ctor()
   at LicClient.LicenseGRpcInterface..ctor()
   at LicClient.LicenseGrpcClient.get_Interface()

```

**Comment by tdhintz** [comment]
https://github.com/grpc/grpc/issues/8978
