### ISSUE TITLE
[Flake] py38_gevent.test.unit._dynamic_stubs_test.DynamicStubTest

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#25675]
```
+ /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/py38_gevent/bin/python3.8 /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/setup.py test_gevent
running test_gevent
Running       unit._dynamic_stubs_test.DynamicStubTest.test_grpc_tools_unimportable
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 50, in _wrapped
    fn()
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 63, in _wrapped
    fn()
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 119, in _test_grpc_tools_unimportable
    with _grpc_tools_unimportable():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_gevent/src/python/grpcio_tests/tests/unit/_dynamic_stubs_test.py", line 38, in _grpc_tools_unimportable
    raise unittest.SkipTest("Failed to make grpc_tools unimportable.")
unittest.case.SkipTest: Failed to make grpc_tools unimportable.
```

https://source.cloud.google.com/results/invocations/ce4f9f1e-7fe1-4ebd-8ebf-3a65b3f96283/targets/github%2Fgrpc%2Frun_tests%2Fpython_macos_opt_gevent%2Fpy38_gevent.test.unit._dynamic_stubs_test.DynamicStubTest/tests

**Comment by lidizheng** [comment]
Another instance of this flake:

https://source.cloud.google.com/results/invocations/73e125c2-4aec-4273-a919-15d3e232919b/targets/github%2Fgrpc%2Frun_tests%2Fpython_macos_opt_gevent%2Fpy38_gevent.test.unit._dynamic_stubs_test.DynamicStubTest/tests

It's on macOS.
