### ISSUE TITLE
node-gyp rebuild error on CircleCI containers

### ISSUE THREAD

**Issue by aymericbeaumet** [grpc/grpc#2596]
I encounter the following error when `npm install grpc@0.10` on the CircleCI containers:

```
$ npm install grpc@0.10
-
> grpc@0.10.0 install /home/ubuntu/backend/node_modules/grpc
> node-gyp rebuild

make: Entering directory `/home/ubuntu/backend/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
  CXX(target) Release/obj.target/grpc/ext/channel.o
  CXX(target) Release/obj.target/grpc/ext/completion_queue_async_worker.o
../ext/completion_queue_async_worker.cc: In member function ‘virtual void grpc::node::CompletionQueueAsyncWorker::Execute()’:
../ext/completion_queue_async_worker.cc:65:60: error: could not convert ‘gpr_inf_future’ from ‘gpr_timespec (*)(gpr_clock_type)’ to ‘gpr_timespec’
make: *** [Release/obj.target/grpc/ext/completion_queue_async_worker.o] Error 1
make: Leaving directory `/home/ubuntu/backend/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.14.28-031428-generic
gyp ERR! command "node" "/home/ubuntu/nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/backend/node_modules/grpc
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 3.14.28-031428-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.33/bin/npm" "i" "grpc"
npm ERR! node v0.10.33
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.10.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/backend/npm-debug.log
```

uname: `Linux box404 3.14.28-031428-generic #201501081937 SMP Thu Jan 8 19:39:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
grpc lib commit: `d1408e71636f7ec74839a9bcff0429fb7e2caeb0` (git clone, make, make install...)

**Comment by murgatroid99** [comment]
It looks to me like you have an older version of the gRPC C core than what the Node library requires. You should try reinstalling that.

**Comment by aymericbeaumet** [comment]
That was it, thanks @murgatroid99
