### ISSUE TITLE
[Flake][C#][Windows] CallCancellationTest

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#26023]
https://source.cloud.google.com/results/invocations/53d16cce-a264-4daf-93d2-1e1b8304a264/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_opt_native%2Fcsharp.Grpc.Core.Tests.CallCancellationTest/tests

```
NUnitLite 3.10.1 (.NET Framework 4.5)
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601.65536
  CLR Version: 4.0.30319.42000

Test Files
    T:/src/github/grpc/workspace_csharp_windows_opt_native/src/csharp/Grpc.Core.Tests/bin/Release/net45/Grpc.Core.Tests.exe

Test Filters
    Test: Grpc.Core.Tests.CallCancellationTest

=> Grpc.Core.Tests.CallCancellationTest.CanDisposeDefaultCancellationRegistration
D0416 18:08:26.015625 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "T:\src\github\grpc\workspace_csharp_windows_opt_native\src\csharp\Grpc.Core.Tests\bin\Release\net45\grpc_csharp_ext.x64.dll"
D0416 18:08:26.093750 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
=> Grpc.Core.Tests.CallCancellationTest.ClientStreamingCall_CancelAfterBegin
W0416 18:08:26.359375 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.ClientStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()
=> Grpc.Core.Tests.CallCancellationTest.ClientStreamingCall_CancelServerSideRead
W0416 18:08:26.453125 Grpc.Core.Server Server shutdown has finished but there are still 1 active calls for that server.
W0416 18:08:26.468750 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.ClientStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()
=> Grpc.Core.Tests.CallCancellationTest.ClientStreamingCall_ServerSideReadAfterCancelNotificationReturnsNull
W0416 18:08:26.531250 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.ClientStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()
=> Grpc.Core.Tests.CallCancellationTest.ServerStreamingCall_CancelClientSideRead
W0416 18:08:26.671875 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite)
   at Grpc.Core.Internal.ServerStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext()

Errors, Failures and Warnings

1) Error : Grpc.Core.Tests.CallCancellationTest.ClientStreamingCall_ServerSideReadAfterCancelNotificationReturnsNull
TearDown : System.AggregateException : One or more errors occurred.
  ----> System.Exception : Shutdown check: Detected 1 pending batch completions.
--TearDown
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Grpc.Core.Tests.CallCancellationTest.Cleanup()
--Exception
   at Grpc.Core.Internal.DebugStats.DebugWarning(String message)
   at Grpc.Core.Internal.DebugStats.CheckOK()
   at Grpc.Core.GrpcEnvironment.<ShutdownAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.GrpcEnvironment.<ReleaseAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<ShutdownInternalAsync>d__32.MoveNext()

Run Settings
    Number of Test Workers: 1
    Work Directory: T:\src\github\grpc\workspace_csharp_windows_opt_native
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 5, Passed: 4, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2021-04-17 01:08:25Z
    End time: 2021-04-17 01:08:26Z
    Duration: 0.761 seconds
```

**Comment by jtattermusch** [comment]
Not seen in the last 100days.
