### ISSUE TITLE
Type.GetType error on .Net 5

### ISSUE THREAD

**Issue by yejinmo** [grpc/grpc#26057]
### What version of gRPC and what language are you using?
Grpc.Core 2.37.0 / C#

### What operating system (Linux, Windows,...) and version?
CentOS 7.5 1804

### What runtime / compiler are you using (e.g. python version or version of gcc)
.Net 5

### What did you do?
Create instance of `Grpc.Core.Server` 

### What did you expect to see?
Successful create

### What did you see instead?
```
Could not load file or assembly 'Xamarin.iOS, Culture=neutral, PublicKeyToken=null'. The parameter is incorrect.
 (0x80070057 (E_INVALIDARG))
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Grpc.Core.Internal.PlatformApis..cctor()
```

The  error occurred in `Grpc.Core.Internal`:
```
PlatformApis.isXamarinIOS = (Type.GetType("Foundation.NSObject, Xamarin.iOS") != null);
```

### Anything else we should know about your project / environment?

Everything is OK in `.Net core 3.1`
It looks like the `.Net 5` modify the implementation of `Type.GetType` method
Reference: [Type.GetType(string, bool) don't work in . NET5](https://github.com/dotnet/runtime/issues/46066)

**Comment by jtattermusch** [comment]
Can you please provide a minimal reproduction, ideally in a form of a github repository with ready-to-run code? It would make it easier for us to reproduce the issue you're experiencing and debug it afterwards.

**Comment by yejinmo** [comment]
One dependency package is using `Grpc.Core` `2.23.0`, update `Grpc.Core` to `2.37.0` problem solved.

Thanks.
