### ISSUE TITLE
ImportError on grpcio-1.37.0 for arm32v7

### ISSUE THREAD

**Issue by sr-gi** [grpc/grpc#26094]
### What version of gRPC and what language are you using?

`grpcio-1.37.0` for Python (installed via PyPI using using `grpcio-1.37.0-cp37-cp37m-linux_armv7l.whl`)

### What operating system (Linux, Windows,...) and version?

Debian 10 (buster) for arm32v7 (dockerized, pulling from `rycus86/armhf-debian-qemu`)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7.3

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

- Create a docker container pulling from `rycus86/armhf-debian-qemu` (I assume any arm32v7 setup would do)
- Install grpcio==1.37.0 via PyPi
- Try to import grcpio within Python

### What did you expect to see?

The library being imported

### What did you see instead?

```
[...]
import grpc
  File "/usr/lib/python3.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/python3.7/site-packages/grpc/_cython/__init__.py)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

Just as a side note, I can confirm that `grpcio-1.36.0` does work under the same environment. However, the latter needs compiling since no wheel for arm32v7 is available, so not sure if that can give you a head start.

**Comment by need2buy** [comment]
Hit the same error on armv7 architecture

**Comment by need2buy** [comment]
Tried again with latest 1.38. Same issue persist on python 3.9.2 with armv7

Python 3.9.2 (default, Mar 22 2021, 07:09:13)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from grpc._cython import cygrpc as _cygrpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/python3.9/site-packages/grpc/_cython/__init__.py)

Environment: 
cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 1600.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

processor	: 1
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 1600.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

**Comment by Darkmasterhk** [comment]
Getting the same error similar setup:

Error:

> Traceback (most recent call last):`
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/root/rp_py_sw/sc_rp_sw.py", line 6, in <module>
>     import grpc
>   File "/usr/lib/python3.8/site-packages/grpc/__init__.py", line 23, in <module>
>     from grpc._cython import cygrpc as _cygrpc
> ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/python3.8/site-packages/grpc/_cython/__init__.py)

Environment:
Python 3.8.5 (OS included version - Poky (Yocto Project Reference Distro) 3.2.1 (Build with Yocto Project))
grpc 1.38.1 & 1.39.0-rc

processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 200.00
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 200.00
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Altera SOCFPGA
Revision        : 0000
Serial          : 0000000000000000

**Comment by need2buy** [comment]
with latest 1.39 still hit same error. Hope you can help 

Python 3.9.2 (default, Mar 22 2021, 07:09:13)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/python3.9/site-packages/grpc/_cython/__init__.py)

**Comment by lidizheng** [comment]
CC @jtattermusch 

@need2buy Can you share the result for installing with our pre-built binary wheels? For example, this one `grpcio-1.39.0-cp39-cp39-linux_armv7l.whl`, [link](https://pypi.org/project/grpcio/#copy-hash-modal-4a41207d-43b0-474b-844b-34cfad513aa9).

The import error means the C extension is not loaded.

**Comment by need2buy** [comment]
@lidizheng 

My test is below

pip3 install grpcio-1.39.0-cp39-cp39-linux_armv7l.whl
Processing ./grpcio-1.39.0-cp39-cp39-linux_armv7l.whl
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3.9/site-packages (from grpcio==1.39.0) (1.15.0)
Installing collected packages: grpcio
Successfully installed grpcio-1.39.0
WARNING: You are using pip version 21.0.1; however, version 21.2.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
==========================
Python 3.9.2 (default, Mar 22 2021, 07:09:13)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/python3.9/site-packages/grpc/_cython/__init__.py)
>>>

**Comment by jtattermusch** [comment]
for repro, it would be the easiest if you included a `Dockerfile` that reproduces the problem - that way it's easy to repro and experiment with it, and we would also be sure that everyone's running into the same issue.

**Comment by cyanosp** [comment]
#27512 related?

**Comment by allenporter** [comment]
I have a locally built wheel with `python3 tools/run_tests/task_runner.py -b python_linux_extra_armv7_cp39-cp39` (though, note, I had to tweak this to get a local build working as discussed in #27512. I've also seen this from the wheels from https://www.piwheels.org/project/grpcio/ 
 
```
FROM arm32v7/alpine:3.14.2
RUN apk add --no-cache python3 py3-pip
# Note: Likely not all these are needed
RUN apk add libstdc++ libc6-compat libatomic musl-dev
RUN python3 --version

WORKDIR /code
COPY example.py .

ENV WHEEL=grpcio-1.43.0.dev0-cp39-cp39-linux_armv7l.whl
COPY ${WHEEL} .

RUN python3 --version
RUN pip3 install $WHEEL
RUN pip3 install google-cloud-pubsub

CMD python3 ./example.py
```

Then example.py:
```
#!/usr/bin/python

from google.cloud import pubsub_v1

def main():
  print("Hello world")

if __name__ == "__main__":
  main()
```

Building and running
```
$ docker build -t local-wheel docker/local-wheel/
$ docker run local-wheel:latest
Traceback (most recent call last):
  File "/code/./example.py", line 3, in <module>
    from google.cloud import pubsub_v1
  File "/usr/lib/python3.9/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/usr/lib/python3.9/site-packages/google/cloud/pubsub_v1/types.py", line 27, in <module>
    from google.api_core import gapic_v1
  File "/usr/lib/python3.9/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/usr/lib/python3.9/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/usr/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/lib/python3.9/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/lib/python3.9/site-packages/grpc/_cython/__init__.py)
```

**Comment by RobertFromBerlin** [comment]
Had the exact same issue. Turns out the cygrpc module had the wrong filename so Python was not able to find it (CPython has some specific name requierements).
Python was linux_arm-linux-gnueabihf but the name of the module was cygrpc.cpython-38-arm-linux-gnueabi.so (note the missing hf). Once I renamed it to cygrpc.cpython-38-arm-linux-gnueabihf.so all worked as expected.

**Comment by sreenithi** [comment]
Closing the issue as stale.
