### ISSUE TITLE
Python error messages are not propagated through

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#2611]
When trying to create a cluster (I made a sample), using too long a cluster name:

## Error messages in Python

With the (Python [sample][2]):

```bash
$ USE_APP_DEFAULT=True make create_cluster
[ -d gcloud-python-bigtable ] || git clone https://github.com/dhermes/gcloud-python-bigtable
cd gcloud-python-bigtable && git pull origin master
From https://github.com/dhermes/gcloud-python-bigtable
 * branch            master     -> FETCH_HEAD
Already up-to-date.
python grpc_create_cluster.py
D0722 15:06:10.527594770   12574 frame_settings.c:230]       adding 983041 for initial_window change
Traceback (most recent call last):
  File "grpc_create_cluster.py", line 31, in <module>
    main()
  File "grpc_create_cluster.py", line 27, in main
    request_pb=request_pb)
  File "/bigtable_stuff/grpc-python-bigtable-examples/util.py", line 202, in make_cluster_request
    pretty_print=pretty_print, request_pb=request_pb)
  File "/bigtable_stuff/grpc-python-bigtable-examples/util.py", line 188, in _make_api_request
    result_pb = response.result()
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/alpha/_reexport.py", line 96, in result
    raise _reexport_error(e)
grpc.framework.alpha.exceptions.ExpirationError
D0722 15:06:20.123899042   12569 iomgr.c:126]                Waiting for 1 iomgr objects to be destroyed
D0722 15:06:30.123906522   12569 iomgr.c:156]                Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0722 15:06:30.123957013   12569 iomgr.c:161]                LEAKED OBJECT: tcp-client:74.125.129.95:443 0x2abc74014718
make: *** [create_cluster] Error 1
```

with the settings (in `config.py`)

```python
PROJECT_ID = 'foobar-your-project'
KEYFILE_PATH = ''
ZONE = 'us-central1-c'
CLUSTER = 'gcloud-python-cluster-0123456789'
TIMEOUT_SECONDS = 10
# See https://gist.github.com/dhermes/bbc5b7be1932bfffae77
# for appropriate values on other systems.
SSL_CERT_FILE = '/etc/ssl/certs/ca-certificates.crt'
```

## Error messages in Go

With the (Go [sample][1]):

```bash
$ USE_APP_DEFAULT=True make create_cluster
2015/07/22 14:46:56 rpc error: code = 3 desc = "Error in field 'cluster_id' : Invalid id for collection cluster : Length should be between [6,30], but found 32 (gcloud-python-cluster-0123456789)"
exit status 1
make: *** [create_cluster] Error 1
```

with the settings (in `consts.go`)

```go
package main

const (
	ProjectID          = "foobar-your-project"
	Zone               = "us-central1-c"
	ClusterID          = "gcloud-python-cluster-0123456789"
	DisplayName        = "Display name for cluster"
	ServeNodes         = 3
	KeyFile            = ""
	ScopeCloudPlatform = "https://www.googleapis.com/auth/cloud-platform"
)
```

[1]: https://github.com/dhermes/gcloud-golang-bigtable-examples
[2]: https://github.com/dhermes/grpc-python-bigtable-examples

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle To help prioritize this, every time I encounter an error **I have to write the same code in Go** so I can see what the failure is. 100% of the errors have just been me sending bad data (e.g. exceeding 30 chars for a cluster ID, leaving required fields unset, etc.) but I have no visibility into this using the Python client.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle Now that I look at this a little more closely, I'm kinda confused: why are we raising an expiration error here?

**Comment by nathanielmanistaatgoogle** [comment]
This is a subset of #2634; closing as a duplicate.

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm after a month of thinking about it it's probably that there's a `KeyError` inside the `rear.RearLink` which means that no `BackToFrontTicket` ever reaches the `FrontLink` and so from the `FrontLink`'s point of view the RPC times out.

Glad that none of that matters for Beta. :-)

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Can you re-open. With beta, all errors are `NetworkError`.

Making an invalid create cluster request should give something like the error above (from Go):

```
rpc error: code = 3 desc = "Error in field 'cluster_id' : Invalid id for collection cluster : Length should be between [6,30], but found 32 (gcloud-python-cluster-0123456789)"
```

Here is the example with `gcloud-python-bigtable`:

```python
>>> from gcloud_bigtable.client import Client
>>> client = Client(admin=True, project='foobar-your-project')
>>> client.start()
>>> cluster_name = 'gcloud-python-cluster-0123456789'
>>> len(cluster_name)
32
>>> cluster = client.cluster('us-central1-c', cluster_name)
>>> cluster.create()
D1125 08:45:10.045579061   18896 frame_settings.c:230]       adding 983041 for initial_window change
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud_bigtable/cluster.py", line 334, in create
    request_pb, timeout_seconds)
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/crust/implementations.py", line 73, in __call__
    protocol_options, metadata, request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/crust/_control.py", line 412, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.NetworkError
>>> client.stop()
```

**Comment by nathanielmanistaatgoogle** [comment]
@dhermes: have you looked at the `code` and `details` attributes of the `NetworkError` that you are seeing?

**Comment by dhermes** [comment]
Nope. Thanks for the pointer!

```python
>>> try:
...     cluster.create()
... except Exception as exc:
...     print 'Failed'
... 
change
Failed
>>> exc
NetworkError()
>>> exc.code
<StatusCode.INVALID_ARGUMENT: 3>
>>> exc.details
"Error in field 'cluster_id' : Invalid id for collection cluster : Length should be between [6,30], but found 32 (gcloud-python-cluster-0123456789)"
```

------

Any reason you didn't put the `details` in the `__repr__` of the `NetworkError`?

**Comment by nathanielmanistaatgoogle** [comment]
There's probably a reason, but I doubt that it's a _good_ reason. :-P
