### ISSUE TITLE
"address family not supported by protocol" over link-local ipv6

### ISSUE THREAD

**Issue by comotion** [grpc/grpc#26175]
### What version of gRPC and what language are you using?
grpcio-1.37.1 (python)

### What operating system (Linux, Windows,...) and version?
linux ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.5

### What did you do?
Tried connecting to grpc service on ipv6 link local
```
import route_guide_pb2
import route_guide_pb2_grpc
with grpc.insecure_channel("fe80::1118:bf31:531d:1d00%enp34s0") as channel:
    stub = route_guide_pb2_grpc.RouteGuideStub(channel)
    reponse = stub.GetFeature(empty_pb2.Empty())
```

### What did you expect to see?
successful connection, or "connection refused" if service was off.

### What did you see instead?
```
0505 14:48:56.663029165   75745 init.cc:226]                grpc_shutdown starts clean-up now
Traceback (most recent call last):
  File "grpc-test.py", line 20, in <module>
    reponse = stub.GetFeature(empty_pb2.Empty())
  File "/home/comotion/.local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/comotion/.local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1620218936.662904964","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1620218936.662896864","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
```

### Anything else we should know about your project / environment?

I traced grpc with `export GRPC_VERBOSITY=DEBUG` and finally saw 
```
D0505 14:48:56.662391961   75745 ev_posix.cc:173]            Using polling engine: epollex
D0505 14:48:56.662455031   75745 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0505 14:48:56.662464761   75745 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0505 14:48:56.662469051   75745 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0505 14:48:56.662472181   75745 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0505 14:48:56.662478911   75745 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0505 14:48:56.662485451   75745 dns_resolver_ares.cc:491]   Using ares dns resolver
D0505 14:48:56.662508421   75745 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0505 14:48:56.662515371   75745 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0505 14:48:56.662518601   75745 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0505 14:48:56.662525591   75745 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0505 14:48:56.662530291   75745 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
I0505 14:48:56.662848054   75745 socket_utils_common_posix.cc:428] Disabling AF_INET6 sockets because ::1 is not available.
I0505 14:48:56.662884824   75745 subchannel.cc:1012]         Connect failed: {"created":"@1620218936.662865384","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":444,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[fe80::1118:bf31:531d:1d00%252]:0"}
I0505 14:48:56.662899384   75745 subchannel.cc:957]          Subchannel 0x1c40e70: Retry in 1000 milliseconds
D0505 14:48:56.663029165   75745 init.cc:226]                grpc_shutdown starts clean-up now
Traceback (most recent call last):
  File "grpc-test.py", line 20, in <module>
    reponse = stub.GetFeature(empty_pb2.Empty())
  File "/home/comotion/.local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/comotion/.local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1620218936.662904964","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1620218936.662896864","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
```
Notice the `Disabling AF_INET6 sockets because ::1 is not available.`
this led me to investigate, and I found that sysctl `net.ipv6.conf.lo.disable_ipv6=1`

So, this bug is caused by the loopback interface not having an IPv6 address, which is rather unintuitive since I was trying to connect over an interface that does have IPv6 enabled.

Does it make sense to disable IPv6 sockets because loopback doesn't have IPv6 address? It causes a hard-to-debug issue.

**Comment by yashykt** [comment]
This is certainly an annoying issue to run into. What I'm happy about is that the gRPC logs pointed out the issue.

For gRPC internals, this seems to have been intended as a quick way to determine whether IPv6 sockets are enabled or not. Suggestions welcome

**Comment by comotion** [comment]
IPv6 sockets are enabled if the given interface has an ip6 address, or to put it another way, if we have a route to that address. That is handled in the operating system, and throws a "network unreachable" when it fails to find a route.

**Comment by yashykt** [comment]
Could you please send a pull request with the change that you are talking about?

**Comment by yashykt** [comment]
@ctiller What do you think?
