### ISSUE TITLE
Continuous Failure: py37_native.test.unit._contextvars_propagation_test.ContextVarsPropagationTest

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#26322]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_contextvars_propagation_test.py", line 112, in test_propagation_to_auth_plugin
    response = stub(_REQUEST, wait_for_ready=True)
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Getting metadata from plugin failed with error: None != 24601"
	debug_error_string = "{"created":"@1621521604.321564241","description":"Getting metadata from plugin failed with error: None != 24601","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":93,"grpc_status":14}"
>

[1mstdout:[0m

[1mstderr:[0m
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<unit._contextvars_propagation_test.TestCallCredentials object at 0x7f207876feb8>" raised exception!
Traceback (most recent call last):
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_plugin_wrapping.py", line 78, in __call__
    context, _AuthMetadataPluginCallback(callback_state, callback))
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_contextvars_propagation_test.py", line 78, in __call__
    _EXPECTED_VALUE))
AssertionError: None != 24601
```

https://source.cloud.google.com/results/invocations/7bf104e3-7d15-4e26-b5fa-18b68f4266a1/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_native%2Fpy37_native.test.unit._contextvars_propagation_test.ContextVarsPropagationTest/tests

**Comment by gnossen** [comment]
It looks like this failure started last night around 9:00PM.

**Comment by gnossen** [comment]
Further testing shows that this is actually a high percentage flake. ~65% on my workstation.

**Comment by drfloob** [comment]
The first instance I saw of it was yesterday at noon on my PR branch, which is not merged https://source.cloud.google.com/results/invocations/675b457d-4124-4922-85a2-00623962c01e/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_native%2Fpy37_native.test.unit._contextvars_propagation_test.ContextVarsPropagationTest/tests

**Comment by gnossen** [comment]
Bisecting has revealed that commit d7954e8300006d9a5850a24f9c72a97f2c454637 was the trigger for this.
