### ISSUE TITLE
py36_asyncio.test_aio.unit.connectivity_test.TestConnectivityState consistently failing on linux aarch64

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#26394]
Note that I've only seen these failures on aarch64.

```
+ PYTHON=/home/ubuntu/workspace/grpc/py36_asyncio/bin/python3.6
++ pwd
+ ROOT=/home/ubuntu/workspace/grpc
+ /home/ubuntu/workspace/grpc/py36_asyncio/bin/python3.6 /home/ubuntu/workspace/grpc/src/python/grpcio_tests/setup.py test_aio
running test_aio
Running       unit.connectivity_test.TestConnectivityState.test_normal_backend
Running       unit.connectivity_test.TestConnectivityState.test_shutdown
Running       unit.connectivity_test.TestConnectivityState.test_timeout
Running       unit.connectivity_test.TestConnectivityState.test_unavailable_backend
[95mTesting gRPC Python...
[0m[92mSUCCESS       unit.connectivity_test.TestConnectivityState.test_normal_backend
[0m[92mSUCCESS       unit.connectivity_test.TestConnectivityState.test_shutdown
[0m[92mSUCCESS       unit.connectivity_test.TestConnectivityState.test_timeout
[0m[91mERROR         unit.connectivity_test.TestConnectivityState.test_unavailable_backend
[0m4 tests finished:
	3 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures:
[91munit.connectivity_test.TestConnectivityState.test_unavailable_backend[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/ubuntu/workspace/grpc/src/python/grpcio_tests/tests_aio/unit/_test_base.py", line 31, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/ubuntu/workspace/grpc/src/python/grpcio_tests/tests_aio/unit/connectivity_test.py", line 51, in test_unavailable_backend
    test_constants.SHORT_TIMEOUT)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

Example occurrences:
https://source.cloud.google.com/results/invocations/72cc53c8-e6e8-4a64-92d6-2887e0489383/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_gevent%2Fpy36_asyncio.test_aio.unit.connectivity_test.TestConnectivityState/tests
https://source.cloud.google.com/results/invocations/4eb247d5-ec92-4ea5-bd94-badb853aff8d/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_gevent%2Fpy36_asyncio.test_aio.unit.connectivity_test.TestConnectivityState/tests
https://source.cloud.google.com/results/invocations/9b8bde1b-6a0f-4481-91a2-aac20a82bfa1/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_gevent%2Fpy36_asyncio.test_aio.unit.connectivity_test.TestConnectivityState/tests

**Comment by jtattermusch** [comment]
Test has been disabled by https://github.com/grpc/grpc/pull/26409
