### ISSUE TITLE
gRPC usage with gevent and Unix sockets

### ISSUE THREAD

**Issue by lorenzo-arena** [grpc/grpc#26422]
### What version of gRPC and what language are you using?

Python 3.8.2, gprcio 1.37.0

### What operating system (Linux, Windows,...) and version?

Linux embedded / Ubuntu 20.10

### What did you do?

I have a flask server which connects as a client to a gRPC server running on `/var/tmp/test`. The flask server is monkey patched with

```python
from gevent import monkey
monkey.patch_all()

import grpc.experimental.gevent as grpc_gevent
grpc_gevent.init_gevent()
```

But when I try to open a channel on the unix socket with 

```python
url = "unix:///var/tmp/test"
channel = grpc.insecure_channel(url)
```

I get the error

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "src/python/grpcio/grpc/_cython/_cygrpc/grpc_gevent.pyx.pxi", line 68, in grpc._cython.cygrpc.socket_connect_async
  File "src/python/grpcio/grpc/_cython/_cygrpc/grpc_gevent.pyx.pxi", line 59, in grpc._cython.cygrpc.socket_connect_async_cython
  File "/usr/lib/python3.8/site-packages/gevent/_socket3.py", line 329, in connect
    address = _socketcommon._resolve_addr(self._sock, address)
  File "/usr/lib/python3.8/site-packages/gevent/_socketcommon.py", line 395, in _resolve_addr
    r = getaddrinfo(host, None, sock.family)
  File "/usr/lib/python3.8/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/lib/python3.8/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/lib/python3.8/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
2020-09-20T11:50:36Z <Greenlet at 0xffff881688c0: socket_connect_async(<grpc._cython.cygrpc.SocketWrapper object at 0xfff, ('(sockaddr family=1)', 1))> failed with TypeError

```

**Comment by lidizheng** [comment]
gevent + UDS is not yet supported. gevent uses the custom I/O manager, which we are going to deprecate. So, we might delay this feature request until the new event engine is rolled out.
