### ISSUE TITLE
Is it possible to connect client and server when on different Wifi networks? 

### ISSUE THREAD

**Issue by Rutujaa** [grpc/grpc#26434]
I want to run the client and server on different machines. I tried this on the same wifi network it worked. But when I ran the client and server on different wifi networks it gives the following error.

`Traceback (most recent call last):
  File "client.py", line 17, in <module>
    response = stub.SquareRoot(number)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\grpc\_channel.py", line 946, in _call_
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1622034767.452000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5420,"referenced_errors":[{"created":"@1622034767.452000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"`

**Comment by Rutujaa** [comment]
I resolved this issue. 
There was a networking problem. The IP address and port forwarding were set incorrectly.
