### ISSUE TITLE
sefgault with streming reply

### ISSUE THREAD

**Issue by kofemann** [grpc/grpc#26506]
I am trying tu build an gRPC based service that replys a stream of messages. The unimessage mode forks as expected. However in streaming mode I am always getting segfault.

### What version of gRPC and what language are you using?
[root@4d5784c34a53 build]# rpm -qa | egrep  "grpc|proto"
grpc-plugins-1.19.0-1.el7.x86_64
protobuf-3.6.1-4.el7.x86_64
grpc-1.19.0-1.el7.x86_64
grpc-devel-1.19.0-1.el7.x86_64
protobuf-compiler-3.6.1-4.el7.x86_64
protobuf-devel-3.6.1-4.el7.x86_64
[root@4d5784c34a53 build]# 

### What operating system (Linux, Windows,...) and version?
CentOS-7

### What runtime / compiler are you using (e.g. python version or version of gcc)

[root@4d5784c34a53 build]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### What did you do?
The simplified test case is:

```proto
service CtaRpc {
  rpc GetMessages (google.protobuf.Empty) returns (stream TestMessage) {}
}

message TestMessage {
  string message = 1;
}
```

### What did you see instead?

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f424a549700 (LWP 1354)]
0x00007f424a53b150 in ?? ()
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cryptopp-5.6.2-10.el7.x86_64 cyrus-sasl-lib-2.1.26-23.el7.x86_64 elfutils-libelf-0.176-5.el7.x86_64 elfutils-libs-0.176-5.el7.x86_64 glibc-2.17-324.el7_9.x86_64 json-c-0.11-4.el7_0.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libaio-0.3.109-13.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libblkid-2.23.2-65.el7_9.1.x86_64 libcap-2.22-11.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libibverbs-22.4-6.el7_9.x86_64 libnl3-3.2.28-4.el7.x86_64 librados2-14.2.20-0.el7.x86_64 libradosstriper1-14.2.20-0.el7.x86_64 librdmacm-22.4-6.el7_9.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libuuid-2.23.2-65.el7_9.1.x86_64 libxml2-2.9.1-6.el7.5.x86_64 lttng-ust-2.10.0-1.el7.x86_64 lz4-1.8.3-1.el7.x86_64 mariadb-libs-10.3.20-3.el7.0.0.rdo1.x86_64 nspr-4.25.0-2.el7_9.x86_64 nss-3.53.1-7.el7_9.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 nss-util-3.53.1-1.el7_9.x86_64 openldap-2.4.44-23.el7_9.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 postgresql-libs-9.2.24-7.el7_9.x86_64 protobuf-3.6.1-4.el7.x86_64 sqlite-3.7.17-8.el7_7.1.x86_64 systemd-libs-219-78.el7_9.3.x86_64 tinyxml-2.6.2-3.el7.x86_64 userspace-rcu-0.10.0-3.el7.x86_64 xrootd-client-libs-5.2.0-1.el7.x86_64 xrootd-libs-5.2.0-1.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb) bt
#0  0x00007f424a53b150 in ?? ()
#1  0x00000000004b0b18 in google::protobuf::MessageLite::ByteSize (this=0x7f424a53ac78) at /usr/include/google/protobuf/message_lite.h:336
#2  0x00000000004b9f8b in grpc::GenericSerialize<grpc::ProtoBufferWriter, cta::rpc::TestMessage> (msg=..., bb=0x7f423c0097a8, own_buffer=0x7f424a53abaf)
    at /usr/include/grpcpp/impl/codegen/proto_utils.h:52
#3  0x00000000004b903f in grpc::SerializationTraits<cta::rpc::TestMessage, void>::Serialize (msg=..., bb=0x7f423c0097a8, own_buffer=0x7f424a53abaf)
    at /usr/include/grpcpp/impl/codegen/proto_utils.h:110
#4  0x00000000004b834b in grpc::Status grpc::internal::CallOpSendMessage::SendMessage<cta::rpc::TestMessage>(cta::rpc::TestMessage const&, grpc::WriteOptions)::{lambda(void const*)#1}::operator()(void const*) const (__closure=0x7f423c009de0, message=0x7f424a53ac78)
    at /usr/include/grpcpp/impl/codegen/call_op_set.h:396
#5  0x00000000004baa21 in std::_Function_handler<grpc::Status (void const*), grpc::Status grpc::internal::CallOpSendMessage::SendMessage<cta::rpc::TestMessage>(cta::rpc::TestMessage const&, grpc::WriteOptions)::{lambda(void const*)#1}>::_M_invoke(std::_Any_data const&, void const*) (__functor=..., 
    __args#0=0x7f424a53ac78) at /usr/include/c++/4.8.2/functional:2057
#6  0x00007f426634f3d5 in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallNoOp<3>, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::ContinueFillOpsAfterInterception() () from /lib64/libgrpc++.so.1
#7  0x00007f426634f8a8 in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallNoOp<3>, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::FillOps(grpc::internal::Call*) () from /lib64/libgrpc++.so.1
#8  0x00000000004af13e in grpc::internal::Call::PerformOps (this=0x7f423c009968, ops=0x7f423c009768) at /usr/include/grpcpp/impl/codegen/call.h:67
#9  0x00000000004b4c71 in grpc::ServerWriter<cta::rpc::TestMessage>::Write (this=0x7f424a53b320, msg=..., options=...)
    at /usr/include/grpcpp/impl/codegen/sync_stream.h:670
#10 0x00000000004ae5ca in CtaRpcImpl::GetMessages (this=0x7ffee946d3d0, context=0x7f423c009610, request=0x7f423c008a70, writer=0x7f424a53b320)
    at /workdir/frontend_svc/gRPC/FrontendGRpcSvc.cpp:143
```

The service method (the stack trace above) is:
```c++
Status CtaRpcImpl::GetMessages(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::cta::rpc::TestMessage>* writer) {

    ::cta::rpc::TestMessage tm;

    for(int i = 0; i < 100; i++) {
        tm.set_message("Message-" + i);
        writer->Write(tm, grpc::WriteOptions());
    }
    return Status::OK;
}
```

This is such a trivial case, that obviously someting wrong on my side, but I have no idea what...

Thanks.

**Comment by kofemann** [comment]
After updating to grpc-1.20.1 works as expected.
