### ISSUE TITLE
Python flake: //src/python/grpcio_tests/tests/unit:_metadata_flags_test.python2

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#26611]
Log snippet:

```
FAIL: //src/python/grpcio_tests/tests/unit:_metadata_flags_test.python2 (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/testlogs/src/python/grpcio_tests/tests/unit/_metadata_flags_test.python2/test.log)
INFO: From Testing //src/python/grpcio_tests/tests/unit:_metadata_flags_test.python2:
==================== Test output for //src/python/grpcio_tests/tests/unit:_metadata_flags_test.python2:
test_call_wait_for_ready_default (__main__.MetadataFlagsTest) ... ok
test_call_wait_for_ready_disabled (__main__.MetadataFlagsTest) ... ok
test_call_wait_for_ready_enabled (__main__.MetadataFlagsTest) ... E0702 05:50:28.302761520   30241 server_chttp2.cc:49]        {"created":"@1625205028.302703307","description":"No address added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":873,"referenced_errors":[{"created":"@1625205028.302665523","description":"Unable to configure socket","fd":7,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":218,"referenced_errors":[{"created":"@1625205028.302660385","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":191,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1625205028.302691067","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::1]:33173"}]}
ERROR

======================================================================
ERROR: test_call_wait_for_ready_enabled (__main__.MetadataFlagsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3278/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/unit/_metadata_flags_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/unit/_metadata_flags_test.py", line 245, in test_call_wait_for_ready_enabled
    server.add_insecure_port(addr)
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3278/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/unit/_metadata_flags_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_server.py", line 971, in add_insecure_port
    address, _add_insecure_port(self._state, _common.encode(address)))
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3278/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/unit/_metadata_flags_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address localhost:33173; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

----------------------------------------------------------------------
Ran 3 tests in 1.125s

FAILED (errors=1)
```

```
//src/python/grpcio_tests/tests/unit:_metadata_flags_test.python2        FAILED in 1.4s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/testlogs/src/python/grpcio_tests/tests/unit/_metadata_flags_test.python2/test.log

Executed 145 out of 145 tests: 144 tests pass and 1 fails locally.
```

https://source.cloud.google.com/results/invocations/8820c906-9347-420b-9d75-634a82474650/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_python_bazel_test/log

Seen in https://github.com/grpc/grpc/pull/26599 on 1.39.x branch

**Comment by markdroth** [comment]
Also seeing this test timeout:

https://source.cloud.google.com/results/invocations/51d34d47-b84f-4292-977c-d786b8ca61d2/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_python_bazel_test/log

**Comment by lidizheng** [comment]
This flake is still occurs in the past week, and it happens on different Python version. Related bug b/192479876.
