### ISSUE TITLE
Bazel Basic Tests for Python (Local)

### ISSUE THREAD

**Issue by itsemmanuelfrancis** [grpc/grpc#26648]
Bazel Basic Tests for Python (Local) is failing for the PR: #26471. The failure seems to be unrelated to the changes in the PR.
Log: https://source.cloud.google.com/results/invocations/ccd03a11-1686-48b1-9f22-48a383d75fee/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_python_bazel_test/log

**Comment by gnossen** [comment]
```
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3326/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/_intraop_test_case.py", line 36, in testClientStreaming
    methods.TestCase.CLIENT_STREAMING.test_interoperability(self.stub, None)
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3326/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/methods.py", line 451, in test_interoperability
    _client_streaming(stub)
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3326/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/interop/methods.py", line 107, in _client_streaming
    response = stub.StreamingInputCall(requests)
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3326/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_channel.py", line 1131, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3326/execroot/com_github_grpc_grpc/bazel-out/k8-py2-fastbuild/bin/src/python/grpcio_tests/tests/interop/_insecure_intraop_test.python2.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Broken pipe"
	debug_error_string = "{"created":"@1625848679.987405821","description":"Error received from peer ipv4:127.0.0.1:33901","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Broken pipe","grpc_status":14}"
>
```

Looks like a one-off broken pipe. This test is still green on master. Waiting until we see this again.

**Comment by sreenithi** [comment]
the linked PR is merged and the mentioned tests are working fine too. Closing the issue as stale.
