### ISSUE TITLE
FLAKE: //src/python/grpcio_tests/tests/unit:_reconnect_test.python3

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#26649]
Log snippet:

```
FAIL: //src/python/grpcio_tests/tests/unit:_reconnect_test.python3 (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests/unit/_reconnect_test.python3/test.log)
INFO: From Testing //src/python/grpcio_tests/tests/unit:_reconnect_test.python3:
==================== Test output for //src/python/grpcio_tests/tests/unit:_reconnect_test.python3:
test_reconnect (__main__.ReconnectTest) ... E0709 04:47:18.735672994   12735 server_chttp2.cc:49]        {"created":"@1625806038.735601826","description":"No address added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":873,"referenced_errors":[{"created":"@1625806038.735561352","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":218,"referenced_errors":[{"created":"@1625806038.735552926","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":191,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1625806038.735588001","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::1]:38387"}]}
ERROR

======================================================================
ERROR: test_reconnect (__main__.ReconnectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3724/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/unit/_reconnect_test.python3.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests/unit/_reconnect_test.py", line 60, in test_reconnect
    server.add_insecure_port(addr)
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3724/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/unit/_reconnect_test.python3.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_server.py", line 971, in add_insecure_port
    address, _add_insecure_port(self._state, _common.encode(address)))
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/3724/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests/unit/_reconnect_test.python3.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address localhost:38387; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

----------------------------------------------------------------------
Ran 1 test in 5.160s

FAILED (errors=1)
```

https://source.cloud.google.com/results/invocations/73444523-b875-4ef4-a90d-2d147a92b6a4/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_python_bazel_test/log

Seen in https://github.com/grpc/grpc/pull/26642

**Comment by lidizheng** [comment]
This looks like a one time failure. The resolution result looks like the MetadataFlagTest. Merging with https://github.com/grpc/grpc/issues/26611.
