### ISSUE TITLE
C# tests sometimes fails on Windows

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#2673]
Seen multiple times on Windows. Based on the log, the test process probably crashes without printing anything and the "no connection could be made" error comes from nunit agent being unable to connect to the process running the tests.

***** Grpc.Core.Tests.ClientServerTest.UnaryCall_DisposedChannel

I7/25/2015 8:52:50 AM 0 c:\jenkins\workspace\grpc_pull_requests\config\dbg\language\csharp\platform\windows\src\core\surface\server.c:1154: grpc_server_request_call(server=040D4A78, call=003ED0AC, details=003ED0B0, initial_metadata=003ED0CC, cq_bound_to_call=040BA800, cq_for_notification=040BA800, tag=003ED060)

I7/25/2015 8:52:50 AM 0 c:\jenkins\workspace\grpc_pull_requests\config\dbg\language\csharp\platform\windows\src\core\surface\server.c:995: grpc_server_shutdown_and_notify(server=040D4A78, cq=040BA800, tag=003ECD18)

I7/25/2015 8:52:50 AM 0 c:\jenkins\workspace\grpc_pull_requests\config\dbg\language\csharp\platform\windows\src\core\surface\completion_queue.c:182: RETURN_EVENT[040BA800]: OP_COMPLETE: tag:003ED060 ERROR

I7/25/2015 8:52:50 AM 0 c:\jenkins\workspace\grpc_pull_requests\config\dbg\language\csharp\platform\windows\src\core\surface\completion_queue.c:182: RETURN_EVENT[040BA800]: OP_COMPLETE: tag:003ECD18 OK

Unhandled Exception:
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:55921

Server stack trace: 

   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)

   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)

   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket(EndPoint ipEndPoint)

   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket()

   at System.Runtime.Remoting.Channels.RemoteConnection.GetSocket()

   at System.Runtime.Remoting.Channels.SocketCache.GetSocket(String machinePortAndSid, Boolean openNew)

   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.SendRequestWithRetry(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream)

   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)

   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 

   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

   at System.IDisposable.Dispose()

   at NUnit.Core.ProxyTestRunner.Dispose()

   at NUnit.Util.ProcessRunner.Dispose()

   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)

   at NUnit.ConsoleRunner.Runner.Main(String[] args)

**Comment by jtattermusch** [comment]
#2708 partially fixes that.

**Comment by jtattermusch** [comment]
I haven't seen this for a while and I am unable to reproduce when running tests locally.
