### ISSUE TITLE
Quick start for C# - running server app fails

### ISSUE THREAD

**Issue by wrong42** [grpc/grpc#26785]
**Issue description**
After downloading the grpc examples from github, next step is to run the server application. But in both v1.38.0 and master branche, the server will throw an exeption after running the `dotnet run -f netcoreapp2.1` command.

Output of the `dotnet run -f netcoreapp2.1` command:

```
Greeter server listening on port 30051
Press any key to stop the server...

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at GreeterServer.Program.Main(String[] args) in C:\git\grpc\examples\csharp\Helloworld\GreeterServer\Program.cs:line 46

```

**Steps to reproduce the issue**
1. Download source code from github
2. Checkout to master branch or v1.38.0
3. Go to the GreeterServer directory
4. Run `dotnet run -f netcoreapp2.1` command
5. See the error

**Expected behavior**
The server starts normally.

**Additional info**
Running on Windows 10 Pro, Version: 20H2, OS Build: 19042.1110.

**How to fix it**
The fix is easy. Just replacing the `Console.ReadKey();` call in `Program.cs` of `GreeterServer` project with `Console.Read();`

**Comment by wrong42** [comment]
Created pull request as fix: https://github.com/grpc/grpc/pull/26784
