### ISSUE TITLE
If I use asyncio.wait_for(channel.channel_ready(), 2.0) program not quits (need double Ctrl+C) and exit with error.

### ISSUE THREAD

**Issue by ChameleonRed** [grpc/grpc#26887]
### What version of gRPC and what language are you using?
1.39

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.6

### What did you do?

```
"""
Learn how client and server behave on stopped server or not run.
"""

import asyncio
import logging

import grpc

import s01_proto_pb2
import s01_proto_pb2_grpc
from performance.stopper import Stopper


async def main():
    channel = grpc.aio.insecure_channel('localhost:50051')

    while True:
        if channel.get_state() != grpc.ChannelConnectivity.READY:
            try:
                print('Check if channel ready.')
                await asyncio.wait_for(channel.channel_ready(), 2.0)
            except asyncio.exceptions.TimeoutError as exception:
                print('Connection failed.')
                print(type(exception), exception)
                delay = 2.0
                print(f'Wait {delay}.')
                await asyncio.sleep(delay)
                continue

        stub = s01_proto_pb2_grpc.GrpcServerStub(channel)

        stopper = Stopper()
        check_heartbeat_call = s01_proto_pb2.CheckHeartBeatCall()
        try:
            stopper.start()
            print('Call started.')
            print(f'Channel state is {channel.get_state()}.')
            await stub.check_heartbeat(check_heartbeat_call, timeout=20.0)
            stopper.stop()
        except Exception as exception:
            stopper.stop()
            print('Call failed.')
            print(type(exception), exception)
            print(f'Channel state is {channel.get_state()}.')
            print(f'{stopper.seconds():.3e}')
            delay = 2.0
            print(f'Wait {delay}.')
            await asyncio.sleep(delay)
            continue
        else:
            print('Call success.')
            print(f'{stopper.seconds():.3e}')
            delay = 2.0
            print(f'Wait {delay}.')
            await asyncio.sleep(delay)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    try:
        asyncio.run(main(), debug=True)
    except KeyboardInterrupt:
        pass
```

```
syntax = "proto3";
//import "google/protobuf/empty.proto";

message CheckHeartBeatCall {
}

message CheckHeartBeatReply {
}

service GrpcServer {
  rpc check_heartbeat(CheckHeartBeatCall) returns(CheckHeartBeatReply);
}
```

1. Run.
2. Try to hit `await asyncio.wait_for(channel.channel_ready(), 2.0)` which cause error.
3. Try to stop program with "Ctrl+C" (I am using PyCharm to stop.

### What did you expect to see?

Program should exit with code 0.

I want use await asyncio.wait_for(channel.channel_ready(), 2.0) to check if connection is established.
If not I will change channel to different server in cluster until I find working server (this is not include in example but lead to such code).

### What did you see instead?

1. Program NOT exit.

First Ctrl+C lead to:
"C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\venv\Scripts\python.exe" "C:/Users/Cezary Wagner/PycharmProjects/medptr-v2/sandbox/grpc/s03_connection_error/s01_proto_async_client.py"
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Check if channel ready.
DEBUG:asyncio:Close <ProactorEventLoop running=False closed=False debug=True>

Next Ctrl+C lead to:
Process finished with exit code -1

2. When you do it in different place of code:
"C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\venv\Scripts\python.exe" "C:/Users/Cezary Wagner/PycharmProjects/medptr-v2/sandbox/grpc/s03_connection_error/s01_proto_async_client.py"
Check if channel ready.
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Connection failed.
<class 'asyncio.exceptions.TimeoutError'> 
Wait 2.0.
DEBUG:asyncio:Close <ProactorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/completion_queue.pyx.pxi", line 170, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: 'grpc._cython.cygrpc.PollerCompletionQueue._poll'
Traceback (most recent call last):
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/completion_queue.pyx.pxi", line 170, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Process finished with exit code -1

As you see that is little random but really depend on line of code.

This code cause problems `await asyncio.wait_for(channel.channel_ready(), 2.0)` or rather `channel.channel_ready()`.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

If you remove `channel.channel_ready()` rest works.

This works perfect but it is not grpc:

```
import asyncio


async def main():
    while True:
        await asyncio.sleep(1.0)

if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```

**Comment by ChameleonRed** [comment]
Server is not need for test but if you wish to play here is code:

```
import asyncio
import logging
from asyncio.runners import _cancel_all_tasks

import grpc

from sandbox.grpc.s03_connection_error import s01_proto_pb2_grpc
from sandbox.grpc.s03_connection_error.s01_proto_pb2 import CheckHeartBeatReply
from sandbox.grpc.s03_connection_error.s01_proto_pb2_grpc import GrpcServerServicer


class ProtoService(GrpcServerServicer):
    async def check_heartbeat(self, request, context):
        await asyncio.sleep(15.0)
        return CheckHeartBeatReply()


async def serve(server: grpc.aio.Server):
    s01_proto_pb2_grpc.add_GrpcServerServicer_to_server(ProtoService(), server)
    server.add_insecure_port('127.0.0.1:50051')
    await server.start()

    await server.wait_for_termination()


def main():
    logging.basicConfig(level=logging.DEBUG)
    server = grpc.aio.server()

    loop = asyncio.get_event_loop()
    loop.set_debug(True)
    try:
        loop.run_until_complete(serve(server))
    finally:
        # define server stop task
        async def server_graceful_shutdown():
            await server.stop(grace=0.0)

        try:
            # graceful grpc server stop
            loop.run_until_complete(server_graceful_shutdown())

            # asyncio.run() cleanup
            _cancel_all_tasks(loop)
            loop.run_until_complete(loop.shutdown_asyncgens())
            loop.run_until_complete(loop.shutdown_default_executor())
        finally:
            loop.close()


if __name__ == '__main__':
    main()

```

**Comment by lidizheng** [comment]
I simplified the reproduce snippet, but yet to find a similar behavior on macOS or Linux. This behavior difference might be caused by the heterogenous design of CTRL+C on Windows. On Linux, the KeyboardInterrupt will always be populated to the main thread, so I saw a consistent behavior. But on Windows, it seems the KeyboardInterrupt is being sent to one of our background thread.

I'm not sure what's the fix here. Feel free to suggest. Here are some options I can think of:
1. Should we try to use Python's signal handler?
2. A change in the background thread to let it wake up every 200ms from C space to see if there is any Python signal.

Can you help to double-check if this behavior is only exhibiting on Windows by also testing your snippet on Linux or macOS?

Following is the snippet I used, and the log (I tried to inject CTRL+C at multiple points):

```py
import asyncio
import grpc
import logging

async def main():
    channel =  grpc.aio.insecure_channel('localhost:50051')
    while True:
        try:
            print('Check if channel ready.')
            await asyncio.wait_for(channel.channel_ready(), 20.0)
        except asyncio.TimeoutError as exception:
            print('Connection failed.')
            print(type(exception), exception)
            delay = 2.0
            print(f'Wait {delay}.')
            await asyncio.sleep(delay)
            continue
        print("Nah")

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("Killed by KeyboardInterrupt")
```

```bash
python3 b.py
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Check if channel ready.
^CKilled by KeyboardInterrupt
```

**Comment by ChameleonRed** [comment]
I will try to check it on Linux (I have not Apple)... and try to check it with console not PyCharm - maybe today or tomorrow (it is end of my day today).

I tested many combinations and I can not find good workaround.
Problem is that `channel.get_state()` is not forcing connection same with `wait_for_state_change`. `channel.get_state()` is also not async I think problem can be here `self._channel.check_connectivity_state(try_to_connect)` but I just searching and I am not sure at all. I have to force it with `try_to_connect` which cause problem on asyncio.

Why it is so important because I found that first call of `check_heartbeat_call = s01_proto_pb2.CheckHeartBeatCall()` takes 2s but rest is 2e-4 so I can not judge if server is ready or not in cluster since first call is very slow.

I can make workaround but it is complex - for example call `check_heartbeat_call = s01_proto_pb2.CheckHeartBeatCall()` double time  and waste first call - this is not efficient - It need be fast for example no more 50ms (2.0s is to slow). So maybe `await stub.check_heartbeat(check_heartbeat_call, timeout=0.1)`.

This strange workaround since I forced to implement `stub.check_heartbeat(check_heartbeat_call, timeout=20.0)` in proto - I cannot use `get_state` or functions include in `channel_ready` (it include get_state).

```
    async def channel_ready(self) -> None:
        state = self.get_state(try_to_connect=True)
        while state != grpc.ChannelConnectivity.READY:
            await self.wait_for_state_change(state)
            state = self.get_state(try_to_connect=True)
```

**Comment by lidizheng** [comment]
The method `get_state(try_to_connect=True)` tells gRPC to initiate the connection, but it doesn't block until it is READY. What you observed is right. The `channel_ready()` method on the other hand does initiate the connection and block until READY.

For details in the 2s delay, you can check https://github.com/grpc/grpc/blob/master/doc/environment_variables.md to print more verbose log, e.g., set `GRPC_TRACE=api GRPC_VERBOSITY=debug`.

As for the heartbeat function, there are several other options:
1. You can use our keep alive feature: https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md
2. Or streaming health checking: https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md or usage example https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests_aio/health_check/health_servicer_test.py#L47.

**Comment by ChameleonRed** [comment]
On Windows terminal (powershell - no matter) it exists after one/two Ctrl+C so it is unstable. Now time for Linux.

**Comment by ChameleonRed** [comment]
On Linux Ubuntu Python 3.9.4 (not 3.8.6):

```
cezary@ubuntu20-4server:~/code/medptr-v2/sandbox/grpc/s03_connection_error$ python3 s01_proto_async_client.py
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Check if channel ready.
Connection failed.
<class 'asyncio.exceptions.TimeoutError'>
Wait 2.0.
^CDEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
cezary@ubuntu20-4server:~/code/medptr-v2/sandbox/grpc/s03_connection_error$ python3 s01_proto_async_client.py
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Check if channel ready.
^CDEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
cezary@ubuntu20-4server:~/code/medptr-v2/sandbox/grpc/s03_connection_error$
```

**Comment by ChameleonRed** [comment]
Windows use different loop - so problem is on the Windows only I think so `ProactorEventLoop`. That is different OS and probably `self._channel.check_connectivity_state(try_to_connect)` not works in Windows but is very rough idea without facts to confirm.

```
PS C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\sandbox\grpc\s03_connection_error> python .\s01_01_proto_async_client.py
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Check if channel ready.
Connection failed.
<class 'asyncio.exceptions.TimeoutError'>
Wait 2.0.
DEBUG:asyncio:Close <ProactorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\sandbox\grpc\s03_connection_error\s01_01_proto_async_client.py", line 65, in <module>
    loop.run_until_complete(main())
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\root\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\root\Python\Python39\lib\asyncio\base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\root\Python\Python39\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "C:\root\Python\Python39\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
```

**Comment by ChameleonRed** [comment]
I wait on your response tomorrow if you can answer.

**Comment by lidizheng** [comment]
Sorry, I don't know how `ProactorEventLoop` affects tcp connect. If you are interested, can you help to find out?

**Comment by ChameleonRed** [comment]
If you do not know how Windows asyncio works you can not solve problem and implement GRPC so you should pass error to other expert. It looks only that `self._channel.check_connectivity_state(try_to_connect)` not works which is C++ code. For me it is too deep to analyses this code since I need to know deep GRPC to solve this problem.

Please pass error to other expert.

**Comment by ChameleonRed** [comment]
I found that code which lead to error but I can not understand it since it not my project and not understand Python/C++ binding.

```
grpc_connectivity_state grpc_channel_check_connectivity_state(
    grpc_channel* channel, int try_to_connect) {
  grpc_core::ApplicationCallbackExecCtx callback_exec_ctx;
  grpc_core::ExecCtx exec_ctx;
  GRPC_API_TRACE(
      "grpc_channel_check_connectivity_state(channel=%p, try_to_connect=%d)", 2,
      (channel, try_to_connect));
  // Forward through to the underlying client channel.
  grpc_core::ClientChannel* client_channel =
      grpc_core::ClientChannel::GetFromChannel(channel);
  if (GPR_UNLIKELY(client_channel == nullptr)) {
    gpr_log(GPR_ERROR,
            "grpc_channel_check_connectivity_state called on something that is "
            "not a client channel");
    return GRPC_CHANNEL_SHUTDOWN;
  }
  return client_channel->CheckConnectivityState(try_to_connect);
}
```

[channel_connectivity.cc](https://github.com/grpc/grpc/blob/ca945a58e9ccff69df9815bdb657c4b32e2e6b37/src/core/ext/filters/client_channel/channel_connectivity.cc)

**Comment by lidizheng** [comment]
I meant the Proactor behavior difference than the SelectorEventLoop, on handling the CTRL+C. From what I read and know, the Windows CTRL+C is not the same as Linux-based, and it has caused issues with asyncio in the past: https://bugs.python.org/issue32661 https://bugs.python.org/issue23057.

In this case, the first CTRL+C closes event loop successfully, but require a second CTRL+C to force exit the shutdown process. I can see what I am able to change as a library to prevent this behavior.

**Comment by ChameleonRed** [comment]
It will be nice if you check back library to check why this not works with asyncio on Windows.

Whatever I think that problem really is that some functions are no `async` but should be because they force client to connect.

It is not good that first call have 2.0s overhead at first call and next calls takes about 0.001s.

```
    async def channel_ready(self) -> None:
        state = self.get_state(try_to_connect=True)
        while state != grpc.ChannelConnectivity.READY:
            await self.wait_for_state_change(state)
            state = self.get_state(try_to_connect=True)
```

`get_state` is blocking not async.

**Comment by XuanWang-Amos** [comment]
From what I can see, It's expected to require a second CTRL+C on windows because of different event loop behavior.

And `channel_ready` should be a blocked call as documented [here](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_base_channel.py#L264).

Closing this issue since I don't think there is any action items on our side.
