### ISSUE TITLE
Grpc.Core server rejects gRPC requests forwarded with YARP with "Missing header"

### ISSUE THREAD

**Issue by Tratcher** [grpc/grpc#27065]
---
**Issue moved from microsoft/reverse-proxy#1191**
- Please respond to @mzabsky.

---

_From @mzabsky on Wednesday, August 18, 2021 4:43:54 PM_

### Describe the bug
I have an insecure C# Grpc.Core server and want to forward requests to it via an YARP reverse proxy. The proxy receives the request and then the subsequent HTTP request to the gRPC server fails with an exception:

      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: The request was aborted.
       ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
         --- End of inner exception stack trace ---
         at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
         at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
         at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
         at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

I have followed documentation, namely the [gRPC page](https://microsoft.github.io/reverse-proxy/articles/grpc.html). The most interesting gRPC server trace prints appear to be these "Missing header" and "Missing :authority or :path":

```
I0818 18:27:38.889382 0 ..\..\..\src\core\lib\channel\channel_stack.cc:239: OP[connected:000001FC81FC0CB0]:  CANCEL:{"created":"@1629304058.888000000","description":"Missing :authority or :path","file":"..\..\..\src\core\lib\surface\server.cc","file_line":1421,"referenced_errors":[{"created":"@1629304058.888000000","description":"Failed processing incoming headers","file":"..\..\..\src\core\ext\filters\http\server\http_server_filter.cc","file_line":123,"referenced_errors":[{"created":"@1629304058.888000000","description":"Missing header","file":"..\..\..\src\core\ext\filters\http\server\http_server_filter.cc","file_line":204,"key":"te"}]}]}
I0818 18:27:38.889556 0 ..\..\..\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:1646: perform_stream_op[s=000001FC81FC1A70]:  CANCEL:{"created":"@1629304058.888000000","description":"Missing :authority or :path","file":"..\..\..\src\core\lib\surface\server.cc","file_line":1421,"referenced_errors":[{"created":"@1629304058.888000000","description":"Failed processing incoming headers","file":"..\..\..\src\core\ext\filters\http\server\http_server_filter.cc","file_line":123,"referenced_errors":[{"created":"@1629304058.888000000","description":"Missing header","file":"..\..\..\src\core\ext\filters\http\server\http_server_filter.cc","file_line":204,"key":"te"}]}]}
```
[Full log](https://gist.github.com/mzabsky/e6145fbe34906522958acaccafd85b18)

The call is served properly when I call the gRPC server from the client directly.

### To Reproduce
I have prepared a [reproduction repo](https://github.com/mzabsky/GrpcProxyTest/tree/master/GrpcProxyTest). Just clone the repo, open in VS and F5.

I have also tried the code-first approach outlined [on the Direct Forwarding page](https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html) as well, with same result (having adjusted VersionPolicy in RequestProxyOptions).

### Further technical details
- Windows 10
- VS 16.9.3
- .Net 5.0
- Grpc.Core 2.39.1
- Yarp.ReverseProxy 1.0.0-preview.12.21328.2

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#1191**
- Please respond to @Tratcher.

---

_From @Tratcher on Wednesday, August 18, 2021 5:04:00 PM_

Next steps:
- Get a network capture (Wireshark) between YARP and the destination to see the wire format for the request and if one of these request headers really is missing.
- Getting the debug level logs from YARP would also be useful. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

@mzabsky if you're able to capture those it would help, otherwise we'll get to it.

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#1191**
- Please respond to @mzabsky.

---

_From @mzabsky on Thursday, August 19, 2021 7:14:39 AM_

[Trace logs for the proxy host](https://gist.github.com/mzabsky/b5f3b06a230a7eeb644cbf5dc33c5ce4)
[Wireshark capture for the destination port](https://github.com/microsoft/reverse-proxy/files/7012457/yarp-grpc-1191.pcapng.gz)

The headers:
![image](https://user-images.githubusercontent.com/1764281/130024611-4807a2fa-1d71-4555-8998-e32ebe970d86.png)

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#1191**
- Please respond to @Tratcher.

---

_From @Tratcher on Thursday, August 19, 2021 4:22:08 PM_

Thanks. The Wireshark and the YARP logs are consistent which implies a compat issue at the destination. @JamesNK who's a good person to follow up on the gRPC server end of this?

**Comment by Tratcher** [comment]
---
**Issue moved from microsoft/reverse-proxy#1191**
- Please respond to @JamesNK.

---

_From @JamesNK on Thursday, August 19, 2021 7:35:38 PM_

Create an issue at https://github.com/grpc/grpc

**Comment by mzabsky** [comment]
I followed up a bit more and did a [Wireshark capture of a direct call without forwarding](https://github.com/microsoft/reverse-proxy/files/7019776/direct-grpc-1191.pcapng.gz). Here are the headers:

![image](https://user-images.githubusercontent.com/1764281/130195563-4ad52787-8b34-42ec-b722-2a155158367e.png)

The only header missing in the forwarded request posted above appears to be "te: trailers". I modified the proxy to use HttpForwarder and added the header manually:
```
        private class CustomTransformer : HttpTransformer
        {
            public override async ValueTask TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, string destinationPrefix)
            {
                // Copy headers normally and then remove the original host.
                // Use the destination host from proxyRequest.RequestUri instead.
                await base.TransformRequestAsync(httpContext, proxyRequest, destinationPrefix);
                proxyRequest.Headers.TE.Add(new TransferCodingWithQualityHeaderValue("trailers"));
                proxyRequest.Headers.Host = null;
            }
        }
```
After this modification, the forwarded call suddenly works and the client receives the reply. I have pushed a functional version of the reproduction code with this workaround [to a branch](https://github.com/mzabsky/GrpcProxyTest/tree/workaround).

However, I am not very familiar with HTTP/2 or details of the gRPC protocol so I can't tell if the server should be able to serve the request with the "te" header missing.
