### ISSUE TITLE
pod install failed for examples/objective-c/helloworld

### ISSUE THREAD

**Issue by seaguest** [grpc/grpc#27548]
### What version of gRPC and what language are you using?
objective-c, I tried to run the objective-c grpc example, however pod install failed.

### What operating system (Linux, Windows,...) and version?
macOS big sur.

### What runtime / compiler are you using (e.g. python version or version of gcc)
pod install

### What did you do?

```
git clone git@github.com:grpc/grpc.git

cd grpc/examples/objective-c/helloworld

pod install --verbose

```

### What did you expect to see?
```
pod install succeed, no following error:

     fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Recv failure: Connection reset by peer

```

### What did you see instead?

```
seaguest@DEV helloworld $ pod install --verbose                         
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-HelloWorld`: (``)

Fetching external sources
-> Fetching podspec for `HelloWorld` from `.`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A !ProtoCompiler
  A !ProtoCompiler-gRPCPlugin
  A BoringSSL-GRPC
  A HelloWorld
  A Protobuf
  A abseil
  A gRPC
  A gRPC-Core
  A gRPC-ProtoRPC
  A gRPC-RxLibrary

Downloading dependencies

-> Installing !ProtoCompiler (3.17.3)
  > Copying !ProtoCompiler from `/Users/seaguest/Library/Caches/CocoaPods/Pods/Release/!ProtoCompiler/3.17.3-41c92` to `Pods/!ProtoCompiler`

-> Installing !ProtoCompiler-gRPCPlugin (1.41.0)
  > Copying !ProtoCompiler-gRPCPlugin from `/Users/seaguest/Library/Caches/CocoaPods/Pods/Release/!ProtoCompiler-gRPCPlugin/1.41.0-cba1a` to `Pods/!ProtoCompiler-gRPCPlugin`

-> Installing BoringSSL-GRPC (0.0.20)
  > Copying BoringSSL-GRPC from `/Users/seaguest/Library/Caches/CocoaPods/Pods/Release/BoringSSL-GRPC/0.0.20-3b971` to `Pods/BoringSSL-GRPC`

-> Installing HelloWorld (0.0.1)
 > Running prepare command
   $ /bin/bash -c  set -e mkdir -p Pods/HelloWorld Pods/!ProtoCompiler/protoc         --plugin=protoc-gen-grpc=Pods/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin         --objc_out=Pods/HelloWorld    
   --grpc_out=Pods/HelloWorld         -I ../../protos         -I Pods/!ProtoCompiler         ../../protos/helloworld.proto

-> Installing Protobuf (3.18.0)
  > Copying Protobuf from `/Users/seaguest/Library/Caches/CocoaPods/Pods/Release/Protobuf/3.18.0-1a37e` to `Pods/Protobuf`

-> Installing abseil (1.20210324.0)
  > Copying abseil from `/Users/seaguest/Library/Caches/CocoaPods/Pods/Release/abseil/1.20210324.0-c12ca` to `Pods/abseil`

-> Installing gRPC (1.41.0)
  > Copying gRPC from `/Users/seaguest/Library/Caches/CocoaPods/Pods/Release/gRPC/1.41.0-e8598` to `Pods/gRPC`

-> Installing gRPC-Core (1.41.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/grpc/grpc.git /var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev --template= --single-branch --depth 1 --branch v1.41.0
     Cloning into '/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev'...
     Note: switching to 'fc662b7964384b701af5bd3ce6994d2180080eb4'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     
     Updating files: 100% (9295/9295), done.
     $ /usr/bin/git -C /var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev submodule update --init --recursive
     Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
     Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
     Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
     Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
     Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
     Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
     Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'
     Submodule 'third_party/opencensus-proto' (https://github.com/census-instrumentation/opencensus-proto.git) registered for path 'third_party/opencensus-proto'
     Submodule 'third_party/opentelemetry' (https://github.com/open-telemetry/opentelemetry-proto.git) registered for path 'third_party/opentelemetry'
     Submodule 'third_party/protobuf' (https://github.com/protocolbuffers/protobuf.git) registered for path 'third_party/protobuf'
     Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
     Submodule 'third_party/re2' (https://github.com/google/re2.git) registered for path 'third_party/re2'
     Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
     Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/abseil-cpp'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/benchmark'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/boringssl-with-bazel'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/cares/cares'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/envoy-api'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/googleapis'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/googletest'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/libuv'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/opencensus-proto'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/opentelemetry'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protobuf'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protoc-gen-validate'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/re2'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/udpa'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/zlib'...
     Submodule path 'third_party/abseil-cpp': checked out '997aaf3a28308eba1b9156aa35ab7bca9688e9f6'
     Submodule path 'third_party/benchmark': checked out '73d4d5e8d6d449fc8663765a42aa8aeeee844489'
     Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/googletest'
     Submodule 'third_party/libFuzzer' (https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer) registered for path 'third_party/bloaty/third_party/libFuzzer'
     Submodule 'third_party/re2' (https://github.com/google/re2) registered for path 'third_party/bloaty/third_party/re2'
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/googletest'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer'...
     fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Recv failure: Connection reset by peer
     fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer' failed
     Failed to clone 'third_party/libFuzzer'. Retry scheduled
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/re2'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer'...
     fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Recv failure: Connection reset by peer
     fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer' failed
     Failed to clone 'third_party/libFuzzer' a second time, aborting
     Submodule path 'third_party/boringssl-with-bazel': checked out 'fc44652a42b396e1645d5e72aba053349992136a'
     Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
     Submodule path 'third_party/envoy-api': checked out '2f0d081fab0b0823f088c6e368f40e1992f46fcd'
     Submodule path 'third_party/googleapis': checked out '2f9af297c84c55c8b871ba4495e01ade42476c92'
     Submodule path 'third_party/googletest': checked out 'c9ccac7cb7345901884aabf5d1a786cfa6e2f397'
     Submodule path 'third_party/libuv': checked out '15ae750151ac9341e5945eb38f8982d59fb99201'
     Submodule path 'third_party/opencensus-proto': checked out '4aa53e15cbf1a47bc9087e6cfdca214c1eea4e89'
     Submodule path 'third_party/opentelemetry': checked out '60fa8754d890b5c55949a8c68dcfd7ab5c2395df'
     Submodule path 'third_party/protobuf': checked out '909a0f36a10075c4b4bc70fdee2c7e32dd612a72'
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/protobuf/third_party/googletest'
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protobuf/third_party/benchmark'...
     Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protobuf/third_party/googletest'...
     Submodule path 'third_party/protobuf/third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
     Submodule path 'third_party/protobuf/third_party/googletest': checked out '5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081'
     Submodule path 'third_party/protoc-gen-validate': checked out '59da36e59fef2267fc2b1849a05159e3ecdf24f3'
     Submodule path 'third_party/re2': checked out 'aecba11114cf1fac5497aeb844b6966106de3eb6'
     Submodule path 'third_party/udpa': checked out '6414d713912e988471d192940b62bf552b11793a'
     Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
     Failed to recurse into submodule path 'third_party/bloaty'

[!] Error installing gRPC-Core
[!] /usr/bin/git -C /var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev submodule update --init --recursive

Submodule path 'third_party/abseil-cpp': checked out '997aaf3a28308eba1b9156aa35ab7bca9688e9f6'
Submodule path 'third_party/benchmark': checked out '73d4d5e8d6d449fc8663765a42aa8aeeee844489'
Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
Submodule path 'third_party/boringssl-with-bazel': checked out 'fc44652a42b396e1645d5e72aba053349992136a'
Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
Submodule path 'third_party/envoy-api': checked out '2f0d081fab0b0823f088c6e368f40e1992f46fcd'
Submodule path 'third_party/googleapis': checked out '2f9af297c84c55c8b871ba4495e01ade42476c92'
Submodule path 'third_party/googletest': checked out 'c9ccac7cb7345901884aabf5d1a786cfa6e2f397'
Submodule path 'third_party/libuv': checked out '15ae750151ac9341e5945eb38f8982d59fb99201'
Submodule path 'third_party/opencensus-proto': checked out '4aa53e15cbf1a47bc9087e6cfdca214c1eea4e89'
Submodule path 'third_party/opentelemetry': checked out '60fa8754d890b5c55949a8c68dcfd7ab5c2395df'
Submodule path 'third_party/protobuf': checked out '909a0f36a10075c4b4bc70fdee2c7e32dd612a72'
Submodule path 'third_party/protobuf/third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
Submodule path 'third_party/protobuf/third_party/googletest': checked out '5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081'
Submodule path 'third_party/protoc-gen-validate': checked out '59da36e59fef2267fc2b1849a05159e3ecdf24f3'
Submodule path 'third_party/re2': checked out 'aecba11114cf1fac5497aeb844b6966106de3eb6'
Submodule path 'third_party/udpa': checked out '6414d713912e988471d192940b62bf552b11793a'
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'
Submodule 'third_party/opencensus-proto' (https://github.com/census-instrumentation/opencensus-proto.git) registered for path 'third_party/opencensus-proto'
Submodule 'third_party/opentelemetry' (https://github.com/open-telemetry/opentelemetry-proto.git) registered for path 'third_party/opentelemetry'
Submodule 'third_party/protobuf' (https://github.com/protocolbuffers/protobuf.git) registered for path 'third_party/protobuf'
Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
Submodule 'third_party/re2' (https://github.com/google/re2.git) registered for path 'third_party/re2'
Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/abseil-cpp'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/benchmark'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/boringssl-with-bazel'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/cares/cares'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/envoy-api'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/googleapis'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/googletest'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/libuv'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/opencensus-proto'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/opentelemetry'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protobuf'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protoc-gen-validate'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/re2'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/udpa'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/zlib'...
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/googletest'
Submodule 'third_party/libFuzzer' (https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer) registered for path 'third_party/bloaty/third_party/libFuzzer'
Submodule 'third_party/re2' (https://github.com/google/re2) registered for path 'third_party/bloaty/third_party/re2'
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/googletest'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Recv failure: Connection reset by peer
fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer' failed
Failed to clone 'third_party/libFuzzer'. Retry scheduled
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/re2'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Recv failure: Connection reset by peer
fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/bloaty/third_party/libFuzzer' failed
Failed to clone 'third_party/libFuzzer' a second time, aborting
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/protobuf/third_party/googletest'
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protobuf/third_party/benchmark'...
Cloning into '/private/var/folders/kp/cvx3fsfn5jggmgdlkvh9km500000gn/T/d20211001-69218-k5h3ev/third_party/protobuf/third_party/googletest'...
Failed to recurse into submodule path 'third_party/bloaty'


/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:139:in `execute_command'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/base.rb:166:in `block in executable'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/git.rb:153:in `target_git'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/git.rb:114:in `update_submodules'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/git.rb:101:in `block in clone'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/git.rb:98:in `clone'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/git.rb:66:in `download!'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/base.rb:82:in `block in download'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:156:in `ui_action'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/base.rb:80:in `download'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:108:in `download_source'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:75:in `download_request'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader/cache.rb:171:in `download'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/downloader.rb:42:in `download'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:561:in `install_source_of_pod'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:512:in `block (2 levels) in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:511:in `block in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:494:in `each'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:494:in `install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:253:in `block in download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:252:in `download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:161:in `install!'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/gems/cocoapods-1.10.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/bin/pod:23:in `load'
/opt/homebrew/Cellar/cocoapods/1.10.2/libexec/bin/pod:23:in `<main>'
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
macos

**Comment by seaguest** [comment]
it was a network issue, the original issue was connection to "chromium.googlesource.com" timeout, then I used a proxy, I got this reset by peer problem, Then I have to download the full project on a server which can access that site, and I update the Podfile to:
```
target 'HelloWorld' do
  # Depend on the generated HelloWorld library.
  pod 'gRPC-Core', :path => '~/Downloads/grpc'
  pod 'gRPC-ProtoRPC', :path => '~/Downloads/grpc'
  pod 'gRPC-RxLibrary', :path => '~/Downloads/grpc'
  pod 'HelloWorld', :path => '.'
end
```

finally it works.
