### ISSUE TITLE
GRPC_DEFAULT_SSL_ROOTS_FILE_PATH not respected for Python

### ISSUE THREAD

**Issue by ianonavy** [grpc/grpc#27549]
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jstewmon** [comment]
@ianonavy I'm not sure why reading the file yourself would make a difference, but we were able to resolve the LetsEncrypt issue setting `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=/etc/ssl/certs/ca-certificates.crt` with grpc 1.30.0 and python 3.8.5 on Debian buster, BUT we had to exclude the expired DST cert first:

```shell
sed -i 's~mozilla/DST_Root_CA_X3.crt~!mozilla/DST_Root_CA_X3.crt~' /etc/ca-certificates.conf && \
    update-ca-certificates
```

You may have found a separate issue, but I thought this was worth mentioning.

**Comment by lidizheng** [comment]
@yihuazhang  Can you help to take a look at the creds setup issue?

**Comment by yihuazhang** [comment]
I am confused why `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` does not work for you. gRPC python calls C-core SSL credential API ([here](https://github.com/grpc/grpc/blob/b9a69481c20ac16da8603cf0097beedcb26f1c55/src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi#L156)), and in C-core, it respects the logic of reading from `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` (https://github.com/grpc/grpc/blob/master/src/core/lib/security/security_connector/ssl_utils.cc#L562-L570). The comment from jstewmon@ also indicates that `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` works.

**Comment by ianonavy** [comment]
Alright so using the python [helloworld example client and server](https://github.com/grpc/grpc/tree/8c885f754a03235221a9515cec3e24b22a6a0899/examples/python/helloworld), I was able to consistently reproduce with the latest Debian, Python and grpcio using a self-signed cert. This time instead of trying to use the system chain, I just try to pass the cert through `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH`.

## Setup

`cd` into the `examples/` directory. Create a self-signed cert:

```
openssl req -x509 -out localhost.crt -keyout localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=server\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:server\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

Then create a local test environment with Docker:

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM python:3.9.7

RUN pip install grpcio==1.41.0 grpcio-tools==1.41.0

WORKDIR /app
ADD . /app
```
</details>

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3.7"
services:
  server:
    build: .
    command: ["python", "helloworld/greeter_server.py"]
    volumes:
      - .:/app
  client:
    build: .
    command: ["python", "helloworld/greeter_client.py"]
    volumes:
      - .:/app
    environment:
      GRPC_DEFAULT_SSL_ROOTS_FILE_PATH: "localhost.crt"
```
</details>

Change `greeter_server.py`'s `serve` function to use the new key:

```python
def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)

    with open('localhost.key', 'rb') as f:
        private_key = f.read()
    with open('localhost.crt', 'rb') as f:
        certificate_chain = f.read()
    server_credentials = grpc.ssl_server_credentials( ( (private_key, certificate_chain), ) )
    server.add_secure_port('0.0.0.0:50051', server_credentials)
    server.start()
    server.wait_for_termination()
```

Change `greeter_client.py` to use the new key:

```python
def run():
    print("====> Manually reading certificate chain")

    with open(os.environ.get('GRPC_DEFAULT_SSL_ROOTS_FILE_PATH'), 'rb') as f:
        certificate_chain = f.read()
    creds = grpc.ssl_channel_credentials(certificate_chain)

    with grpc.secure_channel('server:50051', creds) as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
    print("Greeter client received: " + response.message)

    print("====> No argument to get_ssl_credentials")

    creds = grpc.ssl_channel_credentials()

    with grpc.secure_channel('server:50051', creds) as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
    print("Greeter client received: " + response.message)
```

## Run test

Start the server:
```bash
docker compose up server
```

In a separate shell, run the client:
```bash
docker compose run --rm client
```

<details>
<summary>My output here:</summary>

```
➤ docker compose run --rm client
====> Manually reading certificate chain
Greeter client received: Hello, you!
====> No argument to get_ssl_credentials
E1001 21:46:07.493124400       1 ssl_transport_security.cc:1469] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Traceback (most recent call last):
  File "/app/helloworld/greeter_client.py", line 51, in <module>
    run()
  File "/app/helloworld/greeter_client.py", line 45, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1633124767.493368500","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3158,"referenced_errors":[{"created":"@1633124767.493363500","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
>
```

</details>

## Analysis

It would seem like `grpc.ssl_channel_credentials()` does not use `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH`, or at least it isn't loading `localhost.crt` as expected. Am I setting up the credentials incorrectly?

**Comment by ashithasantosh** [comment]
I ran examples from
https://github.com/grpc/grpc/tree/master/examples/python/auth (already uses ssl creds)
Updated `customized_auth_client.py` to use `grpc.ssl_channel_credential()`, in order to retrieve root certificate from specified path.
Set the environment variable
`export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=credentials/root.crt`
And it worked for me. 
Also tried feeding an incorrect path, and it errors out as expected at https://github.com/grpc/grpc/blob/master/src/core/lib/security/security_connector/ssl_utils.cc#L568

I believe the problem here is related to incorrect setup/credentials.

**Comment by sevenam** [comment]
For debugging purposes it might be a good idea to print out the content of the GRPC_DEFAULT_SSL_ROOTS_FILE_PATH environment variable to confirm it contains what you think and is pointing at the correct CA file.

```
import os
thepath = os.environ.get('GRPC_DEFAULT_SSL_ROOTS_FILE_PATH')
print(thepath)
```

In my case the variable was empty as I was using JupyterHub and I had to put the environment variable in the Jupyter kernel.json.
