### ISSUE TITLE
Impossible to use tls with python client

### ISSUE THREAD

**Issue by flokasper** [grpc/grpc#27655]
We setup a simple server and a ALB with the following helm chart:
```
apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: grpc-ingress-gateway1
   annotations:
     kubernetes.io/ingress.class: alb
     alb.ingress.kubernetes.io/backend-protocol-version: GRPC
     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 50000}]'
     alb.ingress.kubernetes.io/certificate-arn: <random-certificate>
 spec:
  backend:
    serviceName: my-grpc-server
    servicePort: 50000
```

A grpcurl works perfectly:
```
grpcurl  -v -insecure -proto my-url:50000  example.ExampleService.ping
```

But the python client doesn't go through:
```
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    responses = c.call_simple_request()
  File "<path>/client.py", line 44, in call_simple_request
    stub.ping(void())
  File "<path>/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "<path>/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1633707025.212783000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1633707025.212779000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
```

With
```
export GRPC_TRACE=all
export GRPC_VERBOSITY=DEBUG
export GODEBUG=http2debug=1
export GODEBUG=http2debug=2
```

We found this trace:
```
D1008 17:35:36.978054000 4545637824 tcp_posix.cc:673]                  DATA: 48 54 54 50 2f 31 2e 31 20 34 30 30 20 42 61 64 20 52 65 71 75 65 73 74 0d 0a 53 65 72 76 65 72 3a 20 61 77 73 65 6c 62 2f 32 2e 30 0d 0a 44 61 74 65 3a 20 46 72 69 2c 20 30 38 20 4f 63 74 20 32 30 32 31 20 31 35 3a 33 35 3a 33 36 20 47 4d 54 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 78 74 2f 68 74 6d 6c 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 31 32 32 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 0d 0a 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 30 20 42 61 64 20 52 65 71 75 65 73 74 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e 0d 0a 3c 62 6f 64 79 3e 0d 0a 3c 63 65 6e 74 65 72 3e 3c 68 31 3e 34 30 30 20 42 61 64 20 52 65 71 75 65 73 74 3c 2f 68 31 3e 3c 2f 63 65 6e 74 65 72 3e 0d 0a 3c 2f 62 6f 64 79 3e 0d 0a 3c 2f 68 74 6d 6c 3e 0d 0a 'HTTP/1.1 400 Bad Request..Server: awselb/2.0..Date: Fri, 08 Oct 2021 15:35:36 GMT..Content-Type: text/html..Content-Length: 122..Connection: close....<html>..<head><title>400 Bad Request</title></head>..<body>..<center><h1>400 Bad Request</h1></center>..</body>..</html>..'
```

We didn't find how to setup tls with the python client.

Version:
python 3.7
grpc 1.41

**Comment by lidizheng** [comment]
In the trace, I found `HTTP/1.1`, gRPC only speaks HTTP/2. This is likely caused by configuration issues in gateway or proxy. For TLS in gRPC, you can find our guide here: https://grpc.io/docs/guides/auth/. The guide includes Python snippets to setup TLS in clients and servers.
