### ISSUE TITLE
context.set_trailing_metadata (hanging grpc async server, lack of documentation, lack of Python typing)

### ISSUE THREAD

**Issue by ChameleonRed** [grpc/grpc#27735]
### What version of gRPC and what language are you using?
1.41

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.10

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

First of all documentation not show type of parameter for:
https://grpc.github.io/grpc/python/grpc_asyncio.html?highlight=set_trailing_metadata#grpc.aio.ServicerContext.set_trailing_metadata

Second no errors at runtime on server - sever hang async call (no error response).
It is not accepatable on production to wait on timeout - it should report error.
```
import asyncio
import logging
import uuid


import grpc
from grpc import ServicerContext, StatusCode

from sandbox.grpc.s04_errors import s01_proto_pb2_grpc
from sandbox.grpc.s04_errors.s01_proto_pb2 import PutFileCall, PutFileReply
from sandbox.grpc.s04_errors.s01_proto_pb2_grpc import FileEngineServicer


class ProtoService(FileEngineServicer):
    def put_file(self, request: PutFileCall, context: ServicerContext):
        # context.set_trailing_metadata((('error', 'error'),))
        context.set_trailing_metadata({'error': 'error'})
        # context.set_trailing_metadata({'error': ('error1', 'error2')})
        context.abort(StatusCode.UNKNOWN, 'wrong')
        return PutFileReply(file_guid=str(uuid.uuid1()))


async def main():
    server = grpc.aio.server()
    s01_proto_pb2_grpc.add_FileEngineServicer_to_server(ProtoService(), server)
    server.add_insecure_port('127.0.0.1:50051')
    await server.start()
    await server.wait_for_termination()

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    asyncio.run(main())
```

Client:
```
import asyncio
import logging

import grpc
from grpc.aio import AioRpcError

from sandbox.grpc.s04_errors import s01_proto_pb2_grpc, s01_proto_pb2


async def main():
    async with grpc.aio.insecure_channel('localhost:50051') as channel:
        stub = s01_proto_pb2_grpc.FileEngineStub(channel)

        call = s01_proto_pb2.PutFileCall(data='x'.encode(), name='x', client_name='x', client_token='x')
        try:
            reply = await stub.put_file(call, timeout=100)
        except AioRpcError as ex:
            print(ex)
        else:
            print(reply)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    asyncio.run(main())
```

Proto:
```
syntax = "proto3";
//import "google/protobuf/empty.proto";

message PutFileCall {
  string client_name = 1;
  string client_token = 2;
  bytes data = 3;
  string name = 5;
}

message PutFileReply {
  string file_guid = 1;
}

service FileEngine {
  rpc put_file(PutFileCall) returns(PutFileReply);
}

```

### What did you expect to see?

Error from server not halt of server (no response to client at all - should success or error).
I think that GRPC internal server has lack of support for such errors.

This code works but it is not explained why I should code this like this and what is possible what not.
`context.set_trailing_metadata((('error', 'error'),))`

This in documentation is not sufficient - why there is not Python typing in GRPC API?

```
metadatum

    A key-value pair included in the HTTP header. It is a 2-tuple where the first entry is the key and the second is the value, i.e. (key, value). The metadata key is an ASCII str, and must be a valid HTTP header name. The metadata value can be either a valid HTTP ASCII str, or bytes. If bytes are provided, the key must end with ‘-bin’, i.e. ('binary-metadata-bin', b'\\x00\\xFF')
metadata

    A sequence of metadatum.
```

Fix documentation too because it is not clear and need not need time consuming analysis how to code it.

### What did you see instead?

No error and server is hang  up (no error response).
Python typing in gRPC API - it is simple to add some typing to reduce not need questions and speed up learning curve.

**Comment by lidizheng** [comment]
@ChameleonRed Wow, thanks a lot for the neat reproduction example. I'm able to reproduce the issues and find root cause easily.

The first issue with the doc: https://grpc.github.io/grpc/python/grpc_asyncio.html?highlight=set_trailing_metadata#grpc.aio.ServicerContext.set_trailing_metadata

You are right, we should document how to use raw tuple-over-tuple metdata, sent PR: https://github.com/grpc/grpc/pull/27768.

The second issue with the hanging. The reason is that by passing a non-asyncio method handler, the compatible mode is triggered on server. The method is delegated to another thread (it's sync, that's the only way). If we update the method handler to following, the error message will show:

```
    async def put_file(self, request: PutFileCall, context: ServicerContext):
        context.set_trailing_metadata(...)
        await context.abort(StatusCode.UNKNOWN, 'wrong')
        return PutFileReply(file_guid=str(uuid.uuid1()))
```

The third issue with server not returning error to the client. The metadata validation is delayed until the Python layer going to 
 talk to the C++ layer, which is the last step of RPC. After the last step failed, there is no more error handling mechanism. This may require a bit more design for how to handle all similar errors.

**Comment by ChameleonRed** [comment]
I tested code after some suggested changes but it still hangs without error.
Added async to def.
Added await to abort.

```
import asyncio
import logging
import uuid


import grpc
from grpc import ServicerContext, StatusCode

from sandbox.grpc.s04_errors import s01_proto_pb2_grpc
from sandbox.grpc.s04_errors.s01_proto_pb2 import PutFileCall, PutFileReply
from sandbox.grpc.s04_errors.s01_proto_pb2_grpc import FileEngineServicer


class ProtoService(FileEngineServicer):
    async def put_file(self, request: PutFileCall, context: ServicerContext):
        # context.set_trailing_metadata((('error', 'error'),))
        context.set_trailing_metadata({'error': 'error'})
        # context.set_trailing_metadata({'error': ('error1', 'error2')})
        await context.abort(StatusCode.UNKNOWN, 'wrong')
        return PutFileReply(file_guid=str(uuid.uuid1()))


async def main():
    server = grpc.aio.server()
    s01_proto_pb2_grpc.add_FileEngineServicer_to_server(ProtoService(), server)
    server.add_insecure_port('127.0.0.1:50051')
    await server.start()
    await server.wait_for_termination()

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    asyncio.run(main(), debug=True)
```

Lead to this error but server hangs client:

```
ERROR:grpc._cython.cygrpc:Unexpected [ValueError] raised by servicer method [/FileEngine/put_file]
Traceback (most recent call last):
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 664, in grpc._cython.cygrpc._handle_exceptions
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 763, in _handle_rpc
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 529, in _handle_unary_unary_rpc
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 386, in _finish_handler_with_unary_response
  File "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\sandbox\grpc\s04_errors\s01_proto_async_server.py", line 19, in put_file
    await context.abort(StatusCode.UNKNOWN, 'wrong')
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 183, in abort
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/callback_common.pyx.pxi", line 184, in _send_error_status_from_server
  File "src\python\grpcio\grpc\_cython\_cygrpc/aio/callback_common.pyx.pxi", line 82, in execute_batch
  File "src\python\grpcio\grpc\_cython\_cygrpc/tag.pyx.pxi", line 64, in grpc._cython.cygrpc._BatchOperationTag.prepare
  File "src\python\grpcio\grpc\_cython\_cygrpc/operation.pyx.pxi", line 105, in grpc._cython.cygrpc.SendStatusFromServerOperation.c
  File "src\python\grpcio\grpc\_cython\_cygrpc/metadata.pyx.pxi", line 41, in grpc._cython.cygrpc._store_c_metadata
ValueError: too many values to unpack (expected 2)
```

Probably it is third issue which you explaned before?

**Comment by ChameleonRed** [comment]
Synchronous server works (not hangs client).

```
import asyncio
import logging
import uuid
from concurrent import futures

import grpc
from grpc import ServicerContext, StatusCode

from sandbox.grpc.s04_errors import s01_proto_pb2_grpc
from sandbox.grpc.s04_errors.s01_proto_pb2 import PutFileCall, PutFileReply
from sandbox.grpc.s04_errors.s01_proto_pb2_grpc import FileEngineServicer


class ProtoService(FileEngineServicer):
    def put_file(self, request: PutFileCall, context: ServicerContext):
        # context.set_trailing_metadata((('error', 'error'),))
        context.set_trailing_metadata({'error': 'error'})
        # context.set_trailing_metadata({'error': ('error1', 'error2')})
        context.abort(StatusCode.UNKNOWN, 'wrong')
        return PutFileReply(file_guid=str(uuid.uuid1()))


def main():
    server = grpc.server(futures.ThreadPoolExecutor())
    s01_proto_pb2_grpc.add_FileEngineServicer_to_server(ProtoService(), server)
    server.add_insecure_port('127.0.0.1:50051')
    server.start()
    server.wait_for_termination()


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main()
```
  Error is reported and client is not hanged.
  
  ```
  "C:\Users\Cezary Wagner\PycharmProjects\medptr-v2\venv\Scripts\python.exe" "C:/Users/Cezary Wagner/PycharmProjects/medptr-v2/sandbox/grpc/s04_errors/s01_proto_async_client.py"
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
<AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "wrong"
	debug_error_string = "{"created":"@1634821890.738000000","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"wrong","grpc_status":2}"
>

Process finished with exit code 0
```
