### ISSUE TITLE
Issue with gRPC channel class missing `request` method 

### ISSUE THREAD

**Issue by EwanValentine** [grpc/grpc#27817]
### What operating system (Linux, Windows,...) and version?

`OSx Big Sur 11.5.2`

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.9

### What did you do?

Generated a Python client using `protoc-gen-grpclib_python`, attempted to use the generated client:

```python
import sys
import asyncio

sys.path.insert(0, '../clients/python')

import grpc

from proto.hot_storage_pb2 import SetRequest, GetRequest
from proto.hot_storage_grpc import HotStorageServiceStub

from google.protobuf import struct_pb2 as struct

async def main():
    with grpc.insecure_channel('0.0.0.0:9000') as channel:
        stub = HotStorageServiceStub(channel=channel)

        await stub.Set(SetRequest(key='key', values=struct.Struct(fields={'value': struct.Value(string_value='value')})))
        result = await stub.Get(GetRequest(key='key'))
        print(result)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

### What did you expect to see?

I expected the code snippet to call my gRPC server, and return a result. 

### What did you see instead?

Instead, I got the following error:

```
Traceback (most recent call last):
  File "/Users/ewanvalentine/work/hot-storage-rollout/playground/test.py", line 24, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ewanvalentine/work/hot-storage-rollout/playground/test.py", line 17, in main
    await stub.Set(SetRequest(key='key', values=struct.Struct(fields={'value': struct.Value(string_value='value')})))
  File "/Users/ewanvalentine/work/hot-storage-rollout/playground/venv/lib/python3.9/site-packages/grpclib/client.py", line 881, in __call__
    async with self.open(timeout=timeout, metadata=metadata) as stream:
  File "/Users/ewanvalentine/work/hot-storage-rollout/playground/venv/lib/python3.9/site-packages/grpclib/client.py", line 853, in open
    return self.channel.request(self.name, self._cardinality,
AttributeError: 'Channel' object has no attribute 'request'
```

### Anything else we should know about your project / environment?

`$ pip freeze .` generates:

```
asyncio==3.4.3
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.7
coverage==6.0.2
Cython==0.29.24
google-api-core==2.1.1
google-api-python-client==2.27.0
google-auth==2.3.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.53.0
greenlet==1.1.1
grpcio==1.41.0
grpcio-tools==1.41.0
grpclib==0.4.2
h2==4.1.0
hpack==4.0.0
httplib2==0.20.1
hyperframe==6.0.1
idna==3.3
msgpack==1.0.2
multidict==5.2.0
mypy-extensions==0.4.3
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pynvim==0.4.3
pyparsing==2.4.7
python-engineio==3.12.1
requests==2.26.0
rsa==4.7.2
ruamel.yaml==0.16.13
ruamel.yaml.clib==0.2.6
six==1.16.0
typed-argument-parser==1.7.1
typing-extensions==3.10.0.2
typing-inspect==0.7.1
uritemplate==4.1.1
urllib3==1.26.7
```

**Comment by drfloob** [comment]
>   File "/Users/ewanvalentine/work/hot-storage-rollout/playground/venv/lib/python3.9/site-packages/grpclib/client.py", line 853, in open
    return self.channel.request(self.name, self._cardinality,
AttributeError: 'Channel' object has no attribute 'request'

The error is in `grpclib`, which is a separate project: https://github.com/vmagamedov/grpclib.

**Comment by EwanValentine** [comment]
Oh! My apologies @drfloob, silly me!

**Comment by nflux-pyang** [comment]
How did you solve it, I got the same problem

**Comment by KiranHighNote** [comment]
I am also having same issue.. How is that fixed?

**Comment by atulsriv** [comment]
Anyone have any contributions to the above issue?
