### ISSUE TITLE
gRPC does not build without a connection to the internet

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#27819]
### What version of gRPC and what language are you using?

HEAD

### What operating system (Linux, Windows,...) and version?

Mac, recent (work laptop)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Bazel

### What did you do?

Ran `tools/bazel build test/core/slice:slice_test`

### What did you expect to see?

Lots of compilation failures - I'm mid-refactoring :)

### What did you see instead?

```
ctiller@ctiller-macbookpro2 ~/grpc (a-_____-of-heaven)> tools/bazel build test/core/slice:slice_test
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 4.2.1 will be used instead of system-wide bazel installation.
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
DEBUG: /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_msan not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:11:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: mirror.bazel.build
ERROR: An error occurred during the fetch of repository 'remote_coverage_tools':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip] to /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/remote_coverage_tools/temp5958440819841394632/coverage_output_generator-v2.5.zip: Unknown host: mirror.bazel.build
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip] to /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/remote_coverage_tools/temp5958440819841394632/coverage_output_generator-v2.5.zip: Unknown host: mirror.bazel.build
INFO: Repository com_google_googletest instantiated at:
  /Users/ctiller/grpc/WORKSPACE:5:10: in <toplevel>
  /Users/ctiller/grpc/bazel/grpc_deps.bzl:226:21: in grpc_deps
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/bazel_tools/tools/test/BUILD:36:6: @bazel_tools//tools/test:coverage_report_generator depends on @remote_coverage_tools//:coverage_report_generator in repository @remote_coverage_tools which failed to fetch. no such package '@remote_coverage_tools//': java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip] to /private/var/tmp/_bazel_ctiller/edf50bce8d85d243d54717c19741e75b/external/remote_coverage_tools/temp5958440819841394632/coverage_output_generator-v2.5.zip: Unknown host: mirror.bazel.build
ERROR: Analysis of target '//test/core/slice:slice_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 21.540s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (44 packages loaded, 1405 targets configured)
ctiller@ctiller-macbookpro2 ~/grpc (a-_____-of-heaven) [1]> 
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
@ctiller ping
