### ISSUE TITLE
Problem or Bug with Async. Interceptor

### ISSUE THREAD

**Issue by Askill** [grpc/grpc#27941]
### What version of gRPC and what language are you using?
Using python3.8 and version 1.41.1 of the library

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python3.8

### What did you do?
I used the example code in https://github.com/grpc/grpc/tree/2231c2ba77cf22f3c8c302d91209c1c3f2f0632f/examples/python/interceptors/headers

For an existing code base which uses aio.server() and I am getting the error:

ERROR:grpc._cython.cygrpc:Unexpected [AttributeError] raised by servicer method [/<replacedMethodName>]
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 664, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 762, in _handle_rpc
AttributeError: 'coroutine' object has no attribute 'request_streaming'

I know the example was meant for non aio, but I can't nail the error down.

### Anything else we should know about your project / environment?
There should be nothing special about the environment.

**Comment by Askill** [comment]
Okay this wasn't a bug, but my fault. I simply used the example not realising that aio uses async functions.

I am using the following interceptor to check if the username and password in the header are correct:

``` python
class RequestHeaderValidatorInterceptor(grpc.aio.ServerInterceptor):
    def __init__(
        self,
        header_key_1: str,
        header_key_2: str,
        name: str,
        password: str,
        code: int,
        details: str,
    ):
        super().__init__()
        self._header_key_1: str = header_key_1
        self._header_key_2: str = header_key_2
        self._name: str = name
        self._password: str = password
        self._terminator: grpc.RpcMethodHandler = _unary_unary_rpc_terminator(
            code, details
        )

    # https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests_aio/unit/server_interceptor_test.py#L42
    async def intercept_service(
        self, continuation, handler_call_details
    ) -> grpc.RpcMethodHandler:
        metadata = dict([tuple(x) for x in handler_call_details.invocation_metadata])
        if metadata[self._header_key_1] == self._name and metadata[self._header_key_2] == self._password:
            return await continuation(handler_call_details)
        else:
            return self._terminator
```

Note the ```return await continuation(handler_call_details)```, in the original example this is simply a ```return```, but since the continuation function is async we have to add the await.
