### ISSUE TITLE
pip install fails with "No such file or directory: 'c++': 'c++'"

### ISSUE THREAD

**Issue by LongZaiAiYueLiang** [grpc/grpc#28166]
**What version of gRPC and what language are you using?**
grpcio-1.33.2 for python

**What operating system (Linux, Windows,...) and version?**
Linux 4.19.36-vhulk1907.1.0.h702.eulerosv2r8.aarch64 aarch64

**What runtime / compiler are you using (e.g. python version or version of gcc)**
Python 3.7

What did you do?
pip37 install grpcio

**What did you expect to see?**
Installed!

**What did you see instead?**
Collecting grpcio==1.33.2
  Downloading https://mirrors.aliyun.com/pypi/packages/cc/1e/5d65ae830536fdb67f10f4bcedca6eb59190ad60d20d796ef3ccdfda4797/grpcio-1.33.2.tar.gz (20.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-osmsrcd0/grpcio_c86f4fb2b5d9450dafcf404743286f5b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-osmsrcd0/grpcio_c86f4fb2b5d9450dafcf404743286f5b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bl374nfd
         cwd: /tmp/pip-install-osmsrcd0/grpcio_c86f4fb2b5d9450dafcf404743286f5b/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-osmsrcd0/grpcio_c86f4fb2b5d9450dafcf404743286f5b/setup.py", line 224, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-osmsrcd0/grpcio_c86f4fb2b5d9450dafcf404743286f5b/setup.py", line 174, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'
    ----------------------------------------
WARNING: Discarding https://mirrors.aliyun.com/pypi/packages/cc/1e/5d65ae830536fdb67f10f4bcedca6eb59190ad60d20d796ef3ccdfda4797/grpcio-1.33.2.tar.gz#sha256=21265511880056d19ce4f809ce3fbe2a3fa98ec1fc7167dbdf30a80d3276202e (from https://mirrors.aliyun.com/pypi/simple/grpcio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement grpcio==1.33.2 (from versions: 0.4.0a0, 0.4.0a1, 0.4.0a2, 0.4.0a3, 0.4.0a4, 0.4.0a5, 0.4.0a6, 0.4.0a7, 0.4.0a8, 0.4.0a13, 0.4.0a14, 0.5.0a0, 0.5.0a1, 0.5.0a2, 0.9.0a0, 0.9.0a1, 0.10.0a0, 0.11.0b0, 0.11.0b1, 0.12.0b0, 0.13.0, 0.13.1rc1, 0.13.1, 0.14.0rc1, 0.14.0, 0.15.0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.3, 1.2.0, 1.2.1, 1.3.0, 1.3.5, 1.4.0, 1.6.0, 1.6.3, 1.7.0, 1.7.3, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.6, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1rc1, 1.10.1rc2, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.12.0rc1, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0rc3, 1.13.0, 1.14.0rc1, 1.14.0rc2, 1.14.0, 1.14.1, 1.14.2rc1, 1.14.2, 1.15.0rc1, 1.15.0, 1.16.0rc1, 1.16.0, 1.16.1rc1, 1.16.1, 1.17.0rc1, 1.17.0, 1.17.1rc1, 1.17.1, 1.18.0rc1, 1.18.0, 1.19.0rc1, 1.19.0, 1.20.0rc1, 1.20.0rc2, 1.20.0rc3, 1.20.0, 1.20.1, 1.21.0rc1, 1.21.1rc1, 1.21.1, 1.22.0rc1, 1.22.0, 1.22.1, 1.23.0rc1, 1.23.0, 1.23.1, 1.24.0rc1, 1.24.0, 1.24.1, 1.24.3, 1.25.0rc1, 1.25.0, 1.26.0rc1, 1.26.0, 1.27.0rc1, 1.27.0rc2, 1.27.1, 1.27.2, 1.28.0.dev0, 1.28.0rc1, 1.28.0rc2, 1.28.0rc3, 1.28.1, 1.29.0, 1.30.0rc1, 1.30.0, 1.31.0rc1, 1.31.0rc2, 1.31.0, 1.32.0rc1, 1.32.0, 1.33.0rc1, 1.33.0rc2, 1.33.1, 1.33.2, 1.34.0rc1, 1.34.0, 1.34.1, 1.35.0rc1, 1.35.0, 1.36.0rc1, 1.36.0, 1.36.1, 1.37.0rc1, 1.37.0, 1.37.1, 1.38.0rc1, 1.38.0, 1.38.1, 1.39.0rc1, 1.39.0, 1.40.0rc1, 1.40.0, 1.41.0rc2, 1.41.0, 1.41.1, 1.42.0rc1, 1.42.0)
ERROR: No matching distribution found for grpcio==1.33.2

**Anything else we should know about your project / environment?**
pip is installing all other packages with no problem.

Dockerfile，the python image version I use is Linux / arm / V8. This image is very compact without apt or yum
```
FROM python:3.7-alpine3.14@sha256:9be7f02f5dac06e855ed90a42863934785c48956350712a8bf4005d2a8f34ae5

RUN pip install grpcio==1.33.2
```

**Comment by LongZaiAiYueLiang** [comment]
It has been solved. The solution is
```
apk add build-base linux-headers
```
