### ISSUE TITLE
cloud_to_prod aspnetcore interop tests failing continuously

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#28233]
Example failure:

```
Runtime: 6.0.0-rtm.21522.10+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6
Use TLS: True
Use WinHttp: False
Use HTTP/3: False
Use GrpcWebMode:
Use Test CA: False
Client type: httpclient
Server host: grpc-test.sandbox.googleapis.com
Server port: 443
[40m[32minfo[39m[22m[49m: Grpc.Shared.TestAssets.InteropClient[0]
      Running compute_engine_creds
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[1]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Starting gRPC call. Method type: 'Unary', URI: 'https://grpc-test.sandbox.googleapis.com/grpc.testing.TestService/UnaryCall'.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.Resolver[4]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Resolver result with status code 'OK' and 1 addresses.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[1]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Subchannel id '1' created with addresses: grpc-test.sandbox.googleapis.com:443
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Channel picker updated.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[4]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Subchannel id '1' connection requested.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[11]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.PickFirstBalancer[1]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Processing subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[3]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Channel state updated to Connecting.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[6]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Subchannel id '1' connecting to transport.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[11]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Subchannel id '1' state changed to Ready. Detail: 'Passively connected.'.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.PickFirstBalancer[1]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Processing subchannel id '1' state changed to Ready. Detail: 'Passively connected.'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[3]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Channel state updated to Ready.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Channel picker updated.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.Resolver[1]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Resolver refresh requested.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[5]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Pick started.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[6]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Successfully picked subchannel id '1' with address Unspecified/grpc-test.sandbox.googleapis.com:443.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[18]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Sending message.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[21]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Serialized 'Grpc.Testing.SimpleRequest' to 271844 byte message.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[19]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Message sent.
[40m[37mtrce[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[2]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Response headers received.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[13]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Reading message.
[41m[30mfail[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[17]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Error reading message.
System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageContent(Stream responseStream, Memory`1 messageData, Int32 length, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/StreamExtensions.cs:line 224
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/StreamExtensions.cs:line 112
[40m[32minfo[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[3]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error starting gRPC call. IOException: The request was aborted. IOException: The response ended prematurely while waiting for the next frame from the server.'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[4]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      Finished gRPC call.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[8]
      => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
      gRPC call canceled.
[40m[32minfo[39m[22m[49m: Grpc.Shared.TestAssets.InteropClient[0]
      Failed!
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. IOException: The request was aborted. IOException: The response ended prematurely while waiting for the next frame from the server.", DebugException="System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageContent(Stream responseStream, Memory`1 messageData, Int32 length, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/StreamExtensions.cs:line 224
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/StreamExtensions.cs:line 112
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Grpc.Shared.TestAssets.InteropClient.RunComputeEngineCreds(IChannelWrapper channel, ClientOptions options) in /var/local/git/grpc-dotnet/testassets/Shared/InteropClient.cs:line 429
   at Grpc.Shared.TestAssets.InteropClient.RunTestCaseAsync(IChannelWrapper channel, ClientOptions options) in /var/local/git/grpc-dotnet/testassets/Shared/InteropClient.cs:line 295
   at Grpc.Shared.TestAssets.InteropClient.Run() in /var/local/git/grpc-dotnet/testassets/Shared/InteropClient.cs:line 86
Unhandled exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. IOException: The request was aborted. IOException: The response ended prematurely while waiting for the next frame from the server.", DebugException="System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageContent(Stream responseStream, Memory`1 messageData, Int32 length, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/StreamExtensions.cs:line 224
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/StreamExtensions.cs:line 112
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Grpc.Shared.TestAssets.InteropClient.RunComputeEngineCreds(IChannelWrapper channel, ClientOptions options) in /var/local/git/grpc-dotnet/testassets/Shared/InteropClient.cs:line 429
   at Grpc.Shared.TestAssets.InteropClient.RunTestCaseAsync(IChannelWrapper channel, ClientOptions options) in /var/local/git/grpc-dotnet/testassets/Shared/InteropClient.cs:line 295
   at Grpc.Shared.TestAssets.InteropClient.Run() in /var/local/git/grpc-dotnet/testassets/Shared/InteropClient.cs:line 86
   at InteropTestsClient.Program.<>c.<<Main>b__0_1>d.MoveNext() in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/Program.cs:line 71
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

https://source.cloud.google.com/results/invocations/734675e8-1bcc-4219-8bd7-bed883a9cdb7/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_prod:aspnetcore:default:server_streaming:tls;row=2

This seems to be failing 100% in the most recent handful of runs today, but it has been flaking - passing on and off at least since November 29th. I'm having trouble seeing failure history back further to see exactly when this started.

**Comment by apolcyn** [comment]
cc @JamesNK @jtattermusch

**Comment by apolcyn** [comment]
This looks like a duplicate of https://github.com/grpc/grpc-dotnet/issues/1511

**Comment by JamesNK** [comment]
grpc-dotnet issue: https://github.com/grpc/grpc-dotnet/issues/1511

I can't repo when callings the server from my local machine.

I have a PR to add lower-level logs: https://github.com/grpc/grpc-dotnet/pull/1513
@apolcyn Could you approve?
