### ISSUE TITLE
grpc_basictests_ruby  presubmit test flake 

### ISSUE THREAD

**Issue by dennycd** [grpc/grpc#28404]
As seen in 
* https://source.cloud.google.com/results/invocations/b15af7c6-79f0-4882-ad5e-dd8b31c115d0/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_basictests_ruby/log

```
run_tests_329bf6b8-7700-41ec-be42-130ca6140edc
+ exit 2
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1612, in <module>
    env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 2

2021-12-22 10:29:08,656 FAILED: run_tests_ruby_linux_dbg_native [ret=1, pid=15805, time=1979.3sec]
2021-12-22 10:32:21,892 PASSED: run_tests_ruby_linux_opt_native [time=2172.5sec, retries=0:0]
2021-12-22 10:32:21,935 FAILED: Some run_tests.py instances have failed.
```

**Comment by yashykt** [comment]
Closing since we decided not to track test flakes on github
