### ISSUE TITLE
[FLAKE] Ruby: GemNotFound: Could not find gem 'facter (~> 2.4)'

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#28483]
```
+ bundle exec rake gem:native
bundler: failed to load command: rake (/usr/local/rvm/rubies/ruby-2.4.1/bin/rake)
Bundler::GemNotFound: Could not find gem 'facter (~> 2.4)' in any of the gem sources listed in your Gemfile.
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/resolver.rb:255:in `each'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/resolver.rb:49:in `start'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/resolver.rb:22:in `resolve'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/definition.rb:258:in `resolve'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

https://source.cloud.google.com/results/invocations/8ebb54cf-fd93-4170-801c-924d33612fdc/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_build_artifacts/log

**Comment by apolcyn** [comment]
fixed by https://github.com/grpc/grpc/pull/28522
