### ISSUE TITLE
 symbol not found in flat namespace '_gpr_asprintf'

### ISSUE THREAD

**Issue by ag-303** [grpc/grpc#28509]
### What version of gRPC and what language are you using?
GRPC 1.42.0

### What operating system (Linux, Windows,...) and version?
Mac OS (Monterey) - M1 chip

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
1. clone the repository.
2. gem install bundler
3. bundle install
4. rake

### What did you expect to see?
all rake test pass

### What did you see instead?
```
...
Running RuboCop...
Inspecting 78 files
..............................................................................

78 files inspected, no offenses detected
** Execute suite:wrapper
/Users/--/.asdf/installs/ruby/2.5.0/bin/ruby -I/Users/--/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-support-3.10.3/lib:/Users/--/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib /Users/--/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/debug_message_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/errors_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb src/ruby/spec/user_agent_spec.rb

An error occurred while loading spec/spec_helper.
Failure/Error: return gem_original_require(path)

LoadError:
  dlopen(/Users/--/outside/grpc/src/ruby/lib/grpc/grpc_c.bundle, 0x0009): symbol not found in flat namespace '_gpr_asprintf' - /Users/--/outside/grpc/src/ruby/lib/grpc/grpc_c.bundle
# ./src/ruby/lib/grpc/grpc.rb:22:in `<top (required)>'
# ./src/ruby/lib/grpc.rb:19:in `require_relative'
# ./src/ruby/lib/grpc.rb:19:in `<top (required)>'
# ./src/ruby/spec/spec_helper.rb:34:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00005 seconds (files took 0.28582 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00005 seconds (files took 0.28582 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


Coverage report generated for wrapper to /Users/--/outside/grpc/coverage. 78 / 152 LOC (51.32%) covered.
/Users/--/.asdf/installs/ruby/2.5.0/bin/ruby -I/Users/--/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-support-3.10.3/lib:/Users/--/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib /Users/--/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/exe/rspec src/ruby/spec/call_credentials_spec.rb src/ruby/spec/call_spec.rb src/ruby/spec/channel_connection_spec.rb src/ruby/spec/channel_credentials_spec.rb src/ruby/spec/channel_spec.rb src/ruby/spec/client_auth_spec.rb src/ruby/spec/client_server_spec.rb src/ruby/spec/compression_options_spec.rb src/ruby/spec/debug_message_spec.rb src/ruby/spec/error_sanity_spec.rb src/ruby/spec/errors_spec.rb src/ruby/spec/google_rpc_status_utils_spec.rb src/ruby/spec/server_credentials_spec.rb src/ruby/spec/server_spec.rb src/ruby/spec/spec_helper.rb src/ruby/spec/time_consts_spec.rb src/ruby/spec/user_agent_spec.rb failed
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I have set LDFLAGS, CPPFLAGS and PKG_CONFIG_PATH. they did not change anything:
```
ASDF_DIR=/opt/homebrew/opt/asdf/libexec
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
LDFLAGS=-L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/libpq/lib
CPPFLAGS=-I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/libpq/include
PKG_CONFIG_PATH=/opt/homebrew/opt/zlib/lib/pkgconfig /opt/homebrew/opt/libpq/lib/pkgconfig
```

**Comment by ag-303** [comment]
i tried to take a look at the symbol table of the compiled library. maybe a compile option does not work or missed for arm64?
[compare two symbol tables](https://i.ibb.co/0qMnQnx/Screenshot-2022-01-11-at-13-22-07.png)

**Comment by kuntoaji** [comment]
It seems you need to upgrade your Ruby version. I use Ruby 2.7.1 and get same the same error on my M1 Mac. I upgrade Ruby to version 2.7.5 and it works fine now.

**Comment by ag-303** [comment]
it worked. thank you @kuntoaji

**Comment by keshandrr** [comment]
2.7.4 Works fine too for me

**Comment by Bashorun97** [comment]
Upgrading grpc to version 1.43.1 worked for me.

**Comment by emm26** [comment]
I am facing the same issue on:
- ruby 2.3.8p459 (2018-10-18 revision 65136) [-darwin21]
- grpc (1.35.0)
- macOS Monterey
- M1 pro chip

**Comment by kuntoaji** [comment]
> I am facing the same issue on:
> 
> * ruby 2.3.8p459 (2018-10-18 revision 65136) [-darwin21]
> * grpc (1.35.0)
> * macOS Monterey
> * M1 pro chip
> 
> Sadly upgrading ruby is not a valid option at this time

As an alternative, you can use docker. In my case, all my projects with the old version of Ruby and Grpc were successfully installed on M1 Mac pro with docker.

**Comment by lporras** [comment]
I'm using `grpc (1.43.1)` and I have ruby 2.6.6 installed using asdf, and every time I run a ruby command like `rake db:create` I'm getting this error:

```
grpc-1.43.1/src/ruby/lib/grpc/grpc_c.bundle, 0x0009): symbol not found in flat namespace (_gpr_asprintf)
```
