### ISSUE TITLE
Memory leak from cronet channel

### ISSUE THREAD

**Issue by qlisc** [grpc/grpc#28713]
### What version of gRPC and what language are you using?
v1.33.2 C++

### What operating system (Linux, Windows,...) and version?

IOS&MacOS, Android (we use same c++ code)

### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc Apple clang version 12.0.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

We are using cronet channel with gRPC-C++ library. The cronet channel creation example code.
std::shared_ptrgrpc::ChannelCredentials cronetChannelCredentials =
grpc::CronetChannelCredentials([Cronet getGlobalEngine]);
auto channel = grpc::CreateChannel(target, cronetChannelCredentials);

We perform regular operation send&receive gRPC request then close cronet channel after client job finished.

### What did you expect to see?
No memory leak

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Memory memory leak detect tool detects the memory leak of a made_transport_op object created  [here](https://github.com/grpc/grpc/blob/v1.33.x/src/core/lib/transport/transport.cc#L228), which is called from [channel destructor](https://github.com/grpc/grpc/blob/v1.33.x/src/core/lib/surface/channel.cc#L515). This object is never released.
Here is the captured call stack. It should be reproduced by any tests using cronet channel in gRPC-C++. 

 #0 0x10eedfbdd in wrap__Znwm+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x51bdd)
    #1 0x1054b2602 in grpc_make_transport_op(grpc_closure*) transport.cc:228
    #2 0x10549bbd4 in grpc_channel_destroy_internal(grpc_channel*) channel.cc:515
    #3 0x10549bd50 in grpc_channel_destroy channel.cc:528
    #4 0x10539de0a in grpc::Channel::~Channel() channel_cc.cc:57
    #5 0x1053a0e16 in std::__1::__shared_ptr_pointer<grpc::Channel*, std::__1::shared_ptr<grpc::Channel>::__shared_ptr_default_delete<grpc::Channel, grpc::Channel>, std::__1::allocator<grpc::Channel> >::__on_zero_shared() memory:3265
    #6 0x10422b641 in std::__1::__shared_count::__release_shared() memory:2475
    #7 0x10422b588 in std::__1::__shared_weak_count::__release_shared() memory:2517
    #8 0x10433942b in std::__1::shared_ptr<grpc::Channel>::~shared_ptr() memory:3212
  ...

There is no memory leak if we use http2/ssl channel in gRPC-C++. We suspect the transport_op cleanup might not be implemented/handled properly in cronet transport module.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment]
We dropped support for the cronet transport a while back, so this is obsolete.
