### ISSUE TITLE
`grpc_health.v1._async.HealthServicer.Watch` is not considered as an async generator when there is a server interceptor

### ISSUE THREAD

**Issue by ysk24ok** [grpc/grpc#28728]
### What version of gRPC and what language are you using?

Python 3.9.9
grpio 1.43.0
grpcio-health-checking 1.43.0

### What operating system (Linux, Windows,...) and version?

macOS Big Sur 11.6.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

```console
% gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
% python3 --version
Python 3.9.9
```

### What did you do?

Here's the server.

```py
import asyncio

import grpc

from grpc_health.v1.health_pb2_grpc import add_HealthServicer_to_server
from grpc_health.v1._async import HealthServicer


class MyServerInterceptor(grpc.aio.ServerInterceptor):
    async def intercept_service(self, continuation, handler_call_details):
        def wrap_unary_unary(behavior):
            async def new_unary_unary(request, context):
                response = await behavior(request, context)
                print(response)  # to show this interceptor works
                return response

            return new_unary_unary

        def wrap_unary_stream(behavior):
            async def new_unary_stream(request, context):
                async for response in behavior(request, context):
                    print(response)  # to show this interceptor works
                    yield response

            return new_unary_stream

        handler = await continuation(handler_call_details)
        if handler.response_streaming:
            return grpc.unary_stream_rpc_method_handler(
                wrap_unary_stream(handler.unary_stream),
                request_deserializer=handler.request_deserializer,
                response_serializer=handler.response_serializer,
            )
        else:
            return grpc.unary_unary_rpc_method_handler(
                wrap_unary_unary(handler.unary_unary),
                request_deserializer=handler.request_deserializer,
                response_serializer=handler.response_serializer,
            )


async def serve() -> None:
    server = grpc.aio.server(interceptors=(MyServerInterceptor(),))
    add_HealthServicer_to_server(HealthServicer(), server)
    listen_addr = "localhost:50051"
    server.add_insecure_port(listen_addr)
    await server.start()
    await server.wait_for_termination()


if __name__ == "__main__":
    asyncio.run(serve())
```

Here's the client.

```py
import asyncio

import grpc
from grpc_health.v1.health_pb2 import HealthCheckRequest
from grpc_health.v1.health_pb2_grpc import HealthStub


async def run(port: int) -> None:
    async with grpc.aio.insecure_channel(f"localhost:{port}") as channel:
        stub = HealthStub(channel)
        request = HealthCheckRequest()
        async for response in stub.Watch(request):
            print(response)


if __name__ == "__main__":
    port = 50051
    asyncio.run(run(port))
```

Execute the server and the client.

### What did you expect to see?

`status: SERVING` is shown in the client's console.
The server does not throw an exception.

### What did you see instead?

The server's console.

```
/Users/y-nishioka/repos/grpc/health_check_async_server.py:21: RuntimeWarning: coroutine 'HealthServicer.Watch' was never awaited
  async for response in behavior(request, context):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

The client's console.

```
Traceback (most recent call last):
  File "/Users/y-nishioka/repos/grpc/health_check_async_client.py", line 19, in <module>
    asyncio.run(run(port))
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/y-nishioka/repos/grpc/health_check_async_client.py", line 12, in run
    async for response in stub.Watch(request):
  File "/Users/y-nishioka/repos/grpc/venv/lib/python3.9/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/Users/y-nishioka/repos/grpc/venv/lib/python3.9/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'TypeError'>: 'async for' requires an object with __aiter__ method, got coroutine"
        debug_error_string = "{"created":"@1643285974.296514000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Unexpected <class 'TypeError'>: 'async for' requires an object with __aiter__ method, got coroutine","grpc_status":2}"
>
```

Looks like `HealthServicer.Wait()` is considered as a coroutine, not async generator, probably because the method does not have `yield` inside.  That's why `async for response in behavior(request, context)` in the server interceptor does not work.

**Comment by lidizheng** [comment]
@ysk24ok Sorry for the late reply. The AsyncIO API support two methods of writing a message to streaming responses (see [doc](https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.StreamStreamCall):

1. Using the `read`/`write` method;
2. Using the function body as an async generator.

In terms of server interceptors, the interceptor here unfortunately expected to do extra work here to support both output methods. For example, here is one way to inject logic to write:

```
class AsyncIOContextWrapper:

    def __init__(self, parent_context):
        self._parent_context = parent_context

    def __getattr__(self, attr):
        if attr == "write":
            # logic
            pass
        return getattr(self._parent_context, attr)
```

```
return behavior(request, AsyncIOContextWrapper(context))
```

**Comment by ysk24ok** [comment]
Thank you for your response. I didn't know read/write API ...

I found that adding read/write methods to `AsyncIOContextWrapper` might be more useful in terms of customizability.

```py
class AsyncIOContextWrapper:
    def __init__(self, parent_context):
        self._parent_context = parent_context

    def __getattr__(self, name):
        return getattr(self._parent_context, name)

    async def read(self):
        print("before read")
        message = await self._parent_context.read()
        print("after read")
        return message

    async def write(self, message):
        print("before write")
        await self._parent_context.write(message)
        print("after write")
```

Streaming response methods can use either of the APIs, so server interceptors have to deal with both cases. It should look like this:

```py
def wrap_behavior(behavior):
    async def new_behavior_for_coro(request, context):
        context_wrapper = AsyncIOContextWrapper(context)
        return await behavior(request, context_wrapper)
                                                                                                       
    async def new_behavior_for_asyncgen(request, context):
        async for response in behavior(request, context):
            print("before response")
            yield response
            print("after response")
                                                                                                       
    return new_behavior_for_asyncgen if inspect.isasyncgenfunction(behavior) else new_behavior_for_coro
```

Also it might be better that `examples/python` directory has an example for async interceptors.
Anyway, let me close this issue.

**Comment by xushaoxiao** [comment]
how to fix this problem?

```text
/home/shaoxiao/repos/tec-ai-mono/.venv-312/lib/python3.12/site-packages/py_async_grpc_prometheus/prometheus_async_server_interceptor.py:122: RuntimeWarning: coroutine 'HealthServicer.Watch' was never awaited
  async for behavior_response in behavior(request_or_iterator, servicer_context):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
24-12-16 18:31:47 - ERROR - events.py line:88 func:_run() - Unexpected [TypeError] raised by servicer method [/grpc.health.v1.Health/Watch]
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 689, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 838, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 587, in _handle_unary_stream_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 501, in _finish_handler_with_stream_responses
  File "/home/shaoxiao/repos/tec-ai-mono/.venv-312/lib/python3.12/site-packages/py_async_grpc_prometheus/prometheus_async_server_interceptor.py", line 153, in new_response_stream_behavior
    raise e
  File "/home/shaoxiao/repos/tec-ai-mono/.venv-312/lib/python3.12/site-packages/py_async_grpc_prometheus/prometheus_async_server_interceptor.py", line 122, in new_response_stream_behavior
    async for behavior_response in behavior(request_or_iterator, servicer_context):
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

**Comment by sem-k32** [comment]
@xushaoxiao
The Watch method of the async HealthServicer is a coroutine and it uses [context.write()](https://github.com/grpc/grpc/blob/master/src/python/grpcio_health_checking/grpc_health/v1/_async.py#L67-L69) for server streaming. But the py_async_grpc_prometheus interceptor assumes it is an async generator, and the issue discussed above arises. You can subclass HealthServicer and make Watch an async generator:
```python
class GenHealthServicer(grpc_health.v1._async.HealthServicer):
    async def Watch(self, request, context):
        condition = self._server_watchers[request.service]
        last_status = None
        try:
            async with condition:
                while True:
                    status = self._server_status.get(
                        request.service,
                        health_pb2.HealthCheckResponse.SERVICE_UNKNOWN,
                    )
                    # now yields
                    yield health_pb2.HealthCheckResponse(status=status)
                    last_status = status
                    await condition.wait()
        finally:
            self._server_watchers.pop(request.service, None)
```
Or you can redefine the interceptor based on the ```AsyncIOContextWrapper``` to execute py_async_grpc_prometheus logic for every .write() on the context object.
