### ISSUE TITLE
.NET NativeExtension class does not recognise 32-bit ARM, so Firestore can't be accessed from Raspberry Pi 4

### ISSUE THREAD

**Issue by jblam** [grpc/grpc#28752]
Steps to repro:

1. on a Raspberry Pi 4, create a new .NET project (e.g. `dotnet new console`)
2. add package reference to Google.Cloud.Firestore v2.5.0 NuGet package
3. in Program.cs, replace the default Hello World with
    ```
    using Google.Cloud.Firestore;
    FirestoreDbBuilder builder = new()
    {
      ProjectId = "some valid Firestore project",
      JsonCredentials = "some valid JSON credentials",
    };
    builder.Build();
    ```
    <sup>Please excuse any typos, I'm copying this off my Pi by hand.</sup>
3. `dotnet run`

Expected behaviour: program terminates without error.
Actual behaviour: throws an exception as follows

```
System.InvalidOperationException: Unsupported architecture "Unknown".
  at Grpc.Core.Internal.NativeExtension.GetArchitectureString()
  at Grpc.Core.Internal.NativeExtension.GetNativeLibraryFilename()
  <snip>
```

Here's the problem: NativeExtension doesn't understand 32-bit ARM exists.

https://github.com/grpc/grpc/blob/b9b6255993dad2a54669710db46fe0f9650cc9b2/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L296-L309

… because 

https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/csharp/Grpc.Core/Internal/CommonPlatformDetection.cs#L88-L89

Now, it is true that Google doesn't distribute an ARMv7 build of `libgrpc_csharp_ext`. However, [someone else does](https://github.com/erikest/libgrpc_csharp_ext) (or you could build it yourself), but because `NativeExtension.GetArchitectureString` won't emit `armv7`, I can't convince the grpc library to load it.

Could we have the implementation not "simply return unrecognised" so I can supply my own native build?

**Comment by jblam** [comment]
Actually it looks like [Firestore has a workaround](https://github.com/googleapis/google-cloud-dotnet/issues/7560#issuecomment-975414370) -- TL;DR: you can substitute an [alternative implementation](https://github.com/googleapis/gax-dotnet) of gRPC.

This solves my problem, so I'll close here.
