### ISSUE TITLE
grpc::InsecureServerCredentials() hangs forever

### ISSUE THREAD

**Issue by rollebolle** [grpc/grpc#28754]
### What version of gRPC and what language are you using?
1.38, 1.41, C++

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc11 x86_64, compiled with Yocto, linked with openssl 1.1.1

### What did you do?
From main(), simple call to:
`auto secCred = grpc::InsecureServerCredentials();`

### What did you expect to see?
The program continues after the statement

### What did you see instead?
The program hangs at the statement in the TraceFlagList module, with a busy wait. Might indicate some problem in the loop 

`for (t = root_tracer_; t; t = t->next_tracer_)`

D0127 16:58:18.877267850 9559 ev_posix.cc:173] Using polling engine: epollex
D0127 16:58:18.877339375 9559 init_unsecure.cc:30] Using insecure gRPC build. Security handshakers will not be invoked even if secure credentials are used.
D0127 16:58:18.877376866 9559 dns_resolver_ares.cc:499] Using ares dns resolver
D0127 16:58:18.877386441 9559 lb_policy_registry.cc:42] registering LB policy factory for "grpclb"
D0127 16:58:18.877391521 9559 lb_policy_registry.cc:42] registering LB policy factory for "priority_experimental"
D0127 16:58:18.877394231 9559 lb_policy_registry.cc:42] registering LB policy factory for "weighted_target_experimental"
D0127 16:58:18.877396515 9559 lb_policy_registry.cc:42] registering LB policy factory for "pick_first"
D0127 16:58:18.877398996 9559 lb_policy_registry.cc:42] registering LB policy factory for "round_robin"

**Backtrace:**

#0 __strcmp_avx2 () at strcmp-avx2.S:100
#1 0x00007ffff7da5f1c in grpc_core::TraceFlagList::Set(char const*, bool) () fromcore2-64-oe-linux/usr/lib/libgrpc_unsecure.so.16
#2 0x00007ffff7da603a in grpc_tracer_init() () from/core2-64-oe-linux/usr/lib/libgrpc_unsecure.so.16
#3 0x00007ffff7debdb0 in grpc_init () fromcore2-64-oe-linux/usr/lib/libgrpc_unsecure.so.16
#4 0x00007ffff7f53d93 in grpc::ServerCredentials::ServerCredentials() () fromysroots/core2-64-oe-linux/usr/lib/libgrpc++.so.1.38
#5 0x00007ffff7f3e10a in grpc::InsecureServerCredentials() () fromcore2-64-oe-linux/usr/lib/libgrpc++.so.1.38

**Comment by rollebolle** [comment]
duplicate of multiple issues
