### ISSUE TITLE
`_StreamCallResponseIterator.cancel()` raises an error when server interceptors are set

### ISSUE THREAD

**Issue by ysk24ok** [grpc/grpc#28778]
### What version of gRPC and what language are you using?

- Python 3.9.10
- grpcio 1.43.0

### What operating system (Linux, Windows,...) and version?

macOS Big Sur 11.6.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

```console
% gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What did you do?

helloworld.proto

```proto
syntax = "proto3";

package helloworld;

service Greeter {
  rpc SayHelloServerStreaming (HelloRequest) returns (stream HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

greeter_server.py

```py
import asyncio
import grpc

import helloworld_pb2
import helloworld_pb2_grpc


class Greeter(helloworld_pb2_grpc.GreeterServicer):
    async def SayHelloServerStreaming(self, request, context):
        yield helloworld_pb2.HelloReply(message="Hello, %s!" % request.name)


async def serve() -> None:
    server = grpc.aio.server()
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    listen_addr = "[::]:50051"
    server.add_insecure_port(listen_addr)
    await server.start()
    await server.wait_for_termination(None)


if __name__ == "__main__":
    asyncio.run(serve())
```

greeter_client.py

```py
import asyncio

import grpc

import helloworld_pb2
import helloworld_pb2_grpc


class UnaryStreamClientInterceptor(grpc.aio.UnaryStreamClientInterceptor):
    async def intercept_unary_stream(
        self,
        continuation,
        client_call_details,
        request,
    ):
        async def generator():
            call = await continuation(client_call_details, request)
            async for response in call:
                yield response

        return generator()


async def run(port: int) -> None:
    interceptor = UnaryStreamClientInterceptor()
    async with grpc.aio.insecure_channel(f"localhost:{port}", interceptors=[interceptor]) as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        request = helloworld_pb2.HelloRequest(name="Alice")
        async for response in stub.SayHelloServerStreaming(request):
            print(response.message)


if __name__ == "__main__":
    port = 50051
    asyncio.run(run(port))
```

Run the server and client.

```console
$ pythno3 greeter_server.py
```

```console
$ python3 greeter_client.py
```

### What did you expect to see?

```console
$ python3 greeter_client.py
Hello, Alice!
```

### What did you see instead?

```console
$ python3 greeter_client.py
Hello, Alice!
Exception ignored in: <function InterceptedCall.__del__ at 0x10eee5550>
Traceback (most recent call last):
  File "/Users/y-nishioka/repos/grpc_samples/venv/lib/python3.9/site-packages/grpc/aio/_interceptor.py", line 292, in __del__
    self.cancel()
  File "/Users/y-nishioka/repos/grpc_samples/venv/lib/python3.9/site-packages/grpc/aio/_interceptor.py", line 338, in cancel
    return call.cancel()
  File "/Users/y-nishioka/repos/grpc_samples/venv/lib/python3.9/site-packages/grpc/aio/_interceptor.py", line 935, in cancel
    return self._call.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
```

`_call` property of `_StreamCallResponseIterator` object should not be None. If it can be None, all methods of the class should check if it's None or not.
I haven't confirmed, but I think bidirectional streaming might encounter the same bug.

**Comment by ysk24ok** [comment]
Now I got the reason. Moving `continuation` call outside of the generator makes it work.

```diff
diff --git a/greeter_async_client.py b/greeter_async_client.py
index 2a02c14..58c79b5 100644
--- a/greeter_async_client.py
+++ b/greeter_async_client.py
@@ -14,10 +14,10 @@ class UnaryStreamClientInterceptor(grpc.aio.UnaryStreamClientInterceptor):
         request,
     ):
         async def generator():
-            call = await continuation(client_call_details, request)
             async for response in call:
                 yield response

+        call = await continuation(client_call_details, request)
         return generator()
```

Let me close this issue.
It would be useful for users if [examples/python/interceptors](https://github.com/grpc/grpc/tree/master/examples/python/interceptors) directory has examples for `grpc.aio` and stream response RPC. Or, I may be going to work on it.
