### ISSUE TITLE
 System.AccessViolationException   at Grpc.Core.Internal.BatchContextSafeHandle.ReleaseHandle()

### ISSUE THREAD

**Issue by syamalaids** [grpc/grpc#28950]
Using Grpc.Core.2.44.0 for C# as Nuget package for VisualStudio 2019 on Win2012 r2 server

The C# program is crashing with AccessViolation error:
```
Unhandled exception (Process IsTerminating=True): System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Grpc.Core.Internal.BatchContextSafeHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize().
```

**Comment by drfloob** [comment]
I think we'd need more information to be able to help. Can you provide a working reproduction, additional logs, and/or crash dump (including native stacktrace)?

**Comment by syamalaids** [comment]
I updated all the dlls to build with same .net version and issue got resolved. Thanks for your time.
