### ISSUE TITLE
Cancellation during stream-response RPC in the aio.server with non-async servicer often make the server termination hang up

### ISSUE THREAD

**Issue by ysk24ok** [grpc/grpc#28999]
### What version of gRPC and what language are you using?

Python 3.10.2
grpio 1.44.0

### What operating system (Linux, Windows,...) and version?

macOS Big Sur 11.6.1

### What runtime / compiler are you using (e.g. python version or version of gcc)

```console
% gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
% python --version
Python 3.10.2
```

### What did you do?

Here's the proto.

```proto
syntax = "proto3";

package helloworld;

service Greeter {
  rpc SayHelloServerStreaming (HelloRequest) returns (stream HelloReply) {}
  rpc SayHelloBidiStreaming (stream HelloRequest) returns (stream HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

Here's the server/client in a test file.

```py
import asyncio

import grpc
import pytest
import pytest_asyncio

import helloworld_pb2
import helloworld_pb2_grpc


class Greeter(helloworld_pb2_grpc.GreeterServicer):
    def SayHelloServerStreaming(self, request, context):
        yield helloworld_pb2.HelloReply(message=f"Hello, {request.name}!")
        yield helloworld_pb2.HelloReply(message=f"Hello, {request.name}!")

    def SayHelloBidiStreaming(self, request_iterator, context):
        for request in request_iterator:
            yield helloworld_pb2.HelloReply(message=f"Hello, {request.name}!")


@pytest_asyncio.fixture()
async def target(event_loop):
    server = grpc.aio.server()
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    listen_addr = "[::]:50051"
    server.add_insecure_port(listen_addr)
    await server.start()
    wait_task = event_loop.create_task(server.wait_for_termination())
    yield "localhost:50051"
    await server.stop(grace=5)
    await wait_task


"""
@pytest.mark.asyncio
async def test_unary_stream(target):
    async with grpc.aio.insecure_channel(target) as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        request = helloworld_pb2.HelloRequest(name="Alice")
        call = stub.SayHelloServerStreaming(request)
        with pytest.raises(asyncio.CancelledError):
            async for response in call:
                print(response.message)
                call.cancel()
"""

@pytest.mark.asyncio
async def test_stream_stream(target):
    names = ["Alice", "Bob"]
    request_iterator = iter(helloworld_pb2.HelloRequest(name=name) for name in names)
    async with grpc.aio.insecure_channel(target) as channel:
        stub = helloworld_pb2_grpc.GreeterStub(channel)
        call = stub.SayHelloBidiStreaming(request_iterator)
        with pytest.raises(asyncio.CancelledError):
            async for response in call:
                print(response.message)
                call.cancel()
```

### What did you expect to see?

Test execution succeeds,

### What did you see instead?

The execution often hangs up when a thread in `grpc.aio.server` shuts down.

```console
% pytest -s test.py
=========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0
rootdir: /Users/y-nishioka/repos/grpc_samples
plugins: asyncio-0.18.1
asyncio: mode=legacy
collected 1 item                                                                                                                                                                                         

test.py Hello, Alice!
.

============================================================================================ warnings summary =============================================================================================
venv310/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191
  /Users/y-nishioka/repos/grpc_samples/venv310/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================================== 1 passed, 1 warning in 0.05s =======================================================================================
^CException ignored in: <module 'threading' from '/Users/y-nishioka/.pyenv/versions/3.10.2/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/y-nishioka/.pyenv/versions/3.10.2/lib/python3.10/threading.py", line 1530, in _shutdown
    atexit_call()
  File "/Users/y-nishioka/.pyenv/versions/3.10.2/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/Users/y-nishioka/.pyenv/versions/3.10.2/lib/python3.10/threading.py", line 1089, in join
    self._wait_for_tstate_lock()
  File "/Users/y-nishioka/.pyenv/versions/3.10.2/lib/python3.10/threading.py", line 1109, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
```

With this example, `test_unary_stream` does not hang up, but I confirmed it did in https://github.com/DataDog/dd-trace-py/pull/3240.
Tests with async servicer does not hang up, so I think it's not pytest's fault.

**Comment by sonjaer** [comment]
We also experience hanging executions with this version of grpcio
