### ISSUE TITLE
ruby macos build flake - /bin/sh: /bin/sh: cannot execute binary file

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#29042]
```
[C]       Compiling src/core/ext/upbdefs-generated/xds/annotations/v3/sensitive.upbdefs.c
mkdir -p `dirname /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/sensitive.upbdefs.o`
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="\"RUBY\""  -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="\"1.45.0.dev\""  -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/gens -I/usr/local/include -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99 -Wextra-semi -g   -MMD -MF /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/sensitive.upbdefs.dep -c -o /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/sensitive.upbdefs.o src/core/ext/upbdefs-generated/xds/annotations/v3/sensitive.upbdefs.c
[C]       Compiling src/core/ext/upbdefs-generated/xds/annotations/v3/status.upbdefs.c
/bin/sh: /bin/sh: cannot execute binary file
mkdir -p `dirname /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/status.upbdefs.o`
make: *** [/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/sensitive.upbdefs.o] Error 126
make: *** Waiting for unfinished jobs....
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="\"RUBY\""  -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="\"1.45.0.dev\""  -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/gens -I/usr/local/include -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99 -Wextra-semi -g   -MMD -MF /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/status.upbdefs.dep -c -o /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/tmp/universal-darwin/grpc_c/3.0.0/objs/opt/src/core/ext/upbdefs-generated/xds/annotations/v3/status.upbdefs.o src/core/ext/upbdefs-generated/xds/annotations/v3/status.upbdefs.c
*** ../../../../src/ruby/ext/grpc/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=../../../../src/ruby/ext/grpc
	--curdir
	--ruby=/Users/kbuilder/.rake-compiler/ruby/x86_64-darwin11/ruby-3.0.0/bin/$(RUBY_BASE_NAME)
rake aborted!
Command failed with status (1): [/Users/kbuilder/.rvm/rubies/ruby-2.5.0/bin...]
/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/bundle_local_gems/ruby/2.5.0/gems/rake-compiler-1.1.1/lib/rake/extensiontask.rb:206:in `block (2 levels) in define_compile_tasks'
/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/bundle_local_gems/ruby/2.5.0/gems/rake-compiler-1.1.1/lib/rake/extensiontask.rb:203:in `block in define_compile_tasks'
/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_native_gem_macos_darwin/bundle_local_gems/ruby/2.5.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/bin/bundle:25:in `load'
/Users/kbuilder/.rvm/gems/ruby-2.5.0/bin/bundle:25:in `<main>'
Tasks: TOP => native => native:universal-darwin => native:grpc:universal-darwin => tmp/universal-darwin/stage/src/ruby/lib/grpc/3.0/grpc_c.bundle => copy:grpc_c:universal-darwin:3.0.0 => tmp/universal-darwin/grpc_c/3.0.0/grpc_c.bundle => tmp/universal-darwin/grpc_c/3.0.0/Makefile
(See full trace by running task with --trace)
+ '[' Darwin == Darwin ']'
++ ls 'pkg/*.gem'
++ grep -v darwin
ls: pkg/*.gem: No such file or directory
+ rm
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
```

https://source.cloud.google.com/results/invocations/a5266702-9573-493b-a946-2f0a779cbd1e/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log

**Comment by alto-ruby** [comment]
This appears to be environment issue. Closes since no ruby 2.5 support any more.
