### ISSUE TITLE
Python source distribution on PyPI cannot be installed on windows

### ISSUE THREAD

**Issue by niyas-sait** [grpc/grpc#29073]
Python source distributions for `grpc` package provided through pip cannot be used for installation on windows machines. 

`pip install grpcio --no-binary :all:`

Generates following error

`generated\envoy\extensions\filters\network\http_connection_manager\v3\http_connection_manager.upb.c : fatal error C1083: Cannot open compiler generated file: '': Invalid argument`

If we clone git repository and build it then it seems to compile fine so looks like the issue is in the generation of package building.

I notice some of the cython related auto-generated files distributed are not compliable on windows. 

E.g : auto-generated file`src\python\grpcio\grpc/_cython/cygrpc.cpp` includes `pthread.hpp`.

Local builds from fresh git checkout don't seem to generate similar files and compiles OK.

### What version of gRPC and what language are you using?

v1.44.0 and Python

### What operating system (Linux, Windows,...) and version?

Windows (x64 and Arm64)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.10 and MSVC 2019

### What did you do?

`pip install grpcio --no-binary :all:`

### What did you expect to see?

grpcio package is installed.

### What did you see instead?

```
third_party\upb\upb/upb.h(342): warning C4244: 'function': conversion from 'uint64_t' to 'uint32_t', possible loss of data
third_party\upb\upb/table_internal.h(200): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
third_party\upb\upb/msg_internal.h(469): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
third_party\upb\upb/msg_internal.h(741): warning C4090: 'function': different 'const' qualifiers
C:\Users\niyas.sait\AppData\Local\Temp\2\pip-install-jioo6dxu\grpcio_2cdf485e2d3e4aa1be581dd01254fb87\src\core\ext\upb-generated\envoy\extensions\filters\network\http_connection_manager\v3\http_connection_manager.upb.c : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
creating Users
creating Users\NIYAS~1.SAI
creating Users\NIYAS~1.SAI\AppData
creating Users\NIYAS~1.SAI\AppData\Local
creating Users\NIYAS~1.SAI\AppData\Local\Temp
creating Users\NIYAS~1.SAI\AppData\Local\Temp\2
creating Users\NIYAS~1.SAI\AppData\Local\Temp\2\tmpfctx284x
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\niyas.sait\Workspace\venv\include -IC:\Users\niyas.sait\AppData\Local\Programs\Python\Python310\include -IC:\Users\niyas.sait\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /TcC:\Users\NIYAS~1.SAI\AppData\Local\Temp\2\tmpfctx284x\a.c /FoUsers\NIYAS~1.SAI\AppData\Local\Temp\2\tmpfctx284x\a.obj
a.c
Traceback (most recent call last):
  File "C:\Users\niyas.sait\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 401, in compile
    self.spawn(args)
  File "C:\Users\niyas.sait\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 507, in spawn
    return super().spawn(cmd)
  File "C:\Users\niyas.sait\AppData\Local\Temp\2\pip-install-jioo6dxu\grpcio_2cdf485e2d3e4aa1be581dd01254fb87\src\python\grpcio\_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "C:\Users\niyas.sait\AppData\Local\Programs\Python\Python310\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\niyas.sait\AppData\Local\Programs\Python\Python310\lib\distutils\spawn.py", line 91, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1

During handling of the above exception, another exception occurred:


```
### Anything else we should know about your project / environment?

I have tried the steps on windows/x64 and windows/arm64 platforms and seem to be getting similar error message.

I have also tried setting the `GRPC_PYTHON_BUILD_WITH_CYTHON` flag but hit a similar error message.

**Comment by lidizheng** [comment]
@nsait-linaro We do have distribtests running on Windows for source-compile and binary-wheel installation. We might need a very concrete reproduction case here.

As a starter, can you help to include the entire installation log? Compiling failed due to file-not-found error for upb file is strange.

Also, are you using mingw or cygwin or similar toolset?

**Comment by nsait-linaro** [comment]
Thanks @lidizheng for having a look.

I am running on powershell.

Please check the attached installation log from pip.

[grpcio_install.log](https://github.com/grpc/grpc/files/8226405/grpcio_install.log)

**Comment by lidizheng** [comment]
I didn't find any obvious red flag from the install log. Can you help to try if the issue persists in our latest release candidate? https://pypi.org/project/grpcio/#history

To push this issue forward, we might need more investigation on your-side. Like, finding out what file is missing.

**Comment by nsait-linaro** [comment]
I just tried the latest release candidate, unfortunately, I am getting the same error.

`pip install grpcio==1.45.0rc1 --no-binary :all: -v --log grpcio_1_45_install.log`

Can you point me to any CI run which works with source distribution?

Also, how is the python source distribution generated? Any scripts I could take a look at

**Comment by lidizheng** [comment]
You can find the script here: https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/build_artifact_python.bat

One example run: https://source.cloud.google.com/results/invocations/82a2f0b8-1702-462f-bfab-edfc1e52a0fe/targets

**Comment by nsait-linaro** [comment]
Thanks, @lidizheng. I think the script builds the binary wheel. I don't see how the source package is created in that script. This specific issue happens when installed with the [source distribution](https://files.pythonhosted.org/packages/6d/fe/c457729a716e386532f8596b6704bda6f95f1833043c8f2fb58e68356af1/grpcio-1.45.0rc1.tar.gz)

**Comment by lidizheng** [comment]
Oh, the source wheels is produced here: https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/build_artifact_python.sh#L87

**Comment by nsait-linaro** [comment]
@lidizheng I think we need to remove auto-generated `cygrpc.cpp` as it seems to be platform-specific and better to let build scripts regenerate during the build

 https://github.com/grpc/grpc/pull/29178

**Comment by XuanWang-Amos** [comment]
I believe the issue still exist, here is a summary:
* We're seeing  `Cannot open compiler generated file` error when installing grpcio using source distributions on Windows.
* This is because the auto-generated `cygrpc.cpp` file can't compile on Windows.
* We can't remove this file from source distributions since we support building without Cython, which means we need distribute all `.c` or `.cpp` files.

A potential solution is distribute `cygrpc.cpp` under a different name and use it only for Linux builds if [GRPC_PYTHON_BUILD_WITH_CYTHON](https://github.com/grpc/grpc/blob/master/setup.py#L129-L134) is not set.

Since this issue only impact Windows building from source, we're treating it as a low priority.

We welcome any contributions if anyone wants to help with this :)

**Comment by fancybear-dev** [comment]
I'm having this issue right now, with Python 3.12.0b4 and Windows 11 25393.1 channel using 14.36.32532 MSVC. Anyone with viable solutions? And before anyone mentions, yes I'm running Windows like I'm on Arch which is likely the actual root cause.

**Comment by dlech** [comment]
The errors mentioned above probably aren't relevant anymore, but this is still a problem. Especially since there are no ARM64 Windows binary wheels (https://github.com/grpc/grpc/issues/39362).

My first attempt to build failed because of missing `unistd.h`. So clearly the source distribution still has files generated for *nix systems.

So I tried with `$env:GRPC_PYTHON_BUILD_WITH_CYTHON="1"` to avoid the generated files.

However, this still fails with: 

```
src\core\ext\upb-gen\envoy\extensions\load_balancing_policies\client_side_weighted_round_robin\v3\client_side_weighted_round_robin.upb_minitable.c : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
```

During:

```
"C:\Program Files\Microsoft Visual Studio\18\Insiders\VC\Tools\MSVC\14.50.35615\bin\HostARM64\ARM64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"\\\"Python\\\"\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"\\\"1.76.0\\\"\" -DOPENSSL_NO_ASM=1 -DWIN32_LEAN_AND_MEAN=1 -DCARES_STATICLIB=1 -DGRPC_ARES=0 -DNTDDI_VERSION=100663296 -DNOMINMAX=1 -DMS_WIN64=1 -DGRPC_PYTHON_BUILD=1 -D__STDC_FORMAT_MACROS -Isrc\python\grpcio -Iinclude -I. -Ithird_party\abseil-cpp -Ithird_party\address_sorting\include -Ithird_party\cares\cares\include -Ithird_party\cares -Ithird_party\cares\cares -Ithird_party\cares\cares\src\lib\include -Ithird_party\cares\cares\src\lib -Ithird_party\re2 -Ithird_party\boringssl-with-bazel\src\include -Ithird_party\upb -Isrc\core\ext\upb-gen -Isrc\core\ext\upbdefs-gen -Ithird_party\utf8_range -Ithird_party\xxhash -Ithird_party\zlib -IC:\Users\extra\AppData\Local\pypoetry\Cache\virtualenvs\bleak-76eGtwQD-py3.11\include -IC:\Users\extra\AppData\Local\Programs\Python\Python311-arm64\include -IC:\Users\extra\AppData\Local\Programs\Python\Python311-arm64\Include "-IC:\Program Files\Microsoft Visual Studio\18\Insiders\VC\Tools\MSVC\14.50.35615\include" "-IC:\Program Files\Microsoft Visual Studio\18\Insiders\VC\Tools\MSVC\14.50.35615\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\18\Insiders\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tcsrc/core/ext/upb-gen/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.upb_minitable.c /Fopyb\temp.win-arm64-cpython-311\Release\src\core\ext\upb-gen\envoy\extensions\load_balancing_policies\client_side_weighted_round_robin\v3\client_side_weighted_round_robin.upb_minitable.obj /std:c11 /MT
```
