### ISSUE TITLE
Failing to build grpcio from scratch on Raspberry Pi

### ISSUE THREAD

**Issue by vatine** [grpc/grpc#29228]
### What version of gRPC and what language are you using?

Pythinb

### What operating system (Linux, Windows,...) and version?

Raspberry Pi / Debian

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python, I guess whatever the "most current at time of install"

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Having had a "not actually wrking wit hte glibc installed", I was trying to build from scratch. I was expecting a successful build.

### What did you expect to see?

A successful build.

### What did you see instead?

Note, this is just the tail end of the output, it filled my xterm scrollback buffer, there's about 10x more of essentially the same thing. Not sure if this is a grpcio thing, a pip thing, a compiler thing, or whatever....

```
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="Python" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="1.45.0" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/usr/include/python3.7m -c src/core/lib/transport/bdp_estimator.cc -o python_build/temp.linux-armv7l-3.7/src/core/lib/transport/bdp_estimator.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="Python" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="1.45.0" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/usr/include/python3.7m -c src/core/lib/transport/byte_stream.cc -o python_build/temp.linux-armv7l-3.7/src/core/lib/transport/byte_stream.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
    cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
    creating None
    creating None/tmp
    creating None/tmp/tmppszv7czy
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c /tmp/tmppszv7czy/a.c -o None/tmp/tmppszv7czy/a.o
    Traceback (most recent call last):
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/commands.py", line 280, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
        _compile_single_file, objects)
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
        raise self._value
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
        result = (True, func(*args, **kwds))
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-54o4sdvd/grpcio/setup.py", line 542, in <module>
        cmdclass=COMMAND_CLASS,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/commands.py", line 285, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/commands.py", line 280, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
        _compile_single_file, objects)
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
        raise self._value
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
        result = (True, func(*args, **kwds))
      File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/tmp/pip-install-54o4sdvd/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-54o4sdvd/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rneqap0t/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-54o4sdvd/grpcio/

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

This is just me trying to get gRPC working in Python on a Raspberry Pi, so I don't have to implement USB support for a 3rd party hardware device in Go, just so I can send gRPC commands to it. If I can't get this working, I guess I will have to fall back on manually-constructed network RPC protocols, but I would actually prefer getting gRPC working.

**Comment by vatine** [comment]
I am currently upgrading the OS on the Raspberry Pi, with a hope of being able to use the pre-built PIP package, but I an still surprised that trying to build it from scratch ended up with what looks like an invalid flag combination.

**Comment by abarberenaCPDS** [comment]
Hi @gnossen 👋 

I can't make it work for Raspberry PI 3B+ either. I am trying to run the Google PubSub QuickStart but no luck

Where can I find a supported Linux distros matrix or similar?

Does this library work for Centos aarch64?

```bash
uname -a
Linux centospi 5.4.72-v8.1.el7 #1 SMP PREEMPT Wed Oct 21 17:35:36 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

This is my installation log file:
[log.txt](https://github.com/grpc/grpc/files/8624950/log.txt)

**Comment by gnossen** [comment]
@abarberenaCPDS Thanks for the build log. This seems to be the actual error:

```
  In file included from third_party/abseil-cpp/absl/memory/memory.h:34:0,
                   from ./src/core/lib/gprpp/memory.h:28,
                   from ./src/core/lib/gprpp/global_config_generic.h:26,
                   from ./src/core/lib/gprpp/global_config_env.h:24,
                   from ./src/core/lib/gprpp/global_config.h:93,
                   from ./src/core/lib/debug/trace.h:28,
                   from ./src/core/lib/channel/channel_stack.h:57,
                   from ./src/core/ext/filters/server_config_selector/server_config_selector_filter.h:24,
                   from src/core/ext/filters/server_config_selector/server_config_selector_filter.cc:17:
  third_party/abseil-cpp/absl/meta/type_traits.h:55:53: error: ‘max_align_t’ is not a member of ‘std’
   #define ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT alignof(std::max_align_t)
```

A little further up we see:

```
  cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
```

Just to make sure, do you have a C++ compiler installed?

**Comment by abarberenaCPDS** [comment]
Hey @gnossen, thx for getting back!

I got to say that part of the problem was that I was using a mediocre Microcenter MicroSD card, so, after upgrading to a 64GB Sandisk Gold, I was able to install both the compiler and the library.

Now, my I was back on my Google pub/sub QuickStart tutorial, I am getting the following error:

```bash
root@centospi  ~/dpy source dev/bin/activate
(dev)  ⚡ root@centospi  ~/dpy  pip install --upgrade google-cloud-pubsub
Requirement already satisfied: google-cloud-pubsub in ./dev/lib/python3.6/site-packages (2.12.0)
Requirement already satisfied: proto-plus>=1.15.0 in ./dev/lib/python3.6/site-packages (from google-cloud-pubsub) (1.20.3)
Requirement already satisfied: grpcio<2.0dev,>=1.38.1 in ./dev/lib/python3.6/site-packages (from google-cloud-pubsub) (1.46.0)
Requirement already satisfied: grpcio-status>=1.16.0 in ./dev/lib/python3.6/site-packages (from google-cloud-pubsub) (1.46.0)
Requirement already satisfied: grpc-google-iam-v1<0.13dev,>=0.12.3 in ./dev/lib/python3.6/site-packages (from google-cloud-pubsub) (0.12.4)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in ./dev/lib/python3.6/site-packages (from google-cloud-pubsub) (2.7.3)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in ./dev/lib/python3.6/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (2.6.6)
Requirement already satisfied: protobuf>=3.12.0 in ./dev/lib/python3.6/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (3.19.4)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in ./dev/lib/python3.6/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (2.27.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in ./dev/lib/python3.6/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (1.56.0)
Requirement already satisfied: six>=1.5.2 in ./dev/lib/python3.6/site-packages (from grpcio<2.0dev,>=1.38.1->google-cloud-pubsub) (1.16.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./dev/lib/python3.6/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (4.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./dev/lib/python3.6/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in ./dev/lib/python3.6/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./dev/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in ./dev/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./dev/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./dev/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (2.0.12)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./dev/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-pubsub) (0.4.8)
``` 

Then, after the first line 

```python
from google.cloud import pubsub_v1 # this one fails

# TODO(developer)
# project_id = "your-project-id"
```

I execute the following command and got a ***segmentation error***  ❗ ❓  

```bash
python sender.py 
[1]    3154 segmentation fault  python sender.py
```

I also tried to figure out the issue by running this:

```zsh
(dev)  ✘ ⚡ root@centospi  ~/dpy  PYTHONFAULTHANDLER=1 python sender.py  
Fatal Python error: Segmentation fault

Current thread 0x0000007fa2225000 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 922 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 658 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/dpy/dev/lib64/python3.6/site-packages/grpc/_compression.py", line 15 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/dpy/dev/lib64/python3.6/site-packages/grpc/__init__.py", line 22 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/dpy/dev/lib64/python3.6/site-packages/google/api_core/gapic_v1/config.py", line 23 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/dpy/dev/lib64/python3.6/site-packages/google/api_core/gapic_v1/__init__.py", line 16 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/dpy/dev/lib64/python3.6/site-packages/google/cloud/pubsub_v1/types.py", line 27 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/dpy/dev/lib64/python3.6/site-packages/google/cloud/pubsub_v1/__init__.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "senderpy", line 4 in <module>
[1]    3219 segmentation fault  PYTHONFAULTHANDLER=1 python sender.py
(dev)  ✘ ⚡ root@centospi  ~/dpy  
```

**Comment by oiwn** [comment]
Any news?

**Comment by XuanWang-Amos** [comment]
@oiwn Are you able to generate a backtrace with GDB?
