### ISSUE TITLE
Asyncio exception handler called on client after server cancelling stream-stream RPC due to internal exception

### ISSUE THREAD

**Issue by marcosatti** [grpc/grpc#29518]
### What version of gRPC and what language are you using?
gRPC 1.45.0, Python

### What operating system (Linux, Windows,...) and version?
Windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10.4

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

Using an asynchronous iterator client stream-stream RPC call, when the server encounters an exception while executing and subsequently cancels the RPC call (UNKNOWN return status), the client iterator task is not cleaned up properly and causes the asyncio event loop exception handler to be called with "Task was destroyed but it is pending!".

Additionally, there is also the GeneratorExit message which is generated, although it is not related to the asyncio exception handler.

### What did you expect to see?
No call to the asyncio event loop exception handler.

In our application a call to the asyncio exception handler indicates a fatal error and will start shutdown procedures - we would like to not have to add an exception for this case.

### What did you see instead?
```
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:grpc._cython.cygrpc:Using AsyncIOEngine.POLLER as I/O engine
Calling RPC...
Called RPC and error occurred from server (expected): <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'ValueError'>: test"
        debug_error_string = "{"created":"@1651227999.079000000","description":"Error received from peer ipv6:[::1]:63000","file":"src/core/lib/surface/call.cc","file_line":906,"grpc_message":"Unexpected <class 'ValueError'>: test","grpc_status":2}"
>
Bug should happen after do_gc() progresses but before this sleep(10) finishes with 'Client request_iterator raised exception: GeneratorExit' and 'ERROR:asyncio:Task was destroyed but it is pending! (self._async_request_poller = self._loop.create_task)'
****************************** Running GC ******************************
ERROR:asyncio:Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "C:\Work\Development\python-sandbox\client.py", line 82, in <module>
    asyncio.run(main(), debug=True)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1888, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Work\Development\python-sandbox\client.py", line 47, in client_task
    await do_rpc()
  File "C:\Work\Development\python-sandbox\client.py", line 42, in do_rpc
    async for response in stub.StreamStreamMethod(client_iterator()):
  File "C:\Users\Marco\AppData\Roaming\Python\Python310\site-packages\grpc\aio\_channel.py", line 227, in __call__
    call = StreamStreamCall(request_iterator, deadline, metadata,
  File "C:\Users\Marco\AppData\Roaming\Python\Python310\site-packages\grpc\aio\_call.py", line 633, in __init__
    self._init_stream_request_mixin(request_iterator)
  File "C:\Users\Marco\AppData\Roaming\Python\Python310\site-packages\grpc\aio\_call.py", line 379, in _init_stream_request_mixin
    self._async_request_poller = self._loop.create_task(
task: <Task pending name='Task-7' coro=<_StreamRequestMixin._consume_request_iterator() running at C:\Users\Marco\AppData\Roaming\Python\Python310\site-packages\grpc\aio\_call.py:406> wait_for=<Future cancelled created at C:\Program Files\Python310\lib\asyncio\base_events.py:429> created at C:\Users\Marco\AppData\Roaming\Python\Python310\site-packages\grpc\aio\_call.py:379>
DEBUG:grpc.aio._call:Client request_iterator raised exception:
Traceback (most recent call last):
  File "C:\Users\Marco\AppData\Roaming\Python\Python310\site-packages\grpc\aio\_call.py", line 406, in _consume_request_iterator
    async for request in request_iterator:
GeneratorExit

****************************** After GC ******************************
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-9' coro=<<async_generator_athrow without __name__>()> exception=RuntimeError('aclose(): asynchronous generator is already running') created at C:\Program Files\Python310\lib\asyncio\events.py:80>
source_traceback: Object created at (most recent call last):
  File "C:\Work\Development\python-sandbox\client.py", line 82, in <module>
    asyncio.run(main(), debug=True)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1888, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: aclose(): asynchronous generator is already running
DEBUG:asyncio:Close <ProactorEventLoop running=False closed=False debug=True>
```

### Reproducible test case
Spawn `python server.py` first, then `python client.py` second. Be sure to compile the protobuf beforehand.

`service.proto`:
```
syntax = "proto3";

import "google/protobuf/empty.proto";

service Service {
    rpc StreamStreamMethod (stream google.protobuf.Empty) returns (stream google.protobuf.Empty);
}
```

`client.py`:
```
# Before running:
# python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto

# To run:
# Ensure `python server.py` is running.
# Then: `python client.py`.

import asyncio
import logging
import grpc
import signal
import gc
import service_pb2_grpc
from google.protobuf.empty_pb2 import Empty
from functools import partial

logging.basicConfig(level=logging.DEBUG)

shutdown_event = asyncio.Event()

def handle_signal(loop: asyncio.AbstractEventLoop) -> None:
    print(f"Signal SIGINT/SIGTERM caught")
    loop.call_soon_threadsafe(shutdown_event.set)

def handle_exception(loop: asyncio.AbstractEventLoop, context) -> None:
    loop.default_exception_handler(context)
    loop.call_soon_threadsafe(shutdown_event.set)

async def client_task():
    channel = grpc.aio.insecure_channel(f"[::1]:63000")
    await asyncio.wait_for(channel.channel_ready(), 3.0)
    stub = service_pb2_grpc.ServiceStub(channel)

    async def do_rpc():
        response_queue = asyncio.Queue()

        async def client_iterator():
            for _ in range(10):
                yield Empty()
                await response_queue.get()

        async for response in stub.StreamStreamMethod(client_iterator()):
            response_queue.put_nowait(response)

    try:
        print("Calling RPC...")
        await do_rpc()
    except grpc.aio.AioRpcError as exc:
        print(f"Called RPC and error occurred from server (expected): {exc}")

    print("Bug should happen after do_gc() progresses but before this sleep(10) "
          "finishes with 'Client request_iterator raised exception: GeneratorExit' and "
          "'ERROR:asyncio:Task was destroyed but it is pending! (self._async_request_poller = self._loop.create_task)'")
    await asyncio.sleep(10)

async def do_gc() -> None:
    await asyncio.sleep(5)
    print("****************************** Running GC ******************************")
    gc.collect()
    print("****************************** After GC ******************************")

async def main():
    loop = asyncio.get_running_loop()
    loop.set_exception_handler(handle_exception)

    try:
        loop.add_signal_handler(signal.SIGTERM, partial(handle_signal, loop))
        loop.add_signal_handler(signal.SIGINT, partial(handle_signal, loop))
    except (AttributeError, NotImplementedError):
        pass

    asyncio.create_task(client_task())
    asyncio.create_task(do_gc())
    await shutdown_event.wait()
  
asyncio.run(main(), debug=True)
```

`server.py`:
```
# Before running:
# python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto

import asyncio
import logging
import signal
import grpc
import service_pb2_grpc
from functools import partial

logging.basicConfig(level=logging.DEBUG)

class ServiceServicer(service_pb2_grpc.ServiceServicer):
    async def StreamStreamMethod(self, request_iterator, context):
        request_iterator = request_iterator.__aiter__()
        request = await request_iterator.__anext__()
        raise ValueError("test")

shutdown_event = asyncio.Event()

def handle_signal(loop: asyncio.AbstractEventLoop) -> None:
    print(f"Signal SIGINT/SIGTERM caught")
    loop.call_soon_threadsafe(shutdown_event.set)

def handle_exception(loop: asyncio.AbstractEventLoop, context) -> None:
    loop.default_exception_handler(context)
    loop.call_soon_threadsafe(shutdown_event.set)

async def main():    
    loop = asyncio.get_running_loop()
    loop.set_exception_handler(handle_exception)

    try:
        loop.add_signal_handler(signal.SIGTERM, partial(handle_signal, loop))
        loop.add_signal_handler(signal.SIGINT, partial(handle_signal, loop))
    except (AttributeError, NotImplementedError):
        pass

    server = grpc.aio.server()
    server.add_insecure_port("[::1]:63000")
    service_pb2_grpc.add_ServiceServicer_to_server(ServiceServicer(), server)
    await server.start()
    await shutdown_event.wait()
    await server.stop(3.0)
  
asyncio.run(main(), debug=True)
```

**Comment by marcosatti** [comment]
I figured out this workaround in the meantime for anyone else:

```
    async def do_rpc():
        response_queue = asyncio.Queue()
        server_error = asyncio.Event()

        async def client_iterator():
            for _ in range(10):
                yield Empty()

                response_task = asyncio.create_task(response_queue.get())
                server_error_task = asyncio.create_task(server_error.wait())
                (done_task,), _ = await asyncio.wait({response_task, server_error_task}, return_when=asyncio.FIRST_COMPLETED)
                if done_task == response_task:
                    server_error_task.cancel()
                    with contextlib.suppress(asyncio.CancelledError):
                        await server_error_task
                    response = await done_task
                    # Do something with response...
                elif done_task == server_error_task:
                    response_task.cancel()
                    with contextlib.suppress(asyncio.CancelledError):
                        await response_task
                    # Exit out of the client iterator, which causes gRPC to exit the internal task (_StreamRequestMixin::_consume_request_iterator()) too.
                    return
                else:
                    raise NotImplementedError()

        call: grpc.aio.StreamStreamCall = stub.StreamStreamMethod(client_iterator())

        async def server_error_setter():
            if await call.code() == grpc.StatusCode.UNKNOWN:
                server_error.set()

        server_error_setter_task = asyncio.create_task(server_error_setter())
        try:
            async for response in call:
                response_queue.put_nowait(response)
        finally:
            server_error_setter_task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await server_error_setter_task
```

RPC exits as expected and resources are cleaned up.

Seems like `_consume_iterator_request()` should be doing something similar perhaps (wait for an iterator value or wait for a RPC status event and act accordingly)?
