### ISSUE TITLE
Client-side streaming early OK fails with StatusCode.CANCELLED from python client

### ISSUE THREAD

**Issue by ebraraktas** [grpc/grpc#29615]
### What version of gRPC and what language are you using?

Python 3.8.12 - gRPC 1.44.0

### What operating system (Linux, Windows,...) and version?

MacOS 11.4

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.8.12

### What did you do?
I implemented simple client-side streaming endpoint using `tonic-rs` (Unofficial gRPC implementation in Rust). It may return early if `latitude` of a `Point` in client-side stream is `0`.

```rust
async fn record_route(
    &self,
    request: Request<Streaming<Point>>,
) -> Result<Response<RouteSummary>, Status> {
    let mut stream = request.into_inner();

    let mut summary = RouteSummary::default();

    while let Some(point) = stream.next().await {
        let point = point?;
        summary.point_count += 1;
        // return early if latitude is 0
        if point.latitude == 0 {
            println!("Return early: {}", summary.point_count);
            return Ok(Response::new(summary));
        }
    }
    println!("Return normal: {}", summary.point_count);
    Ok(Response::new(summary))
}
```

GitHub repo to reproduce the issue: https://github.com/ebraraktas/tonic-client-stream-early-ok

### What did you expect to see?

 I expected to reach that server from [this simple python client](https://github.com/ebraraktas/tonic-client-stream-early-ok/blob/main/proto/client.py).

### What did you see instead?

However, when I call this server from [that python client](https://github.com/ebraraktas/tonic-client-stream-early-ok/blob/main/proto/client.py) it fails with the exception (`StatusCode.CANCELLED`) below:

```shell
# python client.py 5000
port = 5000
early_return_index = 2
Sleep 500 ms
Sleep 500 ms
Sleep 500 ms
Traceback (most recent call last):
  File "client.py", line 46, in <module>
    main()
  File "client.py", line 42, in main
    call_stream(client)
  File "client.py", line 34, in call_stream
    print(client.RecordRoute(iter_points()))
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 1131, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.CANCELLED
        details = "Received RST_STREAM with error code 8"
        debug_error_string = "{"created":"@1651470233.217719000","description":"Error received from peer ipv6:[::1]:5000","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Received RST_STREAM with error code 8","grpc_status":1}"
>
```

### Anything else we should know about your project / environment?

As the [Issue section](https://github.com/ebraraktas/tonic-client-stream-early-ok#issue) of the README of the linked repo states, it runs ok with rust client. To make sure it is not related to `tonic-rs`, I implemented same client in Go; and that works, too. I opened [an issue](https://github.com/hyperium/tonic/issues/992) in the `tonic` repository, and they think it is related to Python implementation of gRPC.

**Comment by ebraraktas** [comment]
@gnossen Thank you for your answer. I will attach it to [the issue I opened in tonic-rs repo](https://github.com/hyperium/tonic/issues/992). However, how can we explain that a go client works with same `tonic-rs` server while python one doesn't? ([see my message on tonic-rs issue about the details](https://github.com/hyperium/tonic/issues/992#issuecomment-1116668866)).
