### ISSUE TITLE
Unable to install grpcio with python 3.8 on ppc64le (power 8) machine

### ISSUE THREAD

**Issue by pt-arvind** [grpc/grpc#29939]
### What version of gRPC and what language are you using?
gRPC: 1.16.0
python: 3.8.0

### What operating system (Linux, Windows,...) and version?
ubuntu 18.04, ppc64le (power 8)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8.0
cython 0.29.30

```bash
$ powerpc64le-linux-gnu-gcc --version
powerpc64le-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### What did you do?
```bash

$ python -m pip install grpcio 2>&1 | tee build-grpcio.log

```

### What did you expect to see?

Success!

### What did you see instead?

```bash

Collecting grpcio
  Using cached grpcio-1.46.3.tar.gz (21.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six>=1.5.2 in /home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages (from grpcio) (1.16.0)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py): started
  Building wheel for grpcio (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [3179 lines of output]
      ASM Builds for BoringSSL currently not supported on: linux-ppc64le
      Found cython-generated files...
      running bdist_wheel
      running build
      running build_py
      running build_project_metadata
      creating python_build
      creating python_build/lib.linux-ppc64le-cpython-38
      creating python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_common.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_simple_stubs.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_runtime_protos.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_compression.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_server.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_auth.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_plugin_wrapping.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_channel.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_utilities.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      copying src/python/grpcio/grpc/_interceptor.py -> python_build/lib.linux-ppc64le-cpython-38/grpc
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/_metadata.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/interfaces.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/_client_adaptations.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/utilities.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/_server_adaptations.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      copying src/python/grpcio/grpc/beta/implementations.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/beta
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/experimental
      copying src/python/grpcio/grpc/experimental/session_cache.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/experimental
      copying src/python/grpcio/grpc/experimental/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/experimental
      copying src/python/grpcio/grpc/experimental/gevent.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/experimental
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/framework
      copying src/python/grpcio/grpc/framework/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_metadata.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_server.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_base_server.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_base_call.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_channel.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_base_channel.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_call.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_typing.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_interceptor.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      copying src/python/grpcio/grpc/aio/_utils.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/aio
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/_cython
      copying src/python/grpcio/grpc/_cython/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/_cython
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/experimental/aio
      copying src/python/grpcio/grpc/experimental/aio/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/experimental/aio
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces
      copying src/python/grpcio/grpc/framework/interfaces/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/framework/common
      copying src/python/grpcio/grpc/framework/common/cardinality.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/common
      copying src/python/grpcio/grpc/framework/common/style.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/common
      copying src/python/grpcio/grpc/framework/common/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/common
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/future.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/callable_util.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/stream.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/abandonment.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/logging_pool.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      copying src/python/grpcio/grpc/framework/foundation/stream_util.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/foundation
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/base
      copying src/python/grpcio/grpc/framework/interfaces/base/base.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/base
      copying src/python/grpcio/grpc/framework/interfaces/base/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/base
      copying src/python/grpcio/grpc/framework/interfaces/base/utilities.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/base
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/face
      copying src/python/grpcio/grpc/framework/interfaces/face/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/face
      copying src/python/grpcio/grpc/framework/interfaces/face/utilities.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/face
      copying src/python/grpcio/grpc/framework/interfaces/face/face.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/framework/interfaces/face
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/_cython/_cygrpc
      copying src/python/grpcio/grpc/_cython/_cygrpc/__init__.py -> python_build/lib.linux-ppc64le-cpython-38/grpc/_cython/_cygrpc
      creating python_build/lib.linux-ppc64le-cpython-38/grpc/_cython/_credentials
      copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.linux-ppc64le-cpython-38/grpc/_cython/_credentials
      running build_ext
      Found cython-generated files...
      building 'grpc._cython.cygrpc' extension
      creating python_build/temp.linux-ppc64le-cpython-38
... (logs edited for brevity) ..

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
      cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
      In file included from src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc:26:0:
      third_party/xxhash/xxhash.h: In function ‘void XXH3_accumulate_512_vsx(void*, const void*, const void*)’:
      third_party/xxhash/xxhash.h:4148:58: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_ld
               xxh_u64x2 acc_vec        = vec_xl(0, xacc + 2 * i);
                                                                ^
      third_party/xxhash/xxhash.h:4158:41: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_st
               vec_xst(acc_vec, 0, xacc + 2 * i);
                                               ^
      powerpc64le-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fexceptions -g -fwrapv -O2 -fPIC -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.46.3\" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/include -I/usr/include/python3.8 -c third_party/abseil-cpp/absl/time/internal/cctz/src/zone_info_source.cc -o python_build/temp.linux-ppc64le-cpython-38/third_party/abseil-cpp/absl/time/internal/cctz/src/zone_info_source.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread

... (logs edited for brevity but these errors repeat many times) ..

Traceback (most recent call last):
        File "/tmp/pip-install-3yjmrpo4/grpcio_e081f518ed54430fa84ac95f5519e7ce/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/tmp/pip-install-3yjmrpo4/grpcio_e081f518ed54430fa84ac95f5519e7ce/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
          raise self._value
        File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/tmp/pip-install-3yjmrpo4/grpcio_e081f518ed54430fa84ac95f5519e7ce/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/piptestuser2/.cache/pypoetry/virtualenvs/cp-analysis-MzkzEAws-py3.8/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 176, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/powerpc64le-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I tried upgrading setuptools, cython, and wheel but to no avail. I also tried installing a newer gcc (`sudo apt-get install gcc-6 g++-6`) but that also doesn't seem to work.

**Comment by nicolasnoble** [comment]
If you can, try overriding the compilation flags to define `XXH_VECTOR` to 0. This will disable the vector optimizations when compiling xxhash. Ultimately however, this is a compilation problem on one of our external dependencies: https://github.com/Cyan4973/xxHash

It may be relevant to try their base examples and see if (1) it happens from the same version we have currently, (2) it happens from their HEAD, and (3) potentially file an issue on their repository.

**Comment by pt-arvind** [comment]
thanks let me try that and get back to this issue

**Comment by pt-arvind** [comment]
all I needed to do was update `powerpc64le-linux-gnu-gcc` which I found after digging through the issues on `xxhash`

the solution in case it helps others:

```bash

$ ll /usr/bin/powerpc64le-linux-gnu-gcc
lrwxrwxrwx 1 root root 5 May 20  2019 /usr/bin/powerpc64le-linux-gnu-gcc -> gcc-7*


$ sudo update-alternatives --install /usr/bin/powerpc64le-linux-gnu-gcc powerpc64le-linux-gnu-gcc /usr/bin/gcc-8 1
$ sudo update-alternatives --install /usr/bin/powerpc64le-linux-gnu-gcc powerpc64le-linux-gnu-gcc /usr/bin/gcc-7 2

$ update-alternatives --list powerpc64le-linux-gnu-gcc

# picked gcc-8
$ sudo update-alternatives --config powerpc64le-linux-gnu-gcc

# this now works!
$ poetry run python -m pip install grpcio 2>&1 | tee build-grpcio.log
```

thank you again for the tip
