### ISSUE TITLE
Error occurred at "pip install grpcio" on Mac M1

### ISSUE THREAD

**Issue by DrMartiner** [grpc/grpc#30064]
### What version of gRPC and what language are you using?
Python 3.9.1 (default, Jun 10 2022, 21:55:47)

### What operating system (Linux, Windows,...) and version?
21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)
pip install grpcio

PS: I try to use the solution: https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop

### What did you see instead?
```
Collecting grpcio
  Using cached grpcio-1.46.3.tar.gz (21.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six>=1.5.2 in /Users/username/.pyenv/versions/3.9.1/envs/tango_back/lib/python3.9/site-packages (from grpcio) (1.16.0)
Using legacy 'setup.py install' for grpcio, since package 'wheel' is not installed.
Installing collected packages: grpcio
  Running setup.py install for grpcio: started
  Running setup.py install for grpcio: finished with status 'error'
..............................
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/stdlib.h:361:13: note: insert '_Nonnull' if the pointer should never be null
      extern char *suboptarg;         /* getsubopt(3) external variable */
                  ^
                    _Nonnull
      In file included from /var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/tmp0ozp57af/a.c:2:
      In file included from /Users/username/.pyenv/versions/3.9.1/include/python3.9/Python.h:136:
      In file included from /Users/username/.pyenv/versions/3.9.1/include/python3.9/pythread.h:128:
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:328:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
      #if !_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT
           ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:197:2: note: expanded from macro '_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT'
              defined(SWIFT_CLASS_EXTRA) && (!defined(SWIFT_SDK_OVERLAY_PTHREAD_EPOCH) || (SWIFT_SDK_OVERLAY_PTHREAD_EPOCH < 1))
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:328:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:197:34: note: expanded from macro '_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT'
              defined(SWIFT_CLASS_EXTRA) && (!defined(SWIFT_SDK_OVERLAY_PTHREAD_EPOCH) || (SWIFT_SDK_OVERLAY_PTHREAD_EPOCH < 1))
                                              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:537:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
      #if !_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT
           ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:197:2: note: expanded from macro '_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT'
              defined(SWIFT_CLASS_EXTRA) && (!defined(SWIFT_SDK_OVERLAY_PTHREAD_EPOCH) || (SWIFT_SDK_OVERLAY_PTHREAD_EPOCH < 1))
              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:537:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
      /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/pthread.h:197:34: note: expanded from macro '_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT'
              defined(SWIFT_CLASS_EXTRA) && (!defined(SWIFT_SDK_OVERLAY_PTHREAD_EPOCH) || (SWIFT_SDK_OVERLAY_PTHREAD_EPOCH < 1))
                                              ^
      197 warnings generated.
      Traceback (most recent call last):
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/spawn.py", line 87, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/username/.pyenv/versions/3.9.1/envs/tango_back/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/setup.py", line 527, in <module>
          setuptools.setup(
        File "/Users/username/.pyenv/versions/3.9.1/envs/tango_back/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/username/.pyenv/versions/3.9.1/envs/tango_back/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/install.py", line 546, in run
          self.run_command('build')
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/username/.pyenv/versions/3.9.1/envs/tango_back/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 87, in run
          _build_ext.run(self)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/commands.py", line 284, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/spawn.py", line 87, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/username/.pyenv/versions/3.9.1/envs/tango_back/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-z2f1az_0/grpcio_0a9198af58c744269b29de516330c8df/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by DrMartiner** [comment]
`lipo -archs $(which python)`: `fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: can't figure out the architecture type of: /Users/username/.pyenv/shims/python`

The result of the command `rch -x86_64 python -m pip install grpcio` are same: many errors:
```
....

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-c2pjv7uv/grpcio_d8275d3192ba4169b1973fc6ee724a9e/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/username/.pyenv/versions/tango_back/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-c2pjv7uv/grpcio_d8275d3192ba4169b1973fc6ee724a9e/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-c2pjv7uv/grpcio_d8275d3192ba4169b1973fc6ee724a9e/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/dm/34ggc73d577dsxd6ngncgfx00000gn/T/pip-install-c2pjv7uv/grpcio_d8275d3192ba4169b1973fc6ee724a9e/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/username/.pyenv/versions/3.9.1/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by gnossen** [comment]
@DrMartiner Does your original post include the entire output? I'm seeing several clang warnings, but no clang errors. If not, can you please link to the full output?

**Comment by toanju** [comment]
[build.log](https://github.com/grpc/grpc/files/8977076/build.log)

Was running into build issues on an M1, too. Guessing they are related thus logs attached.

**Comment by gnossen** [comment]
@toanju Thanks for the logs!

```
DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.47.0\" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_darwin -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/Users/user/Library/Caches/pypoetry/virtualenvs/cvpcollector-Or5EsOiM-py3.8/include -I/Users/user/.pyenv/versions/3.8.13/include/python3.8 -c src/core/ext/filters/client_channel/lb_policy/address_filtering.cc -o python_build/temp.macosx-12.3-arm64-3.8/src/core/ext/filters/client_channel/lb_policy/address_filtering.o -std=c++14 -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -DHAVE_UNISTD_H -pthread
        clang: warning: argument unused during compilation: '-L/opt/homebrew/include' [-Wunused-command-line-argument]
        clang: warning: argument unused during compilation: '-L/opt/homebrew/include' [-Wunused-command-line-argument]
        src/core/lib/iomgr/resolve_address.cc:41:35: error: no member named 'keys' in 'grpc_event_engine::experimental::EventEngine::DNSResolver::LookupTaskHandle'; did you mean 'key'?
          return absl::StrCat("{", handle.keys[0], ",", handle.keys[1], "}");
                                          ^~~~
                                          key
        /opt/homebrew/include/grpc/event_engine/event_engine.h:262:16: note: 'key' declared here
              intptr_t key[2];
                       ^
        src/core/lib/iomgr/resolve_address.cc:41:56: error: no member named 'keys' in 'grpc_event_engine::experimental::EventEngine::DNSResolver::LookupTaskHandle'; did you mean 'key'?
          return absl::StrCat("{", handle.keys[0], ",", handle.keys[1], "}");
                                                               ^~~~
                                                               key
        /opt/homebrew/include/grpc/event_engine/event_engine.h:262:16: note: 'key' declared here
              intptr_t key[2];
                       ^
        2 errors generated.
```

```
        clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/include -L/opt/homebrew/include -L/opt/homebrew/include -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.47.0\" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_darwin -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/Users/user/Library/Caches/pypoetry/virtualenvs/cvpcollector-Or5EsOiM-py3.8/include -I/Users/user/.pyenv/versions/3.8.13/include/python3.8 -c src/core/lib/security/credentials/external/file_external_account_credentials.cc -o python_build/temp.macosx-12.3-arm64-3.8/src/core/lib/security/credentials/external/file_external_account_credentials.o -std=c++14 -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -DHAVE_UNISTD_H -pthread
        clang: warning: argument unused during compilation: '-L/opt/homebrew/include' [-Wunused-command-line-argument]
        clang: warning: argument unused during compilation: '-L/opt/homebrew/include' [-Wunused-command-line-argument]
        clang: warning: argument unused during compilation: '-L/opt/homebrew/include' [-Wunused-command-line-argument]
        clang: warning: argument unused during compilation: '-L/opt/homebrew/include' [-Wunused-command-line-argument]
        src/core/lib/surface/channel_stack_type.cc:38:3: error: use of undeclared identifier 'GPR_ERROR'
          GPR_UNREACHABLE_CODE(return true;);
          ^
        /opt/homebrew/include/grpc/impl/codegen/port_platform.h:555:13: note: expanded from macro 'GPR_UNREACHABLE_CODE'
            gpr_log(GPR_ERROR, "Should never reach here."); \
                    ^
        src/core/lib/surface/channel_stack_type.cc:38:3: error: use of undeclared identifier 'abort'
        /opt/homebrew/include/grpc/impl/codegen/port_platform.h:556:5: note: expanded from macro 'GPR_UNREACHABLE_CODE'
            abort();                                        \
            ^
        src/core/lib/surface/channel_stack_type.cc:56:3: error: use of undeclared identifier 'GPR_ERROR'
          GPR_UNREACHABLE_CODE(return "UNKNOWN");
          ^
        /opt/homebrew/include/grpc/impl/codegen/port_platform.h:555:13: note: expanded from macro 'GPR_UNREACHABLE_CODE'
            gpr_log(GPR_ERROR, "Should never reach here."); \
                    ^
        src/core/lib/surface/channel_stack_type.cc:56:3: error: use of undeclared identifier 'abort'
        /opt/homebrew/include/grpc/impl/codegen/port_platform.h:556:5: note: expanded from macro 'GPR_UNREACHABLE_CODE'
            abort();                                        \
            ^
        4 errors generated.
```

@drfloob Looks like some of this is event engine related. Would you please take a look?

**Comment by drfloob** [comment]
@toanju It looks like you're compiling newer gRPC code against an older version's set of headers. The `event_engine.h` installed at `/opt/homebrew/include/grpc/event_engine/event_engine.h` is likely older, since the `key` field the compiler is complaining about was changed to `keys` before v1.47. An older version of gRPC may have been installed as a transitive dependency, but if it's possible to remove it, I'd try that and see if it fixes the issue.

@gnossen otherwise, we may need to investigate how to teach the compiler to prefer headers from the source distribution over other include paths.

**Comment by gnossen** [comment]
I will try to reproduce this locally and see if I tweak the build process to prefer the packaged headers over system headers. The current workaround might have some pretty annoying implications, like having to uninstall `mosh`.

**Comment by toanju** [comment]
@drfloob thanks, great spot. Just did a clean reinstall and it worked without a problem.

**Comment by reecenil** [comment]
@toanju , What do you mean by clean reinstall? which exact commands did you use? Thanks!

**Comment by toanju** [comment]
I had grpc installed via brew which I used some time ago. In addition the required headers and libs were by default setup into my env (CFLAGS, ...). As I did no longer need the local grpc lib I simply uninstalled it and removed the env setup.

**Comment by t4t5** [comment]
This worked for me:

```
GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install grpcio
```

**Comment by ehagerty** [comment]
forgive my question, but would it be appropriate/safe to always set GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true and GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true in my development python environments?

**Comment by ulises-castro** [comment]
> This worked for me:
> 
> ```
> GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install grpcio
> ```

That worked for me as well, thank you so much.
