### ISSUE TITLE
Segmentation fault apache2

### ISSUE THREAD

**Issue by niyonx** [grpc/grpc#30075]
### What version of gRPC and what language are you using?
1.46.3

### What operating system (Linux, Windows,...) and version?
Ubuntu 22

### What runtime / compiler are you using (e.g. python version or version of gcc)
Apache php

### What did you do?
I was seeing some segmentation faults by apache. I checked and got this error log

```
(gdb) bt full
#0  0x00007eff9897064a in zend_hash_apply_with_argument () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#1  0x00007eff989ced94 in zend_unregister_ini_entries () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#2  0x00007eff99011dcf in ?? () from /usr/lib/php/20210902/opcache.so
No symbol table info available.
#3  0x00007eff989642df in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#4  0x00007eff9895c830 in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#5  0x00007eff98970239 in zend_hash_graceful_reverse_destroy () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#6  0x00007eff9895dbe7 in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#7  0x00007eff988fb002 in php_module_shutdown () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#8  0x00007eff988fb0ad in php_module_shutdown_wrapper () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#9  0x00007eff98a44c65 in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#10 0x00007eff99b42a8e in apr_pool_destroy () from /lib/x86_64-linux-gnu/libapr-1.so.0
No symbol table info available.
#11 0x00007eff997b6387 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#12 0x00007eff997b6a59 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#13 0x00007eff997b6def in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#14 0x00007eff997b7b68 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#15 0x0000556b5b0abdc8 in ap_run_mpm ()
No symbol table info available.
#16 0x0000556b5b0a37f9 in main ()
No symbol table info available.
(gdb) thread apply all bt full

Thread 4 (Thread 0x7eff9124f700 (LWP 738250)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007eff97ddb2f2 in absl::lts_20211102::synchronization_internal::FutexImpl::WaitUntil (t=..., val=0, v=0x7eff924c8340) at **/tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/futex.h:97**
        abs_timeout = {tv_sec = 1655836271, tv_nsec = 610042950}
        err = 0
        err = <optimized out>
        abs_timeout = <optimized out>
#2  absl::lts_20211102::synchronization_internal::Waiter::Wait (this=this@entry=0x7eff924c8340, t=t@entry=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.cc:95
        x = <optimized out>
        err = <optimized out>
        first_pass = <optimized out>
#3  0x00007eff97ddb1a6 in AbslInternalPerThreadSemWait_lts_20211102 (t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.h:95
        timeout = false
        identity = 0x7eff924c8300
        ticker = <optimized out>
#4  0x00007eff97ddeff0 in absl::lts_20211102::CondVar::WaitCommon (this=0x7eff9810f900 <g_cv_wait>, mutex=0x7eff9810f910 <g_mu>, t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/mutex.cc:2559
        rc = false
        mutex_v = <optimized out>
        mutex_how = 0x7eff97fd6a80 <absl::lts_20211102::kExclusiveS>
        v = <optimized out>
        waitp = {how = 0x7eff97fd6a80 <absl::lts_20211102::kExclusiveS>, cond = 0x0, timeout = {ns_ = 1655836271610042950}, cvmu = 0x7eff9810f910 <g_mu>, thread = 0x7eff924c8300, cv_word = 0x0, contention_start_cycles = 312794504744024}
#5  0x00007eff97c8d808 in gpr_cv_wait (cv=cv@entry=0x7eff9810f900 <g_cv_wait>, mu=mu@entry=0x7eff9810f910 <g_mu>, abs_deadline=...) at /tmp/pear/temp/grpc/src/core/lib/gpr/sync_abseil.cc:92
        ts = <optimized out>
#6  0x00007eff97cbc1b1 in wait_until (next=...) at /tmp/pear/temp/grpc/src/core/lib/iomgr/timer_manager.cc:202
        my_timed_waiter_generation = <optimized out>
#7  timer_main_loop () at /tmp/pear/temp/grpc/src/core/lib/iomgr/timer_manager.cc:256
        next = {millis_ = 66814}
#8  timer_thread (completed_thread_ptr=0x556b5bb1a450) at /tmp/pear/temp/grpc/src/core/lib/iomgr/timer_manager.cc:285
        exec_ctx = {_vptr.ExecCtx = 0x7eff980dc990 <vtable for grpc_core::ExecCtx+16>, closure_list_ = {head = 0x0, tail = 0x0}, combiner_data_ = {active_combiner = 0x0, last_combiner = 0x0}, flags_ = 4, starting_cpu_ = 4294967295, now_is_valid_ = true, now_ = {millis_ = 65814}, static exec_ctx_ = 0x7eff9124edc0, last_exec_ctx_ = 0x0}
#9  0x00007eff97c92860 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>) at /tmp/pear/temp/grpc/src/core/lib/gprpp/thd_posix.cc:140
        arg = {thread = 0x556b5bb1a480, body = 0x7eff97cbbe90 <timer_thread(void*)>, arg = 0x556b5bb1a450, name = <optimized out>, joinable = <optimized out>, tracked = <optimized out>}
#10 grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at /tmp/pear/temp/grpc/src/core/lib/gprpp/thd_posix.cc:145
No locals.
#11 0x00007eff99b06609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139636116879104, 1872946832369873920, 140737048134766, 140737048134767, 140737048134928, 139636116877184, -2017285591181724672, -2017269206235778048}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#12 0x00007eff99a2b133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 3 (Thread 0x7eff91a50700 (LWP 738249)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007eff97ddb28e in absl::lts_20211102::synchronization_internal::FutexImpl::WaitUntil (t=..., val=0, v=0x7eff924c7d40) at **/tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/futex.h:104**
        err = 0
        err = <optimized out>
        abs_timeout = <optimized out>
#2  absl::lts_20211102::synchronization_internal::Waiter::Wait (this=this@entry=0x7eff924c7d40, t=t@entry=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.cc:95
        x = <optimized out>
        err = <optimized out>
        first_pass = <optimized out>
#3  0x00007eff97ddb1a6 in AbslInternalPerThreadSemWait_lts_20211102 (t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.h:95
        timeout = false
        identity = 0x7eff924c7d00
        ticker = <optimized out>
#4  0x00007eff97ddeff0 in absl::lts_20211102::CondVar::WaitCommon (this=0x556b5bb22828, mutex=0x556b5bb22810, t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/mutex.cc:2559
        rc = false
        mutex_v = <optimized out>
        mutex_how = 0x7eff97fd6a80 <absl::lts_20211102::kExclusiveS>
        v = <optimized out>
        waitp = {how = 0x7eff97fd6a80 <absl::lts_20211102::kExclusiveS>, cond = 0x0, timeout = {ns_ = 0}, cvmu = 0x556b5bb22810, thread = 0x7eff924c7d00, cv_word = 0x0, contention_start_cycles = 312754483482572}
#5  0x00007eff97c8d82f in gpr_cv_wait (cv=cv@entry=0x556b5bb22828, mu=mu@entry=0x556b5bb22810, abs_deadline=...) at /tmp/pear/temp/grpc/src/core/lib/gpr/sync_abseil.cc:85
        ts = <optimized out>
#6  0x00007eff97caa9bd in grpc_core::Executor::ThreadMain (arg=0x556b5bb22810) at /tmp/pear/temp/grpc/src/core/lib/iomgr/executor.cc:238
        closures = <optimized out>
        ts = 0x556b5bb22810
        exec_ctx = {_vptr.ExecCtx = 0x7eff980dc990 <vtable for grpc_core::ExecCtx+16>, closure_list_ = {head = 0x0, tail = 0x0}, combiner_data_ = {active_combiner = 0x0, last_combiner = 0x0}, flags_ = 4, starting_cpu_ = 4294967295, now_is_valid_ = false, now_ = {millis_ = 0}, static exec_ctx_ = 0x7eff91a4fdc0, last_exec_ctx_ = 0x0}
        subtract_depth = 0
#7  0x00007eff97c92860 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>) at /tmp/pear/temp/grpc/src/core/lib/gprpp/thd_posix.cc:140
        arg = {thread = 0x556b5bb24860, body = 0x7eff97caa880 <grpc_core::Executor::ThreadMain(void*)>, arg = 0x556b5bb22810, name = <optimized out>, joinable = <optimized out>, tracked = <optimized out>}
#8  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at /tmp/pear/temp/grpc/src/core/lib/gprpp/thd_posix.cc:145
No locals.
#9  0x00007eff99b06609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139636125271808, 1872946832369873920, 140737048134590, 140737048134591, 140737048134752, 139636125269888, -2017286690156481536, -2017269206235778048}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#10 0x00007eff99a2b133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7eff92251700 (LWP 738248)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007eff97ddb28e in absl::lts_20211102::synchronization_internal::FutexImpl::WaitUntil (t=..., val=0, v=0x7eff924c7740) at **/tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/futex.h:104**
        err = 0
        err = <optimized out>
        abs_timeout = <optimized out>
#2  absl::lts_20211102::synchronization_internal::Waiter::Wait (this=this@entry=0x7eff924c7740, t=t@entry=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.cc:95
        x = <optimized out>
        err = <optimized out>
        first_pass = <optimized out>
#3  0x00007eff97ddb1a6 in AbslInternalPerThreadSemWait_lts_20211102 (t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.h:95
        timeout = false
        identity = 0x7eff924c7700
        ticker = <optimized out>
#4  0x00007eff97ddeff0 in absl::lts_20211102::CondVar::WaitCommon (this=0x556b5bb22338, mutex=0x556b5bb22320, t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/mutex.cc:2559
        rc = false
        mutex_v = <optimized out>
        mutex_how = 0x7eff97fd6a80 <absl::lts_20211102::kExclusiveS>
        v = <optimized out>
        waitp = {how = 0x7eff97fd6a80 <absl::lts_20211102::kExclusiveS>, cond = 0x0, timeout = {ns_ = 0}, cvmu = 0x556b5bb22320, thread = 0x7eff924c7700, cv_word = 0x0, contention_start_cycles = 312754483424102}
#5  0x00007eff97c8d82f in gpr_cv_wait (cv=cv@entry=0x556b5bb22338, mu=mu@entry=0x556b5bb22320, abs_deadline=...) at /tmp/pear/temp/grpc/src/core/lib/gpr/sync_abseil.cc:85
        ts = <optimized out>
#6  0x00007eff97caa9bd in grpc_core::Executor::ThreadMain (arg=0x556b5bb22320) at /tmp/pear/temp/grpc/src/core/lib/iomgr/executor.cc:238
        closures = <optimized out>
        ts = 0x556b5bb22320
        exec_ctx = {_vptr.ExecCtx = 0x7eff980dc990 <vtable for grpc_core::ExecCtx+16>, closure_list_ = {head = 0x0, tail = 0x0}, combiner_data_ = {active_combiner = 0x0, last_combiner = 0x0}, flags_ = 4, starting_cpu_ = 4294967295, now_is_valid_ = false, now_ = {millis_ = 0}, static exec_ctx_ = 0x7eff92250dc0, last_exec_ctx_ = 0x0}
        subtract_depth = 0
#7  0x00007eff97c92860 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator() (__closure=0x0, v=<optimized out>) at /tmp/pear/temp/grpc/src/core/lib/gprpp/thd_posix.cc:140
        arg = {thread = 0x556b5b582cf0, body = 0x7eff97caa880 <grpc_core::Executor::ThreadMain(void*)>, arg = 0x556b5bb22320, name = <optimized out>, joinable = <optimized out>, tracked = <optimized out>}
#8  grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at /tmp/pear/temp/grpc/src/core/lib/gprpp/thd_posix.cc:145
No locals.
#9  0x00007eff99b06609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139636133664512, 1872946832369873920, 140737048134590, 140737048134591, 140737048134752, 139636133662592, -2017278988743248896, -2017269206235778048}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#10 0x00007eff99a2b133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7eff99890d40 (LWP 738244)):
#0  0x00007eff9897064a in zend_hash_apply_with_argument () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#1  0x00007eff989ced94 in zend_unregister_ini_entries () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#2  0x00007eff99011dcf in ?? () from /usr/lib/php/20210902/opcache.so
No symbol table info available.
#3  0x00007eff989642df in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#4  0x00007eff9895c830 in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#5  0x00007eff98970239 in zend_hash_graceful_reverse_destroy () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#6  0x00007eff9895dbe7 in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#7  0x00007eff988fb002 in php_module_shutdown () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#8  0x00007eff988fb0ad in php_module_shutdown_wrapper () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#9  0x00007eff98a44c65 in ?? () from /usr/lib/apache2/modules/libphp8.1.so
No symbol table info available.
#10 0x00007eff99b42a8e in apr_pool_destroy () from /lib/x86_64-linux-gnu/libapr-1.so.0
No symbol table info available.
#11 0x00007eff997b6387 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#12 0x00007eff997b6a59 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#13 0x00007eff997b6def in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#14 0x00007eff997b7b68 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#15 0x0000556b5b0abdc8 in ap_run_mpm ()
No symbol table info available.
#16 0x0000556b5b0a37f9 in main ()
No symbol table info available.

```

I then decided to update grpc with 

```
sudo pecl install grpc
```

in the last lines of the install I then see segmentation fault.

```
/bin/bash /tmp/pear/temp/pear-build-rootFPCUZl/grpc-1.46.3/libtool --mode=install cp ./grpc.la /tmp/pear/temp/pear-build-rootFPCUZl/grpc-1.46.3/modules
libtool: install: cp ./.libs/grpc.so /tmp/pear/temp/pear-build-rootFPCUZl/grpc-1.46.3/modules/grpc.so
libtool: install: cp ./.libs/grpc.lai /tmp/pear/temp/pear-build-rootFPCUZl/grpc-1.46.3/modules/grpc.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /tmp/pear/temp/pear-build-rootFPCUZl/grpc-1.46.3/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/pear/temp/pear-build-rootFPCUZl/grpc-1.46.3/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3" install
Installing shared extensions:     /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3/usr/lib/php/20210902/
running: find "/tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3" | xargs ls -dils
1556359      4 drwxr-xr-x 3 root root      4096 Jun 21 15:22 /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3
2071832      4 drwxr-xr-x 3 root root      4096 Jun 21 15:22 /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3/usr
2071833      4 drwxr-xr-x 3 root root      4096 Jun 21 15:22 /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3/usr/lib
2071834      4 drwxr-xr-x 3 root root      4096 Jun 21 15:22 /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3/usr/lib/php
2071835      4 drwxr-xr-x 2 root root      4096 Jun 21 15:22 /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3/usr/lib/php/20210902
2071836 190436 -rwxr-xr-x 1 root root 195004048 Jun 21 15:22 /tmp/pear/temp/pear-build-rootFPCUZl/install-grpc-1.46.3/usr/lib/php/20210902/grpc.so

Build process completed successfully
Installing '/usr/lib/php/20210902/grpc.so'
**Segmentation fault**
```

### Anything else we should know about your project / environment?

I use grpc to send firestore messages from PHP and followed this tutorial. https://cloud.google.com/php/grpc

**Comment by niyonx** [comment]
In some other coredumps, I see

```
Error while mapping shared library sections:
`/usr/lib/php/20210902/grpc.so': not in executable format: file truncated
```

**Comment by alto-php** [comment]
Are you still seeing this issue with latest version?
