### ISSUE TITLE
Crash on exit when `std::shared_ptr<::grpc::Channel>` object is in global scope and built with `-O0` flag

### ISSUE THREAD

**Issue by jiminj** [grpc/grpc#30151]
# 

### What version of gRPC and what language are you using?
1.45.2

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 9.4, confirmed that having the same issue with gcc 7.5

### What did you do?
Found out it crashes on exit when `std::shared_ptr<::grpc::Channel> channel;` is on global scope and optimization level is `-O0`.

Below is the minimal reproducible code. The target endpoint should be a valid one.

```c++
#include <iostream>
#include <grpcpp/channel.h>
#include <grpcpp/create_channel.h>

using namespace std::chrono_literals;
namespace {
    std::shared_ptr<::grpc::Channel> channel;
}

int main() {
    channel = ::grpc::CreateChannel(“endpoint address”, 
                                    ::grpc::InsecureChannelCredentials());
    channel->WaitForConnected(std::chrono::system_clock::now() + 10s);
    auto channelState = channel->GetState(false);
    std::cout << “done: “ << channelState << std::endl;
}
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.22)

set(TARGET GrpcErrorReprod)
set(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
project(${TARGET} LANGUAGES CXX)

include(FetchContent)

## grpc
FetchContent_Declare( grpc
        GIT_REPOSITORY https://github.com/grpc/grpc
        GIT_TAG        v1.45.2
        )
FetchContent_MakeAvailable(grpc)
add_executable(${TARGET} main.cpp)
target_link_libraries(${TARGET} PUBLIC grpc++)
```

### What did you expect to see?
Successful build & run
```
done: 2
```

### What did you see instead?
Crash on exit
```
done: 2
pure virtual method called
terminate called without an active exception
```

```gdb
(gdb) r
Starting program: /home/project/cmake-build-debug/GrpcErrorReprod
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6bf7700 (LWP 33479)]
[New Thread 0x7ffff63f6700 (LWP 33480)]
[New Thread 0x7ffff5bf5700 (LWP 33481)]
done: 2
pure virtual method called
terminate called without an active exception

Thread 1 "GrpcErrorReprod" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6c387f1 in __GI_abort () at abort.c:79
#2  0x00007ffff763c0a9 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7647506 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7647571 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff764825f in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555556fe19b in grpc_core::Waker::~Waker (this=0x7ffff0002bf0, __in_chrg=<optimized out>) at /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/promise/activity.h:68
#7  0x00005555556f6d27 in grpc_core::ReclamationSweep::~ReclamationSweep (this=0x7ffff0002bd8, __in_chrg=<optimized out>) at /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/resource_quota/memory_quota.cc:44
#8  0x0000555555654d43 in grpc_chttp2_transport::~grpc_chttp2_transport (this=0x7ffff0002b70, __in_chrg=<optimized out>)
    at /home/project/cmake-build-debug/_deps/grpc-src/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:202
#9  0x0000555555663b53 in grpc_chttp2_unref_transport (t=0x7ffff0002b70, reason=0x555555cd0f84 "reading_action",
    file=0x555555ccfdc0 "/home/project/cmake-build-debug/_deps/grpc-src/src/core/ext/transport/chttp2/transport/chttp2_transport.cc", line=2540)
    at /home/project/cmake-build-debug/_deps/grpc-src/src/core/ext/transport/chttp2/transport/internal.h:800
#10 0x000055555565ec2d in read_action_locked (tp=0x7ffff0002b70, error=0x555556329af0) at /home/project/cmake-build-debug/_deps/grpc-src/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2540
#11 0x00005555556cf9c2 in grpc_combiner_continue_exec_ctx () at /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/combiner.cc:240
#12 0x00005555556d3e05 in grpc_core::ExecCtx::Flush (this=0x7fffffffbe30) at /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/exec_ctx.cc:82
#13 0x00005555555c4663 in grpc_core::ExecCtx::~ExecCtx (this=0x7fffffffbe30, __in_chrg=<optimized out>) at /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/exec_ctx.h:117
#14 0x000055555572b4cd in grpc_channel_destroy (channel=0x555556327e50) at /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/surface/channel.cc:501
#15 0x00005555555ba97b in grpc::Channel::~Channel (this=0x555556325ed0, __in_chrg=<optimized out>) at /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/client/channel_cc.cc:59
#16 0x00005555555baa58 in grpc::Channel::~Channel (this=0x555556325ed0, __in_chrg=<optimized out>) at /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/client/channel_cc.cc:69
#17 0x00005555555c2947 in std::_Sp_counted_ptr<grpc::Channel*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555563262e0) at /usr/include/c++/9/bits/shared_ptr_base.h:377
#18 0x00005555555ba2ae in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555563262e0) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#19 0x00005555555ba0fd in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5555562f9bf8 <(anonymous namespace)::channel+8>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#20 0x00005555555ba022 in std::__shared_ptr<grpc::Channel, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5555562f9bf0 <(anonymous namespace)::channel>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#21 0x00005555555ba03e in std::shared_ptr<grpc::Channel>::~shared_ptr (this=0x5555562f9bf0 <(anonymous namespace)::channel>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#22 0x00007ffff6c3b031 in __run_exit_handlers (status=0, listp=0x7ffff6fe3718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#23 0x00007ffff6c3b12a in __GI_exit (status=<optimized out>) at exit.c:139
#24 0x00007ffff6c19c8e in __libc_start_main (main=0x5555555b9ce5 <main()>, argc=1, argv=0x7fffffffc0c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffc0b8) at ../csu/libc-start.c:344
#25 0x00005555555b9c2a in _start ()
(gdb)
```

Not sure this is related, but I got a TSAN warning message as well when I enabled it.

```
==================
WARNING: ThreadSanitizer: data race (pid=79945)
  Atomic write of size 4 at 0x7fe6ed98f140 by main thread:
    #0 __tsan_atomic32_fetch_add <null> (libtsan.so.0+0x816a5)
    #1 std::__atomic_base<int>::fetch_add(int, std::memory_order) /usr/include/c++/9/bits/atomic_base.h:541 (GrpcErrorReprod+0x8175cc)
    #2 absl::lts_20211102::synchronization_internal::Waiter::Post() /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/internal/waiter.cc:110 (GrpcErrorReprod+0x8175cc)
    #3 AbslInternalPerThreadSemPost_lts_20211102 /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/internal/per_thread_sem.cc:73 (GrpcErrorReprod+0x816f9b)
    #4 absl::lts_20211102::synchronization_internal::PerThreadSem::Post(absl::lts_20211102::base_internal::ThreadIdentity*) <null> (GrpcErrorReprod+0x81507a)
    #5 absl::lts_20211102::Mutex::IncrementSynchSem(absl::lts_20211102::Mutex*, absl::lts_20211102::base_internal::PerThreadSynch*) /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:566 (GrpcErrorReprod+0x80a7e8)
    #6 absl::lts_20211102::Mutex::Wakeup(absl::lts_20211102::base_internal::PerThreadSynch*) /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:1156 (GrpcErrorReprod+0x80c0fd)
    #7 absl::lts_20211102::Mutex::UnlockSlow(absl::lts_20211102::SynchWaitParams*) /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:2321 (GrpcErrorReprod+0x811fec)
    #8 absl::lts_20211102::Mutex::Unlock() /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:1712 (GrpcErrorReprod+0x80ef13)
    #9 gpr_mu_unlock /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/gpr/sync_abseil.cc:61 (GrpcErrorReprod+0x76a59b)
    #10 grpc_core::Executor::Enqueue(grpc_closure*, grpc_error*, bool) /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:354 (GrpcErrorReprod+0x21ac35)
    #11 default_enqueue_short /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:60 (GrpcErrorReprod+0x219417)
    #12 grpc_core::Executor::Run(grpc_closure*, grpc_error*, grpc_core::ExecutorType, grpc_core::ExecutorJobType) /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:401 (GrpcErrorReprod+0x21b07a)
    #13 on_writable /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/tcp_client_posix.cc:237 (GrpcErrorReprod+0x2225d4)
    #14 exec_ctx_run /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/exec_ctx.cc:49 (GrpcErrorReprod+0x218b04)
    #15 grpc_core::ExecCtx::Flush() /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/exec_ctx.cc:79 (GrpcErrorReprod+0x218c98)
    #16 end_worker /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/ev_epoll1_linux.cc:990 (GrpcErrorReprod+0x5830dc)
    #17 pollset_work /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/ev_epoll1_linux.cc:1059 (GrpcErrorReprod+0x58352a)
    #18 pollset_work /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/ev_posix.cc:323 (GrpcErrorReprod+0x217efc)
    #19 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, grpc_core::Timestamp) /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/pollset.cc:48 (GrpcErrorReprod+0x21ca57)
    #20 cq_next /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/surface/completion_queue.cc:1047 (GrpcErrorReprod+0x2a7a85)
    #21 grpc_completion_queue_next /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/surface/completion_queue.cc:1126 (GrpcErrorReprod+0x2a824c)
    #22 grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/common/completion_queue_cc.cc:146 (GrpcErrorReprod+0x81608)
    #23 grpc::CompletionQueue::Next(void**, bool*) <null> (GrpcErrorReprod+0x700d7)
    #24 grpc::Channel::WaitForStateChangeImpl(grpc_connectivity_state, gpr_timespec) /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/client/channel_cc.cc:211 (GrpcErrorReprod+0x6e8f3)
    #25 bool grpc::ChannelInterface::WaitForStateChange<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > >(grpc_connectivity_state, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) <null> (GrpcErrorReprod+0x6d2b6)
    #26 bool grpc::ChannelInterface::WaitForConnected<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > >(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) <null> (GrpcErrorReprod+0x6ce01)
    #27 main /home/project/main.cpp:12 (GrpcErrorReprod+0x6c650)

  Previous write of size 8 at 0x7fe6ed98f140 by thread T1:
    #0 mmap <null> (libtsan.so.0+0x6191d)
    #1 DoAllocWithArena /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/base/internal/low_level_alloc.cc:562 (GrpcErrorReprod+0x82fea5)
    #2 absl::lts_20211102::base_internal::LowLevelAlloc::Alloc(unsigned long) /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/base/internal/low_level_alloc.cc:606 (GrpcErrorReprod+0xa904cf)
    #3 NewThreadIdentity /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/internal/create_thread_identity.cc:113 (GrpcErrorReprod+0x816b1e)
    #4 absl::lts_20211102::synchronization_internal::CreateThreadIdentity() /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/internal/create_thread_identity.cc:129 (GrpcErrorReprod+0x816b99)
    #5 absl::lts_20211102::synchronization_internal::GetOrCreateCurrentThreadIdentity() /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/internal/create_thread_identity.h:51 (GrpcErrorReprod+0x815027)
    #6 Synch_GetPerThread /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:538 (GrpcErrorReprod+0x80a662)
    #7 Synch_GetPerThreadAnnotated /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:546 (GrpcErrorReprod+0x80a6c4)
    #8 absl::lts_20211102::CondVar::WaitCommon(absl::lts_20211102::Mutex*, absl::lts_20211102::synchronization_internal::KernelTimeout) /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:2550 (GrpcErrorReprod+0x813536)
    #9 absl::lts_20211102::CondVar::Wait(absl::lts_20211102::Mutex*) /home/project/cmake-build-debug/_deps/grpc-src/third_party/abseil-cpp/absl/synchronization/mutex.cc:2594 (GrpcErrorReprod+0x813907)
    #10 gpr_cv_wait /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/gpr/sync_abseil.cc:85 (GrpcErrorReprod+0x76a6e9)
    #11 grpc_core::Executor::ThreadMain(void*) /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:238 (GrpcErrorReprod+0x21a4f3)
    #12 operator() /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/gprpp/thd_posix.cc:140 (GrpcErrorReprod+0x77716a)
    #13 _FUN /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/gprpp/thd_posix.cc:145 (GrpcErrorReprod+0x7771e0)
    #14 <null> <null> (libtsan.so.0+0x2e3bf)

  Thread T1 'default-executo' (tid=80092, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x5fe84)
    #1 ThreadInternalsPosix /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/gprpp/thd_posix.cc:108 (GrpcErrorReprod+0x77759f)
    #2 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/gprpp/thd_posix.cc:186 (GrpcErrorReprod+0x7778ce)
    #3 grpc_core::Executor::SetThreading(bool) /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:172 (GrpcErrorReprod+0x219d87)
    #4 grpc_core::Executor::Init() /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:97 (GrpcErrorReprod+0x21969d)
    #5 grpc_core::Executor::InitAll() /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/executor.cc:392 (GrpcErrorReprod+0x21af88)
    #6 grpc_iomgr_init() /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/iomgr/iomgr.cc:62 (GrpcErrorReprod+0x596410)
    #7 grpc_init /home/project/cmake-build-debug/_deps/grpc-src/src/core/lib/surface/init.cc:185 (GrpcErrorReprod+0x2abd91)
    #8 grpc::internal::GrpcLibrary::init() /home/project/cmake-build-debug/_deps/grpc-src/include/grpcpp/impl/grpc_library.h:34 (GrpcErrorReprod+0x707f7)
    #9 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) /home/project/cmake-build-debug/_deps/grpc-src/include/grpcpp/impl/codegen/grpc_library.h:48 (GrpcErrorReprod+0x6fae6)
    #10 grpc::ChannelCredentials::ChannelCredentials() /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/client/credentials_cc.cc:25 (GrpcErrorReprod+0x86153)
    #11 InsecureChannelCredentialsImpl /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/client/insecure_credentials.cc:31 (GrpcErrorReprod+0x7ad62)
    #12 grpc::InsecureChannelCredentials() /home/project/cmake-build-debug/_deps/grpc-src/src/cpp/client/insecure_credentials.cc:65 (GrpcErrorReprod+0x7ae09)
    #13 main /home/project/main.cpp:11 (GrpcErrorReprod+0x6c594)

SUMMARY: ThreadSanitizer: data race (/usr/lib/x86_64-linux-gnu/libtsan.so.0+0x816a5) in __tsan_atomic32_fetch_add
```

**Comment by markdroth** [comment]
We don't support global gRPC objects like that.  For some context, see #29861.

**Comment by amaciuc** [comment]
@jiminj 

I got the same warnings from TSAN as you. Any news about these data races ?

**Comment by jiminj** [comment]
> 
@amaciuc 
If my memory is correct, it was related to the issue and was gone after I removed this global channel allocation. Check out the lifecycle of the channel objects.

**Comment by amaciuc** [comment]
I found that my warnings are related to this [issue](https://github.com/google/sanitizers/issues/953): it comes from abseil-cpp.

Thank you!
