### ISSUE TITLE
Observed " Error shutting down fd 43. errno: 9" Error from grpc when rpc is invoked

### ISSUE THREAD

**Issue by balaji07s** [grpc/grpc#30328]
I have seen the below error trace during rpc gets invoked in the client side.

> E0108 23:57:39.627493254 13286 ev_epollex_linux.cc:512] Error shutting down fd 43. errno: 9

Adding the backtrace taken from gdb below for reference.
```

(gdb) bt
#0  0x00007ffff6a21770 in shutdown () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5c3a085 in fd_shutdown (fd=0x7fff8006d8c0, why=0x7fff640008e0) at src/core/lib/iomgr/ev_epollex_linux.cc:491
#2  0x00007ffff5ce4db5 in fd_node_shutdown_locked (reason=reason@entry=0x7ffff5dce61d "grpc_ares_ev_driver_shutdown", fdn=<optimized out>, fdn=<optimized out>)
    at src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:127
#3  0x00007ffff5ce5763 in fd_node_shutdown_locked (fdn=0x7fff80059190, fdn=0x7fff80059190, reason=0x7ffff5dce61d "grpc_ares_ev_driver_shutdown")
    at src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:124
#4  grpc_ares_ev_driver_shutdown_locked (ev_driver=<optimized out>) at src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:184
#5  0x00007ffff5ce57ee in on_timeout_locked (arg=0x7fff8005b5f0, error=0x0) at src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc:214
#6  0x00007ffff5c3584a in grpc_combiner_continue_exec_ctx () at src/core/lib/iomgr/combiner.cc:268
#7  0x00007ffff5c3f357 in grpc_core::ExecCtx::Flush (this=0x7fff799f2d70) at src/core/lib/iomgr/exec_ctx.cc:151
#8  0x00007ffff5c3aba4 in pollset_work (pollset=0x7fff800592b0, worker_hdl=0x7fff799f2c20, deadline=140735341239128) at src/core/lib/iomgr/ev_epollex_linux.cc:1151
#9  0x00007ffff5cb0741 in run_poller (arg=0x7fff80059a00, error=<optimized out>) at src/core/ext/filters/client_channel/backup_poller.cc:122
#10 0x00007ffff5c3f0ce in exec_ctx_run (closure=<optimized out>, error=0x0) at src/core/lib/iomgr/exec_ctx.cc:40
#11 0x00007ffff5c3f33c in grpc_core::ExecCtx::Flush (this=0x7fff799f2d70) at src/core/lib/iomgr/exec_ctx.cc:148
#12 0x00007ffff5c4f134 in run_some_timers () at src/core/lib/iomgr/timer_manager.cc:140
#13 timer_main_loop () at src/core/lib/iomgr/timer_manager.cc:246
#14 timer_thread (completed_thread_ptr=0x7fff700008e0) at src/core/lib/iomgr/timer_manager.cc:293
#15 0x00007ffff5cef443 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::_FUN(void*) () at src/core/lib/gprpp/thd_posix.cc:114
#16 0x00007ffff77a7064 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#17 0x00007ffff6a2062d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Please let me know why this error trace is coming and how to resolve this.
thanks!!!
```

**Comment by yashykt** [comment]
Note that epollex engine has been deleted

**Comment by balaji07s** [comment]
I have few questions.

1. What caused the epollex engine to be deleted?
2. Is this epollex engine deletion will affect the grpc communication?
3. if this will cause any issue means  how to resolve this?

Thanks!!!
