### ISSUE TITLE
Node Installation error on Linux 4.0.9-boot2docker

### ISSUE THREAD

**Issue by jasonkuhrt** [grpc/grpc#3033]
```
Step 5 : RUN npm install --global grpc
 ---> Running in 5af8acca20f0

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/grpc/node_modules/protobufjs/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync
> node postinstall


> grpc@0.10.1 install /usr/local/lib/node_modules/grpc
> node-gyp rebuild

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/grpc/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
../ext/call.cc: In static member function 'static void grpc::node::Call::New(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:513:63: error: cannot convert 'grpc_completion_queue*' to 'grpc_call*' for argument '2' to 'grpc_call* grpc_channel_create_call(grpc_channel*, grpc_call*, gpr_uint32, grpc_completion_queue*, const char*, const char*, gpr_timespec, void*)'
           channel->GetHost(), MillisecondsToTimespec(deadline));
                                                               ^
../ext/call.cc: In static member function 'static void grpc::node::Call::StartBatch(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:590:52: error: too few arguments to function 'grpc_call_error grpc_call_start_batch(grpc_call*, const grpc_op*, size_t, void*, void*)'
           callback, op_vector.release(), resources));
                                                    ^
In file included from ../ext/call.cc:41:0:
/usr/local/include/grpc/grpc.h:520:17: note: declared here
 grpc_call_error grpc_call_start_batch(grpc_call *call, const grpc_op *ops,
                 ^
../ext/call.cc:592:52: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
     return NanThrowError("startBatch failed", error);
                                                    ^
../ext/call.cc: In static member function 'static void grpc::node::Call::Cancel(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:604:62: error: too few arguments to function 'grpc_call_error grpc_call_cancel(grpc_call*, void*)'
   grpc_call_error error = grpc_call_cancel(call->wrapped_call);
                                                              ^
In file included from ../ext/call.cc:41:0:
/usr/local/include/grpc/grpc.h:575:17: note: declared here
 grpc_call_error grpc_call_cancel(grpc_call *call, void *reserved);
                 ^
../ext/call.cc:606:48: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
     return NanThrowError("cancel failed", error);
                                                ^
grpc.target.mk:114: recipe for target 'Release/obj.target/grpc/ext/call.o' failed
make: *** [Release/obj.target/grpc/ext/call.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/grpc
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--global" "grpc"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
The command '/bin/sh -c npm install --global grpc' returned a non-zero code: 1
```

I am investigating this issue and will report back any useful details I find along the way. Any help about why this is failing would be appreciated. A colleague was able to build the image on Ubuntu just fine so its mostly likely related to the VM shipped with docker toolkit.

**Comment by pires** [comment]
I'm facing a similar issue.

```
Step 9 : RUN npm install
 ---> Running in 409433aac947
npm WARN prefer global coffee-script@1.9.3 should be installed with -g


> dtrace-provider@0.5.0 install /usr/src/app/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> spawn-sync@1.0.13 postinstall /usr/src/app/node_modules/grpc/node_modules/protobufjs/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync
> node postinstall


> grpc@0.10.1 install /usr/src/app/node_modules/grpc
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
../ext/call.cc: In static member function 'static void grpc::node::Call::New(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:513:63: error: cannot convert 'grpc_completion_queue*' to 'grpc_call*' for argument '2' to 'grpc_call* grpc_channel_create_call(grpc_channel*, grpc_call*, gpr_uint32, grpc_completion_queue*, const char*, const char*, gpr_timespec, void*)'
           channel->GetHost(), MillisecondsToTimespec(deadline));
                                                               ^
../ext/call.cc: In static member function 'static void grpc::node::Call::StartBatch(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:590:52: error: too few arguments to function 'grpc_call_error grpc_call_start_batch(grpc_call*, const grpc_op*, size_t, void*, void*)'
           callback, op_vector.release(), resources));
                                                    ^
In file included from ../ext/call.cc:41:0:
/usr/local/include/grpc/grpc.h:520:17: note: declared here
 grpc_call_error grpc_call_start_batch(grpc_call *call, const grpc_op *ops,
                 ^
../ext/call.cc:592:52: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
     return NanThrowError("startBatch failed", error);
                                                    ^
../ext/call.cc: In static member function 'static void grpc::node::Call::Cancel(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:604:62: error: too few arguments to function 'grpc_call_error grpc_call_cancel(grpc_call*, void*)'
   grpc_call_error error = grpc_call_cancel(call->wrapped_call);
                                                              ^
In file included from ../ext/call.cc:41:0:
/usr/local/include/grpc/grpc.h:575:17: note: declared here
 grpc_call_error grpc_call_cancel(grpc_call *call, void *reserved);
                 ^
../ext/call.cc:606:48: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
     return NanThrowError("cancel failed", error);
                                                ^
grpc.target.mk:114: recipe for target 'Release/obj.target/grpc/ext/call.o' failed
make: *** [Release/obj.target/grpc/ext/call.o] Error 1
make: Leaving directory '/usr/src/app/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/grpc
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN prefer global nodemon@1.4.1 should be installed with -g
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**Comment by pires** [comment]
The same `Dockerfile` builds successfully on Ubuntu 14.04.

**Comment by jasonkuhrt** [comment]
Reducing the problem space further, here is the result of using https://hub.docker.com/r/grpc/node/~/dockerfile/

```
❯ docker build .
Sending build context to Docker daemon 49.44 MB
Step 0 : FROM node:latest
latest: Pulling from library/node

902b87aaaec9: Already exists
9a61b6b1315e: Already exists
1ff9f26f09fb: Already exists
607e965985c1: Already exists
9213e81cb0f2: Already exists
6ad0799af6bd: Already exists
e0919a8b95a8: Already exists
3383909e8f95: Already exists
8b74d7a75802: Already exists
9e20baae42c8: Already exists
Digest: sha256:bc558bd89891896f827c03d6df7550892fbaf1084f47c993c4d28e03904ef100
Status: Downloaded newer image for node:latest
 ---> 9e20baae42c8
Step 1 : RUN apt-get update && apt-get install -y   gcc   git   libc6-dbg   libc6-dev   libgtest-dev   libgflags-dev   libtool   make && apt-get clean
 ---> Using cache
 ---> 326d48d0fe6c
Step 2 : RUN git clone https://github.com/grpc/grpc.git /var/local/git/grpc
 ---> Using cache
 ---> 6bd32a1eb992
Step 3 : RUN cd /var/local/git/grpc &&   git pull --recurse-submodules &&   git submodule update --init --recursive
 ---> Using cache
 ---> 9d5262b92513
Step 4 : RUN cd /var/local/git/grpc && make install_c
 ---> Using cache
 ---> f0388e6c01fc
Step 5 : RUN npm install -g grpc
 ---> Running in 86dc91ca3066

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/grpc/node_modules/protobufjs/node_modules/yargs/node_modules/os-locale/node_modules/exec-file-sync/node_modules/spawn-sync
> node postinstall


> grpc@0.10.1 install /usr/local/lib/node_modules/grpc
> node-gyp rebuild

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/grpc/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
../ext/call.cc: In static member function 'static void grpc::node::Call::New(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:513:63: error: cannot convert 'grpc_completion_queue*' to 'grpc_call*' for argument '2' to 'grpc_call* grpc_channel_create_call(grpc_channel*, grpc_call*, gpr_uint32, grpc_completion_queue*, const char*, const char*, gpr_timespec, void*)'
           channel->GetHost(), MillisecondsToTimespec(deadline));
                                                               ^
../ext/call.cc: In static member function 'static void grpc::node::Call::StartBatch(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:590:52: error: too few arguments to function 'grpc_call_error grpc_call_start_batch(grpc_call*, const grpc_op*, size_t, void*, void*)'
           callback, op_vector.release(), resources));
                                                    ^
In file included from ../ext/call.cc:41:0:
/usr/local/include/grpc/grpc.h:520:17: note: declared here
 grpc_call_error grpc_call_start_batch(grpc_call *call, const grpc_op *ops,
                 ^
../ext/call.cc:592:52: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
     return NanThrowError("startBatch failed", error);
                                                    ^
../ext/call.cc: In static member function 'static void grpc::node::Call::Cancel(const v8::FunctionCallbackInfo<v8::Value>&)':
../ext/call.cc:604:62: error: too few arguments to function 'grpc_call_error grpc_call_cancel(grpc_call*, void*)'
   grpc_call_error error = grpc_call_cancel(call->wrapped_call);
                                                              ^
In file included from ../ext/call.cc:41:0:
/usr/local/include/grpc/grpc.h:575:17: note: declared here
 grpc_call_error grpc_call_cancel(grpc_call *call, void *reserved);
                 ^
../ext/call.cc:606:48: warning: 'void NanThrowError(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:741) [-Wdeprecated-declarations]
     return NanThrowError("cancel failed", error);
                                                ^
grpc.target.mk:114: recipe for target 'Release/obj.target/grpc/ext/call.o' failed
make: *** [Release/obj.target/grpc/ext/call.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/grpc
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "grpc"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
The command '/bin/sh -c npm install -g grpc' returned a non-zero code: 1
```

**Comment by pires** [comment]
I guess the issue here is using gRPC built from source with version 0.10.1 of the npm module. Building it from source as well and removing `grpc` from `package.json` dependencies seems to fix this.

```
FROM ubuntu:14.04

# Install needed tools to build gRPC
RUN apt-get update && apt-get install -y \
  curl \
  build-essential \
  gcc \
  git \
  libc6-dev \
  libgtest-dev \
  libgflags-dev \
  libtool \
  make && apt-get clean

# Install node 0.12.7
RUN curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
RUN apt-get install -y nodejs

# Build and install gRPC
RUN git clone https://github.com/grpc/grpc.git /var/local/git/grpc && \
  cd /var/local/git/grpc && \
  git pull --recurse-submodules && \
  git submodule update --init --recursive && \
  cd /var/local/git/grpc && make install_c && \
  cd src/node && npm install
```

**Comment by yang-g** [comment]
Ready to close?

**Comment by murgatroid99** [comment]
I think this issue is with an old version of the Node Dockerfile that we no longer distribute.
