### ISSUE TITLE
Cannot build setup.py: TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by Hnasar** [grpc/grpc#30372]
All versions newer than 1.45 fail to build in python.

### What did you try?
Try to build on piwheels CI environment: https://github.com/piwheels/packages/issues/308

### What did you see?

build failures ([link](https://www.piwheels.org/project/grpcio/))

```
2022-06-17T19:06:09,566 Collecting grpcio==1.47.0rc1
2022-06-17T19:06:09,571   Created temporary directory: /tmp/pip-unpack-1d9_gblt
2022-06-17T19:06:11,283   Downloading grpcio-1.47.0rc1.tar.gz (21.9 MB)
2022-06-17T19:06:39,255   Added grpcio==1.47.0rc1 from https://files.pythonhosted.org/packages/5e/69/bc30cb1e02a46110ce19589261eaabe5a09a58075e559b43b1c150cf3205/grpcio-1.47.0rc1.tar.gz#sha256=2548a7adca9db022f9a516d36d29d214a58a6dbde9bc29f54ee4198f7a3899bd to build tracker '/tmp/pip-build-tracker-jpzsr1ep'
2022-06-17T19:06:39,258   Running setup.py (path:/tmp/pip-wheel-ev5792q7/grpcio_b673f59ba3e0437bb1ff93e5d678be19/setup.py) egg_info for package grpcio
2022-06-17T19:06:39,260   Created temporary directory: /tmp/pip-pip-egg-info-3f8_6uur
2022-06-17T19:06:39,260   Preparing metadata (setup.py): started
2022-06-17T19:06:39,262   Running command python setup.py egg_info
2022-06-17T19:06:44,306   Traceback (most recent call last):
2022-06-17T19:06:44,308     File "<string>", line 36, in <module>
2022-06-17T19:06:44,308     File "<pip-setuptools-caller>", line 34, in <module>
2022-06-17T19:06:44,308     File "/tmp/pip-wheel-ev5792q7/grpcio_b673f59ba3e0437bb1ff93e5d678be19/setup.py", line 263, in <module>
2022-06-17T19:06:44,309       if check_linker_need_libatomic():
2022-06-17T19:06:44,309     File "/tmp/pip-wheel-ev5792q7/grpcio_b673f59ba3e0437bb1ff93e5d678be19/setup.py", line 223, in check_linker_need_libatomic
2022-06-17T19:06:44,309       stderr=PIPE)
2022-06-17T19:06:44,310     File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
2022-06-17T19:06:44,310       restore_signals, start_new_session)
2022-06-17T19:06:44,310     File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child
2022-06-17T19:06:44,311       executable = os.fsencode(executable)
2022-06-17T19:06:44,311     File "/usr/lib/python3.7/os.py", line 809, in fsencode
2022-06-17T19:06:44,311       filename = fspath(filename)  # Does type-checking of `filename`.
2022-06-17T19:06:44,312   TypeError: expected str, bytes or os.PathLike object, not list
```

There's been a two-line fix waiting for review for over a month: https://github.com/grpc/grpc/pull/30076

@gnossen @markdroth @ctiller 
Thank you for the help!

**Comment by alexeyshockov** [comment]
Same here, `google-cloud-bigquery` installation fails because of it.

```
Collecting grpcio<2.0dev,>=1.47.0
  Using cached grpcio-1.47.0.tar.gz (21.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/js/6nvh3y95755d8pt1zbm5m6ch0000gn/T/pip-install-3kqsay3z/grpcio_9a0d849c6dcd44a691ff3193483d6e15/setup.py", line 263, in <module>
          if check_linker_need_libatomic():
        File "/private/var/folders/js/6nvh3y95755d8pt1zbm5m6ch0000gn/T/pip-install-3kqsay3z/grpcio_9a0d849c6dcd44a691ff3193483d6e15/setup.py", line 219, in check_linker_need_libatomic
          cpp_test = subprocess.Popen(
        File "/Users/alexeyshockov/.pyenv/versions/3.9.9/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/alexeyshockov/.pyenv/versions/3.9.9/lib/python3.9/subprocess.py", line 1696, in _execute_child
          and os.path.dirname(executable)
        File "/Users/alexeyshockov/.pyenv/versions/3.9.9/lib/python3.9/posixpath.py", line 152, in dirname
          p = os.fspath(p)
      TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by tarzasai** [comment]
The same for `google-cloud-secret-manager`.

**Comment by demony0320** [comment]
In my environment, after pip upgrade, issue was gone (20.x->21.3.1)
`python3 -m pip install install --upgrade pip`

**Comment by 9268** [comment]
> In my environment, after pip upgrade, issue was gone (20.x->21.3.1) `python3 -m pip install install --upgrade pip`

I install pip==21.3.1 and retry, pip failed on install grpcio1.48 again and try lower version,finally succeed on grpcio1.46.3

**Comment by gdubicki** [comment]
Same here with Python 3.10 on a Mac with M1 (if it matters):

```
$ pip install grpcio
Collecting grpcio
  Downloading grpcio-1.48.1.tar.gz (22.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.0/22.0 MB 45.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2n/szr7pwsd4dv60w8l699sb8580000gp/T/pip-install-t9u6gnow/grpcio_8181aff2ef8e48fdaf6f3bc8dcfc1152/setup.py", line 263, in <module>
          if check_linker_need_libatomic():
        File "/private/var/folders/2n/szr7pwsd4dv60w8l699sb8580000gp/T/pip-install-t9u6gnow/grpcio_8181aff2ef8e48fdaf6f3bc8dcfc1152/setup.py", line 219, in check_linker_need_libatomic
          cpp_test = subprocess.Popen(
        File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1720, in _execute_child
          and os.path.dirname(executable)
        File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
          p = os.fspath(p)
      TypeError: expected str, bytes or os.PathLike object, not list
      [end of output]
```

**Comment by XuanWang-Amos** [comment]
Looks like this was fixed by this: https://github.com/grpc/grpc/pull/30522

Closing this issue, please open a new issue if this still exists.
