### ISSUE TITLE
Need to peg final 2.x version of grpcio for Python 2 app deployments

### ISSUE THREAD

**Issue by wescpy** [grpc/grpc#30432]
When deploying a basic Python 2 app to Cloud Run _without_ `grpcio` in `requirements.txt`, a version incompatible to 2.x (1.41) is requested, failing the build. In any Python 2 build, no version higher than 1.39.1 should be even considered. "Upstream" apps dependent on `grpcio` likely have no idea what version to lock in, so it should be done here at the source.

A workaround does exist (see below), and that's manually adding `grpcio` to `requirements.txt`, but that's an unfair burden to place on the higher-level app developer who may not even know about it nor that it's required nor what version.

**FAILED BUILD**

Example `requirements.txt`:
```
flask
google-cloud-translate
```
Example log output from running a build with: `gcloud run deploy translate --allow-unauthenticated --platform managed --region us-west2 --source .`
```
starting build "1f7f0c7d-861d-4f5f-972c-07be4673bef3"

FETCHSOURCE
Fetching storage object: gs://PROJECT_ID_cloudbuild/source/1659029475.956891-93c6e7a228d0411a95272c275bec73c1.tgz#1659029476368317
Copying gs://PROJECT_ID_cloudbuild/source/1659029475.956891-93c6e7a228d0411a95272c275bec73c1.tgz#1659029476368317...
/ [0 files][    0.0 B/  2.0 KiB]                                                
/ [1 files][  2.0 KiB/  2.0 KiB]                                                
Operation completed over 1 objects/2.0 KiB.                                      
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon  9.216kB

Step 1/6 : FROM python:2-slim
2-slim: Pulling from library/python
123275d6e508: Pulling fs layer
dd1cd6637523: Pulling fs layer
0c4e6d630f2c: Pulling fs layer
13e9cd8f0ea1: Pulling fs layer
13e9cd8f0ea1: Waiting
dd1cd6637523: Verifying Checksum
dd1cd6637523: Download complete
0c4e6d630f2c: Verifying Checksum
0c4e6d630f2c: Download complete
13e9cd8f0ea1: Verifying Checksum
13e9cd8f0ea1: Download complete
123275d6e508: Verifying Checksum
123275d6e508: Download complete
123275d6e508: Pull complete
dd1cd6637523: Pull complete
0c4e6d630f2c: Pull complete
13e9cd8f0ea1: Pull complete
Digest: sha256:6c1ffdff499e29ea663e6e67c9b6b9a3b401d554d2c9f061f9a45344e3992363
Status: Downloaded newer image for python:2-slim
 ---> eeb27ee6b893
Step 2/6 : WORKDIR /app
 ---> Running in a0eae283a1f4
Removing intermediate container a0eae283a1f4
 ---> 9d807dd02f41
Step 3/6 : COPY requirements.txt .
 ---> 4b6ef5715c30
Step 4/6 : RUN pip install -r requirements.txt
 ---> Running in 451536c75839
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting flask
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
Collecting google-cloud-translate
  Downloading google_cloud_translate-2.0.4-py2.py3-none-any.whl (92 kB)
Collecting click<8.0,>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Werkzeug<2.0,>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting Jinja2<3.0,>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting itsdangerous<2.0,>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting google-cloud-core<3.0dev,>=1.1.0
  Downloading google_cloud_core-1.7.3-py2.py3-none-any.whl (28 kB)
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-1.32.0-py2.py3-none-any.whl (93 kB)
Collecting protobuf<4.0.0dev
  Downloading protobuf-3.17.3-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Collecting six>=1.12.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting google-auth<2.0dev,>=1.24.0
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
Collecting pytz
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting requests<3.0.0dev,>=2.18.0
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python2.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-translate->-r requirements.txt (line 4)) (44.1.0)
Collecting futures>=3.2.0; python_version < "3.2"
  Downloading futures-3.3.0-py2-none-any.whl (16 kB)
Collecting packaging>=14.3
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Collecting grpcio<2.0dev,>=1.29.0; extra == "grpc"
  Downloading grpcio-1.41.1.tar.gz (21.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vqmpqc/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vqmpqc/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-vqmpqc/grpcio/pip-egg-info
         cwd: /tmp/pip-install-vqmpqc/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vqmpqc/grpcio/setup.py", line 256, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-vqmpqc/grpcio/setup.py", line 206, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/local/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/usr/local/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

**WORKAROUND**

Manually add `grpcio` to `requirements.txt`:
```
grpcio<1.40.0
flask
google-cloud-translate
```

This results in a successful build:
```
starting build "622cf8ed-a36c-4e8b-9cfe-40d5adc96198"

FETCHSOURCE
Fetching storage object: gs://PROJECT_ID_cloudbuild/source/1659030160.979049-f46916f953b24c7db6d3555cf9d57840.tgz#1659030161349151
Copying gs://PROJECT_ID_cloudbuild/source/1659030160.979049-f46916f953b24c7db6d3555cf9d57840.tgz#1659030161349151...
/ [0 files][    0.0 B/  2.0 KiB]                                                
/ [1 files][  2.0 KiB/  2.0 KiB]                                                
Operation completed over 1 objects/2.0 KiB.                                      
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon  9.216kB

Step 1/6 : FROM python:2-slim
2-slim: Pulling from library/python
123275d6e508: Pulling fs layer
dd1cd6637523: Pulling fs layer
0c4e6d630f2c: Pulling fs layer
13e9cd8f0ea1: Pulling fs layer
13e9cd8f0ea1: Waiting
dd1cd6637523: Verifying Checksum
dd1cd6637523: Download complete
0c4e6d630f2c: Verifying Checksum
0c4e6d630f2c: Download complete
13e9cd8f0ea1: Verifying Checksum
13e9cd8f0ea1: Download complete
123275d6e508: Verifying Checksum
123275d6e508: Download complete
123275d6e508: Pull complete
dd1cd6637523: Pull complete
0c4e6d630f2c: Pull complete
13e9cd8f0ea1: Pull complete
Digest: sha256:6c1ffdff499e29ea663e6e67c9b6b9a3b401d554d2c9f061f9a45344e3992363
Status: Downloaded newer image for python:2-slim
 ---> eeb27ee6b893
Step 2/6 : WORKDIR /app
 ---> Running in d9c1783250e7
Removing intermediate container d9c1783250e7
 ---> ebfc86bec10d
Step 3/6 : COPY requirements.txt .
 ---> a8056b9a9e63
Step 4/6 : RUN pip install -r requirements.txt
 ---> Running in 844f9831bedd
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting flask
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
Collecting grpcio<1.40.0
  Downloading grpcio-1.39.0-cp27-cp27mu-manylinux2010_x86_64.whl (4.1 MB)
Collecting google-cloud-translate
  Downloading google_cloud_translate-2.0.4-py2.py3-none-any.whl (92 kB)
Collecting click<8.0,>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Werkzeug<2.0,>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting Jinja2<3.0,>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting itsdangerous<2.0,>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting enum34>=1.0.4; python_version < "3.4"
  Downloading enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting futures>=2.2.0; python_version < "3.2"
  Downloading futures-3.3.0-py2-none-any.whl (16 kB)
Collecting google-cloud-core<3.0dev,>=1.1.0
  Downloading google_cloud_core-1.7.3-py2.py3-none-any.whl (28 kB)
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-1.32.0-py2.py3-none-any.whl (93 kB)
Collecting protobuf<4.0.0dev
  Downloading protobuf-3.17.3-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Collecting google-auth<2.0dev,>=1.24.0
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
Collecting pytz
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting requests<3.0.0dev,>=2.18.0
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python2.7/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-translate->-r requirements.txt (line 4)) (44.1.0)
Collecting packaging>=14.3
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-3.1.1-py2.py3-none-any.whl (11 kB)
Collecting rsa<4.6; python_version < "3.6"
  Downloading rsa-4.5-py2.py3-none-any.whl (36 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
Collecting idna<3,>=2.5; python_version < "3"
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2; python_version < "3"
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Installing collected packages: click, Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, six, enum34, futures, grpcio, pytz, certifi, urllib3, idna, chardet, requests, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, protobuf, pyparsing, packaging, googleapis-common-protos, google-api-core, google-cloud-core, google-cloud-translate
Successfully installed Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 cachetools-3.1.1 certifi-2021.10.8 chardet-4.0.0 click-7.1.2 enum34-1.1.10 flask-1.1.4 futures-3.3.0 google-api-core-1.32.0 google-auth-1.35.0 google-cloud-core-1.7.3 google-cloud-translate-2.0.4 googleapis-common-protos-1.52.0 grpcio-1.39.0 idna-2.10 itsdangerous-1.1.0 packaging-20.9 protobuf-3.17.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-2.4.7 pytz-2022.1 requests-2.27.1 rsa-4.5 six-1.16.0 urllib3-1.26.11
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Removing intermediate container 844f9831bedd
 ---> 39f89e059847
Step 5/6 : COPY . .
 ---> 43406757def5
Step 6/6 : ENTRYPOINT ["python", "main.py"]
 ---> Running in b53e515016bb
Removing intermediate container b53e515016bb
 ---> 61d0fabf7894
Successfully built 61d0fabf7894
Successfully tagged us-west2-docker.pkg.dev/PROJECT_ID/cloud-run-source-deploy/translate:latest
PUSH
Pushing us-west2-docker.pkg.dev/PROJECT_ID/cloud-run-source-deploy/translate
The push refers to repository [us-west2-docker.pkg.dev/PROJECT_ID/cloud-run-source-deploy/translate]
fe79dcba30c8: Preparing
e8b329b18814: Preparing
1b09485bf264: Preparing
e3576aa06e85: Preparing
7a287aad297b: Preparing
7ea2b60b0a08: Preparing
568944187d93: Preparing
b60e5c3bcef2: Preparing
7ea2b60b0a08: Waiting
568944187d93: Waiting
b60e5c3bcef2: Waiting
7a287aad297b: Layer already exists
7ea2b60b0a08: Layer already exists
568944187d93: Layer already exists
b60e5c3bcef2: Layer already exists
fe79dcba30c8: Pushed
e3576aa06e85: Pushed
1b09485bf264: Pushed
e8b329b18814: Pushed
latest: digest: sha256:e96a507d0e18ff074d9985c18ee03bc304da97237474ea40b15f3a17b2ba816d size: 1997
DONE
```

**Comment by asheshvidyut** [comment]
Hey @wescpy Apologies for delay here.

Currently we do not support Py2.

Hence I am closing this issue. But feel free to reopen in case this issue still persists.

cc @sreenithi @sergiitk
