### ISSUE TITLE
Can create a channel that use a CA that is not in the certificates store of windows

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc#30692]
I would like to create a gRPC client library that it could be used by windows applications (WPF) and MAUI projects (Android), all in .NET 6 and Grpc.Net.

Then I create my library, that has a class that wrap the grpc client. This is the code.

```
using Grpc.Core;
using Grpc.Net.Client;
using System.Net.Http;
using System.Numerics;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Channels;

namespace GestorOrdenadores.Service.Client.Grpc
{
    public class ServiceClientGrpc
    {
        #region constructores
        public ServiceClientGrpc(string paramDireccion, int paramPuerto, string paramCA, string paramCertificado, string paramKey)
        {
            X509Certificate2 cert = X509Certificate2.CreateFromPem(paramCertificado, paramKey);

            paramDireccion = @"https://192.168.1.200";
            paramPuerto = 5001;


            //Esto usa un certificado
            HttpClientHandler miHttpHandler = new HttpClientHandler();
            miHttpHandler.ClientCertificates.Add(cert);
            miHttpHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

            HttpClient httpClient = new(miHttpHandler);

            GrpcChannel channel = GrpcChannel.ForAddress(paramDireccion + ":" + paramPuerto, new GrpcChannelOptions
            {
                HttpClient = httpClient
            });


            _client = new Greeter.GreeterClient(channel);
        }
        #endregion constructores


        private readonly Greeter.GreeterClient _client;



        public async Task<string> SayHelloAsync(string paramNombre)
        {
            HelloRequest miRequest = new HelloRequest()
            {
                Name = paramNombre
            };

            return (await _client.SayHelloAsync(miRequest)).Message;
        }
    }
}
```

The WPF client:

```
private async void BtnSaludar_Click(object sender, RoutedEventArgs e)
{
    try
    {
        string miStrCertificado = System.IO.File.ReadAllText(@"Certificados\Client.crt");
        string miStrClave = System.IO.File.ReadAllText(@"Certificados\Client.key");
        string miStrCA = System.IO.File.ReadAllText(@"Certificados\ca.crt");

        ServiceClientGrpc miService = new ServiceClientGrpc("https://192.168.1.200", 5001, miStrCA, miStrCertificado, miStrClave);


        MessageBox.Show(await miService.SayHelloAsync("Álvaro"));
    }
    catch(Exception ex)
    {
        MessageBox.Show(ex.Message);
    }
}
```

Mi MAUI client:

```
private async void OnBtnSaludarClicked(object sender, EventArgs e)
{
    try
    {
        //Get address from XML file.
        string miStrDireccion = Configuracion.GestorConfiguracion.GetDireccionServicio();
        int miStrPuerto = Configuracion.GestorConfiguracion.GetPuertoServicio();

        //Get certificates from the asserts
        using Stream miStmCertificado = await FileSystem.OpenAppPackageFileAsync("certificados/client.crt");
        using StreamReader miSrCertificado = new StreamReader(miStmCertificado);
        string miStrCertificado = await miSrCertificado.ReadToEndAsync();

        using Stream miStmKey = await FileSystem.OpenAppPackageFileAsync("certificados/client.key");
        using StreamReader miSrKey = new StreamReader(miStmKey);
        string miStrKey = await miSrKey.ReadToEndAsync();

        using Stream miStmCa = await FileSystem.OpenAppPackageFileAsync("certificados/ca.crt");
        using StreamReader miSrCa = new StreamReader(miStmKey);
        string miStrCa = await miSrKey.ReadToEndAsync();

        ServiceClientGrpc miServicio = new ServiceClientGrpc("192.168.1.200", miStrPuerto, miStrCa, miStrCertificado, miStrKey);

        EtrRespuestaPing.Text = await miServicio.SayHelloAsync("Álvaro");
    }
    catch(Exception ex)
    {
        await DisplayAlert("Alert", ex.Message, "OK");
    }
}
```

With this solution I can connect with the WPF application, because in the library I am using DangerousAcceptAnyServerCertificateValidator, but I get an error in the MAUI project because Android doesn't allow a dangerous channel.

If I comment this line, I can connect with the WPF application, because I am using a self-signed certificate and the CA is not in the certificates store of windows. I would like to avoid t o have to install this CA in every windows client.

The problem here is that I don't know how to create a channel with ForAddress() in which I could indicate the CA, because the X509Certificate2 doesn't allow to indicate the CA.

Then I tried to use Grpc.Core instead of Grpc.Net in the library, so the code would be this:

```
public ServiceClientGrpc(string paramDireccion, int paramPuerto, string paramCA, string paramCertificado, string paramKey)
{
    var keypair = new KeyCertificatePair(paramCertificado, paramKey);
    var sslCreds = new SslCredentials(paramCA, keypair);

    Channel channel = new Channel(paramDireccion, paramPuerto, sslCreds);
    _client = new Greeter.GreeterClient(channel);


    _client = new Greeter.GreeterClient(channel);
}
```
In this case, I can connect from the windows client without using DangerousAcceptAnyServerCertificateValidator, because with Grpc.Core I can set the CA in the credentials.

The problem with this solution is that the MAUI progect give me this error:

```
{System.DllNotFoundException: grpc_csharp_ext
   at Grpc.Core.Internal.NativeLogRedirector.Redirect(NativeMethods native) in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeLogRedirector.cs:line 49
   at Grpc.Core.Internal.NativeExtension..ctor() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:line 46
   at Grpc.Core.Internal.NativeExtension.Get() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:line 67
   at Grpc.Core.Internal.NativeMethods.Get() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeMethods.cs:line 49
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit() in /var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:line 373
   at Grpc.Core.GrpcEnvironment..ctor() in /var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:line 302
   at Grpc.Core.GrpcEnvironment.AddRef() in /var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:line 78
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options) in /var/local/git/grpc/src/csharp/Grpc.Core/Channel.cs:line 70
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options) in /var/local/git/grpc/src/csharp/Grpc.Core/Channel.cs:line 107
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials) in /var/local/git/grpc/src/csharp/Grpc.Core/Channel.cs:line 95
   at GestorOrdenadores.Service.Client.Grpc.ServiceClientGrpc..ctor(String paramDireccion, Int32 paramPuerto, String paramCA, String paramCertificado, String paramKey) in D:\desarrollo\proyectos\GestorOrdenadores\GestorOrdenadores.Service.Client.Grpc\ServiceClientGrpc.cs:line 74
   at GestorOrdenadores.Client.Maui.MainPage.OnBtnPingClicked(Object sender, EventArgs e) in D:\desarrollo\proyectos\GestorOrdenadores\GestorOrdenadores.Client.Maui\MainPage.xaml.cs:line 51}
```

I would like to know if with Grpc.Net it is possible to set the CA in some way to create a channel that use a self-signed certificate that needs a CA that is not stored in the certificates store of windows, so in this way, I could use the same library for different kind of clients.

Perhaps implementing the ServerCertificateCustomValidationCallback with a custom implementation? If this could be the way to go, how could I do it?

Thanks.

EDIT: I have implemented the ServerCertificateCustomValidationCallback, returning always true for testing purposes, and then I can connect from the WPF client, but I can't get from the MAUI client because I get the following error:

```
{Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed, see inner exception. SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1[[System.Net.Http.Http2Connection, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__73[[GestorOrdenadores.Service.Client.Grpc.HelloRequest, GestorOrdenadores.Service.Client.Grpc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[GestorOrdenadores.Service.Client.Grpc.HelloReply, GestorOrdenadores.Service.Client.Grpc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 493")
   at GestorOrdenadores.Service.Client.Grpc.ServiceClientGrpc.SayHelloAsync(String paramNombre) in D:\desarrollo\proyectos\GestorOrdenadores\GestorOrdenadores.Service.Client.Grpc\ServiceClientGrpc.cs:line 148
   at GestorOrdenadores.Client.Maui.MainPage.OnBtnPingClicked(Object sender, EventArgs e) in D:\desarrollo\proyectos\GestorOrdenadores\GestorOrdenadores.Client.Maui\MainPage.xaml.cs:line 53}
```

So I would like to know how I could implemented a grpc client that could be used for both, MAUI and WPF clients.

**Comment by tonydnewell** [comment]
For the parts of your issue relating to **Grpc.Net** please ask in the **grpc-dotnet** repository: https://github.com/grpc/grpc-dotnet/issues

As for **Grpc.Core** with Android MAUI project (Xamarin support):
 - The Grpc.Core implementation is now in maintenance mode and we're only going to focus on critical and security fixes.
 - Supporting Xamarin simply presents too much maintenance overhead and it's also difficult to test with the test infrastructure available to us
 - The Xamarin support has always been classified as "[experimental](https://github.com/grpc/grpc/tree/v1.46.x/src/csharp/experimental)"
See the recent [update on gRPC C#](https://grpc.io/blog/grpc-csharp-future/) for more details. 

Note that in practice, running Grpc.Core on Android might still be possible (there is nothing in principle that would prevent it from working), but it will be completely at your own risk and it's simply not one of the use cases the grpc team will help you with as Grpc.Core on Xamarin is now considered as "not supported" by us (but you might still be able to get help from the community).
