### ISSUE TITLE
"pip install grpcio" failure on MacOS 12 M1 and Python 3.10

### ISSUE THREAD

**Issue by reecenil** [grpc/grpc#30723]
### What version of gRPC and what language are you using?
grpcio 1.48.0

### What operating system (Linux, Windows,...) and version?
MacOS 12.2.1 M1 version

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10.5

### What did you do?
"pip install grpcio"

### What did you expect to see?
Successful installation

### What did you see instead?

```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/setup.py", line 541, in <module>
          setuptools.setup(
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/install.py", line 568, in run
          self.run_command('build')
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/src/python/grpcio/commands.py", line 284, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/unixccompiler.py", line 117, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/spawn.py", line 91, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/fj/xsnm6gvs68z2z9w33s8ylfyc0000gr/T/pip-install-c8ufot7p/grpcio_8a6031b5c387497ba09e6a11073a0024/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/cen.valencia/.pyenv/versions/3.10.5/lib/python3.10/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by gnossen** [comment]
Thanks for including the full build log! Makes things much easier. 😃 

I'm seeing lots of `unqualified-id` errors related to the C++ standard library:

```
      third_party/abseil-cpp/absl/time/time.h:460:14: error: expected unqualified-id
          if (std::isnan(n))
```

```
      third_party/abseil-cpp/absl/time/time.h:461:19: error: expected unqualified-id
            return std::signbit(n) ? -InfiniteDuration() : InfiniteDuration();
```

@veblush Seems these symbols were introduced in C++11, but this SDK seems pretty recent, so I don't think the issue is just the version of the C++ stdlib. Any thoughts on this?

**Comment by reecenil** [comment]
@gnossen , Just an update.
I fixed this by updating my python to 3.10.6

**Comment by gnossen** [comment]
> I fixed this by updating my python to 3.10.6

Hm. I'm not sure why changing your Python minor version would have fixed this issue. Did you also enable Rosetta so that you pulled down prebuilt x86 artifacts instead?

**Comment by reecenil** [comment]
@gnossen , No not at all.. just updated my python.
I noticed that with python 3.10.5, i can install grpcio 1.46.3 without problems.
So I tried updating with the latest

**Comment by enhuiz** [comment]
> Thanks for including the full build log! Makes things much easier. 😃
> 
> I'm seeing lots of `unqualified-id` errors related to the C++ standard library:
> 
> ```
>       third_party/abseil-cpp/absl/time/time.h:460:14: error: expected unqualified-id
>           if (std::isnan(n))
> ```
> 
> ```
>       third_party/abseil-cpp/absl/time/time.h:461:19: error: expected unqualified-id
>             return std::signbit(n) ? -InfiniteDuration() : InfiniteDuration();
> ```
> 
> @veblush Seems these symbols were introduced in C++11, but this SDK seems pretty recent, so I don't think the issue is just the version of the C++ stdlib. Any thoughts on this?

I got the same unqualified-id errors when `pip install grpcio`, but I'm already on 3.10.6. Any ideas on how to solve this?

**Comment by joelbixbyrevel** [comment]
I have a few people with the same unqualified-id errors. Python 3.8.13. Still trying to find a fix for them.

**Comment by Jihadik** [comment]
Seeing the same errors here

**Comment by reecenil** [comment]
@gnossen looks like not a python version issue as indicated by other users. Not sure why my upgrade fixed this. BTW, I am using pyenv and poetry as well

**Comment by Jihadik** [comment]
Is there a quick mitigation on this? Maybe some older version?

**Comment by amcconag** [comment]
Also having this issue, wondering if there is a quick fix.  Running `Python 3.9.7` and `MacOS 12.5.1, M1 Pro`

**Comment by joelbixbyrevel** [comment]
Alright, this is what worked for at least two machines. Hopefully its just modifying the versions for you.

```
pyenv uninstall 3.8.13
pyenv install 3.8.13
pyenv local 3.8.13
pip install virtualenv
virtualenv test
source test/bin/activate
pip install grpcio
```

For whatever reason, that works for us.

**Comment by amcconag** [comment]
@joelbixbyrevel thank you, this worked for me as well, not sure why either.

**Comment by Jihadik** [comment]
Deleting all pythons in pyenv and installing them back worked for me as well. Tried with 3.9.13

**Comment by larsyencken** [comment]
I have the same issue, but deleting and recreating the pyenv environment did not seem to work. I tried several Python versions.

**Comment by veblush** [comment]
I don't understand why this error is coming up but my wild guess is that wrong `cmath` header file was used? `std::isnan` is defined in `cmath` so it should be able to compile it as long as `time.h` includes it. I verified that time.h has `#include <cmath>`. I suspect that installed xcode happened to present a wrong cmath header?

maybe-relevant references
- https://developer.apple.com/forums/thread/110594
- https://github.com/nlohmann/json/issues/2056 might be relevant?

**Comment by Jihadik** [comment]
@larsyencken, try to uninstall ALL pythons with version 3.X via pyenv and then install the desired version

**Comment by larsyencken** [comment]
I did get it working with 3.10. Unfortunately I don't know what the change was, but once it worked for one Python version it immediately worked to `pip install grpcio` for several of them.

**Comment by cjwebb** [comment]
Another person here that upgraded Python versions to make it work 👋 
My setup seems to consistently fail on Python 3.10.4 for some reason. Just commenting in case this turns out to be useful to someone.

```
grpcio_testing # pyenv versions
  system
  3.9.12
* 3.10.4 (set by /Users/colin/.pyenv/version)
  3.10.6
grpcio_testing # pyenv local 3.10.6
grpcio_testing # pyenv versions
  system
  3.9.12
  3.10.4
* 3.10.6 (set by /Users/colin/kickstand/grpcio_testing/.python-version)
grpcio_testing # python -m venv venv
grpcio_testing # source venv/bin/activate
(venv) grpcio_testing # python --version
Python 3.10.6
(venv) grpcio_testing # pip install grpcio
Collecting grpcio
  Using cached grpcio-1.48.1.tar.gz (22.0 MB)
  Preparing metadata (setup.py) ... done
Collecting six>=1.5.2
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for grpcio, since package 'wheel' is not installed.
Installing collected packages: six, grpcio
  Running setup.py install for grpcio ... done
Successfully installed grpcio-1.48.1 six-1.16.0

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
(venv) grpcio_testing # deactivate


grpcio_testing # pyenv local 3.10.4
grpcio_testing # python -m venv venv2
grpcio_testing # source venv2/bin/activate
(venv2) grpcio_testing # python --version
Python 3.10.4
(venv2) grpcio_testing # pip install grpcio
Collecting grpcio
  Using cached grpcio-1.48.1.tar.gz (22.0 MB)
  Preparing metadata (setup.py) ... done
Collecting six>=1.5.2
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for grpcio, since package 'wheel' is not installed.
Installing collected packages: six, grpcio
  Running setup.py install for grpcio ... error

... truncated (but full of the same `legacy-install-failure` from the OP)
```

**Comment by ldbrandi** [comment]
The latest version that I could install properly was `1.46.3` on Python 3.10.6 and Mac M1. The problem is the package that I need to install depends on the `1.48.1`, it's dbt-bigquery adapter. Any news on this?

**Comment by WayneYe** [comment]
@ldbrandi  +1 

### What version of gRPC and what language are you using?
grpcio 1.49.1

### What operating system (Linux, Windows,...) and version?
MacOS 12.6 Monteray M1 version

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.10.6

### What did you do?
"pip install -U grpcio"

### What did you expect to see?
Successful installation

### What did you see instead?
Complete logs attached below

```
❯ clang --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

pip install -U grpcio
Requirement already satisfied: grpcio in /Users/wayne/.pyenv/versions/3.10.6/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.46.3)
Collecting grpcio
  Using cached grpcio-1.49.1.tar.gz (22.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six>=1.5.2 in /Users/wayne/.pyenv/versions/3.10.6/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from grpcio) (1.16.0)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... \
  ...

      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
```
```

Installing older version of grpc 1.46.3 succeeded:
```
❯ python --version
Python 3.10.6
❯ pip list
Package    Version
---------- -------
greenlet   1.1.2
grpcio     1.46.3
msgpack    1.0.4
pip        22.2.2
pynvim     0.4.3
setuptools 65.3.0
six        1.16.0
wheel      0.37.1

❯ pip install grpcio==1.46.3
Collecting grpcio==1.46.3
  Downloading grpcio-1.46.3-cp310-cp310-macosx_10_10_universal2.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 20.2 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5.2 in /Users/wayne/.pyenv/versions/3.10.6/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from grpcio==1.46.3) (1.16.0)
Installing collected packages: grpcio
Successfully installed grpcio-1.46.3
```

**Comment by saranshkataria** [comment]
upgrading python version worked for me. Tested 3.10.6 and 3.9.14 and both worked fine.

**Comment by pragbatra-mendel** [comment]
Same issue with grpcio 1.50 on M1 mac.

**Comment by TengCheng** [comment]
grpcio 1.50
M1 mac
python3.9
`CFLAGS="-I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/opt/homebrew/opt/openssl/include" LDFLAGS="-L/opt/homebrew/opt/openssl/lib" pip3 install grpcio`
It works

**Comment by caseyduquettesc** [comment]
You can try installing Xcode. I've seen using that over the default command line tools fix issues like this for some people.

**Comment by talhakabakus** [comment]
> upgrading python version worked for me. Tested 3.10.6 and 3.9.14 and both worked fine.

I'm on Python 3.10.6 but did not work for me.

p.s. I'm using macOS Ventura 13.0 & M2 chip.

**Comment by lovesuper** [comment]
> > upgrading python version worked for me. Tested 3.10.6 and 3.9.14 and both worked fine.
> 
> I'm on Python 3.10.6 but did not work for me.
> 
> p.s. I'm using macOS Ventura 13.0 & M2 chip.

The same story

**Comment by gnossen** [comment]
I believe the issues being reported in this thread are caused by toolchain issues. The ultimate fix is going to be publishing native M1 artifacts so that you don't have to have a developer toolchain installed. In the meantime, if you are still having issues building from source, I would recommend using Rosetta in x86 compatibility mode.

I suspect that the users reporting that changing Python versions helped switched from a version for which they did not have Python headers installed to one where they did, enabling compilation. Most of the comments I see above don't give me the full compiler logs, which reveal the actual cause of the failure. I'm going to close this particular issue out since there isn't anything actionable left to deal with. If there are further build issues, please open a new issue and include _full_ logs from the failure so that we can help debug.

**Comment by kapilt** [comment]
closing a widely reported and experienced issue that has no resolution, while providing no help or information for users, "besides your doing it wrong",  is kinda of problematic, there are dozens of other issues in this repo wrt m1 python issues, some of which have helpful information re workarounds for the lack of actual support in released artifacts. ie. at the very least, link to the issue for m1 binary artifacts or a user workaround. given how many years it took to produce linux aarch64 artifacts, no one is holding their breath on binary artifacts.

**Comment by gnossen** [comment]
> while providing no help or information for users, "besides your doing it wrong"

The problem here was simply that we could not reproduce the issue. Many people in this thread said that they resolved their issue simply by changing Python version, which is what led us to believe that the issue was with the Python headers. The message is not "you're doing it wrong." The message is "install Python headers for your intended version."

> given how many years it took to produce linux aarch64 artifacts, no one is holding their breath on binary artifacts.

universal2 artifacts (compatible with both arm64 and x86) are being produced on the master branch and will be included in the next release.

**Comment by koorukuroo** [comment]
> The latest version that I could install properly was `1.46.3` on Python 3.10.6 and Mac M1. The problem is the package that I need to install depends on the `1.48.1`, it's dbt-bigquery adapter. Any news on this?

The following command well works in Python 3.9.15 and Mac M1
```pip install --ignore-installed --no-binary grpcio grpcio```

**Comment by gibsondan** [comment]
@gnossen that's really great to hear that universal2 artifacts are coming. Do you think there's any chance that those will be backported for older grpcio releases as well? 

We are stuck back on 1.47.2 currently due to a separate issue (https://github.com/grpc/grpc/issues/30843) but being able to provide wheels to our Mac users for that version would help tons of users who have trouble building from source.

**Comment by kevinashaw** [comment]
I'm not sure why it is so difficult to install grpcio on an M1 Mac.  Every time I open a new repo I have go through this again, and again and again.  Sometimes, after a couple hours of trying, I get it work, but sometimes it doesnt.  Like now.
My primary interest is to install tensorflow-serving-api (2.11.0), which requires tensorflow, which tried to install grpcio and failed.  I've tried several versions of each.

So, I'm unable to install `grpcio` on a MacBook Pro M1/Max with MacOS 12.2.
I'm using Python V3.10.9
And I added these exports:
* export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
* export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

The error message is long enough that it filled the terminal buffer, so I attached it as a text file: 
[grpcio-dump.txt](https://github.com/grpc/grpc/files/10504588/grpcio-dumpt.txt)

The last error trace is:
```
      Traceback (most recent call last):
        File "/private/var/folders/9m/ms8r01p55fd8cldfdwjbz6c40000gn/T/pip-install-tnssv36d/grpcio_79c2ad0e67da41d7ad661e1114c85053/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/kevin/tfserving_ai2/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/Users/kevin/tfserving_ai2/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/kevin/tfserving_ai2/venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/kevin/tfserving_ai2/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/9m/ms8r01p55fd8cldfdwjbz6c40000gn/T/pip-install-tnssv36d/grpcio_79c2ad0e67da41d7ad661e1114c85053/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
          raise self._value
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/9m/ms8r01p55fd8cldfdwjbz6c40000gn/T/pip-install-tnssv36d/grpcio_79c2ad0e67da41d7ad661e1114c85053/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/9m/ms8r01p55fd8cldfdwjbz6c40000gn/T/pip-install-tnssv36d/grpcio_79c2ad0e67da41d7ad661e1114c85053/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/kevin/tfserving_ai2/venv/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      
```

**Comment by kevinashaw** [comment]
So, what i've discovered is that:
* `pip install grpcio` 

Fails as documented above.  But:
* `conda install -c apple grpcio`
* `conda install -c apple tensorflow-deps`
* `conda install -c apple tensorflow-macos`
* `pip install tensorflow-serving-api`

Will complete with only minor errors.

**Comment by maikgreubel** [comment]
Here is what I could learn during my try-and-error steps to find a working concept:

- Use the zlib-devel package provided by distribution
- Use a more recent C-Compiler (I began with 4.2 (which was the installed version), updated to 4.8, updated to 5.5, updated to 8.3), which I installed to /usr/local (without any prefix)
- Use a more recent BinUtils package (installed 2.20, updated to 2.29), which I installed in custom directory /opt/binutils2291
- Use at least OpenSSL 1.0.2 (configure -fPIC -shared), which I installed in custom directory /opt/openssl102

Then I played with the environment variables and found, these are finally build and install the package without an error:

```PKG_CONFIG_PATH=/opt/openssl102/lib/pkgconfig:$PKG_CONFIG_PATH GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1 CFLAGS="-I/opt/binutils2291/include -I/opt/openssl102/include -L/opt/openssl102/lib" LDFLAGS="-L/opt/openssl102/lib" pip install grpcio```
