### ISSUE TITLE
linux v1.39.0 error return without exception set

### ISSUE THREAD

**Issue by 984958198** [grpc/grpc#30908]
Linux rbtnode1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
grpcio-1.39.0
python2.7

Here is my part of the code that throws an exception in the third step
This code is normal under window
I couldn't upgrade Python for a variety of reasons
```
with grpc.insecure_channel(ip_port) as channel:
        a = channel.unary_unary(path)
        operations = (
            cygrpc.SendInitialMetadataOperation(None, 0),
            cygrpc.SendMessageOperation(serialized_request, 0),
            cygrpc.SendCloseFromClientOperation(0),
            cygrpc.ReceiveInitialMetadataOperation(0),
            cygrpc.ReceiveMessageOperation(0),
            cygrpc.ReceiveStatusOnClientOperation(0),
        )
        print '1111111111'
        state = _RPCState(_UNARY_UNARY_INITIAL_DUE, None, None, None, None)
        print '2222222222'
        call = channel._channel.segregated_call(cygrpc.PropagationConstants.GRPC_PROPAGATE_DEFAULTS,
                                                a._method, None, time.time() + 5, None, None,
                                                ((operations, None,),), a._context)
        print '3333333333333'
        event = call.next_event()
        _handle_event(event, state, a._response_deserializer)
        print state.response
```

```
Traceback (most recent call last):
  File "/tmp/test/test.py", line 28, in <module>
    test()
  File "/tmp/test/test.py", line 27, in test
    print state.response
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 1560, in __exit__
    self._close()
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 1548, in _close
    self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 515, in grpc._cython.cygrpc.Channel.close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 399, in grpc._cython.cygrpc._close
  File "/usr/local/lib/python2.7/threading.py", line 285, in __enter__
    def __enter__(self):
SystemError: error return without exception set
Exception SystemError: SystemError('error return without exception set',) in <bound method _ChannelCallState.__del__ of <grpc._channel._ChannelCallState object at 0x7f60326f0510>> ignored

```

**Comment by gnossen** [comment]
A couple of thoughts:
- This seems to be Python 2. This is no longer supported.
- `_RPCState`, `channel._channel`, and `_handle_event` are all public APIs. Are you actually using these directly? If so, that is not supported. If not, can you please provide a reproduction that only uses public APIs?
