### ISSUE TITLE
Build failure with a gRPC + Go + Python project

### ISSUE THREAD

**Issue by ovidiupl** [grpc/grpc#30965]
### What version of gRPC and what language are you using?

- Bazel build with `rules_proto_grpc-4.2.0`
- Golang on the server
- Python on the client

### What operating system (Linux, Windows,...) and version?

- Ubuntu Linux 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

- Go 1.19.1
- Bazel 5.3.0

### What did you do?

I followed the instructions at https://rules-proto-grpc.com/en/latest/lang/python.html#python-grpc-library for Python, and similar guidelines for setting up a project with a Bazel build, protocol buffers, gRPC, Go and Python support.

In particular, note the dependency on the Go 1.19.1 toolchain. This bug still reproduces with any other version number, including the one in [bazel/grpc_extra_deps.bzl#L56](https://github.com/grpc/grpc/blob/92f58c18a8da2728f571138c37760a721c8915a2/bazel/grpc_extra_deps.bzl#L56)

Consider the following Bazel `WORKSPACE` file:

```python
workspace(name = "project-foo")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# https://github.com/bazelbuild/rules_proto

http_archive(
    name = "rules_proto",
    sha256 = "e017528fd1c91c5a33f15493e3a398181a9e821a804eb7ff5acdd1d2d6c2b18d",
    strip_prefix = "rules_proto-4.0.0-3.20.0",
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0-3.20.0.tar.gz",
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

# https://github.com/bazelbuild/rules_go

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "16e9fca53ed6bd4ff4ad76facc9b7b651a89db1689a2877d6fd7b82aa824e366",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.34.0/rules_go-v0.34.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.34.0/rules_go-v0.34.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_download_sdk", "go_register_toolchains", "go_rules_dependencies")

go_download_sdk(
    name = "go_sdk",
    version = "1.19.1",
)

go_rules_dependencies()

go_register_toolchains()

# https://github.com/rules-proto-grpc/rules_proto_grpc

http_archive(
    name = "rules_proto_grpc",
    sha256 = "bbe4db93499f5c9414926e46f9e35016999a4e9f6e3522482d3760dc61011070",
    strip_prefix = "rules_proto_grpc-4.2.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/4.2.0.tar.gz"],
)

# https://rules-proto-grpc.com/en/latest/#installation

load("@rules_proto_grpc//:repositories.bzl", "bazel_gazelle", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()

rules_proto_grpc_repos()

# https://rules-proto-grpc.com/en/latest/lang/go.html

bazel_gazelle()

load("@rules_proto_grpc//go:repositories.bzl", rules_proto_grpc_go_repos = "go_repos")

rules_proto_grpc_go_repos()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

# https://rules-proto-grpc.com/en/latest/lang/python.html#python-grpc-library

load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos = "python_repos")

rules_proto_grpc_python_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", rules_proto_grpc_python_deps = "grpc_deps")

rules_proto_grpc_python_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", rules_proto_grpc_python_extra_deps = "grpc_extra_deps")

rules_proto_grpc_python_extra_deps()
```

Add a `BUILD` file with the following contents:

```python
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc//go:defs.bzl", "go_grpc_library")
load("@rules_proto_grpc//python:defs.bzl", "python_grpc_library")

proto_library(
    name = "project_foo_proto",
    srcs = ["project_foo.proto"],
    visibility = ["//visibility:public"],
)

go_grpc_library(
    name = "project_foo_go_proto",
    importpath = "github.com/company/project-foo",
    protos = [":project_foo_proto"],
    visibility = ["//visibility:public"],
)

python_grpc_library(
    name = "project_foo_py_proto",
    protos = [":project_foo_proto"],
    visibility = ["//visibility:public"],
)
```

Create a minimal `project_foo.proto` with a request message, a response message and a service definition with one method using the two messages.

Run `bazel build :all` (or `bazelisk build :all`).

### What did you expect to see?

Successful build.

### What did you see instead?

```
ERROR: Traceback (most recent call last):
        File "/home/ovidiu.platon/src/admission-control/WORKSPACE", line 85, column 35, in <toplevel>
                rules_proto_grpc_python_extra_deps()
        File "/home/ovidiu.platon/.cache/bazel/_bazel_ovidiu.platon/499be9f2b6984f13f37570e2aac3fba9/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl", line 56, column 27, in grpc_extra_deps
                go_register_toolchains(version = "1.18")
        File "/home/ovidiu.platon/.cache/bazel/_bazel_ovidiu.platon/499be9f2b6984f13f37570e2aac3fba9/external/io_bazel_rules_go/go/private/sdk.bzl", line 419, column 13, in go_register_toolchains
                fail("go_register_toolchains: version set after go sdk rule declared ({})".format(", ".join([r["name"] for r in sdk_rules])))
Error in fail: go_register_toolchains: version set after go sdk rule declared (go_sdk)
```

### Anything else we should know about your project / environment?

The error happens regardless of whether the `WORKSPACE` file uses `go_sdk` or `go_register_toolchains`. The `grpc_extra_deps` function must not provide its Go toolchain version number. Not only it removes control from the `WORKSPACE` writer, but it conflicts with any other badly written helpers (it fails the "what if everyone else did this" test). It is order dependent and introduces fragility.

**Comment by ovidiupl** [comment]
I also filed https://github.com/bazelbuild/rules_go/issues/3292 with `bazelbuild/rules_go`. I think both projects have their part in this situation - the Go Bazel rules should figure out a different strategy for toolchain version unification (or for multiple toolchain versions, whatever is more appropriate), and other Bazel rules that depend on Go internally should not choose on the `WORKSPACE` user's behalf.
