### ISSUE TITLE
Memory leak in NativeClientChannelDNSResolver::StartRequest

### ISSUE THREAD

**Issue by gjasny** [grpc/grpc#31014]
### What version of gRPC and what language are you using?
C++
* happens with 1.48 and 1.49.0
* does not happen with 1.47

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04 

### What runtime / compiler are you using (e.g. python version or version of gcc)
Clang 14 / C++20

### What did you do?
I'm using gRPC to communicate with a server. Om shutdown the ASAN leak checker reports a leak.

### What did you expect to see?
No shutdown leaks

### What did you see instead?
```
==3657839==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x555ce1b15cbd in operator new(unsigned long) (/home/gregorj/Git/rtc-platform/_build_asan_d/bin/rtcrmclientcpp-integrationtest_asan_d+0x3e3cbd) (BuildId: 3054e985208ba15bfee18f4bf88d66f880565a68)
    #1 0x555ce28b2944 in std::unique_ptr<grpc_core::(anonymous namespace)::NativeClientChannelDNSResolver::Request, grpc_core::OrphanableDelete> grpc_core::MakeOrphanable<grpc_core::(anonymous namespace)::NativeClientChannelDNSResolver::Request>() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/gprpp/orphanable.h:68:27
    #2 0x555ce28b185d in grpc_core::(anonymous namespace)::NativeClientChannelDNSResolver::StartRequest() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc:130:10
    #3 0x555ce28d8581 in grpc_core::PollingResolver::StartResolvingLocked() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/resolver/polling_resolver.cc:204:14
    #4 0x555ce28d7639 in grpc_core::PollingResolver::MaybeStartResolvingLocked() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/resolver/polling_resolver.cc:200:3
    #5 0x555ce28d6bc4 in grpc_core::PollingResolver::StartLocked() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/resolver/polling_resolver.cc:68:39
    #6 0x555ce255fa25 in grpc_core::ClientChannel::CreateResolverLocked() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/client_channel.cc:1502:14
    #7 0x555ce2563006 in grpc_core::ClientChannel::TryToConnectLocked() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/client_channel.cc:1775:5
    #8 0x555ce25773d9 in grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8::operator()() const /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/client_channel.cc:1790:52
    #9 0x555ce257737c in void std::__invoke_impl<void, grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8&>(std::__invoke_other, grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:14
    #10 0x555ce257731c in std::enable_if<is_invocable_r_v<void, grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8&>, void>::type std::__invoke_r<void, grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8&>(grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111:2
    #11 0x555ce25771cc in std::_Function_handler<void (), grpc_core::ClientChannel::CheckConnectivityState(bool)::$_8>::_M_invoke(std::_Any_data const&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290:9
    #12 0x555ce1b57032 in std::function<void ()>::operator()() const /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590:9
    #13 0x555ce2ecede9 in grpc_core::WorkSerializer::WorkSerializerImpl::DrainQueueOwned() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/gprpp/work_serializer.cc:221:5
    #14 0x555ce2ecd32c in grpc_core::WorkSerializer::WorkSerializerImpl::Run(std::function<void ()>, grpc_core::DebugLocation const&) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/gprpp/work_serializer.cc:109:5
    #15 0x555ce2ed017a in grpc_core::WorkSerializer::Run(std::function<void ()>, grpc_core::DebugLocation const&) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/gprpp/work_serializer.cc:237:10
    #16 0x555ce25731fb in grpc_core::ClientChannel::CallData::CheckResolutionLocked(grpc_call_element*, absl::lts_20220623::Status*)::$_9::operator()(void*, absl::lts_20220623::Status) const /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/client_channel.cc:2301:9
    #17 0x555ce2573047 in grpc_core::ClientChannel::CallData::CheckResolutionLocked(grpc_call_element*, absl::lts_20220623::Status*)::$_9::__invoke(void*, absl::lts_20220623::Status) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/ext/filters/client_channel/client_channel.cc:2301:9
    #18 0x555ce2292bd5 in closure_impl::closure_wrapper(void*, absl::lts_20220623::Status) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/iomgr/closure.h:134:3
    #19 0x555ce2f1b9fa in exec_ctx_run(grpc_closure*) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/iomgr/exec_ctx.cc:43:3
    #20 0x555ce2f1b440 in grpc_core::ExecCtx::Flush() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/iomgr/exec_ctx.cc:71:9
    #21 0x555ce228ed6d in grpc_core::ExecCtx::~ExecCtx() /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/iomgr/exec_ctx.h:117:5
    #22 0x555ce31d31db in grpc_call_start_batch /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/core/lib/surface/call.cc:1850:3
    #23 0x555ce22a8618 in grpc::CoreCodegen::grpc_call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, void*) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/cpp/common/core_codegen.cc:112:10
    #24 0x555ce1f89990 in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpClientSendClose, grpc::internal::CallOpRecvInitialMetadata, grpc::internal::CallOpRecvMessage<google::protobuf::MessageLite>, grpc::internal::CallOpClientRecvStatus>::ContinueFillOpsAfterInterception() /home/gregorj/Git/ExternalLibs/grpc/_deploy/Applications_ubuntu2204_x64_cxx20_clang14/include/grpcpp/impl/codegen/call_op_set.h:976:53
    #25 0x555ce1f8948a in grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpClientSendClose, grpc::internal::CallOpRecvInitialMetadata, grpc::internal::CallOpRecvMessage<google::protobuf::MessageLite>, grpc::internal::CallOpClientRecvStatus>::FillOps(grpc::internal::Call*) /home/gregorj/Git/ExternalLibs/grpc/_deploy/Applications_ubuntu2204_x64_cxx20_clang14/include/grpcpp/impl/codegen/call_op_set.h:906:7
    #26 0x555ce2276278 in grpc::Channel::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) /home/gregorj/Git/ExternalLibs/grpc/_build_asan_d/../src/cpp/client/channel_cc.cc:171:8
    #27 0x555ce1f656fd in grpc::internal::Call::PerformOps(grpc::internal::CallOpSetInterface*) /home/gregorj/Git/ExternalLibs/grpc/_deploy/Applications_ubuntu2204_x64_cxx20_clang14/include/grpcpp/impl/codegen/call.h:68:17
    #28 0x555ce1f8b88e in void grpc::internal::ClientAsyncResponseReaderHelper::SetupRequest<google::protobuf::MessageLite, google::protobuf::MessageLite>(grpc_call*, grpc::internal::CallOpSendInitialMetadata**, std::function<void (grpc::ClientContext*, grpc::internal::Call*, grpc::internal::CallOpSendInitialMetadata*, void*)>*, std::function<void (grpc::ClientContext*, grpc::internal::Call*, bool, grpc::internal::CallOpSendInitialMetadata*, grpc::internal::CallOpSetInterface**, void*, grpc::Status*, void*)>*, google::protobuf::MessageLite const&)::'lambda'(grpc::ClientContext*, grpc::internal::Call*, bool, grpc::internal::CallOpSendInitialMetadata*, grpc::internal::CallOpSetInterface**, void*, grpc::Status*, void*)::operator()(grpc::ClientContext*, grpc::internal::Call*, bool, grpc::internal::CallOpSendInitialMetadata*, grpc::internal::CallOpSetInterface**, void*, grpc::Status*, void*) const /home/gregorj/Git/ExternalLibs/grpc/_deploy/Applications_ubuntu2204_x64_cxx20_clang14/include/grpcpp/impl/codegen/async_unary_call.h:184:15
    #29 0x555ce1f8b647 in void std::__invoke_impl<void, void grpc::internal::ClientAsyncResponseReaderHelper::SetupRequest<google::protobuf::MessageLite, google::protobuf::MessageLite>(grpc_call*, grpc::internal::CallOpSendInitialMetadata**, std::function<void (grpc::ClientContext*, grpc::internal::Call*, grpc::internal::CallOpSendInitialMetadata*, void*)>*, std::function<void (grpc::ClientContext*, grpc::internal::Call*, bool, grpc::internal::CallOpSendInitialMetadata*, grpc::internal::CallOpSetInterface**, void*, grpc::Status*, void*)>*, google::protobuf::MessageLite const&)::'lambda'(grpc::ClientContext*, grpc::internal::Call*, bool, grpc::internal::CallOpSendInitialMetadata*, grpc::internal::CallOpSetInterface**, void*, grpc::Status*, void*)&, grpc::ClientContext*, grpc::internal::Call*, bool, grpc::internal::CallOpSendInitialMetadata*, grpc::internal::CallOpSetInterface**, void*, grpc::Status*, void*>(std::__invoke_other, google::protobuf::MessageLite&&, grpc::ClientContext*&&, grpc::internal::Call*&&, bool&&, grpc::internal::CallOpSendInitialMetadata*&&, grpc::internal::CallOpSetInterface**&&, void*&&, grpc::Status*&&, void*&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:14

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```

### Anything else we should know about your project / environment?

Please note that we explicitly disable c-ares when compiling gRPC and rely on the operating system resolver library.

I guess `NativeClientChannelDNSResolver::Request::Orphan()` needs an implementation to not leak the object:
https://github.com/grpc/grpc/blob/8f8edfd04b46ee67f90454b3f6a70aa58ff82c2d/src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc#L85

CC: @drfloob @markdroth 

Thanks,
Gregor

**Comment by gjasny** [comment]
If I revert 4d15e256cec8d15b939a5fe34a1b891d3f8f8edb from #29903 the leak is gone.

**Comment by markdroth** [comment]
Thanks for reporting this!  I think https://github.com/grpc/grpc/pull/31017 should fix it.
