### ISSUE TITLE
xds-protos: Regenerate with protoc >= 3.19.0

### ISSUE THREAD

**Issue by serge30** [grpc/grpc#31064]
Hello,

I'm trying to use `xds-protos` packet with `protobuf==4.21.6` and get Python error on import anything from this package. As I can see from error message, it suggests to regenerate Python code with `protoc >= 3.19.0`

Can we have a new version of `xds-protos` package please?

--
Thanks,
Serhii

### What version of gRPC and what language are you using?

```
xds-protos==0.0.11
grpcio==1.48.1
protobuf==4.21.6
six==1.16.0
```

### What operating system (Linux, Windows,...) and version?

MacOS Monterey 12.6

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
Python 3.8.14 (default, Sep  6 2022, 23:17:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
```

### What did you do?

```
(venv) serge@macbook xds_test % pip install xds-protos
Collecting xds-protos
  Using cached xds_protos-0.0.11-py3-none-any.whl (1.8 MB)
Collecting grpcio
  Using cached grpcio-1.48.1-cp38-cp38-macosx_12_0_arm64.whl
Collecting protobuf
  Using cached protobuf-4.21.6-cp37-abi3-macosx_10_9_universal2.whl (484 kB)
Collecting six>=1.5.2
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, protobuf, grpcio, xds-protos
Successfully installed grpcio-1.48.1 protobuf-4.21.6 six-1.16.0 xds-protos-0.0.11
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/serge/projects/xds_test/venv/bin/python3.8 -m pip install --upgrade pip' command.

(venv) serge@macbook xds_test % python3
Python 3.8.14 (default, Sep  6 2022, 23:17:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import envoy.config.cluster.v3.cluster_pb2
```

### What did you expect to see?

No errors

### What did you see instead?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/envoy/config/cluster/v3/cluster_pb2.py", line 14, in <module>
    from envoy.config.cluster.v3 import circuit_breaker_pb2 as envoy_dot_config_dot_cluster_dot_v3_dot_circuit__breaker__pb2
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/envoy/config/cluster/v3/circuit_breaker_pb2.py", line 14, in <module>
    from envoy.config.core.v3 import base_pb2 as envoy_dot_config_dot_core_dot_v3_dot_base__pb2
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/envoy/config/core/v3/base_pb2.py", line 15, in <module>
    from envoy.config.core.v3 import address_pb2 as envoy_dot_config_dot_core_dot_v3_dot_address__pb2
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/envoy/config/core/v3/address_pb2.py", line 14, in <module>
    from envoy.config.core.v3 import socket_option_pb2 as envoy_dot_config_dot_core_dot_v3_dot_socket__option__pb2
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/envoy/config/core/v3/socket_option_pb2.py", line 14, in <module>
    from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/udpa/annotations/status_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Users/serge/projects/xds_test/venv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by gnossen** [comment]
Thanks for reporting this. We should have a fix for it out soon.

**Comment by serge30** [comment]
@gnossen Thank you for the fix!

Will be new xds-protos 0.0.12 pushed to the PyPi repository? I see only 0.0.11 version there:

https://pypi.org/project/xds-protos/

**Comment by serge30** [comment]
@gnossen, any updates on this?

**Comment by villainy** [comment]
PyPI is still showing xds-protos 0.0.11 as latest. Will 0.0.12 be released at some point?

**Comment by gnossen** [comment]
There turned out to be additional problems with the build pipeline. Those issues have been fixed by https://github.com/grpc/grpc/pull/33797. It has been switched to be versioned in lockstep with `grpcio` and the rest of the `grpcio-*` packages. The next release will likely be `1.57.1` in the next week or two.
