### ISSUE TITLE
grpcio installation fails on M1 MAC

### ISSUE THREAD

**Issue by deepalakshmic** [grpc/grpc#31130]
**What version of gRPC and what language are you using?**
GRPC 1.49.1
Python version: 3.9.5

**What operating system (Linux, Windows,...) and version?**
MAC OS : 
Chip: Apple M1 pro
Darwin 192-168-1-103.tpgi.com.au 21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 arm64

**What runtime / compiler are you using (e.g. python version or version of gcc)**
python version: 3.9.5
gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.0.1

**What did you do?**
poetry install
**What did you expect to see?**
Successful install

**What did you see instead?**
Install failed with below trace.

Traceback (most recent call last):
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
            self.spawn(compiler_so + cc_args + [src, '-o', obj] +
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
            _classic_spawn(self, command)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
            spawn(cmd, dry_run=self.dry_run)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/spawn.py", line 87, in spawn
            raise DistutilsExecError(
        distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/commands.py", line 280, in build_extensions
            build_ext.build_ext.build_extensions(self)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
            self._build_extensions_serial()
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
            self.build_extension(ext)
          File "/Users/deepa/Documents/MaxKelsen/SAVI_API_LIB/py/savi-alembic/.venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
            _build_ext.build_extension(self, ext)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
            objects = self.compiler.compile(sources,
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
            multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 364, in map
            return self._map_async(func, iterable, mapstar, chunksize).get()
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 771, in get
            raise self._value
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 125, in worker
            result = (True, func(*args, **kwds))
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
            return list(map(*args))
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
            self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/commands.py", line 263, in new_compile
            return old_compile(obj, src, ext, cc_args, extra_postargs,
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
            raise CompileError(msg)
        distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/setup.py", line 540, in <module>
            setuptools.setup(
          File "/Users/deepa/Documents/MaxKelsen/SAVI_API_LIB/py/savi-alembic/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in setup
            return distutils.core.setup(**attrs)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/core.py", line 148, in setup
            dist.run_commands()
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/Users/deepa/Documents/MaxKelsen/SAVI_API_LIB/py/savi-alembic/.venv/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
            return orig.install.run(self)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/install.py", line 546, in run
            self.run_command('build')
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build.py", line 135, in run
            self.run_command(cmd_name)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/Users/deepa/Documents/MaxKelsen/SAVI_API_LIB/py/savi-alembic/.venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
            _build_ext.run(self)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 340, in run
            self.build_extensions()
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/commands.py", line 284, in build_extensions
            raise CommandError(
        commands.CommandError: Failed `build_ext` step:
        Traceback (most recent call last):
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
            self.spawn(compiler_so + cc_args + [src, '-o', obj] +
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
            _classic_spawn(self, command)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
            spawn(cmd, dry_run=self.dry_run)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/spawn.py", line 87, in spawn
            raise DistutilsExecError(
        distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/commands.py", line 280, in build_extensions
            build_ext.build_ext.build_extensions(self)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
            self._build_extensions_serial()
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
            self.build_extension(ext)
          File "/Users/deepa/Documents/MaxKelsen/SAVI_API_LIB/py/savi-alembic/.venv/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
            _build_ext.build_extension(self, ext)
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
            objects = self.compiler.compile(sources,
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
            multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 364, in map
            return self._map_async(func, iterable, mapstar, chunksize).get()
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 771, in get
            raise self._value
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 125, in worker
            result = (True, func(*args, **kwds))
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
            return list(map(*args))
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
            self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
          File "/private/var/folders/hw/t8j1ydqd4flbxl8ks3d6975w0000gn/T/pip-req-build-ujwttuke/src/python/grpcio/commands.py", line 263, in new_compile
            return old_compile(obj, src, ext, cc_args, extra_postargs,
          File "/Users/deepa/.pyenv/versions/3.9.5/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
            raise CompileError(msg)
        distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure

  × Encountered error while trying to install package.
  ╰─> grpcio

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.

  at ~/.poetry/lib/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│
      1185│         return decode(output)
      1186│
      1187│     def execute(self, bin, *args, **kwargs):

**Comment by tducret** [comment]
Hi @deepalakshmic !
I encountered the same problem. [This comment](https://github.com/grpc/grpc/issues/30723#issuecomment-1231809453) helped me fix the issue.
In your case, I would try :
```
deactivate # in case you have an activated virtual environment

pyenv uninstall 3.9.5
pyenv install 3.9.5
pyenv shell 3.9.5
poetry shell
pip install grpcio # or poetry install
```

**Comment by amirsalaar** [comment]
> Hi @deepalakshmic ! I encountered the same problem. [This comment](https://github.com/grpc/grpc/issues/30723#issuecomment-1231809453) helped me fix the issue. In your case, I would try :
> 
> ```
> deactivate # in case you have an activated virtual environment
> 
> pyenv uninstall 3.9.5
> pyenv install 3.9.5
> pyenv shell 3.9.5
> poetry shell
> pip install grpcio # or poetry install
> ```

this worked fine for me on 3.9.12

**Comment by saranshkataria** [comment]
upgrading python version worked for me. Tested 3.10.6 and 3.9.14 and both worked fine.

**Comment by deepalakshmic** [comment]
> Hi @deepalakshmic ! I encountered the same problem. [This comment](https://github.com/grpc/grpc/issues/30723#issuecomment-1231809453) helped me fix the issue. In your case, I would try :
> 
> ```
> deactivate # in case you have an activated virtual environment
> 
> pyenv uninstall 3.9.5
> pyenv install 3.9.5
> pyenv shell 3.9.5
> poetry shell
> pip install grpcio # or poetry install
> ```

Thanks for the recommendation. Uninstalling pyenv and re-installing worked for me.

**Comment by deepalakshmic** [comment]
Following the recommendation in the comment helped me. I uninstalled the pyenv and re-installed and it fixed the issue,

**Comment by saranshkataria** [comment]
> I have the same issue on MacOS with M1, but I don't have pyenv. Any idea what the fix is intended to do?

you just need to re-install python, do not need pyenv explicitly. Something with python headers changed from what I understood.

**Comment by Vichoko** [comment]
I managed to fix this issue by temporarly updating my python version from 3.8 to 3.9, then updated GRPCIO 1.51.1 to 1.60.1 with `poetry install`, rolled back to python 3.8 and the installation issues stopped popping up on my M1.
