### ISSUE TITLE
grpc_extra_deps disallows to define a version of go toolchain

### ISSUE THREAD

**Issue by lripoche** [grpc/grpc#31182]
### What version of gRPC and what language are you using?
gRPC version : `1.49.1`
Go version : `1.18`

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Go version : `1.18`
Bazel : `5.3.0`

### What did you do?

Consider following WORKSPACE file : 
```
workspace(name = "test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies", "go_download_sdk")

go_download_sdk(
    name = "go_sdk",
    version = "1.18",
)

go_rules_dependencies()

go_register_toolchains()

http_archive(
    name = "bazel_gazelle",
    sha256 = "5982e5463f171da99e3bdaeff8c0f48283a7a5f396ec5282910b9e8a49c0dd7e",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.25.0/bazel-gazelle-v0.25.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.25.0/bazel-gazelle-v0.25.0.tar.gz",
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("//:deps.bzl", "go_dependencies")

# gazelle:repository_macro deps.bzl%go_dependencies
go_dependencies()

gazelle_dependencies()

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "",
    strip_prefix = "grpc-1.49.1",
    urls = [
        "https://github.com/grpc/grpc/archive/v1.49.1.zip",
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
```

I want to define my own version of the go toolchains and use gazelle to generate bazel build files for my go code.

### What did you expect to see?

```
bazel build //:gazelle
DEBUG: 
INFO: Analyzed target //:gazelle (90 packages loaded, 10076 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 18.606s, Critical Path: 9.76s
INFO: 43 processes: 2 internal, 41 linux-sandbox.
INFO: Build completed successfully, 43 total actions
```

### What did you see instead?

```
bazel build //:gazelle
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
	File "/home/lucas/projects/grpc-deps-minimal-demo/WORKSPACE", line 58, column 16, in <toplevel>
		grpc_extra_deps()
	File "/home/lucas/.cache/bazel/_bazel_lucas/03e5ee3de23111152f8b4bc57e72dd15/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl", line 56, column 27, in grpc_extra_deps
		go_register_toolchains(version = "1.18")
	File "/home/lucas/.cache/bazel/_bazel_lucas/03e5ee3de23111152f8b4bc57e72dd15/external/io_bazel_rules_go/go/private/sdk.bzl", line 409, column 13, in go_register_toolchains
		fail("go_register_toolchains: version set after go sdk rule declared ({})".format(", ".join([r["name"] for r in sdk_rules])))
Error in fail: go_register_toolchains: version set after go sdk rule declared (go_sdk)
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 1.489s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

This issue is a slightly simplified version of #30965

**Comment by veblush** [comment]
Richard, would you take a look at this?

**Comment by teabuff** [comment]
I am also curious what is the best practices here when meet such a conflicts (use go_register_toolchains multiple times). https://github.com/bazelbuild/rules_go/issues/2761 mentioned a workaround that use go_download_sdk and unset version in go_register_toolchains. However, that still requires remove the version of go_register_toolchains in grpc/bazel/grpc_extra_deps.bzl.

For now, I simply create a patch file ignore_version_in_go_register_toolchains.patch:
```
diff --git a/bazel/grpc_extra_deps.bzl b/bazel/grpc_extra_deps.bzl
index 4d8afa3131..514189f9a5 100644
--- a/bazel/grpc_extra_deps.bzl
+++ b/bazel/grpc_extra_deps.bzl
@@ -53,7 +53,7 @@ def grpc_extra_deps(ignore_version_differences = False):
     api_dependencies()
 
     go_rules_dependencies()
-    go_register_toolchains(version = "1.18")
+    go_register_toolchains()
     gazelle_dependencies()
 
     # Pull-in the go 3rd party dependencies for protoc_gen_validate, which is
```

Then I patch it to com_github_grpc_grpc deps in WORKSPACE file:

```
http_archive(
  name = "com_github_grpc_grpc",
  patch_args = ["-p1"],
  patches = ["//tools:ignore_version_in_go_register_toolchains.patch"],
  sha256 = "76900ab068da86378395a8e125b5cc43dfae671e09ff6462ddfef18676e2165a",
  strip_prefix = "grpc-1.50.0",
  urls = ["https://github.com/grpc/grpc/archive/v1.50.0.tar.gz"],
)
```

This works as a workaround, but not sure if it is just a hacky way. Probably a better behavior is inside grpc_extra_deps if it detects the go_sdk version is set, just call the go_register_tools() instead of go_register_tools(version = "1.8").

**Comment by avagin** [comment]
We met the same issue in gVisor. Right now, we worked around it with this patch https://github.com/google/gvisor/blob/master/tools/grpc_extra_deps.patch.

Cc: @lidizheng

**Comment by devesh-bedrock** [comment]
I can confirm that the patch approach worked for us.
