### ISSUE TITLE
can grpc work while using c++ as a server and java as a client?

### ISSUE THREAD

**Issue by garygogo** [grpc/grpc#3151]
I used "grpc/examples/cpp/route_guide" as a server and "grpc-java/examples/src/main/java/io/grpc/examples/routeguide" as a client,  port is 50051;
I got error as follow:

com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED
at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
at io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:204)
at io.grpc.examples.routeguide.RouteGuideClient.getFeature(RouteGuideClient.java:81)
at io.grpc.examples.routeguide.RouteGuideClient.main(RouteGuideClient.java:233)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED
at io.grpc.Status.asRuntimeException(Status.java:428)
at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:402)
at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED
at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
at io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:204)
at io.grpc.examples.routeguide.RouteGuideClient.getFeature(RouteGuideClient.java:81)
at io.grpc.examples.routeguide.RouteGuideClient.main(RouteGuideClient.java:233)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED
at io.grpc.Status.asRuntimeException(Status.java:428)
at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:402)
at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

can grpc support do like this?

**Comment by yang-g** [comment]
It seems the java and c++ protos are using different package names, which
may cause the problem.
For a quick workaround, you can try to use the same string as package name
in
https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/route_guide.proto
and
https://github.com/grpc/grpc/blob/master/examples/protos/route_guide.proto
to see whether that works.

**Comment by yang-g** [comment]
https://github.com/grpc/grpc/issues/3161 and https://github.com/grpc/grpc-go/issues/321 are created to use the same package name everywhere. Back to your question, all languages should be able to interop with all others. Thanks for reporting the issue.

**Comment by garygogo** [comment]
yeah, it works,thank you very much.

**Comment by tobegit3hub** [comment]
Thanks @yang-g and @garygogo . We have the similar issue because the proto files from server have upgrade. This helps a lot 👍
