### ISSUE TITLE
See goaway errors in Ruby client when enabling max_connection_age_ms from server side

### ISSUE THREAD

**Issue by ylifigma** [grpc/grpc#31733]
### What version of gRPC and what language are you using?
grpc v1.46.2, also happens in v1.51.0 (latest version).

### What operating system (Linux, Windows,...) and version?
M1 osx 

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby 2.7.6

### What did you do?
We are seeing goaway errors in Ruby clients when enabling `max_connection_age_ms` to rebalance the connections in server side.

To help reproduce the bug, I updated the public **route_guide** example:
- Server: Set `grpc.max_connection_age_ms` to 1
- Client: Add 1000 iterations.
```
diff --git a/examples/ruby/route_guide/route_guide_client.rb b/examples/ruby/route_guide/route_guide_client.rb
index 7f9c012a3d..ed5214b4a5 100755
--- a/examples/ruby/route_guide/route_guide_client.rb
+++ b/examples/ruby/route_guide/route_guide_client.rb
@@ -147,18 +147,12 @@ end

 def main
   stub = RouteGuide::Stub.new('localhost:50051', :this_channel_is_insecure)
-  run_get_feature(stub)
-  run_list_features(stub)
-  run_route_chat(stub)
-  if ARGV.length == 0
-    p 'no feature database; skipping record_route'
-    exit
-  end
-  raw_data = []
-  File.open(ARGV[0]) do |f|
-    raw_data = MultiJson.load(f.read)
-  end
-  run_record_route(stub, raw_data)
+  1000.times {|i|
+    p i
+    run_get_feature(stub)
+    run_list_features(stub)
+    run_route_chat(stub)
+  }
 end

 main
diff --git a/examples/ruby/route_guide/route_guide_server.rb b/examples/ruby/route_guide/route_guide_server.rb
index 9ee1b98eca..4f54e5dcce 100755
--- a/examples/ruby/route_guide/route_guide_server.rb
+++ b/examples/ruby/route_guide/route_guide_server.rb
@@ -168,7 +168,7 @@ def main
   end
   feature_db = Hash[raw_data.map { |x| [x['location'], x['name']] }]
   port = '0.0.0.0:50051'
-  s = GRPC::RpcServer.new
+  s = GRPC::RpcServer.new(server_args: {"grpc.max_connection_age_ms" => 1})
   s.add_http2_port(port, :this_port_is_insecure)
   GRPC.logger.info("... running insecurely on #{port}")
   s.handle(ServerImpl.new(feature_db))
```

Then run server and client:
Terminal 1
```
 bundle exec route_guide/route_guide_server.rb ../python/route_guide/route_guide_db.json
```
Terminal 2
```
bundle exec route_guide/route_guide_client.rb
```

Later, we see the error is raised and client stops.

### What did you expect to see?
Ideally we shouldn't get any errors. gPRC should handle goaway internally when server wants to gracefully disconnect based on [RFC](https://www.rfc-editor.org/rfc/rfc9113.html#name-goaway).

NB: We haven't noticed this issue in our go gPRC client.

### What did you see instead?

**Error**
```
14:GOAWAY received. debug_error_string:{UNKNOWN:Error in HTTP transport completing operation: send_initial_metadata_finished write_state=WRITING+MORE refs=1 flags=1 {created_time:"2022-11-21T15:51:05.138713-08:00", target_address:"ipv6:%5B::1%5D:50051", children:[UNKNOWN:Pending writes failed due to stream closure {created_time:"2022-11-21T15:51:05.138703-08:00", children:[UNKNOWN:GOAWAY received {created_time:"2022-11-21T15:51:05.138556-08:00", http2_error:0, grpc_status:14, raw_bytes:""}]}]}} (GRPC::Unavailable)
```

**The whole track**
```
Traceback (most recent call last):
	25: from /Users/yli/.rbenv/versions/2.7.6/bin/bundle:23:in `<main>'
	24: from /Users/yli/.rbenv/versions/2.7.6/bin/bundle:23:in `load'
	23: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
	22: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	21: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
	20: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
	19: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	18: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
	17: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	16: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	14: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
	13: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
	12: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
	11: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
	10: from route_guide/route_guide_client.rb:158:in `<top (required)>'
	 9: from route_guide/route_guide_client.rb:150:in `main'
	 8: from route_guide/route_guide_client.rb:150:in `times'
	 7: from route_guide/route_guide_client.rb:153:in `block in main'
	 6: from route_guide/route_guide_client.rb:64:in `run_list_features'
	 5: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/service.rb:181:in `block (3 levels) in rpc_stub_class'
	 4: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/client_stub.rb:348:in `server_streamer'
	 3: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	 2: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/client_stub.rb:349:in `block in server_streamer'
	 1: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:456:in `server_streamer'
/Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:456:in `run_batch': call#run_batch failed somehow (GRPC::Core::CallError)
	28: from /Users/yli/.rbenv/versions/2.7.6/bin/bundle:23:in `<main>'
	27: from /Users/yli/.rbenv/versions/2.7.6/bin/bundle:23:in `load'
	26: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
	25: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	24: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
	23: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
	22: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	21: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
	20: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	19: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	17: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
	16: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
	15: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
	14: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
	13: from route_guide/route_guide_client.rb:158:in `<top (required)>'
	12: from route_guide/route_guide_client.rb:150:in `main'
	11: from route_guide/route_guide_client.rb:150:in `times'
	10: from route_guide/route_guide_client.rb:153:in `block in main'
	 9: from route_guide/route_guide_client.rb:64:in `run_list_features'
	 8: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/service.rb:181:in `block (3 levels) in rpc_stub_class'
	 7: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/client_stub.rb:348:in `server_streamer'
	 6: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	 5: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/client_stub.rb:349:in `block in server_streamer'
	 4: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:457:in `server_streamer'
	 3: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:458:in `rescue in server_streamer'
	 2: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:175:in `receive_and_check_status'
	 1: from /Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:186:in `attach_status_results_and_complete_call'
/Users/yli/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/grpc-1.50.0/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 14:GOAWAY received. debug_error_string:{UNKNOWN:Error in HTTP transport completing operation: send_initial_metadata_finished write_state=WRITING+MORE refs=1 flags=1 {created_time:"2022-11-21T15:51:05.138713-08:00", target_address:"ipv6:%5B::1%5D:50051", children:[UNKNOWN:Pending writes failed due to stream closure {created_time:"2022-11-21T15:51:05.138703-08:00", children:[UNKNOWN:GOAWAY received {created_time:"2022-11-21T15:51:05.138556-08:00", http2_error:0, grpc_status:14, raw_bytes:""}]}]}} (GRPC::Unavailable)
```

**Comment by alto-ruby** [comment]
This is not ruby specific, I can reproduce it with the cpp server: `examples/cpp/route_guide:route_guide_server` as well.

Can someone in c-core take a look at this?

CC: @HannahShiSFB 

```
git diff src/cpp/server/server_builder.cc
diff --git a/src/cpp/server/server_builder.cc b/src/cpp/server/server_builder.cc
index 583ca42c26..af8553ea0d 100644
--- a/src/cpp/server/server_builder.cc
+++ b/src/cpp/server/server_builder.cc
@@ -268,6 +268,7 @@ ChannelArguments ServerBuilder::BuildChannelArgs() {
                               authorization_provider_->c_provider(),
                               grpc_authorization_policy_provider_arg_vtable());
   }
+  args.SetInt(GRPC_ARG_MAX_CONNECTION_AGE_MS, 1);
   return args;
 }
```
