### ISSUE TITLE
Bump gevent version to avoid Cython cpdef issue

### ISSUE THREAD

**Issue by shareefj** [grpc/grpc#31802]
### What version of gRPC and what language are you using?
gRPC v1.50.1 and I'm using C++ but this issue is with a Python dependency

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04.01 LTS in WSL

### What runtime / compiler are you using (e.g. python version or version of gcc)
$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ python -V
Python 3.10.6

### What did you do?
$ bazel query //...

### What did you expect to see?
The list of available labels.

### What did you see instead?
I get an error when running query.  This seems to be due to a dependency on gevent which is too old.

```
ERROR: Could not find a version that satisfies the requirement gevent==21.1.2 (from versions: 0.9.2, 0.9.3, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 1.0, 1.0.1, 1.0.2, 1.1a1, 1.1a2, 1.1b1, 1.1b2, 1.1b3, 1.1b4, 1.1b5, 1.1b6, 1.1rc1, 1.1rc2, 1.1rc3, 1.1rc4, 1.1rc5, 1.1.0, 1.1.1, 1.1.2, 1.2a1, 1.2a2, 1.2.0, 1.2.1, 1.2.2, 1.3a1, 1.3a2, 1.3b1, 1.3b2, 1.3.0, 1.3.1, 1.3.2, 1.3.2.post0, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4.0, 1.5a1, 1.5a2, 1.5a3, 1.5a4, 1.5.0, 20.4.0, 20.5.0, 20.5.1, 20.5.2, 20.6.0, 20.6.1, 20.6.2, 20.9.0, 20.12.0, 20.12.1, 21.1.0, 21.1.1, 21.1.2, 21.8.0, 21.12.0, 22.8.0, 22.10.1, 22.10.2)
ERROR: No matching distribution found for gevent==21.1.2
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shareefj/.cache/bazel/_bazel_shareefj/ebd63933a37b436858f7ab2b2d82e5ea/external/io_bazel_rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in <module>
    main()
  File "/home/shareefj/.cache/bazel/_bazel_shareefj/ebd63933a37b436858f7ab2b2d82e5ea/external/io_bazel_rules_python/python/pip_install/extract_wheels/__init__.py", line 76, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/shareefj/git/grpc/.venv/bin/python3', '-m', 'pip', '--isolated', 'wheel', '-r', '/home/shareefj/.cache/bazel/_bazel_shareefj/ebd63933a37b436858f7ab2b2d82e5ea/external/com_github_grpc_grpc/requirements.bazel.txt']' returned non-zero exit status 1.
```

An associated ticket on gevent:  https://github.com/gevent/gevent/issues/1801

If I manually try to install gevent as you have it in `requirements.bazel.txt`, gevent==21.1.2, I get the same error.

**Comment by shareefj** [comment]
So the safe tags to use are:

```
$ git tag --contains 1aac7caba91
v1.51.0
v1.51.0-pre1
v1.51.1
```
