### ISSUE TITLE
Hermetic bazel python builds

### ISSUE THREAD

**Issue by philstahlfeld** [grpc/grpc#31892]
### Is your feature request related to a problem? Please describe.
When I use bazel to build python gRPC servers (and, I suppose, clients), I get "undefined symbol" cython errors if by bazel python rules version doesn't match my system's python version. For example, when I try to "import grpc" with a bazel python version of 3.9 and a system python version of 3.10, I get the following error:
```
==================== Test output for //coultech/thor/backend:candidate_service_test:
Traceback (most recent call last):
  File "/home/philstahlfeld/.cache/bazel/_bazel_philstahlfeld/06691ff925eb71d440deffe948c90182/sandbox/linux-sandbox/3255/execroot/__main__/bazel-out/k8-opt/bin/coultech/thor/backend/candidate_service_test.runfiles/__main__/coultech/thor/backend/candidate_service_test.py", line 5, in <module>
    import grpc
  File "/home/philstahlfeld/.cache/bazel/_bazel_philstahlfeld/06691ff925eb71d440deffe948c90182/sandbox/linux-sandbox/3255/execroot/__main__/bazel-out/k8-opt/bin/coultech/thor/backend/candidate_service_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/philstahlfeld/.cache/bazel/_bazel_philstahlfeld/06691ff925eb71d440deffe948c90182/sandbox/linux-sandbox/3255/execroot/__main__/bazel-out/k8-opt/bin/coultech/thor/backend/candidate_service_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /home/philstahlfeld/.cache/bazel/_bazel_philstahlfeld/06691ff925eb71d440deffe948c90182/sandbox/linux-sandbox/3255/execroot/__main__/bazel-out/k8-opt/bin/coultech/thor/backend/candidate_service_test.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so: undefined symbol: PyDescr_IsData
================================================================================
```
If I switch my bazel python version to 3.10, the test passes. This indicates that the cython rules are looking at a locally installed version of python and not the one that will be used in the `py_test` or `py_binary` rules.

The cython rules seem to use the [local python headers](https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/bazel/cython_library.bzl#L74).

### Describe the solution you'd like
Performing a `bazel test` or a `bazel run` should pass/fail independently of the locally installed python version. 

### Describe alternatives you've considered
One option I've explored is using pip to install the grpcio package and that works fine if I just wanted to do "import grpc". However, I want to use the `py_proto_library` and `py_grpc_library` targets provided by this repo.

### Additional context
Add any other context about the feature request here.
I'm happy to implement this if someone from the gRPC team can approve my design. When adding the gRPC rules to the WORKSPACE, I recommend adding an optional `python_headers` parameter to `grpc_deps` so the WORKSPACE would look as follows:
```
python_register_toolchains(
    name = "python3_9",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.9",
)

http_archive(
    name = "com_github_grpc_grpc",
    ...
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps(
    python_headers="@python3_9//:python_headers",
)

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
```
The `python_headers` parameter would then be passed through to the location where the headers [are bound](https://github.com/grpc/grpc/blob/master/bazel/grpc_python_deps.bzl#L35). The cython rules can then be updated to refer to `//external:python_headers` [here](https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/bazel/cython_library.bzl#L74).

Note that I've tested this out locally and it yield results that are independent from the locally installed python.

**Comment by gnossen** [comment]
This is an issue we are aware of and have fixing it on our roadmap. However, the user should not have to explicitly pass in the headers. We're looking at contributing an upstream change to `rules_python` to make this target available as a `toolchain` so that not only we can access it without user intervention but so can any other projects building a native extension.

**Comment by philstahlfeld** [comment]
Awesome! Thank you for the quick response. Do you have a timeline for when this will be implemented?

**Comment by gnossen** [comment]
My hope is to have this finished by the end of February, but that's not a hard date.

**Comment by harrisonfang-helm** [comment]
@gnossen Any updates on the timeline or workarounds in the short-term?

**Comment by philstahlfeld** [comment]
FWIW, my team has been using the workaround mentioned in the Additional Context section. We forked the repo so that we can manually pass the python headers to the grpc_deps call in our WORKSPACE file. It works for us, but certainly hasn't been blessed by the gRPC folks.

**Comment by gnossen** [comment]
This is still high priority but has been pre-empted by other fires. I would say this is now at least a month away from completion.

**Comment by sfc-gh-mussakli** [comment]
@gnossen, what's the progress on this currently? Can you point to a workaround at least that would allow us to refer to the `python_headers` from the toolchain? The lack of a hermetic solution here makes using protobufs in Python a non-starter for us.

**Comment by philstahlfeld** [comment]
@nvachhar not sure if this is helpful for you or not, but you can get this working with a [simple patch](https://gist.github.com/philstahlfeld/63216433672acf91f59c4a783bea7d1e).

**Comment by nvachhar** [comment]
Thanks @philstahlfeld - I'll give a try

**Comment by ramilmsh** [comment]
@philstahlfeld if it's not too difficult, could you make an example workspace with this workaround? I have attempted to implement it, but continue to get the same error as before

WORKSPACE
```
...
python_register_toolchains(
    name = "python310",
    python_version = "3.10",
)
...
git_repository(
    name = "com_github_grpc_grpc",
    commit = "12161ee3aa7c216741cd7c406573abc0df1d0926",
    patches = ["//tools/patches/grpc:grpc.patch"],
    remote = "https://github.com/grpc/grpc.git",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps(
    python_headers = "@python310//:python_headers",
)
...
```

BUILD
```
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "test",
    srcs = [
        "__init__.py",
    ],
    imports = ["../../.."],
    visibility = ["//:__subpackages__"],
    deps = ["@pip_grpcio//:pkg"],
)

py_binary(
    name = "test_bin",
    srcs = ["__main__.py"],
    imports = ["../../.."],
    main = "__main__.py",
    visibility = ["//:__subpackages__"],
    deps = [":test"],
)
```

__init__.py:
```
import grpc


def get_version() -> str:
    return grpc.__version__
```

__main__.py:
```
from <package> import get_version

if __name__ == "__main__":
    print(get_version())
```

Error:
```
ImportError: cannot import name 'cygrpc' from 'grpc._cython'
```

I feel like I am missing something obvious and it's a blocker for python bazel integration at the moment...

**Comment by philstahlfeld** [comment]
@ramilmsh, I put together a basic example of importing grpc [here](https://github.com/philstahlfeld/grpc-hermetic-python). It doesn't include any protos, but that doesn't seem to be what you're stuck on. Let me know if you have any questions.

**Comment by ramilmsh** [comment]
@philstahlfeld Thanks for the example, it was very useful to validate my setup. However, yes, I had a different issue. To use your example here is what I had:

```
load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(  # this line broke everything
    name = "python3_8",
    python_version = "3.8",
)

python_register_toolchains(
    name = "python3_10",
    python_version = "3.10",
)

load("@python3_10//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_deps",
    python_interpreter_target = interpreter,
    requirements_lock = "//python:requirements.txt",
)

load("@pip_deps//:requirements.bzl", install_pip_deps = "install_deps")

install_pip_deps()
```

With 2 registered toolchains, i would get the error, but removing one of them worked... Still not 100% sure why, my suspicion is the way system python is determined (`python3` on my system pointed to 3.10, but bazel was using 3.8).

So the example you provided should work just fine.

**Comment by ankit-agarwal1999** [comment]
Any update on this?
