### ISSUE TITLE
TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by zhouyq9001** [grpc/grpc#32045]
### What version of gRPC and what language are you using?
 "grpcio==1.51.0",
 "grpcio-tools==1.51.0",
 "protobuf==4.21.6",
### What operating system (Linux, Windows,...) and version?
Mac OS 12.0.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.7

### Error information

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webullsdkquotescore/grpc/grpc_client.py", line 29, in <module>
    from webullsdkquotescore.grpc.connect import Connect
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webullsdkquotescore/grpc/connect.py", line 28, in <module>
    from webullsdkquotescore.grpc.msg import Msg
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webullsdkquotescore/grpc/msg.py", line 18, in <module>
    from webullsdkquotescore.grpc.pb import gateway_pb2 as pb
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/webullsdkquotescore/grpc/pb/gateway_pb2.py", line 49, in <module>
    create_key=_descriptor._internal_create_key),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by zhouyq9001** [comment]
The problem has been solved.
