### ISSUE TITLE
Not reporting errors when processing malformed data frame in response

### ISSUE THREAD

**Issue by felix021** [grpc/grpc#32257]
### What version of gRPC and what language are you using?
client: grpcio 1.51.1, python 3.7.3
server: kitex 0.4.4, golang 1.19.5

### What operating system (Linux, Windows,...) and version?
Linux, Debian 10, kernel 5.4.143.bsk.8-amd64

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.7.3

### What did you do?
Use the python client to call a gRPC server implemented on top of kitex 0.4.4 with a bug that in certain cases it will return a malformed data frame with the `compressed flag` set to a random number like 0xAF or 0xB7. 

![image](https://user-images.githubusercontent.com/367085/215973784-d874ad13-271a-438c-809a-a91dafadc202.png)

By capturing the packet we're sure the response is wrong (kitex will fix its own bug), but the python grpc client didn't report any error, and just returned a `None` as the response, which make it hard to diagnose.

### What did you expect to see?
To raise an exception when the response is malformed, in this case, it can be detected by:
1. the compressed flag is neither 0 nor 1;
2. if the flag is 0xAF, and client treat it to be 1, and fails to decompress the data;

### What did you see instead?
a `None` is returned as the response with no error.

**Comment by XuanWang-Amos** [comment]
Hi @ctiller, this looks like related to core, can you help take a look?

**Comment by XuanWang-Amos** [comment]
Hi @felix021, it's possible that we already detected the error, can you help provide us more information by:
1. Check if error were reported in the call status.
2. Check if error were logged by enable client with flag: `GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`

**Comment by felix021** [comment]
I've checked with `GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`, no error reported, that's why I had to capture and decode the response packet in wireshak

**Comment by felix021** [comment]
Open it again since it's closed by bot; close it if it's not meant to be fixed.

**Comment by felix021** [comment]
Steps for reproduction:

1. clone the demo project:
> git clone https://github.com/felix021/kitex-test.git
> cd kitex-test
> git checkout issue/grpc-32257

2. build and run the server
> sh build.sh
> sh output/bootstrap.sh

3. run the client
> cd pyclient
> python3 client.py

Hopefully you'll get output like this:

> Will try to send request ...
> Traceback (most recent call last):
>  File "/Users/felix021/github-kitex-test/pyclient/client.py", line 24, in <module>
>     run()
>  File "/Users/felix021/github-kitex-test/pyclient/client.py", line 19, in run
>    print("client received: " + response.message)
> AttributeError: 'NoneType' object has no attribute 'message'

**Comment by felix021** [comment]
Happen to recall this, and any chance this might be fixed? Not an important issue though.
