### ISSUE TITLE
Python grpc.aio + asyncio.run() gives RuntimeError: attached to a different loop

### ISSUE THREAD

**Issue by jogc** [grpc/grpc#32480]
I'm getting this error whenever I try to run a program using the recommended way with asyncio.run():

```
Traceback (most recent call last):
  File "/tmp/testcase/testcase.py", line 42, in <module>
    asyncio.run(app.run())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/testcase/testcase.py", line 38, in run
    print(await self.stub.GetInfo(ln.GetInfoRequest()))
  File "/home/x/venv/lib/python3.9/site-packages/grpc/aio/_call.py", line 271, in __await__
    response = yield from self._call_response
RuntimeError: Task <Task pending name='Task-1' coro=<App.run() running at /tmp/testcase/testcase.py:38> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-2' coro=<UnaryUnaryCall._invoke() running at /home/x/venv/lib/python3.9/site-packages/grpc/aio/_call.py:509>> attached to a different loop
```

Testcase:
```
import asyncio
import codecs
import grpc
import grpc.aio
import lngrpc.lightning_pb2 as ln
import lngrpc.lightning_pb2_grpc as lnrpc


class App():
    def __init__(self):

        rpcserver = '127.0.0.1:10009'
        tlscertpath = 'tls.cert'

        cert = open(tlscertpath, 'rb').read()

        cert_creds = grpc.ssl_channel_credentials(cert)
        auth_creds = grpc.metadata_call_credentials(self._metadata_callback)
        combined_creds = grpc.composite_channel_credentials(cert_creds,
            auth_creds)

        self._channel = grpc.aio.secure_channel(rpcserver,
            combined_creds, [
                ('grpc.max_message_length', 50 * 1024 * 1024),
                ('grpc.max_receive_message_length', 50 * 1024 * 1024)
            ])
        self.stub = lnrpc.LightningStub(self._channel)


    def _metadata_callback(self, context, callback):
        pass


    async def run(self):
        print(await self.stub.GetInfo(ln.GetInfoRequest()))


app = App()

# this does not work:
asyncio.run(app.run())

# this works:
#loop = asyncio.get_event_loop()
#loop.run_until_complete(app.run())
```

Required proto files: [lngrpc.zip](https://github.com/grpc/grpc/files/10839459/lngrpc.zip)

Tested with both Python 3.9.2 and 3.10.6 using:

googleapis-common-protos 1.58.0
grpcio                   1.51.3
grpcio-tools             1.51.3
pip                      23.0.1
protobuf                 4.22.0
setuptools               67.1.0
wheel                    0.38.4

**Comment by FedirAlifirenko** [comment]
Hi @jogc 👋 
`asyncio.run()` [creates](https://docs.python.org/3/library/asyncio-runner.html#running-an-asyncio-program) a new event loop. During `app` instantiation channel creation makes another event loop  
So, thats the reason of the error you've mentioned.

**Comment by gnossen** [comment]
[@FedirAlifirenko is correct](https://docs.python.org/3/library/asyncio-runner.html#asyncio.run). Please let us know if you have any further issues.

**Comment by jogc** [comment]
Maybe I'm missing something but for me this was not obvious at all that you are not allowed to use rpc.aio.secure_channel until after you have run asyncio.run, and are already in an async context. Maybe it should be documented?
Thank you
