### ISSUE TITLE
gRPC call throws  Invalid non-ASCII or control character in header: 0x0011 when request contains url 

### ISSUE THREAD

**Issue by WD1993** [grpc/grpc#32577]
### What version of gRPC and what language are you using?
2.49.0

### What operating system (Linux, Windows,...) and version?
Windows server 2019

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET6

### What did you do?
invoke a gRPC call 
            ManagedBackupConfiguration config = new ManagedBackupConfiguration
            {
                IsEnabled = settings.Enable,
                DatabaseName = string.Empty,
                **ContainerUrl = "https://xxxxxx.blob.core.windows.net/container4",**
                RetentionPolicyInDays = settings.RetentionPolicyInDays
            };

            new SqlQueryClient()._client.ConfigureManagedBackup(new IaaSRPC.QueryService.ConfigureManagedBackupRequest
            {
                SqlInstanceName = SqlInstanceHelper.CurrentTargetedSqlInstance,
                Config = config
            });

### What did you  see?
when containerurl is a valid http url, error raised 

		Exception: 
		**System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x0011**
		   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
		   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(String headerName, StringValues headerValues, Func`2 encodingSelector)
		   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast(String key, StringValues value)
		   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
		   at Microsoft.AspNetCore.Http.ParsingHelpers.SetHeaderUnmodified(IHeaderDictionary headers, String key, Nullable`1 values)
		   at Microsoft.AspNetCore.Http.ParsingHelpers.AppendHeaderUnmodified(IHeaderDictionary headers, String key, StringValues values)
		   at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
		   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.ProcessHandlerError(Exception ex, String method)
		   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
		   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
		   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

			

	Application: SqlIaaSExtension.Service.exe
CoreCLR Version: 6.0.1423.7309
.NET Version: 6.0.14
Description: The process was terminated due to an unhandled exception.
**Exception Info: [AzureStorageError] Status(StatusCode="Unknown", Detail="Bad gRPC response. HTTP status code: 500")**    at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.RevokePermissionOnActionFailure(Action action, PermissionSetOwner owner, String instanceName, Boolean IsLeastPrivilegeModeEnabled)
   at Microsoft.SqlServer.Management.AutoBackup.AutoBackupManagement.UpdateConfigurations(Int32 configurationSequenceNumber, SecureString protectedSettingsCertificateThumbprint, SecureString protectedSettings, PublicSettings publicSettings)
   at Microsoft.SqlServer.Management.SqlIaaSHandler.IaaSHandler.NewConfigurationFileFound(Object sender, NewFileEventsArgs e)
   at Microsoft.SqlServer.Management.IaaSUtility.DirectoryMonitor.CheckFile(String fullPath)
   at Microsoft.SqlServer.Management.IaaSUtility.DirectoryMonitor.OnFileRenamed(Object sender, RenamedEventArgs e)
   at System.IO.FileSystemWatcher.OnRenamed(RenamedEventArgs e)
   at System.IO.FileSystemWatcher.NotifyRenameEventArgs(WatcherChangeTypes action, ReadOnlySpan`1 name, ReadOnlySpan`1 oldName)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(ReadOnlySpan`1 buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)Inner exception: Status(StatusCode="Unknown", Detail="Bad gRPC response. HTTP status code: 500")    at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at IaaSRPC.QueryService.SqlQueryService.SqlQueryServiceClient.ConfigureManagedBackup(ConfigureManagedBackupRequest request, CallOptions options)
   at IaaSRPC.QueryService.SqlQueryService.SqlQueryServiceClient.ConfigureManagedBackup(ConfigureManagedBackupRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Microsoft.SqlServer.Management.AutoBackup.ManagedBackupV2Helpers.ConfigureManagedBackup(ManagedBackupSettings settings, String containerUrl, List`1 dbs)
   at Microsoft.SqlServer.Management.AutoBackup.ManagedBackupQueriesV2.UpdateManagedBackupConfigurations(ManagedBackupSettings settings, String& errorMessage)

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Output the header since it is indicating header contains non-ascii 

Header: user-agent=grpc-dotnet/2.49.0(.NET 6.0.14; CLR net6.0; windows; x64)

**Comment by tonydnewell** [comment]
This is a **grpc-dotnet** issues and should be reported there: https://github.com/grpc/grpc-dotnet
although it does appear that @JamesNK has already fix it.
