### ISSUE TITLE
[Python install]

### ISSUE THREAD

**Issue by xhrp** [grpc/grpc#32843]
### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

### What did you see instead?

C:\GPT\chatgpt-retrieval-plugin-main>poetry shell
Spawning shell within C:\Users\jbrucker\AppData\Local\pypoetry\Cache\virtualenvs\chatgpt-retrieval-plugin-0ucaB-47-py3.11

(chatgpt-retrieval-plugin-py3.11) C:\GPT\chatgpt-retrieval-plugin-main>poetry install
Installing dependencies from lock file

Package operations: 35 installs, 0 updates, 0 removals

  • Installing grpcio (1.47.5)

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  Found cython-generated files...
  ASM Builds for BoringSSL currently not supported on: win-amd64
  running bdist_wheel
  running build
  running build_py
  running build_project_metadata
  creating python_build
  creating python_build\lib.win-amd64-cpython-311
  creating python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_common.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_runtime_protos.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_server.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_simple_stubs.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win-amd64-cpython-311\grpc
  copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc
  creating python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_base_call.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_base_channel.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_base_server.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_call.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_channel.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_interceptor.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_server.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_typing.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\_utils.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  copying src\python\grpcio\grpc\aio\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\aio
  creating python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\beta
  creating python_build\lib.win-amd64-cpython-311\grpc\experimental
  copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
  copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
  copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental
  creating python_build\lib.win-amd64-cpython-311\grpc\framework
  copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework
  creating python_build\lib.win-amd64-cpython-311\grpc\_cython
  copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\_cython
  creating python_build\lib.win-amd64-cpython-311\grpc\experimental\aio
  copying src\python\grpcio\grpc\experimental\aio\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\experimental\aio
  creating python_build\lib.win-amd64-cpython-311\grpc\framework\common
  copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
  copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
  copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\common
  creating python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\foundation
  creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces
  copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces
  creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
  copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
  copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
  copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\base
  creating python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
  copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
  copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
  copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\framework\interfaces\face
  creating python_build\lib.win-amd64-cpython-311\grpc\_cython\_cygrpc
  copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win-amd64-cpython-311\grpc\_cython\_cygrpc
  creating python_build\lib.win-amd64-cpython-311\grpc\_cython\_credentials
  copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win-amd64-cpython-311\grpc\_cython\_credentials
  running build_ext
  Non-fatal exception:Traceback (most recent call last):
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpe8jw61xj\grpcio-1.47.5\src\python\grpcio\commands.py", line 231, in compiler_ok_with_extra_std
      cc_test = subprocess.Popen(['cc', '-x', 'c', '-std=c++14', '-'],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python311\Lib\subprocess.py", line 1022, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Python311\Lib\subprocess.py", line 1491, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  Found cython-generated files...
  building 'grpc._cython.cygrpc' extension
  Traceback (most recent call last):
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpe8jw61xj\grpcio-1.47.5\src\python\grpcio\commands.py", line 280, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
                ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
      self.initialize()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
      vc_env = _get_vc_env(plat_spec)
               ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\msvc.py", line 210, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\msvc.py", line 164, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Python311\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Python311\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Python311\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 541, in <module>
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\__init__.py", line 108, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
      super().run_command(command)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
      super().run_command(command)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
      super().run_command(command)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
      self.build_extensions()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpe8jw61xj\grpcio-1.47.5\src\python\grpcio\commands.py", line 283, in build_extensions
      support.diagnose_build_ext_error(self, error, formatted_exception)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpe8jw61xj\grpcio-1.47.5\src\python\grpcio\support.py", line 110, in diagnose_build_ext_error
      raise commands.CommandError(
  commands.CommandError:

  We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).

  Traceback (most recent call last):
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpe8jw61xj\grpcio-1.47.5\src\python\grpcio\commands.py", line 280, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
                ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
      self.initialize()
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
      vc_env = _get_vc_env(plat_spec)
               ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\msvc.py", line 210, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jbrucker\AppData\Local\Temp\tmpdiwh_kil\.venv\Lib\site-packages\setuptools\msvc.py", line 164, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

  at C:\Python311\Lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with grpcio (1.47.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "grpcio (==1.47.5)"'.

**Comment by gnossen** [comment]
> distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

You've fallen back to a from-source build because the gRPC version (1.47.5) does not support Python 3.11. You'll need to do one of the following:

- Install a working developer toolchain to compile from source
- Upgrade your `grpcio` pin to `1.49.1` or higher
- Or downgrade your Python version to 3.10 or lower
