### ISSUE TITLE
NodeJS unit tests crash with a segmentation fault on Mac OS X

### ISSUE THREAD

**Issue by iam-johntan** [grpc/grpc#3284]
Randomly fails with a segmentation fault in either end-to-end and interop tests.  

Here's a sample run:

```
/usr/local/lib/node_modules/grpc>npm test

> grpc@0.10.1 test /usr/local/lib/node_modules/grpc
> node ./node_modules/mocha/bin/mocha && npm run-script lint

child_process: customFds option is deprecated, use stdio instead.


  call
    constructor
      ✓ should reject anything less than 3 arguments 
      ✓ should succeed with a Channel, a string, and a date or number 
      ✓ should fail with a closed channel 
      ✓ should fail with other types 
    startBatch
      ✓ should fail without an object and a function 
      ✓ should succeed with an empty object 
    startBatch with metadata
      ✓ should succeed with a map of strings to string arrays 
      ✓ should succeed with a map of strings to buffer arrays 
      ✓ should fail with other parameter types 
    cancel
      ✓ should succeed 
D0908 16:26:12.359573000 140735271944960 server.c:496] Waiting for all listeners to be destroyed (@ 0/1)

  channel
    constructor
      ✓ should require a string for the first argument 
      ✓ should accept an object for the second parameter 
      ✓ should only accept objects with string or int values 
    close
      ✓ should succeed silently 
      ✓ should be idempotent 

  Proto message serialize and deserialize
    ✓ should preserve positive int64 values 
    ✓ should preserve negative int64 values 
    ✓ should preserve uint64 values 
    ✓ should preserve positive sint64 values 
    ✓ should preserve negative sint64 values 
    ✓ should preserve fixed64 values 
    ✓ should preserve positive sfixed64 values 
    ✓ should preserve negative sfixed64 values 

  constants
    ✓ should have all of the status constants 
    ✓ should have all of the call errors 

  end-to-end
sh: line 1: 58128 Segmentation fault: 11  node ./node_modules/mocha/bin/mocha
npm ERR! Test failed.  See above for more details.
```
  
**Relevant info:**
Installed using homebrew as per instructions here:  https://github.com/grpc/grpc/tree/master/src/node
Mac OS X 10.10.5 (14F27) - Yosemite
```
/usr/local/lib/node_modules/grpc>node -v
v0.12.7
```
```
/usr/local/lib/node_modules/grpc>npm ls nan
grpc@0.10.1 /usr/local/lib/node_modules/grpc
└── nan@1.9.0 
```
May be related to issue #3259.

**Comment by murgatroid99** [comment]
Do you still see this problem under version 0.11?

**Comment by iam-johntan** [comment]
From the release-0_11 branch, the tests all pass now.

From the homebrew installation, health_check/health.js appears to be missing so the tests won't run.  I assume they would pass if the module was there since the package is built from the release-0_11 branch?  Thanks!

```
/Users/johntan/node_modules/grpc>npm test

> grpc@0.11.0 test /Users/johntan/node_modules/grpc
> node ./node_modules/mocha/bin/mocha && npm run-script lint

child_process: customFds option is deprecated, use stdio instead.
module.js:338
    throw err;
    ^
Error: Cannot find module '../health_check/health.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/johntan/node_modules/grpc/test/health_test.js:38:14)
```

**Comment by iam-johntan** [comment]
Closing since the release-0_11 branch appears to be ok.
