### ISSUE TITLE
Stack smashing before `main()` caused by adding `import` to quick start's greeter proto file

### ISSUE THREAD

**Issue by keith-bennett-airmap** [grpc/grpc#33039]
### What version of gRPC and what language are you using?
v1.54.1

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
`gcc --version` ->
```
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### What did you do?
1. Use the `Greeter` service quickstart example from `grpc.io` found [here](https://grpc.io/docs/languages/cpp/quickstart/).
    1. Copy-pasted the first proto file text found in the quick start website into [`./src/proto/greeter.proto`](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/src/proto/greeter.proto)
    2. **I did _not_** copy [the .proto file from the grpc repository](https://github.com/grpc/grpc/blob/7155c92910aca35720d88b70bf827b051555cf9f/examples/protos/helloworld.proto)
2. Add `import "google/api/field_behavior.proto";` to import a `.proto` file from `googleapis` repository [here](https://github.com/googleapis/googleapis/blob/6f5d107aadb4782b71c530f4dc17ec86c922d8a9/google/api/field_behavior.proto).

This is verified in a repository I created with a demonstration [here](https://github.com/keith-bennett-airmap/grpc-stacksmash).

You can run `./build.sh`. It will:
1. [Find or create a couple of toolchain images](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/build.sh#L5)
    1. [Find, or create and tag, `ubuntu-2004-toolchain` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/build.sh#L5-L7) which includes only the Ubuntu packages required to compile
        1. this takes a couple minutes
        2. `gcc-11` is [installed from ubunut-toolchain PPA](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/ubuntu-2004-toolchain.Dockerfile#L16-L24)
    2. [Find, or create and tag, `grpc-toolchain` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/build.sh#L8-L10) which includes `cmake`, `protobuf`, and `grpc` built from source
        1. This takes about ten minutes on my local machine.
        2. **NOTE: this image [enables Address Sanitizer via environment variables](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/grpc-toolchain.Dockerfile#L4-L6) to enforce ASAN throughout the demonstration.**
        3. [Here](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/grpc-toolchain.Dockerfile#L30) is `protobuf` version. Note that I use version `v21.12` due to [a separate issue found](https://github.com/protocolbuffers/protobuf/issues/12653) while constructing this demonstration.
        4. [Here](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/docker/grpc-toolchain.Dockerfile#L49) is `grpc` version
2. [Remove an existing `grpc-stacksmash` image and `docker system prune`](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/build.sh#L7-L8) to keep Docker from using tons of resources while iterating changes to the source tree
3. [Create and tag a new `grpc-stacksmash` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/build.sh#L9) which compiles a demonstration
    1. This take about 30 seconds on my local machine.
4. [Runs the `grpc-stacksmash` image](https://github.com/keith-bennett-airmap/grpc-stacksmash/blob/7155c92910aca35720d88b70bf827b051555cf9f/build.sh#L10) to demonstrate whether the resulting executable is viable

### What did you expect to see?
Per initial commit [here](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/e5d2b931dc2f86e68d85ace675050f2739be116d):
`./build.sh` ->
```
Successfully built 55df7a9eb834
Successfully tagged grpc-stacksmash:latest
greeter service created -- no stacksmash
```

### What did you see instead?
Per +1 commit [here](https://github.com/keith-bennett-airmap/grpc-stacksmash/commit/7155c92910aca35720d88b70bf827b051555cf9f):
`./build.sh` ->
```
Successfully tagged grpc-stacksmash:latest
*** stack smashing detected ***: terminated
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7f5d4a894941 bp 0x7fff9a8d4380 sp 0x7fff9a8d4120 T0)
==1==The signal is caused by a READ memory access.
==1==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x7f5d4a894941 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x22941)
    #1 0x7f5d4a8ff26d  (/lib/x86_64-linux-gnu/libc.so.6+0x8d26d)
    #2 0x7f5d4a9a1ab9 in __fortify_fail (/lib/x86_64-linux-gnu/libc.so.6+0x12fab9)
    #3 0x7f5d4a9a1a85 in __stack_chk_fail (/lib/x86_64-linux-gnu/libc.so.6+0x12fa85)
    #4 0x55e5c318da3a in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/descriptor_database.cc:564
    #5 0x55e5c3120562 in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/descriptor.cc:1986
    #6 0x55e5c30d7bb4 in AddDescriptorsImpl /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3049
    #7 0x55e5c30d7bf1 in AddDescriptors /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3060
    #8 0x55e5c30d7b8f in AddDescriptorsImpl /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3045
    #9 0x55e5c30d7bf1 in AddDescriptors /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3060
    #10 0x55e5c30d7b8f in AddDescriptorsImpl /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3045
    #11 0x55e5c30d7bf1 in AddDescriptors /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3060
    #12 0x55e5c30d7cfd in google::protobuf::internal::AddDescriptorsRunner::AddDescriptorsRunner(google::protobuf::internal::DescriptorTable const*) /usr/src/grpc/grpc/third_party/protobuf/src/google/protobuf/generated_message_reflection.cc:3095
    #13 0x55e5c2ffd2ae in __static_initialization_and_destruction_0 /usr/src/grpc-stacksmash/src/build/proto/proto-out/proto/greeter.pb.cc:104
    #14 0x55e5c2ffd2e6 in _GLOBAL__sub_I.00102__HelloRequest_default_instance_ /usr/local/include/google/protobuf/port_undef.inc:154
    #15 0x55e5c3b0dcbc in __libc_csu_init (/usr/bin/greeter-service+0xbd4cbc)
    #16 0x7f5d4a89600f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2400f)
    #17 0x55e5c2fcc96d in _start (/usr/bin/greeter-service+0x9396d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x22941) in abort
==1==ABORTING
```

### Anything else we should know about your project / environment?
The `import` problem is a _Minimal Compilable Reproducible Example_ that has been trimmed down from a larger codebase. The larger codebase includes several golang projects which are currently using the .proto files being imported. **This issue blocks me from building a C++ project to communicate with several golang projects that are already importing this file.**

2023-05-09 update -- changed links to `7155c92910aca35720d88b70bf827b051555cf9f` instead of `master`

**Comment by keith-bennett-airmap** [comment]
Ahh it looks like this problem is actually in protobuf and not grpc. I opened [a new issue in the protobuf repository](https://github.com/protocolbuffers/protobuf/issues/12732).
