### ISSUE TITLE
Exception in client side message iterator intermittently treated as clean connection close on server side

### ISSUE THREAD

**Issue by legaul-cisco** [grpc/grpc#33038]
### What version of gRPC and what language are you using?
Python, grpcio v1.54.0

### What operating system (Linux, Windows,...) and version?
Linux (multiple)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11, 3.10

### What did you do?
- Set up a simple gRPC server supporting a stream-stream method
- Set up a simple gRPC client to send messages to the server
- Raise an exception in the message iterator (see below)

```python
def msg_iterator():
    logging.debug("Sending gRPC message")
    yield msg
    time.sleep(1)
    raise Exception("gRPC client unclean connection close")
```

Hopefully this is clear enough and straightforward enough to reproduce, but if not I can provide code samples.

### What did you expect to see?
Expected `grpc.RpcError` to be raised when calling `__next__()` on the server side message iterator.

Some debug logs I added into the grpc code:
```
2023-05-08 12:56:29,434  INFO (t=25766)[__main__] - Connection established with gRPC peer: ipv6:%5B::1%5D:55906
2023-05-08 12:56:29,434 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.client='open'
2023-05-08 12:56:29,434 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.due={'receive_message', 'receive_close_on_server'}
2023-05-08 12:56:29,434 DEBUG (t=25746)[grpc._server] - receive_message():
2023-05-08 12:56:29,434 DEBUG (t=25746)[grpc._server] - _possibly_finish_call(): state.due={'receive_message', 'receive_close_on_server'}, remove receive_message
2023-05-08 12:56:29,434 DEBUG (t=25766)[grpc._server] - _look_for_request(): self._state.client='open', self._state.request=ReqId: 1
, self._state.due={'receive_close_on_server'}
2023-05-08 12:56:29,434 DEBUG (t=25766)[__main__] - Got message
2023-05-08 12:56:29,434 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.client='open'
2023-05-08 12:56:29,434 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.due={'receive_message', 'receive_close_on_server'}
2023-05-08 12:56:30,437 DEBUG (t=25746)[grpc._server] - receive_message():
2023-05-08 12:56:30,437 DEBUG (t=25746)[grpc._server] - _possibly_finish_call(): state.due={'receive_message', 'receive_close_on_server'}, remove receive_message
2023-05-08 12:56:30,437 DEBUG (t=25746)[grpc._server] - receive_close_on_server():
2023-05-08 12:56:30,437 DEBUG (t=25746)[grpc._server] - receive_close_on_server(): Setting client state to cancelled
2023-05-08 12:56:30,437 DEBUG (t=25746)[grpc._server] - _possibly_finish_call(): state.due={'receive_close_on_server'}, remove receive_close_on_server
2023-05-08 12:56:30,437 DEBUG (t=25766)[grpc._server] - _look_for_request(): self._state.client='cancelled', self._state.request=None, self._state.due=set()
2023-05-08 12:56:30,437  INFO (t=25766)[__main__] - Connection lost with gRPC peer ipv6:%5B::1%5D:55906
Traceback (most recent call last):
  File "grpc-conn/server.py", line 38, in MdtDialout
    msg = next(request_iterator)
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 486, in __next__
    return self._next()
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 478, in _next
    request = self._look_for_request()
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 460, in _look_for_request
    _raise_rpc_error(self._state)
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 155, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
```

### What did you see instead?
*Intermittently*, the connection gets closed cleanly, i.e. `request_iterator.__next__()` raises `StopIteration`.
```
2023-05-08 12:56:24,919  INFO (t=25766)[__main__] - Connection established with gRPC peer: ipv6:%5B::1%5D:55904
2023-05-08 12:56:24,919 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.client='open'
2023-05-08 12:56:24,919 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.due={'receive_message', 'receive_close_on_server'}
2023-05-08 12:56:24,919 DEBUG (t=25746)[grpc._server] - receive_message():
2023-05-08 12:56:24,920 DEBUG (t=25746)[grpc._server] - _possibly_finish_call(): state.due={'receive_message', 'receive_close_on_server'}, remove receive_message
2023-05-08 12:56:24,920 DEBUG (t=25766)[grpc._server] - _look_for_request(): self._state.client='open', self._state.request=ReqId: 1
, self._state.due={'receive_close_on_server'}
2023-05-08 12:56:24,920 DEBUG (t=25766)[__main__] - Got message
2023-05-08 12:56:24,920 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.client='open'
2023-05-08 12:56:24,920 DEBUG (t=25766)[grpc._server] - _raise_or_start_receive_message(): self._state.due={'receive_message', 'receive_close_on_server'}
2023-05-08 12:56:25,923 DEBUG (t=25746)[grpc._server] - receive_message():
2023-05-08 12:56:25,923 DEBUG (t=25746)[grpc._server] - _possibly_finish_call(): state.due={'receive_message', 'receive_close_on_server'}, remove receive_message
2023-05-08 12:56:25,923 DEBUG (t=25746)[grpc._server] - receive_close_on_server():
2023-05-08 12:56:25,923 DEBUG (t=25766)[grpc._server] - _look_for_request(): self._state.client='closed', self._state.request=None, self._state.due={'receive_close_on_server'}
2023-05-08 12:56:25,924  WARN (t=25766)[__main__] - !!!!!!!!!!!!!!
2023-05-08 12:56:25,924 DEBUG (t=25746)[grpc._server] - receive_close_on_server(): Setting client state to cancelled
2023-05-08 12:56:25,924  INFO (t=25766)[__main__] - Connection closed by gRPC peer ipv6:%5B::1%5D:55904
Traceback (most recent call last):
  File "grpc-conn/server.py", line 38, in MdtDialout
    msg = next(request_iterator)
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 486, in __next__
    return self._next()
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 478, in _next
    request = self._look_for_request()
  File "grpc-conn/venv3.10/lib/python3.10/site-packages/grpc/_server.py", line 465, in _look_for_request
    raise StopIteration()
StopIteration
2023-05-08 12:56:25,924 DEBUG (t=25746)[grpc._server] - _possibly_finish_call(): state.due={'receive_close_on_server'}, remove receive_close_on_server
```

### Anything else we should know about your project / environment?
n/a

**Comment by legaul-cisco** [comment]
After staring at `grpc/_server.py` for a while, my best guess is that it's a race to obtain the thread lock taking place between `_RequestIterator._next()` at `self._state.condition.wait()` and `receive_close_on_server()` at `with state.condition:`.

One thing I'm not clear on is why `receive_message()` gets triggered at all in this case, which is what leads to `_RequestIterator._look_for_request()` (via `_RequestIterator._next()`) to raise `StopIteration`:
```python
if self._state.client is _CANCELLED:
    _raise_rpc_error(self._state)
elif self._state.request is None and _RECEIVE_MESSAGE_TOKEN not in self._state.due:
    raise StopIteration()

**Comment by XuanWang-Amos** [comment]
Hi, Sorry for the the wait, you're correct that it's caused by a race condition between  `_RequestIterator._next()` and `receive_close_on_server()`.

To add more context, for RPCs using streaming request, we'll always use a separate thread to read the request (using [_RequestIterator._next](https://github.com/grpc/grpc/blob/v1.54.x/src/python/grpcio/grpc/_server.py#L423)), which will create a `ReceiveMessageOperation` and call core API to start this operation, in your example, the Exception in client side causing this operation returned  a None [as request here](https://github.com/grpc/grpc/blob/v1.54.x/src/python/grpcio/grpc/_server.py#L232-L235) and then closed the client using `CLOSED` instead of `CANCELLED`

**Comment by gibsondan** [comment]
@XuanWang-Amos in the dagster project we're seeing an error with some similar symptoms, except the client and servers are swapped compared to this report. We have a streaming server rpc call that always returns at least one message when it succeeds, but the client is intermittently getting an empty list as a response without any exceptions (i.e. an unexpected StopIteration call before any messages are received, which shouldn't happen). Unfortunately i haven't been able to nail down a reproduction yet, but could there possibly be a similar root cause as this issue?

**Comment by XuanWang-Amos** [comment]
@gibsondan We don't think your issue is the same with this one, can you help create a new issue so we can better track it?

**Comment by gibsondan** [comment]
@XuanWang-Amos  Got it, thanks - created a new issue here (with some more information, including an error message on the client): https://github.com/grpc/grpc/issues/34670
