### ISSUE TITLE
This problem occurs

### ISSUE THREAD

**Issue by opt-liang** [grpc/grpc#33102]
==3725==The signal is caused by a READ memory access.
==3725==Hint: address points to the zero page.
    #0 0x7fb946b9df  (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x97b9df)
    #1 0x7fb90c1007 in grpc_core::channelz::ChannelzRegistry::InternalRegister(grpc_core::channelz::BaseNode*) (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x5d1007)
    #2 0x7fb90b6a93 in grpc_core::channelz::BaseNode::BaseNode(grpc_core::channelz::BaseNode::EntityType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x5c6a93)
    #3 0x7fb90b869f in grpc_core::channelz::ServerNode::ServerNode(unsigned long) (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x5c869f)
    #4 0x7fb910a76f in grpc_core::Server::Server(grpc_channel_args const*) (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x61a76f)
    #5 0x7fb910a8fb in grpc_server_create (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x61a8fb)
    #6 0x7fb9055d2f in grpc::Server::Server(grpc::ChannelArguments*, std::shared_ptr<std::vector<std::unique_ptr<grpc::ServerCompletionQueue, std::default_delete<grpc::ServerCompletionQueue> >, std::allocator<std::unique_ptr<grpc::ServerCompletionQueue, std::default_delete<grpc::ServerCompletionQueue> > > > >, int, int, int, std::vector<std::shared_ptr<grpc::internal::ExternalConnectionAcceptorImpl>, std::allocator<std::shared_ptr<grpc::internal::ExternalConnectionAcceptorImpl> > >, grpc_server_config_fetcher*, grpc_resource_quota*, std::vector<std::unique_ptr<grpc::experimental::ServerInterceptorFactoryInterface, std::default_delete<grpc::experimental::ServerInterceptorFactoryInterface> >, std::allocator<std::unique_ptr<grpc::experimental::ServerInterceptorFactoryInterface, std::default_delete<grpc::experimental::ServerInterceptorFactoryInterface> > > >) (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x565d2f)
    #7 0x7fb90510b7 in grpc::ServerBuilder::BuildAndStart() (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x5610b7)
    #8 0x7fb8eb95e7 in SMTRPCServerImpl::RunServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short) ../SMTRPCServerImpl.cpp:95
    #9 0x7fb8e74047 in ServerImpl::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short) (/root/OPT_SC_Viewer/libSMTRPCServer.so.1+0x384047)
    #10 0x7fb8e72013 in SMTRPCServer::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short) ../SMTRPCServer.cpp:138
    #11 0x7fba34db8b in SCViewerEngineService::startService(unsigned short) ../SCViewerEngineService.cpp:1677
    #12 0x5577de142f in threadFunction() ../main.cpp:15
    #13 0x5577de19db in void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) /usr/aarch64-linux-gnu/include/c++/7/bits/invoke.h:60
    #14 0x5577de17a7 in std::__invoke_result<void (*)()>::type std::__invoke<void (*)()>(void (*&&)()) /usr/aarch64-linux-gnu/include/c++/7/bits/invoke.h:95
    #15 0x5577de1f4b in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/aarch64-linux-gnu/include/c++/7/thread:234
    #16 0x5577de1eff in std::thread::_Invoker<std::tuple<void (*)()> >::operator()() /usr/aarch64-linux-gnu/include/c++/7/thread:243
    #17 0x5577de1ecb in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() /usr/aarch64-linux-gnu/include/c++/7/thread:186
    #18 0x7fb9a5ab97  (/usr/lib/libstdc++.so.6+0xcab97)
    #19 0x7fb985cc9b  (/lib/libc.so.6+0x6cc9b)
    #20 0x7fb98b201b  (/lib/libc.so.6+0xc201b)

**Comment by opt-liang** [comment]
The problem with my program.

**Comment by opt-liang** [comment]
When my program encapsulates a GRPC library as a dynamic library, the program will jump to this location during startup. When the GRPC library is encapsulated as a static library, the program can run normally. It is unclear what caused this problem. Starting the GRPC library service alone is not a problem, but it will crash when starting other libraries with my main program.
Can you give me some advice
