### ISSUE TITLE
Bazel build failing due to `com_envoyproxy_protoc_gen_validate` SHA change

### ISSUE THREAD

**Issue by dbolduc** [grpc/grpc#33199]
We are seeing this error downstream in the `google-cloud-cpp` bazel builds:

```
WARNING: Download from https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 21a61b5cbc67a70e8dccd7595f6cccbdc83c8cfc7b7e575168bc51c324a61367 but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
ERROR: An error occurred during the fetch of repository 'com_envoyproxy_protoc_gen_validate':
   Traceback (most recent call last):
	File "/h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz] to /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/com_envoyproxy_protoc_gen_validate/temp7506162141866319839/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz: Checksum was 21a61b5cbc67a70e8dccd7595f6cccbdc83c8cfc7b7e575168bc51c324a61367 but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
ERROR: /workspace/WORKSPACE.bazel:32:10: fetching http_archive rule //external:com_envoyproxy_protoc_gen_validate: Traceback (most recent call last):
	File "/h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz] to /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/com_envoyproxy_protoc_gen_validate/temp7506162141866319839/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz: Checksum was 21a61b5cbc67a70e8dccd7595f6cccbdc83c8cfc7b7e575168bc51c324a61367 but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
ERROR: Error computing the main repository mapping: no such package '@com_envoyproxy_protoc_gen_validate//': java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz] to /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/com_envoyproxy_protoc_gen_validate/temp7506162141866319839/4694024279bdac52b77e22dc87808bd0fd732b69.tar.gz: Checksum was 21a61b5cbc67a70e8dccd7595f6cccbdc83c8cfc7b7e575168bc51c324a61367 but wanted 1e490b98005664d149b379a9529a6aa05932b8a11b76b4cd86f3d22d76346f47
```

Maybe we need to update this:

https://github.com/grpc/grpc/blob/4f445219ef0df391f2cc3293283ec6a473dff58a/bazel/grpc_deps.bzl#L494

to "21a61b5cbc67a70e8dccd7595f6cccbdc83c8cfc7b7e575168bc51c324a61367" ?

**Comment by dbolduc** [comment]
This was an upstream problem that got fixed. See: https://github.com/bufbuild/protoc-gen-validate/issues/878
