### ISSUE TITLE
pip install grpcio failed on intel cpu macbook

### ISSUE THREAD

**Issue by fengerzh** [grpc/grpc#33489]
```
pip install grpcio
pip install grpcio==1.49.1
```
all failed. cpu is intel. macos version: 13.0.1. gcc version:

```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
```

failed result:

```
      gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -I/opt/miniconda3/envs/pypy39/include/pypy3.9 -c /var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/tmp8p6opse2/a.c -o None/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/tmp8p6opse2/a.o
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/setup.py", line 540, in <module>
          setuptools.setup(
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/commands.py", line 284, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-u7_c358d/grpcio_1a006a47ad6f4668a3da6fc74502ec26/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

      [end of output]
```

**Comment by fengerzh** [comment]
I am pretty sure it's Apple's gcc problem.

After I `brew install gcc` and use brew gcc instead of Apple gcc, everything solved.

```
cd /usr/local/bin
ln -s gcc-11 gcc
```
