### ISSUE TITLE
Cannot use grpcio on manylinux2014_aarch64 (undefined symbol)

### ISSUE THREAD

**Issue by morambro** [grpc/grpc#33734]
### What version of gRPC and what language are you using?

Lang: Python 3.10
Version: 1.56.0

### What operating system (Linux, Windows,...) and version?

[quay.io/pypa/manylinux2014_aarch64](https://quay.io/repository/pypa/manylinux2014_aarch64/manifest/sha256:9d9cb1d47af9989b7b408e0a27700556cdb85b6243a67506d0f984c0fb24140f)

### What runtime / compiler are you using (e.g. python version or version of gcc)

```
[root@b59a58c303a9 /]# /opt/python/cp310-cp310/bin/python3 --version
Python 3.10.12
[root@b59a58c303a9 /]# gcc --version
gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
```

### What did you do?

From a [T2A instance](https://cloud.google.com/blog/products/compute/tau-t2a-is-first-compute-engine-vm-on-an-arm-chip):

```shell
MANYLINUX_AARCH64_IMAGE=quay.io/pypa/manylinux2014_aarch64@sha256:9d9cb1d47af9989b7b408e0a27700556cdb85b6243a67506d0f984c0fb24140f
sudo docker run -it "${MANYLINUX_AARCH64_IMAGE}" bash
[root@b59a58c303a9 /]# /opt/python/cp310-cp310/bin/python3 -m pip install grpcio==1.56.0
Collecting grpcio==1.56.0
  Obtaining dependency information for grpcio==1.56.0 from https://files.pythonhosted.org/packages/26/cb/a2debcb7fe7a6f90f27d589facb85aa69e8ce39660e8faff2775911f58ee/grpcio-1.56.0-cp310-cp310-manylinux_2_17_aarch64.whl.metadata
  Downloading grpcio-1.56.0-cp310-cp310-manylinux_2_17_aarch64.whl.metadata (4.0 kB)
Downloading grpcio-1.56.0-cp310-cp310-manylinux_2_17_aarch64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 45.5 MB/s eta 0:00:00
Installing collected packages: grpcio
Successfully installed grpcio-1.56.0
root@b59a58c303a9 /]# /opt/python/cp310-cp310/bin/python3 -c "import grpc"
```

### What did you expect to see?

No errors given that the binary wheel is tagged with `manylinux_2_17_aarch64`.

This seems related to #30218.

### What did you see instead?

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/cp310-cp310/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/opt/python/cp310-cp310/lib/python3.10/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: /opt/python/cp310-cp310/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-aarch64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE
```

### Anything else we should know about your project / environment?

```shell
[root@b59a58c303a9 /]# ldd  /opt/python/cp310-cp310/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-aarch64-linux-gnu.so 
        linux-vdso.so.1 =>  (0x0000ffffb38af000)
        librt.so.1 => /lib64/librt.so.1 (0x0000ffffb2e66000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffffb2e31000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x0000ffffb2d0a000)
        libm.so.6 => /lib64/libm.so.6 (0x0000ffffb2c59000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffffb2ad3000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffb3881000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000ffffb2aa2000)
[root@b59a58c303a9 /]# strings /lib64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.17
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by h-vetinari** [comment]
There are two times the manylinux version becomes relevant here - at build time, and at runtime. You cannot directly change how the wheels are built (though it's probably worth considering moving to manylinux_2_28 in any case), but an you try what happens when you use a newer manylinux image to run, e.g. quay.io/pypa/manylinux_2_28_aarch64?

**Comment by gnossen** [comment]
@jtattermusch Can you take a look since you were the original author of the Python aarch64 build?

**Comment by cpungasc** [comment]
I got an identical error on `Python 3.9`. Tried multiple `grpcio` versions starting from 1.46.3 to the latest version, all of them fail on a native `centOS 7 aarch64`.

Any pointers or plans to reopen this issue, please?
