### ISSUE TITLE
ODR violation between the libgpr.so and libgrpc.so

### ISSUE THREAD

**Issue by qazwsxedcrfvtg14** [grpc/grpc#33962]
### What version of gRPC and what language are you using?
1.43.0, but I think we will have the same issue on the ToT.

### What operating system (Linux, Windows,...) and version?
gLinux and inside the ChromeOS chroot.

### What runtime / compiler are you using (e.g. python version or version of gcc)
ChromeOS Toolchain with this ebuild file:
[net-libs/grpc](https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/third_party/chromiumos-overlay/net-libs/grpc/)
It will build grpc with cmake.

### What did you do?
We built the ASAN version of gRPC shared libraries, after running the binary that linked to the grpc.so, we will see the ODR violations.

### What did you expect to see?
No ODR violations.

### What did you see instead?

```
 * ASAN error detected:
 * =================================================================
 * ==57==ERROR: AddressSanitizer: odr-violation (0x7f8d8449a240):
 *   [1] size=24 'google_protobuf_Any_msginit' /build/amd64-generic/tmp/portage/net-libs/grpc-1.43.0-r6/work/grpc-1.43.0/src/core/ext/upb-generated/google/protobuf/any.upb.c
 *   [2] size=24 'google_protobuf_Any_msginit' /build/amd64-generic/tmp/portage/net-libs/grpc-1.43.0-r6/work/grpc-1.43.0/src/core/ext/upb-generated/google/protobuf/any.upb.c
 * These globals were registered at these points:
 *   [1]:
 *     #0 0x5614c84c078a in __asan_register_globals ??:0:0
 *     #1 0x7f8d841ae88e in asan.module_ctor any.upb.c:?
 *     #2 0x7f8d85741dae in call_init.part.0 /var/tmp/portage/cross-x86_64-cros-linux-gnu/glibc-2.35-r22/work/glibc-2.35/elf/dl-init.c:70:3
 *     #3 0x7f8d85741ea8 in call_init /var/tmp/portage/cross-x86_64-cros-linux-gnu/glibc-2.35-r22/work/glibc-2.35/elf/dl-init.c:33:6
 *     #4 0x7f8d85741ea8 in _dl_init /var/tmp/portage/cross-x86_64-cros-linux-gnu/glibc-2.35-r22/work/glibc-2.35/elf/dl-init.c:117:5
 *     #5 0x7f8d857592f9 in _dl_start_user ??:0:0
 * 
 *   [2]:
 *     #0 0x5614c84c078a in __asan_register_globals ??:0:0
 *     #1 0x7f8d84e0face in Thread ??:?
 *     #2 0x7f8d85741dae in call_init.part.0 /var/tmp/portage/cross-x86_64-cros-linux-gnu/glibc-2.35-r22/work/glibc-2.35/elf/dl-init.c:70:3
 *     #3 0x7f8d85741ea8 in call_init /var/tmp/portage/cross-x86_64-cros-linux-gnu/glibc-2.35-r22/work/glibc-2.35/elf/dl-init.c:33:6
 *     #4 0x7f8d85741ea8 in _dl_init /var/tmp/portage/cross-x86_64-cros-linux-gnu/glibc-2.35-r22/work/glibc-2.35/elf/dl-init.c:117:5
 *     #5 0x7f8d857592f9 in _dl_start_user ??:0:0
 * 
```

### Anything else we should know about your project / environment?

```
$ ldd /build/amd64-generic/usr/lib64/libgrpc++.so.1.43
        linux-vdso.so.1 (0x00007fff953b8000)
        libgrpc.so.21 => /usr/lib64/libgrpc.so.21 (0x00007eff2ec00000)
        libabsl_raw_hash_set.so.2301.0.0 => /usr/lib64/libabsl_raw_hash_set.so.2301.0.0 (0x00007eff2f0c7000)
        libabsl_hash.so.2301.0.0 => /usr/lib64/libabsl_hash.so.2301.0.0 (0x00007eff2f0c3000)
        libabsl_statusor.so.2301.0.0 => /usr/lib64/libabsl_statusor.so.2301.0.0 (0x00007eff2f0be000)
        libgpr.so.21 => /usr/lib64/libgpr.so.21 (0x00007eff2f0a7000)
        libupb.so.21 => /usr/lib64/libupb.so.21 (0x00007eff2f086000)
        libabsl_status.so.2301.0.0 => /usr/lib64/libabsl_status.so.2301.0.0 (0x00007eff2f07b000)
        libabsl_synchronization.so.2301.0.0 => /usr/lib64/libabsl_synchronization.so.2301.0.0 (0x00007eff2f069000)
        libabsl_time.so.2301.0.0 => /usr/lib64/libabsl_time.so.2301.0.0 (0x00007eff2ebee000)
        libabsl_strings.so.2301.0.0 => /usr/lib64/libabsl_strings.so.2301.0.0 (0x00007eff2ebd1000)
        libabsl_raw_logging_internal.so.2301.0.0 => /usr/lib64/libabsl_raw_logging_internal.so.2301.0.0 (0x00007eff2ebcd000)
        libc++.so.1 => /usr/lib64/libc++.so.1 (0x00007eff2ead0000)
        libc++abi.so.1 => /usr/lib64/libc++abi.so.1 (0x00007eff2ea90000)
        libc.so.6 => /lib64/libc.so.6 (0x00007eff2e8a5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007eff2f26a000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007eff2e88a000)
        libcares.so.2 => /usr/lib64/libcares.so.2 (0x00007eff2e874000)
        libm.so.6 => /lib64/libm.so.6 (0x00007eff2e7d8000)
        libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007eff2e748000)
        libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007eff2e400000)
        libaddress_sorting.so.21 => /usr/lib64/libaddress_sorting.so.21 (0x00007eff2e744000)
        libre2.so.10 => /usr/lib64/libre2.so.10 (0x00007eff2e6e5000)
        libabsl_cord.so.2301.0.0 => /usr/lib64/libabsl_cord.so.2301.0.0 (0x00007eff2e6c9000)
        libabsl_str_format_internal.so.2301.0.0 => /usr/lib64/libabsl_str_format_internal.so.2301.0.0 (0x00007eff2e6af000)
        libabsl_time_zone.so.2301.0.0 => /usr/lib64/libabsl_time_zone.so.2301.0.0 (0x00007eff2e3dd000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007eff2e3c8000)
        libabsl_city.so.2301.0.0 => /usr/lib64/libabsl_city.so.2301.0.0 (0x00007eff2e3c4000)
        libabsl_low_level_hash.so.2301.0.0 => /usr/lib64/libabsl_low_level_hash.so.2301.0.0 (0x00007eff2e3c1000)
        libabsl_spinlock_wait.so.2301.0.0 => /usr/lib64/libabsl_spinlock_wait.so.2301.0.0 (0x00007eff2e3be000)
        libabsl_cordz_info.so.2301.0.0 => /usr/lib64/libabsl_cordz_info.so.2301.0.0 (0x00007eff2e3b5000)
        libabsl_strerror.so.2301.0.0 => /usr/lib64/libabsl_strerror.so.2301.0.0 (0x00007eff2e3b1000)
        libabsl_graphcycles_internal.so.2301.0.0 => /usr/lib64/libabsl_graphcycles_internal.so.2301.0.0 (0x00007eff2e3aa000)
        libabsl_stacktrace.so.2301.0.0 => /usr/lib64/libabsl_stacktrace.so.2301.0.0 (0x00007eff2e3a6000)
        libabsl_symbolize.so.2301.0.0 => /usr/lib64/libabsl_symbolize.so.2301.0.0 (0x00007eff2e39e000)
        libabsl_malloc_internal.so.2301.0.0 => /usr/lib64/libabsl_malloc_internal.so.2301.0.0 (0x00007eff2e396000)
        libabsl_base.so.2301.0.0 => /usr/lib64/libabsl_base.so.2301.0.0 (0x00007eff2e391000)
        libabsl_int128.so.2301.0.0 => /usr/lib64/libabsl_int128.so.2301.0.0 (0x00007eff2e389000)
        libabsl_strings_internal.so.2301.0.0 => /usr/lib64/libabsl_strings_internal.so.2301.0.0 (0x00007eff2e385000)
        libabsl_cord_internal.so.2301.0.0 => /usr/lib64/libabsl_cord_internal.so.2301.0.0 (0x00007eff2e36c000)
        libabsl_crc_cord_state.so.2301.0.0 => /usr/lib64/libabsl_crc_cord_state.so.2301.0.0 (0x00007eff2e363000)
        libabsl_cordz_functions.so.2301.0.0 => /usr/lib64/libabsl_cordz_functions.so.2301.0.0 (0x00007eff2e360000)
        libabsl_cordz_handle.so.2301.0.0 => /usr/lib64/libabsl_cordz_handle.so.2301.0.0 (0x00007eff2e35b000)
        libabsl_debugging_internal.so.2301.0.0 => /usr/lib64/libabsl_debugging_internal.so.2301.0.0 (0x00007eff2e355000)
        libabsl_demangle_internal.so.2301.0.0 => /usr/lib64/libabsl_demangle_internal.so.2301.0.0 (0x00007eff2e34b000)
        libabsl_throw_delegate.so.2301.0.0 => /usr/lib64/libabsl_throw_delegate.so.2301.0.0 (0x00007eff2e343000)
        libabsl_crc32c.so.2301.0.0 => /usr/lib64/libabsl_crc32c.so.2301.0.0 (0x00007eff2e33e000)
        libabsl_exponential_biased.so.2301.0.0 => /usr/lib64/libabsl_exponential_biased.so.2301.0.0 (0x00007eff2e33b000)
        libabsl_crc_internal.so.2301.0.0 => /usr/lib64/libabsl_crc_internal.so.2301.0.0 (0x00007eff2e335000)
$ ldd /build/amd64-generic/usr/lib64/libgrpc.so.21.0.0
        linux-vdso.so.1 (0x00007ffe075e9000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007fbc0bbd2000)
        libcares.so.2 => /usr/lib64/libcares.so.2 (0x00007fbc0bbbc000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fbc0bb20000)
        libabsl_statusor.so.2301.0.0 => /usr/lib64/libabsl_statusor.so.2301.0.0 (0x00007fbc0bb1b000)
        libgpr.so.21 => /usr/lib64/libgpr.so.21 (0x00007fbc0b1e9000)
        libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007fbc0b15b000)
        libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007fbc0ae00000)
        libaddress_sorting.so.21 => /usr/lib64/libaddress_sorting.so.21 (0x00007fbc0bb15000)
        libre2.so.10 => /usr/lib64/libre2.so.10 (0x00007fbc0b0fc000)
        libabsl_hash.so.2301.0.0 => /usr/lib64/libabsl_hash.so.2301.0.0 (0x00007fbc0bb11000)
        libupb.so.21 => /usr/lib64/libupb.so.21 (0x00007fbc0b0dd000)
        libabsl_status.so.2301.0.0 => /usr/lib64/libabsl_status.so.2301.0.0 (0x00007fbc0b0d2000)
        libabsl_cord.so.2301.0.0 => /usr/lib64/libabsl_cord.so.2301.0.0 (0x00007fbc0b0b6000)
        libabsl_str_format_internal.so.2301.0.0 => /usr/lib64/libabsl_str_format_internal.so.2301.0.0 (0x00007fbc0ade6000)
        libabsl_synchronization.so.2301.0.0 => /usr/lib64/libabsl_synchronization.so.2301.0.0 (0x00007fbc0add4000)
        libabsl_time.so.2301.0.0 => /usr/lib64/libabsl_time.so.2301.0.0 (0x00007fbc0adc2000)
        libabsl_strings.so.2301.0.0 => /usr/lib64/libabsl_strings.so.2301.0.0 (0x00007fbc0ada5000)
        libabsl_time_zone.so.2301.0.0 => /usr/lib64/libabsl_time_zone.so.2301.0.0 (0x00007fbc0ad84000)
        libc++.so.1 => /usr/lib64/libc++.so.1 (0x00007fbc0ac89000)
        libc++abi.so.1 => /usr/lib64/libc++abi.so.1 (0x00007fbc0ac49000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbc0aa5e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbc0bbfd000)
        libabsl_spinlock_wait.so.2301.0.0 => /usr/lib64/libabsl_spinlock_wait.so.2301.0.0 (0x00007fbc0bb0a000)
        libabsl_raw_logging_internal.so.2301.0.0 => /usr/lib64/libabsl_raw_logging_internal.so.2301.0.0 (0x00007fbc0b0b2000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fbc0aa49000)
        libabsl_cordz_info.so.2301.0.0 => /usr/lib64/libabsl_cordz_info.so.2301.0.0 (0x00007fbc0aa42000)
        libabsl_city.so.2301.0.0 => /usr/lib64/libabsl_city.so.2301.0.0 (0x00007fbc0aa3e000)
        libabsl_low_level_hash.so.2301.0.0 => /usr/lib64/libabsl_low_level_hash.so.2301.0.0 (0x00007fbc0b0af000)
        libabsl_strerror.so.2301.0.0 => /usr/lib64/libabsl_strerror.so.2301.0.0 (0x00007fbc0aa3a000)
        libabsl_cord_internal.so.2301.0.0 => /usr/lib64/libabsl_cord_internal.so.2301.0.0 (0x00007fbc0aa1f000)
        libabsl_crc_cord_state.so.2301.0.0 => /usr/lib64/libabsl_crc_cord_state.so.2301.0.0 (0x00007fbc0aa18000)
        libabsl_cordz_functions.so.2301.0.0 => /usr/lib64/libabsl_cordz_functions.so.2301.0.0 (0x00007fbc0aa15000)
        libabsl_int128.so.2301.0.0 => /usr/lib64/libabsl_int128.so.2301.0.0 (0x00007fbc0aa0d000)
        libabsl_graphcycles_internal.so.2301.0.0 => /usr/lib64/libabsl_graphcycles_internal.so.2301.0.0 (0x00007fbc0aa06000)
        libabsl_stacktrace.so.2301.0.0 => /usr/lib64/libabsl_stacktrace.so.2301.0.0 (0x00007fbc0aa00000)
        libabsl_symbolize.so.2301.0.0 => /usr/lib64/libabsl_symbolize.so.2301.0.0 (0x00007fbc0a9f8000)
        libabsl_malloc_internal.so.2301.0.0 => /usr/lib64/libabsl_malloc_internal.so.2301.0.0 (0x00007fbc0a9f2000)
        libabsl_base.so.2301.0.0 => /usr/lib64/libabsl_base.so.2301.0.0 (0x00007fbc0a9ed000)
        libabsl_strings_internal.so.2301.0.0 => /usr/lib64/libabsl_strings_internal.so.2301.0.0 (0x00007fbc0a9e9000)
        libabsl_cordz_handle.so.2301.0.0 => /usr/lib64/libabsl_cordz_handle.so.2301.0.0 (0x00007fbc0a9e2000)
        libabsl_throw_delegate.so.2301.0.0 => /usr/lib64/libabsl_throw_delegate.so.2301.0.0 (0x00007fbc0a9dc000)
        libabsl_crc32c.so.2301.0.0 => /usr/lib64/libabsl_crc32c.so.2301.0.0 (0x00007fbc0a9d7000)
        libabsl_exponential_biased.so.2301.0.0 => /usr/lib64/libabsl_exponential_biased.so.2301.0.0 (0x00007fbc0a9d4000)
        libabsl_debugging_internal.so.2301.0.0 => /usr/lib64/libabsl_debugging_internal.so.2301.0.0 (0x00007fbc0a9ce000)
        libabsl_demangle_internal.so.2301.0.0 => /usr/lib64/libabsl_demangle_internal.so.2301.0.0 (0x00007fbc0a9c2000)
        libabsl_crc_internal.so.2301.0.0 => /usr/lib64/libabsl_crc_internal.so.2301.0.0 (0x00007fbc0a9bc000)
$ ldd /build/amd64-generic/usr/lib64/libgpr.so
        linux-vdso.so.1 (0x00007ffc6353f000)
        libabsl_status.so.2301.0.0 => /usr/lib64/libabsl_status.so.2301.0.0 (0x00007fc6fd310000)
        libabsl_cord.so.2301.0.0 => /usr/lib64/libabsl_cord.so.2301.0.0 (0x00007fc6fd2f4000)
        libupb.so.21 => /usr/lib64/libupb.so.21 (0x00007fc6fd2d5000)
        libabsl_cordz_info.so.2301.0.0 => /usr/lib64/libabsl_cordz_info.so.2301.0.0 (0x00007fc6fd2ce000)
        libabsl_synchronization.so.2301.0.0 => /usr/lib64/libabsl_synchronization.so.2301.0.0 (0x00007fc6fd2bc000)
        libabsl_time.so.2301.0.0 => /usr/lib64/libabsl_time.so.2301.0.0 (0x00007fc6fd2a8000)
        libabsl_str_format_internal.so.2301.0.0 => /usr/lib64/libabsl_str_format_internal.so.2301.0.0 (0x00007fc6fd28e000)
        libabsl_strings.so.2301.0.0 => /usr/lib64/libabsl_strings.so.2301.0.0 (0x00007fc6fd271000)
        libabsl_raw_logging_internal.so.2301.0.0 => /usr/lib64/libabsl_raw_logging_internal.so.2301.0.0 (0x00007fc6fd26d000)
        libabsl_spinlock_wait.so.2301.0.0 => /usr/lib64/libabsl_spinlock_wait.so.2301.0.0 (0x00007fc6fd26a000)
        libc++.so.1 => /usr/lib64/libc++.so.1 (0x00007fc6fd16f000)
        libc++abi.so.1 => /usr/lib64/libc++abi.so.1 (0x00007fc6fd12d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc6fcf42000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc6fd356000)
        libabsl_strerror.so.2301.0.0 => /usr/lib64/libabsl_strerror.so.2301.0.0 (0x00007fc6fcf3e000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fc6fcf29000)
        libabsl_cord_internal.so.2301.0.0 => /usr/lib64/libabsl_cord_internal.so.2301.0.0 (0x00007fc6fcf10000)
        libabsl_crc_cord_state.so.2301.0.0 => /usr/lib64/libabsl_crc_cord_state.so.2301.0.0 (0x00007fc6fcf09000)
        libabsl_cordz_functions.so.2301.0.0 => /usr/lib64/libabsl_cordz_functions.so.2301.0.0 (0x00007fc6fcf04000)
        libabsl_cordz_handle.so.2301.0.0 => /usr/lib64/libabsl_cordz_handle.so.2301.0.0 (0x00007fc6fceff000)
        libabsl_stacktrace.so.2301.0.0 => /usr/lib64/libabsl_stacktrace.so.2301.0.0 (0x00007fc6fcefb000)
        libabsl_base.so.2301.0.0 => /usr/lib64/libabsl_base.so.2301.0.0 (0x00007fc6fcef6000)
        libabsl_graphcycles_internal.so.2301.0.0 => /usr/lib64/libabsl_graphcycles_internal.so.2301.0.0 (0x00007fc6fceef000)
        libabsl_symbolize.so.2301.0.0 => /usr/lib64/libabsl_symbolize.so.2301.0.0 (0x00007fc6fcee5000)
        libabsl_malloc_internal.so.2301.0.0 => /usr/lib64/libabsl_malloc_internal.so.2301.0.0 (0x00007fc6fcedf000)
        libabsl_time_zone.so.2301.0.0 => /usr/lib64/libabsl_time_zone.so.2301.0.0 (0x00007fc6fcebe000)
        libabsl_int128.so.2301.0.0 => /usr/lib64/libabsl_int128.so.2301.0.0 (0x00007fc6fceb6000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc6fce1a000)
        libabsl_strings_internal.so.2301.0.0 => /usr/lib64/libabsl_strings_internal.so.2301.0.0 (0x00007fc6fce14000)
        libabsl_throw_delegate.so.2301.0.0 => /usr/lib64/libabsl_throw_delegate.so.2301.0.0 (0x00007fc6fce0e000)
        libabsl_crc32c.so.2301.0.0 => /usr/lib64/libabsl_crc32c.so.2301.0.0 (0x00007fc6fce09000)
        libabsl_exponential_biased.so.2301.0.0 => /usr/lib64/libabsl_exponential_biased.so.2301.0.0 (0x00007fc6fce06000)
        libabsl_debugging_internal.so.2301.0.0 => /usr/lib64/libabsl_debugging_internal.so.2301.0.0 (0x00007fc6fce00000)
        libabsl_demangle_internal.so.2301.0.0 => /usr/lib64/libabsl_demangle_internal.so.2301.0.0 (0x00007fc6fcdf4000)
        libabsl_crc_internal.so.2301.0.0 => /usr/lib64/libabsl_crc_internal.so.2301.0.0 (0x00007fc6fcdee000)
$ ldd /build/amd64-generic/usr/lib64/libupb.so
        linux-vdso.so.1 (0x00007ffd4fbc1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f152d066000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f152d2a1000)
```

After some testing, we figured out that moving those files into the libupb.so will resolve this issue.
https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4741457/4/net-libs/grpc/files/grpc-1.43.0-Fix-proto-ODR-issue.patch

I'm not very familiar with the grpc code base, so I'm not sure if this is the best way to fix this issue or not.

Thanks.

**Comment by eugeneo** [comment]
@veblush seems to be CMake issue. Is that file generated?

**Comment by veblush** [comment]
We've changed how upb generated source files are included in the gRPC in the past so it'd be useful to try the recent version of gRPC like 1.57.0. Would you do this?

**Comment by Allen-Webb** [comment]
I can check the next time we upgrade GPRC.

**Comment by igor-anferov** [comment]
I experience the same problem with the most recent version — 1.59.1
