### ISSUE TITLE
`StatusCode.UNKNOWN Stream removed` when it should be unavailable

### ISSUE THREAD

**Issue by juandelacruz-calvo** [grpc/grpc#34076]
### What version of gRPC and what language are you using?
1.56.2 and 1.57.0

### What operating system (Linux, Windows,...) and version?
Linux GCP

### What runtime / compiler are you using (e.g. python version or version of gcc)
3.8.13

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
We have a high availability Kubernetes cluster using Envoy as gRPC proxy since we use SRV records on our DNS. gRPC has some issues working with SRV records using the Python client.

We recently updated from `1.48.1` to both `1.57.0 and `1.56.2` and in both libraries we are seen a new behaviour which is causing some issues.

When there is high load and one of our upstream services does a Kubernetes deployment, while new pods are spinning up and old pods are dying, Envoy starts to respond `unavailable`. With the version `1.48.1` these unavailable calls would tell the gRPC that the client was no longer available and it would open a new connection, but with the new versions gRPC client doesn't process the `unavailable` response and instead throws an unrecoverable error.

From here the only thing we can do is restart Envoy to mitigate the issue
>
### What did you expect to see?
We would expect to see an unavailable error in gRPC and create a new connection from Envoy

### What did you see instead?

```
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 438, in result
    raise self
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_interceptor.py", line 343, in with_call
    return self._with_call(
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 438, in result
    raise self
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 1178, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/usr/src/app/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-08-16T10:21:12.913725397+00:00"}"
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Its happening with high load around 50 RPS

**Comment by juandelacruz-calvo** [comment]
Could it have something to do with this issue? https://github.com/grpc/grpc/issues/33935#ref-pullrequest-1825316991

**Comment by krishna4git88** [comment]
Any update on this issue ?

**Comment by XuanWang-Amos** [comment]
Sorry for the delay, I'm not sure if it's related to the reference issue at this point. For that issue, we're getting 401 status and mapped it to `StatusCode.UNKNOWN`, but in your log I don't see status other than `UNKNOWN`, there should be more logs above, can you share us the full log?

And could you please share the logs from 1.48.1 too?

**Comment by krishna4git88** [comment]
Below is the exceptions I'm receiving,


E0922 14:33:43.878000000 25760 src/core/ext/transport/chttp2/transport/hpack_parser.cc:993] Error parsing 'content-type' metadata: invalid value
Traceback (most recent call last):
  File "\Python\Python311\site-packages\google\api_core\grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python\Python311\Lib\site-packages\grpc\_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python\Python311\Lib\site-packages\grpc\_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-09-22T18:33:43.8935151+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python testing\questionanswer_langchain.py", line 113, in <module>
    index = mengine.create_index(
            ^^^^^^^^^^^^^^^^^^^^^
  File "c:\python testing\utils\matching_engine_utils.py", line 77, in create_index
    index = self.get_index()
            ^^^^^^^^^^^^^^^^
  File "c:\python testing\utils\matching_engine_utils.py", line 34, in get_index
    page_result = self.index_client.list_indexes(request=request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\Python311\site-packages\google\cloud\aiplatform_v1\services\index_service\client.py", line 810, in list_indexes
    response = rpc(
               ^^^^
  File "Python\Python311\site-packages\google\api_core\gapic_v1\method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\Python311\site-packages\google\api_core\grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None Stream removed

**Comment by superaldo** [comment]
Same here, any update? I have a simple script on python3 for update data in firestore
 
E1005 15:18:30.894443949 1838275 hpack_parser.cc:999]                  Error parsing 'content-type' metadata: invalid value
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-10-05T15:18:30.89573854+00:00", grpc_status:2, grpc_message:"Stream removed"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/coinpaprika/main.py", line 25, in <module>
    update_document('prices', 'coins', {'algo_pen.value': round(algo_pen['price'], 3),
  File "/usr/local/bin/coinpaprika/main.py", line 22, in update_document
    doc_ref.update(update_data)
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/firestore_v1/document.py", line 325, in update
    write_results = batch.commit(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/firestore_v1/batch.py", line 59, in commit
    commit_response = self._client._firestore_api.commit(
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/firestore_v1/services/firestore/client.py", line 1125, in commit
    response = rpc(
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/grpc_helpers.py", line 77, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None Stream removed

**Comment by nanonyme** [comment]
Only traces I could find where the code is emitting "Stream removed" are https://github.com/grpc/grpc/blob/7fabc61f07be423cccda79463f30dc390b83ac9c/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2207 C++ code where socket has been closed for both reading and writing and code wants to bubble up an error.

**Comment by nanonyme** [comment]
The classification as Python is most likely wrong. I expect this to be a bug in grpc core.

**Comment by gnossen** [comment]
Sorry for the delay on this one. I think it's quite likely that this issue _is_ related to https://gist.github.com/juandelacruz-calvo/3edcf5ffe58970150cd41747e63ee942 . The issue there was that nginx was returning the wrong MIME type in case of errors (`text/html` instead of `application/grpc`). The logs above look like they cut off the interesting bit -- the raw HTTP response from Envoy. If we could confirm whether that's happening here, that'd be great.

@ctiller @yashykt In parallel, could we please work on being more permissive with `Content-Type` in HTTP error mappings based on [this doc](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md). This is clearly a common pattern for HTTP middleware.

**Comment by juandelacruz-calvo** [comment]
We ended up moving our egress gRPC traffic to use HAProxy as proxy since it had a few perks that were not implemented yet in Envoy, like SRV resolution. For what I could see, we couldn't find the same pattern from that ticket. I did check on that ticket before. Unfortunately, given that these were production systems, we are unable to test again without a significant effort

**Comment by RenaLu** [comment]
Hi there, any updates on the issue? I've been hitting this error while using `aiplatform.gapic.PredictionServiceClient`

**Comment by ergeng2001** [comment]
File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:10.0.2.130:50051: recvmsg:Connection reset by peer"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:10.0.2.130:50051: recvmsg:Connection reset by peer {grpc_status:14, created_time:"2025-05-27T15:07:01.0021999+08:00"}"    I have a similar problem here, that is, in distributed training, 10.0.2.130:50051 cannot be recognized

**Comment by sergiitk** [comment]
@pawbhard I think we need to re-verify and re-triage this. 

Internal ref on the Python side: b/321658525.

**Comment by sergiitk** [comment]
cc @sreenithi @asheshvidyut
