### ISSUE TITLE
xds-protos _pb2 file need to be regenerated

### ISSUE THREAD

**Issue by newswangerd** [grpc/grpc#34093]
This report is specifically for the xds-protos package

### What version of gRPC and what language are you using?
```
xds-protos==0.0.11
protobuf==4.24.0
grpcio==1.57.0
grpcio-tools==1.57.0
```

### What operating system (Linux, Windows,...) and version?
`quay.io/centos/centos:stream9` container image

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.0

### What did you do?
Running a grpc server that implements envoy.service.auth.v3.external_auth_pb2_grpc.AuthorizationServicer from the xds-protos module.

### What did you expect to see?
Server should start up

### What did you see instead?
I get this error message saying that the `generated code is out of date and must be regenerated with protoc >= 3.19.0`.

Note: setting `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` as the error message suggests works, but I would rather not use the python implementation.

```
Traceback (most recent call last):
  File "/opt/aap_gateway/aap_gateway/manage.py", line 22, in <module>
    main()
  File "/opt/aap_gateway/aap_gateway/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django_grpc/management/commands/grpcserver.py", line 23, in handle
    self._serve_async(**options)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django_grpc/management/commands/grpcserver.py", line 55, in _serve_async
    server = create_server(max_workers, port)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django_grpc/utils.py", line 42, in create_server
    add_servicers(server, servicers_list)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django_grpc/utils.py", line 77, in add_servicers
    callback = import_string(path)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/aap_gateway/aap_gateway/aap_gateway_api/proxy/control_plane.py", line 10, in <module>
    from envoy.config.core.v3.base_pb2 import HeaderValueOption, HeaderValue
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/envoy/config/core/v3/base_pb2.py", line 15, in <module>
    from envoy.config.core.v3 import address_pb2 as envoy_dot_config_dot_core_dot_v3_dot_address__pb2
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/envoy/config/core/v3/address_pb2.py", line 14, in <module>
    from envoy.config.core.v3 import socket_option_pb2 as envoy_dot_config_dot_core_dot_v3_dot_socket__option__pb2
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/envoy/config/core/v3/socket_option_pb2.py", line 14, in <module>
    from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/udpa/annotations/status_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/opt/aap_gateway/venv/lib64/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by gnossen** [comment]
Will be resolved by https://github.com/grpc/grpc/pull/33797 in the next release.
