### ISSUE TITLE
"Resource temporarily unavailable" error when running sys.exit() after closing async channel

### ISSUE THREAD

**Issue by arvidfm** [grpc/grpc#34139]
### What version of gRPC and what language are you using?
Python 3.11 with gRPC 1.57.0

### What operating system (Linux, Windows,...) and version?
Arch Linux, kernel 6.4.10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11

### What did you do?
Ran `sys.exit(0)` immediately after a completed asynchronous (`grpc.aio`) stream-stream gRPC call.

See MWE here for code: https://github.com/arvidfm/grpc_mwe

### What did you expect to see?
A clean shutdown.

### What did you see instead?
The following error:

```
Exception in callback PollerCompletionQueue._handle_events(<_UnixSelecto...e debug=False>)()
handle: <Handle PollerCompletionQueue._handle_events(<_UnixSelecto...e debug=False>)()>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/x/Documents/git/grpc_mwe/mwe.py", line 37, in main
    await run_client()
  File "/home/x/Documents/git/grpc_mwe/mwe.py", line 29, in run_client
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

### Anything else we should know about your project / environment?
MWE: https://github.com/arvidfm/grpc_mwe

The error only seems to happen if explicitly calling `sys.exit()` after the gRPC call (even outside the `with` block for the channel); letting the program exit by simply reaching the end of the code does not cause the error to be printed.

In my case, this is annoying because I'm using gRPC as part of a CLI application, where a command may run a gRPC request before immediately exiting. Additionally, it's the CLI framework I am using (`asyncclick`) which runs the `sys.exit()` call when a command finishes. What this effectively means is that unless I add an extra sleep somewhere to work around the race condition, the user will see a huge stack trace printed to the terminal half of the time when running a command, even though the command itself executed successfully.

The repro rate is about 50% on my system. Seems to be a race condition where the `PollerCompletionQueue._handle_events` reader is not unregistered from the event loop in time.

What should be happening is:
* `AioChannel.__dealloc__` starts the shutdown process: https://github.com/grpc/grpc/blob/v1.57.0/src/python/grpcio/grpc/_cython/_cygrpc/aio/channel.pyx.pxi#L53-L54
* `_actual_aio_shutdown` calls the `shutdown` method of the completion queue: https://github.com/grpc/grpc/blob/v1.57.0/src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi#L79
* `PollerCompletionQueue.shutdown` calls `_BoundEventLoop.close` which removes the reader from the event loop: https://github.com/grpc/grpc/blob/v1.57.0/src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi#L69

But perhaps `__dealloc__` is sometimes not being called before asyncio starts shutting down due to the exit signal, causing the reader to run even though the socket has been closed already.

**Comment by asheshvidyut** [comment]
Hey @ecryth ,

Apologies for late response.

I have tried to repro this issue and this looks resolved in the latest version of gRPC Python [1.83.0rc1](https://pypi.org/project/grpcio/1.83.0rc1)

Hence I am closing this issue. 

Please feel free to reopen in case there is some more things needed from gRPC Python team.

Thanks.
