### ISSUE TITLE
Cannot build repo from source. GPR_ASSERT(h->count) in histogram.c:215:17

### ISSUE THREAD

**Issue by Andyccs** [grpc/grpc#3430]
I tried to build this project from source in MAC OS using `make` command. I get the following error:

```
src/core/support/histogram.c:215:17: error: implicit conversion turns floating-point number into integer: 'double' to '_Bool' [-Werror,-Wfloat-conversion]
  GPR_ASSERT(h->count);
```

I do not understand anything about this project, but it turns out that if I remove this line or I change it to `h->count != 0`, the build will continue without any error.

I attach the log for your reference:

```
Andy-Chongs-MacBook-Pro:grpc andyccs$ make clean
[CLEAN]   Cleaning build directories.
Andy-Chongs-MacBook-Pro:grpc andyccs$ make 
[MAKE]    Generating libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[MAKE]    Generating libs/opt/pkgconfig/gpr.pc
[C]       Compiling src/core/support/alloc.c
[C]       Compiling src/core/support/cmdline.c
[C]       Compiling src/core/support/cpu_iphone.c
[C]       Compiling src/core/support/cpu_linux.c
[C]       Compiling src/core/support/cpu_posix.c
[C]       Compiling src/core/support/cpu_windows.c
[C]       Compiling src/core/support/env_linux.c
[C]       Compiling src/core/support/env_posix.c
[C]       Compiling src/core/support/env_win32.c
[C]       Compiling src/core/support/file.c
[C]       Compiling src/core/support/file_posix.c
[C]       Compiling src/core/support/file_win32.c
[C]       Compiling src/core/support/histogram.c
src/core/support/histogram.c:215:17: error: implicit conversion turns floating-point number into integer: 'double' to '_Bool' [-Werror,-Wfloat-conversion]
  GPR_ASSERT(h->count);
  ~~~~~~~~~~~~~~^~~~~~
include/grpc/support/log.h:98:11: note: expanded from macro 'GPR_ASSERT'
    if (!(x)) {                                       \
          ^
1 error generated.
make: *** [objs/opt/src/core/support/histogram.o] Error 1
```

**Comment by Andyccs** [comment]
This problem not happen on branch `release-0_11`. Most probably it has been fixed in the latest branch.

**Comment by killme2008** [comment]
Any update?
I have the same problem on mac osx with ruby example `bundle install`.

```sh
Using grpc 0.11.0 from https://github.com/grpc/grpc.git (at master)

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Volumes/HDD/Users/apple/.rvm/rubies/ruby-2.0.0-p0/bin/ruby -r ./siteconf20150928-9694-130lkew.rb extconf.rb
checking for dlopen() in -ldl... yes
checking for inflate() in -lz... yes
checking for gpr_now() in -lgpr... no
Building internal gRPC
[MAKE]    Generating cache.mk
[C]       Compiling src/core/support/histogram.c
src/core/support/histogram.c:215:17: error: implicit conversion turns floating-point number into integer: 'double' to '_Bool' [-Werror,-Wfloat-conversion]
  GPR_ASSERT(h->count);
  ~~~~~~~~~~~~~~^~~~~~
include/grpc/support/log.h:98:11: note: expanded from macro 'GPR_ASSERT'
    if (!(x)) {                                       \
          ^
1 error generated.
make: *** [/Users/dennis/.rvm/gems/ruby-2.0.0-p0/bundler/gems/grpc-0f9a118f4e94/objs/opt/src/core/support/histogram.o] Error 1
checking for gpr_now() in -lgpr... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Volumes/HDD/Users/apple/.rvm/rubies/ruby-2.0.0-p0/bin/ruby
	--with-grpc-dir
	--without-grpc-dir
	--with-grpc-include
	--without-grpc-include=${grpc-dir}/include
	--with-grpc-lib
	--without-grpc-lib=${grpc-dir}/
	--with-dllib
	--without-dllib
	--with-zlib
	--without-zlib
	--with-gprlib
	--without-gprlib
	--with-gprlib
	--without-gprlib
extconf.rb:97:in `rescue in <main>': gpr not found (RuntimeError)
	from extconf.rb:75:in `<main>'

extconf failed, exit code 1
```

**Comment by sreecha** [comment]
Issue should fixed now.
