### ISSUE TITLE
bazel run failed to run python grpc server/client

### ISSUE THREAD

**Issue by peggyxia-alj** [grpc/grpc#34465]
### What version of gRPC and what language are you using?
grpc-1.58.1
Python

### What operating system (Linux, Windows,...) and version?
Mac OS.
arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)
I use bazel to build. The python version of bazel is 3.11

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

This can be reproduced by the greeter_server python example using bazel(using com_github_grpc_grpc) on Mac OS. Bazel can build the rpc server and client successfully, but there is a run-time error which complains the imcompability of M1 and grpc python at runtime(error: mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')). 

This issue seems already being fixed in the non-bazel version(https://github.com/grpc/grpc/issues/28387): if I don't use bazel run, use python to run e.g. python greeting_server.py, it can run successfully. But in bazel, it will fail.

I tried different version of com_github_grpc_grpc, e.g. 1.47.0, 1.55.1, 1.58.1, they all have the same issue.

### What did you expect to see?
bazel run the greeter_server.py and greeter_client.py successful without error.

### What did you see instead?
bazel build succeed, but bazel run failed with this error:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_yuxia/09cda42d8fc3fc106105f00b2748eae8/execroot/hello/bazel-out/darwin-fastbuild/bin/greeter_server.runfiles/hello/greeter_server.py", line 19, in <module>
    import grpc
  File "/private/var/tmp/_bazel_yuxia/09cda42d8fc3fc106105f00b2748eae8/execroot/hello/bazel-out/darwin-fastbuild/bin/greeter_server.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/private/var/tmp/_bazel_yuxia/09cda42d8fc3fc106105f00b2748eae8/execroot/hello/bazel-out/darwin-fastbuild/bin/greeter_server.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/private/var/tmp/_bazel_yuxia/09cda42d8fc3fc106105f00b2748eae8/execroot/hello/bazel-out/darwin-fastbuild/bin/greeter_server.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so, 0x0002): tried: '/private/var/tmp/_bazel_yuxia/09cda42d8fc3fc106105f00b2748eae8/execroot/hello/bazel-out/darwin-fastbuild/bin/greeter_server.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.so' (no such file), '/usr/lib/cygrpc.so' (no such file), '/private/var/tmp/_bazel_yuxia/09cda42d8fc3fc106105f00b2748eae8/execroot/hello/bazel-out/darwin-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.so' (no such file), '/usr/lib/cygrpc.so' (no such file)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by peggyxia-alj** [comment]
I am not familiar with bazel toolchain. Do you have any commands or pointers that I can run to verify this?
