### ISSUE TITLE
grpcio 1.59.0 cannot import name 'errors'  from 'setuptools'

### ISSUE THREAD

**Issue by GavBurke** [grpc/grpc#34569]
### What version of gRPC and what language are you using?
1.59.0 via pip

### What operating system (Linux, Windows,...) and version?
Linux via dns-google Docker image: https://hub.docker.com/r/certbot/dns-google/#! 

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8

### What did you do?
*We* did nothing, grpcio 1.59.0 got released and the install fails, where as 1.58.0 installer works

### What did you expect to see?
grpcio 1.59.0 install

### What did you see instead?
```
#10 [5/15] RUN pip install --upgrade google-cloud-kms
#10 1.004 Collecting google-cloud-kms
#10 1.225   Downloading https://artifactory.retracteddomain.com/artifactory/api/pypi/pypi-virtual/packages/packages/96/f2/653abb0c4e57900b89c04b5dd228d329bca4de3e5ee4f34a78ac59f7d236/google_cloud_kms-2.19.1-py2.py3-none-any.whl (141kB)
#10 1.356 Collecting proto-plus<2.0.0dev,>=1.22.0 (from google-cloud-kms)
#10 1.496   Downloading https://artifactory.retracteddomain.com/artifactory/api/pypi/pypi-virtual/packages/packages/36/5b/e02636d221917d6fa2a61289b3f16002eb4c93d51c0191ac8e896d527182/proto_plus-1.22.3-py3-none-any.whl (48kB)
#10 1.862 Requirement already up-to-date: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0 in /usr/local/lib/python3.8/site-packages (from google-cloud-kms)
#10 1.965 Collecting grpc-google-iam-v1<1.0.0dev,>=0.12.4 (from google-cloud-kms)
#10 2.052   Downloading https://artifactory.retracteddomain.com/artifactory/api/pypi/pypi-virtual/packages/packages/34/72/c84e54991d452942c5a85474693c8433169104a596e9dd23b05c5f091894/grpc_google_iam_v1-0.12.6-py2.py3-none-any.whl
#10 3.111 Requirement already up-to-date: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /usr/local/lib/python3.8/site-packages (from google-cloud-kms)
#10 3.350 Requirement already up-to-date: google-auth<3.0.dev0,>=2.14.1 in /usr/local/lib/python3.8/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-kms)
#10 3.435 Requirement already up-to-date: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.8/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-kms)
#10 3.575 Requirement already up-to-date: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.8/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-kms)
#10 3.621 Collecting grpcio<2.0dev,>=1.33.2; extra == "grpc" (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-kms)
#10 6.247   Downloading https://artifactory.retracteddomain.com/artifactory/api/pypi/pypi-virtual/packages/packages/38/98/ca2cb5a81e0e2f3e3a00ebf91338fd3278ea0673e156a7ff2de30fe17113/grpcio-1.59.0.tar.gz (24.8MB)
#10 12.91     Complete output from command python setup.py egg_info:
#10 12.91     Traceback (most recent call last):
#10 12.91       File "<string>", line 1, in <module>
#10 12.91       File "/tmp/pip-build-otz1um9x/grpcio/setup.py", line 95, in <module>
#10 12.91         import commands
#10 12.91       File "/tmp/pip-build-otz1um9x/grpcio/src/python/grpcio/commands.py", line 31, in <module>
#10 12.91         import support
#10 12.91       File "/tmp/pip-build-otz1um9x/grpcio/src/python/grpcio/support.py", line 21, in <module>
#10 12.91         from setuptools import errors
#10 12.91     ImportError: cannot import name 'errors' from 'setuptools' (/usr/local/lib/python3.8/site-packages/setuptools/__init__.py)
#10 12.91     
#10 12.91     ----------------------------------------
#10 13.24 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-otz1um9x/grpcio/
#10 ERROR: executor failed running [/bin/sh -c pip install --upgrade google-cloud-kms]: runc did not terminate sucessfully
------
 > [5/15] RUN pip install --upgrade google-cloud-kms:
12.91       File "/tmp/pip-build-otz1um9x/grpcio/setup.py", line 95, in <module>
12.91         import commands
12.91       File "/tmp/pip-build-otz1um9x/grpcio/src/python/grpcio/commands.py", line 31, in <module>
12.91         import support
12.91       File "/tmp/pip-build-otz1um9x/grpcio/src/python/grpcio/support.py", line 21, in <module>
12.91         from setuptools import errors
12.91     ImportError: cannot import name 'errors' from 'setuptools' (/usr/local/lib/python3.8/site-packages/setuptools/__init__.py)
12.91     
12.91     ----------------------------------------
13.24 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-otz1um9x/grpcio/
```

**Comment by XuanWang-Amos** [comment]
Hi, upgrade to latest Docker image should fix the issue (We verified locally), you can also choose to upgrade `setuptools` version to as least v59.0.0 (Since they [exposed distutils errors starting v59.0.0](https://github.com/pypa/setuptools/commit/974dbb03769a500c5077d37291817f30359a0d7b)).

To add more context, we added support for Python 3.12 in gRPC 1.59.0, as part of the effort we're migrating away from `distutils` since [it's deprecated with removal planned for Python 3.12](https://peps.python.org/pep-0632/), some of the functions in `distutils` was replaced with `setuptools` but you'll need a higher version of `setuptools` to use them.

**Comment by rkrishnasanka** [comment]
I'm facing the same issue installing `grpcio>=1.24.3` do you know what version of setup tools I'm supposed to install to not have this problem ?

**Comment by XuanWang-Amos** [comment]
I don't know the exact version of grpc you're trying to install, assume you're installing latest version of grpcio (1.60.0) with Python 3.8+, then you'll need `setuptools>=59.0.0`.
