### ISSUE TITLE
GRPC C++ Server that calls Python Code (using PyRun_StringFlags) hangs whenever there's a python floating point error

### ISSUE THREAD

**Issue by rahejapankaj** [grpc/grpc#34845]
GRPC version : 1.49.1
Python version : 2.7

Whenever the same GRPC thread gets to process a request that results in python FPE (Floating point error_ – it’s all fine - PyGILState_Ensure() followed by PyGILState_Release() – works seamlessly.
However, as soon as a new thread gets to process a request that FPE’s – it hangs. Can be demonstrated using gdb.

#0  0x00007f34b2b7cb3b in do_futex_wait.constprop.1 ()
#1  0x00007f34b2b7cbcf in __new_sem_wait_slow.constprop.0 () 
#2  0x00007f34b2b7cc6b in sem_wait@@GLIBC_2.2.5 () 
#3  0x00007f34c38f44d8 in PyThread_acquire_lock (lock=lock@entry=0x26383aa0, waitflag=waitflag@entry=1)
#4  0x00007f34c38b8077 in PyEval_RestoreThread (tstate=tstate@entry=0x161af760)
#5  0x00007f34c38e06ae in PyGILState_Ensure ()
#6  0x00007f349d32b9cd in _error_handler (method=method@entry=0, errobj=errobj@entry=0x7f348967ccd0, errtype=errtype@entry=0x7f349d35056f "underflow", retstatus=retstatus@entry=4, first=first@entry=0x7f34a7e33114) at numpy/core/src/umath/ufunc_object.c:98
#7  0x00007f349d33934f in PyUFunc_handlefperr (errmask=521, errobj=0x7f348967ccd0, retstatus=4, first=0x7f34a7e33114) at numpy/core/src/umath/ufunc_object.c:192
#8  0x00007f349d343d18 in PyUFunc_checkfperr (first=0x7f34a7e33114, errobj=0x7f348967ccd0, errmask=521) at numpy/core/src/umath/ufunc_object.c:209

**Comment by rahejapankaj** [comment]
Adding numpy.setterr(all='ignore') to the python code that gets executed is a workaround - however that would mean the errors would not get printed.

**Comment by rahejapankaj** [comment]
import numpy
from numpy import exp

#numpy.seterr(all='ignore') # with all=ignore, it doesn't hang
print (exp(-900)) # results in FPE underflow - otherwise 'harmless' but hangs the GRPC server

**Comment by rahejapankaj** [comment]
Seems to be more of multi-threaded C++ programs + Py GIL (lock / unlock) issue and less of a GRPC issue.

**Comment by rahejapankaj** [comment]
Closing this issue - should be solved using some appropriate PY/C API's and not within the grpc code. Py GIL + Mult-Threaded apps' - very annoying.
