### ISSUE TITLE
New Grpc.Core.Server creation not working in a Mac M2

### ISSUE THREAD

**Issue by ropinheiro** [grpc/grpc#35414]
### What version of gRPC and what language are you using?

I am using C# with the latest `grpc-dotnet` (2.59.0) and the project includes the `Grpc.Core` and `Grpc.Tools` nuGet packages (2.46.6).

### What operating system (Linux, Windows,...) and version?

MacOS Sonoma 14.1.2 (23B92) - RID: osx-arm64

### What runtime / compiler are you using (e.g. python version or version of gcc)

.NET Core SDK 8.0.100 (runtime: 8.0.0)

### What did you do?

Execute "dotnet run" in an application containing a line of code with "new Grpc.Core.Server(...)" in an M2 Mac.

### What did you expect to see?

An application running without errors, and properly communicating with other applications through gRPC.

I know it is possible because it worked on a different Mac with the same setup, same code, same .NET SDK and runtime, same .NET version, etc. but **with the Intel chip** (older Mac) - hence my guess that maybe it's a bug related to the M2 chip.

### What did you see instead?

When I execute "dotnet run", I get this error:

_Note: I used (...) as a replacement for my specific irrelevant stuff_

```
[18:33:31 FTL] Unhandled exception!
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: 
  (...)/bin/Debug/net8.0/libgrpc_csharp_ext.arm64.dylib,
  (...)/bin/Debug/net8.0/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib,
  (...)/bin/Debug/net8.0/../../runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Grpc.Core.Server..ctor()
   at (...).Grpc.GrpcServer.StartServer() in (...)/Grpc/GrpcServer.cs:line 41
   at (...).Grpc.GrpcServer..ctor(...) in (...)/Grpc/GrpcServer.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at (...).Program.MainAsync() in (...)/Program.cs:line 196
   at (...).Program.Main() in (...)/Program.cs:line 39
[18:33:31 DBG] Flushing logs....
[18:33:31 INF] Trapped SIGTERM: shutting down...
```

Line 41 mentioned in the error message is the first line of this code block:

```
        var server = new Grpc.Core.Server
        {
            Services = { MyService.BindService(myService) },
            Ports =
            {
                new Grpc.Core.ServerPort("0.0.0.0", myPort, Grpc.Core.ServerCredentials.Insecure)
            }
        };
```

### Anything else we should know about your project / environment?

Not sure. I have a gut feeling that it is related to the Intel vs M2 chip difference. I spent some time checking all possible differences between the two Macs, and that's the major one. Also, the OS is 14.2.1 on the old Mac (I still had no opportunity to upgrade to the newer one from its 14.1.2).

**Comment by ropinheiro** [comment]
Additional note: I was able to run the same application in a Docker container in the same Mac M2, using this image: mcr.microsoft.com/dotnet/sdk:8.0.100-1-bookworm-slim-amd64

Still not sure why it doesn't run directly in my host during development (I am using JetBrains Rider, and running the application in the console using "dotnet run").

**Comment by tonydnewell** [comment]
@ropinheiro There is some confusion since you meantion both `grpc-dotnet` (2.59.0) and `grpc.core` (2.46.0) which are different implementations for gRPC for C#.

The stack trace shows that you are using `grpc.core`. 

I think the general problem is that the Mac M2 version of the grpc_csharp_ext native library isn't available (we only ship the native library for Intel Mac). The Grpc.Core implementation is now in maintenance mode and we're only going to focus on critical and security fixes. You should consider migrating to the `grpc-dotnet`  implementation instead. See https://learn.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-8.0

I don't have access to a Mac to know why your applications runs with the docker image. Maybe it can run using Rosetta to run the intel binaries?

**Comment by ropinheiro** [comment]
Thanks for the comments! We now understand that we should choose one of the approaches and not the other. The obvious choice almost always goes for the latest and still supported one, so we are going for `grpc-dotnet`. The main issue I see now (but I may be too conservative or have understood something wrong) is `grpc-dotnet` requiring ASP.NET libraries to have the server part working. Therefore, I will have to turn my tiny edge app running in a low CPU/RAM gateway into a full-blown web application. Is that correct? Won't it be too much impact?

**Comment by tonydnewell** [comment]
You can run a grpc-dotnet ASP.NET Core server in an app that you start from the console. It can use the kestrel web server which is the default if you follow the tutorial: https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-8.0&tabs=visual-studio

A gRPC server application needs a server, whether it is the c-core based one used in legacy grpc, or an ASP.NET server used by grpc-dotnet. If one is more lightweight that the other I cannot say.
