### ISSUE TITLE
Segfault in grpc_wakeup_fd_init

### ISSUE THREAD

**Issue by dajofrey** [grpc/grpc#35652]
### What version of gRPC and what language are you using?
Version: commit 0417b882aa7abc1512f534e56f9cd97c557bb68f, v1.58.0
Language: C++

### What operating system (Linux, Windows,...) and version?
Cross-Compilation with target being:
OpenWRT based GNU/Linux (aarch64, kernel 4.4.60) with MUSL based standard libraries.     

### What runtime / compiler are you using (e.g. python version or version of gcc)
OpenWrt GCC 8.3.0 r11427-9ce6aa9d8d)
On the device, we are mostly using the libs that grpc provides us with:
```
libabsl_bad_any_cast_impl.so                        libabsl_leak_check.so.2308.0.0                              libabsl_string_view.so 
libabsl_bad_any_cast_impl.so.2308.0.0               libabsl_log_entry.so                                        libabsl_string_view.so.2308.0.0 
libabsl_bad_optional_access.so                      libabsl_log_entry.so.2308.0.0                               libabsl_symbolize.so 
libabsl_bad_optional_access.so.2308.0.0             libabsl_log_flags.so                                        libabsl_symbolize.so.2308.0.0 
libabsl_bad_variant_access.so                       libabsl_log_flags.so.2308.0.0                               libabsl_synchronization.so 
libabsl_bad_variant_access.so.2308.0.0              libabsl_log_globals.so                                      libabsl_synchronization.so.2308.0.0 
libabsl_base.so                                     libabsl_log_globals.so.2308.0.0                             libabsl_throw_delegate.so 
libabsl_base.so.2308.0.0                            libabsl_log_initialize.so                                   libabsl_throw_delegate.so.2308.0.0 
libabsl_city.so                                     libabsl_log_initialize.so.2308.0.0                          libabsl_time.so 
libabsl_city.so.2308.0.0                            libabsl_log_internal_check_op.so                            libabsl_time.so.2308.0.0 
libabsl_civil_time.so                               libabsl_log_internal_check_op.so.2308.0.0                   libabsl_time_zone.so 
libabsl_civil_time.so.2308.0.0                      libabsl_log_internal_conditions.so                          libabsl_time_zone.so.2308.0.0 
libabsl_cord_internal.so                            libabsl_log_internal_conditions.so.2308.0.0                 libaddress_sorting.so 
libabsl_cord_internal.so.2308.0.0                   libabsl_log_internal_format.so                              libaddress_sorting.so.35 
libabsl_cord.so                                     libabsl_log_internal_format.so.2308.0.0                     libaddress_sorting.so.35.0.0 
libabsl_cord.so.2308.0.0                            libabsl_log_internal_globals.so                             libcrypto.so 
libabsl_cordz_functions.so                          libabsl_log_internal_globals.so.2308.0.0                    libgpr.so 
libabsl_cordz_functions.so.2308.0.0                 libabsl_log_internal_log_sink_set.so                        libgpr.so.35 
libabsl_cordz_handle.so                             libabsl_log_internal_log_sink_set.so.2308.0.0               libgpr.so.35.0.0 
libabsl_cordz_handle.so.2308.0.0                    libabsl_log_internal_message.so                             libgrpc++_alts.so 
libabsl_cordz_info.so                               libabsl_log_internal_message.so.2308.0.0                    libgrpc++_alts.so.1.58 
libabsl_cordz_info.so.2308.0.0                      libabsl_log_internal_nullguard.so                           libgrpc++_alts.so.1.58.0 
libabsl_cordz_sample_token.so                       libabsl_log_internal_nullguard.so.2308.0.0                  libgrpc_authorization_provider.so 
libabsl_cordz_sample_token.so.2308.0.0              libabsl_log_internal_proto.so                               libgrpc_authorization_provider.so.1.58 
libabsl_crc32c.so                                   libabsl_log_internal_proto.so.2308.0.0                      libgrpc_authorization_provider.so.1.58.0 
libabsl_crc32c.so.2308.0.0                          libabsl_log_severity.so                                     libgrpc++_error_details.so 
libabsl_crc_cord_state.so                           libabsl_log_severity.so.2308.0.0                            libgrpc++_error_details.so.1.58 
libabsl_crc_cord_state.so.2308.0.0                  libabsl_log_sink.so                                         libgrpc++_error_details.so.1.58.0 
libabsl_crc_cpu_detect.so                           libabsl_log_sink.so.2308.0.0                                libgrpc_plugin_support.so 
libabsl_crc_cpu_detect.so.2308.0.0                  libabsl_low_level_hash.so                                   libgrpc_plugin_support.so.1.58 
libabsl_crc_internal.so                             libabsl_low_level_hash.so.2308.0.0                          libgrpc_plugin_support.so.1.58.0 
libabsl_crc_internal.so.2308.0.0                    libabsl_malloc_internal.so                                  libgrpcpp_channelz.so 
libabsl_debugging_internal.so                       libabsl_malloc_internal.so.2308.0.0                         libgrpcpp_channelz.so.1.58 
libabsl_debugging_internal.so.2308.0.0              libabsl_periodic_sampler.so                                 libgrpcpp_channelz.so.1.58.0 
libabsl_demangle_internal.so                        libabsl_periodic_sampler.so.2308.0.0                        libgrpc++_reflection.so 
libabsl_demangle_internal.so.2308.0.0               libabsl_random_distributions.so                             libgrpc++_reflection.so.1.58 
libabsl_die_if_null.so                              libabsl_random_distributions.so.2308.0.0                    libgrpc++_reflection.so.1.58.0 
libabsl_die_if_null.so.2308.0.0                     libabsl_random_internal_distribution_test_util.so           libgrpc++.so 
libabsl_examine_stack.so                            libabsl_random_internal_distribution_test_util.so.2308.0.0  libgrpc.so 
libabsl_examine_stack.so.2308.0.0                   libabsl_random_internal_platform.so                         libgrpc++.so.1.58 
libabsl_exponential_biased.so                       libabsl_random_internal_platform.so.2308.0.0                libgrpc++.so.1.58.0 
libabsl_exponential_biased.so.2308.0.0              libabsl_random_internal_pool_urbg.so                        libgrpc.so.35 
libabsl_failure_signal_handler.so                   libabsl_random_internal_pool_urbg.so.2308.0.0               libgrpc.so.35.0.0 
libabsl_failure_signal_handler.so.2308.0.0          libabsl_random_internal_randen_hwaes_impl.so                libgrpc++_unsecure.so 
libabsl_flags_commandlineflag_internal.so           libabsl_random_internal_randen_hwaes_impl.so.2308.0.0       libgrpc_unsecure.so 
libabsl_flags_commandlineflag_internal.so.2308.0.0  libabsl_random_internal_randen_hwaes.so                     libgrpc++_unsecure.so.1.58 
libabsl_flags_commandlineflag.so                    libabsl_random_internal_randen_hwaes.so.2308.0.0            libgrpc++_unsecure.so.1.58.0 
libabsl_flags_commandlineflag.so.2308.0.0           libabsl_random_internal_randen_slow.so                      libgrpc_unsecure.so.35 
libabsl_flags_config.so                             libabsl_random_internal_randen_slow.so.2308.0.0             libgrpc_unsecure.so.35.0.0 
libabsl_flags_config.so.2308.0.0                    libabsl_random_internal_randen.so                           libprotobuf-lite.so 
libabsl_flags_internal.so                           libabsl_random_internal_randen.so.2308.0.0                  libprotobuf-lite.so.23.4.0 
libabsl_flags_internal.so.2308.0.0                  libabsl_random_internal_seed_material.so                    libprotobuf.so 
libabsl_flags_marshalling.so                        libabsl_random_internal_seed_material.so.2308.0.0           libprotobuf.so.23.4.0 
libabsl_flags_marshalling.so.2308.0.0               libabsl_random_seed_gen_exception.so                        libprotoc.so 
libabsl_flags_parse.so                              libabsl_random_seed_gen_exception.so.2308.0.0               libprotoc.so.23.4.0 
libabsl_flags_parse.so.2308.0.0                     libabsl_random_seed_sequences.so                            libre2.so 
libabsl_flags_private_handle_accessor.so            libabsl_random_seed_sequences.so.2308.0.0                   libre2.so.9 
libabsl_flags_private_handle_accessor.so.2308.0.0   libabsl_raw_hash_set.so                                     libre2.so.9.0.0 
libabsl_flags_program_name.so                       libabsl_raw_hash_set.so.2308.0.0                            libssl.so 
libabsl_flags_program_name.so.2308.0.0              libabsl_raw_logging_internal.so                             libupb_collections_lib.so 
libabsl_flags_reflection.so                         libabsl_raw_logging_internal.so.2308.0.0                    libupb_collections_lib.so.35 
libabsl_flags_reflection.so.2308.0.0                libabsl_scoped_set_env.so                                   libupb_collections_lib.so.35.0.0 
libabsl_flags.so                                    libabsl_scoped_set_env.so.2308.0.0                          libupb_json_lib.so 
libabsl_flags.so.2308.0.0                           libabsl_spinlock_wait.so                                    libupb_json_lib.so.35 
libabsl_flags_usage_internal.so                     libabsl_spinlock_wait.so.2308.0.0                           libupb_json_lib.so.35.0.0 
libabsl_flags_usage_internal.so.2308.0.0            libabsl_stacktrace.so                                       libupb.so 
libabsl_flags_usage.so                              libabsl_stacktrace.so.2308.0.0                              libupb.so.35 
libabsl_flags_usage.so.2308.0.0                     libabsl_statusor.so                                         libupb.so.35.0.0 
libabsl_graphcycles_internal.so                     libabsl_statusor.so.2308.0.0                                libupb_textformat_lib.so 
libabsl_graphcycles_internal.so.2308.0.0            libabsl_status.so                                           libupb_textformat_lib.so.35 
libabsl_hash.so                                     libabsl_status.so.2308.0.0                                  libupb_textformat_lib.so.35.0.0 
libabsl_hash.so.2308.0.0                            libabsl_strerror.so                                         libutf8_range_lib.so 
libabsl_hashtablez_sampler.so                       libabsl_strerror.so.2308.0.0                                libutf8_range_lib.so.35 
libabsl_hashtablez_sampler.so.2308.0.0              libabsl_str_format_internal.so                              libutf8_range_lib.so.35.0.0 
libabsl_int128.so                                   libabsl_str_format_internal.so.2308.0.0                     libz.so 
libabsl_int128.so.2308.0.0                          libabsl_strings_internal.so                                 libz.so.1 
libabsl_kernel_timeout_internal.so                  libabsl_strings_internal.so.2308.0.0                        libz.so.1.2.13 
libabsl_kernel_timeout_internal.so.2308.0.0         libabsl_strings.so 
libabsl_leak_check.so                               libabsl_strings.so.2308.0.0 
```
### What did you do?
I created a program for testing:

```
#include <iostream> 
#include <memory> 
#include <string> 
#include <grpcpp/grpcpp.h> 

int main(int argc, char** argv) { 
    if (argc != 2) { 
        std::cerr << "Usage: " << argv[0] << " URI" << std::endl; 
        return 1; 
    } 
    std::string uri = argv[1]; 
    auto channel = grpc::CreateChannel(uri, grpc::InsecureChannelCredentials()); 
    return 0; 
} 
```

### What did you expect to see?
Nothing in particular, just normal execution without segfault.

### What did you see instead?
A segfault somewhere in grpc. This is the backtrace:

```
Core was generated by ... 
Program terminated with signal SIGSEGV, Segmentation fault. 
#0  0x0000007f7dc7dec8 in grpc_wakeup_fd_init (fd_info=0x7f7dddde90 <global_wakeup_fd>) at grpc-1.59.3/src/core/lib/iomgr/wakeup_fd_posix.cc:58 
58        return wakeup_fd_vtable->init(fd_info); 
[Current thread is 1 (LWP 2631)]
(gdb) bt 
#0  0x0000007f7dc7dec8 in grpc_wakeup_fd_init (fd_info=0x7f7dddde90 <global_wakeup_fd>) at grpc-1.59.3/src/core/lib/iomgr/wakeup_fd_posix.cc:58 
#1  0x0000007f7dc5fe18 in pollset_global_init () at grpc-1.59.3/src/core/lib/iomgr/ev_epoll1_linux.cc:530 
#2  init_epoll1_linux () at grpc-1.59.3/src/core/lib/iomgr/ev_epoll1_linux.cc:1323 
#3  0x0000007f7f38e680 in try_engine (engine=...) at grpc-1.59.3/third_party/abseil-cpp/absl/strings/string_view.h:197 
#4  <lambda()>::operator()(void) const (__closure=<optimized out>) at grpc-1.59.3/src/core/lib/iomgr/ev_posix.cc:147 
#5  0x0000007f7ee50a9c in absl::lts_20230802::base_internal::Callable::Invoke<void (*&)()> (f=@0x7fcfba50a8: 0x7f7f38e81c <<lambda()>::_FUN(void)>) 
    at grpc-1.59.3/third_party/abseil-cpp/absl/base/internal/invoke.h:211 
#6  absl::lts_20230802::base_internal::invoke<void (*&)()> (f=@0x7fcfba50a8: 0x7f7f38e81c <<lambda()>::_FUN(void)>) 
    at grpc-1.59.3/third_party/abseil-cpp/absl/base/internal/invoke.h:212 
#7  absl::lts_20230802::base_internal::CallOnceImpl<void (*&)()> (control=control@entry=0x7f7f6020b0 <g_choose_engine>, scheduling_mode=scheduling_mode@entry=absl::lts_20230802::base_internal::SCHEDULE_COOPERATIVE_AND_KERNEL, 
    fn=@0x7fcfba50a8: 0x7f7f38e81c <<lambda()>::_FUN(void)>) at grpc-1.59.3/third_party/abseil-cpp/absl/base/call_once.h:178 
#8  0x0000007f7ee50a58 in absl::lts_20230802::call_once<void (*&)()> (fn=@0x7fcfba50a8: 0x7f7f38e81c <<lambda()>::_FUN(void)>, flag=...) 
    at toolchain-aarch64_cortex-a53_gcc-8.3.0_musl/aarch64-openwrt-linux-musl/include/c++/8.3.0/bits/atomic_base.h:390 
#9  gpr_once_init (once=once@entry=0x7f7f6020b0 <g_choose_engine>, init_function=<optimized out>, init_function@entry=0x7f7f38e81c <<lambda()>::_FUN(void)>) 
    at grpc-1.59.3/src/core/lib/gpr/sync_abseil.cc:107 
#10 0x0000007f7f38e900 in grpc_event_engine_init () at grpc-1.59.3/src/core/lib/iomgr/ev_posix.cc:144 
#11 0x0000007f7f393ee4 in iomgr_platform_init () at grpc-1.59.3/src/core/lib/iomgr/iomgr_posix.cc:43 
#12 0x0000007f7f39346c in grpc_iomgr_init () at grpc-1.59.3/src/core/lib/iomgr/iomgr.cc:61 
#13 0x0000007f7f423568 in grpc_init () at grpc-1.59.3/src/core/lib/surface/init.cc:145 
#14 0x0000007f7eee3d64 in grpc::internal::GrpcLibrary::GrpcLibrary (call_grpc_init=true, this=<optimized out>) atgrpc-1.59.3/include/grpcpp/impl/grpc_library.h:36 
#15 grpc::ChannelCredentials::ChannelCredentials (this=<optimized out>) at grpc-1.59.3/include/grpcpp/security/credentials.h:69 
#16 grpc::(anonymous namespace)::InsecureChannelCredentialsImpl::InsecureChannelCredentialsImpl (this=<optimized out>) 
    atgrpc-1.59.3/src/cpp/client/insecure_credentials.cc:35 
#17 grpc::InsecureChannelCredentials () at grpc-1.59.3/src/cpp/client/insecure_credentials.cc:35 
#18 0x000000000041180c in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:53

```

### Anything else we should know about your project / environment?
We know what the issue is: `wakeup_fd_vtable` gets initalized in `grpc_wakeup_fd_global_init` to a valid pointer using
```
      wakeup_fd_vtable = &grpc_specialized_wakeup_fd_vtable;                                                    
```
But when `grpc_wakeup_fd_init` is called, `wakeup_fd_vtable` is somehow back to NULL, causing a segfault. This we don't understand, since `wakeup_fd_vtable` is static and not used anywhere else.          

Any help or ideas would really be appreciated.

**Comment by dajofrey** [comment]
Tis was a problem with our build-procedure. Closing.
