### ISSUE TITLE
Cert verify failure against SNI Nginx gateway in Kubernetes

### ISSUE THREAD

**Issue by andreas-ibm** [grpc/grpc#35728]
### What version of gRPC and what language are you using?
python3 
grpcio                1.60.0

### What operating system (Linux, Windows,...) and version?
Red Hat Enterprise Linux release 9.3 (Plow)
Linux 5.14.0-362.18.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 3 15:54:45 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.18

### What did you do?
1. Created milvus server in kubernetes at dre-cluster.internal.host
2. Created NGIИX ingress with http/2 proxy to milvus server
3. Set up ingress with catch-all cert signed by internal intermediate CA signed by internal root CA
4. tested with cURL and openSSL s_client
5. tested with the following python:
```python
import os
from pymilvus import connections
milvus_host = os.environ['MILVUS_HOST']
milvus_port = os.environ['MILVUS_PORT']
milvus_uri = f"https://{milvus_host}:{milvus_port}"
connections.connect(
  alias="default",
  user='username',
  password='password',
  uri=milvus_uri,
)
print("Connected")
```
which invokes across grpc

### What did you expect to see?
"Connected"

### What did you see instead?
```
$MILVUS_HOST=milvus.dre-cluster.fyre.ibm.com MILVUS_PORT=443 python3 test.py
E0129 16:35:19.332032277  120455 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0129 16:35:20.331896854  120455 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0129 16:35:22.238078817  120455 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0129 16:35:24.900505156  120455 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Traceback (most recent call last):
  File "/home/amartens/.local/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 143, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/home/amartens/.local/lib/python3.9/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/home/amartens/.local/lib/python3.9/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amartens/Development/test.py", line 6, in <module>
    connections.connect(
  File "/home/amartens/.local/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 414, in connect
    connect_milvus(**kwargs, user=****, password=****, token=token, db_name=db_name)
  File "/home/amartens/.local/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 365, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/amartens/.local/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 146, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on milvus.dre-cluster.internal.host:443. Timeout)>
```

### Anything else we should know about your project / environment?
I *can* connect if I point it directly to milvus on an unsecured port, so I know the gRPC server is happily running, I just can't secure it.

I have multiple other HTTP/1.1 services running on this cluster happily using nginx ingress, but this is the first time I've used it for handling gRPC data. 

I *think* I've covered all the complexity above... 
Attached full GRPC trace
[grpctrace.log](https://github.com/grpc/grpc/files/14087156/grpctrace.log)

**Comment by XuanWang-Amos** [comment]
@gtcooke94 Can you help take a look?

**Comment by gtcooke94** [comment]
Can you show more on how the grpc credentials are set up? My guess is either a misconfiguration there or a misconfigured cert in general.

@rockspore

**Comment by andreas-ibm** [comment]
Yep,
We have a corporate internal CA with an intermediate CA under it. I've configured the nginx ingress with the full chain of server->intemediate->root. I can connect with openssl s_client:
```
$echo "GET /index.html HTTP/2.0"|openssl s_client -servername milvus.dre-cluster.fyre.ibm.com -connect milvus.dre-cluster.fyre.ibm.com:443
CONNECTED(00000006)
depth=2 C = US, O = International Business Machines Corporation, CN = IBM Internal Root CA
verify return:1
depth=1 C = US, O = International Business Machines Corporation, CN = IBM INTERNAL INTERMEDIATE CA
verify return:1
depth=0 C = GB, ST = Hursley, L = Hursley, O = ibm.com, OU = Software, CN = *.dre-cluster.fyre.ibm.com, UID = <redacted>, mail = <redacted>
verify return:1
write W BLOCK
```

And if I run with python/grpc:
```

$GRPC_TRACE=cares_resolver,cares_address_sorting,dns_resolver GRPC_VERBOSITY=DEBUG GRPC_DNS_RESOLVER=native  MILVUS_HOST=milvus.dre-cluster.fyre.ibm.com MILVUS_PORT=443 python test.py
D0205 12:06:16.882063000 140704368781184 config.cc:175]                gRPC EXPERIMENT tcp_frame_size_tuning               OFF (default:OFF)
D0205 12:06:16.882095000 140704368781184 config.cc:175]                gRPC EXPERIMENT tcp_rcv_lowat                       OFF (default:OFF)
D0205 12:06:16.882100000 140704368781184 config.cc:175]                gRPC EXPERIMENT peer_state_based_framing            OFF (default:OFF)
D0205 12:06:16.882103000 140704368781184 config.cc:175]                gRPC EXPERIMENT memory_pressure_controller          OFF (default:OFF)
D0205 12:06:16.882106000 140704368781184 config.cc:175]                gRPC EXPERIMENT unconstrained_max_quota_buffer_size OFF (default:OFF)
D0205 12:06:16.882109000 140704368781184 config.cc:175]                gRPC EXPERIMENT event_engine_client                 OFF (default:OFF)
D0205 12:06:16.882112000 140704368781184 config.cc:175]                gRPC EXPERIMENT monitoring_experiment               ON  (default:ON)
D0205 12:06:16.882115000 140704368781184 config.cc:175]                gRPC EXPERIMENT promise_based_client_call           OFF (default:OFF)
D0205 12:06:16.882218000 140704368781184 config.cc:175]                gRPC EXPERIMENT free_large_allocator                OFF (default:OFF)
D0205 12:06:16.882224000 140704368781184 config.cc:175]                gRPC EXPERIMENT promise_based_server_call           OFF (default:OFF)
D0205 12:06:16.882227000 140704368781184 config.cc:175]                gRPC EXPERIMENT transport_supplies_client_latency   OFF (default:OFF)
D0205 12:06:16.882230000 140704368781184 config.cc:175]                gRPC EXPERIMENT event_engine_listener               OFF (default:OFF)
D0205 12:06:16.882234000 140704368781184 config.cc:175]                gRPC EXPERIMENT schedule_cancellation_over_write    OFF (default:OFF)
D0205 12:06:16.882237000 140704368781184 config.cc:175]                gRPC EXPERIMENT trace_record_callops                OFF (default:OFF)
D0205 12:06:16.882240000 140704368781184 config.cc:175]                gRPC EXPERIMENT event_engine_dns                    OFF (default:OFF)
D0205 12:06:16.882243000 140704368781184 config.cc:175]                gRPC EXPERIMENT work_stealing                       OFF (default:OFF)
D0205 12:06:16.882247000 140704368781184 config.cc:175]                gRPC EXPERIMENT client_privacy                      OFF (default:OFF)
D0205 12:06:16.882250000 140704368781184 config.cc:175]                gRPC EXPERIMENT canary_client_privacy               OFF (default:OFF)
D0205 12:06:16.882253000 140704368781184 config.cc:175]                gRPC EXPERIMENT server_privacy                      OFF (default:OFF)
D0205 12:06:16.882256000 140704368781184 config.cc:175]                gRPC EXPERIMENT unique_metadata_strings             ON  (default:ON)
D0205 12:06:16.882259000 140704368781184 config.cc:175]                gRPC EXPERIMENT keepalive_fix                       OFF (default:OFF)
D0205 12:06:16.882262000 140704368781184 config.cc:175]                gRPC EXPERIMENT keepalive_server_fix                OFF (default:OFF)
D0205 12:06:16.882446000 140704368781184 ev_posix.cc:113]              Using polling engine: poll
D0205 12:06:16.882536000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "priority_experimental"
D0205 12:06:16.882551000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "outlier_detection_experimental"
D0205 12:06:16.882556000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "weighted_target_experimental"
D0205 12:06:16.882562000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "pick_first"
D0205 12:06:16.882566000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "round_robin"
D0205 12:06:16.882571000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "weighted_round_robin"
D0205 12:06:16.882583000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "grpclb"
D0205 12:06:16.882599000 140704368781184 dns_resolver_plugin.cc:57]    Using native dns resolver
D0205 12:06:16.882618000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "rls_experimental"
D0205 12:06:16.882638000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "xds_cluster_manager_experimental"
D0205 12:06:16.882644000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "xds_cluster_impl_experimental"
D0205 12:06:16.882649000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "cds_experimental"
D0205 12:06:16.882654000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "xds_cluster_resolver_experimental"
D0205 12:06:16.882660000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "xds_override_host_experimental"
D0205 12:06:16.882666000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "xds_wrr_locality_experimental"
D0205 12:06:16.882670000 140704368781184 lb_policy_registry.cc:47]     registering LB policy factory for "ring_hash_experimental"
D0205 12:06:16.882676000 140704368781184 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
I0205 12:06:16.885306000 123145454723072 polling_resolver.cc:63]       [polling resolver 0x7ff37191a8e0] created
D0205 12:06:16.885321000 123145454723072 dns_resolver.cc:98]           [dns_resolver=0x7ff37191a8e0] created
D0205 12:06:16.885339000 123145454723072 dns_resolver.cc:115]          [dns_resolver=0x7ff37191a8e0] starting request=0x700009159639
I0205 12:06:16.885344000 123145454723072 polling_resolver.cc:265]      [polling resolver 0x7ff37191a8e0] starting resolution, request_=0x6000030381a0
D0205 12:06:19.983851000 123145428275200 dns_resolver.cc:124]          [dns_resolver=0x7ff37191a8e0] request complete, status="OK"
I0205 12:06:19.983883000 123145428275200 polling_resolver.cc:155]      [polling resolver 0x7ff37191a8e0] request complete
I0205 12:06:19.983892000 123145428275200 polling_resolver.cc:160]      [polling resolver 0x7ff37191a8e0] returning result: addresses=<1 addresses>, service_config=<null>, resolution_note=
I0205 12:06:19.991864000 123145428275200 polling_resolver.cc:191]      [polling resolver 0x7ff37191a8e0] result status from channel: OK
E0205 12:06:20.081944000 123145454723072 ssl_transport_security.cc:1432] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0205 12:06:20.083747000 123145454723072 security_handshaker.cc:208]   Security handshake failed: UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:20.082004+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}
I0205 12:06:20.084057000 123145454723072 subchannel.cc:711]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: connect failed (UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:20.082004+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}), backing off for 900 ms
I0205 12:06:20.084103000 123145454723072 polling_resolver.cc:246]      [polling resolver 0x7ff37191a8e0] in cooldown from last resolution (from 3198 ms ago); will resolve again in 26802 ms
I0205 12:06:20.989352000 123145430958080 subchannel.cc:666]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: backoff delay elapsed, reporting IDLE
E0205 12:06:21.085224000 123145454723072 ssl_transport_security.cc:1432] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0205 12:06:21.085306000 123145454723072 security_handshaker.cc:208]   Security handshake failed: UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:21.085264+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}
I0205 12:06:21.085563000 123145454723072 subchannel.cc:711]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: connect failed (UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:21.085264+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}), backing off for 1223 ms
I0205 12:06:22.314817000 123145434714112 subchannel.cc:666]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: backoff delay elapsed, reporting IDLE
E0205 12:06:22.401902000 123145454723072 ssl_transport_security.cc:1432] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0205 12:06:22.402010000 123145454723072 security_handshaker.cc:208]   Security handshake failed: UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:22.40196+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}
I0205 12:06:22.402367000 123145454723072 subchannel.cc:711]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: connect failed (UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:22.40196+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}), backing off for 2816 ms
I0205 12:06:25.222852000 123145434714112 subchannel.cc:666]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: backoff delay elapsed, reporting IDLE
E0205 12:06:25.318562000 123145454723072 ssl_transport_security.cc:1432] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0205 12:06:25.318701000 123145454723072 security_handshaker.cc:208]   Security handshake failed: UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:25.318662+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}
I0205 12:06:25.318965000 123145454723072 subchannel.cc:711]            subchannel 0x7ff360791280 {address=ipv4:<IP>:443, args={grpc.client_channel_factory=0x600003024160, grpc.default_authority=milvus.dre-cluster.fyre.ibm.com:443, grpc.enable_retries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x600002708000, grpc.internal.event_engine=0x6000030032a0, grpc.internal.security_connector=0x600001c21e00, grpc.internal.subchannel_pool=0x600001934000, grpc.keepalive_time_ms=55000, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.58.0, grpc.resource_quota=0x600003c3c300, grpc.server_uri=dns:///milvus.dre-cluster.fyre.ibm.com:443}}: connect failed (UNKNOWN:Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED {created_time:"2024-02-05T12:06:25.318662+00:00", tsi_error:"TSI_PROTOCOL_FAILURE", tsi_code:10}), backing off for 4777 ms
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 133, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/usr/local/lib/python3.11/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amartens/Development/Broker/ai/test.py", line 6, in <module>
    connections.connect(
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 356, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 302, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 136, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on milvus.dre-cluster.fyre.ibm.com:443. Timeout)>
```
Now it's possible that python/grpc is picking up its trust anchors from a different place to openssl / keychain. Is there a way to see where so I can add our Root CA there too?

**Comment by andreas-ibm** [comment]
bump, any comment? Does grpc look for trust anchors in a different place?

**Comment by gtcooke94** [comment]
Hello, thanks for the bump - I'm not familiar with Milvus, but I suspect you need to look at the internals of how it is configuring gRPC. Somewhere there are gRPC credentials and channels being created and there you'll see the roots and certs that are configured. That's where I suspect there's a problem given that you are able to connect successfully via other means.

**Comment by andreas-ibm** [comment]
Ahh, so you're saying that gRPC doesn't use a global trust anchor with trusted root certs, but the root certificate needs to be passed down by the caller (i.e. Milvus in this case)?
I'll have a play with the APIs to see what I can afffect.
wait, no, if that was the case then *no* gRPC call would work against an SSL secured channel without explicit certificates being passed down, is that really the case?

**Comment by gtcooke94** [comment]
It depends on the configuration - there are generally reasonable defaults if you don't explicitly configure the roots, but somewhere something is configured to tell grpc what to use/where to look (even if it's defaults)

**Comment by gtcooke94** [comment]
For example, in C++ https://grpc.github.io/grpc/cpp/structgrpc_1_1_ssl_credentials_options.html

**Comment by andreas-ibm** [comment]
yes I see, I'll do a little more digging (it's been a little while since I played with this, so my memory might be failing me).  What I was hoping was to find the defaults and inject our root cert there, like we have for others such as browsers and openssl.
Otherwise I'll have to find a way to pass it through Milvus on a case-by-case basis
