### ISSUE TITLE
undefined symbol: __atomic_compare_exchange_1 on riscv64

### ISSUE THREAD

**Issue by grubles** [grpc/grpc#35839]
On riscv it seems grpcio runs into a similar issue as https://github.com/grpc/grpc/issues/20400?

grpcio version 1.59.2
Ubuntu 22.04
riscv64

```
python3 -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-grpc-proto/pyln/grpc/ --grpc_python_out=contrib/pyln-grpc-proto/pyln/grpc/ --experimental_allow_proto3_optional                                                                
Traceback (most recent call last):                                                         
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main    
    return _run_code(code, main_globals, None,              
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code 
    exec(code, run_globals)                
  File "/home/user/.cache/pypoetry/virtualenvs/cln-meta-project-YocaCd4z-py3.10/lib/python3.10/site-packages/grpc_tools/protoc.py", line 20, in <module>
    from grpc_tools import _protoc_compiler                                                
ImportError: /home/user/.cache/pypoetry/virtualenvs/cln-meta-project-YocaCd4z-py3.10/lib/python3.10/site-packages/grpc_tools/_protoc_compiler.cpython-310-riscv64-linux-gnu.so: undefined symbol: __atomic_compare_exchange_1                                                     
make: *** [Makefile:388: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Error 1
```

**Comment by gnossen** [comment]
As much as I'd love to, we don't officially support RISC-V. But if you're willing to contribute a patch, we'd happily accept it.

**Comment by XuanWang-Amos** [comment]
Glad to hear it's solved, closing this issue.
