### ISSUE TITLE
ResourceWarning: unclosed <socket.socket fd=15, family=1, type=1, proto=0>

### ISSUE THREAD

**Issue by mukund-ananthu** [grpc/grpc#35974]
Encountering `ResourceWarning: unclosed <socket.socket fd=15, family=1, type=1, proto=0>`

### What version of gRPC and what language are you using?
Language: Python 3.10
gRPC: 1.62.0

### What operating system (Linux, Windows,...) and version?
Linux

Observing failures:
```
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/common.pyx.pxi", line 184, in grpc._cython.cygrpc.get_working_loop
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/common.pyx.pxi", line 190, in grpc._cython.cygrpc.get_working_loop
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/asyncio/events.py", line 697, in get_event_loop
    warnings.warn('There is no current event loop',
DeprecationWarning: There is no current event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen _collections_abc>", line 804, in get
ResourceWarning: unclosed <socket.socket fd=26, family=1, type=1, proto=0>
FAILED tests/unit/gapic/pubsub_v1/test_publisher.py::test_publisher_client_client_api_endpoint[PublisherClient] - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=1, type=1, proto=0>

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/functools.py", line 54, in update_wrapper
    pass
ResourceWarning: unclosed <socket.socket fd=18, family=1, type=1, proto=0>
```

Issue doesn't appear with python 3.11 and older, and only appears in the latest release

**Comment by XuanWang-Amos** [comment]
Can you share more information about how the test is set up?

I'm seeing `Exception ignored` message, but we're intentionally ignore DeprecationWarning for Python 3.12.

**Comment by parthea** [comment]
I was able to re-create the resource warning with the following code. The warning doesn't appear if I don't include grpc create channel options

```
import grpc
from grpc import aio
print(grpc.__version__)

import google.auth
import google.auth.credentials
import google.auth.transport.grpc
import google.auth.transport.requests

default_scopes=('https://www.googleapis.com/auth/cloud-platform','https://www.googleapis.com/auth/pubsub')
credentials = google.auth.credentials.with_scopes_if_required(
            google.auth.credentials.AnonymousCredentials(), scopes=[], default_scopes=default_scopes
        )
request = google.auth.transport.requests.Request()
default_host='pubsub.googleapis.com'
metadata_plugin = google.auth.transport.grpc.AuthMetadataPlugin(
        credentials,
        request,
        default_host=default_host,
    )
google_auth_credentials = grpc.metadata_call_credentials(metadata_plugin)
target ='pubsub.googleapis.com:443'
grpc_creds = grpc.compute_engine_channel_credentials(google_auth_credentials)
options=[('grpc.max_send_message_length', -1), ('grpc.max_receive_message_length', -1), ('grpc.max_metadata_size', 4194304), ('grpc.keepalive_time_ms', 30000)]
aio.secure_channel(
        target, grpc_creds, options
    )
aio.secure_channel(
        target, grpc_creds, options
    )
aio.secure_channel(
        target, grpc_creds, options
    )
```

```
1.62.0
/usr/local/google/home/partheniou/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by XuanWang-Amos** [comment]
@parthea I tried your code and not able to reproduce in both 3.12.0 and 3.12.1, is there other setup required to reproduce the issue?

**Comment by parthea** [comment]
@XuanWang-Amos 

Please can you try this code sample instead?

The following packages are needed
`google-auth`
`requests`

```
import grpc
from grpc import aio
print(grpc.__version__)

import google.auth
import google.auth.credentials
import google.auth.transport.grpc
import google.auth.transport.requests

default_scopes=('https://www.googleapis.com/auth/cloud-platform','https://www.googleapis.com/auth/pubsub')
credentials = google.auth.credentials.with_scopes_if_required(
            google.auth.credentials.AnonymousCredentials(), scopes=[], default_scopes=default_scopes
        )
request = google.auth.transport.requests.Request()
default_host='pubsub.googleapis.com'
metadata_plugin = google.auth.transport.grpc.AuthMetadataPlugin(
        credentials,
        request,
        default_host=default_host,
    )
google_auth_credentials = grpc.metadata_call_credentials(metadata_plugin)
target ='pubsub.googleapis.com:443'
grpc_creds = grpc.compute_engine_channel_credentials(google_auth_credentials)
options=[('grpc.max_send_message_length', -1), ('grpc.max_receive_message_length', -1), ('grpc.max_metadata_size', 4194304), ('grpc.keepalive_time_ms', 30000)]
aio.secure_channel(
        target, grpc_creds, options
    )
aio.secure_channel(
        target, grpc_creds, options
    )
aio.secure_channel(
        target, grpc_creds, options
    )
```

**Comment by parthea** [comment]
I see the errors when I exit the python terminal
```
>>> exit()
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by parthea** [comment]
I can still reproduce the issue with https://github.com/grpc/grpc/issues/35974#issuecomment-1961617612, but the error only appears when I exit the terminal.

```
>>> 
>>> aio.secure_channel("http://localhost/", grpc.local_channel_credentials()) 
<grpc.aio._channel.Channel object at 0x7fefed7d1e50>
>>> aio.secure_channel("http://localhost/", grpc.local_channel_credentials()) 
<grpc.aio._channel.Channel object at 0x7fefed7d0ec0>
>>> aio.secure_channel("http://localhost/", grpc.local_channel_credentials()) 
<grpc.aio._channel.Channel object at 0x7fefed7d1be0>
>>> aio.secure_channel("http://localhost/", grpc.local_channel_credentials()) 
<grpc.aio._channel.Channel object at 0x7fefed7d1e50>
>>> aio.secure_channel("http://localhost/", grpc.local_channel_credentials()) 
<grpc.aio._channel.Channel object at 0x7fefed7d0ec0>
>>> exit()
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/asyncio/base_events.py:703: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
```
