### ISSUE TITLE
gRPC Crashes when destructor of grpc server is called

### ISSUE THREAD

**Issue by saurabhjangir** [grpc/grpc#36397]
### What version of gRPC and what language are you using?
v1.60.x [commit : 0ef13a7555dbaadd4633399242524129eef5e231]

### What operating system (Linux, Windows,...) and version?
Linux 5.4.17-2136.328.3.el7uek.x86_64 

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC: (GNU) 11.4.0

### What did you do?
When unique pointer to the grpc server is going out of the scope, It calls destructor of grpc server which is crashing.

### What did you expect to see?
grpc server is destructed successfully without a crash.

### What did you see instead?

Getting following backtraces 
```
#0  0x0000ffff7fce1ec8 in ?? () from /lib/libc.so.6
#1  0x0000ffff7fc9dd50 in raise () from /lib/libc.so.6
#2  0x0000ffff7fc8af64 in abort () from /lib/libc.so.6
#3  0x0000ffff7ff24d10 in ?? () from /usr/lib/libmtwo.so.0
#4  0x0000ffff7ff250c0 in free () from /usr/lib/libmtwo.so.0
#5  0x0000ffff44d113fc in std::default_delete<grpc_core::channelz::PerCpuCallCountingHelper::PerCpuData []>::operator()<grpc_core::channelz::PerCpuCallCountingHelper::PerCpuData> (__ptr=<optimized out>, this=<optimized out>) at /usr/include/c++/11.4.0/bits/unique_ptr.h:116
#6  std::unique_ptr<grpc_core::channelz::PerCpuCallCountingHelper::PerCpuData [], std::default_delete<grpc_core::channelz::PerCpuCallCountingHelper::PerCpuData []> >::~unique_ptr (this=0xffff284e0288, __in_chrg=<optimized out>) at /usr/include/c++/11.4.0/bits/unique_ptr.h:612
#7  grpc_core::PerCpu<grpc_core::channelz::PerCpuCallCountingHelper::PerCpuData>::~PerCpu (this=0xffff284e0278, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/per_cpu.h:83
#8  grpc_core::channelz::PerCpuCallCountingHelper::~PerCpuCallCountingHelper (this=0xffff284e0278, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/channel/channelz.h:142
#9  grpc_core::channelz::ServerNode::~ServerNode (this=0xffff284e0230, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/channel/channelz.cc:273
#10 0x0000ffff44d1148c in grpc_core::channelz::ServerNode::~ServerNode (this=0xffff284e0230, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/channel/channelz.cc:273
#11 0x0000ffff44ead4c0 in grpc_core::UnrefDelete::operator()<grpc_core::channelz::BaseNode> (p=0xffff284e0230, this=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/ref_counted.h:222
#12 grpc_core::RefCounted<grpc_core::channelz::BaseNode, grpc_core::PolymorphicRefCount, grpc_core::UnrefDelete>::Unref (this=0xffff284e0230)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/ref_counted.h:299
#13 grpc_core::RefCounted<grpc_core::channelz::BaseNode, grpc_core::PolymorphicRefCount, grpc_core::UnrefDelete>::Unref (this=0xffff284e0230)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/ref_counted.h:297
#14 grpc_core::RefCountedPtr<grpc_core::channelz::ServerNode>::~RefCountedPtr (this=0xffff283fac80, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/ref_counted_ptr.h:107
#15 grpc_core::Server::~Server (this=0xffff283fac60, __in_chrg=<optimized out>) at /localdisk/ELS/95/grpc/src/core/lib/surface/server.cc:811
#16 0x0000ffff44ead868 in grpc_core::Server::~Server (this=0xffff283fac60, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/surface/server.cc:799
#17 grpc_core::UnrefDelete::operator()<grpc_core::Server> (p=0xffff283fac60, this=<optimized out>)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/ref_counted.h:223
#18 grpc_core::InternallyRefCounted<grpc_core::Server, grpc_core::UnrefDelete>::Unref (this=0xffff283fac60)
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/orphanable.h:102
#19 grpc_core::InternallyRefCounted<grpc_core::Server, grpc_core::UnrefDelete>::Unref (this=0xffff283fac60)
--Type <RET> for more, q to quit, c to continue without paging--
    at /localdisk/ELS/95/grpc/src/core/lib/gprpp/orphanable.h:100
#20 grpc_core::Server::Orphan (this=0xffff283fac60) at /localdisk/ELS/95/grpc/src/core/lib/surface/server.cc:1135
#21 0x0000ffff44eaf3ac in grpc_server_destroy (server=0xffff283fac60) at /localdisk/ELS/95/grpc/src/core/lib/surface/server.cc:1966
#22 0x0000ffff4518a878 in grpc::Server::~Server (this=0xffff284cec00, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/cpp/server/server_cc.cc:996
#23 0x0000ffff4518abd8 in grpc::Server::~Server (this=0xffff284cec00, __in_chrg=<optimized out>)
    at /localdisk/ELS/95/grpc/src/cpp/server/server_cc.cc:997
<Application traces>
```
Following logs are seen in application logs
```
 mtwo[26979]: Failed to verify head: ptr 0x7f08880eae00 size 149 (0)
```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment]
We've got bunch of tests around this so my initial reaction is that there's a bug in the usage. Can you provide your code as a gist maybe?

**Comment by saurabhjangir** [comment]
I think this is caused by the wrapper lib I am using for alloc and free functions to track the memory usage. 

#4  0x0000ffff7ff250c0 in free () from /usr/lib/**libmtwo.so.0**

When running without this library, gRPC is working fine. Thanks
