### ISSUE TITLE
PHP auth interop tests use illegal header key

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3671]
`E1006 17:46:31.705709438     410 call.c:1036]                attempt to send invalid metadata key: Authorization`

This is most likely because C core prohibits metadata keys with capital letters. s/Authorization/authorization/

Full log:
```
Running test case jwt_token_creds
E1006 17:46:31.705709438     410 call.c:1036]                attempt to send invalid metadata key: Authorization
PHP Fatal error:  Uncaught exception 'LogicException' with message 'start_batch was called incorrectly' in /var/local/git/grpc/src/php/lib/Grpc/UnaryCall.php:57
Stack trace:
#0 /var/local/git/grpc/src/php/lib/Grpc/UnaryCall.php(57): Grpc\Call->startBatch(Array)
#1 /var/local/git/grpc/src/php/lib/Grpc/BaseStub.php(181): Grpc\UnaryCall->start(Object(grpc\testing\SimpleRequest), Array, Array)
#2 /var/local/git/grpc/src/php/tests/interop/test.php(23): Grpc\BaseStub->_simpleRequest('/grpc.testing.T...', Object(grpc\testing\SimpleRequest), '\\grpc\\testing\\S...', Array, Array)
#3 /var/local/git/grpc/src/php/tests/interop/interop_client.php(93): grpc\testing\TestServiceClient->UnaryCall(Object(grpc\testing\SimpleRequest))
#4 /var/local/git/grpc/src/php/tests/interop/interop_client.php(154): performLargeUnary(Object(grpc\testing\TestServiceClient), true, true)
#5 /var/local/git/grpc/src/php/tests/interop/interop_client.php(389): jwtTokenCreds(Object(grpc\testing\TestServiceClient), Array)
#6 {main}
  thrown in /var/local/git/grpc/src/php/lib/Grpc/UnaryCall.php on line 57
```

**Comment by stanley-cheung** [comment]
May be the same issue as #3206

**Comment by stanley-cheung** [comment]
The error is now fixed. The PHP Auth interop test is now runnable on the `master` branch

```
~/grpc/src/php$ GOOGLE_APPLICATION_CREDENTIALS=$HOME/var/oauth_certs/stubby\
CloudTestingTest-7dd63462c60c.json SSL_CERT_FILE=$HOME/var/cacerts/roots.pem $HOME/grpc/src/php/bin\
/interop_client.sh --server_host grpc-test.sandbox.google.com --server_port 443 --test_case service\
_account_creds --oauth_scope https://www.googleapis.com/auth/xapi.zoo --server_host_override grpc-t\
est.sandbox.google.com
D1012 11:12:17.148488221   24714 channel.c:170]              Initialized secure channel
Connecting to grpc-test.sandbox.google.com
Running test case service_account_creds
D1012 11:12:17.686557225   24714 frame_settings.c:231]       adding 983041 for initial_window chang\
e
```
