### ISSUE TITLE
Grpc request failing with "onStreamError" on enabling ssl and http2

### ISSUE THREAD

**Issue by ShivaniSK** [grpc/grpc#36750]
```
<html>
<body>
<!--StartFragment-->
May 29, 2024 7:30:55 AM io.grpc.netty.NettyServerHandler onStreamError
--
  | WARNING: Stream Error
  | io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
  | at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:173)
  | at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481)
  | at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105)
  | at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)

<!--EndFragment-->
</body>
</html>
```

**Comment by ShivaniSK** [comment]
Closing as figured out the issue was with the gateway from where the request was coming.
