### ISSUE TITLE
Grpc.Tools 2.64 fails on macOS arm64 (Apple silicone) machines

### ISSUE THREAD

**Issue by AArnott** [grpc/grpc#36836]
### What version of gRPC and what language are you using?

Grpc.Tools 2.64 nuget package

### What operating system (Linux, Windows,...) and version?

macOS Sonoma (14.5)

### What runtime / compiler are you using (e.g. python version or version of gcc)

The nuget package is running in the context of MSBuild, as part of the .NET 8 SDK.

### What did you do?

I'm building a C# program that references the gRPC.Tools nuget package.

### What did you expect to see?

A successful build, as I see on Windows, Linux, and x64 mac machines.

### What did you see instead?

The build failed, because the msbuild target tried to invoke an x64 `protoc` tool instead of one built for macOS arm64:

```
/Users/buildagent/myagent/_work/_temp/.nuget/packages/grpc.tools/2.64.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: The specified task executable "/Users/buildagent/myagent/_work/_temp/.nuget/packages/grpc.tools/2.64.0/tools/macosx_x64/protoc" could not be run. System.ComponentModel.Win32Exception (86): An error occurred trying to start process '/Users/buildagent/myagent/_work/_temp/.nuget/packages/grpc.tools/2.64.0/tools/macosx_x64/protoc' with working directory '/Users/buildagent/myagent/_work/1/s/src/Nerdbank.Zcash'. Bad CPU type in executable
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.Build.Utilities.ToolTask.StartToolProcess(Process proc)
   at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute() [/Users/buildagent/myagent/_work/1/s/src/Nerdbank.Zcash/Nerdbank.Zcash.csproj]
```

### Anything else we should know about your project / environment?

Apparently the nuget package lacks a `macosx_arm64` toolset, so the correct choice couldn't have been made by the `ProtoToolsPlatform` msbuild task anyway. 
Since all new macOS hardware ships with Apple Silicone (i.e. arm64), this nuget package should be updated to include macOS arm64 tools or we can't build projects on that hardware.

**Comment by marcoeg** [comment]
having a similar problem in building for macos apple arm.

Output (tail) from the 'pip install':
```
...
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/zlib/include -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX=\"Python\" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX=\"1.41.0\" -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 "-DPyMODINIT_FUNC=extern \"C\" __attribute__((visibility (\"default\"))) PyObject*" -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_darwin -Ithird_party/re2 -I/usr/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -I/usr/include -I/Users/marco/Development/ntoplabs/HackMentor/venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c third_party/re2/util/rune.cc -o python_build/temp.macosx-13.0-arm64-cpython-311/third_party/re2/util/rune.o -std=c++11 -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -DHAVE_UNISTD_H -pthread
      creating None
      creating None/var
      creating None/var/folders
      creating None/var/folders/tq
      creating None/var/folders/tq/pq23_1150_q5my3yj45w7wkw0000gn
      creating None/var/folders/tq/pq23_1150_q5my3yj45w7wkw0000gn/T
      creating None/var/folders/tq/pq23_1150_q5my3yj45w7wkw0000gn/T/tmpnsgf_cwq
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/zlib/include -I/Users/marco/Development/ntoplabs/HackMentor/venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/tq/pq23_1150_q5my3yj45w7wkw0000gn/T/tmpnsgf_cwq/a.c -o None/var/folders/tq/pq23_1150_q5my3yj45w7wkw0000gn/T/tmpnsgf_cwq/a.o
      Traceback (most recent call last):
        File "/Users/marco/Development/ntoplabs/HackMentor/venv/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/tq/pq23_1150_q5my3yj45w7wkw0000gn/T/pip-install-y67mp_mb/grpcio_5150c9bf29f64e54ba50c26283d8fcb8/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/marco/Development/ntoplabs/HackMentor/venv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/Users/marco/Development/ntoplabs/HackMentor/venv/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
```

**Comment by AArnott** [comment]
I found that installing `Rosetta` solved the problem. Apparently with just that, macOS will automatically emulate for running x64 executables, without even having to switch modes explicitly.

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

Still, the less software that requires rosetta to be installed, the better. And Grpc.Tools could work by default for more users if it offered osx-arm64 binaries.

**Comment by marcoeg** [comment]
> I found that installing `Rosetta` solved the problem. Apparently with just that, macOS will automatically emulate for running x64 executables, without even having to switch modes explicitly.
> 
> ```
> /usr/sbin/softwareupdate --install-rosetta --agree-to-license
> ```
> 
> Still, the less software that requires rosetta to be installed, the better. And Grpc.Tools could work by default for more users if it offered osx-arm64 binaries.

Not solving it in my case because rosetta is installed:
```
$ pgrep oahd
536
```

**Comment by tonydnewell** [comment]
Grpc.Tools only supports x64 binaries for MacOS - but these should work on MacOS arm64 when using Rosetta.
See [BUILD-INTEGRATION.md](https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#getting-started)

See also https://github.com/grpc/grpc/issues/32006#issuecomment-1369942650

**Comment by AArnott** [comment]
That's what I figured out too. Consider this a request for arm64 support via arm64 binaries. If that's not on the table, then feel free to close the issue, since I'm unblocked using the technique you mentioned, @tonydnewell.
Thanks.

**Comment by yashykt** [comment]
This seems like something that should go on grpc/grpc-dotnet. I wasn't able to transfer this myself. @tonydnewell can I leave it to you to do that please?

**Comment by tonydnewell** [comment]
@yashykt At the moment `Grpc.Tools` is built in this repository, so this is the right place for bug reports.

There are too many dependencies to easily move `Grpc.Tools` to grpc/grpc-dotnet, e.g. building the protoc and plugin binaries, distrib tests, codegen tests.  Maybe one day it can be moved.

**Comment by yashykt** [comment]
got it, thanks @tonydnewell

**Comment by chadlwilson** [comment]
Is there anything in particular blocking this or making this difficult that anyone knows of, or perhaps can be tackled by an outside contributor not at Google?

This is literally the only among hundreds of dev tools I use that don't still don't have native arm64 packaged builds. I prefer to not install Rosetta as you cannot remove or disable it safely and I found it allows sub-optimal workflows to remain hidden (e.g tools downloading/installing wrong arch etc) in confusing ways.

**Comment by jjmanton** [comment]
I took at stab at fixing this with #41222 . If it can get some attention from the google team, we can eliminate Rosetta!

**Comment by chadlwilson** [comment]
That would be very nice!
