### ISSUE TITLE
subprocess.Popen Hangs (again)

### ISSUE THREAD

**Issue by matejsp** [grpc/grpc#37259]
### What version of gRPC and what language are you using?
Python

grpcio = "==1.64.1"
grpcio-reflection = "==1.64.1"

tried also versions: 1.59.0, 1.60.1, 1.64.1, 1.65.1

### What operating system (Linux, Windows,...) and version?
MacOSX M3 Max (Sonoma 14.5)

### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 3.11.9

### What did you do?
We tried calling GRPC via grpc-reflection using it in [robotframework](https://robotframework.org/). We were surprised that any grpc call resulted in python dead locked.

I created one reproducable:
```
import grpc
from grpc_reflection.v1alpha.proto_reflection_descriptor_database import (
    ProtoReflectionDescriptorDatabase,
)
import subprocess


if __name__ == '__main__':
    with grpc.insecure_channel("localhost:51058") as channel:
        reflection_db = ProtoReflectionDescriptorDatabase(channel)
        services = reflection_db.get_services()
        print(f"found services: {services}")

    for i in range(9999999):
        print("Start echo")
        p = subprocess.Popen(["/bin/echo", "Hello", "world"])
        print("Waiting for echo")
        p.wait()
        print("Echo return code: {}".format(p.returncode))

```

### What did you expect to see?
Normally working subprocess.POpen

### What did you see instead?
Process is dead locked and unable to even cancel it via Ctrl + C in terminal.
We have two different grpc servers. 

The funny thing is that connecting from client to one server works without a problem ... But the second server always freezes the clients subprocess.Popen ...
Both grpc servers are in Go using the same grpc version (1.49.0).
The client connection to second server does not dead lock when stepping though via python debugger.

I saw similar old issue https://github.com/grpc/grpc/issues/17986 ... that was supposedly fixed ... but for us it behaves the same as this bug ... I found a lot of closed issues with forking (https://github.com/grpc/grpc/issues/13873). I don't understand why grpc CLIENT is messing up with unrelated subprocesses that has nothing to do with grpc.

I tried debugging GRPC_TRACE=tcp,http,api python testgrpcbug.py but didn't get any output. If you need more info I can provide it to you.

**Comment by matejsp** [comment]
Even replacing call to reflection with direct call creates the same issue:
```
    with grpc.insecure_channel("localhost:50058") as channel:
        stub = balance_data_pb2_grpc.BalanceDataStub(channel)
        print(stub.GetUserBalance(request))
```

Output is stuck at "Start echo" and won't continue without killing the process.

**Comment by sreenithi** [comment]
Hi @matejsp , Python gRPC versions before 1.50.0 are known to be affected by this issue. As you mentioned that you used gRPC Go version 1.49.0 for the servers, can you try with a newer version and see if it is still the case.

**Comment by matejsp** [comment]
@sreenithi 
We are not using python version 1.49.0. We are connecting to grpc server written in Golang that uses 1.49.0 ...

Python client side that I tested was using versions: 1.59.0, 1.60.1, 1.64.1, 1.65.1 and all off them with hanging subprocesses.
Are you saying that older SERVER version can DDOS latest python CLIENT?

**Comment by gnossen** [comment]
> Are you saying that older server version can DDOS/crash latest python client?

No, we were just making sure that the reported versions of gRPC Python used were correct since we had seen similar symptoms in previous versions, but not in recent versions. If this is legitimately an issue in recent versions of gRPC Python, we take it very seriously and want to resolve the issue.

**Comment by matejsp** [comment]
Ok :D

I tried to quickly update golang grpc server to latest but I am having some troubles in go code with
ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules ...
When I manage to resolve it I will try again with different server version.

But it seems like python grpc client dead locking issue to me. Because even after I close all the channels it still locks subprocess.Popen

**Comment by matejsp** [comment]
I have managed to upgrade problematic grpc server written in go to: google.golang.org/grpc v1.65.0

But the problem is still the same using the above code.
It is wierd that connecting to one grpc server works and to the other python client freezes using the same configuration.

I have made minimal grpc server that triggers the issue for me at least on MacOSX (Sonoma 14.5) M3 

```
package main

import (
	"fmt"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
	"log"
	"net"
)

func main() {
	port := 51058
	lis, err := net.Listen("tcp", fmt.Sprintf("localhost:%d", port))
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	var opts []grpc.ServerOption

	grpcServer := grpc.NewServer(opts...)
	reflection.Register(grpcServer)

	grpcServer.Serve(lis)
}
```

Issue is the same for sample server code using 1.59.0 or 1.65.0

Output is frozen at:
```
found services: ['grpc.reflection.v1.ServerReflection', 'grpc.reflection.v1alpha.ServerReflection']
Start echo
```

**Comment by sreenithi** [comment]
Hi @matejsp, thank you for investigating the different server and client combinations. Glad to know that having both server and client in Python is working. 
So this issue is possibly something that comes up when doing a cross-language interaction, and we will further look into this issue.

**Comment by matejsp** [comment]
No problem. If you need anything more I can try.

One side note ... when testing using debugger (python client) the code worked.
So perhaps because python is a lot slower we maybe hit some race condition with native code servers.

**Comment by sreenithi** [comment]
Hi @matejsp, we require some more information to investigate this issue. Could you provide us with a docker image with the reproduction of the issue.
And also please share the core logs with us. You can enable core logs by setting the following variables:  `GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`

**Comment by matejsp** [comment]
I tested on Mac M3 directly ... Not sure that Linux has the same issue (I can try with docker if its the same issue on linux).

**Comment by matejsp** [comment]
I have tried to prepare docker image and indeed inside docker and it works:
```
docker run -it amazonlinux:2023.5.20240722.0
dnf install -y python3.11 python3.11-pip golang

curl -O https://gist.githubusercontent.com/matejsp/5370277/raw/5ae82745086f0b11781411145a9f88f16767ac00/main.go
curl -O https://gist.githubusercontent.com/matejsp/5370277/raw/5ae82745086f0b11781411145a9f88f16767ac00/runme.py

go mod init http://example.com/m
go get google.golang.org/grpc@latest
go mod tidy
go build
nohup ./m & 

pip3.11 install grpcio==1.65.1 grpcio-reflection==1.65.1
python3.11 runme.py
```

**Comment by matejsp** [comment]
But running the same code on my Mac M3:

```
mkdir grpclockingissue
cd grpclockingissue 
curl -O https://gist.githubusercontent.com/matejsp/5370277/raw/5ae82745086f0b11781411145a9f88f16767ac00/main.go
curl -O https://gist.githubusercontent.com/matejsp/5370277/raw/5ae82745086f0b11781411145a9f88f16767ac00/runme.py

go mod init example.com/m
go get google.golang.org/grpc@latest
go mod tidy
go build
nohup ./m & 

pip3.11 install grpcio==1.65.1 grpcio-reflection==1.65.1 --index-url https://pypi.python.org/simple
python3.11 runme.py
```

and output with immediate freeze where grpc client process is so broken that even Ctrl + C does not work ...
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   396  100   396    0     0   5766      0 --:--:-- --:--:-- --:--:--  5739
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   627  100   627    0     0   8697      0 --:--:-- --:--:-- --:--:--  8830
go: creating new go.mod: module example.com/m
go: to add module requirements and sums:
	go mod tidy
go: added golang.org/x/net v0.25.0
go: added golang.org/x/sys v0.20.0
go: added golang.org/x/text v0.15.0
go: added google.golang.org/genproto/googleapis/rpc v0.0.0-20240528184218-531527333157
go: added google.golang.org/grpc v1.65.0
go: added google.golang.org/protobuf v1.34.1
[1] 71608
appending output to nohup.out
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: grpcio==1.65.1 in /opt/homebrew/lib/python3.11/site-packages (1.65.1)
Requirement already satisfied: grpcio-reflection==1.65.1 in /opt/homebrew/lib/python3.11/site-packages (1.65.1)
Requirement already satisfied: protobuf<6.0dev,>=5.26.1 in /opt/homebrew/lib/python3.11/site-packages (from grpcio-reflection==1.65.1) (5.27.2)

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1722144485.539878 4150761 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
I0000 00:00:1722144485.541833 4150762 subchannel.cc:806] subchannel 0x146686b10 {address=ipv6:%5B::1%5D:51058, args={grpc.client_channel_factory=0x600001b741e0, grpc.default_authority=localhost:51058, grpc.internal.channel_credentials=0x600001b741d0, grpc.internal.client_channel_call_destination=0x1107b7618, grpc.internal.event_engine=0x600001b74580, grpc.internal.security_connector=0x600000c71380, grpc.internal.subchannel_pool=0x600003270620, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x600001770960, grpc.server_uri=dns:///localhost:51058}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (61) {created_time:"2024-07-28T07:28:05.541003+02:00"}), backing off for 999 ms
found services: ['grpc.reflection.v1.ServerReflection', 'grpc.reflection.v1alpha.ServerReflection']
Start echo
I0000 00:00:1722144485.542889 4150761 work_stealing_thread_pool.cc:320] WorkStealingThreadPoolImpl::PrepareFork
```


Now the funny part is that with tracing enabled ... the code DOES NOT LOCK
```
GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check python3.11 runme.py > output.log
```

So it seems some kind of race condition and explains why in debugger the code was working.
[output.log](https://github.com/user-attachments/files/16402331/output.log)

**Comment by matejsp** [comment]
@sreenithi 
I have tested with version 1.66.0 and it seems that the issue is solved (including excessive logging) and I don't see the issue anymore.

```
pip3.11 install grpcio==1.66.0 grpcio-reflection==1.66.0 --index-url https://pypi.python.org/simple
```

When reinstalling 1.65.1 the issue reapears. So it seems that latest version fixed this issue.

**Comment by sourabhsinghs** [comment]
@matejsp  Thanks . I was also able to verify issue is resolved in 1.66.0 . 
Folks facing same issue , Please upgrade to version >= 1.66.0 . Closing the issue.

**Comment by matejsp** [comment]
I can confirm the issue with python server and python client. The client hangs every 1/10 tries for me (using Mac M3 Max). Unable to kill it with ctrl+c. It has the same symptoms as original issue.

Interesting that the combination with golang server and python client is ok.

Perhaps if grpc maintainers can reopening or file for separate issue.

**Comment by matejsp** [comment]
I can reproduce the issue with 1.59.0rc1 and now I got this exception running python request (leaving it hang for couple of minutes but closing server).

1.68.1:
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1735019978.479540 14153219 work_stealing_thread_pool.cc:281] Check failed: queue_.Empty() 
Traceback (most recent call last):
  File "/Users/myuser/temp/grpclockingissue/request.py", line 16, in <module>
    p = subprocess.Popen(["/bin/echo", "Hello", "world"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1885, in _execute_child
*** Check failure stack trace: ***
    @        0x104782100  absl::lts_20240722::log_internal::LogMessage::SendToLog()
    @        0x104781cd0  absl::lts_20240722::log_internal::LogMessage::Flush()
    @        0x1047824ac  absl::lts_20240722::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x1047824bc  absl::lts_20240722::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x1048480c8  grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::Quiesce()
    @        0x104424a34  grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::Quiesce()
    @        0x104415ee8  grpc_event_engine::experimental::PosixEventEngine::~PosixEventEngine()
    @        0x1044161b8  grpc_event_engine::experimental::PosixEventEngine::~PosixEventEngine()
    @        0x10442e068  really_destroy()
    @        0x10442dffc  grpc_combiner_continue_exec_ctx()
    @        0x104435094  grpc_core::ExecCtx::Flush()
    @        0x1045ea908  grpc_core::WorkSerializer::DispatchingWorkSerializer::Run()
    @        0x1044267d4  grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step()
    @        0x10442636c  grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody()
    @        0x104426ca8  grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke()
    @        0x1045dff04  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::__invoke()
    @        0x1851e5f94  _pthread_start
    @        0x1851e0d34  thread_start
[1]    60163 abort      python request.py
```

grpcio 1.69rc1
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1735020672.649620 14168862 work_stealing_thread_pool.cc:239] Check failed: !IsQuiesced() 
Hello world
*** Check failure stack trace: ***
    @        0x1057f9a38  absl::lts_20240722::log_internal::LogMessage::Flush()
    @        0x1057fa298  absl::lts_20240722::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x1057fa2a8  absl::lts_20240722::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x105a14448  grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::Run()
    @        0x1054900d4  grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::Run()
    @        0x10548fff0  grpc_event_engine::experimental::WorkStealingThreadPool::Run()
    @        0x10548c814  grpc_event_engine::experimental::TimerManager::RestartPostFork()
    @        0x105476794  grpc_event_engine::experimental::ObjectGroupForkHandler::PostforkParent()
    @        0x1851e580c  _pthread_atfork_parent_handlers
    @        0x18509ed14  fork
    @        0x1024a6b38  do_fork_exec
    @        0x1024a6630  subprocess_fork_exec
    @        0x102a9aa18  cfunction_call
    @        0x102a50140  _PyObject_MakeTpCall
    @        0x102b2c2d8  _PyEval_EvalFrameDefault
    @        0x102b30684  _PyEval_Vector
    @        0x102a503e8  _PyObject_FastCallDictTstate
    @        0x102ab9e04  slot_tp_init
    @        0x102ab22e4  type_call
    @        0x102a50140  _PyObject_MakeTpCall
    @        0x102b2c2d8  _PyEval_EvalFrameDefault
    @        0x102b21608  PyEval_EvalCode
    @        0x102b77eac  run_eval_code_obj
    @        0x102b77e10  run_mod
    @        0x102b77c50  pyrun_file
    @        0x102b776a0  _PyRun_SimpleFileObject
    @        0x102b7702c  _PyRun_AnyFileObject
    @        0x102b93a9c  pymain_run_file_obj
    @        0x102b933e0  pymain_run_file
    @        0x102b92cac  Py_RunMain
    @        0x102b93dec  Py_BytesMain
    @        0x184e5b154  start
```

**Comment by sreenithi** [comment]
Hi @matejsp we haven't looked into this issue yet, we will check and get back to you with an update soon

**Comment by matejsp** [comment]
@sreenithi any update on the issue. This is a major blocker for us.

**Comment by sreenithi** [comment]
Hi @matejsp , unfortunately we haven't had the chance to investigate from the Python side yet. However there is some active work in Core for fork support. I would like to check if that helps in solving the issue.
Meanwhile, if possible please continue to use v1.67.1 where the issue was temporarily resolved

**Comment by matejsp** [comment]
I understand. Thank you for the update. Stability is the key for us.
We are really struggling keeping grpcio up to date because this happens a lot and is a major issue for us.

Can you please link me with the release when ready that would solve this.

**Comment by marcosfrenkel** [comment]
I am having the same issue as other people have commented. I went back to version 1.66.0 and my gRPC server does not hang anymore, everything seems to be working. I am getting these messages now printed between my calls: 

```I0000 00:00:1758600708.896289   25055 fork_posix.cc:75] Other threads are currently calling into gRPC, skipping fork() handlers```

Not entirely sure what that means, but just hoping it gives some info

**Comment by asheshvidyut** [comment]
Hey @marcosfrenkel and @matejsp can you please try the repro code on latest version.

I tried using the repro code but did not see any hang. Please confirm at your end as well.

In particular please try `1.78.0` and `1.78.1`. 

Thanks.

**Comment by matejsp** [comment]
Looks like 1.78.1 is already deemed broken with solving hangs and was already yanked released in pypi. 
Also seeing lots of reports of hangs in latest release ... sigh ...

We have just started testing internally 1.78.0, but it seems that 1.78.1 would be better fit to fix the issue if it would work ... 
I can try with 1.78.0 but it seems that fork logic will be changed yet again creating a possible instability (after fixing 1.78.1). 
So I would like to confirm that it works after fixing 1.78.1 hanging issues.

**Comment by matejsp** [comment]
I tried on mac m4 pro, and couldn't reproduce the problem with 1.78.0 and also not with 1.78.1.
The interesting thing is that I couldn't reproduce the issue with 1.68.1 while in the past I could (on mac m3 max. But I could reproduce it with 1.64.1.

**Comment by asheshvidyut** [comment]
Since this issue is not reproducible anymore, I am closing this now. 

But please feel free to reopen this issue, in case you see hangs.

cc @matejsp @marcosfrenkel
