### ISSUE TITLE
Windows PYTHON3_BIN_PATH use the wrong slash

### ISSUE THREAD

**Issue by jackshi0912** [grpc/grpc#37273]
### What version of gRPC and what language are you using?
1.65.1

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
python3.12.3

### What did you do?
Try to use grpc via bazel. In my WORKSPACE, I have this target.
```
http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-1.65.1",
    urls = [
        #        "https://github.com/grpc/grpc/archive/refs/tags/v1.41.1.tar.gz",
        "https://github.com/grpc/grpc/archive/refs/tags/v1.65.1.tar.gz",
    ],
)
```

### What did you expect to see?
Bazel not failing with 
```
  C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:335:21: in grpc_deps
  C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl:30:21: in grpc_python_deps
Repository rule python_configure defined at:
  C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/third_party/py/python_configure.bzl:354:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 344, column 35, in _python_autoconf_impl
		_create_single_version_package(
	File "C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 293, column 26, in _create_single_version_package
		_check_python_bin(repository_ctx,
	File "C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 226, column 18, in _check_python_bin
		_fail("--define %s='%s' is not executable. Is it the python binary?" %
	File "C:/users/jackshi0912/_bazel_jackshi0912/o2a4rd2e/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 33, column 9, in _fail
		fail("%sPython Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Python Configuration Error: --define PYTHON3_BIN_PATH='C:/Python312/python.exe' is not executable. Is it the python binary?
```

### Anything else we should know about your project / environment?
I think that the issue is `C:/Python312/python.exe`. The correct path should be `C:\Python312\python.exe` since `\` is used on windows.

**Comment by sreenithi** [comment]
Hi @jackshi0912, PYTHON3_BIN_PATH seems to be an environment variable. Can you try manually setting the path to `C:\Python312\python.exe` in your workspace and retry

**Comment by jackshi0912** [comment]
I set it to `C:\Python312\python.exe` on my machine (previously not set) and nothing has changed. Maybe this is bazel behaviour and not grpc specific?

**Comment by jackshi0912** [comment]
Even if I use `register_toolchains` in my workspace to specify a custom `py_runtime` it still doesn't work.

**Comment by sreenithi** [comment]
Hi @jackshi0912, unfortunately we don't claim support for building gRPC Python in Windows using Bazel as of now. We'll be happy to accept PRs to add support for the same.
