### ISSUE TITLE
"Comparison method violates its general contract" when cloning repo on Jenkins

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3736]
https://grpc-testing.appspot.com/job/gRPC_master/7999/console

```
FATAL: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:747)
	at java.util.TimSort.mergeAt(TimSort.java:483)
	at java.util.TimSort.mergeCollapse(TimSort.java:410)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8200)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8164)
	at org.codehaus.groovy.runtime.dgm$728.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.jenkinsci.plugins.ScriptRunner.run(ScriptRunner.groovy:31)
	at org.jenkinsci.plugins.ScriptRunner$run.call(Unknown Source)
	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:40)
	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:45)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:352)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:301)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Finished: FAILURE
```

**Comment by nicolasnoble** [comment]
@ejona86 do you think you could give us some advice on that one ?

**Comment by ejona86** [comment]
Something is being sorted and its compareTo method is inconsistent. That code seems to be quite different upstream now. Maybe should update to a newer version.

**Comment by jtattermusch** [comment]
Alright, so I think I tracked down the root cause.

The problem is in Matrix Execution Strategy Plugin, which is the plugin that runs our simple groovy script to determine the configurations of the matrix job that should (or shouldn't be) run. (see Project -> Configure -> Execution strategy)

Links to source code based on the call stack that prove the problem is in matrix execution strategy plugin:
https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/ScriptRunner.groovy#L29
https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/GroovyScriptMES.groovy#L62
https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/BaseMES.groovy#L51
https://github.com/jenkinsci/matrix-project-plugin/blob/matrix-project-1.6/src/main/java/hudson/matrix/MatrixBuild.java#L352

The most interesting part is https//github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/ScriptRunner.groovy#L29, which tries to shuffle List<Combination> by invoking `c.sort { Math.random() }`. The comparator returns a random number each time, which violates the contract of a comparator if the sorting algorithm happens to invoke comparison for the same two numbers twice. 
Actually, Math.random() always returns a positive number, so the line is a very broken way to shuffle a collection.

The call stack:
```
FATAL: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:868)
	at java.util.TimSort.mergeAt(TimSort.java:485)
	at java.util.TimSort.mergeCollapse(TimSort.java:410)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8200)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8164)
	at org.codehaus.groovy.runtime.dgm$728.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.jenkinsci.plugins.ScriptRunner.run(ScriptRunner.groovy:29)
	at org.jenkinsci.plugins.ScriptRunner$run.call(Unknown Source)
	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:62)
	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:51)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:352)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:301)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by jtattermusch** [comment]
Version 1.0.3 of https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Groovy+Execution+Strategy+Plugin has been released. Now upgrading Jenkins to newer version of this plugin.
