### ISSUE TITLE
[Python install]

### ISSUE THREAD

**Issue by MarioCaricato** [grpc/grpc#37716]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mario\\AppData\\Local\\Temp\\pip-install-g4wrcy0u\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mario\\AppData\\Local\\Temp\\pip-install-g4wrcy0u\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mario\AppData\Local\Temp\pip-record-fuof4bya\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\
    Complete output (195 lines):
    ASM Builds for BoringSSL currently not supported on: win32
    Found cython-generated files...
    running install
    running build
    running build_py
    running build_project_metadata
    creating pyb
    creating pyb\lib.win32-3.7
    creating pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_auth.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_channel.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_common.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_compression.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_grpcio_metadata.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_interceptor.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_observability.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_plugin_wrapping.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_runtime_protos.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_server.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_simple_stubs.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_typing.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\_utilities.py -> pyb\lib.win32-3.7\grpc
    copying src\python\grpcio\grpc\__init__.py -> pyb\lib.win32-3.7\grpc
    creating pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_base_call.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_base_channel.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_base_server.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_call.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_channel.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_interceptor.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_metadata.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_server.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_typing.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\_utils.py -> pyb\lib.win32-3.7\grpc\aio
    copying src\python\grpcio\grpc\aio\__init__.py -> pyb\lib.win32-3.7\grpc\aio
    creating pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\implementations.py -> pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\interfaces.py -> pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\utilities.py -> pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_client_adaptations.py -> pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_metadata.py -> pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\_server_adaptations.py -> pyb\lib.win32-3.7\grpc\beta
    copying src\python\grpcio\grpc\beta\__init__.py -> pyb\lib.win32-3.7\grpc\beta
    creating pyb\lib.win32-3.7\grpc\experimental
    copying src\python\grpcio\grpc\experimental\gevent.py -> pyb\lib.win32-3.7\grpc\experimental
    copying src\python\grpcio\grpc\experimental\session_cache.py -> pyb\lib.win32-3.7\grpc\experimental
    copying src\python\grpcio\grpc\experimental\__init__.py -> pyb\lib.win32-3.7\grpc\experimental
    creating pyb\lib.win32-3.7\grpc\framework
    copying src\python\grpcio\grpc\framework\__init__.py -> pyb\lib.win32-3.7\grpc\framework
    creating pyb\lib.win32-3.7\grpc\_cython
    copying src\python\grpcio\grpc\_cython\__init__.py -> pyb\lib.win32-3.7\grpc\_cython
    creating pyb\lib.win32-3.7\grpc\experimental\aio
    copying src\python\grpcio\grpc\experimental\aio\__init__.py -> pyb\lib.win32-3.7\grpc\experimental\aio
    creating pyb\lib.win32-3.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\cardinality.py -> pyb\lib.win32-3.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\style.py -> pyb\lib.win32-3.7\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\__init__.py -> pyb\lib.win32-3.7\grpc\framework\common
    creating pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\future.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\__init__.py -> pyb\lib.win32-3.7\grpc\framework\foundation
    creating pyb\lib.win32-3.7\grpc\framework\interfaces
    copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> pyb\lib.win32-3.7\grpc\framework\interfaces
    creating pyb\lib.win32-3.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> pyb\lib.win32-3.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> pyb\lib.win32-3.7\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> pyb\lib.win32-3.7\grpc\framework\interfaces\base
    creating pyb\lib.win32-3.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> pyb\lib.win32-3.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> pyb\lib.win32-3.7\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> pyb\lib.win32-3.7\grpc\framework\interfaces\face
    creating pyb\lib.win32-3.7\grpc\_cython\_cygrpc
    copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> pyb\lib.win32-3.7\grpc\_cython\_cygrpc
    creating pyb\lib.win32-3.7\grpc\_cython\_credentials
    copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> pyb\lib.win32-3.7\grpc\_cython\_credentials
    running build_ext
    Non-fatal exception:Traceback (most recent call last):
      File "C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\src\python\grpcio\commands.py", line 262, in compiler_ok_with_extra_std
        stderr=subprocess.PIPE,
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

    Found cython-generated files...
    building 'grpc._cython.cygrpc' extension
    Traceback (most recent call last):
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\src\python\grpcio\commands.py", line 313, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\setup.py", line 615, in <module>
        cmdclass=COMMAND_CLASS,
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\src\python\grpcio\commands.py", line 316, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\src\python\grpcio\support.py", line 130, in diagnose_build_ext_error
        " backtrace).\n\n{}".format(type(error), formatted)
    commands.CommandError:

    We could not diagnose your build failure with type <class 'distutils.errors.DistutilsPlatformError'>. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).

    Traceback (most recent call last):
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Mario\AppData\Local\Temp\pip-install-g4wrcy0u\grpcio\src\python\grpcio\commands.py", line 313, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Mario\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mario\\AppData\\Local\\Temp\\pip-install-g4wrcy0u\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mario\\AppData\\Local\\Temp\\pip-install-g4wrcy0u\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mario\AppData\Local\Temp\pip-record-fuof4bya\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 24.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Mario\Desktop\16 Farmbot>cd source

C:\Users\Mario\Desktop\16 Farmbot\source>python bot.py
windows_win32_x32_AMD64_3.7.5rc1
Traceback (most recent call last):
  File "bot.py", line 54, in <module>
    import main
ImportError: DLL load failed: %1 non è un'applicazione di Win32 valida.

C:\Users\Mario\Desktop\16 Farmbot\source>pause
Premere un tasto per continuare . . .

**Comment by MarioCaricato** [comment]
i resolved
