### ISSUE TITLE
realloc SIGABRT signal ClientReaderWriterInterface::Read when updating to 1.60.1

### ISSUE THREAD

**Issue by mahbabu** [grpc/grpc#37797]
### What version of gRPC and what language are you using?
1.60.1

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

starting grpc client server  connection
restarting the system 
on restart we are closing grpc connection using m_context->TryCancel();

### What did you expect to see?
on cancel it should close the conenction without any SIGABRT

### What did you see instead?
SIGABRT is triggered with the below mentioned callstack :

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x0000007fa67e04a0 in __GI_abort () at abort.c:79
#2  0x0000007fa682c808 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fa68edd20 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x0000007fa683455c in malloc_printerr (str=str@entry=0x7fa68ea048 "realloc(): invalid pointer") at malloc.c:5389
#4  0x0000007fa68393ac in __GI___libc_realloc (oldmem=0x7f0dffacb0, bytes=78580181677824) at malloc.c:3195
#5  0x0000007fa67a0978 in gpr_realloc (p=<optimized out>, size=<optimized out>) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/gpr/alloc.cc:54
#6  0x0000007fabf95460 in grpc_core::FilterStackCall::PublishAppMetadata (this=this@entry=0x7f34004530, b=b@entry=0x7f34004da0, is_trailing=is_trailing@entry=true) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/surface/call.cc:1195
#7  0x0000007fabf95a04 in grpc_core::FilterStackCall::RecvTrailingFilter (this=0x7f34004530, b=0x7f34004da0, batch_error=...) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/surface/call.cc:1242
#8  0x0000007fabf96130 in grpc_core::FilterStackCall::BatchControl::ReceivingTrailingMetadataReady (this=0x7f3400ab70, error=...) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/surface/call.cc:1491
#9  0x0000007fabf96274 in grpc_core::FilterStackCall::<lambda(void*, grpc_error_handle)>::operator() (__closure=0x0, error=..., bctl=<optimized out>) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/surface/call.cc:1832
#10 grpc_core::FilterStackCall::<lambda(void*, grpc_error_handle)>::_FUN(void *, grpc_error_handle) () at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/surface/call.cc:1832
#11 0x0000007fabe92b04 in exec_ctx_run (closure=0x7f340053f0) at /usr/include/absl/status/status.h:902
#12 grpc_core::ExecCtx::Flush (this=0x7fa2068f78) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/iomgr/exec_ctx.cc:84
#13 0x0000007fabe884d0 in end_worker (pollset=pollset@entry=0x7f9c014b38, worker=worker@entry=0x7fa2068da0, worker_hdl=worker_hdl@entry=0x7fa2068f08) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/iomgr/ev_epoll1_linux.cc:980
#14 0x0000007fabe88ef4 in pollset_work (ps=0x7f9c014b38, worker_hdl=0x7fa2068f08, deadline=...) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/iomgr/ev_epoll1_linux.cc:1048
#15 0x0000007fabe8dfa0 in pollset_work (pollset=0x7f9c014b38, worker=0x7fa2068f08, deadline=...) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/iomgr/ev_posix.cc:249
#16 0x0000007fabe972d8 in grpc_pollset_work (pollset=<optimized out>, worker=<optimized out>, deadline=...) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/iomgr/pollset.cc:48
#17 0x0000007fabfb41ac in cq_pluck (cq=0x7f9c014940, tag=0x7fa2069180, deadline=..., reserved=<optimized out>) at /usr/src/debug/grpc/1.60.1-r0/git/src/core/lib/surface/completion_queue.cc:1283
#18 0x0000007faa1d496c in grpc::CompletionQueue::Pluck (tag=0x7fa2069180, this=0x7f9c00d468) at /usr/include/grpcpp/completion_queue.h:322
#19 grpc::ClientReader<com::dm::rpc::DeviceManagerMbientApiCallBack>::Read (msg=0x7fa2069118, this=0x7f9c00d450) at /usr/include/grpcpp/support/sync_stream.h:215

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by eugeneo** [comment]
Please provide more detailed code example to reproduce the code.
