### ISSUE TITLE
Bazel build fails on ARM based Mac OS X

### ISSUE THREAD

**Issue by vii** [grpc/grpc#37860]
### What version of gRPC and what language are you using?

gRPC 1.66.2

### What operating system (Linux, Windows,...) and version?

Mac OS X arm (M1). Rosetta is installed.

### What runtime / compiler are you using (e.g. python version or version of gcc)

`bazel build ...`

### What did you see instead?

```
ERROR: /Users/fremlin/grpc-1.66.2/third_party/toolchains/rbe_ubuntu2004/cc/BUILD:47:19: in cc_toolchain_suite rule //third_party/toolchains/rbe_ubuntu2004/cc:toolchain: cc_toolchain_suite '//third_party/toolchains/rbe_ubuntu2004/cc:toolchain' does not contain a toolchain for cpu 'darwin_arm64'
ERROR: /Users/fremlin/grpc-1.66.2/third_party/toolchains/rbe_ubuntu2004/cc/BUILD:47:19: Analysis of target '//third_party/toolchains/rbe_ubuntu2004/cc:toolchain' failed
```

**Comment by vii** [comment]
I tried to build that.

```
$ bazel build  //:grpc++
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 7.1.0 will be used instead of system-wide bazel installation.
INFO: Repository local_config_apple_cc instantiated at:
  /Users/fremlin/grpc-1.66.2/WORKSPACE:11:16: in <toplevel>
  /Users/fremlin/grpc-1.66.2/bazel/grpc_extra_deps.bzl:64:31: in grpc_extra_deps
  /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/lib/repositories.bzl:59:23: in apple_support_dependencies
  /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/setup.bzl:61:23: in apple_cc_configure
Repository rule _apple_cc_autoconf defined at:
  /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/setup.bzl:45:37: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_apple_cc':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/setup.bzl", line 39, column 49, in _apple_cc_autoconf_impl
		success, error = configure_osx_toolchain(repository_ctx)
	File "/private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/osx_cc_configure.bzl", line 167, column 21, in configure_osx_toolchain
		_compile_cc_file(repository_ctx, libtool_check_unique_src_path, "libtool_check_unique")
	File "/private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/osx_cc_configure.bzl", line 85, column 13, in _compile_cc_file
		fail(out_name + " failed to generate. Please file an issue at " +
Error in fail: libtool_check_unique failed to generate. Please file an issue at https://github.com/bazelbuild/apple_support/issues with the following:
return code 1, stderr: /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/libtool_check_unique.cc:15:10: fatal error: 'cstdlib' file not found
   15 | #include <cstdlib>
      |          ^~~~~~~~~
1 error generated.
, stdout:
ERROR: /Users/fremlin/Junk/grpc-1.66.2/WORKSPACE:11:16: fetching _apple_cc_autoconf rule //external:local_config_apple_cc: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/setup.bzl", line 39, column 49, in _apple_cc_autoconf_impl
		success, error = configure_osx_toolchain(repository_ctx)
	File "/private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/osx_cc_configure.bzl", line 167, column 21, in configure_osx_toolchain
		_compile_cc_file(repository_ctx, libtool_check_unique_src_path, "libtool_check_unique")
	File "/private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/osx_cc_configure.bzl", line 85, column 13, in _compile_cc_file
		fail(out_name + " failed to generate. Please file an issue at " +
Error in fail: libtool_check_unique failed to generate. Please file an issue at https://github.com/bazelbuild/apple_support/issues with the following:
return code 1, stderr: /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/libtool_check_unique.cc:15:10: fatal error: 'cstdlib' file not found
   15 | #include <cstdlib>
      |          ^~~~~~~~~
1 error generated.
, stdout:
ERROR: no such package '@@local_config_apple_cc//': libtool_check_unique failed to generate. Please file an issue at https://github.com/bazelbuild/apple_support/issues with the following:
return code 1, stderr: /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/libtool_check_unique.cc:15:10: fatal error: 'cstdlib' file not found
   15 | #include <cstdlib>
      |          ^~~~~~~~~
1 error generated.
, stdout:
ERROR: /Users/fremlin/grpc-1.66.2/BUILD:920:16: //:grpc++ depends on @@local_config_apple_cc//:cc-compiler-darwin_arm64 in repository @@local_config_apple_cc which failed to fetch. no such package '@@local_config_apple_cc//': libtool_check_unique failed to generate. Please file an issue at https://github.com/bazelbuild/apple_support/issues with the following:
return code 1, stderr: /private/var/tmp/_bazel_fremlin/e77ab4a53be31bdafb566f2ab8f7dd7e/external/build_bazel_apple_support/crosstool/libtool_check_unique.cc:15:10: fatal error: 'cstdlib' file not found
   15 | #include <cstdlib>
      |          ^~~~~~~~~
1 error generated.
, stdout:
ERROR: Analysis of target '//:grpc++' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.698s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

I tried to add the brew libtool like this ` export PATH=$HOME/homebrew/bin:/Users/fremlin/homebrew/opt/libtool/libexec/gnubin:$PATH` 


Now `which libtool` is `/Users/fremlin/homebrew/opt/libtool/libexec/gnubin/libtool`


The same error comes up.

**Comment by eugeneo** [comment]
`cstdlib` is a standard header so this means your environment is messed up. My guess is that XCode is missing (that's how Apple distributes the compiler, standard library and such). See details - https://github.com/grpc/grpc/blob/master/BUILDING.md#macos

It might also be that there's something wrong in environment variables. Make sure you don't have files like `~/.bazelrc` that may interfere with the build process.

**Comment by eugeneo** [comment]
(Looks like Bazel is not using installed libtool but builds one itself)
