### ISSUE TITLE
contextvars-based value is not propagated from async interceptor to sync handler

### ISSUE THREAD

**Issue by denik** [grpc/grpc#37881]
### What version of gRPC and what language are you using?

1.68.0.dev0
41dc97e1d66f32d95fdf016641164d9f7dc6fb94
Python

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.9.18
gcc (Debian 8.3.0-6) 8.3.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue 
once you have a reproduction.

```
$ cat test_interceptor_contextvar.py
import os
import asyncio
import contextvars
import grpc
import greeting_pb2
import greeting_pb2_grpc


log = []
context_var = contextvars.ContextVar("request_id", default=None)
USE_SYNC = int(os.environ.get('USE_SYNC', 0))


class ContextVarsInterceptor(grpc.aio.ServerInterceptor):
    async def intercept_service(self, continuation, handler_call_details):
        context_var.set("my_request_id")
        return await continuation(handler_call_details)


class GreeterServicer(greeting_pb2_grpc.GreeterServicer):
    def _impl(self, request, context):
        request_id = context_var.get()
        log.append(request_id)
        response = greeting_pb2.HelloReply()
        response.message = f"Hello, {request.name}! Request ID: {request_id}"
        return response

    if USE_SYNC:
        print('Using sync method')
        def SayHello(self, request, context):
            return self._impl(request, context)
    else:
        print('Using async method')
        async def SayHello(self, request, context):
            return self._impl(request, context)


async def start_server():
    server = grpc.aio.server(interceptors=[ContextVarsInterceptor()])
    greeting_pb2_grpc.add_GreeterServicer_to_server(GreeterServicer(), server)
    port = server.add_insecure_port('[::]:0')
    await server.start()
    return server, port


async def run_client(port):
    async with grpc.aio.insecure_channel(f'localhost:{port}') as channel:
        stub = greeting_pb2_grpc.GreeterStub(channel)
        response = await stub.SayHello(greeting_pb2.HelloRequest(name='Name'))
        log.append(response.message)


async def main():
    server, port = await start_server()
    await run_client(port)
    await asyncio.sleep(2)
    await server.stop(0)
    print(f'{log=}')
    assert log == ['my_request_id', 'Hello, Name! Request ID: my_request_id'], log

if __name__ == "__main__":
    # Run the asyncio event loop
    asyncio.run(main())
```

### What did you expect to see?

Contextvar value set in interceptor should be visible to handler, regardless of whether it is async or sync.

### What did you see instead?

When sync method is used, contextvar value is not visible.

```
$ python3 test_interceptor_contextvar.py
Using async method
log=['my_request_id', 'Hello, Name! Request ID: my_request_id']

$ USE_SYNC=1 python3 test_interceptor_contextvar.py
Using sync method
log=[None, 'Hello, Name! Request ID: None']
Traceback (most recent call last):
  File "/home/user/grpc/test_interceptor_contextvar.py", line 63, in <module>
    asyncio.run(main())
  File "/home/user/.pyenv/versions/3.9.18/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/user/.pyenv/versions/3.9.18/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/user/grpc/test_interceptor_contextvar.py", line 59, in main
    assert log == ['my_request_id', 'Hello, Name! Request ID: my_request_id'], log
AssertionError: [None, 'Hello, Name! Request ID: None']

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by denik** [comment]
This patch seems to fix this test:

```
diff --git a/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi b/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi
index 8332c5a0d5..2df89c86a4 100644
--- a/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi
+++ b/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi
@@ -414,7 +414,7 @@ async def _finish_handler_with_unary_response(RPCState rpc_state,
         sync_servicer_context = _SyncServicerContext(servicer_context)
         response_message = await loop.run_in_executor(
             rpc_state.server.thread_pool(),
-            unary_handler,
+            _run_with_context(unary_handler),
             request,
             sync_servicer_context,
         )
diff --git a/src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi b/src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi
index be4cb8b9a8..ba0267589e 100644
--- a/src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi
+++ b/src/python/grpcio/grpc/_cython/_cygrpc/thread.pyx.pxi
@@ -50,10 +50,10 @@ if _contextvars_supported():
     def _run_with_context(target):
         ctx = contextvars.copy_context()
         def _run(*args):
-            ctx.run(target, *args)
+            return ctx.run(target, *args)
         return _run
 else:
     def _run_with_context(target):
         def _run(*args):
-            target(*args)
+            return target(*args)
         return _run
```
