### ISSUE TITLE
`pip install grpcio` on Python 3.13 Alpine is unable to find precompiled version

### ISSUE THREAD

**Issue by jensenbox** [grpc/grpc#38008]
### What version of gRPC and what language are you using?
3.13 - From the `python:3-alpine` image

### What operating system (Linux, Windows,...) and version?
Mac osx Sequoia 15.0 - M3 Pro - this may be a CPU Architecture problem - not tested in x86

### What runtime / compiler are you using (e.g. python version or version of gcc)
None

### What did you do?
    docker run -ti python:3-alpine sh
    pip install grpcio

### What did you expect to see?
Install from the precompiled version - without the need for a compiler to be installed

### What did you see instead?
```
❯ docker run -ti python:3-alpine sh
Unable to find image 'python:3-alpine' locally
3-alpine: Pulling from library/python
Digest: sha256:c38ead8bcf521573dad837d7ecfdebbc87792202e89953ba8b2b83a9c5a520b6
Status: Downloaded newer image for python:3-alpine
/ # pip install grpcio
Collecting grpcio
  Downloading grpcio-1.67.0.tar.gz (12.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 8.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-blm7dfdg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-blm7dfdg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-blm7dfdg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-blm7dfdg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 274, in <module>
        File "<string>", line 218, in check_linker_need_libatomic
        File "/usr/local/lib/python3.13/subprocess.py", line 1036, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              pass_fds, cwd, env,
                              ^^^^^^^^^^^^^^^^^^^
          ...<5 lines>...
                              gid, gids, uid, umask,
                              ^^^^^^^^^^^^^^^^^^^^^^
                              start_new_session, process_group)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.13/subprocess.py", line 1966, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'c++'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
/ # 
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

### Anything else we should know about your project / environment?
I am on an Apple M3 Pro chip

**Comment by jensenbox** [comment]
yea - I just tested on an x86 and it works as expected. This is most certainly a CPU architecture issue.

```
root@homelab:~# docker run -ti python:3-alpine sh
Unable to find image 'python:3-alpine' locally
3-alpine: Pulling from library/python
43c4264eed91: Already exists 
99a612635ae6: Pull complete 
ea644e5aaa5c: Pull complete 
ae04b12910c8: Pull complete 
Digest: sha256:c38ead8bcf521573dad837d7ecfdebbc87792202e89953ba8b2b83a9c5a520b6
Status: Downloaded newer image for python:3-alpine
/ # pip install grpcio
Collecting grpcio
  Downloading grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl.metadata (3.9 kB)
Downloading grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 11.9 MB/s eta 0:00:00
Installing collected packages: grpcio
Successfully installed grpcio-1.67.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
/ # 
```

**Comment by sreenithi** [comment]
Hi @jensenbox it does look like a CPU architecture issue as you described. I haven't tried on a Mac, but wasn't able to reproduce it on a Debian Linux x86_64 machine. While we further check the issue, can you try manually downloading the `grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl` file and installing it in the docker container.
```
wget https://files.pythonhosted.org/packages/9e/a8/96b3ef565791d7282c300c07c2a7080471311e7d5a239db15678aaac47eb/grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl
pip install grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl
```

**Comment by sourabhsinghs** [comment]
@jensenbox  we need some dependency. use this
```
docker run -ti python:3-alpine sh
apk update
apk add build-base linux-headers protoc
pip install grpcio
```

**Comment by jensenbox** [comment]
> @jensenbox we need some dependency. use this
> 
> ```
> docker run -ti python:3-alpine sh
> apk update
> apk add build-base linux-headers protoc
> pip install grpcio
> ```

I can confirm that this worked perfectly - no compilation and a speedy install. Thank you!

### Important

I was able to simplify the instructions to simply issue an `apk update` rather than having to install the other APKs:

```
christian@christian-desktop:/projects/core$ docker run -ti --rm --env PIP_ROOT_USER_ACTION=ignore python:3-alpine sh
Unable to find image 'python:3-alpine' locally
3-alpine: Pulling from library/python
43c4264eed91: Pull complete 
99a612635ae6: Pull complete 
ea644e5aaa5c: Pull complete 
ae04b12910c8: Pull complete 
Digest: sha256:c38ead8bcf521573dad837d7ecfdebbc87792202e89953ba8b2b83a9c5a520b6
Status: Downloaded newer image for python:3-alpine
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
v3.20.3-226-ge6f221129e2 [https://dl-cdn.alpinelinux.org/alpine/v3.20/main]
v3.20.3-225-g23f01f9dae0 [https://dl-cdn.alpinelinux.org/alpine/v3.20/community]
OK: 24166 distinct packages available
/ # pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.13/site-packages (24.2)
Collecting pip
  Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 40.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-24.3.1
/ # pip install grpcio
Collecting grpcio
  Downloading grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl.metadata (3.9 kB)
Downloading grpcio-1.67.0-cp313-cp313-musllinux_1_1_x86_64.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 75.3 MB/s eta 0:00:00
Installing collected packages: grpcio
Successfully installed grpcio-1.67.0
/ #
```

So effectively the process is now:

```
docker run -ti --rm --env PIP_ROOT_USER_ACTION=ignore python:3-alpine sh
apk update
pip install grpcio
```
