### ISSUE TITLE
Windows testing failure due to "file being used by another process."

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#3810]
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/3765/config=opt,language=c,platform=windows/consoleText
```
Started by upstream project "gRPC_pull_requests" build number 3765
originally caused by:
 GitHub pull request #3726 of commit 9e76e7aa3a0d6a8fe95b159177c839f32f3acabb, no merge conflicts.
Building remotely on grpc-jenkins-windows-worker1 (x86_64 i386 windows) in workspace c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows
Wiping out workspace first.
java.io.IOException: remote file operation failed: c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows at hudson.remoting.Channel@6c9027f3:grpc-jenkins-windows-worker1: java.nio.file.FileSystemException: c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows\tmp_htaan: The process cannot access the file because it is being used by another process.

	at hudson.FilePath.act(FilePath.java:987)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.FilePath.deleteContents(FilePath.java:1184)
	at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:28)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1040)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.nio.file.FileSystemException: c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows\tmp_htaan: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at hudson.Util.deleteFile(Util.java:247)
	at hudson.FilePath.deleteRecursive(FilePath.java:1204)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1213)
	at hudson.FilePath.access$1100(FilePath.java:191)
	at hudson.FilePath$15.invoke(FilePath.java:1187)
	at hudson.FilePath$15.invoke(FilePath.java:1184)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2691)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at ......remote call to grpc-jenkins-windows-worker1(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:778)
	at hudson.FilePath.act(FilePath.java:980)
	... 13 more
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level c:\jenkins\workspace\gRPC_pull_requests\config\opt\language\c\platform\windows\reports to /home/jenkins/jenkins_home/jobs/gRPC_pull_requests/configurations/axis-config/opt/axis-language/c/axis-platform/windows/builds/3765/htmlreports/HTML_Report
[copy-to-slave] Copying 'report.xml', excluding nothing, from 'file:/c:/jenkins/workspace/gRPC_pull_requests/config/opt/language/c/platform/windows/' on 'hudson.slaves.DumbSlave[grpc-jenkins-windows-worker1]' to 'file:/home/jenkins/jenkins_home/jobs/gRPC_pull_requests/workspace/' on the master.
Recording test results
ERROR: Publisher 'Publish JUnit test result report' failed: No test report files were found. Configuration error?
Finished: FAILURE
```

**Comment by dgquintas** [comment]
@nicolasnoble

**Comment by jtattermusch** [comment]
This is an instance of #3813
