### ISSUE TITLE
GRPC static libraries linked application crashing in startup

### ISSUE THREAD

**Issue by rameshpasunoori** [grpc/grpc#38125]
### What version of gRPC and what language are you using?
1.65.x and C++

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
[root@rp671005-rk8vm1 SS]# gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

The application that is used as grpc client, built grpc and its dependencies as static lib's and 
Linked to my application, at startup the application crashed.

### What did you expect to see?

Application started and able to communicate grpc Java server.

### What did you see instead?
Application aborted with coredump.

Core was generated by `./SpectroSERVER'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50        return ret;
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f8a095b2e65 in __GI_abort () at abort.c:79
#2  0x0000000000842b79 in grpc_core::Crash(absl::lts_20240116::string_view, grpc_core::SourceLocation) ()
#3  0x0000000000b9fd61 in grpc_core::GlobalInstrumentsRegistry::RegisterInstrument(grpc_core::GlobalInstrumentsRegistry::ValueType, grpc_core::GlobalInstrumentsRegistry::InstrumentType, absl::lts_20 240116::string_view, absl::lts_20240116::string_view, absl::lts_20240116::string_view, bool, absl::lts_20240116::Span<absl::lts_20240116::string_view const>, absl::lts_20240116::Span<absl::lts_20240 116::string_view const>) ()
#4  0x0000000000bc9fff in grpc_core::GlobalInstrumentsRegistry::RegistrationBuilder<(grpc_core::GlobalInstrumentsRegistry::ValueType)2, (grpc_core::GlobalInstrumentsRegistry::InstrumentType)1, 3ul,  0ul>::Build() ()
#5  0x000000000086be1f in __static_initialization_and_destruction_0(int, int) [clone .constprop.383] ()
#6  0x00000000013de66d in __libc_csu_init ()
#7  0x00007f8a095cb778 in __libc_start_main (main=0x876059 <main(int, char**)>, argc=1, argv=0x7ffcaa007968, init=0x13de620 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffcaa007958) at ../csu/libc-start.c:270
#8  0x0000000000875b0e in _start ()

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment]
Would you provide repro so that we can take a look at that?
