### ISSUE TITLE
npm install with error on Jenkins build

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#3823]
Example: https://grpc-testing.appspot.com/job/gRPC_pull_requests/3803/config=opt,language=node,platform=linux/console

```
+ npm install --unsafe-perm

> grpc@0.11.1 install /var/local/git/grpc
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 response dowloading http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
```

**Comment by stanley-cheung** [comment]
Not sure if they are related, but I see a slightly different error on the interop test Jenkins build: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/94/console

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.12.7 | linux | x64
gyp http GET https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
gyp ERR! command "node" "/root/.nvm/versions/node/v0.12.7/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/local/git/grpc
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
+ EXITCODE=1
```
