### ISSUE TITLE
[grpcio>=1.68.0][Backup Poller] Client fails to reconnect after server restart & Sporadic connection failures due to 'ping timeout'

### ISSUE THREAD

**Issue by petur-keystrike** [grpc/grpc#38290]
### What version of gRPC and what language are you using?

Python grpcio 1.68.1

### What operating system (Linux, Windows,...) and version?

Ubuntu 24.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.12

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

server.proto:

```proto
syntax = "proto3";

service Server {
    rpc Method(Message) returns (Message) {}
}

message Message {

}
```

server.py:

```py
from concurrent import futures
import grpc
import server_pb2_grpc


class Server(server_pb2_grpc.ServerServicer):
    def Method(self, request, context):
        return request

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=5))
    server_pb2_grpc.add_ServerServicer_to_server(Server(), server)
    server.add_insecure_port("[::]:50051")
    server.start()
    server.wait_for_termination()

if __name__ == "__main__":
    serve()

```

client.py:

```py
import time
import traceback
import grpc
import server_pb2
import server_pb2_grpc


def main():
    channel = grpc.insecure_channel("localhost:50051")
    stub = server_pb2_grpc.ServerStub(channel)

    message = server_pb2.Message()

    while True:
        try:
            stub.Method(message)    
        except Exception:
            print(traceback.format_exc())
        time.sleep(0.1)


if __name__ == "__main__":
    main()

```

Run the client and server. Once the client is running, kill the server and restart it.

### What did you expect to see?

The client should eventually reconnect to the server after the restart.

### What did you see instead?

The client is unable to reconnect. Instead, it produces this error forever:

```py
Traceback (most recent call last):
  File "/home/petur/work/Keystrike/grpcbug/./client.py", line 16, in main
    stub.Method(message)
  File "/home/petur/work/Keystrike/grpcbug/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petur/work/Keystrike/grpcbug/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::1%5D:50051: Failed to connect to remote host: Timeout occurred: FD Shutdown"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-12-16T10:38:14.390753299+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::1%5D:50051: Failed to connect to remote host: Timeout occurred: FD Shutdown"}"
>
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

With grpcio 1.66.2, the client reconnects as expected.

**Comment by petur-keystrike** [comment]
Also reproduced with 1.68.0, but 1.67.1 seems fine.

**Comment by zeyu-zh** [comment]
We encountered the same issue on grpcio 1.68.0 and python 3.10.

**Comment by petur-keystrike** [comment]
Also reproduced on Windows Server 2022, Python 3.12.2:

```
Traceback (most recent call last):
  File "C:\Users\petur\grpcbug\client.py", line 16, in main
    stub.Method(message)
  File "C:\Users\petur\grpcbug\.venv\Lib\site-packages\grpc\_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\petur\grpcbug\.venv\Lib\site-packages\grpc\_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: socket is null"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-12-17T11:42:20.0855535+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: socket is null"}"
>
```

**Comment by eric-silverberg-spoton** [comment]
I'm able to reproduce this behavior, and it seems that the HTTP/2 connection preface (https://datatracker.ietf.org/doc/html/rfc7540#section-3.5) is not sent when reestablishing the connection if using `grpcio` 1.68.1. `grpcio` 1.67.1 _does_ successfully reestablish the connection by sending the preface. I suspect this is related. See the attached PCAP summaries and timings below. Note the length 82 packets from `tcpdump` and "magic" entries from `tshark`.

[1.68.1_tshark.txt](https://github.com/user-attachments/files/18371493/1.68.1_tshark.txt)
[1.67.1_tcpdump.txt](https://github.com/user-attachments/files/18371495/1.67.1_tcpdump.txt)
[1.67.1_tshark.txt](https://github.com/user-attachments/files/18371496/1.67.1_tshark.txt)
[1.68.1_tcpdump.txt](https://github.com/user-attachments/files/18371497/1.68.1_tcpdump.txt)


Important timings:
v1.67.1 test (works):
- server taken down at approximately 1736488238
- server restored at approximately 1736488259

v1.68.1 test (broken):
- server taken down at approximately 1736471866
- server restored at approximately 1736471878

I can provide additional verbose logs or other information if helpful.

**Comment by sreenithi** [comment]
Thanks for reporting this and providing some detailed analyses. We're currently looking into it and found that a recent change is causing this issue. We'll get back with a fix soon

**Comment by drfloob** [comment]
I can't reproduce this on master @ HEAD. See my example here https://github.com/grpc/grpc/compare/master...drfloob:grpc:repro-38290.

```
bazel build examples/python/repro_38290:all
bazel run examples/python/repro_38290:server  # shell 1
bazel run examples/python/repro_38290:client  # shell 2
```

Once the client begins getting replies, I killed and restarted the server multiple times - the client gets errors, then replies, the errors, cycling ad infinitum.

**Comment by dmo2000** [comment]
I could reproduce this using grpcio 1.71.0, python 3.13 and Windows 10.

**Comment by JC3** [comment]
> Thanks for reporting this and providing some detailed analyses. We're currently looking into it and found that a recent change is causing this issue. We'll get back with a fix soon

@sreenithi Any word on a fix?

**Comment by sergiitk** [comment]
@JC3, we're still working on the fix compatible with older releases. Will post updates here to keep the community informed.

**Comment by sergiitk** [comment]
Merging with #39113.

> The python grpc release `grpcio==1.68.0` introduces a regression that I can consistently reproduce in an Apache Beam pipeline running on Cloud Dataflow.
> 
> In the reproduction, I have two processes: a Python process (client) and a C++ process (server), running in their own docker containers. The processes establish streaming bidirectional RPC channels with each other, and both run on the same vm, connecting to a `localhost:someport` address.
> 
> The client process writes ~15-50 GB of data over network to GCS in a separate thread, while the connection channels with the server owned by other threads.
> 
> If the amount of data written in the side thread crosses a certain threshold (between 10 and 15 GB), the GRPC connections between client and server starts to terminate with errors like:
> 
> `UNKNOWN:Error received from peer ipv6:%!B(MISSING)::1%!D(MISSING):12371 {created_time:\"2024-12-03T13:53:05.992753213+00:00\", grpc_status:14, grpc_message:"ping timeout"`
> 
> **Mitigation**:
> 
> Set an environment variable: `GRPC_EXPERIMENTS="-event_engine_client"` in the environment of the Python process or downgrade to an earlier version of grpc. We are sticking with "grpc<1.66.0" in Apache Beam for now and don't reproduce this error.
> 
> cc: @drfloob, @yashykt @XuanWang-Amos who have started investigating this and might be able to add details and/or rootcause once more information becomes available.
> 
> ### What operating system (Linux, Windows,...) and version?
> Linux.
> 
> Reproducible on `grpcio==1.68.0` and newer, including the current latest version (`grpcio==1.71.0`).
> 
> ### What runtime / compiler are you using (e.g. python version or version of gcc)
> Python 3.10
>
> — @tvalentyn

**Comment by sergiitk** [comment]
PSA: Just released grpc [v1.73.1](https://github.com/grpc/grpc/releases/tag/v1.73.1) containing the fix for this issue. Package [grpcio 1.73.1](https://pypi.org/project/grpcio/1.73.1/) uploaded to PyPi. Please update to the latest version.

**Comment by sergiitk** [comment]
PSA: This issue was fixed in the following releases:

* `v1.73.1`: [pypi](https://pypi.org/project/grpcio/1.73.1), [github release](https://github.com/grpc/grpc/releases/tag/v1.73.1).
* `v1.72.2`: [pypi](https://pypi.org/project/grpcio/1.72.2), [github release](https://github.com/grpc/grpc/releases/tag/v1.72.2).
* `v1.71.2`: [pypi](https://pypi.org/project/grpcio/1.71.2), [github release](https://github.com/grpc/grpc/releases/tag/v1.71.2).

Unfortunately, backporting to `v1.68.x`, `v1.69.x`, and `v1.70.x` has proven difficult, and we currently do not plan to issue patch releases for these versions. We may reconsider this if there is strong community demand. I'll add a warning to the release notes for affected versions.
