### ISSUE TITLE
ASAN use-after-poison in client from v1.55.0

### ISSUE THREAD

**Issue by dubvulture** [grpc/grpc#38302]
See the code example https://github.com/dubvulture/grpc-bug, just a simple client/server scenario with a server streaming RPC.
After version v1.55.0 (inclusive), compiling with `-fsanitize=address` produces `use-after-poison` errors **on the client** when:
- client starts w/o a server
- server is stopped via Ctrl+C

See [logs](https://gist.github.com/dubvulture/d0e18b7c416866c150f67faf641684cd)

I managed to track down the origin of this error from the update to protobuf 23:
- https://github.com/grpc/grpc/pull/32914
- https://github.com/grpc/grpc/pull/33053

### What operating system (Linux, Windows,...) and version?
Debian Testing
Ubuntu 22.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 14.2 on Debian
gcc 11.4 on Ubuntu

EDIT: Same results on Ubuntu 22.04 with different gcc version.

**Comment by eugeneo** [comment]
I was unable to reproduce the bug. I build top of the tree gRPC as described in [quickstart](https://grpc.io/docs/languages/cpp/quickstart/) and then followed your project readme. I manually verified that it used the gRPC I built locally.

Please confirm you followed the gRPC build instructions.

This is my terminal log:
```
$ ./build/bin/server &
[1] 380410
$ ./build/bin/client &
[2] 380522
$ Client_A - HelloStream START
HelloServiceImpl - HelloStream START
Write done
Read done
Write done
Read done
Write done
Read done
Write done
Read done
killWrite done
Read done
 %Write done
Read done
1Write done
Read done

Read failure, break
Client_A - HelloStream END
[1]-  Terminated              ./build/bin/server
$ Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
kill Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
%Client_A - HelloStream START
Read failure, break
Client_A - HelloStream END
2
[2]+  Terminated              ./build/bin/client
```

**Comment by dubvulture** [comment]
I've compiled with cmake 3.30 and 3.31, with:
```bash
cmake \
    -DCMAKE_INSTALL_PREFIX="...." \
    -DCMAKE_CXX_STANDARD=17 \
    -DABSL_PROPAGATE_CXX_STD=ON \
    -DRE2_BUILD_TESTING=OFF \
    -DBUILD_TESTING=OFF \
    -DCARES_BUILD_TOOLS=OFF \
    -DgRPC_BUILD_TESTS=OFF \
    -DgRPC_INSTALL=ON \
    -DgRPC_ZLIB_PROVIDER=module \
    -DgRPC_SSL_PROVIDER=module \
    -DgRPC_PROTOBUF_PROVIDER=module \
    -DgRPC_BUILD_CODEGEN=ON \
    -DgRPC_BUILD_CSHARP_EXT=OFF \
    -DgRPC_BUILD_GRPC_CPP_PLUGIN=ON \
    -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF \
    -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF \
    -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
    -B build \
    -S .
```

I've just retried this from scratch with grpc v1.56.4 and I am able to reproduce the same problems.

**Comment by yashykt** [comment]
A quick sanity check - Do we still see this issue on the later releases?

**Comment by eugeneo** [comment]
I can confirm the issue with CMake and 1.69.0. Does not seem to repro with Bazel so looks like something with the build system, I am still looking.

Bazelified version: https://github.com/eugeneo/grpc-bug
To build:
```
bazel build --config=asan -c dbg //src/...
```

I confirmed ASAN is enabled y making a deliberate mistake.

**Comment by eugeneo** [comment]
This looks like a false positive. The stack trace I am seeing is completely different due to my local env:
```
Thread T9 created by T0 here:
    #0 0x7f1a57eecbb1 in pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x55c101153da3 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0xd24da3) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #2 0x55c1011543b9 in grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0xd253b9) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #3 0x55c100d04983 in grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread() (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d5983) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #4 0x55c100d0457e in grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::Start() (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d557e) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #5 0x55c100d03f5b in grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPool(unsigned long) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d4f5b) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #6 0x55c100d03aa0 in void std::_Construct<grpc_event_engine::experimental::WorkStealingThreadPool, unsigned long&>(grpc_event_engine::experimental::WorkStealingThreadPool*, unsigned long&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d4aa0) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #7 0x55c100d038af in std::_Sp_counted_ptr_inplace<grpc_event_engine::experimental::WorkStealingThreadPool, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<unsigned long&>(std::allocator<void>, unsigned long&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d48af) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #8 0x55c100d036be in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<grpc_event_engine::experimental::WorkStealingThreadPool, std::allocator<void>, unsigned long&>(grpc_event_engine::experimental::WorkStealingThreadPool*&, std::_Sp_alloc_shared_tag<std::allocator<void> >, unsigned long&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d46be) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #9 0x55c100d0361b in std::__shared_ptr<grpc_event_engine::experimental::WorkStealingThreadPool, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<void> >, unsigned long&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d461b) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #10 0x55c100d03528 in std::shared_ptr<grpc_event_engine::experimental::WorkStealingThreadPool>::shared_ptr<std::allocator<void>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<void> >, unsigned long&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d4528) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #11 0x55c100d03491 in std::shared_ptr<std::enable_if<!std::is_array<grpc_event_engine::experimental::WorkStealingThreadPool>::value, grpc_event_engine::experimental::WorkStealingThreadPool>::type> std::make_shared<grpc_event_engine::experimental::WorkStealingThreadPool, unsigned long&>(unsigned long&) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d4491) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #12 0x55c100d03352 in grpc_event_engine::experimental::MakeThreadPool(unsigned long) (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8d4352) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
    #13 0x55c100cd671b in grpc_event_engine::experimental::PosixEventEngine::PosixEventEngine() (/usr/local/google/home/eostroukhov/work/grpc/user-projects/use-after-poison-38302/build/bin/client+0x8a771b) (BuildId: 40f019a35e6b4faef47b396e409ec8fb2cc72925)
```

CMake uses prebuilt gRPC that was not built with sanitizer support and does not have all necessary instrumentations (e.g. ASAN will not know all the valid memory locations). There are some even more significant discrepancies, e.g. see #19224

Bazel build will completely rebuild both the gRPC and the client application with consistent compiler and linker flags.

Please let us know if you may reproduce this with the Bazel.
