### ISSUE TITLE
distutils.errors.UnknownFileError: unknown file type '.s' (from 'third_party\boringssl-with-bazel\src\crypto\curve25519\asm\x25519-asm-arm.s')

### ISSUE THREAD

**Issue by samiulextreem** [grpc/grpc#38370]
### What version of gRPC and what language are you using?
grpcio 1.68.1, python 3.12

### What operating system (Linux, Windows,...) and version?
Windows 11

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.12

### What did you do?
pip.exe install grpcio

### What did you expect to see?
 to be installed  properly

### What did you see instead?
    raise UnknownFileError(f"unknown file type '{ext}' (from '{src_name}')")
      distutils.errors.UnknownFileError: unknown file type '.s' (from 'third_party\boringssl-with-bazel\src\crypto\curve25519\asm\x25519-asm-arm.s')

### Anything else we should know about your project / environment?
I also downloaded the following whl file from pypi but "
grpcio-1.68.1-cp312-cp312-win_amd64.whl" which should be able to be installed , but it trhrows error saying that  unsupported platform.

**Comment by sreenithi** [comment]
Hi @samiulextreem, not sure what can be causing this. As you are on windows, can you try once again by updating pip to the latest version and running `pip.exe install` from a command line that is run as administrator.
Also you mentioned that `grpcio-1.68.1-cp312-cp312-win_amd64.whl` throws an unsupported platform error. Can you confirm if your machine is amd64, and provide the full error message when installing it

**Comment by samiulextreem** [comment]
![image](https://github.com/user-attachments/assets/5ad5809e-6b67-4c4a-a9e1-ac2e44aa283d)
yes, my machine is amd64 for sure. 
```

Collecting grpcio
  Downloading grpcio-1.69.0.tar.gz (12.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 8.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: grpcio
  Building wheel for grpcio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for grpcio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [228 lines of output]
      Found cython-generated files...
      SSE2 not enabled on mingw_x86_64_msvcrt_gnu platform
      running bdist_wheel
      running build
      running build_py
      running build_project_metadata
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_auth.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_channel.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_common.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_compression.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_grpcio_metadata.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_interceptor.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_observability.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_plugin_wrapping.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_runtime_protos.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_server.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_simple_stubs.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_typing.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\_utilities.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      copying src\python\grpcio\grpc\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_call.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_channel.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_server.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_call.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_channel.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_interceptor.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_metadata.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_server.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_typing.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\_utils.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      copying src\python\grpcio\grpc\aio\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\aio
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta
      copying src\python\grpcio\grpc\beta\implementations.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta     
      copying src\python\grpcio\grpc\beta\interfaces.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta
      copying src\python\grpcio\grpc\beta\utilities.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta
      copying src\python\grpcio\grpc\beta\_client_adaptations.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta 
      copying src\python\grpcio\grpc\beta\_metadata.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta
      copying src\python\grpcio\grpc\beta\_server_adaptations.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta 
      copying src\python\grpcio\grpc\beta\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\beta
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\experimental
      copying src\python\grpcio\grpc\experimental\gevent.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\experimental
      copying src\python\grpcio\grpc\experimental\session_cache.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\experimental
      copying src\python\grpcio\grpc\experimental\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\experimental
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework
      copying src\python\grpcio\grpc\framework\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework  
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\_cython
      copying src\python\grpcio\grpc\_cython\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\_cython      
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\experimental\aio
      copying src\python\grpcio\grpc\experimental\aio\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\experimental\aio
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\cardinality.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\style.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\common
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\future.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\foundation
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces
      copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\base
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\framework\interfaces\face
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\_cython\_cygrpc
      copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\_cython\_cygrpc
      creating pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\_cython\_credentials
      copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> pyb\lib.mingw_x86_64_msvcrt_gnu-cpython-312\grpc\_cython\_credentials
      running build_ext
      Found cython-generated files...
      building 'grpc._cython.cygrpc' extension
      Traceback (most recent call last):
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 990, in _make_out_path_exts
          new_ext = extensions[src.suffix]
                    ~~~~~~~~~~^^^^^^^^^^^^
      KeyError: '.s'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-install-6ik3ox1s\grpcio_a10f392db669459bbc0e91686ab847bf\src\python\grpcio\commands.py", line 313, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 481, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 507, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\command\build_ext.py", line 264, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 562, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-install-6ik3ox1s\grpcio_a10f392db669459bbc0e91686ab847bf\src\python\grpcio\_parallel_compile_patch.py", line 55, in _parallel_compile
          macros, objects, extra_postargs, pp_opts, build = self._setup_compile(
                                                            ^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 352, in _setup_compile
          objects = self.object_filenames(sources, strip_dir=False, output_dir=outdir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 963, in object_filenames
          return list(
                 ^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 964, in <genexpr>
          self._make_out_path(output_dir, strip_dir, src_name)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\cygwinccompiler.py", line 229, in _make_out_path
          return super()._make_out_path(output_dir, strip_dir, norm_src_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 973, in _make_out_path
          return self._make_out_path_exts(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 992, in _make_out_path_exts
          raise UnknownFileError(f"unknown file type '{src.suffix}' (from '{src}')")
      distutils.errors.UnknownFileError: unknown file type '.s' (from 'third_party\boringssl-with-bazel\src\crypto\curve25519\asm\x25519-asm-arm.s')

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\Users\GHOSTFISH\Downloads\MAV\lib\python3.12\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\Users\GHOSTFISH\Downloads\MAV\lib\python3.12\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\Users\GHOSTFISH\Downloads\MAV\lib\python3.12\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 597, in <module>
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\core.py", line 202, in run_commands
          dist.run_commands()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\dist.py", line 983, in run_commands
          self.run_command(cmd)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\dist.py", line 993, in run_command
          super().run_command(command)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\dist.py", line 1002, in run_command
          cmd_obj.run()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\command\bdist_wheel.py", line 379, in run
          self.run_command("build")
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\dist.py", line 993, in run_command
          super().run_command(command)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\dist.py", line 1002, in run_command
          cmd_obj.run()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build.py", line 136, in run
          self.run_command(cmd_name)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\dist.py", line 993, in run_command
          super().run_command(command)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\dist.py", line 1002, in run_command
          cmd_obj.run()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\command\build_ext.py", line 99, in run
          _build_ext.run(self)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 365, in run
          self.build_extensions()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-install-6ik3ox1s\grpcio_a10f392db669459bbc0e91686ab847bf\src\python\grpcio\commands.py", line 316, in build_extensions
          support.diagnose_build_ext_error(self, error, formatted_exception)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-install-6ik3ox1s\grpcio_a10f392db669459bbc0e91686ab847bf\src\python\grpcio\support.py", line 125, in diagnose_build_ext_error
          raise commands.CommandError(
      commands.CommandError:

      We could not diagnose your build failure with type <class 'distutils.errors.UnknownFileError'>. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).

      Traceback (most recent call last):
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 990, in _make_out_path_exts
          new_ext = extensions[src.suffix]
                    ~~~~~~~~~~^^^^^^^^^^^^
      KeyError: '.s'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-install-6ik3ox1s\grpcio_a10f392db669459bbc0e91686ab847bf\src\python\grpcio\commands.py", line 313, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 481, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 507, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\command\build_ext.py", line 264, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\command\build_ext.py", line 562, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-install-6ik3ox1s\grpcio_a10f392db669459bbc0e91686ab847bf\src\python\grpcio\_parallel_compile_patch.py", line 55, in _parallel_compile
          macros, objects, extra_postargs, pp_opts, build = self._setup_compile(
                                                            ^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 352, in _setup_compile
          objects = self.object_filenames(sources, strip_dir=False, output_dir=outdir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 963, in object_filenames
          return list(
                 ^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 964, in <genexpr>
          self._make_out_path(output_dir, strip_dir, src_name)
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\cygwinccompiler.py", line 229, in _make_out_path
          return super()._make_out_path(output_dir, strip_dir, norm_src_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 973, in _make_out_path
          return self._make_out_path_exts(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\GHOSTFISH\AppData\Local\Temp\pip-build-env-b4p85q4o\overlay\lib\python3.12\site-packages\setuptools\_distutils\ccompiler.py", line 992, in _make_out_path_exts
          raise UnknownFileError(f"unknown file type '{src.suffix}' (from '{src}')")
      distutils.errors.UnknownFileError: unknown file type '.s' (from 'third_party\boringssl-with-bazel\src\crypto\curve25519\asm\x25519-asm-arm.s')

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
Failed to build grpcio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (grpcio)
```

**Comment by samiulextreem** [comment]
thanks for replying.  There was some problem with venv creation. now it installs correctly. thanks for your attention.
