### ISSUE TITLE
node -v v0.12.2 mac os，install the grpc official example,an error occurred

### ISSUE THREAD

**Issue by chelsh** [grpc/grpc#3874]
i cross-reference this article:http://www.grpc.io/docs/installation/node.html

then run this code:

$ git clone https://github.com/grpc/grpc.git

$ cd examples/node
$ npm install
then happen the follow error:

whwdeMacBook-Pro:node whw$ npm install

/

> grpc@0.11.1 install /Users/whw/grpc

> node-gyp rebuild

usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]

[-e pattern] [-f file] [--binary-files=value] [--color=when]

[--context[=num]] [--directories=action] [--label] [--line-buffered]

[--null] [pattern] [file ...]

gyp: Call to 'node -v | grep -oP "(?<=v)(\d+)(?=\.\d+\.\d+)"' returned exit status 2. while trying to load binding.gyp

gyp ERR! configure error 

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)

gyp ERR! stack     at ChildProcess.emit (events.js:110:17)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

gyp ERR! System Darwin 14.5.0

gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /Users/whw/grpc

gyp ERR! node -v v0.12.2

gyp ERR! node-gyp -v v1.0.3

gyp ERR! not ok 

npm ERR! Darwin 14.5.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

npm ERR! node v0.12.2

npm ERR! npm  v2.7.4

npm ERR! code ELIFECYCLE

npm ERR! grpc@0.11.1 install: `node-gyp rebuild`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.

npm ERR! This is most likely a problem with the grpc package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node-gyp rebuild

npm ERR! You can get their info via:

npm ERR!     npm owner ls grpc

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     /Users/whw/grpc/examples/node/npm-debug.log

**Comment by chelsh** [comment]
any help?

**Comment by murgatroid99** [comment]
Thank you for reporting this. The documentation on the website is actually for the released version of the library, so you can avoid this problem by running `git checkout origin/release-0_11` after the `git clone` step.

**Comment by chelsh** [comment]
```
whwdeMacBook-Pro:node whw$ npm install
npm WARN package.json grpc-demo@0.11.0 No repository field.
\
> grpc@0.11.1 install /Users/whw/grpc/examples/node/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/whw/grpc/examples/node/node_modules/grpc
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whw/grpc/examples/node/npm-debug.log
whwdeMacBook-Pro:node whw$ git branch
* (detached from origin/release-0_11)
  master
whwdeMacBook-Pro:node whw$ 

```

**Comment by chelsh** [comment]
also error:(

**Comment by murgatroid99** [comment]
I understand now. You were actually following outdated instructions. The up-to-date instructions are at https://github.com/grpc/grpc/tree/master/examples/node. Note that you will still have to checkout the release-0_11 branch to get that to work.

The important difference there is that it instructs you to install the gRPC library first, and that depends on Homebrew on Mac.

**Comment by chelsh** [comment]
```
PREREQUISITES

node: This requires Node 10.x or greater.
homebrew on Mac OS X. This simplifies the installation of the gRPC C core.

```


must install homebrew?

**Comment by chelsh** [comment]
bogon:~ whw$ brew --version
0.9.5

－－－－i have installed brew before i cross-reference this article:http://www.grpc.io/docs/installation/node.html

**Comment by chelsh** [comment]
what can i do ?:(

**Comment by chelsh** [comment]
can reopen this issue?

**Comment by murgatroid99** [comment]
Did you try following the instructions I linked?

**Comment by chelsh** [comment]
```
whwdeMacBook-Pro:grpc whw$ git branch
* (detached from origin/release-0_11)
  master
whwdeMacBook-Pro:grpc whw$ node --version
v0.12.2
whwdeMacBook-Pro:grpc whw$ brew --version
0.9.5
whwdeMacBook-Pro:grpc whw$ npm install grpc
-
> grpc@0.11.1 install /Users/whw/grpc/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/whw/grpc/node_modules/grpc
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grpc"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whw/grpc/npm-debug.log

```

**Comment by murgatroid99** [comment]
OK, you also have to install the gRPC core library, as described in https://github.com/grpc/grpc/tree/release-0_11/src/node#installation. The command line to do that is 

```
curl -fsSL https://goo.gl/getgrpc | bash -s nodejs
```

**Comment by chelsh** [comment]
```
whwdeMacBook-Pro:grpc whw$ git branch
* (detached from origin/release-0_11)
  master
whwdeMacBook-Pro:grpc whw$ brew --version
0.9.5
whwdeMacBook-Pro:grpc whw$ curl -fsSL https://goo.gl/getgrpc | bash -s nodejs
Error: undefined method `desc' for Formulary::Formulae::Zlib:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-dupes/zlib.rb:2:in `<class:Zlib>'
/usr/local/Library/Taps/homebrew/homebrew-dupes/zlib.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

```

**Comment by chelsh** [comment]
```

whwdeMacBook-Pro:node whw$ npm install

> grpc@0.11.1 install /Users/whw/grpc/src/node
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/whw/grpc/src/node
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! grpc@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whw/grpc/src/node/npm-debug.log

```

**Comment by murgatroid99** [comment]
This appears to be a bug in our homebrew script. I have reported it.

**Comment by chelsh** [comment]
3Q：）
