### ISSUE TITLE
Jenkins master build failed at grpc-jenkins-windows-worker3 FileSystemException 

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#3877]
The last relatively green master build is https://grpc-testing.appspot.com/job/gRPC_master/8345/ at Oct 15, 2015 8:42:01 PM (since last Thursday night, about 4 days ago). Ever since then (8346 and onward), all the master builds are failing at the very top with this stack trace

```
Started by timer
Building remotely on grpc-jenkins-windows-worker3 (x86_64 i386 windows) in workspace c:\jenkins\workspace\gRPC_master
Wiping out workspace first.
java.io.IOException: remote file operation failed: c:\jenkins\workspace\gRPC_master at hudson.remoting.Channel@6877b8a3:grpc-jenkins-windows-worker3: java.nio.file.FileSystemException: c:\jenkins\workspace\gRPC_master\config\dbg\language\c\platform\windows: The process cannot access the file because it is being used by another process.

	at hudson.FilePath.act(FilePath.java:987)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.FilePath.deleteContents(FilePath.java:1184)
	at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:28)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1040)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:301)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.nio.file.FileSystemException: c:\jenkins\workspace\gRPC_master\config\dbg\language\c\platform\windows: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
```

**Comment by stanley-cheung** [comment]
I tried to log into the instance but couldn't quite figure out what process is locking that file

**Comment by stanley-cheung** [comment]
I restarted the instance `grpc-jenkins-windows-worker3` and looked like the problem goes away. But the issue could come back in the future.

**Comment by stanley-cheung** [comment]
The error only went away for 2 builds

https://grpc-testing.appspot.com/job/gRPC_master/10927/
https://grpc-testing.appspot.com/job/gRPC_master/10928/

The error starts happening again after

https://grpc-testing.appspot.com/job/gRPC_master/10929/

**Comment by stanley-cheung** [comment]
This thread seems relevant: https://issues.jenkins-ci.org/browse/JENKINS-19994. One suggestion in the middle of the thread is to disable the "Wipe out repository & force clone" options in the project configuration.

**Comment by yang-g** [comment]
Seen this again today~

**Comment by stanley-cheung** [comment]
I don't know what was done but this seems to not happen anymore. When a build failed now it's most likely due to #3724.

**Comment by jtattermusch** [comment]
Doesn't look like we're seeing this anymore. Closing this as part of buildpony bankruptcy.
