### ISSUE TITLE
"hudson.remoting.ChannelClosedException: channel is already closed" when starting a test on Jenkins

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#3889]
Seen in several tests in [this PR test run](https://grpc-testing.appspot.com/job/gRPC_pull_requests/3889/):

```
java.io.IOException: remote file operation failed: /home/jenkins/workspace/gRPC_pull_requests@3/config/dbg/language/c/platform/linux at hudson.remoting.Channel@28b5d426:grpc-jenkins-worker7: hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.FilePath.act(FilePath.java:987)
    at hudson.FilePath.act(FilePath.java:969)
    at hudson.FilePath.mkdirs(FilePath.java:1152)
    at hudson.plugins.git.GitSCM.createClient(GitSCM.java:695)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1037)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)
Caused by: hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.remoting.Channel.send(Channel.java:575)
    at hudson.remoting.Request.call(Request.java:130)
    at hudson.remoting.Channel.call(Channel.java:777)
    at hudson.FilePath.act(FilePath.java:980)
    ... 13 more
Caused by: java.io.IOException
    at hudson.remoting.Channel.close(Channel.java:1160)
    at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:118)
    at hudson.remoting.PingThread.ping(PingThread.java:126)
    at hudson.remoting.PingThread.run(PingThread.java:85)
Caused by: java.util.concurrent.TimeoutException: Ping started at 1445299672400 hasn't completed by 1445299912401
    ... 2 more
```

**Comment by hsaliak** [comment]
@nicolasnoble @murgatroid99 is this still relevant?

**Comment by murgatroid99** [comment]
I don't remember seeing it recently.

**Comment by nicolasnoble** [comment]
Alright, let's close that one.

**Comment by adelez** [comment]
Still very much alive: https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5642906408845312

**Comment by adelez** [comment]
Same with PR: https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5759180434571264.

**Comment by hsaliak** [comment]
@adelez is this issue still relevant?

**Comment by adelez** [comment]
Just saw this again: https://grpc-testing.appspot.com/job/gRPC_master_linux/2168/console
