### ISSUE TITLE
Null pointer exception when starting tests on Jenkins

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#3897]
Seen in several test runs in https://grpc-testing.appspot.com/job/gRPC_pull_requests/3895/.

```
originally caused by:
 GitHub pull request #3890 of commit fe3d9ea14ff437961871d11a0fc3da8acaf88105, no merge conflicts.
FATAL: null
java.lang.NullPointerException
	at hudson.model.Slave.createLauncher(Slave.java:375)
	at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:564)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:495)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
```

**Comment by hsaliak** [comment]
Is this still relevant?
