### ISSUE TITLE
node -v v0.12.2, branch:origin/release-0_10 , fatal error: 'grpc/grpc.h' file not found

### ISSUE THREAD

**Issue by chelsh** [grpc/grpc#3904]
```

whwdeMacBook-Pro:grpc whw$ git branch
* (detached from origin/release-0_10)
  master
whwdeMacBook-Pro:grpc whw$ cd examples
whwdeMacBook-Pro:examples whw$ cd node
whwdeMacBook-Pro:node whw$ echo $LDFLAGS
-L/usr/local/lib
whwdeMacBook-Pro:node whw$ echo $CXXFLAGS
-I/usr/local/include
whwdeMacBook-Pro:node whw$ npm install
npm WARN package.json grpc-demo@0.5.0 No repository field.
|
> grpc@0.10.1 install /Users/whw/grpc/examples/node/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/whw/grpc/examples/node/node_modules/grpc
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whw/grpc/examples/node/npm-debug.log

```

**Comment by murgatroid99** [comment]
I would suggest using release-0_11, because it is more recent, and it is what you will get default with Homebrew. You seem to be experiencing this failure because you have not installed the gRPC core library. Instructions for installing it can be found at https://github.com/grpc/grpc/tree/release-0_11/src/node#installation.

**Comment by chelsh** [comment]
```
whwdeMacBook-Pro:node whw$ npm install

> grpc@0.11.1 install /Users/whw/grpc/src/node
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
../ext/byte_buffer.cc:38:10: fatal error: 'grpc/grpc.h' file not found
#include "grpc/grpc.h"
         ^
1 error generated.
make: *** [Release/obj.target/grpc/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/whw/grpc/src/node
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! grpc@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whw/grpc/src/node/npm-debug.log


```

**Comment by murgatroid99** [comment]
This seems to be the same issue as #3874
