### ISSUE TITLE
npm install fail on OSX with node 4.1: "error: thread-local storage is not supported "

### ISSUE THREAD

**Issue by themez** [grpc/grpc#3918]
`curl -fsSL https://goo.gl/getgrpc | bash -s nodejs`

then run `npm install`:

```
./src/core/support/cpu_posix.c:45:8: error: thread-local storage is not supported for the current target
static __thread char magic_thread_local;
       ^
1 error generated.
make: *** [Release/obj.target/gpr/src/core/support/cpu_posix.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zengxian/workspace/grpc
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! grpc@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zengxian/workspace/grpc/examples/node/npm-debug.log
```

**Comment by murgatroid99** [comment]
@nicolasnoble How does the C core build deal with this?

**Comment by murgatroid99** [comment]
Where are you running `npm install`? If you are running it in the `examples/node` directory in the master branch, I would suggest that you checkout the release-0_11 branch and try to use the examples there instead. The examples on master have not yet been finalized.

**Comment by themez** [comment]
Revise: I'm runing `npm install grpc`.

**Comment by murgatroid99** [comment]
OK. Does it work? Are you getting the same error? A different error?

**Comment by daspecster** [comment]
Hello @murgatroid99!
I'm getting this error now when building python/grpcio==1.0.0 on OSX 10.11.6.

```bash
╰─$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

╰─$ clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The error I get is...
```bash
src/core/lib/support/cpu_posix.c:45:8: error: thread-local storage is not supported
for the current target
static __thread char magic_thread_local;
```

I know with the recent release of Xcode 8, they now support [`thread-local`](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html). I'm not sure if that's related, and I'm not sure where `magic_thread_local` comes from if I'm honest.

LMK if there's anything I can do to help! Thanks!

/cc @bjwatson
