### ISSUE TITLE
hello world example was wrong ?

### ISSUE THREAD

**Issue by tangjiaxi** [grpc/grpc#3952]
When I test the example of hello world ( in example/python/) with python.

sh run_server.sh, it run ok.

But sh run_client.sh. It crash.
The error info: 
[tangjiaxi@ip-10-11-255-21 grpc_fun]$ sh run_client.sh 
Traceback (most recent call last):
  File "greeter_client.py", line 15, in <module>
    run()
  File "greeter_client.py", line 11, in run
    response = stub.SayHello(hello_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/usr/local/python2.7_virtual_environment/lib/python2.7/site-packages/grpc/framework/crust/implementations.py", line 73, in __call__
    protocol_options, metadata, request)
  File "/usr/local/python2.7_virtual_environment/lib/python2.7/site-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/usr/local/python2.7_virtual_environment/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 412, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.LocalError

I haven't modify the code.

**Comment by hsaliak** [comment]
I am unable to reproduce this issue. @tangjiaxi  Can you provide more information on your environment?

**Comment by tangjiaxi** [comment]
Sorry, a small mistake.It's okay now.

**Comment by EBouillot** [comment]
Can you please give us what was your problem ? I'm facing the same thing (not with exemple but with my own code)

**Comment by tangjiaxi** [comment]
@EBouillot    Sorry, long time have passed. I can only tell you that you should be more careful with your code. Please review it again. I guess that you must had  made a small mistake, just check.

**Comment by thunderboltsid** [comment]
@EBouillot Did you find a fix to this?
