### ISSUE TITLE
run_tests.py script crashed on macOS

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4049]
https://grpc-testing.appspot.com/job/gRPC_master/12733/config=dbg,language=c,platform=macos/console

```
Traceback (most recent call last):
  File "./tools/run_tests/run_tests.py", line 933, in <module>
    xml_report=args.xml_report)
  File "./tools/run_tests/run_tests.py", line 876, in _build_and_run
    add_env={'GRPC_TEST_PORT_SERVER': 'localhost:%d' % port_server_port})
  File "/jenkins/workspace/gRPC_master/config/dbg/language/c/platform/macos/tools/run_tests/jobset.py", line 403, in run
    if not js.start(cmdline):
  File "/jenkins/workspace/gRPC_master/config/dbg/language/c/platform/macos/tools/run_tests/jobset.py", line 323, in start
    self._add_env)
  File "/jenkins/workspace/gRPC_master/config/dbg/language/c/platform/macos/tools/run_tests/jobset.py", line 195, in __init__
    self.start()
  File "/jenkins/workspace/gRPC_master/config/dbg/language/c/platform/macos/tools/run_tests/jobset.py", line 211, in start
    env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1307, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
OSError: [Errno 22] Invalid argument
```

**Comment by jtattermusch** [comment]
Adding @adelez  for triage.

**Comment by adelez** [comment]
I see this error is gone now. I'm going to add some logging.

**Comment by ctiller** [comment]
I sent you a PR fixing this, it just needs to be merged
