### ISSUE TITLE
NULL pointer dereference in src/core/transport/chttp2/frame_ping.c

### ISSUE THREAD

**Issue by newsoft** [grpc/grpc#4386]
Yet another bug found by Mozilla HTTP/2 fuzzer. Here is the repro against `helloworld/greeter_server`:
```go
package main

import (
	"io"
	"net"
	"github.com/bradfitz/http2"
	"github.com/c0nrad/http2fuzz/util"
)

func main() {
	var Target = "localhost:50051"
	conn := Dial(Target)
	io.WriteString(conn, http2.ClientPreface)
	framer := http2.NewFramer(conn, conn)
	framer.WriteRawFrame(http2.FrameType(6), http2.Flags(1), 1812335, util.FromBase64("M/O2gGCHLpY="))
}

func Dial(host string) net.Conn {
	conn, err := net.Dial("tcp", host)
	if err != nil {
		panic(err)
	}
	return conn
}
```

The NULL pointer dereference happens in `src/core/transport/chttp2/frame_ping.c`:
```c
    if (p->is_ack) {
      for (ping = transport_parsing->pings.next;
           ping != &transport_parsing->pings; ping = ping->next) {
        if (0 == memcmp(p->opaque_8bytes, ping->id, 8)) {  // One of those two pointers is NULL
          grpc_exec_ctx_enqueue(exec_ctx, ping->on_recv, 1);
        }
        ping->next->prev = ping->prev;
        ping->prev->next = ping->next;
        gpr_free(ping);
      }
    } else {
```

Unfortunately, despite being compiled at `-O0`, arguments were optimized out so I cannot tell right away if `p->opaque_8bytes` or `ping->id` is NULL. Here the full call stack in case it helps:
```
#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:799
#1  0x00000000004bbe84 in memcmp ()
#2  0x00007ffff71b7ae4 in grpc_chttp2_ping_parser_parse (exec_ctx=<optimized out>, parser=<optimized out>, transport_parsing=<optimized out>, 
    stream_parsing=<optimized out>, slice=..., is_last=<optimized out>) at src/core/transport/chttp2/frame_ping.c:92
#3  0x00007ffff7201100 in parse_frame_slice (exec_ctx=<optimized out>, transport_parsing=<optimized out>, slice=..., is_last=<optimized out>)
    at src/core/transport/chttp2/parsing.c:842
#4  0x00007ffff71feea0 in grpc_chttp2_perform_read (exec_ctx=0x7ffff26fd550, transport_parsing=0x62500002c5e0, slice=...)
    at src/core/transport/chttp2/parsing.c:394
#5  0x00007ffff7237175 in recv_data (exec_ctx=0x7ffff26fd550, tp=0x62500002a900, success=1) at src/core/transport/chttp2_transport.c:1296
#6  0x00007ffff710495d in call_read_cb (exec_ctx=0x7ffff26fd550, tcp=0x61400000fe40, success=1) at src/core/iomgr/tcp_posix.c:173
#7  0x00007ffff71069b6 in tcp_continue_read (exec_ctx=0x7ffff26fd550, tcp=0x61400000fe40) at src/core/iomgr/tcp_posix.c:242
#8  0x00007ffff710090b in tcp_handle_read (exec_ctx=0x7ffff26fd550, arg=0x61400000fe40, success=1) at src/core/iomgr/tcp_posix.c:259
#9  0x00007ffff70c70d7 in grpc_exec_ctx_flush (exec_ctx=0x7ffff26fd550) at src/core/iomgr/exec_ctx.c:51
#10 0x00007ffff70e4ae9 in grpc_pollset_work (exec_ctx=<optimized out>, pollset=<optimized out>, worker=<optimized out>, now=..., deadline=...)
    at src/core/iomgr/pollset_posix.c:343
#11 0x00007ffff717a166 in grpc_completion_queue_next (cc=0x61300000de80, deadline=..., reserved=0x0) at src/core/surface/completion_queue.c:288
#12 0x00007ffff7a8e95a in grpc::CompletionQueue::AsyncNextInternal (this=0x610000007d58, tag=0x7ffff26fdca0, ok=0x7ffff26fdea0, deadline=...)
    at src/cpp/common/completion_queue.cc:56
#13 0x00007ffff7a3012a in grpc::CompletionQueue::Next (this=0x610000007d58, tag=0x7ffff26fdca0, ok=0x7ffff26fdea0) at include/grpc++/completion_queue.h:127
#14 0x00007ffff7af5352 in grpc::Server::SyncRequest::Wait (cq=0x610000007d58, ok=0x7ffff26fdea0) at src/cpp/server/server.cc:148
#15 0x00007ffff7aec562 in grpc::Server::RunRpc (this=<optimized out>) at src/cpp/server/server.cc:556
#16 0x00007ffff7afad18 in std::_Mem_fn_base<void (grpc::Server::*)(), true>::operator()<, void>(grpc::Server*) const (this=0x6030000047b0, __object=0x610000007d40)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:600
#17 0x00007ffff7afa8f8 in std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (
    this=0x6030000047b0, __args=<unknown type in /usr/local/lib/libgrpc++_unsecure.so.0, CU 0x69142, DIE 0x7baaf>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:1073
#18 0x00007ffff7afa680 in std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::operator()<, void>() (this=0x6030000047b0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:1131
#19 0x00007ffff7af904f in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)> >::_M_invoke(std::_Any_data const&) (
    __functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:1871
#20 0x00007ffff7a9ed4e in std::function<void ()>::operator()() const (this=0x7ffff26fe820)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:2271
#21 0x00007ffff7a99a99 in grpc::DynamicThreadPool::ThreadFunc (this=<optimized out>) at src/cpp/server/dynamic_thread_pool.cc:81
#22 0x00007ffff7a98d37 in grpc::DynamicThreadPool::DynamicThread::ThreadFunc (this=<optimized out>) at src/cpp/server/dynamic_thread_pool.cc:50
#23 0x00007ffff7ac2ed8 in std::_Mem_fn_base<void (grpc::DynamicThreadPool::DynamicThread::*)(), true>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const (this=0x60600000e7b0, __object=0x60200000ee10) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:600
#24 0x00007ffff7ac2a42 in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x60600000e7a8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:1530
#25 0x00007ffff7ac2851 in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() (this=0x7ffff26fed40) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/functional:1520
#26 0x00007ffff7ac26c1 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() (this=0x7ffff26fee20) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/thread:115
#27 0x00007ffff60a6030 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#28 0x00007ffff657a6aa in start_thread (arg=0x7ffff26ff700) at pthread_create.c:333
#29 0x00007ffff5602eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by ctiller** [comment]
I think this is addressed by #4325
