### ISSUE TITLE
interop failure: node:csharp_server:status_code_and_message

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4472]
https://grpc-testing.appspot.com/job/gRPC_interop_master/1694/console

```
I1215 19:06:18.718281358     196 socket_utils_common_posix.c:148] Disabling AF_INET6 sockets because ::1 is not available.

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: 'Received RST_STREAM err=8' === 'test status message'
    at ClientDuplexStream.<anonymous> (/var/local/git/grpc/src/node/interop/interop_client.js:367:12)
    at ClientDuplexStream.emit (events.js:107:17)
    at /var/local/git/grpc/src/node/src/client.js:557:14

FAILED: cloud_to_cloud:node:csharp_server:status_code_and_message [ret=1, pid=4917]
```

**Comment by ctiller** [comment]
CC @jtattermusch

**Comment by jtattermusch** [comment]
Yeah, this is another instance of https://github.com/grpc/grpc/issues/4427. Any ideas what could be wrong? Looks like it's a C core issue.

**Comment by murgatroid99** [comment]
I think this problem can be tracked sufficiently in #4227.

**Comment by jtattermusch** [comment]
@murgatroid99  probably a wrong issue number.

**Comment by murgatroid99** [comment]
I already fixed it.
