### ISSUE TITLE
NodeJS - Install grpc via npm failed

### ISSUE THREAD

**Issue by mastermix252** [grpc/grpc#4570]
Hello dear gRPC community, 

Sadly I cannot install gRPC as a global (or even local) node module.
OS: Ubuntu 15.10

I already have installed the libgrpc-dev and libgrpc0

The command I run are
```
npm install grpc
```
and/or
```
npm install -g grpc
```

The following output is shown in terminal:

```
> grpc@0.11.1 install /usr/local/lib/node_modules/grpc
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
  CXX(target) Release/obj.target/grpc/ext/channel.o
In file included from ../ext/channel.cc:45:0:
../ext/credentials.h:51:42: error: ‘grpc_credentials’ has not been declared
   static v8::Local<v8::Value> WrapStruct(grpc_credentials *credentials);
                                          ^
../ext/credentials.h:54:3: error: ‘grpc_credentials’ does not name a type
   grpc_credentials *GetWrappedCredentials();
   ^
../ext/credentials.h:57:41: error: expected ‘)’ before ‘*’ token
   explicit Credentials(grpc_credentials *credentials);
                                         ^
../ext/credentials.h:76:3: error: ‘grpc_credentials’ does not name a type
   grpc_credentials *wrapped_credentials;
   ^
../ext/channel.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Channel::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../ext/channel.cc:114:5: error: ‘grpc_credentials’ was not declared in this scope
     grpc_credentials *creds;
     ^
../ext/channel.cc:114:23: error: ‘creds’ was not declared in this scope
     grpc_credentials *creds;
                       ^
../ext/channel.cc:121:27: error: ‘class grpc::node::Credentials’ has no member named ‘GetWrappedCredentials’
     creds = creds_object->GetWrappedCredentials();
                           ^
grpc.target.mk:114: recipe for target 'Release/obj.target/grpc/ext/channel.o' failed
make: *** [Release/obj.target/grpc/ext/channel.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-22-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/grpc
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "grpc"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.11.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mastermix252/test/npm-debug.log
[08:12:15]mastermix252@FFML0004:~/test$ sudo npm install --global grpc@0.12.0
npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "grpc@0.12.0"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: grpc@0.12.0
npm ERR! Valid install targets:
npm ERR! 0.11.1, 0.11.0, 0.10.1, 0.10.0, 0.9.2, 0.9.1, 0.9.0, 0.8.0, 0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mastermix252/test/npm-debug.log
```

Could you please have a look at this and give me some adivce :pray:

**Comment by twolfy** [comment]
I can reproduce the issue with the following Dockerfile:

```docker
FROM ubuntu:15.10

RUN apt-get update && apt-get install -y libgrpc0 libgrpc-dev build-essential golang npm nodejs nodejs-legacy

RUN npm install grpc

# run the service command
COMMAND ["echo", "hello world"]
```

**Comment by twolfy** [comment]
related to #4131

**Comment by murgatroid99** [comment]
gRPC 0.12.0 has been published to NPM, and it no longer depends on any other package, so it should no longer have this problem. Can you check whether it works for you?

**Comment by mastermix252** [comment]
Hi @murgatroid99, this now works fine! Both, local and global install via npm are installing grpc properly.
Thank you for the notification and fix.
