### ISSUE TITLE
Build from source directions do not work

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#4592]
- no mention of need to install tox
- after apt-get install python-tox I get the following:
```
ctiller@ctiller:~/grpc$ CONFIG=opt tools/run_tests/build_python.sh 2.7
++ dirname tools/run_tests/build_python.sh
+ cd tools/run_tests/../..
++ pwd
+ ROOT=/usr/local/google/home/ctiller/grpc
+ export LD_LIBRARY_PATH=/usr/local/google/home/ctiller/grpc/libs/opt
+ LD_LIBRARY_PATH=/usr/local/google/home/ctiller/grpc/libs/opt
+ export DYLD_LIBRARY_PATH=/usr/local/google/home/ctiller/grpc/libs/opt
+ DYLD_LIBRARY_PATH=/usr/local/google/home/ctiller/grpc/libs/opt
+ export PATH=/usr/local/google/home/ctiller/grpc/bins/opt:/usr/local/google/home/ctiller/grpc/bins/opt/protobuf:/usr/lib/ccache:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/usr/local/google/home/ctiller/grpc/bins/opt:/usr/local/google/home/ctiller/grpc/bins/opt/protobuf:/usr/lib/ccache:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export 'CFLAGS=-I/usr/local/google/home/ctiller/grpc/include -std=c89'
+ CFLAGS='-I/usr/local/google/home/ctiller/grpc/include -std=c89'
+ export 'LDFLAGS=-L/usr/local/google/home/ctiller/grpc/libs/opt -L/usr/local/google/home/ctiller/grpc/libs/opt/openssl'
+ LDFLAGS='-L/usr/local/google/home/ctiller/grpc/libs/opt -L/usr/local/google/home/ctiller/grpc/libs/opt/openssl'
+ export GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ export GRPC_PYTHON_ENABLE_CYTHON_TRACING=1
+ GRPC_PYTHON_ENABLE_CYTHON_TRACING=1
+ tox --notest
Traceback (most recent call last):
  File "/usr/bin/tox", line 9, in <module>
    load_entry_point('tox==1.6.0', 'console_scripts', 'tox')()
  File "/usr/lib/python2.7/dist-packages/tox/_cmdline.py", line 25, in main
    config = parseconfig(args, 'tox')
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 44, in parseconfig
    parseini(config, inipath)
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 246, in __init__
    self._makeenvconfig(name, "_xz_9", reader._subs, config)
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 296, in _makeenvconfig
    vc.commands = reader.getargvlist(section, "commands")
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 448, in getargvlist
    commandlist.append(self._processcommand(current_command))
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 467, in _processcommand
    new_word = self._replace(word, quote=True)
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 626, in _replace
    return rexpattern.sub(replace_func, x)
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 615, in _replace_match_quote
    return self._replace_match(match, quote=True)
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 612, in _replace_match
    return handler(match, quote)
  File "/usr/lib/python2.7/dist-packages/tox/_config.py", line 549, in _replace_env
    (envkey, envkey))
tox.ConfigError: ConfigError: substitution env:'PYGRPC_ROOT': unkown environment variable 'PYGRPC_ROOT'
```

**Comment by michael-berlin** [comment]
tox as dependency is mentioned now: https://github.com/grpc/grpc/blob/master/src/python/README.md

But what's missing is the required version number and that is currently 1.6.1 because tox.ini contains the ["-rrequirements.txt"](http://tox.readthedocs.org/en/latest/example/basic.html#depending-on-requirements-txt) directive. (Unfortunately, Ubuntu Trusty ships with tox 1.6.0.)

@soltanmm told me over Hangouts he plans to replace tox anyway for building Python gRPC and keep it only for running the tests.
