### ISSUE TITLE
Several Jenkins builds failed with java.io.IOException: Failed to mkdirs

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#4605]
Seen at https://grpc-testing.appspot.com/job/gRPC_master/14209

```
java.io.IOException: Failed to mkdirs: /home/jenkins/workspace/gRPC_master/config/msan/language/c/platform/linux
	at hudson.FilePath.mkdirs(FilePath.java:1163)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by jtattermusch** [comment]
I recreated linux workers 6, 9 and 10 using our tools/gce/create_linux_worker script.

**Comment by adelez** [comment]
Closing since it hasn't occurred for a while.
