### ISSUE TITLE
tests.cloud_to_cloud:node:csharp_server:status_code_and_message: "AssertionError: 'Received RST_STREAM err=8' === 'test status message'"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#4651]
Courtesy of Twilight Sparkle:
https://grpc-testing.appspot.com/job/gRPC_interop_master/2270/testReport/(root)/tests/cloud_to_cloud_node_csharp_server_status_code_and_message/
```
stdin: is not a tty
I0108 19:06:51.821253332     195 socket_utils_common_posix.c:148] Disabling AF_INET6 sockets because ::1 is not available.

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: 'Received RST_STREAM err=8' === 'test status message'
    at ClientDuplexStream.<anonymous> (/var/local/git/grpc/src/node/interop/interop_client.js:367:12)
    at ClientDuplexStream.emit (events.js:107:17)
    at /var/local/git/grpc/src/node/src/client.js:557:14
```

**Comment by murgatroid99** [comment]
This is identical to #4472 and another instance of #4427.
