### ISSUE TITLE
protoc-gen-python-grpc: Plugin failed with status code 1.

### ISSUE THREAD

**Issue by incidenthunter** [grpc/grpc#4961]
Hello,

I tried for 2 hours to install the Python implementation of grpc, on my laptop, in a virtualenv or in a new virtual machine and I am stuck. It always fails with `protoc-gen-python-grpc: Plugin failed with status code 1.`

I followed the documentation, what am I missing please? How can I generate the plugin?

```
root@7955e5e6435f:/root# apt-get install python-dev python-pip python-setuptools libgrpc-dev
root@7955e5e6435f:/root# /usr/local/bin/protoc --version
libprotoc 3.0.0
root@7955e5e6435f:/root# pip install grpcio==0.12.0b0
Downloading/unpacking grpcio==0.12.0b0
  Downloading grpcio-0.12.0b0.tar.gz (442kB): 442kB downloaded
  Running setup.py (path:/tmp/pip-build-WFfG1d/grpcio/setup.py) egg_info for package grpcio
  
...
Installing collected packages: grpcio, enum34, futures
  Running setup.py install for grpcio
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WFfG1d/grpcio/setup.py", line 176, in <module>
        test_runner=TEST_RUNNER,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "commands.py", line 152, in run
        self.run_command('build_proto_modules')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "commands.py", line 127, in run
        command, e.message, e.output))
    Exception: Command:
    ['/usr/local/bin/protoc', '--plugin=protoc-gen-python-grpc=None', '-I /tmp/pip-build-WFfG1d/grpcio', '--python_out=/tmp/pip-build-WFfG1d/grpcio', '--python-grpc_out=/tmp/pip-build-WFfG1d/grpcio', '/tmp/pip-build-WFfG1d/grpcio/tests/interop/empty.proto', '/tmp/pip-build-WFfG1d/grpcio/tests/interop/test.proto', '/tmp/pip-build-WFfG1d/grpcio/tests/interop/messages.proto']
    Message:
    
    Output:
    None: program not found or is not executable
    --python-grpc_out: protoc-gen-python-grpc: Plugin failed with status code 1.
    
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-WFfG1d/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-E1zcoT-record/install-record.txt --single-version-externally-managed --compile:
    running install
running build
running build_py
running build_proto_modules
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-WFfG1d/grpcio/setup.py", line 176, in <module>
    test_runner=TEST_RUNNER,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "commands.py", line 152, in run
    self.run_command('build_proto_modules')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "commands.py", line 127, in run
    command, e.message, e.output))
Exception: Command:
['/usr/local/bin/protoc', '--plugin=protoc-gen-python-grpc=None', '-I /tmp/pip-build-WFfG1d/grpcio', '--python_out=/tmp/pip-build-WFfG1d/grpcio', '--python-grpc_out=/tmp/pip-build-WFfG1d/grpcio', '/tmp/pip-build-WFfG1d/grpcio/tests/interop/empty.proto', '/tmp/pip-build-WFfG1d/grpcio/tests/interop/test.proto', '/tmp/pip-build-WFfG1d/grpcio/tests/interop/messages.proto']

Message:

Output:
None: program not found or is not executable
--python-grpc_out: protoc-gen-python-grpc: Plugin failed with status code 1.

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-WFfG1d/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-E1zcoT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-WFfG1d/grpcio
Storing debug log for failure in /root/.pip/pip.log
```

I also tried in a new VM to build every parts from git trees but still no luck

Thx!

**Comment by soltanmm** [comment]
The version currently on PyPI is not particularly good about installation, I'll give you that (this'll be much, much nicer come next version).

The protoc plugin for Python is supposed to come from a separate package. I can't quite remember at the moment whence though so I'll leave that at that for now (will try to get back to you).

The instructions for building from source have been outdated for a bit. The steps for a source installation are:

```
git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init
pip install -rrequirements.txt
GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .
```

The above should chuck a warning at you about a missing plugin (instead of failing; it isn't a necessary part of the build here).

If you need to generate protobuf code from `.proto` files (i.e. need the `protoc` plugin for reasons beyond the error you're experiencing):

```
make
```

The relevant version of `protoc` and its plugins will end up in the `bins/opt/protobuf` and `bins/opt` directories respectively.

That should get you rolling from the master branch, at least.

Or did you want to stay on a release branch?

**Comment by incidenthunter** [comment]
> Or did you want to stay on a release branch?

Not in particular, I like living on the bleeding edge :)

Your instructions worked, thank you so much!
