### ISSUE TITLE
Interop failure tests.cloud_to_prod_auth:default:python:compute_engine_creds

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#5299]
https://grpc-testing.appspot.com/job/gRPC_interop_master/2965/testReport/(root)/tests/cloud_to_prod_auth_default_python_compute_engine_creds/

```
ygrpc-0.14.0.dev0-Linux-x86_64-ucs4.so
running run_interop
Searching for oauth2client>=1.4.7
Reading https://pypi.python.org/simple/oauth2client/
Best match: oauth2client 2.0.0
Downloading https://pypi.python.org/packages/source/o/oauth2client/oauth2client-2.0.0.tar.gz#md5=9b9f8473ff1abbae359321dd222c7584
Processing oauth2client-2.0.0.tar.gz
Writing /tmp/easy_install-6V4mDN/oauth2client-2.0.0/setup.cfg
Running oauth2client-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6V4mDN/oauth2client-2.0.0/egg-dist-tmp-38Brbs
warning: no previously-included files matching '*' found under directory 'tests'
zip_safe flag not set; analyzing archive contents...
Moving oauth2client-2.0.0-py2.7.egg to /var/local/git/grpc/.eggs

Installed /var/local/git/grpc/.eggs/oauth2client-2.0.0-py2.7.egg
Searching for rsa>=3.1.4
Reading https://pypi.python.org/simple/rsa/
Best match: rsa 3.3
Downloading https://pypi.python.org/packages/source/r/rsa/rsa-3.3.tar.gz#md5=513ed05c3b2038e8bc6d0686772455ab
Processing rsa-3.3.tar.gz
Writing /tmp/easy_install-8r6W28/rsa-3.3/setup.cfg
Running rsa-3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8r6W28/rsa-3.3/egg-dist-tmp-4e5lma
warning: no files found matching 'README'
zip_safe flag not set; analyzing archive contents...
Moving rsa-3.3-py2.7.egg to /var/local/git/grpc/.eggs

Installed /var/local/git/grpc/.eggs/rsa-3.3-py2.7.egg
Searching for pyasn1-modules>=0.0.5
Reading https://pypi.python.org/simple/pyasn1-modules/
Best match: pyasn1-modules 0.0.8
Downloading https://pypi.python.org/packages/2.7/p/pyasn1-modules/pyasn1_modules-0.0.8-py2.7.egg#md5=f03fff5bc43106475a64a1c34d4052d7
Processing pyasn1_modules-0.0.8-py2.7.egg
Moving pyasn1_modules-0.0.8-py2.7.egg to /var/local/git/grpc/.eggs

Installed /var/local/git/grpc/.eggs/pyasn1_modules-0.0.8-py2.7.egg
Searching for pyasn1>=0.1.7
Reading https://pypi.python.org/simple/pyasn1/
Best match: pyasn1 0.1.9
Downloading https://pypi.python.org/packages/2.7/p/pyasn1/pyasn1-0.1.9-py2.7.egg#md5=08eef0e822233609f6cad55b419ae00c
Processing pyasn1-0.1.9-py2.7.egg
Moving pyasn1-0.1.9-py2.7.egg to /var/local/git/grpc/.eggs

Installed /var/local/git/grpc/.eggs/pyasn1-0.1.9-py2.7.egg
Searching for httplib2>=0.9.1
Reading https://pypi.python.org/simple/httplib2/
Best match: httplib2 0.9.2
Downloading https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.2.zip#md5=404bac4a4e0d10b3ba498ce483c8c456
Processing httplib2-0.9.2.zip
Writing /tmp/easy_install-oVTwgL/httplib2-0.9.2/setup.cfg
Running httplib2-0.9.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oVTwgL/httplib2-0.9.2/egg-dist-tmp-ZlfzGk
zip_safe flag not set; analyzing archive contents...
httplib2.__init__: module references __file__
creating /var/local/git/grpc/.eggs/httplib2-0.9.2-py2.7.egg
Extracting httplib2-0.9.2-py2.7.egg to /var/local/git/grpc/.eggs

Installed /var/local/git/grpc/.eggs/httplib2-0.9.2-py2.7.egg
ERROR:root:Exception during transmission!
Traceback (most recent call last):
  File "/var/local/git/grpc/src/python/grpcio/grpc/framework/foundation/callable_util.py", line 69, in _call_logging_exceptions
    return _EasyOutcome(Outcome.Kind.RETURNED, behavior(*args, **kwargs), None)
  File "/var/local/git/grpc/src/python/grpcio/grpc/_links/invocation.py", line 407, in accept_ticket
    self._kernel.add_ticket(ticket)
  File "/var/local/git/grpc/src/python/grpcio/grpc/_links/invocation.py", line 341, in add_ticket
    ticket.timeout, ticket.allowance, grpc_call_options)
  File "/var/local/git/grpc/src/python/grpcio/grpc/_links/invocation.py", line 255, in _invoke
    transformed_initial_metadata = self._metadata_transformer(initial_metadata)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/client.py", line 86, in <lambda>
    ('authorization', 'Bearer %s' % _oauth_access_token(args))]
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/client.py", line 71, in _oauth_access_token
    return scoped_credentials.get_access_token().access_token
  File "build/bdist.linux-x86_64/egg/oauth2client/client.py", line 776, in get_access_token
    self.refresh(http)
  File "build/bdist.linux-x86_64/egg/oauth2client/client.py", line 659, in refresh
    self._refresh(http.request)
  File "build/bdist.linux-x86_64/egg/oauth2client/contrib/gce.py", line 102, in _refresh
    raise HttpAccessTokenRefreshError(content, status=response.status)
HttpAccessTokenRefreshError: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That\u2019s an error.</ins>
  <p>The requested URL <code>/computeMetadata/v1/instance/service-accounts/default/acquire?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fxapi.zoo</code> was not found on this server.  <ins>That\u2019s all we know.</ins>
 This can occur if a VM was created with no service account or scopes.
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    setuptools.setup(**setup_arguments)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 291, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 307, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/client.py", line 120, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 337, in test_interoperability
    _compute_engine_creds(stub, args)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 283, in _compute_engine_creds
    response = _large_unary_common_behavior(stub, True, True)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 96, in _large_unary_common_behavior
    response = response_future.result()
  File "/var/local/git/grpc/src/python/grpcio/grpc/framework/crust/_control.py", line 324, in result
    raise self._termination.abortion_error  # pylint: disable=raising-bad-type
grpc.framework.interfaces.face.face.NetworkError: NetworkError(code=None, details="None")
ERROR: InvocationError: '/var/local/git/grpc/.tox/interop_client/bin/python setup.py run_interop --client --args=--server_host=grpc-test.sandbox.googleapis.com --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=compute_engine_creds --oauth_scope=https://www.googleapis.com/auth/xapi.zoo --default_service_account=830293263384-compute@developer.gserviceaccount.com'
___________________________________ summary ____________________________________
ERROR:   interop_client: commands failed
```

**Comment by jtattermusch** [comment]
Doesn't look like we're seeing this anymore. Closing as part of buildpony bankruptcy.
