### ISSUE TITLE
Interop test failure: tests.cloud_to_cloud:python:c++_server:cancel_after_first_response

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5504]
https://grpc-testing.appspot.com/job/gRPC_interop_master/3070/testReport/junit/(root)/tests/cloud_to_cloud_python_c___server_cancel_after_first_response/

```
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    setuptools.setup(**setup_arguments)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 291, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 307, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/client.py", line 120, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 331, in test_interoperability
    _cancel_after_first_response(stub)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 240, in _cancel_after_first_response
    response = next(response_iterator)
  File "/var/local/git/grpc/src/python/grpcio/grpc/framework/crust/_control.py", line 412, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=None, details="None")
```

**Comment by jtattermusch** [comment]
Looks like this has been fixed sometime during the fixit.
