### ISSUE TITLE
Doc Fixit: python installation failed

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#5518]
I tried following the Python installation steps: https://github.com/grpc/grpc/tree/master/src/python/grpcio#from-pypi and got this error

```
    Installed /tmp/pip-build-3yV22j/grpcio/.eggs/protobuf-3.0.0b2-py2.7.egg
    Searching for futures>=2.2.0
    Reading https://pypi.python.org/simple/futures/
    Best match: futures 3.0.5
    Downloading https://pypi.python.org/packages/source/f/futures/futures-3.0.5.tar.gz#md5=ced2c365e518242512d7a398b515ff95
    Processing futures-3.0.5.tar.gz
    Writing /tmp/easy_install-tByYlQ/futures-3.0.5/setup.cfg
    Running futures-3.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tByYlQ/futures-3.0.5/egg-dist-tmp-9KUkrJ
    creating /tmp/pip-build-3yV22j/grpcio/.eggs/futures-3.0.5-py2.7.egg
    Extracting futures-3.0.5-py2.7.egg to /tmp/pip-build-3yV22j/grpcio/.eggs
    
    Installed /tmp/pip-build-3yV22j/grpcio/.eggs/futures-3.0.5-py2.7.egg
    Searching for enum34>=1.0.4
    Reading https://pypi.python.org/simple/enum34/
    Best match: enum34 1.1.2
    Downloading https://pypi.python.org/packages/source/e/enum34/enum34-1.1.2.zip#md5=a9ebbad4ce451c1298cf094de07cdf69
    Processing enum34-1.1.2.zip
    Writing /tmp/easy_install-Jo2a8p/enum34-1.1.2/setup.cfg
    Running enum34-1.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Jo2a8p/enum34-1.1.2/egg-dist-tmp-zDwsrA
    zip_safe flag not set; analyzing archive contents...
    Moving enum34-1.1.2-py2.7.egg to /tmp/pip-build-3yV22j/grpcio/.eggs
    
    Installed /tmp/pip-build-3yV22j/grpcio/.eggs/enum34-1.1.2-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3yV22j/grpcio/setup.py", line 242, in <module>
        setuptools.setup(**setup_arguments)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 827, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 702, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.10'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3yV22j/grpcio
```

I was in a fresh GCE instance Debian Jessie 8.3 (debian-8-jessie-v20160219). I tried a few things I found from searching for the error on google (e.g. make sure setuptools, pip, etc are up to date) but the error still happens.

I am probably missing some pre-requisites, so perhaps it might make sense to document those before the installation steps?

**Comment by ctiller** [comment]
It's worth documenting which OS was installed on your GCE instance.

**Comment by stanley-cheung** [comment]
Oops right. Updated bug description.

**Comment by soltanmm** [comment]
You can only get that error if a dependency is *already* installed **and** is owned by the system. There's no way that was a fresh OS w/o Python installed at first (or maybe that's just how Debian is distributed [with batteries included], I'm not sure). The fix is to invoke installation of the dependencies like so:

`pip install --ignore-installed six`

... I imagine y'all want some sort of a 'troubleshooting' section added to the installation docs? I'm beginning to find this surprisingly common...

**Comment by stanley-cheung** [comment]
This fixes the issue for me.

About how to document this, I am not sure. On one hand this seems like an environment issue that is usually fixed by googling, but the solution here doesn't look intuitive and obvious to me.

I think a 'troubleshooting' section will be useful for this type of issue. Do you mind starting such section for Python?
