### ISSUE TITLE
Interop test failure: tests.cloud_to_prod:default:python:cancel_after_first_response

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#5669]
[Link](https://grpc-testing.appspot.com/job/gRPC_interop_master/3262/testReport/%28root%29/tests/cloud_to_prod_default_python_cancel_after_first_response/).

```
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    setuptools.setup(**setup_arguments)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 327, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio/commands.py", line 343, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/client.py", line 120, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 331, in test_interoperability
    _cancel_after_first_response(stub)
  File "/var/local/git/grpc/src/python/grpcio/tests/interop/methods.py", line 240, in _cancel_after_first_response
    response = next(response_iterator)
  File "/var/local/git/grpc/src/python/grpcio/grpc/framework/crust/_control.py", line 412, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=None, details="None")
ERROR: InvocationError: '/var/local/git/grpc/.tox/interop_client/bin/python setup.py run_interop --client --args=--server_host=grpc-test.sandbox.googleapis.com --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_first_response'
___________________________________ summary ____________________________________
ERROR:   interop_client: commands failed
```

**Comment by jtattermusch** [comment]
Looks like this has been fixed sometime during the fixit.

**Comment by apolcyn** [comment]
seen again on kokoro:

```
2017-08-16 14:03:20,003 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 184, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 200, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 126, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 460, in test_interoperability
    _cancel_after_first_response(stub)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 263, in _cancel_after_first_response
    response = next(response_iterator)
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 351, in next
    return self._next()
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 342, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, )>

2017-08-16 14:03:20,003 FAILED: cloud_to_prod:default:python:cancel_after_first_response [ret=1, pid=5565]
```

https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/1139/

from c# pr https://github.com/grpc/grpc/pull/12176
