### ISSUE TITLE
Building artifacts broken for Python on Linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5707]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/361/architecture=x64,language=python,platform=linux/console

```
Installed /var/local/git/grpc/.eggs/protobuf-3.0.0b2.post2-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 246, in <module>
    setuptools.setup(**setup_arguments)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 838, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2462, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2686, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2696, in _compute_dependencies
    current_req = packaging.requirements.Requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'and plat'"
```

**Comment by jtattermusch** [comment]
(not super urgent but will be needed for the next release of course).

**Comment by soltanmm** [comment]
[Something is broken upstream somewhere somehow](https://bitbucket.org/pypa/setuptools/issues/503/pkg_resources_vendorpackagingrequirementsi). Poking further...
