### ISSUE TITLE
Node grpc fails to install

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5816]
https://grpc-testing.appspot.com/job/gRPC_master/15873/config=opt,language=node,platform=windows/console

```
gyp ERR! build error 
gyp ERR! stack Error: EBUSY: resource busy or locked, open 'C:\Users\jenkins\.node-gyp\4.2.6\Release\node.lib'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\jenkins\\workspace\\gRPC_master\\config\\opt\\language\\node\\platform\\windows\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=c:\\jenkins\\workspace\\gRPC_master\\config\\opt\\language\\node\\platform\\windows\\src\\node\\extension_binary"
gyp ERR! cwd c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\jenkins\\workspace\\gRPC_master\\config\\opt\\language\\node\\platform\\windows\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.23
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows\src\node\extension_binary' (1)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--build-from-source"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! grpc@0.14.0-dev install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.14.0-dev install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\jenkins\workspace\gRPC_master\config\opt\language\node\platform\windows\npm-debug.log
```

**Comment by vjpai** [comment]
Transient Jenkins failure. Marking to close.
