### ISSUE TITLE
Interop tests: Slave went offline during the build

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5822]
https://grpc-testing.appspot.com/job/gRPC_interop_master/3389/console

```
+ tools/run_tests/run_interop_tests.py -l all -s all --cloud_to_prod --cloud_to_prod_auth --use_docker --http2_interop -t -j 12
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2332)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2801)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

Build step 'Execute shell' marked build as failure
ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.michelin.cio.hudson.plugins.copytoslave.CopyToMasterNotifier.perform(CopyToMasterNotifier.java:91)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Copy files back to the job's workspace on the master node' marked build as failure
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for gRPC_interop_master #3389
[htmlpublisher] Archiving HTML reports...
ERROR: Build step failed with exception
java.lang.NullPointerException
Build step 'Publish HTML reports' marked build as failure
Finished: FAILURE
```

**Comment by jcanizales** [comment]
Seen here too https://grpc-testing.appspot.com/job/gRPC_interop_master/3400/console

**Comment by jtattermusch** [comment]
This is basically https://github.com/grpc/grpc/issues/5768 (I had to restart the worker manually to get it unstuck).

Leaving this issue open to prevent buildpony from filing new issues for the same problem.

**Comment by vjpai** [comment]
Transient Jenkins failure. Let's close it.
