### ISSUE TITLE
tests.py.test._later_test.LaterTest.test_simple_delay (opt,python,macos)

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc#5905]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/7188/config=opt,language=python,platform=macos/console

The **BUILDPONY** might be on someone else's desk, but the **BUILDPONY** is omnipresent.

Filed this issue despite it being on a PR as it's a pure Python test as far as I can tell, and the relevant change only touched C code.

**Comment by stanley-cheung** [comment]
Still see this happening on master: https://grpc-testing.appspot.com/job/gRPC_master/16208/config=opt,language=python,platform=macos/console

```
Running       _later_test.LaterTest.test_simple_delay
FAILURE       _later_test.LaterTest.test_simple_delay
4 tests finished:
	3 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
_later_test.LaterTest.test_simple_delay
traceback:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/jenkins/workspace/gRPC_master/config/opt/language/python/platform/macos/src/python/grpcio/tests/unit/framework/foundation/_later_test.py", line 57, in test_simple_delay
    self.assertFalse(computation_future.done())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 418, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false

stdout:

stderr:


Unexpected successes: []
Test failure
I0331 13:19:00.689925000 140735211819776 init.c:210] grpc_shutdown(void)

FAILED: py.test._later_test.LaterTest [ret=1, pid=11199]
```

**Comment by stanley-cheung** [comment]
Similar error but on LaterTest.test_cancel

https://grpc-testing.appspot.com/job/gRPC_master/16566/config=dbg,language=python,platform=linux/testReport/junit/(root)/tests/py_test__later_test_LaterTest/

**Comment by soltanmm** [comment]
Haven't seen in a while.
