### ISSUE TITLE
[Python] SerializeToString exception cause client Deadline Exceeded

### ISSUE THREAD

**Issue by yancl** [grpc/grpc#5969]
Hi,
  Today I made some change to the gRPC python example to verify the situation several days ago I met.

server side changes:
```
-- a/examples/python/helloworld/greeter_server.py
+++ b/examples/python/helloworld/greeter_server.py
@@ -39,7 +39,8 @@ _ONE_DAY_IN_SECONDS = 60 * 60 * 24
 class Greeter(helloworld_pb2.BetaGreeterServicer):

   def SayHello(self, request, context):
-    return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
+    #return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
+    return 1
```

client side changes:
```
--- a/examples/python/helloworld/greeter_client.py
+++ b/examples/python/helloworld/greeter_client.py
@@ -35,14 +35,24 @@ from grpc.beta import implementations

 import helloworld_pb2

+import time
+
 _TIMEOUT_SECONDS = 10


 def run():
-  channel = implementations.insecure_channel('localhost', 50051)
-  stub = helloworld_pb2.beta_create_Greeter_stub(channel)
-  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
-  print("Greeter client received: " + response.message)
+    channel = implementations.insecure_channel('localhost', 50051)
+    stub = helloworld_pb2.beta_create_Greeter_stub(channel)
+    for i in xrange(10):
+        print("loop:%d" % i)
+        t0 = time.time()
+        try:
+            response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
+            print("Greeter client received: " + response.message)
+        except Exception,e:
+            print("ex:%s" % e)
+        t1 = time.time()
+        print('cost:%f' %  (t1 - t0))
```

the server side output:
```
RROR:root:Exception during transmission!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grpc/framework/foundation/callable_util.py", line 69, in _call_logging_exceptions
    return _EasyOutcome(Outcome.Kind.RETURNED, behavior(*args, **kwargs), None)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_links/service.py", line 473, in accept_ticket
    self._kernel.add_ticket(ticket)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_links/service.py", line 345, in add_ticket
    call.write(rpc_state.response_serializer(ticket.payload), call, flags)
TypeError: unbound method SerializeToString() must be called with HelloReply instance as first argument (got int instance instead)
```

and the client side output:
```
loop:0
ex:ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")
cost:10.004531
loop:1
ex:ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")
cost:10.004997
loop:2
ex:NetworkError(code=StatusCode.INTERNAL, details="Received RST_STREAM err=2")
cost:10.004129
loop:3
ex:NetworkError(code=StatusCode.INTERNAL, details="Received RST_STREAM err=2")
cost:10.004836
```

As the output above shows, when the server returns a wrong type(`int` in this case), the client halt there for about the TIMEOUT(10s in this case) duration. So will you change the code to make it like that server side has an exception arises and the client returns as soon as possible? thanks:)

**Comment by nathanielmanistaatgoogle** [comment]
Closing; the work needed here is a subset of [issue 2634](https://github.com/grpc/grpc/issues/2634).
