### ISSUE TITLE
pip install grpcio fails on Mac OS ElCapitan

### ISSUE THREAD

**Issue by vsubramani** [grpc/grpc#6027]
pip install grpcio fails on Mac OS ElCapitan with the below error. Trying the workaround mentioned [here](https://github.com/pypa/pip/issues/3165), gets passed the installation issue but blows up at runtime because of not being able to find the right version of six. 

Actual: Error below
Expected: Package installation should work with any errors

```
Requirement already satisfied (use --upgrade to upgrade): grpcio in /Library/Python/2.7/site-packages
Collecting six>=1.10 (from grpcio)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /Library/Python/2.7/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /Library/Python/2.7/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /Library/Python/2.7/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0a3->grpcio)
Installing collected packages: six
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-WcrzQK-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

```

**Comment by soltanmm** [comment]
What was the *exact command* you used to work around `six` being distutils installed on Mac OS by default? What was the *exact workaround* you used to get a broken system? What were the errors you received from the broken installation?

**Comment by soltanmm** [comment]
Did you use sudo while `pip install`ing?

**Comment by jjangsangy** [comment]
Look like he's trying to install the package in system python 

Due to [System Integrity Protection](https://support.apple.com/en-us/HT204899) in El Capitan, you can't actually write to `/System`. 

```
OSError: [Errno 1] Operation not permitted:

/tmp/pip-WcrzQK-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info
```

This directory is actually symlinked to `/System`, from `/tmp`

**Comment by soltanmm** [comment]
Closing as stale - feel free to re-open if this was done in error!
