### ISSUE TITLE
can not load cygrpc in python3.5

### ISSUE THREAD

**Issue by goldenbull** [grpc/grpc#6040]
Here is the output of greeter_server.py
Is grpc python3 compatible now?

```
C:\Anaconda3\python.exe D:/git/grpc/examples/python/helloworld/greeter_server.py
Traceback (most recent call last):
  File "D:/git/grpc/examples/python/helloworld/greeter_server.py", line 34, in <module>
    import helloworld_pb2
  File "D:\git\grpc\examples\python\helloworld\helloworld_pb2.py", line 109, in <module>
    from grpc.beta import implementations as beta_implementations
  File "C:\Anaconda3\lib\site-packages\grpc\beta\implementations.py", line 38, in <module>
    from grpc._adapter import _intermediary_low
  File "C:\Anaconda3\lib\site-packages\grpc\_adapter\_intermediary_low.py", line 57, in <module>
    from grpc._adapter import _low
  File "C:\Anaconda3\lib\site-packages\grpc\_adapter\_low.py", line 33, in <module>
    from grpc._cython import cygrpc
  File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 69, in init grpc._cython.cygrpc (./src/python/grpcio\grpc/_cython/cygrpc.c:27772)
  File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 58, in grpc._cython.cygrpc._ModuleState.__cinit__ (./src/python/grpcio\grpc/_cython/cygrpc.c:21175)
TypeError: expected bytes, str found
```

**Comment by nicolasnoble** [comment]
Sorry, but, no, grpc is still not compatible with python 3.

**Comment by goldenbull** [comment]
Is there any schedule for python3 compatibility?
