### ISSUE TITLE
Installing grpico on Py 3.5.1 fails via pip

### ISSUE THREAD

**Issue by davidchua** [grpc/grpc#6075]
Python Version: 3.5.1
Installation Method:
```pip install grpcio```

When installing grpcio package via pip, I'm getting a:

```
AttributeError: 'CommandError' object has no attribute 'message'
```

during the installation.

Fulll trace below:

```
Collecting grpcio
  Using cached grpcio-0.13.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.10 in /home/davidc/.virtualenvs/random/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /home/davidc/.virtualenvs/random/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /home/davidc/.virtualenvs/random/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /home/davidc/.virtualenvs/random/lib/python3.5/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/davidc/.virtualenvs/random/lib/python3.5/site-packages (from protobuf>=3.0.0a3->grpcio)
Installing collected packages: grpcio
  Running setup.py install for grpcio: started
    Running setup.py install for grpcio: finished with status 'error'
    Complete output from command /home/davidc/.virtualenvs/random/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xxkaav_8/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-y_rjtftg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/davidc/.virtualenvs/random/include/site/python3.5/grpcio:
    could not download precompiled extension: https://storage.googleapis.com/grpc-precompiled-binaries/python/cygrpc-0.13.1-py3.5-Linux-x86_64-ucsNone.so
    /home/davidc/.virtualenvs/random/lib/python3.5/site-packages/setuptools/command/easy_install.py:310: UserWarning: Unbuilt egg for grpcio [unknown version] (/tmp/pip-build-xxkaav_8/grpcio/src/python/grpcio)
      self.local_index = Environment(self.shadow_path + sys.path)
    running install
    running build
    running build_py
    running build_proto_modules
    Traceback (most recent call last):
      File "/tmp/pip-build-xxkaav_8/grpcio/src/python/grpcio/commands.py", line 209, in run
        self.run_command('build_proto_modules')
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-xxkaav_8/grpcio/src/python/grpcio/commands.py", line 158, in run
        raise CommandError('could not find grpc_python_plugin '
    commands.CommandError: could not find grpc_python_plugin (protoc plugin for GRPC Python)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xxkaav_8/grpcio/setup.py", line 246, in <module>
        setuptools.setup(**setup_arguments)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/davidc/.virtualenvs/random/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/davidc/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-xxkaav_8/grpcio/src/python/grpcio/commands.py", line 211, in run
        sys.stderr.write('warning: %s\n' % error.message)
    AttributeError: 'CommandError' object has no attribute 'message'
    
    ----------------------------------------
```

**Comment by soltanmm** [comment]
We don't yet support Python 3! It's on the roadmap for late this quarter one way or another.

**Comment by davidchua** [comment]
@soltanmm thanks! I tried running it on 2.7.1 earlier and it didn't go through as well so I thought it might had been a release issue.

But nope, its all me! I thought my virtualenv was set to the correct py version despite switching over to 2.7.1 in pyenv.

Got it installed now! Thanks again!
