### ISSUE TITLE
AttributeError: type object 'ConnectivityState' has no attribute 'shutdown'

### ISSUE THREAD

**Issue by jerjou** [grpc/grpc#6125]
I'm trying to use the grpcio package (version 0.13.1 from pypi) to make a streaming api call to the Google Cloud Speech api. You can see my code [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/api/speech_streaming.py). It works in python2.

When I run it with python3, though, I get:

```bash
~/python-docs-samples/speech/api$ python3 speech_streaming.py
Traceback (most recent call last):
  File "speech_streaming.py", line 7, in <module>
    from google.cloud.speech.v1.cloud_speech_pb2 import *  # noqa
  File "/usr/local/google/home/jerjou/opensrc/python-docs-samples/speech/api/venv3/lib/python3.4/site-packages/google/cloud/speech/v1/cloud_speech_pb2.py", line 490, in <module>
    from grpc.beta import implementations as beta_implementations
  File "/usr/local/google/home/jerjou/opensrc/python-docs-samples/speech/api/venv3/lib/python3.4/site-packages/grpc/beta/implementations.py", line 38, in <module>
    from grpc._adapter import _intermediary_low
  File "/usr/local/google/home/jerjou/opensrc/python-docs-samples/speech/api/venv3/lib/python3.4/site-packages/grpc/_adapter/_intermediary_low.py", line 57, in <module>
    from grpc._adapter import _low
  File "/usr/local/google/home/jerjou/opensrc/python-docs-samples/speech/api/venv3/lib/python3.4/site-packages/grpc/_adapter/_low.py", line 33, in <module>
    from grpc._cython import cygrpc
SystemError: error return without exception set
```

which seems to be a generic error that happens when some C code returned an error without setting an exception type.

**Comment by nathanielmanistaatgoogle** [comment]
What hardware, operating system, and version of Python 3?

**Comment by jerjou** [comment]
Linux x86_64 python 3.4.3 [GCC 4.8.4]

**Comment by thunderboltsid** [comment]
@jerjou I'm trying to reproduce the issue. Upon running `python speech_streaming.py`, I get a warning and then it kinda just hangs my shell session. The warning I get is as follows:
```
2016-06-10 20:11:44.250 python[40167:229182] 20:11:44.249 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```

**Comment by thunderboltsid** [comment]
@jerjou Friendly ping!

**Comment by jerjou** [comment]
Huh interesting. I'm getting a different error:

```
$ python3 speech_streaming.py                                                                                                                                                                                           
Exception ignored in: 'grpc._cython.cygrpc.CredentialsMetadataPlugin.make_c_plugin'
TypeError: expected bytes, str found
...
Segmentation fault (core dumped)
```

Are you running in a virtualenv? Did you do `pip3 install -r requirements-grpc.txt`?

`speech_streaming.py` uses pyaudio (which depends on pulseaudio being installed) to listen for audio on your mic. It's expected to hang, listening for audio and transcribing words it hears until it hears 'exit'.

Anyway, it sounds like you got further than I did. Did you use the same `requirements-grpc.txt`?

**Comment by thunderboltsid** [comment]
@jerjou Ran this in a venv. Managed to replicate the issue. Will look into it.

**Comment by nathanielmanistaatgoogle** [comment]
(Current status of this issue is [this stack trace](http://pastebin.com/HuW0Pdjf).)

**Comment by jerjou** [comment]
Oh nice - how did you manage to get the more-informative stack?

**Comment by thunderboltsid** [comment]
@jerjou From my understanding, the issue should already be resolved in the current master branch and would be shipped out with the new release. Are you available for a quick skype call? My username is thunderboltsid

**Comment by thunderboltsid** [comment]
This issue can be marked close now. For anyone seeing the aforementioned error, do `git clean -xdf` (WARNING: It will clean everything in the repo), it's likely originating from a stale `cygrpc.so` file.
