### ISSUE TITLE
Node Error: Module version mismatch

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#6218]
It's highly likely it's my environment problem but I couldn't seem to find a solution. 

I recently upgraded Node to version 4 and try to run some test on the `master` branch and ran into this error:

```
~/grpc$ node src/node/test/math/math_server.js 
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/google/home/stanleycheung/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
stanleycheung@gummybear:~/grpc$ which npm
/usr/local/google/home/stanleycheung/.nvm/versions/node/v4.4.2/bin/npm
stanleycheung@gummybear:~/grpc$ which node
/usr/local/google/home/stanleycheung/.nvm/versions/node/v4.4.2/bin/node
stanleycheung@gummybear:~/grpc$ npm -v
2.15.0
stanleycheung@gummybear:~/grpc$ node -v
v4.4.2
```

I removed the entire `node_modules` folder and re-ran `npm install` on the root `grpc` directory

**Comment by murgatroid99** [comment]
If you change the Node version you have to explicitly update the gRPC binary by doing `npm install --update-binary`

**Comment by stanley-cheung** [comment]
Yes, that solved my problem. Thanks!
