### ISSUE TITLE
grpc node.js module doesn't install w/ gcc 4.6

### ISSUE THREAD

**Issue by ianlewis** [grpc/grpc#6302]
I tried to install on a BeagleBone Green and got the following error:

```
npm WARN package.json io-2016-iot-demo@0.0.1 No repository field.
npm WARN package.json io-2016-iot-demo@0.0.1 No README data
npm WARN package.json io-2016-iot-demo@0.0.1 license should be a valid SPDX license expression

> sse4_crc32@5.0.0 install /root/client/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/fast-crc32c/node_modules/sse4_crc32
> node-gyp rebuild

gyp ERR! configure error 
 stack Error: EACCES, mkdir '/root/client/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/fast-crc32c/node_modules/sse4_crc32/build'
gyp ERR! System Linux 3.8.13-bone71.1
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/client/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/fast-crc32c/node_modules/sse4_crc32
gyp ERR! node -v v0.10.42
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing sse4_crc32@5.0.0
-
> grpc@0.13.1 install /root/client/node_modules/gcloud/node_modules/grpc
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
npm ERR! Linux 3.8.13-bone71.1
npm ERR! argv "/root/opt/node-v4.4.3-linux-armv7l/bin/node" "/root/opt/node-v4.4.3-linux-armv7l/bin/npm" "install" "gcloud"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! grpc@0.13.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the grpc@0.13.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/client/npm-debug.log
```

npm-debug.log had this traceback in it:

```
33590 info grpc@0.13.1 Failed to exec install script
33591 verbose unlock done using /root/.npm/_locks/grpc-f247cb14c0f020d1.lock for /root/client/node_modules/gcloud/node_modules/grpc
33592 verbose about to build /root/client/node_modules/gcloud
33593 verbose unlock done using /root/.npm/_locks/gcloud-a823c70d2a5d5b62.lock for /root/client/node_modules/gcloud
33594 verbose stack Error: grpc@0.13.1 install: `node-pre-gyp install --fallback-to-build`
33594 verbose stack spawn ENOENT
33594 verbose stack     at ChildProcess.<anonymous> (/root/opt/node-v4.4.3-linux-armv7l/lib/node_modules/npm/lib/utils/spawn.js:17:16)
33594 verbose stack     at emitTwo (events.js:87:13)
33594 verbose stack     at ChildProcess.emit (events.js:172:7)
33594 verbose stack     at maybeClose (internal/child_process.js:827:16)
33594 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by IanLewis** [comment]
This is a permissions error because I was trying to install as root. If I fix that issue I ran into another error. It looks like it's because the Debian on the BeagleBone Green only has gcc 4.6.

http://stackoverflow.com/questions/16256586/how-to-enable-c11-on-later-versions-of-gcc

```
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [Release/obj.target/grpc_node/src/node/ext/byte_buffer.o] Error 1
make: Leaving directory `/home/debian/client/node_modules/gcloud/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.8.13-bone71.1
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/debian/client/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/debian/client/node_modules/gcloud/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /home/debian/client/node_modules/gcloud/node_modules/grpc
gyp ERR! node -v v0.10.42
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/home/debian/client/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/debian/client/node_modules/gcloud/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/debian/client/node_modules/gcloud/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.8.13-bone71.1
node-pre-gyp ERR! command "node" "/home/debian/client/node_modules/gcloud/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/debian/client/node_modules/gcloud/node_modules/grpc
node-pre-gyp ERR! node -v v0.10.42
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/home/debian/client/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/debian/client/node_modules/gcloud/node_modules/grpc/src/node/extension_binary' (1)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! grpc@0.13.2-pre1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.13.2-pre1 install script.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.13-bone71.1
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/debian/client
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/debian/client/npm-debug.log
npm ERR! not ok code 0
```

**Comment by murgatroid99** [comment]
I don't think the library will compile without C++11, and we don't distribute precompiled ARM binaries. I think that the best solution here will be to upgrade gcc.

**Comment by borg286** [comment]
On brand spanking new Ubuntu 16.04 I installed npm, cloned this repo, and tried doing 'npm install' on the node example and ran into this same error.

```
npm ERR! grpc@0.13.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@0.13.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/borg/grpc/examples/node/npm-debug.log

```

**Comment by soltanmm** [comment]
@borg286 Yo dawg, I heard your error message suggested including a debug file located at `/home/borg/grpc/examples/node/npm-debug.log`. Could you attach that log to your log so we can build your build?

(that aside, given your stated distribution you probably have a compiler newer than GCC 4.6 and should file a separate bug with all the details attached)

**Comment by borg286** [comment]
http://pastebin.com/qxEC2qed

This may be relevant

borg@ubuntu:~/grpc/examples/node$ node-pre-gyp install --fallback-to-build
node-pre-gyp: command not found

I think the install script assumes the user has node-pre-gyp installed, when npm seems to be the only one assumed.

**Comment by borg286** [comment]
Namely this one: https://github.com/grpc/grpc/blob/master/src/node/tools/package.json#L23

**Comment by borg286** [comment]
It seems to be coupled with the assumption that protoc is a binary on the user's system: https://github.com/grpc/grpc/commit/2dc8442eeff523f7201b201022e5b684076bb6e2#diff-6cddcfad7bd54c7a9378422ff82848c4R46

I just tried to install the debian tools on http://www.grpc.io/docs/installation/node.html but alas, I get the same error. Tell me, do these debian packages bring protoc with them? After the above install I don't have the binaries it seems, yet the protoc.js file seems to assume there is.

**Comment by murgatroid99** [comment]
The install script does not assume that `node-pre-gyp` is installed on your system; `node-pre-gyp` is bundled with the package. I don't know why that is failing, but I will look into it.

That `protoc.js` is completely irrelevant here. Not only is that file not distributed with this package, but when it is distributed, it will be distributed with the protoc binary.

**Comment by borg286** [comment]
After installing nodejs-legacy it installed correctly.
