### ISSUE TITLE
Leak in `bins/asan/h2_proxy_test cancel_after_*`

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#6395]
```
=================================================================
==118148==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 248 byte(s) in 1 object(s) allocated from:
    #0 0x4b057b in malloc /home/development/llvm/3.8.0/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52:3
    #1 0x57744c in grpc_raw_compressed_byte_buffer_create /usr/local/google/home/dgq/grpc/forks/grpc/src/core/surface/byte_buffer.c:47:26
    #2 0x57733e in grpc_raw_byte_buffer_create /usr/local/google/home/dgq/grpc/forks/grpc/src/core/surface/byte_buffer.c:40:10
    #3 0x584383 in process_data_after_md /usr/local/google/home/dgq/grpc/forks/grpc/src/core/surface/call.c:1034:33
    #4 0x581cd5 in receiving_stream_ready /usr/local/google/home/dgq/grpc/forks/grpc/src/core/surface/call.c:1052:5
    #5 0x55f4e6 in grpc_exec_ctx_flush /usr/local/google/home/dgq/grpc/forks/grpc/src/core/iomgr/exec_ctx.c:54:7
    #6 0x5638dd in grpc_pollset_work /usr/local/google/home/dgq/grpc/forks/grpc/src/core/iomgr/pollset_posix.c:322:22
    #7 0x58e7a2 in grpc_completion_queue_next /usr/local/google/home/dgq/grpc/forks/grpc/src/core/surface/completion_queue.c:342:7
    #8 0x54da2c in thread_main /usr/local/google/home/dgq/grpc/forks/grpc/test/core/end2end/fixtures/proxy.c:413:21
    #9 0x5ef4bd in thread_body /usr/local/google/home/dgq/grpc/forks/grpc/src/core/support/thd_posix.c:57:3
    #10 0x7f5794b4c181 in start_thread /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
```

After running a bisect, it seems the issue was introduced as part of 
https://github.com/grpc/grpc/pull/2286 (commit 3abb242e3beb2e06110ad560b6ef2f1e2a922967). In particular, `surface/call.c::receiving_slice_ready` doesn't seem to be properly invoked whilst under load, which is the callback for the `grpc_byte_stream_next` call on line 992.

**Comment by muxi** [comment]
Does not seem to appear as of now. Closing

**Comment by hcaseyal** [comment]
Closing because this issue doesn't seem to have appeared for at least several months.

**Comment by hcaseyal** [comment]
Changing priority because of incorrect triaging.
