### ISSUE TITLE
Flake: bins/opt/end2end_test:SecureEnd2end/SecureEnd2endTest.BlockingAuthMetadataPluginAndProcessorFailure/0  polling=legacy

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#6668]
at master 3c62c555a4d1b4385d4f8c6c9f533c34c82cec5a

```
[ RUN      ] SecureEnd2end/SecureEnd2endTest.BlockingAuthMetadataPluginAndProcessorFailure/0
I0520 17:31:04.659306817   25359 end2end_test.cc:198]        Scenario: proxy 0, credentials ssl
D0520 17:31:04.659419997   25359 ev_posix.c:101]             Using polling engine: legacy
E0520 17:31:04.663952921   25360 tcp_client_posix.c:173]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
D0520 17:31:04.679698200   25359 ev_posix.c:101]             Using polling engine: legacy
E0520 17:31:04.692644281   25363 sync_posix.c:51]            assertion failed: pthread_mutex_lock(mu) == 0
```

It only happens for opt and dbg (no asan _sad face_). It needs a high number of antagonists and -n inf. To wit:

`./tools/run_tests/run_tests.py -l c++ -c dbg -n inf -a 20 -r Test.BlockingAuthMetadataPluginAndProcessorFailure -S`

The dbg run does dump a core. Here's the backtrace:

```
#0  0x00007f01a05d7cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f01a05db0d8 in __GI_abort () at abort.c:89
#2  0x0000000000491cf3 in gpr_mu_lock (mu=0x90bb40 <g_freelist_mu>) at src/core/lib/support/sync_posix.c:51
#3  0x00000000004a493e in grpc_cq_internal_unref (cc=0x20ddc30) at src/core/lib/surface/completion_queue.c:191
#4  0x00000000004a672f in server_delete (exec_ctx=0x7f01a059f7d0, server=0x20dde10) at src/core/lib/surface/server.c:373
#5  0x00000000004a67f2 in server_unref (exec_ctx=0x7f01a059f7d0, server=0x20dde10) at src/core/lib/surface/server.c:386
#6  0x00000000004a81a8 in destroy_channel_elem (exec_ctx=0x7f01a059f7d0, elem=0x7f019800b358) at src/core/lib/surface/server.c:880
#7  0x0000000000493e00 in grpc_channel_stack_destroy (exec_ctx=0x7f01a059f7d0, stack=0x7f019800b328) at src/core/lib/channel/channel_stack.c:154
#8  0x00000000004a3d57 in destroy_channel (exec_ctx=0x7f01a059f7d0, arg=0x7f019800b2e0, iomgr_success=true) at src/core/lib/surface/channel.c:272
#9  0x000000000049a59d in grpc_exec_ctx_flush (exec_ctx=0x7f01a059f7d0) at src/core/lib/iomgr/exec_ctx.c:70
#10 0x000000000049a5f3 in grpc_exec_ctx_finish (exec_ctx=0x7f01a059f7d0) at src/core/lib/iomgr/exec_ctx.c:81
#11 0x00000000004a0946 in grpc_call_destroy (c=0x7f0198012ca0) at src/core/lib/surface/call.c:677
#12 0x00000000004a6511 in kill_zombie (exec_ctx=0x7f01a059f910, elem=0x7f01980131e8, success=true) at src/core/lib/surface/server.c:324
#13 0x000000000049a59d in grpc_exec_ctx_flush (exec_ctx=0x7f01a059f910) at src/core/lib/iomgr/exec_ctx.c:70
#14 0x000000000049a5f3 in grpc_exec_ctx_finish (exec_ctx=0x7f01a059f910) at src/core/lib/iomgr/exec_ctx.c:81
#15 0x0000000000547229 in on_md_processing_done (user_data=0x7f0198013200, consumed_md=0x0, num_consumed_md=0, response_md=0x0, num_response_md=0, 
    status=GRPC_STATUS_UNAUTHENTICATED, error_details=0x7f017c000b78 "Invalid principal: Mr Hyde") at src/core/lib/security/server_auth_filter.c:152
#16 0x00000000004730f9 in grpc::AuthMetadataProcessorAyncWrapper::InvokeProcessor (this=0x20d9260, ctx=0x7f019800d400, md=0x7f01980025e0, num_md=6, 
    cb=0x546f54 <on_md_processing_done>, user_data=0x7f0198013200) at src/cpp/server/secure_server_credentials.cc:108
#17 0x0000000000475c0d in std::_Mem_fn<void (grpc::AuthMetadataProcessorAyncWrapper::*)(grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)>::operator()<grpc_auth_context*&, grpc_metadata const*&, unsigned long&, void (*&)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*&, void> (this=0x7f017c0008c0, __object=0x20d9260) at /usr/include/c++/4.8/functional:601
#18 0x0000000000475817 in std::_Bind<std::_Mem_fn<void (grpc::AuthMetadataProcessorAyncWrapper::*)(grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::AuthMetadataProcessorAyncWrapper*, grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)>::__call<void, , 0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) (this=0x7f017c0008c0, 
    __args=<unknown type in /usr/local/google/home/dgq/grpc/forks/grpc/bins/dbg/end2end_test, CU 0x1a8e5f, DIE 0x1c3bdd>)
    at /usr/include/c++/4.8/functional:1296
#19 0x0000000000474fe4 in std::_Bind<std::_Mem_fn<void (grpc::AuthMetadataProcessorAyncWrapper::*)(grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::AuthMetadataProcessorAyncWrapper*, grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)>::operator()<, void>() (this=0x7f017c0008c0)
    at /usr/include/c++/4.8/functional:1355
#20 0x00000000004749d0 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::AuthMetadataProcessorAyncWrapper::*)(grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::AuthMetadataProcessorAyncWrapper*, grpc_auth_context*, grpc_metadata const*, unsigned long, void (*)(void*, grpc_metadata const*, unsigned long, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> >::_M_invoke(std::_Any_data const&) (
    __functor=...) at /usr/include/c++/4.8/functional:2071
#21 0x000000000047be80 in std::function<void ()>::operator()() const (this=0x7f01a059fd40) at /usr/include/c++/4.8/functional:2471
#22 0x000000000047b31b in grpc::DynamicThreadPool::ThreadFunc (this=0x20d9410) at src/cpp/server/dynamic_thread_pool.cc:81
#23 0x000000000047b128 in grpc::DynamicThreadPool::DynamicThread::ThreadFunc (this=0x20d9280) at src/cpp/server/dynamic_thread_pool.cc:50
#24 0x000000000047ed63 in std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const (this=0x20daab8, __object=0x20d9280) at /usr/include/c++/4.8/functional:601
#25 0x000000000047ecb3 in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x20daab0) at /usr/include/c++/4.8/functional:1732
#26 0x000000000047ebbb in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() (this=0x20daab0) at /usr/include/c++/4.8/functional:1720
#27 0x000000000047eb54 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() (this=0x20daa98) at /usr/include/c++/4.8/thread:115
#28 0x00007f01a0f33a60 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:84
#29 0x00007f01a13a7182 in start_thread (arg=0x7f01a05a0700) at pthread_create.c:312
#30 0x00007f01a069b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by dgquintas** [comment]
@ctiller FYI
