### ISSUE TITLE
[Node.js] Handshake failed with fatal error SSL_ERROR_SSL: BAD_ECC_CERT

### ISSUE THREAD

**Issue by jo3l33** [grpc/grpc#6722]
Hello, 
I am trying to connect from node.js script to external grpc API using TLS with self signed cert (please see below) but during the handshake grpc terminates with following error:

```
E0527 09:49:28.689000000  4712 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:1000006b:SSL routines:OPENSSL_internal:BA
D_ECC_CERT.
E0527 09:49:28.689000000  4712 handshake.c:241] Handshake failed with error TSI_PROTOCOL_FAILURE
E0527 09:49:28.689000000  4712 secure_channel_create.c:99] Secure handshake failed with error 1.
{ [Error] code: 14, metadata: Metadata { _internal_repr: {} } }
```

I am running `Node.js (v.4.4.5 LTS)` under `win 7 (x64bit)` with `GRPC package (v. 0.14.1)` installed via `npm install grpc --save`.

The script I am running is this:

```
var fs = require('fs');
var path = require('path');
var os = require('os');

process.env['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA';

var grpc = require('grpc');
var protoDescriptor = grpc.load('./api.proto');
var walletrpc = protoDescriptor.walletrpc;

var cert = fs.readFileSync('rpc.cert');
var creds = grpc.credentials.createSsl(cert);
var client = new walletrpc.WalletService('127.0.0.1:9110', creds);

var request = {
    account_number: 0,
    required_confirmations: 1
};
client.balance(request, function(err, response) {
    if (err) {
        console.error(err);
    } else {
        console.log('Spendable balance:', response.spendable);
    }
})
```

Certificate file is standard certificate:

`-----BEGIN CERTIFICATE-----
MIICkzCCAfWgAwIBAgIRAMtVW1yCGKIrJBcbmqYVu3owCgYIKoZIzj0EAwQwPDEl
MCMGA1UEChMcZGNyd2FsbGV0IGF1dG9nZW5lcmF0ZWQgY2VydDETMBEGA1UEAxMK
bm9uYW1lMi1QQzAeFw0xNjA0MjUyMTIwMTJaFw0yNjA0MjQyMTIwMTJaMDwxJTAj
BgNVBAoTHGRjcndhbGxldCBhdXRvZ2VuZXJhdGVkIGNlcnQxEzARBgNVBAMTCm5v
bmFtZTItUEMwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAASZVcgIuql7ho9aGv0
X0DuHVcAKBmBbegMi7fPbaXRNmIDFQ3XKaj/lbNGYXX5AyEhaTckZQn0KZip6onh
qG2SFgEpy4uaUULC84m5axEX21X4c74moLHkbklYkRQWRRIBfVqfKPc0QUPUwn7r
PQnmAUARq9Nndlh8EDTEGZATSU3gYKOBlDCBkTAOBgNVHQ8BAf8EBAMCAqQwDwYD
VR0TAQH/BAUwAwEB/zBuBgNVHREEZzBlggpub25hbWUyLVBDgglsb2NhbGhvc3SH
BH8AAAGHEAAAAAAAAAAAAAAAAAAAAAGHBMCoAWSHEP6AAAAAAAAArEkF3rly3muH
BAoEE9KHEP6AAAAAAAAA/XXG85N81M+HBMCoOAEwCgYIKoZIzj0EAwQDgYsAMIGH
AkIBX6FOBzDM0kUGIXNfNljng0T4aIk/xCHACdSa56iaqQxM25CmZSri2lT0rMIV
WX7FcrQLYUN3GXMy4nmTGOwG2mgCQUhutDgUjTslkie+5QM9HGAtNKg09e9yGyQ0
NYR99j5FNVmNvvS3kRF33XncGvundj21SEKWo/ykYMpIWYW8F/fl
-----END CERTIFICATE-----`

Please help me with this error - where is the problem/how  should I debug it ? Is it cert problem - GRPC problem ?
Thank you very much in advance for any help!

**Comment by jrick** [comment]
To add more detail to this issue, the same client and server code work fine on Linux, but the client is unable to connect when running on Windows.

Keys and certificates are being generated with this code: https://github.com/decred/dcrutil/blob/85fac3a15425f15408f1dcec28bfd4b18ea2f882/certgen.go#L25

There is also a [standalone tool](https://github.com/decred/dcrd/blob/master/cmd/gencerts/) that can be used to generate the keypairs (can be useful for reproducing this issue with other servers).  To install: `go get -u github.com/dered/dcrd/cmd/gencerts`.

**Comment by murgatroid99** [comment]
I notice that the certificate you are using uses IP addresses as Subject Alternative Names. And the primary difference between the Linux and Windows versions of the gRPC library is that the Linux library uses OpenSSL and the Windows library uses BoringSSL. It may be that BoringSSL cannot handle that kind of certificate.

As an alternative to using machine-specific certificates for testing, you can use a regular certificate for a domain, and initialize the client with a couple of extra options. For example, you could use a self-signed certificate for `example.com` and change the client construction line to this:

```
var options = {
  'grpc.ssl_target_name_override' : 'example.com',
  'grpc.default_authority': 'example.com'
};
var client = new walletrpc.WalletService('127.0.0.1:9110', creds, options)
```

This will make the client validate the certificate it receives as though it came from `example.com`.

**Comment by jrick** [comment]
Is BoringSSL or OpenSSL used for the C# client?  Because I have no issues connecting a C# client (.NET Framework 4.6 on Windows) to the same server.

**Comment by murgatroid99** [comment]
CC @jtattermusch

**Comment by jtattermusch** [comment]
C# on windows is currently using OpenSSL (and we are planning to switch to boringssl eventually). On linux, it has been switched to boringssl a while ago.

**Comment by mocsharp** [comment]
@jrick do you happened to have an example of the server and client in c# that you can share?

I generated certs using https://github.com/codequest-eu/grpc-demo/blob/master/keys/generate.sh with oepnssl for windows but am also running into **Handshake failed with error TSI_PROTOCOL_FAILURE** error.

Thank you!

**Comment by angshuman** [comment]
I am running into the same issue on Windows with Grpc 1.0. I am not using self signed certificate but actual issued one. Was there a solution to this?

**Comment by jrick** [comment]
I'm also helping @alexyp troubleshoot with his issue in #8601.

> I notice that the certificate you are using uses IP addresses as Subject Alternative Names.

We just tried removing all IP addresses from the SANs, leaving only localhost and the computer's hostname.  The client is dialing localhost (as expected, dialing 127.0.0.1 or ::1fails).  When election is not included by the linux client (so it is using OpenSSL rather than BoringSSL), the connection works.  When adding electron (so gRPC uses BoringSSL) then the security handshake still fails.  So it must be something other than IP addresses in the SANs...

**Comment by murgatroid99** [comment]
The thing with IP addresses was just a guess, and you're right, it looks like that's not the cause of the problem. But it also looks like the problem is caused by some difference between OpenSSL and BoringSSL. Maybe the corresponding command line tools from each could help determine what's going on.

**Comment by jcvernaleo** [comment]
So I tried using the command lines tools (openssl and bssl) to connect to the kind of server @jrick was talking about.  openssl connects fine.  With bssl (on Linux) I get:
```
jcv@triforce tool $ ./bssl s_client -connect 127.0.0.1:9110
Connecting to 127.0.0.1:9110
Error while connecting: 1
41106832:error:1000006b:SSL routines:OPENSSL_internal:BAD_ECC_CERT:/home/jcv/code/boringssl/ssl/ssl_cert.c:821:
```

**Comment by murgatroid99** [comment]
Thank you for investigating this. That appears to confirm the hypothesis that for some reason, OpenSSL and BoringSSL treat those certificates differently. I would suggest reporting the problem to BoringSSL; that seems like the most likely path to getting this fixed.

**Comment by jrick** [comment]
This can probably be closed.  We discovered boringssl removed all EC support except for P-256 and P-384, while were using P-521.  We are changing to P-384, which works with boringssl.

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/kWwLfeIQIBM/9chGZ40TCQAJ

**Comment by jrick** [comment]
Seems I spoke too soon, still getting SSL_BAD_CERT even with P-384:

```
E1115 20:28:12.846000000 16076 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:1000006b:SSL routines:OPENSSL_internal:BAD_ECC_CERT.
E1115 20:28:12.846000000 16076 handshake.c:128] Security handshake failed: {"created":"@1479259692.846000000","description":"Handshake failed","file":"..\src\core\lib\security\transport\handshake.c","file_line":264,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
{ Error
    at C:\Users\jrick\node_modules\grpc\src\node\src\client.js:417:17 code: 14, metadata: Metadata { _internal_repr: {} } }
```

**Comment by jrick** [comment]
@hsaliak can this be reopened? appears to still be an issue for me everywhere boringssl is used (windows, electron).  The latest bssl built from boringssl master connects fine but not the others.  I assume either a new boringssl needs to be used, or there is a bug in boringssl's usage in the tsi lib that is causing the handshake error.

**Comment by hsaliak** [comment]
For sure. Thanks for responding back on the issue and the additional details.

**Comment by jcvernaleo** [comment]
It looks like grpc uses a much older boringssl than I was using for the command line tests.  I'd like to test grpc with a newer boringssl.  I can update the repo in the third_party directory but my builds still fail with:
```
  CC(target) Release/obj.target/boringssl/third_party/boringssl/crypto/asn1/t_bitst.o
make: *** No rule to make target 'Release/obj.target/boringssl/third_party/boringssl/crypto/asn1/t_pkey.o', needed by 'Release/obj.target/libboringssl.a'.  Stop.
make: Leaving directory '/data/shared/tmp/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jcv/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-47-generic
gyp ERR! command "/home/jcv/.nvm/versions/node/v6.5.0/bin/node" "/home/jcv/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--runtime=electron" "--disturl=https://atom.io/download/atom-shell" "--target=1.4.6" "--module=/data/shared/tmp/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/data/shared/tmp/grpc/src/node/extension_binary"
gyp ERR! cwd /data/shared/tmp/grpc
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```
(there is more output that I can share but it didn't look too helpful).  Is there some extra step I need after updating the third_party repo before I can do a test build that I'm missing?

**Comment by murgatroid99** [comment]
It looks like some files may have been added or removed in BoringSSL. If that is the case, you should be able to run `tools/buildgen/generate_projects.sh` to regenerate `package.json`.

**Comment by jcvernaleo** [comment]
Thanks.  I actually discovered that script about half an hour ago so I was able to build grpc with a newer boringssl.  Going to test with something closer to what I used on the command line now.

**Comment by nitinlodhe** [comment]
<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative-boringssl-static</artifactId>
		        <version>1.1.33.Fork26</version>
			<classifier>windows-x86_64</classifier>
			
		</dependency>

I am using this dependency and still getting the same error

**Comment by Jose-CF** [comment]
Experiencing the same problem. Did you find out any workarounds?

**Comment by mably** [comment]
Has a solution been found to this problem yet?  I'm stuck too.

**Comment by jrick** [comment]
Certs using the P-256 curve are working fine.

**Comment by mably** [comment]
@jrick it works! thanks.

**Comment by muxi** [comment]
@murgatroid99 is this solved?

**Comment by lawliet89** [comment]
This also happens on the Python library.

In any case, P384 curves are not supported. You have to use P256. Probably a BoringSSL issue.

**Comment by ssiloti** [comment]
For the sake of documentation, the offending code is:

https://github.com/grpc/grpc/blob/7b63731b87ccdcc24b03e25f13a2bb91d0531b0f/src/core/tsi/ssl_transport_security.cc#L695

It appears this code was added to configure ECDH to use P-256, but it has the side effect of also restricting ECC certificate keys to that curve.

**Comment by mastersingh24** [comment]
Node 10 TLS not working for us either ... seems like certificate verification is failing ... works with Node 8.  We are using P-256 certs:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            02:6c:86:dd:39:39:dc:81:b9:ec:c7:c3:e4:60:cd:6b
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: serialNumber=158006625605442038503088828480991666707
        Validity
            Not Before: Mar 20 12:25:18 2019 GMT
            Not After : Mar 18 12:25:18 2029 GMT
        Subject: serialNumber=3221959422312993751132547075436236139
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:96:ed:4d:23:f5:ef:fe:31:08:c2:4b:8c:77:77:
                    1c:53:7f:ab:7f:00:a9:6c:ca:52:ea:fb:b8:26:61:
                    fd:36:89:d2:0a:0c:c2:89:54:cf:26:d4:01:18:1a:
                    76:ca:97:a1:e5:d7:1b:47:8c:83:09:a6:43:b7:18:
                    a1:08:e0:4b:09
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:peer0.org2.example.com
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:c8:27:b9:bd:ba:83:4d:21:eb:40:44:dd:04:
         69:2c:af:7e:39:48:ce:6a:eb:4e:90:d4:50:af:61:e7:ec:c6:
         67:02:20:72:82:5b:eb:d8:3a:97:ca:01:ef:2d:61:1d:44:32:
         11:8f:29:f3:2d:80:06:0e:13:89:51:db:a1:55:c6:7e:bb
```

**Comment by AspirinSJL** [comment]
Raising priority because it's been a long time since creation.

**Comment by ssiloti** [comment]
I don't see any obvious changes which would address this. I suspect everyone who hits the bug now finds this issue and quietly switches their certs to use P-256.

Or course your bot doesn't know that, so it will dutifully close this issue 180 days from now. Yay automation!

**Comment by DaniGuardiola** [comment]
Stumbled upon this issue in the Python library while trying to use secp256k1. Tried to switch to P-256 (prime256v1) and it still doesn't work. We're pretty much stuck. Help? :)

**Comment by stanley-cheung** [comment]
@murgatroid99 ping, seems like this is on the c stack. With the release of the JS stack, if this is no longer relevant, please close. Thanks!

**Comment by anon17** [comment]
```
openssl ecparam -genkey -name prime256v1 -noout -out server4.key
openssl req -x509 -new -key server4.key -out server4.crt -days 3650 -subj '/CN=test.local'
```
```cs
var cred = new SslCredentials(cert);
var options = new[] { new ChannelOption("grpc.ssl_target_name_override", "test.local:5000") };
Channel channel = new Channel(Address, Port, cred, options);
```
This way I got it working.

**Comment by seanamos** [comment]
> I don't see any obvious changes which would address this. I suspect everyone who hits the bug now finds this issue and quietly switches their certs to use P-256.
> 
> Or course your bot doesn't know that, so it will dutifully close this issue 180 days from now. Yay automation!

That's exactly how I ended up here. This obviously doesn't just affect Node.js as the title might imply. I imagine many people are hitting this when they try to use Envoy.
