### ISSUE TITLE
Python Client 0.14.0 don't recover from connection failure

### ISSUE THREAD

**Issue by bclermont** [grpc/grpc#6730]
# Issue

Python client version `0.14.0` don't recover and reconnect to server if any failures occurs.
Problem can't be reproduced in `0.13.1`.

Either if the client is started and the server isn't available.
Or if the server restart while client is running.

# Tests

Tested on gRPC latest pypi version `0.14.0` as `.1` isn't in pypi yet.
On both OSX ElCapitan and Linux (Ubuntu trusty).
And using Python and Golang server.
With and without IPv6.

To show the problem, I modified `greeter_client.py` to loop:

```
diff --git a/examples/python/helloworld/greeter_client.py b/examples/python/helloworld/greeter_client.py
index 40d637f..4b53dcb 100644
--- a/examples/python/helloworld/greeter_client.py
+++ b/examples/python/helloworld/greeter_client.py
@@ -30,6 +30,7 @@
 """The Python implementation of the GRPC helloworld.Greeter client."""

 from __future__ import print_function
+import time

 from grpc.beta import implementations

@@ -41,8 +42,10 @@ _TIMEOUT_SECONDS = 10
 def run():
   channel = implementations.insecure_channel('localhost', 50051)
   stub = helloworld_pb2.beta_create_Greeter_stub(channel)
-  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
-  print("Greeter client received: " + response.message)
+  while True:
+    time.sleep(1)
+    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
+    print("Greeter client received: " + response.message)
```

```
(test2) [11:26] ~/test/src/grpc/examples/python/helloworld python greeter_client.py
Greeter client received: Hello, you!
Greeter client received: Hello, you!
Greeter client received: Hello, you!
Greeter client received: Hello, you!
E0531 11:26:07.204037000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 11:26:07.204308000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
Traceback (most recent call last):
  File "greeter_client.py", line 52, in <module>
    run()
  File "greeter_client.py", line 47, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/Users/test2/lib/python2.7/site-packages/grpc/framework/crust/implementations.py", line 75, in __call__
    protocol_options, metadata, request)
  File "/Users/ben/test2/lib/python2.7/site-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/Users/test2/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 415, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.NetworkError: NetworkError(code=StatusCode.UNAVAILABLE, details="")
E0531 11:26:12.321777000 123145306509312 tcp_client_posix.c:191] failed to connect to 'ipv4:127.0.0.1:50051': timeout occurred
E0531 11:26:12.425114000 123145306509312 tcp_client_posix.c:191] failed to connect to 'ipv6:[::1]:50051': timeout occurred
E0531 11:26:16.325317000 123145306509312 tcp_client_posix.c:191] failed to connect to 'ipv4:127.0.0.1:50051': timeout occurred
E0531 11:26:17.189443000 123145306509312 tcp_client_posix.c:191] failed to connect to 'ipv6:[::1]:50051': timeout occurred
```

First it's working, then I stop server and start it.
It never recover when server is started.

after this, the process must be killed (see #3820).

Go client output:

```
2016/05/31 11:21:35 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
2016/05/31 11:21:37 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
2016/05/31 11:21:40 Greeting: Hello, world!
```

it recovered.

# How to reproduce

Run unchanged  `greeter_client.py` *before* `greeter_server.py`.

the client never connecter ever after that,.

**Comment by bclermont** [comment]
I just tried C++ client as it also use the same C library and it recovered correctly:

```
~/test/src/grpc/examples/cpp/helloworld git diff greeter_client.cc
diff --git a/examples/cpp/helloworld/greeter_client.cc b/examples/cpp/helloworld/greeter_client.cc
index bf3b63c..8419186 100644
--- a/examples/cpp/helloworld/greeter_client.cc
+++ b/examples/cpp/helloworld/greeter_client.cc
@@ -88,8 +88,10 @@ int main(int argc, char** argv) {
   GreeterClient greeter(grpc::CreateChannel(
       "localhost:50051", grpc::InsecureChannelCredentials()));
   std::string user("world");
-  std::string reply = greeter.SayHello(user);
-  std::cout << "Greeter received: " << reply << std::endl;
+  while(1) {
+    std::string reply = greeter.SayHello(user);
+    std::cout << "Greeter received: " << reply << std::endl;
+  }

   return 0;
 }
```

output:

```
~/test/src/grpc/examples/cpp/helloworld ./greeter_client
D0531 11:48:11.441326000 140735317880832 ev_posix.c:100] Using polling engine: poll
E0531 11:48:11.445295000 140735317880832 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 11:48:11.445501000 140735317880832 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
Greeter received: RPC failed
E0531 11:48:13.447448000 140735317880832 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 11:48:13.447551000 140735317880832 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
Greeter received: RPC failed
E0531 11:48:16.620150000 140735317880832 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 11:48:16.853832000 140735317880832 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
Greeter received: RPC failed
Greeter received: Hello world
Greeter received: Hello world
Greeter received: Hello world
```

**Comment by wukai-gd** [comment]
I have the same problem. I found that `self._down()` can't exit the threads pool.

**Comment by bclermont** [comment]
maybe it's related to:

```
E0531 11:26:07.204308000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
Traceback (most recent call last):
  File "greeter_client.py", line 52, in <module>
    run()
  File "greeter_client.py", line 47, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/Users/test2/lib/python2.7/site-packages/grpc/framework/crust/implementations.py", line 75, in __call__
    protocol_options, metadata, request)
  File "/Users/ben/test2/lib/python2.7/site-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/Users/test2/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 415, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.NetworkError: NetworkError(code=StatusCode.UNAVAILABLE, details="")
E0531 11:26:12.321777000 123145306509312 tcp_client_posix.c:191] failed to connect to 'ipv4:127.0.0.1:50051': timeout occurred
```

after the exception is raised, the log switch from `tcp_client_posix.c:173` to `tcp_client_posix.c:191`

**Comment by bclermont** [comment]
I tried gRPC 0.13.1 and the problem isn't there:

```
(test3) [12:52] ben@BensMacBook:~/test/src/grpc/examples/python/helloworld python greeter_client.py
E0531 12:52:55.225108000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 12:52:55.225396000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
E0531 12:52:56.225564000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 12:52:56.225672000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
E0531 12:52:57.536165000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 12:52:57.536254000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
E0531 12:52:59.830059000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 12:52:59.830173000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
Greeter client received: Hello you
Greeter client received: Hello you
Greeter client received: Hello you
Greeter client received: Hello you
Greeter client received: Hello you
Greeter client received: Hello you
E0531 12:53:10.162397000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 12:53:10.162692000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
E0531 12:53:11.165139000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:50051': socket error: connection refused
E0531 12:53:11.165253000 123145306509312 tcp_client_posix.c:173] failed to connect to 'ipv4:127.0.0.1:50051': socket error: connection refused
```

**Comment by bclermont** [comment]
As 0.14.1 isn't in pypi, I couldn't test it

**Comment by GuoJing** [comment]
Same problem here, mark.

**Comment by GuoJing** [comment]
@bclermont looks like master fixed this problem, master grpcio version is 0.15.0.dev0.

**Comment by GuoJing** [comment]
@bclermont sorry, This is not fixed in `0.15.0.dev0`. Looks like this problem started from 0.14.0 and really need to fix.

If we close server, client will not recover from connection failure, it try to reconnect but not  success.

Try this:

start a server and client, then close server, have a client call (will return network error), then restart the server.

Now, if you are using `netstat -an|grep 50051`, you should find out two `ESTABLISHED` connections. But wait some seconds, you will find out the port is changing!

Looks like there is a auto connection recovery mechanism. But has a bug, client try to reconnect (success) but looks like client don't think is success.

**Comment by killpanda** [comment]
+1

**Comment by bclermont** [comment]
I asked here as well https://groups.google.com/d/msg/grpc-io/IcHUk_qt4hU/fac1Kx8IAQAJ

**Comment by hsaliak** [comment]
Thanks for flagging this, will take a look asap. /cc @soltanmm

**Comment by GuoJing** [comment]
hi

master has fixed. Install from source should work. this is bad. 

BUT install from source with tag 0.14.1 still include this bug.

We downgrade to 0.13.1. 

Hope 0.14.1 will fix this. (When release to pip)

Please TEST it. 

Thanks

GuoJing
-----------------------------
http://guojing.me <http://guojing.me/> 
The one who love coding.
--> ret <--
echo null
rm -rf /

**Comment by kpayson64** [comment]
In release 0.14, fail-fast became the default behavior for all wrapped languages (gRPC-Go will follow suit):
https://github.com/grpc/grpc/releases

With fail-fast, attempting to connect to an unavailable server will throw an exception immediately.

We plan on exposing the ability to disable fail-fast mode in the wrapped language APIs, but in the mean time, clients should handle unavailable server exceptions.  

In gRPC-Python, there is an open issue where unhandled exceptions cause the client to freeze:
https://github.com/grpc/grpc/issues/6666

Which causes the issue seen here.

**Comment by GuoJing** [comment]
@kpayson64 Yes, sure, I think fail fast is better than wait for n times then fail. Please fix this bug ASAP, Python client is unuseable.

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: this issue has drifted pretty far over the last month, and some of the problems linked from the discussion have been resolved in the intervening time. What remaining defect is tracked here?

**Comment by kpayson64** [comment]
I think #6770 and #3820 capture the remaining work.
