### ISSUE TITLE
Python Install - distutils.errors.DistutilsPlatformError on OSX 10.11

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#6735]
Upon running `make test_python` with Python 3.4-dev on #6503  throws some interesting errors. Basically, it raises `distutils.errors.DistutilsPlatformError` mentioning a mismatch between the deployment target during configure (OSX 10.11) and make (OSX 10.7). While handling that error, it throws an error `commands.CommandError` from `src/python/grpcio/support.py:122` in `diagnose_build_ext_error`. Find the stack trace attached below.

```
[MAKE]    Generating cache.mk
[RUN]     Testing python code

++ dirname tools/run_tests/build_python.sh
+ cd tools/run_tests/../..
+ TOX_PYTHON_ENV=py34
+ PY_VERSION=34
++ pwd
+ ROOT=/Users/siddharthshukla/grpc
+ export LD_LIBRARY_PATH=/Users/siddharthshukla/grpc/libs/opt
+ LD_LIBRARY_PATH=/Users/siddharthshukla/grpc/libs/opt
+ export DYLD_LIBRARY_PATH=/Users/siddharthshukla/grpc/libs/opt
+ DYLD_LIBRARY_PATH=/Users/siddharthshukla/grpc/libs/opt
+ export PATH=/Users/siddharthshukla/grpc/bins/opt:/Users/siddharthshukla/grpc/bins/opt/protobuf:/Users/siddharthshukla/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ PATH=/Users/siddharthshukla/grpc/bins/opt:/Users/siddharthshukla/grpc/bins/opt/protobuf:/Users/siddharthshukla/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
+ export 'CFLAGS=-I/Users/siddharthshukla/grpc/include -std=gnu99'
+ CFLAGS='-I/Users/siddharthshukla/grpc/include -std=gnu99'
+ export LDFLAGS=-L/Users/siddharthshukla/grpc/libs/opt
+ LDFLAGS=-L/Users/siddharthshukla/grpc/libs/opt
+ export GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ export GRPC_PYTHON_USE_PRECOMPILED_BINARIES=0
+ GRPC_PYTHON_USE_PRECOMPILED_BINARIES=0
+ '[' opt = gcov ']'
+ tox -e py34 --notest
py34 installed: coverage==4.1,Cython==0.24,enum34==1.1.6,futures==3.0.5,protobuf==3.0.0b3,six==1.10.0
___________________________________ summary ____________________________________
  py34: skipped tests
  congratulations :)
+ '[' 34 -gt 27 ']'
+ mv /Users/siddharthshukla/grpc/src/python/grpcio/grpc/_cython/cygrpc.so /Users/siddharthshukla/grpc/src/python/grpcio/grpc/_cython/cygrpc.so.backup
+ /Users/siddharthshukla/grpc/.tox/py34/bin/python /Users/siddharthshukla/grpc/setup.py build
running build
running build_py
running build_proto_modules
running build_project_metadata
copying ./src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.macosx-10.11-x86_64-3.4/grpc
copying ./src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.macosx-10.11-x86_64-3.4/grpc/_cython/_credentials
running build_ext
building 'grpc._cython.cygrpc' extension
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/siddharthshukla/grpc/include -std=gnu99 -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) PyObject* -I./src/python/grpcio -I./include -I. -I./third_party/boringssl/include -I./third_party/zlib -I/Users/siddharthshukla/.pyenv/versions/3.4-dev/include/python3.4m -c ./src/python/grpcio/grpc/_cython/cygrpc.c -o python_build/temp.macosx-10.11-x86_64-3.4/./src/python/grpcio/grpc/_cython/cygrpc.o -fvisibility=hidden -pthread -std=gnu99
warning: Command:
['/usr/local/bin/protoc', '--plugin=protoc-gen-python-grpc=/Users/siddharthshukla/grpc/bins/opt/grpc_python_plugin', '-I /Users/siddharthshukla/grpc', '--python_out=/Users/siddharthshukla/grpc/src/python/gens', '--python-grpc_out=/Users/siddharthshukla/grpc/src/python/gens', '/Users/siddharthshukla/grpc/src/proto/grpc/binary_log/v1alpha/log.proto']
Message:
Command '/usr/local/bin/protoc --plugin=protoc-gen-python-grpc=/Users/siddharthshukla/grpc/bins/opt/grpc_python_plugin -I /Users/siddharthshukla/grpc --python_out=/Users/siddharthshukla/grpc/src/python/gens --python-grpc_out=/Users/siddharthshukla/grpc/src/python/gens /Users/siddharthshukla/grpc/src/proto/grpc/binary_log/v1alpha/log.proto' returned non-zero exit status 1
Output:
b'src/proto/grpc/binary_log/v1alpha/log.proto:34:1: Expected ";".\nsrc/proto/grpc/binary_log/v1alpha/log.proto:37:14: Missing numeric value for enum constant.\nsrc/proto/grpc/binary_log/v1alpha/log.proto:38:14: Missing numeric value for enum constant.\nsrc/proto/grpc/binary_log/v1alpha/log.proto:39:14: Missing numeric value for enum constant.\nsrc/proto/grpc/binary_log/v1alpha/log.proto:40:14: Missing numeric value for enum constant.\nsrc/proto/grpc/binary_log/v1alpha/log.proto:44:13: Missing field number.\nsrc/proto/grpc/binary_log/v1alpha/log.proto:45:15: Missing field number.\n'Traceback (most recent call last):
  File "/Users/siddharthshukla/grpc/src/python/grpcio/commands.py", line 252, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/Users/siddharthshukla/grpc/.tox/py34/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "/Users/siddharthshukla/grpc/.tox/py34/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 178, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/command/build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/unixccompiler.py", line 116, in _compile
    extra_postargs)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/spawn.py", line 111, in _spawn_posix
    raise DistutilsPlatformError(my_msg)
distutils.errors.DistutilsPlatformError: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.11" during configure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/siddharthshukla/grpc/setup.py", line 253, in <module>
    test_runner=TEST_RUNNER,
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/siddharthshukla/grpc/.tox/py34/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 66, in run
    _build_ext.run(self)
  File "/Users/siddharthshukla/grpc/.tox/py34/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/siddharthshukla/grpc/src/python/grpcio/commands.py", line 255, in build_extensions
    support.diagnose_build_ext_error(self, error, formatted_exception)
  File "/Users/siddharthshukla/grpc/src/python/grpcio/support.py", line 112, in diagnose_build_ext_error
    "\n\n{}".format(formatted))
commands.CommandError:

We could not diagnose your build failure. Please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title.

Traceback (most recent call last):
  File "/Users/siddharthshukla/grpc/src/python/grpcio/commands.py", line 252, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/Users/siddharthshukla/grpc/.tox/py34/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "/Users/siddharthshukla/grpc/.tox/py34/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 178, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/command/build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/unixccompiler.py", line 116, in _compile
    extra_postargs)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/siddharthshukla/.pyenv/versions/3.4-dev/lib/python3.4/distutils/spawn.py", line 111, in _spawn_posix
    raise DistutilsPlatformError(my_msg)
distutils.errors.DistutilsPlatformError: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.11" during configure

FAILED: tools/run_tests/build_python.sh [ret=1, pid=88521]
FAILED: Some tests failed
make: *** [test_python] Error 1
```

**Comment by kpayson64** [comment]
This error was observed on PR #6503.  It has since been resolved.
