### ISSUE TITLE
Window update sent before settings frame

### ISSUE THREAD

**Issue by croachrose** [grpc/grpc#6931]
There seems to be a timing problem with new streams that I have started to hit recently. I am using grpc 0.14.1 to connect to a golang service. The go http2 implementation requires a settings frame be sent as the first frame of a new stream. It appears that the c implementation can sometimes send a window update first.

Below is the trace of the bad behavior. I added a log to know when the settings frame was being considered and when t->executor.parsing_active changed. It looks like right after sending the initial "PRI \* HTTP/2.0..." we get a read event which updates the parsing state (and announce_incoming_window). During active parsing, a write is attempted which does not send settings (due to is_parsing being true) but does send a window update.

I have traced a good request as well. What I see in that trace is "tcp_posix.c: read: success=1" way after writing the settings and the initial metadata. I have been able to reproduce this more easily on a virtual machine.

```
I0616 13:16:25.416463738    8476 init.c:187]                 grpc_init(void)
I0616 13:16:25.455543856    8476 channel_create.c:219]       grpc_insecure_channel_create(target=0x7fc25985248c, args=0x7fc259852570, reserved=(nil))
I0616 13:16:25.456140962    8476 completion_queue.c:124]     grpc_completion_queue_create(reserved=(nil))
I0616 13:16:25.456980408    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0616 13:16:25.457536167    8481 channel.c:201]              grpc_channel_create_call(channel=0x11ed4e0, parent_call=(nil), propagation_mask=0, cq=0x12b0500, method=/authn.Auth/ValidateEmail, host=(null), deadline=gpr_timespec { tv_sec: 1466082990, tv_nsec: 457520008, clock_type: 1 }, reserved=(nil))
I0616 13:16:25.457858355    8481 metadata_array.c:42]        grpc_metadata_array_init(array=0x7fc258fe6650)
I0616 13:16:25.458172698    8481 call.c:1478]                grpc_call_start_batch(call=0x7fc248001800, ops=0x7fc248002260, nops=1, tag=0x7fc25997b440, reserved=(nil))
I0616 13:16:25.458407645    8481 call.c:1190]                ops[0]: SEND_INITIAL_METADATA
I0616 13:16:25.458642512    8481 client_channel.c:109]       OP[client-channel:0x7fc248001d60]: SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 61 75 74 68 6e 2e 41 75 74 68 2f 56 61 6c 69 64 61 74 65 45 6d 61 69 6c '/authn.Auth/ValidateEmail', key=3a 61 75 74 68 6f 72 69 74 79 ':authority' value=6c 6f 63 61 6c 68 6f 73 74 'localhost', key=67 72 70 63 2d 65 6e 63 6f 64 69 6e 67 'grpc-encoding' value=69 64 65 6e 74 69 74 79 'identity', key=67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding' value=69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip' deadline=62786.271656894}
D0616 13:16:25.458852468    8481 connectivity_state.c:90]    CONWATCH: 0x7fc248002e50 (null): get IDLE
D0616 13:16:25.459027579    8481 connectivity_state.c:149]   SET: 0x11ed5f8 client_channel: IDLE --> IDLE [new_lb+resolver]
D0616 13:16:25.459235248    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248002e50 (null): from IDLE [cur=IDLE] notify=0x7fc248002f88
D0616 13:16:25.459398879    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248003280 subchannel: from IDLE [cur=IDLE] notify=0x7fc2480034e8
D0616 13:16:25.459550335    8481 connectivity_state.c:149]   SET: 0x7fc248003280 subchannel: IDLE --> CONNECTING [state_change]
D0616 13:16:25.459834798    8481 connectivity_state.c:149]   SET: 0x7fc248002e50 (null): IDLE --> CONNECTING [connecting_changed]
D0616 13:16:25.460015448    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248003280 subchannel: from CONNECTING [cur=CONNECTING] notify=0x7fc2480038d8
I0616 13:16:25.460184990    8481 chttp2_transport.c:1531]    Parsing now active
I0616 13:16:25.460360490    8481 writing.c:63]               Settings: 1 0 1
D0616 13:16:25.460519180    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248005c18 client_transport: from READY [cur=READY] notify=0x7fc2480061b0
D0616 13:16:25.460703639    8481 connectivity_state.c:149]   SET: 0x7fc248003280 subchannel: CONNECTING --> READY [connected]
D0616 13:16:25.460880672    8481 connectivity_state.c:149]   SET: 0x11ed5f8 client_channel: IDLE --> CONNECTING [lb_changed]
D0616 13:16:25.461049637    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248002e50 (null): from CONNECTING [cur=CONNECTING] notify=0x7fc248002c48
D0616 13:16:25.461205422    8481 parsing.c:164]              FLOW   parsed: client   transport CREDIT       global.announce_incoming_window(0) by                   announce_bytes(983041) giving 983041
D0616 13:16:25.461382423    8481 parsing.c:166]              FLOW   parsed: client   transport CREDIT           parsing.incoming_window(65535) by                   announce_bytes(983041) giving 1048576
I0616 13:16:25.461531003    8481 chttp2_transport.c:1577]    Parsing done
D0616 13:16:25.461704054    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 50 52 49 20 2a 20 48 54 54 50 2f 32 2e 30 0d 0a 0d 0a 53 4d 0d 0a 0d 0a 'PRI * HTTP/2.0....SM....'
D0616 13:16:25.461932190    8481 connectivity_state.c:149]   SET: 0x7fc248002e50 (null): CONNECTING --> READY [connecting_ready]
D0616 13:16:25.462166697    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248005c18 client_transport: from READY [cur=READY] notify=0x7fc248002de8
D0616 13:16:25.462279820    8481 tcp_posix.c:163]            read: success=1
D0616 13:16:25.462289243    8481 tcp_posix.c:167]            READ 0x7fc248003730: 00 00 00 04 00 00 00 00 00 00 00 04 08 00 00 00 00 00 00 0e ff f1 '......................'
I0616 13:16:25.462401140    8481 chttp2_transport.c:1531]    Parsing now active
I0616 13:16:25.462409951    8481 writing.c:63]               Settings: 1 0 1
D0616 13:16:25.462419236    8481 writing.c:167]              FLOW    write: client   transport DEBIT   global.announce_incoming_window(983041) by                        announced(983041) giving 0
D0616 13:16:25.462425574    8481 connectivity_state.c:149]   SET: 0x11ed5f8 client_channel: CONNECTING --> READY [lb_changed]
D0616 13:16:25.462430862    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248002e50 (null): from READY [cur=READY] notify=0x7fc248002f88
D0616 13:16:25.462442915    8481 frame_window_update.c:114]  FLOW    parse: client   transport CREDIT               parsing.outgoing_window(0) by                  received_update(983025) giving 983025
D0616 13:16:25.462450465    8481 parsing.c:150]              FLOW   parsed: client   transport MOVE                  global.outgoing_window(0) <-          parsing.outgoing_window(983025) giving 983025
I0616 13:16:25.462455555    8481 chttp2_transport.c:1577]    Parsing done
D0616 13:16:25.462461295    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 00 00 04 08 00 00 00 00 00 00 0f 00 01 '.............'
I0616 13:16:25.462643600    8481 http_client_filter.c:143]   OP[http-client:0x7fc248008638]: SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 61 75 74 68 6e 2e 41 75 74 68 2f 56 61 6c 69 64 61 74 65 45 6d 61 69 6c '/authn.Auth/ValidateEmail', key=3a 61 75 74 68 6f 72 69 74 79 ':authority' value=6c 6f 63 61 6c 68 6f 73 74 'localhost', key=67 72 70 63 2d 65 6e 63 6f 64 69 6e 67 'grpc-encoding' value=69 64 65 6e 74 69 74 79 'identity', key=67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding' value=69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip' deadline=62786.271656894}
I0616 13:16:25.462670664    8481 connected_channel.c:70]     OP[connected:0x7fc248008650]: SEND_INITIAL_METADATA{key=3a 73 63 68 65 6d 65 ':scheme' value=68 74 74 70 'http', key=3a 6d 65 74 68 6f 64 ':method' value=50 4f 53 54 'POST', key=3a 70 61 74 68 ':path' value=2f 61 75 74 68 6e 2e 41 75 74 68 2f 56 61 6c 69 64 61 74 65 45 6d 61 69 6c '/authn.Auth/ValidateEmail', key=3a 61 75 74 68 6f 72 69 74 79 ':authority' value=6c 6f 63 61 6c 68 6f 73 74 'localhost', key=67 72 70 63 2d 65 6e 63 6f 64 69 6e 67 'grpc-encoding' value=69 64 65 6e 74 69 74 79 'identity', key=67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding' value=69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip', key=74 65 'te' value=74 72 61 69 6c 65 72 73 'trailers', key=63 6f 6e 74 65 6e 74 2d 74 79 70 65 'content-type' value=61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc', key=75 73 65 72 2d 61 67 65 6e 74 'user-agent' value=50 79 74 68 6f 6e 2d 67 52 50 43 2d 30 2e 31 34 2e 31 20 67 72 70 63 2d 63 2f 30 2e 31 34 2e 31 20 28 6c 69 6e 75 78 29 'Python-gRPC-0.14.1 grpc-c/0.14.1 (linux)' deadline=62786.271656894}
D0616 13:16:25.462831000    8481 chttp2_transport.c:814]     HTTP:CLI: Allocating new grpc_chttp2_stream 0x7fc248008768 to id 1
D0616 13:16:25.462840410    8481 tcp_posix.c:163]            read: success=0
I0616 13:16:25.462844943    8481 chttp2_transport.c:1531]    Parsing now active
I0616 13:16:25.462850428    8481 writing.c:63]               Settings: 1 0 1
D0616 13:16:25.462857394    8481 writing.c:81]               FLOW    write: client   transport MOVE             writing.outgoing_window(65535) <-           global.outgoing_window(983025) giving 1048560
D0616 13:16:25.462864538    8481 writing.c:98]               FLOW    write: client   stream[1] MOVE                 writing.outgoing_window(0) <-            global.outgoing_window(65535) giving 65535
I0616 13:16:25.462870778    8481 chttp2_transport.c:1577]    Parsing done
D0616 13:16:25.462875187    8481 chttp2_transport.c:1641]    set connectivity_state=4
D0616 13:16:25.462879836    8481 connectivity_state.c:149]   SET: 0x7fc248005c18 client_transport: READY --> FATAL_FAILURE [close_transport]
D0616 13:16:25.462893184    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 00 00 00 04 01 00 00 00 00 '.........'
D0616 13:16:25.462898580    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 00 01 09 01 04 00 00 00 01 40 07 '.........@.'
D0616 13:16:25.462903533    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 3a 73 63 68 65 6d 65 ':scheme'
D0616 13:16:25.462908400    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 04 '.'
D0616 13:16:25.462912958    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 68 74 74 70 'http'
D0616 13:16:25.462917318    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 07 '@.'
D0616 13:16:25.462921692    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 3a 6d 65 74 68 6f 64 ':method'
D0616 13:16:25.462926105    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 04 '.'
D0616 13:16:25.462930476    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 50 4f 53 54 'POST'
D0616 13:16:25.462934788    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 05 '@.'
D0616 13:16:25.462939216    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 3a 70 61 74 68 ':path'
D0616 13:16:25.462943503    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 19 '.'
D0616 13:16:25.462948639    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 2f 61 75 74 68 6e 2e 41 75 74 68 2f 56 61 6c 69 64 61 74 65 45 6d 61 69 6c '/authn.Auth/ValidateEmail'
D0616 13:16:25.462953365    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 0a '@.'
D0616 13:16:25.462957903    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 3a 61 75 74 68 6f 72 69 74 79 ':authority'
D0616 13:16:25.462962695    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 09 6c 6f 63 61 6c 68 6f 73 74 40 0d '.localhost@.'
D0616 13:16:25.462967439    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 67 72 70 63 2d 65 6e 63 6f 64 69 6e 67 'grpc-encoding'
D0616 13:16:25.462971891    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 08 '.'
D0616 13:16:25.462976364    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 69 64 65 6e 74 69 74 79 'identity'
D0616 13:16:25.462980716    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 14 '@.'
D0616 13:16:25.462985668    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding'
D0616 13:16:25.462990188    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 15 '.'
D0616 13:16:25.463166015    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'
D0616 13:16:25.463173239    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 02 '@.'
D0616 13:16:25.463177541    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 74 65 'te'
D0616 13:16:25.463181587    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 08 '.'
D0616 13:16:25.463185940    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 74 72 61 69 6c 65 72 73 'trailers'
D0616 13:16:25.463190327    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 0c '@.'
D0616 13:16:25.463194993    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 63 6f 6e 74 65 6e 74 2d 74 79 70 65 'content-type'
D0616 13:16:25.463199127    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 10 '.'
D0616 13:16:25.463203629    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
D0616 13:16:25.463207967    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 0a '@.'
D0616 13:16:25.463212323    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 75 73 65 72 2d 61 67 65 6e 74 'user-agent'
D0616 13:16:25.463216573    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 28 '('
D0616 13:16:25.463225237    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 50 79 74 68 6f 6e 2d 67 52 50 43 2d 30 2e 31 34 2e 31 20 67 72 70 63 2d 63 2f 30 2e 31 34 2e 31 20 28 6c 69 6e 75 78 29 'Python-gRPC-0.14.1 grpc-c/0.14.1 (linux)'
D0616 13:16:25.463230170    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 40 0c '@.'
D0616 13:16:25.463234513    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 67 72 70 63 2d 74 69 6d 65 6f 75 74 'grpc-timeout'
D0616 13:16:25.463238815    8481 tcp_posix.c:401]            WRITE 0x7fc248003730: 02 35 53 '.5S'
D0616 13:16:25.463245929    8481 connectivity_state.c:149]   SET: 0x7fc248002e50 (null): READY --> FATAL_FAILURE [selected_changed]
D0616 13:16:25.463251011    8481 connectivity_state.c:149]   SET: 0x7fc248003280 subchannel: READY --> FATAL_FAILURE [reflect_child]
D0616 13:16:25.463274551    8481 connectivity_state.c:149]   SET: 0x7fc248002e50 (null): FATAL_FAILURE --> FATAL_FAILURE [shutdown]
D0616 13:16:25.463280553    8481 connectivity_state.c:101]   CONWATCH: 0x7fc248005c18 client_transport: unsubscribe notify=0x7fc248002de8
D0616 13:16:25.463286071    8481 connectivity_state.c:149]   SET: 0x11ed5f8 client_channel: READY --> TRANSIENT_FAILURE [lb_changed]
I0616 13:16:25.463292512    8481 completion_queue.c:233]     grpc_cq_end_op(exec_ctx=0x7fc253ffd190, cc=0x12b0500, tag=0x7fc25997b440, success=1, done=0x7fc259d560f0, done_arg=0x7fc248001858, storage=0x7fc248001860)
I0616 13:16:25.463301698    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: OP_COMPLETE: tag:0x7fc25997b440 OK
I0616 13:16:25.463348238    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
D0616 13:16:25.463367619    8481 connectivity_state.c:90]    CONWATCH: 0x7fc248006d80 (null): get IDLE
D0616 13:16:25.463374216    8481 connectivity_state.c:149]   SET: 0x11ed5f8 client_channel: TRANSIENT_FAILURE --> IDLE [new_lb+resolver]
D0616 13:16:25.463379117    8481 connectivity_state.c:104]   CONWATCH: 0x7fc248006d80 (null): from IDLE [cur=IDLE] notify=0x7fc2480028d8
I0616 13:16:25.463385995    8481 metadata_array.c:47]        grpc_metadata_array_destroy(array=0x7fc258fe6650)
I0616 13:16:25.463412191    8481 metadata_array.c:42]        grpc_metadata_array_init(array=0x7fc258fe6650)
I0616 13:16:25.463424430    8481 call.c:1478]                grpc_call_start_batch(call=0x7fc248001800, ops=0x7fc248002260, nops=1, tag=0x7fc25997b440, reserved=(nil))
I0616 13:16:25.463615734    8481 call.c:1190]                ops[0]: RECV_INITIAL_METADATA ptr=0x7fc258fe6650
I0616 13:16:25.463624222    8481 client_channel.c:109]       OP[client-channel:0x7fc248001d60]: RECV_INITIAL_METADATA
I0616 13:16:25.463629268    8481 http_client_filter.c:143]   OP[http-client:0x7fc248008638]: RECV_INITIAL_METADATA
I0616 13:16:25.463633940    8481 connected_channel.c:70]     OP[connected:0x7fc248008650]: RECV_INITIAL_METADATA
I0616 13:16:25.463640192    8481 completion_queue.c:233]     grpc_cq_end_op(exec_ctx=0x7fc253ffd190, cc=0x12b0500, tag=0x7fc25997b440, success=1, done=0x7fc259d560f0, done_arg=0x7fc248001858, storage=0x7fc248001860)
I0616 13:16:25.463651163    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: OP_COMPLETE: tag:0x7fc25997b440 OK
I0616 13:16:25.463718039    8481 metadata_array.c:42]        grpc_metadata_array_init(array=0x7fc258fe66a0)
I0616 13:16:25.463730146    8481 call.c:1478]                grpc_call_start_batch(call=0x7fc248001800, ops=0x7fc248002260, nops=1, tag=0x7fc25997b440, reserved=(nil))
I0616 13:16:25.463736758    8481 call.c:1190]                ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7fc258fe66a0 status=0x7fc2599f6cf8 details=0x7fc2599f6d00
I0616 13:16:25.463742147    8481 client_channel.c:109]       OP[client-channel:0x7fc248001d60]: RECV_TRAILING_METADATA
I0616 13:16:25.463746805    8481 http_client_filter.c:143]   OP[http-client:0x7fc248008638]: RECV_TRAILING_METADATA
I0616 13:16:25.463751308    8481 connected_channel.c:70]     OP[connected:0x7fc248008650]: RECV_TRAILING_METADATA
I0616 13:16:25.463758108    8481 completion_queue.c:233]     grpc_cq_end_op(exec_ctx=0x7fc253ffd190, cc=0x12b0500, tag=0x7fc25997b440, success=1, done=0x7fc259d560f0, done_arg=0x7fc248001858, storage=0x7fc248001860)
I0616 13:16:25.463822710    8481 call.c:1478]                grpc_call_start_batch(call=0x7fc248001800, ops=0x7fc248007310, nops=1, tag=0x7fc25997b520, reserved=(nil))
I0616 13:16:25.463831452    8481 call.c:1190]                ops[0]: SEND_MESSAGE ptr=0x7fc248007210
I0616 13:16:25.463837280    8481 client_channel.c:109]       OP[client-channel:0x7fc248001d60]: SEND_MESSAGE:flags=0x00000000:len=44
I0616 13:16:25.463842448    8481 http_client_filter.c:143]   OP[http-client:0x7fc248008638]: SEND_MESSAGE:flags=0x00000000:len=44
I0616 13:16:25.464016372    8481 connected_channel.c:70]     OP[connected:0x7fc248008650]: SEND_MESSAGE:flags=0x00000000:len=44
I0616 13:16:25.464025030    8481 completion_queue.c:233]     grpc_cq_end_op(exec_ctx=0x7fc253ffd190, cc=0x12b0500, tag=0x7fc25997b520, success=0, done=0x7fc259d560f0, done_arg=0x7fc2480018b0, storage=0x7fc2480018b8)
I0616 13:16:25.464473506    8479 call.c:1478]                grpc_call_start_batch(call=0x7fc248001800, ops=0x7fc254002040, nops=1, tag=0x7fc25997b280, reserved=(nil))
I0616 13:16:25.464482860    8479 call.c:1190]                ops[0]: RECV_MESSAGE ptr=0x7fc25f4e5370
I0616 13:16:25.464487121    8479 client_channel.c:109]       OP[client-channel:0x7fc248001d60]: RECV_MESSAGE
I0616 13:16:25.464490201    8479 http_client_filter.c:143]   OP[http-client:0x7fc248008638]: RECV_MESSAGE
I0616 13:16:25.464492734    8479 connected_channel.c:70]     OP[connected:0x7fc248008650]: RECV_MESSAGE
D0616 13:16:25.464498059    8479 chttp2_transport.c:1716]    FLOW       op: client   stream[1] CREDIT             global.max_recv_bytes(65535) by                add_max_recv_bytes(65535) giving 131070
D0616 13:16:25.464502874    8479 chttp2_transport.c:1719]    FLOW       op: client   stream[1] CREDIT global.unannounced_incoming_window_for_parse(0) by                add_max_recv_bytes(65535) giving 65535
D0616 13:16:25.464507273    8479 chttp2_transport.c:1722]    FLOW       op: client   stream[1] CREDIT global.unannounced_incoming_window_for_writing(0) by                add_max_recv_bytes(65535) giving 65535
I0616 13:16:25.464511699    8479 completion_queue.c:233]     grpc_cq_end_op(exec_ctx=0x7fc25981fca0, cc=0x12b0500, tag=0x7fc25997b280, success=1, done=0x7fc259d560f0, done_arg=0x7fc248001908, storage=0x7fc248001910)
I0616 13:16:25.464537098    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0616 13:16:25.464542548    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: OP_COMPLETE: tag:0x7fc25997b440 OK
I0616 13:16:25.464602844    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0616 13:16:25.464608637    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: OP_COMPLETE: tag:0x7fc25997b520 ERROR
I0616 13:16:25.464648187    8479 call.c:1478]                grpc_call_start_batch(call=0x7fc248001800, ops=0x7fc254001260, nops=1, tag=0x7fc25997b520, reserved=(nil))
I0616 13:16:25.464652655    8479 call.c:1190]                ops[0]: SEND_CLOSE_FROM_CLIENT
I0616 13:16:25.464656109    8479 client_channel.c:109]       OP[client-channel:0x7fc248001d60]: SEND_TRAILING_METADATA{}
I0616 13:16:25.464658873    8479 http_client_filter.c:143]   OP[http-client:0x7fc248008638]: SEND_TRAILING_METADATA{}
I0616 13:16:25.464661514    8479 connected_channel.c:70]     OP[connected:0x7fc248008650]: SEND_TRAILING_METADATA{}
I0616 13:16:25.464665425    8479 completion_queue.c:233]     grpc_cq_end_op(exec_ctx=0x7fc25981fca0, cc=0x12b0500, tag=0x7fc25997b520, success=1, done=0x7fc259d560f0, done_arg=0x7fc248001858, storage=0x7fc248001860)
I0616 13:16:25.464678192    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0616 13:16:25.464682440    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: OP_COMPLETE: tag:0x7fc25997b280 OK
I0616 13:16:25.464714346    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0616 13:16:25.464719277    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: OP_COMPLETE: tag:0x7fc25997b520 OK
I0616 13:16:25.464746534    8479 completion_queue.c:299]     grpc_completion_queue_next(cc=0x12b0500, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
Traceback (most recent call last):
  File "/vagrant/test.py", line 8, in <module>
    groups=['alpha-team']))
  File "/home/vagrant/transloc/python/transloc/rpc.py", line 31, in __call__
    return self._target(*args, **kwargs)
  File "/home/vagrant/transloc/env/local/lib/python2.7/site-packages/grpc/framework/crust/implementations.py", line 75, in __call__
    protocol_options, metadata, request)
  File "/home/vagrant/transloc/env/local/lib/python2.7/site-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/home/vagrant/transloc/env/local/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 415, in next
    raise self._termination.abortion_error
grpc.framework.interfaces.face.face.NetworkError: NetworkError(code=StatusCode.UNAVAILABLE, details="")
I0616 13:16:25.465781958    8482 metadata_array.c:47]        grpc_metadata_array_destroy(array=0x7fc258fe66a0)
I0616 13:16:25.473361535    8476 completion_queue.c:483]     grpc_completion_queue_shutdown(cc=0x12b0500)
I0616 13:16:25.473429232    8479 completion_queue.c:350]     RETURN_EVENT[0x12b0500]: QUEUE_SHUTDOWN
I0616 13:16:25.473457695    8479 call.c:648]                 grpc_call_destroy(c=0x7fc248001800)
I0616 13:16:25.473469961    8479 completion_queue.c:483]     grpc_completion_queue_shutdown(cc=0x12b0500)
I0616 13:16:25.473482827    8479 completion_queue.c:503]     grpc_completion_queue_destroy(cc=0x12b0500)
I0616 13:16:25.473485332    8479 completion_queue.c:483]     grpc_completion_queue_shutdown(cc=0x12b0500)
I0616 13:16:25.485019848    8476 metadata_array.c:47]        grpc_metadata_array_destroy(array=0x7fc258fe6650)
I0616 13:16:25.489126731    8476 init.c:192]                 grpc_shutdown(void)
D0616 13:16:26.503322469    8476 iomgr.c:99]                 Waiting for 1 iomgr objects to be destroyed
```

**Comment by croachrose** [comment]
The following patch appears to fix it:

```
diff --git a/src/core/ext/transport/chttp2/transport/writing.c b/src/core/ext/transport/chttp2/transport/writing.c
index a8fb463..832a67d 100644
--- a/src/core/ext/transport/chttp2/transport/writing.c
+++ b/src/core/ext/transport/chttp2/transport/writing.c
@@ -156,7 +156,8 @@ int grpc_chttp2_unlocking_check_writes(
 
   /* if the grpc_chttp2_transport is ready to send a window update, do so here
      also; 3/4 is a magic number that will likely get tuned soon */
-  if (transport_global->announce_incoming_window > 0) {
+  if (transport_global->sent_local_settings &&
+      transport_global->announce_incoming_window > 0) {
     uint32_t announced = (uint32_t)GPR_MIN(
         transport_global->announce_incoming_window, UINT32_MAX);
     GRPC_CHTTP2_FLOW_DEBIT_TRANSPORT("write", transport_global,
```

**Comment by ctiller** [comment]
Nice catch (and fix!)

Sent out a PR containing it, we should get this merged relatively quickly.
