### ISSUE TITLE
Settings frame sent with ACK as initial frame

### ISSUE THREAD

**Issue by yusefnapora** [grpc/grpc#6936]
Hi,

I've been experiencing a connection issue when using a grpc-java server with a python client.  The issue seems related to https://github.com/grpc/grpc/issues/6931, but applying the patch referenced in that issue doesn't completely resolve the problem.

Given a hello-world service implemented in scala, and a client in python that repeatedly issues "hello world" requests, it will trigger a netty connection error on the server after a few requests (somewhere between 5 and 40):

```
Jun 16, 2016 6:09:44 PM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000040800
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:82)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:300)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:209)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:391)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

The above is when using the 0.14.0 release of the grpcio python package.  When installing grpc from source using the [bugfix branch](https://github.com/grpc/grpc/pull/6933) referenced in the above issue (https://github.com/grpc/grpc/issues/6931), the same exception is thrown, but the received frame is different.

Instead of `Hex dump for first 5 bytes: 0000040800`, I get `Hex dump for first 5 bytes: 0000000401`. Digging a bit into [the http2 spec](https://http2.github.io/http2-spec/#iana-frames) shows that that is in fact a SETTINGS frame.  The error message here is misleading; the [netty code responsible](http://netty.io/4.1/xref/io/netty/handler/codec/http2/Http2ConnectionHandler.html#302) checks both that it's a SETTINGS frame, and that the ACK flag is not set.

So it looks like grpc is sending a settings frame with the ACK flag set before receiving the initial frame?  I'm afraid I don't have enough experience with http2 or grpc to diagnose much further.

An example hello world client and server that exhibits this behavior is available here: https://github.com/yusefnapora/grpc-settings-frame-bug

If you have vagrant installed, you should be able to reproduce it in the environment setup in the Vagrantfile in that repo.

Possibly interesting is that I have not been able to reproduce this issue if the client is running on a Mac OS X host (the latest El Capitan), however under linux it seems to happen pretty reliably.

**Comment by yusefnapora** [comment]
I added some log statements to try to figure out the order of events here.
I put an info log statement here (when sending the ACK): https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/frame_settings.c#L165

and one here, when sending the SETTINGS frame without ACK: https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/writing.c#L65

Just before the crash, the ACK frame is indeed sent before the SETTINGS frame:

```
...

saying hello...
I0616 19:49:04.503060801   22620 writing.c:65]               sending SETTINGS frame
I0616 19:49:04.503685210   22620 frame_settings.c:165]       sending SETTINGS ACK frame
response: Hello world
saying hello...
I0616 19:49:04.506613656   22620 writing.c:65]               sending SETTINGS frame
I0616 19:49:04.507124852   22620 frame_settings.c:165]       sending SETTINGS ACK frame
response: Hello world
saying hello...
I0616 19:49:04.509950066   22620 frame_settings.c:165]       sending SETTINGS ACK frame
I0616 19:49:04.510115226   22620 writing.c:65]               sending SETTINGS frame
failed after 146 attempts with error: AbortionError(code=StatusCode.UNAVAILABLE, details="")
```
