### ISSUE TITLE
Can't `npm install grpc-tools` on OS X

### ISSUE THREAD

**Issue by drobertduke** [grpc/grpc#6937]
```
> npm install grpc-tools

> grpc-tools@0.14.1 install /Users/dduke/projs/grpc/grpc/node_modules/grpc-tools
> node-pre-gyp install

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Pre-built binary not available for your system, looked for https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc-tools/v0.14.1/darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/dduke/projs/grpc/grpc/node_modules/grpc-tools/node_modules/node-pre-gyp/lib/install.js:99:37)
node-pre-gyp ERR! stack     at emitOne (events.js:95:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:182:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/dduke/projs/grpc/grpc/node_modules/grpc-tools/node_modules/node-pre-gyp/node_modules/request/request.js:977:10)
node-pre-gyp ERR! stack     at emitOne (events.js:90:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:359:20)
node-pre-gyp ERR! stack     at emitOne (events.js:90:13)
node-pre-gyp ERR! System Darwin 15.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/5.11.0/bin/node" "/Users/dduke/projs/grpc/grpc/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/dduke/projs/grpc/grpc/node_modules/grpc-tools
node-pre-gyp ERR! node -v v5.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Pre-built binary not available for your system, looked for https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc-tools/v0.14.1/darwin-x64.tar.gz
```

I also get failures from `npm install grpc-tools --build-from-source`:
`gyp: binding.gyp not found (cwd: /Users/dduke/projs/grpc/grpc/node_modules/grpc-tools) while trying to load binding.gyp`

**Comment by murgatroid99** [comment]
This should work now, if you try installing grpc-tools@1.0.0-pre1. Previously, the precompiled binaries were uploaded with incorrect names.
