### ISSUE TITLE
failed to load core gRPC library on windows for 32 bit version

### ISSUE THREAD

**Issue by LordRoad** [grpc/grpc#6964]
python 2.7 64bit and 32bit are both installed. and 32bit installed with "Register Extensions and select Entire feature will be unavailable".  And install grpcio from pip for 32bit version python. some basic tests, it shows:

Traceback (most recent call last):
  File "E:/git/game/game_service.py", line 11, in <module>
    import client_game_pb2
  File "E:\git\game\client_game_pb2.py", line 170, in <module>
    from grpc.beta import implementations as beta_implementations
  File "C:\Python27_32\lib\site-packages\grpc\beta\implementations.py", line 38, in <module>
    from grpc._adapter import _intermediary_low
  File "C:\Python27_32\lib\site-packages\grpc\_adapter\_intermediary_low.py", line 57, in <module>
    from grpc._adapter import _low
  File "C:\Python27_32\lib\site-packages\grpc\_adapter\_low.py", line 33, in <module>
    from grpc._cython import cygrpc
  File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 72, in init grpc._cython.cygrpc (./src/python/grpcio\grpc/_cython/cygrpc.c:29223)
  File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 59, in grpc._cython.cygrpc._ModuleState.__cinit__ (./src/python/grpcio\grpc/_cython/cygrpc.c:23129)
ImportError: failed to load core gRPC library

any suggestion?

**Comment by kpayson64** [comment]
This error gets thrown on Windows when the grpc dll fails to load.

It looks like the load script is hard-coded to load the x86-64 version of the binary.

We should be able to have a fix shortly, but In the mean time, are you able to run gRPC using your 64 bit Python installation?

**Comment by LordRoad** [comment]
@kpayson64 64bit python is ok. thanks for the help.

**Comment by kpayson64** [comment]
Cutting this over to @soltanmm, I think this should be resolved by #6797.

**Comment by soltanmm** [comment]
This should no longer be an issue (the offending mechanism has been removed).
