### ISSUE TITLE
[Python] Unknown event on android

### ISSUE THREAD

**Issue by amasty** [grpc/grpc#6975]
Hi. I'm trying to run python grpc module on Android.
On Android i use QPython and compiled module grpc with Android NDK.

But every time i getting RuntimeError('unknown event'), cause 'ev.type' always contains garbage like 6619138 or 5832706. 

For example there are few runs where i remove raise exception to show ev.type:

```
root@msm8974:/data/lerson # ./qpython.sh test/grpcclient.py
ev.type = 6619138
ev.type = 2
ev.type = 2
ev.type = 13238274
ev.type = 2
{'stream_name': [u'rtsp_stream']}
root@msm8974:/data/lerson # ./qpython.sh test/grpcclient.py
ev.type = 6619138
ev.type = 2
ev.type = 2
ev.type = 13238274
ev.type = 2
{'stream_name': [u'rtsp_stream']}
root@msm8974:/data/lerson # ./qpython.sh test/grpcclient.py
ev.type = 6619138
ev.type = 2
ev.type = 2
ev.type = 13238274
ev.type = 2
{'stream_name': [u'rtsp_stream']}
root@msm8974:/data/lerson # ./qpython.sh test/grpcclient.py
ev.type = 6619138
ev.type = 2
ev.type = 2
ev.type = 13238274
ev.type = 2
{'stream_name': [u'rtsp_stream']}
root@msm8974:/data/lerson # ./qpython.sh test/grpcclient.py
ev.type = 6619138
ev.type = 2
ev.type = 2
ev.type = 2
ev.type = 13238274
ev.type = 2
{'stream_name': [u'rtsp_stream']}
```

Full traceback 

```
root@msm8974:/data/lerson # ./qpython.sh test/grpcclient.py
ev.type = 6619138
ERROR:root:Unexpected exception from <bound method _Kernel._spin of <grpc._links.invocation._Kernel object at 0xb5b2c9f0>> executed in logging pool!
Traceback (most recent call last):
  File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 41, in _wrapping
    return behavior(*args, **kwargs)
  File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/grpc/_links/invocation.py", line 209, in _spin
    event = completion_queue.get(None)
  File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/grpc/_adapter/_intermediary_low.py", line 203, in get
    return self.get(deadline)
  File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/grpc/_adapter/_intermediary_low.py", line 225, in get
    raise RuntimeError('unknown event')
RuntimeError: unknown event
```

**Comment by nathanielmanistaatgoogle** [comment]
Python on Android? Wow. Wow!

I can tell from your stack trace that you're using gRPC Python `0.14`.

Are you able to run code from our master branch in your Android development environment? If so, are you able to run our unit tests? They would almost certainly tickle the same problem that you're seeing and perhaps be more informative.

**Comment by amasty** [comment]
```
amasty@amasty-VirtualBox:~/arm/grpc-master$ python2.7 setup.py build
running build
running build_py
```
...
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DOPENSSL_NO_ASM=1 -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DPyMODINIT_FUNC=__attribute__((visibility ("default"))) void -I./src/python/grpcio -I./include -I. -I./third_party/boringssl/include -I./third_party/zlib -I/usr/include/python2.7 -c ./src/python/grpcio/grpc/_cython/cygrpc.c -o python_build/temp.linux-x86_64-2.7/./src/python/grpcio/grpc/_cython/cygrpc.o -fvisibility=hidden -pthread -std=gnu99
x86_64-linux-gnu-gcc: error: ./src/python/grpcio/grpc/_cython/cygrpc.c: Нет такого файла или каталога
x86_64-linux-gnu-gcc: fatal error: no input files

```
