### ISSUE TITLE
Python SSL server crash on insecure connection request

### ISSUE THREAD

**Issue by meomap** [grpc/grpc#6995]
I modified example `greeter_server.py` at hello word example to have secure server
[example.zip](https://github.com/grpc/grpc/files/327793/example.zip)

credentials could be found here https://github.com/grpc/grpc/tree/master/src/python/grpcio/tests/unit/credentials

after run server, I tried to request with `curl -k` then server crashed miserably
```
E0622 19:29:37.133985005   23373 http_server_filter.c:105]   Invalid :method: header: 'GET'
E0622 19:29:37.134034668   23373 http_server_filter.c:156]   Missing :method header
E0622 19:29:37.134060273   23373 http_server_filter.c:162]   Missing te trailers header
ERROR:root:Unexpected exception from <bound method _Kernel._spin of <grpc._links.service._Kernel object at 0x7fcfb4c77ad0>> executed in logging pool!
Traceback (most recent call last):
  File "/home/hails/code/uba/src/git.devcats.io/aop/cm/env/local/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 41, in _wrapping
    return behavior(*args, **kwargs)
  File "/home/hails/code/uba/src/git.devcats.io/aop/cm/env/local/lib/python2.7/site-packages/grpc/_links/service.py", line 287, in _spin
    self._on_finish_event(event)
  File "/home/hails/code/uba/src/git.devcats.io/aop/cm/env/local/lib/python2.7/site-packages/grpc/_links/service.py", line 254, in _on_finish_event
    rpc_state = self._rpc_states[call]
KeyError: <grpc._adapter._intermediary_low.Call object at 0x7fcfb4c67690>
```

at client side
```
curl --http2 -v -k https://127.0.0.1:50051
curl: /usr/local/lib/libcurl.so.4: no version information available (required by curl)
* Rebuilt URL to: https://127.0.0.1:50051/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 50051 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP2 (h2)
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: C=US; ST=Illinois; L=Chicago; O=Example, Co.; CN=*.test.google.com
*        start date: Nov  4 02:20:24 2015 GMT
*        expire date: Nov  1 02:20:24 2025 GMT
*        issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=testca
*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7367e0)
> GET / HTTP/1.1
> Host: 127.0.0.1:50051
> User-Agent: curl/7.35.0
> Accept: */*
> 
* HTTP/2 stream 1 was not closed cleanly: error_code = 8
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (16) HTTP/2 stream 1 was not closed cleanly: error_code = 8
```

**Comment by meomap** [comment]
I tested with with `grpcio==0.13.1`, upgrading to `grpcio==0.14.0`, server does not crash anymore
```
E0622 19:55:37.324117722   25654 http_server_filter.c:116]   Invalid :method: header: 'GET'
E0622 19:55:37.324310168   25654 http_server_filter.c:167]   Missing :method header
E0622 19:55:37.324351183   25654 http_server_filter.c:173]   Missing te trailers header
E0622 19:55:37.325047090   25654 ssl_transport_security.c:437] SSL_read returned 0 unexpectedly.
E0622 19:55:37.325164636   25654 secure_endpoint.c:173]      Decryption error: TSI_INTERNAL_ERROR
```

**Comment by nathanielmanistaatgoogle** [comment]
Closing; glad to hear you were able to move forward after the upgrade.
