### ISSUE TITLE
ASAN failure: tests.bins/asan/end2end_test:SecureEnd2end/SecureEnd2endTest.BlockingAuthMetadataPluginFailure 

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#7142]
Local repro:
``` shell  
$ # Run this from grpc root
$ tools/run_tests/run_tests.py -lc++ -casan --build_only
$ tools/run_tests/run_tests.py -lc++ -casan -r BlockingAuthMetadataPluginFailure -S
```

```
Error Message

Failure
Standard Output

td::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::MetadataCredentialsPluginWrapper::*)(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::MetadataCredentialsPluginWrapper*, grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> >::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2039:2
    #21 0x6d03ac in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14
    #22 0x6cd4a3 in grpc::DynamicThreadPool::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:81:7
    #23 0x6cc90f in grpc::DynamicThreadPool::DynamicThread::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:50:3
    #24 0x6d43ae in void std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11
    #25 0x6d41d4 in void std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18
    #26 0x6d412f in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16
    #27 0x6d3ad6 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13
    #28 0x7f1c94c8496f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb696f)

Objects leaked above:
0x602000003f50 (16 bytes)

[1m[34mIndirect leak of 16 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4d0168 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x7012c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:58:7
    #2 0x75f8b2 in box_time /var/local/git/grpc/src/core/lib/iomgr/error.c:71:23
    #3 0x75f519 in grpc_error_create /var/local/git/grpc/src/core/lib/iomgr/error.c:242:28
    #4 0x7e5fcd in perform_stream_op_locked /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1033:11
    #5 0x7d21d7 in grpc_chttp2_run_with_global_lock /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:701:7
    #6 0x7e42e1 in perform_stream_op /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1122:3
    #7 0x7cbc8f in grpc_transport_perform_stream_op /var/local/git/grpc/src/core/lib/transport/transport.c:119:3
    #8 0x746c26 in con_start_transport_stream_op /var/local/git/grpc/src/core/lib/channel/connected_channel.c:72:3
    #9 0x74141c in grpc_call_next_op /var/local/git/grpc/src/core/lib/channel/channel_stack.c:236:3
    #10 0x7476e3 in hc_start_transport_op /var/local/git/grpc/src/core/lib/channel/http_client_filter.c:168:3
    #11 0x74141c in grpc_call_next_op /var/local/git/grpc/src/core/lib/channel/channel_stack.c:236:3
    #12 0xb1ca51 in bubble_up_error /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:96:3
    #13 0xb1ce35 in on_credentials_metadata /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:111:5
    #14 0x85664f in plugin_md_request_metadata_ready /var/local/git/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.c:70:5
    #15 0x696a6c in grpc::MetadataCredentialsPluginWrapper::InvokePlugin(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*) /var/local/git/grpc/src/cpp/client/secure_credentials.cc:215:3
    #16 0x69de46 in void std::_Mem_fn<void (grpc::MetadataCredentialsPluginWrapper::*)(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)>::operator()<grpc_auth_metadata_context&, void (*&)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*&, void>(grpc::MetadataCredentialsPluginWrapper*, grpc_auth_metadata_context&, void (*&)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11
    #17 0x69da47 in void std::_Bind<std::_Mem_fn<void (grpc::MetadataCredentialsPluginWrapper::*)(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::MetadataCredentialsPluginWrapper*, grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)>::__call<void, , 0ul, 1ul, 2ul, 3ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11
    #18 0x69d7a2 in void std::_Bind<std::_Mem_fn<void (grpc::MetadataCredentialsPluginWrapper::*)(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::MetadataCredentialsPluginWrapper*, grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)>::operator()<, void>() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:11
    #19 0x69c537 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::MetadataCredentialsPluginWrapper::*)(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> (grpc::MetadataCredentialsPluginWrapper*, grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*)> >::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2039:2
    #20 0x6d03ac in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14
    #21 0x6cd4a3 in grpc::DynamicThreadPool::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:81:7
    #22 0x6cc90f in grpc::DynamicThreadPool::DynamicThread::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:50:3
    #23 0x6d43ae in void std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11
    #24 0x6d41d4 in void std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18
    #25 0x6d412f in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16
    #26 0x6d3ad6 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13
    #27 0x7f1c94c8496f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb696f)

Objects leaked above:
0x602000003f30 (16 bytes)

-----------------------------------------------------
Suppressions used:
  count      bytes template
      1         32 CRYPTO_set_thread_local
      1        400 err_get_state
-----------------------------------------------------

SUMMARY: AddressSanitizer: 1355 byte(s) leaked in 28 allocation(s).
Command exited with non-zero status 1
real 0.34
user 0.06
sys 0.06
```

**Comment by sreecha** [comment]
Fixed by https://github.com/grpc/grpc/pull/7176
