### ISSUE TITLE
ASAN: tests.bins/asan/end2end_test:SecureEnd2end/SecureEnd2endTest.NonBlockingAuthMetadataPluginFailure/0

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#7143]
Local repro:
``` shell
$ tools/run_tests/run_tests.py -lc++ -casan --build_only
$ tools/run_tests/run_tests.py -lc++ -casan -r NonBlockingAuthMetadataPluginFailure -S
```
--------------

```
tests.bins/asan/end2end_test:SecureEnd2end/SecureEnd2endTest.NonBlockingAuthMetadataPluginFailure/0 (from grpc.tests)

Failing for the past 2 builds (Since Unstable#10409 )
Took 0.31 sec.
Error Message

Failure
Standard Output

7:5
    #29 0x7664c3 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:200:10

Objects leaked above:
0x602000003fb0 (16 bytes)

[1m[34mIndirect leak of 16 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4d0168 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x7012c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:58:7
    #2 0x75f8b2 in box_time /var/local/git/grpc/src/core/lib/iomgr/error.c:71:23
    #3 0x75f519 in grpc_error_create /var/local/git/grpc/src/core/lib/iomgr/error.c:242:28
    #4 0x7d3eaf in grpc_chttp2_complete_closure_step /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:916:11
    #5 0x7e5b8c in perform_stream_op_locked /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1016:9
    #6 0x7d21d7 in grpc_chttp2_run_with_global_lock /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:701:7
    #7 0x7e42e1 in perform_stream_op /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1122:3
    #8 0x7cbc8f in grpc_transport_perform_stream_op /var/local/git/grpc/src/core/lib/transport/transport.c:119:3
    #9 0x746c26 in con_start_transport_stream_op /var/local/git/grpc/src/core/lib/channel/connected_channel.c:72:3
    #10 0x74141c in grpc_call_next_op /var/local/git/grpc/src/core/lib/channel/channel_stack.c:236:3
    #11 0x7476e3 in hc_start_transport_op /var/local/git/grpc/src/core/lib/channel/http_client_filter.c:168:3
    #12 0x74141c in grpc_call_next_op /var/local/git/grpc/src/core/lib/channel/channel_stack.c:236:3
    #13 0xb1ca51 in bubble_up_error /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:96:3
    #14 0xb1ce35 in on_credentials_metadata /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:111:5
    #15 0x85664f in plugin_md_request_metadata_ready /var/local/git/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.c:70:5
    #16 0x696a6c in grpc::MetadataCredentialsPluginWrapper::InvokePlugin(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*) /var/local/git/grpc/src/cpp/client/secure_credentials.cc:215:3
    #17 0x695f51 in grpc::MetadataCredentialsPluginWrapper::GetMetadata(void*, grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*) /var/local/git/grpc/src/cpp/client/secure_credentials.cc:190:5
    #18 0x856292 in plugin_get_request_metadata /var/local/git/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.c:108:5
    #19 0x84534f in grpc_call_credentials_get_request_metadata /var/local/git/grpc/src/core/lib/security/credentials/credentials.c:124:3
    #20 0xb1c871 in send_security_metadata /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:192:3
    #21 0xb1be12 in on_host_checked /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:203:5
    #22 0x85ee29 in ssl_channel_check_call_host /var/local/git/grpc/src/core/lib/security/transport/security_connector.c:628:3
    #23 0x85aa54 in grpc_channel_security_connector_check_call_host /var/local/git/grpc/src/core/lib/security/transport/security_connector.c:172:5
    #24 0xb1b27a in auth_start_transport_op /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:259:7
    #25 0x88fed8 in grpc_subchannel_call_process_op /var/local/git/grpc/src/core/ext/client_config/subchannel.c:696:3
    #26 0x894411 in retry_ops /var/local/git/grpc/src/core/ext/client_config/subchannel_call_holder.c:234:5
    #27 0x75db46 in closure_wrapper /var/local/git/grpc/src/core/lib/iomgr/closure.c:99:3
    #28 0x767656 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:70:7
    #29 0xace6db in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1447:5

Objects leaked above:
0x602000003f90 (16 bytes)

[1m[34mIndirect leak of 16 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4d0168 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x7012c7 in gpr_malloc /var/local/git/grpc/src/core/lib/support/alloc.c:58:7
    #2 0x75f8b2 in box_time /var/local/git/grpc/src/core/lib/iomgr/error.c:71:23
    #3 0x75f519 in grpc_error_create /var/local/git/grpc/src/core/lib/iomgr/error.c:242:28
    #4 0x7e5fcd in perform_stream_op_locked /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1033:11
    #5 0x7d21d7 in grpc_chttp2_run_with_global_lock /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:701:7
    #6 0x7e42e1 in perform_stream_op /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1122:3
    #7 0x7cbc8f in grpc_transport_perform_stream_op /var/local/git/grpc/src/core/lib/transport/transport.c:119:3
    #8 0x746c26 in con_start_transport_stream_op /var/local/git/grpc/src/core/lib/channel/connected_channel.c:72:3
    #9 0x74141c in grpc_call_next_op /var/local/git/grpc/src/core/lib/channel/channel_stack.c:236:3
    #10 0x7476e3 in hc_start_transport_op /var/local/git/grpc/src/core/lib/channel/http_client_filter.c:168:3
    #11 0x74141c in grpc_call_next_op /var/local/git/grpc/src/core/lib/channel/channel_stack.c:236:3
    #12 0xb1ca51 in bubble_up_error /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:96:3
    #13 0xb1ce35 in on_credentials_metadata /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:111:5
    #14 0x85664f in plugin_md_request_metadata_ready /var/local/git/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.c:70:5
    #15 0x696a6c in grpc::MetadataCredentialsPluginWrapper::InvokePlugin(grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*) /var/local/git/grpc/src/cpp/client/secure_credentials.cc:215:3
    #16 0x695f51 in grpc::MetadataCredentialsPluginWrapper::GetMetadata(void*, grpc_auth_metadata_context, void (*)(void*, grpc_metadata const*, unsigned long, grpc_status_code, char const*), void*) /var/local/git/grpc/src/cpp/client/secure_credentials.cc:190:5
    #17 0x856292 in plugin_get_request_metadata /var/local/git/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.c:108:5
    #18 0x84534f in grpc_call_credentials_get_request_metadata /var/local/git/grpc/src/core/lib/security/credentials/credentials.c:124:3
    #19 0xb1c871 in send_security_metadata /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:192:3
    #20 0xb1be12 in on_host_checked /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:203:5
    #21 0x85ee29 in ssl_channel_check_call_host /var/local/git/grpc/src/core/lib/security/transport/security_connector.c:628:3
    #22 0x85aa54 in grpc_channel_security_connector_check_call_host /var/local/git/grpc/src/core/lib/security/transport/security_connector.c:172:5
    #23 0xb1b27a in auth_start_transport_op /var/local/git/grpc/src/core/lib/security/transport/client_auth_filter.c:259:7
    #24 0x88fed8 in grpc_subchannel_call_process_op /var/local/git/grpc/src/core/ext/client_config/subchannel.c:696:3
    #25 0x894411 in retry_ops /var/local/git/grpc/src/core/ext/client_config/subchannel_call_holder.c:234:5
    #26 0x75db46 in closure_wrapper /var/local/git/grpc/src/core/lib/iomgr/closure.c:99:3
    #27 0x767656 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.c:70:7
    #28 0xace6db in pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_epoll_linux.c:1447:5
    #29 0x7664c3 in grpc_pollset_work /var/local/git/grpc/src/core/lib/iomgr/ev_posix.c:200:10

Objects leaked above:
0x602000003f70 (16 bytes)

-----------------------------------------------------
Suppressions used:
  count      bytes template
      1         32 CRYPTO_set_thread_local
      1        400 err_get_state
-----------------------------------------------------

SUMMARY: AddressSanitizer: 1355 byte(s) leaked in 28 allocation(s).
Command exited with non-zero status 1
real 0.31
user 0.09
sys 0.04
```

**Comment by yang-g** [comment]
This should have been fixed by https://github.com/grpc/grpc/pull/7176.
