### ISSUE TITLE
large_unary test between java and ruby fail

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#717]
Running test large_unary
Feb 19, 2015 11:42:38 PM io.netty.channel.DefaultChannelId defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 9a:09:74:79:6c:84:ce:44
Exception in thread "main" org.junit.ComparisonFailure: expected:<payload {
  [type: COMPRESSABLE
  ]body: "\000\000\000\...> but was:<payload {
  []body: "\000\000\000\...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.grpc.testing.integration.Util.assertEquals(Util.java:101)
	at io.grpc.testing.integration.AbstractTransportTest.largeUnary(AbstractTransportTest.java:153)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:184)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:171)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:73)
Shutting down
:grpc-integration-testing:execute FAILED

FAILURE: Build failed with an exception.

BUILD FAILED

Total time: 24.159 secs
* What went wrong:
Execution failed for task ':grpc-integration-testing:execute'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

This is a known proto2 vs proto3 issue. Once we all swap to proto3 it will go away.

**Comment by tbetbetbe** [comment]
This is now fixed, as the java interop test has switched to proto3
