### ISSUE TITLE
Ruby on OSX: trivial RpcServer shutdown leaks tcp-server-listener

### ISSUE THREAD

**Issue by peterhuene** [grpc/grpc#7217]
OS: Mac OS X (10.11.5)
Ruby version: 2.2.5
gRPC version: 0.15.0

Note: the repro intentionally fails to register a service with the RPC server simply for the sake of a simplified repro, but even if a service is registered, the same wait-delay and leak is experienced when `SIGINT` is received by the process.

Repro:
```ruby
require 'grpc'

puts "gRPC version: #{GRPC::VERSION}"
server = GRPC::RpcServer.new
server.add_http2_port('0.0.0.0:3000', :this_port_is_insecure)
server.run_till_terminated
```

Output (stdout and stderr):
```
gRPC version: 0.15.0
D0701 15:37:37.892394000 140735319822336 ev_posix.c:101] Using polling engine: poll
/Users/peterhuene/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grpc-0.15.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:340:in `block in run': cannot run without registering services (RuntimeError)
	from /Users/peterhuene/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grpc-0.15.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:339:in `synchronize'
	from /Users/peterhuene/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grpc-0.15.0-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:339:in `run'
	from repro.rb:6:in `<main>'
D0701 15:37:38.932565000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:39.952944000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:40.983342000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:42.010067000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:43.045996000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:44.074138000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:45.096166000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:46.124101000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:47.147566000 140735319822336 iomgr.c:99] Waiting for 1 iomgr objects to be destroyed
D0701 15:37:47.974508000 140735319822336 iomgr.c:118] Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0701 15:37:47.974544000 140735319822336 iomgr.c:80] LEAKED OBJECT: tcp-server-listener:(sockaddr family=157) fd=9 0x7fd35ad43670
````

**Comment by peterhuene** [comment]
This appears fixed in 1.0.0.  Closing for now.
