### ISSUE TITLE
Error: grpc_node.node: invalid ELF header

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#7236]
_From @Nabarun on July 5, 2016 5:11_

I have a node.js app which is deployed in heroku. I am using gcloud to query vision related stuff. It works on my local but in heroku it throws following exception. Please help me to resolve this

```
2016-07-05T04:56:40.742299+00:00 app[web.1]: module.js:440
2016-07-05T04:56:40.742348+00:00 app[web.1]:   return process.dlopen(module, path._makeLong(filename));
2016-07-05T04:56:40.742354+00:00 app[web.1]:                  ^
2016-07-05T04:56:40.742355+00:00 app[web.1]: 
2016-07-05T04:56:40.742356+00:00 app[web.1]: Error: /app/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node: invalid ELF header
2016-07-05T04:56:40.742356+00:00 app[web.1]:     at Error (native)
2016-07-05T04:56:40.742357+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:440:18)
2016-07-05T04:56:40.742358+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-05T04:56:40.742358+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-07-05T04:56:40.742359+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-07-05T04:56:40.742359+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-07-05T04:56:40.742360+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
2016-07-05T04:56:40.742361+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-07-05T04:56:40.742361+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-07-05T04:56:40.742362+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-05T04:56:40.723358+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/getlogo?url=http://i.forbesimg.com/media/lists/companies/coca-cola_416x416.jpg" host=runu.herokuapp.com request_id=92c7b1f8-be1c-4009-b2a9-73ac8adf81fe fwd="71.202.43.114" dyno=web.1 connect=1ms service=1350ms status=503 bytes=0
2016-07-05T04:56:41.531276+00:00 heroku[web.1]: Process exited with status 1
2016-07-05T04:56:41.516318+00:00 heroku[web.1]: State changed from up to crashed
```

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1409_

**Comment by stephenplusplus** [comment]
_From @Nabarun on July 5, 2016 5:13_

node --version
v4.4.1

**Comment by murgatroid99** [comment]
That error looks like the heroku instance, for some reason, has a non-Linux version of the `grpc_node.node` file. What is your process for deploying to heroku?

**Comment by Nabarun** [comment]
Here is the process I followed

Download and install the Heroku Toolbelt or learn more about the Heroku Command Line Interface.

If you haven't already, log in to your Heroku account and follow the prompts to create a new SSH public key.

$ heroku login
Clone the repository

Use Git to clone runu's source code to your local machine.

$ heroku git:clone -a runu
$ cd runu
Deploy your changes

Make some changes to the code you just cloned and deploy them to Heroku using Git.

$ git add .
$ git commit -am "make it better"
$ git push heroku master

**Comment by murgatroid99** [comment]
OK, if you're installing the package on a local machine that is not Linux, then copying everything you get to Heroku, I would not expect that to work for this package or any other package with a native extension.

I would recommend following [this guide](https://devcenter.heroku.com/articles/deploying-nodejs). Specifically, this part is important:

> Prevent build artifacts from going into revision control by creating a .gitignore file that looks something like this:

> ```
/node_modules
npm-debug.log
.DS_Store
/*.env
```

**Comment by Nabarun** [comment]
I followed the tutorial, now it is crashing due to different reason on heroku. BTW my local setup is on Mac.

Does gcloud use stream-shift?

'connect-time': '19',
2016-07-09T05:11:12.804935+00:00 app[web.1]: module.js:327
2016-07-09T05:11:12.804961+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-07-09T05:11:12.804956+00:00 app[web.1]:     ^
2016-07-09T05:11:12.804955+00:00 app[web.1]:     throw err;
2016-07-09T05:11:12.804958+00:00 app[web.1]: Error: Cannot find module 'stream-shift'
2016-07-09T05:11:12.804959+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:325:15)
2016-07-09T05:11:12.804963+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-07-09T05:11:12.804963+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-07-09T05:11:12.804957+00:00 app[web.1]: 
2016-07-09T05:11:12.804960+00:00 app[web.1]:     at Function.Module._load (module.js:276:25)
2016-07-09T05:11:12.804960+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-07-09T05:11:12.804964+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-07-09T05:11:12.804965+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-07-09T05:11:12.804962+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/gcloud/node_modules/duplexify/index.js:4:13)
2016-07-09T05:11:12.804964+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-07-09T05:11:12.810388+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/getlabels?url=https://make.wordpress.org/core/files/2016/02/2A-3-1.jpg" host=runu.herokuapp.com request_id=a972c855-e0c0-4b1d-a8fd-ea2d915e1c5f fwd="71.202.43.114" dyno=web.1 connect=19ms service=43ms status=503 bytes=0
2016-07-09T05:11:13.601448+00:00 heroku[web.1]: Process exited with status 1

**Comment by Nabarun** [comment]
OK again I am hitting the same invalid ELF issue after importing stream-shift module


2016-07-09T16:15:03.242914+00:00 app[web.1]: 
2016-07-09T16:15:03.242917+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-07-09T16:15:03.242913+00:00 app[web.1]:                  ^
2016-07-09T16:15:03.242915+00:00 app[web.1]: Error: /app/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node: invalid ELF header
2016-07-09T16:15:03.242915+00:00 app[web.1]:     at Error (native)
2016-07-09T16:15:03.242912+00:00 app[web.1]:   return process.dlopen(module, path._makeLong(filename));
2016-07-09T16:15:03.242919+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-07-09T16:15:03.242916+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:434:18)
2016-07-09T16:15:03.242920+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
2016-07-09T16:15:03.242919+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-07-09T16:15:03.242921+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-07-09T16:15:03.242918+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-07-09T16:15:03.242921+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-07-09T16:15:03.242922+00:00 app[web.1]:     at Module.load (module.js:343:32)

**Comment by Nabarun** [comment]
I kind of solved it by building the app in a linux box. Now everything is working fine. Created a sample app with gcloud. It works seemless. Thanks guys for this wonderful addon. http://runu.herokuapp.com/#/imagedetection

**Comment by andrewconnell** [comment]
+1 same problem... Node.js app (v5.11.1) that works fine on the host (OSX), but throws the same error when spinning up within a Docker container. I copied the package.json into the container and ran `NPM INSTALL` from within the container it was acquired & built on a linux system.

`Dockerfile` snippet:
```
COPY package.json /voyager/app/
RUN npm install --production
```

Output:
```
app_1  | module.js:440
app_1  |   return process.dlopen(module, path._makeLong(filename));
app_1  |                  ^
app_1  |
app_1  | Error: /voyager/app/node_modules/grpc/src/node/extension_binary/grpc_node.node: invalid ELF header
app_1  |     at Error (native)
app_1  |     at Object.Module._extensions..node (module.js:440:18)
app_1  |     at Module.load (module.js:357:32)
app_1  |     at Function.Module._load (module.js:314:12)
app_1  |     at Module.require (module.js:367:17)
app_1  |     at require (internal/module.js:20:19)
app_1  |     at Object.<anonymous> (/voyager/app/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
app_1  |     at Module._compile (module.js:413:34)
app_1  |     at Object.Module._extensions..js (module.js:422:10)
app_1  |     at Module.load (module.js:357:32)
```

**Comment by skymapHans** [comment]
I thought I should leave a comment on this as I've been struggling with this issue back and forth a bit.
Turns out the problem I was having was that I was using [an onbuild docker image (link)](https://github.com/grpc/grpc-docker-library/blob/master/1.0/node/onbuild/Dockerfile) which did: 
`ONBUILD RUN npm install` before
`ONBUILD COPY . /usr/src/app`
And I simply didn't have a .dockerignore to ignore my node_modules folder. Thus after installing dependencies with npm install, it copied my local node_modules, compiled on a windows-machine, onto the Linux VM, effectively overwriting the correct native build of grpc that was already on there.

So just add node_modules to your .dockerignore and it's solved.

**Comment by hsaliak** [comment]
@skymapHans thanks for the details - very useful pointers for others who might experience this. I'll leave the issue as closed.

**Comment by mahanhaz** [comment]
@skymapHans i did what you say but still got the issue. 
instead i removed my node_module directory from my project, also added them into .dockerignore and changed my code to this:
```
# Install app dependencies
ADD package.json /tmp/package.json
RUN cd /tmp && yarn install
RUN cp -ar /tmp/node_modules /usr/local/lib/
```

ofcourse i used `yarn`, you guys can change it with `npm install`

i just copied the dependencies into global directory of nodejs. incase you have another global directory you can copy there

**Comment by bellaj** [comment]
Thanks @skymapHans very much. that was exactly my problem, in the beginning i suspected a file corruption but when i read your answer I've remembered that I've omitted the "node_modules/*
" from the .dockerignore file.

**Comment by sdiachenko** [comment]
The fast solution for me was to add '.dockerignore' and ignore 'node_modules' there
