### ISSUE TITLE
address sanitizer warning on c++ example

### ISSUE THREAD

**Issue by elazarl** [grpc/grpc#7261]
Compiling C++ helloworld example with `-fsanitize=address -fsanitize=undefined` on clang-3.8 on ARM, gives the following warning:

```
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:666:4: runtime error: member call on address 0x75101ed0 which does not point to an object of type 'std::_Sp_counted_base<__gnu_cxx::_Lock_policy::_S_atomic>'
0x75101ed0: note: object is of type '*St15_Sp_counted_ptrIPN4grpc12_GLOBAL__N_129InsecureServerCredentialsImplELN9__gnu_cxx12_Lock_policyE1EE'
 02 00 00 7c  c8 07 f0 76 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~
              vptr for '*St15_Sp_counted_ptrIPN4grpc12_GLOBAL__N_129InsecureServerCredentialsImplELN9__gnu_cxx12_Lock_policyE1EE'
SUMMARY: AddressSanitizer: undefined-behavior /usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:666:4 in 
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:146:46: runtime error: member access within address 0x75101ed0 which does not point to an object of type 'std::_Sp_counted_base<__gnu_cxx::_Lock_policy::_S_atomic>'
0x75101ed0: note: object is of type '*St15_Sp_counted_ptrIPN4grpc12_GLOBAL__N_129InsecureServerCredentialsImplELN9__gnu_cxx12_Lock_policyE1EE'
 02 00 00 7c  c8 07 f0 76 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~
              vptr for '*St15_Sp_counted_ptrIPN4grpc12_GLOBAL__N_129InsecureServerCredentialsImplELN9__gnu_cxx12_Lock_policyE1EE'
SUMMARY: AddressSanitizer: undefined-behavior /usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:146:46 in 
```

When compiling with gcc 3.9 `-fsanitize=address` I recieve

```
ASAN:SIGSEGV
=================================================================
==22041==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0x00000000 sp 0x7367bd68 bp 0x7367bd8c T1)
ASAN:SIGSEGV
==22041==AddressSanitizer: while reporting a bug found another one.Ignoring.

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
Thread T1 created by T0 here:
    #0 0x76a4cf43 in __interceptor_pthread_create (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1ff43)
    #1 0x7680a57b in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) (/usr/lib/arm-linux-gnueabihf/libstdc++.so.6+0xa557b)
    #2 0x76a09d47 in thread<void (grpc::DynamicThreadPool::DynamicThread::*)(), grpc::DynamicThreadPool::DynamicThread*> /usr/include/c++/4.9/thread:138
    #3 0x76a09d47 in grpc::DynamicThreadPool::DynamicThread::DynamicThread(grpc::DynamicThreadPool*) src/cpp/server/dynamic_thread_pool.cc:43
    #4 0x76a0a26f in grpc::DynamicThreadPool::DynamicThreadPool(int) src/cpp/server/dynamic_thread_pool.cc:96
    #5 0x76a0983b in grpc::CreateDefaultThreadPool() src/cpp/server/create_default_thread_pool.cc:45
    #6 0x76a14863 in grpc::ServerBuilder::BuildAndStart() src/cpp/server/server_builder.cc:146
```

Both on ARM.

**Comment by mehrdada** [comment]
I stumbled upon this old issue while searching for another issue. The code base has changed quite a bit since this was filed and I don't have immediate access to the ARM environment you mentioned to try and repro. Please let me know if you can see it on the current 1.9.x or master branch heads. Otherwise, if you are unable to repro or we don't hear back, I think closing this issue makes sense (in that case, feel free to ping or refile, obviously). Thanks!
