### ISSUE TITLE
Windows Python Test Flake

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#7309]
```
[91m_exit_test.ExitTest.test_running_server_terminate[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "C:\Python27\Lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\jenkins\workspace\gRPC_pull_requests\config\dbg\language\python\platform\windows\src\python\grpcio_tests\tests\unit\_exit_test.py", line 111, in test_running_server_terminate
    interrupt_and_wait(process)
  File "C:\jenkins\workspace\gRPC_pull_requests\config\dbg\language\python\platform\windows\src\python\grpcio_tests\tests\unit\_exit_test.py", line 77, in interrupt_and_wait
    os.kill(process.pid, signal.SIGINT)
WindowsError: [Error 5] Access is denied
```

**Comment by kpayson64** [comment]
I think https://github.com/grpc/grpc/pull/7315 will solve this.

I think the permission errors are because we are trying to kill a pid we no longer own, the exit-test exits immediately because of an unexpected exception.
