### ISSUE TITLE
import user.proto err

### ISSUE THREAD

**Issue by zxydaisy** [grpc/grpc#7524]
var PROTO_PATH = __dirname + '../lib/protos/user.proto';
var grpc = require('grpc');
var hello_proto = grpc.load(PROTO_PATH).helloworld;

D0726 11:46:08.857119000 140735144903424 ev_posix.c:101] Using polling engine: poll
/Users/zhangjinglong/console-web/node_modules/grpc/src/node/index.js:124
  return loadObject(builder.ns, options);
                           ^

TypeError: Cannot read property 'ns' of null
    at Object.load (/Users/zhangjinglong/console-web/node_modules/grpc/src/node/index.js:124:28)
    at Object.<anonymous> (/Users/zhangjinglong/console-web/controller/imageclassify.js:9:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/zhangjinglong/console-web/controller/index.js:19:18)
    at Module._compile (module.js:409:26)

**Comment by murgatroid99** [comment]
This indicates that Protobuf.js failed to load the file. Are you sure the `PROTO_PATH` is correct? Are you sure the .proto file is syntactically correct?

**Comment by tylerwgoza** [comment]
I am actually having the same issue. And in my case I can confirm that the helloworld.proto is correct or appears to be because the server js file I'm running is loading the same .proto file without any issues.

**Comment by tylerwgoza** [comment]
I retract my previous statement. I did, in fact, have my path wrong. Glad I caught my mistake before I had anyone wasting too much time on this. So sorry.

**Comment by wbmrcb** [comment]
@zxydaisy PROTO_PATH should be `__dirname + '/../lib/protos/user.proto';`
