### ISSUE TITLE
Installation error on Ubuntu 14.04

### ISSUE THREAD

**Issue by linardo** [grpc/grpc#7565]
I am running` sudo pip install gprcio` and I am getting the following errors:

```
`Collecting grpcio
  Downloading grpcio-0.15.0.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 261kB/s 
3DRequirement already satisfied (use --upgrade to upgrade): six>=1.10 in /usr/local/lib/python3.4/dist-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /usr/local/lib/python3.4/dist-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /usr/local/lib/python3.4/dist-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /usr/local/lib/python3.4/dist-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python3.4/dist-packages (from protobuf>=3.0.0a3->grpcio)
Installing collected packages: grpcio
  Running setup.py install for grpcio ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ukgk1dzq/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-btt2lldy-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_proto_modules
    Traceback (most recent call last):
      File "/tmp/pip-build-ukgk1dzq/grpcio/src/python/grpcio/commands.py", line 229, in run
        self.run_command('build_proto_modules')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-ukgk1dzq/grpcio/src/python/grpcio/commands.py", line 161, in run
        raise CommandError('could not find grpc_python_plugin '
    commands.CommandError: could not find grpc_python_plugin (protoc plugin for GRPC Python)
    
   During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ukgk1dzq/grpcio/setup.py", line 258, in <module>
        test_runner=TEST_RUNNER,
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-ukgk1dzq/grpcio/src/python/grpcio/commands.py", line 231, in run
        sys.stderr.write('warning: %s\n' % error.message)
    AttributeError: 'CommandError' object has no attribute 'message'
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ukgk1dzq/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-btt2lldy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ukgk1dzq/grpcio/
```

**Comment by nathanielmanistaatgoogle** [comment]
Do you happen to know which version of `pip` you are using? Also `0.15` is just a little bit out of date - do you see the same problem for `pip install --upgrade --pre grpcio==1.0.0rc1`?

**Comment by linardo** [comment]
```
pip --version
pip 8.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)

```

**Comment by soltanmm** [comment]
PyPI pre-release candidates are only installed via recent `pip`s when the `--pre` flag is specified. Not specifying it implies you don't want a pre-release.

Wheels for Linux have only recently been made available via PyPI and `pip`, so the system-packaged `pip`s for systems older than a few months are too old unless backports were made.
