### ISSUE TITLE
Python: beta_create_<Package>_stub doesn't exist

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc#7622]
```python
dir(domain_pb2)
# ['DESCRIPTOR', 'Empty', 'GetContextResponse', 'GroupRequest', 'IdentifyRequest', 'ReportErrorRequest', 'ReportWarningRequest', 'SetRequest', 'StatsRequest', 'StatusResponse', 'StoreContextRequest', 'StoreContextResponse', 'TrackRequest', '_EMPTY', '_GETCONTEXTRESPONSE', '_GROUPREQUEST', '_IDENTIFYREQUEST', '_REPORTERRORREQUEST', '_REPORTWARNINGREQUEST', '_SETREQUEST', '_STATSREQUEST', '_STATUSRESPONSE', '_STORECONTEXTREQUEST', '_STORECONTEXTRESPONSE', '_TRACKREQUEST', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_b', '_descriptor', '_message', '_reflection', '_sym_db', '_symbol_database', 'descriptor_pb2', 'sys']

domain_pb2.beta_create_Source_stub(channel)
# AttributeError: module 'segment_source.domain_pb2' has no attribute 'beta_create_Source_stub'
```

This is the generated module- https://gist.github.com/tejasmanohar/6cfb0cce9c4c86449101f643bda6a92b. I used the following command to build it-
```
$ protoc --version
libprotoc 3.0.0
$ protoc --python_out=. --plugin=protoc-gen-grpc=grpc_python_plugin segment_source/shared/domain.proto
# ...
```
as per [the docs](http://www.grpc.io/docs/tutorials/basic/python.html)

Any ideas why this method doesn't exist?

**Comment by tejasmanohar** [comment]
Can't debug further due to https://github.com/grpc/homebrew-grpc/issues/84 :(

**Comment by tejasmanohar** [comment]
Tried generating code for the examples using exact commands from guide
```
Tejass-MacBook-Pro:route_guide tejas$ python -m grpc.tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/route_guide.proto
D0802 23:36:40.380919000 140735246098432 ev_posix.c:101] Using polling engine: poll
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/site-packages/grpc/tools/protoc.py", line 41, in <module>
    sys.argv + ['-I{}'.format(proto_include)])
  File "grpc/tools/protoc_compiler.pyx", line 38, in grpc.tools.protoc_compiler.run_main (grpc/tools/protoc_compiler.cpp:783)
TypeError: expected bytes, str found
```

This is just after `pip install --upgrade cython grpc grpcio-tools`

**Comment by pgrosu** [comment]
Hi Tejas,

Do you mean `beta_create_$Service$_server` and `beta_create_$Service$_stub` from these two lines?

https://github.com/grpc/grpc/blob/master/src/compiler/python_generator.cc#L285

https://github.com/grpc/grpc/blob/master/src/compiler/python_generator.cc#L385

It seems you are running Python 3.5, which is in beta now as noted here https://github.com/grpc/grpc/issues/7591#issuecomment-236700747.  Can you try with 2.7?

The following works for me for [`helloworld.proto`](https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto):

```
python -c "from grpc.tools import protoc;  protoc.main(('', '-I../../protos', '--python_out=.', '--grpc_python_out=.', '../../protos/helloworld.proto',))"
```

And I get the `beta_create`:

```
$ fgrep beta helloworld_pb2.py
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
def beta_create_Greeter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)
def beta_create_Greeter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'helloworld.Greeter', cardinalities, options=stub_options)
[pgrosu@eofe4 hw]$ fgrep beta_create helloworld_pb2.py
def beta_create_Greeter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
def beta_create_Greeter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
$
```

I think with your proto file it would the following:

```
python -c "from grpc.tools import protoc;  protoc.main(('', '-I../../protos', '--python_out=.', '--grpc_python_out=.', 'segment_source/shared/domain.proto',))"
```

Hope it helps,
Paul

**Comment by tejasmanohar** [comment]
`protoc  -I segment_source/shared/ --python_out=segment_source --grpc_out=segment_source --plugin=protoc-gen-grpc=`which grpc_python_plugin` segment_source/shared/domain.proto`

works for me on python 3

**Comment by tejasmanohar** [comment]
yeah your solution also works there

**Comment by pgrosu** [comment]
Glad to hear it helped.

Thanks,
~p

**Comment by tejasmanohar** [comment]
Thanks!
