### ISSUE TITLE
gRPC_interop_experiments is broken

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#7657]
https://grpc-testing.appspot.com/job/gRPC_interop_experiments/2901/console

ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/grpc/grpc.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:799)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1055)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1086)
	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:143)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "git reset --hard" returned status code 128:
stdout: 
stderr: error: object file .git/objects/4e/29480e430b94392105934750adfd85cb7849ce is empty
error: object file .git/objects/4e/29480e430b94392105934750adfd85cb7849ce is empty
fatal: loose object 4e29480e430b94392105934750adfd85cb7849ce (stored in .git/objects/4e/29480e430b94392105934750adfd85cb7849ce) is corrupt

**Comment by pgrosu** [comment]
@adelez This looks like a temporary Github issue.  I would just resubmit that build.

**Comment by adelez** [comment]
It's caused by a corrupted github object. Fixed now.
