### ISSUE TITLE
grpc_node.node: undefined symbol: MOZ_Z_deflate in Docker container

### ISSUE THREAD

**Issue by danvk** [grpc/grpc#7685]
I'm trying to use gcloud-node to access Google Cloud Storage. I'm able to do this on my dev box (running Mac OS X). When I try to do the same inside a docker image running on GKE (Google Container Engine), however, I get the following runtime error:

```
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.7.1
npm info lifecycle static-gcs-server@1.0.0~prestart-prod: static-gcs-server@1.0.0
npm info lifecycle static-gcs-server@1.0.0~start-prod: static-gcs-server@1.0.0

> static-gcs-server@1.0.0 start-prod /usr/src/app
> node server.js --port $STATIC_PORT

module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/src/app/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node: undefined symbol: MOZ_Z_deflate
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/src/app/node_modules/gcloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

npm info lifecycle static-gcs-server@1.0.0~start-prod: Failed to exec start-prod script
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-prod"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! static-gcs-server@1.0.0 start-prod: `node server.js --port $STATIC_PORT`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the static-gcs-server@1.0.0 start-prod script 'node server.js --port $STATIC_PORT'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the static-gcs-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --port $STATIC_PORT
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs static-gcs-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls static-gcs-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

On my dev system:

```
$ npm --version
3.5.3
$ node --version
v5.5.0

$ npm ls grpc
static-gcs-server@1.0.0 /Users/danvk/github/static-gcs-server
└─┬ gcloud@0.37.0
  └── grpc@0.14.1
```

On the GKE instance:
```
$ npm --version
3.6.0
$ node --version
v5.7.1

$ npm ls grpc
static-gcs-server@1.0.0 /usr/src/app
`-- gcloud@0.37.0
  `-- grpc@0.14.1
```

Is there something else I need to install in my Docker container to make this work?

**Comment by danvk** [comment]
I figured out the issue. I was running `npm install` on CircleCI, then copying `node_modules` into the Docker image. This works great for pure-JS modules, but it doesn't work for modules like `grpc` that compile C code. The environment on CircleCI and inside my Docker image was different, so it crashed.

One solution would be to run `npm install` inside the Docker image. For various reasons I didn't want to do that. So instead I reinstalled gcloud inside the image. Here's what I added to my `Dockerfile`:

```
RUN npm uninstall gcloud && npm install gcloud
```
