### ISSUE TITLE
gRPC Python-on-Mac installation woes: "OSError: [Errno 1] Operation not permitted"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#7689]
From today's friction testing, courtesy of @menghanl:
```
% sudo pip install grpcio
Collecting grpcio
  Using cached grpcio-0.15.0-cp27-cp27m-macosx_10_10_intel.whl
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /Library/Python/2.7/site-packages (from grpcio)
Collecting six>=1.10 (from grpcio)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from grpcio)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting protobuf>=3.0.0a3 (from grpcio)
  Using cached protobuf-3.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0a3->grpcio)
Installing collected packages: six, enum34, protobuf, grpcio
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-qwTLbI-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```
. I confirmed afterward that `pip` was at a late enough version (8.1.2) and that `sudo pip install --upgrade --pre grpcio` and `sudo pip uninstall six` were also unsuccessful.

**Comment by nathanielmanistaatgoogle** [comment]
This may be a recurrence of [issue 6027](https://github.com/grpc/grpc/issues/6027). At the very least it seems too easy for Mac users to get into a troubled state.

**Comment by nathanielmanistaatgoogle** [comment]
@kpayson64: is this issue as fixed as it's going to get by [today's documentation change](https://github.com/grpc/grpc.github.io/pull/299)? If so please close.
