### ISSUE TITLE
Cannot use Empty message as GRPC response

### ISSUE THREAD

**Issue by alenkacz** [grpc/grpc#8010]
I have a service defined like this 

`rpc reportCentroids(Centroids) returns (google.protobuf.Empty) {}`

When making the request, I got an exception because value is missing - I suspect, that google.protobuf.Empty message actually is a message of length 0 bytes, which might look like the whole value is missing (?). But I did not dug that deeply into the code.

```
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: No value received for unary call
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
	at com.avast.odin.norny.clustering.ReportClusteringGrpc$ReportClusteringBlockingStub.reportCentroids(ReportClusteringGrpc.java:197)
	at com.avast.odin.norny.clustering.ReportClusteringClient.reportClustering(ReportClusteringClient.scala:20)
	at com.avast.odin.norny.clustering.Server$.main(Server.scala:17)
	at com.avast.odin.norny.clustering.Server.main(Server.scala)
```

Everything works, when I substitute google.protobuf.Empty for a message with an actual field (not an empty message). Is this a bug? (I think it is - btw. the C++ client behaves the same)

**Comment by ejona86** [comment]
What language is the server implemented in? That error says that there was no message received, which is different from a zero-length message. I expect the bug is on server-side.

**Comment by alenkacz** [comment]
Hmm, you are right - that being bug on server actually makes much more sense.

Server is implemented in Scala (but uses grpc-java).

**Comment by ejona86** [comment]
Is the server calling `StreamObserver.onCompleted()` (or `ServerCall.close(Status.OK,...)`) without first sending a message?

**Comment by alenkacz** [comment]
@ejona86 this is really embarassing, sorry :) My first app in GRPC.

**Comment by ejona86** [comment]
@alenkacz, no problem. It made us realize we weren't verifying that on server-side. :smile:

**Comment by forestwanglin** [comment]
I got the same issue with grpc-1.6., jdk1.8.   
If I ran the server in IDE, I can get the response data in client side. But if I ran the server from jar directly, I got the error.
INTERNAL: No value received for unary call

anyone can help？
