### ISSUE TITLE
Fuzzing detected memory leak in HTTP GET implementation

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#8088]
https://github.com/grpc/grpc/pull/8087 shows a memory leak in our GET implementation:

```
=================================================================
==24715==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 746 byte(s) in 1 object(s) allocated from:
    #0 0x4c4e08 in malloc /usr/local/google/home/ctiller/llvm-3.8.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x65e8a7 in gpr_malloc /usr/local/google/home/ctiller/grpc2/src/core/lib/support/alloc.c:58:7
    #2 0x563b9f in grpc_mdstr_from_buffer /usr/local/google/home/ctiller/grpc2/src/core/lib/transport/metadata.c:418:9
    #3 0x5c45de in hc_mutate_op /usr/local/google/home/ctiller/grpc2/src/core/lib/channel/http_client_filter.c:248:13
    #4 0x5c31af in hc_start_transport_op /usr/local/google/home/ctiller/grpc2/src/core/lib/channel/http_client_filter.c:294:3
    #5 0x656ff8 in grpc_subchannel_call_process_op /usr/local/google/home/ctiller/grpc2/src/core/ext/client_config/subchannel.c:696:3
    #6 0x64eb01 in retry_ops /usr/local/google/home/ctiller/grpc2/src/core/ext/client_config/client_channel.c:432:5
    #7 0x57a986 in closure_wrapper /usr/local/google/home/ctiller/grpc2/src/core/lib/iomgr/closure.c:99:3
    #8 0x510096 in grpc_exec_ctx_flush /usr/local/google/home/ctiller/grpc2/src/core/lib/iomgr/exec_ctx.c:71:7
    #9 0x5486f0 in grpc_completion_queue_next /usr/local/google/home/ctiller/grpc2/src/core/lib/surface/completion_queue.c:376:7
    #10 0x4f4f69 in LLVMFuzzerTestOneInput /usr/local/google/home/ctiller/grpc2/test/core/end2end/fuzzers/api_fuzzer.c:565:25
    #11 0x4ff636 in main /usr/local/google/home/ctiller/grpc2/test/core/util/one_corpus_entry_fuzzer.c:50:3
    #12 0x7fa384addf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

Indirect leak of 1200 byte(s) in 1 object(s) allocated from:
    #0 0x4c4e08 in malloc /usr/local/google/home/ctiller/llvm-3.8.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x65e8a7 in gpr_malloc /usr/local/google/home/ctiller/grpc2/src/core/lib/support/alloc.c:58:7
    #2 0x668ff8 in gpr_slice_malloc /usr/local/google/home/ctiller/grpc2/src/core/lib/support/slice.c:200:27
    #3 0x8dfba5 in grpc_chttp2_base64_encode_and_huffman_compress_impl /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/bin_encoder.c:185:22
    #4 0x568827 in grpc_mdstr_as_base64_encoded_and_huffman_compressed /usr/local/google/home/ctiller/grpc2/src/core/lib/transport/metadata.c:744:9
    #5 0x6118f7 in get_wire_value /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/hpack_encoder.c:275:12
    #6 0x610901 in emit_lithdr_noidx_v /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/hpack_encoder.c:339:27
    #7 0x60aca5 in hpack_enc /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/hpack_encoder.c:450:5
    #8 0x608bcd in grpc_chttp2_encode_header /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/hpack_encoder.c:573:5
    #9 0x63f35b in finalize_outbuf /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/writing.c:218:7
    #10 0x63e7e5 in grpc_chttp2_perform_writes /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/writing.c:190:3
    #11 0x5e9cc4 in writing_action /usr/local/google/home/ctiller/grpc2/src/core/ext/transport/chttp2/transport/chttp2_transport.c:1014:3
    #12 0x510096 in grpc_exec_ctx_flush /usr/local/google/home/ctiller/grpc2/src/core/lib/iomgr/exec_ctx.c:71:7
    #13 0x5486f0 in grpc_completion_queue_next /usr/local/google/home/ctiller/grpc2/src/core/lib/surface/completion_queue.c:376:7
    #14 0x4f4f69 in LLVMFuzzerTestOneInput /usr/local/google/home/ctiller/grpc2/test/core/end2end/fuzzers/api_fuzzer.c:565:25
    #15 0x4ff636 in main /usr/local/google/home/ctiller/grpc2/test/core/util/one_corpus_entry_fuzzer.c:50:3
    #16 0x7fa384addf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
```

**Comment by makdharma** [comment]
https://github.com/grpc/grpc/pull/8254

**Comment by vjpai** [comment]
@makdharma - please update the status of that PR which is still pending
