### ISSUE TITLE
CoreCLR apps require libc-dev to be installed.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8156]
Otherwise they fail with `System.DllNotFoundException: Unable to load DLL 'libdl.so'`

https://github.com/grpc/grpc/blob/08eddaa7c117f69bd829992d7379aadeef5b0cbb/tools/dockerfile/distribtest/csharp_ubuntu1404_x64/Dockerfile#L58

**Comment by jtattermusch** [comment]
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libdl.so': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at TestGrpcPackage.MainClass.Main(String[] args)
```
