### ISSUE TITLE
Python portability tests starts failing after protobuf 3.1.0

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#8210]
The "linux_default_python3.4" portability tests seem to start failing since this build:

https://grpc-testing.appspot.com/job/gppr/language=python,scenario=linux_default_python3.4/7227/

Relevant part of the logs

```
Installing collected packages: cython
Successfully installed cython-0.24.1
+ pip_install_dir /var/local/git/grpc
++ pwd
+ PWD=/var/local/git/grpc
+ cd /var/local/git/grpc
+ /var/local/git/grpc/py34/bin/python setup.py build_ext -c unix
Compiling src/python/grpcio/grpc/_cython/cygrpc.pyx because it changed.
[1/1] Cythonizing src/python/grpcio/grpc/_cython/cygrpc.pyx
You requested a Cython build via GRPC_PYTHON_BUILD_WITH_CYTHON, but do not have Cython installed. We won't stop you from using other commands, but the extension files will fail to build.
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
__pycache__.six.cpython-34: module references __path__

Installed /var/local/git/grpc/.eggs/six-1.10.0-py3.4.egg
Searching for sphinx_rtd_theme>=0.1.8

...

creating /var/local/git/grpc/.eggs/Sphinx-1.5a1-py3.4.egg
Extracting Sphinx-1.5a1-py3.4.egg to /var/local/git/grpc/.eggs

Installed /var/local/git/grpc/.eggs/Sphinx-1.5a1-py3.4.egg
Searching for protobuf>=3.0.0
Reading https://pypi.python.org/simple/protobuf/
Downloading https://pypi.python.org/packages/ee/5d/8547e2904eb65d921ca175dce68b0cf4b33e3f326d237009c6eeabfe60f7/protobuf-3.1.0.tar.gz#md5=595afcffc64069e1ecfca0229af739f4
Best match: protobuf 3.1.0
Processing protobuf-3.1.0.tar.gz
Writing /tmp/easy_install-zmqklh05/protobuf-3.1.0/setup.cfg
Running protobuf-3.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zmqklh05/protobuf-3.1.0/egg-dist-tmp-xgk1ua52
no previously-included directories found matching 'google/protobuf/internal/import_test_package'
warning: no previously-included files found matching 'google/protobuf/internal/*_pb2.py'
warning: no previously-included files found matching 'google/protobuf/internal/*_test.py'
warning: no previously-included files found matching 'google/protobuf/internal/*.proto'

...


warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Can't find required file: ../src/google/protobuf/descriptor.proto
Generating google/protobuf/descriptor_pb2.py...
Traceback (most recent call last):
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 246, in run_setup


...


File "/usr/lib/python3.4/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_py')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-zmqklh05/protobuf-3.1.0/setup.py", line 128, in run
    
  File "/tmp/easy_install-zmqklh05/protobuf-3.1.0/setup.py", line 66, in generate_proto
    _spawn_patch.monkeypatch_spawn()
SystemExit: -1

```

The version 3.1.0 of the protobuf package seem to have been uploaded some time earlier today: https://pypi.python.org/pypi/protobuf/3.1.0

**Comment by stanley-cheung** [comment]
Interop tests also start failing around the same time with the same error:

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/8479/console

**Comment by haberman** [comment]
It looks like the Python package may have gotten built without including the well-known types.

**Comment by xfxyjwf** [comment]
@TeBoring

Currently protobuf setup.py requires a "./setup.py build" step to generate well-known types before "./setup.py sdist upload". It seems the build step was skipped when uploading the source package.

We have to upload another one to fix this issue (using version number 3.1.0.post1).

**Comment by nicolasnoble** [comment]
Okay. This is precisely a major reason why I kept pushing for having an actual Jenkins job to automatically create these packages. Manual package building kept biting us in Ruby, and now apparently bites us in Python too. I'll be pushing for revisiting our decision on automatic package building again because of this.

**Comment by haberman** [comment]
No one is against using Jenkins for this. Everyone wants that. It's just
for a lack of time to implement it and a lack of familiarity with Jenkins.

**Comment by nicolasnoble** [comment]
That wasn't the last update I got :-) But that discussion is orthogonal to the problem, so I'll avoid hijacking this any further.

**Comment by nathanielmanistaatgoogle** [comment]
@teboring @haberman @xfxyjwf: should [the protobuf 3.1.0 package currently on PyPI be hidden](https://pypi.python.org/pypi/protobuf/3.1.0)? If so should it be hidden immediately or only after 3.1.0.post1 is published?

**Comment by TeBoring** [comment]
3.1.0.post1 published. 3.1.0 hided.

**Comment by stanley-cheung** [comment]
Jenkins tests are passing now.
