### ISSUE TITLE
Recursive stack corruption in PHP7

### ISSUE THREAD

**Issue by mdhheydari** [grpc/grpc#8250]
Hi,
I got a segmentation fault today while using pixelfedrations/vitess-pdo-php which uses gRPC as its communication backend. I tried to see what actually happens with gdb and I saw there is an endless recursion:
```
#0  0x00005555556d4ec0 in zif_count ()
#1  0x000055555578fe4b in dtrace_execute_internal ()
#2  0x000055555581cc54 in ZEND_DO_FCALL_SPEC_HANDLER ()
#3  0x00005555557de72b in execute_ex ()
#4  0x000055555578fd29 in dtrace_execute_ex ()
#5  0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#6  0x00005555557de72b in execute_ex ()
#7  0x000055555578fd29 in dtrace_execute_ex ()
#8  0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#9  0x00005555557de72b in execute_ex ()
#10 0x000055555578fd29 in dtrace_execute_ex ()
#11 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#12 0x00005555557de72b in execute_ex ()
#13 0x000055555578fd29 in dtrace_execute_ex ()
#14 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#15 0x00005555557de72b in execute_ex ()
#16 0x000055555578fd29 in dtrace_execute_ex ()
#17 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#18 0x00005555557de72b in execute_ex ()
#19 0x000055555578fd29 in dtrace_execute_ex ()
#20 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#21 0x00005555557de72b in execute_ex ()
#22 0x000055555578fd29 in dtrace_execute_ex ()
#23 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#24 0x00005555557de72b in execute_ex ()
#25 0x000055555578fd29 in dtrace_execute_ex ()
#26 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#27 0x00005555557de72b in execute_ex ()
#28 0x000055555578fd29 in dtrace_execute_ex ()
#29 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#30 0x00005555557de72b in execute_ex ()
#31 0x000055555578fd29 in dtrace_execute_ex ()
#32 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
.
.
.
#120735 0x00005555557de72b in execute_ex ()
#120736 0x000055555578fd29 in dtrace_execute_ex ()
#120737 0x000055555581c920 in ZEND_DO_FCALL_SPEC_HANDLER ()
#120738 0x00005555557de72b in execute_ex ()
#120739 0x000055555578fd29 in dtrace_execute_ex ()
#120740 0x000055555582889f in zend_execute ()
#120741 0x000055555579fa43 in zend_execute_scripts ()
#120742 0x0000555555740a48 in php_execute_script ()
#120743 0x000055555582a508 in do_cli ()
#120744 0x000055555562481a in main ()
```
I don't know how php native extensions work. Though I will continue trying to figure it out.

**Comment by stanley-cheung** [comment]
Can you share some code snippet that caused this?

**Comment by mdhheydari** [comment]
Sorry for false alarming, I found that there was a recursion in my code so it wasn't gRPC. Though PHP 7 has a bug that it doesn't keep track of recursive methods and it will crash if someone does it so.
