### ISSUE TITLE
Building gRPC Node sometimes fails for parallel builds 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8293]
We sometimes (20% of time?) see a failed node build when running  node opt and node dbg  in parallel (from two different workspaces).

Is there something we can do about this?

https://grpc-testing.appspot.com/job/gRPC_master_windows/33/console

```
gyp ERR! build error 
gyp ERR! stack Error: EBUSY: resource busy or locked, open 'C:\Users\jenkins\.node-gyp\4.2.6\Release\node.lib'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\jenkins\\workspace\\gRPC_master_windows\\workspace_node_windows_dbg\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\jenkins\\workspace\\gRPC_master_windows\\workspace_node_windows_dbg\\src\\node\\extension_binary"
gyp ERR! cwd C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\jenkins\\workspace\\gRPC_master_windows\\workspace_node_windows_dbg\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\jenkins\workspace\gRPC_master_windows\workspace_node_windows_dbg\src\node\extension_binary' (1)
```

**Comment by murgatroid99** [comment]
This should happen a lot less now that npm 5 has been released. And anecdotally, it seems to actually be happening less.

**Comment by sreecha** [comment]
Is this issue still relevant ?

**Comment by murgatroid99** [comment]
We've pretty much entirely redone the Node build, so this specific issue shouldn't be relevant anymore.
