### ISSUE TITLE
Cannot run Node dynamic_codegen example

### ISSUE THREAD

**Issue by aguerere** [grpc/grpc#8416]
Hi

This is my first time trying grpc. Just following the instructions in the `http://www.grpc.io/docs/quickstart/node.html#run-a-grpc-application` quickstart.
I am trying to run this on Ubuntu 16.04 64, and am getting this error:

```
beto@beto-T440p ~/temp/grpc/examples/node $ npm install
npm WARN package.json grpc-examples@0.1.0 No repository field.
npm WARN package.json grpc-examples@0.1.0 No license field.
-
> grpc@1.0.0 install /home/beto/temp/grpc/examples/node/node_modules/grpc
> node-pre-gyp install --fallback-to-build

[grpc] Success: "/home/beto/temp/grpc/examples/node/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote
minimist@1.2.0 node_modules/minimist

async@1.5.2 node_modules/async

google-protobuf@3.1.1 node_modules/google-protobuf

lodash@4.16.4 node_modules/lodash

grpc@1.0.0 node_modules/grpc
├── arguejs@0.2.3
├── nan@2.4.0
├── lodash@3.10.1
└── protobufjs@4.1.3 (ascli@1.0.0, bytebuffer@4.1.0, glob@5.0.15, yargs@3.32.0)
beto@beto-T440p ~/temp/grpc/examples/node $ node dynamic_codegen/greeter_server.js 
/home/beto/temp/grpc/examples/node/node_modules/grpc/src/node/index.js:124
  return loadObject(builder.ns, options);
                           ^
TypeError: Cannot read property 'ns' of null
    at Object.load (/home/beto/temp/grpc/examples/node/node_modules/grpc/src/node/index.js:124:28)
    at Object.<anonymous> (/home/beto/temp/grpc/examples/node/dynamic_codegen/greeter_server.js:37:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
beto@beto-T440p ~/temp/grpc/examples/node $ 
```

Am I missing something? This looks very straight forward and does not work for me. Have tried on node 0.12, 4.6.1 and 6.9.0, error is the same. Any clues? Thanks

**Comment by aguerere** [comment]
Nevermind, all this error means is that the .proto file is not found.
Solved it by indicating the correct path for my .proto file.
