### ISSUE TITLE
grpc server response data format error, client timeout not info response 

### ISSUE THREAD

**Issue by syzh** [grpc/grpc#8434]
// server error
// client request timeout, not info response
Error: .xxxx.core.Account#userID is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2440:35)
    at MessagePrototype.set (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:1877:28)
    at T.ProtoBuf.Reflect.FieldPrototype.verifyValue (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:3436:33)
    at MessagePrototype.set (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2443:59)
    at MessagePrototype.set (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/usr/src/app/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
    at serialize (/usr/src/app/node_modules/grpc/src/node/src/common.js:87:23)
    at sendUnaryResponse (/usr/src/app/node_modules/grpc/src/node/src/server.js:128:17)
    at sendUnaryData (/usr/src/app/node_modules/grpc/src/node/src/server.js:502:11)
    at /usr/src/app/src/rpc/handlers/AccountHandler.js:56:5
    at next (native)
    at step (/usr/src/app/src/rpc/handlers/AccountHandler.js:6:1)
    at /usr/src/app/src/rpc/handlers/AccountHandler.js:6:1

// proto file
message Account {
  uint64 id = 1 ;
  string phone = 2;
  AccountType type = 3;
  AvailableStatus status = 4;
  uint64 createdTime = 5;
  uint64 updatedTime = 6;
}

// data
account: {
  phone: '13943212179',
  type: 'aTeacher',
  status: 'available',
  userID: 19,
  updatedTime: 1476981523,
  createdTime: 1476981523 
}

**Comment by syzh** [comment]
fixed:
$diff node_modules/grpc/src/node/src/server.js node_modules/grpc/src/node/src/newserver.js
120a121
>   var message = serialize(value);
130d130
<   var message = serialize(value);
