### ISSUE TITLE
Linux/Mono: Deadline Exceeded when trying to connect to grpc service in 50% of cases

### ISSUE THREAD

**Issue by y-skindersky** [grpc/grpc#8475]
There are 3 grpc services:
- Server1 is written in Java and running on Widows
- Server2 is written in C# and running on Linux/Mono
- Credentials service which returns hosts/ports for Server1/Server2 which is running on the same host/port with Server2 in the same process

Use case:
- Client gets credentials using request to Credentials service
- Client connects to Server1
- Client connects to Server2 (we experienced Deadline Exceeded error in 50% of cases here)

It seems that 'Connect' request was not even written? Could anybody help me with finding the root of problem? Maybe it is related to my network connection configuration: I run Linux/Ubuntu on VMware virtual machine with NAT network adapter. Or maybe it is 'race condition' in grpc libs' code.

[connectClientErrorLog.txt](https://github.com/grpc/grpc/files/547178/connectClientErrorLog.txt)
[connectClientValidLog.txt](https://github.com/grpc/grpc/files/547180/connectClientValidLog.txt)
[connectServerLog.txt](https://github.com/grpc/grpc/files/547179/connectServerLog.txt)

**Comment by y-skindersky** [comment]
Maybe the same issue as here https://github.com/grpc/grpc/issues/6948 but I am not sure

**Comment by y-skindersky** [comment]
Server2 is also hangs while calling Server1:

"grpc 6 (cq 6)" tid=0x0x7f0f8f7fb700 this=0x0x7f0fbf5ab830 thread handle 0x11e3 state : not waiting owns ()
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.wrapper_native_0x7f0fbc66ea10 (Grpc.Core.Internal.CompletionQueueSafeHandle) <0xffffffff>
  at (wrapper delegate-invoke) <Module>.invoke_CompletionQueueEvent_CompletionQueueSafeHandle (Grpc.Core.Internal.CompletionQueueSafeHandle) <0xffffffff>
  at Grpc.Core.Internal.CompletionQueueSafeHandle.Next () <0x00030>
  at Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop (Grpc.Core.Internal.CompletionQueueSafeHandle) <0x0004b>
  at Grpc.Core.Internal.GrpcThreadPool/<>c__DisplayClass6.<CreateAndStartThread>b__5 () <0x00017>
  at System.Threading.ThreadHelper.ThreadStart_Context (object) <0x00099>
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x0016e>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00020>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) <0x00059>
  at System.Threading.ThreadHelper.ThreadStart () <0x0002e>
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0xffffffff>

**Comment by y-skindersky** [comment]
Server1 sometimes receives exceptions like below:

java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(native)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)[na:1.8.0_91]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)[na:1.8.0_91]
at sun.nio.ch.IOUtil.read(IOUtil.java:192)[na:1.8.0_91]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)[na:1.8.0_91]
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)[netty-all-4.1.5.Final.jar:4.1.5.Final]
at java.lang.Thread.run(Thread.java:745)[na:1.8.0_91]

Wireshark is also shows packets with RST flag in communication between Server2 and client
