### ISSUE TITLE
Unable to install grpc-tools on OSX using pip

### ISSUE THREAD

**Issue by shadowmint** [grpc/grpc#8507]
```
(env) Clank:client doug$ pip --version
pip 8.1.2 from /Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages (python 2.7)

(env) Clank:client doug$ pip install grpcio.tools
Collecting grpcio.tools
  Using cached grpcio_tools-1.0.0-cp27-cp27m-macosx_10_10_intel.whl
Requirement already satisfied (use --upgrade to upgrade): grpcio>=1.0.0 in ./env/lib/python2.7/site-packages (from grpcio.tools)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0 in ./env/lib/python2.7/site-packages (from grpcio.tools)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in ./env/lib/python2.7/site-packages (from grpcio>=1.0.0->grpcio.tools)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in ./env/lib/python2.7/site-packages (from grpcio>=1.0.0->grpcio.tools)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in ./env/lib/python2.7/site-packages (from grpcio>=1.0.0->grpcio.tools)
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./env/lib/python2.7/site-packages (from protobuf>=3.0.0->grpcio.tools)
Installing collected packages: grpcio.tools
Exception:
Traceback (most recent call last):
  File "/Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Users/doug/dev/clojure/learn/hello_microservice/client/env/lib/python2.7/site-packages/pip/wheel.py", line 348, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: grpcio.tools .dist-info directory not found
```

OSX version: 10.12.1 (16B2555)

**Comment by soltanmm-google** [comment]
I've never seen that syntax before (`pip install grpcio.tools` as opposed to `pip install grpcio-tools`). Using it on my Mac OS X results in a failure similar to yours, but using `pip install grpcio-tools` results in success. Could you please try `pip install grpcio-tools`?

**Comment by shadowmint** [comment]
Ah, my apologies, that is indeed my mistake. 

Strange, I also have no idea why pip doesn't return a normal 'Could not find a version that satisfies the requirement ...' error, but `pip install grpcio-tools` correctly installs and works.

Thanks very much!

**Comment by soltanmm-google** [comment]
Probably has to do with `pip` silently projecting out symbols to underscores, then uses the projections for file comparisons instead of the originals and the names within said files. I'unno.
