### ISSUE TITLE
call.waitForCancel() to detect client disconnection to clean up the ressources

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#8593]
Hello,
on **NODE.JS**,
here is my proto definition:
```protobuf
rpc GetStream(Empty) returns (stream Object) {}
```
and here is the method definition on the server side:
```javascript
function getStream(call) {
    const peer = call.getPeer();
    call.waitForCancel();
} 
```
when using ```call.waitForCancel();``` it throws:
```
{ Error: startBatch failed at Error (native) at ServerWritableStream.waitForCancel (.../node_modules/grpc/src/node/src/server.js:438:13) at Object.<anonymous> (.../src/server.grpc.js:47:12) at next (native) at step (.../src/server.grpc.js:227:191) at .../src/server.grpc.js:227:437 at Object.<anonymous> (.../src/server.grpc.js:227:99) at Object.getStream (.../src/server.grpc.js:76:18) at Object.wrapper [as func] (.../node_modules/lodash/lodash.js:4941:19) at .../node_modules/grpc/src/node/src/server.js:523:13 code: 8 }
```
**My problem:** I'd like to detect when a client disconnect, so I can clean up the ressources.
Aside question: Can I rely on the ```getPeer()``` method to uniquely identify a client?

Many thanks for you help!

**Comment by sulliwane** [comment]
Actually no need to call ```waitForCancel()```, directly listen for the **'cancelled'** event:
```javascript
call.on('cancelled', () => console.log('cancelled'));
```
