### ISSUE TITLE
Windows + Node 0.12 + grpc 1.0.1 failure

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#8609]
`@google-cloud/common` fails to install inside of an AppVeyor VM: https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-node/build/1.0.486/job/fq93q63thufoaea6#L1276

```
> grpc@1.0.1 install C:\projects\google-cloud-node\packages\common\node_modules\grpc
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v14-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@0.12.16 (node-v14 ABI) (falling back to source compile with node-gyp) 

...

gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\projects\google-cloud-node\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\projects\\google-cloud-node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects\\google-cloud-node\\packages\\common\\node_modules\\grpc\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\projects\\google-cloud-node\\packages\\common\\node_modules\\grpc\\src\\node\\extension_binary"
gyp ERR! cwd C:\projects\google-cloud-node\packages\common\node_modules\grpc
gyp ERR! node -v v0.12.16
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\projects\google-cloud-node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\google-cloud-node\packages\common\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\projects\google-cloud-node\packages\common\node_modules\grpc\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\google-cloud-node\packages\common\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1019:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "C:\\projects\\google-cloud-node\\packages\\common\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects\google-cloud-node\packages\common\node_modules\grpc
node-pre-gyp ERR! node -v v0.12.16
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\projects\google-cloud-node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\google-cloud-node\packages\common\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\projects\google-cloud-node\packages\common\node_modules\grpc\src\node\extension_binary' (1)
```

**Comment by murgatroid99** [comment]
This should work now. The Node Windows 32 bit build is still failing on Jenkins and I don't know why, so I built the binaries on my own machine and uploaded them.

**Comment by stephenplusplus** [comment]
Great, I re-ran the build, and it passed. Thanks!

**Comment by murgatroid99** [comment]
I'm going to keep this open as an issue for fixing our build.

**Comment by murgatroid99** [comment]
This failure is no longer occurring.
