### ISSUE TITLE
PHP rake pear fails on OSX

### ISSUE THREAD

**Issue by tbillington** [grpc/grpc#8669]
Getting an error when running `rake pear:package version=1.0` from http://www.grpc.io/docs/quickstart/php.html.

On OSX 10.11.4. There is no version of ruby specified in the quick start page, could this be the issue?

```bash
> rake pear:package version=1.0 --trace
** Invoke pear:package (first_time)
** Invoke doc:build (first_time)
** Execute doc:build
ronn -w -s toc -r5 --markdown man/*.ronn
     roff: man/protobuf-php.3
     html: man/protobuf-php.3.html                           +man,toc
 markdown: man/protobuf-php.3.markdown
     roff: man/protobuf-php.5
     html: man/protobuf-php.5.html                           +man,toc
 markdown: man/protobuf-php.5.markdown
     roff: man/protoc-gen-php.1
     html: man/protoc-gen-php.1.html                         +man,toc
 markdown: man/protoc-gen-php.1.markdown
** Invoke pear:xml (first_time)
** Invoke pear:clean (first_time)
** Execute pear:clean
Cleaning up...
rm -f library/package.xml
rm -f library/README.md
rm -f library/LICENSE
rm -f library/protoc-gen-php.php
rm -f library/protoc-gen-php.bat
** Execute pear:xml
** Execute pear:package
cp README.md library/README.md
cp LICENSE library/LICENSE
cp protoc-gen-php.php library/protoc-gen-php.php
cp protoc-gen-php.bat library/protoc-gen-php.bat
pear package -n library/package.xml
Rolling back...
** Execute pear:clean
Cleaning up...
rm -f library/package.xml
rm -f library/README.md
rm -f library/LICENSE
rm -f library/protoc-gen-php.php
rm -f library/protoc-gen-php.bat
rake aborted!
Command failed with status (127): [pear package -n library/package.xml...]
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/file_utils.rb:69:in `block in create_shell_runner'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/file_utils.rb:59:in `sh'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/trent/Protobuf-PHP/Rakefile:48:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => pear:package
```

**Comment by stanley-cheung** [comment]
Do you have `pear` installed? Run `pear version`? If not, you may want to try
```
$ curl -O http://pear.php.net/go-pear.phar
$ sudo php -d detect_unicode=0 go-pear.phar
```

**Comment by tbillington** [comment]
Ah, I installed it but it didn't get put in the path.

What part of that log gave away that pear wasn't found?

**Comment by stanley-cheung** [comment]
`Command failed with status (127): [pear package -n library/package.xml...]`
