### ISSUE TITLE
Python Server 1.0.0 raises serialisation exception when return grpc error

### ISSUE THREAD

**Issue by meomap** [grpc/grpc#8672]
I modified example hello world to return grpc error with `context.set_details` and `context.set_code`
```
diff --git a/examples/python/helloworld/greeter_server.py b/examples/python/helloworld/greeter_server.py
index 37d8bd4..dd32ea1 100644
--- a/examples/python/helloworld/greeter_server.py
+++ b/examples/python/helloworld/greeter_server.py
@@ -42,7 +42,9 @@ _ONE_DAY_IN_SECONDS = 60 * 60 * 24
 class Greeter(helloworld_pb2.GreeterServicer):
 
   def SayHello(self, request, context):
-    return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
+    context.set_code(grpc.StatusCode.PERMISSION_DENIED)
+    context.set_details('Not Allowed')
+    return
```

exception raised at server when run `python greeter_server.py`
```
ERROR:root:Exception serializing message!
Traceback (most recent call last):
  File "/Users/meomap/env/lib/python2.7/site-packages/grpc/_common.py", line 117, in _transform
    return transformer(message)
TypeError: unbound method SerializeToString() must be called with HelloReply instance as first argument (got NoneType instance instead)
```

though client still can receive grpc error with expected message 
```
Traceback (most recent call last):
  File "greeter_client.py", line 47, in <module>
    run()
  File "greeter_client.py", line 42, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/Users/meomap/env/lib/python2.7/site-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/Users/meomap/env/lib/python2.7/site-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Not Allowed)>
```

If I return an empty `helloworld_pb2.HelloReply()` message instead of return `None` then exception gone but I don't think it's reasonable to return an empty message everytime server want to raise an grpc error

**Comment by kpayson64** [comment]
There is a new method, ```abort()``` which terminates the handler with an exception when called.

This will be a cleaner solution to avoid this problem going forward (although we still need to support set_code)
https://grpc.io/grpc/python/grpc.html#grpc.ServicerContext.abort

**Comment by mehrdada** [comment]
For reference: discussed in https://github.com/grpc/grpc/issues/12826 and conclusion was introduction of `ServicerContext.abort` superseding `set_code` to terminate RPCs with non-OK status in https://github.com/grpc/grpc/pull/13667
