### ISSUE TITLE
Can't restart python server

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#8734]
```
>>> server_pool = logging_pool.pool(4)
>>> server = grpc.server(logging_pool)
>>> server.start()
>>> server.stop(0).wait()
True
>>> server.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/grpc2/tmp/local/lib/python2.7/site-packages/grpc/_server.py", line 750, in start
    _start(self._state)
  File "/workspace/grpc2/tmp/local/lib/python2.7/site-packages/grpc/_server.py", line 717, in _start
    state.server.start()
  File "src/python/grpcio/grpc/_cython/_cygrpc/server.pyx.pxi", line 95, in grpc._cython.cygrpc.Server.start (src/python/grpcio/grpc/_cython/cygrpc.c:20542)
    if self.is_started:
ValueError: the server has already started
```

**Comment by UnICorN21** [comment]
presumably because `is_started` in _cython not be set to false in the shutdown

**Comment by nathanielmanistaatgoogle** [comment]
Making servers restartable might be complicated by the current server lifecycle and the fact that servers get created, then ports get added to them, then they get started, and then they get stopped.

Should a server hang onto its ports after being stopped just in case it gets started again? I suspect not. Should a server remember on which ports it was serving before and attempt to serve on those ports again when it is restarted?

How painful today is working around the lack of server restarting? What use cases would server restarting benefit if implemented?

**Comment by kpayson64** [comment]
I don't think this feature is needed.  Feel free to close.
