### ISSUE TITLE
unable to load '@google-cloud/datastore'

### ISSUE THREAD

**Issue by kurapatijayaram** [grpc/grpc#8826]
Hi, when I am trying to load '@google-cloud/datastore' in electron app I am getting error as 

```sh
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/heresy/electron_apps/app_2/node_modules/grpc/src/node/extension_binary/grpc_node.node: undefined symbol: _ZN2v86Object14SetHiddenValueENS_5LocalINS_6StringEEENS1_INS_5ValueEEE
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/heresy/electron_apps/app_2/node_modules/grpc/src/node/src/grpc_extension.js:38:15)

```

**Comment by murgatroid99** [comment]
We don't yet support electron. Work on that is ongoing in pull request #8601.

**Comment by murgatroid99** [comment]
The npm module grpc@1.1.0-pre1 should now work on electron. Make sure that you follow the instructions in the electron docs for [installing native modules](http://electron.atom.io/docs/tutorial/using-native-node-modules/). You should be able to omit the line `export npm_config_build_from_source=true` to install the precompiled binary file for electron.
