### ISSUE TITLE
Error: Cannot find module '.../node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#8860]
_From @intralizee on November 26, 2016 0:8_

Hi,

I'm having an issue when using google-cloud on my server that is running Ubuntu.

#### Environment details

  - OS: Ubuntu 16.04.1 LTS
  - Node.js version: v7.2.0
  - npm version: 3.10.9
  - google-cloud-node version: 0.44.0

#### Steps to reproduce

  1. require `google-cloud`
  2. npm install
  3. node app.js

nom-debug.log contains:
```
89314 info lifecycle grpc@1.0.1~install: grpc@1.0.1
89315 verbose lifecycle grpc@1.0.1~install: unsafe-perm in lifecycle true
89316 verbose lifecycle grpc@1.0.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/intralizee/Psychedelices/node_modules/google-cloud/node_module$
89317 verbose lifecycle grpc@1.0.1~install: CWD: /home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc
89318 silly lifecycle grpc@1.0.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
89319 verbose stack Error: spawn ENOMEM
89319 verbose stack     at exports._errnoException (util.js:1022:11)
89319 verbose stack     at ChildProcess.spawn (internal/child_process.js:313:11)
89319 verbose stack     at exports.spawn (child_process.js:385:9)
89319 verbose stack     at spawn (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:21:13)
89319 verbose stack     at runCmd_ (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:247:14)
89319 verbose stack     at runCmd (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:208:5)
89319 verbose stack     at runPackageLifecycle (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:174:3)
89319 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
89319 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
89319 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
89320 verbose cwd /home/intralizee/Psychedelices
89321 error Linux 4.4.0-47-generic
89322 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
89323 error node v7.2.0
89324 error npm  v3.10.9
89325 error code ENOMEM
89326 error errno ENOMEM
89327 error syscall spawn
89328 error spawn ENOMEM
89329 error If you need help, you may report this error at:
89329 error     <https://github.com/npm/npm/issues>
89330 verbose exit [ 1, true ]
```

When running the server by node app.js the console outputs:
```
Error: Cannot find module '/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/src/client.js:55:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/index.js:45:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

If there is anything else I can provide, let me know and thanks for the hard work!

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1820_

**Comment by murgatroid99** [comment]
The top level error in that `npm-debug.log` dump is `Error: spawn ENOMEM`. This means that Node attempted to spawn a process to download or build the extension, but it failed because there was insufficient memory available. You need more RAM, or maybe you need to change some OS settings.

**Comment by intralizee** [comment]
Hi,

Thanks so much for the help and you're correct. 🙂

Stopping my vm and boosting the memory made it possible to build it successfully.
I should have been able to google that... I assumed it was something else because you guys just finished fixing building on OS X and I thought this may be somehow connected but with Ubuntu.

Anyway thanks again!

**Comment by algas** [comment]
I have same problem.
`.gitignore` has `src/node/extension_binary/`.
https://github.com/grpc/grpc/blob/master/.gitignore#L21

**Comment by murgatroid99** [comment]
Do you have the same error I mentioned? If so, have you tried the solution I suggested? If you have a different error, can you post it here or in a separate issue?

**Comment by algas** [comment]
@murgatroid99 It was not the same. It may be bugs of yarn.
https://github.com/yarnpkg/yarn/issues/853
yarn do not run postinstall.

**Comment by murgatroid99** [comment]
It's actually the `install` script that needs to be run, but it looks from that issue like yarn may not run that either. I would suggest running `yarn run install` to explicitly run the install script, and see if that successfully installs the extension.

**Comment by alex88** [comment]
I've having the same issue deploying a function to google cloud functions

```
Build failed: exit status 1

> grpc@1.2.0 install /workspace/node_modules/google-cloud/node_modules/grpc
> node-pre-gyp install --fallback-to-build

module.js:471
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/workspace/node_modules/google-cloud/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.0-71-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "rebuild" "--update-binary"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! grpc@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log
```

**Comment by isasameasb** [comment]
Cannot find module '/opt/gopath/src/CrossBorder_Remittance/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/gopath/src/CrossBorder_Remittance/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

can anyone give me a solution(I have tried all things posted in every relevant queries.Nothing seem to work :( )???

**Comment by gauravccloud** [comment]
Error: Cannot find module '/home/gaurav_sharma/abc/abc-abc/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gaurav_sharma/shopgroQA/shopgro-abc/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gaurav_sharma/shopgroQA/shopgro-superadmin/node_modules/grpc/src/node/src/client.js:55:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
Worker 27803 died with code: 1, and signal: null
Starting a new worker
Worker 27809 died with code: 1, and signal: null
Starting a new worker
Worker 27815 is online
Worker 27816 is online

Anybody has solution for it ??

**Comment by narendeveloper1** [comment]
I fixed the error. I think it was because I had Installed the @Google-Cloud module with sudo. So I sudo uninstalled it then reinstalled it without sudo and it worked.

**Comment by gauravccloud** [comment]
Yes, it's a version problem after reinstalling it works for me.

**Comment by oreporan** [comment]
only `npm rebuild` worked for me

**Comment by kirillgroshkov** [comment]
same issue when running on AWS! Any idea how to do `npm rebuild`?

**Comment by mboughaba** [comment]
`npm rebuild` and `npm install` didn't work for me either. `yarn install` was the one that solved the issue for me.
