### ISSUE TITLE
Ruby artifact building is broken

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9031]
```
rake-compiler-dock bash -c "CPPFLAGS=\"-D_WIN32_WINNT=0x600 -DUNICODE -D_UNICODE -Wno-unused-variable -Wno-unused-result\" LDFLAGS=-static SYSTEM=MINGW32 EMBED_ZLIB=true BUILDDIR=/tmp V=0  CC=x86_64-w64-mingw32-gcc LD=x86_64-w64-mingw32-gcc  make -j /tmp/libs/opt/grpc-1.dll && x86_64-w64-mingw32-strip -x -S /tmp/libs/opt/grpc-1.dll && cp /tmp/libs/opt/grpc-1.dll grpc_c.64.ruby"
make: *** No rule to make target `/tmp/libs/opt/grpc-1.dll'.  Stop.
rake aborted!
Command failed with status (2): [docker run -v /home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux:/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux -e UID\=1012 -e GID\=1012 -e USER\=jenkins -e GROUP\=jenkins -e ftp_proxy\= -e http_proxy\= -e https_proxy\= -e RCD_HOST_RUBY_PLATFORM\=x86_64-linux -e RCD_HOST_RUBY_VERSION\=2.2.1 -e RCD_IMAGE\=grpc/rake-compiler-dock:095ffe190d7dca8eba8d141fd5862280997e6f55 -w /home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux --rm -i grpc/rake-compiler-dock:095ffe190d7dca8eba8d141fd5862280997e6f55 runas sigfw bash -c CPPFLAGS\=\"-D_WIN32_WINNT\=0x600\ -DUNICODE\ -D_UNICODE\ -Wno-unused-variable\ -Wno-unused-result\"\ LDFLAGS\=-static\ SYSTEM\=MINGW32\ EMBED_ZLIB\=true\ BUILDDIR\=/tmp\ V\=0\ \ CC\=x86_64-w64-mingw32-gcc\ LD\=x86_64-w64-mingw32-gcc\ \ make\ -j\ /tmp/libs/opt/grpc-1.dll\ \&\&\ x86_64-w64-mingw32-strip\ -x\ -S\ /tmp/libs/opt/grpc-1.dll\ \&\&\ cp\ /tmp/libs/opt/grpc-1.dll\ grpc_c.64.ruby]
/home/jenkins/.rvm/gems/ruby-2.2.1/gems/rake-compiler-dock-0.5.3/lib/rake_compiler_dock/starter.rb:81:in `exec'
/home/jenkins/.rvm/gems/ruby-2.2.1/gems/rake-compiler-dock-0.5.3/lib/rake_compiler_dock/starter.rb:15:in `sh'
/home/jenkins/.rvm/gems/ruby-2.2.1/gems/rake-compiler-dock-0.5.3/lib/rake_compiler_dock.rb:36:in `sh'
tools/distrib/docker_for_windows.rb:56:in `docker_for_windows'
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/Rakefile:94:in `block (2 levels) in <top (required)>'
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/Rakefile:91:in `each'
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/Rakefile:91:in `block in <top (required)>'
/home/jenkins/workspace/gRPC_build_artifacts/architecture/x64/language/ruby/platform/linux/Rakefile:110:in `block in <top (required)>'
/home/jenkins/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/jenkins/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => gem:native
(See full trace by running task with --trace)
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/2331/architecture=x64,language=ruby,platform=linux/console

**Comment by apolcyn** [comment]
this looks like the issue seen in https://github.com/grpc/grpc/issues/8318 and https://github.com/grpc/grpc/issues/8124, ok to move it there?
