### ISSUE TITLE
tests.cloud_to_cloud:node:node_server:status_code_and_message

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9048]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10012/testReport/junit/(root)/tests/cloud_to_cloud_node_node_server_status_code_and_message/

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: 14 === 2
    at ClientDuplexStream.<anonymous> (/var/local/git/grpc/src/node/interop/interop_client.js:369:12)
    at emitOne (events.js:77:13)
    at ClientDuplexStream.emit (events.js:169:7)
    at ClientDuplexStream._emitStatusIfDone (/var/local/git/grpc/src/node/src/client.js:187:10)
    at ClientDuplexStream._readsDone (/var/local/git/grpc/src/node/src/client.js:158:8)
    at readCallback (/var/local/git/grpc/src/node/src/client.js:217:12)

**Comment by dgquintas** [comment]
It seems we haven't seen this in a while. @murgatroid99 can you verify and close if appropriate?
