### ISSUE TITLE
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 1385

### ISSUE THREAD

**Issue by sunysen** [grpc/grpc#9083]
```

java version: 1.8.0_45
grpc version:1.0.2
system version:CentOS Linux release 7.1.1503 (Core)

Dec 13, 2016 6:29:27 PM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 1385
at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:127)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:556)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:176)
at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:411)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:245)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:155)
at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:335)
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:395)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
at java.lang.Thread.run(Thread.java:745)

```

**Comment by grzegorz-zur** [comment]
You get this stacktrace when you message is over size limit.

**Comment by shanghai-Jerry** [comment]
@grzegorz-zur  what about this? [java.lang.NoSuchMethodError: io.netty.handler.codec.http.HttpResponseStatus.codeAsText()Lio/netty/util/AsciiString;
	at io.netty.handler.codec.http2.Http2ConnectionHandler.<clinit>(Http2ConnectionHandler.java:69)
	at io.grpc.netty.NettyServerTransport.createHandler(NettyServerTransport.java:154)
	at io.grpc.netty.NettyServerTransport.start(NettyServerTransport.java:99)
	at io.grpc.netty.NettyServer$1.initChannel(NettyServer.java:175)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:133)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:119)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)](url)

**Comment by shanghai-Jerry** [comment]
@grzegorz-zur  what about this exception? `java.lang.NoSuchMethodError: io.netty.handler.codec.http.HttpResponseStatus.codeAsText()Lio/netty/util/AsciiString;
	at io.netty.handler.codec.http2.Http2ConnectionHandler.<clinit>(Http2ConnectionHandler.java:69)
	at io.grpc.netty.NettyServerTransport.createHandler(NettyServerTransport.java:154)
	at io.grpc.netty.NettyServerTransport.start(NettyServerTransport.java:99)
	at io.grpc.netty.NettyServer$1.initChannel(NettyServer.java:175)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:133)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:119)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by hzariv** [comment]
We also been seeing a lot of these warnings. Could someone shed some light on what is causing this?

2017-10-04 19:21:08,485 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5
--
2017-10-04 19:21:08,488 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5
--
2017-10-04 19:21:08,489 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5
--
2017-10-04 19:53:07,139 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 145
--
2017-10-04 19:53:07,169 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 145
--
2017-10-05 07:38:08,033 WARN [ForkJoinPool-1-worker-1]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 123

**Comment by ejona86** [comment]
This was opened against the wrong repository. Closing in favor of grpc/grpc-java#3548 which seems to be the same problem.
