### ISSUE TITLE
Python interop: AttributeError: 'module' object has no attribute 'AuthMetadataPlugin'

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9099]
Eg:

```
START: cloud_to_cloud:c++:ruby_server:large_unary
running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 121, in <module>
    test_runner=TEST_RUNNER,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 201, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 215, in run_client
    from tests.interop import client
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 36, in <module>
    from grpc.beta import implementations
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/beta/implementations.py", line 39, in <module>
    from grpc import _auth
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_auth.py", line 43, in <module>
    class GoogleCallCredentials(grpc.AuthMetadataPlugin):
AttributeError: 'module' object has no attribute 'AuthMetadataPlugin'

FAILED: cloud_to_cloud:python:ruby_server:cancel_after_first_response [ret=1, pid=20520]
```

Full output [here](https://gist.github.com/dgquintas/daaaafbb600c891e0045e111cc54240a) (from https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10090/console)

**Comment by soltanmm-google** [comment]
Well, running manually produces no errors.

```
atash@grpc-canary-interop3:~/grpc$ ./tools/run_tests/run_interop_tests.py -l python -s python --use_docker
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_python [time=602.9sec; retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_python
PASSED: cloud_to_cloud:python:python_server:large_unary [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:empty_unary [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:cancel_after_begin [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:server_streaming [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:empty_stream [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:custom_metadata [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:timeout_on_sleeping_server [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:ping_pong [time=2.9sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:cancel_after_first_response [time=3.1sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:client_streaming [time=3.3sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:status_code_and_message [time=3.5sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:unimplemented_service [time=3.8sec; retries=0:0]
PASSED: cloud_to_cloud:python:python_server:unimplemented_method [time=3.9sec; retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_python:f98f5b18-69a1-48e9-ba59-4b9a9b31bde2
atash@grpc-canary-interop3:~/grpc$ git branch
  jenkins-docker
* master
  praytell-babbage-if-you-do-the-wrong-thing-will-it-still-do-the-right-thing
  v1.0.x
```

As suggested offline, this might be some sort of caching problem. Will need to chase down whoever it is that needs to be chased down to figure out how to sneak dystopian forget-everything pills into Jenkins' diet.

**Comment by dgquintas** [comment]
Looking at [the history](https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10116/testReport/history/), it's happening intermittently, which to me looks like some Jenkins workers are fubar.

**Comment by soltanmm-google** [comment]
The last several instances of this failure (I'unno the entire history) appear to be on `grpc-canary-interop2`...

**Comment by apolcyn** [comment]
A possible different error but in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11181/console the python interop image just timed out while building.
```
START: /var/local/git/grpc/tools/run_tests/helper_scripts/build_python.sh
WAITING: 1 queued, 1 jobs running, 0 complete, 0 failed

TIMEOUT: build_docker_python [pid=28192]
```
pr #9548 against master

**Comment by nathanielmanistaatgoogle** [comment]
Closing; we don't seem to have seen `AttributeError: 'module' object has no attribute 'AuthMetadataPlugin'` in some time.

**Comment by naveensinghal** [comment]
@nathanielmanistaatgoogle @dgquintas 

Getting the exact same error on my Ubuntu System. Any resolution on how to resolve this please ?
(Exact same code worked till yesterday)


Thanks,

**Comment by nathanielmanistaatgoogle** [comment]
@naveensinghal: well, what happened yesterday? And are you able to undo it? More largely: which version of Ubuntu? Are you using virtual environments when working with Python? What minimal sequence of commands demonstrates the problem? If you have access to a brand-new virtual machine, are you able to describe how to demonstrate the problem from a fresh Ubuntu installation?

**Comment by naveensinghal** [comment]
Looks like an intermittant issue which seems to be resolved now. 
Not sure about the exact cause though.

Anyways, Thanks @nathanielmanistaatgoogle

**Comment by Hazarapet** [comment]
+
