### ISSUE TITLE
tests.cloud_to_cloud:node:node_server:custom_metadata is flaky

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9166]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connect Failed
    at ClientDuplexStream._emitStatusIfDone (/var/local/git/grpc/src/node/src/client.js:190:19)
    at ClientDuplexStream._readsDone (/var/local/git/grpc/src/node/src/client.js:158:8)
    at readCallback (/var/local/git/grpc/src/node/src/client.js:218:12)

https://grpc-testing.appspot.com/job/gRPC_interop_master/9712/testReport/(root)/tests/cloud_to_cloud_node_node_server_custom_metadata/

**Comment by adelez** [comment]
Probably a dup of #9167
