### ISSUE TITLE
tests.cloud_to_cloud:node:node_server:server_streaming, client_streaming and custom_metadata are flaky

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9167]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connect Failed
    at ClientReadableStream._emitStatusIfDone (/var/local/git/grpc/src/node/src/client.js:190:19)
    at ClientReadableStream._readsDone (/var/local/git/grpc/src/node/src/client.js:158:8)
    at readCallback (/var/local/git/grpc/src/node/src/client.js:218:12)

https://grpc-testing.appspot.com/job/gRPC_interop_master/9712/testReport/(root)/tests/cloud_to_cloud_node_node_server_server_streaming/

**Comment by adelez** [comment]
You can see all three failures in https://grpc-testing.appspot.com/job/gRPC_interop_master/9712/testReport/. They all have connection failures.

**Comment by dgquintas** [comment]
@murgatroid99 can this be closed?

**Comment by dgquintas** [comment]
Not seen in two months, closing.
