### ISSUE TITLE
Fetch failure from Git trying to start tests

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9250]
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/8244/console
https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_c/1002/console

```
GitHub pull request #9243 of commit 17dfaf1a6e6dfe03b9fbcfff4f2101fcc77a22cc, no merge conflicts.
Setting status of 17dfaf1a6e6dfe03b9fbcfff4f2101fcc77a22cc to PENDING with url https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/8244/ and message: 'Build started sha1 is merged.'
Using context: gRPC_performance_pull_requests
Building remotely on grpc-performance-gce2 (performance) in workspace /home/jenkins/workspace/gRPC_performance_pull_requests
[WS-CLEANUP] Deleting project workspace...
Disk space threshold is set to :50Gb
Checking disk space Now 
Total Disk Space Available is: 258Gb
 Node Name: grpc-performance-gce2
Running Prebuild steps
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/grpc/grpc.git
 > git init /home/jenkins/workspace/gRPC_performance_pull_requests # timeout=10
Fetching upstream changes from https://github.com/grpc/grpc.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/grpc/grpc.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/grpc/grpc.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/grpc/grpc.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/grpc/grpc.git
 > git fetch --tags --progress https://github.com/grpc/grpc.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/grpc/grpc.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:797)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1051)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1082)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/grpc/grpc.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1752)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1495)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:64)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:315)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to grpc-performance-gce2(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1433)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:797)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy54.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:795)
	... 11 more
ERROR: null
[htmlpublisher] Archiving HTML reports...
```

**Comment by matt-kwong** [comment]
I changed Jenkins to retry pulling from GitHub up to 3 times when there's an error like this. I'd like to see this failure again to see if Jenkins handles it well with the new setting.

**Comment by dgquintas** [comment]
Seems to have helped, issue doesn't seem to have recurred. Closing.
