### ISSUE TITLE
java:jwt_token_creds failing

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9497]
cloud_to_prod_auth:default:java:jwt_token_creds failed in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10969/consoleFull

```
Jan 29, 2017 5:01:58 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 69:61:e5:0d:72:6b:0b:d6
Shutting down
Exception in thread "main" io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
	at io.grpc.testing.integration.AbstractInteropTest.jwtTokenCreds(AbstractInteropTest.java:1184)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:242)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:194)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:78)
Jan 29, 2017 5:01:59 AM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [io.grpc.internal.ManagedChannelImpl-1] Terminated

FAILED: cloud_to_prod_auth:default:java:jwt_token_creds [ret=1, pid=22006]
```

**Comment by dgquintas** [comment]
Seen again #9508

**Comment by jtattermusch** [comment]
Seen again: https://github.com/grpc/grpc/pull/9390

**Comment by dgquintas** [comment]
@ejona86 any ideas?

**Comment by murgatroid99** [comment]
I didn't realize that this issue existed so I also filed it at grpc/grpc-java#2680

**Comment by dgquintas** [comment]
@ejona86 has actually found the issue. fix coming up
