### ISSUE TITLE
objc_macos_dbg.objc-tests failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9550]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2376/console

```
# xcodebuild is very verbose. We filter its output and tell Bash to fail if any
# element of the pipe fails.
# TODO(jcanizales): Use xctool instead? Issue #2540.
set -o pipefail
XCODEBUILD_FILTER='(^===|^\*\*|\bfatal\b|\berror\b|\bwarning\b|\bfail)'
xcodebuild \
    -workspace Tests.xcworkspace \
    -scheme AllTests \
    -destination name="iPhone 6" \
    test \
    | egrep "$XCODEBUILD_FILTER" \
    | egrep -v "(GPBDictionary|GPBArray)" -
I0201 13:49:33.300510000 140735272424192 server_builder.cc:247] Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
I0201 13:49:33.300709000 140735272424192 server_builder.cc:247] Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
2017-02-01 13:49:37.597 xcodebuild[12847:81621011] [MT] IDETestOperationsObserverDebug: (5F5BD5FC-E54A-482D-8316-453D7B3428A6) Beginning test session 5F5BD5FC-E54A-482D-8316-453D7B3428A6 with Xcode 7C1002 on target <DVTiPhoneSimulator: 0x7fcedacbc8b0> {
		SimDevice: SimDevice : iPhone 6 (989B8DD9-386D-4B8D-8AC7-39A4631E4D16) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 9.2 (13C75) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 }
} (9.2 (13C75))
E0201 13:51:39.403680000 4321468416 call.c:793] validate_metadata: {"created":"@1485985899.403654000","description":"Illegal header value","file":"src/core/lib/surface/validate_metadata.c","file_line":55,"offset":59,"raw_bytes":"46 6f 6f 20 67 72 70 63 2d 6f 62 6a 63 2f 31 2e 30 2e 32 20 67 72 70 63 2d 63 2f 33 2e 30 2e 30 2d 64 65 76 20 28 69 6f 73 3b 20 63 68 74 74 70 32 3b 20 67 72 65 65 6e 29 3f 60 89 dd 7f 'Foo grpc-objc/1.0.2 grpc-c/3.0.0-dev (ios; chttp2; green)?`...'"}
E0201 13:51:39.403704000 4321468416 server_cc.cc:564] assertion failed: GRPC_CALL_OK == result
E0201 13:51:56.857814000 4432527360 chttp2_server.c:126] Handshaking failed: {"created":"@1485985916.857692000","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.c","file_line":238,"referenced_errors":[{"created":"@1485985916.857162000","description":"Socket closed","fd":11,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":250,"target_address":"ipv6:[::1]:53307"}]}
** TEST FAILED **
```

**Comment by muxi** [comment]
Looked into this. Looks like some internal problem with interop server; it failed to resolve the metadata to be sent for some unknown reason. Got a debug that caught where it happened:
```
Process 59130 launched: '../../../bins/dbg/interop_server' (x86_64)
I0202 17:16:36.623577000 140736153174976 server_builder.cc:247] Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
E0202 17:16:39.483448000 123145420587008 call.c:807] validate_metadata: {"created":"@1486084599.483423000","description":"Illegal header value","file":"src/core/lib/surface/validate_metadata.c","file_line":55,"offset":65,"raw_bytes":"46 6f 6f 20 67 72 70 63 2d 6f 62 6a 63 2f 31 2e 30 2e 32 20 67 72 70 63 2d 63 2f 33 2e 30 2e 30 2d 64 65 76 20 28 69 6f 73 3b 20 63 68 74 74 70 32 3b 20 67 72 65 65 6e 29 31 30 30 30 38 62 33 40 17 0d 'Foo grpc-objc/1.0.2 grpc-c/3.0.0-dev (ios; chttp2; green)10008b3@..'"}
```
The code location:
```
additional_metadata_count=0) + 335 at call.c:808
   805 	               !GRPC_LOG_IF_ERROR(
   806 	                   "validate_metadata",
   807 	                   grpc_validate_header_nonbin_value_is_legal(md->value))) {
-> 808 	      break;
   809 	    }
   810 	    l->md = grpc_mdelem_from_grpc_metadata(exec_ctx, (grpc_metadata *)md);
   811 	  }
```
Stack backtrace:
```
(lldb) bt
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
* thread #2: tid = 0x54074, 0x000000010008384f interop_server`prepare_application_metadata(exec_ctx=0x00007000070cb498, call=0x0000000101002000, count=1, metadata=0x00000001022001b0, is_trailing=0, prepend_extra_metadata=0, additional_metadata=0x00007000070cb3b0, additional_metadata_count=0) + 335 at call.c:808, stop reason = breakpoint 2.1
  * frame #0: 0x000000010008384f interop_server`prepare_application_metadata(exec_ctx=0x00007000070cb498, call=0x0000000101002000, count=1, metadata=0x00000001022001b0, is_trailing=0, prepend_extra_metadata=0, additional_metadata=0x00007000070cb3b0, additional_metadata_count=0) + 335 at call.c:808
    frame #1: 0x0000000100081f16 interop_server`call_start_batch(exec_ctx=0x00007000070cb498, call=0x0000000101002000, ops=0x00007000070cb540, nops=3, notify_tag=0x00007000070cb8a8, is_notify_tag_closure=0) + 1046 at call.c:1405
    frame #2: 0x0000000100081ae2 interop_server`grpc_call_start_batch(call=0x0000000101002000, ops=0x00007000070cb540, nops=3, tag=0x00007000070cb8a8, reserved=0x0000000000000000) + 210 at call.c:1676
    frame #3: 0x00000001000c61ad interop_server`grpc::Server::PerformOpsOnCall(this=0x0000000100906090, ops=0x00007000070cb8a8, call=0x00007000070cbae0) + 157 at server_cc.cc:563
    frame #4: 0x0000000100048eef interop_server`grpc::Call::PerformOps(this=0x00007000070cbae0, ops=0x00007000070cb8a8) + 47 at call.h:624
    frame #5: 0x0000000100031a9c interop_server`grpc::RpcMethodHandler<grpc::testing::TestService::Service, grpc::testing::Empty, grpc::testing::Empty>::RunHandler(this=0x00000001009040b0, param=0x00007000070cba30) + 780 at method_handler_impl.h:75
    frame #6: 0x00000001000ca3c9 interop_server`grpc::Server::SyncRequest::CallData::Run(this=0x00007000070cbac8, global_callbacks=ptr = 0x100905990 strong=4 weak=1) + 201 at server_cc.cc:211
    frame #7: 0x00000001000c9edb interop_server`grpc::Server::SyncRequestThreadManager::DoWork(this=0x0000000100906190, tag=0x0000000100906580, ok=true) + 459 at server_cc.cc:297
    frame #8: 0x00000001000d18e2 interop_server`grpc::ThreadManager::MainWorkLoop(this=0x0000000100906190) + 306 at thread_manager.cc:172
    frame #9: 0x00000001000d175f interop_server`grpc::ThreadManager::WorkerThread::Run(this=0x0000000100907760) + 31 at thread_manager.cc:48
    frame #10: 0x00000001000d3614 interop_server`void* std::__1::__thread_proxy<std::__1::tuple<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*> >(void*) [inlined] decltype(__f=0x0000000100907fe0, __a0=0x0000000100907ff0)).*fp(std::__1::forward<>(fp1))) std::__1::__invoke<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*, void>(void (grpc::ThreadManager::WorkerThread::*&&)(), grpc::ThreadManager::WorkerThread*&&) + 127 at __functional_base:383
    frame #11: 0x00000001000d3595 interop_server`void* std::__1::__thread_proxy<std::__1::tuple<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*> >(void*) [inlined] void std::__1::__thread_execute<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*, 1ul>(__t=0x0000000100907fe0)(), grpc::ThreadManager::WorkerThread*>&, std::__1::__tuple_indices<1ul>) + 40 at thread:337
    frame #12: 0x00000001000d356d interop_server`void* std::__1::__thread_proxy<std::__1::tuple<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*> >(__vp=0x0000000100907fe0) + 365 at thread:347
    frame #13: 0x00007fffa7a76aab libsystem_pthread.dylib`_pthread_body + 180
    frame #14: 0x00007fffa7a769f7 libsystem_pthread.dylib`_pthread_start + 286
    frame #15: 0x00007fffa7a761fd libsystem_pthread.dylib`thread_start + 13
```

**Comment by dgquintas** [comment]
The C++ interop server seems to be trying to send an invalid (and
nonsensical) metadata entry "Foo grpc-objc/1.0.2 grpc-c/3.0.0-dev (ios;
chttp2; green)10008b3@.." which not only does not correspond to a C++
server, but also contains invalid bytes at the end (reason why the
validation call failed). It smells like memory corruption in the interop
server. Running it under asan will probably help.

**Comment by muxi** [comment]
Asan logs:
```
==77422==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c000005ff9 at pc 0x00010750445d bp 0x700009889630 sp 0x700009888df0
READ of size 58 at 0x60c000005ff9 thread T2
    #0 0x10750445c in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib+0x4345c)
    #1 0x106da2d94 in std::__1::char_traits<char>::length(char const*) string:640
    #2 0x105f8e828 in MaybeEchoMetadata(grpc::ServerContext*) string:2005
    #3 0x105f93810 in TestServiceImpl::EmptyCall(grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*) interop_server.cc:155
    #4 0x105f437db in grpc::Status std::__1::__invoke_void_return_wrapper<grpc::Status>::__call<std::__1::__mem_fn<grpc::Status (grpc::testing::TestService::Service::*)(grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*)>&, grpc::testing::TestService::Service*, grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*>(std::__1::__mem_fn<grpc::Status (grpc::testing::TestService::Service::*)(grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*)>&&&, grpc::testing::TestService::Service*&&, grpc::ServerContext*&&, grpc::testing::Empty const*&&, grpc::testing::Empty*&&) __functional_base:383
    #5 0x105f43003 in std::__1::__function::__func<std::__1::__mem_fn<grpc::Status (grpc::testing::TestService::Service::*)(grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*)>, std::__1::allocator<std::__1::__mem_fn<grpc::Status (grpc::testing::TestService::Service::*)(grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*)> >, grpc::Status (grpc::testing::TestService::Service*, grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*)>::operator()(grpc::testing::TestService::Service*&&, grpc::ServerContext*&&, grpc::testing::Empty const*&&, grpc::testing::Empty*&&) functional:1437
    #6 0x105f45852 in std::__1::function<grpc::Status (grpc::testing::TestService::Service*, grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*)>::operator()(grpc::testing::TestService::Service*, grpc::ServerContext*, grpc::testing::Empty const*, grpc::testing::Empty*) const functional:1817
    #7 0x105f44276 in grpc::RpcMethodHandler<grpc::testing::TestService::Service, grpc::testing::Empty, grpc::testing::Empty>::RunHandler(grpc::MethodHandler::HandlerParameter const&) method_handler_impl.h:59
    #8 0x1061c80ff in grpc::Server::SyncRequest::CallData::Run(std::__1::shared_ptr<grpc::Server::GlobalCallbacks>) server_cc.cc:211
    #9 0x1061c65a4 in grpc::Server::SyncRequestThreadManager::DoWork(void*, bool) server_cc.cc:297
    #10 0x1061ecb0a in grpc::ThreadManager::MainWorkLoop() thread_manager.cc:172
    #11 0x1061ec1fe in grpc::ThreadManager::WorkerThread::Run() thread_manager.cc:48
    #12 0x1061f5210 in void* std::__1::__thread_proxy<std::__1::tuple<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*> >(void*) __functional_base:383
    #13 0x7fffa7a76aaa in _pthread_body (libsystem_pthread.dylib+0x3aaa)
    #14 0x7fffa7a769f6 in _pthread_start (libsystem_pthread.dylib+0x39f6)
    #15 0x7fffa7a761fc in thread_start (libsystem_pthread.dylib+0x31fc)

0x60c000005ff9 is located 0 bytes to the right of 121-byte region [0x60c000005f80,0x60c000005ff9)
allocated by thread T1 here:
    #0 0x1075099c0 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib+0x489c0)
    #1 0x1061fc757 in gpr_malloc alloc.c:58
    #2 0x10608ebd1 in grpc_slice_intern slice_intern.c:258
    #3 0x1062d915a in take_string hpack_parser.c:709
    #4 0x1062d9a2e in finish_lithdr_incidx_v hpack_parser.c:871
    #5 0x1062d1e37 in parse_next hpack_parser.c:732
    #6 0x1062d5118 in begin_parse_string hpack_parser.c:1521
    #7 0x1062d49aa in parse_value_string hpack_parser.c:1566
    #8 0x1062d9831 in parse_value_string_with_literal_key hpack_parser.c:1582
    #9 0x1062d1e37 in parse_next hpack_parser.c:732
    #10 0x1062d43af in parse_string_prefix hpack_parser.c:1298
    #11 0x1062d1e37 in parse_next hpack_parser.c:732
    #12 0x1062d5118 in begin_parse_string hpack_parser.c:1521
    #13 0x1062d977a in parse_key_string hpack_parser.c:1536
    #14 0x1062d1e37 in parse_next hpack_parser.c:732
    #15 0x1062d43af in parse_string_prefix hpack_parser.c:1298
    #16 0x1062cf28f in parse_lithdr_incidx_v hpack_parser.c:914
    #17 0x1062ccda3 in parse_begin hpack_parser.c:745
    #18 0x1062d9b9c in finish_lithdr_incidx_v hpack_parser.c:874
    #19 0x1062d1e37 in parse_next hpack_parser.c:732
    #20 0x1062d5118 in begin_parse_string hpack_parser.c:1521
    #21 0x1062d49aa in parse_value_string hpack_parser.c:1566
    #22 0x1062d9831 in parse_value_string_with_literal_key hpack_parser.c:1582
    #23 0x1062d1e37 in parse_next hpack_parser.c:732
    #24 0x1062d43af in parse_string_prefix hpack_parser.c:1298
    #25 0x1062d1e37 in parse_next hpack_parser.c:732
    #26 0x1062d5118 in begin_parse_string hpack_parser.c:1521
    #27 0x1062d977a in parse_key_string hpack_parser.c:1536
    #28 0x1062d1e37 in parse_next hpack_parser.c:732
    #29 0x1062d43af in parse_string_prefix hpack_parser.c:1298

Thread T2 created by T1 here:
    #0 0x1074fff99 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib+0x3ef99)
    #1 0x1061f4374 in std::__1::thread::thread<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*, void>(void (grpc::ThreadManager::WorkerThread::*&&)(), grpc::ThreadManager::WorkerThread*&&) thread:359
    #2 0x1061f18bd in std::__1::thread::thread<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*, void>(void (grpc::ThreadManager::WorkerThread::*&&)(), grpc::ThreadManager::WorkerThread*&&) thread:355
    #3 0x1061ec10f in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*) thread_manager.cc:45
    #4 0x1061ec28d in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*) thread_manager.cc:45
    #5 0x1061f0d8d in grpc::ThreadManager::MaybeCreatePoller() thread_manager.cc:137
    #6 0x1061ec9f0 in grpc::ThreadManager::MainWorkLoop() thread_manager.cc:171
    #7 0x1061ec1fe in grpc::ThreadManager::WorkerThread::Run() thread_manager.cc:48
    #8 0x1061f5210 in void* std::__1::__thread_proxy<std::__1::tuple<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*> >(void*) __functional_base:383
    #9 0x7fffa7a76aaa in _pthread_body (libsystem_pthread.dylib+0x3aaa)
    #10 0x7fffa7a769f6 in _pthread_start (libsystem_pthread.dylib+0x39f6)
    #11 0x7fffa7a761fc in thread_start (libsystem_pthread.dylib+0x31fc)

Thread T1 created by T0 here:
    #0 0x1074fff99 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib+0x3ef99)
    #1 0x1061f4374 in std::__1::thread::thread<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*, void>(void (grpc::ThreadManager::WorkerThread::*&&)(), grpc::ThreadManager::WorkerThread*&&) thread:359
    #2 0x1061f18bd in std::__1::thread::thread<void (grpc::ThreadManager::WorkerThread::*)(), grpc::ThreadManager::WorkerThread*, void>(void (grpc::ThreadManager::WorkerThread::*&&)(), grpc::ThreadManager::WorkerThread*&&) thread:355
    #3 0x1061ec10f in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*) thread_manager.cc:45
    #4 0x1061ec28d in grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*) thread_manager.cc:45
    #5 0x1061f0d8d in grpc::ThreadManager::MaybeCreatePoller() thread_manager.cc:137
    #6 0x1061f07cf in grpc::ThreadManager::Initialize() thread_manager.cc:110
    #7 0x1061c09c3 in grpc::Server::SyncRequestThreadManager::Start() server_cc.cc:335
    #8 0x1061b530b in grpc::Server::Start(grpc::ServerCompletionQueue**, unsigned long) server_cc.cc:497
    #9 0x1061806b9 in grpc::ServerBuilder::BuildAndStart() server_builder.cc:335
    #10 0x105f91312 in grpc::testing::interop::RunServer(std::__1::shared_ptr<grpc::ServerCredentials>) interop_server.cc:347
    #11 0x105e7c606 in main interop_server_bootstrap.cc:49
    #12 0x7fffa785f254 in start (libdyld.dylib+0x5254)
    #13 0x2  (<unknown module>)
```
