### ISSUE TITLE
multiple interop docker image build failures - problems with ports

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9583]
```
SUCCESS: All tests passed
/var/local/jenkins/grpc/tools/dockerfile/interoptest/grpc_interop_csharpcoreclr/build_interop.sh: line 47:   923 Alarm clock             tools/run_tests/run_tests.py -l csharp -c dbg --compiler coreclr --build_only
+ EXITCODE=142
+ docker rm -f build_grpc_interop_csharpcoreclr_6ffeddd5-0dd9-4b1b-bdd0-bbcd7916787d
build_grpc_interop_csharpcoreclr_6ffeddd5-0dd9-4b1b-bdd0-bbcd7916787d
+ exit 142

FAILED: build_docker_csharpcoreclr [ret=142, pid=4714]
```

log in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11129/console

pr: https://github.com/grpc/grpc/pull/9563

**Comment by apolcyn** [comment]
There actually seems to be some undetermined docker build failures across languages.

Seems like after any one failure in building a docker image, that https://github.com/grpc/grpc/blob/master/tools/run_tests/run_interop_tests.py#L867 ends up failing multiple times with something like: 
```
+ docker rm -f build_grpc_interop_python_3ea0d2cb-1472-41d0-a817-7cdb4e5f4eef
Error response from daemon: No such container: build_grpc_interop_...
```

noticed in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11297/console

in which node docker image fails, but i think this is related to getting the port for docker rather than node:
```
START: interop_server_node
Method handler for /grpc.testing.TestService/CacheableUnaryCall expected but not provided
Method handler for /grpc.testing.TestService/UnimplementedCall expected but not provided
Server attaching to port 8080

TIMEOUT: interop_server_node [pid=32396]
Removing docker image grpc_interop_node:6d9a4ecd-4cf0-44fe-b992-04543df905f5
Removing docker image grpc_interop_php7:38549c11-1b19-4f06-a465-d6ccced354e2
Removing docker image grpc_interop_java:cc7baeaf-fdcb-43f0-b647-6393d034b161
Removing docker image grpc_interop_python:7c802a00-fd9e-45ab-b504-c4da1b4e898b
Removing docker image grpc_interop_csharp:faba38d4-55f4-4b03-907d-8fee12195230
Removing docker image grpc_interop_cxx:5b8c225d-a9c4-4ccd-8c27-50d3cd607c62
Removing docker image grpc_interop_csharpcoreclr:b330a5eb-b58e-45ee-a36e-34268ddc3535
Removing docker image grpc_interop_http2:1c62883d-4ff5-4f3d-9e05-ed320a92e97b
Removing docker image grpc_interop_go:bd4f3cfe-e213-438c-9d97-bf79965925fd
Removing docker image grpc_interop_php:5d032c1c-24e6-4476-8ade-4ca98bbd55ba
Removing docker image grpc_interop_ruby:05a16559-1946-4cd2-9990-4ba3b72c0ecf
Traceback (most recent call last):
  File "tools/run_tests/run_interop_tests.py", line 880, in <module>
    server_addresses[lang] = ('localhost', job.mapped_port(_DEFAULT_SERVER_PORT))
  File "/home/jenkins/workspace/gRPC_interop_pull_requests@2/grpc/tools/run_tests/python_utils/dockerjob.py", line 114, in mapped_port
    return docker_mapped_port(self._container_name, port)
  File "/home/jenkins/workspace/gRPC_interop_pull_requests@2/grpc/tools/run_tests/python_utils/dockerjob.py", line 70, in docker_mapped_port
    (port, cid))
Exception: Failed to get exposed port 8080 for container interop_server_node_3f307567-85cb-4da7-b477-74c382cfc3e9.
stty: standard input: Inappropriate ioctl for device
+ true
```

**Comment by jtattermusch** [comment]
Have we tried to restart all the interop workers?

**Comment by jtattermusch** [comment]
AFAIK, they are not getting restarted periodically

**Comment by jtattermusch** [comment]
I'll try to restart them once there are no jobs running there.

**Comment by jtattermusch** [comment]
I restarted the interop workers a while ago and I haven't seen issues recently.

**Comment by mehrdada** [comment]
I saw this issue again https://sponge.corp.google.com/target?id=3508688f-9884-4854-b8e2-06f563ca39fa&target=grpc/ubuntu/pull_request/grpc_interop_tocloud&searchFor=&show=ALL&sortBy=STATUS

**Comment by adelez** [comment]
@mehrdada, I think your failure is caused by a different issue: #1572

**Comment by mehrdada** [comment]
@adelez thanks!
