### ISSUE TITLE
pubsub client: ObjectDisposedException when creating a new call

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9670]
Context: https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/733

The circumstances when this occur aren't clear yet. 

```
unhandled error pulling messages: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
   at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.PubSub.V1.Subscriber.SubscriberClient.PullAsync(PullRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__0(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
   at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.PubSub.V1.Subscriber.SubscriberClient.PullAsync(PullRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__0(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()<---
Having seen tons of those, we switched to the current 'New up a client every iteration' plan which led to this behavior, which I don't especially like because that means we create a new channel for every client that just gets torn down, which seems expensive and excessive.
```

**Comment by jtattermusch** [comment]
@baronfel, can you please provide some details about how to reproduce?

**Comment by jtattermusch** [comment]
Not sure if this is an actual gRPC issue, it just look that the underlying channel has been already disposed, so creating a new call on it throws ObjectDisposedException.

CC @jskeet

**Comment by baronfel** [comment]
So I'm not doing any explicit closing of channels at all, I'm just creating clients using the `<ClientType>.Create()` static members.  In my application, when I saw this behavior, I had created a single PublisherClient and a single SubscriberClient from the 1.0.0-beta006 and onwards versions of the Google.Cloud.PubSub.V1 nuget packages, which as I understand it creates a single GRPC channel for each of those clients.  These clients were then passed as parameters to functions that would run potentially concurrently sending and receiving messages.  The problem always seemed to be on the Subscriber Client after one successful message receipt.

**Comment by baronfel** [comment]
I'm still working on finding time to make a small application to demonstrate the issue, but I hope to do that sometime this weekend.

**Comment by jskeet** [comment]
Hmm... as @baronfel says, it will reuse the channel - it shouldn't be disposing anything. Thanks in advance for the repro - I'm sure we'll get to the bottom of it that way. There's probably not much use in spending time guessing until then, given that it's already a surprise.

**Comment by jtattermusch** [comment]
There's been no update on this for the last 4 months, so I'm going to close now. Please reopen if there's still issues.
