### ISSUE TITLE
Tests time out after they pass

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9726]
https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/2785/testReport/junit/(root)/aggregate_tests/run_tests_node_linux_dbg_default_electron1_3/

```
895127d774b13ac3201f3f55760 tools/dockerfile/test/node_jessie_x64
Sending build context to Docker daemon  5.12 kB

Step 1 : FROM debian:jessie
 ---> ddf73f48a05d
Step 2 : RUN apt-get update && apt-get install -y   autoconf   autotools-dev   build-essential   bzip2   ccache   curl   gcc   gcc-multilib   git   golang   gyp   lcov   libc6   libc6-dbg   libc6-dev   libgtest-dev   libtool   make   perl   strace   python-dev   python-setuptools   python-yaml   telnet   unzip   wget   zip && apt-get clean
 ---> Using cache
 ---> 63a08dbe847b
Step 3 : RUN apt-get update && apt-get install -y time && apt-get clean
 ---> Using cache
 ---> bbb6c821ad33
Step 4 : RUN apt-get update && apt-get install -y   libasound2   libgconf-2-4   libgtk2.0-0   libnss3   libxss1   libxtst6   xvfb
 ---> Using cache
 ---> a5194e5a8d8f
Step 5 : RUN apt-get update && apt-get install -y     python-all-dev     python3-all-dev     python-pip
 ---> Using cache
 ---> e54703ac6d9d
Step 6 : RUN pip install pip --upgrade
 ---> Using cache
 ---> 2b1f02ebfbe9
Step 7 : RUN pip install virtualenv
 ---> Using cache
 ---> a84fedb883e1
Step 8 : RUN pip install futures==2.2.0 enum34==1.0.4 protobuf==3.0.0a2 six==1.10.0
 ---> Using cache
 ---> f1ff02b0f5c1
Step 9 : RUN touch .profile
 ---> Using cache
 ---> 98a62a2911a7
Step 10 : RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
 ---> Using cache
 ---> f1270c731594
Step 11 : RUN /bin/bash -l -c "nvm install 0.12 && npm config set cache /tmp/npm-cache"
 ---> Using cache
 ---> 70b42febf017
Step 12 : RUN /bin/bash -l -c "nvm install 4 && npm config set cache /tmp/npm-cache"
 ---> Using cache
 ---> 5abba119ff42
Step 13 : RUN /bin/bash -l -c "nvm install 5 && npm config set cache /tmp/npm-cache"
 ---> Using cache
 ---> 314500cfaa33
Step 14 : RUN /bin/bash -l -c "nvm alias default 4"
 ---> Using cache
 ---> c4c3f8a01249
Step 15 : RUN ln -s /usr/bin/ccache /usr/local/bin/gcc
 ---> Using cache
 ---> 2a595c6dc47d
Step 16 : RUN ln -s /usr/bin/ccache /usr/local/bin/g++
 ---> Using cache
 ---> 356d68314be3
Step 17 : RUN ln -s /usr/bin/ccache /usr/local/bin/cc
 ---> Using cache
 ---> afef5b7b43be
Step 18 : RUN ln -s /usr/bin/ccache /usr/local/bin/c++
 ---> Using cache
 ---> 9c12af72ff23
Step 19 : RUN ln -s /usr/bin/ccache /usr/local/bin/clang
 ---> Using cache
 ---> 6ff3c77ac151
Step 20 : RUN ln -s /usr/bin/ccache /usr/local/bin/clang++
 ---> Using cache
 ---> df23d83b2d18
Step 21 : RUN mkdir /var/local/jenkins
 ---> Using cache
 ---> 98074ecf1354
Step 22 : CMD bash
 ---> Using cache
 ---> 780aadd5d615
Successfully built 780aadd5d615
++ uuidgen
+ CONTAINER_NAME=run_tests_3127b9f4-9448-45dd-92e8-e2c5fec3a256
+ docker_instance_git_root=/var/local/jenkins/grpc
+ DOCKER_EXIT_CODE=0
+ docker run -e 'RUN_TESTS_COMMAND=python tools/run_tests/run_tests.py -t -j 2 -x report_node_linux_dbg_default_electron1.3.xml --report_suite_name node_linux_dbg_default_electron1.3 -l node -c dbg --arch default --compiler electron1.3 --build_only' -e config= -e arch= -e CCACHE_DIR=/tmp/ccache -e XDG_CACHE_HOME=/tmp/xdg-cache-home -e 'THIS_IS_REALLY_NEEDED=see https://github.com/docker/docker/issues/14203 for why docker is awful' -e HOST_GIT_ROOT=/home/jenkins/workspace/gRPC_portability_pull_requests_linux -e LOCAL_GIT_ROOT=/var/local/jenkins/grpc -e BUILD_ID=2785 -i -v /home/jenkins/workspace/gRPC_portability_pull_requests_linux:/var/local/jenkins/grpc -v /tmp/ccache:/tmp/ccache -v /tmp/npm-cache:/tmp/npm-cache -v /tmp/xdg-cache-home:/tmp/xdg-cache-home -w /var/local/git/grpc --name=run_tests_3127b9f4-9448-45dd-92e8-e2c5fec3a256 node_jessie_x64_8f3f61b0cb311895127d774b13ac3201f3f55760 bash -l /var/local/jenkins/grpc/tools/run_tests/dockerize/docker_run_tests.sh
stdin: is not a tty
Cloning into '/var/local/git/grpc'...
done.
Note: checking out 'a264e028ad332710938860f95fe2f86d5b3b6c33'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Entering 'third_party/benchmark'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Cloning into 'third_party/benchmark'...
Submodule path 'third_party/benchmark': checked out '44c25c892a6229b20db7cd9dc05584ea865896de'
Entering 'third_party/boringssl'
Submodule 'third_party/boringssl' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl'
Cloning into 'third_party/boringssl'...
Submodule path 'third_party/boringssl': checked out '78684e5b222645828ca302e56b40b9daff2b2d27'
Entering 'third_party/boringssl-with-bazel'
Submodule 'third_party/boringssl-with-bazel' (https://boringssl.googlesource.com/boringssl) registered for path 'third_party/boringssl-with-bazel'
Cloning into 'third_party/boringssl-with-bazel'...
Submodule path 'third_party/boringssl-with-bazel': checked out '886e7d75368e3f4fab3f4d0d3584e4abfc557755'
Entering 'third_party/gflags'
Submodule 'third_party/gflags' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags'
Cloning into 'third_party/gflags'...
Submodule path 'third_party/gflags': checked out 'f8a0efe03aa69b3336d8e228b37d4ccb17324b88'
Entering 'third_party/googletest'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Cloning into 'third_party/googletest'...
Submodule path 'third_party/googletest': checked out 'c99458533a9b4c743ed51537e25989ea55944908'
Entering 'third_party/protobuf'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Cloning into 'third_party/protobuf'...
Submodule path 'third_party/protobuf': checked out 'a428e42072765993ff674fda72863c9f1aa2d268'
Entering 'third_party/thrift'
Submodule 'third_party/thrift' (https://github.com/apache/thrift.git) registered for path 'third_party/thrift'
Cloning into 'third_party/thrift'...
Submodule path 'third_party/thrift': checked out 'bcad91771b7f0bff28a1cac1981d7ef2b9bcef3c'
Entering 'third_party/zlib'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into 'third_party/zlib'...
Submodule path 'third_party/zlib': checked out '50893291621658f355bc5b4d450a8d06a563053d'
START: tools/run_tests/helper_scripts/pre_build_node_electron.sh
PASSED: tools/run_tests/helper_scripts/pre_build_node_electron.sh [time=26.4sec; retries=0:0]
START: tools/run_tests/helper_scripts/build_node_electron.sh
PASSED: tools/run_tests/helper_scripts/build_node_electron.sh [time=223.6sec; retries=0:0]
SUCCESS: All tests passed
/var/local/jenkins/grpc/tools/run_tests/dockerize/docker_run_tests.sh: line 57:  1164 Alarm clock             $RUN_TESTS_COMMAND
  adding: reports/ (stored 0%)
  adding: reports/index.html (deflated 22%)
  adding: report_node_linux_dbg_default_electron1.3.xml (deflated 46%)
+ DOCKER_EXIT_CODE=142
++ mktemp
+ TEMP_REPORTS_ZIP=/tmp/tmp.P4gyPDlvNM
+ docker cp run_tests_3127b9f4-9448-45dd-92e8-e2c5fec3a256:/var/local/git/grpc/reports.zip /tmp/tmp.P4gyPDlvNM
+ unzip -o /tmp/tmp.P4gyPDlvNM -d /home/jenkins/workspace/gRPC_portability_pull_requests_linux
Archive:  /tmp/tmp.P4gyPDlvNM
  inflating: /home/jenkins/workspace/gRPC_portability_pull_requests_linux/reports/index.html  
  inflating: /home/jenkins/workspace/gRPC_portability_pull_requests_linux/report_node_linux_dbg_default_electron1.3.xml  
+ rm -f /tmp/tmp.P4gyPDlvNM
+ docker rm -f run_tests_3127b9f4-9448-45dd-92e8-e2c5fec3a256
run_tests_3127b9f4-9448-45dd-92e8-e2c5fec3a256
+ exit 142
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1281, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tools/run_tests/dockerize/build_docker_and_run_tests.sh']' returned non-zero exit status 142
```

**Comment by muxi** [comment]
This still happens in master:
https://grpc-testing.appspot.com/job/gRPC_master_linux/2415/testReport/junit/(root)/aggregate_tests/run_tests_node_linux_dbg_native/
https://grpc-testing.appspot.com/job/gRPC_master_linux/2415/testReport/junit/(root)/aggregate_tests/run_tests_php7_linux_dbg_native/

**Comment by murgatroid99** [comment]
All of these failures aren't actually related to Electron. They all show an "alarm clock" error in `docker_run_tests.sh` after the tests pass.
