### ISSUE TITLE
C-core doesn't support incoming data frames with padding

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9779]
running new tests in https://github.com/grpc/grpc/pull/9776, it looks like the core-wrapping languages all fail fast with `unkown` when receiving padded data frames. 

The new test here is a server that implements interop `UnaryCall`, and existing interop clients call `LargeUnary` against it. It sends its response across a series of small, padded data frames.

If these clients call `LargeUnary` against the same server that's only not using padding, then call completes ok.

<s>To repro from that pr:

* `tools/run_tests/run_interop_tests.py -l c++ --use_docker --http2_edge_server_interop --insecure -j 1`

or manually:

install patched `hyper-h2` python package:
```
git clone --recursive https://github.com/python-hyper/hyper-h2.git hyper-h2
cd hyper-h2 && git fetch origin pull/468/head:pull_468 && git checkout pull_468
python setup.py sdist
cd dist && pip install h2-2.6.0dev0.tar.gz
```

run server with 
`python test/http2_test/http2_test_server.py`

run client with 
```
bins/opt/interop_client \
  --server_host=localhost \
  --server_port=8080 \
  --use_tls=false \
  --test_case=large_unary
```
</s>

**Comment by apolcyn** [comment]
To update, that test is checked in now. But for now core-wrapping languages don't run it.

To repro manually:

Run the server:
```
python http2_test_server.py 
WARNING    2017-03-27 16:41:40,630 http2_test_server:114 | serving on port 8080 : data_frame_padding
WARNING    2017-03-27 16:41:40,630 http2_test_server:114 | serving on port 8081 : goaway
WARNING    2017-03-27 16:41:40,630 http2_test_server:114 | serving on port 8082 : max_streams
WARNING    2017-03-27 16:41:40,630 http2_test_server:114 | serving on port 8083 : no_df_padding_sanity_test
WARNING    2017-03-27 16:41:40,630 http2_test_server:114 | serving on port 8084 : ping
WARNING    2017-03-27 16:41:40,630 http2_test_server:114 | serving on port 8085 : rst_after_data
WARNING    2017-03-27 16:41:40,631 http2_test_server:114 | serving on port 8086 : rst_after_header
WARNING    2017-03-27 16:41:40,631 http2_test_server:114 | serving on port 8087 : rst_during_data
```

Run the client against server that sends padded data:
```
> bins/opt/interop_client --test_case=large_unary --server_host=localhost --server_port=8080 --test_case=large_unary
I0327 16:37:15.394024983  133621 client.cc:105]              Testing these cases: large_unary
E0327 16:37:15.432329024  133621 interop_client.cc:158]      Error status code: 2 (expected: 0), message: Stream removed
Aborted (core dumped)
```

Note that running against the otherwise same server that only doesn't use padding passes:
```
> bins/opt/interop_client --test_case=large_unary --server_host=localhost --server_port=8083 --test_case=large_unary
I0327 16:37:39.848193777  133667 client.cc:105]              Testing these cases: large_unary
```

**Comment by jadekler** [comment]
Was this happening on ARM (e.g. raspberry pi) / windows?

**Comment by apolcyn** [comment]
@jadekler I originally filed the issue after observing the behavior using the tested linux builds. I'd assume that the same thing occurs on other platforms but I hadn't tried.

**Comment by jadekler** [comment]
Thanks @apolcyn

**Comment by srini100** [comment]
Bumping priority to P1. This is seen in multiple langs. See https://github.com/grpc/grpc/issues/15623

**Comment by ncteisen** [comment]
This reproduction does not work for me (on MacOS or Linux).

I see this error from the server:
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1066, in doRead
    protocol = self.factory.buildProtocol(self._buildAddr(addr))
  File "test/http2_test/http2_test_server.py", line 67, in buildProtocol
    return t(use_padding=False).get_base_server()
  File "/usr/local/google/home/ncteisen/Desktop/grpc/test/http2_test/test_data_frame_padding.py", line 31, in __init__
    self._base_server = http2_base_server.H2ProtocolBaseServer()
  File "/usr/local/google/home/ncteisen/Desktop/grpc/test/http2_test/http2_base_server.py", line 31, in __init__
    self._conn = h2.connection.H2Connection(client_side=False)
exceptions.TypeError: __init__() got an unexpected keyword argument 'client_side'
```

**Comment by ericgribkoff** [comment]
@ncteisen The [http2 test script](https://github.com/grpc/grpc/blob/a2769d5ee4116152eead50678741906b1667923b/tools/dockerfile/interoptest/grpc_interop_http2/Dockerfile) needs h2 version 2.6.1 (the client_side argument is gone in the latest h2 version)

**Comment by ncteisen** [comment]
```
[hi on] DESK ~/Desktop/grpc [master] (0) $ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import h2
>>> h2.__version__
'3.0.1'
```

I am on 3.0.1 and I still see this error..

**Comment by ncteisen** [comment]
Oh, I see, it needs the older version.. Got it

**Comment by ncteisen** [comment]
Man I with I uses venv

**Comment by ncteisen** [comment]
Now I see this error:

```
Unhandled Error
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Library/Python/2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/Library/Python/2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/ncteisen/Desktop/grpc/test/http2_test/http2_base_server.py", line 78, in dataReceived
    self._handlers['DataReceived'](event)
  File "/Users/ncteisen/Desktop/grpc/test/http2_test/test_data_frame_padding.py", line 66, in on_data_received
    self._base_server.setup_send(response_data , event.stream_id, pad_length=self._pad_length, read_chunk_size=self._read_chunk_size)
  File "/Users/ncteisen/Desktop/grpc/test/http2_test/http2_base_server.py", line 124, in setup_send
    self.default_send(stream_id, pad_length=pad_length, read_chunk_size=read_chunk_size)
  File "/Users/ncteisen/Desktop/grpc/test/http2_test/http2_base_server.py", line 149, in default_send
    self._conn.send_data(stream_id, data, end_stream=False, pad_length=pad_length)
exceptions.TypeError: send_data() got an unexpected keyword argument 'pad_length'

INFO       2018-06-25 12:09:47,974 http2_base_server:61 | Disconnected [Failure instance: Traceback (failure with no frames): <type 'exceptions.TypeError'>: send_data() got an unexpected keyword argument 'pad_length'
```

**Comment by sreecha** [comment]
@apolcyn @ncteisen : Is this issue still relevant ? - if not, can we just close it?

**Comment by a11r** [comment]
Alex - can you please try reproducing and assign to me if this needs attention.

If not reproducible/relevant any more please close.

**Comment by apolcyn** [comment]
Sorry, this issue should really be titled: "C-core doesn't support incoming data frames with padding"

I don't think support has since been added, but will check

**Comment by apolcyn** [comment]
This is still reproduceable, and would technically be a gap in C-core's following of the h2 spec. 
But at the same time:
1) I'm not aware of any users that have actually ran into this in the wild (I'm not sure if/what h2 implementations send padding, grpc doesn't)
2) C-core fails fast. E.g. contrarily, Go accepted padding but didn't account for it in flow control to grant back to the sender

Lowered to p2 and keeping open, if anyone hits it; though it likely could be closed
