### ISSUE TITLE
tests.cloud_to_cloud:php:java_server:custom_metadata interop failure

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9797]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11528/testReport/(root)/tests/cloud_to_cloud_php_java_server_custom_metadata/

Also for php7: 
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11528/testReport/(root)/tests/cloud_to_cloud_php7_java_server_custom_metadata/

**Comment by ejona86** [comment]
The error message makes it sound like PHP is using the C API incorrectly.

**Comment by jtattermusch** [comment]
Saw similar error for:
tests.cloud_to_cloud:php:java_server:large_unary
tests.cloud_to_cloud:php7:java_server:custom_metadata

**Comment by stanley-cheung** [comment]
Quick update: 
 - This is news to me. Last time I touched PHP code the interop test passed #9751 
 - As of `master` now, only `php:java_server:custom_metadata` and maybe one other test failed. Some other tests between php client and java server were successful. All other interop tests passed for servers in other languages.
 - If I go back to a commit like `7e54f14` on `master` (about 14 days ago), all tests between php client and java server also passed. So something happened during the last 14 days.

**Comment by stanley-cheung** [comment]
Now I am confused. The tests appear to have passed:

https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11757/consoleFull

```
PASSED: cloud_to_cloud:php:java_server:custom_metadata [time=10.3sec; retries=0:0]
```

**Comment by stanley-cheung** [comment]
I just ran the interop tests between PHP client and Java server off cli off the latest master and they all passed:

```
stanleycheung@gummybear:~/grpc$ ./tools/run_tests/run_interop_tests.py -l php -s java --use_docker -t -j 8
START: Building interop docker images.
PASSED: build_docker_java [time=32.3sec; retries=0:0]
PASSED: build_docker_php [time=197.3sec; retries=0:0]
SUCCESS: All docker images built successfully.
START: interop_server_java
PASSED: cloud_to_cloud:php:java_server:large_unary [time=3.0sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:ping_pong [time=3.9sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:client_streaming [time=4.2sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:server_streaming [time=5.1sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:empty_unary [time=5.6sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:cancel_after_first_response [time=5.9sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:empty_stream [time=6.2sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:status_code_and_message [time=3.4sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:cancel_after_begin [time=8.1sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:timeout_on_sleeping_server [time=5.3sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:custom_metadata [time=4.6sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:unimplemented_method [time=3.6sec; retries=0:0]
PASSED: cloud_to_cloud:php:java_server:unimplemented_service [time=3.2sec; retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_php:73a26374-950a-4d8c-ac33-cb381a80f70d
Removing docker image grpc_interop_java:f32aac5f-a7ee-48d1-9596-df19e72d4e83
```

**Comment by dgquintas** [comment]
Just saw it in one of my (100% unrelated) PRs:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11755/testReport/junit/(root)/tests/cloud_to_cloud_php7_java_server_large_unary/

**Comment by dgquintas** [comment]
And again
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11620/testReport/junit/(root)/tests/cloud_to_cloud_php_java_server_custom_metadata/

**Comment by stanley-cheung** [comment]
I guess this could be a flaky test. Like this latest run from #9838 there's no PHP failures: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11768/#showFailuresLink

**Comment by stanley-cheung** [comment]
I still couldn't reproduce this.

If I run it with docker, I can't run it too many times because each run takes a few minutes. I cannot reproduce that way. See above.

I also try to run a local java interop server and then keep running the PHP client indefinitely and I couldn't see even one error

`gcloud compute ssh stanleycheung-debian8`

```
root@stanleycheung-debian8:~/grpc-java# ./run-test-server.sh 
Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.

Using fake CA for TLS certificate. Test clients should expect host
*.test.google.fr and our test CA. For the Java test client binary, use:
--server_host_override=foo.test.google.fr --use_test_ca=true

Mar 01, 2017 2:06:45 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: e5:d7:56:a7:51:15:db:6c
Server started on port 8080
```

```
# this script just runs the PHP interop client over and over again until exit status = 1
/home/stanleycheung$ ./test.sh
```

**Comment by stanley-cheung** [comment]
The PHP tests continue to be flaky on jenkins on the most recent runs:

This passed: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11776/

This failed: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/11774/#showFailuresLink

**Comment by stanley-cheung** [comment]
@jtattermusch Any idea on how to better reproduce the error?

**Comment by stanley-cheung** [comment]
Ok I finally reproduced it. It's actually my bad. The good run was caused by the fact that I built my PHP extension accidentally using the 1.1.0 released code.

I re-built the PHP extension using the `master` C core and I can reproduce the error about 1 in 6 times.

I observed the same symptoms as #9762. A whole bunch (gotta be thousands lines) of this got spitted out

```
E0301 04:16:58.000276657   21592 parser.c:287]   HTTP client max line length (4096) exceeded
```

And this is seen on the Java server side

```
Mar 01, 2017 4:17:03 AM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:487)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:468)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:103)
        at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:345)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1224)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:1172)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:549)
        at io.netty.handler.codec.http2.DefaultHttp2Connection.close(DefaultHttp2Connection.java:151)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:187)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:380)
        at io.grpc.netty.NettyServerHandler.channelInactive(NettyServerHandler.java:300)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:861)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by stanley-cheung** [comment]
This is seen just before the `HTTP client max line length (4096) exceeded` lines start

```
0301 04:32:45.011151032   22164 combiner.c:217]             C:0x29efce0 grpc_combiner_execute c=0x2bdb200 cov=0 last=1
D0301 04:32:45.011160184   22164 combiner.c:287]             C:0x29efce0 grpc_combiner_continue_exec_ctx workqueue=0x29edc30 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=0
D0301 04:32:45.011165177   22164 combiner.c:306]             C:0x29efce0 maybe_finish_one n=0x2bdb200
D0301 04:32:45.011178481   22164 parsing.c:397]              FLOW    parse: client DEBIT                                   STREAM[1]:incoming_window_delta   -49152 by                                              incoming_frame_size    16150 giving -65302
D0301 04:32:45.011196017   22164 chttp2_transport.c:729]     W:0x2bdb0e0 CLIENT state IDLE -> WRITING [window-update-required]
D0301 04:32:45.011207790   22164 combiner.c:399]             C:0x29efce0 grpc_combiner_execute_finally c=0x2bdb188; ac=0x29efce0; cov=0
D0301 04:32:45.011223853   22164 parsing.c:413]              FLOW    parse: client DEBIT                                         TRANSPORT:incoming_window 2147434495 by                                              incoming_frame_size    16150 giving 2147418345
D0301 04:32:45.011235881   22164 parsing.c:397]              FLOW    parse: client DEBIT                                   STREAM[1]:incoming_window_delta   -65302 by                                              incoming_frame_size     1468 giving -66770
D0301 04:32:45.011243083   22164 chttp2_transport.c:729]     W:0x2bdb0e0 CLIENT state WRITING -> WRITING+MORE [window-update-required]
D0301 04:32:45.011252760   22164 parsing.c:413]              FLOW    parse: client DEBIT                                         TRANSPORT:incoming_window 2147418345 by                                              incoming_frame_size     1468 giving 2147416877
```

And these are seen right after those thousands of lines

```
D0301 04:33:03.888165133   22164 combiner.c:351]             C:0x29efce0 finish old_state=5
D0301 04:33:03.888209483   22164 combiner.c:287]             C:0x29efce0 grpc_combiner_continue_exec_ctx workqueue=0x29edc30 is_covered_by_poller=(final=0 elems=0)->0 exec_ctx_ready_to_finish=1 time_to_execute_final_list=1
D0301 04:33:03.888219506   22164 combiner.c:335]             C:0x29efce0 execute_final[0] c=0x2bdb188
D0301 04:33:03.888227759   22164 writing.c:210]              W:0x2bdb0e0 CLIENT[1] im-(sent,send)=(1,0) announce=0
D0301 04:33:03.888236815   22164 chttp2_transport.c:729]     W:0x2bdb0e0 CLIENT state WRITING+MORE -> IDLE [begin writing nothing]
D0301 04:33:03.888245382   22164 chttp2_transport.c:2154]    set connectivity_state=4
D0301 04:33:03.888276713   22164 connectivity_state.c:184]   SET: 0x2bdb328 client_transport: READY --> SHUTDOWN [close_transport] error=0x2bcb7e0 {"created":"@1488342783.888160732","description":"Delayed close due to in-progress write","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":517,"grpc_status":14,"referenced_errors":[{"created":"@1488342783.888159142","description":"Failed parsing HTTP/2","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1971,"referenced_errors":[{"created":"@1488342765.011263572","description":"frame of size 16384 overflows incoming window of 0","file":"src/core/ext/transport/chttp2/transport/parsing.c","file_line":391}]}]}
D0301 04:33:03.888320985   22164 connectivity_state.c:211]   NOTIFY: 0x2bdb328 client_transport: 0x7fafe4001f30
D0301 04:33:03.888326719   22164 combiner.c:217]             C:0x29ec950 grpc_combiner_execute c=0x7fafe4001f30 cov=0 last=1
D0301 04:33:03.888332746   22164 connectivity_state.c:211]   NOTIFY: 0x2bdb328 client_transport: 0x2bcd540
```

**Comment by stanley-cheung** [comment]
To reproduce and see the trace:

```
gcloud compute ssh stanleycheung-debian8
/home/stanleycheung/grpc/src/php/bin/interop_client.sh --server_host localhost --server_port 8080 --test_case custom_metadata --use_tls=true --use_test_ca=true
```

The Java interop server is already running

**Comment by yang-g** [comment]
Thanks Stanley for debugging!

From the above info, what I am guessing is:
1. Somehow Java sees an error, it sends back the stacktrace or something
(which is largish).
2. The core transport will try to parse the response as HTTP to see whether
it received an HTTP response (designed for 404/502 etc)
3. The HTTP (1.0) parser, thinking it is parsing headers, and the parser
sees a line longer than 4096 which it cannot parse.
4. It prints an error for every byte after 4096 bytes... It should return
an error but currently it wrongly returns ERROR_NONE.

What I am not sure and/or we need to do:
a. understand the error on java side in 1.
b. fix 4. to return an error.
c. understand whether we need to handle large HTTP response (is the java
response an HTTP response?)
d. double check whether the following logs still exist and whether it makes
sense: D0301 04:33:03.888276713 22164 connectivity_state.c:184] SET:
0x2bdb328 client_transport: READY --> SHUTDOWN [close_transport]
error=0x2bcb7e0 {"created":"@1488342783.888160732","description":"Delayed
close due to in-progress write","file":"src/core/ext/
transport/chttp2/transport/chttp2_transport.c","file_
line":517,"grpc_status":14,"referenced_errors":[{"created"
:"@1488342783.888159142","description":"Failed parsing
HTTP/2","file":"src/core/ext/transport/chttp2/transport/
chttp2_transport.c","file_line":1971,"referenced_errors"
:[{"created":"@1488342765.011263572","description":"frame of size 16384
overflows incoming window of 0","file":"src/core/ext/
transport/chttp2/transport/parsing.c","file_line":391}]}]}

**Comment by yang-g** [comment]
Filed https://github.com/grpc/grpc/issues/9925 to track item b.

**Comment by jtattermusch** [comment]
@stanley-cheung  FYI I have identified a similar problem for C#: see #9762

**Comment by apolcyn** [comment]
seen again https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11728/testReport/junit/(root)/tests/cloud_to_cloud_php7_java_server_custom_metadata/

pr https://github.com/grpc/grpc/pull/9894

**Comment by yang-g** [comment]
@ejona86 Could you take a look at the java trace above to see whether it means anything to you?

**Comment by dgquintas** [comment]
Can this issue be closed?

**Comment by ejona86** [comment]
The "Stream closed before write could take place" is just the java implementation being surprised that the connection was closed. The problem is the connection was closed, not the error.

The "frame of size 16384 overflows incoming window of 0" looks like grpc-java#2801 which has been fixed, but it has also been worked around in C core in #10073.

So I think this can be closed.
