### ISSUE TITLE
python_linux_dbg.py34.test.unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest (from grpc.python_linux_dbg)

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#9844]
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2726/testReport/junit/(root)/python_linux_dbg/py34_test_unit_beta__face_interface_test_MultiCallableInvokerBlockingInvocationInlineServiceTest/

```
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testSuccessfulUnaryRequestUnaryResponse
[0mRunning       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testWaitingForSomeButNotAllParallelInvocations
[92mSUCCESS       unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testWaitingForSomeButNotAllParallelInvocations
[0m15 tests finished:
	14 successful
	1 unsuccessful
	4 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91munit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest.testFailedStreamRequestUnaryResponse[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 266, in _blocking_stream_unary
    credentials=_credentials(protocol_options))
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 631, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, OS Error)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/framework/interfaces/face/_blocking_invocation_inline_service.py", line 291, in testFailedStreamRequestUnaryResponse
    iter(requests), test_constants.LONG_TIMEOUT)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 389, in __call__
    self._response_deserializer)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 268, in _blocking_stream_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="OS Error")

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure
```

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: any known frequency to this, or is the one link above the one (recorded) observation of it? Any idea what could have gone wrong on the local machine to result in the details string `OS Error`?

**Comment by dgquintas** [comment]
Not seen for a while, closing.
