### ISSUE TITLE
tests.cloud_to_cloud:java:ruby_server:custom_metadata flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9865]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11676/testReport/junit/(root)/tests/cloud_to_cloud_java_ruby_server_custom_metadata/

```
Feb 24, 2017 2:36:06 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: f2:07:88:cf:f8:e7:a3:3e
Exception in thread "main" java.lang.AssertionError: io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.testing.integration.AbstractInteropTest.assertSuccess(AbstractInteropTest.java:1244)
	at io.grpc.testing.integration.AbstractInteropTest.customMetadata(AbstractInteropTest.java:991)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:264)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:197)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:81)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at io.grpc.stub.MetadataUtils$2$1$1.onClose(MetadataUtils.java:140)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:74)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:425)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:540)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Shutting down
```

**Comment by jtattermusch** [comment]
Some issue happening with node: https://github.com/grpc/grpc/issues/9878
