### ISSUE TITLE
cloud_to_cloud:java:csharp_server:large_unary interop failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#9937]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11791/testReport/junit/(root)/tests/cloud_to_cloud_java_csharp_server_large_unary/

```
Running test large_unary
Mar 01, 2017 5:40:42 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: e7:2c:69:3f:31:2a:73:70
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
	at io.grpc.testing.integration.AbstractInteropTest.largeUnary(AbstractInteropTest.java:225)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:213)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:197)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:81)
Shutting down
```

**Comment by apolcyn** [comment]
seen again https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11728/#showFailuresLink

pr https://github.com/grpc/grpc/pull/9894
