### ISSUE TITLE
Node - uncaught exception if wrong type passed in a client call

### ISSUE THREAD

**Issue by dcolens** [grpc/grpc#9973]
# test
(added to https://github.com/grpc/grpc/blob/master/src/node/test/surface_test.js#L446)
```javascript
  it('bad input type', function(done) {
    client.unary({error: 'false'}, metadata, function(err, data) {
      assert(err);
      done();
    });
  });
```

Should return an error in the callback because 'false' is not boolean, but instead, it triggers an uncaught exception:
```
     Error: Illegal value for errorvalue element of type bool: string (not a boolean)
      at Error (native)
      at fail (node_modules/protobufjs/dist/protobuf.js:1817:23)
      at ProtoBuf.Reflect.ElementPrototype.verifyValue (node_modules/protobufjs/dist/protobuf.js:1866:25)
      at ProtoBuf.Reflect.FieldPrototype.verifyValue (node_modules/protobufjs/dist/protobuf.js:3499:33)
      at MessagePrototype.set (node_modules/protobufjs/dist/protobuf.js:2493:59)
      at MessagePrototype.set (node_modules/protobufjs/dist/protobuf.js:2483:38)
      at Message (node_modules/protobufjs/dist/protobuf.js:2411:34)
      at serialize (src/node/src/common.js:87:23)
      at Client.makeUnaryRequest [as unary] (src/node/src/client.js:395:19)
      at Context.<anonymous> (src/node/test/surface_test.js:447:12)
```
This makes it hard for the client code to catch the error.

**Comment by murgatroid99** [comment]
Passing an incorrectly typed value as an argument is an invalid use of the API. If you need to pass user input in, validate it or coerce it to the correct type.

**Comment by dcolens** [comment]
One could expect the error is returned in the callback, otherwise what's the point of having the error argument in the callback at all if it cannot be trusted to returns errors ?

**Comment by murgatroid99** [comment]
There's a difference between a dynamic failure of an RPC and a misuse of the API. An error caused by passing an incorrectly typed parameter should be corrected by the programmer, by changing the code, so it shouldn't matter where the error comes out. The difference is that if we throw the error instead of passing it to the callback, it's harder to accidentally ignore it.
